### ISSUE TITLE
RSS Enhancements

### ISSUE THREAD

**Issue by uytko** [wallabag/wallabag#1000]
A few suggestions:
- As stated in issue #553, I'd like a limitation (A number of articles or a date range).
- The pubDate of the item could be the date the article was added by user to Wallabag. I don't know if it's stored.

**Comment by nicosomb** [comment]
Hello @uytko ! 

Thanks to @vpmalley, first suggestion is already done, see #1003.

**Comment by tcitworld** [comment]
> The pubDate of the item could be the date the article was added by user to Wallabag. I don't know if it's stored.

Not stored, going to v2.

**Comment by uytko** [comment]
(Very late) Thanks to both of you. I am able to find a workaround to my problem with the limitation.

**Comment by nicosomb** [comment]
> The pubDate of the item could be the date the article was added by user to Wallabag. I don't know if it's stored.

Done by @j0k3r in v2.
