### ISSUE TITLE
Wrong  url in the iOS application

### ISSUE THREAD

**Issue by fl0rent** [wallabag/wallabag#1001]
When you use the ios application, there is a problem with the URL. There are wrong. Should be changed to avoid falling on error pages.

Wrong URL are = 
wallaby FAQ: https://www.wallabag.org/frequently-asked-questions/
Install your own wallabag: http://doc.wallabag.org/doku.php?id=users:begin:install

![img_1976](https://cloud.githubusercontent.com/assets/1076038/5756261/b1d6efb6-9cad-11e4-9d47-6c01dd6acedd.PNG)

**Comment by tcitworld** [comment]
If follows [here](https://github.com/wallabag/ios-app/issues/24).
