### ISSUE TITLE
social api

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#1002]
Mozilla à sorti Social API (https://developer.mozilla.org/fr/docs/Social_API). Pourquoi pas faire un plugin pour wallabag ?

**Comment by tcitworld** [comment]
Normalement il y a déjà un ticket sur le sujet, cherche ce que j'avais dit à l'époque, même si je pense que ça a évolué.

**Comment by nicosomb** [comment]
Duplicate of #625
