### ISSUE TITLE
The "back to top" button is missing in responsive design (Baggy theme)

### ISSUE THREAD

**Issue by ParoTheParrot** [wallabag/wallabag#1010]

**Comment by tcitworld** [comment]
I wonder if we should add an option to display it or not. It's rather a big button on small screen, and it covers text.

**Comment by tcitworld** [comment]
OK. There's also an issue to put the toolbar at the bottom, (somewhere).

**Comment by tcitworld** [comment]
There's now a toolbar at the bottom.
