### ISSUE TITLE
PDF export fails if pictures are not accessible

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1011]
> TCPDF ERROR: [Image] Unable to get the size of the image: http://www.framablog.org/public/_img/framablog/wallaby_baby.jpg

If pictures are not accessible, like if the website is down, the export fails miserably.

**Comment by tcitworld** [comment]
OK, I didn't managed to produce pdf anyway, but at least there's exceptions to handle errors.

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
