### ISSUE TITLE
Wallabag goes to 100% CPU and does not respond when adding Google Drive spreadsheet

### ISSUE THREAD

**Issue by rixx** [wallabag/wallabag#1027]
General Information:
* Version 1.8.1
* Hosting with nginx on a dedicated server running Arch Linux
* PHP version 5.6.5
* storage via MySQL

I wanted to add a generic Google Drive spreadsheet via the bookmarklet (up to date Firefox), but there was no reaction and eventually a 504 error (during that time I couldn't reach wallabag via other means neather). During the no reaction time wallabag used 100% of the server CPU. Things went back to normal after either waiting for the timeout of after killing the php process.

**Comment by tcitworld** [comment]
Wow. Never seen that.

Did not manage to reproduce it with one of my own Sheets, though. I agree it takes some time, but I did get some content.

When trying to add a new blanck spreadsheet, I get an entry with no content.

You should have had a timeout anyway.

If it's not confidential, can you link us to a spreadsheet we can test and confirm the issue ?

**Comment by nicosomb** [comment]
ping @rixx

**Comment by rixx** [comment]
Hm. Couldn't reproduce it this time around, I'll go ahead and mark it as closed since there have been no other sightings.
