### ISSUE TITLE
Sort on latest read

### ISSUE THREAD

**Issue by 876974** [wallabag/wallabag#1032]
The sort function in the archive materials according to the latest timestamp of the last read it.

**Comment by tcitworld** [comment]
I didn't have the idea to save date of last read. Will do.

**Comment by j0k3r** [comment]
@876974 I didn't quite fully understand what do you need. Care to elaborate ?

**Comment by tcitworld** [comment]
I think he means the last time you opened an article inside wallabag itself.

**Comment by 876974** [comment]
I need to list (archive) read materials Default Sort no time in which the material was added, and the first display materials that have been marked as read the latest. Similar to how it is implemented in Pocket

**Comment by j0k3r** [comment]
I guess I have to open a Pocket account to fully understand what you mean :-)

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/issues/2178
