### ISSUE TITLE
Preserving comments while saving webpages

### ISSUE THREAD

**Issue by devaj68** [wallabag/wallabag#1033]
Hi all,
I would like to preserve comments while saving webpages. I tried removing "comment" and "disqus" mentioned in the $regexps of Readability.php but the webpages saved still didn't displayed any comments available on that article online.
I would greatly appreciate if anyone could tell me how can this be achieved.
Here's the url that I am trying to save with comments (there are quite a few gems in the comment section of many articles relating to programming or system administration.)

http://php.net/manual/en/class.domdocument.php

P.S: Do excuse my english. It's not my first language.

**Comment by tcitworld** [comment]
I think you also need to edit [this](https://github.com/wallabag/wallabag/blob/master/inc/3rdparty/site_config/standard/php.net.txt) file, since wallabag first relies on site_config files before using Readability to detect content.
Some help on how to edit the file here : http://help.fivefilters.org/customer/portal/articles/223153-site-patterns

**Comment by devaj68** [comment]
After editing the php.net.txt site config located at /var/www/wallabag/inc/3rdparty/site_config/standard like below:

```siteconfig
body: //div[@id='content']
comment: //section[@id='usernotes']
strip_id_or_class: manualnavbar

prune: no

test_url: http://www.php.net/manual/en/migration5.incompatible.php
```
causes wallabag to discard the content (body) all together and just prints one of the comments. The below result is via using the Readability.php experimental feature i.e via http://127.0.0.1/wallabag/inc/3rdparty/libraries/readability/Readability.php?url=http://www.php.net/manual/en/migration5.incompatible.php

![image](https://cloud.githubusercontent.com/assets/4107215/5983786/6a522e1c-a8f6-11e4-8e50-702afc794506.png)

While if I try to save the link via wallabag's inbuilt save link tab, it saves nothing, not even the url.

![image](https://cloud.githubusercontent.com/assets/4107215/5983893/2ed95a8a-a8f7-11e4-8313-4d3154e3a513.png)

I got the comment section's  xpath from the fivefilters.org online tool

![image](https://cloud.githubusercontent.com/assets/4107215/5983935/a64039ea-a8f7-11e4-987a-7328ec111ad5.png)

Hope this helps

**Comment by tcitworld** [comment]
What if you add to the existing body section the `usernotes` as `body: //div[@class='usernotes']` ? I think it should be added to the main content and therefore being shown.
Wallabag doesn't currently consider comments, even detected by FullTextRSS from Fivefilters.

Will run some tests soon if I can get some time.

**Comment by devaj68** [comment]
```siteconfig
body: //div[@id='content']
body: //section[@id='usernotes']
strip_id_or_class: manualnavbar

prune: no

test_url: http://www.php.net/manual/en/migration5.incompatible.php
```
Still the same result as before.
Tried using the below configuration 
```siteconfig
body: //section[@id='usernotes']
strip_id_or_class: manualnavbar

prune: no

test_url: http://www.php.net/manual/en/migration5.incompatible.php
```
No change in the result

Btw thank you for your prompt replies.
P.S: For your reference, I am using the url specified in the php.net.txt site config ( i.e http://www.php.net/manual/en/migration5.incompatible.php )

**Comment by tcitworld** [comment]
When saying « Same result as before », do you mean in both cases (calling the Readability class directly and adding a link from wallabag itself) ?

**Comment by devaj68** [comment]
Yes in both the cases the result is the same as before ( reference : screenshots posted above )
