### ISSUE TITLE
Add note to articles

### ISSUE THREAD

**Issue by yforster** [wallabag/wallabag#1038]
Hi,

I have a feature I really miss in wallabag: I want to annotate the article with something longer than just tag. This may be a short note where I cot the article from, why I want to remember it or what I think about it.

So, the possibility to add a note to saved links would be great.

**Comment by tcitworld** [comment]
I thought we already have an issue for that, but I didn't find it.
Anyway, I've already started to work on that.

**Comment by nicosomb** [comment]
v1 or v2?

**Comment by tcitworld** [comment]
I started work on v1, but it v2 comes sooner I won't have to keep going. ;)

**Comment by nicosomb** [comment]
we have to talk about v1 / v2 and new features to know what we have to do.

**Comment by tcitworld** [comment]
And I definitely have to learn Symfony during the next holidays.

**Comment by nicosomb** [comment]
:+1:

**Comment by j0k3r** [comment]
You are right. Once the v2 is on the way, I think we found _freeze_ new feature on the v1.

**Comment by tcitworld** [comment]
Some of the work on v1 on features will benefit to wallabag v2, but I agree to freeze most features for now.
I have in mind to release 1.8.2, 1.9 then 2.0 will come with what you're doing.

**Comment by tcitworld** [comment]
1.9 should be a stable version before 2.0.

**Comment by j0k3r** [comment]
Duplicate https://github.com/wallabag/wallabag/issues/592
