### ISSUE TITLE
404 Links on Install Page

### ISSUE THREAD

**Issue by edent** [wallabag/wallabag#1039]
When installing Wallabag, the links to the "FAQ" and "Help" are broken.

https://www.wallabag.org/help/

https://www.wallabag.org/frequently-asked-questions/

From https://github.com/wallabag/wallabag/blob/153237671001225dea40957e33e67fe16e6124fc/install/index.php

Not a great first impression for new users.

**Comment by tcitworld** [comment]
@nicosomb Can you make redirections (.htaccess should be enough) while the new version is released ?

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
