### ISSUE TITLE
New Install - Can't Log In

### ISSUE THREAD

**Issue by edent** [wallabag/wallabag#1040]
Trying to log in via the web just redirects me back to the login page.  No error is displayed.  If I enter a deliberately incorrect username/password, the same thing happens - taken back to the login page with no error.

This is a new install. Compatibility check said everything was fine.  Looking in phpmyadmin, the database has been set up and my user was created.

Tried on Chrome and Firefox.

My site is using HTTPS via CloudFlare - do I need to configure anything specifically for that?

**Comment by tcitworld** [comment]
It *could* be something to do with CloudFlare, but I would start looking in the php logs to see if something's wrong. Also, activating debug mode (edit the inc/poche/config.inc.php file) might bring some additionnal informations.


Finally, errors message are not quite visible on login page (look at [demo.wallabag.org](http://demo.wallabag.org/) and change credentials), so you may miss them if your screen is not bright. We **totally** need to change that.

**Comment by edent** [comment]
There is no error message in the top right of my installation.

Adding Debug mode just gives me "debug mode is on so cache is off. your wallabag version:1.8.1. storage: mysql"

Where can I find Wallabag's logs?

Thanks for your help.

**Comment by tcitworld** [comment]
wallabag logs are outputed in cache/log.txt **and** in your php logs, where you should find more information. 

I will enable CloudFlare on my own domain tomorrow and test how it's going.

**Comment by edent** [comment]
Interesting... The log says

    2015/02/01_22:20:42 - 141.101.98.137 - storage type mysql
    2015/02/01_22:21:01 - 141.101.98.137 - login successful
    2015/02/01_22:21:01 - 141.101.98.137 - redirect to https://shkspr.mobi/wallabag/

So, it *thinks* I've logged in?  If I put in an incorrect username, I get `login failed`.

**Comment by tcitworld** [comment]
I'm highly suspecting CloudFlare at the moment. Will check that tomorrow.

Can you access your server over regular http or do you enforce https ? I will test if it works without https too.

**Comment by edent** [comment]
It's enforced at the moment.  Will see if I can break through ;-)

Have a great evening - and thanks for your prompt help.

**Comment by edent** [comment]
Just switched off HTTPS - still doesn't work.

**Comment by tcitworld** [comment]
Okay. I will test that. I'm suspecting a problem with the http headers sent by CloudFlare.

Could you tell me what are your Cloudflare settings for your website (Security Profile, Performance Profile, anything else that is not default) ? So that I compare with my own when I will set it up.

And if you're curious with some time, you can even try setting wallabag on a subdomain, de-activate CloudFlare on this subdomain and test how it goes. :D

**Comment by edent** [comment]
Medium security
CDN  + Full optimization
SPDY
Full SSL
Always use SSL

**Comment by edent** [comment]
Just tried it on a server *without* CloudFlare. Same issue.  Log shows success - web still shows login page.

Compatibility check is fine - is there anything else I can try?

**Comment by tcitworld** [comment]
Sorry, I said I was going to do try some things today, didn't have the time. If it's not Cloudflare which is guilty, then I don't know.
Maybe a phpinfo() would come handy. Also, have you enabled and looked to php logs during installation and login. If there's absolutely no error, then I've got no answer... for the moment.

Before all that, you could check in config.inc.php if all values are correctly filled : 
```
STORAGE', 'mysql'
STORAGE SERVER, DB, USER, PASSWORD

**Comment by tcitworld** [comment]
After a chat via Twitter with the @edent, we were unable to determine why it didn't work. SQLite wasn't better.

The server was kind of old, maybe that was the thing, but I can't find why. I close for now, we wait until next version(s).
