### ISSUE TITLE
Cannot add some articles from FreshRSS

### ISSUE THREAD

**Issue by essembeh** [wallabag/wallabag#1041]
Hello

I try to use wallabag to save interesting articles I read from my FreshRSS reader but I noticed some articles cannot be imported, the content is not fetched.

For example, korben.info (which use feedproxy.google.com).
No problem to save an article from the website using the bookmarklet, but when I read articles from FreshRSS and use FreshRSS share feature to sed the article to wallabag.
The content is not fetched (I tried with the wallabag demo: http://demo.wallabag.org/index.php?view=view&id=5091 )

    Untitled
    [unable to retrieve full-text content]...

To share the article, FreshRSS calls the URL

    http://demo.wallabag.org/?action=add&url=aHR0cDovL2ZlZWRwcm94eS5nb29nbGUuY29tL35yL0tvcmJlbnNCbG9nLVVwZ3JhZGVZb3VyTWluZC9+My9xWjJpdTBxOUdBMC93YXB0Lmh0bWw=

once decoded

    http://demo.wallabag.org/?action=add&url=http://feedproxy.google.com/~r/KorbensBlog-UpgradeYourMind/~3/qZ2iu0q9GA0/wapt.html

Could be a FreshRSS or feedproxy issue...
Any ideas for this one?

**Comment by tcitworld** [comment]
Well, no idea, since I tested twice to add the URL, it failed the first time and worked the second time. I wonder if the redirection causes wallabag to fail the first time, can you test adding it a second time from FreshRSS ?

**Comment by essembeh** [comment]
I have just tested to add the same article on both demo.wallabag.org and my own instance ithout success.

Plus, while trying to find the cause, I also tried many times to add the same article and it never worked for me.

I also planning to try shaarli (https://github.com/sebsauvage/shaarli) and I noticed an interesting point in the README:

    Automatic removal of annoying FeedBurner/Google FeedProxy parameters in URL (?utm_source…)

Maybe google services prevent wallabag to fetch the content because of the URL syntax?

**Comment by tcitworld** [comment]
I remember having seen a reference to feedburner in one of the libraries wallabag uses. Will check on that. I'll try using Sebsauvage piece of code if needed.

**Comment by essembeh** [comment]
I've just tested the *dev* branch (9e5dc91c0383973470f2292b1ec123c48e908e17) and the issue is not resolved.

**Comment by tcitworld** [comment]
Hmm, I was trying  to reproduce the bug (regardless of previous commit) but I didn't manage to have URL with feedproxy inside it. 
The feed URL I was using was http://www.korben.info/feed. Is it the same as yours ? Or could you provide me a RSS feed using feedproxy ?

**Comment by j0k3r** [comment]
@tcitworld here is a RSS using feedproxy http://feeds.feedburner.com/d0od 
AFAIK Korben doesn't use feedproxy.

**Comment by essembeh** [comment]
@j0k3r It seems that Korben.info provides 2 rss feeds, http://korben.info/feed and http://feeds2.feedburner.com/KorbensBlog-UpgradeYourMind (via the "RSS" link in the rop menu of the website)

I've been using http://feeds2.feedburner.com/KorbensBlog-UpgradeYourMind for ages, and the issue I have (#1041) is using this feedburner feed.

Thanks @tcitworld for this alternative rss feed, I've tested it successfully with my FreshRSS. It does not seem to use feedburner stuff and works well.

But the issue remains with feedburner ...
If you want to test send from FreshRSS to Wallabag, there is a demo here: http://demo.freshrss.org/

**Comment by j0k3r** [comment]
It looks great on the v2.
