### ISSUE TITLE
Feature Request: Evernote

### ISSUE THREAD

**Issue by ParoTheParrot** [wallabag/wallabag#1043]
In adition to the Twitter Icon I would like to see an Evernote icon!
I think it's easy using the webclipper feature: https://evernote.com/webclipper.
Evernote bookmarklet code:
```
javascript:(function()%7BEN_CLIP_HOST='http://www.evernote.com';try%7Bvar%20x=document.createElement('SCRIPT');x.type='text/javascript';x.src=EN_CLIP_HOST+'/public/bookmarkClipper.js?'+(new%20Date().getTime()/100000);document.getElementsByTagName('head')%5B0%5D.appendChild(x);%7Dcatch(e)%7Blocation.href=EN_CLIP_HOST+'/clip.action?url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title);%7D%7D)();
```

**Comment by tcitworld** [comment]
Done, thank you for the script, I would have searched for it for a long time if you didn't provide it. :)

**Comment by ParoTheParrot** [comment]
You are welcome! :-)
Where do you add it in the code? I want to test it in my installation.
When will we see this in an official release?

**Comment by tcitworld** [comment]
It's currently in dev branch and we plan to have a release next week.
