### ISSUE TITLE
Install instruction is a mess! 

### ISSUE THREAD

**Issue by Kondra007** [wallabag/wallabag#1045]
First of all, wrong order (as noticed in #1024)
Second, no words about composer.json and his depencies. Otherwise, nothing is installed and there is no "composer" in my system.

**Comment by nicosomb** [comment]
First of all, hello.

> no words about composer.json and his depencies
What do you want to know? If you want documentation about composer.json, you can read this nice website https://getcomposer.org/

Have a nice day.

**Comment by Kondra007** [comment]
You see, in composer.json I need to set depencies for Wallabag, right? But which ones?
Maybe I do not understand something.

**Comment by Kondra007** [comment]
You see, in composer.json I need to set depencies for Wallabag, right? But which ones?
Maybe I do not understand something.

**Comment by nicosomb** [comment]
You don't need to create a composer.json file. 
You have to install composer : 
```
curl -s http://getcomposer.org/installer | php
```

Then, install wallabag: 
```
composer create-project wallabag/wallabag . dev-master
```

**Comment by Kondra007** [comment]
I'm getting an error "No composer.json"

**Comment by nicosomb** [comment]
You have this error after executing this command `composer create-project wallabag/wallabag . dev-master`?

**Comment by Kondra007** [comment]
Yes, but I'm using koding.com virtual machine. To be sure, I'll try this on my local machine.

**Comment by nicosomb** [comment]
OK. Tell me if you still encounter problems.

**Comment by Kondra007** [comment]
After first command I get this info:
>Composer successfully installed to: /home/kondra007/proj/composer.phar
>Use it: php composer.phar

After second command I get 
>Command 'composer' not found

**Comment by tcitworld** [comment]
You can use commands starting with `composer` only if composer is installed globally on your system. See https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx
If that's not the case, all commands must be done in the same directory... I think.

**Comment by Kondra007** [comment]
Yes! That's exactly what I missed. I didn't install it globally, so I should use `php composer.phar` instead of `composer`.
Thanks!

**Comment by nicosomb** [comment]
Thank you @tcitworld ! 
Can I close?

**Comment by Kondra007** [comment]
Yes, now everything is fine..I hope.
