### ISSUE TITLE
v2: bug when adding link

### ISSUE THREAD

**Issue by kevmeyer** [wallabag/wallabag#1057]
Stacktrace: https://gist.github.com/kevmeyer/ef53f2ff256b9a0ffd59  
Test-URL: https://play.google.com/store/apps/details?id=fr.gaulupeau.apps.InThePoche

Line mentioned in Stacktrace: https://github.com/wallabag/wallabag/blob/v2/src/Wallabag/CoreBundle/Service/Extractor.php#L13

**Comment by nicosomb** [comment]
I can't load stacktrace :-/

**Comment by kevmeyer** [comment]
Sorry, updated link. Should work now.
