### ISSUE TITLE
"Fetch content for articles with no content" doesn't work 

### ISSUE THREAD

**Issue by sg-s** [wallabag/wallabag#1058]
# the problem:

I've imported a large number of articles (1000+) from a pocket HTML dump. wallabag imported them all, but most of them turn up with "Untitled - Import - Click to finish import". I gave it a day to process them. It did nothing. Then I clicked on the "Fetch content for articles with no content" in the `config` page, which only fetches a few articles (~5). I see that there are two parameters called `IMPORT_LIMIT` and `IMPORT_DELAY` in `inc/poche/config.inc.php` This makes it import more at a time...but the import fails with this error:

```
Fatal error: Maximum execution time of 120 seconds exceeded in /Library/WebServer/Documents/wallabag/inc/3rdparty/libraries/readability/Readability.php on line 454
```

**How do I get wallabag to import content for missing links without manually clicking the import button every 30 seconds or so?**

# info about install:

Mac OS X, with MAMP 

php --version gives:

```
PHP 5.6.2 (cli) (built: Oct 20 2014 16:21:27) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by sg-s** [comment]
further info:

in `/etc/php.ini`, I see there is a `max_execution_time = 30`.

**Comment by tcitworld** [comment]
I will write a detailed anwser later, but for the moment, you can try some things at #640.

**Comment by sg-s** [comment]
thanks ... that looks helpful. i'll give it a shot.
