### ISSUE TITLE
1.7.x to 1.8 gives blank page

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#1064]
Hi

I upgraded from 1.7 something to 1.8 and all I am getting is a blank page. 

I downloaded te latest zip copied onto 1.7.x deleted the install folder and cleared out the cache folder. 

And I do not know how to upgrade from scratch like moving the database settings etc to a clean install

thanks

**Comment by tcitworld** [comment]
I guess you have some errors that aren't displayed. Are you able to enable errors in your php.ini and tell us what they are ? (`display_errors` to `on` and `error_level` to `E_ALL`).

**Comment by gerroon** [comment]
ok I will try it

How do I manually move database and the settings from the old setup to a fresh setup?

**Comment by tcitworld** [comment]
It depends what database system you were using. 
With SQLite, saving and coping `db/poche.sqlite` and the config file at `inc/poche/config.inc.php` *should* be enough,
With MySQL and PostgreSQL, copying just the config file will do (if you don't change your database)

In all case, be sure not to run the install page when putting version 1.8. Just put the 1.8 files, copy the config file at it's location and remove the default one `config.inc.default.php` (and eventually the SQLite DB file), **remove the install folder** and hope I'm correct. ;)

**Comment by gerroon** [comment]
well that is interesting i just created a new fresh 1.8 and copied the database and the config and I still get an empty page I even installed the vendor stuff
