### ISSUE TITLE
Empty Articles from www.businessinsider.com

### ISSUE THREAD

**Issue by markwaters** [wallabag/wallabag#1073]
http://www.businessinsider.com/how-bitcoin-may-have-more-impact-than-the-internet-2015-2

**Comment by nicosomb** [comment]
It works with latest version (dev branch).

**Comment by amd55554** [comment]
Thanks for post this helpful post - Please visit for More information about -
http://www.expert5th.in/packers-and-movers-bangalore/
http://www.expert5th.in/packers-and-movers-hyderabad/
