### ISSUE TITLE
Using Wallabag with Apache in a location different than /

### ISSUE THREAD

**Issue by nRaecheR** [wallabag/wallabag#1075]
Hi,

I'm trying to setup Wallabag as an additional location on my domain with an "domain.tld/wallabag/ location. I've configured the Apache2 server to make a ProxyPass for the mentioned location to the server with the Wallabag instance. 

Problem: Wallabag seems to rewrite the URL to the root (/) location which leads to a redirect to my main webpage. 

Is there any way to prevent this rewrite of the URL? Does Wallabag support a different location as root (/) ?

**Comment by tcitworld** [comment]
The faulty function is `getPocheUrl()` in [`inc/poche/Tools.php`](https://github.com/wallabag/wallabag/blob/master/inc/poche/Tools.class.php#L41).

The value of $_SERVER["SCRIPT_NAME"] would help to determine what's wrong.

**Comment by bartatgithub** [comment]
Same problem here before, but after third clean install, i come always back to the install page with this message: "wallabag seems already installed. If you want to update it, you only have to delete install folder, then reload this page."

**Comment by tcitworld** [comment]
@bartatgithub You should check your permissions, this means the install script couldn't delete the install folder. Or else, the paths are mistaken (and therefore the folder hasn't been deleted) since you use a proxy.
Anyway, it should work when manually deleting install folder.

**Comment by bartatgithub** [comment]
Permissions ok, deleted install folder and it works. Thanks! 
Sorry, i should have started a new issue.

**Comment by nRaecheR** [comment]
@bartatgithub I don't think that my Apache2 installation is the problem. I run several services from the main instance, all with ProxyPass setting and "domain.tld/wallabag/ scheme. But only Wallabag redirects to the main domain.

**Comment by MoriTanosuke** [comment]
I have a similar problem when running behind a reverse proxy. The installation of wallbag went fine, and also looked like it had the theme applied. But when I try to log in, and even after, everything looks black and white and all the links point to *http://mydomain/themes/...*.

Is there a way to set the base URL of my installation so I get valid links or do I have a rewrite mod on my reverse proxy to fix this?

**Comment by MoriTanosuke** [comment]
I had a look at the sources and I think I found the place that is causing me issues with my reverse proxy setup. If you take a look at https://github.com/wallabag/wallabag/blob/master/inc/poche/Tools.class.php#L75 the path that is used by themes to generate the links is using a calculated path.

I modified wallabag in my fork and added a new config option *BASE_URL* which I can set to a absolute URL which is then used in themes to generate links to CSS and JS resources. That way I can run my installation behind a reverse proxy. :smile:

My knowledge of PHP and the used frameworks is, well, limited. Maybe someone can have a look at my *dev* branch over at https://github.com/MoriTanosuke/wallabag/tree/dev and tell me if I missed something important and accidentally broke the API or something stupid like that. I can use the Android app, but maybe there is more than I see at the moment.

If there is nothing else I need to change or no better way to set the *BASE_URL*, I'd like to create a pull request for this change.

**Comment by tcitworld** [comment]
Please create a PR, it's much better for reviewing. Thanks for the work anyway !

**Comment by nRaecheR** [comment]
Updated to 1.9.1-b...works like a charm now under a subfolder. Good work, closing issue...

**Comment by tcitworld** [comment]
I will close again when https://github.com/wallabag/wallabag/pull/2181 will be merged.

**Comment by 1337sup3rh4x0r** [comment]
I was just about to open a new issue; I can access my wallabag just fine locally via http but not from externally via my ssl proxy. The login page doesn't work and it looks weird. Basically all images and css styles seem to be missing.

Will #2181 fix this?
Could I just update the 4 files it contains?

**Comment by tcitworld** [comment]
It should, yet. We just don't have the time to test it right now, but please tell us how it goes.

**Comment by 1337sup3rh4x0r** [comment]
Ok, merci beaucoup for the quick answer! I'll try and report back.

**Comment by 1337sup3rh4x0r** [comment]
I'm having some trouble configuring this correctly.
I updated the files from the commit and after running

    env SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist

the setup asked me 

    Some parameters are missing. Please provide them.
    base_path (''): 

I put ´´/usr/home/wallabag/wallabag/web´´, which is where my ´´app.php´´ is.

But I guess that was wrong, as I now get 404 ... :)

should I have left that blank?

**Comment by tcitworld** [comment]
@1337sup3rh4x0r Please look where your assets are being fetched without the patch (Ctrl + Maj + K to see loading errors on Firefox, Ctrl + Maj + J for Chrome) and try to determine their correct location.

**Comment by nicosomb** [comment]
@1337sup3rh4x0r your answer will help us to merge (or not) #2181 ;-)

**Comment by 1337sup3rh4x0r** [comment]
Sorry for delaying the train! I will look into it again!

**Comment by 1337sup3rh4x0r** [comment]
How do I get back to the point that I am asked to provide a new base_path like in the dialogue mentioned above?
Or where do I change it manually? I put a wrong path and now I can't bring up wallabag anymore.

**Comment by 1337sup3rh4x0r** [comment]
So I figured out that the base_path parameter is stored in `app/config/parameters.yml`
After editing this file, I need to run `env SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist`

So far so good. But I just can't figure out what to set the `base_path` parameter to.

With the changes from #2181 applied I just can't connect to wallabag, not directly and not via the proxy, no matter what I type in as `base_path`

Maybe I am just doing it horribly wrong. I tried to figure out via the firefox console the way @tcitworld described it. I thought that pointed me to the relative subfolder `web/` in my wallabag install directory (absolute path: `/usr/home/wallabag/wallabag`) but that didn't work.
`app` didn't work either. Leaving it blank also doesn't work.

I think I maybe just don't get the concept of this parameter ... 
is this an absolute folder path to a file, or a relative path from the web root of my webserver?

maybe someone can enlighten me?

**Comment by nicosomb** [comment]
Hello all, 

Can you have a look to my post here please https://github.com/wallabag/wallabag/issues/1913#issuecomment-259626511?

**Comment by 1337sup3rh4x0r** [comment]
Hi nicosomb,
I just started with a fresh install of wallabag to see if things might have improved.
Locally, when accessing wallabag from within my LAN via its IP adress, all is well. 
But I still can't get it to work behind my reverse proxy.

When I call the address of the proxy from outside, I am redirected to the local IP address which, which is not accessible from outside.

My problem is not, that I want to install wallabag in a subfolder of my website.

My situation is the following:

I have a reverse proxy that is accessible only via ssl:

    https://mydyndns.address.com

depending on the called location, it redirects to different webservers that are on my lan:

    https://mydyndns.address.com/owncloud -> http://192.168.178.21
    https://mydyndns.address.com/roundcube -> http://192.168.178.22
    https://mydyndns.address.com/wordpress -> http://192.168.178.23
    https://mydyndns.address.com/wallabag -> http://192.168.178.24

My problem is, that this isn't working for wallabag. When I call https://mydyndns.address.com/wallabag, I am redirected  to http://192.168.178.24/login, which doesn't exist.

Access Log:

    192.168.178.20 - - [20/Nov/2016:19:07:01 +0100] "GET / HTTP/1.0" 302 356 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"

When I call https://mydyndns.address.com/wallabag/login directly, It displays the login page, but without any assets.

Access Log:

	192.168.178.20 - - [20/Nov/2016:19:08:33 +0100] "GET /login HTTP/1.0" 200 5298 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"

When I call the local address http://192.168.178.24, it works just fine.

Access Log:

	192.168.178.65 - - [20/Nov/2016:19:03:52 +0100] "GET / HTTP/1.1" 302 300 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
	192.168.178.65 - - [20/Nov/2016:19:03:52 +0100] "GET /quickstart HTTP/1.1" 200 15853 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
	192.168.178.65 - - [20/Nov/2016:19:03:52 +0100] "GET /bundles/wallabagcore/themes/material/css/style.min.css HTTP/1.1" 304 0 "http://192.168.178.24/quickstart" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
	192.168.178.65 - - [20/Nov/2016:19:03:52 +0100] "GET /bundles/wallabagcore/themes/material/js/material.min.js HTTP/1.1" 304 0 "http://192.168.178.24/quickstart" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
	192.168.178.65 - - [20/Nov/2016:19:03:52 +0100] "GET /bundles/wallabagcore/themes/_global/img/logo-square.png HTTP/1.1" 304 0 "http://192.168.178.24/quickstart" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"

Do you understand my problem?

**Comment by nicosomb** [comment]
@1337sup3rh4x0r thank you for your explanations. Does #2181 fix your problem?

**Comment by 1337sup3rh4x0r** [comment]
Not yet, as mentioned above I didn't manage to set the base parameter to a value that would make it work.
I would gladly try this and report back if someone could look at my questions above, regarding what to set the parameter to.

**Comment by Kdecherf** [comment]
This issue relates to wallabag v1 and had no update in the past six years, closing it
