### ISSUE TITLE
No article from Catholic.com get save to wallabag

### ISSUE THREAD

**Issue by shackra** [wallabag/wallabag#1076]
I get "Untitled" and "[unable to retrieve full-text content]..."

Using the instance provided by Framabag.

**Comment by j0k3r** [comment]
Could you give us an example please ?
Thanks

**Comment by shackra** [comment]
I was able to save articles after some time ago, this should be close!

El domingo 10 de abril del 2016 a las 1157 horas, Jeremy Benoist escribió:

> Could you give us an example please ?
> Thanks
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/wallabag/wallabag/issues/1076#issuecomment-208032485


-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra
