### ISSUE TITLE
Wrong display in wallabag: lowerclassmag.com

### ISSUE THREAD

**Issue by innir** [wallabag/wallabag#1077]
Hi,

on http://lowerclassmag.com hte image captions are not excluded which is kind of confusing, see

http://lowerclassmag.com/2015/02/die-linke-und-der-islam-2/

I think a site_config like

    title: //h1[contains(concat(' ',normalize-space(@class),' '),' entry-title ')]
    body: //div[contains(concat(' ',normalize-space(@class),' '),' entry-content ')]
    test_url: http://lowerclassmag.com/2015/02/die-linke-und-der-islam-2/

should work.

BTW: I'm using Framabag.

Best

**Comment by j0k3r** [comment]
Looks good without a site config.
If you still think it needs a site config don't hesitate to submit it at https://github.com/fivefilters/ftr-site-config
