### ISSUE TITLE
allow_url_fopen disabled try to use php-curl

### ISSUE THREAD

**Issue by bartatgithub** [wallabag/wallabag#1078]
here my new issue: 
I know that i am missing allow_url_fopen and wallaby will not work properly. 
I have installed Wallabag on my virtual server. All needed php function are enabled but my host doesn't want to enable allow_url_fopen because of security risks. My host tells me to use instead php-curl.

Is it possible to use Wallabag without allow_url_fopen and instead with php-curl?
Can i use Wallabag with less function so that i don't need allow_url_fopen?

Thanks for any help.

**Comment by tcitworld** [comment]
It should work anyway. wallabag compatibility script shows it as a requirement (will fix that), but it seems we don't actually use it when curl is present, except with the PHP library used to produce ePub files.
So wallabag should run anyway, please tell us if it doesn't. :)

**Comment by bartatgithub** [comment]
Right started to use and it works like a charm, thanks! 
Yes, it has confused me and let me search for almost a week for a solution. 
Almost changed to an other host. :-)

**Comment by tcitworld** [comment]
Well, disabling `allow_url_fopen` is kind of unusual...

**Comment by bartatgithub** [comment]
One fast question: is it normal that there is no way to add tags?

**Comment by tcitworld** [comment]
Replied on other issue.
