### ISSUE TITLE
Change tag icon

### ISSUE THREAD

**Issue by bartatgithub** [wallabag/wallabag#1079]
Is it normal that there is no way at all to add tags? 
The tags page is empty except title "tags".

**Comment by tcitworld** [comment]
You have to go on an article page to add article to each of them.

Currently, you have to add tags once the article is already saved. This will change in next version.

**Comment by bartatgithub** [comment]
Ok, thanks. Stupid me! 
A small tag icon in the same place as the toggles, delete and original buttons would be more clear and nice.

**Comment by tcitworld** [comment]
Will do. :)

**Comment by bartatgithub** [comment]
Thanks! Strange or not, when i "bag" a Wallabag web page or Wallabag Github page there is no title or text at all saved. Only the url! Is this self censure? :)

**Comment by tcitworld** [comment]
What do you mean by wallabag web page ? Github pages can't be saved because Github is using some server specific http headers to forbit that [(more details)](https://github.com/sebsauvage/Shaarli/issues/94).

**Comment by bartatgithub** [comment]
This one where i first have asked my question also: http://support.wallabag.org/discussions/problems/100-allow_url_fopen-disabled-try-to-use-php-curl
Maybe for the same reason but not possible to "bag" properly. 
![wallabag_screenshot](https://cloud.githubusercontent.com/assets/6533745/6188874/1c339a72-b396-11e4-916f-9a5fadd19a48.png)

**Comment by tcitworld** [comment]
Hmm, still this regression from version 1.7.0 to 1.8.1. You may encounter more pages not saving, but most of them should work just fine, hopefully.
Right, I guess I've got some work to do. :)

**Comment by bartatgithub** [comment]
Till now only Wallabag related web pages aren't properly saving. :) 
You have already done a BIG job. 
I am happy with what it does and how it works now. 
Will start using Wallabag intensive now and let you know if something wrong or an idea popping up.

**Comment by tcitworld** [comment]
I'm not the one to thank. @nicosomb does most of the job. ;)

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
