### ISSUE TITLE
v1.9 beta: random does not work

### ISSUE THREAD

**Issue by kevmeyer** [wallabag/wallabag#1082]
On my setup the feature `?action=random` does not work.
When trying to get a random article the site doesn't load in minutes until the php execution time limit is reached. Then it fails with `500 Internal Server Error`.

I think [this while loop](https://github.com/wallabag/wallabag/blob/dev/inc/poche/Poche.class.php#L397) in combination with my current database is causing the while loop to become an infinite loop. In my Database the article ids are much bigger than the count of articles, which seems to be the reason for this behaviour.

**Comment by tcitworld** [comment]
Okay, I will change the system (quite ugly code, now that you point it out).

**Comment by tcitworld** [comment]
Okay, can you test how it's going now ?

**Comment by nicosomb** [comment]
As I told to @tcitworld, the random is the SQL's job, not PHP one.

**Comment by kevmeyer** [comment]
Still doesn't work for me:
```
Fatal error: Call to a member function fetchAll() on a non-object in /var/www/.../html/wallabag-dev/inc/poche/Database.class.php on line 419
```

**Comment by tcitworld** [comment]
Hmm, strange. All that will change anyway.

**Comment by tcitworld** [comment]
Sorry for the error before, can you test it now ?

**Comment by kevmeyer** [comment]
working, thanks!

**Comment by tcitworld** [comment]
Without any timeout ? Great.
