### ISSUE TITLE
Add untagged support.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1083]
I am transitioning over from pocket and I am used to have a sort by untagged option and I would really appricate it if you added it in a later version. I don't think it would be that hard you could just add it to the tags. If I am missing something that is already in wallabag (v.1.8.1) that does the same thing please let me know.

**Comment by tcitworld** [comment]
You mean, get all the article which aren't tagged ?

**Comment by mathwhiz1212** [comment]
Yes, it would (in theory) act pretty much like a tag that way the ones I have already sorted aren't in my way when I'm trying to sort the untagged articles which makes it a lot easier to deal with 1,000+ articles.

**Comment by tcitworld** [comment]
Will try some things, without promise it will done soon, since it must be much easier to deal with that kind of feature on v2.

**Comment by j0k3r** [comment]
Duplicate of https://github.com/wallabag/wallabag/issues/1631
