### ISSUE TITLE
Saying I don't have permission to access to /inc/poche/config.inc.php during install.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1086]
(I have solved this but It took me a while to find a solution and I thought it might be helpful to give the solution here.) When I was installing wallabag v.1.8.1  During the installation it said access denied or something like that and said it was unable to write to /inc/poche/config.inc.php and I was able to fix it by simply giving the web server write access to inc as well as the assets, cache and db directories.

Technical info on the setup I had:
I was install wallabag v.1.8.1, running nginx on a raspberry pi that had raspbian on it and it wasn't doing anything else other than hosting the wallabag server at the time. I think I had PHP 5.4.36 it was either that or the version directly before it. There were no problems with the wallabag_compatibility_test.php.

**Comment by tcitworld** [comment]
I'll add a message *check the rights on the wallabag folder* to the `unable to write to /inc/poche/config.inc.php` error message.

**Comment by mathwhiz1212** [comment]
That will help people in the future, thanks.

**Comment by colinjoy** [comment]
Not sure if documentation issues are handled via github as well, but this requirement should certainly be part of the installation instructions. At least for English it isnt.

**Comment by tcitworld** [comment]
We will change that. :)
