### ISSUE TITLE
Delete cached images

### ISSUE THREAD

**Issue by 876974** [wallabag/wallabag#1087]
It would be desirable if the option to cache images on the server when removing materials, images of this material as well removed from the server folder assets

**Comment by tcitworld** [comment]
Well, pictures should be deleted when you delete the corresponding article. If they don't, you have a problem.

**Comment by 876974** [comment]
Either this is a mistake of the new 1.9 version, that when you reboot the material remains as the old folder with images, so established and new, with re-loaded.

**Comment by tcitworld** [comment]
Sorry to ask you, but could you explain better what you're trying to mean ? I'm not sure I understood.

When you reload an article with the "reload" button, pictures are kept, not re-fetched.

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
