### ISSUE TITLE
Project ideas

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1088]
This is a list of projects or ideas to work on that we suggest.

### Write a mobile app
**Description** : Currently relying on reading RSS feeds, the mobile applications are missing a lot of features (mark as read, tags, category, searching) that can now be provided by the API included with v2.0. The new apps should take advantage of [all the possibilities](http://v2.wallabag.org/api/doc/) offered by the API.
The app should be build with a cross-plateform framework, such as AngularJS and Cordova, so that the work can be reused on different systems.

**Knowledge prerequisites:** 
_minimal_  html5, js, git, iOS *or* Android *or* Windows 8 apps *or* Firefox OS *or* Ubuntu Touch
 _preferred_ : AngularJS, Cordova

**Difficulty:** medium/hard

### Connect wallabag to IFTTT
**Description** : Write IFTTT recipes to connect wallabag on determined actions. Ask IFTTT for a [partnership](https://docs.google.com/forms/d/1dlH6aA2nXQ4EWfQbxHKueHvfyulFPmInkjk7PabUxF8/viewform) for them to add a wallabag Channel (there are already Pocket, Instapaper and Readability channels).

**Knowledge prerequisites:** to be determined, we must exchange with them
**Difficulty :** easy

### Make linux install packages
**Description** : There have been attempts to create debian packages for wallabag, but they didn't succeed. We should have deb and rpm packages. wallabag is already in the [AUR](https://aur.archlinux.org/packages/wallabag) for archlinux.

**Knowledge prerequisites:** linux, debian packaging (while following guidelines), rpm packaging

**Difficulty :** medium

### Support LDAP account management
**Description** For enterprises, offer wallabag accounts based on a LDAP directory. LDAP Symfony bundles exist. Discussion at #966.

**Knowledge prerequisites:** PHP, Symfony, knowing LDAP would be a plus

**Difficulty :** easy/medium

### Fetch content from password protected websites
**Description** wallabag currently can't fetch content from websites that are requiring an authentication to display content. We have two leads on how to deal with that : 
* save http sessions and cookies and wallabag sends them : tricky solution, since every website has it's own method
* use browser extensions to fetch content with javascript and then send it to wallabag : better solution, should work anywhere

**Knowledge prerequisites** (for the second solution) : javascript, Chrome/Firefox extensions, PHP and Symfony

**Difficulty :** medium/hard

### Extend the functionalities of the Browser extensions
**Description** : Currently the extensions only consist in sending the window link to wallabag, nothing more. With v2, they should be capable to : 
* show if the webpage has already been saved
* directly tag the page just saved
* change it's properties (starred, archive, deleted, etc)

**Knowledge prerequisites** (for the second solution) : javascript, Chrome/Firefox extensions

**Difficulty :** medium

### Use the Mozilla social API inside Firefox
**Description** : 
> The [Social API](https://developer.mozilla.org/fr/docs/Social_API) is a new API to make it easier for web browsers to integrate with social media services
Pocket already uses the social API for it's bookmarklet inside Firefox. If the social API can replace a browser extension, then better use the social API.

**Knowledge prerequisites** : js, xul

**Difficulty :** easy (if the work on previous idea has already been done)

### [v1.x] Adapt Chrome extension to Opera
**Description** Opera now uses the Chromium extension model, it should be fairly easy to support Opera too.

**Knowledge prerequisites** : JS, Chrome extensions

**Difficulty :** easy

**Comment by tcitworld** [comment]
I've locked this issue as it should just be a static page. Please create specific issues depending on the idea or join one of the already existing ones if you want to discuss.

**Comment by nicosomb** [comment]
I close this issue, I put all these ideas here #1254.
