### ISSUE TITLE
How long should I expect wallabag to be down after importing?

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1091]
How long should I expect wallabag to be down after importing ~7,500 articles from pocket?
Wallabag V.1.8.1, PHP 5.4.36, mysql Ver 14.14

**Comment by tcitworld** [comment]
Wow, I don't think anyone has once imported a such amount of articles. I guess you will have a timeout at some point, and you may have to play with the `IMPORT_LIMIT` (increase) and `IMPORT_DELAY` (reduce) if your webserver can handle it in your `inc/poche/config.inc.php` config file.

Import system is really bad, but we are focused on v2 right now.

**Comment by mathwhiz1212** [comment]
I already had it set IMPORT_LIMIT to 8000 because I knew it was around 7500 articles, And I set IMPORT_DELAY to 1 before I started this import and it seems to be working the php5-fpm process is averaging ~60% cpu usage ranging from 30-95% on my raspberry pi web server. I just hope it all works, I did export the articles before I did this just in case anything went wrong and it broke or something. I haven't been able to access the server since I did the import.

**Comment by mathwhiz1212** [comment]
It finished I'm going to undo because it only imported some of them.

**Comment by mathwhiz1212** [comment]
It only imported ~700 of them going to delete, then restore old file for organizations sake, mabye v2 will fix this.

**Comment by mathwhiz1212** [comment]
Ok I deleted my account and all data assoicated with it on my server how do I create a new one from the server side?

**Comment by mathwhiz1212** [comment]
Do I have to reinstall or is there a simpler method?

**Comment by mathwhiz1212** [comment]
Tcitworld responded with this in another issue:

You've got to use phpMyAdmin or the mysql console and create a new row in the users table with :

    your username
    your salted password = the sha1 of (yourpassword + your username + your salt available in the config file inc/poche/config.inc.php). *To obtain the sha1, you can use this tool. For instance, passwordloginsalt gives 1bbc43879ee7fb5c78c8dcefee1f9f31d0ffe4f2
    your username again... for some reason I can't see why
    your email eventually, or leave blank
