### ISSUE TITLE
Did you forget to select a file?  Import finished. When trying to import.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1096]
I am trying to import a .json file from another wallabag installation and it says:  Did you forget to select a file? Import finished. and nothing happens. IMPORT_LIMIT is set to 9999 and IMPORT_DELAY is set to 1. I have tried importing different .json files but I still get the same error

Wallabag V.1.8.1, PHP 5.4.36, mysql Ver 14.14

**Comment by tcitworld** [comment]
Did you choose your file correctly in the modal window ? It seems it isn't detected.

**Comment by mathwhiz1212** [comment]
Here are some screenshots.
![screenshot from 2015-02-17 18 43 09](https://cloud.githubusercontent.com/assets/11021683/6241085/1ab1edba-b6d5-11e4-958e-f3e9243e07ce.png)
![screenshot from 2015-02-17 18 44 25](https://cloud.githubusercontent.com/assets/11021683/6241084/1aafe984-b6d5-11e4-8b8b-6bf7f222e963.png)
![screenshot from 2015-02-17 18 44 03](https://cloud.githubusercontent.com/assets/11021683/6241086/1ab38fe4-b6d5-11e4-824f-40f64e10770b.png)

**Comment by mathwhiz1212** [comment]
A smaller file with only 3 articles in it was easily imported and it worked perfectly.

**Comment by tcitworld** [comment]
Quite strange. Anyway, when I said on the other issue, increase IMPORT_LIMIT, it was never meant to be increased to 9999. IMPORT_LIMIT is the limit for a batch of articles, at the end of which the process is restarted, not the whole of them. Set it to a number from 10 to 50.

**Comment by mathwhiz1212** [comment]
I tried 50, 20 and 10 and I even tried scraping the current install of wallabag and starting over with just twitter and flattr share links turned off and DOWNLOAD_PICTURES set to TRUE and IMPORT_LIMIT set to 10 then I also tried with IMPORT_LIMIT and IMPORT_DELAY at their defaults and I still get the same error.

**Comment by tcitworld** [comment]
> just twitter and flattr share links turned of

Nothing to do with those kind of settings

> DOWNLOAD_PICTURES set to TRUE

Setting it to FALSE will make things run faster, since you don't have to download pictures for each article.

I'm starting to wonder if it's not a problem with the file. Could it be corrupted ?

The `Did you forget to select a file` message should only occur when the server did not manage to upload the file. Could you checkout [this solution](http://stackoverflow.com/a/2184541) and see what's the weight of your file ?

**Comment by mathwhiz1212** [comment]
It works! I did what that you sent me and I got a 504 error. Then I did this http://www.nginxtips.com/504-gateway-time-out-using-nginx (slightly modified because I have a different setup and it worked)

**Comment by mathwhiz1212** [comment]
@tcitworld Thanks for all the help with all of many problems. :+1:

**Comment by tcitworld** [comment]
Glad to help.

Actually, I've released a [new version](https://github.com/wallabag/wallabag/releases/tag/1.9) while you were dealing with those problems. Don't worry, upgrade is possible. :D

**Comment by mathwhiz1212** [comment]
Super cool updates, I am up and running with V.1.9. :D As far as servers go it was a breeze to update.

**Comment by tcitworld** [comment]
Great !

**Comment by mathwhiz1212** [comment]
Although I'm not seeing how to download 1 article as a .pdf without downloading all of them (don't know if it's possible.) or how to do public registration.

**Comment by mathwhiz1212** [comment]
I opened another issue.

**Comment by lapineige** [comment]
I have the same issue (should I re-open it ?), I tried the solution in the link you gave @tcitworld (http://stackoverflow.com/a/2184541) so I changed this file: /etc/php5/cli/php.ini
I put 100M for each value, and I try to upload a 2,3M file.
I also changed /etc/nginx/nginx.conf to allow upload of <100M files.

I still have the issue. Any idea ?

**Comment by tcitworld** [comment]
Version v1.x isn't supported anymore, sorry. If you have the issue on v2, please open a new ticket.

**Comment by lapineige** [comment]
Ok. I've not v2 available (i'm using it on Yunohost) so I can't test now.
I will try to cut that file manually.
