### ISSUE TITLE
'X-Frame-Options' - 'DENY'

### ISSUE THREAD

**Issue by skynet** [wallabag/wallabag#1097]
I get this error after trying to use Chrome extension with self-hosted wallabag.

Refused to display 'https://www.mydomain.com/wallabag/?view=home' in a frame because it set 'X-Frame-Options' to 'DENY'.

**Comment by tcitworld** [comment]
Well, you've got to configure your webserver to disable this configuration line, the extensions uses iframes anyway at the moment.

**Comment by skynet** [comment]
I believe that I need to send a special header from server, to the browser.

**Comment by tcitworld** [comment]
You need to stop your server to send that particular header. It shouldn't send it by default. [Here's](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options) what you should remove, depending on your webserver software.

**Comment by skynet** [comment]
And ... you are right!
```
x-content-type-options:nosniff
x-frame-options:DENY
x-page-speed:Powered By PageSpeed
```
I need to find out what module (or maybe PageSpeed) is adding this header.
