### ISSUE TITLE
full webpage screenshot

### ISSUE THREAD

**Issue by heini91** [wallabag/wallabag#1098]
it would be fine if on item add there would be taken a full webpage screenshot for exmaple on base of phantomjs. so if the webpage is down, you have also a saved full view of the site.

**Comment by j0k3r** [comment]
What will be the added value to the text already saved by Wallabag?

**Comment by heini91** [comment]
a alternative view particularly for pages where not only the text is interesting.

**Comment by tcitworld** [comment]
You can locally download pictures if needed. Moreover, I don't think it's an easy thing to do in our case, even with PhantomJS.

**Comment by heini91** [comment]
Yes locally download is an option, but in one app it is a better solution, i think. If you investigate something and the original page is deleted you have an overview about this page. I know PhantomJS to take automated screen captures, i dont know if there is an similar option in PHP.

**Comment by githubtobi** [comment]
I would love it too. The added value is the image. People can connect images easier in their mind than headlines or text. And it looks nicer ;-)

BTW: Great application!

**Comment by j0k3r** [comment]
@githubtobi I think you misunderstood the request. What you said could be related to #972

@heini91 want a full screenshot of the content behind the url entry, as a backup in case of Wallabag content wasn't that good and user wants to see the website while it's down (*that's a lot of conditions anyway*)

**Comment by githubtobi** [comment]
right - sry @j0k3r

**Comment by nicosomb** [comment]
This feature won't be implemented in wallabag, wallabag fetches articles, not full web page. Other tools do this stuff very well.
