### ISSUE TITLE
Login screen not centered

### ISSUE THREAD

**Issue by Inalith** [wallabag/wallabag#1099]
Hi! Really enjoying Wallabag so far! What I did do noticed, when I click the logo (add-on on firefox) I get a small screen for login. But it is not centered so I have to make the screen bigger so I can log in propperly. Is there any way that could be fixed? Thanks!
![screenshot from 2015-02-18 21 00 03](https://cloud.githubusercontent.com/assets/11065286/6255568/3e62c0ae-b7b1-11e4-9bbe-25e079d33955.png)

**Comment by tcitworld** [comment]
Yup, I'm fixing this right now.

**Comment by Inalith** [comment]
Ah cool! Thank you so much! And good luck :)
