### ISSUE TITLE
Make the dice bigger

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1101]
I'm not seeing how to download 1 article as a .pdf without downloading all of them (don't know if it's possible.) or how to do public registration.

**Comment by tcitworld** [comment]
You've got to edit the config file `inc/poche/config.inc.php` file, while referring to the model named `config.default.inc.php` (also available [here](https://github.com/wallabag/wallabag/blob/master/inc/poche/config.inc.default.php)).

For PDF it's `@define ('PDF', TRUE);` and for public registration it's `@define ('ALLOW_REGISTER', TRUE);`

**Comment by mathwhiz1212** [comment]
Thanks for the help, tell me if you want me to make another issue for this but you should make the random button more prominent, I didn't see until I looked for it and I think it's a cool feature, But overall 1.9 is a huge improvement, although probablly not noticable to most people there is a speed improvement as well as what is listed and it doesn't take over the current window, it opens another one and automatically closes. (The bookmark.) But anyway, I really like V.1.9 and I can't wait to see what V.2.0 is going to be like!

**Comment by tcitworld** [comment]
Well, I though the dice would be pretty obvious.

**Comment by mathwhiz1212** [comment]
I was just thinking maybe make it bigger.

**Comment by tcitworld** [comment]
Actually it's 16px square, I will increase it's size a little to see how it goes.

**Comment by mathwhiz1212** [comment]
Ok going along with my original title I'm not seeing the functionality to tag an article when saving it is there something I need to enable in the config as well?

**Comment by tcitworld** [comment]
Hmm no.
Don't you have the label icon next to the url field ? 
![savelink](https://cloud.githubusercontent.com/assets/2197836/6305445/9256485e-b92b-11e4-9285-1d3332ce769f.PNG)

**Comment by mathwhiz1212** [comment]
Yes it does, I was using the bookmark and the firefox extension to save articles because it's a little more convenient, you should make it so after you save a link with the bookmark or extension you are given the option to add a tag that goes away after x amount of seconds.

**Comment by tcitworld** [comment]
This can't be done currently. This needs the API and v2.

**Comment by mathwhiz1212** [comment]
I was figuring it would probablly be in v2, I think v2 might be the "bountiful update" with so many awesome features planned it's going to be really impressive.

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
