### ISSUE TITLE
I'm getting duplicate articles.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1102]
I'm getting duplicate articles when I get the same article saved twice with just slight variations.
e,g : 
http://lifehacker.com/call-your-doctor-mid-morning-to-snag-a-cancelled-appoin-1682628702?utm_source=feedburner 
http://lifehacker.com/call-your-doctor-mid-morning-to-snag-a-cancelled-appoin-1682628702
and it saves 2 articles instead of just one.

**Comment by tcitworld** [comment]
Yeah, today it doesn't save another article only if the URL matches exactly the one from the other article. We've got to make exceptions for these kind of cases.

**Comment by tcitworld** [comment]
That's fixed.

**Comment by mathwhiz1212** [comment]
I was just thinking a good way to add an exception for these cases might be that anything after the ? is usually not the page's URL itself but telling the page to do something or for antalytics.

**Comment by tcitworld** [comment]
The exceptions I've made are just `&utm_source=`,  `?utm_source=` and `#xtor=RSS-` and should concern just feedburner and most social networks sources.
