### ISSUE TITLE
Courgette theme still present

### ISSUE THREAD

**Issue by Linuxine** [wallabag/wallabag#1103]
I have juste installed the 1.9 version, and I still can choose the courgette theme in the list, is it normal ? The release note says it has been removed ? I have tried to "delete cache" without success.

**Comment by tcitworld** [comment]
Hmm. Just delete the courgette theme inside the themes/ folder and it shouldn't show up anymore. 

We've only deleted it in newer versions, but since you've upgraded, you have kept it.

**Comment by Linuxine** [comment]
Oh, good point, I didn't think of the upgrade !  Sorry, my mistake :)
