### ISSUE TITLE
Firefox Addon give an error on saving a link

### ISSUE THREAD

**Issue by Ricardo-Glasswall** [wallabag/wallabag#1104]
I just upgraded to server version 1.9.0. I tried to save a link with the Firefox addon (v1.2) and I recieve the error:

Fatal error: Class 'HTMLPurifier_URIFilter' not found in /srv/www/htdocs/wallabag/inc/3rdparty/htmlpurifier/HTMLPurifier/URIFilter/DisableExternal.php on line 4

Note: I do not get this error on all sites. I tried it on this githup page and this worked. But on the WordPress page showed in the attachment I got the error. Also on a Dutch newsite: www.telegraaf.nl

![screenshot from 2015-02-19 11 49 24](https://cloud.githubusercontent.com/assets/8694148/6265540/ef8ad5fa-b82f-11e4-87b3-909958bd9932.png)

**Comment by Ricardo-Glasswall** [comment]
Also, I just tried to add the url from the Save a link page on the Wallabag site and the url box becomes red and it didn't save the link.

**Comment by tcitworld** [comment]
The first error suggests a file is missing (precisely `inc/3rdparty/htmlpurifier/HTMLPurifier/URIFilter.php`). Maybe coping the files failed ? Please copy all of the files over your installation again, then just delete the install directory.

**Comment by Ricardo-Glasswall** [comment]
The file was there, I allready checked it. But it was only half the size of what it should have been (2.4k).
Thanks!
