### ISSUE TITLE
Add tag field.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1108]
You should have the add tag field appear on the current page when you click the edit tags button (The pencil) instead of going to another page.

![screenshot from 2015-02-19 20 58 02](https://cloud.githubusercontent.com/assets/11021683/6281230/0560a356-b87a-11e4-8e3a-22d870ba2bdd.png)
![screenshot from 2015-02-19 20 57 40](https://cloud.githubusercontent.com/assets/11021683/6281231/068d89b0-b87a-11e4-8bcf-9206ba108be1.png)

**Comment by nicosomb** [comment]
Done in material theme in wallabag v2.
