### ISSUE TITLE
Add capability to add tags from main page.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1109]
You should add capablity to add tags from main page possibly in the same place that we can currently delete, archive, favorite, or go to original link from. (hopefully a bulk edit for adding tags to a bunch of articles at once as well.)
![screenshot from 2015-02-19 21 04 57](https://cloud.githubusercontent.com/assets/11021683/6281275/44678cee-b87b-11e4-98b3-d6fca5dba56f.png)

**Comment by j0k3r** [comment]
This something we will implement in the v2, for sure. That won't appear in the 1.9.x I guess.

**Comment by gadjou** [comment]
A better and quicker way would be to be able to expand the "tags" node on the left to list the existing tags, and let the user drag and drop an article on a given tab to tag it.

**Comment by matclab** [comment]
Is this really closed ?
I dn't see a way to do it on wallabag.it…

**Comment by j0k3r** [comment]
It's on the left navigation, you have an entry to add a tag.

**Comment by matclab** [comment]
@j0k3r , thanks for the help, but I'm sorry, I cannot see the tag entry. If i want to add a tag I have to go inside each article and the, on the left navigation I have an entry to add the tag.
However, after an import, I have 1650 articles to tag and it quickly becomes impossible to do it.

#2246 was closed as being a duplicate of this ticket, buit both of them ask for a mean to bulk add tags to article, which do not seem possible to me.

However, after some more searching, I found that #3118 encompass the feature. So it is of for this bug to be closed. Sorry for the noise
