### ISSUE TITLE
Adding automatic articles tags support

### ISSUE THREAD

**Issue by misterair** [wallabag/wallabag#1111]
Add automatic support tags recovering with those present in the article (via specific div? Rel attribute?)

**Comment by tcitworld** [comment]
There's also the solution of parsing the page, searching for keywords. Some ideas here : http://stackoverflow.com/a/1575345

**Comment by tcitworld** [comment]
See Prismatic and their [API](http://blog.getprismatic.com/interest-graph-api/) [(FAQ)](https://github.com/Prismatic/interest-graph)

**Comment by j0k3r** [comment]
This could be closed in favor to https://github.com/wallabag/wallabag/issues/719
