### ISSUE TITLE
Error while exporting to pdf.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1113]
I got this error while exporting to a pdf:
![tcpdf error](https://cloud.githubusercontent.com/assets/11021683/6306803/bad9c220-b8f3-11e4-8a89-dcaa8a5125e3.png)

**Comment by mathwhiz1212** [comment]
Sorry entirely a permissions issue I just ran  sudo chown -hR www-data wallabag
and it's fixed now (wallabag is my install directory.)

**Comment by tcitworld** [comment]
I was writing a long explanation text. :'(

**Comment by mathwhiz1212** [comment]
Sorry. Once I have it working it's really cool except for the first page is taken up by made with tcpdf and wallabag or something like that. :)

**Comment by tcitworld** [comment]
Yeah, well, we needed a coved, I put the simplest thing.

**Comment by mathwhiz1212** [comment]
Makes sense.
