### ISSUE TITLE
Erreur à l'installation

### ISSUE THREAD

**Issue by sashavonbadass** [wallabag/wallabag#1114]
Erreur après la finalisation de l'installation sur mutualisé:
`Fatal error: Call to a member function prepare() on a non-object in /home/xxxx/wallabag/install/install_functions.php on line 101`

Serveur: mutualisé (OVH)
Version de PHP:5_4
BDD: SQLite
Version de Wallabag: 1.9
Erreur au test de prérequis: RAS sauf Tidy.

**Comment by tcitworld** [comment]
Merci pour ton retour. « Après la finalisation de l'installation » signifie à quel moment ?

**Comment by tcitworld** [comment]
As-tu moyen de voir ce qui a été écrit dans MySQL avec par exemple PHPMyAdmin ?

**Comment by sashavonbadass** [comment]
C'est sur une base SQLite, je ne peux qu'avoir une seule base sur MySQL et
elle est déjà utilisée.

Le 20 février 2015 22:27, Thomas Citharel <notifications@github.com> a
écrit :

**Comment by tcitworld** [comment]
>  As-tu moyen de voir ce qui a été écrit dans MySQL avec par exemple PHPMyAdmin ?

J'avais mal lu, désolé. Tu peux répondre à la question précédente et refaire l'installation en vérifiant les droits sur les répertoires ?

**Comment by tcitworld** [comment]
Apparemment il pourrait avoir un problème avec certains hébergements mutualisés et la fonction realpath.

**Comment by ActionsFLE** [comment]
Bonjour,

Même problème également chez ovh mais sur une base MySQL. Aucune table n'est créée dans la bdd.

Je vais essayer de réinstaller la version précédente et de partir de cette installation pour faire la mise à jour.

**Comment by tcitworld** [comment]
Même erreur exactement ?

**Comment by ActionsFLE** [comment]
Oui exactement la même

**Comment by tcitworld** [comment]
Tous les champs sont-ils bien remplis manuellement à l'installation ? L'adresse du serveur ne devrait pas être localhost si c'est un hébergement mutualisé.

**Comment by ActionsFLE** [comment]
Oui, j'ai tout bien renseigné et j'ai vérifié ensuite dans le fichier config : il a bien été modifié.

Ce qui est étrange, c'est que j'ai également la même installation sur un autre site et que wallabag 1.9 fonctionne bien dessus... (update de la version précédente).

**Comment by tcitworld** [comment]
Sur un serveur différent, du coup ?

**Comment by ActionsFLE** [comment]
oui mais a priori les 2 serveurs sont en mysql5.1

**Comment by tcitworld** [comment]
Mouais. Je soupçonne vraiment l'hébergement mutualisé là. Il doit y avoir un problème de chemins.

**Comment by ActionsFLE** [comment]
Pour info, impossible de réinstaller la version précédente non plus... J'ai l'erreur suivante qui apparaît : 

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2019] Can't initialize character set utf8mb4 (path: /usr/share/mysql/charsets/)' in /home/xxxxx/www/wallabag/install/index.php:112 Stack trace: #0 /home/xxxxxxx/www/wallabag/install/index.php(112): PDO->__construct('mysql:host=mysq...', 'user', 'mdp', Array) #1 /home/xxxxxx/www/wallabag/check_setup.php(10): require('/home/xxxxxx/...') #2 /home/xxxxxx/www/wallabag/index.php(13): require('/home/xxxxxx/...') #3 {main} thrown in /home/xxxxxx/www/wallabag/install/index.php on line 112

**Comment by tcitworld** [comment]
Non, c'était une fonctionnalité non compatible avec les vieilles versions de MySQL, corrigé dans la 1.9 justement. A priori pas en relation.

**Comment by ActionsFLE** [comment]
Ok, le truc, c'est que ça marchait avant que j'essaye la mise à jour ;-)

Autre précision : j'ai commencé par mettre à jour mon installation de wallabag vers la version 1.9.1. La mise à jour a bien fonctionné mais dès que j'ai essayé d'ajouter un lien, j'ai une erreur qui est apparue.

J'ai donc tout désinstallé et réinstallé en repartant avec une version vide. Tout fonctionne jusqu'à ce que j'essaie d'ajouter un lien (par le bookmarklet ou directement via wallabag) et ça bloque tout.

L'erreur annoncée est :
Fatal error: Call to a member function getConfigValue() on a non-object in /home/actionsf/www/mybag/inc/poche/Language.class.php on line 37

J'étais obligée de quitter le navigateur/vider le cache. J'avais de nouveau accès à wallabag mais impossible d'ajouter un lien sans que l'erreur revienne :-( et le lien soit n'était pas enregistré soit vidé (Untitled text etc.).

J'ai donc de nouveau tout viré et tout réinstallé et là, je tombe maintenant sur l'erreur annoncée en haut.

**Comment by tcitworld** [comment]
La version 1.9.1 ? La version de développement ? Ce problème est peut-être normal, j'ai fait des modifications ce matin même.

Je regarde.

**Comment by tcitworld** [comment]
Le problème suggère que la table users_config n'a pas été remplie.

**Comment by ActionsFLE** [comment]
C'était avec la version 1.9.1, la table existait bien et le user était renseigné, il me semble.

Si j'essaye de créer les tables à la main, ça peut marcher ? Pas idéal mais bon...

**Comment by tcitworld** [comment]
Je ne suis pas au courant d'une version 1.9.1. La [dernière en date](https://www.wallabag.org/pages/download-wallabag.html) est 1.9.0. ;)

**Comment by ActionsFLE** [comment]
oups :-) c'est bien la 1.9.0

**Comment by tcitworld** [comment]
J'ai créé [une version alpha](https://github.com/wallabag/wallabag/releases/tag/1.9.1alpha1) pour voir si les changements que j'ai effectués depuis la dernière version changent certaines choses. Peux-tu l'essayer s'il te plait ?

**Comment by ActionsFLE** [comment]
J'ai cette erreur qui apparaît à l'installation : 

Errors during installation:

    SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: 'utf8mb4'

et ce que je coche la case "Use UTF-8 MB4" ou pas.

**Comment by tcitworld** [comment]
Oups, petit oubli de ma part, c'est corrigé. 
https://github.com/wallabag/wallabag/releases/tag/1.9.1alpha2

**Comment by ActionsFLE** [comment]
Nope :-( on revient à l'erreur de dépar de ce fil.

**Comment by ActionsFLE** [comment]
Pour info, je viens d'installer la version stable 1.9.0 sur un autre serveur avec une autre base mysql, en suivant la même procédure, et ça fonctionne sans problème... Va comprendre... ;-)

**Comment by tcitworld** [comment]
Il faut trouver les différences entre les deux serveurs. ;-)

**Comment by ActionsFLE** [comment]
Pour la dernière install qui a réussi 

Serveur : synology DSM 5.1
PHP 5.5
MySQL 5.5

Donc, au minimum, la version de MySQL est différente.

**Comment by tcitworld** [comment]
Le fait est que le PO essayait avec une base SQLite. Tu peux tenter cette méthode (sur le serveur qui ne marche pas) pour voir ce qu'il en est ?

**Comment by tcitworld** [comment]
Cela devrait éliminer le système de base de données comme suspect.

**Comment by ActionsFLE** [comment]
ok. Avec la version 1.9.0 "gd public" ?

**Comment by tcitworld** [comment]
A priori rien de changé, mais tu peux quand même prendre l'autre.

**Comment by ActionsFLE** [comment]
il y a toujours l'erreur après connexion. Par contre, la table "tags" se crée bien (2 champs : id et value).

Question-remarque : dans l'installateur, au moment de renseigner les infos pour la base de données, j'ai par défaut un identifiant et un mdp qui sont renseignés. Ils ne correspondent pas à mes logins de bdd. Par contre, ce sont des logins que j'utilise notamment pour Leed, installé sur le même serveur et la même bdd. Or, j'avais remarqué des interférences sur ces points entre Wallabag, Leed et Shaarli. Est-ce que ça peut venir de là ? Ou bien est-ce juste mon navigateur ?

**Comment by tcitworld** [comment]
Hmm. Ca semble être également commun avec #1121. Encore du boulot pour trouver le problème, j'imagine.

C'est le navigateur qui a enregistré tes informations et les sauvegarde puis les propose ici, oui.

**Comment by ActionsFLE** [comment]
Avec la version de développement, je suis de nouveau stoppée plus tôt avec cette erreur 
Errors during installation:     SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: 'utf8mb4'

**Comment by tcitworld** [comment]
La 2eme version alpha ?  J'ai dû me mélanger les pinceaux.

**Comment by ActionsFLE** [comment]
moi aussi ;-) donc j'ai testé la version wallabag-master, wallabag alpha2 (lien plus haut) et la version wallabag-dev.
Avec les 2 premières : erreur après connexion 
Avec la dernière : erreur au moment de l'installation

**Comment by tcitworld** [comment]
D'accord. Je suppose que tu obtiens : 
>  Fatal error: Call to a member function prepare() on a non-object in /home/xxxx/wallabag/install/install_functions.php on line 101

Pour l'installation

>  Fatal error: Call to a member function fetchAll() on a non-object in wallabag/inc/poche/Database.class.php on line 190

Pour la connexion

**Comment by ActionsFLE** [comment]
Ok résultats suivant mes tests : 
1- Avec la version dev, 
* en cochant "Use UTF-8 MB4" : après avoir cliqué sur "install wallabag", j'ai l'erreur
`Errors during installation:     SQLSTATE[HY000] [2019] Can't initialize character set utf8mb4 (path: /usr/share/mysql/charsets/)`
* sans cocher "Use UTF-8 MB4" : après avoir cliqué sur "install wallabag", j'ai l'erreur
`Errors during installation:     SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: 'utf8mb4'`

pour les 2 tests : aucune table bdd créée

2- Avec la version alpha 2
* sans cocher "Use ..." : après avoir validé sur la page login, j'ai une nouvelle page avec l'erreur 
`Fatal error: Call to a member function fetchAll() on a non-object in /home/actionsf/www/wallabag-1.9.1alpha2/inc/poche/Database.class.php on line 190`
mais la table tags est créée (mais vide)

3- Avec la version master, sans cocher "Use..."
`Fatal error: Call to a member function fetchAll() on a non-object in /home/actionsf/www/wallabag-master/inc/poche/Database.class.php on line 190`
avec création de la table "tags"

**Comment by tcitworld** [comment]
Merci pour ta patience. Je vais tenter de regler ça une bonne fois pour toutes. 
Et chercher pourquoi je n'arrive pas à reproduire ces situations.

**Comment by ActionsFLE** [comment]
ok :-) en espérant que ce ne soit pas moi qui me plante quelque part...

**Comment by tcitworld** [comment]
Oh non, il y a beaucoup trop de gens avec les mêmes problèmes, les statistiques montrent que nous avons quelque chose qui foire quelque part.

**Comment by peakwinter** [comment]
J'ai pu constater le même erreur avec `fetchAll()` dans les installations Wallabag d'arkOS. Par contre, il me semble que c'est seulement avec MySQL et pas SQLite3. Je ne sais pas si ça aide mais... :)

**Comment by tcitworld** [comment]
J'étais justement dessus, mais j'ai toujours du mal à avoir la même configuration pour reproduire le bug. Je vais tester ton image vagrant.

**Comment by peakwinter** [comment]
@tcitworld OK -- le bon est ici: https://amnl.mirror.arkos.io/resources/arkos-dev.box

**Comment by B1bl10** [comment]
Bonjour,
Je rencontre exactement le même problème que sashavonbadass. Je suis chez OVh avec un serveur mutualisé. L'installation s'est réalisée avec succès mais au moment de l'identification il y a le fameux problème fetchAll().
Je pense que le problème est du côté d'OVH.

**Comment by peakwinter** [comment]
Après avoir testé "Alpha 2", le problème est encore là mais un peu différent : 
```
Fatal error: Call to a member function fetchAll() on boolean in /srv/http/webapps/testbag/inc/poche/Database.class.php on line 381
```

**Comment by tcitworld** [comment]
Seems #1175 is the solution with Alpha2 and correct credentials.

@peakwinter : It's still alpha2, but I cheated, I added a commit since.

**Comment by tcitworld** [comment]
This is now fixed in dev branch. :)

@ActionsFLE Tu peux confirmer que j'ai résolu le problème en essayant [la beta 1](https://github.com/wallabag/wallabag/releases/tag/1.9.1beta1) ?

**Comment by ActionsFLE** [comment]
Ok, je teste demain :-)

**Comment by ActionsFLE** [comment]
Bonjour,

finalement je n'ai pu tester que ce soir. Tout fonctionne jusqu'à ce que j'essaye d'ajouter un lien (en utilisant la fonctionnalité "save a link" et non pas un bookmarklet ou plugin). Ca me met que le lien est ajouté mais quand je retourne sur la page d'accueil, j'obtiens cette erreur : 
Fatal error: Call to a member function getConfigValue() on a non-object in /home/actionsf/www/wallabag/inc/poche/Language.class.php on line 37
et ça bloque tout...

**Comment by ActionsFLE** [comment]
Je ne pense pas que ce soit lié mais je viens de découvrir que mon espace disque et ma bdd sont quasis pleins.

**Comment by tcitworld** [comment]
Ça se pourrait mais je pense que c'est autre chose, apparemment, une table (users_config) n'est pas créée ou est vide.
Je ne me suis pas encore mis à nouveau dedans. Merci du retour.

PS : Éventuellement, pense à vider les cookies à chaque réinstallation. Je viens d'y penser, le fait d'avoir les anciens pourrait avoir des effets indésirables que ça ne me surprendrait pas.

**Comment by ActionsFLE** [comment]
J'ai refait la manip en virant les cookies et en vidant ma bdd. Tout fonctionne bien tant que je ne cherche pas à ajouter un lien... Un peu gênant ;-)
Les tables suivantes ont été créées dans la bdd : config, entries, tags, tags_entries, users, users_config. 2 lignes de données dans la table users_config : pager et language bien associées à mon id user.

**Comment by tcitworld** [comment]
Alors, je viens de remarquer que les sessions ont des problèmes si le dossier (ou la partition) de fichiers temporaires dans lequel php écrit est plein (#1188), du coup y a peut-être un souci de ce côté là.

Pour en être sûr, il faudrait bien se déconnecter proprement (cliquer sur déconnection, éventuellement vider les connexions actives dans Firefox) puis se reconnecter. Ensuite, l'idéal serait de jeter un oeil aux fichiers de log pour voir s'il n'y a pas quelques *warning* qui apparaissent.

Si tu as du temps... ;)

**Comment by tcitworld** [comment]
La beta2 devrait résoudre le problème rencontré. J'espère que d'autres ne viendront pas. :)

**Comment by peakwinter** [comment]
Côté arkOS je retrouve encore les erreurs suivants après avoir sauvegardé un lien (avec base MariaDB):

    Warning: The first parameter of bindtextdomain must not be empty in /srv/http/webapps/testbag/inc/poche/Language.class.php on line 41
    Warning: Division by zero in /srv/http/webapps/testbag/inc/3rdparty/paginator.php on line 124
    Fatal error: Call to a member function fetchAll() on boolean in /srv/http/webapps/testbag/inc/poche/Database.class.php on line 381

SQLite3 marche parfaitement bien !

**Comment by tcitworld** [comment]
Merci ! C'est bien avec la dernière beta ça ?

**Comment by peakwinter** [comment]
Oui, effectivement

**Comment by Jukanox** [comment]
Hello,
Je reviens sur l'erreur du début, j'ai eu la même quand j'ai essayé d'installer la version 1.9.0 sur mon hébergment mutualisé. Je suis passé à la version 1.9.1 pour régler le soucis mais j'ai un autre message d'erreur qui apparait :  Warning: session_destroy() [function.session-destroy]: Trying to destroy uninitialized session in /datas/xxxx/wallabag/install/index.php on line 39

Quand j'essaie tout de même d'installer wallabag rien ne se passe, la page est simplement rechargée.

Serveur: mutualisé (Web4all)
Version de PHP: 5.3.29
BDD: MySQL
Version de Wallabag: 1.9.1
Erreur au test de prérequis: RAS sauf Tidy.

**Comment by romu70** [comment]
Bonjour,
Je me permets de m'incruster pour poser des questions à @ActionsFLE pour son installation sur Synology, car je rencontre quelques soucis :

* D'abord l'install me dit qu'il manque l'extension php_tidy, l'as tu installé, et si oui, comment ?
* Ensuite l'installation ne se passe pas bien, Wallabag me dit que le dossier cache n'est pas accessible en écriture, ok, mais il est où ce dossier ? et pour quel utilisateur doit-il être accessible ?

Merci.

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
