### ISSUE TITLE
"About" not translated into french in the menu ?

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#1116]
There seems to miss a translation for "About" in the menu.

I can't find any entry in the .po files reading "About".

My theme : baggy (but everything seems OK here).
![screenshot_2015-02-21-11-41-02](https://cloud.githubusercontent.com/assets/3419050/6313934/0cd14a5e-b9c5-11e4-99da-30d8ce463063.png)

**Comment by tcitworld** [comment]
Fixed in next release.
