### ISSUE TITLE
add site_config

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#1117]
Hello !
Quelques sites auquel j'ai pas le contenu et je présume qu'il faut rajouter un site_config
- Rue 89 (mobile)
- lecourrier.ch
- http://lapin-blanc.blogs.docteo.net/2015/01/20/lencadrement-doctoral-deviendrait-il-un-sujet-dactualite/
- Kokopelli Semence
- reflets.info
- http://giminik.developpez.com/articles/debian-gnu-linux/gravure-audio-ligne-commande/
- Scienceetavenir.fr
- https://www.linkedin.com/pulse/3-le%C3%A7ons-re%C3%A7ues-de-mes-ariane-dumont
- http://www.yosko.net/article33/snippet-06-javascript-capturer-des-raccourcis-clavier-utilises-par-votre-navigateur (PluxXML)
- http://www.captaineconomics.fr/-les-immigres-recemment-arrives-en-france-qui-sont-ils-insee
- http://pérotin.com/post/2009/06/09/SAV-Free-un-sketch-kafkaien
- https://www.spiil.org/guide-bonnes-pratiques-editeurs-de-presse-ligne
- http://www.hackersrepublic.org/culture-du-hacking/une-histoire-de-privileges
- http://herveleblouch.free.fr/vev/index.php/1001_trucs_pour_sauver_la_plan%C3%A8te

Voilà :)

**Comment by tcitworld** [comment]
Merci, y a du boulot là. :)

**Comment by tcitworld** [comment]
Rue 89 en mobile devrait rediriger automatiquement vers la version desktop lorsque wallabag vient la chercher. En tout cas, ça marche en version dev.

**Comment by tcitworld** [comment]
Les gens qui ont codé lecourrier.ch devraient être &@$%£* violemment, car le contenu vient intégralement en javascript et n'est pas accessible en téléchargeant le page (il n'y a rien d'ailleurs dans le cache Google), et leur référencement est d'ailleurs ridiculement nul. Déjà ils utilisent Drupal (sic) et en plus ce module de &@$%. Si quelqu'un veut perdre du temps en envoyant un mail leur expliquant le ridicule de leur situation...

Pas grand chose à faire ici.

**Comment by tcitworld** [comment]
Pareil pour Kokopelli Semence, ils sont bloqués avec des pratiques déjà mauvaises en 1995.

![](https://pbs.twimg.com/media/CJP5aXVWIAAYN47.png)

**Comment by tcitworld** [comment]
reflets.info marche très bien chez moi.

**Comment by tcitworld** [comment]
http://giminik.developpez.com/articles/debian-gnu-linux/gravure-audio-ligne-commande/ marche aussi.

**Comment by tcitworld** [comment]
http://www.sciencesetavenir.fr marche aussi.

**Comment by tcitworld** [comment]
Sur linkedin, le problème est qu'il y a plusieurs genre de contenu pour le même domaine. Nous avons encore besoin de trouver une solution pour ces cas.

**Comment by tcitworld** [comment]
Note pour moi-même, suis bloqué à http://pérotin.com/post/2009/06/09/SAV-Free-un-sketch-kafkaien

**Comment by tcitworld** [comment]
Bon, j'ai ouvert un ticket (#1235) pour ce site précis. Ça marche en utilisant http://xn--protin-bva.com/post/2009/06/09/SAV-Free-un-sketch-kafkaien

**Comment by tcitworld** [comment]
Le dernier site est pareil, besoin de JS, aller engueuler l'auteur. Sinon tout est traité.

**Comment by qwertygc** [comment]
Merci :-)

Tu me sauve la misr avec basta et cyrille borne :-)

**Comment by nicosomb** [comment]
> Sinon tout est traité.

Donc on peut fermer ?
