### ISSUE TITLE
Are all of the dependecies including those installed by composer under the MIT license as well?

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1118]
Are all of the dependecies including those installed by composer under the MIT license or a comparable open source license as well? If there is variations could someone give me a list of the licenses involved in the program. (Like MIT, GPLv2 etc.)

**Comment by tcitworld** [comment]
All that is installed by the vendor (Twig dependencies) package is MIT-licenced, except Twig itself which is BSD-3-Clause licenced [(see here)](https://github.com/wallabag/wallabag/blob/master/composer.lock).

There are also many libraries inside inc/3rdparty. I've seen AGPL, Apache, LGPL, GPL, BSD, etc.

**Comment by tcitworld** [comment]
I will make a page where we describe all what is used inside wallabag. And provide their licence.

**Comment by nicosomb** [comment]
Where ? Documentation or website if you want.

Le 21 février 2015 20:41:40 UTC+01:00, Thomas Citharel <notifications@github.com> a écrit :
>I will make a page where we describe all what is used inside wallabag.
>And provide their licence.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wallabag/wallabag/issues/1118#issuecomment-75388777

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tcitworld** [comment]
I think documentation is good. And it can be translated.

**Comment by nicosomb** [comment]
I don't think we have to list all our licences dependencies. If someone wants to have dependency license, it's easy to retrieve it.
