### ISSUE TITLE
Error in first log in

### ISSUE THREAD

**Issue by Dtrieb** [wallabag/wallabag#1121]
I get this error if i try log in
Fatal error: Call to a member function fetchAll() on a non-object in /homepages/34/d179600664/htdocs/wallabag/inc/poche/Database.class.php on line 190

**Comment by tcitworld** [comment]
Please tell us the database used.

**Comment by Dtrieb** [comment]
@define ('LANG', 'de_DE.utf8');

@define ('STORAGE', 'mysql'); # postgres, mysql or sqlite

@define ('STORAGE_SQLITE', ROOT . '/db/poche.sqlite'); # if you are using sqlite, where the database file is located

# only for postgres & mysql
@define ('STORAGE_SERVER', 'xxx');
@define ('STORAGE_DB', 'xxx');
@define ('STORAGE_USER', 'xxx');
@define ('STORAGE_PASSWORD', 'xxx');
@define ('MYSQL_USE_UTF8MB4', FALSE); //

**Comment by tcitworld** [comment]
Thanks. Can you use a tool like phpMyAdmin or the mysql console are see if the table `users` exists and look if there's any content in it ? Seems like the user was not created for some reason.

**Comment by Dtrieb** [comment]
There are only " ID" and " value" in.

**Comment by tcitworld** [comment]
Are you sure that's table `users` ? That's very, very odd. 
I recommend deleting all tables (entries, tags, tags_entries, users, users_config) or directly dropping the database, re-create it and reinstall.

**Comment by Dtrieb** [comment]
If I install it new did the database created automatically or have I put something in?

**Comment by tcitworld** [comment]
You have to create a database, but you don't need to put anything in it, the install script should handle all the rest.

This makes me realize documentation isn't up-to-date.

**Comment by Dtrieb** [comment]
I reinstall all but the same error!

**Comment by tcitworld** [comment]
Try selecting SQLite installation for the moment. At least we will know if that works.

But it's very strange, what you have in your database.

**Comment by Dtrieb** [comment]
My mySql works on Port 3306 can this be the problem?

**Comment by tcitworld** [comment]
Well, in that case it seems to me you've got to put on server address : myserver:3306

Oh, and be sure you are using wallabag version 1.9 also. I'm not sure if the website has been fully updated.

**Comment by Dtrieb** [comment]
Yes I used the last version 1.9.0. and try it it with myserver:3306 but no sucess!
So now I use SQLite.

**Comment by tcitworld** [comment]
Can you tell me your webserver and php/mysql versions so that I try to reproduce the bug with same config ?

**Comment by Dtrieb** [comment]
Host is 1und1.com/de
php Version: PHP 5.6
mysql version: MySQL5

**Comment by bruo** [comment]
I'm facing the same problem (i guess). This is on a debian (wheezy) box.

mysql 5.5.41
php 5.4.36
webserver: apache 2.2.22

I hope that helps to reproduce the bug

**Comment by tcitworld** [comment]
@bruo & @mathwhiz1212 Can you look with PHPMyAdmin or an other tool what you find in the users table ?
Still can't manage to reproduce the bug, even though I've made some changes. If someone is interested to see if this resolves the problem, please checkout dev branch.

**Comment by tcitworld** [comment]
Eventually, also post if other tables are filled or not.

**Comment by bruo** [comment]
Hi,

I'm sorry I should have done that too.

mysql> show tables;
| Tables_in_wallabag |
| tags               |

aaaand it's empty. so, installed failed. I'll test the dev branch later today and will tell you how it goes (maybe it fixes this bug).

**Comment by m42e** [comment]
I had the same issue, not providing the host and the user for the mysql database (I assumed the grey default values are used) and the installation told me everything is fine, but no tables were created at all.

**Comment by tcitworld** [comment]
@bruo & @mathwhiz1212 Did you do the same thing ? I think I got it thanks to @m42e.

**Comment by tcitworld** [comment]
I've created [an alpha version](https://github.com/wallabag/wallabag/releases/tag/1.9.1alpha1) to test if the changes made since last version have fixed this problem. Can you test it please ?

**Comment by bruo** [comment]
Tested 1.9.1 and it worked. This time all the tables were configured.

As @m42e said, the grey info on the install form has to be filled, i notice that on the generated config.inc.php when i tried the first time, but i only had the tags table created. 

Anyway, this works pretty good. Thanks!

**Comment by tcitworld** [comment]
Yeah, all the fields must be filled before validating. But since there's a bug with Firefox in that particular configuration (*required attribute for an input inside an ul/li list*), we can't force users to input those fields without some javascript.
Anyway, I've added some checks on the server side, and now the default values shown in the interface are used to connect to the database.
I didn't think the users would think that the values proposed with the *placeholder* attribute would be taken as actual values. I will add `ex : ` or `eg : ` before them.
