### ISSUE TITLE
See all tags while tagging

### ISSUE THREAD

**Issue by erixtekila** [wallabag/wallabag#1122]
In order to re-use previous tags, it'd be interesting to show them all in the tagging interface.

**Comment by tcitworld** [comment]
There is already autocomplete but that's a good idea.

**Comment by erixtekila** [comment]
IMHO it could be a mean to keep the number of tags short.

**Comment by tcitworld** [comment]
To avoid close duplicates, you mean ?

**Comment by erixtekila** [comment]
For example or mistyping.
You can also forget about the previous one you've created.

This could be a way to help the user.
I, for myself, have created a nomenclature, that mimic sub-categories.
For example, I use "tool/requirejs" and '"tool/browserify". But if later I try to add an article about bower, which needs a new tag, I may mistakenly create "tools/bower" 'cause it's a new one, and I don't get a clue about my past nomenclature… do you follow me ?

Anyhow, tags that could group other tags would be by far the best feature ! ;)
Than I would have create the tag group "tool" and add to it "requirejs", "browserify" and the likes.

**Comment by tcitworld** [comment]
I fully understand and I'm creating another issue to see if using group/parent tags is possible.

**Comment by erixtekila** [comment]
Marvellous !

**Comment by tcitworld** [comment]
Main issue is now OK. For the rest, follow at #1129.

**Comment by erixtekila** [comment]
@tcitworld Is this feature impleme,ted in version 2.0.4 ? I can't get it to work.

**Comment by j0k3r** [comment]
@erixtekila nope, this feature is still not on the v2.
v2.1 will introduce a better tag system.
