### ISSUE TITLE
[UX] Next, previous article

### ISSUE THREAD

**Issue by erixtekila** [wallabag/wallabag#1123]
A little button to browse to next | previous article would be really handy.

**Comment by Aypac** [comment]
Preferably three, one for "Mark read an next", just "Next" and just "Previous".
And best at the bottom, hovering (that they can be accessed all the time).

**Comment by tcitworld** [comment]
Should be nice now, I'll let you know when it's released. :)

**Comment by tcitworld** [comment]
@erixtekila @Aypac  Actually, I'm reopening, since I wanted your advice. Should left be set to previous article or next article (classified by date, as the list does).

**Comment by Aypac** [comment]
I could not really image a use-case where I would really care which article came up next. The exact behaviour could be specified in the settings (youngest unread, oldest unread, random, the next younger, the next older). Personally I would use the next older as default.
Another idea would be the fixed placement at 50% height on each side. Those should not mark as read though (could be used for pacing through the articles to find something interesting).

**Comment by erixtekila** [comment]
@tcitworld Left side usuallly means past history.

**Comment by tcitworld** [comment]
> @tcitworld Left side usuallly means past history.

In most cases, I would agree with you, but in that case, the list view displays articles from newest to oldest, so if I go to the left, I find a most recent article. So I'm kind of hesitating.

**Comment by erixtekila** [comment]
Good point @tcitworld ! Show the article in the reverse order from which they appear : so the latest, then !
