### ISSUE TITLE
Change URL of article

### ISSUE THREAD

**Issue by erixtekila** [wallabag/wallabag#1124]
While you provide a mean to refresh the current article, sometimes articles changes their URL.

**Comment by j0k3r** [comment]
Do you mean changing it manually, or from an action from the user? Like a refresh button or sth?

**Comment by tcitworld** [comment]
I think he means : change the article URL, and refresh it (you keep linked informations : notes, favorite, tags).
It's instead of refetching the new article and deleting the old one manually.

**Comment by erixtekila** [comment]
Exactly @tcitworld !
BTW, notes ? Can we add notes ? How ?

**Comment by j0k3r** [comment]
Then I assume we don't care if the user change the url to something completely different from the current url?

**Comment by tcitworld** [comment]
>  BTW, notes ? Can we add notes ? How ?
No, but we plan to.

> Then I assume we don't care if the user change the url to something completely different from the current url?

Hmm, well it shouldn't be an action you could do by accident.

**Comment by erixtekila** [comment]
Ah then, disregards https://github.com/wallabag/wallabag/issues/1130 then.

But, you're right, it could cause issues. Thinking twice, it could be a bad idea…
Or it'd need an URL checker to validate the change… PITA !

**Comment by nicosomb** [comment]
I never answered to this issue, but edit URL won't be a feature in wallabag. 
The URL is like an identifier in wallabag. 

If the article moved, please save it with the new URL.

**Comment by istenrot** [comment]
If you have tons of tags attached to an URL you'd like to migrate to new address copying tags manually is PITA as well.
