### ISSUE TITLE
Save Twitter favorites

### ISSUE THREAD

**Issue by erixtekila** [wallabag/wallabag#1127]
I wonder if it's be possible to use Twitter APIs to fetch favorites articles in wallabag.
That's be a great place for it…

**Comment by j0k3r** [comment]
I definitively love this idea. That would required some extra developement for sure.
Until we plan something on that, you can give a try to https://muna.io/

**Comment by erixtekila** [comment]
Waouh ! @j0k3r… muna is 15$/year to send an email with your twitters favs ?! 8-[
Twitter API requires just oauth authentification to access their API. What a pain !

There should also be a list of the  provided favs to check/uncheck them from importing.

**Comment by j0k3r** [comment]
Well, I won't discuss this here, but Muna isn't just an email with your favorite tweets :)

**Comment by tcitworld** [comment]
> There should also be a list of the provided favs to check/uncheck them from importing.

Hmm, if you do a manual import, yes, but I was thinking more in an automatic way.

**Comment by j0k3r** [comment]
This is something that will be automatic, for sure. User will manually mark them as read or deleted item they don't want.

**Comment by erixtekila** [comment]
Nice one @tcitworld and @j0k3r.

I'll check deeper in muna then…

**Comment by tcitworld** [comment]
> This is something that will be automatic, for sure. User will manually mark them as read or deleted item they don't want.

I was thinking to fetch already favorited tweets.

**Comment by erixtekila** [comment]
https://twitteroauth.com/ may help…

**Comment by tcitworld** [comment]
Yeah, I guess there's many PHP libraries doing the job.

**Comment by nicosomb** [comment]
@tcitworld @j0k3r is that a job for wallabag? I mean, we can use tools like django-th from @foxmask or IFTTT.

**Comment by j0k3r** [comment]
Pinboard supports that.
I'm personally using Zapier & f43.me to do that (twitter favorites => rss feed => f43.me => feedly).
But this can be done with external tools.

I'm +1 for closing.

**Comment by foxmask** [comment]
Curently TriggerHappy does not do anything When a someone set a tweet as "hart" . But that could be a request .
