### ISSUE TITLE
Baggy theme: no Icon for shaarli

### ISSUE THREAD

**Issue by ParoTheParrot** [wallabag/wallabag#1131]
For Shaarli instead of the icon only "*shaarli" is displayed:
![clipboard](https://cloud.githubusercontent.com/assets/5046600/6326138/d1864040-bb4e-11e4-8df5-6d25f87589a6.jpg)

**Comment by tcitworld** [comment]
Please clean browser cache (CTRL + F5) on the page and wallabag's cache (into config).

**Comment by ParoTheParrot** [comment]
It is already done - before I did this post.

**Comment by tcitworld** [comment]
Yeah, I've seen the code, and that's logical. Will fix that.

**Comment by tcitworld** [comment]
Ready for next release.
