### ISSUE TITLE
translation issue

### ISSUE THREAD

**Issue by ParoTheParrot** [wallabag/wallabag#1133]
wallabag/locale/de_DE.utf8/LC_MESSAGES/de_DE.utf8.po :
```
msgstr "zum artikel zurückkehren" 
```
-> 
```
msgstr "zum Artikel zurückkehren" 
```

**Comment by j0k3r** [comment]
You can manually edit the file in Github and submit a PR :)

https://github.com/wallabag/wallabag/edit/master/locale/de_DE.utf8/LC_MESSAGES/de_DE.utf8.po#L227
