### ISSUE TITLE
[feature] RSS feeds to choose from

### ISSUE THREAD

**Issue by erixtekila** [wallabag/wallabag#1134]
Hi,

Another great workflow, would be to be able to use selected numbers of RSS feeds.
On each new article, wallabag could create a notification for the user to permit adding it as unread or dismiss it.

**Comment by j0k3r** [comment]
IMHO this shouldn't be in Wallabag.
It's not a RSS Reader ..

**Comment by tcitworld** [comment]
We had the exact same discussion about this in another issue (trying to find which one) and we come to @j0k3r's conclusion.
Although a plugin to do just this work is possible.
