### ISSUE TITLE
Add the ability to edit URLs

### ISSUE THREAD

**Issue by zedascouves** [wallabag/wallabag#1136]
This is a feature request and not a bug.
It would be nice to have the ability to edit the URL of an article. For example, I've saved a link like:
"http://liquor.com/recipes/classic-bloody-mary/%20via%20DuckDuckGo%20for%20Android"
This is obviously wrong, so I'd like to edit the link to remove the wrong part. If it's already possible, I'm sorry, as I couldn't find it.

**Comment by j0k3r** [comment]
This doesn't exist atm but we already discuss it in https://github.com/wallabag/wallabag/issues/1124
