### ISSUE TITLE
Implement Piwik

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1137]
For Framabag, I think we should implement Piwik to have more data on our users. 

Do you think it can be a good idea or not?

**Comment by j0k3r** [comment]
Even if it's not for Framabag, we can handle few config parameters to be able to activate Piwik.

So people using Wallabag on their own will be able to have stats too (which won't be that interesting if only one guys use it .. ).

**Comment by tcitworld** [comment]
Isn't Piwik kind of big for what we're trying to get ?

Anyway, what kind of data are you interested in ?

**Comment by nicosomb** [comment]
piwik is used by all frama* services.

**Comment by tcitworld** [comment]
Yeah, I was responding to @j0k3r in particular.

**Comment by j0k3r** [comment]
Well, I was just following the idea of @nicosomb :)

For one guy that host its own wallabag instance, I don't see any value to have piwik.

**Comment by tcitworld** [comment]
Okay. :)
Well, some basic stats are still interesting, though, but no need for piwik for that.

**Comment by willdurand** [comment]
Maybe you could just document where to put the `<script>` tag in the `base.html.twig` template (or something similar). Or a config param that, if filled in, would enable the Piwik tag in a template.

**Comment by nicosomb** [comment]
> Or a config param that, if filled in, would enable the Piwik tag in a template.

That was my idea ;-)

**Comment by nicosomb** [comment]
@tcitworld what about adding this feature in next minor of 1.x? Framasoft needs analytics :-)

**Comment by tcitworld** [comment]
Oh, I guess we can do it easily. It's just a JS line to add, right ? Were should it be (login page, homepage) ?
You need also to inform users on that.

**Comment by nicosomb** [comment]
I can send a mail to our newsletter. 
And we can disable tracking here: https://framabag.org/nav/html/legals.html
Today, we are already tracked but only on framabag homepage.

**Comment by tcitworld** [comment]
>  Today, we are already tracked but only on framabag homepage. 

That's why I asked were should it be (login page, homepage) ? Unread articles ? Calls to save item function ?

**Comment by nicosomb** [comment]
> That's why I asked were should it be (login page, homepage) ?
On each instance (unread / read / favs / config) ... all the pages. 

>  Calls to save item function ?
Not necessary.

**Comment by willdurand** [comment]
Is there a banner (cf. http://cookiesdirective.com/) to inform users?

**Comment by nicosomb** [comment]
Oh not yet!

**Comment by nicosomb** [comment]
Not necessary: http://www.cnil.fr/pied-de-page/cookies-statistiques/

**Comment by tcitworld** [comment]
I don't understand what you want to tell with your link, @nicosomb.

**Comment by nicosomb** [comment]
I answered to @willdurand. And I forgot this link http://www.cnil.fr/fileadmin/documents/approfondir/dossier/internet/Configuration_piwik.pdf

> Ce guide vous explique comment configurer Piwik pour être en conformité avec les recommandations 
de la CNIL

**Comment by tcitworld** [comment]
Yeah, but they don't talk about having an "about tracking" page.

**Comment by tcitworld** [comment]
FYI : https://github.com/piwik/piwik-php-tracker

**Comment by j0k3r** [comment]
I think this is a better solution https://github.com/mnapoli/PiwikTwigExtension
