### ISSUE TITLE
Error when trying to save and now I can't even view articles.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1138]
I get this error: 
Fatal error: Call to a member function fetchAll() on a non-object in /var/www/wallabag/inc/poche/Database.class.php on line 190

**Comment by tcitworld** [comment]
Duplicate of  #1121.

**Comment by mathwhiz1212** [comment]
So... How do I fix this and is there any way to retrieve my data if there isn't a way to fix this.
Using MySQL

**Comment by tcitworld** [comment]
I didn't start yet to try and reproduce the problem, I'm not available at the moment. But I will find the problem, promise. :)

**Comment by mathwhiz1212** [comment]
Ok, I just realised how dependent on this I am :) and Thank you for you help.

**Comment by tcitworld** [comment]
You can use SQLite for now if you really need it. Or use Framabag. ;)

**Comment by mathwhiz1212** [comment]
Mainly I'm concerned that I might have done something that would make my files irrecoverable.

**Comment by tcitworld** [comment]
You can always access content via phpMyAdmin.

**Comment by mathwhiz1212** [comment]
btw my setup is Wallabag v.1.9, PHP 5.4.36, mysql Ver 14.14 running on a raspberry pi with raspbian.

**Comment by tcitworld** [comment]
Your MySQL version is quite... unusual. :p

**Comment by tcitworld** [comment]
It's the *Distrib* information we'll need. ;)
