### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by Pierrotd** [wallabag/wallabag#1139]
Je viens d'installer wallabag 1.9 sur mon serveur centos 7.
L'installation se passe bien mais après la page de login j'ai:
L'utilisation de « getPreventDefault() » est obsolète. Utiliser « defaultPrevented » à la place.

**Comment by tcitworld** [comment]
Etrange, c'est une erreur javascript et je n'en trouve pas dans le code. Sur que c'est lié à wallabag ?

**Comment by Pierrotd** [comment]
En faisant un 
grep getPreventDefault -R *
dans le répertoire wallabag.
Je trouve cette chaine de caractères dans:
docs/js/jquery-1.11.0.min.js et themes/_global/js/jquery-2.0.3.min.js

**Comment by tcitworld** [comment]
OK. On mettra jQuery à jour pour éventuellement éviter ça.

**Comment by tcitworld** [comment]
jQuery inside wallabag updated. The one inside the documentation will be removed (the documentation system has been changed).
