### ISSUE TITLE
Update documentation inside wallabag

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1141]

**Comment by nicosomb** [comment]
Done.

**Comment by tcitworld** [comment]
@nicosomb, can you redo it please ? It needs to be re-done since I've lost the commits with the Gitlab sync problem and I don't know how to do it, I get https://github.com/wallabag/documentation/issues/65

**Comment by tcitworld** [comment]
Is there a way doc could be done with a submodule, btw ?
