### ISSUE TITLE
How to send an article from an external software? api?

### ISSUE THREAD

**Issue by fguillot** [wallabag/wallabag#1147]
Hi,

I would like to add a connector for Wallabag to [Miniflux](https://github.com/miniflux/miniflux), a minimalist open source RSS reader.

I didn't found any documentation about that. How to send a link to Wallabag? do you have any api or an example of http request?

Thanks.

**Comment by nicosomb** [comment]
Hello Fred :-) !

You just have to create a link like this: `http://yourwallabag/?action=add&amp;url=http://theUrlToWallabagEncodedInBase64`.

The API will be available in wallabag v2 (already here in very alpha version http://v2.wallabag.org/api/doc) 
I need to write a tutorial about this API. 

Regards, 

Nicolas

**Comment by fguillot** [comment]
Je voudrais ajouter le lien côté serveur en php et apparement l'authentification est obligatoire.

J'ai fais quelques tests avec curl en ligne de commande mais sans succès :

```bash
curl -v "http://wallabag:wallabag@127.0.0.1:8000/?action=add&url=aHR0cDovL2xpbnV4ZnIub3JnL25ld3Mvc2VjdXJlZHRleHQtbGVzLXNtcy1ldC1tbXMtY2hpZmZyZXMtc3VyLWFuZHJvaWQtY2Utbi1lc3QtcGFzLWZpbmk="
```

J'obtiens une redirection 302 comme réponse (vers le référant d'après le code). L'authentification à l'air de marcher mais ça ajoute pas le lien.

Ça pourrait probablement fonctionner avec 2 requêtes HTTP, une pour s'authentifier et une autre pour ajouter l'article. Mais il y a pas moyen de le faire avec un seul call http ?

**Comment by tcitworld** [comment]
> J'obtiens une redirection 302 comme réponse (vers le référant d'après le code). L'authentification à l'air de marcher mais ça ajoute pas le lien.

Regarde peut-être le log de wallabag à `cache/log.txt`, activable dans `inc/poche/config.inc.php`, ça aidera peut-être.
Si cela peut aider, je me souviens d'un problème où le lien n'est pas ajouté lorsque l'authentification n'est pas réussie du premier coup.

Mais de toute manière, toute la partie authentification de wallabag est cause d'un certain nombre de problèmes, du coup je suis bien content que la v2 arrive et mette tout ça au propre.

**Comment by tcitworld** [comment]
Going for v2 with this, check out the API.
