### ISSUE TITLE
[v2] When you change your username, you can't login

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1149]
I changed my username, and now I can't login.

**Comment by nicosomb** [comment]
I restored my username in the database, all is fine. In fact, there is a problem because we encrypt the password with username ..

**Comment by j0k3r** [comment]
Do we have to avoid user to change its username then?

**Comment by j0k3r** [comment]
Or maybe we can simply ask the user to give their current password to validate the username change. Then we can easily rebuild the hash. What do you think?

**Comment by nicosomb** [comment]
> Or maybe we can simply ask the user to give their current password to validate the username change. Then we can easily rebuild the hash. What do you think?

:+1:
