### ISSUE TITLE
Random feature must fetch an article in current status

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1153]
I was trying random feature, and I got an old and read article. 
This feature is here to save my time ("I don't know what I can I read ... Random reading!"), but if I have to read a read article ... ;-) 

The best: this feature takes care of the status where we are (on favorite articles, random feature only fetches in featured articles).

**Comment by tcitworld** [comment]
I think I had modified this, but maybe it's only in dev branch.
