### ISSUE TITLE
Password is cached only for a very short time

### ISSUE THREAD

**Issue by brabalan** [wallabag/wallabag#1156]
It seems that wallabag forgets my password very quickly (I have never seen it remembered for more than one hour), so I always need to enter it to change the status of articles or add new ones. I see this in Firefox on my laptop, in Safari on my iPad, and in the wallabag iOS app (when I use the sharing sheet to add an article).

**Comment by tcitworld** [comment]
Alas, this is a recurring bug in some versions on many installations (see #769), but we never focused on it totally and now that we're on building v2, I don't think it will be changed. :(
But hopefully it will work perfectly on v2 since it uses a whole different system.

**Comment by brabalan** [comment]
I understand. This gives me another reason to eagerly wait for v2 ;)

Feel free to close this (I'm not sure whether I should close it myself).
