### ISSUE TITLE
Solarized Dark theme issue

### ISSUE THREAD

**Issue by lightonflux** [wallabag/wallabag#1159]
There is a curly bracket for some reason. I guess it is not supposed to look like that:

![auswahl_093](https://cloud.githubusercontent.com/assets/1377943/6705580/8d19ebe0-cd56-11e4-84ce-b91a246edd9e.png)

**Comment by tcitworld** [comment]
I think I corrected it in dev version but I can't be sure. Will check.

**Comment by tcitworld** [comment]
Fixed. Also, the not displaying icons are now here.
