### ISSUE TITLE
If I install wallabag over my current wallabag like I am upgrading will it keep my data?

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1170]
If I install wallabag v1.9.0 over my current v1.9.0 installation like I am upgrading will it keep my data?
Continuation of https://github.com/wallabag/wallabag/issues/1138

**Comment by tcitworld** [comment]
Totally, as long as the database and the config.inc.php file is kept. But you should always backup anyway. ;-)

**Comment by mathwhiz1212** [comment]
Thanks :)
