### ISSUE TITLE
Connection time out during import

### ISSUE THREAD

**Issue by nblumoe** [wallabag/wallabag#1171]
I get time out errors when trying to import articles from pocket. Here is the error message from nginx `error.log`:

    2015/03/30 20:46:47 [error] 13588#0: *2 upstream timed out (110: Connection timed out) while
    reading response header from upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.xxx, request:
    "GET /?import HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxx.xxx.xxx", 
    referrer: "xxx.xxx.xxx/?import"

I tried tweaking some php5-fpm params, but no succes, I am not proficient with php at all. Any hints are appreciated.

**Comment by tcitworld** [comment]
I suggest playing on the `IMPORT_LIMIT` and `IMPORT_DELAY` constants at the bottom of the `inc/poche/config.inc.default.php`

**Comment by nblumoe** [comment]
Any recommendations for those values? Should I increase or decrease the default values? I am quite clueless here tbh.

**Comment by nblumoe** [comment]
I tinkered a bit with these values, but could not produce any different behaviour so far.

Also, I enabled debug mode and got this:

    2015/03/30 21:31:17 [error] 14136#0: *7 FastCGI sent in stderr: "PHP message: DEBUG POCHE : storage type mysql
    PHP message: DEBUG POCHE : display home view [...]
    2015/03/30 21:32:35 [error] 14135#0: *19 upstream timed out (110: Connection timed out) while reading response header from upstream

No other debug output between these two messages. I would have expected to see more, might be a hint about what is going on (or not).

**Comment by nblumoe** [comment]
This seems to have been an issue with a specific article. I did not investigate further why this did happen with that article but after removing it from the database the import continues with the other articles.

Thus I am closing the issue. Thanks for the help @tcitworld

**Comment by tcitworld** [comment]
Okay. :)
Just a question : were you able to get the article with your browser ? Maybe the article didn't exist anymore and it wasn't ignored (now I can't remember if it had should or not).
