### ISSUE TITLE
Trying to access wallabag for the first time on a fresh install.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1172]
Warning: require_once(/var/www/wallabag/inc/poche/../poche/config.inc.php): failed to open stream: No such file or directory in /var/www/wallabag/inc/poche/global.inc.php on line 52

Fatal error: require_once(): Failed opening required '/var/www/wallabag/inc/poche/../poche/config.inc.php' (include_path='/var/www/wallabag/inc/3rdparty/htmlpurifier:.:/usr/share/php:/usr/share/pear') in /var/www/wallabag/inc/poche/global.inc.php on line 52

Self-hosted, raspbian on a raspberry pi. no problems with the compatibility test, Permissions given through sudo chown -hR www-data folder, As far as I can tell this is regardless of browser as I have tried serveral.
mysql  Ver 14.14 Distrib 5.5.41, PHP 5.4.39

**Comment by tcitworld** [comment]
> Permissions given through sudo chown -hR www-data folder

Did you do it before installing ? You must copy the files, do the chown, then access your browser to launch the install.
