### ISSUE TITLE
Email sharing not functional with gmail

### ISSUE THREAD

**Issue by Linuxine** [wallabag/wallabag#1173]
Hi,

after updating my wallabag to the 1.9, maybe I have misconfigured something, but the "share by email" feature seems broken : when I click on the button, I get a new email, with the title of the article as a subject, but the content is strange (using gmail to handle the mailto links) : there is not link to the article, only the title of the article and/or his first lines.

For example, I have added this article : http://campus.lemonde.fr/campus/article/2015/04/01/le-canada-durcit-l-accueil-des-stagiaires-etrangers_4607268_4401467.html

When I click on the "email" button, the only content of the email is : 
"  Mauvaise nouvelle pour les jeunes Français à la recherche d'un  stage à l'étranger : la nouvelle réglementation du gouvernement  fédéral concernant les demandes d'EIC (Expérience internationale  Canada) aura «"
which is the beginning of the article, truncated.

I have not tried yet with another email provider or client.

**Comment by phofm** [comment]
I have the same problem with [this article](https://www.washingtonpost.com/news/to-your-health/wp/2015/08/11/the-most-depressing-statistic-imaginable-about-being-a-new-parent/?postshare=3441439336707008).

Looking into the generated E-Mail-Link the problem appears to be the ampersand (`&`, encoded with HTML entity `&amp;` but turned into an actual & in the email client). The ampersand in such an email link denotes the beginning of a new field (cf. `&body=`): 

```html
<a title="Email" class="tool email icon icon-mail" 
href="mailto:?subject=It turns […] of a partner
&amp;body=[…] parenthood is supposed to be among the&amp;<!-- This is the culprit -->nbsp;most 
joyous. [rest cut]"><span>Email</span></a>
```
I don’t have the time to look into the Wallabag code at the moment, but I could imagine something along the lines of 

```php
$article_snippet = urlencode($article_snippet);
/* or potentially use rawurlencode for compliance with RFC 3986 */
```
might solve the problem.

If I find some free time I will look into this.

**Comment by nicosomb** [comment]
Is that the same bug than #1273?

**Comment by phofm** [comment]
I can send the artice referenced in #1273 with the email link and get a new message with the title as subject and snippet and link in the body. So I would say no, not the same bug.

However, I did notice that some spaces get dropped that are there on the original page:
For example: 
> […] Windows 10.Vous […]
> […] bougé depuisWindows 7 […]
> […] gratuites etperformantes […]

But I can’t see whether and how that is related to this bug.

**Comment by nicosomb** [comment]
Fixed in v2 cause we only send article's title.
