### ISSUE TITLE
[v2] API: Remove the user property from the entries

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#1176]
I think we should **remove** the `user` property from the entries, because *it's creating a massive overhead.* For example, when I call `/api/entries.json`, I got the following results: 

- **2,72 MB** with `user`
- around 0,9 MB without `user` (estimated)

This JSON result just contains 15 entries, imagine this overhead with >100 entries :wink: 
Anyway, the property is senseless, because the entries are limited to the user/password combination, aren't they?

**Comment by j0k3r** [comment]
I agree with that. But it's currently *by default*: Doctrine loads related entities, we should try the lazy option on the relation between `entry` and `user`.

- http://doctrine-orm.readthedocs.org/en/latest/reference/annotations-reference.html#annref-manytoone
- https://github.com/wallabag/wallabag/blob/v2/src/Wallabag/CoreBundle/Entity/Entry.php#L117-120

**Comment by nicosomb** [comment]
Can I assign this issue to you, @j0k3r ? :-)

**Comment by j0k3r** [comment]
Just did :)

**Comment by j0k3r** [comment]
Just a follow up.
I've tried and the user property isn't that big, it only contains the id:

```
      1 =>
      array (
        'id' => 6,
        'title' => 'test title entry6',
        'url' => 'http://0.0.0.0',
        'is_archived' => true,
        'is_starred' => false,
        'content' => 'This is my content /o/',
        'created_at' => '2015-06-02T16:52:59+0200',
        'updated_at' => '2015-06-02T16:52:59+0200',
        'user' =>
        array (
          'id' => 1,
        ),
        'tags' =>
        array (
        ),
        '_links' =>
        array (
          'self' =>
          array (
            'href' => '/api/entries/6',
          ),
        ),
      ),
```

**Comment by jlnostr** [comment]
I created the issue 2 months ago - now the whole structure of the JSON changed (to a better way). 😊 

Therefore the issue can be closed now.

**Comment by j0k3r** [comment]
:+1: Thanks for the feedback!
