### ISSUE TITLE
Display hostname in full article view

### ISSUE THREAD

**Issue by numahell** [wallabag/wallabag#1177]
The full article view could display the hostname (blog.example.com, or rue89.nouvelobs.com, or anything.co.uk).
This could be usefull to display the media source of an article. 

Maybe the article list view could display it, but I have no preference. 

This issue is related to #981

**Comment by modos189** [comment]
The host name is displayed in the subject of Material Theme ( https://github.com/wallabag/wallabag/pull/1276 ). Maybe set material theme as default? =)

**Comment by nicosomb** [comment]
I will do that. Thank you.
