### ISSUE TITLE
Mozilla Reading List server support

### ISSUE THREAD

**Issue by jsit** [wallabag/wallabag#1178]
Mozilla has a reading list server that can be used with Firefox 38+:

https://github.com/mozilla-services/readinglist

It would be incredible if Wallabag could be set up to be used as a custom reading list server (available in Firefox's about:config under readinglist.server).

**Comment by tcitworld** [comment]
Thanks for the link, I was looking up for an API.

**Comment by nicosomb** [comment]
<3

**Comment by nicosomb** [comment]
As discussed on twitter with @julienw and @natim (see https://twitter.com/nicosomb/status/796738082045304832), we can close this issue.
