### ISSUE TITLE
Persistent sort order preference

### ISSUE THREAD

**Issue by DarwinAwardWinner** [wallabag/wallabag#1179]
It would be nice if there was a way to save a sort order as the default, or if Wallabag just remembered the last used sort order and used that the next time the page is loaded.

**Comment by j0k3r** [comment]
We can add this feature in the v2. We can put it in the configuration page so the order is defined by default for all lists.

**Comment by marriedgeek** [comment]
Yes, please! Thank you. This is the one thing keeping me from moving full-time to this from Pocket.

**Comment by he7d3r** [comment]
:+1:

**Comment by tcitworld** [comment]
Will need https://github.com/wallabag/wallabag/issues/2178 first.

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/issues/2178
