### ISSUE TITLE
unable to retrieve full-text content from www.it-connect.fr

### ISSUE THREAD

**Issue by SamR1** [wallabag/wallabag#1181]
Hello,

Wallabag can't retrieve content from it-connect.fr
example : http://www.it-connect.fr/debuter-avec-docker-et-les-containers-sous-debian-8/

![screenshot](https://lut.im/wHTqi3FO/s1kSifBq)

Version : 1.9.0

Thx.

**Comment by tcitworld** [comment]
Fixed in next release.
