### ISSUE TITLE
[v2] API wishes

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#1182]
Here are some wishes I'm currently having:

- Link to the preview picture in each post (related to #972)
- Access to the share links (shaarli, epub, etc.)

**Comment by tcitworld** [comment]
> Access to the share links (shaarli, epub, etc.)

epub can be hardcoded, it doesn't need an API. The best would be to have API requests for some specific server options.

**Comment by jlnostr** [comment]
Oh, didn't noticed that.
What do you mean with "specific server operations"?

**Comment by tcitworld** [comment]
For instance, obtaining shaarli/diaspora adresses or language used.

**Comment by jlnostr** [comment]
Thanks for the explanation :-)
I think all this information could be inside a `POST /api/user.format`/} request, which could contain the following things:

- shaarli/diaspora adresses
- the salt of the user
- the number of unread/favorite/archived items
- the full name
- the avatar image URL
- ...

**Comment by abeudin** [comment]
it's possible to add create users in api

**Comment by tcitworld** [comment]
There should be more user-oriented features in the future.

**Comment by freddyb** [comment]
Current documentation allows modifying tags. There is nothing to search for read/fav/archive or move between the other. Is this going to be solved using tags or are you going to have another attribute?

**Comment by tcitworld** [comment]
> There is nothing to search for read/fav/archive or move between the other.

I'm not sure what you mean here. [The documentation](http://v2.wallabag.org/api/doc/#patch--api-entries-{entry}.{_format}) shows a way to patch an entry to change its category. There's no way to search for an entry as for this first specification.

**Comment by nicosomb** [comment]
@jlnostr Can we close this issue? Thanks to the API, you have preview picture and as @tcitworld said, you can hardcode links to share plateforms.

**Comment by jlnostr** [comment]
Not sure. All of the requested things are resolved now. The only thing that's still missing is the download possibility for the files (EPUB, PDF, MOBI, etc.). I tried to hardcode them but then wallabag is redirecting me to the login page, submitting the oAuth token doesn't help. If you want I can create a new issue for this case :)

**Comment by j0k3r** [comment]
Yep, you can create a sperate issue for that :+1: 
In the mean time I'll then close that issue.
