### ISSUE TITLE
I don't see any icons.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1183]
I don't see any icons just this:
![screenshot from 2015-04-22 15 31 38](https://cloud.githubusercontent.com/assets/11021683/7285831/db8f5f84-e904-11e4-88ac-8c280cb1f1ea.png)
Wallabag v1.9.0 PHP 5.4.39 Mysql mysql  Ver 14.14 Distrib 5.5.43

**Comment by tcitworld** [comment]
This should be fixed by clearing both wallabag's and your browser's cache.

**Comment by mathwhiz1212** [comment]
I started out by clearing wallabag's cache and refreshing the page but neglected to clear my browser's cache. It's working now.
