### ISSUE TITLE
Unable to retrieve content for github.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1185]
I can't add any issues, download pages or anything on github to wallabag.
It either says Untitled and there is no content in it or it says unable to retrieve full text content.

**Comment by tcitworld** [comment]
The issue can be linked to this : https://github.com/sebsauvage/Shaarli/issues/94

**Comment by mathwhiz1212** [comment]
Also it may be of note that this does the same through the bookmark, browser extension or save a link in wallabag.

**Comment by tcitworld** [comment]
Of course, there's also the site config missing issue.
It will be tricky, though, to have issues *and* pages.

**Comment by tcitworld** [comment]
Discussion on #1198
