### ISSUE TITLE
unable to retrieve full-text content from bastamag.net

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#1186]
Impossible to save this page http://www.bastamag.net/Jose-Bove-L-ecologie-n-est-pas-un-supplement-d-ame-c-est-une-transformation

**Comment by lupinehorror** [comment]
this is happening to me too on various sites. slashdot for example.

**Comment by j0k3r** [comment]
@lupinehorror could you open an issue then? With an example?

**Comment by lupinehorror** [comment]
have created a new issue

https://github.com/wallabag/wallabag/issues/1205

thanks.

**Comment by tcitworld** [comment]
Fixed in next release.
