### ISSUE TITLE
Error after installation in IIS - "login failed: user doesn't exist"

### ISSUE THREAD

**Issue by ChrisDeChef** [wallabag/wallabag#1187]
- I copy all the files from the .zip file to my webfolder (IIS 8.0).
- The Webuser has read- and writepermissions for everything.
- At the installation wizard the server compatibility-test is successfull.
- Then I click on "Download vendor.zip"
- After the successfull install of Twig it doesn't matter if I choose MySQL or SQLite.
- It also doesn't matter if I change the username / password or not.
- After the installation is successfully done, it removes the install directory and redirects me to index.php

And then always the same error message appears:
login failed: user doesn't exist

No login form, no debug infos (with >> define ('DEBUG_POCHE', TRUE); <<), nothing.

My two test configurations:
Webserver: IIS 7.5 / IIS 8.0
PHP: 5.4.38 / 5.4.24
DEV-Tool: Notepad++ / WebMatrix
MySQL: 5.6.19 / 5.5.35

It also doesn't matter, which version of wallabag I'm trying to install - the error unfortunately stays the same from 1.5.0 to 1.9.1 Beta 1.

I don't know what I still could try to do... I'm totally baffled.

**Comment by tcitworld** [comment]
Hi,

> And then always the same error message appears:
> login failed: user doesn't exist

You don't even access the login form, the error comes right after installation, that's right ?

**Comment by tcitworld** [comment]
I think it's the fact that you're using IIS that's causing trouble. Can you try this : http://stackoverflow.com/a/12100180

**Comment by ChrisDeChef** [comment]
> You don't even access the login form, the error comes right after installation, that's right ?
You are right. I've never seen a login form.

After disabling "Anonymous Authentication" in IIS and Enabling "Basic Authentication" with a normal webuser everything works fine. Thanks.

**Comment by tcitworld** [comment]
Great ! :)
Will add this to documentation.
