### ISSUE TITLE
No warning at login when session can't be created

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1188]
I had a fully filled temporary partition disk and these errors came in the logs when trying to login. 

> PHP Warning:  Unknown: write failed: No space left on device (28) in Unknown on line 0, referer: http://localhost/wallabag/index.php

> PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on line 0, referer: http://localhost/wallabag/index.php

It was resolved when the temporary files were emptied, but it would be nice to show a warning message when it fails to login.

**Comment by nicosomb** [comment]
I close, because I think this bug won't happen with wllbg v2. Reopen it if necessary.
