### ISSUE TITLE
Incomplete article with self-hosted wallabag

### ISSUE THREAD

**Issue by andrey-str** [wallabag/wallabag#1189]
Hi, I have a problem with saving article with self-hosted wallabag. Framabag works good with it though — saves it completely.
Here are the urls: 
http://railstutorial.ru/chapters/4_0/beginning#top
http://railstutorial.ru/chapters/4_0/a-demo-app#top

Compatibility check has no warnings, so everything is green.

Host is ubuntu 14.04.LTS, on apache2

How can I fix this? Thanks!

**Comment by andrey-str** [comment]
Are you sure that this is site config issue? As I said Framabag's account saves article completely, so I thought(based on some threads here, on issue tracker) that this could be server configuration problem.

**Comment by tcitworld** [comment]
Yeah, it's just for me to remember.

**Comment by tcitworld** [comment]
OK, so I can confirm it works on my side on different versions, so as the article is rather long, I thing it's related to memory usage overload on your server. 

The apache error logs should help you to confirm this, and you may try to increase the number for the following line in your php.ini file : 
```
memory_limit
```

**Comment by andrey-str** [comment]
How much memory should I try to give for php scripts? Yesterday I tried to use 256M memory_limit instead of 128M, now just tried 512M -> no difference in saved length of the article.
Apache error log seems doesn’t contains any error messages. The latest message is about apache service restarting, nothing related to php/wallabag.

**Comment by tcitworld** [comment]
Not this much, I think I have far less, I guess something else is to be blamed. Maybe Apache itself. You can try to look into some other issues here meanwhile (search for timeout for instance). I will try to come with answers tonight.

**Comment by tcitworld** [comment]
As for errors, that's odd you have none. Maybe setting your error level to E_ALL will make them appear, but it would be surprising.

**Comment by andrey-str** [comment]
This is what I see in apache log after set LogLevel to “debug”:

Tue May 05 14:58:28.550335 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of Require all granted: granted, referer: http://railstutorial.ru/chapters/4_0/a-demo-app
[Tue May 05 14:58:28.550399 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of <RequireAny>: granted, referer: http://railstutorial.ru/chapters/4_0/a-demo-app
[Tue May 05 14:58:28.550672 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of Require all granted: granted, referer: http://railstutorial.ru/chapters/4_0/a-demo-app
[Tue May 05 14:58:28.550681 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of <RequireAny>: granted, referer: http://railstutorial.ru/chapters/4_0/a-demo-app
[Tue May 05 14:58:30.579904 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of Require all granted: granted, referer: http://railstutorial.ru/chapters/4_0/a-demo-app
[Tue May 05 14:58:30.579938 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of <RequireAny>: granted, referer: http://railstutorial.ru/chapters/4_0/a-demo-app
[Tue May 05 14:58:30.580082 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of Require all granted: granted, referer: http://railstutorial.ru/chapters/4_0/a-demo-app
[Tue May 05 14:58:30.580090 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of <RequireAny>: granted, referer: http://railstutorial.ru/chapters/4_0/a-demo-app
[Tue May 05 14:58:30.591853 2015] [deflate:debug] [pid 35623] mod_deflate.c(849): [client 5.149.209.152:51889] AH01384: Zlib: Compressed 10208 to 2502 : URL /wallabag/index.php, referer: http://railstutorial.ru/chapters/4_0/a-demo-app
[Tue May 05 14:58:33.673696 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of Require all granted: granted, referer: http://anse.me/wallabag/
[Tue May 05 14:58:33.673732 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of <RequireAny>: granted, referer: http://anse.me/wallabag/
[Tue May 05 14:58:33.673892 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of Require all granted: granted, referer: http://anse.me/wallabag/
[Tue May 05 14:58:33.673900 2015] [authz_core:debug] [pid 35623] mod_authz_core.c(802): [client 5.149.209.152:51889] AH01626: authorization result of <RequireAny>: granted, referer: http://anse.me/wallabag/
[Tue May 05 14:58:33.685245 2015] [deflate:debug] [pid 35623] mod_deflate.c(849): [client 5.149.209.152:51889] AH01384: Zlib: Compressed 10082 to 2447 : URL /wallabag/index.php, referer: http://anse.me/wallabag/ <http://anse.me/wallabag/>

These are(seems) started from running bookmark for saving article to wallabag and also accessing to “unread” pages also is shown here.
I can’t find anything criminal…

Also tried to direct php error logging to /var/log/php_error.log (not sure where it was by default), and it’s level is already set to E_ALL, but couldn’t even find php_error.log file after saving article.
Any hint where I can find old php logs? 

Thanks for help!

**Comment by tcitworld** [comment]
> Any hint where I can find old php logs?

Default PHP logs are outputted in apache logs.

Have you tried to save your links with the bookmarklet or with the button on the menu from the interface ?

**Comment by andrey-str** [comment]
Today only with bookmarklet, but before I also tried “Save link” from the interface.

**Comment by tcitworld** [comment]
What database system do you use ? Is you hard drive full ?
Can you try this also : https://github.com/wallabag/wallabag/issues/833#issuecomment-55054924

**Comment by andrey-str** [comment]
sorry for late response: I use MySQL 5.5.41-0ubuntu0.14.04.1
With sqlite3 article is saved completely. So the problem somehow related to database setup.
Any idea how make it work with MySQL?

**Comment by tcitworld** [comment]
Maybe a timeout on the MySQL side, like the user had in my previous link. Don't think much can be done apart changing some configuration. Next major version has this part (database management) completely rewritten, so it shouldn't occur anymore.

**Comment by BennyKay** [comment]
Hey there!
I stumpled across this bug-report as I am experiencing the exact same behaviour: certain rather long articles are not fully saved.
I found the source of this issue in my case and would like to share this with you (knowing that the last message here is 4 months old...):
The 'content' column of the table 'entries' is just of type BLOB. Being of type it should be able to handle about 65KB (binary)-strings which is apparently not enough for some articles. Converting the column-type to MEDIUMBLOB resolved the issue for me - I can now save all the articles I want, even one article wallabags estimates 129 minutes of reading time... 
Maybe there's a better fix, especially as this one will break when the next update will come.

**Comment by tcitworld** [comment]
Thanks for the hint, we'll consider it for next versions.

**Comment by tcitworld** [comment]
The thing is, most of the time the server itself fails to process the content.

**Comment by j0k3r** [comment]
Both links are well parsed on v2.
