### ISSUE TITLE
API Feature request, modify posts to performe additional processing

### ISSUE THREAD

**Issue by octplane** [wallabag/wallabag#1191]
Hello,

I would like to do the following with wallabag:
- list all articles saved and unread
- manipulate their content (more exactly, scan for youtube/other video sites content, and download the video to the article archive, alter the content to reference the offline video, save back to the archive, maybe with an additional tag referencing the completed alteration)

Is this something that's current possible with stable or unstable version ? Would that kind of feature be interesting to add to the product (probably by setting apart the main and probably verboten "download the video from yt" as an external "module")?

**Comment by tcitworld** [comment]
I'm not sure to understand what you meant in your second proposition, but it will be possible with wallabag v2 through its API. It should be released in a few months.

**Comment by octplane** [comment]
Well, if this is going to be possible in v2, I'll wait for the v2 ! Thanks for the quick feedback.

**Comment by tcitworld** [comment]
You're welcome ! Please have a look at how our API will look like http://v2.wallabag.org/api/doc/

**Comment by octplane** [comment]
Are there any notion of "attachment" for article ? Or all external media are supposed to be stored somewhere else ? (I saw in the code the mention of downloaded "images" but I don't see any mention of that in the API, but maybe this is subtle...)

**Comment by tcitworld** [comment]
At first no. But we are currently rewriting the library for parsing and handling content from pages which will be able to handle more metadata and therefore provide them with the API. So it should come with the second upcoming major version, not the next one.

However, you still should get the interesting part of the content and from then, try to get external media by parsing content on your client side if you really need it. ;)
