### ISSUE TITLE
Installation error solution

### ISSUE THREAD

**Issue by gas** [wallabag/wallabag#1192]
Installation process is buggy.
I've moved *install/index.php* to *install.php* and *install/install_functions.php* to *install_functions.php*
Both files one folder up.
Then installation (dev-master) worked.

**Comment by tcitworld** [comment]
Can you be more precise on what problem you encountered ?

**Comment by gas** [comment]
install/index.php can't find path to twig, inc, themes folder.

**Comment by tcitworld** [comment]
Quite strange. What webserver are you using ? Any particular configuration ?

**Comment by gas** [comment]
Quite old: apache, php 5.4, mysql 5.0

**Comment by tcitworld** [comment]
Hmm, I suspect the installation method not to be php 5.4 compliant. Will have to check on that, thanks.

**Comment by nicosomb** [comment]
Can I close? it's not a wallabag v2 bug, and it won't be fixed in wllbg v1.
