### ISSUE TITLE
Import fails unexpectedly

### ISSUE THREAD

**Issue by OleVik** [wallabag/wallabag#1193]
When importing a structured bookmarks.html file exported by a browser (Maxthon, Chrome-derived), no links are imported in spite of an "Import finished." message. This was tested on a clean install of Wallabag 1.9.0, using Bitnami [Nginx Stack](https://bitnami.com/stack/nginx/) [1.6.2-1](https://bitnami.com/stack/nginx/README.txt) on Windows 7 64-bit.

I tried to import the following file: [Gist](https://gist.github.com/OleVik/262c59a4b515f1700679#file-bookmarks-example) (common NETSCAPE-Bookmark-file).

**Comment by tcitworld** [comment]
Import of Netscape-bookmarks-html is not yet supported. I'll try to deliver it with next minor version.

**Comment by tcitworld** [comment]
Supported with next version.
