### ISSUE TITLE
Generate a Wisemapping / Framindmap from tags

### ISSUE THREAD

**Issue by alchy58** [wallabag/wallabag#1194]
## English

It's possible to add tags on articles.
I could be nice to navigate through them using a mindmap.
Maybe it's possible to generate a .wxml so it can be imported into WiseMapping.
## Français

Les articles ajoutés à Wallabag peuvent être tagués.
J'adorerai pouvoir parcourir ces derniers de manière plus visuelle via une carte mentale.
Il devrait être possible de générer un fichier .wxml importable dans WiseMapping.

**Comment by nicosomb** [comment]
Hello. 
I will close this issue, because this feature, even if it could be a good idea, won't be implemented in core of wallabag.
