### ISSUE TITLE
cannot synchronize on ubuntu

### ISSUE THREAD

**Issue by opensas** [wallabag/wallabag#1195]
I've just created a free account on framabag

This is my url: 

I've installed wallabag for android, and I'm trying to configure it

My wallabag url: https://framabag.org/u/opensas/
my user id: opensas
Token: I'm entering my framabag password, but I guess that's not what is asking for

I click on synchronize, I get no errors, but no article is loaded.

Any ideas what I'm doing wrong? I guess there must be something worth documenting

**Comment by tcitworld** [comment]
Sorry for the mistake. The user_id is not your login name, but a number (usually 1). You need to look on the framabag config page and activate RSS feeds. This will also give you the token.

Yes, it's a completely ugly system, but it will be completely changed with next major version.

**Comment by opensas** [comment]
It's ok, I don't mind it's ugliness (not true, I do mind) but I think it should definitely be documented somewhere... the android app should tell you about it.

**Comment by tcitworld** [comment]
You're totally right. Need some time to do it.
