### ISSUE TITLE
Long chapter names produce malformed epub

### ISSUE THREAD

**Issue by kai11** [wallabag/wallabag#1196]
Some readers (android FB2reader) have troubles processing epub books created by wallabag if page names are long

Suggested fix:
https://github.com/wallabag/wallabag/blob/master/inc/poche/WallabagEBooks.class.php
-$book->addChapter($entry['title'], htmlspecialchars($entry['title']) . ".html", $chapter, true, EPub::EXTERNAL_REF_ADD);
 +$book->addChapter($entry['title'], sha1($entry['title']) . ".html", $chapter, true, EPub::EXTERNAL_REF_ADD);

**Comment by tcitworld** [comment]
with sha1, pages names are quite... not recognizable. Maybe crop filenames would be better ?

**Comment by kai11** [comment]
These page names are internal, I don't see them in android fbreader or in my ebook.
Also, I just found out sha1 don't work for pages with identical <title> but different content 
For example, 3 pages of http://www.linuxjournal.com/content/linux-containers-and-future-cloud
They were saved as one article in my book.

So trimming + unique ID (=article index?) is probably better choice then sha1.

**Comment by tcitworld** [comment]
Why not..

**Comment by nicosomb** [comment]
Does this issue affect only v1?
