### ISSUE TITLE
github blobs: "unable to retrieve full-text content"

### ISSUE THREAD

**Issue by JulienPalard** [wallabag/wallabag#1198]
o/

This one: https://github.com/mackyle/sqlite/blob/3cf493d4018042c70a4db733dd38f96896cd825f/src/os.h#L52 resulted in a "unable to retrieve full-text content".

**Comment by j0k3r** [comment]
What content would you like to be readable here?

This once https://raw.githubusercontent.com/mackyle/sqlite/3cf493d4018042c70a4db733dd38f96896cd825f/src/os.h ?

**Comment by JulienPalard** [comment]
Why not :)

**Comment by tcitworld** [comment]
This will need more than a specific rule. The `//tbody` XPath rule seems to apply to the situation, however not all pages on the github.com domain are showing source code files. So I guess it's better to have something hardcoded and directly redirect to the content @j0k3r showed.

**Comment by nicosomb** [comment]
It works with v2.wallabag.org.
