### ISSUE TITLE
Epub generation is slow

### ISSUE THREAD

**Issue by kai11** [wallabag/wallabag#1199]
Wallabag had problem with epub generation.
Steps to reproduce:
1) setup wb 1.9.1 on Ubuntu server
2) add http://krebsonsecurity.com/2015/05/payivy-sells-your-online-accounts-via-paypal/
3) start epub generation
Book generation will be about 30 minutes or so.

**Comment by nicosomb** [comment]
Tested on wallabag v2, this bug doesn't appear.
