### ISSUE TITLE
Revues.org

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#1201]
Hello !
Dans revues.org, il y a des numéros pour indiquer le numéro de paragraphe, contenu dans <span class="paranumber">1</span>. Possibilité de les exclure dans wallabag ?

Cordialement,
Qwerty

**Comment by j0k3r** [comment]
Un exemple?

**Comment by qwertygc** [comment]
http://espacepolitique.revues.org/284

**Comment by tcitworld** [comment]
Fait ! Rendez-vous sur la prochaine version !

**Comment by qwertygc** [comment]
Merci :-)
