### ISSUE TITLE
Tags not being exported in Wallabag 1.9.0

### ISSUE THREAD

**Issue by th3bl4cksmith** [wallabag/wallabag#1203]
Moving from Framabag account to my server (both 1.9.0). Exported and imported JSON file but all tags were missing. Checked Framabag JSON, but nothing to indicate tags were exported. Added tags to local server instance, did an export and still found no tags. 

Seems like Wallabag doesn't currently export its own tags. Tried looking through docs and searching, but found nothing to confirm this.

**Comment by vpmalley** [comment]
Tags were indeed not exported at all. There is a pull request (#1207) for this, I hope you will be able to use the feature soon.

**Comment by tcitworld** [comment]
Fix merged, just a little duplication of tags problem due to #1209 to fix and it's good to go.
