### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabag#1204]
after trying three times to upload my 1.8MB `bookmarks.html` file, i got this error from Nginx on wallabag.org:

```
413 Request Entity Too Large

nginx/1.2.1
```

It seems that it still doesn't want my bookmarks, that thing (coming from #892). ;)

**Comment by tcitworld** [comment]
You need to change your server configuration. Can you try this ? http://cnedelcu.blogspot.fr/2013/09/nginx-error-413-request-entity-too-large.html?m=1

**Comment by anarcat** [comment]
i can't unfortunately, as i do not manage <del>wallabag.org</del> - i meant framabag.org, sorry.

**Comment by tcitworld** [comment]
Oh, OK, then ping @nicosomb.

**Comment by tcitworld** [comment]
@anarcat The server admin has raised the size limit to 4M, can you test how it goes now ?

**Comment by anarcat** [comment]
it works: "× Import finished." but i don't see any links in the archive. maybe this is #892 that is still not fixed :/

**Comment by tcitworld** [comment]
> it works: "× Import finished." but i don't see any links in the archive. maybe this is #892 that is still not fixed :/

My bad, I didn't noticed you were trying to import bookmarks. The issue is indeed fixed, but only in the dev branch and the last beta version, so Framabag doesn't have this right now.

**Comment by anarcat** [comment]
okay, any idea on when it will propagate?

**Comment by tcitworld** [comment]
As soon as possible. ;)
Version 1.9.1 is ready, except just a old nasty bug with some MySQL installations that I can't reproduce occurs and I don't manage to fix it. So maybe I'll release it anyway.

**Comment by anarcat** [comment]
okay - it'd be great if you could let me know here! :) thanks
