### ISSUE TITLE
error loading feed when synchronizing

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#1212]
When I entered an invalid wallabag url from the settings on my android, I got the error : 
error loading feed .
Got invalid response 
followed by the html source code of the main page of https://framabag.org/
I mean the app does not display the home page but (i insist) the HTML source code.

The reason is that I forgot to fill the /u/username after https://framabag.org/

I tested to put https://framabag.org/u/foobarfoobar but when I save setting I get 404 
So when we put https://framabag.org/ instead, as it's not a 404 error, later when synchronizing we face that issue.

May be we can handle a clearer error to avoid to make us confused ;)

**Comment by tcitworld** [comment]
Posted the error at https://github.com/wallabag/android-app/issues/82, since it concerns more the android-app itself. I close here.
