### ISSUE TITLE
Non-ASCII characters from locale files are shown as "?"

### ISSUE THREAD

**Issue by ptar** [wallabag/wallabag#1215]
After a normal installation with a MySql DB resulting in a working Wallabag, switching to a German or French locale renders non ASCII characters like German Umlauts only as question marks "?".
Articles and the locale files are okay, but some configuration seems to be broken.
Does someone know where to fix it? TIA!

**Comment by tcitworld** [comment]
Depending on the browser you use, can you [follow these](https://support.google.com/news/answer/61689?hl=en) instructions ? Can you tell us what encoding setting was used and if setting to UTF-8 fixed it ?

**Comment by ptar** [comment]
Thanks for the suggestion, but the issue is not browser-related:
The head of the config HTML page includes
<meta charset="utf-8">
and Firefox's page information says, the page is UTF-8 encoded.

But within the raw HTML, I can find e.g.
"Durch das Ausf?llen dieses Feldes: "
which is the translation I can find in the UTF-8-encoded file de_DE.utf8.po for:
msgid "By filling this field"
msgstr "Durch das Ausfüllen dieses Feldes"

The UTF-8 encoding seems to get lost somewhere between fetching the translated text and delivering the HTML page.

**Comment by tcitworld** [comment]
I was starting to think to a problem with the MySQL DB, but if you have issues even with the interface strings, this seems to be related to the gettext dependency.

Any particular server configuration you know about ?

**Comment by ptar** [comment]
No, not really. I had had a Wordpress installation on the same server, which had not problems.

You mentioned gettext and I found this hint:
http://www.guyrutenberg.com/2008/11/24/question-marks-instead-of-non-ascii-chars-when-using-gettext-in-php/
I seems to describe (and solve) the problem for another php application.
Could this be of use?

**Comment by tcitworld** [comment]
You can try the following : 
Edit file `inc/poche/Poche.class.php`
Add after the [line 637](https://github.com/wallabag/wallabag/blob/master/inc/poche/Poche.class.php#L637) what follows : 
```
bind_textdomain_codeset($language, 'UTF-8');
```
And reload (eventually logoff/login) to check if it fixes the issue.

**Comment by ptar** [comment]
YES!

That solved the issue!

Thanks a lot!

**Comment by ptar** [comment]
... that was **quick** :+1: ...

**Comment by tcitworld** [comment]
You're welcomed. It's strange we never heard of problems earlier though. If there's no side effects, I'll add this line for next release.

**Comment by ptar** [comment]
*Ups* - something happened, and I don't know what:
The problem re-appeared despite the fact, that the fix is still in `inc/poche/Poche.class.php`

It was definitely gone, but came back a few days ago. Today, I had time to check, if a replaced the fixed file with the original by accident, but I found the fix still in place. Yet not working...

Any idea?

**Comment by tcitworld** [comment]
Do clearing both wallabag's cache and your browser cache helps ?

**Comment by ptar** [comment]
Yes, thanks!
I cleared the wallabag cache by using the configuration page.
Then I logged off, closed the browser (Firefox) and logged in again.
I hope, it's not coming back again (via the cache?)

**Comment by tcitworld** [comment]
When it comes again, check which cache, when it's cleared, fixes it.

**Comment by ptar** [comment]
Hi tcitworld,
testing it for a few days: The problems comes up after a while and clearing the cache + log off + log in resolves it (again).
So there must be another codepoint dealing with the cache, which needs to be fixed to finally catch the bug.
TIA for finding and fixing it!

**Comment by tcitworld** [comment]
We're talking about the browser cache or wallabag's cache here ?

**Comment by ptar** [comment]
Solely the wallabag cache.
(BTW: The wallabag app shows the distorted characters as well.)

**Comment by tcitworld** [comment]
>  (BTW: The wallabag app shows the distorted characters as well.)

So it means it's really the wallabag cache which is concerned. Thanks.

**Comment by ptar** [comment]
Sorry, my fault: It's not the _app_, which is showing virtually nothing from the page but the arcticle content.
I meant I viewing the page on my mobile shows the same behavior.

Did another test on the mobile phone (with Firefox for Android)
- Go to my page an log in: Everything is fine
- Reload the page: The non-ascii characters are replaced by question marks
- Clear the cache of the Firefox app, unload the Firefox app
- Reload the page: The non-ascii characters are replaced by question marks

Now: 
- Clearing the Wallabag cache with FF on my PC (seeing broken non-asciis)
- Log off (while the non-asciis are still broken)
- Log in: Everything looks fine

On the mobile:
- Reload the page: The non-ascii characters are still broken
- Reloading the Firefox app + go to wallabag: The non-ascii characters are still broken
- Log off of wallabag
- Log in: Everything looks fine
- Reload the page: The non-ascii characters are broken, again

Seems to prove the problem concerns the Wallabag cache handling.

**Comment by tcitworld** [comment]
Yeah, no worries, that's what I understood.

**Comment by ptar** [comment]
Great :-)

**Comment by ptar** [comment]
Hello tcitworld,
today I managed to update to 1.9.1-b

The problem is still there, but only if the Wallabag cache is used.

Example with a German locale:
- Goto configuration, clear cache, logout (from this page or another)
- Login: On the page you see, the Non-ASCII characters (like e.g. German Umlaute) are okay
- Switch to another page (from unread to configuration or something) and switch back to the page where you started
- Now the Non-ASCII characters are replaced by question marks.

You can repeat the steps to reproduce the error.

(BTW: It doesn't matter, if the browser's cache is cleared or not)

Thanks for fixing this (too :-)

**Comment by tcitworld** [comment]
Will take a look. Thanks for explaining.

**Comment by tonn** [comment]
After update from 1.9.0 to 1.9.1 and moving mysql-db to another server I had a similar problem. "????" in titles only. https://i.imgur.com/XxPdDDF.png
I fixed it by changing this option to TRUE
@define ('MYSQL_USE_UTF8MB4', TRUE); // This should be false unless you know what it is

**Comment by ptar** [comment]
Hello tonn,
this bug is definitely related to the (wallabag) cache handling, since it vanishes with clearing the cache and it comes back when the cache is going to be filled and used again. (It's not related to the browser's cache, but for testing purposes, it might help to clear that to)
So please check if you can switch off/on your problem by clearing/using the wallabag cache (follow my comment from 27 Aug 2015)
Otherwise you might encounter (and workaround!) another problem.
Thanks!

**Comment by tonn** [comment]
I tried clear cache - without success.
May be you are right about another problem..
The problem can be related to my database. I have clear installation with old database restored from phpmyadmin-backup. I check in restored database (with phpmyadmin) and all title are showed correctly. I found solution with MYSQL_USE_UTF8MB4 but in previous installation this parameter was FALSE and all worked correctly.

**Comment by nicosomb** [comment]
Hello @tonn!

Can you try wallabag v2 please and tell us if problem persists?

**Comment by ptar** [comment]
Hello nicosomb,

I don't think, that tonn's problem is related to the (cache-)problem this issue is about.
Maybe you should open another issue to get both problems solved separatedly?

**Comment by nicosomb** [comment]
@ptar Do you have the encoding problem with v2?

**Comment by ptar** [comment]
I haven't tried, yet.
Alpha.1 was released on Jan. 8, Alpha.2 on Jan.22
Are you going to release an update in the next few days? If yes, I would wait to install that release (Alpha.3 or whatever).

**Comment by tcitworld** [comment]
The beta 1 is to be released tomorrow.

**Comment by ptar** [comment]
Great!
I'll try it ASAP and report the result.

**Comment by tcitworld** [comment]
Any news ?

**Comment by ptar** [comment]
Almost: 
I can't unpack the beta-archive on the server, so I have to upload the unpacked files.
I tried, but but had to stop the upload when I realized, that there are **almost 16000 files** to upload.

I will try again the other day!

_BTW: Does Wallabag really needs so many files or will there be another solution in the released version for those like me (with only FTP-access to the server)?_

**Comment by nicosomb** [comment]
> BTW: Does Wallabag really needs so many files or will there be another solution in the released version for those like me (with only FTP-access to the server)?

You can have a look here #1777

**Comment by nicosomb** [comment]
Any news @ptar?

**Comment by ptar** [comment]
Today, I tried to install wallabag 2 on a shared host in a subdirectory called /wallabag.
Since there is no install routine for that case, I uploaded more than 16000 files from the tar file.
Starting /wallabag/web/login, it seems to work, because I can login.
But: (At least) the css-files are not found, so it's impossible to use.

I'm wondering, that there is no **small PHP installation routine** which I can copy together with the tar.gz file into a subfolder. **It just has to expand the tar.gz, fix the current location and start the login.**
I found this small solution [https://forums.digitalpoint.com/threads/how-do-i-extract-a-tar-gz-file-using-ftp.807248/#post-7462963](url) which at least allows another try with just the upload of the tar.gz-file and calling that PHP-file to upack it.

Now, just please tell me **where to fix the location**, and I hope to be able to give you some news :-)
**Thanks!**
