### ISSUE TITLE
database port not managed

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#1218]
if the database is not running on its default port, nothing works (got blank page)

as PDO is used, the DSN string should use ";port="

eg
 
from inc/config.inc.php 

    @define ('STORAGE_PORT', '5433');

from inc/poche/Database.class.php

    $db_path = 'pgsql:host=' . STORAGE_SERVER . ';port=' . STORAGE_PORT . ';dbname=' . STORAGE_DB;

I could provide a patch but I think you will go faster than me to add the missing piece code everywhere 
its needed

**Comment by j0k3r** [comment]
Good catch, you can submit a patch.
There isn't so much place where you need to update the code, see https://github.com/wallabag/wallabag/search?utf8=%E2%9C%93&q=STORAGE_SERVER

**Comment by foxmask** [comment]
The install form need to be modified too. I'll try to submit something but i left PHP since a decade ;) (2012 in fact)

**Comment by j0k3r** [comment]
Good luck :ok_hand: :trollface:

**Comment by tcitworld** [comment]
Reminder for myself : make changes for MySQL AND Postgresql in the installation form.

**Comment by nicosomb** [comment]
Fixed with wallabag v2. https://github.com/wallabag/wallabag/blob/v2/app/config/parameters.yml.dist#L5
