### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by lightonflux** [wallabag/wallabag#1221]
http://n0where.net/understanding-systemd

Nice article, but wb is unable to archive it.:(

**Comment by Dual-Boot** [comment]
I have just tested it.
I can reproduce it with this message into wallabag : 
[unable to retrieve full-text content]...

**Comment by tcitworld** [comment]
Just a site config issue, no worries.

**Comment by tcitworld** [comment]
Works on dev version, without me knowing why.

**Comment by tcitworld** [comment]
Ok, I already fixed that 19 days ago.
