### ISSUE TITLE
recusive redirection with X-Forwarded-For set

### ISSUE THREAD

**Issue by pmaziere** [wallabag/wallabag#1222]
Hi,
I've just installed the random-spoofer-agent extension for firefox (the full feature github version), and it seems that when the 'spoof X-Forwarded-For' option is activated, wallabag recursively sends a 302 redirection to 'location: ?'
Disabling this option reenable the normal wallabag behavior.
I would guess this is related to how wallabag handle the header X-Forwarded-For, but it might as well be an issue with how the random-spoofer-agent extension deals with it, so I'll let "those who know" decide if this issue is relevant or not.

**Comment by tcitworld** [comment]
Confirmed. Not even able to login.

**Comment by nicosomb** [comment]
Hello @pmaziere!

Can you take time to test http://v2.wallabag.org and tell us if it works?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by pmaziere** [comment]
sorry for the late reply !
i've just tested it with a test/test account on  http://v2.wallabag.org and it seems to work fine

thanks

**Comment by j0k3r** [comment]
Thanks for letting us know that !
