### ISSUE TITLE
Unable to retrieve full-text content from bastamag.net

### ISSUE THREAD

**Issue by jmlrt** [wallabag/wallabag#1223]
Hello,

Wallabag can't retrieve full content from bastamag.net
I use version 1.9.0

example : http://www.bastamag.net/Encadrement-des-loyers-pourquoi-Anne-Hidalgo-ferait-bien-de-visiter-Vienne-l

![wallabag-bastamag](https://cloud.githubusercontent.com/assets/8582351/8276525/b83ab596-18b7-11e5-8b7e-7dc11a2f2994.png)

Thank you for your help

**Comment by tcitworld** [comment]
Fixed in dev version.
