### ISSUE TITLE
Siteconfig issue (will be edited to keep up status)

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1229]
Work to do : 
* http://www.reddit.com/r/LinuxActionShow/comments/1fccny/arch_linux_survival_guide/ Hard to deal with
*  https://news.ycombinator.com/news Mostly comments

Fixed: 

*  ~~https://gokulkrishh.github.io/Javascript-Guidelines/~~ fixed, still works with the blog
* ~~http://metrocop.net/mythic-comics/issue-1/~~ Fixed. Mostly pictures, but news still work.
* ~~http://blog.niqnutn.com/article35/steganographie-l-art-de-dissimuler-un-message~~ Fixed. The https certificate is not correct for this domaine, can't do much here for the https version.

**Comment by j0k3r** [comment]
I don't think we need to be able to save the whole page of HN.
But I think that reddit could be a good thing.
