### ISSUE TITLE
Show button for adding firefox social service only on secured connections

### ISSUE THREAD

**Issue by HeikoAdams** [wallabag/wallabag#1237]
Since Firefox allows adding a social service only on secured connections the button should only be visible on secured connections or there should be a hint notifying that the feature is only available on secured connections.

**Comment by tcitworld** [comment]
I didn't know about this. I works without https on my side.

I just found this phrase here : https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API/Manifest but it doesn't seem to enforce https.
> All URLs in the manifest should be HTTPS URLs

Will try to enforce it, though.

**Comment by HeikoAdams** [comment]
If I try to install the service via an unsecured connection there is an error in the browser console saying
> Activation failed: Error: attempt to activate provider over unsecured channel: [my-wallabag-url]
> TypeError: manifest is null

**Comment by tcitworld** [comment]
Funny, I don't get anything when trying locally. Will try on my remote server when it will be available again. Maybe it's also a security setting for Firefox on my side, don't know.

**Comment by tcitworld** [comment]
OK, I reproduce it now.

**Comment by tcitworld** [comment]
Done. :)
