### ISSUE TITLE
Tag article related to its estimated reading time

### ISSUE THREAD

**Issue by HeikoAdams** [wallabag/wallabag#1239]
Wallabag already estimates the reading time of the saved articles. So it would be cool if it could also automaticly assing tags like "shot", "mid" and "long" to articles related to the articles estimated reading time. This would make it possible to easily filter i.e. articles that have a short reading time and read them now while skipping mid and long reading articles.

**Comment by tcitworld** [comment]
They have been requests for searching by estimated time to read, do you think a tag's necessary ?

**Comment by HeikoAdams** [comment]
IMHO it would be any easier way to just show all article tagged with i.e. "short". Just 2 clicks ;-)

**Comment by tcitworld** [comment]
No problem. Will try something.

**Comment by nicosomb** [comment]
Automatic tagging was added in wallabag v2, thanks to @K-Phoen.
