### ISSUE TITLE
Adding via API does not succeed if logged out

### ISSUE THREAD

**Issue by freddyb** [wallabag/wallabag#1241]
When I am logged out, the API redirects me to the login form. I am expecting the login form to redirect me to the `?action=add`, but it does not happen.

Instead I see the normal login screen that shows my unread articles.

(This bug is related to #1147. Maybe it's just a duplicate, but my French is really bad :-))

**Comment by tcitworld** [comment]
Yup, I talked about this in the issue you're mentioning, but I never had the time to take a look at it. TODO list. ;)

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
