### ISSUE TITLE
Deleting user fails with PHP Fatal error

### ISSUE THREAD

**Issue by dev-zero** [wallabag/wallabag#1242]
When I try to delete the initially created *wallabag* user, I get the following in the PHP error log:

```
[15-Jul-2015 10:34:30 Europe/Zurich] PHP Fatal error:  Call to a member function fetchAll() on boolean in /var/www/myhost/htdocs/wallabag/inc/poche/Database.class.php on line 547
```

Installation was done as per documentation using `composer` using PHP-5.6 and PostgreSQL.

**Comment by tcitworld** [comment]
Maybe linked to  #1114. Strange.

**Comment by dev-zero** [comment]
how do I get the message logged in https://github.com/wallabag/wallabag/blob/master/inc/poche/Database.class.php#L237 ?

**Comment by dev-zero** [comment]
I guess that the query fails either because I'm using PostgreSQL or because there are no tags yet for that user.

**Comment by tcitworld** [comment]
> how do I get the message logged in https://github.com/wallabag/wallabag/blob/master/inc/poche/Database.class.php#L237 ?

wallabag's logs are available (after enabling DEBUG in `inc/poche/config.inc.php`) at `cache/log.txt`.

> I guess that the query fails either because I'm using PostgreSQL or because there are no tags yet for that user.

I think the same. But the query shouldn't fail, unless the tables don't exist. The error in that case [shows](https://github.com/wallabag/wallabag/blob/master/inc/poche/Database.class.php#L546) that `$query` is returning false for some reason.

Hope to reproduce all this.

**Comment by dev-zero** [comment]
this is what I get in the log:

```
2015/07/16_14:52:53 - 130.60.136.224 - storage type postgres
2015/07/16_14:52:53 - 130.60.136.224 - The configuration for user wallabag has been deleted !
2015/07/16_14:52:53 - 130.60.136.224 - execute query error : SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "Array"
```

**Comment by dev-zero** [comment]
and that user is now in a pretty inconsistent state: when I click on UNREAD or FAVORITES, I get a blank page again with the following log entries:

```
2015/07/16_15:00:35 - 130.60.136.224 - storage type postgres
2015/07/16_15:00:35 - 130.60.136.224 - execute query error : SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "OFFSET"
LINE 1: ...d=$1 AND is_read=$2 ORDER BY entries.id DESC LIMIT  OFFSET 0
```

**Comment by tcitworld** [comment]
The last error shows an issue with Postgresql specificities not considered inside the database functions. Should be easy to fix.

I *may* have fixed the first error. Will keep you updated.

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
