### ISSUE TITLE
Installation : wrong path to themes

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#1243]
With a fresh new wallabag install, the installation page does not have any CSS:

![bug-wallabag-2](https://cloud.githubusercontent.com/assets/3419050/8717135/9af7b724-2b98-11e5-81e8-96752af13933.png)

Here is the HTML source tag:
```HTML
<link rel="stylesheet" href="themes/baggy/css/ratatouille.css" media="all">
```
as we can also see on https://github.com/wallabag/wallabag/blob/dev/install/index.php.

However the themes directory is in the upper folder (the root folder). My guess is: all the link tags from *install/index.php* (and maybe other PHP files inside the installation folder) should point to *../themes[...]*.

**Comment by tcitworld** [comment]
You don't need to access install/index.php to go through the installation. Accessing index.php in the root folder should be enough. How does this goes for CSS ?
Will have to fix thing anyway, though.

**Comment by nicofrand** [comment]
Oops my bad, I should not try to do things in the morning !
