### ISSUE TITLE
file config: zataz.com

### ISSUE THREAD

**Issue by nIQnutn** [wallabag/wallabag#1249]
Bonjour,

J'ai un fichier de config pour zataz.com.
J'ai seulementun pb sur la date et l'auteur. J'en ai plusieurs liés dont ceux appartenant à "Articles connexes"
je voudrais //div[@class='gdl-blog-full']//div[@class='blog-date'] mais ça marche pas.

zataz.com

      title: //h1[@class ='blog-title']
      body: //div[@class='blog-content']
      date: //div[@class='blog-date']
      author: //div[@class='blog-author']
      test_url: http://www.zataz.com/90-des-dossiers-medicaux-des-coreens-du-sud-vendus-a-des-entreprises-privees/#axzz3h7mghxeQ

**Comment by j0k3r** [comment]
Without config file, the content looks great on the v2.
