### ISSUE TITLE
[v2] Not able to export in epub/pdf/mobi

### ISSUE THREAD

**Issue by woshilapin** [wallabag/wallabag#1255]
Based on #1254, I installed v2 of Wallabag.  At the moment, I'm unable to export in any of the following format pdf/epub/mobi.  My procedure is only to open an article in wallabag and click on the buttons to export.  I've checked the Firefox debugger "Network" but there is no error.  Same in my Apache logs.

On the same server, I also have a v1.8.1 which works perfectly well.

**Comment by tcitworld** [comment]
That's logic, ebook export is not here yet. ;)

**Comment by nicosomb** [comment]
I have to list the existing features in v2, sorry for that.

**Comment by woshilapin** [comment]
Ah, ok.  And I guess than my other bug report will get the same answer.  Feel free to close them then ;-)
