### ISSUE TITLE
[v2] Wallabag stay in English even when configured with other language

### ISSUE THREAD

**Issue by woshilapin** [wallabag/wallabag#1256]
Based on #1254, I installed v2 of Wallabag.  During the configuration, I've put 'fr_FR' as the language value but my wallabag is all in English.

Version of wallabag is the last commit on v2 branch (unless you've commited something in the last 3 hours).  Wallabag is exposed with Apache and PostgreSQL v9.1.16 on a VPS with Debian GNU/Linux 7 (wheezy) and PHP v5.4.41.

**Comment by nicosomb** [comment]
Same as #1255. 

I'll update #1049 with existing features.
