### ISSUE TITLE
pb recherche dans les tags avec caractère spéciaux.

### ISSUE THREAD

**Issue by nIQnutn** [wallabag/wallabag#1258]
Quand je veux taggé un article, je peux commencé la recherche en tapant le début du mot clé.
Exemple qui marche: si j'ai un tag "wallabg", il me suffit de taper "w" pour m'afficher wallabag et d'autres tag comprenant ce caractère.
Exemple qui ne marche pas:  si j'ai un tag "Économie", en tapant "É" ou "E" ou "e" le tag ne remonte pas. par contre je peux l'avoir en tapant "conomie" 

v     1.9.0

**Comment by nicosomb** [comment]
It affects only wallabag v1. Won't be fixed, we work only on wallabag v2.
