### ISSUE TITLE
Integrate freddyb/wallabag-fxos in wallabag organization

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1259]
Like the other projects (android / iOS, etc.), we could add wallabag-fxos by @freddyb into @wallabag organization. 

@tcitworld @j0k3r @freddyb: are you agree with that?

**Comment by tcitworld** [comment]
Of course

**Comment by j0k3r** [comment]
Agree

**Comment by nicosomb** [comment]
I mean, not a fork of what @freedyb does. I can add freddyb into our teammates.

**Comment by tcitworld** [comment]
I had forked https://github.com/wallabag/wallabag-fxos anyway.

**Comment by nicosomb** [comment]
I know, but it's easier for us if freddyb's work is available instantly.

**Comment by freddyb** [comment]
I'm happy to transfer repo ownership to the wallabag org. If you delete the fork, freddyb/wallabag-fxos will be gone and forward to wallabag/wallagab-fxos.I think I need to be a group member, to start the transfer though.I know, but it's easier for us if freddyb's work is available instantly. 

—Reply to this email directly or view it on GitHub.

  
    
    
  
  
Sent from my tiny mobile computer.

**Comment by nicosomb** [comment]
I just invited you in our organization and deleted the repo.

**Comment by freddyb** [comment]
Thanks. The transfer is done: https://github.com/wallabag/wallabag-fxos

(P.S.: Although it is called wallabag-fxos, it might also work on Android phones and tables if installed through Firefox for Android)

**Comment by nicosomb** [comment]
Welcome on board!

**Comment by freddyb** [comment]
Thanks!wallabag/wallabag schrieb:Welcome on board!

—Reply to this email directly or view it on GitHub.

  
    
    
  
  
Sent from my tiny mobile computer.
