### ISSUE TITLE
Wrong documentation URL

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#1263]
On the configuration page, the documentation URL (the ? in "There are several ways to save an article: (?)") is wrong : http://doc.wallabag.org/en/User_documentation/Save_your_first_article

See https://github.com/wallabag/wallabag/blob/c0cb52c07439c974075c302a190a034a8cce4f92/themes/default/config.twig#L9

**Comment by j0k3r** [comment]
There are already a PR about that #1251

**Comment by nicofrand** [comment]
Oops, I searched before but did not see it ! Excuse me

**Comment by j0k3r** [comment]
@nicofrand no problem, thanks for reporting the issue anyway
