### ISSUE TITLE
Unable to retrieve full-text content (dailylinuxnews.com)

### ISSUE THREAD

**Issue by icaroperseo** [wallabag/wallabag#1265]
Wallabag is unable to obtain the content of this page, I have dealt specifically with the following URL: http://www.dailylinuxnews.com/blog/2014/09/ubuntu-like-debian-font-rendering-using-infinality-font/

**Wallabag version:** 1.9.1 Beta 3

Thanks in advance!

**Comment by j0k3r** [comment]
No more DNS for that domain :confused:
