### ISSUE TITLE
Update documentation website

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1268]
1.9.1 is now available, and we have to update our documentation website (shortcuts, Firefox OS app, etc.).

**Comment by tgrosinger** [comment]
Does this include creating upgrade documentation? I just upgraded to 1.9.1 (successfully), but had a little trouble finding upgrade instructions. For example, the config file to copy over is buried away.

Thanks

**Comment by nicosomb** [comment]
All documentation is welcome on doc.wallabag.org. So if you want to add explanations on this website, let's go!

**Comment by nicosomb** [comment]
see #1495
