### ISSUE TITLE
still using the “fr_FR.utf8

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#1271]
- I have the 1.9.1 version but touched oldest version (all).
- I have a shared hosting (fennek.io, PHP Version 5.4.35-0+deb7u2)
PHP INFO : 
intl
Internationalization support	enabled
version 	1.1.0
ICU version 	4.8.1.1
ICU Data version 	4.8.1

Directive	Local Value	Master Value
intl.default_locale	no value	no value
intl.error_level	0	0

- SQLITE Storage
- no souci with wallabag_compatibility_test.php 

BUT i have the error message :  still using the “fr_FR.utf8 and the text is in english not translate (the bug affect also others languages!)

**Comment by tcitworld** [comment]
I think it's a cookie problem. Can you delete them and login again ?

**Comment by qwertygc** [comment]
Encore ce problème :/

**Comment by tcitworld** [comment]
> I have the 1.9.1 version but touched oldest version (all).

Tu peux m'expliquer ce que tu as voulu dire ainsi ?

Pour une upgrade réussie à coup sûr, il faut mieux copier les fichiers db/poche.sqlite et inc/poche/config.inc.php dans le dossier de la nouvelle version, supprimer le dossier install/ et enfin attribuer à ce dossier les bons droits (chown/chmod).

Si ça marche, tu passes en prod en modifiant le nom du dossier de la nouvelle version pour pointer sur la précédente.

**Comment by qwertygc** [comment]
J'avais ce problème dans les versions précédentes. J'ai fait ce que tu m'a dit et toujours ce problème. Pire, j'ai une page blanche :/

**Comment by qwertygc** [comment]
Bon, j'installe une version "neuve" de A à Z et voir si le problème se reproduit.

Bon, j'ai essayé, ça refait. Problème de configuration serveur ?

**Comment by tcitworld** [comment]
Le problème de changement de langue ? Ça y ressemble.

**Comment by qwertygc** [comment]
Yep. En sachant que mon hébergeur a des problèmes avec la fonction set_locale, je sais pas si y'a un rapport.

**Comment by tcitworld** [comment]
Tu peux modifier ton fichier de configuration php.ini ? As tu accès aux logs ?

Mettre ERROR_REPORTING à `E_ALL` dans inc/poche/config.inc.php (ou dans le php.ini) devrait logger toutes les erreurs. Par contre si tu n'as pas accès aux fichiers de logs (`/var/log/apache2`) il faut aussi mettre `display_errors` à true dans le php.ini pour pouvoir visualiser le problème.

**Comment by tcitworld** [comment]
wallabag [utilise bien](https://github.com/wallabag/wallabag/blob/master/inc/poche/Language.class.php#L40) la fonction set_locale() en effet.

**Comment by qwertygc** [comment]
Bon, alors ça vient de set_locale, j'ai un problème identique avec mes scripts. Faut pas chercher plus loin.

**Comment by tcitworld** [comment]
OK. Je vais voir pour expliciter l'erreur.

**Comment by nicosomb** [comment]
Is this bug still on wllbg v2? I close it, please reopen it if necessary.
