### ISSUE TITLE
Add a confirmation step before saving from Firefox Social API

### ISSUE THREAD

**Issue by Marsup** [wallabag/wallabag#1275]
Hi,

Firefox social API integration is great, but it kind of defeats the behavior that tool should have by default.

The share popup offers multiple services, upon which you choose the one you want to use, then you fill in some information if needed, and confirm the share. wallabag saves the page directly without asking for confirmation as soon as wallabag is the focused service, I don't think we want that.

Maybe the "save a link" popup should be shown instead, if that's technically possible, just an idea...

**Comment by tcitworld** [comment]
I can implement something like this. If it takes too long, it goes for v2.

**Comment by tcitworld** [comment]
Yeah, it implies quite much changes, so we've going with v2 for this.

**Comment by shtrom** [comment]
:+1:

**Comment by raf64flo** [comment]
Seems to depend #625 waiting for v2 implementation.

**Comment by nicosomb** [comment]
I think that we can close this issue https://www.fxsitecompat.com/en-CA/docs/2017/social-api-has-been-completely-removed/
