### ISSUE TITLE
Sessions do not last when switching networks

### ISSUE THREAD

**Issue by tgrosinger** [wallabag/wallabag#1277]
wallabag Version: Self-hosted 1.9.1
Apache Version: Apache/2.4.7 (Ubuntu)
Android App Version: latest

I have followed the steps on the documentation page to fix sessions. It is working great from a desktop which never changes networks. My phone on the other hand does not seem to be working as well.

Over the course of the last day it did not log me out at all while I remained in once place. When I left and switched from wifi to cell and then back to wifi it logged me out. Even when returning to the original wifi network I still had to log in again.

I am sharing articles from a news reader using the wallabag app which seems to just redirect to a browser (Chrome).

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
