### ISSUE TITLE
Notes about material theme

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1281]
* When I save 10 articles, I've got 4 lines: 3 articles on 1st line, 3 on 2nd one, only 1 on 3rd line and 3 on last lines (chrome and firefox)
* notifications when we star articles are buggy
* footer is available even if I'm not logged, so the "about" link can't be accessible. I think the footer on login screen should be different. 
* is the login form not too big? 
* on mobile view (<= 768px), I can't see toolbar on article view.
* There are some references of baggy in material theme. 
* `src/Wallabag/CoreBundle/Resources/views/base.html.twig` has to be updated
* Also, we wanted to add a preview of the article on homepage (with the first picture of the article, for example): can you try to see if it's possible to add a picture on each article (see #972).

**Comment by modos189** [comment]
About the show preview. There is a label with a link so that I can bring this label in the theme? I write on php, but very badly know your project is to add to parse the page and display a reference to the image on the page

**Comment by nicosomb** [comment]
I will have a look to the PHP code for having the preview of the article. You can just try to put a static picture for the moment.

**Comment by modos189** [comment]
>>footer is available even if I'm not logged, so the "about" link can't be accessible. I think the footer on login screen should be different.
>>is the login form not too big?
>>on mobile view (<= 768px), I can't see toolbar on article view.
fixed

**Comment by modos189** [comment]
i think, close
