### ISSUE TITLE
Some bugs with new Materiel theme

### ISSUE THREAD

**Issue by NumEricR** [wallabag/wallabag#1282]
Hi,
I've just check some pages of wallabag with this new theme and I noticed several tiny things.
Maybe some of them are not related to Materiel theme. I use Firefox and a Mac.

## 1
On [Save new entry page](http://v2.wallabag.org/new), the Save button has no specific CSS styles. Should it be displayed as "Save" when editing tags?
![wallabag_issue_1](https://cloud.githubusercontent.com/assets/262560/9073173/e3f7e202-3aff-11e5-8bf9-9c30cae3e2ff.png)

## 2
Has you can see is this next screenshot, search form is activated but I don't see any cross on right.
Cursor is changed when hovering this area but there is no icon. My cache has been cleared with no effect.
![wallabag_issue_2](https://cloud.githubusercontent.com/assets/262560/9073298/c2eb12cc-3b00-11e5-8a81-ad5a65d3734b.png)

## 3
If I click on the Hamburger menu icon, i get a strange display. By the way, this icon is displayed only after closing search form (See #1280)!
Next clicks are good I think: it hide/show menu on left. And I always get an overlay (or sort of) when main menu is also there.
![wallabag_issue_3](https://cloud.githubusercontent.com/assets/262560/9073659/1e307f76-3b03-11e5-9a0c-764e48956e74.png)

## 4
In an article page, we can edit title but the title attribute as a wrong value: "Edit tags".

## 5
- I think it should be better to display current category as title in main area: Unread, Favorites, ...
- And a title could be added on wallabag's logo to know this links goes to unread articles.

**Comment by modos189** [comment]
>I think it should be better to display current category as title in main area: Unread, Favorites, ...

I would like to do so, but is not found for this function in the program

**Comment by modos189** [comment]
1. Fixed
3. Fixed
4. Title replaced, but tags apparently defective in wallabag

**Comment by j0k3r** [comment]
@modos189 when you fix things on commit, could you add the number of the issue in the commit message, like `#1282`? it will helps us a lot. Thanks

**Comment by nicosomb** [comment]
@modos189 what about the 2 other issues? Do you need a specific issue for each one (and I close this issue) or you still comment here?

**Comment by modos189** [comment]
Github not display correctly sing comment. I wrote:

1 Fixed
3 Fixed
4 Title replaced, but tags apparently defective in wallabag

Yet issue is not necessary to close

**Comment by modos189** [comment]
please close
