### ISSUE TITLE
Better Support for RTL Languages

### ISSUE THREAD

**Issue by AmrEldib** [wallabag/wallabag#1285]
I'm not sure if wallabag can detect the language of the article or not, but if it can this opens the door for better support for Right-to-Left languages in two ways:
- [x] Display article in right-to-left orientation
- [ ] Use different font

What do you think?

**Comment by tcitworld** [comment]
> I'm not sure if wallabag can detect the language of the article or not

Currently it does not, but it shouldn't be difficult, since the libraries wallabag uses can try to guess it. And I think there's tools we can try.

**Comment by AmrEldib** [comment]
I think there's a way to do this using HTML and CSS only.
Setting [dir=auto](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) for the div can change direction based on the language used in the div. [More info on dir=auto](http://stackoverflow.com/a/6777228/463)
I'm looking for a way to use different font for different language. Here's a [jsFiddle for a quick demo](http://jsfiddle.net/AmrEldib/k9zy7p0u/).

**Comment by tcitworld** [comment]
Thanks for the doc. Will have a look.

**Comment by AmrEldib** [comment]
One way is to use a javascript library to detect the language, then apply a language selector with different fonts for each language (or family of languages).
Here's a javascript library for detecting languages: [guessLanguage.js](http://richtr.github.io/guessLanguage.js/)
The [lang attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) and [lang selector](https://developer.mozilla.org/en-US/docs/Web/CSS/%3Alang) are the other part of that.

**Comment by AmrEldib** [comment]
I've [updated the fiddle to demo](http://jsfiddle.net/AmrEldib/k9zy7p0u/) how the javascript library can be used. I hope this is helpful.

**Comment by Monirzadeh** [comment]
for now this PR #5599 solve this issue in web version.
if see any issue please report here.

**Comment by j0k3r** [comment]
I re-open because there is still the font problem.

**Comment by nicosomb** [comment]
Done in #5599
