### ISSUE TITLE
Read GET parameters in the themes

### ISSUE THREAD

**Issue by modos189** [wallabag/wallabag#1289]
I propose to add a function to obtain _GET request parameters.

Then, by sending a request http://myserver/unread/?ajax=true

With the code in base.html.twig

```
{% if ReadGET('ajax') == false %}
<html>
...
some description of the page
...
<div id = "content" class = "w600p">
{% endif %}

{% block content %}{% endblock %}

{% if ReadGET('ajax') == false %}
</ div>
...
</ html>
{% endif %}
```

This will allow the transfer of the key "ajax" only get content.

The same approach we use on our projects in the Atom-M CMS.

**Comment by j0k3r** [comment]
But why do you need this `ajax` parameter ?

**Comment by modos189** [comment]
It will go to a page without reloading the page by aJax technology and receive only the new code only

<div id = "content" class = "w600p">
</ div>

and the rest of the page updated by js

**Comment by j0k3r** [comment]
Well, even if the feature seems a great one, I don't think we need to use this kind of _getter_ to handle ajax pagination. This can be done without that.

**Comment by modos189** [comment]
If you can do it a different way so please tell me how
