### ISSUE TITLE
wallabag will use Pootle for translating

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1291]
Framasoft installed Pootle here: https://pootle.framasoft.org/
I will announce it on our blog and on github. 

This application is more useful to translate wallabag. For example: https://pootle.framasoft.org/it/wallabag/translate/#filter=incomplete

**Comment by tcitworld** [comment]
A lot of files don't have all the strings to be translated, we'll have to fix this.

**Comment by modos189** [comment]
Problems with displaying Cyrillic: icons instead of the issue of translation:
http://imgur.com/RwvUgfp

**Comment by ldidry** [comment]
Mysql database encoding shit. I'll try to convert it tonight.

**Comment by ldidry** [comment]
@tcitworld could you delete and re-upload the russian translation file please ?

**Comment by tcitworld** [comment]
I don't seem to have the rights to but @nicosomb has.

**Comment by ldidry** [comment]
Now you got the rights. (I will delete the rights just after that, I prefer if @nicosomb choose himself the rights to give to people)

**Comment by tcitworld** [comment]
My bad, I already had the rights (but I saw the difference, though). It seems to be fine now.

**Comment by ldidry** [comment]
\o/ (by the way: no, you didn't had the rights, I gave you admin rights on wallabag project). So, now, we know:

1. Mysql is shitty as always :wink: 
1. If there is this sort of problem, you have to delete and re-add the translation file

**Comment by nicosomb** [comment]
Note sure to use pootle for v2. pootle doesn't seem to be user friendly. Maybe github is enough for that.

**Comment by nicosomb** [comment]
We won't use pootle for v2.
