### ISSUE TITLE
Change "send" button on config page

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1299]
On config page, the button to valid the form is labelled "Send". I think we can have something better ("save", "validate", "ok", "save my preferences", etc.). 

@tcitworld @j0k3r an opinion?

**Comment by tcitworld** [comment]
Save sounds good to me.

**Comment by nicosomb** [comment]
just "save"? "save my preferences" sounds better to me, but "save" is shorter, it's good too.

**Comment by modos189** [comment]
i think
"Save" for 'Wallabag', 'RSS' and 'User information',
"Update" for 'Password',
"Add a user" for 'Add a user'

**Comment by nicosomb** [comment]
:+1: let's go.

**Comment by nicosomb** [comment]
Done.
