### ISSUE TITLE
What's in my bag this week?

### ISSUE THREAD

**Issue by packetgeek** [wallabag/wallabag#1300]
Thomas Citharel asked that I open an issue here to discuss a side project of mine...

I've added the ability to create a Blogger (or similar) post tracking recent articles that have been saved to Wallabag (even after they've been deleted from Wallabag).  Short version: I added 4 lines of code to the add function in Database.class.php.  When an article is added, the title and url are logged ot a new table called bag (id, title, url, user_id, timestamp).  

A separate script can: delete individual entries, delete all entries, view what the post will look like, and view the raw html for the post (which is what I copy and paste into Blogger).

Current shortcomings: script currently doesn't differentiate between users (I'm the only user on a local instance of Wallabag).

Wish list: posting directly to Blogger (or Wordpress), without having to copy and paste.

Example output is at: http://www.neighborhoodtechie.com/2015/08/whats-been-in-my-bag-this-week-20150808.html

**Comment by nicosomb** [comment]
What a nice feature. 
Maybe you can share your code on github to other wallabag users.

**Comment by packetgeek** [comment]
Apologies.  It's posted at https://github.com/packetgeek/wbimb

**Comment by j0k3r** [comment]
Your work will be a little bit easier with the v2 API :)
By the way, I don't see the point of creating an issue to showcase your side project (even if it's a cool one).

From my POV, what you need (in your wishlist) will be fixed once the v2 will be out. You will be able to use the API to get last content from Wallabag and then use the [Blogger API to post your blogpost](https://developers.google.com/blogger/docs/3.0/using#AddingAPost).

**Comment by tcitworld** [comment]
> By the way, I don't see the point of creating an issue to showcase your side project (even if it's a cool one).

I asked him to.

**Comment by j0k3r** [comment]
@tcitworld well, maybe a simple blogpost in the wallabag blog should be enough. I don't think a lot of people are reading issues here to discover wallabag side project :)

**Comment by packetgeek** [comment]
@j0k3r The Blogger API is still up?  Thought that they'd turned that off (saw comments to such and couldn't get the Oauth2 thing to work).  Thanks for the link, though.  Will take another look at that.
