### ISSUE TITLE
[v2] Maintain baggy for wallabag v2?

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1305]
For wallabag v2, we'll have material theme, thanks to @modos189. 
Today, baggy theme is finished in v2. 

@tcitworld @j0k3r and others too, do you think we have to work on this theme? 
I love it, but I think we'll loose time with it.

**Comment by tcitworld** [comment]
I've got used to it and I think most users are used to it too.

What do you expect to take time ?

**Comment by nicosomb** [comment]
We need to create all the twig files for v2.

**Comment by tcitworld** [comment]
Sure, but I don't see much problems we could encounter. Will have a look.
Who worked on *baggy* in the first place ?

**Comment by nicosomb** [comment]
It was @Courgette :-)

**Comment by tcitworld** [comment]
Well, we'll always be welcomed for help. ;-)

**Comment by j0k3r** [comment]
I think it's cool to have a new theme for the v2 but there are always people who don't really like change. So if we let them come back to the _old_ baggy theme for the v2, they will be really happy :)

So :+1:  to keep Baggy.

**Comment by courgette** [comment]
Hi, personnaly, i don't have time to maintain baggy now. But in October, i can get a few time to participate to projects Open source, so i can create a new theme for the v2 or if baggy already here, redesign it.

**Comment by tcitworld** [comment]
OK. Can I just ask you for help for JS or css stuff sometime ?

**Comment by courgette** [comment]
Yeah, of course

**Comment by nicosomb** [comment]
PR from @j0k3r #1401

**Comment by nicosomb** [comment]
Merged ... So we can close?
