### ISSUE TITLE
[v2] When the title of an article is edited, the article is marked as read

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1306]
tested on v2.wallabag.org

**Comment by nicosomb** [comment]
wow, nice feature :+1: :-D

**Comment by nicosomb** [comment]
Tests locally, the bug is not present.

**Comment by nicosomb** [comment]
Tested on v2.wallabag.org, the bug is not present.

**Comment by tcitworld** [comment]
Hmm, the third time it went well. That's odd.

**Comment by tcitworld** [comment]
Guess I must have misclicked.
