### ISSUE TITLE
Display progress bar at the top of the page?

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1308]
Like here http://www.slate.fr/story/105341/disparition-calotte-glaciaire-cartes-national-geographic, do you think the pink bar at the top of the page which grows when scrolling is a good idea for  `material` theme?

**Comment by tcitworld** [comment]
The idea of the progress one is a good one, and looking at the code, the way they've done it seems quite simple.

**Comment by modos189** [comment]
IMHO a browser progress bar enough

**Comment by tcitworld** [comment]
On mobile devices, those are often hidden since you use touchscreen to scroll, you don't need the browser scroll bar.

**Comment by modos189** [comment]
Well, persuaded =)

**Comment by nicosomb** [comment]
Opened PR https://github.com/wallabag/wallabag/pull/1348

**Comment by j0k3r** [comment]
Now in #1337

**Comment by nicosomb** [comment]
Fixed.
