### ISSUE TITLE
[v2] Redirect to the good URL after login

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1311]
If I click on a wallabag URL when I'm disconnected, I have to fill the login form. But then, I'm redirected to unread view. I want to be redirected to the good URL.

**Comment by tcitworld** [comment]
Do we need to pass parameters through the login phase ?

**Comment by nicosomb** [comment]
No, we have to redirect to referer.

**Comment by tcitworld** [comment]
Won't this show problems with those who use privacy-oriented extensions or have specific server configurations ?

**Comment by nicosomb** [comment]
I don't think, in wallabag v1 we do the same thing.

**Comment by tcitworld** [comment]
Yeah... And I've seen some issues for some people. And if you fail to connect on first try, you loose the referrer.

**Comment by nicosomb** [comment]
yes ... but symfony power.

**Comment by tcitworld** [comment]
I'm counting on you, sf. ;-)

**Comment by nicosomb** [comment]
Done. And if you fail, you don't loose the referer \o/

**Comment by tcitworld** [comment]
Awesome !
