### ISSUE TITLE
Add title on "random article" link

### ISSUE THREAD

**Issue by ldidry** [wallabag/wallabag#1315]
When you're over the "random article" link, which icon is a dice, it could be cool to display some information. I never noticed this link (new feature?) but I had to see that its URL was `action=random` to understand its aim.

A simple `title` attribute in the `<a>` tag would display the title after a little time with the mouse over the dice (at least, Firefox does that, I don't know for other browsers).

**Comment by tcitworld** [comment]
Will do.

**Comment by tcitworld** [comment]
Here. Thanks for noticing.

**Comment by ldidry** [comment]
You're welcome :wink:
