### ISSUE TITLE
[v2] Fix display for "new entry" form

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1321]
When #1319 will be merged, you'll see that we have a bug with the form. Technically, the form works well, but:
* font is white
* the cross to close the form is not visible
* the `+` is not at the good place.

**Comment by ticoombs** [comment]
I was just about to post this. 
White Font is taken care of by either removing color inherit, or removing input from the same section. But as im semi new to the project, I am unsure where else it is referenced) 

```
src/Wallabag/CoreBundle/Resources/views/themes/material/public/css/materialize.css:1826
-  color: inherit;
-  /* 1 */
```

**Comment by nicosomb** [comment]
I really don't know why font color is white, because it seems to be the same code than for search form.

**Comment by nicosomb** [comment]
I started something here: https://github.com/wallabag/wallabag/pull/1327

**Comment by nicosomb** [comment]
I think I've found. About search form, input has search type. And this type is overloaded in CSS.

**Comment by nicosomb** [comment]
Nope, I invode @modos189 power!

**Comment by nicosomb** [comment]
Fixed.
