### ISSUE TITLE
do not display pagination when only 1 page

### ISSUE THREAD

**Issue by nIQnutn** [wallabag/wallabag#1324]
on http://v2.wallabag.org/unread/list
when only 2 items and 1 page I have still the pagination but if think it's uselesss.

BTW pagination is more intuitive with 1.9 :
previous 1 2 ... 11 next

**Comment by nicosomb** [comment]
Fixed here https://github.com/wallabag/wallabag/pull/1328
About the 2nd point, I opened #1329
