### ISSUE TITLE
Pagination more intuitive

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1329]
see #1324 by @nIQnutn : 
> pagination is more intuitive with 1.9 :
> previous 1 2 ... 11 next

**Comment by ThibaudDauce** [comment]
What about an infinite scroll? I know some people don't like this but I do ^^

**Comment by nIQnutn** [comment]
yes, it's an idea.

**Comment by nicosomb** [comment]
Infinite scroll is not a good way for accessibility...

**Comment by ThibaudDauce** [comment]
Oh yes, I knew that.
Is it possible to add an option in the config?

**Comment by tcitworld** [comment]
Yup, it could be made an option.
