### ISSUE TITLE
Add a bar on each page with alpha message

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1332]
It's not a priority. But I want to have a bottom bar with a message like "be careful, it's an alpha version with bugs, etc. please open a new issue etc."

**Comment by modos189** [comment]
Please write the text. You know, I do not have perfect knowledge of the English language =)

**Comment by nicosomb** [comment]
I'll do. As I said, it's not a priority. I'd prefer these issues #1320 and #1321 ;-)

**Comment by modos189** [comment]
Now I do)

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/pull/1369
