### ISSUE TITLE
[v2] Store entry language

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1333]
We can use this library: https://github.com/crodas/LanguageDetector
After that, wallabag will be able to filter by language :fr: :it: :cn:

**Comment by tcitworld** [comment]
FTRSS can already provide language... But I guess the results will be much better with this tool.

**Comment by j0k3r** [comment]
This lib seems efficient but it's got damn to much lines of code just to detect the language ... The _langage model_ is a 700k php file :scream: 
Also, I don't really like the `ini_set('memory_limit', '1G');` in the example ...

**Comment by tcitworld** [comment]
Yeah, even if we use sf and the requirements are higher, this seems quite a huge lib for a little feature.

**Comment by tcitworld** [comment]
Graby now provides language : https://github.com/j0k3r/graby/commit/4b33d5a285a346e2a93207483248c74260098388
