### ISSUE TITLE
Sync read position between clients

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1336]

**Comment by j0k3r** [comment]
You mean read position inside a content ?

**Comment by tcitworld** [comment]
Yup. Like the current *default* theme does, return to the position in the text where you left.

**Comment by nicosomb** [comment]
baggy does also does it. 
But here, the feature is to sync between web app and smartphone app.

**Comment by nicosomb** [comment]
https://twitter.com/h1ro/status/631551090840993793

**Comment by j0k3r** [comment]
Baggy does that? hu

**Comment by nicosomb** [comment]
yes! open an article, scroll down, go to unread and return to your article \o/

**Comment by tcitworld** [comment]
> Baggy does that? hu

It's here : https://github.com/wallabag/wallabag/blob/master/themes/_global/js/restoreScroll.js

**Comment by j0k3r** [comment]
Oh localStorage, I see.

**Comment by nicosomb** [comment]
Duplicate of https://github.com/wallabag/wallabag/issues/2643 
Opened PR: https://github.com/wallabag/wallabag/pull/2644
