### ISSUE TITLE
Lost session too often

### ISSUE THREAD

**Issue by jazzcrack** [wallabag/wallabag#1339]
Need to re-login 10 times a day, without do a logout, or close browser or have a new internet connection. :-(

**Comment by nicosomb** [comment]
Hello @jazzcrack !
Which version do you use? 
Can you try this fix please http://doc.wallabag.org/en/Administrator/sessions.html ?

**Comment by jazzcrack** [comment]
now 1.9.1 ... i think its even better now ... will test in next days

**Comment by das-schaf** [comment]
session.save_path fix does not work for me when my ip address changes (we are using different outgoing ip addresses at work which are chosen randomly for each new connection)

**Comment by tcitworld** [comment]
Sorry about this. I don't think we'll make any changes now for v1.x versions. Version v2 should work just fine.

**Comment by nicosomb** [comment]
@tcitworld is right. Sorry, I close this issue.
