### ISSUE TITLE
What can we do with "wrong display" emails?

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1340]
I receive many mails about websites that wallabag doesn't fetch correctly. But we don't answer to these emails ... 

Do you have any idea of what can we do?

**Comment by tcitworld** [comment]
Automatic email response system that says « your problem has been notified to Nicholas ». And then it opens  a new issue on Github (site_config repo).

Just kidding. If we use an automatic system we may just as well use an API.

**Comment by nicosomb** [comment]
Have a look to #1270 about automatic system.

**Comment by tcitworld** [comment]
Yeah, no. I think we should separate the "wrong display" issues from the rest of the support system.

**Comment by j0k3r** [comment]
We might need a different email maybe that can be handle to automatically create issue.

**Comment by AmrEldib** [comment]
You can use an IFTTT recipe to automate creating GitHub issues from emails (example [here](https://ifttt.com/recipes/247969-github-issues-email-gateway) and [here](https://ifttt.com/recipes/198524-create-a-github-issue-to-ciudadanoi-legislative-congreso-abierto-by-mail)).
I suggest that:
- Use a different email address other than 'hello', something like 'reportwrongdisplay' or something. This way this email will only be for these reports.
- Create a GitHub label specific to those issues and nothing else (like 'site_report'). It's possible that these reports will flood the list. It should be easy to filter them out.
- Auto response is a great idea. Maybe even add a link to the GitHub issue in the response. I don't know if that's possible or not.

**Comment by nicosomb** [comment]
Yeah, good idea. I tried here: https://github.com/wallabag/wallabag/issues/1345, it works.
But we can't assign a label via IFTTT. We have to do it manually. 

About auto response with the link to the issue, it's impossible. Or I really don't know how we can do it. There is no relation between the new issue and the sent email "wrong display in wallabag"... So IFTTT can't send the email with the issue link.

**Comment by AmrEldib** [comment]
Great! glad it's working.
Yeah, I thought it would be difficult to do that. Good to have tried it and rule it out.

**Comment by nicosomb** [comment]
I will create a new email address for wallabag v2, and will se if I can redirect emails with "wrong displayed in wallabag" subject can be redirected to this new email address. 
Thanks for the tip!

**Comment by j0k3r** [comment]
:+1: for the IFTTT recipe, can we then close that issue?
