### ISSUE TITLE
store the user IP?

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1344]
As a service provider with framabag.org, do you think we have to store the user IP un database?

**Comment by NumEricR** [comment]
What is the purpose?
What do you want to do with this data?

**Comment by nicosomb** [comment]
Nothing. I think the law says we have to store it, no?


-------- Message d'origine --------
De : Eric R <notifications@github.com>
Envoyé : 15 août 2015 00:59:26 UTC+02:00
À : wallabag/wallabag <wallabag@noreply.github.com>
Cc : "Nicolas Lœuillet" <nicolas@loeuillet.org>
Objet : Re: [wallabag] store the user IP? (#1344)

What is the purpose?
What do you want to do with this data?

---

**Comment by j0k3r** [comment]
You mean, store every user IP at each login or only the last one ?

**Comment by nicosomb** [comment]
I don't know what the law says.. Only the last one I think

**Comment by tcitworld** [comment]
Au niveau national : 
>  La loi du 21 juin 2004 pour la confiance à l’économie numérique (LCEN) dispose[14] que les fournisseurs d’accès à l’Internet (FAI)[15] ainsi que les hébergeurs[16] « détiennent et conservent les données de nature à permettre l'identification de quiconque a contribué à la création du contenu ou de l'un des contenus des services dont elles sont prestataires ».

Au niveau européen : 

> Selon son article 2,sont définits les données à conserver comme les « données relatives au trafic et les données de localisation, ainsi que les données connexes nécessaires pour identifier l’abonné ou l’utilisateur ». En plus, dans son article 5, elle précise qu’il s’agit des « données nécessaires pour retrouver et identifier la source, la destination, la date, l’heure et la durée d’une communication. Cela concerne, notamment, le numéro de téléphone attribué à toute communication ; les nom et adresse des abonnés, ainsi que leur l’adresse IP (protocole Internet) ». 

I think it's not wallabag's job to store IPs. It's the hoster's job, and they do this looking up apache/nginx/... logs. Not wallabag's. Same applies to Framabag. It's ~~Framasoft~~ @nicosomb's job.

**Comment by nicosomb** [comment]
my job? how can I do? If it's nginx log, it's already done.

**Comment by tcitworld** [comment]
Yeah, so nothing to do on wallabag's side.

**Comment by nicosomb** [comment]
Thank you :)
