### ISSUE TITLE
Cleanup in composer.json

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1356]
Today, we have lot of dependancies in composer.json and github requests a token. I believe (but not sure) it's because our libraries are not tagged.

@j0k3r @FabienM any idea?

**Comment by j0k3r** [comment]
I guess this is because we use these deps as `vcs` so Composer can't get an archive from that vcs and need to clone the project.

What should be done:
- tag each libraries
- declare them on packagist

Also, I think we can cleanup few things, like _kriss_php5_, I don't think we need this one.

**Comment by nicosomb** [comment]
Done.
