### ISSUE TITLE
Display problem if domain name is too big

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1357]
Have a look 

![](https://lut.im/cWAwoNQ4/bhedEgZa)

**Comment by modos189** [comment]
What kind of behavior you expect?

**Comment by nicosomb** [comment]
I think we should truncate the URL. What do you think of that? Have a look to slice function http://twig.sensiolabs.org/doc/filters/slice.html

**Comment by modos189** [comment]
Although... The width of the card varies with the width of the screen, I'll use CSS overflow

**Comment by nicosomb** [comment]
Just opened a PR #1400.
