### ISSUE TITLE
Documentation for v2

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1359]
When we'll release v2, our documentation website must be up to date with new features, screenshots, etc.

**Comment by nicosomb** [comment]
Documentation for wallabag v2 is now hosted here: https://github.com/wallabag/wallabag/tree/v2/docs
And it will be published here: http://wallabag.readthedocs.org/

**Comment by nicosomb** [comment]
Our main documentation is now v2 one: http://doc.wallabag.org

**Comment by j0k3r** [comment]
Do we have to keep that issue open?
