### ISSUE TITLE
Fix Scrutinizer issues

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1360]
See https://scrutinizer-ci.com/g/wallabag/wallabag/

**Comment by j0k3r** [comment]
I've fixed most important issues https://github.com/wallabag/wallabag/pull/1820 and https://github.com/wallabag/wallabag/pull/1819.
We'll keep fixing new issues.

**Comment by j0k3r** [comment]
I remove the milestone since this should be a running issue to not forget about fixing Scrutinizer issues.
