### ISSUE TITLE
Add URL -> URL not saved and logged out

### ISSUE THREAD

**Issue by jazzcrack** [wallabag/wallabag#1361]
If i add this URL (private facebook Group posting), the URL will not be saved and i logged out. With other URLs there no problem.

I can reproduce with different URLs ... private Facebook Group posts may be the problem.

**Comment by jazzcrack** [comment]
Or is it a common problem with facebook ... also normal Facebook pages same problem ...: - /

**Comment by tcitworld** [comment]
If it's a private facebook group, then you can't get content. At for now, content must be public to be fetched.
In the future, we'll use javascript to get content from browsers.

**Comment by j0k3r** [comment]
@jazzcrack can you provide the private group? Just for test purpose. Thanks

**Comment by jazzcrack** [comment]
It is a common problem with facebook ... every Facebook content do the same, the URL will not be saved and i logged out. :-/

**Comment by tcitworld** [comment]
Please provide one or more facebook URLs to a public content that you think should be saved, we'll see what we can do about it.

**Comment by jazzcrack** [comment]
https://www.facebook.com/wallabag

**Comment by jazzcrack** [comment]
Any facebook content

**Comment by j0k3r** [comment]
Yay, it generates an error 500 on the v2..

**Comment by tcitworld** [comment]
Well for instance I can save this post with v1.9.1, even though it's not perfect. https://www.facebook.com/wallabag/posts/596558680485293
The homepage https://www.facebook.com/wallabag will not be saved since it contains many contents, not only one.

wallabag's intention is to save posts or specific text pages, not whole websites.

**Comment by tcitworld** [comment]
There's a very strange css bug with v2/material theme though.

**Comment by jazzcrack** [comment]
Single postings are ok ... but save a facebook page is not. Groups the same problem. The content isnt so important for me. I just want to save URLs i will visit or read later.

**Comment by tcitworld** [comment]
Then you should use bookmarks, not this application.

**Comment by jazzcrack** [comment]
Good style? ... people find bug ... answer: "go away"

I like wallabag, so i save both just some URLs and mostly articles with it.

**Comment by tcitworld** [comment]
I'm sorry if you take it that way. I'm just saying we never said wallabag was intended to save URLs. It's meant to save content (and mostly articles) located at an URL.

**Comment by nicosomb** [comment]
I agree with @tcitworld. wallabag saves articles, other tools save full webpages, I think you should use them.
