### ISSUE TITLE
[v2] back to good section while updating configuration

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1368]
Today, when we update user information, we are redirected to first tab, which can be frustrating because we don't see error message.

**Comment by modos189** [comment]
Need to switch to using aJax

**Comment by NumEricR** [comment]
Same problem while clicking on "Regenerate ?" link (RSS tab).
We are redirected to first tab instead of RSS one.

**Comment by j0k3r** [comment]
@modos189 why do you need ajax here? It can be done in plain javascript without ajax.
Detect # in url, switch active tab depending on #

**Comment by modos189** [comment]
@j0k3r because I want aJax =)

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/pull/1375
