### ISSUE TITLE
Display issues in config screen

### ISSUE THREAD

**Issue by NumEricR** [wallabag/wallabag#1371]
There is a strange display in configuration view: 
- "Rss token VS. token string
- "Rss links" VS. "Unread"

![capture d ecran 2015-08-19 a 01 34 47](https://cloud.githubusercontent.com/assets/262560/9345555/89c1a098-4612-11e5-82ec-a8bf7e885a4b.png)

Moreover "Rss" should be written in caps.
And why not using "favourites" instead of "fav"?
Why mandatory fields are not indicated with a specific character (i.e. *)?

Tested on v2.wallabag.org with Firefox.

**Comment by nicosomb** [comment]
PR: #1384

**Comment by nicosomb** [comment]
Fixed.
