### ISSUE TITLE
Launch test suite using a dedicated ENV variable to define the current theme

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#1373]
Regarding what we said in https://github.com/wallabag/wallabag/pull/1366, we should be able to run the test suite for all default theme. This means for baggy and material.

I think that defining the current theme using an ENV variable should be enough.

Like how Symfony version is handled in Sonata: https://github.com/sonata-project/SonataAdminBundle/blob/master/.travis.yml

``` json
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: CS_FIXER=run
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
```

http://docs.travis-ci.com/user/languages/php/#Testing-Against-Multiple-Versions-of-Dependencies-(e.g.-Symfony)

**Comment by Kdecherf** [comment]
Knowing that baggy has been deprecated and will be removed in 2.6.0, @j0k3r I guess we can close this
