### ISSUE TITLE
Filter date: no results for today

### ISSUE THREAD

**Issue by nIQnutn** [wallabag/wallabag#1379]
When I add a page and I test filter, I don't have expected result.
Today: 19/08/2015

from : 18/09/2015
to : 19/08/2015
> nothing

from : 19/09/2015
to : 19/08/2015
> nothing

from : 19/09/2015
to : 20/08/2015
> it seems to be ok

**Comment by nicosomb** [comment]
Fixed.

**Comment by j0k3r** [comment]
@nIQnutn thanks for the feedback, we didn't try this case when we implement the filter on created date.

**Comment by nIQnutn** [comment]
glad to help the project
