### ISSUE TITLE
Filter: Reading time

### ISSUE THREAD

**Issue by nIQnutn** [wallabag/wallabag#1381]
If I'm stupid and invert values FROM and TO:
from: 15
to: 5

I have no results. 

Results are Ok with:
from: 5
to: 15

Could you add any control to have results in both cases ?

**Comment by nicosomb** [comment]
If you're stupid, I can'd anything for you. 
More seriously, I don't believe we have to do something for this behavior.

**Comment by nIQnutn** [comment]
The filter is working fine yet it could be a little improvement for the UE. 
I reported it, now if you think this is the expected behavior, it's ok..

**Comment by j0k3r** [comment]
From my POV, if you defined wrong data, you'll get the wrong result.
I don't think we need to provide an extra verification. But thanks for reporting.
