### ISSUE TITLE
If parsing fails, just redirects to the article

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1387]
If Pocket can't parse a website, the service redirects to the original article, and don't try to store content. 
Pros: no more failed articles. 
Cons: we don't save the content's article.

@j0k3r @tcitworld any opinion?

**Comment by j0k3r** [comment]
If we can't get content from the website, we can still rely on the open graph data to get an image, a description, etc .. which can be an alternative.

I don't really being redirected to the main content if it's fail. Readability doesn't handle it like Pocket.

**Comment by tcitworld** [comment]
I like @j0k3r's idea, and I'm also against just displaying the original article. But I would found nice to have a detailed error message, and then two options : 
- go to original article
- send an email to display-error-at-wallabag-dot-org or open an issue on wallabag/fix-articles.

**Comment by jlnostr** [comment]
In addition to that, this could be done automatically, if the user enables a specific option.
Then wallabag could create the issue automatically over the GitHub API.
Would it make a lot easier for non-technical users :-)

**As a flowchart:**
fetching fails -> GitHub issue created automatically -> s/o writes a rule -> automatic update (as suggested in #1284)
