### ISSUE TITLE
Wrong display site http://f9r.ru/

### ISSUE THREAD

**Issue by modos189** [wallabag/wallabag#1388]
Instead of displaying articles of the system blocks access to the bot wallabag.

![s6](https://cloud.githubusercontent.com/assets/1785196/9396747/b7a65ec0-479f-11e5-97ab-b7551009617a.png)

(Attention! Your browser is not defined, and so on and so forth...)

Wallabag tested on versions v1 ... and v2

**Comment by j0k3r** [comment]
Could you provide an example of article link?

**Comment by modos189** [comment]
http://f9r.ru/phpaz.html

**Comment by modos189** [comment]
In fact, the site is already old (although a lot of useful information), but I think it will help to better filter the bot to other sites

**Comment by tcitworld** [comment]
Not much we can do if the website has decided to block users depending on user-agent using javascript (http headers are good since wallabag provides them). Just stupid of them.
