### ISSUE TITLE
[v2] "Mark as read" & "Mark as unread"?

### ISSUE THREAD

**Issue by NumEricR** [wallabag/wallabag#1394]
In article view, title of "Toggle mark as read" link always use "Mark as read", no matter its read status.
Shouldn't we see "Mark as unread" if this article has been marked as read previously?

By the way, same bug appears with 1.8.0 (See http://demo.wallabag.org). But I know, you don't care :smile:

**Comment by j0k3r** [comment]
I think that should be postponed to the version 2.0.0 when we'll plan to handle ajax request to that kind of things. It'll be more easy to do it.

**Comment by tcitworld** [comment]
Well, we can do it anyway even without ajax. It's not related.

**Comment by FM33** [comment]
I can reproduce it on framabag. It also matches the issue I have on android : If I don't scroll strictly vertically, then next article is loaded. Very annoying.
Firefox 42, Ubuntu 14.04 and Firefox 41, Android 4.4

**Comment by nicosomb** [comment]
Fixed here https://github.com/wallabag/wallabag/pull/1563
