### ISSUE TITLE
Back to article list when "mark as read" 

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1407]
There may be already be an issue about this.

> There is a button to "mark as read and go to next article" but it could be nice to have a button "mark as read and back to article list".
> It coul be a parameter in preferences to define which default action to do after "mark as read"

Thanks to Nico for the idea.

**Comment by he7d3r** [comment]
Related to https://github.com/wallabag/wallabag/issues/496?

**Comment by tcitworld** [comment]
Yup. Closed.
