### ISSUE TITLE
Support of mathjax

### ISSUE THREAD

**Issue by rgugliel** [wallabag/wallabag#1408]
MathJax is a Javascript library which allows to view LaTeX (mathematical formulas) code inside a browser. The result is a combination of CSS, HTML and SVG.
More information here: https://en.wikipedia.org/wiki/MathJax
And here: https://www.mathjax.org/

It would be really nice to enable MathJax in order to be able to read mathematica articles in Wallabag.
With the use of the CDN of MathJax, it is pretty simple: http://docs.mathjax.org/en/latest/start.html

The following points could be a problem:
- Decide when to enable MathJax
- I don't really know how it works on Android, which could be a problem for an offline mode
- If one wants to use another CDN, it could be more complicated

If the Wallabag team want to implement that, I'm ready to help.

Best.

Rafael

**Comment by j0k3r** [comment]
Could be interesting.
Do you have an url that can contains such _MathJax _ so we can see what can we try to do?

**Comment by froschdesign** [comment]
> With the use of the CDN of MathJax, it is pretty simple: http://docs.mathjax.org/en/latest/start.html

This opens the door for user tracking. This is task for Pocket and not for Wallabag.
So don't do this!

**Comment by nicosomb** [comment]
An alternative exists: http://docs.mathjax.org/en/latest/start.html#installing-your-own-copy-of-mathjax

**Comment by rgugliel** [comment]
@froschdesign : That's why I said "If one wants to use another CDN, it could be more complicated" it is more complicated but of course interesting. And the user could choose between some CDNs.

**Comment by froschdesign** [comment]
@nicosomb 
This is the right way aka. that's what I wanted to say!

**Comment by rgugliel** [comment]
@j0k3r : I have some MathJax in some posts of my blog, for example this one:
http://math.rgug.ch/2013/03/08/matrices-complementaires-et-produits/
(I'm sorry, it is in French)

**Comment by froschdesign** [comment]
@rgugliel 
External CDN's are always a no-go for Wallabag! (imo)
I use Wallabag for privacy reasons.

**Comment by rgugliel** [comment]
@froschdesign 
I understand and I agree but if this feature is implemented in Wallabag, then I would host MathJax in my server in the same way I host Wallabag...
The choice could be left for the user.

**Comment by froschdesign** [comment]
@rgugliel 
> The choice could be left for the user.

Is this really needed? I think it should be a part of the theme. [Same way like jQuery](https://github.com/wallabag/wallabag/tree/master/themes/_global/js).

**Comment by tcitworld** [comment]
It depends on the size on the Mathjax file size, maybe it would be faster to look at the cache. 
But as always, privacy is our number one concern and the default behaviour will be the file being served directly on server.

>  I use Wallabag for privacy reasons.

Please be aware wallabag currently makes requests to our server to check if there's a new version available each time you access the config page.

**Comment by newey01c** [comment]
:+1: this would be amazing. Any new movement on this?

**Comment by hrehfeld** [comment]
Any update? What are the problems implementing this?
