### ISSUE TITLE
Can't get article on shuhaowu

### ISSUE THREAD

**Issue by lightonflux** [wallabag/wallabag#1409]
https://shuhaowu.com/blog/network_emulation_on_your_router.html

The usual message:

    [unable to retrieve full-text content]...

**Comment by r4mp** [comment]
I had the same failure... after installing and activating the following extensions:

php5-mcrypt php5-tidy

everything works fine.

**Comment by tcitworld** [comment]
I confirm this.

**Comment by j0k3r** [comment]
`php5-tidy` should be installed _by default_ to improve content fetching.

**Comment by tcitworld** [comment]
Yeah, we should tell explicitly that it improves content fetching.

**Comment by nicosomb** [comment]
@lightonflux Can you confirm that it works with `php5-tidy`?

**Comment by j0k3r** [comment]
@lightonflux feel free to reply to the issue if you need. We'll re-open. Closing for now.
