### ISSUE TITLE
Adding possibility to delete article with 404 result

### ISSUE THREAD

**Issue by espritlibre** [wallabag/wallabag#1410]
Now there is a Jolla Client for wallabag :)

I imported all my bookmarks to wallabag, but there is lot of old bookmark and lots of page are KO (with 404 result or domain is not exist)

I there a quick possibilty to delete all link where the result when wallabag try to get the content have a 404 as result ?

Thanks

**Comment by j0k3r** [comment]
That could be an option page in the v2 where you can see all your dead link and/or your 4xx / 5xx page.
But for the v1.9.x, you should delete them manually from wallabag or from the database directly,  I guess.

**Comment by tcitworld** [comment]
I don't think this can be backported to v1.9 anyway. 
@j0k3r WIth v2 we can add a http status property for each entry that could do the trick, right ?

**Comment by j0k3r** [comment]
We can do that.

**Comment by espritlibre** [comment]
Thanks
