### ISSUE TITLE
When DOWNLOAD_PICTURES is activated, suggest reimporting everything

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1411]
When an user has activated DOWNLOAD_PICTURES, he should be proposed to re-import all of the articles he already had, so that the pictures on these entries can be fetched too.

Or maybe we can fetch all the pictures from before without re-fetching all the entries ?

**Comment by nicosomb** [comment]
The second way seems to be the best way. 
We already have the picture paths in database, no need to refetch entries. 

But we can't do this from the wallabag front. We need a cron to do this task.

**Comment by tcitworld** [comment]
Hmm, most shared hosting solutions don't offer cron tasks, so maybe we could also have the option to make it from front.

**Comment by nicosomb** [comment]
We can close this old issue: we have a command to refetch all articles and we can also refetch an article from the front view.
