### ISSUE TITLE
Backport site config changes from wallabag v1 to fivefilters repo

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#1414]
Instead of keeping two differents repositories of site configs, it could be better to contribute to the _official_ site config repo from @fivefilters: https://github.com/fivefilters/ftr-site-config

So we need to extract site configs from wallabag v1 (here: https://github.com/wallabag/wallabag/tree/master/inc/3rdparty/site_config/standard) and merge them in the fivefilters repo.

**Comment by tcitworld** [comment]
I think this depends if @fivefilters agrees (and is able to !) to update it fast enough when we PR it.

**Comment by j0k3r** [comment]
As far as I can see, he is fast enough.

**Comment by tcitworld** [comment]
Yeah, it seems so. Right.

**Comment by nicosomb** [comment]
Is this issue needed for next alpha?

**Comment by j0k3r** [comment]
It's not a must have, it's a nice to have.
