### ISSUE TITLE
500 Internal Server Error on filtering articles

### ISSUE THREAD

**Issue by sridharrajs** [wallabag/wallabag#1416]
Environment : http://v2.wallabag.org

Filter articles between 2 and 5.

![unread - wallabag - chromium_037](https://cloud.githubusercontent.com/assets/1156953/9819448/b9504cda-58cb-11e5-9b7d-d536f97976d6.png)

Now, Click on Filter. You can see 500 Internal Server Error.

![an error occurred internal server error - chromium_038](https://cloud.githubusercontent.com/assets/1156953/9819490/f29c4a3e-58cb-11e5-9fae-f425b936a2cb.png)

**Comment by nicosomb** [comment]
I had this bug too, but today it seems to be good. Server problem I think. I close.
