### ISSUE TITLE
Warn that registration is disabled when adding an user

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1423]
Disable registration.
Add new user from config page. Success. Logout.
Trying to login : « User account is disabled. »

Expected behaviour : Directly show on config page a warning.

**Comment by j0k3r** [comment]
Where do you _disable registration_ ?

**Comment by tcitworld** [comment]
Good question. I thought there was a parameter inside https://github.com/wallabag/wallabag/blob/v2/app/config/parameters.yml.dist, but I was wrong.

**Comment by nicosomb** [comment]
is `isEnabled` field set to true for the new user?

**Comment by j0k3r** [comment]
Since we are using FOSUser, `enabled` field is `false` by default.
