### ISSUE TITLE
List view for material theme

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1424]
As in baggy theme, it would be nice to have a list view

![](https://lut.im/QPtl7fnj/bIUSEwhi)

**Comment by modos189** [comment]
It is at odds with the concept of adaptive design.
If you make the width of the card in full screen, it is necessary to limit the maximum width of the page

**Comment by nicosomb** [comment]
if the card take 100%, is that necessary to limit it?

**Comment by modos189** [comment]
it will be very bad look on wide screens

**Comment by nicosomb** [comment]
I understand. I think you have a great idea to implement this feature.

**Comment by modos189** [comment]
also because of the peculiarities of the implementation of display images, pictures have to do with the height of the screen.
so I think that the list view at odds with the idea of the material design

**Comment by nicosomb** [comment]
what about have `l12` css class each li on entries view? And we remove the preview picture?

**Comment by tcitworld** [comment]
> And we remove the preview picture? 

Or resize it to the height of the list element.

**Comment by nicosomb** [comment]
In fact, I don't know if we have to implement this feature in material theme. Each theme has its own features, list view is a baggy one.
