### ISSUE TITLE
Caracter encoding problem on material preview cards

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1426]
HTML content : `The Clarity &amp; Confusion of Grief`
In content : `The Clarity & Confusion of Grief`
On the card : `The Clarity &amp; Confusion of Grief`
On the card, html content : `The Clarity &amp;amp; Confusion of Grief`

![problem](https://cloud.githubusercontent.com/assets/2197836/9975404/a4889140-5ebb-11e5-9e7c-113494814ac4.png)

https://medium.com/@jeffgoins/when-friends-die-329d9d3a7be8

**Comment by j0k3r** [comment]
And how is it using baggy? Maybe it's not a theme problem ..

**Comment by tcitworld** [comment]
Well, baggy doesn't reveals text on cards like material does, there's only pictures.

**Comment by j0k3r** [comment]
Does the encoding is correct when you open the article?

**Comment by tcitworld** [comment]
Yup, that's what I meant by *In content*

**Comment by tcitworld** [comment]
I guess it's linked to https://github.com/wallabag/wallabag/pull/1417#issuecomment-139751226

**Comment by nicosomb** [comment]
This bug is due to the combination of `striptags` and `slice` twig filters. We can't apply these 2 tags at the same time.

**Comment by tcitworld** [comment]
@nicosomb You're sure about that ? Never had issues with this kind of thing.
