### ISSUE TITLE
Unable to bag http://stormsabrewin.org/pizzacigarette.html

### ISSUE THREAD

**Issue by stormi** [wallabag/wallabag#1430]
Attempting to add the above URL doesn't work, and what's worse:
* the "save link" dialog in the web interface still says "Done"
* my user is instantly disconnected

**Comment by nicosomb** [comment]
Hello @stormi !

Good news, I tried with wallabag v2 and it works http://v2.wallabag.org/view/73

**Comment by stormi** [comment]
Ok, all I have to do is to wait for v2 to be released and framabag to update I guess :)

**Comment by nicosomb** [comment]
:+1:
