### ISSUE TITLE
Only french language is stored

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1431]
I tried our new feature #1333, it works with french articles but with other languages, language is not detected. 
You can see the list here: http://v2.wallabag.org/unread/list The language field is empty in database.

**Comment by j0k3r** [comment]
Before #1429, language wasn't stored in the database. So, if you just update the code base and didn't re-import all entries, they won't have language defined.
You will have language defined for new entry only.

**Comment by nicosomb** [comment]
These entries are new one. I also tried locally. 
Oh, maybe it's a server problem: languages may not be installed on it?

**Comment by j0k3r** [comment]
Did you `composer install` ?

**Comment by nicosomb** [comment]
Yes

**Comment by j0k3r** [comment]
I'll check that later.

**Comment by j0k3r** [comment]
It was related to php-readability which removed attributes from the html tag: https://github.com/j0k3r/php-readability/commit/f71c3a419623f821c245e0a003edfbf2c67f278e

**Comment by nicosomb** [comment]
It's better with your last release. 
But these articles don't have any language: http://www.theguardian.com/technology/2015/sep/24/iphone-slow-ios-9-update-iphone-4s-iphone-5-iphone-5s and http://www.spiegel.de/sport/fussball/robert-lewandowski-fuenf-tore-gegen-wolfsburg-machen-sprachlos-a-1054285-druck.html for example.

**Comment by nicosomb** [comment]
I didn't look the sourcecode of the articles, maybe the language is not defined, in fact.

**Comment by j0k3r** [comment]
They both doesn't have language defined in the html..
