### ISSUE TITLE
API V2 Missing endpoints

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#1432]
from http://v2.wallabag.org/api/doc I think an endpoint is missing to get all the items from a given tag eg : 
#### api/tags/Pope.json

Get all entries from a tag. Started here: #1488 

currently (for the tags) we can only do http://v2.wallabag.org/api/tags.json in GET or http://v2.wallabag.org/api/tags/{tag}.json in DELETE 
#### Filter entries by tag

In GET /api/entries.json, we can set a tags array, but WallabagRestController::getEntriesAction() don't manage it. 
#### Filters
- preview picture: In GET /api/entries.json, add a boolean to fetch entries with picture preview only.
- domain name: in GET / api/entries.json, add parameter to fetch entries with specific domain name
- reading time: in GET / api/entries.json, add range to fetch entries with reading time in this range
- language: in GET / api/entries.json, add parameter to fetch entries with specific language
- creation date: in GET / api/entries.json, add range to fetch entries with create date in this range

**Comment by nicosomb** [comment]
I updated the first post to add other missing endpoints. Please tell uf if other endpoints still missing. 
ping @foxmask @jlnostr @freddyb @kevmeyer

**Comment by jlnostr** [comment]
As I told in [#1182](https://github.com/wallabag/wallabag/issues/1182#issuecomment-94302447), user-related information could be there in a `/api/user.format` request, which could contain the following things:

- shaarli/diaspora adresses
- the full name
- the avatar image URL
- oAuth token
- …

This would make the `user` node in each JSON item obsolete, which therefore should be removed.

**Comment by nicosomb** [comment]
> shaarli/diaspora adresses
> the full name
> the avatar image URL

Avatar? We don't have avatar for user. 
Shaarli / diaspora are generic config for wallabag instance, it's not personal information. Do you really need these data?

**Comment by tcitworld** [comment]
Maybe we should.

**Comment by foxmask** [comment]
@nicosomb unfortunatly I dont remember what was the original content on my post. Si I dont know which endpoint(s) has/have been added. So I made a test with http://v2.wallabag.org/api/tags/Pope.json but its failed.
Am I doing something wrong ? Is the doc uptodate ?

**Comment by foxmask** [comment]
@nicosomb unfortunatly I dont remember what was the original content on my post. Si I dont know which endpoint(s) has/have been added. So I made a test with http://v2.wallabag.org/api/tags/Pope.json but its failed.
Am I doing something wrong ? Is the doc uptodate ?

**Comment by foxmask** [comment]
@nicosomb unfortunatly I dont remember what was the original content on my post. Si I dont know which endpoint(s) has/have been added. So I made a test with http://v2.wallabag.org/api/tags/Pope.json but its failed.
Am I doing something wrong ? Is the doc uptodate ?

**Comment by foxmask** [comment]
@nicosomb unfortunatly I dont remember what was the original content on my post. Si I dont know which endpoint(s) has/have been added. So I made a test with http://v2.wallabag.org/api/tags/Pope.json but its failed.
Am I doing something wrong ? Is the doc uptodate ?

**Comment by jlnostr** [comment]
@nicosomb I simply copied the content from the other issue :D
IMHO, an avatar is not necessary, but if someone wishes it, it shouldn't be too hard to add.
I also think that shaarli/diaspora adresses should be a user setting, this would add the share feature to framabag as well :)

**Comment by tcitworld** [comment]
>  IMHO, an avatar is not necessary, but if someone wishes it, it shouldn't be too hard to add.

We can use libgravatar for this.

**Comment by nicosomb** [comment]
@foxmask your post was about api/tags/Pope.json only.
It's not yet implemented.
