### ISSUE TITLE
When displaying domain on themes, skip the www part

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1433]
No one cares about it.

**Comment by nicosomb** [comment]
@j0k3r I think it's good to create a twig extension. What do you think about it? (we can use `replace` in twig, but we have to check if `www.` is at the beginning of the URL)

**Comment by j0k3r** [comment]
Yeah, it might be a bit overkill but could a clean solution !

**Comment by nicosomb** [comment]
I made this fix `{{ entry.domainName|replace({'www.': ''}) }}` but imagine a domainName with www. inside ...

**Comment by nicosomb** [comment]
Tests needed.

**Comment by nicosomb** [comment]
test here #1461
