### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by icaroperseo** [wallabag/wallabag#1444]
Good day!

I've been reading the documentation and looking at the website if there is any way to restore access to self-hosted wallabag 1.9.1b (forgotten password) and I could not find anything about it. This instance has a recovery email but I have been unable find such functionality, on the other hand, only it has a single user so I would appreciate any help.

Thanks in advance.

**Comment by tcitworld** [comment]
Unfortunately, there's currently no way to automatically do it. The only way is to manually edit the database and [choose a new password](https://github.com/wallabag/wallabag/issues/1092#issuecomment-74593670) for the user.

**Comment by tcitworld** [comment]
It's possible with the next version (v2), though.

**Comment by icaroperseo** [comment]
I have my information in a MySQL database, would it be possible to upgrade to wallabag v2 and take advantage of new fucionalidad to reset the password or there is some incompatibility?

**Comment by tcitworld** [comment]
Hmm, no, the migration procedure will require that you export your wallabag data as json. It should be possible to do it manually directly from database, but I guess it would still be hard.

Also, v2 may not be out real soon.

**Comment by icaroperseo** [comment]
Thanks a lot!

**Comment by nicosomb** [comment]
v2 fixes this problem. I close.
