### ISSUE TITLE
Move the footer in the sidebar

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1445]
I think the current footer is too big. @j0k3r proposed to move it in the left sidebar. 
@modos189 any idea?

**Comment by modos189** [comment]
I think that footer should contain all the necessary information. If it is moved to the sidebar, then it simply will not fit.

Footbar is not limited to the screen, and is located just at the end of the page, I think, is where he needed.

Material design concept to the pages were not overloaded with information and buttons.

**Comment by j0k3r** [comment]
The current footer has too much information. Maybe we can just put some usefull information on the left sidebar. And let other stuff in the /about page.

**Comment by nicosomb** [comment]
@j0k3r :+1:

**Comment by j0k3r** [comment]
So, which information should we keep in the left sidebar then @nicosomb :smile: ?

**Comment by nicosomb** [comment]
haha, I have to work now. 

In fact, I don't know if information about our smartphones apps is useful here. 
Maybe we can only keep the about link. That's all. 

What do you think?

**Comment by j0k3r** [comment]
- powered by wallabag
- about page

**Comment by nicosomb** [comment]
ok

**Comment by modos189** [comment]
Not everyone will go to the link. A casually noticing list of applications that the user is interested in them.

**Comment by modos189** [comment]
The only thing I can suggest - to replace links to icons: 
![te1](https://cloud.githubusercontent.com/assets/1785196/10218596/aac2b2b4-6840-11e5-8143-081b4009c0c4.png)

**Comment by nicosomb** [comment]
It can be a nice solution (but with nice icons ;-) )
And the same thing for "take wallabag with you" part. 

In an other issue, @j0k3r said that icons for filters / add link are not very comprehensible. What can we do?

**Comment by modos189** [comment]
Of course, this is just a temporary icon for social networks)

Icons for filters / add link widely used on android> = 5, I do not want to change them

**Comment by tcitworld** [comment]
I also think icons for social networks and applications are a good way to reduce size.

**Comment by nicosomb** [comment]
@modos189 do you think you can do this change soon? I want to release alpha2 in next days.
