### ISSUE TITLE
www.forbes.com/sites

### ISSUE THREAD

**Issue by benages** [wallabag/wallabag#1452]
Unable to Bag articles from forbes

From the config forbes.com.txt
test_url: http://www.forbes.com/forbes/2011/0509/technology-frog-design-jan-chipchase-ethnographer-birth-cool_print.html works but
test_url: http://www.forbes.com/sites/bruceupbin/2012/09/11/the-iphone-5-winners-and-losers/ does not work

**Comment by j0k3r** [comment]
For the 2nd link it's because the whole article is now in a javascript function. So we can't retrieve it..
