### ISSUE TITLE
[v2] tags are not deleted when you delete an entry

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1453]
I thought it had been taken of. If not, my bad.

* Get an article
* Set a tag to it
* Delete the article
* Get a new article right after (so that it has the same id)
* The new article has the old tag

**Comment by j0k3r** [comment]
> Get a new article right after (so that it has the same id)
How? It shouldn't have the same id since id are autoincremented.

**Comment by tcitworld** [comment]
Well, it seems they're not for me.

**Comment by nicosomb** [comment]
It's a SQLite problem I think...



-------- Message d'origine --------
De : Thomas Citharel <notifications@github.com>
Envoyé : 4 octobre 2015 19:58:51 UTC+02:00
À : wallabag/wallabag <wallabag@noreply.github.com>
Cc : "Nicolas Lœuillet" <nicolas@loeuillet.org>
Objet : Re: [wallabag] [v2] tags are not deleted when you delete an entry (#1453)

Well, it seems they're not for me.

---

**Comment by j0k3r** [comment]
Good point, was it using SQLite ?

**Comment by tcitworld** [comment]
Yup, that's the thing.

**Comment by tcitworld** [comment]
However, even if the id from entries went auto-increment, it seems like the entry-tag relation doesn't work properly. Or maybe it's related ?
