### ISSUE TITLE
[v2] Is the username useful?

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1462]
@tcitworld @j0k3r What do you think about removing the username field in registration? 
Users can connect with email address only. 
Like that, registration form can only contain 2 fields: email address & password (with a checkbox to show/hide the password).

**Comment by j0k3r** [comment]
Do you want to remove the username in the registration field or everywhere in the app?

**Comment by nicosomb** [comment]
Maybe everywhere. 
We can login with email address.

**Comment by j0k3r** [comment]
We need to think about that...

**Comment by j0k3r** [comment]
We send few emails (lost password & 2FA) I think it's still valuable to have the username.
3 fields is ok for me.

**Comment by shtrom** [comment]
I think username is worth keeping. I hope to authenticate against LDAP one day (:

That said, it could be optional and default to the email address.

**Comment by nicosomb** [comment]
OK, let's keep the username.
