### ISSUE TITLE
500 Internal Server Error when posting an article via API

### ISSUE THREAD

**Issue by sridharrajs** [wallabag/wallabag#1465]
When I post an article url to http://v2.wallabag.org/api/entries.json. I get `500 Internal Server Error` response. I've included the token in `authorization` header of the request. 

![selection_041](https://cloud.githubusercontent.com/assets/1156953/10306025/b830436c-6c41-11e5-99a2-73535f2a7696.png)

![selection_042](https://cloud.githubusercontent.com/assets/1156953/10306024/b825c37e-6c41-11e5-8a79-c4def579dbba.png)

**Comment by nicosomb** [comment]
Hello @sridharrajs!

We merged oAuth2 this morning and I will deploy it on v2.wallabag.org very soon. I will also publish a tutorial to explain how you can use our API. 
I will post here when it will be over.

**Comment by jlnostr** [comment]
So, WSSE is now dropped completely?

**Comment by nicosomb** [comment]
yes it is. 
I will write a blog post for you (developers)

**Comment by jlnostr** [comment]
Alright :)

**Comment by sridharrajs** [comment]
It works now.
More info here : https://www.wallabag.org/blog/2015/10/06/developers-oauth2
