### ISSUE TITLE
Howto use oauth2 with wallabag

### ISSUE THREAD

**Issue by a-zen** [wallabag/wallabag#1476]
Hi,

could you please provide a short description on how to use oauth2 in wallabag
to use the api? It's not clear to me how to register and what grant-type to use.

--
regards
 alex

**Comment by nicosomb** [comment]
You can read our last blog post https://wallabag.org



Sur 9 oct. 2015 à 20:47, à 20:47, Alex <notifications@github.com> a écrit:

**Comment by a-zen** [comment]
Thanks that's exactly what I needed.
