### ISSUE TITLE
Wrong Content-Disposition header when download epub (rfc1806)

### ISSUE THREAD

**Issue by alkahan** [wallabag/wallabag#1481]
When download an epub file, the content-disposition header value is wrong:

Result:
Content-Disposition: attached; filename="title.epub"

Should be:
Content-Disposition: attachment; filename="title.epub"

see: http://www.ietf.org/rfc/rfc1806.txt

Impact:
The filename is not set properly on some devices like my Sony Reader, and use default filename "filename.bin". The device cannot open the file with that name.

**Comment by j0k3r** [comment]
I guess you are talking about the v1 ?
Feel free to provide a PR about that, it's an easy bug to fix.

:arrow_right: https://github.com/wallabag/wallabag/blob/7d6bd5670e8743e10c52b745142320a47d0f1cbe/inc/3rdparty/libraries/PHPePub/Zip.php#L572

**Comment by alkahan** [comment]
Yes in v1 :1.9.1.

You are right, I will provide a PR today.

**Comment by j0k3r** [comment]
@alkahan awesome ! Don't forget to target the dev branch instead of the master.

**Comment by tcitworld** [comment]
The PR can also be submitted to the PHPePub project.

**Comment by alkahan** [comment]
@tcitworld I have made a PR for PHPePub  3.30 branch. Current master and 4.0.0 rely on PHPZip and provide the right header value.

**Comment by tcitworld** [comment]
Nice. wallabag v2 relies on PHPePub 4.0 so it will be fine.

**Comment by nicosomb** [comment]
Can we close this issue?

**Comment by j0k3r** [comment]
We don't use `sendBook` in the v2, we built the response ourself.
