### ISSUE TITLE
[v2] Add content in 2FA emails

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1490]
The Two Factor Auth emails contain only the code to type in your browser. We should add content (little explanation phrases, wallabag signature) to explain and to avoid being detected as spam.

**Comment by nicosomb** [comment]
About emails, we need a template ping @modos189

**Comment by modos189** [comment]
In fact, the creation of design of letters different from the usual layout of pages, because very high requirements, and you must remember that each of the mail clients are trying in their own rendering code.

But fortunately, I recently engaged in the creation of design mail =)

I can see the code for sending emails? It is necessary to simultaneously send plain text and html versions.

**Comment by tcitworld** [comment]
Personally, I don't mind having only text instead of stylised html.

**Comment by modos189** [comment]
I want html =) it adds credibility to the service to the user's eyes

**Comment by j0k3r** [comment]
Well, I think we need to keep it simple at first, text is fine for me.

@modos189 what do you need to achieve this task?

**Comment by HLFH** [comment]
@j0k3r Isn't U2F the right standard for 2FA? https://github.com/wallabag/wallabag/issues/1499 

Isn't that better to remove the code related to 2FA emails and add some code for U2F support in wallabag? 

Also, if for any reason, you prefer to keep it that way, yes, I agree with you: it would be better to improve first of all the plaintext content in 2FA emails.

**Comment by j0k3r** [comment]
@HLFH Yeah I guess, even if the fact that you need to *purchase* sth to enable 2FA is a no-go for me.

Anyway, we'll have 2FA for wallabag v2 and we'll look into U2F for the v2.1.

**Comment by j0k3r** [comment]
@modos189 the text mail version is ready. Feel free to provide a HTML one.

**Comment by modos189** [comment]
I have a html version mail, but I have a problem with its addition.

1. I turn on two-factor authentication in the profile, but the letter did not come. I get emails with password recovery.

2. How in /src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php get server url?

3. I suggest a wrap message in html to produce in a separate function. This will allow to get rid of html in localization. Where it can be placed?

**Comment by j0k3r** [comment]
@modos189 

1. did you logged out and then logged in after that change?
2. what do you mean by *server url*? The support url is defined in `app/config/parameters.yml` as `wallabag_support_url`
3. yep we can split the text for to ease the html translation

**Comment by j0k3r** [comment]
@modos189 you can add your html in https://github.com/wallabag/wallabag/pull/1565
