### ISSUE TITLE
TOTP as 2FA

### ISSUE THREAD

**Issue by trockenasche** [wallabag/wallabag#1492]
Beside the two factor authentication method e-mail, I really like to see Time-based One-time Password Algorithm (TOTP) as a two factor authentication.

**Comment by tcitworld** [comment]
See https://github.com/stolendata/totp and https://github.com/multiOTP/multiotp

**Comment by securitypedant** [comment]
Or maybe just implement Authy... www.authy.com

**Comment by tcitworld** [comment]
It doesn't seem to be an open-source app and we would prefer something else.

**Comment by securitypedant** [comment]
Ahh yes, sorry Thomas. Authy is not open source.

**Comment by j0k3r** [comment]
https://github.com/Spomky-Labs/otphp

**Comment by j0k3r** [comment]
Fixed in https://github.com/wallabag/wallabag/pull/3798
