### ISSUE TITLE
[v2] API response doesn't match the request

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#1494]
According to the [API documentation](http://v2.wallabag.org/api/doc#patch--api-entries-{entry}.{_format}), apps need to perform a PATCH request with the parameters serialized as JSON. So I did. The server returned http code 200, so I thought everything went fine.

In my case, I tried to mark an item as read.

## Request
```
PATCH https://v2.wallabag.org/api/entries/26.json HTTP/1.1
Accept-Encoding: gzip, deflate
User-Agent: (wallabag for Windows)
Authorization: Bearer <token_here>
Content-Length: 16
Content-Type: application/json; charset=UTF-8
Host: v2.wallabag.org
Connection: Keep-Alive
Cache-Control: no-cache
Cookie: __cfduid=d65922ff9b96fbbfd1b6c134c93a05a431444407579

{"archive":true}
```

## Response
```
HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Tue, 20 Oct 2015 19:54:52 GMT
Content-Type: application/json
Connection: keep-alive
X-Powered-By: PHP/5.4.45-0+deb7u1
0: application/json
Cache-Control: no-cache
CF-RAY: 238746ecd88e2318-FRA
Content-Length: 26054

{"id":26,"title":"BBC - Home","url":"http:\/\/www.bbc.co.uk\/","is_archived":false,"is_starred":false, …}
```

Notice how the server is responding with `is_archived: false`. This error does also appear with other properties, e.g. `star -> is_starred`.

**Comment by tcitworld** [comment]
I may be wrong, but [it seems](https://github.com/wallabag/wallabag/blob/v2/src/Wallabag/ApiBundle/Controller/WallabagRestController.php#L172) the documentation is incorrect and the json to call is `{"is_archived":true}`

**Comment by nicosomb** [comment]
I found a bug, we don't persist entry in this method. But it still doesn't work. I'm on it.

**Comment by jlnostr** [comment]
@tcitworld That's it. Thanks! :+1: 
@nicosomb Should I close the issue now or should I leave it open as a reminder to update the documentation? :wink:

**Comment by tcitworld** [comment]
So what's the most logical thing ? `is_archived` or `archive` ?

**Comment by jlnostr** [comment]
Personally, I prefer the first one because it matches the returned item properties.

**Comment by tcitworld** [comment]
I also have the same advice. We'll have to update documentation if everyone agrees.

**Comment by nicosomb** [comment]
Wow, it doesn't work for me. I will see if we need to fix it or not.

**Comment by nicosomb** [comment]
I don't understand, it doesn't work for me. @jlnostr are you sure it's ok for you? The response seems to be ok, but if I display the web interface, the entry is still the same.

**Comment by jlnostr** [comment]
Yes, I tried it. It does work now :)

**Comment by nicosomb** [comment]
When I execute this command: 

```
http PATCH http://localhost:8000/api/entries/1.json \
        is_archived=true \
        "Authorization:Bearer NWE2OGY2ZDczMmQzNWIzNjRkMDk2OTEwMmE4Nzk2M2I5YTJkMjI0ZWJkNmE1NDRkOTZkODFlOWQ2NzRiNmU5NA"
```

I've got this response: 
```
...
    "is_archived": true, 
    "is_starred": false, 
...
```

But if I display the web interface, the entry is still unread. 
I don't understand why.

**Comment by jlnostr** [comment]
In the current installed version on [v2.wallabag.org](v2.wallabag.org) it's working fine :D

**Comment by j0k3r** [comment]
Well, we need to be ok with the doc.
I fixed some stuff today and noticed that the code wasn't related to the documentation, nor the unit test.

So I've updated the code (https://github.com/wallabag/wallabag/commit/01fddd0cb2fc6c83998a54d24d4ca6a27b564d36).

Question is: which way do we prefer? `is_archived` or `archive`?

**Comment by tcitworld** [comment]
If we choose `archive` instead of `is_archived`, let's change `is_starred` too.

**Comment by j0k3r** [comment]
`is_starred` is already changed to `star` :)

**Comment by tcitworld** [comment]
My bad, I referred to the original post. Then the other way around.

**Comment by j0k3r** [comment]
@jlnostr So it'll be `star` & `archive`.

Should we also update the API response to send `archive` instead of `is_archived`?

**Comment by jlnostr** [comment]
The API response should continue to remain the same, as it makes more sense. You are asking for data and not sending a command :)

**Comment by j0k3r** [comment]
Okay, so we can close this issue.
