### ISSUE TITLE
Support of U2F for authentication

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#1499]
[GitHub announced it some weeks ago](https://github.com/blog/2071-github-supports-universal-2nd-factor-authentication) and as they state in the post:

> GitHub encourages developers to build U2F support into their own applications as well, enabling authentication with simple user experience and strong security using public key cryptography. 

Therefore I think it would be nice if wallabag could support U2F, too. After a quick research I found a [PHP library](https://developers.yubico.com/php-u2flib-server/), which propably could be used. You can find more information about U2F [here](https://www.yubico.com/why-yubico/for-individuals/github/) :)

**Comment by j0k3r** [comment]
This is the part I don't like:

> In order to take advantage of the security improvements provided by U2F, you'll need to purchase a hardware key.

But anyway, this is something we should add in a later release.
