### ISSUE TITLE
[v2] Welcome page when article list is empty

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1501]
- [ ] Link to documentation
- [ ] Link to importers
- [ ] Link to config

What else?

**Comment by tcitworld** [comment]
Quick start page ?

**Comment by nicosomb** [comment]
:+1:

**Comment by nicosomb** [comment]
I want to reditect on this new page when country(allArticles)==0. What is the best way to implement this test ?

**Comment by j0k3r** [comment]
Hum, I don't know if it's the best way, but I'll do that :
- check for the homepage route in showUnread (sth like `$request->attributes->get('_route')`)
- set a global var in the controller (`Pagerfanta $entries`) which will be define in `showEntries`
- then check for the `getNbResults` on `$entries` before returning the rendered template

**Comment by nicosomb** [comment]
> check for the homepage route in showUnread (sth like `$request->attributes->get('_route')`)

But showUnread is the homepage, right?

**Comment by j0k3r** [comment]
Yes, but it can also be access using `/unread/list`.
Also, I think my solution it too complex. It should be better to make a fast and single query to count existing item for the logged in user (still only when it's the `homepage` route) and then apply the redirection or not.

**Comment by nicosomb** [comment]
OK. Which behavior if I click on Fav / Archive tab with no entries in my database?

**Comment by j0k3r** [comment]
I guess you'll have an empty page :) The welcome page should be only on the `/`.

**Comment by nicosomb** [comment]
OK

**Comment by nicosomb** [comment]
But ... when I use wallabag for long time ago, and I manage to clear my unread tab (yes, I think it's possible!), I'll have the quickstart page on my unread tab?

**Comment by nicosomb** [comment]
Do we need a flag on User entity to store if the user choosed to hide the quickstart?
