### ISSUE TITLE
[v2] reload article content

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1503]
Button on article page to re-fetch article content.

**Comment by j0k3r** [comment]
In case of content aren't well fetched at first ?

**Comment by bdunogier** [comment]
> In case of content aren't well fetched at first ?

Yep, there's a need for that on alpha software, I'd say :-)
But given that articles, especially, can be updated overtime, it also makes sense as a regular feature (do we want to cover that as another feature ?).
