### ISSUE TITLE
Delete ALL articles in one click

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/wallabag#1506]
Hello!
The question is formulated in the title. How can I delete all articles at once: both their contents and records from DB. My Wallabag is being hosted at Framabag.

**Comment by tcitworld** [comment]
Hmm, @nicosomb can do it manually if you provide your username but there's currently no way to do this from wallabag itself. I've opened #1507 to change this.

**Comment by Suncatcher** [comment]
Ok, I supported this issue.
And does we have any control over Framabag-hosted accounts? Anything except web-dashboard: DB, source?

**Comment by tcitworld** [comment]
What would you have in mind ?

**Comment by Suncatcher** [comment]
For example, to add my oown theme, or to edit/delete DB-records manually.

**Comment by tcitworld** [comment]
> or to edit/delete DB-records manually

I don't think that's going to happen because of possible security risks (we currently have databases separated for each user, but that's going to change in the future).

About the theme addition, I guess it will be a wallabag feature at some point.

**Comment by j0k3r** [comment]
@Suncatcher does @nicosomb removed all your articles?

**Comment by Suncatcher** [comment]
No. I sent request to him yet in 30.10.

**Comment by nicosomb** [comment]
Oops sorry. Will have a look soon.



Le 28 déc. 2015 20:17, à 20:17, Suncatcher <notifications@github.com> a écrit:

**Comment by nicosomb** [comment]
Sorry to be late. I can't retrieve your email on hello@wallabag.org. 
Do you still need to delete all your articles?

**Comment by acutbal** [comment]
Hi!!

Yes, please, could you delete all my articles?

Thank you very much!! 😀

Enviado desde mi Nexus 6

**Comment by nicosomb** [comment]
@acutbal Done.

**Comment by acutbal** [comment]
Thank you very much!!

Best regards!! 😁😁

Enviado desde mi Nexus 6

**Comment by Suncatcher** [comment]
Well, my articles are still **NOT** deleted. 4 monthes have passed.

**Comment by nicosomb** [comment]
As I said, I didn't find your email. What is your username? 

4 months have passed, I know. I don't see where the problem is.

**Comment by Suncatcher** [comment]
My username Suncatcher (https://www.framabag.org/u/Suncatcher/). I didn't find where can I specify email in Framabag config. There is no such field, only for new user.

**Comment by Suncatcher** [comment]
> I don't see where the problem is.

The problem is closely connected to issue [#97](https://github.com/wallabag/android-app/issues/97)
In order to reproduce/solve this issue I need to fully clean my article list and resync it again.

**Comment by nicosomb** [comment]
@Suncatcher Done.

**Comment by Suncatcher** [comment]
Great! Thanks!
