### ISSUE TITLE
reset account

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1507]
reset with choice : 
- delete all notes
- delete all entries
- delete all tags

**Comment by Suncatcher** [comment]
Greatly support my own initiative:)

**Comment by nicosomb** [comment]
With the user deletion done by @j0k3r, the main part of this issue is done I think.

**Comment by j0k3r** [comment]
I've started working on a real reset account.
Should be available in the 2.2.0 as soon as I finish it.

**Comment by Suncatcher** [comment]
You'd better update the documentation with the structure of default SQLite tables until automatic reset is not implemented.
Following [this hint](http://support.wallabag.org/discussions/questions/264-deleting-all-articles) I dropped wallabag_tag table my by newbieness and desperately tried to recreated it :) Finally done it but it wasn't obvious.

**Comment by Suncatcher** [comment]
It seems I recreated it wrong. Some import run fine and some throws error:

     Integrity constraint violation: 19 wallabag_entry_tag.tag_id may not be NULL at 
     /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine...

But I definitely **didn't** drop `wallabag_entry_tag` table, only `wallabag_tag` one.

**Comment by tcitworld** [comment]
Well the `wallabag_entry_tag` table won't work if the `wallabag_tag` doesn't exist.

**Comment by Suncatcher** [comment]
> Well the wallabag_entry_tag table won't work if the wallabag_tag doesn't exist.

No, I mean I dropped and then recreated it myself. Other tables weren't touched:
     
**sqlite> .tables**

     wallabag.lexik_maintenance             
     wallabag.wallabag_annotation           
     wallabag.wallabag_config               
     wallabag.wallabag_craue_config_setting  
     wallabag.wallabag_entry                
     wallabag.wallabag_entry_tag            
     wallabag.wallabag_oauth2_access_tokens 
     wallabag.wallabag_oauth2_auth_codes    
     wallabag.wallabag_oauth2_clients       
     wallabag.wallabag_oauth2_refresh_tokens
     wallabag.wallabag_tag                  
     wallabag.wallabag_tagging_rule         
     wallabag.wallabag_user 

**sqlite> pragma table_info(wallabag.wallabag_tag);**

     0|id|int|0||0
     1|label|varchar(100)|0||0
     2|slug|varchar(100)|0||0

**sqlite> pragma table_info(wallabag_entry_tag)**

      0|entry_id|INTEGER|1||1
      1|tag_id|INTEGER|1||2

**sqlite> pragma table_info(wallabag_entry)**

     0|id|INTEGER|1||1
     1|user_id|INTEGER|0|NULL|0
     2|uuid|CLOB|0|NULL|0
     3|title|CLOB|0|NULL|0
     4|url|CLOB|0|NULL|0
     5|is_archived|BOOLEAN|1||0
     6|is_starred|BOOLEAN|1||0
     7|content|CLOB|0|NULL|0
     8|created_at|DATETIME|1||0
     9|updated_at|DATETIME|1||0
     10|mimetype|CLOB|0|NULL|0
     11|language|CLOB|0|NULL|0
     12|reading_time|INTEGER|0|NULL|0
     13|domain_name|CLOB|0|NULL|0
     14|preview_picture|CLOB|0|NULL|0
     15|is_public|BOOLEAN|0|'0'|0

**Comment by Suncatcher** [comment]
Nevertheless, what can you say about my structure: is it correct or not? I get this error again and again:

    "exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0)
    : An exception occurred while executing 'INSERT INTO wallabag_entry_tag (entry_id, tag_id) VALUES
     (?, ?)' with params [51, null]: \n\nSQLSTATE[23000]: Integrity constraint violation: 19
     wallabag_entry_tag.tag_id may not be NULL at 
    /var/www/html/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:54,
    Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation:
    19 wallabag_entry_tag.tag_id may not be NULL at 
    /var/www/html/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, 
    PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19
    wallabag_entry_tag.tag_id may not be NULL at 
    /var/www/html/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} 

If not, how can I reset DB structure without full reinstall? Or how can I migrate to Postgres without reinstall?

**Comment by j0k3r** [comment]
The structure looks ok.

If you want to export your data, you can use the export feature to export article and associated tags.
Configuration & annotations aren't exportable (for now).

Once you exported your stuff you need to create a new instance of wallabag using postgres and import the exported file into it.

**Comment by Suncatcher** [comment]
I don't want to migrate the content (it's simpler to import it from Pocket again), I just want to switch to Postgres.
I already have Postgres server installed and running on my EC2 instance.
What steps should I perform to switch to it? In my view I suppose to edit some Wallabag conf-files.
I am **NOT** very familiar with Symphony and PHP (and it is understatement), so could you please give me exact steps?

**Comment by j0k3r** [comment]
- `rm -rf var/cache/*`
- edit `app/config/parameters.yml` and write down information to connect to postgres, something like:

 ```yaml
      database_driver: pdo_pgsql
      database_host: localhost # change that
      database_port:
      database_name: wallabag_test # change that
      database_user: travis # change that
      database_password: ~ # change that
      database_path: ~
 ```
- launch `php bin/console wallabag:install -e=prod`
- follow instruction and then open homepage

If you encountered more problems please open a new issue instead of continuing on this one.
