### ISSUE TITLE
[v2] Account activation link returns 404

### ISSUE THREAD

**Issue by Adam24** [wallabag/wallabag#1508]
When a user registers on v2 demo, the activation link returns a 404 error, preventing user from registering.

**Comment by nicosomb** [comment]
Hello @Adam24 !

I think you already enable your account, that's why you have a 404.
I just made a test and it seems to work. 
But if you click on my activation link now, you have a 404 http://v2.wallabag.org/register/confirm/F6R2lrdqkqhmSooUyQ1VnjF8cvSXcxwuzJYKDZnyDzQ

**Comment by Adam24** [comment]
I tried to login to my newly made account and it said my account is
disabled.

On Tuesday, November 3, 2015, Nicolas Lœuillet <notifications@github.com>
wrote:

> Hello @Adam24 <https://github.com/Adam24> !
>
> I think you already enable your account, that's why you have a 404.
> I just made a test and it seems to work.
> But if you click on my activation link now, you have a 404
> http://v2.wallabag.org/register/confirm/F6R2lrdqkqhmSooUyQ1VnjF8cvSXcxwuzJYKDZnyDzQ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wallabag/wallabag/issues/1508#issuecomment-153389544>.
>


-- 
--Adam Robertson-- (write back)

**Comment by nicosomb** [comment]
What is your login?

**Comment by Adam24** [comment]
AdamTheMinccino

On Tue, Nov 3, 2015 at 2:50 PM, Nicolas Lœuillet <notifications@github.com>
wrote:

> What is your login?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wallabag/wallabag/issues/1508#issuecomment-153484146>.
>



-- 
--Adam Robertson-- (write back)

**Comment by j0k3r** [comment]
@nicosomb any news about that?

**Comment by nicosomb** [comment]
Since this issue, I dropped the v2.wallabag.org database, so this account doesn't exist anymore.
