### ISSUE TITLE
Wallabag\CoreBundle\Entity\Entry object not found. 

### ISSUE THREAD

**Issue by metasystem** [wallabag/wallabag#1512]
:P You will hate me I think ^^
Already on debian jessie ^^
I don't know if i do post on symfony github or yours...
(Sinon au passage, vous préférez peut-être en français? ^^)

>    INFO - Matched route "view".
    DEBUG - Read existing security token from the session.
    DEBUG - SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.locked AS locked_9, t0.expired AS expired_10, t0.expires_at AS expires_at_11, t0.confirmation_token AS confirmation_token_12, t0.password_requested_at AS password_requested_at_13, t0.roles AS roles_14, t0.credentials_expired AS credentials_expired_15, t0.credentials_expire_at AS credentials_expire_at_16, t0.id AS id_17, t0.name AS name_18, t0.created_at AS created_at_19, t0.updated_at AS updated_at_20, t0.authCode AS authCode_21, t0.twoFactorAuthentication AS twoFactorAuthentication_22, t0.trusted AS trusted_23, t24.id AS id_25, t24.theme AS theme_26, t24.items_per_page AS items_per_page_27, t24.language AS language_28, t24.rss_token AS rss_token_29, t24.rss_limit AS rss_limit_30, t24.user_id AS user_id_31 FROM `wallabaguser` t0 LEFT JOIN `wallabagconfig` t24 ON t24.user_id = t0.id WHERE t0.id = ?
    DEBUG - User was reloaded from a user provider.
    DEBUG - Notified event "kernel.request" to listener "Nelmio\CorsBundle\EventListener\CorsListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DumpListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Wallabag\CoreBundle\EventListener\LocaleListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "FOS\RestBundle\EventListener\BodyListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Nelmio\ApiDocBundle\EventListener\RequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Liip\ThemeBundle\EventListener\ThemeRequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Scheb\TwoFactorBundle\Security\TwoFactor\EventListener\RequestListener::onCoreRequest".
    DEBUG - SELECT t0.id AS id_1, t0.title AS title_2, t0.url AS url_3, t0.is_archived AS is_archived_4, t0.is_starred AS is_starred_5, t0.content AS content_6, t0.created_at AS created_at_7, t0.updated_at AS updated_at_8, t0.comments AS comments_9, t0.mimetype AS mimetype_10, t0.language AS language_11, t0.reading_time AS reading_time_12, t0.domain_name AS domain_name_13, t0.preview_picture AS preview_picture_14, t0.is_public AS is_public_15, t0.user_id AS user_id_16 FROM `wallabagentry` t0 WHERE t0.id = ?
    ERROR - Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Wallabag\CoreBundle\Entity\Entry object not found." at /root/wallabag/app/cache/dev/classes.php line 7312
    DEBUG - Notified event "kernel.request" to listener "Nelmio\CorsBundle\EventListener\CorsListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DumpListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Wallabag\CoreBundle\EventListener\LocaleListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "FOS\RestBundle\EventListener\BodyListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Nelmio\ApiDocBundle\EventListener\RequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Liip\ThemeBundle\EventListener\ThemeRequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Scheb\TwoFactorBundle\Security\TwoFactor\EventListener\RequestListener::onCoreRequest".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke".
    INFO - Defining the initRuntime() method in the "form" extension is deprecated. Use the `needs_environment` option to get the Twig_Environment instance in filters, functions, or tests; or explicitly implement Twig_Extension_InitRuntimeInterface if needed (not recommended).
    INFO - Defining the getGlobals() method in the "assetic" extension is deprecated without explicitly implementing Twig_Extension_GlobalsInterface.

**Comment by j0k3r** [comment]
English is fine.
Are you going to an unknown url ? Like you only have one entry in your database and manually rewrite the url to try to see entry with id 50, `/view/50` ?

In that case, it just says it can't find the requested entry. And since there is no id in the stacktrace, I can't tell you which entry wallabag is trying to get.

**Comment by metasystem** [comment]
I'm deleting entry in wallabag...
After this error, entry is deleted, but each time I want to delete one, I have this error...

**Comment by j0k3r** [comment]
You mean, after deleting an entry, you are redirected to the view page of the deleted entry?

**Comment by metasystem** [comment]
I mean after deleting an Intel on wallabag I have this error (I don't know what this error mean). But when I reload, item is correctly removed...
I can create access to test if you want...

**Comment by nicosomb** [comment]
Do you have a cache system on your webserver?

**Comment by metasystem** [comment]
@nicosomb I only use command "php app/console server:run" actually to try wallabag 2 .
I don't have experience in web server, so if you wan't more info, it would be great to say me where I have to search... ^^

**Comment by nicosomb** [comment]
Wow, same bug for me when I was trying #1478. Just deleted an entry, and 404, because I was redirected to the entry.

**Comment by j0k3r** [comment]
@nicosomb https://github.com/wallabag/wallabag/commit/18d5f4541e1b3eea9926497e082724807453fc8c :frog:

**Comment by nicosomb** [comment]
Sorry :-( Will fix it.

**Comment by metasystem** [comment]
hum, I keep this config, waiting for fix...
I'm not pressed... wallabag v2 seems to be very interesting, so I think it is valid to wait for...
