### ISSUE TITLE
Bad credentials response when trying logging into v2

### ISSUE THREAD

**Issue by BrnLng** [wallabag/wallabag#1513]
I'm just an user from v1 trying to access v2. Credentials still work on v1, but on v2 it won't. Any ideas on what can I do?

**Comment by tcitworld** [comment]
v1 and v2 don't use the same database system so you can't just login from one another, you have to recreate an account on v2. And importing entries from v1 to v2 is *nearly* ready : #1443

**Comment by BrnLng** [comment]
ah, thanks! (I'm sorry I must have missed this info before coming here.) Anyway, will v1 have it's data exported to v2 (including accounts) in the future?

**Comment by tcitworld** [comment]
All Framabag accounts will be migrated automatically, if that's what you mean. Of course, we'll release the 3rd party migration tool. However, I'm not sure using such a tool will be faster that recreating your account by hand in v2 and importing entries into it.

**Comment by BrnLng** [comment]
Thanks! It's just that I was not sure if I'm better using the same username or a new one (would they later merge and possibly mismatch)? Anyway, I decided creating a new one because v1's has low number of things and I just exported all as epub, so I'm satisfied!

**Comment by tcitworld** [comment]
> Anyway, I decided creating a new one because v1's has low number of things and I just exported all as epub, so I'm satisfied!

If you want to import it later in v2, you need to export it as json (in config panel).

**Comment by BrnLng** [comment]
Thanks for the information and all the attention! :+1:
