### ISSUE TITLE
Display the base URL for syncing on the config page

### ISSUE THREAD

**Issue by khinsen** [wallabag/wallabag#1514]
Mobile apps that want to sync with Wallabag need a URL pointing to a Wallabag instance. It is not always obvious to a user what this URL must be. As I [found out](https://github.com/wallabag/android-app/issues/118) trying to configure the Android app, Wallabag instances on Framabag require `/u/username` as part of the URL, whereas I had expected this postfix to be appended by the Android app (after all, it asks me for my username).

The most reliable source for the base URL is the server, so I suggest displaying it on the config page, right next to the feed token.

**Comment by tcitworld** [comment]
I will transform framabag.org URLs in framabag.org/u/user URLs.

**Comment by j0k3r** [comment]
Can this issue be move to the Android app repo?

**Comment by nicosomb** [comment]
This issue was moved to wallabag/android-app#190
