### ISSUE TITLE
"stay signed in" do not work

### ISSUE THREAD

**Issue by FM33** [wallabag/wallabag#1515]
Hello,
On Framabag, if I check "stay signed in" box, I am forced to reconnect a few hours later. Cookies are allowed, but there is no attempt to create one.
Firefox 42 Ubuntu 14.04
Firefox 41 Android 4.4

**Comment by tcitworld** [comment]
Hi,
[This](http://doc.wallabag.org/en/Administrator/sessions.html) should have been fixed a while ago, maybe it's only a server misconfiguration. However, we don't make any more modifications on v1.x and therefore it will only be fixed when v2.0 comes out on Framabag.

**Comment by HLFH** [comment]
So we'll wait for v2.0.

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
