### ISSUE TITLE
Unable to retrieve full-text content (http://blog.xebia.fr/)

### ISSUE THREAD

**Issue by HLFH** [wallabag/wallabag#1516]
Salut,

J'ai l'erreur *Unable to retrieve full-text content* sur l'article http://blog.xebia.fr/2015/11/18/retour-sur-dockercon-eu-2015-12/

Merci,
HLFH

**Comment by j0k3r** [comment]
Which version are you using? Framabag? You own server with v1? with v2?

**Comment by HLFH** [comment]
I'm using version 1.9.1 of Wallabag, found on http://wllbg.org/latest.
I'm using my own ArchLinux server. My HTTP/2 server is Nginx 1.9.7 and it's running with php-fpm 5.6.15.

**Comment by j0k3r** [comment]
Thanks for these information :+1:

**Comment by HLFH** [comment]
@j0k3r So, should I migrate to 2.0.0-alpha.0 or does this article not work on this alpha version?

**Comment by j0k3r** [comment]
I've quickly checked and it seems it doesn't work either on the v2. Will work on it later

**Comment by j0k3r** [comment]
This will be soon be available in the v2. Not ETA yet.
