### ISSUE TITLE
Fatal error: Call to undefined function session_get_cookie_params() in wallabag-1.9.1-b/inc/3rdparty/Session.class.php on line 59

### ISSUE THREAD

**Issue by spitfire** [wallabag/wallabag#1519]
In the last stable version of wallabag (1.9.1-b) after configuring it in the browser, I'm being greeted with:
"Fatal error: Call to undefined function session_get_cookie_params() in wallabag-1.9.1-b/inc/3rdparty/Session.class.php on line 59"

I'm installing it in a FreeBSD 9.3-RELEASE-p28 (r288272+4d913dc) jail. I've already tried configuring it with sqlite and MariaDB.

**Comment by tcitworld** [comment]
I'm not familiar with FreeBSD, but it seems to me you have to install [`php55-extensions`](https://www.freshports.org/lang/php55-extensions) to get session support (and much more that is needed for wallabag).

**Comment by spitfire** [comment]
@tcitworld thanks for the hint - I was missing php56-session.
