### ISSUE TITLE
Indiegogo - Pardon Our Interruption / blocked by www.distilnetworks.com

### ISSUE THREAD

**Issue by HLFH** [wallabag/wallabag#1520]
Hi,

I was trying to add https://www.indiegogo.com/projects/2016-ces-winner-revolutionary-auto-tracking-robot#/ to my Wallabag.
![indiegogo block](https://cloud.githubusercontent.com/assets/2359059/11492398/1bea1d0c-97ed-11e5-879b-7b730388cf46.PNG)

They linked [to this support article](https://support.distilnetworks.com/customer/portal/articles/1842381-third-party-browser-plugins-that-block-javascript), but it does not seem to help... I'm also using uBlock Origin but because it's Wallabag that is doing the work and not directly my browser, I don't think this support article really helps.

**Comment by j0k3r** [comment]
Wallabag version 1.9.x ?

**Comment by HLFH** [comment]
Version 1.9.1.

> Btw, why do you have a # before the last /? The indiegogo link is built like that with ‘#/' at the end at least for me on Windows 10 and Chrome ‘46.0.2490.86 m (64-bit)‘.

You sexy workaround does not work on Wallabag 1.9.1?

So, the question is, should I consider to migrate to 2.0.0-alpha.0 that is only alpha version and hasn't be updated a release since September 14?

**Comment by j0k3r** [comment]
Well, I wouldn't recommend to upgrade to v2 at the moment. We are not even in beta stage to ensure current work won't break in the future. The next alpha took much time than we excepted because of lack of free time from us. Sorry about that.

Hum no this doc is only to update v1.x.

**Comment by j0k3r** [comment]
Sadly after an other try, the whole content page is loaded using an ajax query, so we won't be able to retrieve content for indiegogo .. 
I've no idea how Pocket deal with that but Readability can't handle it too.
