### ISSUE TITLE
Upload article from browser

### ISSUE THREAD

**Issue by iav** [wallabag/wallabag#1525]
Pull articles for selected servers not from wallbag server, but upload to wallabag server content already in browser. It a way to store dynamic pages (possible - one-time generated), adblock and other page-modification addons work results, authorisation-required sites (not all sites accept just html login-password auth).
Like as result of a "print" function.

**Comment by j0k3r** [comment]
This is something we already think about. 
There are few things to improve before being able to do that.

But this is definitively something we'll look into in the future. I thing we'll release v2 first and see what can we do about that.

**Comment by tcitworld** [comment]
Follow at #438.

**Comment by Burning-Daylight** [comment]
Strongly support this request, the most wanted feature for me.

**Comment by j0k3r** [comment]
This will be available in the 2.3 (https://github.com/wallabag/wallabag/issues/1634) so browser extension will have to be updated to send the whole html instead of only the url of the article.

**Comment by Pofilo** [comment]
@j0k3r I can't figure out if the browser extension have been updated to send the whole html through the API or not yet ... Do you know if it is the case ?

**Comment by j0k3r** [comment]
@Simounet 👆

**Comment by Simounet** [comment]
@Pofilo I'm sorry but it's not. I didn't know it was possible to send content through the API. If I understood correctly, I can give the content to the `/api/entries` through a `POST` with the `content` param and that's it @j0k3r?

**Comment by j0k3r** [comment]
@Simounet That's right, see https://github.com/wallabag/wallabag/pull/3106

**Comment by matejdro** [comment]
Is there an issue for the browser extension part of this?

**Comment by Simounet** [comment]
@matejdro It's already shipped with wallabagger. Should see a text field in the options page you can fill in with domain want to get the content from the browser.
