### ISSUE TITLE
Problems with my migration from Instapaper

### ISSUE THREAD

**Issue by acutbal** [wallabag/wallabag#1527]
Hi!!
First of all I apologize for my English, it's not my language so I'll try to do my best.

I'm a new Wallabag user, I'm migrating from Instapaper. I use framabag to store my data. After creating my account I've imported my data from Instapaper with an HTML file. Here I get a 504 error, I've refreshed and the articles started to appear. But after a while I get another error (I attach a screenshot).

Then I tried to import again my data but still have the same error, i think that messed up all. I've tried to delete cache but this doesn't fix the problem. 

How could I delete all the data imported? I've searched the option but didn't find. Perhaps delete all my account and creating a new one could be a better solution?

Thank you very much and best regards!!
![captura de pantalla de 2015-12-07 14-03-48](https://cloud.githubusercontent.com/assets/2278584/11629174/dc431ab4-9cf6-11e5-9ab8-198439d7883c.png)

**Comment by nicosomb** [comment]
Hello @acutbal!

Thank you for your issue. 
We are working on wallabag v2, and on a new import system. 
The current one (for wallabag v1) won't be improved. Sorry for that.

**Comment by acutbal** [comment]
Hi @nicosomb 

Thank you very much for the info!! :smile: I understand perfectly, I like wallabag so I'll wait for wallabag v2.

Meanwhile, I would like to delete my framabag account and restart again the process. Could it be possible?

Best regards!!

**Comment by nicosomb** [comment]
You can contact framabag support here https://contact.framasoft.org/#framabag ;-)
