### ISSUE TITLE
[v2] Duplicate tags when 2 rules match article

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1528]
On a fresh install, I created 2 rules : 
* `if « content matches "spurs" » then tag as « sport »`
* `if « content matches "basket" » then tag as « sport »`

If I add this article `http://www.lequipe.fr/Basket/Actualites/Les-san-antonio-spurs-humilient-les-sixers-sur-leur-parquet/614569` (only one rule matches with this article), it creates 2 tags `sport`. 

ping @K-Phoen

**Comment by K-Phoen** [comment]
I'll look into it.

**Comment by j0k3r** [comment]
@nicosomb in fact, both rules match the content because you have some urls inside the content that contains "Basket". Also there were a bug when adding same new tag multiple times.
