### ISSUE TITLE
atteres.org's articles not displayed

### ISSUE THREAD

**Issue by AugierLe42e** [wallabag/wallabag#1532]
An example [here](http://www.atterres.org/article/budget-2016-les-10-m%C3%A9prises-lib%C3%A9rales-du-gouvernement).

**Comment by j0k3r** [comment]
You mean, the whole content isn't displayed or it is half displayed? Since it seems that the content is truncated because we need to pay to see the full article.

**Comment by AugierLe42e** [comment]
Better explained with an image:

![screen shot 2015-12-12 at 21 56 02](https://cloud.githubusercontent.com/assets/3429231/11763847/2b9d8d42-a11b-11e5-81ad-5b122f6f9461.png)

No need to pay the site is entirely free.

**Comment by j0k3r** [comment]
Looks like it's working now using the 2.0.0
