### ISSUE TITLE
Unable to retrieve full-text content (http://www.yellow-bricks.com)

### ISSUE THREAD

**Issue by Ygster** [wallabag/wallabag#1533]
For example the same page with this url : http://feedproxy.google.com/~r/YellowBricks/~3/tIuZPtve-wU/
and this url http://www.yellow-bricks.com/2015/12/11/healthcheck-plugin-requires-drs/

**Comment by j0k3r** [comment]
The connection seems to timeout when I called it using something else but a browser .. weird.

**Comment by Ygster** [comment]
I tried both links with wallabag v2.0.3 and all worked fine, so I close the issue.
