### ISSUE TITLE
json export doesn't work

### ISSUE THREAD

**Issue by ertyz** [wallabag/wallabag#1534]
Wallabag 1.9.1
Ubuntu 14.04 (Linux 3.19 x64)
MySQL (MariaDB 10.1.9 x86_64) + php-fpm (5.5.9) + nginx (1.8.0)
500MB free ram and 2GB swap.

Import ~500 articles from pocket works fine for me, but

After I press export link, browser immediately gives me to download empty json file. It is always 0 bytes. 

I didn't see anything in nginx or php5-fpm logs.
Does wallabag write own log files? What I need to try?

**Comment by ertyz** [comment]
I was try to create new user account. Export work fine on it. Some ram memory restrictions maybe? I got at least 500MB free ram and 2GB swap.

**Comment by ertyz** [comment]
I was trying:
in index.php
> ini_set("memory_limit","256M");

and nothing happen.

Change in php-fpm.ini
> log_level = debug

in config.inc.php
> define ('DEBUG_POCHE', TRUE);

in nginx/error.wallabag.log i see only that debug message:

> 2015/12/14 06:06:30 [error] 2105#0: *37 FastCGI sent in stderr: "PHP message: DEBUG POCHE : storage type mysql" while reading response header from upstream, client: 172.17.1.2, server: , request: "GET /?export HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "mydomain.com", referrer: "http://mydomain.com/?view=config

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.

**Comment by Strubbl** [comment]
I have the same issue. I want to move on to v2, but an export always gets me 0 bytes sized file. Is there some console version to export my data as json?

**Comment by ymage** [comment]
Same issue here.
I am OK with 1.x stop moving but you based your upgrade process on this 1.x export/2.x import.
Maybe you could take a look anyway.

**Comment by tcitworld** [comment]
We'll release a 1.9.2 version which will hopefully fix these issues.

**Comment by nicosomb** [comment]
@ymage you can follow this issue https://github.com/wallabag/wallabag/issues/1747

**Comment by jinnko** [comment]
1.9.2 doesn't resolve the issue.  The documentation states the migration is as easy as export from v1 and import into v2, but that doesn't work and it takes a fair amount of digging to find this ticket and #1747.

The only method I found to work is benediktg's [wallabag-migration](https://github.com/benediktg/wallabag-migration) script.

Effectively you're giving your loyal users and contributors a hard time.  Not cool.  I don't think anyone really minds what approach to take, as long as the documented approach works.
