### ISSUE TITLE
Unable to retrieve readable content http://habrahabr.ru/

### ISSUE THREAD

**Issue by Aligator77** [wallabag/wallabag#1541]
Find problem with url like http://habrahabr.ru/post/$someNumber/ and http://habrahabr.ru/company/$someCompany/blog/$someNumber/, but if use rss link part of content was grab, example link - http://habrahabr.ru/rss/post/$someNumber/.
At first time, i think this was problem with ru locale, but i was wrong, i think problem in -> 'default_parser' => 'libxml'.

**Comment by j0k3r** [comment]
Could you give us real link instead of `$blablabla`? It'll ease the debugging :)

_Yep I don't speak russian_

**Comment by Aligator77** [comment]
http://habrahabr.ru/post/274129/
http://habrahabr.ru/post/274633/
http://habrahabr.ru/company/emc/blog/274245/
http://habrahabr.ru/company/hexlet/blog/274257/
http://habrahabr.ru/rss/post/274245/
http://habrahabr.ru/rss/post/274251/
http://rsport.ru/hockey/20160111/889155389.html
Prev. links do not work, but it works - http://www.gazeta.ru/sport/2016/01/11/a_8015351.shtml

**Comment by Aligator77** [comment]
I did a few tests and concluded that the part of the site can provide such an error because they think client is a bot and give ban. Maybe for advanced users make the settings so they could choose to use a browser?
And wallabag not support charset windows-1251.

**Comment by Aligator77** [comment]
Thank you, everything works fine!

**Comment by ANAT01** [comment]
> And wallabag not support charset windows-1251.
How to add (how posible?) support of content in charset windows-1251 ?
