### ISSUE TITLE
v2 – Remove user reference in Tag entry ?

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#1543]
Since we've added a slug in the Tag entry which is unique, we got awful slug when user use the same tag label.

Here is an example with some fixtures:

id | user_id | label | slug
------------ | ------------ | ------------ | ------------
1 | 2 | foo | foo
2 | 2 | bar | bar
3 | 1 | foo | foo-1
4 | 1 | bar | bar-1

As you can see, we got `foo-1` as slug, it can goes pretty far, since we can then have `foo-4893` for a slug. I don't really that.

That's why I'm wondering if we can remove the user assignation in that entry.

1. If we need to retrieve all tags for a user, we can join over Entry & EntryTag to retrieve them
2. We will have unique slug with a cleaner value
3. Removing a tag for user will only have to remove lines in EntryTag

What do you think?

**Comment by nicosomb** [comment]
:+1:

**Comment by bdunogier** [comment]
I don't have much perspective on this, but it does make sense to deduplicate things here.
