### ISSUE TITLE
Wrong display in wallabag

### ISSUE THREAD

**Issue by fodiator** [wallabag/wallabag#1548]
URL
http://www.konradlischka.info/2016/01/blog/wie-ein-deutsches-start-up-mit-wagniskapital-die-marktluecke-fuer-lokalen-digitaljournalismus-schliessen-will/

Wallagab displays just an enpty entry instead of article 

Version
    1.9.1

**Comment by j0k3r** [comment]
Thanks for the report.
This is already fixed in the v2.
