### ISSUE TITLE
delete item in page n, go back to page 1

### ISSUE THREAD

**Issue by dattaz** [wallabag/wallabag#1551]
information of instance : framabag

if i delete an item in every page n (and n!=1) after i'm being redirect to page 1.
I think i should go back to page n (or n-1 if page n become empty)

**Comment by he7d3r** [comment]
:+1: 
It should update the page on place, without moving things around unnecessarily, so that it is easier to delete many entries (e.g. duplicated entries caused by https://github.com/wallabag/wallabag/issues/1502).

**Comment by j0k3r** [comment]
We need to check if that bug exist in the v2 branch.

**Comment by nicosomb** [comment]
In v2: we are redirected to the same page. So if we are on the last page and we delete the last item, ... 404 appears.
