### ISSUE TITLE
no title in epub

### ISSUE THREAD

**Issue by dattaz** [wallabag/wallabag#1552]
When a generate epub, when i have a summary, but I doesn't know when article is finish and a other start because there is no title in the top of article.
I think each article in epub, should have title, and content of the article.

**Comment by j0k3r** [comment]
By any chance, did you tried on the export feature of the v2 ? Just to be sure the bug is still here

**Comment by dattaz** [comment]
I have try but fail : see #1567

**Comment by j0k3r** [comment]
@dattaz and since you finally fixed your problem, does the epub seems correct?

**Comment by nicosomb** [comment]
ping @dattaz

**Comment by dattaz** [comment]
Sorry for this long time without news.
I have try with v2: (commit 0aafb8dfcb098ae586dc87f3487b4948f8ae2314)
- no cover page
-no summary
- no title for article 
:(

**Comment by j0k3r** [comment]
Which article did you import?

**Comment by dattaz** [comment]
http://sebsauvage.net/links/?0FdWjA and http://lehollandaisvolant.net/?d=2016/02/01/17/10/37-petit-mot-sur-google-password-manager title are correct in wallabag

**Comment by tcitworld** [comment]
There's an issue with PHPePub. The first (or only) article to be exported won't show up because the two first chapters (meaning the TOC and the first article) have the same id in the `book.ops` file.

**Comment by j0k3r** [comment]
@tcitworld should we open an issue https://github.com/Grandt/PHPePub/issues ?

**Comment by tcitworld** [comment]
Workaround is starting the IDs at one, but I can't find why it doesn't work with it at zero. 
`$this->chapterCount = 1;` at line 1302 (for version 4.0.3)

**Comment by nicosomb** [comment]
Not sure if @Grandt still works on PHPePub. Maybe we can fix this issue with your workaround, @tcitworld.

**Comment by tcitworld** [comment]
Well, the latest activity is from last November. I've seen worse.

**Comment by Grandt** [comment]
I'm not gone. Just ... busy :P

I'll see if I can get some time this week.

**Comment by nicosomb** [comment]
Nice. Don't worry, we can move our issue to an other milestone



Le 15 févr. 2016 22:37, à 22:37, "Asbjørn Grandt" <notifications@github.com> a écrit:

**Comment by j0k3r** [comment]
@Grandt Do you plan to cut a new release with the fix about chapter?

**Comment by tcitworld** [comment]
I got the latest version through composer today. Will look out to see if the issue's gone.

**Comment by nicosomb** [comment]
@tcitworld any news about this issue please?

**Comment by tcitworld** [comment]
There's another bug (https://github.com/Grandt/PHPePub/issues/37) I've found, but apart from that, the original issue is fixed. 

Also, phpEPub now requires php-exif.
