### ISSUE TITLE
epub export doesn't work on v2

### ISSUE THREAD

**Issue by dattaz** [wallabag/wallabag#1567]
error : Attempted to call function "imagecreatefromstring" from namespace "PHPePub\Core". 
![screen capture](https://cloud.githubusercontent.com/assets/6572195/12244686/220adac2-b8a5-11e5-806c-de1601f96c47.png)
pdf export work well

**Comment by dattaz** [comment]
correction : apt-get install php5-gd

**Comment by tcitworld** [comment]
Strange, php5-gd should have been a requirement.

**Comment by j0k3r** [comment]
We can add `ext-gd: "*"` in composer.json, I wasn't aware that we need GD to generate epub file

**Comment by tcitworld** [comment]
Pictures are regenerated when locally stored, I don't remember if the epub generating library was needing GD too.
