### ISSUE TITLE
MarkDown Texts

### ISSUE THREAD

**Issue by TheBigfoot** [wallabag/wallabag#1569]
Wallabag Version: 1.9.1

Hello,
I have added yesterday a markdown document to wallabag (https://raw.githubusercontent.com/ansible/ansible/stable-2.0/CHANGELOG.md) and it resulted in a very long line of text. No linebreaks were rendered.

I'm not expecting a complete markdown renderer, but at least having the linebreaks would be awesome.

**Comment by j0k3r** [comment]
Have you tested on the v2? Because it seems to work fine for me: http://v2.wallabag.org/view/685

**Comment by TheBigfoot** [comment]
I haven't tested it on v2, but as you proofed, it will be working in Release 2, I will gladly wait for this Release.

Thanks!
