### ISSUE TITLE
[v2] 404 page

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1570]

**Comment by j0k3r** [comment]
I've started working on that part but I've found a strange bug in LiipThemeBundle. We'll keep digging.

By the way, what do we want to display on the error page? The left menu? Ability to add a new content? Or just a styled error page with a big button to come back to the homepage?

**Comment by nicosomb** [comment]
> Or just a styled error page with a big button to come back to the homepage?

It's enough I think (the same 404 for each theme)
