### ISSUE TITLE
[v2] Ease installation at maximum

### ISSUE THREAD

**Issue by jjanvier** [wallabag/wallabag#1575]
Hello wallabag team. Thanks for your great app :) The v2 is amazing :)

To ease installation for beginners/newcomers I think it would relevant to delete a lot of parameters that are asked during the process. Personnally I found the install process a little bit too long and I didn't find useful to have all these parameters. 

I think the following parameters should be set directly in the `config.yml`:
```
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    warning_message: "You're trying wallabag v2, which is in alpha version. If you find a bug, please have a look to <a href=\"https://github.com/wallabag/wallabag/issues\">our issues list<
/a> and <a href=\"https://github.com/wallabag/wallabag/issues/new\">open a new if necessary</a>\n"
    download_pictures: true
    share_twitter: true
    share_mail: true
    share_shaarli: true
    shaarli_url: 'http://myshaarli.com'
    share_diaspora: false
    diaspora_url: 'http://diasporapod.com'
    flattr: true
    carrot: true
    show_printlink: true
    export_epub: true
    export_mobi: true
    export_pdf: true
    wallabag_url: 'http://v2.wallabag.org'
    wallabag_support_url: 'https://www.wallabag.org/pages/support.html'
    items_on_page: 12
    theme: material
    from_email: no-reply@wallabag.org
    rss_limit: 50
    pocket_consumer_key: xxxxxxxx
```

Also the test database parameters could be dropped from the installation.

And IMHO, all these parameters could be in a wallabag section of the config.yml instead of being root parameters. That would help to clearly identify what can be customized for people that install the app.

I can do a PR if you're interested.

**Comment by nicosomb** [comment]
I think you're righ. All PR is welcome.

**Comment by j0k3r** [comment]
Funny, I just tried your command you updated in the README and I then was thinking about removing all _non_-parameters from the parameters.yml.dist :)

**Comment by j0k3r** [comment]
In fact, I think most of that stuff should be in config that an admin can access. So if admin wants to be able to share to twitter, (s)he activates that feature. etc ..

**Comment by nicosomb** [comment]
That's why we need a full dashboard in v2
