### ISSUE TITLE
Composer?

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#1576]
Hi

I want to install v2 but the doc talks about some app called composer. I am on Debian Wheezy and no Composer available. Do you mind giving hints on this?

It looks like this has moved away from php stuff. So a bit confusing :( hopefully for good.

**Comment by tcitworld** [comment]
Hi,

Please have a look at this page : https://getcomposer.org/doc/00-intro.md

**Comment by j0k3r** [comment]
Thanks @jjanvier, the README file now include a link to composer and how to install it.
