### ISSUE TITLE
Reading mode

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1577]
As Firefox does (and Pocket I think), we can propose a bookmarklet/addon/what you prefer to switch to a reading mode when we are on an article. The article is not stored in your wallabag, we only called [j0k3r/graby](https://github.com/j0k3r/graby) to fetch content and display it.

**Comment by j0k3r** [comment]
Could you describe the user steps to achieve that? Is it from a browser extension? From Wallabag itself?

**Comment by nicosomb** [comment]
Maybe from a browser extension. 

* you are reading an article on lexpress.fr
* you want to hide advert, comments, etc. You click on your browser addon
* you are in a reading mode, like when you click on reading mode in firefox.

**Comment by nicosomb** [comment]
Duplicate of https://github.com/wallabag/wallabag/issues/730.
