### ISSUE TITLE
Fix articles

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#1578]
Hello !
Quelques problèmes : 
http://www.alterecoplus.fr/chronique/y%25c3%25a1nis-varouf%25c3%25a1kis/les-deux-devises-de-la-grece-201601140700-00002872.html
http://www.becomingminimalist.com/most-popular-posts/

avec un fixe pour revues.org

```
# Generated by FiveFilters.org's web-based selection tool
# Place this file inside your site_config/custom/ folder
# Source: http://siteconfig.fivefilters.org/grab.php?url=http%3A%2F%2Fespacepolitique.revues.org%2F284

body: //div[@id='text']
test_url: http://espacepolitique.revues.org/284
strip_id_or_class: paranumber
```

**Comment by j0k3r** [comment]
@qwertygc You can submit the fix here: https://github.com/fivefilters/ftr-site-config

**Comment by tcitworld** [comment]
Article 1 works perfectly on v2. However the URL is saved as http://www.alterecoplus.fr/chronique/y%c3%a1nis-varouf%c3%a1kis/les-deux-devises-de-la-grece-201601140700-00002872.html by wallabag, and therefore doesn't work anymore when I click on Original URL (special character `á` is to blame). We should look into it and maybe report this behaviour to the original website.

Article 2 doesn't work.

**Comment by j0k3r** [comment]
First link is ok to me.
Second one needed a dedicated config file.
