### ISSUE TITLE
Unable to retrieve readable content http://www.firstthings.com

### ISSUE THREAD

**Issue by shackra** [wallabag/wallabag#1579]
For instance, this article cannot be retrieved http://www.firstthings.com/web-exclusives/2013/04/mother-teresa-and-her-critics

**Comment by tcitworld** [comment]
Works properly on v2 : http://v2.wallabag.org/view/818

**Comment by shackra** [comment]
I'm framabag.org user, that means anything? 

El 14 de enero de 2016 14:10:37 CST, Thomas Citharel <notifications@github.com> escribió:
>Works properly on v2 : http://v2.wallabag.org/view/818
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wallabag/wallabag/issues/1579#issuecomment-171766096

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tcitworld** [comment]
Since we'll reimport all entries when we'll update framabag from v1 to v2, your entry will automatically be updated with content then.

**Comment by tcitworld** [comment]
Well, for me it works also on v1 (framabag). Strange.
