### ISSUE TITLE
[v2] Nginx official support?

### ISSUE THREAD

**Issue by HLFH** [wallabag/wallabag#1585]
Hi,

I'm using the v2 branch. I'm on a dedicated server. And for wallabag, I'm using ArchLinux, Nginx, MariaDB and PHP-FPM with PHP 7.

I did 
```bash

git clone https://github.com/wallabag/wallabag.git -b v2
cd wallabag
composer install
php bin/console wallabag:install
php bin/console server:run
```

But then,

When I launched my wallabag website, I got:
> You are not allowed to access this file. Check app_dev.php for more information.

So I don't know what to do to solve this issue. Is there any official Nginx support? And is a systemd file now needed for the v2?

My Nginx configuration was working with 1.9.1 version, but I don't know what to change to make it fully work with the v2 alpha 1.

**Comment by j0k3r** [comment]
Have you tried to access /app.php instead?

**Comment by HLFH** [comment]
I got HTTP 500 error with app.php.

**Comment by j0k3r** [comment]
Alright, open `web/app_dev.php`, and comment line 17/18.
Then go to `/app_dev.php` and report the error here (or fix the problem if you can)

**Comment by tcitworld** [comment]
Wait, when you're using `php bin/console server:run`, you're using php's build-in server, not nginx. So nginx shouldn't be started and your wallabag installation will be available at `yourserver:8000`. Then you'll be able to follow [this tutorial](http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#apache-with-php-fpm).

**Comment by HLFH** [comment]
@j0k3r I commented line 17/18. I went to `/app_dev.php`, then I logged.

Then...this is the stacktrace:

> 1] Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET //quickstart" (from "https://read.hlfh.space/app_dev.php/login")
    at n/a
        in /srv/http/wallabag/var/cache/dev/classes.php line 1970

    at Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))
        in  line 

    at call_user_func(array(object(RouterListener), 'onKernelRequest'), object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))
        in /srv/http/wallabag/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php line 61

    at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher))
        in  line 

    at call_user_func(object(WrappedListener), object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher))
        in /srv/http/wallabag/var/cache/dev/classes.php line 1754

    at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent))
        in /srv/http/wallabag/var/cache/dev/classes.php line 1672

    at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', object(GetResponseEvent))
        in /srv/http/wallabag/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php line 132

    at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))
        in /srv/http/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 120

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /srv/http/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 62

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /srv/http/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 169

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /srv/http/wallabag/web/app_dev.php line 30

[2] Symfony\Component\Routing\Exception\ResourceNotFoundException: 
    at n/a
        in /srv/http/wallabag/var/cache/dev/appDevUrlMatcher.php line 603

    at appDevUrlMatcher->match('//quickstart')
        in /srv/http/wallabag/var/cache/dev/classes.php line 1357

    at Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(object(Request))
        in /srv/http/wallabag/var/cache/dev/classes.php line 1226

    at Symfony\Component\Routing\Router->matchRequest(object(Request))
        in /srv/http/wallabag/var/cache/dev/classes.php line 1954

    at Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))
        in  line 

    at call_user_func(array(object(RouterListener), 'onKernelRequest'), object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))
        in /srv/http/wallabag/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php line 61

    at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher))
        in  line 

    at call_user_func(object(WrappedListener), object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher))
        in /srv/http/wallabag/var/cache/dev/classes.php line 1754

    at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent))
        in /srv/http/wallabag/var/cache/dev/classes.php line 1672

    at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', object(GetResponseEvent))
        in /srv/http/wallabag/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php line 132

    at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))
        in /srv/http/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 120

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /srv/http/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 62

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /srv/http/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 169

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /srv/http/wallabag/web/app_dev.php line 30

@tcitworld You're right, I did `php bin/console server:run`, but if I would prefer to use directly Nginx, I used this command because [it was shown in your blog](https://www.wallabag.org/blog/2016/01/08/wallabag-alpha1-v2). I'm happy I didn't have to use it. So, I'm now trying to use Wallabag v2 with Nginx.

It's my nginx configuration:

> server {
    listen 80;
    server_name read.hlfh.space;
    return 301 https://$server_name$request_uri;
}
server {
    listen 443 ssl http2;
    server_name read.hlfh.space;
    # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
    ssl_certificate /etc/ssl/nginx/ssl-unified.pem;
    ssl_certificate_key /etc/ssl/nginx/ssl.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
    ssl_dhparam /etc/ssl/nginx/dhparam.pem;
    # modern configuration. tweak to your needs.
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AE
SGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA
:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
    ssl_prefer_server_ciphers on;
    # Add headers to serve security related headers
    # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload";
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    # OCSP Stapling ---
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;
    ## verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /etc/ssl/nginx/ocsp.pem;
    resolver 8.8.8.8;
    # Path to the root of your installation
    root /srv/http/wallabag/web/;
    # set max upload size
    client_max_body_size 10G;
    fastcgi_buffers 64 4K;
    index index.php app.php;

    error_log /var/log/nginx/wallabag_error.log;
    access_log /var/log/nginx/wallabag_access.log;

    location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        fastcgi_param modHeadersAvailable true;
        #Avoid sending the security headers twice
        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_intercept_errors on;
    }
}
```

I don't know at all if it's right to configure it like that...

**Comment by HLFH** [comment]
I updated my Nginx configuration:

```nginx
server {
    listen 80;
    server_name read.hlfh.space;
    return 301 https://$server_name$request_uri;
}
server {
    listen 443 ssl http2;
    server_name read.hlfh.space;
    # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
    ssl_certificate /etc/ssl/nginx/ssl-unified.pem;
    ssl_certificate_key /etc/ssl/nginx/ssl.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
    ssl_dhparam /etc/ssl/nginx/dhparam.pem;
    # modern configuration. tweak to your needs.
    ssl_protocols TLSv1.2;
    ssl_ciphers EECDH+AESGCM:ECDHE-RSA-AES256-SHA384;
    ssl_ecdh_curve secp384r1;
    ssl_prefer_server_ciphers on;
    # Add headers to serve security related headers
    # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload";
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    # OCSP Stapling ---
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;
    ## verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /etc/ssl/nginx/ocsp.pem;
    resolver 8.8.8.8;
    # Path to the root of your installation
    root /srv/http/wallabag/web;
    # set max upload size
    client_max_body_size 10G;
    fastcgi_buffers 64 4K;
    index index.php;

    error_log /var/log/nginx/wallabag_error.log;
    access_log /var/log/nginx/wallabag_access.log;

    location / {
        try_files $uri @rewriteapp;
    }

    location @rewriteapp {
        # Ici on réécrit toutes les URL de telle sorte qu'elles pointent vers
        # le fichier app.php
        # Dans mon cas, mon installation était pour un environnement de
        # développement, j'ai donc remplacer app.php par app_dev.php
        rewrite ^(.*)$ /app.php/$1 last;
    }

    location ~ ^/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;
    }
}
```

I imported the JSON from a wallabag v1 instance, and it works. But I'm using the URL: https://read.hlfh.space/app_dev.php and I wondered if I could use instead https://read.hlfh.space without app_dev.php. Furthermore, I would love use app.php and not app_dev.php ; but I'm having HTTP 500 errors with app.php.

**Comment by j0k3r** [comment]
Here is the [nginx configuration from the Symfony website](http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#nginx).
You might need to update yours.

**Comment by j0k3r** [comment]
@HLFH thanks for reporting that bug! It wasn't related to Nginx at all it was a naughty bug that only appear in _prod_ environment.

**Comment by HLFH** [comment]
@j0k3r Yes I understood it later. Thanks a lot for the PR!
