### ISSUE TITLE
[v2] Import from wallabag v2

### ISSUE THREAD

**Issue by HLFH** [wallabag/wallabag#1590]
Hi,

I have a wallabag instance using the last v2 branch.
I want to import a JSON file from another wallabag v2 instance.

And apparently, [JSON import is not supported yet](https://github.com/wallabag/wallabag/blob/v2/docs/en/user/import.rst#from-html-or-json-file).

Do you plan to support it?

Thanks!
HLFH

**Comment by tcitworld** [comment]
Indeed, only json from wallabag v1 instances is currently supported. As written in the documentation, it will of course be supported.

**Comment by nicosomb** [comment]
I changed the title, because we can also implement CSV and XML import from v2 instance.
