### ISSUE TITLE
Can we please get some proper migration guides for v2?

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#1595]
Hi

I finally get v2 up and running. Well the thing is how do I migrate my databases to this? How do I run it under Apache? Am I even able to run this under apache? Does it have to be a separate server?

It would be helpful if we have some preliminary V2 migration guides otherwise it is a like a blank page for a user like me and I have no idea aboutt his Ruby stuff. Last time I needed to use Ruby for Redmine, it was dreadful ;(

**Comment by tcitworld** [comment]
> How do I run it under Apache? Am I even able to run this under apache? Does it have to be a separate server?

Of course you can use Apache ! For now a documentation isn't yet available (hey, this is alpha ;-) ), but you can follow the Symfony documentation for now : http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html

> It would be helpful if we have some preliminary V2 migration guides otherwise it is a like a blank page for a user like me and I have no idea about his Ruby stuff.

The Ruby stuff (capistrano) is mostly for the moment for us to deploy and update Framabag easily. It's not intended to be the main or only way to install wallabag.

**Comment by gerroon** [comment]
thanks for the follow up

**Comment by gerroon** [comment]
Btw which folder do I point to access to the actual Wallabag installation? We have the index.php in the root folder  with the previous version. I do not see anything anywhere to access to the actual app in apache setup.

**Comment by tcitworld** [comment]
As the page I linked to above says, Apache needs the `web/` directory as DocumentRoot (the .htaccess file redirects to app.php instead of a simple index.php file). That's how it works.

**Comment by j0k3r** [comment]
Added here: https://github.com/wallabag/wallabag/pull/1818
