### ISSUE TITLE
Trouble because of proxy.

### ISSUE THREAD

**Issue by 22decembre** [wallabag/wallabag#1596]
So, I installed Wallabag stable (this time it succeed, really). I have yet a big big fail/trouble and I suppose it will happen on th v2, reason why I mention it.

My hosting :
 Openbsd 5.8, self hosted

any other parameters irrelevant to the case, almost no trouble at install, Postgre, fine.

Using the openbsd httpd server, I have a weird web conf in which the webserver itself listen on ::1 port 2002, unencrypted. The real encryption(tls/ssl) job is done on the usual https port by haproxy.

This leads wallabag to give me these url for all things related:

http://blackblock.22decembre.eu:2002/wallabag/themes/baggy/css/font.css

Whereas, obviously, If asking https://blackblock.22decembre.eu/wallabag/themes/baggy/css/font.css, no trouble…

I have some pain describing it correctly, yet it is obviously a real trouble, as you imagine. I am available for any more information needed.

**Comment by tcitworld** [comment]
Nous parlons français, ça sera plus simple à expliquer. :-)

**Comment by 22decembre** [comment]
Ouais, ok, mais t'as quand même compris le schmilblik… (j'ai déscendu d'un niveau de langage aussi par la même occaz'…).

**Comment by tcitworld** [comment]
Du coup le souci c'est bien que wallabag sert les assets (css, images, js...) en http au lieu de https avec ton proxy ?

**Comment by 22decembre** [comment]
oui mais surtout sur le port 2002 (alors que c'est seulement un port utilisé à pour la conf' du serveur web).

**Comment by 22decembre** [comment]
Wallabag detecte que le serveur web écoute sur ::1 2002 et met toutes ses ressources en url dessus. Alors que concretement, l'utilisateur (moi) l'utilise sur un port web banal (https 443).

**Comment by tcitworld** [comment]
> Wallabag detecte que le serveur web écoute sur ::1 2002 et met toutes ses ressources en url dessus.

wallabag ne détecte rien du tout. wallabag v1 n'est qu'un amas de fichiers php tout bêtes exécutés par un serveur. Je ne connais pas haproxy, mais peut-être que les options associées aux ports et aux proxy dans ce fichier de configuration te sauveront : https://github.com/wallabag/wallabag/blob/master/inc/poche/config.inc.default.php

NB : La v2 marche assez différemment, donc je ne pense pas que tu aies forcément le même problème dans le futur.

**Comment by 22decembre** [comment]
Effectivement, en modifiant un truc, (l'adresse de base) alors ça résout tout problème.

Ce qui est bizarre, c'est que j'ai piwigo, qui a quasiment la même conf' (port different, et mysql au lieu de postgre) mais qui ne me fait pas ce truc là.

**Comment by tcitworld** [comment]
C'est la v1, on cherche plus. :D

**Comment by 22decembre** [comment]
Oui en effet. C'est pour ça j'ai clos.
