### ISSUE TITLE
[v2] Client ID/secret

### ISSUE THREAD

**Issue by jangernert** [wallabag/wallabag#1597]
Feels weird to ask this in a bug report, but irc-channel seems pretty dead and also got no reply to the mail I sent to hello@wallabag.org. And since there was this statement at the end of the oAuth2 blog-post
> If you have some problems with the API, feel free to create a new issue on GitHub.

So I want to support a "share article to wallabag" feature in my RSS-Reader. How do I get a client_id and client_secret for this?
Your blog-post says:
> As we are still in alpha, we create a client for you (but in few weeks, each application will have its own client id and client secret).

But the tokens in the post didn't work anymore
>client_id=1_3bcbxd9e24g0gk4swg0kwgcwg4o8k8g4g888kwc44gcc0gwwk4
>client_secret=4ok2x70rlfokc8g0wws8c8kwcokw80k44sg48goc0ok4w0so0k

results in 

> "The client credentials are invalid"

So how do I test my code with v2.wallabag.org?
thx

**Comment by nicosomb** [comment]
Hello @jangernert!

Sorry I received your email last week and I have to reply to it. 
We need a web interface to generate tokens (#1589).

**Comment by jlnostr** [comment]
So, if I understand you correctly, there's no way at the moment to perform API requests?

**Comment by rosenstrauch** [comment]
How about on self hosted instances?  Is there an api and a way to create client keys there?

**Comment by wstrinz** [comment]
I'd also like to know at least a workaround for setting the key/secret on self hosted instances. Going to dig around myself and see what I can find

**Comment by nicosomb** [comment]
You can try the new PR #1675. Fo to /developer and you can create a new client. 
It's a very very first draft. Tell me your needs.

**Comment by jangernert** [comment]
So how do I do this on v2.wallabag.org?
The Wallabag profile on G+ stated that the feature is live on v2.wallabag.org
http://v2.wallabag.org/developer just gives me a 404
Thx :)

**Comment by jlnostr** [comment]
What do you think about pre-defined pairs of ID and secret? I think this could reduce the user frustration if the main wallabag apps are working out-of-the-box without additional configuration. Maybe just one pair should be defined for all wallabag apps.

**Comment by tcitworld** [comment]
> I think this could reduce the user frustration if the main wallabag apps are working out-of-the-box without additional configuration.

I think if you can afford time to set up your own instance of wallabag, you can have time to create your pair of tokens for each client. However, I see your point, and it can be discussed.

**Comment by jlnostr** [comment]
It could be interesting for all the framabag users out there.

**Comment by tcitworld** [comment]
In the case of Framabag of course we would configure ourselves the client tokens.

**Comment by jangernert** [comment]
So do I understand this correctly?
If I would have my own instance of wallabag on my server and wanted to use 3rd party applications with it, I would have to create a ID and a secret for each of the apps in wallabag and configure the apps to use these ID's and secrets. Then I would still need my username and password to log in to wallabag from the app?
That sounds WAY to complicated for the average user =/

**Comment by 0wnrepo** [comment]
Are we targeting average users at this point ?

**Comment by tcitworld** [comment]
> Then I would still need my username and password to log in to wallabag from the app?

The app should just redirect to the wallabag server, asking to the user to allow the app for this account, and that's it.

Thing is, the easy way with OAuth, as we described it in [this blog post](https://www.wallabag.org/blog/2015/10/06/developers-oauth2), meaning that the app asks for your login and password before sending them to the wallabag server, leads to the fact that the 3rd party app HAS access to your credentials, and it kicks quite a bit the interest of OAuth.
I mean, *kind-of official* approved apps could use this way to connect themselves, but it's quite an issue for the other ones.

**Comment by foxmask** [comment]
we have to distinguish 2 things : 

* the oAuth process that permits to third party app to get credentials from his wallabag account
* the oAuth process that permits to log in to wallabag

Personnally I'm concerned by the first one that I think it's a must have, the second one depends on all of you at wallabag project. The main pro of it (when we do not host our own wallabag instance), is to avoid to have to create a new account to another tool. Otherwise, if we are ready to install an instance of wallabag on our own server, it is not important to us to deal with "ho I have to create a new account grr It's not possible blabla" .
