### ISSUE TITLE
[v2] Import of v1 JSON export to v2.wallabag.org fails

### ISSUE THREAD

**Issue by ddeimeke** [wallabag/wallabag#1598]
I get an "500 Internal Server Error" when trying to import a v1 export to v2.wallabag.org.

**Comment by nicosomb** [comment]
Hello @ddeimeke!

What is the size of your JSON file?

**Comment by ddeimeke** [comment]
Hi @nicosomb 

2.87 MB (3'019'709 bytes)

**Comment by nicosomb** [comment]
It's because our PHP config allows 2Mo max per file. I will change this value.

**Comment by ddeimeke** [comment]
Thank you (BTW: my ownCloud-Instance allowes 513 MB),

Maybe setting the value to 10 MB is a good idea.

**Comment by nicosomb** [comment]
We changed the upload limit. Can you try again please?

**Comment by ddeimeke** [comment]
Worked perfectly well.

Many Thanks!
