### ISSUE TITLE
[v2] syntax problem with v2 export

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1600]
I don't know what the problem is, but when I export some entries to reimport them in wallabag v2 (new feature #1590), the json_encode failed and json_last_error returns 4 (see `JSON_ERROR_SYNTAX` http://php.net/manual/fr/function.json-last-error.php). 

I will have a look to my json file after.

**Comment by tcitworld** [comment]
I don't even manage to import a single json entry. Can't find why.

**Comment by nicosomb** [comment]
Maybe you can try with another entry

**Comment by tcitworld** [comment]
Sorry, I meant I have tried with multiple, diverse entries and it didn't work with any of them. ;-)

**Comment by nicosomb** [comment]
Can't reproduce the problem. I tried with many many entries ...
