### ISSUE TITLE
Wallabag V2 : PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Debug\\Exception

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#1609]
Hello

I have been trying to install v2 alpha. I believe that I setup the Virtual host as described. I still get errors. Xxx are there to hide private information.

The server works on the custom server that comes with Symphony.

```
NameVirtualHost *:xxx
<VirtualHost *:xxx>
    ServerName xxxx.com
    DocumentRoot /var/www/wallabag_v2/web
    <Directory /var/www/wallabag_v2/web>
            Options Indexes FollowSymLinks Includes
                AllowOverride All
                Order Allow,Deny
                Allow from All

        </Directory>

                SSLEngine on
                SSLCertificateFile /xxxxxx/server.pem
                SSLCertificateKeyFile  /xxxxxx/server.key

                SSLOptions +StdEnvVars

                SetEnvIf User-Agent ".*MSIE.*" \
                      nokeepalive ssl-unclean-shutdown \
                      downgrade-1.0 force-response-1.0

                ErrorLog /var/log/apache2/wallabag_error.log
            CustomLog /var/log/apache2/wallabag_access.log combined

</VirtualHost>
```

PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Catchable Fatal Error: Argument 2 passed to Wallabag\\UserBundle\\Mailer\\AuthCodeMailer::__construct() must be an instance of Symfony\\Component\\Translation\\DataCollectorTranslator, instance of Symfony\\Bundle\\FrameworkBundle\\Translation\\Translator given, called in /var/www/wallabag_v2/app/cache/prod/appProdProjectContainer.php on line 2207 and defined' in /var/www/wallabag_v2/src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php:59\nStack trace:\n#0 /var/www/wallabag_v2/src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php(59): Symfony\\Component\\Debug\\ErrorHandler->handleError(4096, 'Argument 2 pass...', '/var/www/wallab...', 59, Array)\n#1 /var/www/wallabag_v2/app/cache/prod/appProdProjectContainer.php(2207): Wallabag\\UserBundle\\Mailer\\AuthCodeMailer->__construct(Object(Swift_Mailer), Object(Symfony\\Bundle\\FrameworkBundle\\Translation\\Translator), 'no-reply@wallab...', NULL, 'https://www.wal...')\n#2 /var/www/wallabag_v2/app/bootstrap in /var/www/wallabag_v2/src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php on line 59

**Comment by j0k3r** [comment]
Thanks for reporting that error!

It has been fixed (see https://github.com/wallabag/wallabag/pull/1587) but it's not yet released.
If you want to test it, you can do:

```
composer create-project wallabag/wallabag wallabag 2.x-dev
php bin/console wallabag:install
php bin/console server:run
```
