### ISSUE TITLE
Vendor Package Alpha v2

### ISSUE THREAD

**Issue by UdoKifferbrehl** [wallabag/wallabag#1623]
Hello, you asked me on Facebook to open this issue. Thanks :-)

**Comment by tcitworld** [comment]
There's a zip [here](https://lufi.io/r/KE5AdONLmH#g4pmoORAkIu76TPHR/icAl6eAfocuYAMdExwBDfrqJk=) for you to test.

**Comment by nicosomb** [comment]
If it's OK, please let this PR opened until I store this archive on static.wallabag.org.

**Comment by UdoKifferbrehl** [comment]
Do you have a complete package including the install folder please? The installation did not work.

**Comment by j0k3r** [comment]
@UdoKifferbrehl Hum we don't have an `install` folder in the v2. Are you talking about the v1?

**Comment by tcitworld** [comment]
It's my fault, I had forgotten @UdoKifferbrehl uses shared hosting and can't do `php bin/console wallabag:install`.
Can this command be called from a browser, or do I have to provide the whole directory installed ?

**Comment by j0k3r** [comment]
@tcitworld we need to think about it but it'll be hard I guess ..

**Comment by nicosomb** [comment]
We provide a package for each release.
