### ISSUE TITLE
Wallabag demo website gives Bad credentials

### ISSUE THREAD

**Issue by Jaczel** [wallabag/wallabag#1626]
The demo site for [Wallabag v2.0](http://v2.wallabag.org/login) gives a ```Bad credentials``` error message when logging in with the default username and password: username: wallabag, password: wallabag. Username: poche and Password: poche also does not work (as expected).

Not sure if it is a related issue however the old [Wallabag demo site v1.9](http://demo.wallabag.org/) redirects to the v2.0 website. This has not been updated on the [Try Wallabag Website](https://www.wallabag.org/pages/try-wallabag.html).

**Comment by nicosomb** [comment]
As I just said here (https://github.com/wallabag/wallabag.org/issues/14), I updated the demonstration page on our website:

> These credentials may have changed, but don't worry: you can create a free account on this platform. Please remind that this website is a demonstration website and the database can be dropped at any time.

And about 1.9 demo, see https://github.com/wallabag/wallabag.org/issues/13:

> Now, we only provide one demonstration website, the v2 one.
