### ISSUE TITLE
List all untagged articles

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1631]
To tag all untagged items more easily.

originally at https://twitter.com/bronwyn/status/691674547511123968

**Comment by j0k3r** [comment]
Pocket use a special tag called `_untagged_` to apply this kind of filter: `https://getpocket.com/a/queue/list/_untagged_/`

**Comment by tcitworld** [comment]
What about having a `/untagged/list/{page}` route ?

**Comment by j0k3r** [comment]
Yeah good idea.

**Comment by tcitworld** [comment]
My bad, it's better with a filter instead of a special route.

**Comment by nicosomb** [comment]
> My bad, it's better with a filter instead of a special route.

Can you explain why, please?
