### ISSUE TITLE
Pass content through API when creating an entry

### ISSUE THREAD

**Issue by jcharaoui** [wallabag/wallabag#1634]
It would be useful to be able to send the content when creating an entry using the REST API, as well as being able to set the Starred and Archived states.

**Comment by j0k3r** [comment]
Are you trying to import a bunch of content from an external source to wallabag?
Anyway, it could be a good idea.

**Comment by biva** [comment]
Thank you @tcitworld , I was not skilled enough to understand the connection.

Is there any way (except coding, as I'm not skilled for that) I can help? Is 2.1.0 still scheduled to release this feature?

And by the way, is there already an issue to add the feature of copy/paste content into wallabag? For example a part of a PDF, or something I copy on a web page? Or can I create it?

**Comment by tcitworld** [comment]
There's nothing like that for now.
It will all go into the same work (API and web interface). 

I don't think this will go in the 2.1 release (we already should have shipped it by now), but it should follow.

**Comment by tcitworld** [comment]
@biva We'll certainly need testing when it will be ready, though. :-)

**Comment by Zlitus** [comment]
Hello.

It’s can be great if we can pass some specific fields in the POST request. For example if I can send specifically the title / body / author / …

For example:

POST /api/entries.{_format}
url=https://www.nextinpact.com/news/104101-plongee-dans-wallabag-alternative-libre-a-pocket.htm
title=Plongée dans Wallabag, alternative libre à Pocket
author=Vincent Hermann
publicationDate=2017-04-28
body=<p><b>Après Pocket et Instapaper, nous avons plongé nos mains dans wallabag</b>, un gestionnaire de liens open source. La philosophie du service est très différente des deux premiers et il sera plus délicat de le comparer, même si le cœur des fonctionnalités est bien le même.</p>…
fullhtml=<html><head>…
tags=Pocket,Wallabag

Just an example with some extra-fields.

**Comment by Zlitus** [comment]
Another extra-field can be `recheck`, to indicate “All the useful content is already send in the POST request, don’t launch Grabby on this URL and just add that in Wallabag”:
```
POST /api/entries.{_format}
url=http://…
title=My great news
author=Superman
publicationDate=2017-05-03
body=<p>Text content of the news</p>
recheck=false
```
