### ISSUE TITLE
Change databases name for mysql/pgsql in test environment

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1635]
We defined `wallabag` as a name for test database. We need to change this value.

https://github.com/wallabag/wallabag/blob/v2/app/config/tests/parameters.yml.dist.mysql#L15

**Comment by j0k3r** [comment]
Why ?

**Comment by nicosomb** [comment]
To avoid "content conflicts" with existing database. The name is not `wallabag_test` but `wallabag` ... It will destroy my dev database.
