### ISSUE TITLE
[v2] can't add link on mobile view with material design

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1636]
The add button is not displayed

**Comment by tcitworld** [comment]
Either we make the buttons appear as long as there's space, like this :

![capture d ecran 2016-01-30 a 16 33 23](https://cloud.githubusercontent.com/assets/2197836/12696598/3e78bc32-c76f-11e5-8f87-2dffd91a5441.png)           ![capture d ecran 2016-01-30 a 16 32 54](https://cloud.githubusercontent.com/assets/2197836/12696597/3e70435e-c76f-11e5-810a-8601ef0779ba.png)

or either we create a direct menu entry that redirects to the `/new` form.

**Comment by nicosomb** [comment]
The first option seems good to me.
