### ISSUE TITLE
[Fx 44 Ext 2.0.0] Cannot save login&password anymore

### ISSUE THREAD

**Issue by FM33** [wallabag/wallabag#1637]
Hello,
Each time I restart Firefox, I have to re-login and firefox do not ask for saving password anymore.
Using wallabag extension 2.0.0 with Firefox 44 and framabag.org

**Comment by nicosomb** [comment]
Hello @FM33!
Do  you check the "remember me" checkbox on framabag.org?

**Comment by FM33** [comment]
Yes I do. Auto-filling works from framabag.org, but not from the extension ("bag it!" button). Since the extension icon has no dropdown menu I have to go to framabag.org using other way. Then the extension can handle the login previously set.

**Comment by nicosomb** [comment]
OK, so it's due to wallabag 1.9.x ... It will be fixed in v2.
