### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1640]
In his dashboard (see #1638), a user can delete its account. 

@j0k3r @tcitworld do we need to send a confirmation email here?

**Comment by j0k3r** [comment]
I don't think so.
We can like Github did when you want to delete a repo, just ask at least twice to the user that (s)he is going to remove its account and it can not be undo.

**Comment by nicosomb** [comment]
Good idea :+1:

**Comment by zertrin** [comment]
A typical solution to that is to ask the user to type a string like `yes_delete` or `<username>` as a confirmation. This can't be easily done by mistake and force the user to really read the information given on the warning.

For example GitLab has it when deleting a project and it looks like this:

![fewnuiafhewil](https://cloud.githubusercontent.com/assets/1447163/12721869/30b5ae68-c902-11e5-9897-35b2c8fd8fdf.png)

Something similar but with the username could be done for Wallabag.

**Comment by j0k3r** [comment]
@zertrin yeah it almost the same as Github: 

![](https://cloud.githubusercontent.com/assets/62333/12721958/b3cc0a72-c902-11e5-8301-2ed6a61d0ec5.png)

**Comment by zertrin** [comment]
Oh ok, I didn't try that in GitHub yet, so didn't know they are so close from each other. Sorry for the noise then.

**Comment by nicosomb** [comment]
FYI, @delyriand is working on this feature (it's just to say to other contributors that it's not necessary to work on this feature)

**Comment by nicosomb** [comment]
@delyriand need some help to finish this feature?

**Comment by tcitworld** [comment]
@delyriand @nicosomb Any news on this ?

**Comment by nicosomb** [comment]
FYI, I think this feature is no more WIP.

**Comment by j0k3r** [comment]
One user can't deleted its own account.

**Comment by nicosomb** [comment]
So we can close this issue?

**Comment by j0k3r** [comment]
Nope.
An administrator can delete a user account.
But need to implement the account deletion on the user side.

**Comment by nicosomb** [comment]
I read "one use can deleted ...". 💤

**Comment by v1kn** [comment]
@j0k3r 
I'd like to ask why this issue was closed? I want to be able to have my wallabag account completely deleted, yet I cannot do it, because:

> You are the only user, you cannot delete your own account

Who can delete my account then? I use framabag

**Comment by j0k3r** [comment]
Framabag isn't running wallabag 2, but wallabag 1.
poke @tcitworld

**Comment by v1kn** [comment]
@j0k3r  thank you

@tcitworld 
I'd like to be able to have my wallabag account in `framabag` completely deleted, yet I cannot do it, because:

    You are the only user, you cannot delete your own account

Can You point me in the right direction?

**Comment by nicosomb** [comment]
@v1kn you need to contact Framasoft suppor https://contact.framasoft.org/

**Comment by v1kn** [comment]
Thank You I will try
