### ISSUE TITLE
reflets.info articles : unable to retrieve full-text content

### ISSUE THREAD

**Issue by roylockhart** [wallabag/wallabag#1649]
It concerns every articles I tried so far.

**Comment by j0k3r** [comment]
Are you trying on the v1 or the v2 ?
On the v2 the content looks good to me.

**Comment by roylockhart** [comment]
Well, good news I guess, I'm using v1.9.1 !

I guess we can close this then ?  
closes #1649

**Comment by Simounet** [comment]
Sorry but I still have this issue on 2.0.5 .

**Comment by j0k3r** [comment]
@Simounet could you please provide an example?
Just tried on a [random article](https://reflets.info/democratie-francaise-le-virage/) and got the content.

![image](https://cloud.githubusercontent.com/assets/62333/15738047/ac9bbb60-28a9-11e6-8efb-00e6c0be9de9.png)

**Comment by Simounet** [comment]
I tried the same and get :  `wallabag can't retrieve contents for this article. Please report this issue to us. `.

**Comment by j0k3r** [comment]
Did you got that problem on the 2.0.4 too?

**Comment by Simounet** [comment]
Before today, I was on 2.0.3 and encountering the same issue.

**Comment by j0k3r** [comment]
We'll check that. Thanks for the feedback

**Comment by Simounet** [comment]
This issue is now related to this one: https://github.com/fivefilters/ftr-site-config/pull/194 .

**Comment by j0k3r** [comment]
So I'll close the issue.
This update will be available in the next release !
Thanks
