### ISSUE TITLE
Error installing on windows 7

### ISSUE THREAD

**Issue by 0wnrepo** [wallabag/wallabag#1669]
1.Download php 5.6 from http://windows.php.net/downloads/releases/php-5.6.18-Win32-VC11-x86.zip

2.Unzip 

3.Open php.ini-production and add :
```
extension = php_openssl.dll
extension = php_curl.dll
extension_dir = "ext"
```
4.save as php.ini
5.Download and install https://getcomposer.org/download/
6.Open cmd.exe and create a new folder where your installation will reside, on desktop for example :
```
$ cd Desktop
$ mkdir wallatest
$ cd wallatest
```
7.Set environment variable 
```
set SYMFONY_ENV=prod
```
8.
```
composer create-project wallabag/wallabag wallabag "2.0.*@alpha" --no-dev
```
9.After you finish this step, run 
```
php bin/console wallabag:install --env=prod
```

It will throw an exception :
```
Installing Wallabag...

Step 1 of 4. Checking system requirements.
+---------+--------+----------------+
| Checked | Status | Recommendation |
+---------+--------+----------------+
| PCRE    | OK!    |                |
| DOM     | OK!    |                |
+---------+--------+----------------+
Success! Your system can run Wallabag properly.

Step 2 of 4. Setting up database.
Creating database and schema, clearing the cache
The command "doctrine:database:create" terminated with an error code: 1.


  [Exception]
  The command "doctrine:database:create" terminated with an error code: 1.
```

Any thoughts ?

**Comment by tcitworld** [comment]
Can you run php bin/console doctrine:database:create and post it's output?

**Comment by 0wnrepo** [comment]
```
Could not create database C:\Users\ed\Desktop\testing\wallabag\app/../data/d
b/wallabag.sqlite for connection named default
An exception occured in driver: could not find driver
```

**Comment by tcitworld** [comment]
You need to activate the php_sqlite extension.

**Comment by 0wnrepo** [comment]
First activated php_sqlite3.dll - didn't work
Then activated php_pdo_sqlite.dll - it worked. (i need to see if it's a combination of these, or only the last one)

```date.timezone = "Europe/Paris"
```

It looks like this :
https://imgur.com/n7PT83Z

**Comment by tcitworld** [comment]
Did you do a wallabag:install again ?

**Comment by 0wnrepo** [comment]
Yes, I'll do a fresh install right now..

**Comment by j0k3r** [comment]
Well, it seems you need to install git when composer fail to download the zip package.

Could you try:

```
composer create-project wallabag/wallabag wallabag "2.0.*@alpha" --no-dev --prefer-dist
```

**Comment by 0wnrepo** [comment]
```
[RuntimeException]
An error occurred when executing the ""cache:clear --no-warmup"" command:
 // Clearing the cache for the prod environment with debug false


  [Symfony\Component\Filesystem\Exception\IOException]

  Failed to remove directory "C:\Users\ed\Desktop\testing\wallabag\var\
ca
  che\pro~\annotations".
```

It didn't download anything, it used everything from "cache". How can i reset this, so it always downloads everything ?
```
Installing wallabag/wallabag (2.0.0-alpha.2)
  - Installing wallabag/wallabag (2.0.0-alpha.2)
    Loading from cache
....
```

**Comment by tcitworld** [comment]
The command is `composer clear-cache`.

**Comment by 0wnrepo** [comment]
Should I install git and ignore this path (--prefer-dist) ?

**Comment by j0k3r** [comment]
`2.x-dev` -> latest commits
`2.0.*@alpha` -> latest tagged release (actually alpha2)

We definitely need to package each version with all deps as a zip file. Because I guess we'll get more error like that ...
Looks like you finally found a solution. I'm glad you did!

**Comment by 0wnrepo** [comment]
Aren't the licenses of the deps restrictive for redistribution ?

**Comment by j0k3r** [comment]
I don't really know but I don't think so. Why?

**Comment by 0wnrepo** [comment]
You mentioned :

> We definitely need to package each version with all deps as a zip file.

**Comment by j0k3r** [comment]
We'll need to check that.

**Comment by tcitworld** [comment]
Package | Licence
------------|-----------
behat/transliterator | Artistic 1.0
CraueConfigBundle | MIT
doctrine/annotations | MIT
doctrine/cache | MIT
doctrine/collections | MIT
doctrine/common | MIT
doctrine/dbal | MIT
doctrine/doctrine-bundle | MIT
doctrine/doctrine-cache-bundle | MIT
doctrine/doctrine-migrations-bundle | MIT
doctrine/inflector | MIT
doctrine/instantiator | MIT
doctrine/lexer | MIT
doctrine/migrations | LGPL-2.1
doctrine/orm | MIT
ezyang/htmlpurifier | LGPL
friendsofsymfony/oauth-server-bundle | MIT
friendsofsymfony/oauth2-php | MIT
friendsofsymfony/rest-bundle | MIT
friendsofsymfony/user-bundle | MIT
gedmo/doctrine-extensions | MIT
grandt/binstring | LGPL-2.1
grandt/phpepub | LGPL-2.1
grandt/phpresizegif | LGPL-2.1
grandt/phpzipmerge | LGPL-2.1
grandt/relativepath | LGPL-2.1
guzzlehttp/guzzle | MIT
guzzlehttp/ringphp | MIT
guzzlehttp/streams | MIT
hoa/compiler | BSD-3-Clause
hoa/consistency | BSD-3-Clause
hoa/event | BSD-3-Clause
hoa/exception | BSD-3-Clause
hoa/file | BSD-3-Clause
hoa/iterator | BSD-3-Clause
hoa/math | BSD-3-Clause
hoa/protocol | BSD-3-Clause
hoa/regex | BSD-3-Clause
hoa/ruler | BSD-3-Clause
hoa/stream | BSD-3-Clause
hoa/ustring | BSD-3-Clause
hoa/visitor | BSD-3-Clause
hoa/zformat | BSD-3-Clause
htmlawed/htmlawed | GPL-2.0+ | LGPL-3.0
incenteev/composer-parameter-handler | MIT
j0k3r/graby | AGPL-3.0
j0k3r/graby-site-config | AGPL-3.0
j0k3r/php-readability | Apache-2.0
j0k3r/safecurl | MIT
jdorn/sql-formatter | MIT
jms/metadata | Apache
jms/parser-lib | Apache2
jms/serializer | Apache2
jms/serializer-bundle | Apache2
kphoen/rulerz | MIT
kphoen/rulerz-bundle | MIT
kriswallsmith/assetic | MIT
lexik/form-filter-bundle | MIT
liip/theme-bundle | MIT
mgargano/simplehtmldom | MIT
michelf/php-markdown | BSD-3-Clause
monolog/monolog | MIT
neitanod/forceutf8 | No Licence
nelmio/api-doc-bundle | MIT
nelmio/cors-bundle | MIT
ocramius/proxy-manager | MIT
pagerfanta/pagerfanta | MIT
paragonie/random_compat | MIT
phpcollection/phpcollection | Apache2
phpoption/phpoption | Apache2
phpzip/phpzip | LGPL-2.1
psr/log | MIT
react/promise | MIT
scheb/two-factor-bundle | MIT
sensio/distribution-bundle | MIT
sensio/framework-extra-bundle | MIT
sensiolabs/security-checker | MIT
simplepie/simplepie | BSD-3-Clause
smalot/pdfparser | GPL-3.0
sonata-project/google-authenticator | MIT
stof/doctrine-extensions-bundle | MIT
swiftmailer/swiftmailer | MIT
symfony/assetic-bundle | MIT
symfony/monolog-bundle | MIT
All of Symfony | MIT-licenced
tecnickcom/tcpdf | LGPLv3
twig/extensions | MIT
twig/twig | BSD-3-Clause
wallabag/php-mobi | Apache-2.0
willdurand/hateoas | MIT
willdurand/hateoas-bundle | MIT
willdurand/jsonp-callback-validator | MIT
willdurand/negotiation | MIT
zendframework/zend-code | BSD-3-Clause
zendframework/zend-eventmanager | BSD-3-Clause

Dev package (not for redistribution) | Licence
----------------------------------------------|-----------
doctrine/data-fixtures | MIT
doctrine/doctrine-fixtures-bundle | MIT
phpdocumentor/reflection-docblock | MIT
phpspec/prophecy | MIT
phpunit/php-code-coverage | BSD-3-Clause
phpunit/php-file-iterator | BSD-3-Clause
phpunit/php-text-template | BSD-3-Clause
phpunit/php-timer | BSD-3-Clause
phpunit/php-token-stream | BSD-3-Clause
phpunit/phpunit | BSD-3-Clause
phpunit/phpunit-mock-objects | BSD-3-Clause
sebastian/comparator | BSD-3-Clause
sebastian/diff | BSD-3-Clause
sebastian/environment | BSD-3-Clause
sebastian/exporter | BSD-3-Clause
sebastian/global-state | BSD-3-Clause
sebastian/recursion-context | BSD-3-Clause
sebastian/version | BSD-3-Clause
sensio/generator-bundle | MIT
symfony/phpunit-bridge | MIT

**Comment by j0k3r** [comment]
Seems to be *Revised BSD*, aka **BSD-3-Clause**: https://github.com/neitanod/forceutf8/commit/546fe2b8dfd280764a4d7906c9a9b1dc955eb876

**Comment by tcitworld** [comment]
Yup. So we're good.

**Comment by nicosomb** [comment]
@tcitworld What do we need with this issue? Where can we store your work about dependancies & licenses?

**Comment by tcitworld** [comment]
On the page we were talking about where we could list translators, contributors & dependencies.

**Comment by baptistedonaux** [comment]
Same fail with 2.0.0-beta.1

```
 Fatal error: Uncaught RuntimeException: Setting "wallabag_support_url" couldn't be found. in /wallabag/vendor/craue/config-bundle/Util/Config.php:139 Stack trace: #0 /wallabag/vendor/craue/config-bundle/Util/Config.php(42): Craue\ConfigBundle\Util\Config->createNotFoundException('wallabag_suppor...') #1 /wallabag/src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php(72): Craue\ConfigBundle\Util\Config->get('wallabag_suppor...') #2 /wallabag/var/cache/prod/appProdProjectContainer.php(2214): Wallabag\UserBundle\Mailer\AuthCodeMailer->__construct(Object(Swift_Mailer), Object(Twig_Environment), 'no-reply@wallab...', NULL, Object(Craue\ConfigBundle\Util\Config)) #3 /wallabag/var/bootstrap.php.cache(2103): appProdProjectContainer->getWallabagUser_AuthCodeMailerService() #4 /wallabag/var/cache/prod/appProdProjectContainer.php(1583): Symfony\Component\DependencyInjection\Container->get('wallabag_user.a...') #5 /wallabag/var/bootstrap.php.cache(2103): appProdProjectContainer->getSchebTwoFactor_Security_Email_CodeGeneratorService() #6 in /wallabag/vendor/craue/config-bundle/Util/Config.php on line 139
```

**Comment by j0k3r** [comment]
Care to elaborate a bit more in a separate issue? Thanks
