### ISSUE TITLE
Do not capture mouse gestures

### ISSUE THREAD

**Issue by iamdey** [wallabag/wallabag#1674]
Hello, I usually select text when I'm reading articles on the web.
Unfortunately wallabag captures mouse gestures and let user to go to the next or previous article.

I think it's a bad design and it could be break some user's habits : 
* already defined gestures using external tools (and may be people using accessibility tools)
* selecting text
* may be other

I know this wants to be a "cool" feature that attempt to reproduce native smartphone applications, but we are not always on a smartphone (and I'm not sure this works well on smartphone or touch devices).

Version: 1.9.1
Hoster: framasoft

**Comment by tcitworld** [comment]
Yup, we noticed that. It won't happen on the next version.

**Comment by j0k3r** [comment]
@tcitworld is this enable on the current v2 ?

**Comment by nicosomb** [comment]
nope

**Comment by tcitworld** [comment]
Nope. But maybe we can have touch gestures it without having mouse issues like this.

**Comment by iamdey** [comment]
Great news it's already take in account for v2. Feel free to close this issue so.

Well I don't think adding gesture is good think at all, it's like disabling right click with javascript. It is just bad. Touch gestures are cool with touch devices.

Btw, Thanks for quick answers :)
