### ISSUE TITLE
Feed saved automatically

### ISSUE THREAD

**Issue by 0wnrepo** [wallabag/wallabag#1677]
Hi,

I have a bunch of blogs that I follow and read thoroughly and would like to subscribe and automagically save their newest posts in wally. 

What do you think, is there a need for this ?

**Comment by tcitworld** [comment]
They have been quite a number of demands for this feature. However we always replied that it's more the job of an RSS Reader App. However you never know what will happen in the future.

**Comment by 0wnrepo** [comment]
Ok, this can be closed. Thanks @tcitworld !
