### ISSUE TITLE
Translation string for 'min' in the 'estimated reading time: 10 min'

### ISSUE THREAD

**Issue by mabkenar** [wallabag/wallabag#1682]
![selection_128](https://cloud.githubusercontent.com/assets/3006332/13114209/cde6bab4-d592-11e5-9949-9d85c7c09af3.png)
In RTL languages, the estimated time for reading is displayed wrong. The mix between LTR and RTL words has made the order of the words completely messed up.
It will be better if the word 'min' is also translated into the RTL language (I tested that in my browser).
Is the word 'min' in the screenshot anywhere to be translated?

**Comment by tcitworld** [comment]
min is hardcoded for the moment. I'll add it to the translations later today.
