### ISSUE TITLE
Documentation about translation: which language file is the reference?

### ISSUE THREAD

**Issue by mabkenar** [wallabag/wallabag#1692]
The Persian translation  #1676 was done by duplicating the German file (129 lines) and replacing German strings with Persian translations. Now I see that there are some more strings to translate in the French file (233 lines):
wallabag/src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml 
and the German/Persian translation of those extra strings are missing. 

I suggest to mention this in the **Documentation about translation** that new translations should be done by first copying the French files.

Ideally, there should be an automatic way of adding those extra entries to other languages as they appear in the course of development, e.g. #1683 and #1690 .

**Comment by nicosomb** [comment]
I don't know if a tool like Transifex can help us for this problem. We already discuss about this problem on our internal chat. 
With Transifex, you can see which languages is translated at 100%, which sentences you have to translate, etc. 

@wallabag/core any idea?

**Comment by j0k3r** [comment]
Well, we should be more attentive when we add new translation and add them (with default message) to all translations.
But yes, we should at least say in the Documentation about translation that the most updated one is and will always be the french one.

**Comment by 0wnrepo** [comment]
First of all, let's make it less frustrating: only add translations to one file, because most of the core devs are french, let's stick to that. Next, only add new lines at the end of the paragraph, so we don't need to pick line by line to see if one line was inserted or deleted in each paragraph. 
By paragraph i mean starting with a comment and ending right before the new comment or eof.

```
#comment 

english_name1:'translated term1' 
english_name2:'translated term2'

->>add the new term here.
```

**Comment by nicosomb** [comment]
I opened a new PR with the info about french translation as the reference to translate wallabag.

**Comment by tcitworld** [comment]
Just wondering : shouldn't there be an English translation file ? Logs keep complaining of missing translations for English, it's quite frustrating when you're looking for something useful in the logs. Of course it would bring nothing, but it would be easier for foreigners to translate, starting from this file.

**Comment by nicosomb** [comment]
We'll have english files because @j0k3r wants to change all our translation files by using keys instead of sentences (I will open a new issue for that).

**Comment by tcitworld** [comment]
I agree too.

**Comment by j0k3r** [comment]
Well, I _would_ like :)
