### ISSUE TITLE
Replace sentences by keys in translations file

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1697]
See https://github.com/wallabag/wallabag/issues/1692#issuecomment-185712076

Some good starting point:
- http://jolicode.com/blog/translation-workflow-with-symfony2
- http://developer.happyr.com/how-happyr-work-with-symfony-translations

**Comment by 0wnrepo** [comment]
Give an example of how to do this, and I can pick it up on Tuesday. Or anybody else if it's faster.

**Comment by nicosomb** [comment]
See **Working with translation placeholder / It’s also a good practice to use abstract keys instead of plain string:** here http://jolicode.com/blog/translation-workflow-with-symfony2

**Comment by j0k3r** [comment]
Yeah we just need to define a convention on how we are going to use keys. Like [BUNDLE].[MODULE].[LABEL] or sth else

**Comment by 0wnrepo** [comment]
Just a quick note, not familiar with php, only Objective-C + Android Java + C/C++. Would be nice if you could make an example, and I can pick up from there.

**Comment by nicosomb** [comment]
Good job, @j0k3r!
