### ISSUE TITLE
Ability to redownload previously failed content

### ISSUE THREAD

**Issue by 0wnrepo** [wallabag/wallabag#1704]
### Issue details

If you accidentally unplug your wallabag server from the internet, and you try to download an url contents, it will, naturally, fail. 
Add option to re-download failed content.

### Steps to reproduce/test case

1. Unplug wallabag server from the internet.
2. Attempt to download article -> fail.
3. Reconnect to the internet.
4. Via the "+" button attempt to add a second copy of the url in wallabag. It will fail once more.

### Workaround

After reconnecting to the internet, delete the existing article, then via the "+" button, redownload the content.

### Affected version(s)

v2

**Comment by tcitworld** [comment]
That's correct, because the URL is already in database and therefore isn't fetched again. We should add an exception for Graby to fetch again the content if there wasn't any the last time.

**Comment by j0k3r** [comment]
I haven't tried to reproduce, but if the url is saved, you should be able to clic on the unread article and then, on the left sidebar, you should have a link to re-fetch the content.
