### ISSUE TITLE
cannot import very long article (v2)

### ISSUE THREAD

**Issue by nkoehring** [wallabag/wallabag#1724]
### Issue details

I try to import http://ledger-cli.org/3.0/doc/ledger3.html and it fails with a 500 (log says: readability.php exceeded the maximum execution time of 30s).

Is there any way to speed this up?

### Environment

Wallabag v2.0.0-alpha.2
on Arch Linux ARM
with sqlite database

### Steps to reproduce/test case

try to import http://ledger-cli.org/3.0/doc/ledger3.html

**Comment by j0k3r** [comment]
I agree that article is very long. I guess your server isn't that fast, right?
I tried on two different machine and, apart the fact that it took longer than usual, the content was well imported (http://v2.wallabag.org/view/4870).

I'll see if I can optimized few things on Readability side but I can't guarantee I'll find sth.
In the mean time, can you increase PHP `max_execution_time` on your server?
Also, could you share your server configuration (ram, cpu speed, etc..)

**Comment by tcitworld** [comment]
Is there a way we could timeout the graby query to Readability so that the exception would be caught to avoid a 500 error ?

**Comment by nkoehring** [comment]
It is not a big server. It's a dedicated ARMv7 with 4 cores clocked at 1.3GHz, sporting 2GB of RAM.

**Comment by tcitworld** [comment]
> These long running things should run in the background.

Yup, there's https://github.com/wallabag/wallabag/pull/1581#issuecomment-189371001 to implement this.
