### ISSUE TITLE
timezone error with docker-compose

### ISSUE THREAD

**Issue by DjayDev** [wallabag/wallabag#1726]
Hello,

I've just created the project through the composer command and I had the good surprise to see a docker-compose file.
So with one ```docker-compose up``` I should be able to test this promising application.
But when I start my browser I get the timezone error that most of people using Symfony had one time in his life.
I know that this issue has been already closed (issue #1591 ) when using our own web server configuration.
But here I'm using docker so I would assume to have the timezone fix in the php image.

Personnally I have added directly in the Dockerfile of php the following instruction 
```RUN echo "date.timezone=Europe/Paris" > /usr/local/etc/php/conf.d/date_timezone.ini```
I don't think it's the best but it works...

Thanks for your work.

**Comment by j0k3r** [comment]
Good point and I don't think we can fix it in an other way. Feel free to provide a PR with that change.

Maybe you can use one of these:
- https://github.com/jacksoncage/phppgadmin-docker/blob/master/Dockerfile#L27-L29
- https://github.com/fideloper/docker-nginx-php/blob/master/Dockerfile#L23-L24
