### ISSUE TITLE
readability renders huge share buttons

### ISSUE THREAD

**Issue by nkoehring** [wallabag/wallabag#1729]
### Issue details

Articles from alistapart get huge share icons. It happens on my local version (alpha2) but not on the demo (v2.wallabag.org). See a screenshot: ![screenshot](http://dl.koehr.in/wallabag.jpg).

http://alistapart.com/article/all-talk-and-no-buttons-the-conversational-ui

### Environment

* wallabag version (or git revision) that exhibits the issue: wallabag v2.0.0-alpha2
* Last wallabag version that did not exhibit the issue (if applicable): v2.wallabag.org
* php version: 7.0.3
* OS: Linux 4.4.0 armv7l
* type of hosting: dedicated
* storage system: SQLite

**Comment by j0k3r** [comment]
Thanks for that I'll we fixed in the next beta :wave:
