### ISSUE TITLE
Replace ant to deploy test env

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1735]
Because ant is a java tool (and everyone knows that PHP is better :trollface:), we have to replace ant with a PHP one. 

Some tools:
- https://github.com/Codegyre/Robo
- https://github.com/bldr-io/bldr
- https://github.com/taskphp/task

**Comment by j0k3r** [comment]
Or a bash script.

**Comment by aaa2000** [comment]
There is a `makefile` now, it's not better to use it ?
