### ISSUE TITLE
Only small portion of the website gets saved

### ISSUE THREAD

**Issue by hubertbanas** [wallabag/wallabag#1744]
Only the last part of the article gets parsed

Source location:
http://www.notebookcheck.net/Lenovo-ThinkPad-X1-Carbon-Ultrabook-Review.138033.0.html

Wallabag v2
http://v2.wallabag.org/view/52

**Comment by j0k3r** [comment]
Oh my god the html structure of this website is so crapy ! I can't believe it ...

Anyway, even if the article is really long I successfully extracted most of the content. There is only the first italic paragraph that get wiped out. But it's still better than only the last paragraph

**Comment by j0k3r** [comment]
I'll be fixed in the next release.
Thanks !

**Comment by hubertbanas** [comment]
This is still not fixed in Version: 2.0.0-beta.2

See here:
http://v2.wallabag.org/view/543

**Comment by j0k3r** [comment]
Yeah sorry it'll be fixed in the 2.0.0 (for sure!).
The beta2 was release before [graby-site-config 1.0.15](https://github.com/j0k3r/graby-site-config/releases) which integrate siteconfig for notebookcheck.
