### ISSUE TITLE
v1.9.1: JSON export returns empty file

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#1747]
### Issue details

Wallabag v1.9.1 ; JSON export returns empty file. I have ~900 entries with pictures stored.
### Environment
- wallabag version Wallabag v1.9.1
- wallabag installed Via `composer create-project`
- Last wallabag version that did not exhibit the issue (if applicable): no
- php version: 5.6.17
- OS: debian 8.0 armhf
- type of hosting: dedicated
- storage system MySQL
### Steps to reproduce/test case

config -> export json -> empty file

**Comment by Strubbl** [comment]
seems to duplicate #1534

**Comment by ymage** [comment]
I took a look yesterday night and it seems related to utf8 encoding issue.

**Comment by benediktg** [comment]
Same here, I have an account with about 1250 articles and the export only delivers a 0-byte-sized file.

Is it possible that the export has problems with a big count of articles?

I wonder if it'd be a feasible workaround to extract the article URLs as well as the read and favorite states of a certain user out of the database table `entries` with

```
SELECT `url`, `is_read`, `is_fav` FROM `entries` WHERE `user_id` = '2';
```

and somehow enter this data automatically into the Wallabag v2 account.

**Comment by Rurik19** [comment]
I already did so. There only three sql to migrate from 1.9.1 to 2.0

**Comment by ymage** [comment]
Hi,

The 0-byte-sized file comes from a JSON encoding throwing a JSON_ERROR_UTF8 error.

**Comment by Strubbl** [comment]
@ymage in which file and line is the errors cause (not in the json file, the src creating the json)?

**Comment by blackere** [comment]
In `inc/poche/Tools.class.php` at function `renderJson` the `json_encode` return the message
`unexpected end of data at line 1 column 1 `

**Comment by benediktg** [comment]
@ymage 
> The 0-byte-sized file comes from a JSON encoding throwing a JSON_ERROR_UTF8 error.

The patch from #1866 was applied on the server but it didn't help with the 0-Byte-File – it just did not add any new problems…

**Comment by ymage** [comment]
You're right.
One reason (the one I encountered) for this 0-byte-file was a JSON_ERROR_UTF8 error.
It may have several other reason I did not experienced.

**Comment by tcitworld** [comment]
Version 1.9.2 is out. Please give it a try.

**Comment by Rurik19** [comment]
Unfortunately with 1.9.2 JSON export also doesn't work. Which log should I inspect for details?

**Comment by mourningsun75** [comment]
For me also not working. The File is still 0-byte

**Comment by benediktg** [comment]
Same here – I will try to feed the information of a SQL dump into the new API.

**Comment by blackere** [comment]
I think the problem is still [this](#issuecomment-209859614)

**Comment by Rurik19** [comment]
**benediktg ** your way is wery hard, solution for migration to v2 is just 3 short sql inserts (if you have both databases alongside) - for tags, articles and tags-articles-link

**Comment by benediktg** [comment]
@Rurik19 Is it really that simple? I mean, the database tables have a different structure…

**Comment by Rurik19** [comment]
**benediktg** This three tables only has _additional_ fields, which you can leave empty or fill with some value, like domain - I'v got it from url with regexp

**Comment by blackere** [comment]
Ok, solved for me XD

in `/inc/poche/Database.class.php` at line 41 you can add `$this->handle->exec("SET CHARACTER SET utf8");` or `, array( PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8")`

Previous:
`...
            case 'mysql':
                if (MYSQL_USE_UTF8MB4) {
                    $db_path = 'mysql:host=' . STORAGE_SERVER . ';dbname=' . STORAGE_DB . ';charset=utf8mb4';
                    $this->handle = new PDO($db_path, STORAGE_USER, STORAGE_PASSWORD, array(
                        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8mb4',
                    ));
                } else {
                    $db_path = 'mysql:host=' . STORAGE_SERVER . ';dbname=' . STORAGE_DB;
                    $this->handle = new PDO($db_path, STORAGE_USER, STORAGE_PASSWORD);
                }
                break;
            case 'postgres':
...`

with fix:
`case 'mysql':
                if (MYSQL_USE_UTF8MB4) {
                    $db_path = 'mysql:host=' . STORAGE_SERVER . ';dbname=' . STORAGE_DB . ';charset=utf8mb4';
                    $this->handle = new PDO($db_path, STORAGE_USER, STORAGE_PASSWORD, array(
                        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8mb4',
                    ));
                } else {
                    $db_path = 'mysql:host=' . STORAGE_SERVER . ';dbname=' . STORAGE_DB;
                    $this->handle = new PDO($db_path, STORAGE_USER, STORAGE_PASSWORD, array( PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));
					//or instea of array( PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8")
					//$this->handle->exec("SET CHARACTER SET utf8");
                }
                break;
            case 'postgres':`

**Comment by mourningsun75** [comment]
@blackere: The workaround fixes the problem. but the german umlauts in the title are defect

**Comment by RaphaelSalique** [comment]
I fixed the problem with a function found in the PHP Manual.
I use Wallabag v1.9.2
I added this at the beginning of the inc/poche/Tools.class.php

    function utf8ize($d) {
        if (is_array($d)) {
            foreach ($d as $k => $v) {
                $d[$k] = utf8ize($v);
            }
        } else if (is_string ($d)) {
            return utf8_encode($d);
        }
        return $d;
    }

and I wrote in renderJson static function (around line 238) `echo json_encode(utf8ize($data));`

It worked for me.

**Comment by benediktg** [comment]
Here is my alternative migration script: https://github.com/benediktg/wallabag-migration

**Comment by JimboJoe** [comment]
Migration script from @benediktg worked a treat, thanks!
Using wallabag API instead of SQL import/export makes you benefit from wallabag v2 features (reading time among others) and you have no encoding problems...

**Comment by nicosomb** [comment]
We have a solution (https://github.com/benediktg/wallabag-migration from @benediktg) and v1.x won't be maintained anymore.

**Comment by P3lUZa** [comment]
This is what worked for me:
Just as blackere suggested:
 I edited /inc/poche/Database.class.php
Added a new line at 42: $this->handle->exec("SET CHARACTER SET utf8");

So it should be read:
case 'mysql':
[...]
$this->handle = new PDO($db_path, STORAGE_USER, STORAGE_PASSWORD);
$this->handle->exec("SET CHARACTER SET utf8");
}
break;
case 'postgres':
[...]

Then I got page not found when generating JSON, that was due ram size, 
Then edited wallabag/index.php

And I wrote at the beginning (line 10)
ini_set("memory_limit","512M");

That to increase memory usage as suggested here: #682

**Comment by nicosomb** [comment]
Thank you for your tip. Just for your information, wallabag 1.x is no more maintained.
