### ISSUE TITLE
"Take wallabag with you" disappears

### ISSUE THREAD

**Issue by forteller** [wallabag/wallabag#1751]
### Issue details

When going to http://v2.wallabag.org/new and hovering over a link in the "Take wallabag with you" footer the whole footer disappears.
 
### Environment

http://v2.wallabag.org/

**Comment by j0k3r** [comment]
Which browser are you using?

**Comment by forteller** [comment]
Firefox 41 on Ubuntu Gnome 15.10 64 bit, with Gnome 3.18

**Comment by j0k3r** [comment]
Ok I got the problem too on Firefox 42.

**Comment by tcitworld** [comment]
Having it too. Firefox 40.

**Comment by nicosomb** [comment]
Not with FF44.

**Comment by tcitworld** [comment]
Indeed, can't seem to reproduce it with FF44.

**Comment by nicosomb** [comment]
As it's fixed in Firefox 44, I think you should upgrade your firefox installation.
