### ISSUE TITLE
[v2] Post-installation error with postgresql

### ISSUE THREAD

**Issue by sanpii** [wallabag/wallabag#1752]
Hello,

After installation, I get a blank page due to third party bug: https://github.com/lexik/LexikMaintenanceBundle/issues/53

**Comment by nicosomb** [comment]
You can follow my comment on the issue of the bundle to create the table.



Le 3 mars 2016 20:59, à 20:59, Sanpi <notifications@github.com> a écrit:

**Comment by nicosomb** [comment]
Fixed in [LexikMaintenanceBundle 2.1.1](https://github.com/lexik/LexikMaintenanceBundle/releases/tag/v2.1.1) and will be released in wallabag 2.0.1.
