### ISSUE TITLE
JSON import refresh images

### ISSUE THREAD

**Issue by Matthias84** [wallabag/wallabag#1757]
### Issue details

If v2 import v1 JSON, it doesn't update the article images. This results in a mixed appeareance, as old (imported) article show up just with text, while new added articles will have an image.
![wallabag2-articleimage](https://cloud.githubusercontent.com/assets/217511/13553465/0311293a-e38b-11e5-8472-f49a6a7c8b76.jpg)

It would be nice, when imported articles could be updated and contain an preview picture, too.

**Comment by tcitworld** [comment]
As v1 doesn't refetch content but gets it from the json file, it's not easy to be done. Would you prefer that the export refetches all content (it will take a while) ? We can also fetch content by default and fallback on original content if it fails.

**Comment by Matthias84** [comment]
Hi, thanks for your reply and explanation! 

I guess fetching from scratch is ok, if
* an dialog indicates progress
* no content is lost (e.g. keep old stuff, if new fetch returns bad errorcodes)

**Comment by j0k3r** [comment]
As @tcitworld it could **really** take a while if you want to re-fetch content on import. It can't be done in the actual import because it'll exceed maximum execution time for sure.
But it can be done async with #1581.

**Comment by Matthias84** [comment]
IMHO it's more an 'nice to have' feature, as I personally don't collect that much links ;)

**Comment by HLFH** [comment]
Also, if wallabag could download pictures of the posts in some way, it will fix mixed content issues on HTTPS.

`Mixed Content: The page at 'https://example.com/view/53' was loaded over HTTPS, but requested an insecure image 'http://www.ulyces.co/wp-content/uploads/2015/08/ulyces-viv-01-700x529.jpg'. This content should also be served over HTTPS.`

**Comment by j0k3r** [comment]
We should refetch content for the v1 import and use the default html from the import in case the refetch doesn't work.

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/issues/1842
