### ISSUE TITLE
Crawl multipage articles

### ISSUE THREAD

**Issue by Matthias84** [wallabag/wallabag#1758]
### Issue details

(_I know this might become a hard one_)

Especially newspages create articles with pagination. It would be nice, if wallabag could detect < 1 2 3> links and combine them to one single combined text.

* [W3C suggest rel="Next"](https://www.w3.org/TR/WCAG10-HTML-TECHS/)
* [Google suggests rel="next"](https://support.google.com/webmasters/answer/1663744?hl=en)

**Comment by tcitworld** [comment]
Well, normally wallabag already *tries* to do that. You can sent us links of where it should happen for us to fix it. :)

**Comment by Matthias84** [comment]
Ok will try to collect some links. Till then, feel free to close this issue :smiley:

**Comment by j0k3r** [comment]
We are using siteconfig file to better handle pagination.
For example, this config file for [gsmarena.com](https://github.com/fivefilters/ftr-site-config/blob/f64a03f91e81af700b9c6b99ced97b4503fd1292/gsmarena.com.txt) tells the parser which link will be the next page (with `next_page_link`). The parser will concat page until it can't find the next page link.

But there isn't something like _auto_ find the next page link.
I'll more than happy if you can provide few links with the Google / W3C suggestion. So we can investigate and try to implement that.

**Comment by j0k3r** [comment]
I don't think we'll handle auto link, `next_page_link` is the way to go in siteconfig.
