### ISSUE TITLE
Use NPM to handle external (JS & CSS) assets

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#1759]
Instead of copying external assets in the repo we should use NPM (and/or Bower) to retrieve them.
Here are a list of external assets we actually use:

- prismj
- jquery
- jquery.cookie
- materialize
- annotator
- icomoon
- material-design-icons

**Comment by tcitworld** [comment]
Grr, I need to publish the annotator fork on npm, then. :/

**Comment by j0k3r** [comment]
Yup or maybe we can use a custom directive like the `repositories` in [Composer](https://getcomposer.org/doc/04-schema.md#repositories).

**Comment by tcitworld** [comment]
Now in 2.1 branch.
