### ISSUE TITLE
Tag-list not properly rebuilt  after import 1.9 > 2.0b

### ISSUE THREAD

**Issue by fodiator** [wallabag/wallabag#1760]
### Issue details

After installing 2.0b and re-importing ~70 tagged articels, the "TAGS"-list is missing several entries and the shown tags are not clickable any more. Opening single articels show their right tags. Tagging new articels does not add any new tag-names to the list either. 

### Environment

* wallabag version = 2.0.b
* How did you install wallabag? > downloading the package
* Last wallabag version that did not exhibit the issue (if applicable): 1.91
* php version: PHP 5.5.32-1+deb.sury.org~trusty+1 (cli) (built: Feb  5 2016 10:14:31)
* OS: ubuntu 14.04 LTS
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): default (SQLite)

### Steps to reproduce/test case
export JSON from 1.91
import JSON to 2.0b

**Comment by tcitworld** [comment]
>  the "TAGS"-list is missing several entries

That's bothering. Any clue why they are not here ? Did the entries that had those tags were imported or not ?

> the shown tags are not clickable any more. 

Yup, normal for now.

> Tagging new articles does not add any new tag-names to the list either. 

What ? That's really odd. Can you detail on this ?

**Comment by fodiator** [comment]
>   Any clue why they are not here ? 
No, see this screenshots comparing my installation of 1.91
![taglist1 91](https://cloud.githubusercontent.com/assets/16526094/13609214/47806774-e558-11e5-9ee0-2b747a290bf6.png)
with 2.0b 
![taglist2 0b](https://cloud.githubusercontent.com/assets/16526094/13609232/55e216a0-e558-11e5-8e3c-dfee6e8eac7e.png)


> Did the entries that had those tags were imported or not ?
They were imported from 1.91

To detail unsuccessful tagging: 
I have saved a link to an article, open it and click the tag button and add tags > see this screenshot
![tagged_article](https://cloud.githubusercontent.com/assets/16526094/13609277/8078be28-e558-11e5-8372-38cdedbcaefa.png)
Seems like  commas are not recognised as tag seperators (see "computer, technik" is marked as one tag) and this new tag is not listed in wallabags tags-list.
Is there a 2.0b version as an online service to be able to compare my with local installation and check for differences?

P.S: wallbag (1.91) is extremely nice and helpful, can't wait to have a working 2.0

**Comment by tcitworld** [comment]
> > Did the entries that had those tags were imported or not ?
>
> They were imported from 1.91

Ok. So the entry which has the `job` tag on v1.x is correctly imported on v2, it's just that the tag isn't set, correct ?

>  Seems like commas are not recognised as tag seperators (see "computer, technik" is marked as one tag) and this new tag is not listed in wallabags tags-list.

Got it ! Will fix this. Also, checkout the other theme that we work most on the time, the *baggy* theme will have all the features, but maybe some time after.

> Is there a 2.0b version as an online service to be able to compare my with local installation and check for differences?

There's http://v2.wallabag.org/, but I don't think you'll find anything relevant.

**Comment by fodiator** [comment]
I've now checked and compared the behaviour of my local v2b installation with your public one. Seems that the missing entry within the tag-list when adding a new article is a local issue only. Maybe my installation is somehow faulty - I will check that.

I've as well imported my v1.91 archive to your public v2b service and found that this bug aftects your version as well. Wallabag reports that there are 51 tags , but only ~20 are displayed in tag-list of your server.
See:
![taglist2 1b](https://cloud.githubusercontent.com/assets/16526094/13671181/ab4917de-e6ce-11e5-9652-96db6ca68832.png)

**Comment by fodiator** [comment]
Have now tested the import of my 1.9 archive to 2.0b2 and the issue is still there. 
Several tags are not diplayed in taglist, although they seem to be imported into database (because number count of tags seems right) 
Regards

**Comment by DoumeDuSud** [comment]
same for me after import a JSON file from wallabag 1.9.1 => 2.0.3

- OS: WAMP with php7 on [UWamp](http://www.uwamp.com/fr/)
- fresh installation
- it tell me that I have 171 tags but it show me only 10
- I cannot clic on the tag to access to the list of articles
- _I don't know if it's a bug_ but their are no auto-completation when you tagging an article

Apparently it's the same bug than this one #1994

**Comment by nicosomb** [comment]
You're right. It's a duplicate. I can close.
