### ISSUE TITLE
Generate thumbnails for image-only content

### ISSUE THREAD

**Issue by lightonflux** [wallabag/wallabag#1770]
I am very happy to see that bagging images (png/jpg files) works with v2. But testing revealed that there is no thumbnail generated like with text articles that contain image.

![bildschirmfoto von 2016-03-09 08-23-31](https://cloud.githubusercontent.com/assets/1377943/13628295/4d98a698-e5d1-11e5-9ebb-6a5a6f76b4cb.png)

![bildschirmfoto von 2016-03-09 08-23-42](https://cloud.githubusercontent.com/assets/1377943/13628297/54e37234-e5d1-11e5-9971-382850092677.png)
### Environment
- wallabag version: v2 beta 1
- How did you install wallabag?  shared hosting complete package
- OS: centos 
- type of hosting: shared hosting
- which storage system: sqlite (default)
### Steps to reproduce/test case

Bag this link: http://satwcomic.com/art/sheepish-food-cravings.png

If you bag the article containing the link thumbnail generation works. But not if only one image.

Works: http://satwcomic.com/women-around-the-world
## Expected behaviour

Show thumbnails for image-only content. 

Name the bagged item  "Image: filename.png"

Expected result similar to this:
![bildschirmfoto von 2016-03-09 08-32-58](https://cloud.githubusercontent.com/assets/1377943/13628324/9437138c-e5d1-11e5-9313-dda32769509e.png)

- [ ] make the image clickable
- [ ] then, remove the useless title
- [ ] but keep the domain name

**Comment by j0k3r** [comment]
This is a good improvement !
Actually we are only checking for the opengrah image to display this preview picture. It could be a good idea to generate a thumbnail for image only content.

**Comment by tcitworld** [comment]
Stop me if I'm wrong :

* we check the extension of the file
* we check mimetype
* we regenerate the picture
* We store it in `data/assets/` and link it inside the template
* We delete the picture in `data/assets/` when the entry is deleted

**Comment by j0k3r** [comment]
You can check mime type and if none are provided, you can fallback to extension.

The following items looks good to me

**Comment by tcitworld** [comment]
Right !

**Comment by tcitworld** [comment]
- [ ] make the image clickable
- [ ] then, remove the useless title
- [ ] but keep the domain name

**Comment by j0k3r** [comment]
Looks like this is what we are expecting?
![image](https://user-images.githubusercontent.com/62333/51034741-025f4d80-15a8-11e9-9024-c2ea22177fcc.png)

**Comment by lightonflux** [comment]
Yes it does.
