### ISSUE TITLE
[v2. beta 1] Error 404 on search.

### ISSUE THREAD

**Issue by e-jambon** [wallabag/wallabag#1781]
### Issue details

Searching for a word / expression /   tag gets a 404 error. 
Systematic, can be reproduced.

### Environment
imported all content from v1. Tags included.
Doing one search on content => systematic 404.
Adding removing playing with content ... works fine.

* wallabag version (v2 beta 1) that exhibits the issue:
* How did you install wallabag? Via `composer create-project` /as provided in beta
* Last wallabag version that did not exhibit the issue (last stable version) :
* php version: 5.5.9
* OS: Linux Mint 17.3
* type of hosting (shared or dedicated): dedicated (local install)
* SQLite installation (testing)
* web server apache2.

#### 1st scenario : 
1. I have 117 different tags. Some have accents (french), spaces.
2. Search for a tag (any tag)
3. Error => 404.

Reproduced systematically.

#### 2nd scenario 
Removed every single content. Therefore, all tags are removed (checked and works).
1. Adding new content (4 articles).
2. do a search (with a word that actually is found in an article).
3. => 404 error.
4. Add a tag ( css ) 
5. Search for "css"
6. => 404. error.

#### Apache logs
In my apache log, I find this error over and over again : 
`
PHP Warning:  include_once(): Failed opening '/var/www/wallabag/web/../var/bootstrap.php.cache' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/wallabag/web/app.php on line 9, referer: http://wallabag.mynetwork.lan/
`

All logs from apache2 "acces.log" within the last 2 minutes preceding the request :

`
192.168.0.23 - - [12/Mar/2016:23:38:21 +0100] "GET / HTTP/1.1" 200 3441 "http://strat_p2.mynetwork.lan/view/3" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/material/css/print.css HTTP/1.1" 200 783 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/material/css/materialize.min.css HTTP/1.1" 200 26085 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/material/css/main.css HTTP/1.1" 200 2640 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/_global/js/jquery.cookie.js HTTP/1.1" 200 1701 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/_global/js/bookmarklet.js HTTP/1.1" 200 579 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/_global/js/jquery-2.0.3.min.js HTTP/1.1" 200 29595 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/material/js/init.js HTTP/1.1" 200 1090 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/material/js/materialize.min.js HTTP/1.1" 200 37925 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/_global/js/annotator.min.js HTTP/1.1" 200 121763 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/material/font/roboto/Roboto-Regular.woff2 HTTP/1.1" 304 180 "http://wallabag.mynetwork.lan/bundles/wallabagcore/themes/material/css/materialize.min.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/material/font/roboto/Roboto-Light.woff2 HTTP/1.1" 304 180 "http://wallabag.mynetwork.lan/bundles/wallabagcore/themes/material/css/materialize.min.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/material/font/roboto/Roboto-Bold.woff2 HTTP/1.1" 304 180 "http://wallabag.mynetwork.lan/bundles/wallabagcore/themes/material/css/materialize.min.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/material/img/logo-square.png HTTP/1.1" 304 179 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:22 +0100] "GET /bundles/wallabagcore/themes/material/font/roboto/Roboto-Medium.woff2 HTTP/1.1" 304 180 "http://wallabag.mynetwork.lan/bundles/wallabagcore/themes/material/css/materialize.min.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
192.168.0.23 - - [12/Mar/2016:23:38:48 +0100] "GET /index.php?search=css HTTP/1.1" 404 744 "http://wallabag.mynetwork.lan/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"
`
#### Side note
Same environment / server  / session / content on last Wallabag stable version (v1) : 
  * 1st scenario => works fine.
  * 2nd scenario => did not test.

**Comment by e-jambon** [comment]
FYI : works fine with last v1 stable version,  same environment / web server / machine.

**Comment by tcitworld** [comment]
Search... Isn't finished yet, sorry.
