### ISSUE TITLE
Different font-size for form labels with Material theme

### ISSUE THREAD

**Issue by NumEricR** [wallabag/wallabag#1788]
### Issue details
On config form, labels aren't displayed with same font-size (ex with first tab):
- "Theme": 12px
- "Items per page": 15px

By the way, Theme's label should be placed before ".select-wrapper" in HMTL code to avoid a blank space due to the margin-top of .select-wrapper".

Labels from RSS and Password tabs have same problem.

### Environment
2.0.0-beta.2 via http://v2.wallabag.org/about
FF 45.0 on MacOS X

**Comment by tcitworld** [comment]
#1785 should also get rid of this.

**Comment by nicosomb** [comment]
Fixed by #2260.
