### ISSUE TITLE
Idea to simplify UI for results numbers

### ISSUE THREAD

**Issue by NumEricR** [wallabag/wallabag#1789]
Here's an idea to avoid the result sentence (ie. "There are 13 entries.") used on unread, starred and archive categories.

Why not giving the number of articles next to the category title?
We could see something like this:
![capture d ecran 2016-03-13 a 22 27 47](https://cloud.githubusercontent.com/assets/262560/13731515/362f787c-e96b-11e5-9465-d142115a5376.png)
---
... compared to existing UI:
![capture d ecran 2016-03-13 a 22 28 14](https://cloud.githubusercontent.com/assets/262560/13731516/3b904a76-e96b-11e5-8a9b-c15f0cf918dc.png)

**Comment by tcitworld** [comment]
The idea itself is good, but maybe we can apply certain styles to the number so it catches the eye more. Any ideas ?

**Comment by modos189** [comment]
![362f787c-e96b-11e5-9465-d142115a5376](https://cloud.githubusercontent.com/assets/1785196/13820020/9ceb3a04-ebac-11e5-9a2a-f7111fb7c6b7.png)
Could be better so?

**Comment by tcitworld** [comment]
I love it !

**Comment by modos189** [comment]
Now I'm busy, I can do in a weekend

**Comment by NumEricR** [comment]
Much better than my own idea: we can see those informations on any page! :+1:

**Comment by tcitworld** [comment]
> we can see those informations on any page!

Unfortunately, the count for each category isn't transmitted to each page, so there's backend changes to implement first.

**Comment by tcitworld** [comment]
> Now I'm busy, I can do in a weekend

Don't rush, it can't be done with current backend, I've postponed it to v2.1.

**Comment by NumEricR** [comment]
Don't forget to keep sentences "There is no entry" / "There is no tag" when there is no entry in starred and archive sections, search results or no created tag in tags page.

**Comment by nicosomb** [comment]
Done in #2002.
