### ISSUE TITLE
Editing tagging rules

### ISSUE THREAD

**Issue by NumEricR** [wallabag/wallabag#1794]
After creating a new tagging rule in config, we can delete it but there is no way to edit it!
I think the only way is to delete this rule and create it again with our intended changes :disappointed: 

:bulb:  Could it be possible to add an edit feature?

--
Tested with v2 beta2

**Comment by j0k3r** [comment]
Yeah of course, we didn't think about that at first. Thanks for filling an issue about that :+1:
