### ISSUE TITLE
[Feature request] API endpoint for checking if a URL is already bookmarked

### ISSUE THREAD

**Issue by ThibaudDauce** [wallabag/wallabag#1796]
Hi, 

I'm working on a Firefox extension for Wallabag and I need an endpoint for checking if a URL is or isn't inside my Wallabag yet (I'll put a different icon on the bar depending on the result)

Is there already a method to achieve this goal? And if not, is it possible to implement something? 

Thanks!

**Comment by tcitworld** [comment]
OK, so for starters there was a bug : adding entries through API with the same URL added them a second time. This is fixed in #1797.

Now, how would `/api/exists` with `url` as a parameter would go ?

**Comment by ThibaudDauce** [comment]
That's ok for me! 

If it's possible, it could be useful to be able to pass an array of links and obtain an array of boolean (to check for example all the link in a page with one request)

**Comment by tcitworld** [comment]
Yup, can be done.
