### ISSUE TITLE
Open entries from tags page

### ISSUE THREAD

**Issue by ZeddZull** [wallabag/wallabag#1798]
Hi,
I think it would be great if we could access all the articles with a tag  by clicking on this tag name, on the tag page ?
I can do this.

**Comment by j0k3r** [comment]
Totally agree, this is something we are going to work on after the v2 release.
We plan to focus on tag management, filter entries by tag, etc ...

**Comment by NumEricR** [comment]
Clicking on tag labels in article page should be considered too :wink:

**Comment by nicosomb** [comment]
In progress here: #1943.

**Comment by nicosomb** [comment]
Done in #1943.
