### ISSUE TITLE
Search engine

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#18]

**Comment by 4oo4** [comment]
I see this got removed from the 2.1.0 milestone, any update on where this is at? I would gladly help if I'm able to assist.

Cheers for all the other improvements in v2.1

**Comment by j0k3r** [comment]
Most of the job was done in https://github.com/wallabag/wallabag/pull/1685 but it was closed when we renamed branches.
It can be a good starting point if you want to help us on that.
If we can have it up and running for the 2.2.0 it could be great!

**Comment by 4oo4** [comment]
Cool, so should I just pull from the 2.2.0 branch and go from there? Also, is elasticsearch still the backend?

**Comment by j0k3r** [comment]
Yes. And it is still the backend

**Comment by 4oo4** [comment]
Sounds good! It will take me a few days to clone my production Wallabag instance and get ES up and running, at that point I'll start digging into that commit. I will probably have some questions since I haven't poked around the Wallabag source much. Is there a code style guide I should go off of?

**Comment by tcitworld** [comment]
For the php side `php-cs-fixer` does much of the work. On the assets side, run `grunt tests`.

**Comment by tcitworld** [comment]
You could start by rebasing the old commits and opening a new branch. :-)

**Comment by j0k3r** [comment]
Yep also don't hesitate to come on Gitter instead :)

**Comment by nicosomb** [comment]
Done in #2543.
