### ISSUE TITLE
Selector to choose font

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1802]
As mentioned here #1521, we'll have a new tab in config page, "Display". 
In this tab, we'll have a selector to choose the font size in article view.

**Comment by iGormilhit** [comment]
If we could also choose between sans and serif, I would very much appreciate.

**Comment by Kdecherf** [comment]
Is there any idea on the font-size selector feature? (fixed sizes, percent, other ?)

**Comment by tcitworld** [comment]
I guess it could be both with values in the fields calculating one another (with current value as default).

**Comment by Kdecherf** [comment]
With one value to set (and a ratio applied to all sizes) or with all values to set independently?

**Comment by romu70** [comment]
There are some articles one the web about some "golder values" to maximise the readability. You can even find some calculator: https://pearsonified.com/typography/

**Comment by borisschapira** [comment]
Please add serif and s.t. for people who suffer from dyslexia (https://opendyslexic.org/ ?).

**Comment by notabene** [comment]
Might I be so bold as to suggest trying the Accessible DfA font for dyslexia: https://github.com/Orange-OpenSource/font-accessible-dfa/

Some ideas for minimal settings requirements, gathered from above + experience:

* font size
* font family
* colour set

Take a look at presets in Confort+ http://confort-plus.orange.com/

(comment here is my own of course, although I'm linking to Orange resources)

**Comment by nicosomb** [comment]
Done in only 15 minutes. Still some work to do. 

https://github.com/wallabag/wallabag/assets/121870/a0add06f-364f-487f-b138-e2f2e2e4d853
