### ISSUE TITLE
export pdf/epub : 504 Gateway Time-out 

### ISSUE THREAD

**Issue by dattaz** [wallabag/wallabag#1808]
### Issue details
follow https://twitter.com/nicosomb/status/711955939646111749

I have 504 Gateway Time-out when I try to export to .pdf or .epub
export .mobi work well

### Environment

* wallabag version (or git revision) that exhibits the issue: framabag

**Comment by tcitworld** [comment]
You're trying to export all articles ? How many are they ?

**Comment by dattaz** [comment]
Yes all (with download as at bottom of the page),
20 articles

I have found that if i remove, 1 article (https://fr.wikipedia.org/wiki/Echecs) it's work. (but I already, in the past export this article without issue)

**Comment by tcitworld** [comment]
Mobi was the only export that doesn't regenerate pictures, I guess it's an issue on one of the pictures that take too long.

**Comment by tcitworld** [comment]
Not much to do on here. There's simply too much pictures on the wikipedia page to process (they are regenerated). It works perfectly if you madly increase values inside your `php.ini` though.

With v2, we'll be able to use asynchronous jobs. Follow up at #1927

**Comment by alainwolf** [comment]
Maybe this dirty little workaround helps.
On Nginx I added the following lines inside the `location ~ ^/app\.php(/|$) {}` block.
```
    ...    
    # Preparing long articles for export/download may take a long time.
    # Also set "max_execution_time" in php.ini accordingly.
    fastcgi_read_timeout 5m;

    # Custom PHP settings:
    fastcgi_param PHP_VALUE
        "cgi.fix_pathinfo = 0;
         max_execution_time = 300;";

    # In case of time-out, tell the user why
    error_page 504 /var/www/tooBig4export.html
     ...

```
Still needs patience, tweak the timing to you needs. ...
You may also serve a customized 504 error document, explaining that the article is jut too big for conversion using Nginx `error_page`.

[fastcgi_read_timeout](https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_read_timeout)
[max_execution_time](https://secure.php.net/manual/en/info.configuration.php#ini.max-execution-time)
[error_page](https://nginx.org/en/docs/http/ngx_http_core_module.html#error_page)
