### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#1809]
ping @wallabag/translators 
We updated our languages files, some keys are not translated. 

Please have a look to these files and update them if necessary. 

Don't forget to read our documentation about translation http://doc.wallabag.org/en/v2/developer/translate.html

We planned to release wallabag v2 stable on 3rd April, so it could be a good thing if translations are complete.

**Comment by j0k3r** [comment]
Untranslated string are commented in the each file.
The english version is defined instead.

**Comment by j0k3r** [comment]
- [ ] da
- [ ] de
- [ ] es
- [ ] fa
- [ ] pl
- [ ] ro
- [ ] tr
