### ISSUE TITLE
Implementation of Annotator.js

### ISSUE THREAD

**Issue by cka3o4h1k** [wallabag/wallabag#1810]
Good implementation of Annotator.js in https://hypothes.is/docs/help
You can see all highlights and annotations, and separate buttons for 
Fresh code on https://github.com/hypothesis/h

**Comment by j0k3r** [comment]
@tcitworld is it related to the annotation stuff you did?

**Comment by tcitworld** [comment]
Yup. It's the js library we use.

**Comment by j0k3r** [comment]
So we can close that one?

**Comment by tcitworld** [comment]
I would rather not for now. Annotator.js has not evolved since 2015 and hypothesis is still active, so I would be interested in looking on what they're doing with it.

**Comment by tcitworld** [comment]
Replaced by https://github.com/wallabag/wallabag/issues/3839
