### ISSUE TITLE
Wallabag Client 2.0 - Does not work, is vanishing and does not store articles

### ISSUE THREAD

**Issue by RaspyVotan** [wallabag/wallabag#1811]
Wallabag Client 2.0.0 (downloaded March 21) for Firefox seems to have an issue and keeps vanishing. On  a completely new Firefox instance version 45.0.1 installation works fine and I am able to get the wallabag icon in the browser  so far, so good.

There are two issues:
1) When I hit the button, wallabag web site of my server pops up and I can log in, but I cannot store pages. (From within the wallabag web end, I can store sites - so the problem is not that the server is not running)
2) As soon as I change the privacy settings and ask firefox not to keep any history, the client vanishes - the icon disappears and I have not (yet) found a way to get it back other than running a complete new install.

**Comment by ThibaudDauce** [comment]
Hi,

Are you using the last version (v0.0.4) of https://addons.mozilla.org/fr/firefox/addon/wallabag-v2/?

Can you please run in a terminal:
```bash
http POST http://your_url/oauth/v2/token \
    grant_type=password \
    client_id=your_client_id \
    client_secret=your_secret_id \
    username=your_username \
    password=your_password
```

And after that, with your fresh access token:
```bash
http GET http://v2.wallabag.org/api/entries.json \
    "Authorization:Bearer your_access_token"
```

You can also go to `about:config` and add a new entry `extensions.@wallabag-v2.sdk.console.logLevel` with the value of `all` then restart Firefox and open the developer console with Ctrl-Shift-J, try again to save an article and give me the logs about wallabag (you can use Ctrl-F to search for wallabag).

For your privacy settings I have no idea… Maybe Firefox is creating a new profile and reset all addons at each restart.

**Comment by RaspyVotan** [comment]
Hi,
    that already helped - I had the wrong verson of the client.
    
    Where will I find the "client id" and the "client_secret"? I am not
    yet fully in the details, and unfortunately I could not find it in
    the documentation. 
    
    
    Votan
    
    Am 23.03.16 um 20:39 schrieb Thibaud
      Dauce:
    
    
      Hi,
      Are you using the last version (v0.0.4) of https://addons.mozilla.org/fr/firefox/addon/wallabag-v2/?
      Can you please run in a terminal:
      
        http POST http://your_url/oauth/v2/token \
    grant_type=password \
    client_id=your_client_id \
    client_secret=your_secret_id \
    username=your_username \
    password=your_password
      
      And after that, with your fresh access token:
      
        http GET http://v2.wallabag.org/api/entries.json \
    "Authorization:Bearer your_access_token"
      
      You can also go to about:config and add a new
        entry extensions.@wallabag-v2.sdk.console.logLevel
        with the value of all then restart Firefox and
        open the developer console with Ctrl-Shift-J, try again to save
        an article and give me the logs about wallabag (you can use
        Ctrl-F to search for wallabag).
      For your privacy settings I have no idea… Maybe Firefox is
        creating a new profile and reset all addons at each restart.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by ThibaudDauce** [comment]
Are you running the v2 beta of the server? In the menu go to "Developer" and create a new client (it asks for a URL but it doesn't matter, juste put some random URL).

**Comment by RaspyVotan** [comment]
Perfect - is working now. Will keep testing and will revert if I can
    find anything.
    
    Have a great day and thank you for working on this
    Votan
    
    Am 23.03.16 um 21:39 schrieb Thibaud
      Dauce:
    
    Are you running the v2 beta of the server? In the menu
      go to "Developer" and create a new client (it asks for a URL but
      it doesn't matter, juste put some random URL). 
      
      Le 23 mars 2016 21:19:12 GMT+01:00, RaspyVotan
      <notifications@github.com> a écrit :
      >
      > 
      > 
      > 
      > 
      > Hi,
      > that already helped - I had the wrong verson of the client.
      > 
      > Where will I find the "client id" and the "client_secret"? I
      am not
      > yet fully in the details, and unfortunately I could not find
      it in
      > the documentation. 
      > 
      > 
      > Votan
      > 
      > Am 23.03.16 um 20:39 schrieb Thibaud
      > Dauce:
      > 
      > 
      > Hi,
      >Are you using the last version (v0.0.4) of
      >https://addons.mozilla.org/fr/firefox/addon/wallabag-v2/?
      > Can you please run in a terminal:
      > 
      > http POST http://your_url/oauth/v2/token \
      > grant_type=password \
      > client_id=your_client_id \
      > client_secret=your_secret_id \
      > username=your_username \
      > password=your_password
      > 
      > And after that, with your fresh access token:
      > 
      > http GET http://v2.wallabag.org/api/entries.json \
      > "Authorization:Bearer your_access_token"
      > 
      > You can also go to about:config and add a new
      > entry extensions.@wallabag-v2.sdk.console.logLevel
      > with the value of all then restart Firefox and
      > open the developer console with Ctrl-Shift-J, try again to
      save
      > an article and give me the logs about wallabag (you can use
      > Ctrl-F to search for wallabag).
      > For your privacy settings I have no idea… Maybe Firefox is
      > creating a new profile and reset all addons at each restart.
      > —
      > You are receiving this because you authored the thread.
      > Reply to this email directly or view
      > it on GitHub
      >
      >---
      >You are receiving this because you commented.
      >Reply to this email directly or view it on GitHub:
>https://github.com/wallabag/wallabag/issues/1811#issuecomment-200526390
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by ThibaudDauce** [comment]
Do not hesitate to open an issue on https://github.com/ThibaudDauce/wallabag-firefox if you find anything ☺
