### ISSUE TITLE
 wallabag can't retrieve contents from overblog

### ISSUE THREAD

**Issue by benasse** [wallabag/wallabag#1826]
### Issue details

Impossible to fetch the content of a overblog article, for example : http://autour-du-mont-sainte-odile.overblog.com/2016/01/visitons-le-chateau-de-landsberg.html

### Environment

* http://v2.wallabag.org/

### Steps to reproduce/test case

Try to add the article

**Comment by j0k3r** [comment]
This is strange, it should works. I'll take a look.
Thanks for reporting !

**Comment by benasse** [comment]
I close the issue, it's working on the demo site now ...

If you have an explanation, I'm interested ...

**Comment by j0k3r** [comment]
We've done nothing. Maybe they have changed something on their side.
