### ISSUE TITLE
Installation not possible on cheap webhosting services

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#1827]
wallabag versions below 2.0 can be installed on a cheap web service that only allows FTP access. You had the choice to extract the installation package locally and upload it via FTP.

However with wallabag v2 you need to execute at least one command to install wallabag:

    php bin/console wallabag:install --env=prod

Is there a way to provide a sample configuration file along with the "shared hosting" package to not lose the users using wallabag on a cheap server that *doesn't* provide SSH access?

**Comment by tcitworld** [comment]
Checkout #1777.
A number of commands need to be make without shell access. It is still planned.

**Comment by xhenner** [comment]
Even with the idea in #1777, it require to launch a daemon on port 8888. By definition nothing you can do on a cheap web service.
Or to be more explicite : can I run 2.0 the same way I ran 1.9, with a apache+phpfpm and no wallbag deamon ?

**Comment by nicosomb** [comment]
I uploaded a new package, with a configured database sqlite file. 

I also updated the downloads page of our website: 

> #### On a shared hosting
> 
> ...
> 
> * Download this file here: http://wllbg.org/latest-v2-package
> * Extract it (`tar xvf wallabag-2.0.0.tar.gz`)
> * [Read this documentation to create your virtual host](http://doc.wallabag.org/en/v2/user/installation.html#installing-on-apache)
> * If you changed the database configuration to use MySQL or PostgreSQL, you need to create a user via this command `php bin/console wallabag:install --env=prod`.

**Comment by tcitworld** [comment]
But what are the default credentials ?

**Comment by tcitworld** [comment]
Also, don't forget to also update the blog post.

**Comment by nicosomb** [comment]
See https://github.com/wallabag/wallabag.org/blob/master/content/pages/download.md 

> We already created a user (login and password are wallabag). This user is only available if you use SQLite database.

Oh, yeah, I forgot blog post. WIll do.

**Comment by nicosomb** [comment]
@jlnostr Can you confirm we can close this issue?

**Comment by jlnostr** [comment]
Yep, can be closed :)
