### ISSUE TITLE
[v2-beta2] Fatal error: Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found

### ISSUE THREAD

**Issue by skibbipl** [wallabag/wallabag#1830]
### Issue details

Can't install wallabag v2 beta 2 according to documentation.
```
Installing Wallabag...

Step 1 of 4. Checking system requirements.
+-----------------+--------+----------------+
| Checked         | Status | Recommendation |
+-----------------+--------+----------------+
| PDO Drivers     | OK!    |                |
| curl_exec       | OK!    |                |
| curl_multi_init | OK!    |                |
+-----------------+--------+----------------+
Success! Your system can run Wallabag properly.

Step 2 of 4. Setting up database.
Creating database and schema, clearing the cache
The command "doctrine:database:create" terminated with an error code: 1.

  [Exception]
  The command "doctrine:database:create" terminated with an error code: 1.

# php bin/console doctrine:database:create
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /var/www/wallabag2/app/AppKernel.php:45
Stack trace:
#0 /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(396): AppKernel->registerBundles()
#1 /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(68): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(117): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/wallabag2/bin/console(29): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput in /var/www/wallabag2/app/AppKernel.php on line 45
```

### Environment

* wallabag version (or git revision) that exhibits the issue: v2 beta 2
* How did you install wallabag? Via `composer create-project` or by downloading the package? Followed the documentation. Git pull + composer.
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: PHP 7.0.4-7 (cli) ( NTS )
* OS: debian testing
* type of hosting (shared or dedicated): cloud (dedicated)
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Followed following steps:
```
git clone https://github.com/wallabag/wallabag.git
cd wallabag
git checkout 2.0.0-beta.2
SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
php bin/console wallabag:install --env=prod
```
The issue seems similar to #1617

**Comment by j0k3r** [comment]
Hum I was pretty sure this issue was fixed but I was able to reproduce right now :disappointed: 
We need to take a deeper look at it. Thanks for reporting !

**Comment by j0k3r** [comment]
Do you have php5-sqlite installed on your debian?
And could you list all your installed php package?

**Comment by skibbipl** [comment]
In fact you made me realize that after upgrade to php7.0 I've forgot to install php-sqlite3 package. The issue is solved at least in my scenario.

**Comment by j0k3r** [comment]
Excellent, that's the change I made in #1832. We were only checking for at least one of the mysql, sqlite or pgsql driver to be installed. Now we'll check for the selected driver (when you install wallabag).

Thanks for reporting !
