### ISSUE TITLE
The font used in the "Material" theme renders a bit weirdly in Firefox on Windows

### ISSUE THREAD

**Issue by zertrin** [wallabag/wallabag#1833]
### Issue details

The font used in the "Material" theme renders a bit weirdly in Firefox (see screenshot, open it to 100% of its size to see it better)

Tested using Firefox Developer Edition (47.0a2) (2016-03-28) but also tested with Firefox 45.0.1

![mcpewjafohvhbuir](https://cloud.githubusercontent.com/assets/1447163/14221446/19bd8b06-f867-11e5-915d-94fb524c0972.PNG)

However in Google Chrome (45.0.2454.93) the font renders correctly (see next screenshot)

![greahesahzdnjzx](https://cloud.githubusercontent.com/assets/1447163/14221537/c1d66510-f867-11e5-9641-aaadb770603c.PNG)

### Environment

* wallabag version (or git revision) that exhibits the issue: `2.0.0-beta-2`
* How did you install wallabag? Via `composer install`, see below
* Last wallabag version that did not exhibit the issue (if applicable): Theme "Baggy"
* php version: PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12)
* OS: Debian 8 Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

I only followed the instructions at http://doc.wallabag.org/en/v2/user/installation.html : 

```
git clone https://github.com/wallabag/wallabag.git
cd wallabag
git checkout 2.0.0-beta.2
SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
php bin/console wallabag:install --env=prod
php bin/console server:run 0.0.0.0:5555 --env=prod
```

**Comment by jlnostr** [comment]
I tried to reproduce it but with no success. Here's how it looks here (Firefox 45.0.1 with no plugins enabled). With Opera it looks almost the same.
![image](https://cloud.githubusercontent.com/assets/5391936/14226473/87e55a4c-f8e3-11e5-8716-61423a72da6d.png)

Maybe you've installed a plugin which destroys the font rendering in any way?

**Comment by zertrin** [comment]
Good remark. I just tried again with a completely new Firefox profile (FF 47.0a2 (2016-04-01)) by using the Profile Manager `firefox.exe -P`, and the rendering is the same. (So it's not a plugin issue)

Some more information about my environment: Windows 7 Home Premium (with all updates)

After some more research with the Inspector from the Developer tools I found that the font used is Roboto:

![reagrahrthnbztdmnh](https://cloud.githubusercontent.com/assets/1447163/14229142/74d11c32-f92b-11e5-9e83-8bf3a3218e44.PNG)

And some more Googling lead to that: https://support.mozilla.org/en-US/questions/1069023

So apparently that's an issue specific to that font, on Windows and with Firefox, especially when ClearType is activated (but apparently also when deactivated).

Apparently the only "solution" up to now is to replace Roboto with another font (for example with a rule in Adblock/uBlock or alternatively in Stylish to override the choice of Roboto with a safer font like Arial or Verdana)

**Comment by zertrin** [comment]
Another interesting thread here with another solution that allegedly allows to keep Roboto, at the expense of a more complicated CSS code: https://forums.digitalpoint.com/threads/roboto-font-looks-ugly-in-firefox-and-safari.2750879/

**Comment by tcitworld** [comment]
Thanks. I'll see what we can do on our end, but you may also be willing to report that to [MaterializeCSS](https://github.com/Dogfalo/materialize), that we use.

**Comment by zertrin** [comment]
By searching in the issues of MaterializeCSS, I've found the following that may be relevant:

- [Fonts seem to have a problem on desktop browser](https://github.com/Dogfalo/materialize/issues/93) (opened 13 Nov 2014, closed 1 Dec 2014)
- [Font artifacts](https://github.com/Dogfalo/materialize/issues/745) (opened 24 Feb 2015, closed 2 Mar 2015)
- [Font look very bad on desktop. Why?](https://github.com/Dogfalo/materialize/issues/1329) (opened 8 May 2015, closed 11 May 2015)
- [The web font has some problem.](https://github.com/Dogfalo/materialize/issues/2912) (**very recent**: opened 19 days ago, closed 9 days ago)

Not sure if the problem is really being correctly handled upstream...

I'm not sure why it has to be Roboto and not another font more widely supported like Arial, Verdana or other sans-serif "classicals". The issue [Font other than Roboto](https://github.com/Dogfalo/materialize/issues/2863) (opened 2 Mar 2016) might be worth following on this subject.

**Comment by tcitworld** [comment]
Yeah, I've got another bothering issue (js-related) with MaterializeCSS and they don't seem too eager to fix it.

I guess it's Roberto just because it's Google.

**Comment by prysme01** [comment]
I confirm this issue with firefox on windows. it's ugly yes :)

**Comment by zertrin** [comment]
For information, I worked around this issue with a [Stylish](https://addons.mozilla.org/en-US/firefox/addon/stylish/) user-style:

```
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("wallabag.example.net") {
  html {
    font-family: "segoe ui", arial, helvetica, sans-serif;
  }
}
```

**Comment by j0k3r** [comment]
Is that still relevant?

**Comment by prysme01** [comment]
it is working fine for me now on 2.0.5

**Comment by j0k3r** [comment]
Thanks !

**Comment by zertrin** [comment]
Well for me on 2.0.7 nothing has changed yet.

![eahbternbhtrajhtbs](https://cloud.githubusercontent.com/assets/1447163/19043842/176ccf6c-8992-11e6-98a9-9d513c70567c.PNG)

Will try an upgrade to 2.1 soon and report.

**Comment by j0k3r** [comment]
Yeah could you update and come back to us?
Thanks

**Comment by zertrin** [comment]
After upgrading to 2.1.1 things are not looking ugly anymore. 👍

**Comment by j0k3r** [comment]
Good to know, thanks !
