### ISSUE TITLE
Wallabag only works on localhost

### ISSUE THREAD

**Issue by nicoroud** [wallabag/wallabag#1834]
### Issue details

I install wallabag v2 (beta2) on a dedicated server. Install is good but I can only access wallabag at http://127.0.0.1:8000 (localhost), not at http://server_ip_adress:8000

To access wallabag from outside, the command line must be : `php bin/console server:run server_ip_adress --env=prod`

It would be nice if there was an option during installation that requires that IP address , right?

### Environment

* wallabag version: v2 beta 2
* Install by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:5.6
* OS: debian linux
* type of hosting: dedicated
* storage system: SQLite

**Comment by nicosomb** [comment]
Hello @nicoroud! 

To install wallabag on your dedicated server, you need install apache for example (or nginx). 
Then, follow this documentation: http://doc.wallabag.org/en/v2/user/installation.html#installing-on-apache

`bin/console server:run` is only for localhost ;-)
