### ISSUE TITLE
Search returns 404 page

### ISSUE THREAD

**Issue by nicoroud** [wallabag/wallabag#1836]
When I perform a search, wallabag returns a 404 page :
```
Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

No error in logs.
This error appears everytime I do a search.

How can I fix this ?

Wallabag version : v2 beta 2
installed in debian apache server

**Comment by nicosomb** [comment]
Hello @nicoroud! 

This feature is not yet developed and is planned for next release. We'll hide this button.
