### ISSUE TITLE
A convenient way to get the original url of an entry

### ISSUE THREAD

**Issue by gggdominici** [wallabag/wallabag#1837]
As I wrote #1831 I realized that there is no way to get the original URL from the RSS feed, or even from an entry url. You could use the API, but it requires authentication which could be unnecessarily painful, especially for public entries.

For public entries, I can imagine something like http://mywallabag.com/view/1234/original/ redirecting to the original url of the entry 1234, bypassing the wallabag interface. 
Or anonymous access to the API as suggested by @tcitworld.
Or both ?

I personnally have a preference for the first solution as it is very straightforward for the end-user.

Does anybody have any insight about it ?

**Comment by tcitworld** [comment]
Apart from providing it through the API or interface, we could **also** easily bring it to RSS feeds.

**Comment by tcitworld** [comment]
See https://github.com/wallabag/wallabag/issues/1926 for RSS feeds.

**Comment by j0k3r** [comment]
Original link are now in the RSS since 2.0.2
