### ISSUE TITLE
Refresh all preview pictures from articles imported from v1

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1842]
### Issue details

When you import articles from v1, articles do not get the preview pictures. There should be an option to fetch them during import (hard to implement) or to re-fetch them all after the import has finished (we may have to wait until asynchronous jobs are implemented).

**Comment by knodderdachs** [comment]
I copied the /assets directory from my old wallabag installation to the root directory of wallabag v2. It works. The only problem is, if you remove an article from your collection, wallabag doesn't delete the corresponding directory in /assets. But thats OK for now. Maybe you can make a rescan option to fetch the pictures in a future version of wallabag.

**Comment by knodderdachs** [comment]
Hm, I just found out, that it's possible to re-fetch the images by refreshing each post manually.... that's better than just copying the /assets directory.

**Comment by tcitworld** [comment]
In that case, you don't get local, downloaded images, since this functionality is not yet implemented in 2.x.

**Comment by j0k3r** [comment]
I think we don't care now.
