### ISSUE TITLE
Package installer is broken in 2.0.0

### ISSUE THREAD

**Issue by bigretromike** [wallabag/wallabag#1843]
### Issue details

php bin/console wallabag:install --env=prod
```
PHP Warning:  Unsupported declare 'strict_types' in /var/www/clients/client0/web8/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 19
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/clients/client0/web8/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 97
```

### Environment

* wallabag 2.0.0
* How did you install wallabag? downloading the package
* Last wallabag version that did not exhibit the issue (if applicable): 2.0.0-beta2
* php version: PHP 5.6.17-0+deb8u1
* OS: Debian 8.3

### Steps to reproduce/test case

download tar.gz
extract them
chown for proper user
execute php command

**Comment by fodiator** [comment]
Exact the same here:
:-(

**Comment by bigretromike** [comment]
Updating to 5.6.19-0 didn't reslove this.
beta-2 was working great before.

**Comment by tcitworld** [comment]
We may have an issue with the package we provide. Can someone try to install through composer instead ?

**Comment by bigretromike** [comment]
After replacing Configuration.php with the one from beta2 another file throw same error

```
PHP Warning:  Unsupported declare 'strict_types' in /var/www/clients/client0/web8/vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php on line 19
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/clients/client0/web8/vendor/ocramius/proxy-manager/src/ProxyManager/GeneratorStrategy/EvaluatingGeneratorStrategy.php on line 51
```

**Comment by tcitworld** [comment]
Okay. It seems the package we provide currently only works with php7. Please wait a few hours so we can fix this.

**Comment by bigretromike** [comment]
Thanks! Will wait!

**Comment by NerosTie** [comment]
I have PHP 5.6.19-0+deb8u1 and it works well.

**Comment by bigretromike** [comment]
@NerosTie strange, beacuse even on build test mention in #1844 it failes ;-) sure you use latest 2.0.0 and not beta2 ?:-)

**Comment by NerosTie** [comment]
@bigretromike Yes I'm sure. Installed twice yesterday.

**Comment by nicosomb** [comment]
I updated the package few hours ago. That's why @NerosTie don't have problems I think. ;-)

**Comment by bigretromike** [comment]
@nicosomb you my hero :-)

**Comment by roccostorm** [comment]
I have downloaded the package again and now it works. thank you.

**Comment by nicosomb** [comment]
:+1:
