### ISSUE TITLE
General error: 14 unable to open database file

### ISSUE THREAD

**Issue by skibbipl** [wallabag/wallabag#1845]
### Issue details
So I wanted to test clean install of wallabag. I used selected SQLite as a database vendor with default user/password wallabag/wallabag. Anyway after fixing some permission issues I faced following error:
```
2016/04/04 15:26:02 [error] 19489#19489: *45071 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 14 unable to open database file in /var/www/wallabag2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
Stack trace:
#0 /var/www/wallabag2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(57): PDO->exec('CREATE TABLE IF...')
#1 /var/www/wallabag2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1025): Doctrine\DBAL\Driver\PDOConnection->exec('CREATE TABLE IF...')
#2 /var/www/wallabag2/vendor/lexik/maintenance-bundle/Drivers/Query/DefaultQuery.php(50): Doctrine\DBAL\Connection->exec('CREATE TABLE IF...')
#3 /var/www/wallabag2/vendor/lexik/maintenance-bundle/Drivers/Query/DefaultQuery.php(38): Lexik\Bundle\MaintenanceBundle\Drivers\Query\DefaultQuery->createTableQuery()
#4 /var/www/wallabag2/vendor/lexik/maintenance-bundle/Drivers/DatabaseDriver.php(111): Lexik\Bundle\MaintenanceBundle\Drivers\Query\DefaultQuery->initDb()
#5 /var/www/wallabag2/vendor/lexik/maintenance-bundle/Drivers/Abs" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: wallabag2.xxx.xxx, request: "GET /login HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "wallabag2.xxx.xxx"
```

### Environment

* wallabag 2.0.0
* How did you install wallabag? downloading the package.
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: PHP 7.0.4-7
* OS: debian testing
* type of hosting (shared or dedicated): cloud (dedicated)
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Clean installation according to documentation.

**Comment by tcitworld** [comment]
This means you must have write access to the directory containing the database (meaning `data/`) so that your database can we writable.

**Comment by skibbipl** [comment]
My bad! I was pretty sure I've updated all permissions to folders/files but I was wrong. Sorry for the spam.
