### ISSUE TITLE
Php server takes way too much CPU on Raspberry Pi

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#1846]
### Issue details

Fresh install of Wallabag 2.0.0 on a Raspberry Pi. Even if I'm doing nothing on Wallabag, `php bin/console server: run --env=prod` takes a minimum of 24% of the CPU and I think it's way too much for a service which is not used.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.0
* How did you install wallabag? Via the official doc: http://doc.wallabag.org/en/v2/user/installation.html
* Last wallabag version that did not exhibit the issue (if applicable): 1.x
* php version: php 5.x
* OS: Raspbian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Just install Wallabag 2.0.0 and run it.

**Comment by tcitworld** [comment]
Because it is not planned to be used like this, that's the php build-in server whose performances are aweful ! [Install it](http://doc.wallabag.org/en/v2/user/installation.html) with Apache or Nginx to have normal performances.

**Comment by NerosTie** [comment]
So, I can avoid the steps with composer? Downloading the .zip file is enough (like before)?

**Comment by tcitworld** [comment]
That's nothing to do with it. Instead of launching with `php bin/console server: run --env=prod`, just configure your webserver to point to `web/app.php` like the configuration files from my links above show.

**Comment by NerosTie** [comment]
`Assuming you install wallabag in the /var/www/wallabag folder`

What is supposed to mean? 

Is this part necessary if I want to install with nginx? : 

```
SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
php bin/console wallabag:install --env=prod
```

**Comment by tcitworld** [comment]
It's an example of where you want to install wallabag.
Totally.

**Comment by NerosTie** [comment]
You are right! It works. Thanks.

But IMHO, the doc should be more clear around here. Because I thought it was like Ghost which needs to run in background.
