### ISSUE TITLE
Missing parameters during install

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#1848]
### Issue details

During the installation process, I have this:

```
Some parameters are missing. Please provide them.
database_driver (pdo_sqlite): 
database_host (127.0.0.1): 
database_port (null): 
database_name (symfony): 
database_user (root): 
database_password (null): 
database_path ('%kernel.root_dir%/../data/db/wallabag.sqlite'): 
database_table_prefix (wallabag_): 
test_database_driver (pdo_sqlite): 
test_database_host (127.0.0.1): 
test_database_port (null): 
test_database_name (null): 
test_database_user (null): 
test_database_password (null): 
test_database_path ('%kernel.root_dir%/../data/db/wallabag_test.sqlite'): 
mailer_transport (smtp): 
mailer_host (127.0.0.1): 
mailer_user (null): 
mailer_password (null): 
locale (en): 
secret (ovmpmAWXRCabNlMgzlzFXDYmCFfzGv): 
twofactor_auth (true): 
twofactor_sender (no-reply@wallabag.org): 
fosuser_confirmation (true): 
from_email (no-reply@wallabag.org): 
```

Unfortunately, there is no information about this in the docs. What am I supposed to do?

Is it safe to keep everything to default? My main concern is about the sqlite's password. Do I need a password for my database?  
Should I put `locale` to fr?  
Can I modify the informations about email later?

### Environment

* wallabag version (or git revision) that exhibits the issue:2.0.0
* How did you install wallabag? By downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.x
* OS: Raspbian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case

Normal installation.

__
Thank you!

**Comment by tcitworld** [comment]
You can keep everything by default. The password field does not apply to SQLite. If you put locale to fr, it will be the default language for all new users, but any user can change it's language in the config panel.

All these parameters can be changed later in the parameters.dist file inside `app/config`

**Comment by NerosTie** [comment]
Thank you!
