### ISSUE TITLE
client_max_body_size for Nginx

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#1849]
### Issue details

I think you need to add in the docs (http://doc.wallabag.org/en/v2/user/installation.html) a line in the Nginx configuration:

`# client_max_body_size XM; # allows file uploads up to X megabytes`

You need that when you import a large database from an other Wallabag. If not, you have the error: `413 Request Entity Too Large`. 
However, this do not solve this issue: https://github.com/wallabag/wallabag/issues/1764
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.0
* How did you install wallabag? Via downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 5.x
* OS: Raspbian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Upload a large database from a previous Wallabag with the default Nginx configuration from the docs.

**Comment by j0k3r** [comment]
Feel free to submit a PR about that: https://github.com/wallabag/wallabag/blob/v2/docs/en/user/installation.rst
