### ISSUE TITLE
Can't add an article from the same domain

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#1850]
### Issue details

For tests purpose, I'm trying to add articles from my other sub-domains but it results to the error `wallabag can't retrieve contents for this article.`

Example: 
`http://blog.neros.fr/un-shaarli-moderne/` doesn't work
`https://demo.ghost.io/style-test/` it's basically the same thing as the link before and it works!

`http://links.neros.fr/?SkBPvg` doesn't work
`http://shaarli.sebw.info/?AueTUQ` basically the same thing too and it works!

These 2 links which don't work, they work well on `http://v2.wallabag.org`

This is why I think Wallabag can't add articles from the same domain. It's not really a big issue, because I will not read later my own things, but I'm just wondering why... Or, I have something wrong in my configuration.
### Environment
- wallabag version (or git revision) that exhibits the issue: 5.0.0
- How did you install wallabag? Via downloading the package
- Last wallabag version that did not exhibit the issue (if applicable): don't kwno
- php version: 5.x
- OS: Raspbian
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite
### Steps to reproduce/test case

Add a page in wallabag from an other sub-domain of your website.

**Comment by nicosomb** [comment]
Hello @NerosTie! 

Is that the same webserver? 
I tried to add this link https://www.wallabag.org/blog/2016/04/03/wallabag-v2 in my v2.wallabag.org account, and it works. (v2.wallabag.org and wallabag.org are hosted on 2 different servers).

**Comment by NerosTie** [comment]
Yes, it's the same webserver and I don't have this bug on Wallabag 1.x.  
I tried the same thing as you and it works too. I really don't understand...

**Comment by j0k3r** [comment]
We've added an extra protection (using https://github.com/j0k3r/safecurl) on the v2 about url being called using cURL. So that, url like `file:///etc/passwd`, `telnet://localhost:25` doesn't break / leak data from the app / server.

It can be linked but I'm not sure and it'll be hard to test I guess ..

**Comment by j0k3r** [comment]
I removed the milestone because it'll be a hard issue to fix because it'll be hard to reproduce, so no ETA yet, sorry.

**Comment by NerosTie** [comment]
This bug is now fixed.

**Comment by j0k3r** [comment]
Wow great!
