### ISSUE TITLE
Importing from Pocket in v2 gives Internal Server Error 500

### ISSUE THREAD

**Issue by bigretromike** [wallabag/wallabag#1855]
### Issue details

When trying to import big collection of items from pocket, I get asked for autorization via Pocket, I click it. Then it take some time and throw 500 Internal Server Error on https://wallabag.domain/import/pocket/callback but it looks like It taking to long for importing full collection and when using 'mark as readed' I see that Archive is being populated so probably there is to many items to import and wallabag just get timeout somewhere.

### Environment

* wallabag version: 2.0.0
* How did you install wallabag?: by downloading the package
* php version: PHP 5.6.19-0+deb8u1 (cli) (built: Mar 14 2016 10:22:33)
* OS: Debian 8.4
* which storage system you choose at install: SQLite

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by j0k3r** [comment]
You forgot to fullfill the line _type of hosting (shared or dedicated):_

We are aware that the Pocket import might fail when there are too much entries. We are planning to build async import to solve that, see #1581

**Comment by bigretromike** [comment]
async should helped alot. Eventualy I just import some items, delete them via hand and import rest till I hit end. Good that this problem is known because I was trying to search for any import issues and didnt find the #1581 - I probably wont test this after fixing because I purge my Pocket account (Finally!!!)

**Comment by jlnostr** [comment]
Pocket also supports the [export to an HTML file](https://getpocket.com/export) containing all the links (extract below). Maybe wallabag can make use of it? 

```html
<!DOCTYPE html>
<html>
    <!--So long and thanks for all the fish-->
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Pocket Export</title>
    </head>
    <body>
        <h1>Unread</h1>
        <ul>
            <li><a href="http://zeroturnaround.com/rebellabs/docker-commands-and-best-practices-cheat-sheet" time_added="1459859581" tags="docker,developing">http://zeroturnaround.com/rebellabs/docker-commands-and-best-practices-cheat-sheet</a></li>
            <li><a href="https://medium.com/cuepoint/streaming-music-is-ripping-you-off-61dc501e7f94#.76nnhd2m3" time_added="1459859557" tags="">https://medium.com/cuepoint/streaming-music-is-ripping-you-off-61dc501e7f94#.76nnhd2m3</a></li>
            <li><a href="http://www.theverge.com/2016/4/1/11348960/tesla-model-3-interior-touchscreen-self-driving-theory-autopilot" time_added="1459859547" tags="tesla">http://www.theverge.com/2016/4/1/11348960/tesla-model-3-interior-touchscreen-self-driving-theory-autopilot</a></li>
        </ul>
        <h1>Read Archive</h1>
        <ul>
            <li><a href="http://www.sueddeutsche.de/politik/panama-papers-geheimgeschaefte-von-hunderten-politikern-und-prominenten-in-steueroasen-enthuellt-1.2932232" time_added="1459710325" tags="">http://www.sueddeutsche.de/politik/panama-papers-geheimgeschaefte-von-hunderten-politikern-und-prominenten-in-steueroasen-enthuellt-1.2932232</a></li>
        </ul>
    </body>
</html>
```

**Comment by nicosomb** [comment]
It can be useful, you're right, but we still need to reimport data from each article (pocket HTML export only provides URL).

**Comment by jlnostr** [comment]
Ah, that's what causing the issues. I previously thought is was fetching the content from Pocket :D

**Comment by nicosomb** [comment]
See #1611

**Comment by j0k3r** [comment]
With async in 2.1.0, it should reduce this kind of error.
Let us know if it's still the case and we'll re-open this issue.

**Comment by bigretromike** [comment]
Sorry I wont be able to test it myself as I wipe out pocket account when I moved to superior wallabag ;-) Hope new comers wont have that issue

**Comment by biva** [comment]
Hello @j0k3r , I'm running wallabag 2.2 and I'm getting this error 500 importing a lot of articles from Pocket :(

**Comment by j0k3r** [comment]
I think it's better to open an other issue and explain what is your wallabag setup, server, etc.
