### ISSUE TITLE
Adding SQL Schema for easier initialisation in containers

### ISSUE THREAD

**Issue by xsteadfastx** [wallabag/wallabag#1857]
I work on a docker image for wallabag. There is a problem with the installation dialog in the Dockerfile. This doesnt work for image creation. So it would be much easier if there are some kind of default sql schema files that i could import if its not already there. This would make it much easier.

**Comment by j0k3r** [comment]
The schema is created by the command wallabag:install. Shouldn't this be enough?

**Comment by xsteadfastx** [comment]
this is what i will do now. i just have problems with getting wallabag working with mariadb. if i get it working i will do a fresh sqldump from it.

**Comment by j0k3r** [comment]
:arrow_right: https://github.com/wallabag/wallabag/issues/1858
