### ISSUE TITLE
2 options in internal settings are ineffective 

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#1867]
### Issue details

In Internal Settings -> Article, `Download pictures on your server` and `Display a link to print content` do nothing when they are set to `1`. Images in articles are not from the server itself and I see no link to print.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.0
* How did you install wallabag? by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.19
* OS: Raspbian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Set to `1` `Download pictures on your server` and `Display a link to print content` in Internal Settings -> Article. Then add an article: the image is not from the server where Wallabag is hosted and no link to print.

**Comment by tcitworld** [comment]
* Download pictures on your server is not yet implemented
* Display a link to print content should work. Will check.

**Comment by NerosTie** [comment]
* If it's not implemented, this option should be hidden or in grey
* Have you checked? :)
