### ISSUE TITLE
position of tag edit field

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#1870]
Why tag edit field appears under post picture but not under title? It is quite weird :)

**Comment by tcitworld** [comment]
We can open the discussion. :)

**Comment by Rurik19** [comment]
when tags exist - they are on the top? And there user think to be an edit field.

**Comment by nicosomb** [comment]
I think @Rurik19 is right. When we have preview picture, we don't have to scroll to see the tag form. 

PR in progress.
