### ISSUE TITLE
Waiting indicator

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#1871]
After enter  url of article to save and hit enter there is a pause which is uncommented by site - maybe some wait indicator will be useful? Same thing after editing tag list.

**Comment by j0k3r** [comment]
Well, you should see your browser reloading the page. There is no async request here (as of now).

**Comment by Rurik19** [comment]
It is also useful to disable input or hide edit field -because for now editing is possible while app load article.

**Comment by j0k3r** [comment]
Yeah that option is better than displaying a loading which is a duplicate of the browser loading.
