### ISSUE TITLE
PHP Warnings - bootstrap.php.cache missing

### ISSUE THREAD

**Issue by tmelikoff** [wallabag/wallabag#1872]
### Issue details

Everything works as supposed but warnings are shown in error log file during navigation inside wallabag.

```
2016/04/05 10:06:41 [error] 12717#12717: *1518 FastCGI sent in stderr: "PHP message: PHP Warning:  include_once(/var/www/wallabag/web/../var/bootstrap.php.cache): failed to open stream: No such file or directory in /var/www/wallabag/web/app.php on line 9
PHP message: PHP Warning:  include_once(): Failed opening '/var/www/wallabag/web/../var/bootstrap.php.cache' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/wallabag/web/app.php on line 9" while reading response header from upstream, client: CLI.ENT.IPA.DDR, server: my.server.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "my.server.com", referrer: "https://my.server.com/login"
```
there is no `bootstrap.php.cache` file
also tried to empty `/var/cache `folder as suggested by @tcitworld but same happened

### Environment

* wallabag version (or git revision) that exhibits the issue: wallabag-2.0.0.tar.gz (md5 hash: 62c629d1803a159282dd3065deea9f3a)
* How did you install wallabag? Via `composer create-project` or by downloading the package? Downloading the package
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: PHP 5.6.19-0+deb8u1
* OS: Raspbian Jessie
* type of hosting (shared or dedicated): dedicated (Raspberry Pi 2)
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Installed as in documentation. `chown www-data:www-data` everyting including hidden files inside /var/www/wallabag

### `php --ini` output
```
Configuration File (php.ini) Path: /etc/php5/cli
Loaded Configuration File:         /etc/php5/cli/php.ini
Scan for additional .ini files in: /etc/php5/cli/conf.d
Additional .ini files parsed:      /etc/php5/cli/conf.d/05-opcache.ini,
/etc/php5/cli/conf.d/10-pdo.ini,
/etc/php5/cli/conf.d/20-apcu.ini,
/etc/php5/cli/conf.d/20-curl.ini,
/etc/php5/cli/conf.d/20-gd.ini,
/etc/php5/cli/conf.d/20-imagick.ini,
/etc/php5/cli/conf.d/20-json.ini,
/etc/php5/cli/conf.d/20-memcache.ini,
/etc/php5/cli/conf.d/20-memcached.ini,
/etc/php5/cli/conf.d/20-mysql.ini,
/etc/php5/cli/conf.d/20-mysqli.ini,
/etc/php5/cli/conf.d/20-pdo_mysql.ini,
/etc/php5/cli/conf.d/20-pdo_sqlite.ini,
/etc/php5/cli/conf.d/20-readline.ini,
/etc/php5/cli/conf.d/20-sqlite3.ini,
/etc/php5/cli/conf.d/20-tidy.ini
```

**Comment by j0k3r** [comment]
Can you run `bin/console cache:clear --env=prod` ?
And if it doesn't work `SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist` (assuming you have composer installed).

**Comment by tmelikoff** [comment]
I've run `bin/console cache:clear --env=prod`, got an ok and `chown www-data:www-data` entire `/var/www/wallabag` folder

`[OK] Cache for the "prod" environment (debug=false) was successfully cleared.`

Warnings are still present.

I've then run

`SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist`, got an ok and `chown www-data:www-data` entire `/var/www/wallabag` folder
```
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- -------------------- ------------------
      Bundle               Method / Error
 --- -------------------- ------------------
  ✔   FrameworkBundle      relative symlink
  ✔   NelmioApiDocBundle   relative symlink
  ✔   WallabagCoreBundle   relative symlink
 --- -------------------- ------------------


 [OK] All assets were successfully installed.
```
bootstrap.php.cache is now present and warnings are gone

**Comment by j0k3r** [comment]
@nicosomb I guess that `bootstrap.php.cache` doesn't exist in the package.

**Comment by nicosomb** [comment]
Oh you're right, I excluded var/* while packaging...

**Comment by nicosomb** [comment]
I just uploaded a new package. Can you confirm this bug is now fixed please?

**Comment by tmelikoff** [comment]
Confirmed. Bug is now fixed. No more `bootstrap.php.cache` missing warning.
