### ISSUE TITLE
Not to show preview-image in full article view

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#1875]
As preview-image usual is taken from the article, in full view it duplicates and takes a lot of space. Better not to show at all or to have an option in config. Look: two pictures takes all the window
![image](https://cloud.githubusercontent.com/assets/1955806/14314605/a66c7348-fc11-11e5-84be-2cc179528754.png)

**Comment by j0k3r** [comment]
I don't if we are going to fix that issue for 2.3.1 :confused:

**Comment by biva** [comment]
No milestone anymore ? :(

**Comment by Kdecherf** [comment]
I will try to provide a fix to this in the following weeks. But as I will need to execute a database migration, its release may be postponed to the next major update.

**Comment by kour1er** [comment]
Would it be possible to have an config option to re-enable the preview picture in the full article view? I'm not having the duplicate image issue - in fact, I'm not seeing the top image in my article at all in the web full article view. Using Fiery Feeds support of Wallabag on iOS, there is a config option to show the top image (header image) and that works great so I miss it in the browser view of Wallabag.
