### ISSUE TITLE
Wrong page title for the list archived articles

### ISSUE THREAD

**Issue by Ygster** [wallabag/wallabag#1882]
### Issue details

When we are in the page of the archived article, the title of the page is "entry.page_titles.archived" (see the screenshot below). Tested with the language set to french or english, the problem remains the same.

![20160407-wallabag-title_page_archived](https://cloud.githubusercontent.com/assets/10888555/14357897/e5fcc9d4-fcea-11e5-9a5d-a8d146b2309f.png)

### Environment

* wallabag version 2.00
* Installation on a dedicated server via git and composer
* php version: PHP 5.6.19
* OS: Debian 8.4
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

After login click on Archive in the left menu and see the title of the page.

**Comment by j0k3r** [comment]
Thanks for reporting it was already fixed here: https://github.com/wallabag/wallabag/pull/1840
And it'll be available in the next release !
