### ISSUE TITLE
Composer is killed during Wallabag 2 installation

### ISSUE THREAD

**Issue by Lamecarlate** [wallabag/wallabag#1883]
### Issue details

I can't install Wallabag v2 on my tiny VPS (1024M RAM, 10Go disk space).

`git clone https://github.com/wallabag/wallabag.git` --> OK
`cd wallabag` --> OK (obviously)
`git checkout 2.0.0` -> OK
`SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist` -> **my memory progressively rises and rises and reaches 100%, so Composer is killed.**
`php bin/console wallabag:install --env=prod` --> step not reached

Composer is installed: if I add `-vvv`, I can see a lot of .json written into cache, and it usually stops on "https---packagist.org/provider-kriswallsmith$spork.json", or the wallabag json (which is just after the latter).

I tried to stop services for memory gain (MySQL for example). I tried to limit php use of memory (in `/etc/php5/cli/conf.d/php.ini`) but it seems that had no impact, maybe it was not the good php.ini.

I can't add swap to my machine, disk space is very limited. Well, I have 2Go to spare, maybe I *can* add swap, but I'm not comfortable with this manipulation :/

Has anyone an other solution? It's sad that the recommended way is not safe for little environments…

Thanks!

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.0.0**
* How did you install wallabag? **Steps are written above**
* php version: **PHP 5.5.9-1ubuntu4.14**
* OS: **Ubuntu 14.04**
* type of hosting (shared or dedicated): **dedicated but very small: 1024M memory, 10Go disk space**
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): **not applicable yet**

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**It's the install steps, written above**

**Comment by kletellier** [comment]
Same pb on my Rpi2, i've make the install on windows computer and push the application after in the Rpi, after a simple composer post-install-cmd is needed

**Comment by j0k3r** [comment]
Yeah Composer needs a lot of memory. But we made a mistake in the 2.0.0 about speed up this installation.
This'll be fixed in the 2.0.1.

For technical detail: we forgot to add the `composer.lock` to the tagged version, so Composer needs to calculate all the dependencies when installing instead of reading that file (which contains all the calculated dependencies)

**Comment by Lamecarlate** [comment]
Thanks for your answer, j0k3r.

Do you have an idea of when 2.0.1 will be available? (days, weeks, months :P ) In the meantime, if I simulate a Wallabag install on my computer, with only a `composer update`, then upload the `composer.lock` file, would it work?

**Comment by j0k3r** [comment]
Yeah it'll work.
The 2.0.1 will be available in the coming days.

**Comment by nicosomb** [comment]
Next week!
