### ISSUE TITLE
Wrong display in wallabag v2 - site http://blog.niqnutn.com

### ISSUE THREAD

**Issue by Ygster** [wallabag/wallabag#1888]
### Issue details

When addind this article : http://blog.niqnutn.com/index.php?article49/commandes-de-base , the message "wallabag can't retrieve contents for this article. Please report this issue to us.…" is displayed.
The same article in wallabag 1.9.1 was correctly fetched.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.0
* Last wallabag version that did not exhibit the issue (if applicable): 1.9.1
* php version: 5.6.19-0+deb8u1
* OS: Debian 8.4
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

**Comment by j0k3r** [comment]
Thanks for the report !
