### ISSUE TITLE
Wrong display in wallabag v2 - site http://wiki.korben.info

### ISSUE THREAD

**Issue by Ygster** [wallabag/wallabag#1892]
### Issue details

When addind this element : http://wiki.korben.info/clients_de_messagerie_instantanee , the message "wallabag can't retrieve contents for this article. Please report this issue to us.…" is displayed.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.0

**Comment by j0k3r** [comment]
For an unknown reason it seems that this website send a `HTTP/1.1 500 Internal Server Error` for that url even if the html and every thing seems ok.
Until this is fixed on their side we won't be able to do something for that ...
We'll see: https://twitter.com/j0k/status/719067964314689536

**Comment by nicosomb** [comment]
Seems to work with v2.wallabag.org now. 
I close. Feel free to reopen if problem persists.
