### ISSUE TITLE
Wrong display in wallabag v2 - site https://blog.journalduhacker.net

### ISSUE THREAD

**Issue by Ygster** [wallabag/wallabag#1897]
### Issue details

When addind this element : https://blog.journalduhacker.net/index.php?article27/ouverture-du-framaboard-et-appel-a-contribution , the message "wallabag can't retrieve contents for this article. Please report this issue to us.…" is displayed.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.0

**Comment by j0k3r** [comment]
It was the same bug as of https://github.com/wallabag/wallabag/issues/1888: the `/` in query string were badly encoded resulting in an endless redirect.
Thanks for the report !
