### ISSUE TITLE
Hide pagination when there's too many entries

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1905]
I managed to import a lot of entries, and this it what it looks like with a lot of entries
![capture du 2016-04-10 19-12-08](https://cloud.githubusercontent.com/assets/2197836/14411710/49f2e736-ff50-11e5-8740-addbcaf304de.png)

It's even worse with mobile display.
![capture d ecran 2016-04-10 a 19 13 39](https://cloud.githubusercontent.com/assets/2197836/14411716/77821f1e-ff50-11e5-8305-fc797808c4e7.png)

Only the first and last few pages should be shown.

**Comment by nicosomb** [comment]
Duplicate of #1329 but I keep this one opened (screenshots :+1:)
