### ISSUE TITLE
Show full title in a tooltip

### ISSUE THREAD

**Issue by Ygster** [wallabag/wallabag#1906]
### Issue details

When a title is too long to be completely shown, it would be interesting to show the full title in a tooltip when the cursor is hover the truncated title.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.0

**Comment by tcitworld** [comment]
Will be fixed in 2.0.2.

**Comment by nicosomb** [comment]
It's better to let this issue opened until we merge the PR.
