### ISSUE TITLE
have alexa read your blogs with some integration

### ISSUE THREAD

**Issue by cordoval** [wallabag/wallabag#1907]

**Comment by j0k3r** [comment]
Care to elaborate a bit more ?

**Comment by cordoval** [comment]
hmm not really, what i meant was that is the first thing i saw about this tool and crossed my mind. Alexa is the amazon echo device that reads books and does have some AI over the internet thing. I presume someone could do an integration to bookkeep with wallabag certain blog posts database and then whenever you want to catch up you would say 'alexa read me my wallabag pendings" and then off you go.

**Comment by nicosomb** [comment]
And why did you close your issue?
