### ISSUE TITLE
Login fails after upgrading to 2.0.1

### ISSUE THREAD

**Issue by fodiator** [wallabag/wallabag#1914]
### Issue details

Upgraded a working 2.0.0 version to 2.0.1 using the share hosting package description
Re-Login fails with "Bad credentials."

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.1
* How did you install wallabag? Via `git clone` or by downloading the package? package download
* Last wallabag version that did not exhibit the issue (if applicable): 2.0.0
* php version: 
* OS: Ubuntu 14.04 server
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): default

### Steps to reproduce/test case

wget http://wllbg.org/latest-v2-package && tar xvf latest-v2-package
chown -R www-data:www-data ./release2.0.1
cp ./wallabag/app/config/parameters.yml ./wallabag/app/config/parameters.yml.bak
cp -ar ./release2.0.1 ./wallabag
cp ./wallabag/app/config/parameters.ymlbak ./wallabag/app/config/parameters.yml
service apache2 reload

Login fails with "Bad credentials."

(even tried to backup & replace the whole config-folder)

Kind regards

**Comment by j0k3r** [comment]
Weird.
Could you run `php bin/console cache:clear --env=prod` and then retry to login ?

**Comment by tcitworld** [comment]
If you use the default storage system, it means you use SQLite and you should also have backuped your `data` folder too containing the SQLite file, which contains the user informations.  Hope you didn't lost it.

**Comment by fodiator** [comment]
with /data copied, login is now working
Maybe you should mention this in the upgrade process description?

THX & keep up the good work

**Comment by tcitworld** [comment]
Thanks, will add it.
