### ISSUE TITLE
No branch or tag called 2.0.1

### ISSUE THREAD

**Issue by ddeimeke** [wallabag/wallabag#1920]
### Issue details

I try to update from 2.0.0 to the brandnew version 2.0.1 via git.

### Environment

* wallabag version (or git revision) that exhibits the issue: v2
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 2.0.0
* php version: 5.6.20
* OS: CentOS 7.2.1511 (recent patchlevel)
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

```
# git checkout 2.0.1
error: pathspec '2.0.1' did not match any file(s) known to git.

# git branch --list --all
* v2
  remotes/origin/2.1
  remotes/origin/HEAD -> origin/v2
  remotes/origin/cleanup
  remotes/origin/dev
  remotes/origin/fa
  remotes/origin/feature-public-mode
  remotes/origin/improve-pagination
  remotes/origin/j0k3r-patch-1
  remotes/origin/master
  remotes/origin/title-on-title-entry
  remotes/origin/translation-fa
  remotes/origin/v2
  remotes/origin/v2-alternative-env
  remotes/origin/v2-api-annotation
  remotes/origin/v2-api-annotation-switched
  remotes/origin/v2-api-new-properties
  remotes/origin/v2-asynchronous-jobs
  remotes/origin/v2-documentation-api
  remotes/origin/v2-es
  remotes/origin/v2-fix-unknown-mysql-db
  remotes/origin/v2-proxy-manager
  remotes/origin/v2-use-npm
  remotes/origin/v2-user-share

# git tag --list
0.1
0.11
0.2
0.2.1
0.3
1.0-beta1
1.0-beta2
1.0-beta3
1.0-beta4
1.0-beta5
1.0-beta5.1
1.0-beta5.2
1.0.0
1.1.0
1.2.0
1.3.0
1.3.1
1.4.0
1.5.0
1.5.1
1.5.1.1
1.5.2
1.6.0
1.6.1
1.6.1b
1.7.0
1.7.1
1.7.2
1.8.0
1.8.1
1.8.1b
1.8.1bis
1.8.1old
1.9
1.9.1
1.9.1-b
1.9.1alpha1
1.9.1alpha2
1.9.1beta1
1.9.1beta2
1.9.1beta3
1.9RC1
1.9beta
1.9beta2
2.0.0
2.0.0-alpha.0
2.0.0-alpha.1
2.0.0-alpha.2
2.0.0-beta.1
2.0.0-beta.2
```

**Comment by nicosomb** [comment]
Hello! 

Can you try this command:

```
git pull --tags
```

?

**Comment by ddeimeke** [comment]
Thanks a lot.

Should be "git fetch --all" (git is giving an error).

Works. I thought a "git pull --all" would be enough.

**Comment by nicosomb** [comment]
I updated our website yesterday with this command.

**Comment by ddeimeke** [comment]
Thanks Nicolas.

Could you please add update instructions as well?

**Comment by ddeimeke** [comment]
Sorry, I see you already did it. Thank you.

**Comment by ddeimeke** [comment]
Sorry once again:

There is no "git pull --tags":

Should be:
```
git pull --all
git fetch --tags
```

**Comment by nicosomb** [comment]
> There is no "git pull --tags"

What do you mean?

**Comment by tcitworld** [comment]
The command `git pull --tags` [doesn't seem](https://git-scm.com/docs/git-pull) to exist.

**Comment by nicosomb** [comment]
Oh yes. Will fix that.

**Comment by ddeimeke** [comment]
Hi Nicolas, the recent development version of Git contains the option again, even though it is not mentioned in the manpage. Beforehand you were adviced to use "git fetch --tags".

**Comment by nicosomb** [comment]
> Hi Nicolas, the recent development version of Git contains the option again, even though it is not mentioned in the manpage. 

That's why it works here ;-)

**Comment by nicosomb** [comment]
Website updated.
