### ISSUE TITLE
Domains page

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#1921]
I think it will be useful to have a page with source domains list, just as we have tags page now.

**Comment by j0k3r** [comment]
Listing all different domains from your entries?
And I guess that when you click on one of them you get all article for that domain?

**Comment by Rurik19** [comment]
exactly! 
And, click on tag on the tags page also should set tag-filter

**Comment by j0k3r** [comment]
> And, click on tag on the tags page also should set tag-filter

Yeah that is already planned

**Comment by nicosomb** [comment]
FYI, do you know that you can already filter by domain name with the filters sidebar?

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/pull/4371
