### ISSUE TITLE
.htaccess instead of vhost

### ISSUE THREAD

**Issue by knodderdachs** [wallabag/wallabag#1930]
Hi,

I'm trying to install wallabag v2 on my shared hosting. Unfortunately, I'm not allowed to change the apache config (vhost). I'm forced to use .htaccess.

What do I have to put in the .htaccess file to make wallabag work?

Greetings,
Torsten

**Comment by tcitworld** [comment]
@schiesbn said on Gitter :

> seems like adding this to the .htaccess of my web root works: RewriteRule ^$ /web [L]

**Comment by knodderdachs** [comment]
OK, thanks.

Now, the error.log of the webserver shows the following errors:

> [Sat Apr 16 08:30:09 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message '[WARNING 1549] failed to load external entity "file:////var/www/virtual/XXX/XXX/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd" (in n/a - line 0, column 0)
> 
[Sat Apr 16 08:30:09 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: [WARNING 3084] Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location 'file:////var/www/virtual/XXX/XXX/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd'. Skipping the import. (in in_memory_buffer - line 8, column 0)
> 
[Sat Apr 16 08:30:09 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: [ERROR 1845] Element '{http://symfony.com/schema/dic/services}container': No matching global declaration available for the validation root. (in /var/www/virtual/XXX/XXX/web/ - line 5, column 0)' in /var/www/virtual/XXX/XXX/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:96
> 
[Sat Apr 16 08:30:09 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: Stack trace:
> 
[Sat Apr 16 08:30:09 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #0 /var/www/virtual/k in /var/www/virtual/XXX/XXX/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php on line 263

'XXX' is the path to the wallabag directory.

**Comment by nicosomb** [comment]
I think I can close this issue, because you opened #1952.
