### ISSUE TITLE
HowTo use wallabag v2 with LigHTTPd

### ISSUE THREAD

**Issue by FiSHYsolutions** [wallabag/wallabag#1931]
Obviously the webserver is a dependency, so we need doc's about a LigHTTPd-setup.

**Comment by tcitworld** [comment]
I don't know much about LigHTTPd setups, but if someone have an example, I would be happy to add it to the documentation.

**Comment by abers** [comment]
@FiSHYsolutions 

Try editing your lighttpd.conf to the following:

server.modules = (
"mod_fastcgi",
"mod_access",
"mod_alias",
"mod_compress",
"mod_redirect",
"mod_rewrite",
)
server.document-root = "/var/www/wallabag/web"
server.upload-dirs = ( "/var/cache/lighttpd/uploads" )
server.errorlog = "/var/log/lighttpd/error.log"
server.pid-file = "/var/run/lighttpd.pid"
server.username = "www-data"
server.groupname = "www-data"
server.port = 80
server.follow-symlink = "enable"
index-file.names = ( "index.php", "index.html", "index.lighttpd.html")
url.access-deny = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
compress.cache-dir = "/var/cache/lighttpd/compress/"
compress.filetype = ( "application/javascript", "text/css", "text/html", "text/plain" )
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
dir-listing.activate = "disable"

url.rewrite-if-not-file = (
"^/([^?])(?:\?(.))?" => "/app.php?$1&$2",
"^/([^?]*)" => "/app.php?=$1",
"^/wiki$" => "/app.php", 
)

**Comment by tcitworld** [comment]
Thanks, will add to the documentation (or you are welcomed to open a PR) !

**Comment by nicosomb** [comment]
@FiSHYsolutions Did you try the @abers solution? Does it work?

**Comment by FiSHYsolutions** [comment]
sorry guy's. thank you very much but i'm extremely busy at the moment. i'll try it next week (thu/fri) and give a response.

**Comment by FiSHYsolutions** [comment]
got it with this config:

```
bash$ cat /etc/lighttpd/conf-enabled/50-wallabag.conf 
alias.url += ("/wallabag" => "/var/www/wallabag/web")
server.follow-symlink = "enable"
dir-listing.activate = "disable"

$HTTP["url"] =~ "^/wallabag" {
	url.access-deny = (
		"~",
		".inc"
	)
}

url.rewrite-if-not-file = (
	"^/([^?])(?:\?(.))?" => "/wallabag/app.php?$1&$2",
	"^/([^?]*)" => "/wallabag/app.php?=$1",
)
```

btw, the setup routine is way too complicated...
