### ISSUE TITLE
Hide pagination if not needed

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1932]
Follow up to #1905. When there's only a few entries on only one page, there's no need to show pagination.
![pagination_few](https://cloud.githubusercontent.com/assets/2197836/14577480/f02e351a-0374-11e6-81dd-3f4643523951.png)

**Comment by tcitworld** [comment]
I meant a few, not just one entry. Ideally, your number of entry setting for pagination.

**Comment by nicosomb** [comment]
Oh you're totally right ... I don't know why I did that!

Sent from my Alcatel Onetouch Idol 3 (4.7)
Le 16 avr. 2016 09:28, Thomas Citharel <notifications@github.com> a écrit :Reopened #1932.
