### ISSUE TITLE
delete user missing in admin view

### ISSUE THREAD

**Issue by fodiator** [wallabag/wallabag#1934]
### Issue details

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to http://gitter.im/wallabag/wallabag.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.1
* How did you install wallabag? Via `git clone` or by downloading the package? package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS: ubuntu 14.10
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLITE

### Steps to reproduce/test case

login as admin
create a user
try to delete this user (or to change mail-adress)

Regards

**Comment by j0k3r** [comment]
Will be implemented in https://github.com/wallabag/wallabag/issues/2116
