### ISSUE TITLE
[Documentation request] Please add a curl example to the API documentation of v2

### ISSUE THREAD

**Issue by ddeimeke** [wallabag/wallabag#1939]
I use Wallabag to create my "Linkdump", a list of articles worth reading.

In v1 I took the favorites feed and extracted URLs and titles to form the Linkdump.

Now I like to do the same with v2.  I understand that favorites are called "starred" now. I understand that I need a client (created one under "Developer"). I understand that "get API/entries.html" could be the right thing.

How do I form the request with curl or wget?

Thanks for any hint.

**Comment by ddeimeke** [comment]
Found it by myself.

Nevertheless adding it to the documentation would be great.

**Comment by nicosomb** [comment]
Is this page enough http://doc.wallabag.org/en/v2/developer/api.html ?

**Comment by ddeimeke** [comment]
I would add (example):

```
curl --silent "http://localhost:8000/oauth/v2/token?grant_type=password&client_id=1_3o53gl30vhgk0c8ks4cocww08o84448osgo40wgw4gwkoo8skc&client_secret=636ocbqo978ckw0gsw4gcwwocg8044sco0w8w84cws48ggogs4&username=wallabag&password=wallabag" | json_reformat

{
    "access_token": "ZGJmNTA2MDdmYTdmNWFiZjcxOWY3MWYyYzkyZDdlNWIzOTU4NWY3NTU1MDFjOTdhMTk2MGI3YjY1ZmI2NzM5MA",
    "expires_in": 3600,
    "token_type": "bearer",
    "scope": null,
    "refresh_token": "OTNlZGE5OTJjNWQwYzc2NDI5ZGE5MDg3ZTNjNmNkYTY0ZWZhZDVhNDBkZTc1ZTNiMmQ0MjQ0OThlNTFjNTQyMQ",
    "scope"
}
```

and

`curl --silent --get "https://wallabag.deimeke.net/api/entries.html?access_token=ZGJmNTA2MDdmYTdmNWFiZjcxOWY3MWYyYzkyZDdlNWIzOTU4NWY3NTU1MDFjOTdhMTk2MGI3YjY1ZmI2NzM5MA"`

**Comment by nicosomb** [comment]
I don't understand the differences with the current documentation.

**Comment by ddeimeke** [comment]
You are describing a meta request, I am giving a practical example.

**Comment by tcitworld** [comment]
We can add it to the documentation if you open a pull request.

**Comment by ddeimeke** [comment]
Will do, can you please tell me the correct repository to contribute to?

**Comment by tcitworld** [comment]
It's this one. Check out `docs/en/developer/api.rst` (you can do other languages if you want).

**Comment by ddeimeke** [comment]
#1945 added
