### ISSUE TITLE
Apache reload error 

### ISSUE THREAD

**Issue by abers** [wallabag/wallabag#1950]
Just run into an error when trying to host wallabag through apache. After setting up the virtual host and running sudo service apache2 reload I get the following:

Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.

systemctl status apache2.service returns:
apache2.service - LSB: Apache2 web server
 Loaded: loaded (/etc/init.d/apache2)
 Active: active (exited) (Result: exit-code) since Tue 2016-04-19 12:44:36 BST; 4min 6s ago
  Process: 16000 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 16456 ExecReload=/etc/init.d/apache2 reload (code=exited, status=1/FAILURE)
  Process: 16010 ExecStart=/etc/init.d/apache2 start (code=exited, status=0/SUCCESS)

and journalctl -xn:
No journal files were found.

Error.log is empty however.

**Comment by abers** [comment]
Right purging apache2 and reinstalling fixed that issue and it now reloads fine. However, the virtual host still doesn't work for me. When it says "Assuming you install wallabag in the /var/www/wallabag folder" since I wasn't prompted at any point during the install I assumed that the git folder is also the install folder. Therefore, I created a symbolic link /var/www/wallabag to the git folder. That though doesn't seem to be right, including when uncommenting the lines from the suggest virtual host layout to follow symbolic links - does wallabag install somewhere else that I need to link to or am I doing something else wrong?

**Comment by tcitworld** [comment]
The provided virtual host file is just an example, you need to adapt it to your configuration. Please head over at https://gitter.im/wallabag/wallabag for support.

**Comment by abers** [comment]
Right so after after switching back to lighttpd I can get the site to sort of work. Going to the IP address shows the directory but clicking app.php loads wallabag. I think I need to figure out the right rewrite rules for lighttpd as if I add app.php to index locations it 404s. While leaving that out lets me access it via the web and the firefox addon the Android app doesn't like example.com:8000/app.php. I have a redirect on the router to forward 8000 to 80 on the device hosting it - which again works when putting the url into a browser. Am I just going to have to keep exploring lighttpd config options or is there a way to get the Android app to access the url?

**Comment by abers** [comment]
OK getting closer to a solution. I now have it working normally on the web without needing to add app.php. Change index-file.names to:

index-file.names            = ( "app.php", "index.php", "index.html", "index.lighttpd.html")

And add rewrite:

url.rewrite-if-not-file = (
    "^/(mw-)?config/?" => "$0",
    "^/([^?]*)(?:\?(.*))?" => "/app.php?$1&$2",
    "^/([^?]*)" => "/app.php?=$1",
    "^/wiki$" => "/app.php", # to avoid 404 when the user types /wiki instead of /wiki/
)

However, the Android app still hates the URL for some reason. Test login works fine but still get 404 on refreshing poche.

**Comment by nicosomb** [comment]
Is that OK for the web app? If yes, you can close this issue. 

About Android application, you can open a new issue here: https://github.com/wallabag/android-app

**Comment by abers** [comment]
Actually it might still be a web app error. Just went through all the pages and they all work except for config - which gives 404 error,

**Comment by abers** [comment]
And as soon as I wrote that I saw the remaining issue:

"^/(mw-)?config/?" => "$0",

Can be removed - it was left over from an example file I was editing from. After changing that both web and android work.

**Comment by tcitworld** [comment]
Reopening in order not to forget to add the lighttp config file to the documentation.

**Comment by j0k3r** [comment]
Can be close in favor of https://github.com/wallabag/wallabag/issues/1931
