### ISSUE TITLE
500 internal server error on pdf download

### ISSUE THREAD

**Issue by giovi321** [wallabag/wallabag#1951]
### Issue details

After the update to 2.0.1 from 2.0.0, I get a 500 internal server error when trying to download the pdf of my articles. With all the other formats it works and I can download them, only pdf produces this error.
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.0.1
- How did you install wallabag? Via `git clone`
- Last wallabag version that did not exhibit the issue (if applicable): 2.0.0
- php version: PHP 5.6.19-0+deb8u1
- OS: debian 8
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql
### Steps to reproduce/test case

Click on the "export" link, select pdf.

**Comment by nicosomb** [comment]
Hello @giovi321! 

How many articles do you try to export?

**Comment by giovi321** [comment]
Nine articles

**Comment by nicosomb** [comment]
Can you have a look to your PHP error logs please? 
Maybe it's due to `memory_limit` setting in your PHP configuration.

**Comment by giovi321** [comment]
This is my setting:
```
memory_limit = -1
```

**Comment by tcitworld** [comment]
Can you provide us the link that you want to export so that we can reproduce it ?

**Comment by giovi321** [comment]
There are many links. Do you want me to list them all?

**Comment by giovi321** [comment]
Ok, I just got rid of one of the links and I can export everything. I'll try to remember which one was it!

**Comment by giovi321** [comment]
Sorry for the multiple post. The link that breaks the export is the following:
https://sourceforge.net/projects/openproj/

**Comment by tcitworld** [comment]
Thanks. Will look into it.

**Comment by docljn** [comment]
Hello @tcitworld - I'm looking through old issues, and wondered if this was still under investigation or whether it should be closed for now?

**Comment by Kdecherf** [comment]
This issue had no update in the past four years, closing it
