### ISSUE TITLE
PHP Errors

### ISSUE THREAD

**Issue by knodderdachs** [wallabag/wallabag#1952]
### Issue details

When trying to access wallabag v2 on my shared hosting it doesn't work. The error.log lists the following errors:

> [Sat Apr 16 08:30:09 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message '[WARNING 1549] failed to load external entity "file:////var/www/virtual/XXX/XXX/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd" (in n/a - line 0, column 0)
> 
> [Sat Apr 16 08:30:09 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: [WARNING 3084] Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location 'file:////var/www/virtual/XXX/XXX/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd'. Skipping the import. (in in_memory_buffer - line 8, column 0)
> 
> [Sat Apr 16 08:30:09 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: [ERROR 1845] Element '{http://symfony.com/schema/dic/services}container': No matching global declaration available for the validation root. (in /var/www/virtual/XXX/XXX/web/ - line 5, column 0)' in /var/www/virtual/XXX/XXX/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:96
> 
> [Sat Apr 16 08:30:09 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: Stack trace:
> 
> [Sat Apr 16 08:30:09 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #0 /var/www/virtual/k in /var/www/virtual/XXX/XXX/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php on line 263
### Environment
- wallabag version (or git revision) that exhibits the issue:
  2.01
- How did you install wallabag? Via `git clone` or by downloading the package?
  package
- Last wallabag version that did not exhibit the issue (if applicable):
  v1.91 worked perfectly
- php version:
- OS: CentOS
- type of hosting (shared or dedicated): shared (uberspace.de)
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite (default)
### 

Do I have to do anything else before trying to reach the fresh installation? I just installed it as written in the installation instructions.

**Comment by nicosomb** [comment]
Hello @knodderdachs! 

Can you have a look to #1828 please?

**Comment by knodderdachs** [comment]
Hey @nicosomb!

Just checked issue 1828 and tried the following:

php composer.phar install --no-dev

and received a lot of errors

Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /var/www/virtual/XXX/XXX/app/AppKernel.php on line 45
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-cmd event terminated with an exception

                                                                                                                                                                              
  [RuntimeException]                                                                                                                                                          
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                   
  PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /var/www/virtual/XXX/XXX/app/AppKernel.php on line 45  
  .                                                                                                                                                                           
                                                                                                                                                                              

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...


Then I entered

php bin/console wallabag:install --env=prod

and I let reset the database and kept the default admin account. No errors.

But when I try to reach the wallabag installation using the web browser, I still get HTTP ERROR 500.


The error.log:

[Tue Apr 19 20:15:06 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/virtual/XXX/XXX/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in /var/www/virtual/XXX/XXX/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
[Tue Apr 19 20:15:06 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/virtual/XXX/XXX/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in /var/www/virtual/XXX/XXX/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
[Tue Apr 19 20:15:06 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'Doctrine\\Common\\Persistence\\Mapping\\MappingException' with message 'Invalid mapping file 'FOS.UserBundle.Model.User.orm.xml' for class 'FOS\\UserBundle\\Model\\User'.' in /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86
[Tue Apr 19 20:15:06 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: Stack trace:
[Tue Apr 19 20:15:06 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #0 /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\\Common\\Persistence\\Mapping\\MappingException::invalidMappingFile('FOS\\\\UserBundle\\\\...', 'FOS.UserBundle....')
[Tue Apr 19 20:15:06 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #1 /var/www/virtual/XXX/XXX/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\\Common\\Persistence\\Mapping\\Driver\\FileDriver->getElement('FOS\\\\UserBundle\\\\...')
[Tue Apr 19 20:15:06 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #2 /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\\ORM\\Mapping\\Driver\\XmlDriver->loadMetadataFo in /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php on line 86
[Tue Apr 19 20:15:07 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/virtual/XXX/XXX/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in /var/www/virtual/XXX/XXX/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
[Tue Apr 19 20:15:07 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/virtual/XXX/XXX/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in /var/www/virtual/XXX/XXX/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
[Tue Apr 19 20:15:07 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'Doctrine\\Common\\Persistence\\Mapping\\MappingException' with message 'Invalid mapping file 'FOS.UserBundle.Model.User.orm.xml' for class 'FOS\\UserBundle\\Model\\User'.' in /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86
[Tue Apr 19 20:15:07 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: Stack trace:
[Tue Apr 19 20:15:07 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #0 /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\\Common\\Persistence\\Mapping\\MappingException::invalidMappingFile('FOS\\\\UserBundle\\\\...', 'FOS.UserBundle....')
[Tue Apr 19 20:15:07 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #1 /var/www/virtual/XXX/XXX/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\\Common\\Persistence\\Mapping\\Driver\\FileDriver->getElement('FOS\\\\UserBundle\\\\...')
[Tue Apr 19 20:15:07 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #2 /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\\ORM\\Mapping\\Driver\\XmlDriver->loadMetadataFo in /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php on line 86

**Comment by nicosomb** [comment]
About this command `php composer.phar install --no-dev`, you need to add ``env`` parameter, like this: `php composer.phar install --no-dev --env=prod`

**Comment by knodderdachs** [comment]
OK, I deleted the whole directory and downloaded the latest v2 package again.

I installed composer using `curl -s http://getcomposer.org/installer | php`

Then I entered `php composer.phar install --no-dev --env=prod`

This is the result:
>                                                          
>  [Symfony\Component\Console\Exception\RuntimeException]  
>  The "--env" option does not exist.                      
>                                                          
>
>install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by nicosomb** [comment]
The `--env=prod` option is not for the composer command. 
Please have a look to the documentation here: https://www.wallabag.org/pages/download-wallabag.html ;-)

**Comment by knodderdachs** [comment]
Okay, so `php bin/console wallabag:install --env=prod` should be correct? I could reset the database using this command. After that wallabag still didn't run. Then I edited `app/config/parameters.yml` and put in the whole path to the SQL-Database and tried again - but no success.

Hm, that can't be so hard to get v2 running..? There must be something I do wrong, but I just don't know what.

**Comment by j0k3r** [comment]
How do you access to your wallabag instance, I mean, which url?

**Comment by knodderdachs** [comment]
I use a subdomain (as for wallabag v1.9.1).

When I try to reach the subdomain the address automatically changes to subdomain/web

**Comment by bmauduit** [comment]
Hi,

I have exactly the same issue for me on my wallabag Tag 2.0.4.
I use pdo_pgsql, and I have followed exactly this instruction :
https://www.wallabag.org/pages/download-wallabag.html

I have nginx as webserver, and access wallabag instance as a subdomain (https://wallabag.domain.tld/).

**Comment by j0k3r** [comment]
@bmauduit what same issue? Where is the problem? Can you provide some log?

**Comment by bmauduit** [comment]
The same issue as reported by @knodderdachs 

Just after running this command :
sudo -u www-data php bin/console wallabag:install --env=prod
Everything seems to go fine.

But accessing wallabag instance result in blank page and PHP error in nginx error log :

`2016/05/12 11:15:23 [error] 9107#9107: *34488 FastCGI sent in stderr: "PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;<HIDE_BASE_LOCATION>/wallabag/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in <HIDE_BASE_LOCATION>/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;<HIDE_BASE_LOCATION>wallabag/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in <HIDE_BASE_LOCATION>/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Fatal error:  Uncaught exception 'Doctrine\Common\Persistence\Mapping\MappingException' with message 'Invalid mapping file 'FOS.UserBundle.Model.User.orm.xml' for class 'FOS\UserBundle\Model\User'.' in <HIDE_BASE_LOCATION>/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86
Stack trace:
#0 <HIDE_BASE_LOCATION>/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\Common\Persistence\Mapping\MappingException::invalidMappingFile('FOS\\UserBundle\\...', 'FOS.UserBundle....')
#1 <HIDE_BASE_LOCATION>/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\Common\Persistence\Mapping\Driver\FileDriver->getElement('FOS\\UserBundle\\...')
#2 <HIDE_BASE_LOCATION>/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMetadataForClass('FOS\\UserBund" while reading response header from upstream, client: xxxx:yyyy:zzzz:x::1, server: wallabag.domain.tld, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "wallabag.domain.tld"
`

Thanks for the help.

**Comment by j0k3r** [comment]
Could you then check that this file exist: `<HIDE_BASE_LOCATION>/wallabag/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml` ?

**Comment by bmauduit** [comment]
Yep :

> find -name "User.orm.xml"
> ./vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml

**Comment by tcitworld** [comment]
Hi,
Please follow this for the (temporary) fix : http://support.wallabag.org/discussions/problems/478-v2-blank-page

**Comment by j0k3r** [comment]
So following:
- http://stackoverflow.com/a/27038357/569101
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1062
- https://github.com/symfony/symfony/issues/7291

Could you tell us what version of libxml2 are you using?

```
$ php -r "var_dump(LIBXML_DOTTED_VERSION);"
```
It seems that could be a problem related to libxml2 < 2.6.27.

**Comment by bmauduit** [comment]
@tcitworld Thanks for the link.

I have now another issue, but related to my version of postgresql :

> LINE 1: CREATE TABLE IF NOT EXISTS lexik_maintenance (ttl timestamp ...
Is not supported by postgresql version <9.1. (link : http://stackoverflow.com/questions/1766046/postgresql-create-table-if-not-exists)

Maybe we must notice postgresql wallabag users about this ?

I will switch to sqlite for the moment.
Thanks.

**Comment by j0k3r** [comment]
@bmauduit could you please create a separated issue for that? Thanks.

**Comment by bmauduit** [comment]
@j0k3r 

> php -r "var_dump(LIBXML_DOTTED_VERSION);"
> string(5) "2.9.1"

**Comment by bmauduit** [comment]
@j0k3r yep, I will do it sorry.

**Comment by j0k3r** [comment]
Ensure you have apc installed.
Could you try to add this line `metadata_cache_driver: apc` in app/config/config.yml (around line 88) ?

```yml
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                metadata_cache_driver: apc
```

**Comment by knodderdachs** [comment]
OK, now it works... :)

But it's really strange... Here's how I did it:

1. Read http://support.wallabag.org/discussions/problems/478-v2-blank-page and followed the hint in Post 7. (Editing `/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php` at line 814 from `$xmlElement = simplexml_load_file($file);` to `$xmlData = file_get_contents($file); $xmlElement = simplexml_load_string($xmlData);`

2. Run `php bin/console wallabag:install --env=prod` and let the database reset and install a new admin user.

3. Added the line "metadata_cache_driver: apc" to app/config/config.yml as written in the previous post by j0k3r.

I think that should be written in the documentation so more people can install and use wallabag.

**Comment by j0k3r** [comment]
Could you try again but _without_ updating `XmlDriver.php` file? Because this file is in a dependencies and it'll be overriden when you'll update wallabag.

**Comment by knodderdachs** [comment]
Yes, of course. I get a HTTP Error 500. Here's the error.log:

> [Fri May 13 19:52:16 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/virtual/XXX/XXX/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in /var/www/virtual/XXX/XXX/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
> 
> [Fri May 13 19:52:16 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/virtual/XXX/XXX/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in /var/www/virtual/XXX/XXX/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
> 
> [Fri May 13 19:52:16 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'Doctrine\\Common\\Persistence\\Mapping\\MappingException' with message 'Invalid mapping file 'FOS.UserBundle.Model.User.orm.xml' for class 'FOS\\UserBundle\\Model\\User'.' in /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86
> 
> [Fri May 13 19:52:16 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: Stack trace:
> 
> [Fri May 13 19:52:16 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #0 /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\\Common\\Persistence\\Mapping\\MappingException::invalidMappingFile('FOS\\\\UserBundle\\\\...', 'FOS.UserBundle....')
> 
> [Fri May 13 19:52:16 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #1 /var/www/virtual/XXX/XXX/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\\Common\\Persistence\\Mapping\\Driver\\FileDriver->getElement('FOS\\\\UserBundle\\\\...')
> 
> [Fri May 13 19:52:16 2016] [warn] [client 109.75.87.252] mod_fcgid: stderr: #2 /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\\ORM\\Mapping\\Driver\\XmlDriver->loadMetadataFo in /var/www/virtual/XXX/XXX/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php on line 86

**Comment by knodderdachs** [comment]
Hmm... seems that my workaround doesn't work for v.2.0.5... So I have to keep using 2.0.3.

**Comment by j0k3r** [comment]
I guess the problem is that you need to re-apply the fix on Doctrine because vendors have been updated.

**Comment by knodderdachs** [comment]
No, I did re-apply the fix after decompressing the new version and it doesn't work.

**Comment by kpn3m0** [comment]
The workaround [1] works for me with version v.2.0.5. Without I get errors described above ('failed to load external entity').

[1] http://support.wallabag.org/discussions/problems/478-v2-blank-page

**Comment by tristan-k** [comment]
Same for me.

**Comment by das-schaf** [comment]
+1 - I have to patch the XmlDriver.php with every wallabag update

**Comment by nicosomb** [comment]
We updated the doc: http://doc.wallabag.org/en/master/user/faq.html#i-ve-got-the-failed-to-load-external-entity-error-when-i-try-to-install-wallabag

**Comment by tcitworld** [comment]
Can't we put `libxml_disable_entity_loader(false)` somewhere to fix this ?

**Comment by nicosomb** [comment]
@tcitworld No, it's not a wallabag bug.
