### ISSUE TITLE
API v2 is it possible to use curl to add,remove items like in pocket?

### ISSUE THREAD

**Issue by bigretromike** [wallabag/wallabag#1955]
I been using pocket in few scripts, and I would LOVE to convert them to wallabag v2. 
Is it possible ?

Could I get any example?

Im asking because http://doc.wallabag.org/en/v2/ is empty ;-)

**Comment by nicosomb** [comment]
Hello @bigretromike! 

We renamed our branches two days ago, and v2 branch is now called master. You can read our full documentation here http://doc.wallabag.org (which redirects you to http://doc.wallabag.org/en/master/)

About API documentation, you can read this page: http://doc.wallabag.org/en/master/developer/api.html

**Comment by bigretromike** [comment]
ok, hoped there for examples like pocket docs have but that will need to do for now :-) thank you
