### ISSUE TITLE
Framabag upgrade?

### ISSUE THREAD

**Issue by charloz** [wallabag/wallabag#1958]
Hello,

Sorry if I'm a bit out of topic, but  are there any plans to upgrade Framabag to v2 soon?
If I understood correctly, Framabag is like your "demo", so I thought it would be appropriate to ask the question here. Apologies if I was wrong :-)

Thanks!

**Comment by tcitworld** [comment]
Hi,
It will be done as soon as possible. We need to write some migration scripts.

**Comment by biva** [comment]
Hi!
Any news on this framabag upgrade topic?

**Comment by tcitworld** [comment]
It has been done, but I've encountered issues while migrating some accounts, so I'm not doing the switch for now.

**Comment by Eisfreak7** [comment]
Is this still happening?

**Comment by tcitworld** [comment]
Yes.

**Comment by tcitworld** [comment]
Planned for tomorrow.

**Comment by thenanobel** [comment]
Is this happening now? I'm having trouble to connect with the **Framabag** server. 😐

**Comment by tcitworld** [comment]
You need to reset your password after the migration.

**Comment by falematte** [comment]
I am not able to use the google chrome extension... What kind of URL are we supposed to insert?

**Comment by tcitworld** [comment]
You need to put framabag.org and create an API client on framabag.

**Comment by thenanobel** [comment]
I've reset my password. And I have been able to log in. But, unfortunately I couldn't find the articles I had saved before. 😞

**Comment by nicosomb** [comment]
I think that we can close this issue. If you have issues with Framabag, please contact Framasoft support: https://contact.framasoft.org/

**Comment by tcitworld** [comment]
> But, unfortunately I couldn't find the articles I had saved before

As written in the email I've sent, they will come progressively over the next few days.
