### ISSUE TITLE
Bookmarklet import does not work - page closes too fast

### ISSUE THREAD

**Issue by ToeiRei** [wallabag/wallabag#1960]
### Issue details

Using the bookmarklet 'bag it!' you cannot import articles as it closes too fast

### Environment

* wallabag version: 2.0.2
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.0
* OS: Linux
* type of hosting (shared or dedicated): shared on own server
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL/MariaDB
* Browser: Chrome 49

### Steps to reproduce/test case

1. Use the bookmarklet
2. Wonder why the article isn't in 'unread'
3. Look at the JS code used in the Bookmarklet
4. Remove `wllbg.close();` to keep the window open to maybe get an error message
5. Be astonished that it works and come to the conclusion that `wllbg.close();` kicks in too fast for actually getting the request through the server

**Comment by ToeiRei** [comment]
could be related to #238 in some way.

**Comment by tcitworld** [comment]
I'm not sure what the expected behavior should be : tab staying opened a few seconds ?

Things that we can do are quite limited with the bookmarklet, I'm not even convinced that we should support it in the future.

**Comment by ToeiRei** [comment]
If it stays open, the client got enough time to establish a connection and do the request. I'd suppose that the tab staying open showing the article fetched sounds like a proper solution as you are instantly able to review the spidered page.

**Comment by tcitworld** [comment]
I'll ask for other people's opinion, and make the change if needed.

**Comment by nicosomb** [comment]
Can reproduce on Chrome 50. 
Can't reproduce on Firefox 45.

**Comment by ddeimeke** [comment]
Reproduced on Firefox 45.0.2 (Linux) and Firefox 38.0.x (Windows).

**Comment by PeterTGarner** [comment]
I've been running more tests and it looks like the "wllbg.close;" in the bookmarklet _is_ the problem. If I remove that I have no problem. The web server running Wallabag is quite slow.  This would be a much-appreciated fix, or replace with something else.

**Comment by hugligan** [comment]
PeterTGarner, thank you!! That fixed my issueses as well. Ive been using wallabag for a good year or two and this is the single most important feature if you ask me!

**Comment by Perksls** [comment]
i was also having problems with the bookmarklet 
i've set a timeout on close, and everything seems good now, mine:

`javascript:var url=location.href||url;var wllbg=window.open('http://wallabag.url/bookmarklet?url=' + encodeURI(url),'_blank');setTimeout(function () { wllbg.close();}, 100);void(0);` 

i think that if you just adjust the setTimeout value to fit your needs everything should be good to go
