### ISSUE TITLE
[Installation V2] Impossible to install: post-install-cmd error

### ISSUE THREAD

**Issue by biva** [wallabag/wallabag#1961]
### Issue details

I try to install wallabag v2, but I'm blocked on step 4 (following instructions here: https://www.wallabag.org/pages/download-wallabag.html). The command `SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist` returns:

<pre><code>Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
sh: 1: @post-cmd: not found
Script @post-cmd handling the post-install-cmd event returned with an error
</blockcode>

  [RuntimeException]
  Error Output: sh: 1: @post-cmd: not found

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--] [<packages>]...</code></pre>

### Environment

* wallabag version: 2.0.2
* How did you install wallabag: Via `git clone` 
* Last wallabag version that did not exhibit the issue (if applicable): 1.9 (deleted before this fresh install)
* Ubuntu 15.10 - 4.2.0-35-generic - x86_64
* Server version: Apache/2.4.12 (Ubuntu)
* PHP 5.6.11-1ubuntu3.1 (cli)
* mysql  Ver 14.14 Distrib 5.6.28
* dedicated hosting

**Comment by nicosomb** [comment]
Hello,

It's your composer installation which seem to has issues. How did you install it ? This could help too : https://github.com/composer/composer/issues/3692#issuecomment-72062966

(same problem than http://support.wallabag.org/discussions/problems/468-symfony-problems-trying-to-install-v200-on-an-odroid-xu4)

**Comment by biva** [comment]
Hello, and thanks for your quick answer.

I installed composer following the instructions here: https://getcomposer.org/download/

I installed wallabag 1.9 last year (I deleted it before this install of V2), and today, I saw a lot of messages similar to `Skipped installation of bin/doctrine-migrations for package doctrine/migrations: name conflicts with an existing file`. 

So yes, it seems similar to http://support.wallabag.org/discussions/problems/468-symfony-problems-trying-to-install-v200-on-an-odroid-xu4

I don't understand how to "Run the installer with your php53 so it checks your local settings" like suggested in https://github.com/composer/composer/issues/3692#issuecomment-72062966 . Could you explain me how to do that?

But I tried to follow the idea and added `detect_unicode = Off` at the end of my `php.ini` (`sudo nano /etc/php5/apache2/php.ini`). But it doesn't change anything.

**Comment by biva** [comment]
In order to complete my previous message, I tried this, but nothing was better:
- `composer diagnose` returns OK for everything
- `composer self-update` is done

I finally found a solution by totally uninstall composer from my system, and install it again:
`sudo apt-get purge composer`
`sudo apt-get autoremove`
`sudo find / -iname composer.phar -exec rm {} \+;`
`rm -rf /home/<user>/.composer`
`sudo rm -rf /home/<user>/wallabag`

And make a fresh install following https://getcomposer.org/doc/00-intro.md#locally

**Comment by tcitworld** [comment]
This should be put in a **Known issues/FAQ** section.

**Comment by nicosomb** [comment]
In website?

**Comment by tcitworld** [comment]
Inside the documentation.
