### ISSUE TITLE
Can't fetch indiegogo project

### ISSUE THREAD

**Issue by hubertbanas** [wallabag/wallabag#1972]
### Issue details
I tried to fetch the following 
https://www.indiegogo.com/projects/turris-omnia-hi-performance-open-source-router#/
and got
"wallabag can't retrieve contents for this article. Please report this issue to us."

### Environment

* wallabag version 2.0.2
* installed using docker image provided at https://hub.docker.com/r/wallabag/wallabag/ 
* storage system: SQLite

**Comment by j0k3r** [comment]
Page is loaded using an ajax query, we can't retrieve the content then ...
See https://github.com/wallabag/wallabag/issues/1520
