### ISSUE TITLE
Can't fetch articles from NYTimes.com

### ISSUE THREAD

**Issue by TRox1972** [wallabag/wallabag#1979]
When trying to fetch articles from nytimes.com, [like this one](http://www.nytimes.com/politics/first-draft/2016/04/24/charles-koch-says-he-could-possibly-support-hillary-clinton/), it fails to fetch the title nor the content. I am using version 2.0.3 on desktop.

**Comment by Strubbl** [comment]
can still reproduce with 2.2.3
also does not work: https://www.nytimes.com/2017/01/06/business/sweden-work-employment-productivity-happiness.html because it gets redirect to mobile main page.

**Comment by j0k3r** [comment]
Content is well fetched for me on both the 2.3 and 2.2.3 (and it doesn't matter it uses the mobile website):

![image](https://user-images.githubusercontent.com/62333/27261636-71b7e13e-5447-11e7-9b97-b74e9709aefa.png)

**Comment by Strubbl** [comment]
okay, my issue solved. Thank you for pushing me in the right direction. I remove the vendor folder and ran make update. Afterwards fetching works. Thanks

But the originial issue from TRox1972 still remains
