### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#1982]
There are some things I'm missing right now at the moment:

- [x] delete tag by slug
- [x] delete multiple tags with one request
- [x] parameter `since` in `/api/entries` to get all items that were created or updated after a specific date/timestamp

Additionally I think the `id` property for each tag is quite senseless. It can be used internal for the database index, but the API doesn't need to have access on it. `slug` and `label` should be enough.

**Comment by tcitworld** [comment]
The first two requests are a WIP at https://github.com/wallabag/wallabag/pull/2175.

**Comment by tcitworld** [comment]
And the third is here : #2176.

**Comment by jlnostr** [comment]
Nice!
