### ISSUE TITLE
Doc improvement about installation and rights permission

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#1983]
### Environment

* wallabag version 2.0.3
* How did you install wallabag? `git clone`
* php version: 5.6.19
* OS: Debian 8.5
* type of hosting : dedicated
* which storage system you choose at install:  PostgreSQL

### Installation process
after ending the installation from the console and used http://doc.wallabag.org/en/master/user/installation.html#installing-on-nginx

I got a blank page, which was in fact an error HTTP 500

Here are the log with Nginx :

```log
#0 /home/sites/mybag/wallabag/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /home/sites/mybag/wallabag/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php(58): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /home/sites/mybag/wallabag/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(108): Monolog\Handler\AbstractHandler->handleBatch(Array)
#3 /home/sites/mybag/wallabag/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\FingersCrossedHandler->handle(Array)
#4 /" while reading response header from upstream, client: .... , server: mybag, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "mybag"
2016/04/25 14:08:31 [error] 29406#0: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/sites/mybag/wallabag/var/logs/prod.log" could not be opened: failed to open stream: Permission denied' in /home/sites/mybag/wallabag/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:97
```

As you can see it's a stupid permission denied. I authorized "www-data" user (of nginx process) to access to  /home/sites/mybag/wallabag/web but not to /home/sites/mybag/wallabag/var

May be a notice about the apache/nginx user permission and the folders to access could be helpful ;-)

**Comment by nicosomb** [comment]
Hello @foxmask! 
If you have time to contribute to our documentation, your pull request is welcome ;-)
