### ISSUE TITLE
Tags not handled in /api/entries

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#1984]
### Issue details

The API isn't handling tags as mentioned in the documentation, [there's simply no code for it](https://github.com/wallabag/wallabag/blob/master/src/Wallabag/ApiBundle/Controller/WallabagRestController.php#L52) :D

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.3
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 5.5.10
* OS: CentOS
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

**Comment by ThibaudDauce** [comment]
It could be really cool to have that for the Firefox extension (add tag after saving a page)

**Comment by nicosomb** [comment]
In fact, I change the milestone, because we decided to implement tags features for wallabag 2.1.

**Comment by tcitworld** [comment]
What is the issue here ?
If I access `api/entries.json`, `api/entries/1.json`, or `api/entries/1/tags.json`, I always get the tags (on master branch as on 2.1).

**Comment by jlnostr** [comment]
Yep, I can delete or add tags to an item. However if I want to recieve items with one or more specific tags (`GET /api/entries.json` with `tags` parameter) the resulted items doesn't contain the tags or just one of them.
The second issue I found is that I can't delete an tag from all items (`DELETE /api/tags/1337.json`).

**Comment by tcitworld** [comment]
I fixed the first issue at #2174.

I can't reproduce the second issue : I attributed a tag to two articles, and deleted it successfully without issues.

**Comment by jlnostr** [comment]
Ah, had a look at my unit tests again. The API was working, but my test was depending on the first issue you already fixed and therefore it was failing.
