### ISSUE TITLE
The CSRF token is invalid. Please try to resubmit the form.

### ISSUE THREAD

**Issue by dlgoodr** [wallabag/wallabag#1988]
### Issue details
Attempt to add URL to wallabag, get error "The CSRF token is invalid. Please try to resubmit the form."
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.3
* How did you install wallabag? Via `git clone` or by downloading the package? Downloading package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:5.5.9+dfsg-1ubuntu4.14
* OS: Ubuntu 14.04
* type of hosting (shared or dedicated): Shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case
add URL to wallabag

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by j0k3r** [comment]
Could you try to logout, remove cookie, empty browser cache, login again and try to add an url?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by gufertum** [comment]
I had the same issue on the first login after a fresh install, but cleaning the browser cache did resolve the issue.

**Comment by bermudi** [comment]
I am having this issue, what do I do? Also, if I try to log out it just reloads the main page instead of logging me out.

**Comment by j0k3r** [comment]
Could you clear your cookie and open the page in a new tab and try again?
