### ISSUE TITLE
using API from javascript

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#1989]
I begin to make chrome extension for v2

But I cannot use API from javascript! After call fetch (repeatable from any browser console)

```
fetch(
   "http://v2.wallabag.org/oauth/v2/token", 
   { 
       method: "POST",
       mode: "cors", 
       body: JSON.stringify(
       { 
         "grant_type": "password", 
         "client_id": "9_21rptr1u3dno4skgsg8kckgg400cc0kg8cog44440kw8cw8sw8", 
         "client_secret": "ut6o16vveq8ck8c8kscgwsggcs8kok8os4448gscwsscoc0g0", 
         "password": "wallabag", 
         "username": "wallabag" 
       })
   })
   .then(function(res){ console.log(res) })
   .catch(function(res){ console.log(res) })
```

I got 

```
VM43:1 POST http://v2.wallabag.org/oauth/v2/token (anonymous function) @ VM43:1
about:blank:1 Fetch API cannot load http://v2.wallabag.org/oauth/v2/token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 400. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

and in response body 
`{"error":"invalid_request","error_description":"Invalid grant_type parameter or parameter missing"}`

but just with HTTPie all works just fine!

```
HTTP/1.1 200 OK
CF-RAY: 29a1079015792708-FRA
Cache-Control: no-store, private
Connection: Keep-Alive
Content-Type: application/json
Date: Wed, 27 Apr 2016 08:50:54 GMT
Pragma: no-cache
Proxy-Connection: Keep-Alive
Server: cloudflare-nginx
Set-Cookie: __cfduid=d9f5250c0db520867fdb8f7e494713d091461747054; expires=Thu, 27-Apr-17 08:50:54 GMT; path=/; domain=.wallabag.org; HttpOnly
Transfer-Encoding: chunked

{
    "access_token": "N2QyZWQxZjVjMTI4M2QyMjQ2MTBjMDM5OWZlZmQwYjRhZDA3Y2U0ODVmOWZhMTg5NmZmYzQ5YzYxOWUwNDk1MA",
    "expires_in": 3600,
    "refresh_token": "ODc1YTkwMWZmNWI4ZDcxYWQ0Zjc0MmMxMmFjNTIxNGEzNjRjZmZhOGM2ZjI3ODRiYzAxZDVlYWQ3N2JkYzA0Zg",
    "scope": null,
    "token_type": "bearer"
}
```

**Comment by nicosomb** [comment]
Hello @Rurik19! 

I think this documentation can be useful https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by tcitworld** [comment]
Also, please check out the extension for Firefox : https://github.com/ThibaudDauce/wallabag-firefox

**Comment by Rurik19** [comment]
Thanks for the links, they are useful. So - the problem is that to get right result I MUST set the 
`Content-Type: application/json` header in request. But, according cors docs

> The only allowed values for the Content-Type header are:
application/x-www-form-urlencoded
multipart/form-data
text/plain

So browser makes one more "preflight" request with OPTIONS http type to inquire if server allow such content-type.

`Access-Control-Request-Headers:content-type
Access-Control-Request-Method:POST`

And for **this** OPTIONS request wallabag api response that

> Request header field content-type is not allowed by Access-Control-Allow-Headers

There are just NO such header in response for OPTIONS request

`HTTP/1.1 200 OK
Connection: Keep-Alive
Proxy-Connection: Keep-Alive
Transfer-Encoding: chunked
Date: Wed, 27 Apr 2016 11:22:06 GMT
Content-Type: text/html; charset=UTF-8
Server: cloudflare-nginx
Set-Cookie: __cfduid=d1f9d80eb52e831fdc9bd7aadaebf3aca1461756126; expires=Thu, 27-Apr-17 11:22:06 GMT; path=/; domain=.wallabag.org; HttpOnly
Cache-Control: no-cache
Access-Control-Allow-Origin: null
CF-RAY: 29a1e51143c615a1-FRA
`

About firefox extension - it uses firefox sdk, which I cannot use in chrome

**Comment by Rurik19** [comment]
It possible to resolve by adding this reaction to OPTION requests to server config (nginx in my case) 
but I think that not all the users of wallabag can setup server ?

**Comment by jlnostr** [comment]
Hey there,
I had this problem at the beginning, too. Try setting the `Content-Type` to `application/json`, it worked for me. I don't know if you're running Windows, but if you do, I can recommend [Fiddler](http://www.telerik.com/fiddler) which shows you all the requests beautifully. Wireshark should work, too, but I don't have experience with it. In both tools you can then see the differences and therefore you can try to come closer to the HTTPie request.

My request looks like the following, in case you want to know:
```
POST https://my-wallabag-host.de/oauth/v2/token HTTP/1.1
Accept-Encoding: gzip, deflate
Content-Length: 271
Content-Type: application/json; charset=UTF-8
Host: my-wallabag-host.de
Connection: Keep-Alive
Cache-Control: no-cache
```

**Comment by Rurik19** [comment]
**jlnostr** - yes, I wrote above about it. But it is at fact server issue - it must return right headers for CORS. I think there should be a some part in documentation about server setup for CORS request handling.

**Comment by nicosomb** [comment]
@Rurik19 Can we close this issue?

**Comment by Rurik19** [comment]
@nicosomb sure.
