### ISSUE TITLE
filter list by tag

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#1996]
### Issue details

It will be helpful if we could filter our list of articles by tag
I opened the same on the adroid app side here wallabag/android-app#230 in case the API could permit to save all of us ;)

### Environment

* wallabag version 2.0.3
* How did you install wallabag? Via `git clone` 
* php version: 5.6
* OS: linux debian 8.5
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install : PostgreSQL

**Comment by nicosomb** [comment]
I think that https://github.com/wallabag/wallabag/pull/1943 is the solution.

**Comment by foxmask** [comment]
I cant say that until i could not test it :-) but i hope so

**Comment by j0k3r** [comment]
Will (hopefully) be implemented in 2.1: https://github.com/wallabag/wallabag/issues/1197
