### ISSUE TITLE
Synology packet for easy installation

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1998]
Originally reported at http://support.wallabag.org/discussions/suggestions/110-synology-paquet-for-easy-installation

**Comment by nicosomb** [comment]
See https://github.com/SynoCommunity/spksrc/pull/2165

**Comment by nicosomb** [comment]
See https://github.com/SynoCommunity/spksrc/issues/1725

**Comment by 0wnrepo** [comment]
Just bought a synology NAS, this is great to hear !

**Comment by tolkonepiu** [comment]
https://github.com/SynoCommunity/spksrc/pull/2824 merged

**Comment by nicosomb** [comment]
🎉  

I let this issue opened, because I need to update the wallabag.org website and the documentation.

**Comment by j0k3r** [comment]
Looks like it's done but not up to date :man_shrugging: 
https://synocommunity.com/package/wallabag

**Comment by andrewchenshx** [comment]
does not work as of 2020. [the root password issue](https://github.com/SynoCommunity/spksrc/issues/3113) has been there for two years.

**Comment by VeRychard** [comment]
> 
> 
> does not work as of 2020. [the root password issue](https://github.com/SynoCommunity/spksrc/issues/3113) has been there for two years.

have you tried with MariaDB 5 instead of 10? I got through that error with it, now  struggling with white login page..

**Comment by emo1509** [comment]
[Seems like we have an overlapping thread ](https://github.com/SynoCommunity/spksrc/pull/4179#issuecomment-731633411)

I tried with installing both MariaDB5 and MariaDB 10 without success. I even stopped MariaDB 10 to be sure he would connect to MariaDB 5 (port 3306).
