### ISSUE TITLE
add speed reading option

### ISSUE THREAD

**Issue by TRox1972** [wallabag/wallabag#2000]
Could you add a speed-reading feature/option, like e.g. Instapaper has?

**Comment by nicosomb** [comment]
Hello @TRox1972, 

Could you describe this feature please?

**Comment by TRox1972** [comment]
Sorry for bad description. Instapaper has a feature where the user is displayed each word of the article at a selected word-per-minute. The feature makes it much faster to read (especially long) articles faster, because you do not have to move your eyes all the time.

**Comment by tcitworld** [comment]
I'm sure we had another issue like this before, but I can't find any trace of it.

**Comment by nicosomb** [comment]
@tcitworld #522 maybe?

**Comment by tcitworld** [comment]
Yup. Closing here.
