### ISSUE TITLE
Reading speed not defined when creating user via config page

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2004]
### Issue details

If I create a user via config page (tag "Add a new user"), this new user don't have reading speed in his configuration. When he'll add new articles, he will have an error when he'll display entries list.

**Comment by tcitworld** [comment]
See http://support.wallabag.org/discussions/problems/476-error-while-trying-to-display-ex-alllist-or-add-articles-on-a-new-wallabag-202-instance

**Comment by nicosomb** [comment]
Not really the same bug I think.

**Comment by tcitworld** [comment]
I read to fast (that's going to be my thing) :/
