### ISSUE TITLE
Updating 2x?

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#2007]
Hi

Can you please add updating for 2.x? I just did copy over to upgrade to 2.0.3 then all I was getting empty pages in the browser after the upgrade from 2.0.0 to 2.0.3

thanks

**Comment by nicosomb** [comment]
Hello @gerroon!

Is this documentation enough https://www.wallabag.org/pages/download-wallabag.html ?

**Comment by nicosomb** [comment]
I think #2011 will fix this issue.

**Comment by gerroon** [comment]
@nicosomb 

Thanks, but all I am again gettingis  blank page after upgrade ;( If I revert back my site works again.

I am using apache (with a custom port) with sqlite

**Comment by gerroon** [comment]
Hi

PLease check this error log for wallabag. I hope it helps

https://paste.debian.net/678948/

**Comment by tcitworld** [comment]
Your webserver needs to own the directory where wallabag is installed and you need write access too.

**Comment by gerroon** [comment]
@tcitworld 

It is owned by www-data (on Debian). As I said, this web site works as is befoire the upgrade

**Comment by gerroon** [comment]
Here are the permissions

drwxr-xr-x  5 www-data www-data 4.0K May  2 10:07 app/
drwxr-xr-x  2 www-data www-data 4.0K May  2 10:15 bin/
-rw-r--r--  1 www-data www-data 3.3K May  2 10:07 build.xml
-rw-r--r--  1 www-data www-data  400 Apr 11 19:54 Capfile
-rw-r--r--  1 www-data www-data 6.4K May  2 10:07 CHANGELOG.md
-rw-r--r--  1 www-data www-data  271 Apr 11 19:54 .composer-auth.json
-rw-r--r--  1 www-data www-data 4.5K May  2 10:07 composer.json
-rw-r--r--  1 www-data www-data 212K May  2 10:07 composer.lock
-rwxr-xr-x  1 www-data www-data 1.6M Apr 11 19:55 composer.phar*
-rw-r--r--  1 www-data www-data 1.1K Apr 11 19:54 COPYING.md
-rw-r--r--  1 www-data www-data  282 Apr 11 19:54 CREDITS.md
drwxr-xr-x  4 www-data www-data 4.0K Apr 11 19:54 data/
drwxr-xr-x  6 www-data www-data 4.0K Apr 11 19:54 docker/
-rw-r--r--  1 www-data www-data 1.4K Apr 11 19:54 docker-compose.yml
drwxr-xr-x  5 www-data www-data 4.0K Apr 11 19:54 docs/
-rw-r--r--  1 www-data www-data  182 Apr 11 19:54 .editorconfig
-rw-r--r--  1 www-data www-data  138 Apr 11 19:54 Gemfile
-rw-r--r--  1 www-data www-data  758 Apr 11 19:54 Gemfile.lock
drwxr-xr-x  8 root     root     4.0K May  2 10:07 .git/
drwxr-xr-x  2 www-data www-data 4.0K Apr 11 19:54 .github/
-rw-r--r--  1 www-data www-data  609 Apr 11 19:54 .gitignore
-rw-r--r--  1 www-data www-data 1.1K Apr 11 19:54 phpunit.xml.dist
-rw-r--r--  1 www-data www-data 1.3K May  2 10:07 README.md
-rw-r--r--  1 www-data www-data 2.8K Apr 11 19:54 RELEASE_PROCESS.md
-rw-r--r--  1 www-data www-data  553 Apr 11 19:54 .scrutinizer.yml
drwxr-xr-x  3 www-data www-data 4.0K Apr 11 19:54 src/
-rw-r--r--  1 www-data www-data 1.6K May  2 10:07 .travis.yml
drwxr-xr-x  5 www-data www-data 4.0K May  2 10:15 var/
drwxr-xr-x 49 www-data www-data 4.0K May  2 10:15 vendor/
drwxr-xr-x  4 www-data www-data 4.0K Apr 11 19:59 web/

**Comment by gerroon** [comment]
@tcitworld 
Btw are saying that based on looking at the error log I posted above?

**Comment by tcitworld** [comment]
Yup, it says `The directory "/var/www/wallabagII/var/cache/prod/annotations" is not writable`. Try `chmod 755 -R /var/www/wallabagII/`

**Comment by gerroon** [comment]
@tcitworld 

I am sorry to say but that did not help at all. Also is not it dangerous to 755 the whole wallabag directory in the first place?

**Comment by tcitworld** [comment]
The access write error is gone. Can you try to reinstall now ? 
`SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist`
`php bin/console wallabag:install --env=prod`

**Comment by gerroon** [comment]
[Doctrine\DBAL\Exception\TableNotFoundException]                                                                   
  An exception occurred while executing 'DELETE FROM wallabag_craue_config_setting':                                 
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag2.wallabag_craue_config_setting' doesn't exist  
                                                                                                                     

                                                                                                                     
  [Doctrine\DBAL\Driver\PDOException]                                                                                
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag2.wallabag_craue_config_setting' doesn't exist  
                                                                                                                     

                                                                                                                     
  [PDOException]                                                                                                     
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag2.wallabag_craue_config_setting' doesn't exist  
                                                                                                                     

sudo -u www-data php bin/console wallabag:install --env=prod  6.67s user 0.36s system 31% cpu 22.637 total

**Comment by gerroon** [comment]
Any recommendation?

**Comment by nicosomb** [comment]
Hello @gerroon !
No need to post a new message 8 hours after your last one ;-) 
Github issues are here to report bugs, or to propose new features.

We have a chat for support, you can talk with us about your problems here https://gitter.im/wallabag/wallabag

**Comment by gerroon** [comment]
@nicosomb 

I am not sure if I understand your point. Are you saying that this is not a bug or an issue with the upgrade process?

**Comment by gerroon** [comment]
Guys I really need help with this. I am stuck with upgrading to 2.0.4 ;( 

Step 3 of 5. Administration setup.
Would you like to create a new admin user (recommended) ? (Y/n)n
Step 4 of 5. Config setup.

                                                                                                                     
  [Doctrine\DBAL\Exception\TableNotFoundException]                                                                   
  An exception occurred while executing 'DELETE FROM wallabag_craue_config_setting':                                 
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag2.wallabag_craue_config_setting' doesn't exist  
                                                                                                                     

                                                                                                                     
  [Doctrine\DBAL\Driver\PDOException]                                                                                
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag2.wallabag_craue_config_setting' doesn't exist  
                                                                                                                     

                                                                                                                     
  [PDOException]                                                                                                     
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag2.wallabag_craue_config_setting' doesn't exist

**Comment by gerroon** [comment]
Nevermind, I reinstalled it from scratch and imported an older database
