### ISSUE TITLE
Renderer of the main page not align/overlaps

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2008]
### Issue details

On the list of unread post, on the top of the page, "previous" "next" and number of page overlaps each other

### Environment

* wallabag : 2.0.3
* How did you install wallabag? : Via `git clone`
* php version: 5.6
* OS: linux debian 8.5
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install: postgresql

### Steps to reproduce/test case

This can be seen from Firefox 45 on Android, and also on Firefox 45 on desktop version, when you reduce the size of the window of the browser, until the `<nav ...>` disappears

for example 
![overlaps](https://foxmask.trigger-happy.eu/static/2016/05/wallabag_home_page_decalage.png)

**Comment by tcitworld** [comment]
Note to Fix : Disabling
```
.pagination li.prev {
   width: 10%;
}
```
on low widths.
