### ISSUE TITLE
cant set the title of the post from the API when "post"(ing)

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2009]
### Issue details

when doing a post request and providing a title, this one is not taken and Wallabag generate it from the title page ... but for twitter the title becomes "twitter" and I would like to have my own title ;)

### Environment

* wallabag: 2.0.3
* How did you install wallabag? : `git clone`
* php version: 5.6
* OS: linux debian 8.5
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install : PostgreSQL

### Steps to reproduce/test case

create a post with a given title 

see this doc /api/doc#post--api-entries.{_format}

**Comment by j0k3r** [comment]
Looks like we forgot to set the title when creating an entry in [postEntriesAction](https://github.com/wallabag/wallabag/blob/master/src/Wallabag/ApiBundle/Controller/WallabagRestController.php#L107) but we did it when [updating an entry](https://github.com/wallabag/wallabag/blob/master/src/Wallabag/ApiBundle/Controller/WallabagRestController.php#L173-L175).
