### ISSUE TITLE
 wallabag can't retrieve contents for this article. Please report this issue to us. 

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2026]
### Environment

* wallabag : 2.0.3
* How did you install wallabag? `git clone`
* php version: 5.6
* OS: linux debian 8.5
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install:  PostgreSQL

### Steps to reproduce/test case

just trying to save the page

**Comment by j0k3r** [comment]
Well, wallabag is about saving _article_ with **content** from the Internet.

What do you want to save from that page to be able to read it later?

**Comment by foxmask** [comment]
I though i could save the page itself to keep in mind what this service offer. But as its not the way to use wallabag i can understand that you close this issue

**Comment by j0k3r** [comment]
Yep that's not the way wallabag use, thanks for understanding :)
