### ISSUE TITLE
Articles from wired.de are not loaded

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2030]
### Issue details

All articles from https://www.wired.de/ are not loaded. E.g.:

https://www.wired.de/collection/latest/7-film-universen-die-marvel-vom-thron-stossen-wollen
https://www.wired.de/collection/latest/wusstet-ihr-diese-zehn-fakten-zum-500-euro-schein-bald-ist-er-weg
https://www.wired.de/collection/latest/der-humanoide-tauchroboter-oceanone-erforscht-gesunkene-flagschiffe
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.0.3
- How did you install wallabag? Via `git clone` or by downloading the package? git
- Last wallabag version that did not exhibit the issue (if applicable): -
- php version: 5.6
- OS: debian
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql
### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

Just add one of the links above and you see there's no content.

**Comment by nicosomb** [comment]
It works with your links in wallabag 2.1.3. 

Please reopen if necessary.
