### ISSUE TITLE
filtering option only for unread articles

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2031]
### Issue details

filtering does not work for unread articles. If i click on my unread articles, open the filter side bar and then filter for something, it routes to the "all articles" section and displays archived and starred articles in the result. Altough i did not check those in the filter options. I want to apply my filter only on unread articles. Is that somehow possible?

Maybe we can add the option "unread" next to archived and starred?

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.3
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by nicosomb** [comment]
Fixed in #2052.
