### ISSUE TITLE
link of the addons if the footer

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2037]
### Firefox addons link

at the bottom of the page, the link does not leads to the "right" link of the firefox addons 

by right, I mean that I expected to be routed to the page related to the settings language I setup. In other words, I setup "Français" sa language, so I expected to get that link https://addons.mozilla.org/fr/firefox/addon/wallabag/

### Environment

* wallabag version : 2.0.4
* How did you install wallabag? `git clone`
* php version: 5.6
* OS: debian 8.5
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install: PostgreSQL

**Comment by nicosomb** [comment]
Fixed by #2069.
