### ISSUE TITLE
New third-party resource

### ISSUE THREAD

**Issue by joshp23** [wallabag/wallabag#2039]
I've written [a plugin](https://github.com/joshp23/ttrss-to-wallabag-v2) for [Tiny Tiny RSS](https://tt-rss.org/gitlab/fox/tt-rss/wikis/home) to enable 1-click posting to Wallabag.

It works well, thought you might like to have it listed, didn't know where else to put it.

Enjoy ;)

**Comment by nicosomb** [comment]
👍 
You can easily open a new pull request in our documentation (http://doc.wallabag.org/en/master/developer/documentation.html) to add your plugin.

**Comment by nicosomb** [comment]
Added in #2044. 

We need to add the french translation.

**Comment by nicosomb** [comment]
Already done.
