### ISSUE TITLE
consistency between favorite / star(red) terms

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#2041]
### Issue details
There is some inconsistency in the interface for favorite articles. Sometimes you'll find the term star(red) like on the sidebar but sometimes you'll find the term favorite. On the card of articles the icon to make the article favorite is an heart and not a star :). I know I'm nit-picking

### Environment
This is not relevant for this bug but anyway I provide it
* wallabag version : 2.0.4
* How did you install wallabag? git clone
* Last wallabag version that did not exhibit the issue (if applicable): N/a
* php version: 7.0
* OS: ubuntu 16.04
* type of hosting: dedicated
* which storage system you choose at install: SQLite

**Comment by j0k3r** [comment]
Yeah we already fixed some issue like that.

@wallabag/core Should we choose favorite or star ?

**Comment by nicosomb** [comment]
starred ?
