### ISSUE TITLE
missing image in two factor authentication email

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#2045]
### Issue details

The logo is missing in the mail generated by wallabag when sending the two-factor authentication mail

![email_wallabag](https://cloud.githubusercontent.com/assets/8579/15104245/9c6c982e-15b5-11e6-9a03-2d71a35968c5.png)

The picture links to http://v2.wallabag.org/themes/material/img/logo-other_themes.png which returns a 404. 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag: `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: 7.0.4
* OS: debian
* type of hosting: dedicated
* which storage system you choose at install: MySQL

### Steps to reproduce/test case
N/A

**Comment by nicosomb** [comment]
Maybe I forgot to publish assets on v2.wallabag.org. Will check that.

**Comment by nicosomb** [comment]
In `email_auth_code.html.twig`, we need to replace the picture URL by using `asset` 

```
<td style="padding: 20px;" width="96px" valign="top"><img class="image_fix" src="{{ wallabag_url }}/themes/material/img/logo-other_themes.png" alt="logo" title="{{ wallabag_url }}" style="width: 96px; height: 96px;" /></td>
```
