### ISSUE TITLE
Please add support for secured emails via smtp

### ISSUE THREAD

**Issue by carlinhush** [wallabag/wallabag#2046]
### Issue details

Currently, Wallabag cannot send emails via smtp on secured connections (tls/ssl on ports 587 and 995 with SMTP AUTH) even if port number and encryption is defined in mailer settings. Some hosts do not allow for unsecured smtp anymore (e.g. uberspace.de). Gmsil requires secured connections as well.
### Environment
- Tested version of Wallabag: 2.0.3
- Installed via git clone on uberspace (Cent OS)
- php version: 5.6.21
- OS: Cent OS
### Steps to reproduce/test case

Try to send register or forget password link via smtp on secured connection with SMTP AUTH

**Comment by j0k3r** [comment]
Could you paste the configuration you defined?
We are using Swiftmailer to send email. Of course it supports SSL / TLS connexion, you just need to configure it.
Here is a list of available option: http://symfony.com/doc/current/reference/configuration/swiftmailer.html

Configuration is located here: https://github.com/wallabag/wallabag/blob/master/app/config/config.yml#L108

**Comment by carlinhush** [comment]
Hi,
I tried changing the configuration. Also, there was a discussion on Gitter which ended with "Wallabag does not support this"

Please see my issues on Gitter
#1 April 29, 14:46
#2 May 02, 11:50 (copy of config files attached there)

Uberspace requires STARTTLS upon startup of an smtp connection on port 587. when using gmail as smtp for wallabag on uberspace i get the following log entry: app.ERROR: Exception occurred while flushing email queue: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first. h124sm18676411wmf.7 - gsmtp " [] []

Uberspace suggests to use phpmail instead, but I do not know how to configure that.

**Comment by j0k3r** [comment]
Hum yes, I followed this conversation briefly.
Did you clear the cache after each modification on config.yml files? (by launching `php bin/console cache:clear --env=prod`). And if you edit the config_dev.yml file run it without the `--env=prod` param.

**Comment by carlinhush** [comment]
I do not know how to do this.
Also, I cannot really test the settings as after each attempt to send a password reminder email you have to wait for 24 hours before you can send another one. 
I am not proficient in making lots of changes to config files and working with the console.

**Comment by j0k3r** [comment]
Is there any easy way for us to test Uberspace with that behavior?

**Comment by carlinhush** [comment]
I guess so, you can easily open an account with uberspace free of charge for the first month without registration. Otherwise, just contact them at hallo@uberspace.de, they are quite helpful

**Comment by Speedliner** [comment]
Are there any improvements on this matter? I have understood, that Swiftmailer can be configured for using SSL / TLS communication - but how to do that? I followed the links provided above, but was not able to find an working configuration. Could you provide some examples?

**Comment by gruentee** [comment]
Hey guys, I'm also interested in how this issue is progressing.

**Comment by bnvk** [comment]
> Try to send register or forget password link via smtp on secured connection with SMTP AUTH

I have everything else working, it seems, but am unable to do this / thus really use my wallabag instance as I am unable to configure the local machine to do email

**Comment by noplanman** [comment]
Any update on this?
I'm faced with this too :confused:

**Comment by j0k3r** [comment]
Looks like @glego started something few months ago: https://github.com/wallabag/wallabag/pull/3596
Can someone give it a look and tell me if this fix the secured email problem?

Thanks!

**Comment by noplanman** [comment]
@j0k3r Have commented on the 2 PRs by @glego that you referenced above.

Both the "normal" config and the docker setup work for me.
