### ISSUE TITLE
a title a little bit too big

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2047]
### reading an article from smartphone

Here is the list 
![liste article](https://raw.githubusercontent.com/foxmask/foxmask.trigger-happy.eu/master/content/static/2016/05/tmp_17918-Screenshot_20160509-095007-554867495.png)

And the article itself 

![article](https://raw.githubusercontent.com/foxmask/foxmask.trigger-happy.eu/master/content/static/2016/05/tmp_17918-9%20mai%202016%20095332%20GMT%2B02001756358666.png)

Wallabag 2.0.4

**Comment by j0k3r** [comment]
@tcitworld wasn't be fixed in your recent UI changes?

**Comment by tcitworld** [comment]
Yeah, should be better.
