### ISSUE TITLE
Links without titles can't be opened

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#2053]
### Issue details

The article below provides no title. This means I can it only open by accessing the internal URL directly.
### Steps to reproduce/test case
- Save https://github.com/Fody/PropertyChanged/wiki/NotificationInterception
- Try to open it from the main page

**Comment by j0k3r** [comment]
Works fine for me: http://v2.wallabag.org/view/746

**Comment by jlnostr** [comment]
Yep, by typing the url.

> This means I can it only open by accessing the internal URL directly.

But there's no way to open it from the main page. Or is there another way instead of clicking the title to open an article?
![image](https://cloud.githubusercontent.com/assets/5391936/15176955/e820a85a-176d-11e6-9e1e-e11d057c97dd.png)

**Comment by nicosomb** [comment]
Is that a bug in wallabag or in graby?

(about the https://github.com/Fody/PropertyChanged/wiki/NotificationInterception link, I managed to save it and the title is available).

**Comment by j0k3r** [comment]
@nicosomb it needs investigation. If the title isn't found it should display "No title found"

**Comment by Zlitus** [comment]
Maybe the title is found but empty?

**Comment by Kdecherf** [comment]
Well, I have 'some' cases on current master:
![2017-11-18-160039_1920x1080](https://user-images.githubusercontent.com/226063/32981820-a83d1f0c-cc7a-11e7-864a-8019c6215a16.png)

**Comment by Kdecherf** [comment]
The issue could be linked to wallabagger as I don't see it when adding links via the web interface.
