### ISSUE TITLE
Titles are ellipsized too aggressively

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#2055]
### Issue details
ellipsization in card view is buggy sometimes
* at least wallabag should use something to show an ellipsization was done ("..." for instance)
* the word is cut but it remains a lot of space that would permit the word to be displayed
* the word is cut on the very first letter, so it doesn't make no sense (ie: "Improving log-analysis capabilities with l" where l stands for logstash)

### Environment
* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag: `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 7.0.4
* OS: ubuntu 16.04
* type of hosting: dedicated
* which storage system you choose at install: MysSQL

### Steps to reproduce/test case
wallabag some page with long title and sometimes it will exhibit the bug.
I attach some screenshots
![wallabag_1](https://cloud.githubusercontent.com/assets/8579/15176737/d39b816c-176c-11e6-97df-1c1a2ef9011a.png)
![wallabag_2](https://cloud.githubusercontent.com/assets/8579/15176747/de0623c8-176c-11e6-90fb-151245a15d6a.png)

**Comment by nicosomb** [comment]
Fixed by #2230. 

Thank you @modos189 and @bmillemathias !
