### ISSUE TITLE
OAuth2 refresh token functionality works wrong way

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2056]
### Issue details

I'm developing chrome extension, and I have a trouble

After application token expires (3600 sec), I trying to refresh token by POST  with payload
`
{
client_id:"1_bmsaskgrpkgsgo8oockw4ks4kos4gos44sw0c0o4gok804skk"
client_secret:"3t15zkduev40g00cggk8w8ow0sgcg8wwwg0880g4gog04ckcwk"
grant_type:"refresh_token"
refresh_token:"NjczMWViZmNhZTZhNjlmMjkzOTliNzhkNzEwYWM0ZjY0ZTNhMWFmMzliZTJlYjUzOWY1ZGI3M2RkZTg3ZmUwMw"
}
`
I got error :

`{error: "invalid_grant", error_description: "Invalid refresh token"}`

But if I do so **INSIDE** expire period all works!

`{"access_token":"MTVkMmNhOGI5ZWQ4ZTJjNmJiMDI3M2M3ODY5NzJmZjk0M2RhMTBlZjVjY2RlZTA0M2VlOTU1ZDNlYTJiODZlYQ","expires_in":3600,"token_type":"bearer","scope":null,"refresh_token":"YmVkNDJlNTg3ZDAxOWIyNmRjNTVmYWMyOGZlNTg1ZjNmZjYzZDk4NzkzOTE1NmYwNjU0ODBkNjhmYjRkODdmOQ"}`

This is quite useless, refresh token must works for refreshing application token **after** expire period  ends.
### Environment
- wallabag 2.0.4
- How did you install wallabag? Via `git clone`
- type of hosting? dedicated 
- which storage system you choose at install? MySQL
### Steps to reproduce/test case

httpie or curl

**Comment by Rurik19** [comment]
I looked at database and I see that in the table **oauth2_refresh_tokens** in the field **expired_at** stored exactly the same value as in the table **oauth2_access_tokens** for the access token. I think that refresh token must live much longer - say, two weeks?

**Comment by tcitworld** [comment]
Will look into it this week. Thanks for investigating.

**Comment by tcitworld** [comment]
50400 is 14 hours. 1209600 is 14 days.

**Comment by Rurik19** [comment]
Right!
