### ISSUE TITLE
Tagging rule "language" variable not exist

### ISSUE THREAD

**Issue by kreativmonkey** [wallabag/wallabag#2060]
When you add a tagging rule with the language variable like `language = en` you get the message 
> The variable « en » does not exist.
 
you can fix the problem by adding Quotas to the language like `language = "en"`
 
### Environment

* Version: 2.0.4
* Install: Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): i don't know
* php version: 7
* OS: archlinux
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

look above

**Comment by j0k3r** [comment]
This doesn't seems wrong to me to quote the _string_ language.

**Comment by kreativmonkey** [comment]
Yes its no problem to do it. I think a hint at the documentation are relay great. 

But now the problem with this filter is that when you use `en` at the rule and an article is detected with `en-US`, the rule dosn't matched.

**Comment by j0k3r** [comment]
Yep that's an other problem about i18n :-(
