### ISSUE TITLE
Wallabag require postgresql version >=9.1

### ISSUE THREAD

**Issue by be-neth** [wallabag/wallabag#2061]
### Issue details

When using pdo_postgresql with an old version of postgresql (<9.1) wallabag cannot create database due to unsupported feature : "CREATE TABLE IF NOT EXISTS"

First error is that one :

> FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message SQLSTATE[42601] Syntax error: 7 ERROR:  syntax error at or near "NOT"
> LINE 1: CREATE TABLE IF NOT EXISTS lexik_maintenance (ttl timestamp ...
>                         ^' in < Hide Location > wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.0.4
- How did you install wallabag? Via `git clone`
- php version: PHP 5.6.20
- OS: Debian Stable (jessie)
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL
### Steps to reproduce/test case

Install wallabag instance with pdo_postgresql and an old version of postgresql (<9.1).

Useful link : http://stackoverflow.com/questions/1766046/postgresql-create-table-if-not-exists

Regards,

**Comment by j0k3r** [comment]
This verification should be done in the install command: https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Command/InstallCommand.php#L81
