### ISSUE TITLE
saving from twitter : only mobile version

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2063]
### when saving a page from twitter

... we get the mobile.twitter.com version of the post even when we save a page from `https://twitter.com/<user>/status/<id>` instead of twitter.com version

and most of all, we only have the text of the user who posted the tweet, but not everything else, related to this ID, like : 
- date of the tweet
- number of Retweets
- number of Likes
- comment(s) of this status id 

It could be wonderful if we could have the same from the API ;)
### Environment
- wallabag version : 2.0.4
- How did you install wallabag? : Via `git clone`
- php version: 5.6
- OS: debian 
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install :PostgreSQL
### Steps to reproduce/test case

saving a tweet his own wallabag account and we can see that the name of the website is "mobile.twitter.com"

**Comment by j0k3r** [comment]
This is of course en interesting feature.

**Comment by ttheuer** [comment]
This actually _breaks links_ to hashtag search results! (Though this is twitter's fault, probably.)

On web twitter (without `mobile.` appended) you can link to a search like this:

`https://twitter.com/search?q=%23wallabag`

When I save this link into wallabag and then click on it, twitter *redirects me* to

`https://mobile.twitter.com/explore`

I know there is a separate hashtag search, but I always used the general search so far and it always worked until I tried to import it into wallabag.
