### ISSUE TITLE
Write permission on data/db

### ISSUE THREAD

**Issue by mariovor** [wallabag/wallabag#2064]
### Issue details
I installed today wallabag and the site was afterwards not reachable. 
The log stated:
`PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 8 attempt to write a readonly database`

I could solve the issue by giving write access of data/db to www-user.
However, this is not stated in the documentation http://doc.wallabag.org/en/master/user/installation.html#rights-access-to-the-folders-of-the-project

Is this is a bug or just missing in the documentation?
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? git clone
* Last wallabag version that did not exhibit the issue (if applicable): new install
* php version: PHP Version 5.5.33
* OS: debian wheezy
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): default

**Comment by tcitworld** [comment]
Indeed it's missing from the documentation.

**Comment by nicosomb** [comment]
In the documentation, we can see that we say to do a `chmod -R` for these folders: 

* /var/www/wallabag/bin/
* /var/www/wallabag/app/config/
* /var/www/wallabag/vendor/
* /var/www/wallabag/data/

Fixed.
