### ISSUE TITLE
wallabag can't retrieve contents for this article. Please report this issue to us.…

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2067]
### Issue details

this url failed http://pyjobs.fr/job/1921/developpeur-developpeuse-informatique to be taken
### Environment
- wallabag version : 2.0.4
- How did you install wallabag? : `git clone`
- php version: 5.6 
- OS: deibna 8
- type of hosting : dedicated
- which storage system you choose at install : PostgreSQL

**Comment by j0k3r** [comment]
Well, where is the content on that link :flushed: that you need to read later ?
[This link](http://pyjobs.fr/job/1923/dev-ops-h-f-en-cdi-a-paris) might potentially be better to work on ..

**Comment by foxmask** [comment]
yes usually they dont do that ... its not pleasant

**Comment by nicosomb** [comment]
You first link doesn't exist anymore. And other links on this website (like http://pyjobs.fr/jobs/details/4208/administrateur-systeme-reseau-serveur) seem to work.
