### ISSUE TITLE
wallabag can't retrieve contents for this article: blog.martin-graesslin.com

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2070]
### Issue details

http://blog.martin-graesslin.com/blog/2015/07/porting-qt-applications-to-wayland/

Only partial content is loaded

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.20
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
Could you told us what is missing _specificly_?
Because it looks like everything is ok for me: http://v2.wallabag.org/view/872

**Comment by Strubbl** [comment]
content is loaded only until the first emoji. The rest of the article is missing. i found the reason. same as for #2085 and #2081.

I cannot verify this behaviour from the v2.wallabag.org instance, but my instance does not get the whole article. 

After some investigation, i found out that root of all evil is mysql. character set utf8 is not utf8. utf8mb4 is real utf8 support. So i changed my table:

ALTER TABLE `wallabag_entry` CHANGE `content` `content` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL; 
ALTER TABLE `wallabag_entry` CHANGE `title` `title` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL; 

This is not a clean solution, as i have now mixed character sets, but i am too lazy to fix it everywhere. 
Can you influence the mysql character setting during installation?
