### ISSUE TITLE
wallabag can't retrieve contents for this article: forbes.com

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2074]
### Issue details

http://www.forbes.com/sites/sungardas/2014/04/08/fast-food-for-the-mind-why-i-dont-have-a-facebook-or-twitter-account/#3c296ec44100

Content is not loaded.
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.0.4
- How did you install wallabag? Via `git clone` or by downloading the package? git clone
- Last wallabag version that did not exhibit the issue (if applicable):
- php version: 5.6.20
- OS: Debian Jessie
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
Please, use search before posting a site config issue.
Duplicate of https://github.com/wallabag/wallabag/issues/1452

**Comment by Strubbl** [comment]
Okay. But the print page does not contain the content in the JS: http://www.forbes.com/sites/sungardas/2014/04/08/fast-food-for-the-mind-why-i-dont-have-a-facebook-or-twitter-account/print/

The problem here might be, that it automatically redirects to the url without /print/. Maybe because of a missing referer. Can't work around this?

**Comment by j0k3r** [comment]
Could be an idea.

**Comment by Strubbl** [comment]
I don't know why, but content can now be retrieved for that page with wallabag v2.2.2

**Comment by j0k3r** [comment]
Thanks for letting us know :+1:
