### ISSUE TITLE
wallabag can't retrieve title for this article: blog.uberspace.de

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2078]
### Issue details

https://blog.uberspace.de/telearbeit/

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.20
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
I guess it's related to emoji in the title.

**Comment by Strubbl** [comment]
yes, you are right.
