### ISSUE TITLE
wallabag can't retrieve contents for this article: gizmodo.com

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2079]
### Issue details

http://gizmodo.com/there-are-some-super-shady-things-in-oculus-rifts-terms-1768678169

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.20
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by Strubbl** [comment]
should be fixed with https://github.com/j0k3r/graby-site-config/pull/10

**Comment by j0k3r** [comment]
see https://github.com/fivefilters/ftr-site-config/pull/172
