### ISSUE TITLE
wallabag can't retrieve contents for this article: lifehacker.com

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2082]
### Issue details

http://lifehacker.com/5932887/im-gina-trapani-and-this-is-how-i-work
http://lifehacker.com/5965839/im-bradford-shellhammer-founder-of-fab-and-this-is-how-i-work

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.20
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by Strubbl** [comment]
This should be fixed with https://github.com/j0k3r/graby-site-config/pull/9

**Comment by j0k3r** [comment]
See https://github.com/fivefilters/ftr-site-config/pull/173
