### ISSUE TITLE
wallabag can't retrieve title for this article: jgnatch.com

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2083]
### Issue details
title missing:
http://jgnatch.com/2013/09/13/what-i-ve-lost-my-coding-knowledge/

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.20
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
There is no title in the `<head>` :no_mouth:

**Comment by Strubbl** [comment]
oh, okay. sorry.
