### ISSUE TITLE
wallabag can't retrieve contents for this article: developer-blog.net

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2085]
### Issue details

https://developer-blog.net/racing-manager-der-phpandroid-formel-1-manager/

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.20
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
Works great for me: http://v2.wallabag.org/view/882
What's wrong with that website for you?

**Comment by Strubbl** [comment]
content is loaded only until the first emoji. The rest of the article is missing. i found the reason. same as for #2081 and #2070. in the latter one i explain more
