### ISSUE TITLE
wallabag can't retrieve contents for this article: wired.de

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2086]
### Issue details

https://www.wired.de/collection/latest/wie-aus-einem-hobbyprojekt-eine-milliarden-nutzer-app-wurde-whatsapp-gruender-jan

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.20
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
You already reported that .. https://github.com/wallabag/wallabag/issues/2030
