### ISSUE TITLE
wallabag can't retrieve contents for this article: o6asan.com

### ISSUE THREAD

**Issue by zertrin** [wallabag/wallabag#2099]
### Issue details

wallabag can't retrieve contents for this article:

https://o6asan.com/blog-e/2016/03/14/how-to-install-a-lets-encrypt-certificate-supports-sans-to-apache-on-windows/

### Environment

* wallabag version (or git revision) that exhibits the issue: _2.0.4_
* How did you install wallabag? Via `git clone` or by downloading the package? _git clone_
* Last wallabag version that did not exhibit the issue (if applicable): _not tested with previous versions_
* php version: _PHP 5.6.20-0+deb8u1 (built: Apr 27 2016 11:26:05)_
* OS: _Debian Jessie_
* type of hosting (shared or dedicated): _dedicated_
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): _SQLite_

**Comment by Strubbl** [comment]
works fine on: http://ftr.fivefilters.org/makefulltextfeed.php?url=https%3A%2F%2Fo6asan.com%2Fblog-e%2F2016%2F03%2F14%2Fhow-to-install-a-lets-encrypt-certificate-supports-sans-to-apache-on-windows%2F&max=3

And also in wallabag. 

@zertrin can you please test with the latest wallabag release again and report if that fixes the issue?

**Comment by zertrin** [comment]
Just upgraded to 2.0.5 and it is still not working:

> No title found
> wallabag can't retrieve contents for this article. Please report this issue to us.

**Comment by zertrin** [comment]
In case it helps, I've used http://siteconfig.fivefilters.org to generate a FiveFilters siteconfig:

```
# Generated by FiveFilters.org's web-based selection tool
# Place this file inside your site_config/custom/ folder
# Source: http://siteconfig.fivefilters.org/grab.php?url=https%3A%2F%2Fo6asan.com%2Fblog-e%2F2016%2F03%2F14%2Fhow-to-install-a-lets-encrypt-certificate-supports-sans-to-apache-on-windows%2F

body: //div[contains(concat(' ',normalize-space(@class),' '),' entry-content ')]
test_url: https://o6asan.com/blog-e/2016/03/14/how-to-install-a-lets-encrypt-certificate-supports-sans-to-apache-on-windows/
```

but `entry-content` seems to be probably a common guess for unknown websites, so not sure if it helps really.

**Comment by j0k3r** [comment]
@zertrin siteconfig are per host based. If you provide the `entry-content` for `o6asan.com` host it won't be used for other host.

Could you then submit a PR to https://github.com/fivefilters/ftr-site-config with your fix?

**Comment by zertrin** [comment]
Done: https://github.com/fivefilters/ftr-site-config/pull/185

> siteconfig are per host based. If you provide the entry-content for o6asan.com host it won't be used for other host.

I get that, but I assume that if a site is not listed on the ftr-site-config list, there is a kind of "default parser" to fallback. And I was wondering why `entry-content` is not a pretty obvious candidate to get the correct content... If we need to create a config site for every domain name in the world, I guess something is wrong in the design...

**Comment by j0k3r** [comment]
As far as I know, a global siteconfig is used for every website

:arrow_right: https://github.com/fivefilters/ftr-site-config/blob/master/global.txt

(and I close this issue this the PR is open on fivefilters/ftr-site-config)
