### ISSUE TITLE
wallabag can't retrieve contents for this article: https://lwn.net/Articles/607652/

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#2100]
### Issue details
https://lwn.net/Articles/607652/ 

### Environment
* wallabag version (or git revision) that exhibits the issue:2.0.4
* How did you install wallabag? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): 1.9.x
* php version: 7.0
* OS: ubuntu 16.04 
* type of hosting: dedicated
* which storage system you choose at install: MySQL

### Steps to reproduce/test case
It used to work on wallabag 1.9.x
I noticed when I edit the page (the pen icon) the url displayed is not https://lwn.net/Articles/607652/ but https://lwn.net/Articles/607652/bigpage which actually returns a 404 Status

**Comment by j0k3r** [comment]
Duplicate https://github.com/wallabag/wallabag/issues/2073
And it still in discussion https://github.com/fivefilters/ftr-site-config/commit/fa1be0ba669893a8de6b6906ce273043d27eaa7d
