### ISSUE TITLE
wallabag can't retrieve contents for this article. 

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2102]
### Issue details

[url I cant get](https://reflets.info/a-la-dgsi-on-aimerait-bien-contraindre-les-operateurs/)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? : Via `git clone`

**Comment by j0k3r** [comment]
This is strange, I've no issue here: http://v2.wallabag.org/view/916

**Comment by Strubbl** [comment]
I can see no issue here, too. 
@foxmask what is the exact problem with this site?

**Comment by foxmask** [comment]
I cant get the content at all.

if I try to add the link direclty in my own wallabag instance I get the title + the image of the article + "wallabag can't retrieve contents for this article."
If I try to add the link from the android client (after having dropped the article before) ; I have the title + wallabag can't retrieve contents for this article.

But if you can get it, then close the ticket.
\_(o/o)_/

**Comment by Strubbl** [comment]
Can you please retry with the latest wallabag release?

**Comment by foxmask** [comment]
i confirm that with 2.0.5 the article is not grabbed but just it's title :/

$ php --version
PHP 5.6.22-0+deb8u1 (cli) (built: Jun  9 2016 07:14:06) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

Linux Debian 8.5
Self hosted
Postgresql

**Comment by j0k3r** [comment]
@foxmask is it still an issue?

**Comment by foxmask** [comment]
No. Thanks you
