### ISSUE TITLE
Article : additional property to indicate origin

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2106]
With Evernote, when I create a note from RSS Feeds, I'm able to put, at the bottom of the body, a custom line:  "Provided by {source of the feeds}". It just a simple concat with the content I made and my custom line "Provided by...". Evernote does not provide specific property .
You can see it here 

![article from evernote](https://raw.githubusercontent.com/foxmask/foxmask.trigger-happy.eu/master/content/static/2016/05/Sans%20titre.png)

Thus I know from where the Article come from.

Example : with a planet of a community : http://planetpython.org/rss20.xml

With it, wallabag create an article for each RSS, but when I look at the article, I dont know that the article comes from PlanetPython. 

So my request here is to ask If we could have a new property that we could use and fill it with a customer string (like "Provided by xxxxx"), and of course if this property could be displayed if the article view.

**Comment by foxmask** [comment]
May I ask how the API now looks like with that wonderful improvement ? :)

**Comment by Kdecherf** [comment]
There is a field `origin_url` which takes a string on `POST api/entries.json` and `PATCH api/entries/{entry}.json`

**Comment by foxmask** [comment]
thanks. Will update https://github.com/foxmask/wallabag_api with that.
