### ISSUE TITLE
SERIOUS BUG - Tags clears on all articles after deleting article contains tags

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2121]
### Issue details

When I delete article with tags, this tag clears from all other articles! It deleted also from DB, both from w_tag and from w_entry_tag tables
That behaviour is as in site and also in API.
(I'v just lost tag "programming" :-(  )

### Environment

* wallabag version 2.0.4

### Steps to reproduce/test case

Don't check this with your existing tag...... just with new one.

**Comment by j0k3r** [comment]
We are so sorry about that, really.
We'll check that ASAP and submit a fix for the upcoming 2.0.5 (should be released tomorrow)
