### ISSUE TITLE
Wrong display in wallabag (mysqlblog.fivefarmers.com)

### ISSUE THREAD

**Issue by TheBigfoot** [wallabag/wallabag#2123]
### Issue details

Wallabag ist unable to retrieve content of this link. 
http://mysqlblog.fivefarmers.com/2012/08/16/understanding-mysql_config_editors-security-aspects/
### Environment
- wallabag version (or git revision) that exhibits the issue: Version: 2.0.4
- How did you install wallabag? `git clone`
- php version: 5.6.22
- OS: CentOS 7.2.1511
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite
### Steps to reproduce/test case

Add Link to wallabag.

**Comment by techexo** [comment]
With 2.3.3, I have a 403 error when trying to fetch the article:
```html
<p>We\'re sorry, but we could not fulfill your request for /2012/08/16/understanding-mysql_config_editors-security-aspects/ on this server.</p>
<p>An invalid request was received from your browser. This may be caused by a malfunctioning proxy server or browser privacy software.</p>
<p>You can use this key to <a href="http://www.ioerror.us/bb2-support-key?key=d481-25e6-1756-6707">fix this problem yourself</a>.</p>
<p>If you are unable to fix the problem yourself, please contact <a href="mailto:todd+nospam@nospam.fivefarmers.com">todd at fivefarmers.com</a> and be sure to provide the technical support key shown above.</p>```

I guess some sort of anti-scrapping mechanism.

**Comment by Strubbl** [comment]
This issue should be fixed when graby-site-config fetches the latest configs.
