### ISSUE TITLE
Change preview picture with API

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2124]
### Issue details

This would be useful to have ability to change or delete preview picture address of the article.
I would add it to my chrome plugin :)

**Comment by j0k3r** [comment]
From your point of view, this should be available only for the update, right?

**Comment by Rurik19** [comment]
yes. with PATCH only, I think

**Comment by tcitworld** [comment]
@Rurik19 How would you find a better preview picture ?

**Comment by Rurik19** [comment]
@tcitworld  I'd show to user several largest picture from article to chose from.

**Comment by j0k3r** [comment]
Fixed in https://github.com/wallabag/wallabag/pull/3106
