### ISSUE TITLE
Button "back" on view page returns alwais on first unread page.

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2125]
### Issue details

Button "back" on view page returns alwais on first unread page, but it should return to **previous** page. I think the referer of the page contains previous address?

**Comment by j0k3r** [comment]
Back link doesn't remember from where you come and always return to the homepage.
Could be enhanced.

**Comment by nicosomb** [comment]
Enhanced by a return to referer?

**Comment by nicosomb** [comment]
Fixed by #2547.
