### ISSUE TITLE
Articles duplicates when URI contains non-ascii characters

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2126]
### Issue details

Articles duplicates when URI contains non-ascii characters

### Environment

* wallabag version 2.0.4

### Steps to reproduce/test case

add param with nonascii chars to url and save -> new article

**Comment by j0k3r** [comment]
Could you give us urls example?

**Comment by Rurik19** [comment]
Easy

this one saves only once
https://habrahabr.ru/company/intel/blog/283066/?aa=asciitext

but this one - as many times as i save it
https://habrahabr.ru/company/intel/blog/283066/?aa=русский

**Comment by j0k3r** [comment]
This will be a bit hard to solve.
Could you give me an example where the parameter really mater on the content? I mean, like if the parameter is broken the content will be 404 or completely different?

Thanks

**Comment by Rurik19** [comment]
> Could you give me an example where the parameter really mater on the content?
No, I cannot. Parameters don't affect the content, but only influence the search of existing article with same URI. The links above are good example.

**Comment by MatElGran** [comment]
http://www.aritylabs.com/post/106091708292/des-contrôleurs-optionnels-grâce-à-constmissing poses problem too. There's a new item created each time I save it.
