### ISSUE TITLE
UI issue in the config panel with small screen (material)

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2127]
### Issue details

With a small screen, there is an issue in the config panel as you can see on the screenshot above.

![screenshot_20160531_050843](https://cloud.githubusercontent.com/assets/4572452/15662121/13839806-26ee-11e6-8675-9b5911a162dc.png)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

1. Go in the config panel
2. Reduce the window of the web browser

**Comment by NerosTie** [comment]
It's an issue in `About` too: 

![screenshot_20160531_052335](https://cloud.githubusercontent.com/assets/4572452/15662343/ed768d06-26ef-11e6-9739-4c4ec1c6508d.png)

**Comment by tcitworld** [comment]
`min-width` for the media query should be around `1130px`, as it seems to be around `990px` today.

**Comment by tcitworld** [comment]
Fixed in next version.
