### ISSUE TITLE
Titles are too short in the tiles (material)

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2128]
### Issue details

Titles in the tiles are too short, sometime I can't even know what is the subject. It's not an issue with the theme baggy.

![screenshot_20160531_051546](https://cloud.githubusercontent.com/assets/4572452/15662249/236c842a-26ef-11e6-883c-1f8a3ef2e99b.png)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable): 1.x
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

no steps

**Comment by j0k3r** [comment]
Can be related to https://github.com/wallabag/wallabag/issues/2055

**Comment by modos189** [comment]
Solved?
