### ISSUE TITLE
UI issue with the panel on the left on small screen (baggy)

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2129]
### Issue details

The panel on the left is an issue on small screens with the theme baggy as you can see on the screenshot above:

![screenshot_20160531_053559](https://cloud.githubusercontent.com/assets/4572452/15662518/c2c96c70-26f1-11e6-9440-a761438a1b69.png)

`Déconnexion` enters in conflict with other entries and there is no possibility to access to other entries (like help, developer, import...) because I can't scroll.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

1. reduce the windows of the web browser

**Comment by tcitworld** [comment]
Should be better now in next release.
