### ISSUE TITLE
On Chrome, the bookmarlet doesn't work

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2130]
### Issue details

On Chrome, when I click on the bookmark, nothing happen. It was not an issue with the bookmarlet of wallabag 1.x.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

1. Use Chrome
2. Add the bookmarklet to your bookmarks 
3. Go to an article to save
4. Click on the bookmark
5. Nothing happen

**Comment by j0k3r** [comment]
Are you using that bookmarklet (https://github.com/Rurik19/wallabagger) from @Rurik19 ?

**Comment by Rurik19** [comment]
I think it about that part of [documentation.](http://doc.wallabag.org/en/master/user/first_article.html)

> By using a bookmarklet
On the Howto page, you have a Bookmarklet tab. Drag and drop the bag it! link to your bookmarks bar of your browser.
Now, each time you're reading an article on the web and you want to save it, click on the bag it! link in your bookmarks bar. The article is saved.

and indeed, in chrome that doesn't work

**Comment by tcitworld** [comment]
May be related to https://github.com/wallabag/wallabag/issues/1960.

**Comment by nickian** [comment]
Here's my solution to this problem. Instead of opening a new window and closing it, just redirect to add article URL:

`javascript:var url=location.href||url;var wllbg=window.location.replace('https://url.com/web/bookmarklet?url=' + encodeURI(url));void(0);`

**Comment by NerosTie** [comment]
@nickian Your solution works well!

**Comment by softmetz** [comment]
I had the same problem in Firefox 47 and @nickian's workaround solved it!
