### ISSUE TITLE
Export to html

### ISSUE THREAD

**Issue by lolhangman** [wallabag/wallabag#2133]
I would like to use Wallabag but I really need to be able to export as html (to be able to import in an other software).

**Comment by tcitworld** [comment]
Can we know what software it is so we can test the export ?

**Comment by lolhangman** [comment]
Evernote for exampe. But the fact is that export to html" is not available yet.

**Comment by tcitworld** [comment]
Exporting to xml and renaming the file with the `.enex` Evernote extension, then importing into Evernote as a backup may give you some results in the meantime.

**Comment by lolhangman** [comment]
thanks, but were is the option to export to xml, I only have json, pdf, mob, epub, choices.

**Comment by tcitworld** [comment]
Using wallabag 2.x, you have an advanced config panel where you can activate xml export.

**Comment by lolhangman** [comment]
ok, I'm currently using framabag, guess they are not up to date...Thanks for your help I'll try this on my own instance asap.

**Comment by tcitworld** [comment]
We didn't update Framabag yet, yes.

**Comment by j0k3r** [comment]
@lolhangman did you succeed?

**Comment by lolhangman** [comment]
yep,Exporting to xml and renaming the file with the .enex Evernote extension, then importing into Evernote as a backup may give you some results in the meantime. then export to html from evernote

**Comment by j0k3r** [comment]
Thanks for the workaround
