### ISSUE TITLE
Wallabag can't retrieve contents of a page

### ISSUE THREAD

**Issue by Poorchop** [wallabag/wallabag#2135]
### Issue details

When trying to add [this link](http://www.ufocasebook.com/gulfbreeze.html) to wallabag, I get "wallabag can't retrieve contents for this article. Please report this issue to us."

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.4
* How did you install wallabag? Via `git clone` or by downloading the package? Downloading the package
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: 5.6.22
* OS: CentOS 7 x64
* type of hosting (shared or dedicated): VPS
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

1. Install wallabag 2.0.4 by downloading the package.
2. Copy this link: http://www.ufocasebook.com/gulfbreeze.html
3. Go to your wallabag and add a new entry.
4. Add the above link.

**Comment by Strubbl** [comment]
works with http://ftr.fivefilters.org/makefulltextfeed.php?url=http%3A%2F%2Fwww.ufocasebook.com%2Fgulfbreeze.html&max=3 but not in wallabag.

**Comment by j0k3r** [comment]
So it was basically a problem when converting the content to utf8, everything was broken and no text were extracted.
Will be fixed in next release.
