### ISSUE TITLE
More api/entries filter parameters

### ISSUE THREAD

**Issue by bigretromike** [wallabag/wallabag#2136]
It would be great to have ability to filter more pages out before retrieve. Domain_Name would be great for more automated solutions.

Currently this is only thing missing what I used to use with pocket. Long live the wallabag!

**Comment by j0k3r** [comment]
Could be a good idea !

**Comment by bigretromike** [comment]
currently there is a need to use tools like 'jq' to parse json, extract each domain_name related items, and move to next page to see if there is any left one. Making wallabag just throw only domain_name related entries would be great.

**Comment by nicosomb** [comment]
Duplicate of https://github.com/wallabag/wallabag/issues/1313.
