### ISSUE TITLE
Saving images with v2?

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#2139]
Hi

I cant find information about how to save images in an article in the database. 

I am using 2.0.3 on Debian.

thanks

**Comment by j0k3r** [comment]
This feature hasn't been developped in the v2 yet.
But it is planned

**Comment by aymercury** [comment]
Is this feature still not available? I cannot find any mention of it in any release notes (from 2.0.0 to 2.1.0)...

**Comment by j0k3r** [comment]
It's in progress https://github.com/wallabag/wallabag/pull/2180
We hope to release it with 2.2.0

**Comment by j0k3r** [comment]
Also, duplicate of https://github.com/wallabag/wallabag/issues/2033

**Comment by aymercury** [comment]
Thanks! I am still on 1.9.0 because of this missing feature...

**Comment by j0k3r** [comment]
We know, a lot of people are requiring it :wink:
