### ISSUE TITLE
2 bugs after upgrade to 2.0.5

### ISSUE THREAD

**Issue by fodiator** [wallabag/wallabag#2140]
### Issue details

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to http://gitter.im/wallabag/wallabag.

### Environment

* wallabag version (or git revision) that exhibits the issue:
2.0.5
* How did you install wallabag? Via `git clone` or by downloading the package?
package
* Last wallabag version that did not exhibit the issue (if applicable):
2.0.3
* php version:
PHP 7.0.7-4+deb.sury.org~trusty+1 (cli) ( NTS )

* OS:
ubuntu server 14.04
* type of hosting (shared or dedicated):
shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
SQLite

### Steps to reproduce/test case
upgraded as described in https://www.wallabag.org/pages/download-wallabag.html
(copied data-dir and config, cleared /var/cache) 
restarted Apache2 
calling Wallbag results in a white page

var/apache2/error.log gives: `[:error] [pid 8015] [client 192.168.1.5:58442] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/walla2.0.5/var/cache/prod)\n' in /var/www/walla2.0.5/var/bootstrap.php.cache:2523\nStack trace:\n#0 /var/www/walla2.0.5/var/bootstrap.php.cache(2484): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/walla2.0.5/var/bootstrap.php.cache(2273): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/walla2.0.5/var/bootstrap.php.cache(2304): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/walla2.0.5/web/app.php(28): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/walla2.0.5/var/bootstrap.php.cache on line 2523`

Several directories in ...2.0.5/var/cache could not be created automativalle and have thrown similar errors. I created them manually so 2.0.5 is running now

Bug2 affects the tag-list, please have a look at this http://clip.fastcast.at/screenshot.png screenshot. I do think it is self-explaining. 

Kind regards

**Comment by j0k3r** [comment]
The duplication of tag could be related to an import? If yes, it's a known bug: https://github.com/wallabag/wallabag/issues/1981

Regarding cache permission, you might chmod 777 on the cache directory.

**Comment by fodiator** [comment]
I would suspect it as a lack of security to chmod 777 a directory on a public availabe web-server?

**Comment by tcitworld** [comment]
`chmod 755` might do.

**Comment by yzaguirre** [comment]
You might want to change the folder owner to the **apache2** user and group, like this:
```
chown www-data:www-data -R /var/www/walla2.0.5
```
or change the permissions like mentioned in the comments above.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
