### ISSUE TITLE
Allow socket connection to MySQL

### ISSUE THREAD

**Issue by Neraste** [wallabag/wallabag#2143]
### Issue details

When I try to install the app with the `pdo_mysql` driver communicating by Unix socket, I get the following error when doing `php bin/console wallabag:install --env=prod`:

```
Step 2 of 5. Setting up database.
PHP Warning:  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /srv/www/bag/release-2.0.5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 43
Creating database and schema, clearing the cache
PHP Warning:  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /srv/www/bag/release-2.0.5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 43
The command "doctrine:database:create" terminated with an error code: 1.

                                                                            
  [Exception]                                                               
  The command "doctrine:database:create" terminated with an error code: 1. 
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.5
* How did you install wallabag? Via `git clone` or by downloading the package? tried both
* Last wallabag version that did not exhibit the issue (if applicable): first install
* php version: 5.6.1
* OS: OpenSUSE 13.2 on ARMv7l
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Just tried to install it following the install guide, except that there are no directives for a Mysql install.

Used the following `app/config/parameters.yml` file:

```yml
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: socket:/var/run/mysql/mysql.sock # also tried socket:///var/run/mysql/mysql.sock
    database_port: null
    database_name: symfony
    database_user: symfony_user
    database_password: __password__
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: ovmpmAWXRCabNlMgzlzFXDYmCFfzGv
    twofactor_auth: true
    twofactor_sender: __address__
    fosuser_confirmation: true
    from_email: __address__

**Comment by j0k3r** [comment]
Thanks for reporting this to us, we did not provide configuration for connection using sock right now.
The fix is easy to produce.*

We need to add the option `unix_socket` in the `config.yml` file ([see](http://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration)).
