### ISSUE TITLE
wallabag can't retrieve contents for this article

### ISSUE THREAD

**Issue by borinsky** [wallabag/wallabag#2144]
### Issue details

The following urls can't retrieved: 

http://schuelerlabor.informatik.rwth-aachen.de/module/zauberschule
http://schuelerlabor.informatik.rwth-aachen.de/module/alles-informatik
http://schuelerlabor.informatik.rwth-aachen.de/module/scratchjr
http://schuelerlabor.informatik.rwth-aachen.de/module/robot-karol

.. I get:  wallabag can't retrieve contents for this article. Please report this issue to us.…

... so I do ;-) 

Thank you for this great software ...

### Environment

* wallabag version 2.0.5
* How did you install wallabag? `git clone` 
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6
* OS: freebsd 10.2
* type of hosting (shared or dedicated): freebsd jail
* which storage system you choose at install: SQLite

**Comment by Strubbl** [comment]
should be fixed with https://github.com/fivefilters/ftr-site-config/pull/177

**Comment by Strubbl** [comment]
works with http://ftr.fivefilters.org/makefulltextfeed.php?url=http%3A%2F%2Fschuelerlabor.informatik.rwth-aachen.de%2Fmodule%2Fzauberschule&max=3

But not in wallabag. @j0k3r any idea?

**Comment by j0k3r** [comment]
Will be fixed in the next release.
Removing elements was to agressive with the `info` word.
