### ISSUE TITLE
Wrong estimated reading time for articles in non-latin languages

### ISSUE THREAD

**Issue by di72nn** [wallabag/wallabag#2147]
### Issue details

It seems that most of the articles in Russian (maybe in some other non-Latin alphabets too) have "estimated reading time: < 1 min" no matter of their actual length.
### Environment
- wallabag version: `2.0.5`
- How did you install wallabag? `latest-v2-package`
- Last wallabag version that did not exhibit the issue (if applicable): -
- php version: `7.0.7`
- OS: `Arch Linux`
- type of hosting: `dedicated`
- which storage system you choose at install: `MariaDB`
### Steps to reproduce/test case

Add [an article in Russian](https://geektimes.ru/company/mvideo/blog/277248/), check estimated reading time.

**Comment by j0k3r** [comment]
You're right. We are using this snippet to calculate the reading time of a content.

```php
$readingTime = floor(str_word_count(strip_tags($text)) / 200);
```

`str_word_count` works great for latin alphabet but there is no `mb_str_word_count` for non-latin alphabet.
There is a bug opened on PHP about that: https://bugs.php.net/bug.php?id=63671

We can try several other ways:

- using a built-in `mb_str_word_count`: http://stackoverflow.com/a/13884355/569101
- using an other method to count word ([from yii2](https://github.com/yiisoft/yii2/blob/cfbe50e96d0a6dcbad23afff015aa5b5bdde1072/framework/helpers/BaseStringHelper.php#L274-L284)):
 ```php
 return count(preg_split('/\s+/u', $string, null, PREG_SPLIT_NO_EMPTY));
 ```

**Comment by yzaguirre** [comment]
Spanish is also affected in `2.0.5`, all articles have "estimated reading time: < 1 min".

**Comment by lapineige** [comment]
@j0k3r how does this works ?
> $readingTime = floor(str_word_count(strip_tags($text)) / 200);
What is the text var ? A raw text data ?

I'm actually trying to implement such a reading time estimation feature in FreshRSS as an extension (see issue above) - and I'm interested to know how do you get the text (because on my client side, I need to parse an html doc) from a web page.

Thanks :)
(I'm sorry if it's completely off-topic)

**Comment by tcitworld** [comment]
`$text` is the whole text displayed in wallabag, parsed through Graby.
