### ISSUE TITLE
wallabag can't retrieve contents for this article: osqledaren.se

### ISSUE THREAD

**Issue by chepec** [wallabag/wallabag#2150]
### Issue details

http://osqledaren.se/ol-gor-bangladesh/
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.0.5
- How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
- Last wallabag version that did not exhibit the issue (if applicable):
- php version: `5.6.22`
- OS: Debian Jessie
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL
### Steps to reproduce/test case

Pasting link into "new entry" or adding via Firefox addon v2 both fails with `wallabag can't retrieve contents for this article`.

**Comment by Strubbl** [comment]
Here the issue is, that the site thinks we are a crappy Internet Explorer browser. Currently graby cannot send http headers (user agent), so there is no chance to fix this at the moment.

**Comment by j0k3r** [comment]
The problem is bigger than that.
We automatically detect a refresh meta tag in the html source, because of:

```html
<!--[if lte IE 8]>
<meta http-equiv="refresh" content="0; url=/ie.html" />
<![endif]-->
```

Here is the log from graby:

> Meta refresh redirect found (http-equiv="refresh"), new URL: http://osqledaren.se/ie.html

Graby should remove those comment before analysing html
