### ISSUE TITLE
wallabag can't retrieve contents of fairly simple HTML article

### ISSUE THREAD

**Issue by chepec** [wallabag/wallabag#2152]
### Issue details

http://szabo.best.vwh.net/shell.html
wallabag can't handle this document. Returns "No title found" and "wallabag can't retrieve contents for this article..."

### Environment

* wallabag version (or git revision) that exhibits the issue: `2.0.5`
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: `5.6.22`
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Paste the URL into Wallabag "new entry", or add via Firefox addon.

**Comment by Strubbl** [comment]
hihi, in the source of the page:

`<meta name="GENERATOR" content="Mozilla/4.7 [en] (WinNT; I) [Netscape]">`

Nice peace if internet history. 

There are too many syntax/html errors on that page: https://html5.validator.nu/?doc=http%3A%2F%2Fszabo.best.vwh.net%2Fshell.html
Even with tidy=no, i cannot get the content of that page.

**Comment by chepec** [comment]
That explains why the import didn't work. Thanks for explaining the issue so clearly.
