### ISSUE TITLE
wallabag retrieves only parts of multi-part feature article

### ISSUE THREAD

**Issue by chepec** [wallabag/wallabag#2153]
### Issue details

http://www.houstonchronicle.com/nasa/adrift/1/
This is a seven part feature article with lots of text and plenty of graphics.
Wallabag managed to get the title, and a subset of the graphics (including their captions!).
But sadly, none of the body text.

### Environment

* wallabag version (or git revision) that exhibits the issue: `2.0.5`
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: `5.6.22`
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Paste URL into "new entry" box, or add via Firefox addon.

**Comment by Strubbl** [comment]
see https://github.com/fivefilters/ftr-site-config/pull/178 for fix

**Comment by chepec** [comment]
I recently upgraded to Wallabag 2.0.7 (stack is now PHP 5.6.24, Debian Jessie, dedicated server, MySQL), and this issue still exists. 

Thanks for the pointer to your pull request, but it seems not much has changed since your comment that only images and captions show up in Wallabag (but no article text). I noted the same behaviour.

But in any case, I think this kind of multi-part feature article is an edge case, and I'm very happy with Wallabag. Keep up the good work!

**Comment by j0k3r** [comment]
@chepec yep, the PR hasn't been merged so the _problem_ is still here

**Comment by j0k3r** [comment]
@chepec will be available in the next release 🚀
