### ISSUE TITLE
wallabag only retrieves first page of multi-page articles on arstechnica.co.uk

### ISSUE THREAD

**Issue by chepec** [wallabag/wallabag#2154]
### Issue details

This is a two-page feature article with an in-line separator between the pages.
Wallabag fetched only the first page.
- http://arstechnica.co.uk/information-technology/2016/05/eben-moglen-gpl-online-advertising-is-becoming-a-perfect-despotism/

This is a 9 page article with in-line separator between the pages. Wallabag fetched only the first page.
- http://arstechnica.co.uk/science/2016/06/what-is-open-access-free-sharing-of-all-human-knowledge/

### Environment

* wallabag version (or git revision) that exhibits the issue: `2.0.5`
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: `5.6.22`
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Paste URL into "new entry" box, or add via Firefox addon.

**Comment by Strubbl** [comment]
I have started a config, follow progress here: https://github.com/fivefilters/ftr-site-config/pull/176

**Comment by chepec** [comment]
Ok, that's looks great. I assume Wallabag uses Fivefilters for its article fetching.
So how do I update my own Wallabag install to reflect these changes?  Or should I wait until the next Wallabag release, and if so, how will I know when that happens?

**Comment by tcitworld** [comment]
wallabag uses https://github.com/j0k3r/graby-site-config that is based on Fivefilters repo. Once a new release is done in that repository, you can do `composer up` to update those config files.

**Comment by j0k3r** [comment]
Since the fix will be available in the next release of wallabag, I close this issue.
