### ISSUE TITLE
Wallabag drops bullets in bullet point lists

### ISSUE THREAD

**Issue by chepec** [wallabag/wallabag#2162]
### Issue details

This is a minor gripe, but I've noticed it on a number of occasions.
As an example, take [this blog post](http://blog.martinfenner.org/2014/09/07/commonmark-and-the-future-of-scholarly-markdown/), which Wallabag renders perfectly except for the unordered list (aka bullet points). In Wallabag, the bullets are gone, and the unordered list looks like a bunch of regular paragraphs.

Note: the _ordered_ list looks good in Wallabag, but not the _unordered_ list. I can't say this is a general issue for all lists, but it seems to recur.
### Environment
- wallabag version (or git revision) that exhibits the issue: `2.0.5`
- How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
- Last wallabag version that did not exhibit the issue (if applicable):
- php version: `5.6.22`
- OS: Debian Jessie
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL
### Steps to reproduce/test case

Add this page to Wallabag:
http://blog.martinfenner.org/2014/09/07/commonmark-and-the-future-of-scholarly-markdown/

**Comment by nicosomb** [comment]
Thanks to @Kdecherf (in https://github.com/wallabag/wallabag/pull/2622), it's fixed.
