### ISSUE TITLE
Error during login_check

### ISSUE THREAD

**Issue by ritzelbuerste** [wallabag/wallabag#2163]
### Issue details

Hey guys,

after entering my credentials and trying to login, my nginx server returns a http 500 error. The log file says:

> 
2016/06/21 21:29:08 [error] 671#0: *475 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getLanguage() on a non-object in /opt/wallabag/src/Wallabag/CoreBundle/EventListener/UserLocaleListener.php on line 33" while reading response header from upstream, client: XXX.XXX.XXX.XXX, server: wallabag.example.com, request: "POST /login_check HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "wallabag.example.com", referrer: "https://wallabag.example.com/login"

### Environment
* Ubuntu 14.04
* wallabag 2.0.5
* nginx 1.4.6
* installed php packages:

> 
php5
php5-cgi
php5-cli
php5-common
php5-curl
php5-fpm
php5-gd
php5-json
php5-mysql
php5-readline
php5-xsl

Do you have any ideas what's going wrong? :)

**Comment by j0k3r** [comment]
Could you check that issue https://github.com/wallabag/wallabag/issues/1608 which had the same problem and tell us if it fix your problem?
Thanks

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
