### ISSUE TITLE
wallabag can't retrieve contents for this article. Please report this issue to us.…

### ISSUE THREAD

**Issue by littleyoda** [wallabag/wallabag#2164]
### Issue details

wallabag can't retrieve contents for this article. Please report this issue to us.…

Link: https://www.gscalecentral.net/threads/tcs-t1-decoder-in-playmobil-motor-block.52103/
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.0.5
- How did you install wallabag? git clone
- Last wallabag version that did not exhibit the issue (if applicable):
- php version: PHP 5.5.9-1ubuntu4.17 (cli)
- OS: Ubuntu 14.04 TLS
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

**Comment by techexo** [comment]
This is a forum, so it won't most likely not be supported.
