### ISSUE TITLE
Try to use Google AMP pages for fetching and/or redirect to original page

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#2173]
See https://support.google.com/webmasters/answer/6340290?hl=fr

If page meta contains `<link rel="amphtml" href="https://www.example.com/url/to/amp-version.html" />`, maybe try to parse this one instead of original one.
Same goes to opening original url (quite interesting when you're on mobile).

Of course, this should be set as a setting.

**Comment by j0k3r** [comment]
Should this be part of graby instead?

**Comment by tcitworld** [comment]
Indeed.
