### ISSUE TITLE
Edit title

### ISSUE THREAD

**Issue by mkody** [wallabag/wallabag#218]
Avoir la possibilité de changer le titre d'un élément sauvegardé pour lui donner un titre personnalisé (avec, par exemple, une petite icône d'un crayon à droite de celui-ci). 
Utile s'il n'est d'origine pas très précis. 

Voici un soucis, par exemple, avec certaines pages: 
![cinesion-films](https://f.cloud.github.com/assets/843787/1123099/569d3eb2-1ae9-11e3-8d74-bfa63ef90dfb.PNG)

**Comment by icaroperseo** [comment]
:+1:
