### ISSUE TITLE
Secure https connection is non-stop falling back to unsecure on v2.wallabag.org

### ISSUE THREAD

**Issue by bungabunga** [wallabag/wallabag#2182]
### Issue details

I made a Wallabag account on v2.wallabag.org and tried to use it only via secure https connection but the service is non-stop falling back to http. I think this is not a great user experience security wise, could you please fix it. The best way would be to make a manual "https only" setting.
### Environment
- wallabag version that exhibits the issue: 2.0.3
- How did you install wallabag? I did not install it, I use v2.wallabag.org
- OS: Ubuntu 16.04
### Steps to reproduce/test case

 The simplest way to test this is to go to v2.wallabag.org/login, log in and the https connection becomes http. It also falls back from https to http on other ocasions.

**Comment by j0k3r** [comment]
At the moment, wallabag doesn't care about the protocol and it could be bad implemented (for example for redirection).
This is something we could fix in future release with, as you said, an option like "enable https".

**Comment by bungabunga** [comment]
i think that option should be called, not "enable https", but "force https", since there's no real advantage from https if it doesn not completely replace http.

**Comment by j0k3r** [comment]
Did you try on app.wallabag.it?
v2.wallabag.org is just a test platform.

**Comment by bungabunga** [comment]
yes i did and it works there. this issue is very old and i didn't know at that time this is a test platform. should i close it?

**Comment by tcitworld** [comment]
Yup. I'm going to send an email soon to all v2.wallabag.org users (there are not much anyway) to tell them to migrate to wallabag.it or framabag.org.

**Comment by bungabunga** [comment]
closing. thanks.
