### ISSUE TITLE
wallabag fetches too much content on: www.drgoulu.com

### ISSUE THREAD

**Issue by zertrin** [wallabag/wallabag#2184]
### Issue details

Wallabag fetches too much content for this blog:
http://www.drgoulu.com/2012/10/07/comment-stocker-lenergie/

The comments are included which shouldn't be the case.

I've used http://siteconfig.fivefilters.org to find the correct XPath:

### FiveFilter siteconfig

```
# Generated by FiveFilters.org's web-based selection tool
# Place this file inside your site_config/custom/ folder
# Source: http://siteconfig.fivefilters.org/grab.php?url=http%3A%2F%2Fwww.drgoulu.com%2F2012%2F10%2F07%2Fcomment-stocker-lenergie%2F

body: //section[contains(concat(' ',normalize-space(@class),' '),' entry-content ')]
test_url: http://www.drgoulu.com/2012/10/07/comment-stocker-lenergie/
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.5
* How did you install wallabag? `git clone`
* type of hosting: dedicated
* which storage system you choose at install: SQLite

**Comment by tcitworld** [comment]
Thanks a lot :
Please submit the site config file here with a PR : https://github.com/fivefilters/ftr-site-config/

**Comment by zertrin** [comment]
Done here: https://github.com/fivefilters/ftr-site-config/pull/184

Thanks
