### ISSUE TITLE
PDF said to be saved by wallabag when it isn't.

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#2188]
* Try to save https://developer.nvidia.com/sites/default/files/akamai/gamedev/docs/Porting%20Source%20to%20Linux.pdf
* Flashbag notification says Entry saved
* No entry added.

**Comment by j0k3r** [comment]
I didn't got an _Entry saved_ but a failed to save entry because the url is a 404 (and it's a but in graby).

**Comment by tcitworld** [comment]
That's strange since I can download it without issues from other means. Filtering user agent ?

```
http get https://developer.nvidia.com/sites/default/files/akamai/gamedev/docs/Porting%20Source%20to%20Linux.pdf
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 2853809
Content-Type: application/pdf
Date: Sun, 24 Jul 2016 11:47:33 GMT
ETag: "56944aff-2b8bb1"
Last-Modified: Tue, 12 Jan 2016 00:38:23 GMT
Server: nginx
X-Pantheon-Endpoint: 99573c5a-fafa-4f68-b225-1e75a309cfc3
X-Pantheon-Styx-Hostname: styx94699a92
X-Styx-Req-Id: styx-ea1f232707022980d99e0c9ffcec7cc1
X-Styx-Version: StyxGo



+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+
```

**Comment by j0k3r** [comment]
I mean, the download failed in Graby because of a bug :)

**Comment by j0k3r** [comment]
It's now working, you can give a try here (it use graby@dev-master): http://f43.me/feed/test

**Comment by tcitworld** [comment]
:+1:
