### ISSUE TITLE
The iOS application doesn't work with the latest wallabag version

### ISSUE THREAD

**Issue by fycth** [wallabag/wallabag#2191]
### Issue details

When configuring the iOS application, it can't establish connection to the wallabag hosted installation.
In the server logs I see the mobile application is trying to reach out the following URL:

/index.php?feed&type=home&user_id=1&token=gAPnuiT0y8ND1TE

The URL gives Error 404. Since there is no 'index.php' file in the 'web' folder, I assume it tries to use wrong URL (that might has been changed in the latest wallabag releases).

### Environment

* wallabag version (or git revision) that exhibits the issue:
2.0.5

* How did you install wallabag? Via `git clone` or by downloading the package? 
Git clone (following the docs)

* Last wallabag version that did not exhibit the issue (if applicable):
N/A

* php version:
5.5.9-1

* OS:
Ubuntu 14.04.4 LTS

* type of hosting (shared or dedicated):
VPS

* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
MySQL

### Steps to reproduce/test case

Install wallabag 2.0.5 following the documentation. Install the mobile app on iOS. Try to configure the app - it says "The requested URL was not found on this server"

**Comment by tcitworld** [comment]
Sorry, support for wallabag v2 is still a work in progress for the iOS app.

**Comment by fycth** [comment]
Is the iOS app open source? Maybe could contribute.

**Comment by tcitworld** [comment]
You're very welcomed. Check out https://github.com/wallabag/ios-app/pull/32 for the WIP.

**Comment by j0k3r** [comment]
I guess we can close that issue then
