### ISSUE TITLE
httpoxy vulnerability

### ISSUE THREAD

**Issue by kpn3m0** [wallabag/wallabag#2197]
### Issue details

Guzzle < 6.2.1 is vulnerable to httpoxy [1] [2].

### Solution

Adjust composer to use Guzzle >= 6.2.1

[1] https://httpoxy.org/
[2] https://github.com/guzzle/guzzle/releases/tag/6.2.1

**Comment by j0k3r** [comment]
Thanks for the message.

But we are using Guzzle 5.3.1 which fix it https://github.com/guzzle/guzzle/commit/70f1fa53b71c4647bf2762c09068a95f77e12fb8#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR5
