### ISSUE TITLE
Error 500 when saving a PDF

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#2204]
### Issue details

Recently I tried to save a PDF file in wallabag via the API, all I got was an HTTP error 500. Tried it again over the web interface, same problem.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.3 (v2.wallabag.org) & 2.0.4 (my instance, too lazy to update :wink:)
* How did you install wallabag? Via `git clone` or by downloading the package? package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.5.10
* OS: CentOS
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Save the following link in your wallabag: http://www.iga-info.de/fileadmin/redakteur/Veroeffentlichungen/iga_Reporte/Dokumente/iga-Report_23_Teil2_Auswirkungen_staendiger_Erreichbarkeit.pdf

**Comment by tcitworld** [comment]
It's a rather big file, but it passes http://f43.me/feed/test (so it isn't an issue with Graby dev-master).

**Comment by j0k3r** [comment]
I guess it'll rather be an issue from the web server, I guess that the error raised could be memory related. Did you try with putting more memory to PHP for example?
FYI, I use 256 on f43.me.

**Comment by jlnostr** [comment]
Will try that asap.

**Comment by nicosomb** [comment]
@jlnostr did you try?

**Comment by jlnostr** [comment]
@nicosomb Oh well, forgot it. Tried it right now, PDF was added successfully.

**Comment by j0k3r** [comment]
:+1:
