### ISSUE TITLE
Backslash issue at /var/cache/appProdProjectContainer.php

### ISSUE THREAD

**Issue by Kaishiyoku** [wallabag/wallabag#2205]
### Issue details
/

### Environment

* wallabag version: 2.0.5
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): /
* php version: 5.5.9
* OS: Ubuntu 14.04 64bit
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case
Just follow the instructions at https://www.wallabag.org/pages/download-wallabag.html and run the composer command.

**Comment by tcitworld** [comment]
Can you be a little more specific, please ? Also, did you check file permissions ?

**Comment by Kaishiyoku** [comment]
It has something to do with this bug: https://github.com/symfony/symfony/pull/9184

It has been resolved but when I install wallabag the backslash problem still occurs.

**Comment by Kaishiyoku** [comment]
Sample stacktrace:

`[Wed Jul 27 21:42:22.007793 2016] [:error] [pid xxxx] [client xxx] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Validator\\Exception\\MappingException' with message 'The mapping file "/var/www/html/wallabag\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Form/Resources/config/validation.xml" does not exist' in /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/FileLoader.php:43\nStack trace:\n#0 /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/XmlFilesLoader.php(29): Symfony\\Component\\Validator\\Mapping\\Loader\\FileLoader->__construct('/var/www/html/w...')\n#1 /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/FilesLoader.php(47): Symfony\\Component\\Validator\\Mapping\\Loader\\XmlFilesLoader->getFileLoaderInstance('/var/www/html/w...')\n#2 /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/FilesLoader.php(32): Symfony\\Component\\Validator\\Mapping\\Loader\\FilesLoader->getFileLoaders(Array)\n#3 /var/www/html/wallabag/vendor/symfony/sy in /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/FileLoader.php on line 43`

**Comment by j0k3r** [comment]
Did you try to remove all files/folders from the `var/cache` folders and then run `php bin/console cache:clear -e=prod` ?

**Comment by Kaishiyoku** [comment]
Yes, the backslashes are present there all the time.

**Comment by j0k3r** [comment]
Hum.
Did your composer is up to date? Try running `composer selfupdate` (should be version 1.2).

I'll soon be out of idea :no_mouth:

**Comment by Kaishiyoku** [comment]
Okay, I just followed all steps again but directly on my Ubuntu virtual machine et voilà it worked:
![chrome_2016-08-02_13-31-17](https://cloud.githubusercontent.com/assets/5131112/17327035/962ff896-58b5-11e6-9d8f-150397b9d067.png)

Either the installation scripts fail somehow under Windows or something else was causing the falsy cache generation.

Thanks anyway, this issue can now be closed.

**Comment by tcitworld** [comment]
We indeed never tested on Windows afaik.

**Comment by j0k3r** [comment]
@Kaishiyoku thanks for letting us know !
