### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by Derf911** [wallabag/wallabag#2208]
Hello !

I get this error when I try to access to unread.xml with wallabag 2.0.5 after adding this website, for example : http://roundtrip.fr/decoration-de-mariage-sur-le-theme-du-voyage/ 

This page contains the following errors:
_error on line 930 at column 8: Opening and ending tag mismatch: description line 0 and td
Below is a rendering of the page up to the first error._

Anyone has already had this error ?
Sorry for my poor english

Version : 2.0.5 (installation recommanded)
OS : Raspbian
Database : pdo_pgsql (also try with pdo_mysql)

**Comment by nicosomb** [comment]
Hello @Derf911! 

What is your browser?

**Comment by nicosomb** [comment]
It seems to be fixed in 2.1.3. 

Please reopen if necessary.
