### ISSUE TITLE
Firefox bookmarklet not working 

### ISSUE THREAD

**Issue by leveled** [wallabag/wallabag#2210]
### Issue details

The wallabag addon for Firefox does not seem to be working for me at all, there is no pop-up or anything when I push the hotkey.  The chrome bookmarklet has no problems saving pages. 

### Environment

* wallabag version: latest version 
* How did you install wallabag: this isn't a problem with wallabag, but the firefox extension

### Steps to reproduce/test case

I'm using OS X 10.11.5 and the latest version of Firefox.

**Comment by j0k3r** [comment]
Could you tell us the version of the bookmarklet?

**Comment by leveled** [comment]
It's the v2-0.0.8
