### ISSUE TITLE
CORS: Different "Access-Control-Allow-Origin" header behaviour

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2215]
### Issue details

Wallabag adds 'Access-Control-Allow-Origin' in API section POST response, but in OAuth part it doesn't, so I have to add it myself in nginx server config for OAuth part separately. 

Is it possible to add this header for OAuth part?

### Environment

* wallabag version 2.0.6
* How did you install wallabag? Via `git clone`

**Comment by j0k3r** [comment]
I think we just need to duplicate the api rule [here](https://github.com/wallabag/wallabag/blob/8617972f3f947ba6ceaa872e18487a9172f95189/app/config/config.yml#L152) and change the `'^/api/':` to `'^/oauth/':` so it'll be enabled CORS on the oAuth endpoint `/oauth/v2/token`.

**Comment by Rurik19** [comment]
I did so, but it seems that doesn't work. I restarted php5-fpm and nginx, is that enought for reread config?

**Comment by j0k3r** [comment]
You should remove the cache too (from var/cache/prod)

**Comment by Rurik19** [comment]
Thanks, cleaning cache make thing works.

**Comment by j0k3r** [comment]
You can submit a PR if it fix your problem !

**Comment by nicosomb** [comment]
Fixed by #2216.
