### ISSUE TITLE
iOS App and bag it! doesn't work 

### ISSUE THREAD

**Issue by thwi84** [wallabag/wallabag#2217]
### Issue details
Hi therem

first i have to say that wallabag is such a nice tool and i love it.
But my wallabag 2 will not work with the wallabag iOS App, so i can't share items to wallabag. 
Another Problem is bag it! with help it works (i remove the close paragraph) but now everytime i have to close the new windows after "bag it". With Firefox/Chrome and Safari i tested some extensions to save articles, but it will not work either. :(

Can you help me or will a update come for wallabag 2?
Thanks a lot and sorry for my bad english.
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.6
* How did you install wallabag? Softcloud 
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS: 9.3.4
* type of hosting (shared or dedicated): shared (wint.global)
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by tcitworld** [comment]
For now the iOS app is not compatible with v2 and the bookmarklet issue is at https://github.com/wallabag/wallabag/issues/2210.
