### ISSUE TITLE
Unable to retrieve article because of HTTP 500 from remote article

### ISSUE THREAD

**Issue by raf64flo** [wallabag/wallabag#2219]
### Issue details

Hi, I have a fetching error with this URL:  https://ploum.net/216-le-bepo-sur-le-bout-des-doigts/
Few months ago v1.9.2 correctly fetched the article, but Ploum's website might have change something.
@j0k3r reported on #2211 a problem coming from Ploum with following information: 

> For the record, the problem came from ploum.bet, it returns a http 500 instead of 200:

```
HTTP/1.1 500 Internal Server Error
Server: Apache/2.4.18
Link: <https://ploum.net/wp-json/>; rel="https://api.w.org/", <https://ploum.net/?p=232>; rel=shortlink
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 17 Aug 2016 08:33:44 GMT
Connection: keep-alive
Via: 1.1 varnish
Age: 0
```

 I don't know if something can be done from Wallabag side?

### Environment

* Wallabag v2.0.5
* Yunohost installation via packaging provided by @jeromelebleu at https://github.com/YunoHost-Apps/wallabag2_ynh
* I already fetched this article few months ago using 1.9.2 Wallabag version
* php version: 5.5.7 _de mémoire_
* OS: Yunohost (based on Raspbian)
* Self hosting on a Raspberry Pi 3
* Database used is a MySQL 5.5

### Steps to reproduce/test case

I tried to add the article but got following response from Wallabag: 

> Wallabag can't retrieve contents for this article. Please report this issue to us.…

**Comment by j0k3r** [comment]
I've pinged @ploum about that: https://twitter.com/j0k/status/765830771584143360

**Comment by ploum** [comment]
J'ai déjà investigué sans succès. J'utilise un Wordpress sur un Simple Hosting de Gandi. 

Les vieux articles étaient auparavant sur Dotclear et il y'a donc eu à un moment une migration d'URL. Je suis preneur de toute aide pour résoudre ce problème.

**Comment by raf64flo** [comment]
EN: When did you migrate the website to Wordpress?
FR : À quand remonte la migration à Wordpress ?

**Comment by ploum** [comment]
Entre 2008 et 2010. Bref, c'est pas récent ;-)

**Comment by j0k3r** [comment]
T'as fouillé un peu dans les logs PHP / Apache voir ce qu'il en ressortait ?

**Comment by ploum** [comment]
J'ai fouillé les logs PHP et Apache (du moins ceux auxquels j'ai accès car c'est du Gandi Self Hosting) et je ne vois rien. Y'a juste marqué HTTP 1.1 500 pour ces requêtes là, sans raison.

**Comment by raf64flo** [comment]
C'est censé résoudre la récupération des articles de ploum.net avec la nouvelle version de Wallabag ? 8-)

**Comment by j0k3r** [comment]
C'est censé permettre une meilleure récupération des _nouveaux_ articles, y'a toujours un soucis avec les anciens qui retournent toujours une 500 :disappointed:

**Comment by raf64flo** [comment]
C'est toujours ça de pris ! Merci bien @fivefilters & @j0k3r !

**Comment by j0k3r** [comment]
Bon puisque le problème n'est pas de notre côté, je ferme l'issue.
