### ISSUE TITLE
Copy Paste content into wallabag

### ISSUE THREAD

**Issue by biva** [wallabag/wallabag#2229]
### New feature request

I would love to be able to paste content into wallabag. For example : 
1. Copy a text (word, PDF, web page content)
2. Open a wallabag session in my browser
3. Click on the button "+" (Add a new entry)
4. Paste my content
5. Wallabag recognizes that it's a content, and not a URL
6. Wallabag creates the article with my content

And as additional features:
- The title of the article will be the first sentence of the pasted text, and it could be edited afterwards
- The pasted content can contain formatted text / pictures / table / ... and wallabag is able to grab them correctly
- I can do all of this in my browser extension, without opening the wallabag page

This is related to https://github.com/wallabag/wallabag/issues/1634

**Comment by biva** [comment]
In order to paste text with formatting, is it hard to embed a simple WYSIWYG editor that would generate a temporary html page? And then graby adds this page to wallabag?

**Comment by j0k3r** [comment]
We removed the milestone because we do not have time to work on that feature.
Stuff is done to handle parsing raw html instead of html from a webpage but the rest needs to be done (UI, controller, etc)

**Comment by nicosomb** [comment]
Hi there, 

Thank you for your feature request. We, at wallabag team, really appreciate external contributions and new ideas.
But this feature is not a wanted one by the core team. 

You can for example fork wallabag (Open source spirit ❤️) or write a blog post to explain how implementing this feature. 

I wrote a blog post about that: https://wallabag.org/en/news/wallabag-wont-accept-pr-feature-request

I hope that you can understand our choices. 

Have a nice day, 

Nicolas

**Comment by biva** [comment]
Hello  @nicosomb , thanks for your message, and I fully understand. In fact, your recent feature (_Retrieve content from the browser (an URL by line)_) makes the job for me. Congrats for your great work!!
