### ISSUE TITLE
Some UIs issues using baggy

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#2231]
It looks like we have some issues regarding the baggy theme on the 2.1.
Here is a preview on my local machine:

![image](https://cloud.githubusercontent.com/assets/62333/17871543/51032cd6-68bc-11e6-9a78-ab0af96e565c.png)

- [ ] Titles have padding on the left
- [x] Filter panel is open by default and I can't close it
- [ ] Clear button doesn't work

**Comment by tcitworld** [comment]
> Titles have padding on the left

It was my idea to have them centered. Bad idea.

> Filter panel is open by default and I can't close it

Doesn't seem to happen anymore.

> Clear button doesn't work

On it

**Comment by j0k3r** [comment]
> Doesn't seem to happen anymore.

Still happen for me on Chrome (at least)

Also there is an error about autocomplete:
![image](https://cloud.githubusercontent.com/assets/62333/18905138/07f86aa2-8562-11e6-847e-65109e0f7654.png)
