### ISSUE TITLE
Misinterpretation of URL

### ISSUE THREAD

**Issue by ddeimeke** [wallabag/wallabag#2233]
### Issue details

A reader of my blog told me that he gets the complete frontpage of my blog even though he only wants to add one article to Wallabag.

I was able to reproduce that with my instance.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.7
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): (no idea, sorry)
* php version: 5.6.24
* OS: CentOS 7 (recent patch level)
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Add this URL to your Wallabag instance:

https://www.deimeke.net/dirk/blog/index.php?/archives/3719-Meine-FrOSCon-2016-....html

You will get this:

https://www.deimeke.net/dirk/blog/

(I think Wallabag has problems with the number of dots before html).

**Comment by j0k3r** [comment]
Might be the same problem as (or duplicated) https://github.com/wallabag/wallabag/issues/1632

I don't think the problem came from the dots but from the `/` in the query string (_is there still hosting provider who doesn't allow rewriting url? doh_).

**Comment by ddeimeke** [comment]
It is my dedicated server and I allow everything :-)

Unfortunately I can not tell you if it was working beforehand.

If you want me to test something, I will do that.

**Comment by j0k3r** [comment]
I've checked and it's the same issue as #1632 
I still don't have a proper fix for that but I'll close that issue as duplicate.

**Comment by Strubbl** [comment]
The question mark in the url is causing the confusion in wallabag. In this type of url you can just leave it out to fetch the article content and not the full frontpage. e.g.:

wallabag fetches the content of the whole frontpage of the blog: https://www.deimeke.net/dirk/blog/index.php?/archives/4053-Wie-ich-Ende-2020-arbeite-Client.html

wallabag fetches the article itself: https://www.deimeke.net/dirk/blog/index.php/archives/4053-Wie-ich-Ende-2020-arbeite-Client.html

This cannot be reproduced with the URL of issue #1632

**Comment by ddeimeke** [comment]
Adding to that, it happens with Version 2.4.1 as well.
