### ISSUE TITLE
Instapaper import missing from Wallabag 2?

### ISSUE THREAD

**Issue by khromov** [wallabag/wallabag#2248]
### Issue details

From what I have gathered, Instapaper import is supposed to be available, but I can only import from Pocket or wallabag v1/2. 

### Environment

* 2.0.7
* git clone method
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version: 7.0
* OS: Debian
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

* Install Wallabag 2.0.7
* Go to "Import" tab
* Instapaper import is missing

**Comment by j0k3r** [comment]
This is indeed a good idea !

**Comment by tcitworld** [comment]
Instapaper exports its data in html, so it should be pretty close to browser import. We could use the Instapaper API but it's not sure they will still be live in a few months... :speak_no_evil:

**Comment by nicosomb** [comment]
The problem with the Instapaper API is: 

> HTTPS is required on all endpoints

https://www.instapaper.com/api

I already play with the API, but for wallabag instances without HTTPS, it's impossible to use the import tool.

So we need to use the Instapaper export.

**Comment by khromov** [comment]
Instapaper also has a CSV export function. In terms of parsing, I assume that is much easier than parsing the HTML export they have.

**Comment by j0k3r** [comment]
@nicosomb is it really a problem? We are already fetching information from Pocket using https.
_HTTPS is required on all endpoints_ means we CAN'T call THEIR endpoints using http. So we don't care :)

**Comment by j0k3r** [comment]
Fixed !
https://github.com/wallabag/wallabag/pull/2310
