### ISSUE TITLE
Update js & css assets

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#2249]
There has some changes in css and js files lately. This has to be changed too in 2.1.

**Comment by j0k3r** [comment]
As far as I know, I fixed most of them when fighting against the bad rebase on the 2.1 branch.
But yeah, could be a good idea to check before the release.

**Comment by tcitworld** [comment]
Also, add linters to the build assets travis task (and Grunt watch).

**Comment by j0k3r** [comment]
There is still (from https://github.com/wallabag/wallabag/pull/2314#issuecomment-250390210)

- [ ] Fix for twitter icons becoming facebook one (WTF ?)

**Comment by nicosomb** [comment]
Done 👍 
Good job with the front part, @tcitworld <3

**Comment by j0k3r** [comment]
Fixed here https://github.com/wallabag/wallabag/pull/2353
