### ISSUE TITLE
Tags are empty and not exported in json export

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2256]
### Issue details

I am exporting all my articles as json, but not article has its tags included in the json file

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.7
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version:
* OS: debian jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

### Steps to reproduce/test case

1. Go to export
2. export as json 
3. save that file
4. open it in editor and search for "tags"
5. find every tags value field being empty like:
`"tags":[{}]}` or with multiple tags in the original article: `"tags":[{},{}]}` or `"tags":[{},{},{}]}` etc.

**Comment by patschwork** [comment]
Problem still exists!
