### ISSUE TITLE
Unable to retrieve contents for article: thepointmag.com

### ISSUE THREAD

**Issue by chepec** [wallabag/wallabag#2264]
### Issue details

Got the " wallabag can't retrieve contents for this article. Please report this issue to us.".  
https://thepointmag.com/2016/examined-life/can-liberal-education-save-the-sciences

Wallabag does fetch the nice article header art and title, though.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.7
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.24
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Import into Wallabag using Firefox button.

**Comment by j0k3r** [comment]
Will be available in the next release 🚀
