### ISSUE TITLE
Retrieves article without error, but empty

### ISSUE THREAD

**Issue by KuenzelIT** [wallabag/wallabag#2269]
### Issue details

Used wallabag for this site:
http://www.outsideonline.com/2108066/emerald-citys-velo-thieves-have-problem-bike-batman

It shows no errors, but the saved article is empty with a reading time below a minute.

### Environment

* wallabag version 2.0.7
* Install: git clone
* php version: PHP 5.6.24-0+deb8u1 
* OS: Raspbian GNU/Linux 8 (jessie)
* type of hosting (shared or dedicated): Raspberry PI
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Adding the above url.

**Comment by j0k3r** [comment]
Thanks for the report!
It allow us to handle a new case for image lazyloaded.

It'll be available in the next release.
