### ISSUE TITLE
Import from Framabag (v1) fails

### ISSUE THREAD

**Issue by 1xPdd** [wallabag/wallabag#2276]
### Issue details

Trying to import a ver 1 json from Framabag. It fails after a few minutes with the error, "Secure Connection Failed: The connection to the server was reset while the page was loading." The json file is around 40 MB, so I'm guessing the connection is timing out.
### Environment
- wallabag version: 2.0.7
- installed on Yunohost via https://github.com/YunoHost-Apps/wallabag2_ynh
- Last wallabag version that did not exhibit the issue (if applicable): N/A
- php version: 5.6.24
- OS:  Debian Jessie
- type of hosting (shared or dedicated): dedicated vps 
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
### Steps to reproduce/test case

Go to Import, then import wallabag v1 contents, select local json file, & upload.

**Comment by tcitworld** [comment]
Can you have console access on your YunoHost instance ? This might be a workaround : http://doc.wallabag.org/en/master/user/migration.html#import-via-command-line-interface-cli

**Comment by 1xPdd** [comment]
Initially, I got an error message, saying that permissions were denied. I ran the same command with sudo, which seems to have worked:

> Start : 08-09-2016 17:35:55 ---
> 1925 imported
> 5 already saved
> End : 08-09-2016 17:38:01 ---

However, I don't see any of the saved articles in the web interface. Also, data/db/wallabag.sqlite is only 45K. I restarted nginx, uwsgi, and php5-fpm. I must be missing something obvious, sorry.

**Comment by foxmask** [comment]
I think, You need to run sudo -u user where user is the nginx user. I myself meet problem because i install wallabag in /home/foxmask but the nginx process is running with ,www-data 
Hope this could help

**Comment by j0k3r** [comment]
What database did you enable during the installation?

**Comment by 1xPdd** [comment]
Trying @foxmask's recommendation, while in /var/www/wallabag2/, I ran sudo -u www-data bin/console wallabag:import-v1 1 /home/1xPdd/Downloads/framabag.json --env=prod but get: 
> 0 imported
> 1930 already saved

@j0k3r, It's using Msql.  I've also just upgraded to 2.0.8. Other than this issue, Wallabag2 seems to run great: I've added, annotated, and marked as read a handful of articles with no problem.

**Comment by j0k3r** [comment]
Could you share your `app/config/parameters.yml`? It looks really strange if the command says _1930 already saved_ it means it has 1930 articles in the database. So you should see them in the interface.

**Comment by 1xPdd** [comment]
Sure. Here's my `app/config/parameters.yml`:

```
parameters:
database_driver: pdo_mysql
database_host: 127.0.0.1
database_port: 3306
database_name: wallabag2
database_user: wallabag2
database_password: [REDACTED]
database_path: null
database_table_prefix: null

mailer_transport:  smtp
mailer_host:       127.0.0.1
mailer_user:       null
mailer_password:   null

locale:            en

# A secret key that's used to generate certain security-related tokens
secret:            [REDACTED]

# two factor stuff
twofactor_auth: true
twofactor_sender: no-reply@wallabag.org

# fosuser stuff
fosuser_confirmation: true

from_email: no-reply@wallabag.org
```

**Comment by j0k3r** [comment]
Well ok, still strange.
Just to be sure, the indentation of the file isn't like you paste it? I mean, `parameters:` it good but all other lines should have 4 spaces before them.

Also, could you clear your cache? `php bin/console cache:clear -e=prod`
And try again to load the unread page to see if you got your articles?

**Comment by 1xPdd** [comment]
( yes, the actual file has the indentations but github formatted it weird so I took them out..)

```
 // Clearing the cache for the prod environment with debug false
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared. 
```

None of the imported files appear. Restarted nginx mysql, uwsgi, and php5-fpm. Things appear unchanged.

**Comment by nicosomb** [comment]
@1xPdd did you have a look into the `wallabag_entry` table?

**Comment by tcitworld** [comment]
Are you sure your user has id 1 ?

**Comment by 1xPdd** [comment]
@tcitworld, Yes, it was/is certainly user id 1 on framabag.

@nicosomb, is that within the Mysql database? How can I check it?

**Comment by tcitworld** [comment]
> Yes, it was/is certainly user id 1 on framabag.

I meant on your YUnoHost instance.

**Comment by 1xPdd** [comment]
@tcitworld, Oh, sorry. I believe it is, though I don't see anything in the web config that confirms this. Would ver 2 perchance use a ver 1 database if that had not been removed from previous install? I previously had Wallabag ver 1 installed in Yunohost but had uninstalled it before installing ver 2. Perhaps the uninstall did not fully remove ver 1. Not sure if that makes sense.

**Comment by Gofannon** [comment]
@tcitworld, on Yunohost, **my user id was 2**. I have been able to import the backup from Wallabag v1 using `sudo -u www-data /var/www/wallabag2/bin/console wallabag:import-v1 2 XXX.json --env=prod`

You can check your user id on your instance by typing :

1. `# cat /etc/yunohost/mysql # This is your mysql password`
2. `# mysql -u root -p`
Enter the previous password. You should have a mysql shell now
3. ```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
[...]
| wallabag2          |
+---```

4. ```
mysql> use wallabag2;
Database changed```

5. ```
mysql> show tables;
+-----------------------+
| Tables_in_wallabag2   |
+-----------------------+
| annotation            |
| config                |
| craue_config_setting  |
| entry                 |
| entry_tag             |
| lexik_maintenance     |
| oauth2_access_tokens  |
| oauth2_auth_codes     |
| oauth2_clients        |
| oauth2_refresh_tokens |
| tag                   |
| tagging_rule          |
| user                  |
+-----------------------+
13 rows in set (0.00 sec)
-----------------+```
6. ```
mysql> select * from user;
+----+----------+--------------------+------------------------
| id | username | username_canonical | email                  
+----+----------+--------------------+------------------------
|  1 | wallabag | wallabag           |                        
|  2 | user1   | user1             | user1@XXX  | user1@XXX  |
|  3 | user2   | user2             | user2@XXX | user2@XXX |  
+----+----------+--------------------+------------------------
3 rows in set (0.01 sec)```

Here, you will find your user name and its id. Maybe, there is an easier way to do it :)


I found this ticket because I am unable to upload my backup on Yunohost using the web import function. The file is too big for the webserver so I tried to improve the upload size but it didn't fix it. ( [bug declared on yunohost bugtracker](https://dev.yunohost.org/issues/472)

I got this error now:

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 
```

@tcitworld, should I open a new ticket once I will have debug more on the Yunohost side ? Or can I "borrow" this place ?

**Comment by j0k3r** [comment]
It looks more a bug from Yunohost than wallabag as you said _I tried to import it into the demo website of Wallabag and it worked_. So you don't need to open an issue here.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
