### ISSUE TITLE
Prefill android app with user & server informations through a link

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#2277]
Inspiration from https://github.com/nextcloud/android/issues/248 : Prefill the Android app with user and server informations.

See https://github.com/wallabag/android-app/issues/290 too

**Comment by AndyScherzinger** [comment]
work in progress https://github.com/nextcloud/android/pull/253

**Comment by tcitworld** [comment]
Thanks for the update !

**Comment by AndyScherzinger** [comment]
You are welcome @tcitworld! The URL implementation is kind of ready to go only some Nc/oC server call logik is missing so if anyone here wants to implement the URL "magic" everything is already in the PR I referenced :tada:

**Comment by nicosomb** [comment]
Do we need to implement something in the web application?

**Comment by tcitworld** [comment]
> Do we need to implement something in the web application?

A link with something like wallabag://user@server.tld

**Comment by AndyScherzinger** [comment]
Where and what should happen in the Android app? (which screen basically :smiley: )

**Comment by AndyScherzinger** [comment]
Done for client https://github.com/wallabag/android-app/pull/300 using wallabag://user@server.tld e.g. wallabag://niclas@wallabag.org

**Comment by nicosomb** [comment]
Done in #2523.
