### ISSUE TITLE
wallabag can't retrieve contents for https://getsharex.com/features/

### ISSUE THREAD

**Issue by huggenknubbel** [wallabag/wallabag#2280]
### Issue details

If I add the URL https://getsharex.com/features to wallabag I got this:

"wallabag can't retrieve contents for this article. Please report this issue to us.".
### Environment
- wallabag version (or git revision) that exhibits the issue:  Versio 2.0.8
- How did you install wallabag? Via `git clone` or by downloading the package? Git Clone
- Last wallabag version that did not exhibit the issue (if applicable): Don't know
- php version: 5.6
- OS: Debian 8
- type of hosting (shared or dedicated): VPS
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL
### Steps to reproduce/test case

Add https://getsharex.com/features to wallabag.

**Comment by techexo** [comment]
There is a 404 error for the given link, and the others pages (doc mostly) are fetched without any problem with 2.2.3.
This issue can be closed IMHO.

**Comment by Kdecherf** [comment]
@techexo thanks for your feedback, I'm closing this issue.
