### ISSUE TITLE
Modal window doesn't allow user/pass to be populated

### ISSUE THREAD

**Issue by jinnko** [wallabag/wallabag#2282]
### Issue details

In Firefox using the toolbar addon button a modal window pops up to add the current page to wallabag.  However if I'm not logged into wallabag the login form appears in the modal window, but it's not possible for Firefox to auto fill the credentials.  Right click is also blocked in the modal window, so it's not possible to access the credentials via the contextual menu either.
### Environment
- wallabag version 2.0.8, 1.9.2, 1.9.1
- How did you install wallabag? Via `git clone`
- Last wallabag version that did not exhibit the issue (if applicable):
- php version: 5.6.24-0+deb8u1
- OS: Debian 8
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql
### Steps to reproduce/test case

Using the official wallabag 2.0.0 firefox addon.
When logged out of wallabag and using the wallabag addon button in the toolbar the modal window pops up but it's not possible to auto fill any credentials.  Additionally the contextual menu is not available on mouse right-click.

What I'd expect is that the modal window doesn't have any restrictions and it's possible for the browser to auto fill the form fields.

**Comment by j0k3r** [comment]
This might be moved to https://github.com/wallabag/firefox-ext-v1 or https://github.com/wallabag/firefox-ext-v2

**Comment by tcitworld** [comment]
@jinnko Please re-open at https://github.com/wallabag/firefox-ext-v2/issues
