### ISSUE TITLE
No activation mail sent

### ISSUE THREAD

**Issue by Draky50110** [wallabag/wallabag#2283]
Hello

Just succeed installing Wallabag on a shared hosting.

Trying to register, but I never receive the activation mail.

You can try : www.draky.net/w2

Did I miss something after FTP upload + some htacess in web/bundles ?

**Comment by tcitworld** [comment]
Hi,

Are you your hoster allows the mail() function ?

**Comment by Draky50110** [comment]
Yes.
Normal webhost ;)

**Comment by j0k3r** [comment]
What logs says (`var/log/*`)?

**Comment by Draky50110** [comment]
Shared hosting so no access to /var/log

**Comment by nicosomb** [comment]
You have this folder in your wallabag installation ;-)

**Comment by j0k3r** [comment]
I didn't say `/var/log` but `var/logs` (inside the wallabag folder).

**Comment by Draky50110** [comment]
Ok :)

Pasting log : http://gilles.wittezaele.fr/paste/?020a69d6ba5cb90e#ZSvRWFSPXVl2CGnvrBCzhUrtskJEPFC3oVk76IcFGFc=

Each different time is a different attempt to register.

**Comment by j0k3r** [comment]
The error is quite obvious. It looks like you can't send email using the default host:

```
Connection could not be established with host 127.0.0.1
```

My guess is that 

- you didn't have installed something to send an email
- or your mail host is wrong

Please check on your hosting about these information.

**Comment by Draky50110** [comment]
Is it a config option you can set in a config file ?

**Comment by j0k3r** [comment]
Yep
https://github.com/wallabag/wallabag/blob/master/app/config/parameters.yml.dist#L22-L25

**Comment by Draky50110** [comment]
Ok, thanks.

Which parameters can be used to use mail() function ?
Is there a wiki page about this yml file ?

**Comment by j0k3r** [comment]
Usually default value are ok for mail().
But maybe your hosting provider as a username/password, or doesn't use 127.0.0.1 for sending email, or use a different port, etc.

Documentation are available:
- http://symfony.com/doc/current/email.html
- http://symfony.com/doc/current/reference/configuration/swiftmailer.html

**Comment by Draky50110** [comment]
Ok.
Too much complicated to install W2 on shared hosting.
Not even a installer.

Will stay with a good coding app instead of a geek sandbox.

Thanks for the help.
