### ISSUE TITLE
Export and Import Tagging rules

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2284]
### Issue details

I would love to see a feature, where i can export my tagging rules since i have more than 10 now. It should act as backup, so when i move to a different host i can export my articles and my tagging rules from the old host and can import both exported files on the new host and be up and running again.
(bonus would be if it is in one file (articles+tagging rules)

**Comment by Strubbl** [comment]
It would be nice to have API calls for this feature

**Comment by j0k3r** [comment]
@Strubbl could explain what can be the plus value to add API for that? As we don't have API to export entries for example.

**Comment by tcitworld** [comment]
There's an API to export all entries as JSON.

**Comment by j0k3r** [comment]
But for one entry only, not a bunch of entries.

**Comment by Strubbl** [comment]
Having an API for that would make the backup process for my tagging rules easier. 

In difference to the original post, i think the backup for the tagging rules can be separated by the backup from entries.

The articles+tagging rules in one backup file would be nice for moving your account around. But that is not a use case i do often. It was, when wallabag updates where not that smooth and i re-setup my instance sometimes. And also for moving valid user data to a developer instance.
