### ISSUE TITLE
When an article is marked as read the description in the menu is wrong

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2286]
### Issue details

If I mark an article as read, then I want to mark it as unread there is a bug with the menu. See the picture below:

![screenshot_20160913_143428](https://cloud.githubusercontent.com/assets/4572452/18473872/78ce470a-79bf-11e6-9c60-91d775026d15.png)

First, in French, we have "Marquer comme non" which is not great, and the description is wrong.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.8
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

0. Put the language to French
1. Add an article
2. Open it
3. Mark it as read
4. Put your mouse on the menu on the left

**Comment by nicosomb** [comment]
Fixed in #2292.
