### ISSUE TITLE
Confirmation screen needs margin

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2288]
### Issue details

![](https://d17oy1vhnax1f7.cloudfront.net/items/2M1v0w1L1K3O2A0x2K2K/Capture%20d%E2%80%99e%CC%81cran%202016-09-14%20a%CC%80%2016.52.34.png?v=d1bf05db)

### Environment

* wallabag version (or git revision) that exhibits the issue: v2-asynchronous-jobs
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): I don't know
* type of hosting (shared or dedicated): dedicated

### Steps to reproduce/test case

Create a new account on v2.wallabag.org.

**Comment by nicosomb** [comment]
It was a problem with and old version of wallabag. I just tried locally and on v2.wallabag.org and it looks good. 

![](https://d17oy1vhnax1f7.cloudfront.net/items/0a1K3q342f253I3A381Y/Capture%20d%E2%80%99e%CC%81cran%202016-10-07%20a%CC%80%2014.44.12.png?v=3879feb0)

**Comment by j0k3r** [comment]
I fixed it here: https://github.com/wallabag/wallabag/commit/fb7354c4a430f4f4916a1247aa1b1bf564ead0da
The template name wasn't good. So it used the default one from FOSUser without the margin.
