### ISSUE TITLE
wallabag can't retrieve contents for http://phonosti.co

### ISSUE THREAD

**Issue by leolivier** [wallabag/wallabag#2293]
### Issue details
http://phonosti.co/ :
 wallabag can't retrieve contents for this article. Please report this issue to us. 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.8
* How did you install wallabag? Via `git clone` or by downloading the package? clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.24
* OS: Raspbian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case
Just add phonosti.co to your wallabag

**Comment by j0k3r** [comment]
Should wallabag be able to retrieve content for that kind of url: http://phonosti.co/portfolio-posts/va-dezordr-session-009/ ?

**Comment by nicosomb** [comment]
No, sorry.
