### ISSUE TITLE
2.0.8 hangs when loading articles page

### ISSUE THREAD

**Issue by jwm** [wallabag/wallabag#2302]
### Issue details

I'd been running Wallabag 2.0.6 for a few weeks, and recently upgraded to 2.0.8. When I log in and am redirected to the articles page, the browser (both Firefox and Safari on OS X, I think I tried Chrome, too) consume 100% CPU and the page doesn't load even after several minutes.

### Environment

* wallabag 2.0.8 is affected. Both 2.0.6 and 2.0.7 are fine.
* Installed via `git clone`
* PHP 5.6.24 (Debian packaging)
* Debian jessie
* Dedicated hosting
* SQLite

### Steps to reproduce/test case

I followed the documented upgrade procedure. Downgrading to 2.0.6 or 2.0.7 fixes the behavior.

I spent some time bisecting and found that removing [this `display: block`](https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Resources/public/themes/material/css/main.css#L294) from the CSS that was added in 2.0.8 lets the article page load without a problem.

**Comment by jwm** [comment]
Not sure if this is (or is related to) #2281.

**Comment by tcitworld** [comment]
Thanks for your report and trying to narrow the issue. I think it's indeed related to #2281.
