### ISSUE TITLE
Tags created multiple times on repeated imports

### ISSUE THREAD

**Issue by leolivier** [wallabag/wallabag#2303]
### Issue details

Same tag created several times I assume because the import for Pocket failed several times.
![capture du 2016-09-23 23-12-32](https://cloud.githubusercontent.com/assets/4014752/18801507/4fafba12-81e3-11e6-8c07-046d0f77d118.png)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.8
* How did you install wallabag? Via `git clone` or by downloading the package? clone
* Last wallabag version that did not exhibit the issue (if applicable): ?
* php version: 5.6.24
* OS: raspbian jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case

Import from a Pocket account a lot of articles (creates a timeout) then do it again and again => the tags are re created.

**Comment by j0k3r** [comment]
Yeah this is known issue https://github.com/wallabag/wallabag/issues/1981
