### ISSUE TITLE
"next" links in /api/entries responses lack search parameters

### ISSUE THREAD

**Issue by deanishe** [wallabag/wallabag#2305]
Wallabag 2.0.7

Search parameters aren't propagated to the URLs in `_links` in the JSON response. So given the URL
`/api/entries.json?perPage=30&page=1&archive=0`, the `_links.next.href` is `/api/entries.json?perPage=30&page=2` (i.e. the `archive` parameter has disappeared).

As a result, the URL doesn't point to the next page of results, but of my entire collection, and retrieving the `next` URLs will return all entries, not the search results.

**Comment by j0k3r** [comment]
Good catch, thanks 👍
