### ISSUE TITLE
On big screens, we can display more than 3 entries

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2307]
![](https://d17oy1vhnax1f7.cloudfront.net/items/1d0L0N123L3S1r3L0u1v/Capture%20d%E2%80%99e%CC%81cran%202016-09-25%20a%CC%80%2009.33.45.png?v=8e1f4a28)

When we use a big screen, I think we can reduce the size of each card and display more articles.

**Comment by tcitworld** [comment]
Fixed by #2460, coming in 2.1.3.
