### ISSUE TITLE
Add ability to edit imported contents

### ISSUE THREAD

**Issue by amereservant** [wallabag/wallabag#2321]
### Issue details

This is a feature request.  I'm not sure why this doesn't already exist, but I would like the ability to edit the contents of an imported article.  Sometimes it doesn't import the contents correctly, or an image URL isn't correct, or I'd like to add content to it, etc. and that currently isn't possible.

It would be nice to add an edit button, like the one for the title, so the contents can be edited.  A WYSIWYG editor isn't even necessary.  Editing the raw code would work fine.

Thank you!

**Comment by rabyte** [comment]
I like this idea very much. This happens to me a lot, too. E.g. it would be great beeing able to remove messed up content or unnecessary footers. 

I also was wondering if it is not possible already since editing the title works.
If not I guess it should be straight forward to take over the "title editing function" for the content?

Regards

**Comment by slavniyteo** [comment]
This feature doesn't seem to have a high priority so I'll write here a simple workaround to edit article's content.

There is a form to modify a title of article and it's original url. You can get there by clicking a *pencil* icon next to article's title. We'll modify this form. 

![image](https://user-images.githubusercontent.com/18638390/64022057-07c0d680-cb3e-11e9-89d3-0e649b2b8582.png)

---

Add two pieces of code: to [EditEntryType.php](https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Form/Type/EditEntryType.php)

At the top: 
```php
use Symphony\Component\Form\Extension\Core\Type\TextareaType;
```

At the **buildForm** function, for example between 'title' and 'url' fields:
```php
->add('content', TextareaType::class, [
    'required' => true,
    'label' => 'Content',
    'attr' => [ 'style' => 'height: 20em; padding: 10px' ]
]
```

After you save the file you can refresh the page and get additional field with content of the article.

![image](https://user-images.githubusercontent.com/18638390/64021980-cfb99380-cb3d-11e9-87ab-c2be0a8767d1.png)

Now we can modify the content of article in plain html format. I use it to fix some parsing issues. It is very useful.

**Comment by lizyn** [comment]
> Add two pieces of code: to [EditEntryType.php](https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Form/Type/EditEntryType.php)
> 
> At the top:
> 
> ```
> use Symphony\Component\Form\Extension\Core\Type\TextareaType;
> ```

@slavniyteo , Is there a typo? I think it should be `use Symfony\…\…` instead.

**Comment by slavniyteo** [comment]
Yes, it should be Symfony. Sorry for broken code.

вт, 25 февр. 2020 г., 17:53 lizyn <notifications@github.com>:

**Comment by 3bbing** [comment]
Excellent addition! implemented it too. Thanks! I hope this gets added to the repo. 
It also helps for (pdf) content that did not pull correctly or not at all - can just insert some textblocks that were remarkable from e. g. (journal) article behind a paywall that needs a library VPN or similar.

@slavniyteo did you submit it?

To make it fit seamlessly, also change the View. For Material that is
`CoreBundle/Resources/views/themes/material/Entry/edit.html.twig`

Insert the new _content edit_ element after the last element before the save button. At least that's where I wanted it:

```
<div class="input-field s12">
         {{ form_label(form.origin_url) }}
          {{ form_widget(form.origin_url) }}
 </div>

<div class="input-field s12">
       {{ form_label(form.content) }}
       {{ form_widget(form.content) }}
 </div>
<br>

{{ form_widget(form.save, {'attr': {'class': 'btn waves-effect waves-light'}}) }}`

**Comment by thomassaffer** [comment]
@3bbing: I tried to follow your instructions, but manipulations on html.edit.twig are not adapted. I only see it as slavniyteo proposed it, with edit field below save button…

**Comment by nicosomb** [comment]
See https://github.com/wallabag/wallabag/pull/5544#issuecomment-1080578974
