### ISSUE TITLE
install.sh is missing

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2344]
### Issue details

When I try to update to 2.1.0, I have:

```
➜  poche git:(345a373) ✗ ASSETS=build ./install.sh                       
zsh: aucun fichier ou dossier de ce type: ./install.sh
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.0
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Just try to update following the doc (http://doc.wallabag.org/en/master/user/upgrade-2.0.x-2.1.y.html)

**Comment by j0k3r** [comment]
Could you share the output of `ls -la` from your `poche` folder?

**Comment by NerosTie** [comment]
Sorry, it was a mistake. But I had to type: `git checkout 2.1.0 --force` to make it works.

**Comment by j0k3r** [comment]
Maybe you have unchanged stuff in your repo.
Glad you fixed it.

**Comment by NerosTie** [comment]
Yes unchanged stuff in the repo. But I had not changed anything.
