### ISSUE TITLE
Issue with grunt during the upgrade to 2.1.0

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2346]
### Issue details

```
➜  poche git:(091e4bd) sudo node_modules/grunt/bin/grunt
Running "clean:css" (clean) task
>> 0 paths cleaned.

Running "clean:js" (clean) task
>> 0 paths cleaned.

Running "clean:all" (clean) task
>> 1 path cleaned.

Running "copy:pickerjs" (copy) task
Warning: Unable to create directory "/home/www/http/poche/web/bundles/wallabagcore" (Error code: EEXIST). Use --force to continue.

Aborted due to warnings.
```

If I use `--force`, it's worse.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.0
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Just use the command (in install.sh): 
`node_modules/grunt/bin/grunt`

**Comment by greizgh** [comment]
Removing the mentioned directory let grunt finish the build

**Comment by NerosTie** [comment]
@greizgh It works! Thanks! But I think it needs to be fixed somewhere.
