### ISSUE TITLE
Issue with doctrine migraion on 2.0.8 -> 2.1.0 upgrage

### ISSUE THREAD

**Issue by greizgh** [wallabag/wallabag#2347]
### Issue details

After installing somewhat manually composer and node dependencies, the command:

    php bin/console doctrine:migrations:migrate --env=prod

fails with:

    PHP Fatal error:  Class 'Wallabag\CoreBundle\EventListener\RegistrationConfirmedListener' not found in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php on line 151

### Environment

* wallabag version (or git revision) that exhibits the issue: 091e4bdd64e83a2dda2584cec58b43fdad8ef99d
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): 2.0.8
* php version: 5.6.24
* OS: Debian
* type of hosting: dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

* ASSETS=build ./install.sh
* php bin/console doctrine:migrations:migrate --env=prod

**Comment by tcitworld** [comment]
Please remove the cache of wallabag manually : `rm -rf var/cache/*`

**Comment by greizgh** [comment]
Thank you, closing as this is just me not being able to read the doc :roll_eyes:
