### ISSUE TITLE
Multi-user with LDAP backend or at least REMOTE header

### ISSUE THREAD

**Issue by lunarok** [wallabag/wallabag#235]
Hi,

I want to know if your support for multi-users is coming with LDAP backend in future ? Or at least a possible remote user in header (so a SSO can let access to poche)

This is to get poche integrated in my yunohost (and why not after in wiki and with moulinette of yunohost V2)

Thanks,

Cédric

**Comment by sachaz** [comment]
> yourpoche/api ;-) it's what I made last week. have a look here: https://github.com/inthepoche/poche/tree/api/public it's an alpha of an alpha !

Zed's dead baby as your link
