### ISSUE TITLE
Blank page new installation 2.0.8 with MySQL v5.5.52, PHP 5.5.9-1ubuntu4.19 and Apache v2.4

### ISSUE THREAD

**Issue by Vertux** [wallabag/wallabag#2352]
I had a perfectly running installation of Wallabag (Ubuntu v14.04 LTS). Nevertheless I had to do a completely new installation for some reason.
Now I always get a blank page when I open the login page. In the error log (wallabag_error.log) I have found the following errors:

`[Mon Oct 03 21:16:57.471882 2016] [:error] [pid 27308] [client xxxxxxxx:62625] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/vhosts/wallabag/var/logs/prod.log" could not be opened: failed to open stream: Permission denied' in /var/www/vhosts/wallabag/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/vhosts/wallabag/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/vhosts/wallabag/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php(58): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/vhosts/wallabag/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(98): Monolog\\Handler\\AbstractHandler->handleBatch(Array)\n#3 /var/www/vhosts/wallabag/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(119): Monolog\\Handler\\FingersCrossedHandler->activa in /var/www/vhosts/wallabag/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107`

btw. I cannot install v2.1.0 because of dependencies requirements PHP v5.6 is needed - in contrast the wiki says PHP >=5.5

P.S.: I was not able to post on [http://support.wallabag.org](url), because it is impossible to select a category.

**Comment by nerzhul** [comment]
Just read the doc and set www-data:www-data owner on var directory

**Comment by Vertux** [comment]
@nerzhul It is not that easy, the permissions are set correctly
