### ISSUE TITLE
 2.1.0 PHP Fatal error

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2355]
### Issue details

Fist, there was an XmlDriver.php error just like #1828. After patching that , there is another

`PHP message: PHP Fatal error:  Uncaught exception 'Doctrine\Common\Persistence\Mapping\MappingException' with message 'Invalid mapping file 'FOS.OAuthServerBundle.Entity.Client.orm.xml' for cl
ass 'FOS\OAuthServerBundle\Entity\Client'.' in /var/www/wallabag2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86                                        
Stack trace:                                                                                                                                                                                    
#0 /var/www/wallabag2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\Common\Persistence\Mapping\MappingException::invalidMappingFile('FOS\\
OAuthServer...', 'FOS.OAuthServer...')                                                                                                                                                          
#1 /var/www/wallabag2/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\Common\Persistence\Mapping\Driver\FileDriver->getElement('FOS\\OAuthServer...')           
#2 /var/www/wallabag2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMetadataForClass('FO        `

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.0
* How did you install wallabag? Via `git clone`

**Comment by j0k3r** [comment]
What the hell is that problem :flushed: 
Could you share your whole setup?
Also, can you remove the cache `rm -rf var/cache/*` and give an other try?

**Comment by Rurik19** [comment]
**Sorry** 

That my fault, I fixed XmdDriver.php wrong way  :-(

Just for info:  error like #1828 appears after each release.

**Comment by j0k3r** [comment]
Yeah sorry about that issue, we really don't know how to fix it.
