### ISSUE TITLE
shared hosting Update -> 2.1.0 no graphics 

### ISSUE THREAD

**Issue by benbeton** [wallabag/wallabag#2356]
### Issue details

after updating from v 2.0.8 -> 2.1.0 no images are displayed.  Only Text and checkboxes are available.
Seems like there are mssing all the graphics

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.0
* How did you install wallabag? downloaded
* type of hosting (shared or dedicated): shared
* which storage system you choose at install: SQLite

### Steps to reproduce/test case

update the shared hosting version from 2.0.8 -> 2.1.0 as described in the docs

**Comment by Zayon** [comment]
I have the same problem on a dedicated server

These files are missing :

bundles/wallabagcore/themes/material/css/style.min.css
bundles/wallabagcore/themes/material/js/material.min.js 
bundles/wallabagcore/themes/_global/img/logo-square.png 

I had several problem during the update but I fixed them and everything works fine except the web client, so I'm not sure this is related.

### Environment

- wallabag version (or git revision) that exhibits the issue: 2.1.0
- How did you install wallabag? git
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install: Mysql

**Comment by tcitworld** [comment]
Please wait for 2.1.1 (it should come out today).

**Comment by benbeton** [comment]
@tcitworld thank you, I'll wait...
