### ISSUE TITLE
Cannot fetch LowTechMagazine articles

### ISSUE THREAD

**Issue by TheOneValen** [wallabag/wallabag#2358]
### Issue details
Cannot fetch http://www.lowtechmagazine.com/2015/12/reinventing-the-greenhouse.html . Wallabag says I should report it.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.8
* Git Clone
* Last wallabag version that did not exhibit the issue (if applicable): not applicable
* php version: 5.6.25
* OS: Funtoo
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Try to fetch http://www.lowtechmagazine.com/2015/12/reinventing-the-greenhouse.html

**Comment by TheOneValen** [comment]
Version was actually 2.0.8. Sorry for the confusion.

**Comment by TheOneValen** [comment]
Will try again with 2.1.1 when update succeeds.

**Comment by j0k3r** [comment]
I tried with 2.1.0 and it doesn't work either.

**Comment by TheOneValen** [comment]
2.1.1 neither. Is there any way I can help, I have a bunch of sites that won't work or are incomplete.

**Comment by j0k3r** [comment]
You can try to see if it works here: http://f43.me/feed/test (it use almost the same way as wallabag to retrieve content).
If it works here and not on wallabag, it means there are something internally in wallabag that break the parser (hard to fix)

If it doesn't works, try to extract a site config using: http://siteconfig.fivefilters.org/ (select wich part of the content is _actually_ the content.

You can test it on the same page I told you.
Click on _Want to try a custom siteconfig?_ and put the generated file from siteconfig.fivefilters.org

Repeat until you have something ok.
Then you can submit a PR to https://github.com/fivefilters/ftr-site-config which is the global repo for siteconfig 😄

**Comment by nicosomb** [comment]
@j0k3r oh, this howto needs to stay in the wallabag documentation 😇

**Comment by TheOneValen** [comment]
Thanks. Can I update this config independent from wallabag releases?

**Comment by j0k3r** [comment]
Not yet.
There is an old issue about that https://github.com/wallabag/wallabag/issues/1284

**Comment by j0k3r** [comment]
Don't forget to put a link here or on the fivefilters repo so we can track the progression :)

See https://github.com/fivefilters/ftr-site-config/pull/208

**Comment by TheOneValen** [comment]
:smile: 

So, for the future: make issue here, make pull request over at ftr-site-config?

**Comment by j0k3r** [comment]
You don't need to open an issue here.
I tell you to link them because you already opened an issue :)
