### ISSUE TITLE
Does not remember scroll position in theme "material"

### ISSUE THREAD

**Issue by MoriTanosuke** [wallabag/wallabag#2360]
### Issue details

Today I was a bit annoyed by Wallabag because everytime I open an article, the scroll position started at the top. I searched for open issues, but only found #1336 and https://github.com/wallabag/android-app/issues/92

Then I tried to switch from theme *material* to *baggy* and the scroll position was remembered correctly. I checked the page sourcecode and saw that baggy included the JS */bundles/wallabagcore/themes/_global/js/restoreScroll.js* and also used a couple of functions like `savePercent` and `retrievePercent`.

The JS include and the function calls are not in the sourcecode when I switch back to theme *material*.

I also checked the current versions of *CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig*, but I can't find any mention of *restoreScroll.js*.

### Environment

* wallabag v2.0.8
* Installed via *git clone*
* dedicated hosting

### Steps to reproduce/test case

* Install 2.0.8
* Switch to theme *material*
* Open an article
* Scroll to the middle
* Go back to *Unread*
* Open the article again

Expected is that the scroll position is restored, but the article always starts at the top.

**Comment by MoriTanosuke** [comment]
Functions `savePercent` and `retrievePercent` are included in https://github.com/wallabag/wallabag/blob/master/app/Resources/static/themes/_global/js/tools.js#L11-L27, which is imported in both https://github.com/wallabag/wallabag/blob/master/app/Resources/static/themes/baggy/js/init.js#L1 and https://github.com/wallabag/wallabag/blob/master/app/Resources/static/themes/material/js/init.js#L1.

Looks ok, but I don't know yet how wallabag does this imports.

**Comment by MoriTanosuke** [comment]
Ah, probably this is fixed with #2353 I'll update my installation.

**Comment by tcitworld** [comment]
Yup, please use latest version (it works with me).

**Comment by MoriTanosuke** [comment]
Verified that this is fixed with 2.1.1. Thanks @tcitworld!
