### ISSUE TITLE
UI issue on mobile (Android)

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2361]
### Issue details

![screenshot_20161004-150703](https://cloud.githubusercontent.com/assets/4572452/19075346/cb575a1c-8a44-11e6-861d-a4ecc9273597.png)
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.1.0
- How did you install wallabag? Via `git clone` or by downloading the package?
- Last wallabag version that did not exhibit the issue (if applicable):
- php version:
- OS: 
- type of hosting (shared or dedicated):
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
### Steps to reproduce/test case

Tested on the Gello browser (webkit) and Firefox on my tablet.

**Comment by j0k3r** [comment]
This issue was moved to wallabag/android-app#313

**Comment by j0k3r** [comment]
I read too fast, sorry :grimacing:

**Comment by tcitworld** [comment]
@NerosTie Btw, may I say I just love using emotes as tags ?!

**Comment by NerosTie** [comment]
@tcitworld Better than hashtags :p And I really like Emojione, truly beatiful.

**Comment by tcitworld** [comment]
Indeed.

The issue should be fixed by https://github.com/wallabag/wallabag/pull/2460

**Comment by tcitworld** [comment]
Fix coming in 2.1.3.
