### ISSUE TITLE
Error with simplexml_load_file()

### ISSUE THREAD

**Issue by juzam51** [wallabag/wallabag#2368]
### Issue details

Impossible to view articles or save settings after upgrade to 2.1.1 version of wallabag :
I've git this error : 
`2016/10/05 09:38:55 [error] 24084#0: *8 FastCGI sent in stderr: "PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Fatal error:  Uncaught exception 'Doctrine\Common\Persistence\Mapping\MappingException' with message 'Invalid mapping file 'FOS.UserBundle.Model.User.orm.xml' for class 'FOS\UserBundle\Model\User'.' in /var/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86
Stack trace:
#0 /var/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\Common\Persistence\Mapping\MappingException::invalidMappingFile('FOS\\UserBundle\\...', 'FOS.UserBundle....')
#1 /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\Common\Persistence\Mapping\Driver\FileDriver->getElement('FOS\\UserBundle\\...')
#2 /var/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMetadataForClass('FOS\\UserBundle\\...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#3 /var/www/vendor/doctrine/orm/l" while reading response header from upstream, client: 127.0.0.1, server: domaine.tld, request: "GET /settings HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "domaine.tld", referrer: "https://domaine.tld/settings"`

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.1
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): 2.0
* php version: PHP 5.6.24-0+deb8u1
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by j0k3r** [comment]
This is known issue from Doctrine, take a look at https://github.com/wallabag/wallabag/issues/1828
