### ISSUE TITLE
Improve packaging for maintainers

### ISSUE THREAD

**Issue by nerzhul** [wallabag/wallabag#2371]
### Issue details

Wallabag is a great product but packaging is very hard due to a repository in PHP dev mode no release mode.

Is this possible to improve the packing, by providing a github release or to make tagged branch divergent with a commit providing vendor directory ?

On FreeBSD with poudriere we don't have insecure access to download dependencies when building app (it's strong sandbox). It could be same problem on debian with pbuilder.

This problem also ask the builder to install php packages to create it instead of doing a simple packaging like all other PHP apps in ports (and there are many many many)

Thanks
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.1.X
- How did you install wallabag? Via `git clone` or by downloading the package? both
- Last wallabag version that did not exhibit the issue (if applicable): none
- php version: 7.0
- OS: FreeBSD
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL 9.6

**Comment by nicosomb** [comment]
I close this issue because we now provide a package.

**Comment by nerzhul** [comment]
@nicosomb sorry but i don't see any package, and docker is not an acceptable solution for BSD hosting

**Comment by nicosomb** [comment]
Package is here https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting
Docker image is here https://hub.docker.com/r/wallabag/wallabag/
Feel free to open a new issue with your specifications about BSD.

**Comment by nerzhul** [comment]
Thanks,To make packaging reproductible we need to have versioned packages, not only latest. Is this possible, i think both linux and BSD packagers are interested

**Comment by nicosomb** [comment]
https://static.wallabag.org/releases/
