### ISSUE TITLE
Add a chown command in the docs

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2373]
### Issue details

Every time, after an update I have to type a chown command, otherwise Wallabag doesn't work.  

I think you need to add a command in your docs here: http://doc.wallabag.org/en/master/user/upgrade-2.0.x-2.1.y.html

Maybe like this (for Debian): `chown -R www-data:www-data *`
### Environment
- wallabag version (or git revision) that exhibits the issue:
- How did you install wallabag? Via `git clone` or by downloading the package?
- Last wallabag version that did not exhibit the issue (if applicable):
- php version:
- OS: Debian
- type of hosting (shared or dedicated):
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
### Steps to reproduce/test case

1/ Update Wallabag following the docs
2/ Try to load the webpage
3/ Type the chown command
4/ Try to load the webpage again

**Comment by TheOneValen** [comment]
The user you need to chown the files to depends on the OS. Funtoo (gentoo) for example uses "apache:apache".

Try doing an update with your www-data user. 

```
sudo -u www-data git fetch
sudo -u www-data git checkout 2.x.y
```

etc. This can save you the chown command at the end.

**Comment by j0k3r** [comment]
Could be a good addition, you can add it yourself.
The doc is in the repo.
https://github.com/wallabag/wallabag/blob/master/docs/en/user/upgrade-2.0.x-2.1.y.rst

**Comment by NerosTie** [comment]
@j0k3r I could but it will be Debian related. Plus, here in the docs (http://doc.wallabag.org/en/master/user/installation.html#rights-access-to-the-folders-of-the-project), there is a chown but just for some folders. On my side I'm doing a chown on the entire folder and maybe it's not the best way to do it.

**Comment by rabyte** [comment]
In particular the
`chown -R www-data:www-data /var/www/wallabag/web`
is not mentioned. In the texted it says that it is needed but the chown line (as for the other folders) is missing.
