### ISSUE TITLE
Unable to add tags in the mobile web version

### ISSUE THREAD

**Issue by szafranek** [wallabag/wallabag#2376]
### Issue details

When viewing an entry in the mobile web version, adding a tag is hidden from the sidebar. Tags seem to be intentionally hidden in CSS on small screens. It makes the mobile app much less useful.
### Environment
- wallabag 2.1.1
- OS: Safari on iOS 10, iPhone 6
- Theme: Material
### Steps to reproduce/test case

Open any entry in a mobile browser. You can also use Chrome and switch to mobile view with Safari as user agent.

**Comment by tcitworld** [comment]
Are you using the material or the baggy theme ?

**Comment by szafranek** [comment]
Material.

**Comment by tcitworld** [comment]
@modos189 What do you think of showing the tags panel here ?

**Comment by pmichelazzo** [comment]
IMHO this feature is necessary and, also, some way to start typing the tag name and the system find a match on the stored tags (like an active search).

Best
