### ISSUE TITLE
Unable to add entries on mobile web version

### ISSUE THREAD

**Issue by celebrion** [wallabag/wallabag#2378]
### Issue details

The + button (add) is invisible when using Wallabag on iOS (10.0.2). This is tested on both Safari and Firefox. The + button should be visible in the top right corner.
### Environment
- wallabag version 2.1.1
- How did you install wallabag? Via Softaculous
- php version: 5.6
- OS: CloudLinux 6
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install : MySQL
- theme: material
### Steps to reproduce/test case

Simply log on to a Wallabag 2.1.1 installation on iOS and look at the upper righthand corner.

**Comment by nicosomb** [comment]
Hello @celebrion! 

I reproduced your problem by changing the language of my wallabag installation. 
When it's in english, I can see the `+`. In italian, the `+` is not visible. 

It depends on the size of the page title.

**Comment by celebrion** [comment]
I cannot see it on the English version of my installation. However, I found it when going from portrait mode to landscape view! So a workaround is available, but the issue should really be fixed anyway.

**Comment by nicosomb** [comment]
Will be fixed with https://github.com/wallabag/wallabag/issues/2647.
