### ISSUE TITLE
defaut langage

### ISSUE THREAD

**Issue by prolibre** [wallabag/wallabag#2379]
### Issue details

En paramétrant locale sur fr ( visible dans parameters.yml ) je pensai que le langage par défaut de l'interface serait le français.
Je constate qu'à la création de nouveau comptes (en tout cas via le formulaire public) la langue par défaut reste l'anglais, ce qui oblige l'utilisateur francophone à modifier le paramètre dans sa configuration. 
Je ne sais pas si c'est un bug ou une requête de ma part :-)

PS : merci pour le boulot... cette version 2.1.1 commence a avoir de la gueule :-) 

### Environment

* wallabag version : 2.1.1
* How did you install wallabag? `git clone`  ( fresh install )
* php version: PHP 5.6.24
* OS: debian stable
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

**Comment by tcitworld** [comment]
Probablement un bug.

**Comment by nicosomb** [comment]
Hello @prolibre! 

Did you clear the cache with `bin/console cache:clear --env=prod`?

**Comment by prolibre** [comment]
yes @nicosomb (désolé je vais faire la causerie en français)

je viens de le refaire et d'inscrire un utilisateur. Dès la création le champ language (dans la table wallabag_config) se positionne sur "en" . 
Pourtant dans mon parameters.yml  j'ai bien : 
` locale: fr`

Aucune erreur dans mes logs.

**Comment by nicosomb** [comment]
I tried locally. I just changed `locale` to `fr` in `app/config/parameters.yml` and cleared the cache. 

Here is the result for the registration page and the homepage after registration (TLDR: all is in french): 

![](https://d17oy1vhnax1f7.cloudfront.net/items/0n3n191C1x2b1J2F3I0q/Capture%20d%E2%80%99e%CC%81cran%202016-10-07%20a%CC%80%2014.59.58.png?v=e45f06d4)

![](https://d17oy1vhnax1f7.cloudfront.net/items/3o1W151A113R1r353J3e/Capture%20d%E2%80%99e%CC%81cran%202016-10-07%20a%CC%80%2015.03.54.png?v=b0d6084c)

The problem may be that you don't have the french locale installed on your webserver. Have a look here: http://askubuntu.com/questions/76013/how-do-i-add-locale-to-ubuntu-server for example.

**Comment by prolibre** [comment]
étrange @nicosomb , voici pourtant ma liste de locales sous debian : 
```
locale -a
C
C.UTF-8
en_US.utf8
franÃ§ais
french
fr_FR
fr_FR@euro
fr_FR.iso88591
fr_FR.iso885915@euro
fr_FR.utf8
fr_FR.utf8@euro
POSIX
```
et si je choisi la langue dans l'interface ça fonctionne sans problème. C'est juste la langue par défaut qui n'est pas prise en compte.

**Comment by j0k3r** [comment]
Pas de soucis chez moi non plus en mettant la langue par défaut dans le `parameters.yml` à `fr`. Le login est bien traduit.

Est-ce que tu vides bien ton cache (`php bin/console c:c -e=prod`) avant de faire tes tests et après chaque changement dans le `parameters.yml`?

**Comment by prolibre** [comment]
@j0k3r @nicosomb bonjour tous les deux, et bon week-end,

Je crois qu'il y a incompréhension aussi je tente de réexpliquer plus clairement.
Aucun soucis de traduction : mon interface est bien en français.

Le problème rencontré : 
- création d'un nouvel utilisateur via le formulaire public d'inscription > OK
- validation du compte > OK
- **le problème c'est que la langue du nouvel utilisateur crée est toujours l'anglais par défaut**. Et donc, quand l'utilisateur se logue il se retrouve en anglais et doit modifier sa langue dans les paramètres.

Ce que j'aurai aimé : que la langue par défaut d'un nouvel utilisateur soit celle du `parameters.yml`
Je dis cela parce que j'aimerais faire découvrir votre application à des _néophytes_ francophones et que j'aurai voulu qu'ils ne soient pas perturbés par la langue de l'interface.

**Comment by j0k3r** [comment]
Compris !

**Comment by nicosomb** [comment]
J'suis surpris pcq chez moi ça semblait être OK.

**Comment by j0k3r** [comment]
Même quand tu crées un nouvel utilisateur? Sa config est forcément `en` :)

**Comment by nicosomb** [comment]
Comme je le dis ici https://github.com/wallabag/wallabag/issues/2379#issuecomment-252247016, le 2ème screenshot, c'est après la création via la page register. Pas testé par contre avec la création côté admin.

**Comment by prolibre** [comment]
@nicosomb oui ok mais ton [#2379 (comment)](https://github.com/wallabag/wallabag/issues/2379#issuecomment-252247016) c'est juste l'écran de login (qui lui oui est bien dans la langue de `parameters.yml` ).
Par contre si ton nouvel utilisateur s'identifie il bascule en "en" (langue par défaut).
bon week et merci à vous deux.
