### ISSUE TITLE
Stay on page after bookmarklet usage

### ISSUE THREAD

**Issue by mere-teresa** [wallabag/wallabag#238]
When I add an article/page in my poche, I would like to stay on the page I just added, instead of being redirected to my poche.

**Comment by jalcine** [comment]
Something like this could be implemented by sending a XHR request on the page as opposed to hitting the page in full. I'm not too sure if this would cause CORS issues so testing would be needed.

**Comment by tcitworld** [comment]
wallabag v2 will have a fulll API so this will be more easily made.

**Comment by jalcine** [comment]
@tcitworld I'm actually reading all of the older issues on this :) Hoping I can dive in and help out with this soon.

re: helping, is there a specific issue or page I should watch to contribute?

**Comment by tcitworld** [comment]
Your help will be very welcomed.

There are [guidelines](https://github.com/wallabag/wallabag/blob/dev/GUIDELINES.md) (that aren't much followed in fact, at least by me) and a [Contributing notes](https://github.com/wallabag/wallabag/blob/master/CONTRIBUTING.md)

We work on dev branch for 1.x versions but our next big version is 2.x on v2 branch, build with Symfony.

**Comment by jalcine** [comment]
Noted! I've noticed that 1.x seems to be mainly for bug fixing (as much as possible without hurting support) so I'll try to remember that.

**Comment by tcitworld** [comment]
Yup, we currenly are with 1.9 version, and I think there's just a few of these bugs that we we'll correct in the next 1.9.1 release. I guess with v2 most of them won't be there anymore (except of course for the website config ones).

**Comment by nicosomb** [comment]
We won't support bookmarklet anymore. 

Please reopen if necessary.
