### ISSUE TITLE
Don't display two factor checkbox in user admin panel when two factor is disabled

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#2380]
![image](https://cloud.githubusercontent.com/assets/62333/19143398/eeedc49c-8ba3-11e6-88ff-cd2d9e2feeda.png)

The field shouldn't be displayed if two factor isn't enabled.
It generates a UI problem.

**Comment by nicosomb** [comment]
Related to #2095?

**Comment by j0k3r** [comment]
Yep, but in the user management this time.
