### ISSUE TITLE
Reorder favorites page by date of favorite action and not by date of article import

### ISSUE THREAD

**Issue by yoannsculo** [wallabag/wallabag#2381]
Currently, when we tag an article as favorite it is displayed on the favorite list and this list is ordered by date of article import in database.
But I have hundreds of articles in database and I don't read them in a chronological order. When I mark an article as favorite, it will not be displayed on the top of the favorite list.

I'm using the favorite list to see afterwards the most interesting articles I read since the last time I checked the page. It would be great to be able to change the order of the list to display articles by time of favorite action and not by date of article import in Wallabag.

**Comment by nicosomb** [comment]
Today, this feature is not possible. 
We don't store the date of the `favorite` action. So we need to update the schema database for that.

**Comment by yoannsculo** [comment]
Ah ok I understand the reason. I just had a look at the database. is_starred is a field from wallabag_entry. Too bad it's not a easy request.
Anyway, I would be very happy if we could have this feature in the future :)

**Comment by yoannsculo** [comment]
Nice!!! Thank you very much! :+1:
