### ISSUE TITLE
Can't delete annotation

### ISSUE THREAD

**Issue by prolibre** [wallabag/wallabag#2382]
### Issue details

Impossible de supprimer ou d'éditer les annotations.
Une fois l'annotation saisie aucun icône / lien n'apparait pour la supprimer

Exemple en image : au survol du texte annoté voici ce qui apparait : 
![](http://oi63.tinypic.com/2ql5n4g.jpg)

idem sous firefox 49.0.1 / firefox dev 51.0a2 et chrome
### Environment
- wallabag version : 2.1.1
- How did you install wallabag? `git clone` ( fresh install )
- php version: PHP 5.6.24
- OS: debian stable
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql
### Steps to reproduce/test case

Ajouter une annotation puis essayer de la supprimer :-) en user ou admin

**Comment by tcitworld** [comment]
Cela ne marche pas en tant qu'utilisateur comme en tant qu'admin ?

**Comment by prolibre** [comment]
@tcitworld : pour ma part en tant qu'admin et @j0k3r a testé (conversation gitter) et n'avait pas l'icône en tant qu'user.

**Comment by prolibre** [comment]
Pour info je viens de tester sur la 2.1.2 ( v2.wallabag.org ) et ça fonctionne pour moi :-)

**Comment by tcitworld** [comment]
Mais...on n'a rien changé à ce niveau. :'(

**Comment by j0k3r** [comment]
Tu as bien testé avec un utilisateur non-admin ?

**Comment by prolibre** [comment]
oups ... je m'y perd. Donc effectivement chez moi ça marche avec un non admin ( il me semblait pourtant avoir testé ... mais bon ça marche ).
**Par contre en admin je ne peux pas éditer / supprimer les annotations.**
Désolé mais je jongle avec les comptes pour tester et je m'y perd.

**Comment by tcitworld** [comment]
J'ai retesté à nouveau, ça marche partout pour moi.

**Comment by prolibre** [comment]
Je ne comprends pas. Je viens même d'essayer sous IE ( Microsoft Edge 38.14393.0.0 ) pour voir si ça venait de mon navigateur.

Je suis en admin et voici encore comment l'annotation apparait au survol : 

![](http://oi66.tinypic.com/xnumc4.jpg)

je ne peux ni modifier ni supprimer... aucun icône.

Dans la table ` wallabag_annotation` tout semble normal ... user_id et entry_id sont bien liés à mon utilisateur et mon article.

**Comment by tcitworld** [comment]
Tu peux regarder la console de ton navigateur ?

**Comment by prolibre** [comment]
aucune erreur en console ... par contre j'ai une différence de code html généré (explication ci-dessous).

Je viens de faire le test avec deux users sur une même url et sur le même serveur (et même navigateur).

- Lorsque j'utilise mon compte admin par défaut ( id user1 ) **je n'ai pas les boutons** pour modifier/supprimer les annotation : 

```
<span class="annotator-controls">
/span>
<div>mon annotation</div>
```

- par contre lorsque j'utilise un compte test ( id user 11 ) **j'ai bien les boutons** en questions ( et je les retrouve dans le html généré ) : 

```
<span class="annotator-controls">
**<button type="button" title="Edit" class="annotator-edit">Edit</button>
<button type="button" title="Delete" class="annotator-delete">Delete</button>**
</span>
<div>mon annotation</div>
```

**Le plus étrange c'est que :** 
Pour tester si ça venait d'un problème de droits j'ai modifié à la main dans la bdd les droits de mon utilisateur admin.
J'ai remplacé dans la table user 
ça `a:2:{i:0;s:9:"ROLE_USER";i:1;s:16:"ROLE_SUPER_ADMIN";}`
par ça `a:1:{i:0;s:9:"ROLE_USER";}`

pour que mon admin devienne simple user. Ensuite je me suis déconnecté / reconnecté.

>> Et je suis toujours dans l'incapacité de modifier mes annotations avec ce compte.
Bref je ne trouve pas la "logique" du bug :-)

**Comment by prolibre** [comment]
@tcitworld @j0k3r 
je viens de trouver où ça cloche :-) ça m'énervait aussi j'ai davantage fouillé et le bug est bien présent mais uniquement lorsque le champ "name" est saisie dans l'interface ( "Mon Nom" dans "Mon Compte" ).

Donc je précise le bug : impossible de supprimer / modifier ses anotations quand le champ "nom" ( name dans la bdd ) est renseigné... et ce que que l'on soit admin ou pas.

Pour tester il suffit de renseigner ce champ :-)

**Comment by j0k3r** [comment]
:flushed: 
Merci pour l'investigation !

**Comment by prolibre** [comment]
de rien @j0k3r ... celui là était particulièrement vicieux :-)

**Comment by aaa2000** [comment]
Lorsqu'un nom est défini dans "Mon compte", la requête ajax `/annotations/7?entry=7` retourne une propiété `user`. Cette propriété est utlisé par le plugin `annotator` pour savoir si l'utilisatateur peut modifier, supprimer l'annotation. 

La suppression de la méthode https://github.com/wallabag/wallabag/blob/master/src/Wallabag/AnnotationBundle/Entity/Annotation.php#L239 permettrait de supprimer une annotation. Mais cela a un impact sur l'API.

L'autre moyen est de configurer le package http://docs.annotatorjs.org/en/latest/api/identity.html avec le nom de l'utilisateur dans app/Resources/static/themes/material/js/init.js
```
    app.include(annotator.identity.simple);
    app.include(annotator.storage.http, x);

    app.start().then(() => {
      app.ident.identity = x.user;
      app.annotations.load({ entry: x.entryId });
    });
```

Mais cela affiche cela

![wallabag_bug_annotation](https://cloud.githubusercontent.com/assets/163941/25815090/02d6c40c-3420-11e7-8b89-f6a81a47120d.png)
