### ISSUE TITLE
wallabag can't retrieve contents for http://calligra.org

### ISSUE THREAD

**Issue by leolivier** [wallabag/wallabag#2384]
### Issue details

wallabag can't retrieve contents for https://www.calligra.org/ (the site in the title is wrong)
Works for https://www.calligra.org/get-calligra/

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.1
* How did you install wallabag? Via `git clone` or by downloading the package? clone
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 5.6.24
* OS: raspbian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case
Add the site

**Comment by j0k3r** [comment]
Seems to be ok for an article: https://www.calligra.org/news/calligra-2-9-11-released/

But we won't improve wallabag to retrieve the homepage of this site. It isn't an article so I don't see the benefit to store it in wallabag.
