### ISSUE TITLE
List of tags page has issues

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#2390]
* takes forever to load
* number of articles for a tag is wrong

**Comment by j0k3r** [comment]
What we need to define: which kind of articles should we display when you click on a tag:
- unread articles
- read articles
- all articles (unread + read)

:question:

**Comment by tcitworld** [comment]
For me, it would be at first all of them, but ideally there should be a button to see only the unread/read/favorited/unfavorited articles.
