### ISSUE TITLE
Document parameters.yml and parameters setup during initial install or upgrade

### ISSUE THREAD

**Issue by zertrin** [wallabag/wallabag#2392]
### Issue details

During initial install or upgrade to a new version which introduces new parameters in `parameters.yml`, the step `composer install` will ask the user for parameters. For example:

```
Updating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
fosuser_registration (true):
[...]
```

Without any context, and without finding documentation about it ([I searched for `parameters.yml`](http://doc.wallabag.org/en/master/search.html?q=parameters.yml&check_keywords=yes&area=default) and didn't find what I was looking for, [searching for `fosuser_registration`](http://doc.wallabag.org/en/master/search.html?q=fosuser_registration#) gives zero results...), I feel a bit lost and am not sure what to enter.

I propose to add some documentation about `parameters.yml` and make sure this documentation is easily reachable from the upgrade and install documentation pages.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.1
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

**Comment by j0k3r** [comment]
Yep we lack documentation on that part.

When `composer` ask for a new value for a parameter it is usually safe to use the default value (the one in parenthesis).

But I really agree, we need documentation about `parameters.yml`.

**Comment by j0k3r** [comment]
http://doc.wallabag.org/en/master/user/parameters.html

**Comment by nicosomb** [comment]
We need to add this page in the menu.
