### ISSUE TITLE
Misalignment of the icons on the bottom right of the entry cards on some resolutions

### ISSUE THREAD

**Issue by zertrin** [wallabag/wallabag#2394]
### Issue details

The icons next to the entry's domain name may be dislocated if the domain name is a bit too long.

See screenshots:

When 3 entries are shown per rows:
![nl486uhl27zun17l6](https://cloud.githubusercontent.com/assets/1447163/19201575/a67270c4-8cce-11e6-8a44-a64dfb7b7662.PNG)

With only 2 entries per row (smaller screen):
![1gr6esg46gv6dhz6f](https://cloud.githubusercontent.com/assets/1447163/19201579/ab6260bc-8cce-11e6-85ce-b868dd3fbfec.PNG)
### Environment
- wallabag version (or git revision) that exhibits the issue: **2.1.1**
- How did you install wallabag? Via `git clone` or by downloading the package? **git clone**
- Last wallabag version that did not exhibit the issue (if applicable): **2.0.8**
- php version: **PHP 5.6.24-0+deb8u1**
- OS: **Debian Jessie**
- type of hosting (shared or dedicated): **dedicated**
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): **sqlite**
- Browser: **Firefox Developer Edition 51.0a2 (2016-10-03)**
### Steps to reproduce/test case

Issue happens for me after bagging for example the following articles (see screenshots above):
- https://www.technologyreview.com/s/602541/physicists-create-worlds-first-time-crystal/
- https://www.quantamagazine.org/20150702-paradoxical-crystal-baffles-physicists/
- http://sebastianraschka.com/blog/2015/why-python.html

**Comment by j0k3r** [comment]
Can you share your screen resolution?
It's a problem from my POV because I might have a bigger screen

![](https://cl.ly/00430L442B03/Image%202016-10-07%20at%208.53.31%20PM.png)

But yeah, maybe we should adjust few media-queries to handle all screen size.

**Comment by zertrin** [comment]
I have two screens, one is 1600x900 and the other 1280x1024, however since I'm using the TreeStyleTab extension on firefox, some place is eaten on the left of my browser.

Screenshot from the screen 1280x1024:
![fr5gr486gr6v14r6v1r68](https://cloud.githubusercontent.com/assets/1447163/19202257/b8b78640-8cd1-11e6-8a6b-bde353fac568.png)

Screenshot from the screen 1600x900:
![geraor5t68hz49zd45](https://cloud.githubusercontent.com/assets/1447163/19202263/bfee662c-8cd1-11e6-9722-cc56fa8f47ad.png)

**Comment by j0k3r** [comment]
That might be the problem.
We'll see what can we do.

**Comment by zertrin** [comment]
After some changes in the UI in the last versions, the problem is still there, just not caused by the domain name anymore, but by the estimated reading time and the date:

(same screen resolutions as before)

![1156bjfcjzrd](https://cloud.githubusercontent.com/assets/1447163/20459746/598a4b8a-aecd-11e6-9d3f-4d592e2c1617.png)

![12lzgtzjdtrvzzedfi](https://cloud.githubusercontent.com/assets/1447163/20459747/62df917c-aecd-11e6-8404-4e066b09172a.png)
