### ISSUE TITLE
ClassNotFoundException when executing bin/console

### ISSUE THREAD

**Issue by das-schaf** [wallabag/wallabag#2398]
### Issue details

Running bin/console gives me the following error:

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in /path_to_wallabag/app/AppKernel.php:48`

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.1
* How did you install wallabag? Via `git clone` or by downloading the package? package
* Last wallabag version that did not exhibit the issue (if applicable):  
* php version: PHP 7.0.11 
* OS: centos
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

Applied the following patch to get wallaby running:

vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php):
line 814 :

`$xmlData = file_get_contents($file); $xmlElement = simplexml_load_string($xmlData);`

otherwise i'll get

`simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/virtual/sheep1/tuerschmann.info/vendor/friendsofsymfony/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml&quot; in /var/www/virtual/sheep1/tuerschmann.info/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814`

### Steps to reproduce/test case

Simply run bin/console from web root

**Comment by j0k3r** [comment]
What is the exact command you launched?
To clear the cache for the end user you should use:

```
php bin/console c:c -e=prod
```

If you want to run any other command, you must pass the environment using `-e=prod` otherwise some dev requirement will be included and won't be fulfilled (generating the error you have).

**Comment by das-schaf** [comment]
I tried to run `bin/console wallabag:import:redis-worker pocket -vv` but running `bin/console -e=prod wallabag:import:redis-worker pocket -vv` did the trick. Thanks for the quick support.

Copied the command from the documentation. Maybe your parameter hint should be added to the docs.

**Comment by j0k3r** [comment]
Good catch, thanks for creating an issue about that 👍
