### ISSUE TITLE
Include wallabag.org / docker sources into wallabag/wallabag repository

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2404]
I don't want a monolithic repository for all of our projects, but I think (maybe I'm wrong) release process (and milestones/labels management) would be easier if we have wallabag.org and docker sources into wallabag/wallabag repository. 

What is your opinion? 

cc @wallabag/core @wallabag/wallabag-contributors

**Comment by jlnostr** [comment]
Disagree. In my opinion the repositories should be still separated. It might simplify some steps in the release process. But a shell script can do this as well.

**Comment by j0k3r** [comment]
I agree with @jlnostr.
Why it should be easier?

**Comment by xsteadfastx** [comment]
But sometimes the release has some issues for the docker image. Like right now. It would mess with the docker tags.
