### ISSUE TITLE
Import from Pocket fails

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/wallabag#2408]
### Issue details

Wallabag fails with Internal Server error when I try to import articles from Pocket

### Environment

* wallabag version: 2.1.1
* Install type: via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): none
* php version: 5.6.26
* OS: Amazon Linux
* type of hosting: dedicated AWS EC2
* which storage system you choose at install: SQLite

### Steps to reproduce/test case

I am trying to import items via "Migrate from Pocket" menu located on Quick Start page. Pocket consumer key is valid and has "Retrieve" permission.
First time it failed to import **any** and threw this error, the second time it imported 420 items out of 500 and threw the error again. 
The third time it duplicated (#2407) 100+ entries and threw the error third time.

![2](https://cloud.githubusercontent.com/assets/6388034/19220643/8d77622e-8e3a-11e6-8604-5cebbd724fef.PNG)

Host at issue: http://52.57.95.146/ (default credentials)

**Comment by j0k3r** [comment]
This is because the import fetch content as soon as it import them.
That's why it took too long to handle the import (event for 500 articles).

The recommended way to go is to use async import (which comes in 2.1). This way, you won't have a time out.

- http://doc.wallabag.org/en/master/developer/redis.html
- http://doc.wallabag.org/en/master/developer/rabbitmq.html

An other option is to increase the maximum time exception of your PHP instance.

**Comment by Suncatcher** [comment]
When I try

     # for Pocket import
     bin/console wallabag:import:redis-worker -e=prod pocket -vv >> ./wallabag/var/logs/redis-pocket.log
it gives me `./wallabag/var/logs/redis-pocket.log: Permission denied`, even when I run it via `sudo`.

When I try without  logs
 
      bin/console wallabag:import:redis-worker -e=prod pocket -vv
it throws me

      [InvalidArgumentException]
      The directory "/var/www/html/wallabag/var/cache/prod/annotations is not writeable.

It works only under root. Maybe the guide should be updated.

**Comment by tcitworld** [comment]
If the wallabag directory is not owned by your own user, you must prefix all commands with `sudo -u www-data` or whatever your webserver user is named.
