### ISSUE TITLE
Developer documentation: add information on how to run tests

### ISSUE THREAD

**Issue by szafranek** [wallabag/wallabag#2415]
### Issue details

I already submitted 3 pull requests, but I don't know how should I run unit tests... Could you please add information on how to run tests to developer documentation and `CONTRIBUTING.md`?

**Comment by tcitworld** [comment]
Will add. 
In the meantime, you can install `ant` and `phpunit`. The command to run basic tests is `ant prepare && phpunit`.
Note that you'll have some tests failed (around ~15) if you don't have any Redis server running during the tests.

**Comment by szafranek** [comment]
Thank you!
