### ISSUE TITLE
Upgrade from 2.0.8 --> 2.1.1 Fails at RabbitMqBundle

### ISSUE THREAD

**Issue by TheFu** [wallabag/wallabag#2421]
### Issue details
Installed 2.0.8 about 3 weeks ago. 
Saw that an upgrade to 2.1.1 was available yesterday.
Followed upgrade instructions:
$  sudo service apache2  stop  # seemed like a good idea (not in instructions)
$  rm -rf var/cache/*
$  git fetch origin
$  git fetch --tags
$  git checkout 2.1.1 --force
$  SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
# all seemed fine to this point.
$  php bin/console doctrine:migrations:migrate --env=prod
PHP Fatal error:  Uncaught Error: Class 'OldSound\RabbitMqBundle\OldSoundRabbitMqBundle' not found in /var/www/wallabag/app/AppKernel.php:41
Stack trace:
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(396): AppKernel->registerBundles()
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(68): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(117): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/wallabag/bin/console(29): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#5 {main}
  thrown in /var/www/wallabag/app/AppKernel.php on line 41

Please provide issue details here.
Fails to upgrade per the instructions.

### Environment

* started with wallabag version 2.0.8 on a fresh ubuntu 16.04.1 minimal server install. Only apache and ssh. No DE. No GUI. No end users.
* Install wallabag from the 2.0.8 package.  Ran nicely for a few weeks. Sufficient to get me completely addicted!
* $ php --version
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
* OS: Ubuntu 16.04.1 LTS amd64
* KVM VM. Self-hosted on 172.22.22.x/24 subnet.
* mysql-server-5.7 

### Steps to reproduce/test case
See above. Following upgrade instructions.  

I suspect the dependency on rabbitMQ should have been included in the upgrade instructions, but don't know enough about php webapps to understand the issue.

**Comment by nicosomb** [comment]
Hello @TheFu!

> Sufficient to get me completely addicted!

😍 

About your problem, can you remove the `vendor` directory (with `rm -rf vendor/`) and restart the installation steps at `SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist` please?

**Comment by TheFu** [comment]
Thanks!  That got a little farther (cleaning up vendor/), but more dependency issues ... I'm sure it is trivial to correct for someone familiar with composer. I'm a perl/RoR guy and way out of my depth here.

$ SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-amqplib/php-amqplib v2.6.3 -> satisfiable by php-amqplib/php-amqplib[v2.6.3].
    - php-amqplib/php-amqplib v2.6.3 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
  Problem 2
    - php-amqplib/php-amqplib v2.6.3 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - php-amqplib/rabbitmq-bundle v1.11.0 requires php-amqplib/php-amqplib ~2.6 -> satisfiable by php-amqplib/php-amqplib[v2.6.3].
    - Installation request for php-amqplib/rabbitmq-bundle v1.11.0 -> satisfiable by php-amqplib/rabbitmq-bundle[v1.11.0].

**Comment by nicosomb** [comment]
`sudo apt install php7.0-bcmath` to install the bcmath extension.

**Comment by TheFu** [comment]
Ah. Thanks!  I had tried using compose install/require and that failed.  Don't yet understand what is a php package and what is an OS package from the errors. I'll get there.  Didn't see this OS package listed as a dependency in the installation instructions, BTW. I was probably just looking in the wrong place?  

Closed, for me.  Thanks for the help!

**Comment by flow7** [comment]
can't do sudo on shared host

**Comment by nicosomb** [comment]
Hello @flow7! 

You can contact your web hoster for this problem.
