### ISSUE TITLE
German documentation: Wallabag updaten - wrong links

### ISSUE THREAD

**Issue by rabyte** [wallabag/wallabag#2423]
### Issue details
In the German documentation the urls to the update pages are wrong

* Wallabag updaten points to http://doc.wallabag.org/de/latest/user/upgrade-2.0.x-2.1.y.html
* Wallabag updaten 2.0.x -> 2.1.x points to http://doc.wallabag.org/de/latest/user/upgrade-2.0.x-2.0.y.html

In the English documentation there is no section about upgrading at all?

**Comment by j0k3r** [comment]
English file were moved in that PR https://github.com/wallabag/wallabag/pull/2403
We just forgot to move other translations doc.
