### ISSUE TITLE
Link image in the list view directly to article

### ISSUE THREAD

**Issue by szafranek** [wallabag/wallabag#2424]
### Issue details

Suggestion for improving UX: tapping on image in the entries view should take me to the article, instead of showing animated text snippet. This is something I never want – most websites showing links with images make these images acts as links. See Pocket, Amazon, Google or any other major site. By tapping the image I already expressed my intent to view the article.

Instead that doesn't happen, I need to wait for animation, then make a decision what do I have to tap to actually see the article.

Linking the image directly to the article would improve the flow. And if reading that article is not what I'm interested, I can always use the back button.
### Environment
- wallabag 2.1.1
### Steps to reproduce/test case

Open articles list, tap on image in any article.
Expected behavior: I'm taken to the article.
Actual behavior: a text snippet animates in place of the image.

**Comment by tcitworld** [comment]
cc @modos189 for an opinion

**Comment by nicosomb** [comment]
Maybe we can define a new option in settings (We'll create a UI tab on settings screen).

**Comment by szafranek** [comment]
I'd recommend choosing one approach, in order to reduce complexity in code and UI. But that's just my 2 cents :).

**Comment by Kdecherf** [comment]
We could simply redirect to the article as long as the vertical ellipsis on the right of the title already reveals the card. Thought?
