### ISSUE TITLE
Migrate from SQlite to MySQL/MariaDB

### ISSUE THREAD

**Issue by das-schaf** [wallabag/wallabag#2433]
### Issue details

Is there any best practice describing the producere how to move an existing wallabag installation based on SQLite to MySQL/MariaDB?
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.1.1
- How did you install wallabag? Via `git clone` or by downloading the package? package
- Last wallabag version that did not exhibit the issue (if applicable):
- php version: 7
- OS: centos
- type of hosting (shared or dedicated): shared
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

**Comment by j0k3r** [comment]
The best solution is too export your articles as json and re-import them in your new instance.

But it'll only retrieve articles and tags. Annotations, configuration, users, etc.. won't be exported.

**Comment by das-schaf** [comment]
Exporting all articles as json leads to an error

`500: Internal Server Error
Your data could not be encoded because it contains invalid UTF8 characters.`

**Comment by tcitworld** [comment]
Maybe you'll have more informations into your wallabag (`var/logs/`) logs or your server logs.

**Comment by das-schaf** [comment]
That's the full message:

` request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /wallabag/"" at /var/www/virtual/sheep1/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /wallabag/\" at /var/www/virtual/sheep1/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php`

Exporting my unread articles instead worked like a charm

**Comment by tcitworld** [comment]
This error message doesn't look like it's linked to your export issue.

**Comment by das-schaf** [comment]
Sorry, simple copy-paste error ;-)

`request.CRITICAL: Uncaught PHP Exception RuntimeException: "Your data could not be encoded because it contains invalid UTF8 characters." at /var/www/virtual/sheep1/wallabag/vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php line 36 {"exception":"[object] (RuntimeException(code: 0): Your data could not be encoded because it contains invalid UTF8 characters. at /var/www/virtual/sheep1/wallabag/vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php:36)"} []`

**Comment by j0k3r** [comment]
Looks like one entry is badly encoded.
We should try to identify which one ..

**Comment by das-schaf** [comment]
Sure, just tell me how. Btw i have 1400 entries all together.

**Comment by das-schaf** [comment]
I have migrated the database meanwhile by hand using a sqlite dump. Faced some sql errors due to unescaped single quotation marks.

I can keep the sqlite database for testing if you implement a migration tool in the future.

**Comment by burkemw3** [comment]
I just migrated by hand recently as well, and it was not fun. Below is an overview of what I did from memory and tweaked to avoid FK reference mistakes I made (so don't expect it to be totally accurate).

- backed things up
- dumped the sqlite db: `sqlite3 $PATH_TO_DB .dump > /tmp/wallaexport.sql`
- installed wallabag with mysql, and shut it down
- Modified wallaexport.sql
  - removed stuff related to migration_versions
  - took columns from CREATE TABLE statements and added them to INSERT INTO statements (sqlite and mysql didn't have the same column ordering for all tables)
  - switch table double quotes to back ticks
  - truncated wallabag_craue_config_setting table
  - truncated wallabag_config table
  - truncated wallabag_user table
  - inserted values into tables: wallabag_user, wallabag_craue_config_setting, wallabag_tag, wallabag_config, wallabag_oauth2_refresh_tokens, wallabag_oauth2_access_tokens, wallabag_oauth2_auth_codes, wallabag_entry, wallabag_entry_tag.
  - I didn't have values for other tables, so didn't modify them
- started wallabag pointed at mysql instance, took a deep breath, logged in, and saw it was successful!

Encoding was a problem for some entries. For example some fancy apostrophe's are showing as goofy characters. No other issues found at this time.

ymmv
