### ISSUE TITLE
Can't login after upgrade to 2.1.1

### ISSUE THREAD

**Issue by schiessle** [wallabag/wallabag#2437]
### Issue details

I updated wallabag 2.0.7 to 2.1.1 following this documentation for shared hoster: http://doc.wallabag.org/en/master/user/upgrade-2.0.x-2.1.1.html

For rabbitmq and redis I added this config parameter because both are not available on my shared hoster:

````
   rabbitmq_host: null
    rabbitmq_port: null
    rabbitmq_user: null
    rabbitmq_password: null
    redis_host: null
    redis_port: null
````

and also performed the database queries mentioned in the documentation. 

I can see the login page but I can't login. I get this error message at the login screen after I entered my username and password:

````
An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.locked AS locked_9, t0.expired AS expired_10, t0.expires_at AS expires_at_11, t0.confirmation_token AS confirmation_token_12, t0.password_requested_at AS password_requested_at_13, t0.roles AS roles_14, t0.credentials_expired AS credentials_expired_15, t0.credentials_expire_at AS credentials_expire_at_16, t0.id AS id_17, t0.name AS name_18, t0.created_at AS created_at_19, t0.updated_at AS updated_at_20, t0.authCode AS authCode_21, t0.twoFactorAuthentication AS twoFactorAuthentication_22, t0.trusted AS trusted_23, t24.id AS id_25, t24.theme AS theme_26, t24.items_per_page AS items_per_page_27, t24.language AS language_28, t24.rss_token AS rss_token_29, t24.rss_limit AS rss_limit_30, t24.reading_speed AS reading_speed_31, t24.pocket_consumer_key AS pocket_consumer_key_32, t24.user_id AS user_id_33 FROM `wallabag_user` t0 LEFT JOIN `wallabag_config` t24 ON t24.user_id = t0.id WHERE t0.username_canonical = ? LIMIT 1' with params ["schiesbn"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't24.pocket_consumer_key' in 'field list'
````

I think the `pocket_consumer_key` doesn't exists because the docuemntation said that I should delete it by performing:

````
DELETE FROM `wallabag_craue_config_setting` WHERE `name` = 'pocket_consumer_key';
````

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.1
* How did you install wallabag? downloaded package (tar file)
* Last wallabag version that did not exhibit the issue (if applicable): 2.0.7
* php version: PHP 5.6.26-pl0-gentoo
* OS: Gentoo GNU/Linux on a shared hoster
* type of hosting (shared or dedicated): shared hoster
* which storage system you choose at install (SQLite, MySQL/MariaDB or PosgreSQL): MySQL

### Steps to reproduce/test case

update from 2.0.7 to 2.1.1 following th documentation for shared hosting and then try to login: http://doc.wallabag.org/en/master/user/upgrade-2.0.x-2.1.1.html

**Comment by nicosomb** [comment]
Hello! 

Did you execute this query: 

```
ALTER TABLE `wallabag_config` ADD `pocket_consumer_key` VARCHAR(255) DEFAULT NULL;
```

**Comment by schiessle** [comment]
@nicosomb Thanks, it seems like I really missed this statement... Now it works! :smiley:
