### ISSUE TITLE
In twitter cards, change the description

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2441]
Today, we display the title in the description of the twitter card (see the screenshot).

![](https://d17oy1vhnax1f7.cloudfront.net/items/2p0z1o183g26031A0M2k/Capture%20d%E2%80%99e%CC%81cran%202016-10-13%20a%CC%80%2017.03.10.png?v=1a6dbf99)

We need to improve that by displaying a part of the article.

**Comment by tcitworld** [comment]
Maybe we could have `$entry->getAbstract()`. It could then be reused for themes (cards preview).
