### ISSUE TITLE
Generate QR Code for easier configuration of 3rd party apps

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2448]
For easier configuration of wallabag apps, like the android one, we would like to have a QR Code somewhere in the wallabag web application, which contains the following QR code text: `wallabag://user1@wallabag.example.com`

**Comment by Strubbl** [comment]
I just saw that issue #432 is maybe related. Android app is already capable of handling a qr code with the above mentioned URL. Now we need support from server side in providing a qr code image with such a wallabag user unique link.

**Comment by tcitworld** [comment]
Overkill https://github.com/endroid/QrCode ?

**Comment by Strubbl** [comment]
> Overkill https://github.com/endroid/QrCode ?

Why do you think that?

They write:

> You can use EndroidQrCodeBundle to integrate this service in your Symfony application.

Looks like a solid lib to me. (because of the versioning, usage example and integration in composer and symfony)

**Comment by tcitworld** [comment]
It's one more bundle to add to the app, one more requirement to composer, etc.

**Comment by anarcat** [comment]
isn't #2523 sufficient here?

**Comment by nicosomb** [comment]
You're right.
