### ISSUE TITLE
internal settings contains not translated strings

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2458]
### Issue details

Go to menu "internal settings" (URL: /settings). 

The title of that page is not translated. Instead it is hard-coded, please see https://github.com/wallabag/wallabag/blob/master/app/Resources/CraueConfigBundle/views/Settings/modify.html.twig#L3

Also it seems that the section title "Analytics" is not translated.

**Comment by j0k3r** [comment]
Good catch :)

**Comment by Strubbl** [comment]
@nicosomb on the same page, isn't the section title "Analytics" somehow hard-coded, too?
