### ISSUE TITLE
Do not remove makefile and scripts when errors are happening

### ISSUE THREAD

**Issue by Alwaysin** [wallabag/wallabag#2463]
### Issue details

Following https://github.com/wallabag/wallabag/issues/2461, I couldn't install Wallabag correctly. When I wanted to retry, I noticed I couldn't becaise Makefile and scripts/ (maybe others) were deleted. While I find it normal it happens when the build is successful, I find it pretty bad to do it when errors arise.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.1
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): dunno
* php version: 7.0.12
* OS: Arch Linux ARMv6
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): N/A

### Steps to reproduce/test case
```
git clone https://github.com/wallabag/wallabag.git
cd wallabag/
make install
<error happening>
<fixing the issue>
make install
<error : no Makefile !>
```

**Comment by tcitworld** [comment]
The makefile is currently in master and runs `git checkout 2.1.1`, a version where the makefile didn't exist. This will be fixed by 2.1.2 which is to be released tomorrow.
