### ISSUE TITLE
piwik host url problem

### ISSUE THREAD

**Issue by prolibre** [wallabag/wallabag#2469]
### Issue details

Piwik ne fonctionne pas si `piwik_host` contient http ou https ( "_URL de votre site dans Piwik_" dans la config interne )

ça fonctionne avec une URL de type : `www.domaine.co/piwik`
mais pas avec `https://www.domaine.co/piwik` ou `http://www.domaine.co/piwik`

En cause le bout de code généré pour piwik : 
`var u=(("https:" == document.location.protocol) ? "https" : "http") + "://www.domaine.co/piwik";`

Et cela depuis la version 2.1.0

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.2
* How did you install wallabag?   `git clone` 
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Mysql

**Comment by nicosomb** [comment]
We don't change anything for the 2.1.0 about the Piwik integration. 

In fact, what you describe is the normal behaviour, see https://github.com/mnapoli/PiwikTwigExtension (`{{ piwik('mypiwik.host.com', 123) }}`).

**Comment by prolibre** [comment]
oui je comprends.
C'est seulement déroutant pour l'utilisateur puisque toutes les autres url de l'interface sont de forme http://... et seule celle-ci doit être construite sans le http(s)
