### ISSUE TITLE
Issue during the upgrade to 2.1.2

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2470]
```bash
➜  poche git:(501a4da) ✗ sudo SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
  - Removing mouf/nodejs-installer (v1.0.10)
  - Removing gedmo/doctrine-extensions (v2.4.23)
  - Installing gedmo/doctrine-extensions (v2.4.24)
    Downloading: 100%         

  - Removing twig/twig (v1.26.0)
  - Installing twig/twig (v1.26.1)
    Downloading: 100%         

  - Removing psr/log (1.0.1)
  - Installing psr/log (1.0.2)
    Downloading: 100%         

  - Removing liip/theme-bundle (1.4.0)
  - Installing liip/theme-bundle (1.4.1)
    Downloading: 100%         

  - Removing sensiolabs/security-checker (v3.0.2)
  - Installing sensiolabs/security-checker (v4.0.0)
    Downloading: 100%         

  - Removing sensio/distribution-bundle (v5.0.12)
  - Installing sensio/distribution-bundle (v5.0.13)
    Downloading: 100%         

  - Removing friendsofsymfony/user-bundle (dev-master 47e4de9)
  - Installing friendsofsymfony/user-bundle (dev-master e168ed6)
    Downloading: 100%         

Generating optimized autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_socket (null): 
```

### Issue details

I have this error during the upgrade to 2.1.2 (from 2.1.1). What should I do?

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.1 -> 2.1.2
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Just the follow the official docs about how to upgrade.

**Comment by tcitworld** [comment]
That's not an issue. Just press enter when you don't know what to enter.

**Comment by NerosTie** [comment]
Yes, it works. But it's weird, I was afraid to break something (same error with `redis_scheme (tcp):` and `redis_path (null):`).

Is everything normal?

(btw, big update! :+1: )

**Comment by tcitworld** [comment]
Yeah, it's just parameters that we introduced. It's just for people that are interested with these features. You can checkout http://doc.wallabag.org/en/master/user/parameters.html

**Comment by NerosTie** [comment]
Thanks!

Should I close this "issue"? Or maybe other people will ask the same question?

**Comment by tcitworld** [comment]
Closing an issue doesn't remove it.
