### ISSUE TITLE
404 title isn't translated

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2474]
### Issue details

When deleting article too fast, as the article remains ; when I delete it once again then we have : 

```php
404: Not Found
Wallabag\CoreBundle\Entity\Entry object not found.
```

and the title of the page is : `error.page_title`

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.2
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): no idea
* php version: 5.6 
* OS: deibna 8.6
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

**Comment by tcitworld** [comment]
> When deleting article too fast, as the article remains 

What ?

**Comment by foxmask** [comment]
sometimes when I delete an article, this one is still on the page, so I click on the trash once again and then 404

**Comment by j0k3r** [comment]
Yeah and we won't fix that. It's the normal behavior to got a 404 if you want to delete a non-existing article.
What should be the _good_ behavior for you?

**Comment by j0k3r** [comment]
Oh ok, so that's a translation problem only, thanks :)

**Comment by foxmask** [comment]
right

**Comment by foxmask** [comment]
the title is not translate and the content of the mesage too , isnt it ?

**Comment by j0k3r** [comment]
Well, this message isn't generated by us and in fact it's an _error_ message, a kind of description of what happen. It's more a debug message, maybe we shouldn't display it to the end user ...

**Comment by foxmask** [comment]
just one notice, the title is translated but the page, for an end user, is very annoying, as there is still 
```
404: Not Found
Wallabag\CoreBundle\Entity\Entry object not found.
```
as an error message 
If we could see something like "l'article que vous demandez n'existe (plus|pas)/a deja ete supprimé" will be more readable, wont it?
