### ISSUE TITLE
Date not translated in the footer

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#2476]
### Issue details

The date (not sure what this date is though) appearing in the footer is not translated in french whereas the rest of the content is.

![wallabag-date-not-translated](https://cloud.githubusercontent.com/assets/3419050/19569210/3a622358-96f5-11e6-9840-d2436339fd18.png)
### Environment

Wallabag 2.1.2
### Steps to reproduce/test case

Set wallabag in French and look at the footer on the unread articles page.

**Comment by j0k3r** [comment]
I've already started sth about this.

**Comment by nicofrand** [comment]
Still does not work with wallabag 2.2.0.
How can I help debugging ?

**Comment by aaa2000** [comment]
@nicofrand Check that your local is installed in your server, you can list them with `locale -a`

**Comment by aaa2000** [comment]
Maybe, it is better to use `IntlDateFormatter` instead of `strftime`
in https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Twig/WallabagExtension.php#L145

**Comment by jpbaril** [comment]
The date language should be based on the one set in the configuration section, not the browser or server. In case of the later it's even impossible to manage if using the docker image.
