### ISSUE TITLE
Useless scrollbar in configuration menu when on "Automatic tag rules"

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#2478]
### Issue details

A useless and annoying scrollbar appears when clicking on "Règles de tag automatiques"

![wallabag-scrollbar](https://cloud.githubusercontent.com/assets/3419050/19569947/127ebf4c-96f8-11e6-952c-fe82963fafdf.png)

I believe it comes from the small line underlying the text.

It does not appear with any other item from this menu.
### Environment

Wallabag 2.1.2
Firefox 49.0 (not tested with another browser)
### Steps to reproduce/test case

Go to "Configuration" then click on "Règles de tag automatiques"

**Comment by tcitworld** [comment]
Oh. Can I ask you your screen resolution ?

**Comment by nicofrand** [comment]
1920x1080 so this is not an issue.
But this only appears when clicking on the last item.

**Comment by nicofrand** [comment]
The same issue appears with the last item of the menu in the "Internal configuration" page.

**Comment by tcitworld** [comment]
Related to https://github.com/wallabag/wallabag/pull/2455

**Comment by nicosomb** [comment]
Fixed by #2640.
