### ISSUE TITLE
Document how to backup wallabag

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#2479]
### Issue details

I don't trust my server and would like to regularly do a backup* of my wallabag, that's to say the articles with the tags, images, states, etc.

*Something that I could do in bash in a cron job

I could not find anything in the documentation which says which directory and files I needed to backup to be able to recreate my instance after a crash and reinstallation of wallabag.

**Comment by tcitworld** [comment]
For now, pictures are not downloaded.

All of your entries, tags, favorite/archived status are stored into the database, so if you use SQLite it would be just copying the `data/db/wallabag.sqlite` file somewhere else. Otherwise, lookup on the internet on how to create backups of MySQL or PostgreSQL.

**Comment by nicofrand** [comment]
Oh. I am using wallabag to archive posts that I fear will disappear and some of them are recipes so that images are important. The images were downloaded with Wallabag V1 IIRC, am I right ?

The SQLite file will be fine for the backup then, thanks.

**Comment by tcitworld** [comment]
Yup. Should come back with wallabag 2.2.

**Comment by tcitworld** [comment]
When they'll come back, they will be into `data/assets/images/` so you'll want to backup the whole `data` directory maybe.

**Comment by bmillemathias** [comment]
Hi,

I'm up to write a documentation page to explain what to backup on wallabag.

**Comment by bmillemathias** [comment]
While documenting I find I don't have a `data/assets/images` directory in my installation and however images are working.

**Comment by j0k3r** [comment]
Because, as @tcitworld said, downloading images aren't available yet for wallabag 2.
It should arrive with the 2.2 version

**Comment by bmillemathias** [comment]
I guess this bug can be closed now.

**Comment by nicofrand** [comment]
Nice thanks !

Le jeu. 20 oct. 2016 à 20:33, Thomas Citharel <notifications@github.com> a
écrit :

**Comment by tcitworld** [comment]
> When they'll come back, they will be into data/assets/images/ so you'll want to backup the whole data directory maybe.

My bad, they're at `/web/assets/images/`
