### ISSUE TITLE
Reload content via API

### ISSUE THREAD

**Issue by Thrilleratplay** [wallabag/wallabag#2489]
When a site config or site contents have changes, it would be handy to be able to programmatically refetch contents.

**Comment by nicosomb** [comment]
@j0k3r For this feature, do we need a new route or can we change the PATCH method on an entry (we add a new parameter, called `refetch` to reload the content for the entry)?

**Comment by j0k3r** [comment]
I was thinking of a new route.

**Comment by Rurik19** [comment]
There is unused method PUT :-)
