### ISSUE TITLE
Feature request - Option to view original article side by side

### ISSUE THREAD

**Issue by Thrilleratplay** [wallabag/wallabag#2490]
Option to load the original article in an iframe side by side with the content in Wallabag UI.  It would be useful for verifying the article contents were correctly fetched or if the original contents had been updated.

**Comment by j0k3r** [comment]
Well, for that you can easily open a new tab :)

**Comment by Thrilleratplay** [comment]
True but viewing side by side is more convenient for comparing.

**Comment by bmillemathias** [comment]
@Thrilleratplay You'd rather install an extension to your browser to do that.

**Comment by tcitworld** [comment]
Closing. Not really the point of wallabag. A tool based on Graby or something else can do the trick on it's own.
