### ISSUE TITLE
Unable to retrieve article - http://krebsonsecurity.com/

### ISSUE THREAD

**Issue by markwaters** [wallabag/wallabag#2491]
http://krebsonsecurity.com/2016/10/hacked-cameras-dvrs-powered-todays-massive-internet-outage/

**Comment by j0k3r** [comment]
I think the main problem comes is that website take ages to answer !
So long that isup.me think the website is down: http://isup.me/krebsonsecurity.com

So the request timeout before we can even try to extract the content.

> cURL Error: Operation timed out after 10001 milliseconds with 0 bytes received

We wait 10s by default, after that we assume the website took too long to respond.

I'm sorry but we won't be able to fix that on our side, it should be done on the website site.
