### ISSUE TITLE
Error at install following dedicated web server instructions

### ISSUE THREAD

**Issue by roukydesbois** [wallabag/wallabag#2498]
### Issue details

When following [these instructions](http://doc.wallabag.org/en/master/user/installation.html#on-a-dedicated-web-server-recommended-way), I have this error when I `make install`:

`HEAD is now at 501a4da... Release wallabag 2.1.2
scripts/install.sh: 9: scripts/install.sh: composer: not found
PHP Warning:  require(/home/thomas/wallabag/app/../vendor/autoload.php): failed to open stream: No such file or directory in /home/thomas/wallabag/app/autoload.php on line 9
PHP Fatal error:  require(): Failed opening required '/home/thomas/wallabag/app/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/thomas/wallabag/app/autoload.php on line 9
Makefile:15: recipe for target 'install' failed
make: *** [install] Error 255`

Indeed, there is no vendor folder in the git repository as indicated [here](https://github.com/wallabag/wallabag/blob/master/app/autoload.php#L9)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.2
* How did you install wallabag? Via `git clone`
* php version: 7
* OS: Ubuntu 16.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Clone the repo, `cd wallabag && make install`

**Comment by tcitworld** [comment]
You need to install composer.

**Comment by nicosomb** [comment]
Please read this part of the documentation for composer if (null === $this->getUser() ||

**Comment by nicosomb** [comment]
Please this part of the documentation for composer installation http://doc.wallabag.org/en/master/user/installation.html#requirements

**Comment by j0k3r** [comment]
Maybe we can a check about that in the Makefile?

**Comment by roukydesbois** [comment]
OK, I had to install it globally, it is explained how in the linked specific instructions but it was not obvious to me. Thanks for your help!
