### ISSUE TITLE
Tags - do not differ between upper / lower case

### ISSUE THREAD

**Issue by benbeton** [wallabag/wallabag#2502]
This is a feature request

tags should not be different when written in upper / lower case.

Right now, I see 2 different tags when writing them in upper or lower case.

regards

**Comment by nicosomb** [comment]
Hello @benbeton! 

It's not a feature request, it's a bug in fact.

**Comment by benbeton** [comment]
great, hope that will be fixed in one of the upcoming version.

**Comment by nicosomb** [comment]
We can close this issue thanks to @Kdecherf 🎉
