### ISSUE TITLE
L10N - Make translator work easier, use a translation tool ;)

### ISSUE THREAD

**Issue by Jibec** [wallabag/wallabag#2511]
Hi,

I understand from you documentation we have to edit files to make translations: http://doc.wallabag.org/en/master/developer/translate.html
I have to say it's not easy to make a follow-up, searching and make reviews of you project. Contributor in translation are often unskilled regarding to technical stuff and editing files in git is not that easy. Also, have a little competition against other languages is also nice :)

can you please connect your project with a translation tool ?

As you aim for freedom, I suggest open-source tool. A few exists: Pootle, Zanata, Weblate.
As seen from my translator experience and what I saw from other projects, Weblate is the simplest one I suggest you to use. It also connects directly to the git branch you give.

You can either join weblate.org who host for free open-source projects: https://hosted.weblate.org/projects/ or maybe join a project you share values with, like https://translate.yunohost.org/ (you should ask them if they agree, but I feel like it make sense)

Btw, I created this pull request, it was not easy to find files, I hope I picked the right ones... https://github.com/wallabag/wallabag/pull/2510

**Comment by nicosomb** [comment]
Good idea. We already tried external tools, like pootle and ... (I forgot its name).
I will try weblate 👍

**Comment by Jibec** [comment]
cool :) I suggest to discuss with Yunohost, I think there is an opportunity to set-up (little by little) a platform of translation of tools that are share common values on self-hosting and web empowerment tools.

By the way, what are the rules for YAML files ? When do we need escaping content with simple or double quote? I see an heterogeneous usage, does it change anything?

**Comment by nicosomb** [comment]
I asked an account on weblate.org website. The maintainer seems to be busy and will have a look next week.

**Comment by nicosomb** [comment]
Good news: https://hosted.weblate.org/projects/wallabag/#overview

**Comment by nicosomb** [comment]
@Jibec Can you help us by updating our documentation https://github.com/wallabag/wallabag/blob/master/docs/en/developer/translate.rst? 
Don't remove the other way part, just a chapter about weblate.

**Comment by Jibec** [comment]
I will :) thank you !
Le 18 nov. 2016 15:45, "Nicolas Lœuillet" <notifications@github.com> a
écrit :

**Comment by Jibec** [comment]
after checks:
* this file is not in weblate: src/Wallabag/UserBundle/Resources/translations/wallabag_user.fr.yml

* files "messages" and "validators" are the same in weblate:
https://hosted.weblate.org/translate/wallabag/messages/fr/?type=all should be:  wallabag/src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
https://hosted.weblate.org/translate/wallabag/validators/fr/?type=all

list of language should be the same in all files, so we can have a fair competition when we compare languages ;)

Note: I do not really see the point to tell where to translate it in a "developer" part, can't we use FAQ?
Next step is to add the documentation in weblate :)

**Comment by nicosomb** [comment]
@Jibec What do I need to do?

**Comment by Jibec** [comment]
You have a create a new component to include "wallabag_user" file.

To fix the second issue, I assume each Weblate component is pointing on a git file. You should  go in Weblate, select "wallabag" project, go in component "Messages" and fix the file, so it use  wallabag/src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml

If needed, you can talk with me on XMPP: jean-baptiste@holcroft.fr

Btw, YunoHost team do as follow:
* They automatically push changes from git to weblate.
* They manually pull new translation from weblate to git (they do not translate in git).
I find it fine, I suggest you to do the same.

**Comment by Jibec** [comment]
@nijel can you please have a look?

**Comment by nijel** [comment]
Just changed that. I had to fix few errors in the yaml files though...

**Comment by Jibec** [comment]
Thanks @nijel, but can you also add a new component to add "wallabag_user" for translation ?
https://github.com/wallabag/wallabag/tree/master/src/Wallabag/UserBundle/Resources/translations

**Comment by nijel** [comment]
Added: https://hosted.weblate.org/projects/wallabag/user/

**Comment by Jibec** [comment]
thanks again, we are almost done!

Is it normal not to be 100% in english?
This looks weird: https://hosted.weblate.org/translate/wallabag/android-app/en/?type=allchecks

**Comment by nijel** [comment]
Probably some temporary error, it's no longer there...

**Comment by di72nn** [comment]
Can someone please fix https://hosted.weblate.org/projects/wallabag/fos-user/? There is no "source" (English) language there. Newly added languages show zero strings.

**Comment by Jibec** [comment]
this issue still looks valid. It looks like the file were deleted on purpose, shouldn't we remove this component from weblate?

**Comment by nijel** [comment]
I've just removed it.

**Comment by Jibec** [comment]
Thank you everyone, it was a pretty long issue, keep the good work :)
