### ISSUE TITLE
Footer truncated

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2515]
### Issue details

footer with firefox on mobile is truncated

![29 octobre 2016 210256 gmt 0200](https://cloud.githubusercontent.com/assets/208212/19832202/6bbc8f54-9e1d-11e6-8e4b-9d8c3d40f5a7.png)

the data translation seemed to be fixed here 576d285
### Environment
- wallabag version (or git revision) that exhibits the issue: 2.1.2
- How did you install wallabag? Via `git clone` or by downloading the package? git clone
- Last wallabag version that did not exhibit the issue (if applicable): n/a
- php version: 5.6
- OS: 8.6 debian
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

**Comment by nicosomb** [comment]
Maybe we can hide the stats in the mobile view.

**Comment by nicosomb** [comment]
Fixed by #2640.
