### ISSUE TITLE
2.0 to 2.1 upgrade leads to empty login/start page

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#2516]
I have been using 2.0 fine for a while so I thought I would upgrade to benefit from the new stuff. So I followed this page http://doc.wallabag.org/en/master/user/upgrade-2.0.x-2.1.1.html for the upgrade/

I copied the the parameters.yml and the data folders in th right folders.

I am using Sqlite on Debian Wheezy, Apache 2.2.22 on a self hosted server with custom port that points to wallabag/web

Here is the wallabag error log after the new install (when I open the page)

 `Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException' with message 'You have requested a non-existent parameter "fosuser_registration".' in /var/www/wallabagII/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:84\nStack trace:\n#0 /var/www/wallabagII/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(200): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->get('fosuser_registr...')\n#1 /var/www/wallabagII/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(171): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->resolveString('%fosuser_regist...', Array)\n#2 /var/www/wallabagII/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(161): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->resolveValue('%fosuser_regist...', Array)\n#3 /var/www/wallabagII/vendor/sym in /var/www/wallabagII/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 84`

`

**Comment by nicosomb** [comment]
Hello @gerroon! 

In your `app/config/parameters.yml` file, do you have all the parameters as described here: http://doc.wallabag.org/en/master/user/upgrade-2.0.x-2.1.1.html#upgrade-on-a-shared-hosting? 

It seems that the `fosuser_registration` is missing.

**Comment by nicosomb** [comment]
I close this issue. If necessary, please reopen.
