### ISSUE TITLE
Cannot retrieve content for "Heute im Bundestag"

### ISSUE THREAD

**Issue by kuyper** [wallabag/wallabag#2527]
Tested with wallabag 2.1.2: cannot retrieve the content of 

https://www.bundestag.de/hib#url=L3ByZXNzZS9oaWIvMjAxNjExLy0vNDc4MzAy&mod=mod454590

Start page is https://www.bundestag.de/hib

**Comment by j0k3r** [comment]
It'll be hard to get that content since it is loaded using an ajax request (this one: https://www.bundestag.de/presse/hib/201611/-/478302?view=main).
We can rewrite the url to get that one but we need information in the html page to get identifier (`201611/-/478302`) and it doesn't seems to be in the initial html page 😕

**Comment by techexo** [comment]
After studying a bit the code of the page, the "real" URL of the article is actually present in the footer as an argument of a div:
```html
<div class="shariff" data-lang="de" data-theme="grey" data-orientation="vertical" data-services="[&quot;twitter&quot;,&quot;facebook&quot;,&quot;googleplus&quot;,&quot;whatsapp&quot;,&quot;mail&quot;]" data-mail-url="mailto:" data-mail-subject="Empfehlung aus dem Internetauftritt des Bundestages" data-mail-body="Der nachfolgende Artikel könnte für Sie interessant sein: https://www.bundestag.de/presse/hib/-/580216" data-url="https://www.bundestag.de/presse/hib/-/580216" data-title="Deutscher Bundestag - Lobbyregister im Vergleich">
    <ul class="theme-grey orientation-vertical col-5">
        [...]
    </ul>
</div>
```

The URL is contained in `//div[@class='shariff']/@data-url`. I don't know how to deal with rewrite, however.

**Comment by j0k3r** [comment]
You can use https://help.fivefilters.org/full-text-rss/site-patterns.html#single-page-link-xpath

**Comment by techexo** [comment]
@j0k3r I thought about that, but I am actually running into another issue first:
As the original URLs contain `#`, it seems that graby has some troubles parsing the URL.

For example, trying to fetch `https://www.bundestag.de/hib#url=L3ByZXNzZS9oaWIvMjAxNjExLy0vNDc4MzAy&mod=mod454590` with f43.me leads to the following log:
```
[2018-11-26 20:17:58] graby.DEBUG: Fetching url: {url} {"url":"https://www.bundestag.de/hib#url=L3ByZXNzZS9oaWIvMjAxNjExLy0vNDc4MzAy&mod=mod454590"} []
[2018-11-26 20:17:58] graby.DEBUG: Trying using method "{method}" on url "{url}" {"method":"get","url":"https://www.bundestag.de/hib"} []
```
As everything after the `#` seems to be deleted, there is no way to fetch the true URL.

**Comment by techexo** [comment]
@kuyper As you can see, it will probably be difficult to retrieve the necessary information from the given URL to fetch it in wallabag.
As a workaround, you can however use the [RSS feed](https://www.bundestag.de/static/appdata/includes/rss/hib.rss) of _Heute im Bundestag_, that contains the direct links to the article, that are then perfectly fetched in wallabag :-)

@j0k3r I have absolutely no idea if the `single_page_link_in_feed: [XPath]` instruction could be used for this.
