### ISSUE TITLE
Imported items comes in reverse sorting 

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#2531]
### Issue details
I exported my database as json from wallabag v2 then imported it into the latest version.  

My articles were from latest to the earliest. The articles shows up as first to last in the latest version. So first page shows the first articles so on.

### Environment

* wallabag version (or git revision) that exhibits the issue:
501a4dae5b5a89e76fd4c7b00170a5f42beb1b63

* How did you install wallabag? Via `git clone` or by downloading the package?
git clone, make script (like it was mentioned in the install doc)

* Last wallabag version that did not exhibit the issue (if applicable):
I am not sure. I believe that from v1 to v2 was ok/

* php version:
PHP 5.6.27-1~dotdeb+7.1 (cli) (built: Oct 15 2016 02:45:48) 

* OS:
Debian Wheezy

* type of hosting (shared or dedicated):
Dedicated 

* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
SQLite

### Steps to reproduce/test case
Export your database from v2.0 as json then import into the latest version

Maybe there is some kind of internal setting for sorting the articles but I was not able to find it. IOt would be nice if someone can also provide a way to resort my articles so they show up properlly.

**Comment by j0k3r** [comment]
This is intriguing. I guess list are sorted by `updated_at` date.
We only override the `created_at` date when importing.

**Comment by gerroon** [comment]
@j0k3r 

Is there a way to force to reverse the list? It is a bit of an issue with the android app because it only downloads the earliest ones naturally. I have hundreds of articles.

thanks

**Comment by gerroon** [comment]
@j0k3r 

thanks
