### ISSUE TITLE
Actions hidden with mobile website version

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2538]
### Issue details

when I delete a lot of articles, from my desktop, I click quickly of the mouse, but from my nexus5 with firefox, I have to wait (a lot, this is the feeling when you want to do thing quickly :) a moment before being able again to delete another article.

This is due to the fact that the message "article supprimé" is displayed at the bottom of the screen and then hide all actions we can do. So we have to wait that this message disapeares to be able to, at least, do something 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.2
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 5.6
* OS: debian 8.6
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

### Steps to reproduce/test case

![image](https://cloud.githubusercontent.com/assets/208212/20006576/7218b9ca-a298-11e6-9cbf-3f6f3c5252ad.png)

May be the message could be displayed : 
* the same way it is in the bottom of the screen, but in the middle of the screen with a little fading effect to avoid to be annoying
* as the tag, but beside it and at left of the screen. 

I am not able to say if there will be a side effect in another langage if the message is displayed at the left of the screen.

**Comment by tcitworld** [comment]
This will need to be confirmed on upcoming 2.1.3

**Comment by nicosomb** [comment]
@foxmask Could try with 2.1.3 please?

**Comment by foxmask** [comment]
it's perfeclty fixed ; thanks :+1:
