### ISSUE TITLE
Fresh installation throws 500 errors

### ISSUE THREAD

**Issue by icyground** [wallabag/wallabag#2542]
### Issue details

A fresh installation of wallabag with pdo_mysql backend fails with error 500 on multiple internal sites.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.3
* How did you install wallabag? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): not applicable
* php version: 7.0.8-0ubuntu0.16.04.3
* OS: Ubuntu 16.04.1 LTS
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

- Clone current git repository
- `make`and pick MySQL with valid credentials as backend
- create admin
- log in (until here its working like a charm)
- switch to a site that is article related (all articles, archive, favorites) and see a 500 exception:

`500: Internal Server Error
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT id_0 FROM (SELECT w0_.id AS id_0, w0_.uuid AS uuid_1, w0_.title AS title_2, w0_.url AS url_3, w0_.is_archived AS is_archived_4, w0_.is_starred AS is_starred_5, w0_.content AS content_6, w0_.created_at AS created_at_7, w0_.updated_at AS updated_at_8, w0_.mimetype AS mimetype_9, w0_.language AS language_10, w0_.reading_time AS reading_time_11, w0_.domain_name AS domain_name_12, w0_.preview_picture AS preview_picture_13, w0_.is_public AS is_public_14, w1_.id AS id_15 FROM `wallabag_entry` w0_ LEFT JOIN `wallabag_user` w1_ ON w0_.user_id = w1_.id WHERE w1_.id = ? AND w0_.is_starred = 1) dctrn_result ORDER BY created_at_7 DESC LIMIT 12 OFFSET 0' with params [1]: SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.created_at_7' which is not in SELECT list; this is incompatible with DISTINCT") in "WallabagCoreBundle:Entry:entries.html.twig" at line 23.`
(this is for /starred/list)

**Comment by j0k3r** [comment]
Might be the same kind of error than https://github.com/wallabag/wallabag/issues/2488
Can you please give the version of MySQL?

**Comment by icyground** [comment]
mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64)

**Comment by nicosomb** [comment]
@j0k3r is that a duplicate?

**Comment by j0k3r** [comment]
I don't know. We should try to test using the same MySQL version.

**Comment by nebulade** [comment]
I can confirm, this also happens with MySQL version 5.6.19

**Comment by sandprickle** [comment]
If I'm not mistaken, I have the same issue. 

Wallabag 2.1.4
Ubuntu 16.04.1 LTS
PHP 7.0.8
MySQL 5.7.16

I can access all but Unread, Starred, Archive, and All Entries. 
I just upgraded from 2.1.2 to 2.1.4.

Let me know if there's anything I can do to help.

**Comment by tcitworld** [comment]
See #2602 for temporary fix.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
