### ISSUE TITLE
Can't fetch multipage article from sueddeutsche.de

### ISSUE THREAD

**Issue by andresth** [wallabag/wallabag#2549]
### Issue details

sueddeutsche.de sometimes split their articles over multiple pages.
When you add the link to an article to wallabag, then it fetches only the first page.

I tried to solve this problem by finding a `single_page_link` or `next_page_link` for the siteconfig, but they are using JavaScript to load the full article. If I understand the siteconfig syntax correctly, there seem no way to handle JavaScript

I found out that the JavaScript sends a `POST` request to the article URL with an additional parameter (`article.singlePage=true`).

I tested it as a GET request with several articles and it also works with articles that ahve only one page.

I think there should be a way to define some kind of rewrite rule within the sitconfig.

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.1.3**
* How did you install wallabag? Via `git clone` or by downloading the package? **git clone**
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: **7.0.8**
* OS: **Linux**
* type of hosting (shared or dedicated): **shared**
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): **MySQL**

### Steps to reproduce/test case

Add this link to wallabag and you will only get the content of the first of three pages
http://www.sueddeutsche.de/muenchen/mietshaus-am-gaertnerplatz-alles-muss-raus-1.1556693

If you add this link you will get the full article
http://www.sueddeutsche.de/muenchen/mietshaus-am-gaertnerplatz-alles-muss-raus-1.1556693?article.singlePage=true

**Comment by andresth** [comment]
Hi,
I figured out how to fetch the article via a site config file 😳 

See this PR: fivefilters/ftr-site-config#221

**Comment by j0k3r** [comment]
Great, thanks for noticing us!
It'll be available in the next release then (2.2.0)
