### ISSUE TITLE
Wrong order for variable assignation in update.sh script

### ISSUE THREAD

**Issue by dkrmr** [wallabag/wallabag#2554]
### Issue details

The `TAG` variable is set before the new tags are fetch.
So you need to run `make update` twice for upgrading.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.2
* How did you install wallabag? Via `git clone` or by downloading the package?: clone
* Last wallabag version that did not exhibit the issue (if applicable): None, still present in master and 2.2

### Steps to reproduce/test case

* Have a local repository that do not contains the last tag. Ex: you're in 2.1.2 and want to upgrade to 2.1.3
* run `make update`:
  * The `TAG` variable is set to the last tag locally present, at the time 2.1.2
  * the script fetch the tags from the remote, 2.1.3, 2.2 etc...
  * checkout the `TAG` variable, which is still 2.1.2
* run `make update` again:
  * The `TAG` variable is set to the proper last tag.

**Comment by nicosomb** [comment]
Good catch!

**Comment by dkrmr** [comment]
PR: https://github.com/wallabag/wallabag/pull/2555
