### ISSUE TITLE
[Just info] Wallabagger v 1.1 is on the store

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2557]
Crome extension for wallabag v2 is on v1.1 in store and on github

Fixes # 1
implements # 2 : option "Allow space in tags" switch fix tags key to enter
focus set to tag input right after open
right key add first found tag

found update issue - you must input your options again :-)

Now you don't need mouse to work with tags!

**Comment by nicosomb** [comment]
Hello @Rurik19! 

Thank you for your work. 
Can you write a blog post for wallabag.org about this addon? How to install / configure / use it, etc. with screenshots (or even a video ;-) ). 
You can find blog repository here: https://github.com/wallabag/wallabag.org/tree/master/content/posts

**Comment by nicosomb** [comment]
New issue here https://github.com/wallabag/wallabagger/issues/6
