### ISSUE TITLE
Delete all archived articles in one click

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#2558]
Button should be next to Delete/Reset my account.

**Comment by ngosang** [comment]
I think we should have a button in the right top corner (only in Archive list).
![](http://pix.toile-libre.org/upload/original/1486029668.png)

**Comment by nicosomb** [comment]
It seems to be OK. 

![capture d ecran 2017-06-13 a 17 23 45](https://user-images.githubusercontent.com/121870/27090296-15a9e812-505d-11e7-9d6b-974a15353bd5.png)
