### ISSUE TITLE
Export via cli

### ISSUE THREAD

**Issue by isAAAc** [wallabag/wallabag#2560]
### Issue details
Export with the button give an empty json file 

could we export datas by cli (for all users in one shot)
### Environment

* wallabag version (or git revision) that exhibits the issue: 1.9.2
* How did you install wallabag? Via `git clone` or by downloading the package? git cloen (i think) via Yunohost
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: installed on the server : PHP 5.6.27-0+deb8u1  
* OS: GNU/Linux Debian 8.6
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): good question :/ how can i find it ? installed via yunohost, i didn't choose the db

### Steps to reproduce/test case

each time i want export with the button, json gived file is empty

**Comment by nicosomb** [comment]
Hello @isAAAc! 

I was sure you told about wallabag v2. We won't add features in wallabag v1.
We'll add this feature in wallabag v2.

**Comment by tcitworld** [comment]
I have a python script to handle exports on Framabag. Will share.

**Comment by j0k3r** [comment]
@isAAAc please check https://github.com/wallabag/wallabag/issues/1747

**Comment by isAAAc** [comment]
thx for you all ;)

**Comment by isAAAc** [comment]
ok, i 'm worst that a noob on sql , (used ti break all my sql each time i touch them ^^)

as said , my wallabag is on younohost, 
the cli command to export the cvs in https://github.com/benediktg/wallabag-migration doesn't work 
>admin@krashboyz:~$ mysql -e"
> SELECT url, is_read, is_fav
> FROM entries
> WHERE user_id = ${WB_USERID}
> INTO OUTFILE '/tmp/wallabag-user-${WB_USERID}.csv'
> FIELDS TERMINATED BY ','
> ENCLOSED BY '\"'
> LINES TERMINATED BY '\n';" wallabag
>ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password: NO)

so i installed phpmyadmin ...

i can request like that , but i don't unederstand how to  get the rest with phpmyadmin : 

>SELECT `entries`.`url`, `entries`.`is_read`, `entries`.`is_fav` FROM `entries` 

howto get : 
>WHERE `user_id` = 'N';  # replace N by your actual user ID 

?

thx for your help ;) (if you can help)

**Comment by isAAAc** [comment]
oh, and can i do that for al lmy users in one shot and import all in one shot too ?
or have i to do that for each user on by one ?

**Comment by isAAAc** [comment]
well, i spend to much time with this, i think i'll go faster re-entering all url one by one ...
