### ISSUE TITLE
Add language choice in registration form

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2569]
I want to add a language choice in the register form. 
We need to override the FOSUserBundle form (see http://symfony.com/doc/current/bundles/FOSUserBundle/overriding_forms.html).
We also need to add `setLanguage()` and `getLanguage()` in the `User` entity.

Then, I think we have to override the FOSUserBundle register controller to set the new language.

![capture d ecran 2016-11-10 a 09 43 18](https://cloud.githubusercontent.com/assets/121870/20169881/2dbd09ac-a72a-11e6-902c-027012faa170.png)

**Comment by j0k3r** [comment]
Linked to https://github.com/wallabag/wallabag/issues/1695

**Comment by nicosomb** [comment]
So we can close this duplicate. 👍
