### ISSUE TITLE
error when installing in : php bin/console wallabag:install --env=prod

### ISSUE THREAD

**Issue by michelleunen** [wallabag/wallabag#2572]
Wallabag v2 (all versions) install on a shared web hosting.
I've copied all the files on my web hosting and when I try to execute in a ssh console, as per the documentation, the line: 

`php bin/console wallabag:install --env=prod`

I get the following error:
```
$ php bin/console wallabag:install --env=prodPHP Parse error:  syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /home/clients/62fc79ed58d97c5c3325f89cb65f50d1/web/wllbg/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php on line 419

Parse error: syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /home/clients/62fc79ed58d97c5c3325f89cb65f50d1/web/wllbg/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php on line 419

```
I first thought it was a PHP version error and upgraded to PHP 7 but with no luck. The error is still present. 
Does someone know how to get rid of this ? 
Thanks

**Comment by nicosomb** [comment]
Hello @michelleunen! 

Are you really sure that your PHP version is correct? 
Can you execute `php -v` please?

**Comment by michelleunen** [comment]
Oops, maybe you're right. When I change the PHP version, it doesn't really change. I still get the old one installed by default. I think I've to dig that way.
```
$ php -v
PHP 5.4.45 (cli) (built: Jan 20 2016 11:50:55) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by nicosomb** [comment]
OK, I close this issue. If you have an other problem with wallabag, feel free to open a new one.
