### ISSUE TITLE
Fix layout on password reset confirmation screen

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#2580]
Some classes / html tag are missing.
The rendering isn't pretty.

![image](https://cloud.githubusercontent.com/assets/62333/20260365/9b6fb076-aa59-11e6-9517-39938d37fddd.png)

**Comment by nicosomb** [comment]
#2288 ?

**Comment by j0k3r** [comment]
I've got that screenshot from v2.wallabag.
Isn't updated? :confused:

**Comment by nicosomb** [comment]
![capture d ecran 2016-11-14 a 11 24 06](https://cloud.githubusercontent.com/assets/121870/20261138/e09446a0-aa5c-11e6-8fac-239df48fab19.png)

**Comment by j0k3r** [comment]
Also, the issue isn't related. It was related to an activation email.
Here I'm talking about the reset password screen confirmation.
