### ISSUE TITLE
Documentation : nginx configuration make config.php and make_dev.php accessible

### ISSUE THREAD

**Issue by blankoworld** [wallabag/wallabag#2582]
Hi,

I'm discovering Wallabag, and as I need to install it on Nginx I read these documentations:

  * https://github.com/wallabag/wallabag/blob/master/docs/fr/user/installation.rst
  * https://www.nginx.com/resources/wiki/start/topics/recipes/symfony/

I find that these lines seems to be missing from Nginx configuration from Wallabag official documentation:

```
# return 404 for all other php files not matching the front controller
# this prevents access to other php files you don't want to be accessible.
location ~ \.php$ {
  return 404;
}
```

I think it would be useful to add these lines. What do you think about it?

**Comment by tcitworld** [comment]
Agreed ! Can you open a PR ?

**Comment by blankoworld** [comment]
I can. It will be available today.

**Comment by j0k3r** [comment]
Also: http://symfony.com/doc/current/setup/web_server_configuration.html#nginx
