### ISSUE TITLE
API: result without content

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2585]
When we saving page using API POST request returns all the article in the content field . This POST takes 4s ! It would be useful for speed improvement to have a request parameter like ?nocontent=true to prevent passing article content in the responce?

**Comment by Rurik19** [comment]
Maybe we should separate this objects and make another entry for content? like GET /api/content/id.json  and POST /api/content/id.json. This allows us even to edit content without changing major article data ( in the future... maybe...  )

**Comment by Rurik19** [comment]
And another improvement would be great - initial fetching article content should be done asyncronosly - ie POST returns json wihout content - very fast - while content is fetching by server.

**Comment by j0k3r** [comment]
What about sending a different Accept header to retrieve a light version without the whole `content` field for example?
Sth like GitHub does for specific version or for preview version: https://developer.github.com/v3/media/#request-specific-version

**Comment by j0k3r** [comment]
Fixed in https://github.com/wallabag/wallabag/pull/3960
