### ISSUE TITLE
Dropping existing database when installing wallabag

### ISSUE THREAD

**Issue by michelleunen** [wallabag/wallabag#2586]
The mysql database was already created when I installed Wallabag V2 using this command:
`
$ php bin/console wallabag:install --env=prod
`
In the step 2 of the installation, il detects that the database already exists and ask to reset it. If I answer Y to the question, I got an error message:

```
The command "doctrine:database:drop" generates some errors: 
Could not drop database for connection named /home/clients/62fc79ed58d97c5c3325f89cb65f50d1/web/wllbg/app/../data/db/wallabag.sqlite
An exception occurred while executing 'DROP DATABASE /home/clients/62fc79ed58d97c5c3325f89cb65f50d1/web/wllbg/app/../data/db/wallabag.sqlite':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '/home/clients/62fc79ed58d97c5c3325f89cb65f50d1/web/wllbg/app/../data/db/wallabag' at line 1
```
The workaround was pretty evident for me as the existing database was empty. I just answered N to the question.

**Comment by j0k3r** [comment]
Following your previous issue, are you still using mysql or did you switch to sqlite?

**Comment by michelleunen** [comment]
No, I'm still using mysql. I never made any reference to sqlite in parameters.yml. I had just created an empty database in mysql before launching the install script then answered Y when asked to drop the database and create a new one. That's all I did.

**Comment by j0k3r** [comment]
This is weird...
Never happen to me.
Maybe a cache problem 😕

**Comment by nicosomb** [comment]
I close this issue (3 months ago). If it still happens, please reopen it.
