### ISSUE TITLE
Disabling entity loader causes api errors

### ISSUE THREAD

**Issue by das-schaf** [wallabag/wallabag#2588]
### Issue details

Due to the known php bug i applied `libxml_disable_entity_loader(false);` to the `web/app.php` file (referring to the FAQ).
This produces the following errors when starting the new iOS App: 

`mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/virtual/xxx/var/cache/prod/doctrine/orm/Proxies/__CG__WallabagApiBundleEntityClient.php' (include_path='.:/package/host/localhost/php-7.0.11/lib/php') in /var/www/virtual/xxx/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209`

`mod_fcgid: stderr: PHP Warning:  require(/var/www/virtual/xxx/var/cache/prod/doctrine/orm/Proxies/__CG__WallabagApiBundleEntityClient.php): failed to open stream: No such file or directory in /var/www/virtual/xxx/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209`

Removing the inserted line from `web/app.php` and applying this patch to `vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
` resultings in a working app.

`814c814`
`<         $xmlElement = simplexml_load_file($file);`
`---`
`>       $xmlData = file_get_contents($file); $xmlElement = simplexml_load_string($xmlData);`

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.3
* How did you install wallabag? Via `git clone` or by downloading the package? package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS: centos
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Running the iOS app. Maybe this also applies to the other smartphone apps.

**Comment by j0k3r** [comment]
Did you clear the cache after updating `web/app.php`?

**Comment by das-schaf** [comment]
I cleared the cache using `php bin/console cache:clear -e=prod`. Clearing the cache was my first idea after discovering the errors in the logs.

**Comment by j0k3r** [comment]
We know that applying the fix to the `XmlDriver.php` file is working.
The problem is that you need to re-apply the fix on every release. That's why we found updating the app.php as more durable.
Maybe we should add this to the doc..

**Comment by nicosomb** [comment]
> That's why we found updating the app.php as more durable.

You need to re-apply it in each release too I think.

**Comment by j0k3r** [comment]
Oh yes ... :-(

**Comment by nicosomb** [comment]
We can't do anything about this problem. Sorry for that. 
Feel free to reopen if necessary.
