### ISSUE TITLE
Store the HTTP status code of the articles

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2589]
graby already sends the HTTP status code for each article (thank you @j0k3r). 
We need to store this status in the entry table. 
And we need to have a page to list all the 404 articles. 

It will be useful for massive imports (from third services): maybe some articles are not available and it will be more convenient to retrieve these articles.

**Comment by Kdecherf** [comment]
What about adding a tag for all 40x and 50x errors?

**Comment by nicosomb** [comment]
It can be an idea, but I want to store the status code. Let me this feature, I will do it soon ;-)
