### ISSUE TITLE
Plain Text / Markdown exports

### ISSUE THREAD

**Issue by silvus** [wallabag/wallabag#2591]
### Issue details

The [text export](https://github.com/wallabag/wallabag/blob/7d9abd1ab5425626ce3b0b241f2f50879e109375/src/Wallabag/CoreBundle/Helper/EntriesExport.php#L381) is quite useless when the article contains code samples.
Since all html balise are removed without being replace by lines breaks, each article is a single line.
A `<pre>` who is render fine in the web view is unreadable in the export.

The best solution I can think to keep the actual compatibility of the format (if somebody uses it) is to add a markdown export format.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.2
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: PHP 7.0.8-0ubuntu0.16.04.3
* OS: ubuntu 16.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Make a text export of an article with code sample in `<pre>` balise (exemple article: http://www.gregreda.com/2016/10/16/asynchronous-scraping-with-python/).
Open the text file with an editor (vim) and try to read.

**Comment by tcitworld** [comment]
I think I found no good way to have a good text format from html. Will see how markdown is possible.

**Comment by gwerbin** [comment]
Unless I misunderstand the objective, this is basically what [Pandoc](http://pandoc.org) is good for.

**Comment by Silvus** [comment]
Pandoc can convert an html export to plain text or markdown, yes.

But the point here is more : what is the purpose of the plain text format. In is current state, it is unusable most of the time.

A project like [html2text](https://github.com/soundasleep/html2text) can bring a more integrated solution to Wallbag than Pandoc.
