### ISSUE TITLE
Drop PHP 5.5.x support

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2594]
PHP 5.5 is no more maintained http://php.net/supported-versions.php

Some stats from @seldaek: https://seld.be/notes/php-versions-stats-2016-2-edition PHP 5.5 lost 10 points in 6 months. 
Twig will drop it soon (https://github.com/twigphp/Twig/pull/2229).

**Comment by tcitworld** [comment]
Wasn't this planned for 2017 and 2.4 ?

**Comment by nicosomb** [comment]
2.3 will be released in 2017.

**Comment by j0k3r** [comment]
- [ ] Use PHPUnit ~5.0 instead of 4.0
- [ ] Update composer config platform from `"php": "5.5.9"` to `"php": "5.6.0"`
- [ ] Update composer requirement from `"php": ">=5.5.9",` to `"php": ">=5.6.0",`
