### ISSUE TITLE
Are we still need the Readability import?

### ISSUE THREAD

**Issue by pmichelazzo** [wallabag/wallabag#2595]
Hi guys, this is not an issue, but a question/comment.

Readability shut down the service some weeks ago and, IMHO, we don't need the import option for this service any more.

What do you think?

Best

**Comment by nicosomb** [comment]
Hello @pmichelazzo! 

This importer is still necessary. Readability just closed its service. Maybe some users has their data on their computer and will migrate to wallabag soon. 
But you're right, I think we'll drop it in 2017.

**Comment by tcitworld** [comment]
No need to drop it IMHO as long as it doesn't bothers us...

**Comment by j0k3r** [comment]
It doesn't require too much effort to maintain it (at least 0 effort) so we can keep it.
If people were moving away from Readability they sure exported their articles. So they might be (some day) wanted to test and import their article.

Thanks for your concern anyway :wink:
