### ISSUE TITLE
Help about shortcuts is missing

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#2597]
In 2.2, the documentation inside wallabag is missing about shortcuts (there is nothing in /howto)
So it's really unclear on how we shoud use them and also how can we disabled them.

Also, the display of the _selected_ article is really disturbing me when we arrive on a the default page. It is not clear that the first item is selected and then we can navigate. At first, I though of a bug :confused: 

![image](https://cloud.githubusercontent.com/assets/62333/20424725/af3ce7ba-ad77-11e6-87b9-4f1d806aea50.png)

Following https://github.com/wallabag/wallabag/issues/512

**Comment by tcitworld** [comment]
Any suggestions on how to suggest what's the selected article ? Less shadow ?

**Comment by j0k3r** [comment]
I'll remove the shadow and use a more darken border color.
Maybe we can also add a highlight effect (this is how feedly does) to indicate to the user that the item is selected. Or using a script that make a presentation of the new shortcut.

**Comment by nicosomb** [comment]
Done in #2612.

**Comment by nicosomb** [comment]
I forgot this part, sorry. I just read the title of the issue during my cleanup.
