### ISSUE TITLE
Using shortcut "o" to open an article doesn't work

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#2599]
It generates this error:

> material.min.js:1 Uncaught TypeError: Cannot read property 'click' of undefined(…)

![image](https://cloud.githubusercontent.com/assets/62333/20430993/d9ffad3c-ad97-11e6-825e-5f65dcbfbcb9.png)

npm & grunt up to date
Maybe the css selector is wrong.

**Comment by tcitworld** [comment]
Does `Enter` key works ?

**Comment by j0k3r** [comment]
Yep

**Comment by nicosomb** [comment]
I can't reproduce your bug.

**Comment by j0k3r** [comment]
I still have it on an other computer..

**Comment by j0k3r** [comment]
This happen on a the entries list, not on the entry view itself.
