### ISSUE TITLE
500: Internal Server Error "exception has been thrown during the rendering of a template"

### ISSUE THREAD

**Issue by a8291** [wallabag/wallabag#2602]
### Issue details
New installation:
Right after installation i wasn't able to access starred, archive, tags and got the error below. Indeed i was able to open unread until i added an article. Then it startet to give me th same error.

I can still open settings (and change settings), config, import...

500: Internal Server Error

An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT id_0 FROM (SELECT w0_.id AS id_0, w0_.uuid AS uuid_1, w0_.title AS title_2, w0_.url AS url_3, w0_.is_archived AS is_archived_4, w0_.is_starred AS is_starred_5, w0_.content AS content_6, w0_.created_at AS created_at_7, w0_.updated_at AS updated_at_8, w0_.mimetype AS mimetype_9, w0_.language AS language_10, w0_.reading_time AS reading_time_11, w0_.domain_name AS domain_name_12, w0_.preview_picture AS preview_picture_13, w0_.is_public AS is_public_14, w1_.id AS id_15 FROM `wallabag_entry` w0_ LEFT JOIN `wallabag_user` w1_ ON w0_.user_id = w1_.id WHERE w1_.id = ? AND w0_.is_archived = 0) dctrn_result ORDER BY created_at_7 DESC LIMIT 12 OFFSET 0' with params [1]: SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.created_at_7' which is not in SELECT list; this is incompatible with DISTINCT") in "WallabagCoreBundle:Entry:entries.html.twig" at line 23.

### Environment

* wallabag version (or git revision) that exhibits the issue: 
2.1.3
* How did you install wallabag? Via `git clone` or by downloading the package?
git clone
* Last wallabag version that did not exhibit the issue (if applicable):
first version
* php version:
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
* OS:
ubuntu 16.04
* type of hosting (shared or dedicated):
dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
Mysql

My parameters.yml:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag_database
    database_user: wallabag_user
    database_password: <password>
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    mailer_transport: null
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: <secret>
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: false
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by tcitworld** [comment]
Same error than https://github.com/wallabag/wallabag/issues/2488

Some temporary fixes here : https://stackoverflow.com/questions/35670999/doctrine-querybuilder-order-by-clause-is-not-in-select-list

**Comment by a8291** [comment]
Added 
[mysqld]
sql-mode=""

Doesn't change anything. Same error.
