### ISSUE TITLE
Font changes from 2.1.1 to 2.1.3

### ISSUE THREAD

**Issue by bobberb** [wallabag/wallabag#2610]
To whom it may concern,

The font color of tags overlaying the articles has changed from white on teal to teal on teal, making legibility much more difficult.

I'm awaiting 2.1.4 docker images, apologies if this has been addressed already.

**Comment by j0k3r** [comment]
Can you provide us a screenshot?
Thanks

**Comment by bobberb** [comment]
@j0k3r 

I did I pull for 2.1.4 after the Dockerfile merged, still with the above problems. Linked below:

http://imgur.com/a/wqxL6

**Comment by j0k3r** [comment]
This is strange.
Did you try to clear your browser cache? Or try on an other browser?

**Comment by bobberb** [comment]
What you're seeing is from Chrome win x64, here is a test from my android
phone's Chrome:

http://imgur.com/OrAw6iq

Oddly, this does NOT occur in *shudder* IE 11.

**Comment by nicosomb** [comment]
Can you try to install the 2.2 branch please?

**Comment by bobberb** [comment]
@nicosomb 

I upgraded to 2.1.5 and the issue was resolved. 

(I know this is not the place for this but...) I can only work with docker images on the machine I host wallabag off of, building a container against 2.2 throws the error

"Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Rule.php on line 76
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Rule.php on line 76"

I will await word on if any PHP dependencies were changed before testing 2.2

**Comment by bobberb** [comment]
Like others, I too have the error where the trash/archive buttons are forced downwards:

![2 1 5](https://cloud.githubusercontent.com/assets/1891836/20812124/68c53c44-b7de-11e6-91b6-b127d2ae475c.PNG)

**Comment by nicosomb** [comment]
This last bug is fixed in 2.2. 

About docker, please open a new issue in the good repository ;-) https://github.com/wallabag/docker
