### ISSUE TITLE
[RFC] Change spacing / proportions in the Material Design theme

### ISSUE THREAD

**Issue by eppfel** [wallabag/wallabag#2615]
### Issue details

Now, that the most UI bugs in the Material Theme are fixed :heart_eyes:, I feel the design could take a little cleanup. I fiddled with the CSS on the list view a bit, to give the content more space. I think with the Material look, there is no need for that much spacing. Also, I made small changes in some font-sizes and replaced the blue links, with the reddish...

Please review the screenshots in full resolution. What do you think?

I really like how the contents of each card are wider, although I did not change anything inside them. 

### Environment
* git tag/2.1.3

Before:
![wallabag-top-3col](https://cloud.githubusercontent.com/assets/1899308/20463045/24c1c578-af2b-11e6-9e2d-57e51c1e7cb1.png)
After:
![wallabag-cleanup-top-3col](https://cloud.githubusercontent.com/assets/1899308/20463046/24c1dfea-af2b-11e6-8e8a-2328036f0c5f.png)
Before:
![wallabag-top-4col](https://cloud.githubusercontent.com/assets/1899308/20463044/24c1bc18-af2b-11e6-8f31-4607afa33d35.png)
After:
![wallabag-cleanup-top-4col](https://cloud.githubusercontent.com/assets/1899308/20463047/24c25c5e-af2b-11e6-9041-35cf2d761555.png)

And the sidebar could use less space, too:
<img width="250" alt="bildschirmfoto 2016-11-20 um 14 28 28" src="https://cloud.githubusercontent.com/assets/1899308/20463161/ead8106c-af2d-11e6-8425-e87ebf7bf80b.png"><img width="227" alt="bildschirmfoto 2016-11-20 um 14 23 47" src="https://cloud.githubusercontent.com/assets/1899308/20463162/ed9f3abe-af2d-11e6-8e1f-6da051952664.png">

If you think, some of these changes are worth it, I'll gladly prepare a pull request.

**Comment by tcitworld** [comment]
- Not fan of the red font color for titles.
- I agree left/right margin around entries card can be reduced.
- The sidebar already has issues with some locales https://github.com/wallabag/wallabag/issues/2475 where the text is longer, so we can't do this right now. Maybe collapse it by default like on the article view can be possible though.

**Comment by nicosomb** [comment]
Not fan too for the red color and be careful with translations for the sidebar, @tcitworld is right.

**Comment by Rurik19** [comment]
Not fan of red color too. And I think space between articles is fine now,  more narrow space makes difficult to visually separate articles from each other - it looks just as a table.

**Comment by eppfel** [comment]
Ok, that's unanimous 😅 
I tried to implement it just for myself, but that materialize.css made it complicated. I just changed the link color to cyan for now, the red is definitely unsuited.
