### ISSUE TITLE
Append custom styles

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/wallabag#2618]
I added some changes to the style of Material (_by appending them directly to the minified stylesheet_) to make reading more confortable for me. But this way adds some burden to the upgrade procedure.

It could be interesting to have a textbox on the user config to save some custom styles to append to the main sheet.

**Comment by tcitworld** [comment]
Since assets (css and js files) are linted, checked and minified with a grunt task, that would require to have this tool installed and being called by php.
Better to integrate your changes inside wallabag. If they're major changes, let's create another theme.

**Comment by j0k3r** [comment]
We don't need to put them in the build using grunt. It might just be plain style written in the html page using `<style type="text/css"></style>`

**Comment by Kdecherf** [comment]
I don't think minification is required for this part.

+1 @j0k3r

**Comment by Kdecherf** [comment]
For the record, here are screenshots

original:
![2016-11-20-162611_1920x1080](https://cloud.githubusercontent.com/assets/226063/20464510/c5145d98-af48-11e6-95ff-c0034c4cb9e1.png)

with changes:
![2016-11-20-162616_1920x1080](https://cloud.githubusercontent.com/assets/226063/20464516/ccbc4164-af48-11e6-86c3-657f82c10ff8.png)

**Comment by tcitworld** [comment]
Okay.

Btw, please PR your changes. :-)

**Comment by nicosomb** [comment]
If necessary, we will do the job for grunt.

**Comment by Kdecherf** [comment]
Related to #1802

**Comment by nicosomb** [comment]
In fact, your issue is a duplicate of #1278, right.

**Comment by Kdecherf** [comment]
Oh indeed. Two duplicates in a row, sorry.
