### ISSUE TITLE
Stable URL for "shared hosting" release packages

### ISSUE THREAD

**Issue by di72nn** [wallabag/wallabag#2619]
It is necessary for some cases to be able to download a specific release package (not just the latest with `http://wllbg.org/latest-v2-package`).
`http://framabag.org/wallabag-release-2.x.x.tar.gz` is fine for now, but it is not guaranteed to be present in the future (as was said on gitter).

Please put the release files somewhere with a stable URL.

// One of the cases in which such URL is required is [wallabag package in AUR](https://aur.archlinux.org/packages/wallabag/), which is currently using `http://framabag.org/wallabag-release-2.x.x.tar.gz`.

**Comment by nicosomb** [comment]
We use static.wallabag.org to store production version for 1.x (http://static.wallabag.org/versions/prod), we can use this subdomain to store our releases. 

ping @tcitworld

**Comment by tcitworld** [comment]
Yeah, let's use this.

**Comment by nicosomb** [comment]
Is that ok? http://static.wallabag.org/releases/

I will add previous releases soon.

**Comment by di72nn** [comment]
Yeah, that seems good. Thanks.

Is this the final version of the URL? I need to know so I can suggest an update to the AUR package.

**Comment by nicosomb** [comment]
Yes it is.
