### ISSUE TITLE
API version returns wrong by API

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2626]
Api call /api/version.json returns previous version number

Check: http://v2.wallabag.org/api/version.json = 2.1.3

**Comment by nicosomb** [comment]
v2.wallabag.org is not updated. It will be done today or tomorrow.

**Comment by Rurik19** [comment]
But my site returns 2.1.3 too after update to 2.1.4. And before it returned 2.1.2.

**Comment by nicosomb** [comment]
Did you clear cache?

**Comment by Rurik19** [comment]
make install says at the end:
>  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.

and yes, I remove it manually to.

**Comment by Rurik19** [comment]
Ok. I understand the case.
I experimented (about #2624) with config.yml before update and while updating this file didn't changed.
