### ISSUE TITLE
[UI Bug] MaterializeUI breaks when resizes

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2628]
When I reduce width of browser, the width of article cards shrinks, and at some moment (card width ~320px) the icons get down and break design: 
![image](https://cloud.githubusercontent.com/assets/1955806/20481207/d4931e7a-b007-11e6-8a42-15bdd598d980.png)

## Check

Just resize your browser's width.

**Comment by tcitworld** [comment]
https://github.com/wallabag/wallabag/pull/2613 should be a fix
