### ISSUE TITLE
"Material design" theme in 1280 x 1024 screen resolution

### ISSUE THREAD

**Issue by prolibre** [wallabag/wallabag#2629]
### Issue details

Problem with icons's positions in "material design"
In resolution 1280 x 1024 with firefox 50 ( reinitialised cache )

En français :  ce problème de positionnement avait disparu (il avait déjà été signalé sous une version précédente) puis vient de réapparaitre dans cette dernière version 2.1.5. J'ai bien entendu vidé les caches ( sur le serveur et sous mes navigateurs ).

Capture d'écran pour exemple : 

![wallabag_215](https://cloud.githubusercontent.com/assets/17174902/20481190/41ddf850-afe6-11e6-8250-2775b28884d1.png)

_Si par contre je clique sur un des articles (pour faire apparaitre les premières lignes) le problème disparait... jusqu'au rechargement de la page._

### Environment

* wallabag version (or git revision) : 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? make update
* Last wallabag version that did not exhibit the issue (if applicable): 2.1.4

**Comment by tcitworld** [comment]
https://github.com/wallabag/wallabag/pull/2613 should fix the issue.
