### ISSUE TITLE
Optional original source

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/wallabag#2634]
There's a interesting plugin for Shaarli named `via`. It lets the user link an optional 'original source' name and url to an entry. If these fields are filled, the entry shows a new "Via {original source}" link.

It could be interesting to have a similar feature in Wallabag: it would let the user link an article to a specific source like a tweet or a post somewhere else.

**Comment by j0k3r** [comment]
Someone already requested that but I can't find the issue.

**Comment by nicosomb** [comment]
https://github.com/wallabag/wallabag/issues/2106 ?

**Comment by j0k3r** [comment]
Yep!
