### ISSUE TITLE
Can't update from 2.1.1 to 2.1.5

### ISSUE THREAD

**Issue by Philppe** [wallabag/wallabag#2639]
### Issue details

I am in 2.1.1 release and I want to update to 2.1.5.
I did "make update" in the wallabag folder and I get the following error : 
"make: *** No rule to make target 'update'. Arrêt."

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.1
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6
* OS: Debian jessie
* type of hosting (shared or dedicated): self-hosting
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by nicosomb** [comment]
Hello.

This problem is because our makefile didn't exist in 2.1.1 and our documentation is too recent :/

You need to execute these commands:

```
rm -rf var/cache/*
git fetch origin
git fetch --tags
git checkout 2.1.5 --force
SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
php bin/console cache:clear --env=prod
``` 

Tell me if it's OK.

**Comment by Philppe** [comment]
Hello,

I did like you said and the upgrade worked well.
Now, I can see a makefile in the wallabag-2.1.5 folder so I suppose the upgrade in 2.1.6 will work with the command in the documentation ;-)

Thanks for your help and for your work.
