### ISSUE TITLE
Homepage at wallbag Vedio doesnot streaming.

### ISSUE THREAD

**Issue by jsroyal** [wallabag/wallabag#2645]
## Issue details
I just landed here and found some intersting about wallbag but some issue with streaming  video play.
Could put on youtube and it more faster I think so. :)

**Comment by j0k3r** [comment]
Are you taking about the video from https://www.wallabag.org/?

**Comment by jsroyal** [comment]
Yeah @j0k3r I could not  see video and in does not streaming.

**Comment by jsroyal** [comment]
![screenshot from 2016-11-27 00 15 51](https://cloud.githubusercontent.com/assets/10773353/20642512/c9d99936-b436-11e6-8c32-43dfec400211.png)

**Comment by tcitworld** [comment]
Isn't this an adblock issue ?

**Comment by nicosomb** [comment]
The website has changed. And even with adblock, the video is well displayed. I think we can close.
