### ISSUE TITLE
Improvement of the Wallabag UX on mobile

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#2647]
### Issue details

When Wallabag is used from a mobile phone and through a web browser, the UX has a serious issue:

Once you've got to the end of an article you've just read, you can't mark it as "read" easily. To do that, you've to go back to the top of the page and then you can tap on the "check" button. This doesn't appear on a wide screen because in such case, the toolbar is located on the left of the screen. As a result, the "check" button is always accessible.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.x
* How did you install wallabag? Docker
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS: 
* type of hosting (shared or dedicated): 
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Use Wallabag from a mobile web browser.

**Comment by nicosomb** [comment]
> If you've marked an article as read, wallabag should redirect you to the list of articles, something it doesn't do.

We now have https://github.com/wallabag/wallabag/pull/2547 for that :)

**Comment by romu70** [comment]
Oups sorry, I change my issue.

**Comment by tcitworld** [comment]
So I guess you would rather have the actionbar on bottom too. Or should it be fixed at the top of the screen (this takes some space).

**Comment by nicosomb** [comment]
Or a button to go back to the top of the page?

**Comment by romu70** [comment]
Guess that if you could put a button to go to the top, you can put a button to "check", right? I would make the UX the most simple as possible, so yes, a controls bar which can always stay at the bottom of the screen would be great.

**Comment by tcitworld** [comment]
I think @nicosomb referred to [this kind](http://materializecss.com/buttons.html) of floating button at bottom right, not a full control bar on the bottom.

**Comment by romu70** [comment]
would be great!

**Comment by romu70** [comment]
What would be the best role for such a button? I mean: is there any real need to go back to the top of the page? 

Could we think fo having such floating buttons which, when pressed, would open a small list of actions? Exactly the same thing when click on the + button in Google Inbox.

**Comment by nicosomb** [comment]
Like the "Horizontal FAB" here http://materializecss.com/buttons.html

**Comment by romu70** [comment]
Exactly!

**Comment by nicosomb** [comment]
@romu70 https://github.com/wallabag/wallabag/pull/2670 :)

**Comment by romu70** [comment]
Cool!! Thanks a lot guys.

**Comment by nicofrand** [comment]
I think this can be closed. @nicosomb ?

**Comment by nicosomb** [comment]
:+1:
