### ISSUE TITLE
Rendering issue on UXMatters

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#2648]
### Issue details

This article on UXMatters raises a rendering problem on Wallabag: titles are far to big!! http://www.uxmatters.com/mt/archives/2016/09/the-agile-manifesto-for-designers.php

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1x
* How did you install wallabag? Via `git clone` or by downloading the package? Docker
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS: 
* type of hosting (shared or dedicated): Docker
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

**Comment by j0k3r** [comment]
What should we read on that article? I can't find a reference to wallabag, where it is?
Can you TL;DR what we have to fix?

**Comment by tcitworld** [comment]
Or provide a screenshot.

**Comment by romu70** [comment]
Some screenshots. One from UXMatters.com, the other from this link: http://blog.greenpeace.fr/news/asphyxie-par-le-nucleaire-le-groupe-edf-dans-la-tourmente

Same issue with way tooooooo big font rendering!

![fichier 25-11-2016 09 44 27](https://cloud.githubusercontent.com/assets/1898319/20619325/3b7ea890-b2f4-11e6-90b1-7e9114a0e7df.png)
![fichier 25-11-2016 09 44 38](https://cloud.githubusercontent.com/assets/1898319/20619324/3b7e9896-b2f4-11e6-9930-6013ad6158af.png)

**Comment by j0k3r** [comment]
Maybe we should override the h2 style for a content so the rendering is smaller.

**Comment by tcitworld** [comment]
I think https://github.com/wallabag/wallabag/pull/2622 takes care of it.

**Comment by j0k3r** [comment]
Right!

**Comment by Kdecherf** [comment]
Here is a screenshot with the changes from #2622:

![2016-11-25-135531_1920x2160](https://cloud.githubusercontent.com/assets/226063/20626129/e544489e-b317-11e6-8692-56e1945cfb98.png)

I can still reduce the size of h1/h2 if needed.

**Comment by tcitworld** [comment]
Well, it's not our fault if news site make endless titles...

**Comment by nicosomb** [comment]
I think that the problem is in the greenpeace website: a `<h2>` for an introduction?!

**Comment by Kdecherf** [comment]
Another solution would be to replace h1/h2 with something else using site configs

**Comment by tcitworld** [comment]
Another solution would be to email them and ask them to learn html standards.

**Comment by nicosomb** [comment]
:trollface: 💥

**Comment by j0k3r** [comment]
It's not our fault.
So we don't care.
And if it's **really** a problem, people can still fix it using siteconfig.

**Comment by romu70** [comment]
I agree the GreenPeace site is dumb. @Kdecherf would be nice to see the change with the UXMatters article.

**Comment by Kdecherf** [comment]
Here is a screenshot of UXMatters article with the UI change:
![2016-11-26-000259_1920x2160](https://cloud.githubusercontent.com/assets/226063/20636354/da9b39b2-b36b-11e6-8918-5f615fee0a25.png)

**Comment by romu70** [comment]
Much better!! Personaly, to keep a more "pure" reading experience, I would also make the row with time to read, date, etc hideable. But that's beyond this ticket I think.
