### ISSUE TITLE
Can't add a new entry on a mobile phone in portrait mode

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#2653]
### Issue details

I always read my articles on my mobile. My workflow with Pocket and Wallabag is:
- add articles from my laptops (personal and profesionnal) most of the times
- then read the article from my mobile

On my iPhone, when I open an article on Firefox, I can't check once read because the check button is far on the right of the toolbar. I've to switch to portrait mode and then, I can check. 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.x
* How did you install wallabag? Via `git clone` or by downloading the package? Docker
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Open an article from a small screen mobile phone.

**Comment by tcitworld** [comment]
Could you provide a screenshot.

**Comment by romu70** [comment]
Strange, I can't reproduce it. I've seen it this morning. I close it and if it happens again, I'll reopen it.

**Comment by romu70** [comment]
Just faced the problem. Here are 2 screenshots, portrait and landscape. Firefox for iOS on a small iPhone.

![fichier 07-12-2016 10 01 40](https://cloud.githubusercontent.com/assets/1898319/20961428/3f6b2bf2-bc65-11e6-8e6e-be602467e642.png)
![fichier 07-12-2016 10 01 56](https://cloud.githubusercontent.com/assets/1898319/20961431/41868b52-bc65-11e6-8100-2a4cf98040c5.png)

**Comment by tcitworld** [comment]
Please tell us your screen resolution in both cases (don't forget to refresh) : http://www.whatismyscreenresolution.com/

**Comment by romu70** [comment]
Portrait : 320*568
Says the same on landscape.

Notice the title of the issue is wrong, it's not about marking an article as read, but being able to add a new article.

**Comment by nicosomb** [comment]
It seems that this issue is fixed.
