### ISSUE TITLE
FOSUserBundle alpha4 compatibility

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#2656]
Latest commits in FOSUserBundle have removed [a number of methods and properties](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Upgrade.md#200-alpha3-to-200-alpha4), so the tests don't pass anymore.

**Comment by tcitworld** [comment]
Should we remove the `locked` feature ?

**Comment by j0k3r** [comment]
We can removed it

**Comment by nicosomb** [comment]
Fixed in #2663.
