### ISSUE TITLE
Append cli command to test smtp configuration

### ISSUE THREAD

**Issue by harobed** [wallabag/wallabag#2657]
Append cli command to test smtp configuration.

**Comment by j0k3r** [comment]
Could you please give us more detail?

**Comment by harobed** [comment]
Example with `docker-compose`:

```
$ docker-compose exec wallabag /var/www/wallabag/bin/console swiftmailer:email:send -e prod --from contact@example.com --to contact@gmail.com --subject test --body test
[2016-12-05 17:06:41] app.ERROR: Exception occurred while flushing email queue: Connection could not be established with host smtp [Connection refused #111]
```

Here I can see that Wallabag smtp configure is bad configured.

**Comment by nicosomb** [comment]
Just to be sure, you want to add a check if your SMTP is well configured? 

As for the database parameters, if you give wrong parameters to wallabag, it won't work. 
As the administrator of your wallabag instance, you need to set good parameters.

**Comment by harobed** [comment]
> Just to be sure, you want to add a check if your SMTP is well configured?

Yes. Document this command.

I would like something like:

```
$ docker-compose exec wallabag test-smtp
```

What do you think about that?
