### ISSUE TITLE
Import process discards title, content, of entries that are not available anymore (eg. 404)

### ISSUE THREAD

**Issue by jcharaoui** [wallabag/wallabag#2658]
When importing an entry whose content is unavailable at the original URL, the fetchContent method overwrites the original title to "No title found". It should only update the title if fetching was successful, otherwise, the entry should be imported with the original URL.

**Comment by jcharaoui** [comment]
[AbstractImport.php](https://github.com/wallabag/wallabag/blob/8c3c69fb9c8df3f78fe41ecc4349e11f5d5affdc/src/Wallabag/ImportBundle/Import/AbstractImport.php#L90) relies on an exception being thrown in case of an error during fetching, but Graby doesn't throw an exception in that case (see [README](https://github.com/j0k3r/graby/blob/master/README.md)). Anyway it doesn't even matter because `$entry` is passed by reference, so this function always returns whatever `fetchContent()` sends back.

**Comment by jcharaoui** [comment]
The same thing happens to the entry body, when importing for Wallabag v1 or v2. If the content isn't available anymore at the given URL, the import process will simply discard the title and content. This should not happen. I would say this is a potential data loss bug.

**Comment by j0k3r** [comment]
Can't this be the same as https://github.com/wallabag/wallabag/issues/2101?

**Comment by jcharaoui** [comment]
@j0k3r Indeed, it's the same problem.
