### ISSUE TITLE
MySQL exception during adding specific links

### ISSUE THREAD

**Issue by akovalyov** [wallabag/wallabag#2660]
N.B. This error might be reproducible only on this particular link, but I am not sure that it is  about site configuration. 

### Issue details

Exception ['SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x92\\x9A b...' for column 'content' at row 1'](https://gist.github.com/akovalyov/ca1e6e04327b55816f21c5bce7f84b4f) occurs when I add [this link](https://medium.freecodecamp.com/tor-signal-and-beyond-a-law-abiding-citizens-guide-to-privacy-1a593f2104c3#.betpezr4t) to Wallabag. Since it is Medium platform, it might be related, but other Medium articles are saved correctly. 

### Environment

* wallabag version (or git revision) that exhibits the issue: latest (2.1.5 at the time of writing)
* How did you install wallabag? Via `git clone` or by downloading the package? (git clone)
* Last wallabag version that did not exhibit the issue (if applicable): ~
* php version: 7.0
* OS: Ubuntu Xenial
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL 5.7

### Steps to reproduce/test case

Add link https://medium.freecodecamp.com/tor-signal-and-beyond-a-law-abiding-citizens-guide-to-privacy-1a593f2104c3#.betpezr4t via browser extension or UI.

**Comment by nicosomb** [comment]
Hello, 

It's fixed in 2.2, which will be released in next weeks (see https://github.com/wallabag/wallabag/issues/2057).
