### ISSUE TITLE
Improving sharing to Shaarli - include tags

### ISSUE THREAD

**Issue by lapineige** [wallabag/wallabag#2664]
Hi wallabag team :)

I'm using Wallabag as a read-it-later service, with quite a lot of automated tagging (which is quite handy :smile:) and Shaarli as a bookmarking software.
I'd like to keep my tags while sharing to Shaarli (it would be a lot more convenient than having to set them again).
I've asked on Shaarli repository if it's currently supported (see: https://github.com/shaarli/Shaarli/issues/698): it is, without an API right now, but by passing parameters in the URL. Just like that: `?post=[url]&title=[title]&tags=[tags]`
As Wallabag currently share to Shaarli using an URL with parameters, I imagine this could be adapted to share the tags too.

Note: I tested with a very old Shaarli version, it doesn't work, but it raise no issue, so I think it won't break any compatibility.

As always, I'd be happy to test this feature if you implement it :)
Cheers :)

**Comment by lapineige** [comment]
Up :)

I just saw you marked this as an Easy bug @j0k3r, could you explain which part should be changed in order to implement this feature ?
I'm not a big PHP dev, but maybe I can make a small PR ... ;)

**Comment by j0k3r** [comment]
Shaarli url are display in both template: [here for baggy](https://github.com/wallabag/wallabag/blob/e39aec3e38144f1a2ddb0027ec724e3dfd6f53f1/src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig#L32) and [here for material](https://github.com/wallabag/wallabag/blob/2db9142bfc3e34c1f79f3aabf5b302c3a487b3e1/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig#L128).

In fact, it won't require PHP development but Twig skills. You need to loop on all tags for the `entry` to add them in the url.

**Comment by lapineige** [comment]
When you say Twig, you mean [this one](http://twig.sensiolabs.org/) ?
I discovered something today ^^ Thanks :)

I'll take a look and see if I can understand how to do it :)
(first on material theme, as I'm using it)

**Comment by nicosomb** [comment]
Yes, it's this one.

**Comment by lapineige** [comment]
Ok I found how to share the tags with shaarli using Twig syntax, but I don't know how to get the list of tags -
and then what's the format - so I can convert it to shaarli's format (tags separated by comma).
Is it just entry.tags ? How can I test that ?
Thanks, happy holidays :)

**Comment by nicosomb** [comment]
You already have the tag lists here : https://github.com/wallabag/wallabag/blob/2db9142bfc3e34c1f79f3aabf5b302c3a487b3e1/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig#L240

**Comment by lapineige** [comment]
Ok thanks for the information (that's strange, I made a research for the keyword tag, I missed it :/).

I'm actually willing to try my changes, but when I change those files on my wallabag installation, nothing change.
Does wallabag use them as a kind of source files that are parsed one time and for each query ?

**Comment by nicosomb** [comment]
Try to clear your cache (`bin/console cache:clear -e=prod`). 
Don't forget to edit the good template file too (the default one is Material).

**Comment by lapineige** [comment]
> Don't forget to edit the good template file too (the default one is Material).
 
I checked it, no mistake here.

> Try to clear your cache (bin/console cache:clear -e=prod).

Noob question of the day: where do I run this command ?

**Comment by nicosomb** [comment]
in your wallabag folder. You have a `bin` folder in your wallabag folder.

**Comment by lapineige** [comment]
Oh ok ^^

I did it, here's the command result: 
> // Clearing the cache for the prod environment with debug                            
 // false                                                                             
                                                                                     
> [OK] Cache for the "prod" environment (debug=false) was successfully cleared.

But now my wallabag page is just... empty... (the web console is empty)

**Comment by nicosomb** [comment]
maybe you cleared your cache with the root user: so the cache files (in var/cache) may be created with root permissions and apache (or nginx) can't access to it.

**Comment by lapineige** [comment]
You're right, I did it with root user. Thanks

**Comment by lapineige** [comment]
Solved by PR https://github.com/wallabag/wallabag/pull/2725
Thanks a lot wallabag team :)
