### ISSUE TITLE
Material theme: Allow tags editing on mobile

### ISSUE THREAD

**Issue by MatElGran** [wallabag/wallabag#2668]
### Issue details
On mobile browsers (Android chrome and firefox, IPad safari), when using material theme, article detail sidebar doesn't have full functionality, even when forcing desktop version of the page. Only share, delete, download and problems links are available. Therefore, it is not possible to edit tags form a mobile browser when using material.

I don't see a rationale here, but maybe there is one, and I would be glad to learn about it 

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.1.3**
* How did you install wallabag? `git clone`
* php version: 7
* OS: **ubuntu 14.04**
* type of hosting (shared or dedicated): **shared**
* which storage system you choose at install: **PostgreSQL**

### Steps to reproduce/test case
Open a fetched article in a mobile browser, either in desktop or mobile version, and open the sidebar

**Comment by nicosomb** [comment]
Hello @MatElGran! 

I think your issue is a duplicate of https://github.com/wallabag/wallabag/pull/2553 and it'll be fixed in 2.2 (available in next weeks).

**Comment by MatElGran** [comment]
Oh, my bad, didn't think about going through merged PRs, only open issues. 
Will make sure to think about it next time. Thx
