### ISSUE TITLE
Tagging Rules Allowed to be created that break Bagging.

### ISSUE THREAD

**Issue by chalbersma** [wallabag/wallabag#2678]
### Issue details

Attempted to create a tagging rule: 
Match : `title matches "NSL" or title matches "NSA" or title matches "Snowden" or domainName is "eff.org" or content matches "Hemisphere" or content matches "Black Chamber" or content matches "Project SHAMROCK" or content matches "ECHELON" or content matches "Five Eyes" or content matches "USA Freedom Act" or content matches "Information Awareness Office" or content matches "CALEA"`
Tags: Surveillance, Domestic Spying, 4th

Interface allows this rule to be created, however after adding rule you will get  a 500 error:

> 500: Internal Server Error
> 
> Parse error: syntax error, unexpected 'Five' (T_STRING), expecting ']'

When removing the rule bagging starts to work again.

Based on what happens when I attempt to edit the rule I think the matching rules are limited to 256 characters. The interface and storage should either limit rules to 256 characters or change to a model that doesn't require character limits.

### Environment

* wallabag version (or git revision) that exhibits the issue: `2.1.5`
* How did you install wallabag? Via `git clone` or by downloading the package?  Self Hosted, Git clone followed instructions on site.
* Last wallabag version that did not exhibit the issue (if applicable): N/A (None tested)
* php version: 7.0.13
* OS:  CentOS 7
* type of hosting (shared or dedicated): VPS (Shared)
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB 10.1

### Steps to reproduce/test case

Create the rule noted above (or I think any rule longer than 256 characters) and attempt to bag articles. You should receive 500 errors.

**Comment by chalbersma** [comment]
# Workaround

Create two sub 256 char rules.

**Comment by j0k3r** [comment]
What a long rules ! 🙂 
Thanks for noticing that.
