### ISSUE TITLE
No validation mail received on wallabag.it

### ISSUE THREAD

**Issue by Gregoire-M** [wallabag/wallabag#2681]
### Issue details

I've just created an account on wallabag.it, I'm on the "/register/check-email" page with the following message:

> An email has been sent to g@marchal.email. It contains an activation link you must click to activate your account.

But I haven't received any email, even in spam folder.

### Environment

wallabag.it

### Steps to reproduce/test case

You can reproduce by subscribing with `g+whatever@marchal.email`, I should receive an email :)

**Comment by j0k3r** [comment]
Regarding problem with wallabag.it, make sure to use its own support instead of issue here 🙂 
https://wallabagit.freshdesk.com/support/tickets/new

**Comment by Gregoire-M** [comment]
Oops, done!
