### ISSUE TITLE
v2.wallabag and wallabag.it

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#2684]
Hi !
I see than wallabag.it is lanched. Congrulation ! But, quid of V2.wallabag.org ? I have an account, i must migrate ?

regards,
qwerty

**Comment by tcitworld** [comment]
Yes. v2.wallabag.org was intended as a demonstration and testing server and will be closed at some point. Framabag will of course continue to exist.

**Comment by qwertygc** [comment]
We have the last version in framabag ?

Le 5 décembre 2016 19:22:25 CET, Thomas Citharel <notifications@github.com> a écrit :
>Yes. v2.wallabag.org was intended as a demonstration and testing server
>and will be closed at some point. Framabag will of course continue to
>exist.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wallabag/wallabag/issues/2684#issuecomment-264933387

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tcitworld** [comment]
No. Blame me.

**Comment by qwertygc** [comment]
It's planned ?

**Comment by tcitworld** [comment]
Maybe as a Christmas or new year's eve present.

**Comment by qwertygc** [comment]
Oh great ! I'am curious to see how you migrate. Script?

**Comment by tcitworld** [comment]
Yeah, python scripts. I will probably publish them once it's done.

**Comment by nicosomb** [comment]
Now that all is clear, can I close or do you want to keep it opened?
