### ISSUE TITLE
Can't retrieve content for uebermedien.de

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#2692]
### Issue details

If I try to fetch an article from uebermedien.de, wallabag doesn't fetch the content. However it works fine on http://f43.me/feed/test, so it seems to be a wallabag problem.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* type of hosting (shared or dedicated): wallabag.it

### Steps to reproduce/test case

Example URLs:

- http://uebermedien.de/10293/der-hass-ist-nicht-neu-fuer-uns-nicht/
- http://uebermedien.de/7777/die-bla-frage/

**Comment by jlnostr** [comment]
BTW, this happens for some other sites, too. Below are more example links with the same problem:

- http://www.windowscentral.com/enter-win-brand-new-surface-pro-4-windows-central
- http://www.mopo.de/hamburg/kolumnen/nach-126-mopo-kolumnen--der-kaept-n-geht-von-bord-24864976
- http://www.theverge.com/2016/11/29/13776894/pewdiepie-quit-casey-neistat-vlog-youtube-vloggers (for TheVerge the preview image is fetched, but wallabag didn't fail this time, but the content is empty anyway)

**Comment by nclsHart** [comment]
All of this articles are properly fetched in latest version.
