### ISSUE TITLE
full text search

### ISSUE THREAD

**Issue by scoopex** [wallabag/wallabag#2700]
The possibility to filter articles does currently not provide a fulltext search feature. It should be possible to search in the body, headlines and URLs of the archived articles

Probably it is possible to write a facade for the fulltext search possibilities of the underlying databases:
- http://dev.mysql.com/doc/refman/5.7/en/fulltext-search.html
- https://www.postgresql.org/docs/8.3/static/textsearch.html
- Fallback if database does not support fulltext search

Another option would be the usage of a external search index like Xapian (https://xapian.org/docs/bindings/php/)

Thank you for developing wallabag, i really love it.

**Comment by nicosomb** [comment]
Hello @scoopex! 

Search engine is already available, it will be available in 2.2, released in next days.

**Comment by Vertux** [comment]
@nicosomb 
That is cool, I desperately missing this feature for so long - thanks for the info.

**Comment by heapxor** [comment]
@nicosomb is there some documentation regarding that? I cant see anything related to the full-text search inside wallbag.
thanks
