### ISSUE TITLE
Failure to parse archive.org versions of page

### ISSUE THREAD

**Issue by cdn** [wallabag/wallabag#2703]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Working manually through 2012— entries in my Readability list I have found dead links, so have attempted to wallabag the archive.org equivalents where available; such pages do parse reasonably well via http://f43.me/feed/test

e.g. http://web.archive.org/web/20120620202149/http://www.markboulton.co.uk/journal/comments/gridset-and-compound-grids

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? git clone around 2016–11–30
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.0 (fpm with nginx)
* OS: Ubuntu Linux 16.04
* type of hosting (shared or dedicated): Raspberry Pi B 3
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Attempt to add an archive.org URL as an entry to Wallabag

**Comment by cdn** [comment]
Result from sqlite3 prompt:

sqlite> select * from wallabag_entry where id = 590;
590|1||No title found|http://web.archive.org/web/20120626071159/http://howto.wired.com/wiki/Proxy_Your_Way_to_Online_Anonymity|0|0|wallabag can't retrieve contents for this article. Please <a href="http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that">troubleshoot this issue</a>.
|2016-12-14 10:31:18|2016-12-14 10:31:18|text/html||0|web.archive.org||

**Comment by nclsHart** [comment]
It works fine on latest version.
