### ISSUE TITLE
Empty article after reloading

### ISSUE THREAD

**Issue by Philppe** [wallabag/wallabag#2704]
### Issue details

If you reload an article and if the page no longer exist, the article become empty in wallabag.
So, when you reloading an article, wallabag should check if the page exist and reloading if only the page exist yet.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated): self-hosting
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

**Comment by nicosomb** [comment]
Hello @Philppe!

This bug is fixed (see https://github.com/wallabag/wallabag/issues/2101) in next version, wallabag 2.2, available in next days/weeks.

**Comment by Philppe** [comment]
Ho great ! I didn't see it despite my research. Nice job !!

Thanks
