### ISSUE TITLE
gzuncompress error while importing from Pocket API or Instapaper csv

### ISSUE THREAD

**Issue by itnAAnti** [wallabag/wallabag#2705]
### Issue details

When importing from Pocket via the API, or importing from an Instapaper csv file, I receive the error: **500: Internal Server Error Attempted to call function "gzuncompress" from the global namespace.**

### Environment
* Official Docker image, version 2.1.5
* Docker 1.11.2
* Running on an x86_64 Synology NAS (Linux NAS 3.10.77 #8451)
* PHP 5.6
* PostgreSQL

### Steps to reproduce/test case

1. Download / run latest Docker image, currently version 2.1.5
2. Download, link, run latest PostgreSQL Docker image, currently 9.6.1
3. Start both, verify Wallabag configured the DB ok and is running correctly
3. Get Pocket consumer key on your account and configure in Wallabag
4. Import from Pocket

**Comment by nicosomb** [comment]
This issue was moved to wallabag/docker#40
