### ISSUE TITLE
[Firefox Extension] Support multiprocess

### ISSUE THREAD

**Issue by dest4131** [wallabag/wallabag#2717]
In Firefox 50.1.0 in Linux (Debian/LMDE2), the Mozilla "Add-on Compatibility Reporter" extension says that Wallabag is not compatible with multiprocess (aka "e10s"). Wallabag therefore prevents Firefox from using multiprocess improvements when enabled.
Note: on my system multiprocess is currently off by default, but will be on by default in the future.

**Comment by j0k3r** [comment]
Shouldn't this be moved to https://github.com/wallabag/firefox-ext-v2? :thinking:

**Comment by dest4131** [comment]
It should, and I see that the issue is already submitted there. Sorry about that
