### ISSUE TITLE
render of actions on tablet 10"

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2718]
![tmp_9936-screenshot_2016-12-22-17-58-05449884721](https://cloud.githubusercontent.com/assets/208212/21433510/5d487d0c-c870-11e6-9908-326e57423280.png)

### Issue details

The  render of the actions breaks the display of each card:/

### Environment

* wallabag version (or git revision) that exhibits the issue:2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package?clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:7
* OS:debian 8.6
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

**Comment by tcitworld** [comment]
Again, this should be fixed in 2.2.
