### ISSUE TITLE
Can't install - Class 'PDO' not found in DriverManager.php

### ISSUE THREAD

**Issue by PhuriousGeorge** [wallabag/wallabag#2726]
### Issue details

No matter what I've tried, I cannot get Wallabag installed. Always seems to come back to:
From apache2 error log:

> Class 'PDO' not found in /var/www/html/<snip>/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php on line 172

### Environment

**wallabag version (or git revision) that exhibits the issue:
How did you install wallabag? Via `git clone` or by downloading the package?**
Installed via `wget http://wllbg.org/latest-v2-package && tar xvf latest-v2-package`
Changed parameters.yml to `pdo_mysql` and completed configuration
Ran `php bin/console wallabag:install --env=prod`, but only received constant errors that: 

> Database driver "pdo_sqlite" is not installed.

Decided to try a different route and ran `SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist` successfully, now I receive the PDO error listed above in apache2.

**Last wallabag version that did not exhibit the issue (if applicable):**
Somehow had this working previously (????), but had to reinstall my OS

**php version:**
7.0

**OS:**
Ubuntu 14.04

**type of hosting (shared or dedicated):**
Dedicated, but due to other considerations, I'd rather just install in /var/www and with no rewrite.

**which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):**
mysql

**### Steps to reproduce/test case
Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).**

See above 'how did you install'

**Other ranting due to multiple hours at failing**
Dear God, please make this thing easier to install. It's a b*** every time I have to, but I love it when it's working.

**Comment by PhuriousGeorge** [comment]
#2542
#1777
#2497
#2371

It'd be great if wallabag were easier to install.  Seems each time I have to reinstall, I spend hours trying to get it up and running.  This iteration, I've had no luck at all, always ending in the above error every method I've found to install wallabag.

If someone could make wallabag easier to install / manage / deploy, I'll chip a bounty in.

**Comment by j0k3r** [comment]
Can you list your enable modules in PHP (using `php -i`)? Did you install `php-mysql` or `php-sqlite`?

**Comment by PhuriousGeorge** [comment]
That outputs a lot. I tried parsing only what might be valuable

```
BCMath support => enabled
Calendar support => enabled
zend.enable_gc => On => On
ctype functions => enabled
cURL support => enabled
DOM/XML => enabled
HTML Support => enabled
XPath Support => enabled
XPointer Support => enabled
Schema Support => enabled
RelaxNG Support => enabled
EXIF Support => enabled
fileinfo support => enabled
Input Validation and Filtering => enabled
FTP support => enabled
FTPS support => enabled
GD Support => enabled
FreeType Support => enabled
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
PNG Support => enabled
WBMP Support => enabled
XPM Support => enabled
XBM Support => enabled
WebP Support => enabled
GetText Support => enabled
hash support => enabled
MHASH support => Enabled
iconv support => enabled
json support => enabled
libXML streams => enabled
Multibyte Support => enabled
Multibyte (japanese) regex support => enabled

MysqlI Support => enabled
mysqlnd => enabled
Loaded plugins => mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password,auth_plugin_sha256_password
API Extensions => mysqli,pdo_mysql
OpenSSL support => enabled
pcntl support => enabled
PCRE (Perl Compatible Regular Expressions) Support => enabled
PCRE JIT Support => enabled
PDO support => enabled
PDO drivers => mysql
PDO Driver for MySQL => enabled

Phar: PHP Archive support => enabled
Phar-based phar archives => enabled
Tar-based phar archives => enabled
ZIP-based phar archives => enabled
gzip compression => enabled
Native OpenSSL support => enabled
Readline Support => enabled
Reflection => enabled
Session Support => enabled
shmop support => enabled
Simplexml support => enabled
Schema support => enabled
Sockets Support => enabled
SPL support => enabled
Dynamic Library Support => enabled
sysvmsg support => enabled
Tokenizer Support => enabled
WDDX Support => enabled
WDDX Session Serializer => enabled
XML Support => active
XML Namespace Support => active
XMLReader => enabled
XMLWriter => enabled
XSL => enabled
EXSLT => enabled
SHM Cache => Enabled
Zip => enabled
ZLib Support => enabled
```

**Comment by j0k3r** [comment]
Hum ok, so PDO seems to be enable in your CLI config.

So step by step:

1. could you paste your `app/config/parameters.yml`
2. could you put a file like `phpinfo.php` on your localhost and display it with that content: `<?php phpinfo(); ?>`? So we'll see what is enable for the FPM/Apache POV

**Comment by nicosomb** [comment]
Hello @PhuriousGeorge.
FYI, your issue will be closed soon if we won't have any news from you.

**Comment by PhuriousGeorge** [comment]
Unfortunately I've deleted the install as I spent too much time on it and had intended to try again to get you the parameters.yml, but have been busy with other tasks.

I've not changed my php setup since, so here's my phpinfo:
http://pastebin.com/sE27DdyK

**Comment by tcitworld** [comment]
PDO seems activated through CLI but not through web, according to your phpinfo()

**Comment by nicosomb** [comment]
I close this issue. Feel free to reopen it if necessary.
