### ISSUE TITLE
tags hidden on mobile version with Firefox 50

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2727]
### Issue details

![tmp_16996-29 decembre 2016 114743 gmt 0100-1740808816](https://cloud.githubusercontent.com/assets/208212/21542246/c8a08468-cdbc-11e6-97ba-2cfbfbf2f4ba.jpg)

### Environment

* wallabag version (or git revision) that exhibits the issue:2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package?git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:7
* OS:debian 5.8
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by nicosomb** [comment]
Hello @foxmask! 

Maybe we should display them like that, even if we don't have picture preview:

![capture d ecran 2016-12-29 a 11 58 12](https://cloud.githubusercontent.com/assets/121870/21542462/29de4d68-cdbe-11e6-975a-ec07689d283e.png)

**Comment by foxmask** [comment]
I thought of that, yes. I hope WE didnt meet difficuties with the link of the title that will be under the tag(s)
