### ISSUE TITLE
Automatically send new article by email

### ISSUE THREAD

**Issue by rParslow** [wallabag/wallabag#2738]
Today I have to use IFTTT to receive new articles by mail

Request is to have the possibility to have the same feature within Wallabag.  
By adding an option in https://app.wallabag.it/config "push new article by mail" or "my account" article to be mailed to user email

Nice to have could be to filter by tags

This feature might handle also #770 Add possibility to send articles to Kindle 
In that case the destination email should be a parameter and the article send in mobi format.

**Comment by nicosomb** [comment]
Duplicate of #239
