### ISSUE TITLE
register

### ISSUE THREAD

**Issue by kayloehmann** [wallabag/wallabag#2740]
### Issue details

I get this error randomly:

:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Core Error: Directive 'register_globals' is no longer available in PHP in Unknown:0
Stack trace:
#0 {main}

Next LogicException: Request stack is empty in /home/www/wallabagv2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:99
Stack trace:
#0 [internal function]: Symfony\Component\HttpKernel\HttpKernel->terminateWithException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#1 /home/www/wallabagv2/var/cache/prod/classes.php(2383): call_user_func(Array, Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 /home/www/wallabagv2/var/cache/prod/classes.php(2426): Symfony\Component\Debug\ErrorHandler->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 [internal function]: Symfony\Component\Debug\ErrorHandler::handleFatalError()
#4 {main}
  thrown in 

### Environment

* wallabag version (or git revision) that exhibits the issue:
2.1.5

* How did you install wallabag? Via `git clone` or by downloading the package?
Package Download

* Last wallabag version that did not exhibit the issue (if applicable):
-

* php version:
7.0.13

* OS:
Mac OS Sierra / Firefox

* type of hosting (shared or dedicated):
Shared Hosting

* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
SQLite

### Steps to reproduce/test case
Random occurance!

**Comment by kayloehmann** [comment]
I do not have any register_globals entries in my php.ini

**Comment by j0k3r** [comment]
Which `php.ini` did you check?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
