### ISSUE TITLE
ePub: Titles missing in article view

### ISSUE THREAD

**Issue by mbelow** [wallabag/wallabag#2741]
I am using wallabag via the framabag.org service, and I want to export the articles to ePub so that I can read them on a PocketBook Touch HD (6" eBook reader).

The articles are shown by title in the table of contents. But the individual articles start without title, each time. If I open the ePub in calibre, it is also missing the titles between articles, while the ToC is fine. This makes navigation between articles harder. If I read a number of articles in a row, the title helps a lot to see right away that a new article starts here and what it's about.

(In case my reader & calibre are missing a nifty epub3 feature, please consider supporting older readers in this basic funtionality.)

**Comment by tcitworld** [comment]
Unfortunately we don't support wallabag 1.x anymore, which is the version of framabag.org.
It will migrate at some point, but in the meantime please consider https://wallabag.it or hosting your own instance of wallabag.
