### ISSUE TITLE
Unable to add a tag at all

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2743]
### Issue details

after having saved a webpage, unable to add a tag just on THAT article

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 7
* OS: debian 5.8
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

### Steps to reproduce/test case

add http://www.infoconso-multimedia.fr/blocage/311-bloquer-internetplus-smsplus/
and try to add a tag. 
there is a big big crossair in place a the tag field

**Comment by j0k3r** [comment]
Wow looks like the article broken sth.

**Comment by j0k3r** [comment]
Regarding the issue it's a style in the article which breaks the page.
It should be fixed when these issues will be fixed https://github.com/wallabag/wallabag/issues/3182 & https://github.com/wallabag/wallabag/issues/3134
