### ISSUE TITLE
direction of arrow in back button in article view

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2745]
### Issue details

We have a back to the article list button in our article view side menu. This button is in the opposite direction of the browsers back button and this is, even after looking often at this button, somehow confusing.

I suggest changing it in the opposite direction.

current status is shown in the following screenshot:

![2017-01-12-170835_4480x1440_scrot](https://cloud.githubusercontent.com/assets/97055/21897443/da7bf450-d8e9-11e6-8dc2-ba66e68ece21.png)

What do you think about my proposal?

**Comment by nicosomb** [comment]
Fixed by @Kdecherf in https://github.com/wallabag/wallabag/pull/3513.
