### ISSUE TITLE
Cannot export articles with a given tag containing special characters

### ISSUE THREAD

**Issue by rgugliel** [wallabag/wallabag#2746]
### Issue details

Cannot export articles with a given tag containing special characters

Error:

    Fatal error
    : Call to a member function getId() on null in
    /home/rgugliel/www-dev/user/wallabag/src/Wallabag/CoreBundle/Controller/ExportController.php
    on line 66

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.3
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6
* OS: Ubuntu 14.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

* Click on "Tags"
* Chose a tag, e.g. "c++"
* Click export and chose a format (eg Mobi but issue exists with other formats)

If I don't choose a tag, or if the tag contains only standard characters, the export works just fine.

**Comment by j0k3r** [comment]
Looks like we aren't able to find the tag.
What's the tag name?

**Comment by rgugliel** [comment]
Ah! I'm disappointed I didn't think about that!

The export succeed if that tag has only non-special characters and fails for "c++"

**Comment by nicosomb** [comment]
Fixed in 2.2 (https://github.com/wallabag/wallabag/pull/2416/commits/c8de7ab94cb2d8880205c450ebf52d225991df6e)
