### ISSUE TITLE
Unable to login after update

### ISSUE THREAD

**Issue by giovi321** [wallabag/wallabag#2747]
### Issue details

I am unable to login with my credentials after the update.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 2.0.8
* php version: 5.6.27-0+deb8u1
* OS: Debian 8
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Upgrade from 2.0.8 to 2.1.5

**Comment by nicosomb** [comment]
Hello @giovi321! 
Can you have a look into your logs folder please (`var/logs/` in your wallabag installation)? 
I think your database is not up to date. 
Did you read this documentation http://doc.wallabag.org/en/master/user/upgrade.html#upgrade-from-2-0-x-to-2-1-1 ?

**Comment by giovi321** [comment]
I did, but I go an HTTP 500 error.
Anyway, I solved the issue by backing up the mysql tables containing the articles and reinstalling wallabag from scratch.
