### ISSUE TITLE
Adding font size options would be great

### ISSUE THREAD

**Issue by n00b12345** [wallabag/wallabag#2752]
I have vision issues and sometimes the wallabag font seems a little too small. I know I can change it in the browser settings but then the settings change for ALL websites. Could you please consider adding font size options to wallabag?

Thank you. 
(I love wallabag)

**Comment by nicosomb** [comment]
Hello @n00b12345! 

Thanks for your idea. We already have an issue for that, see https://github.com/wallabag/wallabag/issues/1802

Have a nice day.
