### ISSUE TITLE
Wallabag cannot fetch this article but f43.me can

### ISSUE THREAD

**Issue by matteocoder** [wallabag/wallabag#2754]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

wallabag is unable to fetch the content of this article: https://www.locationrebel.com/become-an-seo-freelancer/

### Environment

* wallabag version (or git revision) that exhibits the issue: 1.11.0 Android app
* How did you install wallabag? Via `git clone` or by downloading the package? Downloaded app
* OS: Android 5.0.2 stock LG rom
* Hosted on framabag.org

### Steps to reproduce/test case

bag the article from the aforementioned link on Android.

**Comment by nicosomb** [comment]
Hello @matteocoder! 

> wallabag version (or git revision) that exhibits the issue: 1.11.0

It's the version of what? Addon? Smarphone app? 
We need the wallabag version or where your wallabag is hosted (wallabag.it?).

**Comment by matteocoder** [comment]
@nicosomb  I've updated the main comment, hope that now it has all the necessary information :)

**Comment by nclsHart** [comment]
It works fine on latest version.
