### ISSUE TITLE
Rendering issue of Wallabag itself

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#2756]
### Issue details

This link works with F43.me and not with Wallabag:
http://www.liberation.fr/elections-presidentielle-legislatives-2017/2017/01/03/social-ce-qui-differencie-valls-hamon-peillon-et-montebourg_1538900

Near the end of the article, all the text gets bold within Wallabag, not with f43.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

n/a

**Comment by nicosomb** [comment]
Just tried on wallabag.it (2.3.0), it works.
