### ISSUE TITLE
Rendering issue with The Verge articles

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#2757]
### Issue details

It's not the first time I see this problem. The Verge articles are well rendered by F43 and not at all byt Wallabag, an example: http://www.theverge.com/2017/1/13/14268252/apple-carplay-google-android-auto-vs-carmakers

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

n/a

**Comment by techexo** [comment]
I have no problem retrieving the content of the article with 2.3.3.
The only weird thing is `theverge.com` using `<q>...</q>` in place of `<h2></h2>`, so they are not retrieved. But we can't really say it's wallabag's fault.

**Comment by j0k3r** [comment]
@romu70 can we close it then?

**Comment by romu70** [comment]
I'll try to update my Docker tonight and test with the 2.3.4.
