### ISSUE TITLE
make multiple tag support more obvious in tag entry

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabag#2760]
When adding tags to an existing articles, i need to click that "add tag" button for each tag. I use tags extensively, and I would like to add multiple tags at once. This is a bit like the wallabager chrome plugin is doing, which is to allow tags to be seperated by spaces (or commas, or whatever) and just type them all in one shot.

**Comment by nicosomb** [comment]
Hello @anarcat! 

You can add multiple tags, by separating them with a comma.

**Comment by anarcat** [comment]
well crap. it would be nice this would  be documented, that way i would have known... and i don't mind buried in some manual somewhere, but directly in the field or next to it... maybe by having a "default,  value" as an example that would be greyed out?

it would be nice to be able to have those space-separated as well...

thanks for the super-fast answer!!!

**Comment by nicosomb** [comment]
![capture d ecran 2017-01-17 a 15 36 54](https://cloud.githubusercontent.com/assets/121870/22024602/cd0ddc36-dcca-11e6-9894-f3cced1eca12.png)

You have this information in the field. 

Maybe it's not so visible.

**Comment by anarcat** [comment]
hmm... i don't see that in the "add a tag" line when editing an article - where is that supposed to be?

i'm running 2.1.5, btw.

**Comment by nicosomb** [comment]
In the "add a tag" field when editing an article, in wallabag 2.1.5. 

Can you send us a screenshot please?

**Comment by anarcat** [comment]
of course:

![no documentation on the add tag field](https://cloud.githubusercontent.com/assets/796623/22026215/2e614ea0-dc9e-11e6-8f76-a1f44b096177.png)

Chromium Version 55.0.2883.75 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)

**Comment by nicosomb** [comment]
@tcitworld @j0k3r do you know what can we do with this issue?

**Comment by nicosomb** [comment]
@anarcat do you still have this issue? 
@tcitworld @j0k3r any idea?

**Comment by anarcat** [comment]
this is fixed for me in 2.2.2 - i see the shadowed text, so i guess this can be closed.
