### ISSUE TITLE
iOS App can't connect to wallabag.it

### ISSUE THREAD

**Issue by Zettt** [wallabag/wallabag#2765]
I think this might still be in the works but am wondering if the iOS app (Wallabag 2 Official), or any other clients for that matter, can be configured with the non-self-hosted version of Wallabag (the paid version). I couldn't find useful information in the documentation, other than I'm probably supposed to create a new "developer app".

Thanks.

**Comment by nicosomb** [comment]
Hello @Zettt! 

Yes, you need to create a developer application. Then, you fill the form with the given informations. 

We need to write more documentation about these steps;

**Comment by Zettt** [comment]
I'd appreciate it.

**Comment by Zettt** [comment]
Hello @nicosomb. Thanks for helping me so far. I figured I can contribute the documentation for this. See: https://github.com/wallabag/wallabag/pull/2788

**Comment by nicosomb** [comment]
Thank you @Zettt. 

I will translate your documentation in french. That's why this issue will stay open.

**Comment by Zettt** [comment]
@nicosomb Thanks. Good to know my work is helpful. I'd translate to German but my time doesn't allow it. Keep up the good work!

**Comment by nicosomb** [comment]
Done here https://github.com/wallabag/wallabag/pull/2882

**Comment by Whitou** [comment]
Hi, sorry to re-open this dusty post, but I can't get my phone to connect on wallabag.it.
I created the api client and I get an "Unknown error" each time. Deleted the client, re-created it... Nothing...
Also created another account, did not help.
I'm wondering if I'm using the right URL (tried https://wallabag.it, app.wallabag.it, v2.wallabag.org, wallabag.it/MyUserAccount,...)
