### ISSUE TITLE
wallabag.it down? 

### ISSUE THREAD

**Issue by Zettt** [wallabag/wallabag#2767]
Is the website down? I can't access it since I've registered it. 

```
504 Gateway Time-out

The server didn't respond in time.
```

PS: I'd appreciate if you added a direct contact email or form to the website. This kind of stuff doesn't make sense to discuss here (publicly). Since you're now also, or like to be, charging for wallabag.

**Comment by nicosomb** [comment]
>  I'd appreciate if you added a direct contact email or form to the website.

There is a form here: https://wallabag.it
Can you send me an email to nicolas@wallabag.it please, with your account information on wallabag.it?
