### ISSUE TITLE
Refresh of Articles

### ISSUE THREAD

**Issue by maitrenageur** [wallabag/wallabag#2770]
Sometimes articles will be updates. In this case, I must add the same article to Wallabag again and to delete the old one afterwards.

My proposal is to add a function to refresh articles with a button.

**Comment by nicosomb** [comment]
Hello @maitrenageur ! 

This feature is already implemented, see http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-try-to-re-fetch-this-article

**Comment by maitrenageur** [comment]
Thank you ;-)
