### ISSUE TITLE
Suggestion: provide tags to Shaarli share url

### ISSUE THREAD

**Issue by koenmetsu** [wallabag/wallabag#2771]
When sharing to Shaarli, the tags are not send.

This could be done by exploding the tags in the shaarli url, something like:

```php
{% if craue_setting('share_shaarli') %}<li><a href="{{ craue_setting('shaarli_url') }}/index.php?post={{ entry.url|url_encode }}&amp;title={{ entry.title|url_encode }}&tags={{ explode(',', entry.Tags)|url_encode" target="_blank" class="tool icon-image icon-image--shaarli" title="shaarli"><span>shaarli</span></a></li>{% endif %}
```
(warning: I don't know any php)

**Comment by nicosomb** [comment]
Hello @koenmetsu! 

It's done here https://github.com/wallabag/wallabag/pull/2725 and will be available in next release.
