### ISSUE TITLE
autocomplet tag name

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2772]
## Feature request

Having an autocompletion when entering a tag name that will display the name of the tag + the number of articles that use this tag between ( ) , this will avoid duplication (by entering for example a word in plurial or singular)/typo error 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 7
* OS: debian 8.5
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

**Comment by j0k3r** [comment]
Might be a duplicate of https://github.com/wallabag/wallabag/issues/1869

**Comment by foxmask** [comment]
if this request is related to the edition of an article then yes . Before I create that issue I searched "autocomplet" in the issue list without any success - sorry for the noise :/

**Comment by nicosomb** [comment]
Agree with @j0k3r, it's a duplicate ;-)
