### ISSUE TITLE
tags unsorted

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2773]
### Issue details

from http://myhome/tag/list the tag list is unsorted

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? clone
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 7
* OS: debian 8.5
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

### Steps to reproduce/test case

just have a look at from http://myhome/tag/list the tag list is unsorted

no alphabetic order, no "most tag used" order.

Could we have one of them of both ? :)

ps : I made a search about that behavior w/o any success

**Comment by nicosomb** [comment]
I think that https://github.com/wallabag/wallabag/pull/2763 fixes your issue. Right ?

**Comment by foxmask** [comment]
I will des once I will have in my hand 😏

**Comment by nicosomb** [comment]
Hello @foxmask. Can you tell us if it looks good for you please?

**Comment by foxmask** [comment]
Yes !
