### ISSUE TITLE
tcpdf: Warning: max(): Array must contain at least one element

### ISSUE THREAD

**Issue by rgugliel** [wallabag/wallabag#2776]
Hi,

### Issue details

I'm trying to export to pdf the following article: https://www.infoq.com/articles/apache-spark-sql
I get the following error (lot of times):

    Warning: max(): Array must contain at least one element in /home/(...)//wallabag/vendor/tecnickcom/tcpdf/tcpdf.php on line 6304
And then the export fails.

Note: export of other three articles of this series are fine.

Question 1: Should I open an issue directly in https://github.com/tecnickcom/tcpdf?
Question 2: What is given to tcpdf by Wallabag? The whole page?

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.6
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6
* OS: Ubuntu 14.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

**Comment by nicosomb** [comment]
Hello @rgugliel. 

It's a tcpdf bug. But the guy behind this project works on a new library (https://github.com/tecnickcom/tc-lib-pdf) and I'm not sure that this bug will be fixed one day.

**Comment by nicosomb** [comment]
FYI, we forked the tcpdf project https://github.com/wallabag/TCPDF
This issue is fixed in this fork but wallabag don't use it yet.

**Comment by rgugliel** [comment]
@nicosomb Thanks for the update!
