### ISSUE TITLE
Fatal Error at installation

### ISSUE THREAD

**Issue by maxpv** [wallabag/wallabag#2777]
After performing a `make install`, the following error appears :  

> PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32 bytes) in /usr/share/php/Composer/DependencyResolver/Rule.php on line 60

I tried to change the following line in `scripts/install.sh` : 
`php -d memory_limit=-1 bin/console wallabag:install --env=$ENV`

And also tried to modify the `memory_limit` to `2G` in php.ini. 

Those were both [recommendations](https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors) from the Composer team, but without success.

System : Centos 7.3 with the wallabag's commit  05fa529

**Comment by nicosomb** [comment]
It's my fault, I forgot a file in the last release. 

We just released wallabag 2.1.6.1 https://github.com/wallabag/wallabag/releases/tag/2.1.6.1

Can you re execute `make update` please?

**Comment by maxpv** [comment]
Works well, rhanks @nicosomb.
