### ISSUE TITLE
"User account is disabled" from API

### ISSUE THREAD

**Issue by funwhilelost** [wallabag/wallabag#2780]
### Issue details

After months of using Wallabag 2.0.8 with one user (myself) and using the v2 API (with the WallabagIt extension) I'm suddenly getting back 401s for the API calls.

### Environment

* wallabag 2.0.8
* MariaDB
* Installed from the Docker Hub with a docker-compose stack

### Steps to reproduce/test case

For months it's been working fine with no problems.  I can still log in to the web front-end, post new articles from the web front-end, and get tokens for the API.  When calling `entries.json` it throws back 401s:

```
curl 'http://wallabag..../api/entries.json' -H 'Origin: chrome-extension://dnedlfknokcnjnpfkglledamalkcmdlp' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: */*' -H 'Cookie: PHPSESSID=ocvs....; REMEMBERME=V2FsbGFi....' -H 'Connection: keep-alive' --data 'url=https%3A%2F%2Forionmagazine.org%2Farticle%2Four-school%2F&title=Orion+Magazine+%7C+Our+School&access_token=N2M1NzA3ZDE3MmZiOTk5OTZiYmNhMWEyYTdjZWM3NGFhMmU5MTY5ZmM4OGU2MzcxODA1YWJiZGJiMDc2OThlZg' --compressed
```

And I'm getting back:

```
Access-Control-Allow-Origin:chrome-extension://dnedlfknokcnjnpfkglledamalkcmdlp
Cache-Control:no-store, private
Connection:keep-alive
Content-Type:application/json
Date:Tue, 24 Jan 2017 05:50:53 GMT
Pragma:no-cache
Server:nginx
Transfer-Encoding:chunked
WWW-Authenticate:Bearer realm="Service", error="access_denied", error_description="User account is disabled."
X-Powered-By:PHP/7.0.10
```

```
{"error":"access_denied","error_description":"User account is disabled."}
```

**Comment by j0k3r** [comment]
Maybe the WallabagIt extension got an update that now breaks communication between the extension and your server?

**Comment by funwhilelost** [comment]
@j0k3r I don't think so.  I'm going to try to get to the bottom of it.  "User account is disabled" comes from Symfony when a user hasn't validated their email but this is the default user `wallabag`.

**Comment by funwhilelost** [comment]
I had, in fact, put the wrong user into the settings.  It had the correct user and password for a user that actually _was_ disabled.  So everything on wallabag's end works as intended.  Thanks!
