### ISSUE TITLE
SQLite reusing IDs could break sync

### ISSUE THREAD

**Issue by FilipBB** [wallabag/wallabag#2781]
### Issue details

Because SQLite might reuse an article's ID after it has been deleted for a new article, apps that access the Wallabag API but which haven't been made aware of the change could reference the ID intending to make a change to an article that no longer exists, and instead change attributes for the new article. I experienced this problem while writing a plugin for [koreader](https://github.com/koreader/koreader). Because koreader runs on an ereader, syncing will not be done immediately when a change is made, instead it could be a long time before sync is called and in the meantime many changes may have been made independently on the server. If IDs are reused syncing will not propagate the changes intended by the user.

### Environment

* wallabag version (or git revision) that exhibits the issue: v2
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.1.1
* OS: Arch Linux
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

**Comment by j0k3r** [comment]
Just avoid using SQLite in production. This is a nightmare.
We plan to strongly depreciate SQLite in production in [the coming version](https://github.com/wallabag/wallabag/issues/2766). It's horrible to handle a SQL migration when we change things. And the kind of behavior you describe shouldn't exist in a database.

So please, advice your users to not use SQLite with wallabag if they plan to often use wallabag.

**Comment by FilipBB** [comment]
Ok, I'll do that then, thanks.
