### ISSUE TITLE
crashed server after try to import firefox bookmarks

### ISSUE THREAD

**Issue by CordlessWool** [wallabag/wallabag#2783]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

500: Internal Server Error

An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT id_0 FROM (SELECT w0_.id AS id_0, w0_.uuid AS uuid_1, w0_.title AS title_2, w0_.url AS url_3, w0_.is_archived AS is_archived_4, w0_.is_starred AS is_starred_5, w0_.content AS content_6, w0_.created_at AS created_at_7, w0_.updated_at AS updated_at_8, w0_.mimetype AS mimetype_9, w0_.language AS language_10, w0_.reading_time AS reading_time_11, w0_.domain_name AS domain_name_12, w0_.preview_picture AS preview_picture_13, w0_.is_public AS is_public_14, w1_.id AS id_15 FROM `wallabag_entry` w0_ LEFT JOIN `wallabag_user` w1_ ON w0_.user_id = w1_.id WHERE w1_.id = ? AND w0_.is_archived = 0) dctrn_result ORDER BY created_at_7 DESC LIMIT 12 OFFSET 0' with params [2]: SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.created_at_7' which is not in SELECT list; this is

### Environment

docker container last version. I think it should be 1.2.6. set it up today evening. I combine it with a mysql database version 5.7

### Steps to reproduce/test case

I try to insert bookmarks from firefox. this crashed my hole server, although I run it in a docker container which is not directly connected to the server. 
 
and now I get only the internal error code if i try to login

**Comment by j0k3r** [comment]
Yeah we know that bug and we need to work on it.
https://github.com/wallabag/wallabag/issues/2542
