### ISSUE TITLE
Cannot bag laquadrature.net article

### ISSUE THREAD

**Issue by doc75** [wallabag/wallabag#2786]
### Issue details

I have issues to bag laquadrature.net article.
When trying to bag https://www.laquadrature.net/fr/si-vous-etes-le-produit I got the "Not title found" error.
When I try to troubleshoot the error following the documentation, it appears to work fine on f43.me.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.6
* How did you install wallabag? Via `git clone` or by downloading the package? git clone + make install
* Last wallabag version that did not exhibit the issue (if applicable): v1.9 (I go from 1.9 to 2.1.6 directly)
* php version: 5.5.9-1ubuntu4.20
* OS: Ubuntu 14.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Just try to bag the page mentionned in the issue description

If there is any trace that I can activate to help debugging, just let me know.

**Comment by gege2b** [comment]
Hi
I Just tested with 2.2 and it works fine (but the title is fetched as : "Si vous êtes le produit, ce n&#039;est pas gratuit"

**Comment by j0k3r** [comment]
Looks good on wallabag.it (which runs 2.2.0)
![](https://cl.ly/3l140Q0O080s/Image%202017-01-30%20at%209.29.33%20AM.png)

@doc75 Can you confirm?

**Comment by doc75** [comment]
I just migrated to 2.2.1 and it is now working great.
It seems this version improves some other site grabing also.
Thanks @j0k3r and @gege2b .
