### ISSUE TITLE
Symbolic link not allowed or link target not accessible after upgrading to 2.2.0

### ISSUE THREAD

**Issue by das-schaf** [wallabag/wallabag#2794]
### Issue details

After upgrading to release 2.2.0 i cannot login any more

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.0
* How did you install wallabag? Via `git clone` or by downloading the package? package
* Last wallabag version that did not exhibit the issue (if applicable): 2.1.6
* php version: PHP 7.0.11
* OS: CentOS 6
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

I am running wallabag on a shared hoster which does not allow creating custom vhost configuration files. This has been resolved by using the following htaccess instructions:

`RewriteCond %{REQUEST_URI} !^/web/`
`RewriteRule !^web/ /web%{REQUEST_URI} [L,NC]`

After upgrading to release 2.2.0 my error log shows following entry. Login is not possible at the moment.

`[Sat Jan 28 16:38:43 2017] [error] [client 2003:71:8f5d:3600:8565:1ab:f1cd:410f] Symbolic link not allowed or link target not accessible: /var/www/virtual/user/wallabag.mydomain.tld/web/bundles/fosjsrouting, referer: https://wallabag.mydomain.tld/login`

**Comment by das-schaf** [comment]
`lrwxrwxrwx 1 sheep1 sheep1   98 28. Jan 16:50 fosjsrouting -> /private/tmp/wllbg-release/release-2.2.0/vendor/friendsofsymfony/jsrouting-bundle/Resources/public
lrwxrwxrwx 1 sheep1 sheep1  106 28. Jan 16:50 nelmioapidoc -> /private/tmp/wllbg-release/release-2.2.0/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/public
drwxr-xr-x 3 sheep1 sheep1 4096 28. Jan 16:50 wallabagcore
lrwxrwxrwx 1 sheep1 sheep1   96 28. Jan 16:50 whiteoctoberpagerfanta -> /private/tmp/wllbg-release/release-2.2.0/vendor/white-october/pagerfanta-bundle/Resources/public`

There seems to be some wrong symbolic links within the current download (see above).

I downloaded via `wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package`

**Comment by schneefux** [comment]
Same here. I downloaded the package from static.wallabag.org, the packaging script should follow symlinks instead of packaging them ;)

**Comment by mourningsun75** [comment]
Same problem here. Restored back to 2.1.6.1

**Comment by nicosomb** [comment]
You didn't have this problem with 2.1.6.1?

**Comment by das-schaf** [comment]
2.1.6 is running smoothly. There are not symlinks in web/bundles in version 2.6.1. "wallabagcore" ist the only folder in web/bundles.

**Comment by mourningsun75** [comment]
yes, no problem with 2.1.6.1

**Comment by schneefux** [comment]
@nicosomb Your shared hosting archives have broken symlinks in `web/bundles` which break the application completely - this is a critical issue.

**Comment by nicosomb** [comment]
I don't understand what has changed since latest versions.

**Comment by schneefux** [comment]
@nicosomb 
```bash
ls release-2.1.6/web/bundles/ -l
drwxr-xr-x 3 me me 60 18. Jan 10:46 wallabagcore
```

```bash
tar xzf wallabag-release-2.2.1.tar.gz
tar: ignoring unknown keyword „SCHILY.dev“ for extended header
tar: ignoring unknown keyword „SCHILY.ino“ for extended header
tar: ignoring unknown keyword „SCHILY.nlink“ for extended header
```
(error messages translated by me)

```bash
ls release-2.2.1/web/bundles -l
drwxr-xr-x 3 me me  60 12. Feb 21:08 wallabagcore
lrwxrwxrwx 1 me me  98 31. Jan 12:27 fosjsrouting -> /private/tmp/wllbg-release/release-2.2.1/vendor/friendsofsymfony/jsrouting-bundle/Resources/public
lrwxrwxrwx 1 me me 106 31. Jan 12:27 nelmioapidoc -> /private/tmp/wllbg-release/release-2.2.1/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/public
lrwxrwxrwx 1 me me  96 31. Jan 12:27 whiteoctoberpagerfanta -> /private/tmp/wllbg-release/release-2.2.1/vendor/white-october/pagerfanta-bundle/Resources/public
```

Your release archive now has symbolic links. They are not relative, they are absolute and the path `/private/tmp/wllbg-release` doesn't exist on any other machine than yours.
`bsdtar` does not produce errors but the result is the same. Maybe the software you use to create the `tar` archives is misconfigured.

**Comment by schiessle** [comment]
I have the same issue as described by @schneefux. Seems contains files linking to files only outside of the packed on the system the packages was created.

**Comment by nicosomb** [comment]
I just opened a new PR to fix this bug :tada: !

**Comment by nicosomb** [comment]
Should be fixed with latest release 

https://wallabag.org/en/news/new-release-wallabag-2-2-2

Could you check please?

**Comment by nicosomb** [comment]
@das-schaf @schneefux @schiessle @mourningsun75 can you try the new release please and tell us if it looks ok for you please?

**Comment by mourningsun75** [comment]
just tried, now i have a new problem. i cant log in anymore. will check logs. when i try to reset password the following error appears.

500: Internal Server Error
An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12, t0.name AS name_13, t0.created_at AS created_at_14, t0.updated_at AS updated_at_15, t0.authCode AS authCode_16, t0.twoFactorAuthentication AS twoFactorAuthentication_17, t0.trusted AS trusted_18, t19.id AS id_20, t19.theme AS theme_21, t19.items_per_page AS items_per_page_22, t19.language AS language_23, t19.rss_token AS rss_token_24, t19.rss_limit AS rss_limit_25, t19.reading_speed AS reading_speed_26, t19.pocket_consumer_key AS pocket_consumer_key_27, t19.action_mark_as_read AS action_mark_as_read_28, t19.list_mode AS list_mode_29, t19.user_id AS user_id_30 FROM `wallabag_user` t0 LEFT JOIN `wallabag_config` t19 ON t19.user_id = t0.id WHERE t0.email_canonical = ? LIMIT 1' with params ["dt@bunkertor.org"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't19.action_mark_as_read' in 'field list'

**Comment by mourningsun75** [comment]
Symbolic link not allowed or link target not accessible: /var/www/wallabag/web/bundles/fosjsrouting, referer: https://wallabag.bunkertor.org/login

**Comment by tcitworld** [comment]
The is a migration issue. Relaunch `make update` ?

**Comment by mourningsun75** [comment]
#git checkout 2.1.6.1 --force
git checkout 2.2.2 --force
SYMFONY_ENV=prod php composer.phar install --no-dev -o --prefer-dist
php bin/console doctrine:migrations:migrate --env=prod
php bin/console cache:clear --env=prod

**Comment by mourningsun75** [comment]
i am back on 2.1.6.1

**Comment by schiessle** [comment]
@nicosomb packages seems to be fine now. But I have the same issue as @mourningsun75 https://github.com/wallabag/wallabag/issues/2794#issuecomment-283914963

Maybe because the db update script didn't finished successful? https://github.com/wallabag/wallabag/issues/2936#issuecomment-283901366

**Comment by nicosomb** [comment]
I close this issue. 

If you have an other issue, please open a new issue if necessary.
