### ISSUE TITLE
Wallabag screwed when upgrading to 2.2

### ISSUE THREAD

**Issue by gege2b** [wallabag/wallabag#2797]
Hi all
First I want to say thank you for this great piece of software !

### Issue details

I'm using Wallabag on a dedicated server.
As version 2.2 was released, I wanted to upgrade my 2.1.5 so I used the instructions given in the doc
``` make update ```

But it failed, complaining that composer.phar wasn't found (even if it was in the root dir of wallabag)
I tried by moving composer.phar at some strategic places ("scripts/", "bin", "/bin/composer", "/usr/local/bin/composer") but it never worked.

```
make update
HEAD est maintenant sur 0e62de9... Release wallabag 2.2.0
scripts/update.sh: 18: scripts/update.sh: composer.phar: not found
PHP Fatal error:  Class 'FOS\JsRoutingBundle\FOSJsRoutingBundle' not found in /var/www/wallabag/app/AppKernel.php on line 33
PHP Fatal error:  Class 'FOS\JsRoutingBundle\FOSJsRoutingBundle' not found in /var/www/wallabag/app/AppKernel.php on line 33
Makefile:18: recipe for target 'update' failed
make: *** [update] Error 255
```

composer is installed locally with 
```curl -s https://getcomposer.org/installer | php ```
as asked in the "install" part of the doc

Finally, manually typing all the commands in the update.sh script did the trick, then messing with database migration (which had some "unique constraints violation" by the way, seems that some migration was already done earlier, but I don't know how)

### Environment

* wallabag version (or git revision) that exhibits the issue: 

2.1.5 -> 2.2 (but I remember I had the same problem with a previous update; 2.1.?? -> 2.1.5)

* How did you install wallabag? Via `git clone` or by downloading the package?

via git clone

* Last wallabag version that did not exhibit the issue (if applicable):

don't remember, sorry. But I had this problem on the only two update I did since I installed Wallabag v2

* php version: 
PHP 5.6.29-0+deb8u1

* OS: 
Debian Jessie 8.7

* type of hosting (shared or dedicated):
Dedicated

* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
SQLite

### Steps to reproduce/test case

Just update with "make update"

Given that nobody seems to have reported a similar issue, I'm afraid it's something linked to my server's config... I'm not against a little help here

If you need some more informations, please ask

cheers

**Comment by Alwaysin** [comment]
#2795

**Comment by gege2b** [comment]
I agree that the migration problem is, well, now a known issue :) 
(I begin to write my ticket more than 3 hours ago, but didn't publish it)

But my ticket is mainly about the "composer.phar not found" error

**Comment by j0k3r** [comment]
Thanks for the report, we are going to centralize all issues about migration problem to 2.2.0
#2795
