### ISSUE TITLE
Database issue when migrating from 2.1.4 to 2.2

### ISSUE THREAD

**Issue by michelleunen** [wallabag/wallabag#2798]
I've updated my wallabag installation from 2.1.4 to 2.2 and now I'm trying to apply the differnet database migration but I've got an error for Migration 20161024212538. PhpMyAdmin complains for the line : 

> ALTER TABLE wallabag_oauth2_clients ADD CONSTRAINT IDX_user_oauth_client FOREIGN KEY (user_id) REFERENCES wallabag_user (id) ON DELETE CASCADE

The error PhpMyAdmin gives is:

> #1452 - Cannot add or update a child row: a foreign key constraint fails (`leg_wallabag`.`#sql-516f_16f4c92b`, CONSTRAINT `IDX_user_oauth_client` FOREIGN KEY (`user_id`) REFERENCES `wallabag_user` (`id`) ON DELETE CASCADE)

I've absolutely no idea what it means. Can someone help me ?

**Comment by azrdev** [comment]
See #2795 and #2797 for more issues with this update

**Comment by j0k3r** [comment]
Thanks for the report, we are going to centralize all issues about migration problem to 2.2.0
#2795
