### ISSUE TITLE
Existing clients not listed on developers page

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2799]
### Issue details

I have updated wallabag from 2.1.5 to 2.2. When i had version 2.1.5 i created some clients on the developer page. After upgrade to 2.2 they are not listed anymore. But i still can use those clients. I did look into the table wallabag_oauth2_clients and there are four rows, which are exactly my created clients.

But why aren't they listed anymore in my developer page?

### Environment

* wallabag version (or git revision) that exhibits the issue:  2.2
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): 2.1.5
* php version: PHP 5.6.29-0+deb8u1
* OS:Debian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

### Steps to reproduce/test case

see issue details

**Comment by j0k3r** [comment]
My guess is that since we added a `user_id` key on that table to be able to conditionally display client to the user who created them. Maybe we forgot to add a default `user_id` to the table ..

**Comment by nicosomb** [comment]
I'm not sure that setting a default user_id is a good thing. 
What about multi users installations?

**Comment by j0k3r** [comment]
Well, yeah. Not a good one.
But we definitively need to clarify what user should do about that point after updating.

**Comment by nicosomb** [comment]
We need to add some documentation about that part (like for the pocket_consumer_key in the previous minor release).
