### ISSUE TITLE
Entitie number shown in "thumbnail" (?) view mode

### ISSUE THREAD

**Issue by gege2b** [wallabag/wallabag#2802]
Hi all

### Issue details

When I display my saved articles in the "thumbnail" view mode, titles shows entities number instead of real caracters

When switching to list view mode, caracters are shown the right way

![image](https://cloud.githubusercontent.com/assets/2814966/22416736/ae327294-e6d0-11e6-9bc2-9136694c756e.png)

![image](https://cloud.githubusercontent.com/assets/2814966/22416748/ba1cad9a-e6d0-11e6-9c73-4fdc97856c79.png)

### Environment

* wallabag version (or git revision) that exhibits the issue: 
2.2.0

* How did you install wallabag? Via `git clone` or by downloading the package?
via git

* Last wallabag version that did not exhibit the issue (if applicable):
I didn't noticed this on previous version

* php version:
5.6

* OS:
Debian Jessie 8.7

* type of hosting (shared or dedicated):
Dedicated 

* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
SQLite

### Steps to reproduce/test case

Save an article with quotes, "&" or anything like this in the title and switch to thumbnail view

**Comment by j0k3r** [comment]
Did you have that problem on each browser?

**Comment by nicofrand** [comment]
Reproducible with https://paragonie.com/blog/2015/08/you-wouldnt-base64-a-password-cryptography-decoded

**Comment by gege2b** [comment]
@j0k3r yes, just tested with Edge (I have not Chrome installed and I don't want to ^_^)
