### ISSUE TITLE
"Article reloaded" on wrong page

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#2803]
### Issue details

The "article reloaded" notification appears on the wrong page.

![wb-error-article-reloaded](https://cloud.githubusercontent.com/assets/3419050/22418210/4ad1c6a2-e6d8-11e6-968d-d11d09f376a2.png)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.0
* How did you install wallabag? Via `git clone` or by downloading the package? : git clone
* Last wallabag version that did not exhibit the issue (if applicable): NA
* php version: 5.6.27
* OS: Linux
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

0. Open several articles in several tabs
0. For each article, reload the content
0. Wait

Some pages do not have the "article reloaded" notification whereas others have several notifications.

**Comment by j0k3r** [comment]
Yeah, this is related to how Symfony handle session notification. Each action will add a notification to the session and the page to request the notification from the session will get all notifications available. Which can result in getting notification from other action.

This _bug_ might not happen if you don't open multiple tab doing an action on each tab.
Also, the content will be reloaded in any case. This won't affect the main purpose of the action. Just the notification.

**Comment by nicosomb** [comment]
We can't do anything for your issue. I understand it might by annoying, but I close.
