### ISSUE TITLE
Weird chars on "all articles" page with some titles

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#2804]
### Issue details

The article's title, on the "all articles" page is :

> You Wouldn&amp;#039;t Base64 a Password - Cryptography Decoded

When I click on the article, the title looks better:

> You Wouldn't Base64 a Password - Cryptography Decoded

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.0
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): do no know
* php version: 5.6.27
* OS: Debian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Bag this link: https://paragonie.com/blog/2015/08/you-wouldnt-base64-a-password-cryptography-decoded

**Comment by tcitworld** [comment]
Probably the same as https://github.com/wallabag/wallabag/issues/2802

**Comment by nicofrand** [comment]
Oops indeed, sorry the title was not speaking to me, I did not see it.
