### ISSUE TITLE
Transparency lost on imported PNG image

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#2805]
### Issue details

The transparency of the PNG logo is lost:

![wb-png-bg](https://cloud.githubusercontent.com/assets/3419050/22418914/5b4029cc-e6db-11e6-8e23-586a3636c360.png)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.0
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): NA
* php version: 5.6.27
* OS: Debian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

0. Enable local import of images
0. Bag http://www.ssi.gouv.fr/administration/precautions-elementaires/calculer-la-force-dun-mot-de-passe/ (not sure from where wallabag fetches that big image though).

**Comment by j0k3r** [comment]
Interesting.
This image is defined in the `og:image` meta in the html: http://www.ssi.gouv.fr/uploads/2014/07/logo_anssi_v3b_500x500.png

**Comment by tcitworld** [comment]
Needs :
```
imagealphablending($img, false);
imagesavealpha($img, true);
```
But I guess there would be some side-effects.

**Comment by Kdecherf** [comment]
These calls should be limited to image/png files.
