### ISSUE TITLE
[security] v2.2  API doesn't compare user_id when checks client? 

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2806]
After migrating to v2.2 there is a new binding of client and user. And afrer migration in the existing clients the new field user_id is null (it is allright, who nows whose client it is :) ).  But existing client applications works well. Does it mean that API doesn't compare user_id when checks client?

**Comment by j0k3r** [comment]
The check is only applied on the web ui.
This means, users can no more see others client id.

Related https://github.com/wallabag/wallabag/issues/2799

**Comment by Rurik19** [comment]
So, If in an client app like wallabagger I set up user2 but client info of user1 to which user will articles be saved?

**Comment by j0k3r** [comment]
The retrieved `used_id` is the one who logged in in your app.
The client / secret is only here to validate that the application (wallabagger) is allowed to use the API of that instance of wallabag.

In fact, you can use one couple client / secret for all users of a wallabag instance.

We added a check on the `user_id` only to avoid other users to remove a client / secret created by an other one.

**Comment by Rurik19** [comment]
ok, I uderstand.
