### ISSUE TITLE
MySQL (MariaDB) Update Errors from 2.1.6 to 2.2.0

### ISSUE THREAD

**Issue by chrbayer** [wallabag/wallabag#2810]
Update from 2.1.6 to 2.2.0 not possible, during "ALTER TABLE wallabag_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" I got the following error:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
I even converted the database from InnoDB to MyISAM to increase the keysize from 767 to 1000 bytes, which was not enough as seen later.

=> No update possible

**Comment by nicosomb** [comment]
Hello @chrbayer! 

Did the first queries in this migration (`app/DoctrineMigrations/Version20161022134138.php`) run well?

**Comment by chrbayer** [comment]
Hello @nicosomb 

Yes, the first queries run well, this was the first which failed.

**Comment by nicosomb** [comment]
I mean `ALTER DATABASE wallabag CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;`? 
(just to be sure)

**Comment by chrbayer** [comment]
Here a copy from the results:

     -> ALTER DATABASE wallabag CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_user CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT NULL;
     -> ALTER TABLE wallabag_user CHANGE salt salt VARCHAR(180) NOT NULL;
     -> ALTER TABLE wallabag_user CHANGE password password VARCHAR(180) NOT NULL;
     -> ALTER TABLE wallabag_annotation CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_entry CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_tag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
Migration 20161022134138 failed during Execution. Error An exception occurred while executing 'ALTER TABLE wallabag_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;':

So the query ALTER DATABASE wallabag CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci; seem to be executed correctly.
By the way, I can see that some of the tables have been converted to utf8mb4 correctly...

**Comment by alecbl** [comment]
I personally got around that by changing the varchar(255) fields on wallabag_user to varchar(191), which seems to be the limit on utf8mb4, given a worst case scenario is assumed.

**Comment by j0k3r** [comment]
Which fields were still at 255?

**Comment by nicosomb** [comment]
All the fields where we didn't define length. 

`* @ORM\Column(name="title", type="text", nullable=true)`

**Comment by chrbayer** [comment]
I changed the varchar(255) fields to varchar(191) and that worked for me too, I didn't checked with InnoDB, but at least I have a working installation now :)

**Comment by pmartin** [comment]
Hi,

I've had the exact same problem while migrating from 2.1(.6?) to 2.2.1.

I ran `make update` without any trouble, but got an error while running the migrations :
```
Migrating up to 20170127093841 from 20161001072726

  ++ migrating 20161022134138

     -> ALTER DATABASE wallabag CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_user CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT NULL;
     -> ALTER TABLE wallabag_user CHANGE salt salt VARCHAR(180) NOT NULL;
     -> ALTER TABLE wallabag_user CHANGE password password VARCHAR(180) NOT NULL;
     -> ALTER TABLE wallabag_annotation CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_entry CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_tag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
Migration 20161022134138 failed during Execution. Error An exception occurred while executing 'ALTER TABLE wallabag_user CONVERT TO CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'ALTER TABLE wallabag_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;':
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

Here's the alter I ran to change the length of the fields that were `varchar(255)` :
```
alter table wallabag_user
    change column `username` `username` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
    change column `username_canonical` `username_canonical` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
    change column `email` `email` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
    change column `email_canonical` `email_canonical` varchar(191) COLLATE utf8_unicode_ci NOT NULL
;
```

After than, I re-ran the migrations and everything went OK ;-)

**Comment by nicosomb** [comment]
@pmartin and your wallabag instance works fine?

**Comment by nicosomb** [comment]
Oh I see, the migrations failed, and you relaunched it, the migration tools believed the migration was already played. So he didn't try to re-execute it. 
Can you try to save an article which contains an emoji please? (that's why we change encoding)

**Comment by pmartin** [comment]
After the migrations failed, the instance was not working anymore.

Then, I ran the alter and re-launched the migrations, which run OK (either some were executed and did not re-run or they were re-run but didn't fail) -- and that fixed the instance, which is now running OK.

Here's the beginning of the output I got when re-running the migrations (after the `alter` I did by hand) :
```
wallabag@ks:~/www$ php bin/console doctrine:migrations:migrate --no-interaction -e=prod
                    Application Migrations

Migrating up to 20170127093841 from 20161001072726

  ++ migrating 20161022134138

     -> ALTER DATABASE wallabag CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_user CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT NULL;
     -> ALTER TABLE wallabag_user CHANGE salt salt VARCHAR(180) NOT NULL;
     -> ALTER TABLE wallabag_user CHANGE password password VARCHAR(180) NOT NULL;
     -> ALTER TABLE wallabag_annotation CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_entry CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_tag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_annotation CHANGE `text` `text` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_annotation CHANGE `quote` `quote` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_entry CHANGE `title` `title` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_entry CHANGE `content` `content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_tag CHANGE `label` `label` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
     -> ALTER TABLE wallabag_user CHANGE `name` `name` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

  ++ migrated (9.39s)

  ++ migrating 20161024212538

     -> ALTER TABLE wallabag_oauth2_clients ADD user_id INT DEFAULT NULL
     -> ALTER TABLE wallabag_oauth2_clients ADD CONSTRAINT IDX_user_oauth_client FOREIGN KEY (user_id) REFERENCES wallabag_user (id) ON DELETE CASCADE
     -> CREATE INDEX IDX_635D765EA76ED395 ON wallabag_oauth2_clients (user_id)

  ++ migrated (0.64s)
```
(the output is much longer : there have been several other migrations going OK)

I tried to save this article from wikipedia : https://fr.wikipedia.org/wiki/Emoji ; the emojis under "Ajouts récents", in both the "Émoticônes" and the "Symboles divers" tables, are OK while reading this page with Firefox.

Trying to read the saved page in wallabag (from the same Firefox), I get this :
![emojis-wallabag](https://cloud.githubusercontent.com/assets/193481/22479432/005236b8-e7ee-11e6-9c8d-4efb880d4996.png)

The emojis from the second table are OK but those from the first one are not -- maybe it's a font problem or something, though?

**Comment by nicosomb** [comment]
You're right, it seems to be a font problem. 
Because the problem with the old encoding (`utf8`) was that wallabag failed (and crashed) when trying to save articles like that.

**Comment by TwizzyDizzy** [comment]
Can confirm anything from https://github.com/wallabag/wallabag/issues/2810#issuecomment-276454378.

Did use alter table statements by @pmartin and then re-ran the migration. Worked like a charm. Wallabag now up and running again :)

Cheers
Thomas

**Comment by HLFH** [comment]
`alter table wallabag_user
    change column `username` `username` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
    change column `username_canonical` `username_canonical` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
    change column `email` `email` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
    change column `email_canonical` `email_canonical` varchar(191) COLLATE utf8_unicode_ci NOT NULL
sudo -u http php bin/console doctrine:migrations:migrate --no-interaction -e=prod;`

I confirm alter table statements fixed this issue.

**Comment by nicosomb** [comment]
Hi there. 

Do we need to do something on this issue please?

**Comment by daniele-athome** [comment]
I guess shrinking the username column as suggested in the workaround - although it's not backward compatible... I don't know what else can we do when the primary key is too large anyway?
If we have to change MySQL/MariaDB configuration, it might not be acceptable in some environments.
