### ISSUE TITLE
Deleting article from search view should keep current search

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/wallabag#2815]
### Issue details

When we delete an article from the search view, we are redirected to the unread view. It could be interesting to keep the search term and be redirected to the search view instead.

### Environment

* wallabag version (or git revision) that exhibits the issue: _2.2.0_
* How did you install wallabag? Via `git clone` or by downloading the package? _git_
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version: _5.6_
* OS: _ Debian Jessie_
* type of hosting (shared or dedicated): _dedicated_
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): _PostgreSQL_

### Steps to reproduce/test case

* Make a search using new search bar
* Delete one item from the list
* We are redirected to the global view

**Comment by nicosomb** [comment]
It seems to be fixed.
