### ISSUE TITLE
Not working website

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2819]
### Issue details

This URL is fetched well in http://f43.me/feed/test but not in wallabag:
http://www.muylinux.com/2017/01/27/scientific-linux-7-3

### Environment

* Version: 2.2.1
* php version: 7
* OS: ubuntu
* shared hosting
* SQLite

**Comment by ngosang** [comment]
Fixed in https://github.com/fivefilters/ftr-site-config/pull/252
When will these changes be incorporated into wallabag?

**Comment by nicosomb** [comment]
Yes, when your pull request will be merged and then, when we'll release a new version.
