### ISSUE TITLE
Instapaper import not working

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2820]
### Issue details

Instapaper import not working. Attached csv. 
[instapaper-export.zip](https://github.com/wallabag/wallabag/files/743651/instapaper-export.zip)

### Environment

* Version: 2.2.1
* php version: 7
* OS: ubuntu
* shared hosting
* SQLite

**Comment by j0k3r** [comment]
Could you explain what is not working? Do you have an error?

**Comment by nicosomb** [comment]
Just tried with the latest wallabag release, freshed instally. And it works.
![capture d ecran 2017-02-01 a 07 58 30](https://cloud.githubusercontent.com/assets/121870/22497789/48b1a644-e854-11e6-8408-6f15628ee0bd.png)

**Comment by ngosang** [comment]
> Could you explain what is not working? Do you have an error?

I see a black popup in the top right corner saying import failed or something like that but isn't enough to find the cause. How can I enable php logs or debug?

**Comment by j0k3r** [comment]
Anything in `var/logs/*`?
Otherwise, update `app/config/config_prod.yml` and put `debug` instead of `error` at [line 18](https://github.com/wallabag/wallabag/blob/master/app/config/config_prod.yml#L18).

**Comment by ngosang** [comment]
I was my fault, some missing files in installation. Sorry.
