### ISSUE TITLE
2FA via third party apps

### ISSUE THREAD

**Issue by n00b12345** [wallabag/wallabag#2822]
I am having a bit of trouble getting 2FA emails delivered to me. 

Wouldn't it be more convenient from a user's perspective to have codes delivered locally via Google authentication app or Authy etc?

Thanks!

**Comment by nicosomb** [comment]
Hello @n00b12345. With the library that we use for 2FA by email, we can handle Google Authenticator. 
But we need to add a new field in database, so I planned this issue for 2.3.0.

**Comment by n00b12345** [comment]
@nicosomb awesome! Thanks!

**Comment by hvhaugwitz** [comment]
It would be very useful to be able use an authentication app instead of email. So I second this feature request.

What is the state of this issue? Why the 'add-google-authenticator' pull request has been closed without being merged?

**Comment by j0k3r** [comment]
Nobody is working on it atm.
And I guess it was closed because of this comment https://github.com/wallabag/wallabag/pull/3170#issuecomment-307323576

**Comment by hvhaugwitz** [comment]
The comment seems just to be about the wording.

So what one can do to get this feature into wallabag?

**Comment by 74cmonty** [comment]
Nextcloud, a fork of Owncloud, is using [this](https://github.com/nextcloud/twofactor_totp#readme) working 2FA OTP.
It is open source, and why should this not work with wallabag after some adaption?
