### ISSUE TITLE
LWN.net articles get cut off

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabag#2825]
### Issue details

[This email on LWN.net](https://lwn.net/Articles/581820) is actually quite readable on the [fivefilters test site](http://f43.me/feed/test). But in wallabag, it gets cut off on the side, probably because of some CSS issue.

Here's a screenshot showing the problem:

![LWN.net with text cut off](https://cloud.githubusercontent.com/assets/796623/22518168/a4928f4e-e879-11e6-9d16-46b567e90271.png)

It makes the whole article basically unreadable. This is especially bad on the EPUB output...

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? unknown
* Last wallabag version that did not exhibit the issue (if applicable): unknown
* php version: unknown
* OS: Debian GNU/Linux 8 "jessie"
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): unknonwn

### Steps to reproduce/test case

Add [this article to wallbag](https://lwn.net/Articles/581820), try to read it. Try it on the fivefilters test site, and actually read it correctly.

**Comment by j0k3r** [comment]
Looks ok to me on app.wallabag.it:

![image](https://cloud.githubusercontent.com/assets/62333/22541529/24f534b8-e927-11e6-83d4-961dc06ba47e.png)

Can you share your browser and your resolution?
Maybe you should upgrade to 2.2.1.

**Comment by anarcat** [comment]
the web browser here is Firefox 50.1.0 (Build identifier: Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0) running on Debian GNU/Linux 9 "stretch". Screen resolution is:

```
[996]anarcat@curie:~$ xrandr -q
Screen 0: minimum 320 x 200, current 1680 x 1050, maximum 8192 x 8192
HDMI-1 disconnected primary (normal left inverted right x axis y axis)
DP-1 connected 1680x1050+0+0 (normal left inverted right x axis y axis) 473mm x 296mm
   1680x1050     59.95*+
```

The font picked may be the problem: here it is [DejaVu](https://en.wikipedia.org/wiki/DejaVu_fonts) Sans Mono - maybe it's wider than your font?

**Comment by j0k3r** [comment]
I've just tested on the same Firefox version on Ubuntu and still not get the problem.
The font is `monospace` here.

**Comment by anarcat** [comment]
yeah, `monospace` is DejaVu Sans Mono here. not sure what it is for you - in the stylesheet, `monospace` is just an alias for the system monospace font: you need to go to the "Fonts" tab to figure out exactly what font is used...

**Comment by j0k3r** [comment]
Interesting.
So the fond used is also DejaVu Sans Mono here.

I guess the problem have been fixed in 2.2

**Comment by nicosomb** [comment]
@anarcat can you tell us if it looks ok for you with latest release?

**Comment by anarcat** [comment]
where can i test? my hoster didn't  upgrade yet...

**Comment by nicosomb** [comment]
you can create a trial account on wallabag.it.

**Comment by anarcat** [comment]
sure looks like the font is different, i guess this is fixed.
