### ISSUE TITLE
Wishlist: Show article creation date

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2827]
I would like to have the article creation date at the top of the article, just below the title. I mean the date in the original article, not the date it was fetched.
Related https://github.com/wallabag/android-app/issues/414

**Comment by j0k3r** [comment]
There is a working in progress on that point https://github.com/j0k3r/graby/pull/68
But it'll be hard to find the date creation of each article.

Also, a duplicate of https://github.com/wallabag/wallabag/issues/2590

**Comment by ngosang** [comment]
> But it'll be hard to find the date creation of each article.

I think it's easier than you think. Most articles have a date tagged with "<time>" tag.

**Comment by j0k3r** [comment]
We'll see :slightly_smiling_face:
