### ISSUE TITLE
Change actual behavior of retrieving article

### ISSUE THREAD

**Issue by bourvill** [wallabag/wallabag#2828]
After importing all articles with the article export / import. 

Ids of article are inverted, i'm explain, the last article imported is id = 1

I think we have two way's, change article import rule or send article through api order by created_at desc 
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2
* How did you install wallabag?  
* php version: 7.1
* OS: Ubuntu 14.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Mysql 👍 

### Steps to reproduce/test case
Export and import articles

**Comment by j0k3r** [comment]
Are you sure about the behavior because since we handle the `created_at` field (see https://github.com/wallabag/wallabag/commit/6d65c0a8b089d3caa6f8e20d7935a9fe2f87d926), the list should be displayed in correct order because we re-created entries with the same `created_at`.
