### ISSUE TITLE
Can not create a user on a new installation 2.2.1

### ISSUE THREAD

**Issue by CordlessWool** [wallabag/wallabag#2833]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

I set up a completly new Docker image (version 2.2.1) with MySQL Database 5.7.17, when I try to regist a user I get the error message: 

500: Internal Server Error

An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.locked AS locked_9, t0.expired AS expired_10, t0.expires_at AS expires_at_11, t0.confirmation_token AS confirmation_token_12, t0.password_requested_at AS password_requested_at_13, t0.roles AS roles_14, t0.credentials_expired AS credentials_expired_15, t0.credentials_expire_at AS credentials_expire_at_16, t0.id AS id_17, t0.name AS name_18, t0.created_at AS created_at_19, t0.updated_at AS updated_at_20, t0.authCode AS authCode_21, t0.twoFactorAuthentication AS twoFactorAuthentication_22, t0.trusted AS trusted_23, t24.id AS id_25, t24.theme AS theme_26, t24.items_per_page AS items_per_page_27, t24.language AS language_28, t24.rss_token AS rss_token_29, t24.rss_limit AS rss_limit_30, t24.reading_speed AS reading_speed_31, t24.pocket_consumer_key AS pocket_consumer_key_32, t24.user_id AS user_id_33 FROM `wallabag_user` t0 LEFT JOIN `wallabag_config` t24 ON t24.user_id = t0.id WHERE t0.username_canonical = ?' with params ["cordless"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.locked' in 'field list'

**Comment by CordlessWool** [comment]
I do crap...

**Comment by JohWayne** [comment]
What was the solution here?

Unfortunately I can't find the cause in the logs. I am currently just quite clueless.

**Comment by j0k3r** [comment]
@JohWayne maybe you can open a new issue with some information about query problem, wallabag version, etc. ?

**Comment by bjo81** [comment]
Did you fix it?
