### ISSUE TITLE
Staying on an article view after removing a tag

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2835]
### Issue details

When we drop a tag from the view page of an article, we are redirected to the unread articles

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 7
* OS: deb 8.5
* type of hosting (shared or dedicated): dedi
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): pgsql

### Steps to reproduce/test case

open an article with tags, drop one tag and see

**Comment by Kdecherf** [comment]
It appears that this behavior is currently handled by _"Where do you want to be redirected after mark an article as read?"_.

@j0k3r @nicosomb Should we create an option for tag removal or just consider that we must always stay on the article?

**Comment by j0k3r** [comment]
I prefer option 2.

**Comment by nicosomb** [comment]
For the tag deletion, I think option 2 too.
