### ISSUE TITLE
Return to unreaded articles after click mark as read button

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2849]
Return to unreaded articles after click mark as read button (the same behavior as when you click delete)

![2017-02-07 23_48_07- recuerdas goldeneye 007 de n64_ ahora puedes jugarlo en pc gracias a este port](https://cloud.githubusercontent.com/assets/10577978/22715139/e8690462-ed8f-11e6-9f49-62d40dd98bb6.png)

**Comment by nicosomb** [comment]
Hello @ngosang! 
You can configure this behavior on your configuration page.
