### ISSUE TITLE
Shared Hosting - 404 in config.

### ISSUE THREAD

**Issue by emillod** [wallabag/wallabag#2851]
Hello.
I have problem with wallabag installation.
I download latest version and extract on my shared hosting.
After I assign domain to folder with wallabag everything is okay, i can log in and everything, but i can't open config, because i have error 404. 
Any ideas?

**Comment by j0k3r** [comment]
What config?

**Comment by emillod** [comment]
http://i.imgur.com/zr7tBrd.png

**Comment by j0k3r** [comment]
All other links in the menu are working?
What's the url of the requested page?

**Comment by emillod** [comment]
Yes. Hmm URL is: domain.com/config

**Comment by j0k3r** [comment]
It's hard to debug then.
Could you try `/config/`?

Could you share your vhost configuration.
Could you check logs to see what's inside?

If no log, please switch `error` to `debug` in `app/config/config_prod.yml`, then remove content from `var/cache` and retry.

**Comment by emillod** [comment]
I have wallabag on shared hosting, so i don't have access to vhost configuration. I just assigned domain to folder */wallabag/web/ and everything's ok..

**Comment by j0k3r** [comment]
By "it's hard to debug",  I mean if you don't give me information I requested, I won't be able to help you.

**Comment by emillod** [comment]
Hi
i remove all files and change value in config files, but nothing changed 😞

**Comment by nicosomb** [comment]
Hello @emillod. 

Do you still have this issue with latest release?

**Comment by emillod** [comment]
Hello @nicosomb , 
no for now everything is okay! 
Thanks :) 
/close

**Comment by pawelorzech** [comment]
Unfortunately I do have this issue. Shared hosting too, installed the newest version and whenever I go to domain.com/config it shows 404. Any ideas why this happens?

**Comment by HolgerAusB** [comment]
@pawelorzech hmm, `/config` might be a reserved keyword on that hosting service. Try an additional slash like statet above `/config/` or try `/app.php/config`. If that works, devs need to think about an alternative keyword. Meanwhile you could set your bookmark to `example.com/app.php`

**Comment by pawelorzech** [comment]
.htaccess should work - but app.php/config doesn't work too. Unfortunately.

**Comment by HolgerAusB** [comment]
But homepage works? If not: php is available in your environment? It's standard, but there are some hosters where you need to pay extra for php.

root folder is `.../wallabag/web`? If not, you maybe need `/web/config` or `/web/app.php/config`

**Comment by pawelorzech** [comment]
Homepage works, yes. PHP as well! 

This is how this folder looks like: https://share.cleanshot.com/N13jVGBZ

**Comment by HolgerAusB** [comment]
The you might open a new issue, as this is closed and provide the devs with more info, like versions of php, wallabag.

I am no dev and just guessing the easy things.
