### ISSUE TITLE
If you change the URL of your wallabag instance, all links to local images are broken

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2852]
### Issue details

When the option `Download images locally` is on 1 (in `Internal Settings` → `Misc`) and if you change `URL of *your* wallabag instance` , all links to local images are not changed to the new setting, so they are all broken.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package? make update
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS: raspbian
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case

0. Lets say your URL is `http://wallabag.name.tld`
1. In `internal settings` → `misc` → `URL of *your* wallabag instance` 
1bis. Put: `http://toto.name.tld`
2. Add an article
2bis. Notice you have a 404 error with images because links begin with `http://toto.name.tld`
3. Back to `internal settings` → `misc` → `URL of *your* wallabag instance` 
3bis. Put: `http://wallabag.name.tld`
4. Back to the previous article: your images are still 404
4bis: Note links for images are still with `http://toto.name.tld` instead of `http://wallabag.name.tld`

**Comment by j0k3r** [comment]
Could you check what's inside your folder `web/assets/images`?
What are the type of url generate for an image?

**Comment by NerosTie** [comment]
It's fixed. It was a typo in `misc`  → `url`. But I have a question: if I change the URL option, why the URL is not changed for local images? Even if I reload the article, links for images are still with the old URL. I have to delete the article then add it again.

**Comment by j0k3r** [comment]
By url, you mean the url of your wallabag instance?
Even after refetching the article or just reloading the page of the article?

**Comment by NerosTie** [comment]
> By url, you mean the url of your wallabag instance?

Yes.

> Even after refetching the article or just reloading the page of the article?

After reloading. But it's not normal.

Steps to reproduce:

0. Lets say your URL is `http://wallabag.name.tld`
1. In `internal settings` → `misc` → `URL of *your* wallabag instance` 
1bis. Put: `http://toto.name.tld`
2. Add an article
2bis. Notice you have a 404 error with images because links begin with `http://toto.name.tld`
3. Back to `internal settings` → `misc` → `URL of *your* wallabag instance` 
3bis. Put: `http://wallabag.name.tld`
4. Back to the previous article: your images are still 404
4bis: Note links for images are still with `http://toto.name.tld` instead of `http://wallabag.name.tld`

**Comment by j0k3r** [comment]
I don't know if it's easy to fix because I think we replace the link from the content by the full url of the image with the current url of your wallabag instance.
So it'll require to update all urls in all articles if you change the url of your wallabag instance..

But I agree, it's a bug which will be hard to fix.

**Comment by NerosTie** [comment]
> So it'll require to update all urls in all articles if you change the url of your wallabag instance..

Yes, it's the main issue.

> it's a bug which will be hard to fix.

Oh… I will avoid this function until a fix is found.

Should I close this issue and open a new one?

**Comment by j0k3r** [comment]
> Oh… I will avoid this function until a fix is found.

Since it affects every one who turn on that feature, we'll put a command to fix image links when we'll have fixed the bug.

And don't close it, update the title and the desc with the full disclosure of the bug, thanks.

**Comment by NerosTie** [comment]
If I change my domain, what would be the command to use?

**Comment by j0k3r** [comment]
We didn't fix that problem yet so there is no command available to fix link images when you change your domain.

**Comment by NerosTie** [comment]
I mean, can I send a sql command to the database?

**Comment by clawer87** [comment]
What worked for me was go to wallabag directory into app/config/ edit the parameters.yml domain_name to the new domain name.  Then go back to the main wallabag directory.  Run make install, answer no to clearing anything or creating any accounts.

**Comment by Qifcn** [comment]
Hello, I also encountered this problem. After the domain name is changed, the article picture is still the old domain name,

**Comment by Qifcn** [comment]
关于更改域名后文章图片还是老域名方法，远程连接数据库批量进行域名替换
使用方如下图片，如果图片不能显示请fq加速
![Snipaste_2021-11-12_00-03-47](https://user-images.githubusercontent.com/34029055/141330382-b7d51ec6-a681-4180-8cb4-5ce8e052f810.png)
法

**Comment by DonPicciotto** [comment]
I have this bug too, it seems every image is pointing to my old url instead of the new one. I already tried with a make install, and url should be correct everywhere, but it doesn't seem anything has changed. Does anyone know any workaround?

**Comment by Qifcn** [comment]
> 我也有这个错误，似乎每张图片都指向我的旧网址而不是新网址。我已经尝试过 make install，并且 url 在任何地方都应该是正确的，但似乎没有任何改变。有谁知道任何解决方法？

Hello, the picture has been clearly displayed. Use this software to connect to the database and replace the old domain names in batches. The same as the wp blog system replaces the old domain name in the article.

**Comment by fdw** [comment]
I had the same problem and fixed it like this (but be aware that this is risky and might cause problems I have missed! Have a backup ready!)
You can open the `wallabag.sqlite` database with `sqlite` and then
- change the URL for inline images with `update wallabag_entry set content = replace(content, '<old url>', '<new url>');`
- change the URL for the preview image with `update wallabag_entry set preview_image = replace(preview_image, '<old url>', <new url>')`.

Again: Do this at your own risk. But it seems to work for me so far ;)

**Comment by DonPicciotto** [comment]
> I had the same problem and fixed it like this (but be aware that this is risky and might cause problems I have missed! Have a backup ready!) You can open the `wallabag.sqlite` database with `sqlite` and then
> 
>     * change the URL for inline images with `update wallabag_entry set content = replace(content, '<old url>', '<new url>');`
> 
>     * change the URL for the preview image with `update wallabag_entry set preview_image = replace(preview_image, '<old url>', <new url>')`.
> 
> 
> Again: Do this at your own risk. But it seems to work for me so far ;)

Thanks a lot! Sadly I can't find the "preview_image" entry, but your answer give me an insight about what I could search online (I know, this should be the first thing to search, but I'm kinda stupid), and I found a very simple way to do it with mysql in this answer from stackoverflow https://stackoverflow.com/a/28016918

> Dump database to text file
> `mysqldump -u user -p databasename > ./db.sql`
> Run sed command to find/replace target string
> `sed -i 's/oldString/newString/g' ./db.sql`
> Reload the database into MySQL
> `mysql -u user -p databasename < ./db.sql`

It was extremely fast and effective!

**Comment by fdw** [comment]
> Sadly I can't find the "preview_image" entry

You're right, it should have been `preview_picture`. I've changed the original comment.

**Comment by miloumeeloo** [comment]
> What worked for me was go to wallabag directory into app/config/ edit the parameters.yml domain_name to the new domain name. Then go back to the main wallabag directory. Run make install, answer no to clearing anything or creating any accounts.

Thanks, also work with a composer update.
