### ISSUE TITLE
Minor issue with French language

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2853]
### Issue details

In an article, in the menu on the left, I have `Marquer comme non` instead of `Marquer comme non lu`.

![spectacle b10083](https://cloud.githubusercontent.com/assets/4572452/22741303/08b2278e-ee13-11e6-8a80-b9da79ca11a9.png)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Put Wallabag in French, add an article then mark it as read then open the menu on the left.

**Comment by j0k3r** [comment]
We already started sth about that https://github.com/wallabag/wallabag/pull/2713
Feel free to contribute to the discussion :slightly_smiling_face:
