### ISSUE TITLE
Saving shortened links from twitter doesn't always work

### ISSUE THREAD

**Issue by n00b12345** [wallabag/wallabag#2858]
When I'm trying to save a link like this, wallabag fails to expand it and gives me a could not retrieve error : 

https://t.co/wOo6g4EERc?ssr=true

Is there any way out?

I'm on 2.2.1

**Comment by j0k3r** [comment]
Looks like it's more related to that link instead of the t.co: http://edition.cnn.com/2017/02/08/politics/spicer-alleged-atlanta-terror-attack-trnd/index.html

**Comment by n00b12345** [comment]
Thanks. I've also had trouble with other t.co links like this one e.g.  

https://t.co/4xQVdygmna?ssr=true

Thanks for the doc links. I'll try and contribute.

**Comment by j0k3r** [comment]
Yeah, they both goes to edition.cnn.com.
http://edition.cnn.com/2017/01/26/opinions/trump-abandoning-americas-principles-aslan/index.html

So it's the same problem.

**Comment by j0k3r** [comment]
It was a problem fetching CNN I guess, it works now.
