### ISSUE TITLE
Feature request: option to disallow saving same article twice

### ISSUE THREAD

**Issue by giovi321** [wallabag/wallabag#2862]
When saving an article, sometimes (especially in the android app) the user gets no confirmation. I happen to click multiple times to make sure the article gets saved. Other times in just save the same article twice as I don't remember that I have already saved it. 
For this reason, it would be useful to have an option not to save the article if the same URL is already present in the database, in order not to have the same article saved multiple times.

**Comment by j0k3r** [comment]
This is already the case, but we have a bug about url that are redirected.
See https://github.com/wallabag/wallabag/issues/2232
