### ISSUE TITLE
Performance issue with assignTagsToEntry method

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2864]
When we use ContentProxy::assignTagsToEntry() method, we have performance issue. 

We need to investigate on this issue, but maybe it's the usage of `findOneByLabel()` when we have many tags in database (17k on wallabag.it). 

The `label` field is a longtext one, without length. I think that it's not the better way to add index on this field. 

We already have an index on `slug` field, but we don't have the slug when we call `assignTagsToEntry` (particularly when we called it during a Pocket/Pinboard import). 

Is that a good way to "slugify" the label and find the tag by slug?

**Comment by j0k3r** [comment]
Interesting!
Since the Tag slug is limited to 128 chars, maybe we can convert it to a simple `varchar(125)` and add an index on it.

**Comment by nicosomb** [comment]
That's fine for me. 
FYI, the longest tag on wallabag.it contains 61 characters.

**Comment by nicosomb** [comment]
Adding an index doesn't fix this bug. 
Need to investigate on it.

**Comment by nicosomb** [comment]
The performance issue is in `addTag` in `Entry.php`:

```
    /**
     * @param Tag $tag
     */
    public function addTag(Tag $tag)
    {
        if ($this->tags->contains($tag)) {
            return;
        }

        // check if tag already exist but has not yet be persisted
        // it seems that the previous condition with `contains()` doesn't check that case
        foreach ($this->tags as $existingTag) {
            if ($existingTag->getLabel() === $tag->getLabel()) {
                return;
            }
        }

        $this->tags->add($tag);
        $tag->addEntry($this);
    }
```

I will investigate on this method later.

**Comment by nicosomb** [comment]
FYI, I re-enabled this part of Import on wallabag.it few days ago ... and I didn't have performance issue.

**Comment by j0k3r** [comment]
All right, then we can clear the milestone and see if you got the issue again later.

**Comment by nicosomb** [comment]
The issue is still here on wallabag.it. 

@tcitworld do you have performance issues on Framabag.org during Pocket imports via RabbitMQ (or maybe imports are disabled on Framabag, I can't remember).

**Comment by tcitworld** [comment]
They are indeed disabled (that's how you fix things over here).

**Comment by nicosomb** [comment]
:trollface: Thank you for your reply.

**Comment by Kdecherf** [comment]
It could be interesting to see slow queries log
