### ISSUE TITLE
Why does f43.me manage to fetch some articles, whereas wallabag doesn’t? 

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2866]
We have so many articles which are OK in f43.me but which fail on wallabag. 

For example, http://www.theverge.com/2015/12/7/9864394/eric-schmidt-calls-for-tools-to-stop-hate-harassment-on-social-media (and we can find dozens samples like this one). 

We need to search why it fails on wallabag.

**Comment by techexo** [comment]
The given `theverge.com` articles actually now is fetched well in with 2.3.3 ;-).

**Comment by Kdecherf** [comment]
Works well with 2.3.4, I'm closing this issue.

Feel free to open a new issue if it still occurs.
