### ISSUE TITLE
Use a list, not cards, in the Material theme's list view

### ISSUE THREAD

**Issue by The0x539** [wallabag/wallabag#2867]
In list view, the content is even more homogenous than in card view, and [the use of cards](https://cloud.githubusercontent.com/assets/7350294/22866697/56c6befa-f140-11e6-82a5-f2af04250cbe.png) is distracting as compared to a [list as defined in the Material spec](https://material.io/guidelines/components/lists.html), each entry separated only by a divider line.

**Comment by nicosomb** [comment]
Done in #3077.
