### ISSUE TITLE
Parsing Mediapart articles behind the paywall doesn't work

### ISSUE THREAD

**Issue by etiess** [wallabag/wallabag#2868]
### Issue details

Thanks everybody for providing the Paywall feature (notably to @bdunogier)!

But I can't make it work for me on Mediapart. I don't know if there's a bug, or if I'm doing something wrong.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.1 
* How did you install wallabag? downloading the package
* php version: PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
* OS: Ubuntu 16.04.2 LTS
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

* Activate the function in Internal Settings / Articles
* Store the (valid) credentials in app/config/parameters.yml
* the content of my vendor/j0k3r/graby-site-config/mediapart.fr.txt is:

```
title://h1[@class="title"]
body: //div[@class="content-article"]/div[@class="page-pane"]

requires_login: yes

login_uri: https://www.mediapart.fr/login_check
login_username_field: name
login_password_field: password

not_logged_in_xpath: //body[@class="not-logged-in"]

test_url: https://www.mediapart.fr/journal/france/170116/le-site-slatefr-est-passe-entre-les-mains-du-cac-40
```

* I even tried to change the login URL in that file, as in my navigator, mediapart.fr/login_check gives an error 404, while mediapart.fr/login is OK.
* Store an article on www.mediapart.fr
* Result: the parsing doesn't give more than the beginning of the article

**Comment by j0k3r** [comment]
We'll look into it.
BTW, `https://www.mediapart.fr/login_check` answer only on POST request.

**Comment by bdunogier** [comment]
I don't have the same setup exactly, but I have added a new article from mediapart a minute ago, and it has worked fine. My `mediapart.fr.txt` is identical to yours.

**Comment by etiess** [comment]
So I did something wrong :( Should I change the permissions on something? Should I reload/restart something? In which logfile should I look to understand the issue? Thanks

**Comment by j0k3r** [comment]
You can start by updating `app/config/config_prod.yml` and switch the `error` value to `debug`.
Clear your cache `rm -rf var/cache/*`.
Try to add a new mediapart content.

Check the log in `var/log/*`

**Comment by j0k3r** [comment]
@bdunogier it could be interesting to log one line saying that authentication has been well handled or not in the graby log :slightly_smiling_face:

**Comment by etiess** [comment]
Thanks to @j0k3r , and for the record, I performed some tests, but without finding a solution:
* updated <code>app/config/config_prod.yml</code> by changing the parameter <code>action_level</code> to <code>debug</code>
* cleared my cache: <code>php bin/console cache:clear -e=prod</code>
* added a Medapart article
* the log <code>var/logs/prod.log</code> doesn't show anything special

**Comment by etiess** [comment]
Solved, thanks to @j0k3r 
I had 2 issues:
* wrong formatting of <code>app/config/parameters.yml</code> : tabs are forbidden, only spaces are allowed
* it's necessary to clear cache with <code>php bin/console cache:clear -e=prod</code> (and it may be necessary to grant the good rights on the good folders after this command)
It works now!

**Comment by tcitworld** [comment]
-> documentation ?

**Comment by etiess** [comment]
yes, I was saying to @j0k3r that I'll update the documentation with this

**Comment by etiess** [comment]
I propose these changes in the documentation:
https://github.com/wallabag/wallabag/compare/master...etiess:patch-2

**Comment by nicosomb** [comment]
OK for me. Could you also translate it in english please?

**Comment by etiess** [comment]
Yup: https://github.com/wallabag/wallabag/compare/master...etiess:patch-3

**Comment by etiess** [comment]
Closing issue. Is the modification of the documentation OK for you? Who should do the PR?
