### ISSUE TITLE
Error in cyrillic month

### ISSUE THREAD

**Issue by Kirill** [wallabag/wallabag#2870]
### Issue details
I begin to create russian translation. All translated text show correct. But automatic generated date: Since 13 February 2017 you read ... showing as 
С 13 ������� 2017 Вы прочитали 0 записей.Это приблизительно 0 в день!

### Environment

* wallabag version (or git revision) that exhibits the issue: git
* How did you install wallabag? Via `git clone` or by downloading the package?: git clone
* Last wallabag version that did not exhibit the issue (if applicable): I don't know
* php version: 5.6.30
* OS: CenOS 6
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL
![2017-02-13 15_30_36](https://cloud.githubusercontent.com/assets/302940/22885299/6ce7174a-f201-11e6-8b38-9d561bf38ccb.png)

**Comment by j0k3r** [comment]
Is it fixed?
Otherwise you can help us: https://hosted.weblate.org/languages/ru/wallabag/
