### ISSUE TITLE
Parsing full Mediapart articles while it's on several pages by default

### ISSUE THREAD

**Issue by etiess** [wallabag/wallabag#2871]
### Issue details

Mediapart displays articles on several pages. Parsing an article (for example https://www.mediapart.fr/journal/france/120217/de-laprimaireorg-charlotte-marchandise-comment-nait-une-candidature-citoyenne) leads to grabbing the first page only.

In order to see the full article on a single page, it's necessary to use a parameter <code>?onglet=full</code> in the URL:
https://www.mediapart.fr/journal/france/120217/de-laprimaireorg-charlotte-marchandise-comment-nait-une-candidature-citoyenne?onglet=full

Is it possible to modify <code>vendor/j0k3r/graby-site-config/mediapart.fr.txt</code> in order to grab the whole article? With @j0k3r , we tried to add this line:
<code>single_page_link: //link[@rel="canonical"]</code>

But it doesn't work: 
* only one picture is grabbed (no text)
* the link "Original article" points to https://www.mediapart.fr/journal/france/120217/de-laprimaireorg-charlotte-marchandise-comment-nait-une-candidature-citoyenne?onglet=full
* the reading time is large (15 minutes): this could be the real reading time of the full article

The issue is the same when I try to directly grab the URL with onglet=full  https://www.mediapart.fr/journal/france/120217/de-laprimaireorg-charlotte-marchandise-comment-nait-une-candidature-citoyenne?onglet=full

**Comment by etiess** [comment]
I tried to use http://f43.me/feed/test but as the article is behind a paywall, I couldn't. 

Then I found a free article: https://www.mediapart.fr/journal/france/150710/bettencourt-de-nouveaux-temoignages-sur-les-enveloppes-aux-politiques?onglet=full

It works on http://f43.me/feed/test but not on wallabag: only one picture grabbed, no text.

**Comment by etiess** [comment]
Hello, Were you able to reproduce this bug? And/or to find a solution? Thanks!

**Comment by j0k3r** [comment]
Could you check with that siteconfig?
It has been updated few days after the latest wallabag release: https://github.com/j0k3r/graby-site-config/pull/16/files

**Comment by etiess** [comment]
Yeah! It works 👍 ! Thank you

I just modified the siteconfig in order to put the "one page" parameter https://github.com/j0k3r/graby-site-config/pull/17

**Comment by j0k3r** [comment]
Great, thanks, this will then be available in the wallabag update!
