### ISSUE TITLE
Encoding issue on titles

### ISSUE THREAD

**Issue by kgaut** [wallabag/wallabag#2873]
### Issue details

Yesterday I imported my saved article from pocket.

It seems that there's a double encoding on title ?

Displayed : 
![2017-2-14_09 08 16-screenshot](https://cloud.githubusercontent.com/assets/736910/22920433/533e71be-f295-11e6-9a97-513a613d081b.png)

In database :
![2017-2-14_09 10 03-screenshot](https://cloud.githubusercontent.com/assets/736910/22920453/659ca894-f295-11e6-855f-8d9b36905c2f.png)

You can try by "wallabag" this page : https://linuxfr.org/users/igor--2/journaux/le-libre-et-l-experience-utilisateur it should result on : `Journal Le libre et l&#039;expérience utilisateur`

Once again the title in DB is clean : `Journal Le libre et l'expérience utilisateur`

### Environment

* Last wallabag installed on dedicated server
* How did you install wallabag:  `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.0.15
* OS: centos 7
* type of hosting : dedicated 
* which storage system you choose at install :  MySQL/MariaDB

**Comment by j0k3r** [comment]
Which version of wallabag did you run?

**Comment by kgaut** [comment]
It seems to be the 2.2.1

**Comment by j0k3r** [comment]
Ok so there is already an issue about that https://github.com/wallabag/wallabag/issues/2802
And a PR too for 2.2.2 https://github.com/wallabag/wallabag/pull/2830
