### ISSUE TITLE
Unable to tag article - article does not finish loading

### ISSUE THREAD

**Issue by sanjayankur31** [wallabag/wallabag#2881]
### Issue details

I've come across a few websites where the article doesn't stop loading - and while this is happening, one cannot tag the article either.

### Environment

* wallabag version (or git revision) that exhibits the issue: wallabag.it account holder here

### Steps to reproduce/test case

Examples:

- http://physiologyonline.physiology.org/content/22/6/358
- http://www.jneurosci.org/content/22/13/5344.full

It shouldn't be permission issues - the text of both articles is processed correctly and is present in the wallabag entry. However, the page continues to "load", and the article cannot be tagged while this is happening. Maybe it should stop loading after a bit - timeout (if something went wrong?), or tagging should be uncoupled from the display part?

**Comment by nicosomb** [comment]
I confirm that but on wallabag.it, but no locally.

**Comment by sanjayankur31** [comment]
@nicosomb - oh? I tried it locally to with the master branch and got the same issue somehow..

**Comment by nicosomb** [comment]
@sanjayankur31 Just re try on master branch too and it works fine.

**Comment by sanjayankur31** [comment]
@nicosomb -  I just did pulled from the repo, checked out master, and ran `make dev` and still get the issue. (Is that not how I should be running it?) New URL too, this time: http://biorxiv.org/content/early/2017/02/11/107706

![wallabag-dev-no-load](https://cloud.githubusercontent.com/assets/102575/22972682/a5db6aa2-f372-11e6-9b6e-fd1f5e99f723.png)

**Comment by sanjayankur31** [comment]
I've tried to create cite configs and have submitted them to the config repo as pull requests. Hopefully that'd improve things.
