### ISSUE TITLE
Feature request: Find and remove duplicate entries

### ISSUE THREAD

**Issue by Crell** [wallabag/wallabag#2884]
### Issue details

Feature request: Find and remove duplicate entries.

After stepping through #2883, repeatedly uploading the same file for import as it choked on about one of every 10 items, I now have over a dozen copies of many articles.  As in, I have 173 articles imported and nearly 1000 entries in Wallabag.  I would dearly love a non-manual way of cleaning this up. :smile: 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* php version: 7.0
* OS: Ubuntu 16.04
* type of hosting (shared or dedicated): Private linux server
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
In fact we have a critical issue about that point (thanks to url redirect etc.) https://github.com/wallabag/wallabag/issues/2232

Your issue will remind us to create a command to deduplicate entries after the duplicate bug is fixed.
