### ISSUE TITLE
Feature Request: specify tags in filters

### ISSUE THREAD

**Issue by brabalan** [wallabag/wallabag#2889]
It would be useful to be able to specify tags when using a filter, so that one could search for Unread entries matching a given tag. (This is an alternative to issue #2633.)

This of course raises the question of what to do when filtering on several tags: is it a AND or a OR?

**Comment by nicosomb** [comment]
Hello @brabalan,

It seems to be a duplicate of #1197
Feel free to reopen it if I'm wrong.

**Comment by brabalan** [comment]
Sorry, I did not see that issue (I searched for "filters" not "filtering").
