### ISSUE TITLE
Links are wrong in about page

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2891]
Links are wrong in about page:
![](http://pix.toile-libre.org/upload/original/1487168044.png)

* wallabag version (master)

**Comment by j0k3r** [comment]
Could you be more specific? What is wrong? Which one?

**Comment by ngosang** [comment]
2nd phrase hould be:

an issue lists all our needs :

**Comment by nicosomb** [comment]
Please feel free to open a new pull request to fix if.
