### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by olgsi** [wallabag/wallabag#2893]
### Issue details

With the first search wallabag doesn't find any tag or headline, with the second search i get the results.
 
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.1 
* How did you install wallabag? With Softaculous
* Last wallabag version that did not exhibit the issue (if applicable): no one
* php version: 7.0.1.5
* OS: macOS Sierra
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

I type a search in the field and get no result. If i search again, i get a result.

Thanks

**Comment by olgsi** [comment]
Thanks a lot!

**Comment by nicosomb** [comment]
Can you give us the search term and the URL which you wanted to retrieve?

**Comment by olgsi** [comment]
Hi,

i cant say why, but know wallabag find everything. :/

**Comment by nicosomb** [comment]
Fine :+1:
