### ISSUE TITLE
PHP fatal error trying to import json file

### ISSUE THREAD

**Issue by fchaix** [wallabag/wallabag#2894]
### Issue details

New installation of lastest wallabag (2.2.1). Trying to import a dump of all my articles from a json file I got from my old wallabag installation (2.1).

I get a php/Symphony error : 

`[http@kim wallabag]$ bin/console wallabag:import 1 /tmp/All\ articles.json --importer=v2
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in /home/www/wallabag/app/AppKernel.php:49
Stack trace:
#0 /home/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(403): AppKernel->registerBundles()
#1 /home/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(113): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /home/www/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(68): Symfony\Component\HttpKernel\Kernel->boot()
#3 /home/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(120): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/www/wallabag/bin/console(29): Symfony\Component\C in /home/www/wallabag/app/AppKernel.php on line 49
`

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.2.1 (commit 92995138fb84be1a54201b7a2af7ce5a12946fa1)**
* How did you install wallabag? Via `git clone` or by downloading the package? : **git clone**
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 
`[http@kim wallabag]$ php -v
PHP 7.0.10 (cli) (built: Aug 21 2016 07:35:18) ( NTS )`
* OS: Archlinux (more or less) up to date
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Fresh 2.2.1 installation, run :
`bin/console wallabag:import 1 /tmp/All\ articles.json --importer=v2`
With my json file (do I have to attach it ?)

**Comment by j0k3r** [comment]
You forgot the `-e=prod` parameter in the command.
