### ISSUE TITLE
UI issue on Chrome when adding a link

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#2898]
### Issue details

With Chrome (not Firefox), when I click on the "+" button to add a link, the input bar is kind of broken. See image below:

![wb-add-bar](https://cloud.githubusercontent.com/assets/3419050/23026003/1a4310aa-f460-11e6-8323-8e72a819ee26.png)

I tried resizing my browser's window but the issue always appears.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.0
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): NA

### Steps to reproduce/test case

1. Use Chrome
1. Click on the "+" button to add a link

**Comment by nicosomb** [comment]
It seems that it's the same bug than this one fixed by @kdecherf https://github.com/wallabag/wallabag/pull/2818
