### ISSUE TITLE
Makefile not included in 2.0.8 release?

### ISSUE THREAD

**Issue by TheFu** [wallabag/wallabag#2899]
### Issue details

Upgrade instructions say to use **make upgrade**, but since there isn't a makefile/Makefile included in the release (at least not what we have here), that isn't useful.  Was there something wrong with our installation that it was missing the Makefile?

Manually migrated to 2.1.x ... to get a Makefile.
Then manually moved to 2.2.1, because I was on a roll.

**Comment by nicosomb** [comment]
You're right, the documentation is only for 2.1.x to 2.2.x. 
Because we miss time, we don't maintain upgrade instructions for all of our versions.

Do we need to keep this issue opened?

**Comment by TheFu** [comment]
Ah - I see that now that you point it out.  http://doc.wallabag.org/en/master/user/upgrade.html#upgrade-from-2-0-x-to-2-1-1 for any lurkers.

BTW, is there an easy way to know which release is being run?  I looked for about 30 min and only found a CHANGELOG file which told me I was running 2.1.0, but clearly without a Makefile, I wasn't.  Seems I'd attempted a 2.1.0 upgrade previously (unknown how much of that was attempted), but didn't complete it.

**Comment by nicosomb** [comment]
You have a About page, available in the footer of your wallabag.

**Comment by TheFu** [comment]
Ah ... the About page.  Haven't made it to the bottom of my reading list in months, so don't see that part of the screen much. ;)
Thanks for the help.
