### ISSUE TITLE
On demand paywall authentication

### ISSUE THREAD

**Issue by bdunogier** [wallabag/wallabag#2901]
This is more of a reminder to myself, but if somebody wants to give it a try...

The reason why paywall won't work with a shared wallabag is that credentials are stored in a yaml file. There is a first implementation in a pull-request, but as an alternative, or as a cheaper solution in the meanwhile, we could quite easily do on-demand authentication:

When an article is fetched from a site with a paywall, and we aren't authenticated, we can ask for the login & password in real time (more work on the android version). We use those to login, the usual way, and the credentials are stored in the cookie jar. They won't be asked until the session expires.

It shouldn't be too invasive nor complicated.

**Comment by nicosomb** [comment]
Good idea but how will you detect that your website requires authentication?

**Comment by tcitworld** [comment]
@nicosomb there's `requires_login` in the conf file.

**Comment by bdunogier** [comment]
> @nicosomb there's requires_login in the conf file.

Yes, it implies that we have a configuration for the site.

**Comment by nicosomb** [comment]
Fixed in 2.3.0.
