### ISSUE TITLE
Image misalignment in share links

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2902]
### Issue details
Image misalignment in share links
![](http://pix.toile-libre.org/upload/original/1487318202.png)

### Environment
* wallabag master

**Comment by ngosang** [comment]
Bonus, a bit more space:
![](http://pix.toile-libre.org/upload/original/1487318347.png)

**Comment by theotix** [comment]
@ngosang What do you thing about make more space on "public link", "delete public link" and "twitter" rather than remove space on links you highlighted?

**Comment by ngosang** [comment]
> What do you thing about make more space on "public link", "delete public link" and "twitter" rather than remove space on links you highlighted?

I agree.

**Comment by nicosomb** [comment]
Fixed thanks to @tcitworld.

![capture d ecran 2017-06-13 a 17 22 05](https://user-images.githubusercontent.com/121870/27090206-ddff2fe4-505c-11e7-92c7-8b31b37dcc28.png)


![capture d ecran 2017-06-13 a 17 22 41](https://user-images.githubusercontent.com/121870/27090231-ee24aaf2-505c-11e7-8619-7cde3e06969c.png)
