### ISSUE TITLE
Huge text in elmundo.es articles

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2903]
### Issue details

elmundo.es is the 2nd most read news paper in Spain and this is happening in most articles.
Example URL => http://www.elmundo.es/espana/2017/02/17/58a6173c268e3e8f138b45a7.html
![](http://pix.toile-libre.org/upload/original/1487319147.png)

### Environment

* wallabag master

**Comment by ngosang** [comment]
More info => Firefox 51 @ Linux

**Comment by techexo** [comment]
@ngosang Is the problem still present with an updated version of wallabag? I had no problem fetching this particular article with 2.3.3.

**Comment by ngosang** [comment]
I can't reproduce anymore.
