### ISSUE TITLE
Nautil.us articles not correctly fetched

### ISSUE THREAD

**Issue by bernardryefield** [wallabag/wallabag#2912]
Article from nautil.us are not fetched correctly (only some irrelevant titles from other article)

### Environment

* wallabag version 1.9.1 (Framabag)

### Steps to reproduce/test case

tested ok on http://f43.me/feed/test
try to fetch any article from this site

**Comment by j0k3r** [comment]
Did you test it under wallabag2?

**Comment by bernardryefield** [comment]
no, I didn't test it under Wallabag 2

**Comment by j0k3r** [comment]
And it works fine on wallabag 2

![image](https://cloud.githubusercontent.com/assets/62333/23133827/cbf4d2ae-f792-11e6-8e2f-7ce5af3b8b32.png)

Siteconfig won't be updated for wallabag 1.x
We encourage you to upgrade to wallabag 2.
