### ISSUE TITLE
fails to render articles on simplenote.com

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabag#2914]
### Issue details

[This article](https://app.simplenote.com/publish/bKHZCC) fails to fetch completely in wallabag:

I get this error on reload: "Entry reloaded but fetching content failed", and the body says: " wallabag can't retrieve contents for this article. Please troubleshoot this issue." which pointed me to file an issue because the site renders fine in [f43.me](http://f43.me/feed/test).

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? package?
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: 7.0
* OS: Debian GNU/Linux jessie 8.7
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL 5.5.50

### Steps to reproduce/test case

Add the article to wallabag. Be sad. Try it on f43.me, be less sad. File a bug.

**Comment by techexo** [comment]
The article is perfectly fetched on my wallabag 2.3.3. @anarcat could you check on an updated version if you still encounter the issue?

**Comment by anarcat** [comment]
i can reproduce with 2.3.2, i'll let you know when my provider upgrades! :)

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
