### ISSUE TITLE
Allow export of all articles even under low memory limit

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2921]
### Issue details

My php is configured to have a memory_limit of 128M. I wanted to export all articles as json, but ran into a OOM:

```
500: Internal Server Error
Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 29447353 bytes)
```
Of course easiest solution would be to increase memory limit, but in some environments this is not possible. Isn't there a way to use less memory for the export of all articles?

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:5.6.30-0+deb8u1
* OS:debian jessie
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):mysql

### Steps to reproduce/test case

1. add ~3000 articles to wallabag
1. configure php to limit its memory
2. go to export as json of all articles https://wallabag.asdf.de/export/all.json?tag=
4. see the above mentioned error message

**Comment by nicosomb** [comment]
Hey @Strubbl ! 

Do https://github.com/wallabag/wallabag/issues/1927 and https://github.com/wallabag/wallabag/issues/2560 seem to be a solution for your issue? 
If yes, I think you can close it.

**Comment by Strubbl** [comment]
Yes, #1927 looks like the solution for that issue also solves my problem. --> Closing
