### ISSUE TITLE
Truncated article on qz.com

### ISSUE THREAD

**Issue by CyrilBrulebois** [wallabag/wallabag#2927]
### Issue details

Importing the following article from qz.com through wallabag.it only led to the first 3 paragraphs being imported → https://qz.com/884448/every-successful-relationship-is-successful-for-the-same-exact-reasons/

I've tried “Re-fetch content”, which triggered no changes.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package? Hosted by wallabag.it
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: ?
* OS: ?
* type of hosting (shared or dedicated): ?
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): ?

### Steps to reproduce/test case

Import the article mentioned above, and notice 3 paragraphs for an announced 44 minutes reading session.

**Comment by techexo** [comment]
No problem fetching the full-length article with wallabag 2.3.3. @CyrilBrulebois, could you check with an updated version of wallabag?

**Comment by CyrilBrulebois** [comment]
Thanks for pinging back; the version deployed on https://app.wallabag.it/ indeed doesn't have this issue any longer, just checked by re-fetching the article.
