### ISSUE TITLE
web client: missing navigation to next or previous article, wrong action on "back" button

### ISSUE THREAD

**Issue by aisbergde** [wallabag/wallabag#2928]
### Issue details
when I use the web client and read an article then I can't find a way navigate to the next (previous) article. I ned to use the back arrow of the browser to go to the overview where I have been before. 

Using "Back" works wrong, it doesn't go back but to "unread" articles. Even if I was in another section before or when I did a search.
 
### Environment
wallabag.it

### Steps to reproduce/test case
do a search
select an article
search for some button or shortcut to go to the next article (arrows will not work)
use "Back" button and you will landing on "unread"

**Comment by nicosomb** [comment]
Hello @aisbergde. 

What is your prefered behavior? 
Arrows or `n`/`p` keys (for next/previous)?

**Comment by nicosomb** [comment]
Duplicate of https://github.com/wallabag/wallabag/issues/1993.
