### ISSUE TITLE
Do not scale images in article list

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2937]
Do not scale images in article list. Would be better to show a little image centred.
![](http://pix.toile-libre.org/upload/original/1488190444.png)
URL: http://www.investopedia.com/university/introduction-stock-trader-types/conclusion.asp

* wallabag master

**Comment by j0k3r** [comment]
Looks like it's fixed:
![image](https://user-images.githubusercontent.com/62333/58963482-8a3f3180-87ad-11e9-943f-54e2a72cbdb4.png)

**Comment by tcitworld** [comment]
It's probably just the website adding new metadata pictures. We should have a look with an other example.

**Comment by ngosang** [comment]
@j0k3r I don't see this problem in newer versions. You can close.
