### ISSUE TITLE
Article-specific fetching problem

### ISSUE THREAD

**Issue by fchaix** [wallabag/wallabag#2938]
### Issue details

Problem fetching 1 article from mademoiselle.com. I tried a few articles from the same website, it works well.
Something in the article brokes the parser, I guess it is interesting to report it.

The url : http://www.madmoizelle.com/couple-deux-copains-temoignage-287404

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* php version: 7.0.10
* OS: archlinux
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Try to fetch this article : http://www.madmoizelle.com/couple-deux-copains-temoignage-287404

**Comment by tcitworld** [comment]
Works with f43.me. Specific to wallabag.

**Comment by fchaix** [comment]
Sorry, works now. I don't understand what was wrong before…

**Comment by tcitworld** [comment]
Indeed. Most probably an issue with the website itself.
