### ISSUE TITLE
Export the result of a search

### ISSUE THREAD

**Issue by Zlitus** [wallabag/wallabag#2945]
Actually we can export “Unread”, “Starred”, “Archive” and “All entries”, should be very great if we can also make a search and export the results of the search.

**Comment by Matoo125** [comment]
this seems to be an essential feature to me, as I read on my kindle and use wallabag for management

**Comment by Kdecherf** [comment]
This issue seems to have been addressed by #2543 (for searches from the search bar)

Closing it.
