### ISSUE TITLE
implement saving of reflowed PDF files

### ISSUE THREAD

**Issue by janLo** [wallabag/wallabag#2951]
It would be useful to be able to add PDF files to wallabag. The text could be extracted with tools like [pdfreflow](https://sourceforge.net/projects/pdfreflow/) or similar.

**Comment by j0k3r** [comment]
The text is already extracted for a PDF url.

**Comment by janLo** [comment]
But it does not really work. I used http://www.cs.vu.nl//~herbertb/download/papers/anc_ndss17.pdf as an example.

**Comment by nicosomb** [comment]
This PDF seems to be a secured file, @j0k3r is right. 
I close this issue, we can't parse these PDF files for now.

**Comment by janLo** [comment]
What do you mean with a secured file? And why not leave it open as a feature request?

**Comment by j0k3r** [comment]
I don't know this is the result from the lib we use.
Maybe open an issue on their side?
