### ISSUE TITLE
Applying new tagging rules on existing content

### ISSUE THREAD

**Issue by Simounet** [wallabag/wallabag#2953]
It could be great having an option to apply a new tagging rule to existing content.

**Comment by j0k3r** [comment]
It would better be a command I think. This kind of action could be quite long if people have a lot of entries.

But regarding wallabag.it (people can't launch a cli command on it) I think we should add:

- an option to re-apply a tagging rule (I wonder if we can re-apply only one tagging rule or all of them) and warn user that it might take sometimes (what if the page timeout during the re-tagging?)
- if the async import is enabled, make the re-apply async instead (which means we should move that async import option out of the import section, might be interesting in the future to have other async actions (like https://github.com/wallabag/wallabag/issues/1927))

**Comment by nicosomb** [comment]
This command already exists, right? 

`bin/console wallabag:tag:all -e=prod`

**Comment by jamietanna** [comment]
Can confirm that @nicosomb was correct, the following worked on my Docker instance:

```bash
DOCKER_IMAGE_NAME=wallabag
WALLABAG_USERNAME=jamietanna
docker exec $DOCKER_IMAGE_NAME /var/www/wallabag/bin/console wallabag:tag:all -e=prod $WALLABAG_USERNAME
```

However, it would be great if this could be exposed via the web UI such that users who don't have shell+Docker access are able to apply these tagging rules themselves.

**Comment by j0k3r** [comment]
But launching a command from the UI isn't the recommend way to do that.

Maybe we can use a queue to handle tagging rule changes and re-apply rules on each update (by publishing a new message).
So, user won't have to trigger the system itself, it'll be automatic.

**Comment by jamietanna** [comment]
Agreed we wouldn't want to be shelling out if we can avoid it - the running of the command can be a workaround for now.

Having it automatic would be nice.

**Comment by lapineige** [comment]
> Maybe we can use a queue to handle tagging rule changes and re-apply rules on each update (by publishing a new message).

But that could be very long, isn't it ?
And slow down the process of adding multiple tagging rules.

**Comment by Edo78** [comment]
I don't know if in all these years something changed but this command isn't working for me.
> This command already exists, right?
> 
> `bin/console wallabag:tag:all -e=prod`

I have to use `bin/console wallabag:tag:all --env=prod` as specified [here](https://doc.wallabag.org/en/admin/console_commands.html)

**Comment by j0k3r** [comment]
@Edo78 I've updated the comment. The `-e` got removed some times ago.
