### ISSUE TITLE
Update fails, but continues the update process

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2957]
### Issue details

When doing an update and a step in the update script `scripts/update.sh` fails, the script does not abort. It continues to run. 

excerpt of `scripts/update.sh`:
```
SYMFONY_ENV=$ENV $COMPOSER_COMMAND install --no-dev -o --prefer-dist
php bin/console doctrine:migrations:migrate --no-interaction --env=$ENV
php bin/console cache:clear --env=$ENV
```

When the script fails in the first line due to my special composer installation, it just goes on to the next line and continues the update. So far nothing worse has happend to my wallabag database, but i fear this can harm. And also it is annoying to see the error and to wait until the script finishes.

My suggestion is to `set -e` to the bash script. And while we are in the script, we can also introduce `set -u`. 
Does that make sense to you?

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

`make update` and composer.phar being not in the typical locations.

**Comment by nicosomb** [comment]
I'm not a shell expert. @tcitworld any opinion?

**Comment by nicosomb** [comment]
@Kdecherf any opinion on this issue?.

**Comment by Kdecherf** [comment]
Let's go for `set -e` and `set -u`

**Comment by nicosomb** [comment]
Do you want to fix this issue? 😊
