### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2958]
### Issue details
Add to wallabag => https://docs.mesosphere.com/1.8/overview/high-availability/
Preview picture will be => https://test-mesosphere-documentation.pantheonsite.io/wp-content/uploads/2016/01/facebook-share-default.png
And you will see an alert in wallabag.
![2017-03-02 20_50_46-high availability - mesosphere dc_os documentation docs mesosphere com walla](https://cloud.githubusercontent.com/assets/10577978/23524252/0fcc4044-ff8a-11e6-98d7-617e3a3214ca.png)

### Environment
* wallabag master

**Comment by nicosomb** [comment]
It's not a security issue. 

If you try to access to the picture, you also have this popup. 
It's not a wallabag issue.
