### ISSUE TITLE
article import fails on smiley face

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabag#2959]
### Issue details

[This article](https://grisebouille.net/fairphone-un-telephone-pour-libriste/) cuts off at the first emoji symbol (`🙂`) in the text, in this sentence: `Le logiciel n’est pas des plus sexy (pas de doute, on est bien chez la FSF 🙂 ) mais il fait le boulot très bien.` In wallabag, the article seems to stop at `FSF`.

Doesn't happen on http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.5
* How did you install wallabag? Via `git clone` or by downloading the package? package?
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: 7.0
* OS: Debian GNU/Linux jessie 8.7
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL 5.5.50

### Steps to reproduce/test case

1. Load this article in wallabag: https://grisebouille.net/fairphone-un-telephone-pour-libriste/
2. Rejoice at the limitless chaos of the computing world :-)

**Comment by j0k3r** [comment]
Your MySQL version is too old.
You need at least MySQL 5.7 to support emoji (and avoid these problem).

**Comment by nicosomb** [comment]
I close this issue, because it's a MySQL one. 
Feel free to reopen if necessary.

**Comment by jcharaoui** [comment]
I think that to support emoji, the database character set just needs to be `utf8mb4`, instead of `utf8`. Four-byte UTF-8 character support exists in MySQL since [5.5.3](https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html).

What else is needed to support emoji, and only available in MySQL 5.7 ?
