### ISSUE TITLE
Error 500 with fresh install

### ISSUE THREAD

**Issue by siSSSou** [wallabag/wallabag#2962]
**Try to install Wallabag v2 : all I get is a 500 error (white page) :**

**cat /var/log/nginx/wallabag-error.log**
`2017/03/04 17:03:26 [error] 8463#0: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/wallabag/vendor/friendsofsymfony/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml&quot; in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/wallabag/vendor/friendsofsymfony/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml&quot; in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Fatal error:  Uncaught exception 'Doctrine\Common\Persistence\Mapping\MappingException' with message 'Invalid mapping file 'FOS.OAuthServerBundle.Entity.Client.orm.xml' for class 'FOS\OAuthServerBundle\Entity\Client'.' in /var/www/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86
Stack trace:
#0 /var/www/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\Common\Persistence\Mapping\MappingException::invalidMappingFile('FOS\\OAuthServer...', 'FOS.OAuthServer...')
#1 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\Common\Persistence\Mapping\Driver\FileDriver->getElement('FOS\\OAuthServer...')
#2 /var/www/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMetadataForClass('FOS\\OAuthServer...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#3 /v", client: 192.168.0.254, server: wallabag.roger1.fr, request: "GET / HTTP/1.1", host: "wallabag.roger1.fr"
`

**cat /var/log/nginx/wallabag-access.log**
`192.168.0.254 - - [04/Mar/2017:17:03:26 +0100] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/603.1 (KHTML, like Gecko) Version/10.0 Safari/603.1 Debian/9.0 (3.22.6-1) Epiphany/3.22.6"
`

**/etc/nginx/conf.d/wallabag.conf**
`server {

	listen 80;
	server_name wallabag.roger1.fr;  
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	server_name wallabag-server.name;
	root /var/www/wallabag/web;

	add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
	add_header X-Content-Type-Options nosniff;
	add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

	location / {
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
	
	location ~ ^/app\.php(/|$) {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
	fastcgi_buffers 16 16k;
	fastcgi_buffer_size 32k;
	fastcgi_cache nginxcache;
	fastcgi_cache_key $request_method$host$request_uri;
	fastcgi_cache_valid any 1h;
	fastcgi_intercept_errors on;

        fastcgi_param  SCRIPT_FILENAME  $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        # Prevents URIs that include the front controller. This will 404:
        # http://domain.tld/app.php/some-path
        # Remove the internal directive to allow URIs like this
        internal;
    }

	error_log /var/log/nginx/wallabag-error.log error;
	access_log /var/log/nginx/wallabag-access.log combined;
}
`

### Environment

* wallabag version : 2.2
* How did you install wallabag? Via `git clone`
* php version: 5.6
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): tried both MySQL and SQLite

### Steps to reproduce/test case

Follow the documentation to install wallabag

**Comment by j0k3r** [comment]
It's a known issue: https://github.com/wallabag/wallabag/issues/1828#issuecomment-205241568

@nicosomb maybe we can put something in the documentation about that recurring error.

**Comment by nicosomb** [comment]
You mean ... http://doc.wallabag.org/en/master/user/faq.html#i-ve-got-the-failed-to-load-external-entity-error-when-i-try-to-install-wallabag ? 😁
