### ISSUE TITLE
provide title field in entries listing response

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabag#2965]
Working with the API, i noticed that the fields sent from the `GET /api/entries/FOO.json` and `GET /api/entries.json` endpoints vary. Could those be harmonized? In particular, I need the `title` field in `/api/entries.json` in this specific case...

**Comment by anarcat** [comment]
it would also be nice if the API could document what is part of the response...

**Comment by j0k3r** [comment]
Could you please be more specifig about which fields is on which side and which one is missing, etc?

**Comment by anarcat** [comment]
`GET /api/entries.json` yields an `_embedded` field that is a list of `items` like this:

```
// Item represents individual items in API responses
type Item struct {
	Links       Links         `json:"_links"`
	Annotations []interface{} `json:"annotations"`
	CreatedAt   WallabagTime  `json:"created_at"`
	DomainName  string        `json:"domain_name"`
	ID          int           `json:"id"`
	IsArchived  int           `json:"is_archived"`
	IsStarred   int           `json:"is_starred"`
	Mimetype    string        `json:"mimetype"`
	ReadingTime int           `json:"reading_time"`
	Tags        []interface{} `json:"tags"`
	UpdatedAt   WallabagTime  `json:"updated_at"`
	UserEmail   string        `json:"user_email"`
	UserID      int           `json:"user_id"`
	UserName    string        `json:"user_name"`
}
```

There may be fields missing there - i don't have a dump of a request handy because I'm too late in the development cycle... This is a Wallabago (the Go API) datastructure and while I have tried to make sure it covers all the fields in that peculiar API call (see https://github.com/Strubbl/wallabago/pull/2 for that patch), I may have missed some.

I do have a dump of a request I did during development in [here](https://gitlab.com/anarcat/wallabako/blob/1a2e3e5b7e13da20ad3ceaff4e4d5a6c847e31cf/main.go#L79), but I'm not sure how accurate it is:

```
{
  "page": 1,
  "limit": 30,
  "pages": 3,
  "total": 64,
  "_links": {
    "self": {
      "href": "https://example.net/wallabag/api/entries?archive=0&sort=created&order=desc&tags=&since=0&page=1&perPage=30"
    },
    "first": {
      "href": "https://example.net/wallabag/api/entries?archive=0&sort=created&order=desc&tags=&since=0&page=1&perPage=30"
    },
    "last": {
      "href": "https://example.net/wallabag/api/entries?archive=0&sort=created&order=desc&tags=&since=0&page=3&perPage=30"
    },
    "next": {
      "href": "https://example.net/wallabag/api/entries?archive=0&sort=created&order=desc&tags=&since=0&page=2&perPage=30"
    }
  },
  "_embedded": {
    "items": [
      {
        "is_archived": 0,
        "is_starred": 0,
        "user_name": "joe",
        "user_email": "joe@example.com",
        "user_id": 3,
        "tags": [],
        "id": 23152
        "created_at": "2014-06-13T12:18:34-0400",
        "updated_at": "2016-11-29T20:02:16-0500",
        "annotations": [],
        "mimetype": "text/html",
        "reading_time": 5,
        "domain_name": "arstechnica.com",
        "_links": {
          "self": {
            "href": "/api/entries/1579"
          }
        }
      }
    ]
  }
}
```

notice that there is no `Title` field in there, which is the field i am looking for. to resolve this, i made a separate request to `/GET /api/entries/1234.json` which yields something like:

```
{
  "is_archived": 0,
  "is_starred": 0,
  "user_name": "joe",
  "user_email": "joe@example.org",
  "user_id": 3,
  "tags": [
    {
      "id": 1,
      "label": "toread",
      "slug": "toread"
    },
  ],
  "id": 923,
  "title": "Example website",
  "url": "http://example.com/",
  "content": "<div id=\"readabilityBody\"><div>[...]content[...]</div></div>",
  "created_at": "2015-08-24T00:35:45-0400",
  "updated_at": "2017-02-22T11:06:20-0500",
  "annotations": [],
  "mimetype": "text/html",
  "reading_time": 11,
  "domain_name": "example.com",
  "_links": {
    "self": {
      "href": "/api/entries/923"
    }
  }
}
```

the extra fields I see here that are missing in the `embedded` entry are:

* `title`
* `url`
* `content`

I don't really need `content`: it's rather big and could impact performance (see also #2817 for that specific yak to shave). But I don't see why `title` and `url` are not shipped along...

should i open a separate issue for the API documentation question?

(BTW, it would be way more convenient if we could access the API through the browser without sending those special headers: it would allow people to directly test the API more easily than having to negociate temporary tokens. I guess just something to keep in mind in #2800? not sure. maybe another issue as well?)

thank you for your time.

**Comment by j0k3r** [comment]
Looks like the title exist in both response now.
