### ISSUE TITLE
remove a tag from a given post without returning to main page

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#2969]
### Issue details

when we drop a tag from a post, we go back to the unread posts
it will be better if we could stay on that post itself, couldnt we ?

### Environment

* wallabag version (or git revision) that exhibits the issue:Version: 2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 7
* OS: debian 8.5
* type of hosting (shared or dedicated): dedi
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): pgsql

### Steps to reproduce/test case

remove a tag from a post and see ;)

**Comment by brabalan** [comment]
You can configure Wallabag to not do that by choosing “Where do you want to be redirected after mark an article as read?“ to be “To the current page”.

I would also like both settings to be distinguished (i.e., removing a tag and marking a page read).

**Comment by foxmask** [comment]
where is that configuration option ?
for the tag purpose I already open an issue earlier this year ;)

**Comment by brabalan** [comment]
On the main page, you click on “Config” on the left-hand side, then in the “Settings” tab (the first one, opened by default), it's the fourth item.

**Comment by foxmask** [comment]
Fine ! I didnt See it . Thanks

**Comment by j0k3r** [comment]
Can we close that issue then?

**Comment by foxmask** [comment]
Yes. Thanks
