### ISSUE TITLE
500 error after upgrading from 2.1.5 to 2.2.2 on a SQLite setup

### ISSUE THREAD

**Issue by bitmagewb** [wallabag/wallabag#2972]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Upgraded in place using make update and php bin/console doctrine:migrations:migrate --no-interaction -e=prod.  No errors seen during update.

I can login, but then I get:

500: Internal Server Error

An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT w0_.id AS id_0, w0_.uid AS uid_1, w0_.title AS title_2, w0_.url AS url_3, w0_.is_archived AS is_archived_4, w0_.is_starred AS is_starred_5, w0_.content AS content_6, w0_.created_at AS created_at_7, w0_.updated_at AS updated_at_8, w0_.mimetype AS mimetype_9, w0_.language AS language_10, w0_.reading_time AS reading_time_11, w0_.domain_name AS domain_name_12, w0_.preview_picture AS preview_picture_13, w0_.is_public AS is_public_14, w0_.http_status AS http_status_15, w0_.user_id AS user_id_16 FROM "wallabag_entry" w0_ WHERE w0_.user_id = ? AND w0_.is_archived = 0 AND w0_.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ORDER BY w0_.created_at DESC' with params [2, "638", "637", "636", "635", "634", "632", "631", "630", "625", "624", "623", "622", "621", "619", "618", "617", "615", "612", "611", "610", "609", "608", "607", "605", "604", "603", "601", "599", "598", "597"]: SQLSTATE[HY000]: General error: 1 no such column: w0_.http_status").

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? Upgrading previous ver that was installed with git clone.
* Last wallabag version that did not exhibit the issue (if applicable): 2.1.5
* php version: 5.5.38
* OS: CentOS 6.8
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Run make update and php bin/console doctrine:migrations:migrate --no-interaction -e=prod in 2.1.5 wallabag dir, then try to login.  500 error occurs.  Reverting to backup of 2.1.5 restores functionality.

**Comment by tcitworld** [comment]
No special output while running `make update` ?

**Comment by bitmagewb** [comment]
Nothing that looks like an error.  It prompted for several new parameters, I accepted the defaults.  Full output below:
-bash-4.1$ make update
composer.phar not found, we'll see if composer is installed globally.
remote: Counting objects: 1881, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 1881 (delta 897), reused 890 (delta 890), pack-reused 965
Receiving objects: 100% (1881/1881), 460.32 KiB, done.
Resolving deltas: 100% (1227/1227), completed with 241 local objects.
From https://github.com/wallabag/wallabag
 * [new branch]      2.3        -> origin/2.3
 * [new branch]      2.3-droping-5.5 -> origin/2.3-droping-5.5
 * [new branch]      add-index-entry-url -> origin/add-index-entry-url
 + dcfe2fc...0b6d917 add-user-group -> origin/add-user-group  (forced update)
 * [new branch]      cleanduplicatescommand -> origin/cleanduplicatescommand
 * [new branch]      credentials-in-db -> origin/credentials-in-db
   625bb56..3f5f303  master     -> origin/master
 + 573947a...10d43f8 progress   -> origin/progress  (forced update)
 * [new branch]      save-changes -> origin/save-changes
From https://github.com/wallabag/wallabag
 * [new tag]         2.1.6      -> 2.1.6
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 14 (delta 8), reused 8 (delta 8), pack-reused 3
Unpacking objects: 100% (14/14), done.
From https://github.com/wallabag/wallabag
 * [new tag]         2.1.6.1    -> 2.1.6.1
 * [new tag]         2.2.0      -> 2.2.0
 * [new tag]         2.2.1      -> 2.2.1                                                                                                               
 * [new tag]         2.2.2      -> 2.2.2
Previous HEAD position was 90352b4... Release wallabag 2.1.5
HEAD is now at 90e74c6... Release wallabag 2.2.2
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
  - Removing lexik/maintenance-bundle (v2.1.1)
  - Removing twig/twig (v1.28.1)
  - Installing twig/twig (v1.32.0)
    Downloading: 100%         

  - Removing symfony/symfony (v3.1.7)
  - Installing symfony/symfony (v3.2.4)
    Downloading: 100%         

  - Removing doctrine/common (v2.6.1)
  - Installing doctrine/common (v2.6.2)
    Downloading: 100%         

  - Removing doctrine/dbal (v2.5.5)
  - Installing doctrine/dbal (v2.5.12)
    Downloading: 100%         

  - Removing doctrine/migrations (1.4.1)
  - Installing doctrine/migrations (v1.5.0)
    Downloading: 100%         

  - Removing doctrine/doctrine-bundle (1.6.4)
  - Installing doctrine/doctrine-bundle (1.6.7)
    Downloading: 100%         

  - Removing doctrine/doctrine-migrations-bundle (v1.2.0)
  - Installing doctrine/doctrine-migrations-bundle (v1.2.1)
    Downloading: 100%         

  - Removing friendsofsymfony/rest-bundle (2.1.0)
  - Installing friendsofsymfony/rest-bundle (2.1.1)
    Downloading: 100%         

  - Removing gedmo/doctrine-extensions (v2.4.24)
  - Installing gedmo/doctrine-extensions (v2.4.26)
    Downloading: 100%         

  - Removing hoa/exception (1.16.11.08)
  - Installing hoa/exception (1.17.01.16)
    Downloading: 100%         

  - Removing hoa/consistency (1.16.03.03)
  - Installing hoa/consistency (1.17.01.10)
    Downloading: 100%         

  - Removing hoa/event (1.16.11.19)
  - Installing hoa/event (1.17.01.13)
    Downloading: 100%         

  - Removing hoa/iterator (2.16.11.19)
  - Installing hoa/iterator (2.17.01.10)
    Downloading: 100%         

  - Removing hoa/visitor (2.16.01.11)
  - Installing hoa/visitor (2.17.01.16)
    Downloading: 100%         

  - Removing hoa/ustring (4.16.01.11)
  - Installing hoa/ustring (4.17.01.16)
    Downloading: 100%         

  - Removing hoa/protocol (1.16.07.07)
  - Installing hoa/protocol (1.17.01.14)
    Downloading: 100%         

  - Removing hoa/zformat (1.16.03.15)
  - Installing hoa/zformat (1.17.01.10)
    Downloading: 100%         

  - Removing hoa/regex (1.16.09.06)
  - Installing hoa/regex (1.17.01.13)
    Downloading: 100%         

  - Removing hoa/math (1.16.08.29)
  - Installing hoa/math (1.17.01.13)
    Downloading: 100%         

  - Removing hoa/stream (1.16.11.08)
  - Installing hoa/stream (1.17.02.21)
    Downloading: 100%         

  - Removing hoa/file (1.16.01.15)
  - Installing hoa/file (1.17.01.13)
    Downloading: 100%         

  - Removing hoa/compiler (3.16.10.24)
  - Installing hoa/compiler (3.17.01.10)
    Downloading: 100%         

  - Removing hoa/ruler (2.16.10.24)
  - Installing hoa/ruler (2.17.01.13)
    Downloading: 100%         

  - Removing tecnickcom/tcpdf (6.2.12)
  - Installing wallabag/tcpdf (6.2.15)
    Downloading: 100%         

  - Removing monolog/monolog (1.21.0)
  - Installing monolog/monolog (1.22.0)
    Downloading: 100%         

  - Removing j0k3r/php-readability (1.1.3)
  - Installing j0k3r/php-readability (1.1.6)
    Downloading: 100%         

  - Removing j0k3r/graby-site-config (1.0.28)
  - Installing j0k3r/graby-site-config (1.0.32)
    Downloading: 100%         

  - Removing react/promise (v2.4.1)
  - Installing react/promise (v2.5.0)
    Downloading: 100%         

  - Removing j0k3r/graby (1.5.1)
  - Installing j0k3r/graby (1.6.0)
    Downloading: 100%         

  - Removing javibravo/simpleue (1.0.0)
  - Installing javibravo/simpleue (1.1.1)
    Downloading: 100%         

  - Removing jms/metadata (1.5.1)
  - Installing jms/metadata (1.6.0)
    Downloading: 100%         

  - Removing jms/serializer (1.4.2)
  - Installing jms/serializer (1.5.0)
    Downloading: 100%         

  - Removing jms/serializer-bundle (1.1.0)
  - Installing jms/serializer-bundle (1.2.0)
    Downloading: 100%         

  - Removing kphoen/rulerz (0.19.1)
  - Installing kphoen/rulerz (0.19.3)
    Downloading: 100%         

  - Removing kphoen/rulerz-bundle (0.12.1)
  - Installing kphoen/rulerz-bundle (0.13.1)
    Downloading: 100%         

  - Removing doctrine/orm (v2.5.5)
  - Installing doctrine/orm (v2.5.6)
    Downloading: 100%         

  - Removing lexik/form-filter-bundle (v5.0.1)
  - Installing lexik/form-filter-bundle (v5.0.3)
    Downloading: 100%         

  - Removing liip/theme-bundle (1.4.1)
  - Installing liip/theme-bundle (1.4.6)
    Downloading: 100%         

  - Removing nelmio/api-doc-bundle (2.13.0)
  - Installing nelmio/api-doc-bundle (2.13.1)
    Downloading: 100%         

  - Removing php-amqplib/rabbitmq-bundle (v1.11.2)
  - Installing php-amqplib/rabbitmq-bundle (v1.12.0)
    Downloading: 100%         

  - Removing scheb/two-factor-bundle (v2.8.2)
  - Installing scheb/two-factor-bundle (v2.9.0)
    Downloading: 100%         

  - Removing sensiolabs/security-checker (v4.0.0)
  - Installing sensiolabs/security-checker (v4.0.1)
    Downloading: 100%         

  - Removing sensio/distribution-bundle (v5.0.14)
  - Installing sensio/distribution-bundle (v5.0.18)
    Downloading: 100%         

  - Removing sensio/framework-extra-bundle (v3.0.16)
  - Installing sensio/framework-extra-bundle (v3.0.22)
    Downloading: 100%         

  - Removing symfony/monolog-bundle (2.12.0)
  - Installing symfony/monolog-bundle (v3.0.3)
    Downloading: 100%         

  - Removing swiftmailer/swiftmailer (v5.4.3)
  - Installing swiftmailer/swiftmailer (v5.4.6)
    Downloading: 100%         

  - Removing symfony/swiftmailer-bundle (v2.4.0)
  - Installing symfony/swiftmailer-bundle (v2.5.1)
    Downloading: 100%         

  - Removing pagerfanta/pagerfanta (v1.0.3)
  - Installing pagerfanta/pagerfanta (v1.0.4)
    Downloading: 100%         

  - Removing white-october/pagerfanta-bundle (v1.0.7)
  - Installing white-october/pagerfanta-bundle (v1.0.8)
    Downloading: 100%         

  - Installing bdunogier/guzzle-site-authenticator (dev-master 196bab1)
    Downloading: 100%         

  - Installing friendsofsymfony/jsrouting-bundle (1.6.0)
    Downloading: 100%         

  - Removing friendsofsymfony/user-bundle (dev-master e168ed6)
  - Installing friendsofsymfony/user-bundle (dev-master 0d70c91)
    Downloading: 100%         

Generating optimized autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_charset (utf8): 
rabbitmq_prefetch_count (10): 
redis_password (null): 
sites_credentials ({  }): 
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as absolute symbolic links.

 --- ------------------------------ ------------------ 
      Bundle                         Method / Error    
 --- ------------------------------ ------------------ 
  ✔   NelmioApiDocBundle             absolute symlink  
  ✔   WhiteOctoberPagerfantaBundle   absolute symlink  
  ✔   FOSJsRoutingBundle             absolute symlink  
 --- ------------------------------ ------------------ 

 [OK] All assets were successfully installed.                                   

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile

 // Clearing the cache for the prod environment with debug false                                                        

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.                                          

-bash-4.1$

**Comment by bitmagewb** [comment]
Nothing that looks like an error.  It prompted for several new parameters, I accepted the defaults.  Full output below:
-bash-4.1$ make update
composer.phar not found, we'll see if composer is installed globally.
remote: Counting objects: 1881, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 1881 (delta 897), reused 890 (delta 890), pack-reused 965
Receiving objects: 100% (1881/1881), 460.32 KiB, done.
Resolving deltas: 100% (1227/1227), completed with 241 local objects.
From https://github.com/wallabag/wallabag
 * [new branch]      2.3        -> origin/2.3
 * [new branch]      2.3-droping-5.5 -> origin/2.3-droping-5.5
 * [new branch]      add-index-entry-url -> origin/add-index-entry-url
 + dcfe2fc...0b6d917 add-user-group -> origin/add-user-group  (forced update)
 * [new branch]      cleanduplicatescommand -> origin/cleanduplicatescommand
 * [new branch]      credentials-in-db -> origin/credentials-in-db
   625bb56..3f5f303  master     -> origin/master
 + 573947a...10d43f8 progress   -> origin/progress  (forced update)
 * [new branch]      save-changes -> origin/save-changes
From https://github.com/wallabag/wallabag
 * [new tag]         2.1.6      -> 2.1.6
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 14 (delta 8), reused 8 (delta 8), pack-reused 3
Unpacking objects: 100% (14/14), done.
From https://github.com/wallabag/wallabag
 * [new tag]         2.1.6.1    -> 2.1.6.1
 * [new tag]         2.2.0      -> 2.2.0
 * [new tag]         2.2.1      -> 2.2.1                                                                                                               
 * [new tag]         2.2.2      -> 2.2.2
Previous HEAD position was 90352b4... Release wallabag 2.1.5
HEAD is now at 90e74c6... Release wallabag 2.2.2
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
  - Removing lexik/maintenance-bundle (v2.1.1)
  - Removing twig/twig (v1.28.1)
  - Installing twig/twig (v1.32.0)
    Downloading: 100%         

  - Removing symfony/symfony (v3.1.7)
  - Installing symfony/symfony (v3.2.4)
    Downloading: 100%         

  - Removing doctrine/common (v2.6.1)
  - Installing doctrine/common (v2.6.2)
    Downloading: 100%         

  - Removing doctrine/dbal (v2.5.5)
  - Installing doctrine/dbal (v2.5.12)
    Downloading: 100%         

  - Removing doctrine/migrations (1.4.1)
  - Installing doctrine/migrations (v1.5.0)
    Downloading: 100%         

  - Removing doctrine/doctrine-bundle (1.6.4)
  - Installing doctrine/doctrine-bundle (1.6.7)
    Downloading: 100%         

  - Removing doctrine/doctrine-migrations-bundle (v1.2.0)
  - Installing doctrine/doctrine-migrations-bundle (v1.2.1)
    Downloading: 100%         

  - Removing friendsofsymfony/rest-bundle (2.1.0)
  - Installing friendsofsymfony/rest-bundle (2.1.1)
    Downloading: 100%         

  - Removing gedmo/doctrine-extensions (v2.4.24)
  - Installing gedmo/doctrine-extensions (v2.4.26)
    Downloading: 100%         

  - Removing hoa/exception (1.16.11.08)
  - Installing hoa/exception (1.17.01.16)
    Downloading: 100%         

  - Removing hoa/consistency (1.16.03.03)
  - Installing hoa/consistency (1.17.01.10)
    Downloading: 100%         

  - Removing hoa/event (1.16.11.19)
  - Installing hoa/event (1.17.01.13)
    Downloading: 100%         

  - Removing hoa/iterator (2.16.11.19)
  - Installing hoa/iterator (2.17.01.10)
    Downloading: 100%         

  - Removing hoa/visitor (2.16.01.11)
  - Installing hoa/visitor (2.17.01.16)
    Downloading: 100%         

  - Removing hoa/ustring (4.16.01.11)
  - Installing hoa/ustring (4.17.01.16)
    Downloading: 100%         

  - Removing hoa/protocol (1.16.07.07)
  - Installing hoa/protocol (1.17.01.14)
    Downloading: 100%         

  - Removing hoa/zformat (1.16.03.15)
  - Installing hoa/zformat (1.17.01.10)
    Downloading: 100%         

  - Removing hoa/regex (1.16.09.06)
  - Installing hoa/regex (1.17.01.13)
    Downloading: 100%         

  - Removing hoa/math (1.16.08.29)
  - Installing hoa/math (1.17.01.13)
    Downloading: 100%         

  - Removing hoa/stream (1.16.11.08)
  - Installing hoa/stream (1.17.02.21)
    Downloading: 100%         

  - Removing hoa/file (1.16.01.15)
  - Installing hoa/file (1.17.01.13)
    Downloading: 100%         

  - Removing hoa/compiler (3.16.10.24)
  - Installing hoa/compiler (3.17.01.10)
    Downloading: 100%         

  - Removing hoa/ruler (2.16.10.24)
  - Installing hoa/ruler (2.17.01.13)
    Downloading: 100%         

  - Removing tecnickcom/tcpdf (6.2.12)
  - Installing wallabag/tcpdf (6.2.15)
    Downloading: 100%         

  - Removing monolog/monolog (1.21.0)
  - Installing monolog/monolog (1.22.0)
    Downloading: 100%         

  - Removing j0k3r/php-readability (1.1.3)
  - Installing j0k3r/php-readability (1.1.6)
    Downloading: 100%         

  - Removing j0k3r/graby-site-config (1.0.28)
  - Installing j0k3r/graby-site-config (1.0.32)
    Downloading: 100%         

  - Removing react/promise (v2.4.1)
  - Installing react/promise (v2.5.0)
    Downloading: 100%         

  - Removing j0k3r/graby (1.5.1)
  - Installing j0k3r/graby (1.6.0)
    Downloading: 100%         

  - Removing javibravo/simpleue (1.0.0)
  - Installing javibravo/simpleue (1.1.1)
    Downloading: 100%         

  - Removing jms/metadata (1.5.1)
  - Installing jms/metadata (1.6.0)
    Downloading: 100%         

  - Removing jms/serializer (1.4.2)
  - Installing jms/serializer (1.5.0)
    Downloading: 100%         

  - Removing jms/serializer-bundle (1.1.0)
  - Installing jms/serializer-bundle (1.2.0)
    Downloading: 100%         

  - Removing kphoen/rulerz (0.19.1)
  - Installing kphoen/rulerz (0.19.3)
    Downloading: 100%         

  - Removing kphoen/rulerz-bundle (0.12.1)
  - Installing kphoen/rulerz-bundle (0.13.1)
    Downloading: 100%         

  - Removing doctrine/orm (v2.5.5)
  - Installing doctrine/orm (v2.5.6)
    Downloading: 100%         

  - Removing lexik/form-filter-bundle (v5.0.1)
  - Installing lexik/form-filter-bundle (v5.0.3)
    Downloading: 100%         

  - Removing liip/theme-bundle (1.4.1)
  - Installing liip/theme-bundle (1.4.6)
    Downloading: 100%         

  - Removing nelmio/api-doc-bundle (2.13.0)
  - Installing nelmio/api-doc-bundle (2.13.1)
    Downloading: 100%         

  - Removing php-amqplib/rabbitmq-bundle (v1.11.2)
  - Installing php-amqplib/rabbitmq-bundle (v1.12.0)
    Downloading: 100%         

  - Removing scheb/two-factor-bundle (v2.8.2)
  - Installing scheb/two-factor-bundle (v2.9.0)
    Downloading: 100%         

  - Removing sensiolabs/security-checker (v4.0.0)
  - Installing sensiolabs/security-checker (v4.0.1)
    Downloading: 100%         

  - Removing sensio/distribution-bundle (v5.0.14)
  - Installing sensio/distribution-bundle (v5.0.18)
    Downloading: 100%         

  - Removing sensio/framework-extra-bundle (v3.0.16)
  - Installing sensio/framework-extra-bundle (v3.0.22)
    Downloading: 100%         

  - Removing symfony/monolog-bundle (2.12.0)
  - Installing symfony/monolog-bundle (v3.0.3)
    Downloading: 100%         

  - Removing swiftmailer/swiftmailer (v5.4.3)
  - Installing swiftmailer/swiftmailer (v5.4.6)
    Downloading: 100%         

  - Removing symfony/swiftmailer-bundle (v2.4.0)
  - Installing symfony/swiftmailer-bundle (v2.5.1)
    Downloading: 100%         

  - Removing pagerfanta/pagerfanta (v1.0.3)
  - Installing pagerfanta/pagerfanta (v1.0.4)
    Downloading: 100%         

  - Removing white-october/pagerfanta-bundle (v1.0.7)
  - Installing white-october/pagerfanta-bundle (v1.0.8)
    Downloading: 100%         

  - Installing bdunogier/guzzle-site-authenticator (dev-master 196bab1)
    Downloading: 100%         

  - Installing friendsofsymfony/jsrouting-bundle (1.6.0)
    Downloading: 100%         

  - Removing friendsofsymfony/user-bundle (dev-master e168ed6)
  - Installing friendsofsymfony/user-bundle (dev-master 0d70c91)
    Downloading: 100%         

Generating optimized autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_charset (utf8): 
rabbitmq_prefetch_count (10): 
redis_password (null): 
sites_credentials ({  }): 
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as absolute symbolic links.

 --- ------------------------------ ------------------ 
      Bundle                         Method / Error    
 --- ------------------------------ ------------------ 
  ✔   NelmioApiDocBundle             absolute symlink  
  ✔   WhiteOctoberPagerfantaBundle   absolute symlink  
  ✔   FOSJsRoutingBundle             absolute symlink  
 --- ------------------------------ ------------------ 

 [OK] All assets were successfully installed.                                   

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile

 // Clearing the cache for the prod environment with debug false                                                        

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.                                          

-bash-4.1$

**Comment by bitmagewb** [comment]
Nothing that looks like an error.  It prompted for several new parameters, I accepted the defaults.  Full ouput attached.
[Uploading makeupdate.txt…]()

**Comment by nicosomb** [comment]
Hello @bitmagewb. 

Can you have a look on this fix please https://gist.github.com/nicosomb/7c537995f2b845a30b4d6cdf23c1e22c ?

**Comment by bitmagewb** [comment]
That has fixed it!  The missing one was:
migrating 20161118134328
     -> ALTER TABLE wallabag_entry ADD COLUMN http_status VARCHAR(3) DEFAULT NULL
All the others had already been played.
Thank you!
