### ISSUE TITLE
When I delete a tag in an article, it sends me to the homepage

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#2974]
### Issue details

When I delete a tag in an article, it sends me to the homepage. It should refresh the article.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS: raspbian
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case

Just delete a tag in an article.

**Comment by nicosomb** [comment]
Hello @NerosTie. 

This behavior can be defined on config page, see: 

![capture d ecran 2017-03-13 a 08 43 40](https://cloud.githubusercontent.com/assets/121870/23845586/4d21c9f4-07c9-11e7-97ff-636854f825a1.png)

**Comment by NerosTie** [comment]
Oh I didn't know… Thanks!
