### ISSUE TITLE
Get language from headers

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2978]
### Issue details
Currently you are getting the language information from the "lang" tag, but many sites doesn't have this tag and uses HTTP headers instead.
My proposal is to use the "lang" tag and if it's not available get the language from the header "Content-Language".
Example URl without tag but with header:
http://www.investopedia.com/university/introduction-stock-trader-types/pivot-traders.asp

### Environment
* wallabag 2.2.2

**Comment by tcitworld** [comment]
Please report this to [Graby](https://github.com/j0k3r/graby) instead.

**Comment by tcitworld** [comment]
But thanks for the tip ;)
