### ISSUE TITLE
[Feature] Add link to original url in article list

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#2980]
There is no way to get directly in the original article. Please add a little icon for that:
![seleccion_022](https://cloud.githubusercontent.com/assets/10577978/23905090/4858a04e-08ca-11e7-9386-6b9735a3b476.png)

**Comment by j0k3r** [comment]
Did you try to click on the domain name?

**Comment by tcitworld** [comment]
Yup. This works.

**Comment by ngosang** [comment]
It's not intuitive but it works, thank you!
