### ISSUE TITLE
Grabbed Pages using responsive images display no image in wallabag article

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#2981]
### Issue details

When responsive images are used in the website, wallabag fetches the images, but leaves the srcset paramaters in, which resolves to no image being displayed.

E.g. this site http://www.heise.de/-3603596 resolves by graby to the https://www.heise.de/tp/features/Indische-Realitaeten-3603596.html?view=print and has i.e. the following code

```
<figure class="rte__inlinebild col-lg-12 col-md-12 col-sm-12 col-xs-12" style="max-width:3648px;">
            
            <img src="//1.f.ix.de/scale/geometry/700/q75/tp/imgs/89/2/1/2/7/9/2/3/783b4c1df50cbe0b.jpg" srcset="/scale/geometry/350/q75/tp/imgs/89/2/1/2/7/9/2/3/783b4c1df50cbe0b.jpg 350w, /scale/geometry/700/q75/tp/imgs/89/2/1/2/7/9/2/3/783b4c1df50cbe0b.jpg 700w, /scale/geometry/1050/q75/tp/imgs/89/2/1/2/7/9/2/3/783b4c1df50cbe0b.jpg 1050w, /scale/geometry/2300/q75/tp/imgs/89/2/1/2/7/9/2/3/783b4c1df50cbe0b.jpg 2300w" sizes="(min-width: 80em) 43.75em, (min-width: 64em) 66.66vw, 100vw" alt="" class="img-responsive">
        <figcaption class="rte__inlinebild_source"><span><div class="text">In den Großstädten gibt es für ein mickriges Gehalt Lärmterror und Abgase … (Foto: Gilbert Kolonko)</div></span>
        </figcaption>
</figure>
```

This code resolves after grabbing the content to

```
<figure class="rte__inlinebild col-lg-12 col-md-12 col-sm-12 col-xs-12 c1">
<img src="https://wallabag.asdf.de/assets/images/2/3/238e88b1/9b0f5075.jpeg" srcset="/scale/geometry/350/q75/tp/imgs/89/2/1/2/7/9/2/3/07c122c20e5d8592.jpg 350w, /scale/geometry/700/q75/tp/imgs/89/2/1/2/7/9/2/3/07c122c20e5d8592.jpg 700w, /scale/geometry/1050/q75/tp/imgs/89/2/1/2/7/9/2/3/07c122c20e5d8592.jpg 1050w, /scale/geometry/2300/q75/tp/imgs/89/2/1/2/7/9/2/3/07c122c20e5d8592.jpg 2300w" sizes="(min-width: 80em) 43.75em, (min-width: 64em) 66.66vw, 100vw" alt="" class="img-responsive">
<figcaption class="rte__inlinebild_source"><div class="text">… und das eine oder andere Feuerchen zu löschen. Foto: Gilbert Kolonko</div>
```

If you now open the article in wallabag, no image is displayed, although it is even cached on the server

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5
* OS: Debian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

### Steps to reproduce/test case

grab the above mentioned page and have a look at it in wallabag, you see no picture

**Comment by nhoizey** [comment]
I have the same issue on wallabag.it (I'm new there) with every content from https://nicolas-hoizey.com (my blog)
