### ISSUE TITLE
Error while installing 

### ISSUE THREAD

**Issue by Praveena0989** [wallabag/wallabag#2991]
### Issue details

Getting this error while calling make install

`
  Problem 1
    - The requested PHP extension ext-dom * is missing from your system. Install or enable PHP's dom extension.
  Problem 2
    - The requested PHP extension ext-curl * is missing from your system. Install or enable PHP's curl extension.
  Problem 3
    - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
  Problem 4
    - The requested PHP extension ext-simplexml * is missing from your system. Install or enable PHP's simplexml extension.
  Problem 5
    - The requested PHP extension ext-mbstring * is missing from your system. Install or enable PHP's mbstring extension.
  Problem 6
    - The requested PHP extension ext-xml * is missing from your system. Install or enable PHP's xml extension.
  Problem 7
    - Installation request for j0k3r/graby 1.6.0 -> satisfiable by j0k3r/graby[1.6.0].
    - j0k3r/graby 1.6.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 8
    - Installation request for j0k3r/safecurl 2.0.2 -> satisfiable by j0k3r/safecurl[2.0.2].
    - j0k3r/safecurl 2.0.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 9
    - Installation request for php-amqplib/php-amqplib v2.6.3 -> satisfiable by php-amqplib/php-amqplib[v2.6.3].
    - php-amqplib/php-amqplib v2.6.3 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
  Problem 10
    - php-amqplib/php-amqplib v2.6.3 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - php-amqplib/rabbitmq-bundle v1.12.0 requires php-amqplib/php-amqplib ~2.6 -> satisfiable by php-amqplib/php-amqplib[v2.6.3].
    - Installation request for php-amqplib/rabbitmq-bundle v1.12.0 -> satisfiable by php-amqplib/rabbitmq-bundle[v1.12.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
PHP Warning:  require(/home/ubuntu/wallabag/app/../vendor/autoload.php): failed to open stream: No such file or directory in /home/ubuntu/wallabag/app/autoload.php on line 9
PHP Fatal error:  require(): Failed opening required '/home/ubuntu/wallabag/app/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ubuntu/wallabag/app/autoload.php on line 9
Makefile:15: recipe for target 'install' failed
make: *** [install] Error 255`

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` 
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS: ubuntu 16.04
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Default

**Comment by tcitworld** [comment]
As written, wallabag requires the following php extensions to work : http://doc.wallabag.org/en/master/user/installation.html#requirements
