### ISSUE TITLE
link stored not correctly

### ISSUE THREAD

**Issue by huggenknubbel** [wallabag/wallabag#2993]
### Issue details

I am running an Up1 server and store some things there (pictures, pastebins, etc)  
So, i got there links like [https://up.knubbel.me/#pScdt-Ji-alhd2K8poCVUQ](https://up.knubbel.me/#pScdt-Ji-alhd2K8poCVUQ).  
But the Web page doesn't store that link correctly. i got there a 'https://up.knubbel.me' and nothing more.

With the windows 10 app it does wok. 

### Environment

* wallabag version (or git revision) that exhibits the issue: latest
* How did you install wallabag? Via `git clone` or by downloading the package?: git clone
* php version: 7.1
* OS: Debian
* type of hosting (shared or dedicated): own server
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case
Try to store this Link: https://up.knubbel.me/#pScdt-Ji-alhd2K8poCVUQ

I know there would be no fetching work beceause of the encryption. There is just a need to store the link.

**Comment by j0k3r** [comment]
Because we remove #value from url. We assume that this shouldn't be a critical value for the document. This kind of value should be used to target user into a specific part of the page but not changing the behavior when there are removed.

> The fragment identifier introduced by a hash mark # is the optional last part of a URL for a document. It is typically used to identify a portion of that document.
> — _https://en.wikipedia.org/wiki/Fragment_identifier_
