### ISSUE TITLE
Search button in Android app

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/wallabag#2995]
After some using of the app I wanna propose such UI improvement: to implement Search button in the upper-left corner.
Now one should make 3 actions to call a search:
1. Press menu button
2. Tap Search menu item
3. Enter text pattern

What I propose is a Search button in the upper left. When tapped it turns out into search box, which receive text input.
The example can be found in the mail app Mailbird, for example. This is how its search button looks like in idle mode

![sketch](https://cloud.githubusercontent.com/assets/6388034/24080466/758ae766-0ca8-11e7-824a-32126218f27e.png)

And this is when it is input-ready
![untitled](https://cloud.githubusercontent.com/assets/6388034/24080471/8ac07646-0ca8-11e7-8d35-1e149120a1b7.png)

It seems, that none of you, guys, ever used wallabag for big amounts of data, and everybody have only 5 articles or so-so :) The lack of batch tools seems quite evident for me.

**Comment by nicosomb** [comment]
This issue was moved to wallabag/android-app#488
