### ISSUE TITLE
Why is MYSQL_ROOT_PASSWORD required?

### ISSUE THREAD

**Issue by McMac** [wallabag/wallabag#2997]
I have a central mysql db which is shared by many webapps. I therefore would like to create the mysql schema (user + database) manually (ideally with scripts provided by wallabag) and then only provide the wallabag db user to the wallabag config. 
Especially when using docker and the lack of password encryption in the launch configs, I'd rather not broadcast my mysql root password in every docker and/or compose script I am deploying. 
If the wallabag user and the db has been created there is zero need for any mysql root credentials.

**Comment by tcitworld** [comment]
Please report this to the docker repository here https://github.com/wallabag/docker

**Comment by McMac** [comment]
@tcitworld, glad you took this as a quick way to close this issue just because you found the term in it. 
Last time I installed wallabag without docker, the installation required the root password of the mysql. Therefore it then has nothing to do with docker in particular but with how wallabag is set up.

**Comment by tcitworld** [comment]
wallabag doesn't asks for mysql root password.
