### ISSUE TITLE
Les logos ne s'affiche pas, fresh install

### ISSUE THREAD

**Issue by tomgue** [wallabag/wallabag#3006]
### Issue details

Le logo ne s'affiche pas.

![capture d ecran 2017-03-22 14 31 36](https://cloud.githubusercontent.com/assets/4108018/24200144/66c7a802-0f0c-11e7-9f0b-276673219ead.png)
![capture d ecran 2017-03-22 14 31 24](https://cloud.githubusercontent.com/assets/4108018/24200146/6972be7a-0f0c-11e7-9a23-4721f60ef656.png)

Logs : [https://www.zerobin.net/?cdca0b67808c97d6#Hhlcc6hfk2l2Ii7U55pMeUYI/jvQn3lwuEIi6f5LgS4=](https://www.zerobin.net/?cdca0b67808c97d6#Hhlcc6hfk2l2Ii7U55pMeUYI/jvQn3lwuEIi6f5LgS4=)

### Environment

* wallabag version: **2.2.2 (Git 90e74c6)**
* How did you install wallabag? **git clone**
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: PHP 5.6.30
* OS: linux
* type of hosting (shared or dedicated): **Shared**
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): **SQLite**

### Steps to reproduce/test case

Fresh install

**Comment by j0k3r** [comment]
Could you please give us the output of the installation process?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
