### ISSUE TITLE
Impossible to bag picture (works on f43.me)

### ISSUE THREAD

**Issue by bipox** [wallabag/wallabag#3008]
The link : https://i.redditmedia.com/UkWGbnPcxXooWc2CdYsFOvIS7RjePmbtPTNP9GB78LA.png?w=824&s=0c3b3f81bdb158cdfdcff0e6fe7dfcfa

I tried to follow the procedure, sorry if I forgot something.

Thanks for developing this great program.

**Comment by j0k3r** [comment]
It works well on both wallabag.it and on my local.
Could you confirm?

**Comment by bipox** [comment]
Yes, it works now!
