### ISSUE TITLE
[BUG] When importing from Pocket for the second time (to refresh list), everything got downloaded again

### ISSUE THREAD

**Issue by cosimosimeoneTR** [wallabag/wallabag#3012]
Guys, really... :-)
There is no way to refresh items miported from Pocket.
And since i tryed to import again, i have ALL my reading list duplicated...
I **really** want to support you, i already subscribed for a 4 months account, but.... **REALLY**??? :-)

**Comment by j0k3r** [comment]
Come one man, you know that god damn it template for issue?
Why did you remove it all and put some non-sense information in your issue?

Also, please us [that form](https://www.wallabag.it/en#cta) for any question regarding wallabagit.
