### ISSUE TITLE
Articles from a website create server error 

### ISSUE THREAD

**Issue by rgugliel** [wallabag/wallabag#3013]
### Issue details

When I try to add http://blog.brakmic.com/data-science-for-losers/ to my Wallabag instance, I get an error 500.

More info:
* The problem does not appear on Froamabag (Wallabag 1.9.1)
* I have no problem adding no articles
* I can add some other articles of blog.brakmic.com

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package? package
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 5.6.30
* OS: Ubuntu LTS 16.04.2
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by nicosomb** [comment]
Hello @rgugliel. 

I think you should have a look to your webserver configuration (memory limit or something like that). 
Can you check your logs (in wallabag/var/logs)? 

I tried on wallabag.it and it works fine.

**Comment by rgugliel** [comment]
Hi Nicolas,
The corresponding log entries are the following:
```
[2017-03-29 10:52:16] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, is_archived, is_starred, content, created_at, updated_at, mimetype, language, reading_time, domain_name, preview_picture, is_public, http_status, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [
........]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x80</...' for column 'content' at row 1 at /home/rgugliel/www-dev/rgugliel/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x80</...' for column 'content' at row 1 at /home/rgugliel/www-dev/rgugliel/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x80</...' for column 'content' at row 1 at /home/rgugliel/www-dev/rgugliel/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

[2017-03-29 10:52:16] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
```

I don't understand where the problem comes from. Encoding?

**Comment by nicosomb** [comment]
You said `SQLite` in your first post, but I think you use MySQL. 
And if you use MySQL you must define `utf8mb4` in `app/config/parameters.yml` for the `database_charset` value.

**Comment by rgugliel** [comment]
Oh! Sorry!

This not seem to solve the problem. Is there another step?
A cache of the parameters to clear?

Thanks!

**Comment by nicosomb** [comment]
Yes, you need to clear the cache: `bin/console cache:clear -e=prod`.

**Comment by rgugliel** [comment]
@nicosomb 
Thanks a lot (and sorry to have used GitHub for support)

**Comment by tcitworld** [comment]
No worries, it's intended to use it like this.
