### ISSUE TITLE
Violated primary key constraint in wallabag_entry

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/wallabag#3016]
### Issue details

I suppose, by this my [self-invented query](https://github.com/wallabag/wallabag/issues/2989#issue-214816967) I broke Postgres primary key ID field in `wallabag_entry`, which is generated I dunno how (BTW, how? by n+1?). How it can be fixed, till we finally implement [this improvement](https://github.com/wallabag/wallabag/issues/2992) (are we gonna do this at all?)

![sketch8](https://cloud.githubusercontent.com/assets/6388034/24472557/cf91da16-14ce-11e7-867f-a2adf5ec9370.png)

![sketch7](https://cloud.githubusercontent.com/assets/6388034/24472563/d43ba1aa-14ce-11e7-81a7-f49a4f31fe79.png)

### Environment

* wallabag version that exhibits the issue: 2.2.2
* How did you install wallabag?: Docker
* Last wallabag version that did not exhibit the issue (if applicable): dunno
* php version: dunno
* OS: AWS AMI Linux 2016.e
* type of hosting (shared or dedicated): AWS EC2 T2 Micro
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Postgre 9.6.2

### Steps to reproduce/test case

Trying to add new article.

**Comment by Suncatcher** [comment]
Any suggestions?

**Comment by nicosomb** [comment]
@Suncatcher not yet, sorry.

**Comment by nicosomb** [comment]
@Suncatcher I don't know ... I want to say "give it a try" :) (and make a backup before)...

**Comment by Suncatcher** [comment]
Win! Finally I fixed it. I changed sequence max value with 

    ALTER SEQUENCE serial RESTART WITH 105;

and it worked. Articles are addable again. Simple as a pie!
Our sequence is called `entry_id_seq` and it was already created in `public` schema. I realized that when I tried to create sequence with the same name. The sequence has type `bigint`, not `seria`l but it anyway works as an auto-increment.
My knowledge in Postgres doesn't allow to analyze this fact properly :)

**Comment by nicosomb** [comment]
So, what can we do in wallabag?

**Comment by Suncatcher** [comment]
> So, what can we do in wallabag?

To implement [this thing](https://github.com/wallabag/wallabag/issues/2989) ASAP, so as not to (re)invent such crappy queries :)
Now I should analyze the database - how to make `INSERT` in a such way, so that ID to auto-increment the counter. Now, for some reason, it works properly only for inserts (new articles) from Wallabag Web-UI.

**Comment by nicosomb** [comment]
So, can we close this issue and only discuss on #2989?

**Comment by Suncatcher** [comment]
Yes, I think we can.
