### ISSUE TITLE
Wallabag Docker image/container update

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/wallabag#3018]
### Issue details
I have several questions regarding this:
1. Does Wallabag image/container updated automatically?
2. If not, how can one update it manually **without stopping** container?
3. If it's not possible without stopping, what is the general procedure?

Having my (very limited) knowledge of Docker, I treat it following way: 
when creating container, Docker pulls the latest image from the Hub, but without recreating container it won't update it by default? Am I right?
As it appears, procedure is quite [complicated](http://stackoverflow.com/a/38235470/911419), and to provide consistent updates [some changes should be made](https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/) to application **prior** to publishing the image.

### Environment

* wallabag version that exhibits the issue: 2.2.2
* How did you install wallabag?: Docker
* Last wallabag version that did not exhibit the issue (if applicable): dunno
* php version: dunno
* OS: AWS AMI Linux 2016.e
* type of hosting (shared or dedicated): AWS EC2 T2 Micro
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Postgre 9.6.2

### Steps to reproduce/test case

Trying to update Wallabag container

**Comment by nicosomb** [comment]
@Suncatcher do you use this container https://hub.docker.com/r/wallabag/wallabag/ ?

**Comment by Suncatcher** [comment]
Exactly. However, [I was said](https://github.com/wallabag/wallabag/issues/2987#issuecomment-287485152) it's only for developers and not for users.

**Comment by nicosomb** [comment]
No, the image available on Docker Hub is for users. 
For developers, you need to use docker-compose.yml in https://github.com/wallabag/wallabag repo.

**Comment by Suncatcher** [comment]
So you guys should be more consistent in providing info :)

**Comment by nicosomb** [comment]
Yes we should. 

Do we need to move this issue to wallabag/docker repo?

**Comment by Suncatcher** [comment]
I suppose yes.

**Comment by nicosomb** [comment]
This issue was moved to wallabag/docker#60
