### ISSUE TITLE
Parsing errorsmashingmagazine.com

### ISSUE THREAD

**Issue by Simounet** [wallabag/wallabag#3028]
Hi,
I have an issue parsing this article https://www.smashingmagazine.com/2017/04/browser-extension-edge-chrome-firefox-opera-brave-vivaldi/ . It stops at a display none element id="note-56".

**Comment by j0k3r** [comment]
It works well on wallabag.it for me.
Could you retry?

I'll improve the siteconfig BTW.

**Comment by Simounet** [comment]
That's weird 'cause it still don't work. I'm on wallabag 2.2.2 and I updated the smashingmag's graby-site-configuration to the one you submitted.

**Comment by j0k3r** [comment]
And it still doesn't work?
I got it working on 2.3.

**Comment by Simounet** [comment]
No, same issue on my 2.3's instance. Even with an up-to-date graby-site-config version: `vendor/j0k3r/graby-site-config/.smashingmagazine.com.txt:test_url: https://www.smashingmagazine.com/2017/04/browser-extension-edge-chrome-firefox-opera-brave-vivaldi/`.

**Comment by techexo** [comment]
The article is fetched perfectly (including pictures and code) for me with 2.3.3. @Simounet could you try with a fully updated version of wallabag?

**Comment by Simounet** [comment]
That's correct. It's working like a charm now.
