### ISSUE TITLE
Add a `NOT` operator for use with tagging comparisons

### ISSUE THREAD

**Issue by jamietanna** [wallabag/wallabag#3031]
It would be useful to perform a comparison, such as `readingTime < 5 AND NOT domainName matches reddit.com`, where the `NOT` operator provides a negation of the following condition.

**Comment by j0k3r** [comment]
You can do that:

```
readingTime < 5 AND domainName != "reddit.com"
```

**Comment by jamietanna** [comment]
True, maybe that example wasn't great. What about something like `readingTime < 5 AND NOT url matches "/selfhosted/"`

**Comment by j0k3r** [comment]
For that particular case, we can add a `notmatches` operator, like we did for the `matches` operator in https://github.com/wallabag/wallabag/tree/master/src/Wallabag/CoreBundle/Operator

If you have time to add it, feel free to provide a PR.

**Comment by nicosomb** [comment]
Done here  #3047
