### ISSUE TITLE
Have description as a separate entry

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#3035]
Today we concatenate description (from `og_description`) from Graby at the top of our article. We should :
- [ ] put it in a special description field of our entry
- [ ] test if it's differ from the beginning of the content ; if it doesn't, don't show it.

**Comment by j0k3r** [comment]
I don't get it.
Could you please give an example?
Are you talking about the list view? the card view? the entry view?

**Comment by nicosomb** [comment]
Thomas talks about entry view. 

I don't have an example in my account, but I see what he means.
For certain articles, you have some duplicated parts: the first paragraph is present in the `og_description` so in the article view, you have this part twice.

**Comment by j0k3r** [comment]
Still needs an example 🙂

**Comment by j0k3r** [comment]
Obsolete
