### ISSUE TITLE
Configuration download_pictures parameter unused 

### ISSUE THREAD

**Issue by Simounet** [wallabag/wallabag#3037]
Hi there,
It might be a useless duplicated configuration parameter:
- /settings#set-entry -> download_pictures (that seems to be unused)
- /settings#set-misc -> download_images_enabled (used for sure)

If the first one is in use for something, the labels are a little bit confusing to me anyway.

Have a nice day.

**Comment by j0k3r** [comment]
Looks like `download_pictures` is a kind of legacy from wallabag v1 and when we implemented that feature we used a new parameter.
So we can safely remove that. It might need a database migration btw.

**Comment by nicosomb** [comment]
In fact, the setting was removed here https://github.com/wallabag/wallabag/pull/1896 (April 2016). 
So this issue is true only for users who installed 2.0.0. 

Do we need a migration for that? 
ping @wallabag/core

**Comment by j0k3r** [comment]
Well, we should have done that migration in #1896
So I think we need it.

**Comment by nicosomb** [comment]
Done in #3048.
