### ISSUE TITLE
Self-hosted images server default parameter

### ISSUE THREAD

**Issue by Simounet** [wallabag/wallabag#3038]
Hi,
I enabled the function to download locally the images contained into the entries. I didn't pay attention to the URL below that was `v2.wallabag.org` by default. I think it could be great to use ours by default.
P.S.: Is it normal that I can upload images to v2.wallabag.org?

**Comment by tcitworld** [comment]
Nope, not normal.

**Comment by nicosomb** [comment]
The pictures are *really* uploaded on v2.wallabag.org?

**Comment by Simounet** [comment]
I don't know if they were uploaded or already there but it was the good images, from v2.wallabag.org.

**Comment by nicosomb** [comment]
OK, so your pictures are uploaded on your webserver (could you check your `assets/images` folder?) but we define the URL of your instance in the settings and we add this URL + the assets path. I don't know if I'm clear. 

But, you can't upload on v2.wallabag.org.

**Comment by Simounet** [comment]
You're right. I have this file on my server. Only the base URL is wrong. Ok for this weird URL issue. What do you think about the rest of this issue?

**Comment by tcitworld** [comment]
You made me quite afraid for a while.

**Comment by Simounet** [comment]
Yup, that's what I do most of the time. 😨

**Comment by j0k3r** [comment]
We add the url host to be sure any external app (like iOS & Android) are able to retrieve the image correctly.
As of now, I have no idea why your image were "uploaded" to v2.wallabag.
Did you try to add many articles and check that image are still requested from v2.wallabag?

**Comment by Simounet** [comment]
The uploaded thing was a false problem. I didn't configured the URL so I can see v2.wallabag references whereas the files were on my server.
I understood why we need this parameter so can we fill it with our URL on install instead of keeping v2.wallabag.org or left it blank (don't know what is the default value nowadays)?

**Comment by j0k3r** [comment]
That value is blank by default: https://github.com/wallabag/wallabag/blob/4a953a250c2fb3597224e8bd4aeb9e558001603d/src/Wallabag/CoreBundle/Command/InstallCommand.php#L402

**Comment by nicosomb** [comment]
because it was the previous default value.
![capture d ecran 2017-04-13 a 11 52 39](https://cloud.githubusercontent.com/assets/121870/24999943/bf39db24-203f-11e7-9136-09c8074c7d54.png)

**Comment by j0k3r** [comment]
Do we have sth about image download in the doc?
Can't find it.
We should put sth about that url by default for previous instance when people enable image download

**Comment by Simounet** [comment]
If it can be used somewhere else, I think it could be great to use our install URL by default.

**Comment by j0k3r** [comment]
It seems to me mostly used in auth email & QR Code for apps.
The problem is, when installing wallabag using the command line you can't retrieve the install URL of the project because you are in CLI.

**Comment by Simounet** [comment]
So we have to add a parameter or ask a question on cli install, don't we?

**Comment by j0k3r** [comment]
The value will now be asked while installing wallabag.
The value has been moved to the parameters.yml file instead of the internal config.

See https://github.com/wallabag/wallabag/pull/3173 & https://github.com/wallabag/doc/pull/8
