### ISSUE TITLE
Performance issue on first load

### ISSUE THREAD

**Issue by sanpii** [wallabag/wallabag#3039]
### Issue details

When I load the index page of my wallabag instance, the first load (generally once by day) the page takes long time to load (30s instead of 300ms).

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version: 7.0.18
* OS: Debian 8
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Postgresql

### Steps to reproduce/test case

Load unread entries after a long time.

Here the performance page for a first load:

![screen shot 2017-04-12 at 22 01 38-fullpage](https://cloud.githubusercontent.com/assets/113045/24977351/119439c8-1fcd-11e7-936a-c6c89a41514f.png)

And for a second load:

![screen shot 2017-04-12 at 21 59 16-fullpage](https://cloud.githubusercontent.com/assets/113045/24977364/1c61a6d8-1fcd-11e7-9589-68b3771313cd.png)

It’s clearly a problem with symfony initialisation.

**Comment by j0k3r** [comment]
First of all, you shouldn't enabled dev env if you want to have a fast wallabag. A lot of extra stuff are loaded in dev mode.
Also, I think the cache might be regenerated after a day or so while using the prod env might not have this problem.

**Comment by sanpii** [comment]
> First of all, you shouldn't enabled dev env if you want to have a fast wallabag. A lot of extra stuff are loaded in dev mode.

I enable the dev environment only for debugging purpose. With the production environment, today, the page toke 22 seconds to load.

**Comment by tcitworld** [comment]
Isn't it the loading time to cache the number of entries ?

**Comment by sanpii** [comment]
> Isn't it the loading time to cache the number of entries ?

How can I check this idea? The SQL queries toke 3 seconds (20 ms for the second load).

I have 7 unread articles and 1110 articles.

**Comment by nicosomb** [comment]
I tried to access to `https://poche.homecomputing.fr/` and your server seems to be very long.
And it's not related to the articles of my account ... because I don't have any account in your instance and when wallabag loads the login form, the articles are not loaded. 

I think that you can have a look in the tuning of your server.

**Comment by nicosomb** [comment]
I close your issue. Please reopen it if necessary.
