### ISSUE TITLE
Problem while fetching Wired article

### ISSUE THREAD

**Issue by clairezed** [wallabag/wallabag#3040]
### Issue details

I'm trying wallabag.it, and have problemsfetching this article from Wired : https://www.wired.com/2017/03/silicon-valley-rather-cure-death-make-life-worth-living/. f43.me doesn't do any better; but pocket manages to fetch it correctly. 

The problem seems to be that the block that contains the article also contain a full short article below, and it's this second article that's being fetched. I don't manage to grab only the article content, using http://siteconfig.fivefilters.org.

### Environment

* wallabag version (or git revision) that exhibits the issue: wallabag.it (wallabag current last version, so 2.2.2 probably ?)

### Steps to reproduce/test case

Try to fetch https://www.wired.com/2017/03/silicon-valley-rather-cure-death-make-life-worth-living/.

Is there a way I could help ?

**Comment by j0k3r** [comment]
I've just tried and it works on wallabag.it.
There is just that little component "related stories" which shouldn't be parsed but the rest is ok to me.

![image](https://user-images.githubusercontent.com/62333/27001831-164ca318-4dd3-11e7-9eed-975b495f526f.png)

Are you still getting some problem?
