### ISSUE TITLE
Local images do not download any longer

### ISSUE THREAD

**Issue by pajd** [wallabag/wallabag#3042]
### Issue details

Hi,
I activated the option to download of images locally and it worked like a charm at first. Now, for a reason I cannot understand, images do not download any longer; my articles are bare. When I deactivate the local image download, images show. What could be the source of the issue?
Thanks for Wallabag, it is a gem.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? via git clone
* Last wallabag version that did not exhibit the issue (if applicable): 2.2.1? Not sure
* php version: 7.0.15-0ubuntu0.16.04.4
* OS: Ubuntu 16.04.2
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Import any webpage. Screen capture attached of the same webpage import with and without the local images import option activated.
![local image option activated](https://cloud.githubusercontent.com/assets/25849717/25086967/5a327050-2374-11e7-90f7-93c524c785f6.jpeg)
![local image option deactivated](https://cloud.githubusercontent.com/assets/25849717/25086968/5a4682d4-2374-11e7-91e6-a002ab5788aa.jpeg)

**Comment by tcitworld** [comment]
Please post your browser logs. https://developer.mozilla.org/en-US/docs/Tools/Browser_Console https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by pajd** [comment]
Not sure how to export these logs, so I did some screen captures that seemed relevant.
Hope it helps.

![browser console 1](https://cloud.githubusercontent.com/assets/25849717/25088950/2049c9c4-2383-11e7-8138-3144571ff444.jpeg)
![browser console 2](https://cloud.githubusercontent.com/assets/25849717/25088952/20510888-2383-11e7-9fb1-34ff8f38758c.jpeg)
![browser console 3](https://cloud.githubusercontent.com/assets/25849717/25088951/204ec7a8-2383-11e7-9d35-5f37c51dde86.jpeg)

**Comment by j0k3r** [comment]
Could you please check your folder `web/assets/images` and tell us what's inside?
Looks like image aren't there (see all the `/assets/images/...` in the log which tells the 404 urls).

Does the folder right / owner are ok?
Could you do `chmod -R 777 web/assets/images` and try again with a new article?

**Comment by pajd** [comment]
You nailed it! It was a simple permission issue... Thank you very much!

**Comment by gerroon** [comment]
Hi 

Sorry to ask about this here, but where do you enable local image caching?

**Comment by nicosomb** [comment]
Hello. 
You can enable it in Internal settings (if you use your own wallabag instance).

**Comment by gerroon** [comment]
@nicosomb 
That is waht I am trying to figure out. Where is the internal settings? I did not see it in the parameters.yml

**Comment by j0k3r** [comment]
It's in your interface not in config file. Use wallabag UI.

**Comment by gerroon** [comment]
Man you guys are so cryptic. I do not see any setting that is related to saving images locally in my WB, using 2.2.3

thanks

**Comment by nicosomb** [comment]
Internal settings is in the sidebar of your wallabag instance.

**Comment by j0k3r** [comment]
See at the bottom:

![image](https://cloud.githubusercontent.com/assets/62333/26391966/294a5e68-4065-11e7-9e62-da7dfdb8bf7d.png)

**Comment by gerroon** [comment]
@j0k3r 
Thanks for the image. I
