### ISSUE TITLE
Fetch Error Cause by User-Agent

### ISSUE THREAD

**Issue by cubesky** [wallabag/wallabag#3046]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Can not fetch Zhihu Articale case by User-Agent .

### Environment

* wallabag version (or git revision) that exhibits the issue: Latest Docker Image
* How did you install wallabag? Via `git clone` or by downloading the package? Docker
* Last wallabag version that did not exhibit the issue (if applicable): yes
* php version: docker include
* OS: Ubuntu 16.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case

Fetch `https://www.zhihu.com/question/21715456/answer/157956365` and zhihu return `https://www.zhihu.com/compatibility/index.html`

**Comment by j0k3r** [comment]
Did you read http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that and tried to fix it using a different user agent?
Also, how do you know this is related to the user agent?

**Comment by cubesky** [comment]
@j0k3r 
I test on Chrome. When I use an old browser UA. Zhihu.com will return that compatibility error page. I read http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that ,but I can not find config about user agent. It all talks about XPath and CSS Selector.

**Comment by j0k3r** [comment]
You're right, user agent isn't documented.
You can try with:

```
http_header(user-agent): WhatEverUserAgentYouWant
```

**Comment by cubesky** [comment]
I just test 
```
http_header(user-agent): "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36"
```
and
```
http_header(user-agent): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36
```
It doesn't work.
I test them on https://f43.me/feed/test

**Comment by cubesky** [comment]
I just test zhihu.com , Now I think it has multi check function.

**Comment by Kdecherf** [comment]
I am able to fetch the linked page on the current release 2.4.1, closing this issue.
