### ISSUE TITLE
Restrict thumbnail image MIME-types

### ISSUE THREAD

**Issue by maltejk** [wallabag/wallabag#3049]
### Issue details

I appears, my wallabag instance tried for several hours to create a thumnail off an mjpeg image from a webcam while syncing with Pocket.

I understand the behaviour might appear only, if "save images locally" is switched on.

I'd like suggest to ignore mjpeg if that would be ignored as a thumbnail image file possible.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 7.0
* OS: Debian Stretch
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install: SQLite

* Enable Redis to import data asynchronously: 1
* Import is running via `export SYMFONY_ENV=prod ; bin/console wallabag:import:redis-worker -vvv pocket`

### Steps to reproduce/test case

- Import from Pocket

**Comment by j0k3r** [comment]
Could you tell us what was the associated article to that image in mjpeg?

**Comment by maltejk** [comment]
Sure, apologies that I did'nt do before: http://nsasimulator.com/. 

Sadly the domain is already parked, but an archived version exists at http://web.archive.org/web/20150801223540/http://nsasimulator.com/

My version, imported from Pocket tries to download 

> [2017-04-21 07:11:31] app.DEBUG: DownloadImages: working on image: http://dcccam.winthrop.edu/axis-cgi/mjpg/video.cgi

**Comment by j0k3r** [comment]
Should be fixed by https://github.com/wallabag/wallabag/pull/3184
