### ISSUE TITLE
If possible, could you increase the import limit size?

### ISSUE THREAD

**Issue by n00b12345** [wallabag/wallabag#3058]
I'm transitioning from one wallabag installation to another. Now, for some reason I'll have to import my unread articles. However, because I use wallabag so often, my unread JSON export is around 3.5 MB. 

But wallabag has an import size limit of 2.5 MB. Could you consider looking into increasing this size limit?

**Comment by tcitworld** [comment]
wallabag has no file size limit for imports. It's the administrator of your instance who has set these limits. I suggest you ask him/her instead. :)
