### ISSUE TITLE
Shared hosting point to version 2.1.4

### ISSUE THREAD

**Issue by bigretromike** [wallabag/wallabag#3059]
### Issue details

http://doc.wallabag.org/en/master/user/installation.html point to latest builds for shared hosting that ain't latest.

**Comment by nicosomb** [comment]
Hello @bigretromike! 

Where did you find a link to 2.1.4?

**Comment by bigretromike** [comment]
https://wllbg.org/latest-v2-package

**Comment by nicosomb** [comment]
Can you try with an other browser please? 

I have the 2.2.2. 

![capture d ecran 2017-05-03 a 16 28 50](https://cloud.githubusercontent.com/assets/121870/25665351/a3acdcec-301d-11e7-85aa-377d0500b164.png)

**Comment by bigretromike** [comment]
6 days ago it was poiting to old version
