### ISSUE TITLE
Trouble saving article from oncletom.io

### ISSUE THREAD

**Issue by mentalo-** [wallabag/wallabag#3063]
### Issue details

The saving of an article from oncletom.io is incomplete.
It's accessible from this url : 
[https://oncletom.io/node.js/chapter-01/index.html](https://oncletom.io/node.js/chapter-01/index.html)
Only 2 chapters (on 9) are saved.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? no i use wallabag.it
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case
I use Firefox 53.0 (last stable release) on Ubuntu 16.04 64 bits. I save the articles with the Firefox extension wallabagger (1.3 version, latest).
When i save the article, the saved version shows the 2 first chapters, but the article has 9 chapters, as you can see in the link above. It ends after the youtube link, juste before the title of the 3rd chapter.

**Comment by mentalo-** [comment]
Someone test this fix before closing the issue ?
I still have the bug, article is cut after the youtube lin : i deleted the old one and resaved the same page to test it.
I have the same requirements than the first message.

**Comment by j0k3r** [comment]
This will be fixed in the previous release.
If you retry right now it's normal that it doesn't work.

**Comment by mentalo-** [comment]
Ok, i'll wait the next release ! Thanks for the fix :)

**Comment by mentalo-** [comment]
Hello,

When this fix will be released ? I still have the issue on wallabag.it.
I would like to read the entire article on my next holidays :)

**Comment by j0k3r** [comment]
It's holidays for us too, so we plan to release it as soon as we got enough time to be ready to handle feedbacks.
