### ISSUE TITLE
Support Courrier Internationnal restricted articles

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#3069]
I made a subcription to work on it.

**Comment by j0k3r** [comment]
Do you still have it?

**Comment by tcitworld** [comment]
Nope, but I can renew the subscription if needed.

**Comment by j0k3r** [comment]
Should be great 👍

**Comment by tcitworld** [comment]
Done, credentials sent.

**Comment by j0k3r** [comment]
Fixed https://github.com/fivefilters/ftr-site-config/commit/65fa7a661c57a2fc0b02bfd939168f4c9d345c07
