### ISSUE TITLE
Cannot connect to mariadb

### ISSUE THREAD

**Issue by tterranigma** [wallabag/wallabag#3074]
### Issue details
Wallabag cannot connect to the database. This is the error in tha apache error 

`log:HP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /srv/http/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43`

### Environment

* wallabag version: 2.2.2
* How did you install wallabag? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 7.1.4
* OS: arch linux (latest packages)
* type of hosting (shared or dedicated): vps
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

I visit my wallabag installation, then get redirected to the /login page and I get a 500 error. The logs contain the above error.
I have cleared caches just in case but didn't help. This is my parameters.yml file (ignore the line numbers):
> 1 # This file is auto-generated during the composer install
 2 parameters:
 3     database_driver: pdo_mysql
 4     database_host: localhost
 5     database_port: ~
 6     database_name: name
 7     database_user: user
 8     database_password: pass
 9 #    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
10     database_path: null
11     database_table_prefix: pre_
12     mailer_transport: smtp
13     mailer_host: 127.0.0.1
14     mailer_user: null
15     mailer_password: null
16     locale: en
17     secret: <secret>
18     twofactor_auth: true
19     twofactor_sender: no-reply@wallabag.org
20     fosuser_registration: true
21     fosuser_confirmation: true
22     from_email: no-reply@wallabag.org
23     rss_limit: 50
24     rabbitmq_host: localhost
25     rabbitmq_port: 5672
26     rabbitmq_user: guest
27     rabbitmq_password: guest
28     redis_host: localhost
29     redis_port: 6379
30 #    database_socket: /run/mysqld/mysqld.sock
31     database_socket: null
32     redis_scheme: tcp
33     redis_path: null
34     database_charset: utf8
35     rabbitmq_prefetch_count: 10
36     redis_password: null
37     sites_credentials: {  }

The commented out lines are stuff I have tried but did not work. 

Also, I can connect with the above credential using the mysql cli tool.

**Comment by tcitworld** [comment]
Maybe set `database_port` to something ? Also, is the php-mysql module installed ?

**Comment by tcitworld** [comment]
It didn't have issue through `wallabag:install` ?

**Comment by j0k3r** [comment]
Does your mariadb instance is running?
What about a `telnet localhost 3306`?

**Comment by tterranigma** [comment]
It is running. Telnet returns Connection refused. Isn't this expected since I have disabled networking?

**Comment by j0k3r** [comment]
If it returns connection refused, there is a problem I think.
I don't know what _disabled networking_ means.

**Comment by tterranigma** [comment]
I mean I have disable network access to mariadb with `skip-networking` in my.cnf. I tried changing the database_socket in parameters.yml to point to the unix socket that mysql is listening at but it didn't work.

**Comment by j0k3r** [comment]
The issue doesn't seems to be related to wallabag itself but more related to the way you installed your MariaDB.
I'm sorry for you and good luck with your database

**Comment by tterranigma** [comment]
Thank you for your fast replies!
