### ISSUE TITLE
When saving YouTube links, "Original article" URL retains embedded format

### ISSUE THREAD

**Issue by JeffMelton** [wallabag/wallabag#3078]
### Issue details

When saving a YouTube link to Wallabag, the "Original article" URL retains the video's embedded format instead of the page link (see test case).

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.0
* How did you install wallabag? Via `git clone` or by downloading the package? package download
* Last wallabag version that did not exhibit the issue (if applicable): unknown
* php version: 5.6.30-0+deb8u1
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

1) Save a YouTube link to Wallabag, via API, extension, or the web interface.
    - https://www.youtube.com/watch?v=NYD3QtyEGGM&list=PL8s6sSjUyaxUk3mCUqiNuJiMNxs9QdthO
2) Click through to the "Original article"
3) Observe YouTube's response.

**Comment by mjmurphy** [comment]
Can also confirm this. Just tested with the official wallabag/wallabag docker image with SQLite for testing.

Also the same issue with Vimeo links - the "original article" link in Wallabag looks like this:

https://vimeo.com/api/oembed.xml?url=[vimeo_url]

or with youtube the original article looks like this:

http://www.youtube.com/oembed?url=[youtube_url]&format=xml

**Comment by The0x539** [comment]
#2149 ?

**Comment by nicosomb** [comment]
👍

**Comment by bcutter** [comment]
Sure this is closed @nicosomb? Because I still see this:

https://github.com/wallabag/wallabag/discussions/8286#discussioncomment-13468328
