### ISSUE TITLE
Easy way to upgrade site-configs only

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3081]
### Issue details

Since wallabag releases are not that often compared to graby-site-config updates, i would like to update the component graby-site-config more often. 

Is there some mechanism already available? 
Otherwise i wish to have such method, because some sites fetching is fixed upstream in ftr-site-config and thus graby-site-config, but not in wallabag. :( An easy way would be to call e.g. `make update-site-config` and get the latest site-config release in my wallabag. Even better would a GUI possibility via admin panel withing wallabag web page itself.

**Comment by nicosomb** [comment]
I think that your issue is related to #1284. Right?
