### ISSUE TITLE
create user via CLI

### ISSUE THREAD

**Issue by oupala** [wallabag/wallabag#3083]
I'd like to be able to create a user via CLI the same way I can install Wallabag via CLI.

It could be something like:

```bash
php bin/console wallabag:createUserl --login=mylogin --pass=mypass
```

And is it normal that the default install of Wallabag creates a wallabag/wallabag user? Isn't it a security problem?

**Comment by j0k3r** [comment]
Use `php bin/console fos:create:user username email password`

```
j0k@MBP:~/Sites/github/wallabag$ php bin/console help fos:user:create
Usage:
  fos:user:create [options] [--] <username> <email> <password>

Arguments:
  username              The username
  email                 The email
  password              The password

Options:
      --super-admin     Set the user as super admin
      --inactive        Set the user as inactive
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -e, --env=ENV         The environment name [default: "dev"]
      --no-debug        Switches off debug mode
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  The fos:user:create command creates a user:

    php bin/console fos:user:create matthieu

  This interactive shell will ask you for an email and then a password.

  You can alternatively specify the email and password as the second and third arguments:

    php bin/console fos:user:create matthieu matthieu@example.com mypassword

  You can create a super admin via the super-admin flag:

    php bin/console fos:user:create admin --super-admin

  You can create an inactive user (will not be able to log in):

    php bin/console fos:user:create thibault --inactive
```

**Comment by tcitworld** [comment]
> And is it normal that the default install of Wallabag creates a wallabag/wallabag user? Isn't it a security problem?

wallabag / wallabag are the default values...

**Comment by oupala** [comment]
@j0k3r Is it normal that I get the following error?

```bash
>php bin/console help fos:user:create
PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /home/ops/apps/release-2.2.2/app/AppKernel.php on line 49
```

While the install was executed without any problem.

**Comment by oupala** [comment]
@tcitworld Do you think creating a default user with a default login and a default password is really secure?

Many people with leave this user untouched, opening backdoor to installed Wallabag's instances.

I think it would be more secure:

- to **not** create any user at install time, there should another step to create the user via the CLI
- to create a default user following mandatory parameter at install time (user login, email, password)
- to **not** create any user at install time, but to create the first user on the first web login after the installation succeded (the *create user on first login* pattern)

What do you think?

**Comment by nicosomb** [comment]
Try this line: 
`php bin/console help fos:user:create --e=prod` 

About your last post, you're right. Pull request is welcome.

**Comment by tcitworld** [comment]
> Do you think creating a default user with a default login and a default password is really secure?

> Many people will with leave this user untouched, opening backdoor to installed Wallabag's instances.

I didn't say a default user was created with the `wallabag` / `wallabag` values. I said `wallabag` / `wallabag` were the default values for the user created at startup. **You can and should** change them during installation.

**Comment by nicosomb** [comment]
A default user with wallabag/wallabag is created in the package.

**Comment by oupala** [comment]
I got the exact same result while adding the `--e=prod` parameter:

```bash
>bin/console help fos:user:create --e=prod
PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /home/ops/apps/release-2.2.2/app/AppKernel.php on line 49
```

Is it normal?

**Comment by oupala** [comment]
@tcitworld If I should change the default user created at installation, you'd better not create a default user and let the person who is installing create its own user.

**Comment by oupala** [comment]
I tested the same command with another parameter: `--env=prod` instead of `--e=prod` (I'm not sure whether the latest can be a shortcut for the first parameter).

I get then another error:

```bash
>bin/console fos:create:user --env=prod totouser totoemail totopassword

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "fos:create" namespace.    
  Did you mean one of these?                                      
      fos:js-routing                                              
      fos:oauth-server                                            
      fos:user                                                    
      fos
```

**Comment by oupala** [comment]
In fact, this works:

```bash
>bin/console fos:user:create --env=prod totouser totoemail totopassword
```

**Comment by oupala** [comment]
By the way, there is no way to delete a user, the CLI can only deactivate a user. Is it normal?

**Comment by tcitworld** [comment]
> you'd better not create a default user and let the person who is installing Wallabag create its own user with its own login.

At the end of the `wallabag:install` command, **user is prompt for a username and a password**. It's enough.

> By the way, there is no way to delete a user, the CLI can only deactivate a user. Is it normal?

FOSUserBundle doesn't provide a way to remove a user, but admin can remove some manually and users can delete their own account (if they're not the only ones on the server).

**Comment by oupala** [comment]
I understand that you're using a framework to manage users. And do you mean that this framework, that aim to manage users, cannot delete users?

When I install Wallabag, I'm using the following command:

```bash
php bin/console wallabag:install --env=prod
```

As you can see, I'm not specifying any username and password on the command line. I cannot be prompted for anything as my script is run in a non-interactive way, by ansible.

I'm surprised that Wallabag create a default user (with a default non-secure password) even if not prompted to.

@nicosomb was ok to say it was an issue, but none of you told me what was the best solution, in your opinion, among the [3 solutions mentionned](#issuecomment-299675983].

**Comment by nicosomb** [comment]
I just sayed that we create a default user for the package (available here https://wllbg.org/latest-v2-package). 
But when you install wallabag via git and via `wallabag:install`, we *don't create* default user.

**Comment by oupala** [comment]
As far as I understand, the install process is:

- via git
  - `git clone`
  - `wallabag:install`
- via the package
  - (prepackaging made by Wallabag's team)
  - download the package
  - copy package files onto the server
  - `wallabag:install`

For each way to install Wallabag, when is the default `wallabag` user created?

From your previous message, when someone installs Wallabag via git, the user is created on the last step, when the `wallabag:install` command is run.

But some installs Wallabag from the package, I don't understand when is the default `wallabag` user created.

**Comment by nicosomb** [comment]
For the package, user don't execute `wallabag:install`. It's done by the wallabag's team. With wallabag/wallabag default credentials.

**Comment by oupala** [comment]
If I just un archive the archive, set the correct permissions, and access Wallabag from the browser, I get a http 503 status code and the logfile reports an error:

> [Thu May 11 23:56:03.178322 2017] [:error] [pid 26532] [client 192.168.50.112:42739] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /opt/release-2.2.2/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php on line 1147

If I execute Wallabag's installation:

```bash
sudo -H -u www-data bash -c 'php bin/console wallabag:install --env=prod'
```

I can now connect to Wallabag via a browser without any error.

Are you sure that executing `wallabag:install` is not mandatory?

**Comment by oupala** [comment]
Are you sure that executing `wallabag:install` is not mandatory?

**Comment by nicosomb** [comment]
Yes, as a wallabag core developer, I'm sure that wallabag:install is not mandatory when you download the archive. Please read the documentation: https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting
