### ISSUE TITLE
Youtube video not retreived

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3087]
### Issue details

In that webpage https://unodieuxconnard.com/2017/05/05/le-petit-theatre-des-operations/ a youtube video is embed but not retreived by Wallabagl

### Environment

* wallabag version (or git revision) that exhibits the issue:2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package? make update
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 7
* OS: debian 8
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

### Steps to reproduce/test case

try to grab the link above

**Comment by j0k3r** [comment]
You mean, it displays `[embedded content]` instead of the video?

**Comment by foxmask** [comment]
no I mean this 
![sans titre](https://cloud.githubusercontent.com/assets/208212/25840179/148f6174-349b-11e7-80bd-c09ed15c40cd.png)

**Comment by j0k3r** [comment]
Could you incept the code and tell me what's the html part of that blank space?
Also, are you using wallabag with https & some Content-Security-Policy?

**Comment by foxmask** [comment]
You got it . CSP is the cause.
I try to setup it for this external resource

**Comment by j0k3r** [comment]
Great, so I'm closing this since we already have an issue about CSP in wallabag https://github.com/wallabag/wallabag/issues/3070

**Comment by foxmask** [comment]
if that case, if you want, I could provide the rules I've setup for my own wallabag instance.

**Comment by j0k3r** [comment]
Yup could be a good start. Add them in the other issue :+1:
