### ISSUE TITLE
strange name after unarchiving: "release"

### ISSUE THREAD

**Issue by oupala** [wallabag/wallabag#3091]
### Issue details

The directory name after unarchiving the archive is very strange.

The name of the directory after unarchiving the archive is `release-2.2.2` which is not very helpful to know what it is about. I think it should be named something like `wallabag-2.2.2`.

### Environment

* wallabag version (or git revision) that exhibits the issue: wallabage 2.2.2 tar gz
* How did you install wallabag? Via `git clone` or by downloading the package? downloading
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version: -
* OS: -
* type of hosting (shared or dedicated): -
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): -

### Steps to reproduce/test case

- download Wallabag's tar.gz
- unarchive the file
- look at the name of the newly created directory

**Comment by nicosomb** [comment]
Won't fix that because we'll stop packaging.

**Comment by oupala** [comment]
Could you please explain your decision?

What will you stop and why?
