### ISSUE TITLE
Unable to delete articles

### ISSUE THREAD

**Issue by giovi321** [wallabag/wallabag#3092]
### Issue details

Unable to delete articles. When I click the delete icon i receive the following error:
500: Internal Server Error
The "/var/www/wallabag/app/../web/assets/images/3/6/3661ab9d" directory does not exist.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 2.2.1
* php version: PHP 5.6.30-0+deb8u1
* OS: Debian 8
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Add an article and try to delete it.

**Comment by nicosomb** [comment]
Hello @giovi321! 

It seems that you enabled "Download picture articles" feature. Is that true? 
The bug is not in the article deletion feature, but when wallabag tries to delete pictures.

**Comment by giovi321** [comment]
Exactly. I thought that this was the problem. Any possible fix for that?

**Comment by j0k3r** [comment]
Did you clear images folder before removing the entry.

**Comment by giovi321** [comment]
@j0k3r: you mean to manually delete the images related to the articles I want to delete from the wallabag server?

**Comment by j0k3r** [comment]
I mean, did you delete image folder and then later delete the article? 

Don't forget to give us the related URL, so we can try to reproduce.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by Elekam** [comment]
I am experiencing the same problem. I am trying to delete the first article I saved, which was accidentally my own wallabag domain. Now when I try to delete it, it says 
```
500: Internal Server Error 
The "/var/www/wallabag/web/assets/images/6/c/6c300461" directory does not exist.
```

And it indeed does not exist, neither in my docker mount or directly inside the container. The images folder is completely empty.
I am not sure how that happened? Something went wrong while trying to save the article and create the folders/download the images in the first place?

My instance:
* **Version**: 2.6.8
* **Installation**: Docker Image
* **PHP version**: Not sure
* **OS**: Ubuntu Desktop 20.04.01
* **Database**: mariadb
* **Parameters**:
`    database_driver: pdo_mysql
    database_host: db
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: wallapass
    database_path: '%kernel.project_dir%/data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://wallabag.my-domain.com'
    server_name: My-Server
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: EXPUNGED
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: wallabag@example.com
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null`

**Comment by adrian-fuertes** [comment]
> I am experiencing the same problem. I am trying to delete the first article I saved, which was accidentally my own wallabag domain. Now when I try to delete it, it says
> 
> ```
> 500: Internal Server Error 
> The "/var/www/wallabag/web/assets/images/6/c/6c300461" directory does not exist.
> ```
> 
> And it indeed does not exist, neither in my docker mount or directly inside the container. The images folder is completely empty. I am not sure how that happened? Something went wrong while trying to save the article and create the folders/download the images in the first place? Or maybe some misconfiguration of mine caused this?
> 
> My instance:
> 
>     * **Version**: 2.6.8
> 
>     * **Installation**: Docker Image
> 
>     * **PHP version**: Not sure
> 
>     * **OS**: Ubuntu Desktop 20.04.01
> 
>     * **Database**: mariadb
> 
>     * **Parameters**:
> 
> 
> ```
>     database_driver: pdo_mysql
>     database_host: db
>     database_port: 3306
>     database_name: wallabag
>     database_user: wallabag
>     database_password: wallapass
>     database_path: '%kernel.project_dir%/data/db/wallabag.sqlite'
>     database_table_prefix: wallabag_
>     database_socket: null
>     database_charset: utf8mb4
>     domain_name: 'https://wallabag.my-domain.com'
>     server_name: My-Server
>     mailer_dsn: 'smtp://127.0.0.1'
>     locale: en
>     secret: EXPUNGED
>     twofactor_sender: no-reply@wallabag.org
>     fosuser_registration: true
>     fosuser_confirmation: true
>     fos_oauth_server_access_token_lifetime: 3600
>     fos_oauth_server_refresh_token_lifetime: 1209600
>     from_email: wallabag@example.com
>     rss_limit: 50
>     rabbitmq_host: localhost
>     rabbitmq_port: 5672
>     rabbitmq_user: guest
>     rabbitmq_password: guest
>     rabbitmq_prefetch_count: 10
>     redis_scheme: tcp
>     redis_host: redis
>     redis_port: 6379
>     redis_path: null
>     redis_password: null
>     sentry_dsn: null
> ```

You have probably resolved this by now but I am facing the same issue: **I'm unable to delete any article with an embedded image.**

The only solution I found was disabling the "Download images locally" (using the admin/wallabag user: `Internal settings/Misc/Download images locally`). It's not really a great "solution", though I could never get the local image download to work anyways so it won't be missed.
