### ISSUE TITLE
Site https://wllbg.org is down.

### ISSUE THREAD

**Issue by Offertorium** [wallabag/wallabag#3094]
Hi there,
I would like to install wallabag on my hosting Server.  I follow the instructions on http://doc.wallabag.org/en/master/user/installation.html. 

When I download the lastest Release i became a Error 404.

Is the Site https://wllbg.org temporary down? Where can I download the lastest Release for Hosting Server?

Thx you and bye
 Fabian

**Comment by nicosomb** [comment]
wllbg.org (and shorten URLs) is back.
