### ISSUE TITLE
Support of CSP headers

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3098]
this is not really an issue, just a feedback of how I've manage that topic :

Here are some NGINX line of conf I put for my wallabag instance that could be used for other, in case they wanted to dig that topic :

```
    location ~ ^/app\.php(/|$) {

	add_header           Front-End-Https    on;
	add_header Cache-Control "public, must-revalidate";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
	add_header Referrer-Policy "same-origin";
        
        # add_header Content-Security-Policy-Report-Only  "default-src 'self'; script-src 'self'; img-src * 'self' data: https:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' www.googleadservices.com *.google.com *.doubleclick.net; object-src 'none'; child-src 'self' www.youtube.com; report-uri /csp_report.php;";
        add_header Content-Security-Policy "default-src 'self'; script-src 'self'; img-src * 'self' data: https:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' www.googleadservices.com *.google.com *.doubleclick.net; object-src 'none'; child-src 'self' www.youtube.com;";

	add_header X-Frame-Options SAMEORIGIN;
	add_header X-Content-Type-Options nosniff;
	add_header X-XSS-Protection "1; mode=block";
```

Various sources very useful: 

* https://www.alsacreations.com/article/lire/1723-tour-horizon-https-et-en-tetes-de-securite.html
* https://github.com/nico3333fr/CSP-useful/tree/master/csp-for-third-party-services

Various testing tools :

* https://observatory.mozilla.org/
* https://securityheaders.io/

A piece of php code (from the openweb article https://openweb.eu.org/articles/content-security-policy) that could be added to the project in case we wanted to use the header 

`Content-Security-Policy-Report-Only`

instead of 

`Content-Security-Policy-Report`

```
<?php
$data = file_get_contents('php://input');

if ($data = json_decode($data, true)) {

   $data = json_encode(

         $data,

         JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES

   );

   mail(EMAIL, SUBJECT, $data);

}
```

Last but not least, when you use your wallabag instance with an adblock you will see a lot of error message `net::ERR_BLOCKED_BY_CLIENT` that dont seem to block anything . 

But if you want you can disable the adblock inside the article you grabbed.

**Comment by j0k3r** [comment]
Could you better move your comment in that issue https://github.com/wallabag/wallabag/issues/3070? Thanks :)

**Comment by foxmask** [comment]
I thought this issue was more "if guys wanted to support CSP" where #3070 serms more "what wallabag need to do to support it"
