### ISSUE TITLE
Footnotes in website make the following text in article smaller

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3100]
### Issue details

Footnotes in website make the following text smaller

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2.
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 5
* OS: debian stable
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

### Steps to reproduce/test case

add an article, which contains footnotes to wallabag and try to read the article in wallabag. 

Example article: 
https://www.schreibdichte.de/blog/feed-aggregator-und-spaeter-lesen-dienst-im-team
see attached screenshot of that article

![2017-05-09-212614_6400x2160_scrot](https://cloud.githubusercontent.com/assets/97055/25868804/59a260fa-34fe-11e7-8028-4f680a7a6447.png)

I have seen this issue already in other websites, but i do not have the links anymore. And those sites only had one footnote and not that much in a row so that the text much smaller to unreadable like in this article

**Comment by j0k3r** [comment]
Can we just remove the footnotes links?

**Comment by Strubbl** [comment]
In the article above they contain a lot of information. They help understanding the article. Therefore i would like to keep them somehow.
