### ISSUE TITLE
Wallabag for Android: unable to "Download PDF"

### ISSUE THREAD

**Issue by returntrip** [wallabag/wallabag#3109]
### Issue details

Articles are not being downloaded as PDF in the Android app.

### Environment

* wallabag version (or git revision) that exhibits the issue: Android - ver 2.0.0b1
* How did you install wallabag? Via `git clone` or by downloading the package? Google Play
* Last wallabag version that did not exhibit the issue (if applicable): Not tested in other versions
* php version: NA
* OS: Android 7.1.2 stock on Nexus 6P
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):  NA

### Steps to reproduce/test case
On the Android app:

1) Open an article
2) From the drop down menu select: "Download PDF"
3) A progress bar will sit in the task bar saying: "wallabg downloads your article [article name]"
4) The article is not downloaded

**Comment by nicosomb** [comment]
This issue was moved to wallabag/android-app#521
