### ISSUE TITLE
Articles from TheVerge aren't being displayed properly

### ISSUE THREAD

**Issue by n00b12345** [wallabag/wallabag#3128]
None of the links from The Verge get parsed properly. You can try any link: https://www.theverge.com/2017/5/17/15561800/dating-apps-video-profile-tinder-lively-klip

Thankfully, the latest site config for The Verge from Five Filters is absolutely perfect. So I would request you to use that if possible. 

Please take a look.

Thanks. 

(I'm on 2.2.2)

**Comment by j0k3r** [comment]
If the lastest siteconfig from five filters works, then it'll be packaged in the upcoming 2.2.3 https://github.com/wallabag/wallabag/pull/3127 (to be released very soon)
Feel free to re-open if it's not the case 🙂
