### ISSUE TITLE
After update to 2.2.3, wallabag doesn't load (screen stays blank)

### ISSUE THREAD

**Issue by necrevistonnezr** [wallabag/wallabag#3129]
### Issue details
Updated from 2.2.2 to 2.2.3 via console as described here: https://doc.wallabag.org/en/admin/upgrade.html
Everything worked fine, no errors.
Afterwards, Wallabag does not load anymore, the website stays blank.
`/var/log/nginx/wallabag_error.log` 
shows the following errors:

`2017/05/18 13:27:06 [error] 1215#1215: *20043 FastCGI sent in stderr: 

"PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external e
ntity &quot;/var/www/wallabag/vendor/friendsofsymfony/oauth-server-bundle/Resour
ces/config/doctrine/Client.orm.xml&quot; in /var/www/wallabag/vendor/doctrine/or
m/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814

PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/wallabag/vendor/friendsofsymfony/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml&quot; in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814

PHP message: PHP Fatal error:  Uncaught Doctrine\Common\Persistence\Mapping\MappingException: Invalid mapping file 'FOS.OAuthServerBundle.Entity.Client.orm.xml' for class 'FOS\OAuthServerBundle\Entity\Client'. in /var/www/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86

Stack trace:

#0 /var/www/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\Common\Persistence\Mapping\MappingException::invalidMappingFile('FOS\\OAuthServer...', 'FOS.OAuthServer...')

#1 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\Common\Persistence\Mapping\Driver\FileDriver->getElement('FOS\\OAuthServer...')

#2 /var/www/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMetadataForClass('FOS\\OAuthServer...', Object(Doctrine\ORM\Mapping\ClassMetadata))

#3 /var/www/wallabag/vendor/doc" while reading response header from upstream, client: 212.114.255.213, server: missmuti.de, request: "GET /login HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "www.missmuti.de:5901"
`

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package?: Updated from 2.2.2 as described here: https://doc.wallabag.org/en/admin/upgrade.html
* Last wallabag version that did not exhibit the issue (if applicable): 2.2.2
* php version: 
> PHP 7.0.18-0ubuntu0.17.04.1 (cli) (built: Apr 26 2017 23:59:48) ( NTS )
> Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies with Zend OPcache v7.0.18-0ubuntu0.17.04.1, Copyright (c) 1999-2017, by Zend Technologies
* OS: Ubuntu 17.0.4
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Update, open Wallabag in browser.

**Comment by tcitworld** [comment]
It's this issue. You need to apply this after every update unfortunaltely.
https://doc.wallabag.org/en/user/faq.html#ive-got-the-failed-to-load-external-entity-error-when-i-try-to-install-wallabag
