### ISSUE TITLE
save an article that just concerns a file

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3131]
### Issue details

when you just want to save the URL of the page, the result is : "no title found" , no link, no content

eg : https://www.ssi.gouv.fr/uploads/2017/01/np_securisation_windows10_collecte_de_donnees.pdf
 
May be a solution could be to create an empty article with just of the URL link  and set the title as the filename itself (the basename of the url) ? 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package?git
* Last wallabag version that did not exhibit the issue (if applicable):n/a
* php version:7
* OS:debian 8.5
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):PostgreSQL

### Steps to reproduce/test case

 try to save the link of a page like a PDF.

**Comment by 2xyo** [comment]
Same here on https://www.framabag.org with https://www.ssi.gouv.fr/uploads/2017/01/np_securisation_windows10_collecte_de_donnees_v1.2.pdf

**Comment by Glandos** [comment]
Honestly, for PDF files, Wallabag could do a simple exception:
 - Download the file
 - Save it as-is in the database
 - when the user want to read it, put it in an object element: all browsers know how to handle PDF nowadays.

**Comment by Kdecherf** [comment]
@Glandos already planned, please see #2655

**Comment by Glandos** [comment]
Thanks, it was hard to find this feature request, even if I was sure it already existed.

**Comment by Kdecherf** [comment]
This issue has been fixed in version 2.3.1 by #3442
