### ISSUE TITLE
If I have an issue with a particular site-config, can I change it locally?

### ISSUE THREAD

**Issue by n00b12345** [wallabag/wallabag#3132]
Is it possible to change a site-config locally? The reason why I ask is because sometimes, to get the latest site-config, one has to wait for the next release. 

Thanks :)

**Comment by j0k3r** [comment]
Yep you can edit your file locally.

https://doc.wallabag.org/en/user/errors_during_fetching.html

**Comment by tcitworld** [comment]
More informations : the files are in the directory `vendor/j0k3r/graby-site-config` and **any change here will most probably be overwritten at each update**, so don't forget to push it upstream to us.

**Comment by n00b12345** [comment]
@tcitworld that's exactly what I needed! Thank you so much 👍
