### ISSUE TITLE
Wallabag can't retrieve contents for this article. 

### ISSUE THREAD

**Issue by mattkduran** [wallabag/wallabag#3136]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details
When adding article from wallabagit chrome extension, title of the article is added but no contents.

wallabag can't retrieve contents for this article. Please troubleshoot this issue.

When adding article directly from wallbag, both the article and title failed to be added. 

Link: http://www.npr.org/sections/parallels/2017/05/19/529148729/michael-flynns-contradictory-line-on-russia
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: PHP Version 7.0.16-3
* OS: Debian
* type of hosting (shared or dedicated): Shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Add link below to wallabag either from chrome extension or directly from dashboard:

http://www.npr.org/sections/parallels/2017/05/19/529148729/michael-flynns-contradictory-line-on-russia

**Comment by j0k3r** [comment]
Thanks for reporting.
It works fine using the upcoming 2.3.

![image](https://cloud.githubusercontent.com/assets/62333/26741535/04fa03ac-47da-11e7-94e6-50e217864c25.png)

**Comment by leggewie** [comment]
This is broken again, but in a different way now. npr.org shows a choice page to accept cookie settings.

**Comment by j0k3r** [comment]
Adding that to the site_config should solve the problem (but not on f43):

```
http_header(cookie): trackingChoice=true; choiceVersion=1; dateOfChoice=1538986154883
```

**Comment by fivefilters** [comment]
Added this to the site config, seems to work now: https://github.com/fivefilters/ftr-site-config/commit/baebfb111653b152e06a530ef71c160348e61f75

**Comment by j0k3r** [comment]
Still doesn't work on f43.me. I guess I have a problem with `http_header(Cookie)`

**Comment by j0k3r** [comment]
Fixed!
