### ISSUE TITLE
delete an article : being redirected to ...

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3140]
### Issue details

When deleting an article, that could be fine if we could stay on the page we were on and not going back to page 1 (or to /unread/list URL) . Same behavior when deleting an article from the list of articles filtered by given tag

currently, there is an option when article is marked as read: (from URL /config )

"Où souhaitez-vous être redirigé après avoir marqué un article comme lu ?"

may be another one when article is deleted ?

"Où souhaitez-vous être redirigé après avoir supprimé un article ?"

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS: debian 8.5
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

### Steps to reproduce/test case

delete an article from a page > 1 or from the URL "/tag/list/__a_tag__"

**Comment by foxmask** [comment]
when we have more than 100 articles to drop ; it's a pain to manage w/o this feature :(

**Comment by BNolet** [comment]
This issue seems to be persisting over a year and a half now. Any comment from the team as to when this might be implemented?
