### ISSUE TITLE
Upgrade Error

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#3141]
Hi

I upraded from 2.12 to 2.2.3 by following the documentation

From 2.1.x:

make update 

php bin/console doctrine:migrations:migrate --no-interaction -e=prod

Now I am getting 500: Internal Server Error I watched the terminal during upgrade and I did not see any errors

Here is the last portion of the database upgrade 

  ++ migrating 20170127093841

     -> DROP INDEX IDX_entry_uid
     -> CREATE TEMPORARY TABLE __temp__wallabag_entry AS SELECT id, user_id, uid, title, url, is_archived, is_starred, content, created_at, updated_at, mimetype, language, reading_time, domain_name, preview_picture, is_public FROM wallabag_entry
     -> DROP TABLE wallabag_entry
     -> CREATE TABLE wallabag_entry (id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, uid CLOB DEFAULT NULL COLLATE BINARY, title CLOB DEFAULT NULL COLLATE BINARY, url CLOB DEFAULT NULL COLLATE BINARY, is_archived BOOLEAN NOT NULL, is_starred BOOLEAN NOT NULL, content CLOB DEFAULT NULL COLLATE BINARY, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, mimetype CLOB DEFAULT NULL COLLATE BINARY, language CLOB DEFAULT NULL COLLATE BINARY, reading_time INTEGER DEFAULT NULL, domain_name CLOB DEFAULT NULL COLLATE BINARY, preview_picture CLOB DEFAULT NULL COLLATE BINARY, is_public BOOLEAN DEFAULT '"0"', PRIMARY KEY(id))
     -> INSERT INTO wallabag_entry (id, user_id, uid, title, url, is_archived, is_starred, content, created_at, updated_at, mimetype, language, reading_time, domain_name, preview_picture, is_public) SELECT id, user_id, uid, title, url, is_archived, is_starred, content, created_at, updated_at, mimetype, language, reading_time, domain_name, preview_picture, is_public FROM __temp__wallabag_entry
     -> DROP TABLE __temp__wallabag_entry
     -> CREATE INDEX IDX_entry_uid ON wallabag_entry (uid)
     -> CREATE INDEX IDX_entry_starred ON wallabag_entry (is_starred)
     -> CREATE INDEX IDX_entry_archived ON wallabag_entry (is_archived)

  ++ migrated (4.64s)

  ------------------------

  ++ finished in 23.56s
  ++ 15 migrations executed
  ++ 59 sql queries

Seems no error.

https://paste.debian.net/hidden/19ba995f/

Bear in mind that 2.1.2 was working perfectly so something went wrong with the upgrade

I am using Apache 2.2.22 on Debian Wheezy 32bit. I believe that I originally installed it using git clone method.

thanks

**Comment by j0k3r** [comment]
Could you show us the output of `php bin/console doctrine:migrations:migrate --no-interaction -e=prod` ?

**Comment by gerroon** [comment]
Application Migrations                    
                                                              

No migrations to execute.

**Comment by gerroon** [comment]
Also if I just type wallabag.url/about it does not give me any server error witht he results below



Developed by
    Nicolas Lœuillet — website
    Thomas Citharel — website
    Jérémy Benoist — website
And many others contributors ♥ on Github
Project website
    https://www.wallabag.org
License: MIT
Version: 2.2.3

However any other attempt to access anything lese results in the server error Igave above.

**Comment by gerroon** [comment]
Hi

Any ideas about how to handle this issue? I am kind of stuck here ;( 


thanks

**Comment by nicosomb** [comment]
Can you run each migration manually please? See https://gist.github.com/nicosomb/7c537995f2b845a30b4d6cdf23c1e22c

**Comment by gerroon** [comment]
@nicosomb 

I get this after. I did not try other steps yet

php bin/console doctrine:migration:execute 20161024212538 -e=prod

                                                                                                                               
  [Doctrine\DBAL\Exceptio\UniqueConstraintViolationException]                                                                 
  An exception occurred while executing 'INSERT INTO migration_versions (version) VALUES (?)' with params ["20161024212538"]:  
  SQLSTATE[23000]: Integrity constraint violation: 19 column version is not unique                                             
                                                                                                                               

                                                                                    
  [Doctrine\DBAL\Driver\PDOException]                                               
  SQLSTATE[23000]: Integrity constraint violation: 19 column version is not unique  
                                                                                    

                                                                                    
  [PDOException]                                                                    
  SQLSTATE[23000]: Integrity constraint violation: 19 column version is not unique

**Comment by gerroon** [comment]
Nevermind. I did  not see the sqlite commands. I think it is ok now. Let me try it for a day or so.


thanks

**Comment by j0k3r** [comment]
Is everything OK now?

**Comment by gerroon** [comment]
Yes, nicosomb`s manual upgrade method worked for me.
