### ISSUE TITLE
Wallabag can't retrieve contents for this article

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3142]
### Issue details

try to capture the page https://www.eff.org/deeplinks/2017/05/new-twitter-policy-abandons-longstanding-privacy-pledge

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via git clone or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7
* OS: debian 8.5
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql
* Steps to reproduce/test case

**Comment by j0k3r** [comment]
wallabag 2.2.4 doesn't exist :thinking: 
Anyway, it works fine on wallabag.it:

![image](https://cloud.githubusercontent.com/assets/62333/26342331/f49d4a90-3f97-11e7-97ff-eb3a4117dcaf.png)

**Comment by foxmask** [comment]
with 2.2.3, I cant ; I tried twice

**Comment by j0k3r** [comment]
It works fine too on my local using the upcoming 2.3.
Don't you have an other problem not related to wallabag?
Closing since I can't repro.
