### ISSUE TITLE
"Please troubleshoot this issue" leads to a 404

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3149]
### Issue details
when saving an article where the content is " wallabag can't retrieve contents for this article. Please troubleshoot this issue. " 
the link behind "troubleshoot this issue" leads to a 404 page => https://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Environment

* wallabag version (or git revision) that exhibits the issue:2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:7
* OS:debian 8.5
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or **PostgreSQL): PostgreSQL

**Comment by tcitworld** [comment]
The correct link is https://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that. PR welcomed.

**Comment by nicosomb** [comment]
Fixed with https://github.com/wallabag/wallabag/pull/3146. 👍
