### ISSUE TITLE
2 Unknown users appeared in account. Possibility of hack/intrusion?

### ISSUE THREAD

**Issue by jpincas** [wallabag/wallabag#3151]
Superb software - thanks so much for this.  I've had a strange occurrence less than 24 hours after installing the software.  It seems unlikely that my installation could have been hacked so quickly, but I guess it's possible?

### Issue details

Installed software this morning.  This afternoon I see two completely unknown users on my 'User Management' page.  Looks like they have never logged on, and clicking on each one show that the account is not 'enabled'

<img width="1250" alt="screen shot 2017-05-27 at 19 51 54" src="https://cloud.githubusercontent.com/assets/17711012/26523340/f77f2702-4315-11e7-87ed-16d6e8ea1a13.png">

### Environment

-  Digital ocean droplet
-  Installed on CoreOS with Docker
-  Using SQLlite

### Steps to reproduce/test case

-  Not sure at what point these users appeared, so don't know the steps to reproduce.
-  If it's relevant, I added about 25 articles from various sources before I saw this
-  I also set up the Chrome bookmarker by setting up a new API client in Wallabag

**Comment by tcitworld** [comment]
Is `registration_enabled` activated in `app/config/parameters.yml` ?

**Comment by jpincas** [comment]
Looking inside the docker container, I can't see an `app` directory.

<img width="490" alt="screen shot 2017-05-28 at 10 37 20" src="https://cloud.githubusercontent.com/assets/17711012/26527318/a4301ef4-4391-11e7-8e9b-ee53c2b69fc7.png">

**Comment by j0k3r** [comment]
Check in `/var/www/wallabag/app/config` directory

**Comment by jpincas** [comment]
OK - found it.  There is no `registration_enabled` parameter.  The closest seems to be `fouser_registration`.

**Comment by j0k3r** [comment]
Sorry, could you check for `fosuser_registration` instead?
If it's `true`, it means anyone can register on your wallabag instance.
You should set it to `false` and clear your cache (remove var/cache/*)

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by jpincas** [comment]
Im kind of stuck with it at the moment - which is why I hadn't come back.  I found the config line you referred to and changed it, but right now I can't login for some reason (my credentials are rejected even though they are correct and haven't changed), so when I get some time I was going to sit down and try to work out how to resent my credentials via the command line.
