### ISSUE TITLE
Handle JMS Serializer UTF8 issues through the API

### ISSUE THREAD

**Issue by bitmagewb** [wallabag/wallabag#3154]
The new Android client is causing PHP errors on my server when it tries to sync:

Upgraded Android client to 2.x and successfully retrieved API keys.  
Client starts syncing, then either fails with "Unknown error" or UnsuccessfulResponseException: HTTP Response: 500 Internal Server Error.  No articles are listed.

prod.log on server shows:
2017-05-27 18:05:29] request.INFO: Matched route "api_get_entries". {"route":"api_get_entries","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\EntryRestController::getEntriesAction","_format":"json","_route":"api_get_entries"},"request_uri":"https://myserver/api/entries.json?order=asc&page=11&perPage=30&since=0&sort=created","method":"GET"} []
[2017-05-27 18:05:29] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Your data could not be encoded because it contains invalid UTF8 characters." at /var/www/wallabag/vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php line 240 {"exception":"[object] (RuntimeException(code: 0): Your data could not be encoded because it contains invalid UTF8 characters. at /var/www/wallabag/vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php:240)"} []

The 1.x Android client and the web client continue to work without errors.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: PHP 5.5.38
* OS: CentOS release 6.9
* type of hosting (shared or dedicated): dedicated 
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case
Upgrade android client to 2.x version and connect.

**Comment by tcitworld** [comment]
Seems like you have an issue with badly encoded utf8 content in an entry. Maybe this could be handled better on the server. cc @wallabag/core

**Comment by tcitworld** [comment]
This issue was moved to wallabag/android-app#533

**Comment by bitmagewb** [comment]
Further detail:  I had the idea of exporting all my entries and then re-importing them to see if that would correct the issue.  The export as json command fails with a "500: Internal Server Error.  Your data could not be encoded because it contains invalid UTF8 characters." message in the browser.

Server side logged the same PHP error:
[2017-05-28 14:38:52] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Your data could not be encoded because it contains invalid UTF8 characters." at /var/www/wallabag/vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php line 240 {"exception":"[object] (RuntimeException(code: 0): Your data could not be encoded because it contains invalid UTF8 characters. at /var/www/wallabag/vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php:240)"} []

**Comment by j0k3r** [comment]
Can you list urls of your instance so we can try to find the one which break everything (to be able to reproduce the error)?

**Comment by bitmagewb** [comment]
I've got ~640 entries in my database, so that's going to be difficult.  Is there a way to instrument /JsonSerializationVisitor.php so it will give more detail on what it didn't like?

**Comment by bitmagewb** [comment]
Found it: http://www.ais.org/~jrh/acn/text/ACN8-1.txt
(Dumped sqlite db, ran iconv -t utf-8 dbdump to get position of illegal input sequence.)
Deleting that entry from my db gets exports and the Android 2.0 client working.  If I re-add it to my wallabag, everything breaks again.

**Comment by tcitworld** [comment]
@j0k3r  Could Graby utf8-encode the content before returning it ?

**Comment by sardaukar** [comment]
@bitmagewb I'd like to be able to pinpoint the entry too - how can I do the sqlite dump?

**Comment by j0k3r** [comment]
@tcitworld it could but this will required more test to be sure it doesn't double encode the content.

**Comment by bitmagewb** [comment]
@sardaukar
Grab a copy of your wallabag sqlite db file (from <install-path>/wallabag/data/db/wallabag.sqlite
Dump your wallabag database to a text file: $sqlite3 wallabag.sqlite .dump > dbdump
Run iconv on that file: $iconv -t utf-8 -o newout dbdump
iconv: illegal input sequence at position 3763370
iconv will return an offset of the first error, open newout in a text editor and look at the last entry in it.  That's where it stopped when it hit the badly encoded character.  Hopefully you can use the text of the entry containing the error to search for the article to delete from your wallabag.
I only had one article that had a problem character in it.  If you have more than one you will have to repeat the steps above. (or hand-edit dbdump to remove the offending characters and repeat the iconv test until it completes without errors.)

**Comment by sardaukar** [comment]
@bitmagewb thanks, managed to track the culprits down. They were all `txt` files, which is weird. But now it works! Cheers

**Comment by j0k3r** [comment]
Thanks to @aaa2000 that might be fixed in the upcoming 2.3

**Comment by pitched-jax-rs** [comment]
https://preprocessor.space/questions/error-message-invalid-utf-8-characters-detected-in-json-data I faced the same dilemma and found a path to resolution
