### ISSUE TITLE
list users via CLI

### ISSUE THREAD

**Issue by oupala** [wallabag/wallabag#3155]
### Issue details

Is there a way to list users and their attributes via CLI?

One usecase is by example that I need to create a user only if it does not exist.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? downloading
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 7.0
* OS: raspbian
* type of hosting (shared or dedicated): raspberry
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

n/a

**Comment by tcitworld** [comment]
Maybe more like a `user:show %username%` command ? wallabag.it and Framabag have thousands of users, we don't want them to show up all in our console.

**Comment by oupala** [comment]
Yes it could be a search feature with a filtering pattern:

- `user:show %username%` shows only user that match the `username`
- `user:show %` lists all users (even with large userbase, it could sometime be useful)

**Comment by oupala** [comment]
My usecase is that my ansible role is managing Wallabag's user.

As ansible is made to launch idempotent task, it tries to create the same users each time the playbook is launched.

In Wallabag, one cannot create the same user due to some unicity check in the database:

> Integrity constraint violation: 19 UNIQUE constraint fail

I need a way to check which users already exist in order to determiner which user should be created.

**Comment by oupala** [comment]
If the solution allows me to get information about a particular user (whose login is provided as a parameter), or even a way to tell if a given user exists or not, it would be a good starting point !

**Comment by nicosomb** [comment]
Please, **do not reply** to your issue each day. If we didn't reply, it's because we didn't have time for it.

**Comment by oupala** [comment]
Please don't get upset. I'm just adding some information in the issue tracker.

Feel free to reply whenever you want, whenever you can.

I'm not pushing you, I'm not saying "up up up" as I can sometime see in some forums.

**Comment by oupala** [comment]
Please don't get upset. I'm just adding some information in the issue tracker when I'm thinking a bit more about my problem.

Feel free to reply whenever you want, whenever you can.

I'm not pushing you, I'm not saying "up up up" as I can sometime see in some forums.

**Comment by j0k3r** [comment]
It might be better to be focus on one issue instead of multiple one.
https://github.com/wallabag/wallabag/issues/3156

**Comment by oupala** [comment]
I was expecting that this issue could be resolved in a relative short term while the other one was on a longer term basis (as you said: "So I guess it won't come early.").

But it is as you want.
