### ISSUE TITLE
Consider sending hash of URL to check if pages already saved

### ISSUE THREAD

**Issue by greigdp** [wallabag/wallabag#3157]
Just a suggestion, rather than a bug. The current implementation appears to send the full URL of pages visited to the server (https://github.com/wallabag/wallabagger/blob/master/wallabagger/js/wallabag-api.js#L218). There may be some risks as a result of this (for example, URLs containing auth tokens or other secrets etc, getting sent to the server).

If you run your own server, this should not be a massive risk (and there's always the option to disable it), although it would appear that the sending of the URL of each visited page could be avoided. One way would be to send the (e.g. SHA256/512) hash of the page URL (and store this on the server side to do a look-up). If there was any "fancy" processing of the URL to remove query parameters etc, this would need done at both client and server side to get the hash to match.

This would appear to preserve privacy of pages visited which are not added to wallabag (and ensuring minimum information is disclosed to the server which could be held in access logs), while preserving the UX benefits of allowing the user to tell if the page is already saved (and giving the green icon).

**Comment by tcitworld** [comment]
I totally agree on this.

cc @wallabag/contributors

**Comment by tcitworld** [comment]
Easy enough.

**Comment by greigdp** [comment]
Just thinking about this and looking over the patch (a long time since I used PHP though), I wonder if it's also worth incorporating a per-user salt to the hash. I am not familiar enough with the wallabag data model to know if such a salt exists (not the password salt). The idea here would be to attempt to mask data beyond passive traffic analysis (if users ignore the advice to use HTTPS). It would complicate the system though, as each logged in session would need to know this salt, and it would need to be stored in the database for new clients.

Maybe this is overkill? The idea would be to use HMAC_SHA512(salt, url), or something similar. That way, there's no way to generate a lookup table of hashes to URLs at the server-side, or to correlate visited URLs between users, since user 1 and user 2 will both generate a different hash for the same URL.

**Comment by Rurik19** [comment]
I am disagree. The hashe computing is quite heavy operation. Is it possible to implement in javascript? How lond will user wait after he clicked on the icon in browser? Will this work at all if computer doesn't have enought memory?

**Comment by di72nn** [comment]
// This should be a wallabagger issue (issue for wallabag is to create new API to implement it with hashes or something).

Sending every visited URL to server (it is what wallabagger does, right?) is very bad for a couple of reasons.
First of all, it is not really needed: I think most of the users "use" wallabagger only for a small fraction of pages they visit. Calling `exists` for every other page is just to waste resources (server receives a lot of unnecessary requests; precious browser performance is affected).
Privacy: it may be ok to report **all your browsing** to your own wallabag instance, but it is not ok for a third-party service (e. g. wallabag.it).
IMO, at best it should be a disabled by default option (so the check should be done on user demand). If it is optional, there is no need to implement it with hash.

> The hashe computing is quite heavy operation. Is it possible to implement in javascript?

Hash computation is cheap. Also it is implemented pretty much for any programming language.

**Comment by tcitworld** [comment]
@Rurik19 https://github.com/emn178/js-sha512

Didn't really benchmark but it's only a matter of milliseconds.

**Comment by tcitworld** [comment]
> precious browser performance is affected

The request should be made after that the page is loaded AFAIK.

**Comment by ThibaudDauce** [comment]
An other option is to pull (refresh) a list of all URLs saved at the beginning of a browser session and do a local check. It's a little bit of work for addons / apps but the server receive only one request (when the user open the browser instead of one request by tab) and the privacy is guaranteed.

One optimization could be to ask for a difference since the last browser local cache update (list of URLs saved and list of URLs removed since). But I think a full refresh is simpler to implement and not really a problem for most of the users (we may check for users with a lot of links).

One drawback is : "there is two problem in computer science : naming things and *cache invalidation*" :-D

**Comment by di72nn** [comment]
> The request should be made after that the page is loaded AFAIK.

I wonder how many other JavaScript stuff is called after the page is loaded. And it's not like the browser (or a PC in general) is going completely idle when the page is loaded.

> a list of all URLs saved at the beginning of a browser session

I'm not against it, but the amount of memory needed grows with number of entries (however, the list probably won't take much space in any case).
Other issue is that the list may get out of sync with changes from other clients.

**Comment by Rurik19** [comment]
if sha512 hache have length of 128 chars, then retrieving 1000 hashes takes 128k of traffic and memory to store. As for me, I have ~4000 records...

**Comment by ThibaudDauce** [comment]
> if sha512 hache have length of 128 chars

Since the cache is stored in the browser, no need to hash the URLs, we can just fetch all plain URLs.

>  then retrieving 1000 hashes takes 128k of traffic and memory

That's a lot… So we can ask for just the updates (new saved and new deletes) but it's a bit harder on the PHP side. I'm not sure if deletes are tracked right now (they could be tracked during a month or so, the time for clients to update their cache).

A JSON file of an array of 10,000 random URLs is 600ko, gzip is 146ko…

**Comment by Rurik19** [comment]
Let see this problem from other side - all worries about sending urls of visited pages is about only one feature of the wallabagger - to show green icon on already visited page. If it is such unsecure - may be we just remove this feature? We can show green icon on pages saved in the current browser session only.

**Comment by ThibaudDauce** [comment]
It's another possibility. But I think it's a good and unique feature (Pocket doesn't do that). Maybe a survey to see how many people use this and how many people want this?

Showing a green icon on pages saved in the current browser session only is useless for me, I have a short-term memory and I can remember what I saw during my day. It's more about articles saved a few weeks ago…

I think it's worth thinking about removing the feature.

**Comment by Rurik19** [comment]
As I see that hash computation is rather cheap operation, the first suggestion is also good, if "exists" function will accept hash that solves a security issue.

**Comment by Simounet** [comment]
I think that the cost of trying to save an already saved page is low. It's handy to see if I already saved this page but not necessary. We could remove this feature but improve the popup displaying the saved article with a mention that it is already store and where (unread / read) if the API could return this info (I didn't check it yet).

**Comment by tcitworld** [comment]
Okay, after viewing my server logs, I think we need to disable this feature asap.

**Comment by j0k3r** [comment]
But this feature isn't yet developped :thinking:

**Comment by tcitworld** [comment]
I'm talking about the `exists` API endpoint.

**Comment by j0k3r** [comment]
Maybe we just need a faster way to check if an url exist. Like using a key/value sort like Redis.

**Comment by nicosomb** [comment]
> Okay, after viewing my server logs, I think we need to disable this feature asap.

I understand your POV. 
But, this feature is disabled on wallabagger by default, right? So when you enable it, you know what you're doing, right?

**Comment by tcitworld** [comment]
> So when you enable it, you know what you're doing, right?

Not really, wallabagger should really warn the user better.

Moreover, it overloads the servers with requests not useful at all.

I agree this is rather useful for client apps like the Android app which uses this endpoint to make sure any entry hasn't been remotely deleted, but as wallabagger uses it, the benefits are too few in regard of the issues this brings.

**Comment by nicosomb** [comment]
> it overloads the servers with requests not useful at all.

👍 

@wallabag/core @jlnostr @di72nn @Rurik19 we need to discuss about this feature.

**Comment by di72nn** [comment]
The implementation that uses `exists` method is generally bad: it's not very effective, has security implications and creates additional server load. **It can be safely used only by users that host wallabag themselves and understand privacy implications.**

I think that [ThibaudDauce's suggestion](#issuecomment-304634535) should work for the most of the users (no matter self-hosting or not). I doubt even a couple of megabytes of memory used to store the list will be noticeable (considering how sites are bloated nowadays). And it can be optional.
However, there's no API method to get the list of saved URLs yet. There's also that "cache invalidation" problem, but it should be eventually solved with #2918.

**Comment by Rurik19** [comment]
I think the method should return all URLs or added since some time. This all return us to the discussion about getting the history of changes.

**Comment by nicosomb** [comment]
We need to do something with wallabagger about this usage of `/entries/exists`. Here are 2 screenshots of analytics on wallabag.it: 

<img width="429" alt="capture d ecran 2017-12-12 a 17 16 09" src="https://user-images.githubusercontent.com/121870/33896333-dd1c0882-df62-11e7-994b-85383517ac60.png">

<img width="593" alt="capture d ecran 2017-12-12 a 17 16 19" src="https://user-images.githubusercontent.com/121870/33896342-e0d6b832-df62-11e7-82fa-461a651345b0.png">

I shouldn't see these URLs and it seems that the addon sends the same URL many many times in few seconds (is that a bug?)

Last question: is the option disabled by default in wallabagger? 

ping @Simounet @Rurik19

**Comment by Rurik19** [comment]
@nicosomb Yes, that option is disabled by default. 
Which OS and browser do you use?

**Comment by Rurik19** [comment]
It correlates with  [#117 Avoid exists API for data URLs](https://github.com/wallabag/wallabagger/issues/117)
that guardian crossword helps me to understand the case: loading data:image causes TabUpdate event in the browser :smile:. Going to fix this today in the Dev branch

**Comment by buzuck** [comment]
Another option would be to use POST instead of GET, even if it goes against API's recommendations.
Hashing is still a must-have even with post though :)
