### ISSUE TITLE
Unable to scroll with zoom

### ISSUE THREAD

**Issue by he7d3r** [wallabag/wallabag#3159]
### Issue details
Unable to scroll.

### Environment

* wallabag version 2.2.2, on https://framabag.org

### Steps to reproduce/test case
1. Open an article using Firefox
2. Press F11 to go into full-screen mode
3. Press CTRL+ + to increase font size (sometimes not needed to reproduce the bug)
4. Try to scroll down without success

**Comment by tcitworld** [comment]
Strange issue, I only had it once and don't manage to reproduce it since (changing the zoom level allowed me to scroll again).
Doesn't happen on Chrome.

Shouldn't be related to Framabag anyway.

**Comment by nicosomb** [comment]
Can't reproduce.

**Comment by he7d3r** [comment]
I'm still able to reproduce the problem on Firefox 57.0.1 (64-bit) with the provided steps.

**Comment by j0k3r** [comment]
Is it still an issue?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
