### ISSUE TITLE
LocaleListener not found

### ISSUE THREAD

**Issue by dakarf** [wallabag/wallabag#3162]
I'm getting this error thrown out from php-fpm:
> PHP Fatal error:  Class 'Wallabag\CoreBundle\EventListener\LocaleListener' not found in /usr/local/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php on line 151

Wallabag stopped working, so I updated the git repository, and checked out to the current master (82a590fd). It's worth noting that I didn't manually modify anything locally except the parameters.yml file.
I then updated with `composer update` and didn't get any errors so I don't think anything is missing that is supposed to be there.

Current Wallabag is 82a590fd, that was fetched through git. The same issue is with tag 2.3 (d181bd72).
Not sure what was the previous version that used to work, but it was from at least a few months ago.
PHP is version `5.6.30` running on `FreeBSD 10.3-STABLE` in a jail on a private server.
The storage is `MySQL` which used in the past just fine (with previous Wallabag), and nothing changed so I can't imagine that would be even remotely related.

I'm not sure how to reproduce this. I imagine something's missing from my composer.json, or something wasn't properly updated even though there weren't any errors in the update process.

FWIW, Google suggests this is an issue related to Symfony.

**Comment by j0k3r** [comment]
> Wallabag stopped working

Which means?
How is it stopped working? Did you do something?

How did you get that fatal error?
Could you tell use the version of symfony/symfony from your composer.lock?

**Comment by dakarf** [comment]
>Which means?
>How is it stopped working? Did you do something?

I didn't 'do' anything in particular. I regularly update services, but didn't touch anything of Wallabag.

>How did you get that fatal error?

The fatal error is in the logs whenever a web client or Android client tries to access the server.

>Could you tell use the version of symfony/symfony from your composer.lock?

This is the output of `composer help|grep symfony`. I hope this is what you're referring to.
# composer info|grep symfony
friendsofsymfony/jsrouting-bundle    1.6.0       A pretty nice way to expose your Symfony2 routing to client applications.
friendsofsymfony/oauth-server-bundle 1.5.2       Symfony2 OAuth Server Bundle
friendsofsymfony/oauth2-php          1.2.1       OAuth2 library
friendsofsymfony/rest-bundle         2.2.0       This Bundle provides various tools to rapidly develop RESTful API's with Symfony
friendsofsymfony/user-bundle         v2.0.0      Symfony FOSUserBundle
symfony/monolog-bundle               v3.1.0      Symfony MonologBundle
symfony/phpunit-bridge               v3.3.0      Symfony PHPUnit Bridge
symfony/polyfill-intl-icu            v1.3.0      Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.3.0      Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.3.0      Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.3.0      Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                v1.3.0      Symfony utilities for portability of PHP codes
symfony/swiftmailer-bundle           v2.6.2      Symfony SwiftmailerBundle
symfony/symfony                      v3.2.9      The Symfony PHP framework

**Comment by j0k3r** [comment]
Ok strange.
I think it's best if you stay on a tag instead of using the master / 2.3 branch which can be instable.

Could you try to remove the folder `var/cache/*` and refresh the app to see if you still have the issue?

**Comment by dakarf** [comment]
>Could you try to remove the folder var/cache/* and refresh the app to see if you still have the issue?

This solved the issue. Maybe this should've been done automatically?

**Comment by j0k3r** [comment]
Well, as a final user you should not switch from branch to branch or jump into the master branch etc.
With the prod env enable, the cache isn't cleared when you do such things. Which is totally normal because you shouldn't do such things.
In dev mode the cache is always rebuild.

That's why I said to our final user to stick on a tag (a release) instead of jumping around to try to solve the problem and then find new one which are in fact, not bug.

BTW the update/upgrade process when we release a new version include the cache clear, obviously.
