### ISSUE TITLE
tag field hidden by menu, from mobile render on Firefox mobile v 52

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3164]
### Issue details

To add a tag to an article, the menu stays opened, then the tag field is not visible even if we can fill it by guessing where the cursor is

### Environment

* wallabag version (or git revision) that exhibits the issue:2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? Git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:7
* OS: debian 8.5
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

### Steps to reproduce/test case

On mobile version, try to add a tag

**Comment by j0k3r** [comment]
Screenshots?

**Comment by nicosomb** [comment]
![](https://lut.im/kZJKgo9dwa/FXOjbhL84UsOvq8J)

**Comment by foxmask** [comment]
flute I made it but I forgot it :)

**Comment by j0k3r** [comment]
Is it still an issue? Because we don't have the screenshot anymore..

**Comment by Kdecherf** [comment]
Yes, see this one (_tag input has the focus_):

![2019-06-06-003328_2560x1440](https://user-images.githubusercontent.com/226063/58995015-c8ab0f80-87f2-11e9-9ba1-72ec85230aea.png)

**Comment by foxmask** [comment]
I don't use wallabag anymore
