### ISSUE TITLE
404 for the link "errors_during_fetching.html#how-can-i-help-to-fix-that"

### ISSUE THREAD

**Issue by tdelmas** [wallabag/wallabag#3166]
That link, used by github template issues and shown by the android app is a 404 :

http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

**Comment by j0k3r** [comment]
Yep it should be http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that
And it'll be fixed in the next release of wallabag: https://github.com/wallabag/wallabag/pull/3146

**Comment by tdelmas** [comment]
(sorry for the partially duplicate issue with #3149 )

- For the android application issue, #3146 Fix it (but a redirect could help too, if easily feasible...)

- Did you noticed the part about the **github issue template** ? 
> :warning: If your issue is about an error during fetching a link, please read: 
> http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that

- More generally, it seams that some pages links to http://doc.wallabag.org/en/master/user/... instead of http://doc.wallabag.org/en/user/... (for example, https://doc.wallabag.org/en/master/user/faq.html instead of https://doc.wallabag.org/en/user/faq.html ) : https://www.google.fr/search?q=oc.wallabag.org%2Fen%2Fmaster%2Fuser so maybe a general redirect should be considered, or at least a better 404 maybe?

**Comment by j0k3r** [comment]
poke @nicosomb ☝️

**Comment by nicosomb** [comment]
This issue was moved to wallabag/doc#28
