### ISSUE TITLE
Wrong display in wallabag (cairn.info)

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#3174]
### Issue details

- I want read http://www.cairn.info/revue-espace-geographique-2010-2-page-159.htm 
- but : we have error during fetching (wallabag can't retrieve contents for this article) and it's work on f43.me

### Environment
- framabag

### Steps to reproduce/test case
I just try to bag it this link

**Comment by tcitworld** [comment]
Seems to work with 2.2.3 on `app.wallabag.it`. Let's wait until framabag.org is updated.

**Comment by prolibre** [comment]
Hello.

+1 for me

For : https://www.cairn.info/revue-spirale-2004-3-page-15.htm
wallabag can't retrieve contents for this article.

It's ok in f43.me

Thanks

**Comment by FrapiFrance** [comment]
Hello, as said in the duplicate #6055 , I confirm the issue on a self-hosted dockerised wallabag 2.3.8 on a raspberry pi 3.
[graby.log](https://github.com/wallabag/wallabag/files/9936221/graby.log)

I'm not very familiar with these graby logs, but it seems that graby find a real lengthy content ("body":"(only length for debug): 238101";  Body size after Readability: 162882 ) but in fine the page on wallabag is on error.

On f43.me, first attempt shows the page ; a reload shows an error.

(tested with https://www.cairn.info/revue-internationale-de-politique-comparee-2001-1-page-59.htm , but it seems that all cairn.info pages have the issue)

**Comment by fradav** [comment]
Hello, that will not be easy to solve : as you can see it in the returned headers, it’s protected by datadome antibot measures from cloudflare. 
For my part, I intend to proxify my local wallabag instance with https://github.com/FlareSolverr/FlareSolverr to solve those type of problems.

**Comment by HolgerAusB** [comment]
@fradav Sounds interesting. Could you please provide more information about how you implemented Flare Solverr with wallabag?

**Comment by FrapiFrance** [comment]
Hi, any update on this issue ?
It 's still there with a brand new 2.6.9 (self-hosted, docker, raspberry pi arm)
