### ISSUE TITLE
Wallabag doesn't get the right content for page, f43.me does

### ISSUE THREAD

**Issue by marblepebble** [wallabag/wallabag#3178]
### Issue details

Adding this link to my wallabag 2.2.3 install got a good cover image, but the article content is replaced with a couple of ads. I tried it in f43.me as the help suggested, and I get the right content there.

https://gamedevelopment.tutsplus.com/tutorials/creating-hexagonal-minesweeper--cms-28655

I have about 300 other pages saved that worked OK.

### Environment

* wallabag version 2.2.3
* Docker; the wallabag/docker docker image but I have symlinked the image dir to the data dir to workaround a different issue that has since been fixed. I don't think that should affect this issue.
* Last wallabag version that did not exhibit the issue (if applicable): N/A I think
* php version: (whatever the docker image uses)
* OS: Host is QNAP NAS, 4.3 (latest) firmware
* type of hosting (shared or dedicated): It's the only thing running in its container, but there are other containers, and a single nginx forwarding to them
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Add https://gamedevelopment.tutsplus.com/tutorials/creating-hexagonal-minesweeper--cms-28655 to wallabag (other tutsplus.com urls also show the problem).

**Comment by j0k3r** [comment]
f43.me is often more up to date than the latest wallabag release (in terme of siteconfigs).
That's why it works on f43.me and not on wallabag 2.2.3.

On wallabag 2.3 it works:
![image](https://cloud.githubusercontent.com/assets/62333/26741165/92b9cb52-47d8-11e7-8dfa-39c68f74b956.png)

It'll be fixed when 2.3 will be released.
