### ISSUE TITLE
Parser: add support for list's start attribute

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabag#3185]
### Issue details

In HTML, lists can have a "start" attribute that allows a number in the list, instead of the default one.

### Environment

Wallabagit & f43.me

### Steps to reproduce/test case

Store this article: http://www.timothysykes.com/blog/10-things-know-short-selling/
Scroll to "“Called out” or “Buy in”", it's point 4 in the article, but point 1 in the stored article. By inspecting the HTML code, you will find that the parser removes the "start" attribute.

Thanks

**Comment by tcitworld** [comment]
cc @j0k3r, related to Graby

**Comment by j0k3r** [comment]
This issue was moved to j0k3r/graby#111
