### ISSUE TITLE
Validate the fetched item properties

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#3186]
When I checked the database of @JeffMelton to determine what caused the windows app to crash, I found the issues in the database. I found json entries like:

    "preview_picture":"https:"

or

     "language":"{{locale}}"

The first one isn't a valid uri according to the RFC standards, and the second one isn't a language code. A basic check if the fetched data is correct would be nice.

**Comment by j0k3r** [comment]
Good suggestion @jlnostr !
