### ISSUE TITLE
[postgresql] Database migration fails from 2.1.2 to 2.2.3

### ISSUE THREAD

**Issue by skibbipl** [wallabag/wallabag#3190]
### Issue details

I tried to upgrade my pretty old self hosted wallabag v2 instance but it fails with SQL errors.
```
Migrating up to 20160916201049 from 0

  ++ migrating 20160410190541

     -> ALTER TABLE "wallabag_entry" ADD uuid UUID DEFAULT NULL
Migration 20160410190541 failed during Execution. Error An exception occurred while executing 'ALTER TABLE "wallabag_entry" ADD uuid UUID DEFAULT NULL':

SQLSTATE[42701]: Duplicate column: 7 ERROR:  column "uuid" of relation "wallabag_entry" already exists

  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'ALTER TABLE "wallabag_entry" ADD uuid UUID DEFAULT NULL':
  SQLSTATE[42701]: Duplicate column: 7 ERROR:  column "uuid" of relation "wallabag_entry" already exists

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42701]: Duplicate column: 7 ERROR:  column "uuid" of relation "wallabag_entry" already exists

  [PDOException]
  SQLSTATE[42701]: Duplicate column: 7 ERROR:  column "uuid" of relation "wallabag_entry" already exists
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.1.2 -> 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? `make update` over previous version.
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: 7.1.4
* OS: Debian 9
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Execute command `php bin/console doctrine:migrations:migrate --no-interaction -e=prod`

**Comment by j0k3r** [comment]
Did you re-run the command and still get the error?

**Comment by skibbipl** [comment]
Still getting the same error.

**Comment by j0k3r** [comment]
Hum this is really strange because we check if the field exists before trying to create it: https://github.com/wallabag/wallabag/blob/38c73f9691b27624d9f5f3f410ab233aa86cf1ea/app/DoctrineMigrations/Version20160410190541.php#L37

Can you update that file with this snippet and put it on line 36:

```php
var_dump($entryTable->getColumns()); die();
```

And give us the output.

**Comment by skibbipl** [comment]
```
PHP Notice:  Undefined variable: entryTable in /var/www/wallabag2/app/DoctrineMigrations/Version20160410190541.php on line 37

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function getColumns() on null
```

**Comment by j0k3r** [comment]
:thinking: 
Could you put the var_dump right after that line: `$entryTable = $schema->getTable($this->getTable('entry'));` ?

**Comment by skibbipl** [comment]
I've just discovered that my git was in a detached state. Therefore upgrade script didn't update all the files correctly. I've restored wallabag data from backup, fixed the git state and successully updated to 2.2.3 version.
Sorry for the trouble.
