### ISSUE TITLE
Improve image URLs regular expressions

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#3191]
I opened this PR https://github.com/wallabag/android-app/pull/546 for the android app.
@nicosomb @j0k3r  could you check if you are handling all cases properly in wallabag web? Thank you!

**Comment by j0k3r** [comment]
What should we do here?
I think you should better ping us from the issue in the android-app repo instead of creating an issue here to ping us 🙂

**Comment by ngosang** [comment]
I thought you were using regular expressions to find images to download in html code. Now I saw this code => https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Helper/DownloadImages.php#L55
If you are not using regular expressions in other parts of the code you can close this issue.

**Comment by j0k3r** [comment]
We are not using regex to find image 🙂
