### ISSUE TITLE
Feature: bulk operations

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabag#3196]
Hi,

It would be really useful to be able to have bulk operations for:

- tagging
- marking as read
- delete

Thanks!

Edit: might be linked to #3118?

**Comment by nicosomb** [comment]
Hello @pVesian 

There is already an issue for this feature, see https://github.com/wallabag/wallabag/issues/3118

**Comment by pVesian** [comment]
@nicosomb Indeed, thanks
