### ISSUE TITLE
Config label improvement

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabag#3199]
Hi,

My English is far from perfect, but I believe the label ["Where do you want to be redirected after mark an article as read?"](https://github.com/wallabag/wallabag/blob/f87e6547e8c49a2fe4bd21ec185e99464d4d957e/src/Wallabag/CoreBundle/Resources/translations/messages.en.yml#L74) can be improved to something like "Where do you want to be redirected to after marking an article as read?".

Thanks

**Comment by j0k3r** [comment]
Feel free to open a PR, you can do that directly from GitHub: https://github.com/wallabag/wallabag/edit/master/src/Wallabag/CoreBundle/Resources/translations/messages.en.yml

**Comment by pVesian** [comment]
@j0k3r I'd love to, but maybe it's used elsewhere too? I don't know Wallabag well enough, I don't want to break it :)

**Comment by j0k3r** [comment]
You won't break it, we'll still validate it before, don't worry
