### ISSUE TITLE
Baggy/Material difference: Wrong number of items in tags

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabag#3201]
Hi,

### Issue details

The number of items in a tag is different in Baggy than in Material. At first I thought Baggy contained the number of pages, but that's not true for at least one of the tags (bitcoin).
![screenshot-app wallabag it-2017-06-09-11-42-07](https://user-images.githubusercontent.com/3509962/26970370-6f29e056-4d09-11e7-8e0b-b1426bd4e765.png)
![screenshot-app wallabag it-2017-06-09-11-46-16](https://user-images.githubusercontent.com/3509962/26970376-71022190-4d09-11e7-96d5-996f5fcf5118.png)

### Environment

Wallabagit

### Steps to reproduce/test case

* Have some tagged items
* Use Baggy, go to the tags list
* Use Material, go to the list
* Compare the numbers

Thanks!

**Comment by j0k3r** [comment]
Thansk, this will be fixed in the next release!
