### ISSUE TITLE
Material: FR translation doesn't fit

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabag#3210]
Hi,

### Issue details

The FR (maybe others too) "mark as unread" doesn't fit in the menu (see screenshot).
So either the menu should have a dynamic width, or another translation should be found.

In the second case, all translation files should be checked.

![screenshot-app wallabag it-2017-06-09-11-25-02](https://user-images.githubusercontent.com/3509962/27004259-a516a1b0-4e06-11e7-9439-4b8bde1ab865.png)

### Environment

Wallabagit

### Steps to reproduce/test case

- Switch to FR
- Go inside a read article
- Hover the left menu: "marquer comme non lu" doesn't fit

**Comment by j0k3r** [comment]
Duplicate https://github.com/wallabag/wallabag/issues/2475
