### ISSUE TITLE
Page not fully secure

### ISSUE THREAD

**Issue by n00b12345** [wallabag/wallabag#3211]
For some weird reason, Wallabag's article pages (Unread/Archive/All entries pages) crop up as _not_ fully secure on Chrome and Firefox, even when https is being used.

All other pages such as individual articles, internal settings, config, login screens etc. are fully secure and show up with the green lock logo on browsers.

Is there a specific reason for this?

(I run wallabag's latest stable shared hosting version)

**Comment by j0k3r** [comment]
Did you enable downloading image locally or not?
Otherwise the preview image displayed on the listing might display image using http.

**Comment by tcitworld** [comment]
At wallabag.it and framabag we use camo to proxy all the pictures through HTTPS and avoid this. We will write something about this asap.

**Comment by n00b12345** [comment]
@j0k3r I haven't disabled anything related to that. Is there a way to disable downloading images locally?

**Comment by j0k3r** [comment]
It's disabled by default.
If you didn't touch the settings under "internal settings" it shouldn't be enable. Which mean preview image come from the website article and might not be https.

**Comment by n00b12345** [comment]
@j0k3r yay! That works! Fantastic. Thank you 👍
