### ISSUE TITLE
Error during upgrade (2.1 to 2.2.3)

### ISSUE THREAD

**Issue by ArthurGarnier** [wallabag/wallabag#3214]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

During the installation of 2.2.1 (make install && ./install or SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist) I get this error : 

```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "executors" under "rulerz"             
```                    

Apparently it's during the "cache:clear --no-warmup" step

                                                                                     
```
  [RuntimeException]                                                                 
  An error occurred when executing the "'cache:clear --no-warmup'" command:          
                                                                                     
    [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]    
    Unrecognized option "executors" under "rulerz"                                   
                                                                                              
```                                                                          

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3 (but also happen with 2.3 and 2.1 now, my old working installation => Probably due to dependency upgrade)
* How did you install wallabag? Via `git clone` or by downloading the package? Git clone
* Last wallabag version that did not exhibit the issue (if applicable): 2.1
* php version: 7.0.19-1
* OS: Debian Stretch
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

I can't find any similar issue on Google, I think it's hard to reproduce but : 
* Install wallabag with 2.1 tag
* Checkout to 2.2.3 and follow installation instructions

**Comment by j0k3r** [comment]
Could you remove the content of `var/cache/*` and try again?

**Comment by ArthurGarnier** [comment]
It works ! Thanks !
I have some authentication issue now (probably due to migration, but I'll check that.
