### ISSUE TITLE
lifehacker.com: images in article are missing

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3217]
### Issue details

Images in lifehacker.com articles are missing. The first image in the article is loaded, but the others are not.
E.g.: http://lifehacker.com/5970995/im-chef-aaron-sanchez-and-this-is-how-i-work

Text content is fetched. 👍 

### Environment

* wallabag version (or git revision) that exhibits the issue:2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package?git
* Last wallabag version that did not exhibit the issue (if applicable):-
* php version:
* OS:debian stable
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):mysql

### Steps to reproduce/test case

- add http://lifehacker.com/5970995/im-chef-aaron-sanchez-and-this-is-how-i-work
- look for the dynamically loaded images in the article, e.g. https://i.kinja-img.com/gawker-media/image/upload/s--L-uaWsUj--/c_fit,fl_progressive,q_80,w_636/189k819yhdof9jpg.jpg , which are missing in the wallabag's content

**Comment by j0k3r** [comment]
It'll require some work to handle image replacement since the whole html for only one image is:

```html
<figure class="js_marquee-assetfigure align--center"style="max-width:533px;">
   <div class="img-wrapper lazy-image ">
      <div class="img-permalink-sub-wrapper" style="padding-bottom: 150.1%">
         <span class="js_lightbox-wrapper lightbox-wrapper">
            <span class="magnifier js_lightbox lightbox hide">
               <svg class="svg-icon svg-zoom-in">
                  <use xlink:href="#iconset-zoom-in" />
               </svg>
            </span>
            <picture>
               <source class="ls-small-media-source"data-srcset="https://i.kinja-img.com/gawker-media/image/upload/s--L-uaWsUj--/c_fit,fl_progressive,q_80,w_636/189k819yhdof9jpg.jpg"media="--small" />
               <source data-srcset="https://i.kinja-img.com/gawker-media/image/upload/s--L-uaWsUj--/c_fit,fl_progressive,q_80,w_636/189k819yhdof9jpg.jpg" media="--xlarge" />
               <source data-srcset="https://i.kinja-img.com/gawker-media/image/upload/s--L-uaWsUj--/c_fit,fl_progressive,q_80,w_636/189k819yhdof9jpg.jpg" />
               <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" class="lazyload ls-lazy-image-tag" data-sizes="auto"data-chomp-id="189k819yhdof9jpg" data-format="jpg" />
            </picture>
         </span>
      </div>
   </div>
</figure>
```
