### ISSUE TITLE
Usage of Webpack Encore

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#3222]
See http://symfony.com/doc/current/frontend.html & https://symfony.com/blog/introducing-webpack-encore-for-asset-management

**Comment by Kdecherf** [comment]
Is this issue still relevant following the recent push of yarn?

**Comment by tcitworld** [comment]
> the recent push of yarn

?

**Comment by tcitworld** [comment]
Webpack Encore is nice for starters projects, but we have some tweaking here due to old js libraries and I don't think they would work out of the box. Also, different entries and produced files.

**Comment by Kdecherf** [comment]
All webpack stuff are currently handled by yarn/npm, do we need to move it on sf?
