### ISSUE TITLE
cannot fetch content of http://www.wheels.ca

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3224]
### Issue details

can't fetch the content of articles from wheels.ca, e.g. http://www.wheels.ca/news/fascinating-story-behind-delorean/

### Environment

* wallabag version (or git revision) that exhibits the issue:2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package?git
* Last wallabag version that did not exhibit the issue (if applicable):-
* php version:
* OS:debian
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):mysql

### Steps to reproduce/test case

add http://www.wheels.ca/news/fascinating-story-behind-delorean/ and see no content is fetched

**Comment by j0k3r** [comment]
Content is well fetched for me on wallabag.it (also on 2.2.3) and locally on the 2.3

![image](https://user-images.githubusercontent.com/62333/27261188-17cb119a-543e-11e7-9c95-326c09ddf932.png)

Might be a problem on your local instance? Can you debug it on your side?

**Comment by Strubbl** [comment]
Thank you. My instance had a problem.
