### ISSUE TITLE
cannot fetch content for tailordev.fr

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3225]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

no content fetched for tailordev.fr, e.g. https://tailordev.fr/blog/2017/06/09/deploying-a-go-app-with-systemd-socket-activation/

### Environment

* wallabag version (or git revision) that exhibits the issue:2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package?git
* Last wallabag version that did not exhibit the issue (if applicable):-
* php version:
* OS:debian
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):mysql

### Steps to reproduce/test case

add https://tailordev.fr/blog/2017/06/09/deploying-a-go-app-with-systemd-socket-activation/ and see no content is fetched

**Comment by j0k3r** [comment]
Same as previous, works on 2.3 and wallabag.it (on 2.2.3).

![image](https://user-images.githubusercontent.com/62333/27261248-9c0f4c68-543f-11e7-8c71-b83654e27e7f.png)

Can this be related to your own installation? Can you debug it?

**Comment by Strubbl** [comment]
Thank you. My instance had a problem.
