### ISSUE TITLE
cannot fetch content of scientificamerican.com

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3226]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

cannot fetch content of scientificamerican.com, e.g. https://www.scientificamerican.com/article/the-surprising-problem-of-too-much-talent/

### Environment

* wallabag version (or git revision) that exhibits the issue:2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package?git
* Last wallabag version that did not exhibit the issue (if applicable):-
* php version:
* OS:debian
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):mysql

### Steps to reproduce/test case

add https://www.scientificamerican.com/article/the-surprising-problem-of-too-much-talent/ and see no content is fetched

**Comment by j0k3r** [comment]
Same.
Works on 2.3 and on wallabag.it (on 2.2.3)

![image](https://user-images.githubusercontent.com/62333/27261286-8ded7ff0-5440-11e7-9cdb-baf360e5c71a.png)

**Comment by Strubbl** [comment]
Thank you. My instance had a problem.
