### ISSUE TITLE
Can't fetch content from everydayfeminism.com, but f43.me works. (New siteconfig also works)

### ISSUE THREAD

**Issue by GeoffMaciolek** [wallabag/wallabag#3228]
### Issue details

* Wallabag cannot fetch the content of articles from everydayfeminism.com, e.g. http://everydayfeminism.com/2017/05/support-autistic-community/
* [f43.me](http://f43.me/feed/test) **does** load the site correctly.
* Generating a siteconfig with http://siteconfig.fivefilters.org and using it with wallabag **also** works.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2, 2.2.3
* How did you install wallabag? *I believe* `git clone` *- though 2.2.3 was via* `make update`
* Last wallabag version that did not exhibit the issue (if applicable): *Unknown / n/a*
* php version: 7.0.18
* OS: Ubuntu Server 16.04.2 LTS
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install: MySQL/MariaDB (MariaDB 10.0.29)

### Steps to reproduce/test case

* Add http://everydayfeminism.com/2017/05/support-autistic-community/
* Note that the title & header image appear, folllowed by the usual
> wallabag can't retrieve contents for this article. Please [troubleshoot this issue](http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that).
* Generate a siteconfig using http://siteconfig.fivefilters.org (or use this one: [everydayfeminism.com.txt](https://github.com/wallabag/wallabag/files/1075331/everydayfeminism.com.txt))
* Place the `everydayfeminism.com.txt` siteconfig into `vendor/j0k3r/graby-site-config/`
* Reload / re-retrieve the site
* Verify that the site loads correctly.

### Extra thoughts

I can submit a pull request with this new siteconfig (or a better one), but given the docs, it seems like this is a result of an internal issue, and a siteconfig would just be a workaround.  But, if a pull request w/siteconfig would help, I'm glad to do so.

**Comment by j0k3r** [comment]
Thanks @GeoffMaciolek !
Next time you can submit your new file to https://github.com/fivefilters/ftr-site-config directly 😉
