### ISSUE TITLE
Wallabag and print support

### ISSUE THREAD

**Issue by oupala** [wallabag/wallabag#3233]
### Issue details

Wallabag does not seem to support print feature.

When I try to print a long article, only the first page is printed, with Wallabag's menu on the left...

This has been tested with this article: http://etunpeudeneurologie.blogspot.fr/2017/06/agnosie-de-lempan-cognitif-le-truc-que.html?m=1

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? downloading the package
* Last wallabag version that did not exhibit the issue (if applicable): don't know
* php version: don't know
* OS: framabag
* type of hosting (shared or dedicated): framabag
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): framabag

### Steps to reproduce/test case

- add an article that is more than one page long
- try to print it using the *print* menu on the left

**Comment by zertrin** [comment]
Same here, only first page is printed, however without wallabag's menu.

* wallabag version: 2.3.1
* installed with git clone
* OS: Debian stretch
* selfhosted
* storage is MySQL

**Comment by j0k3r** [comment]
No news.
Contributions are welcome btw.

**Comment by GusevVictor** [comment]
Please fix it. It print only for first page. Thank!

**Comment by nicosomb** [comment]
I think that https://github.com/wallabag/wallabag/pull/4263 fixes this bug. @GusevVictor @tanrak @oupala @zertrin could you confirm please? (with master branch)

**Comment by tanrak** [comment]
After a long time i have installed wallabag again. In version 2.4.1 the print support works as expected. I think this issue can be closed now.
