### ISSUE TITLE
Can't Fetch : blog.ippon.fr

### ISSUE THREAD

**Issue by xylle** [wallabag/wallabag#3238]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to http://gitter.im/wallabag/wallabag.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.30
* OS: Debian 8.7
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQlite

### Steps to reproduce/test case
fetch https://blog.ippon.fr/2017/05/09/vue-js-2-0-petit-tutoriel-volume-3/
In wallabag article is empty.
I test with f43.me, fetch are good.

**Comment by j0k3r** [comment]
It works fine on the upcoming 2.3 and wallabag.it (running on 2.2.3).

![image](https://user-images.githubusercontent.com/62333/27261453-934f5f88-5443-11e7-8e2d-29516f8155d3.png)

Could you upgrade to 2.2.3 and test again?

**Comment by xylle** [comment]
I am updating and I keep you updated

**Comment by xylle** [comment]
I did the update but wallabag did not work anymore. I launch the command
`make update`
i have the message : 
` PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The directory "/srv/appli/wallabag/var/cache/prod/jms_serializer" is not writable.' in /srv/appli/wallabag/vendor/jms/metadata/src/Metadata/Cache/FileCache.php:17\nStack trace:\n#0 /srv/appli/wallabag/var/cache/prod/appProdProjectContainer.php(7482): Metadata\\Cache\\FileCache->__construct('/srv/appli/wall...')\n#1 /srv/appli/wallabag/var/cache/prod/appProdProjectContainer.php(3878): appProdProjectContainer->getJmsSerializer_MetadataFactoryService()\n#2 /srv/appli/wallabag/var/cache/prod/classes.php(3534): appProdProjectContainer->getNelmioApiDoc_Parser_JmsMetadataParserService()\n#3 /srv/appli/wallabag/var/cache/prod/appProdProjectContainer.php(3736): Symfony\\Component\\DependencyInjection\\Container->get('nelmio_api_doc....')\n#4 /srv/appli/wallabag/var/cache/prod/classes.php(3534): appProdProjectContainer->getNelmioApiDoc_Extractor_ApiDocExtractorService()\n#5 /srv/appli/wallabag/var/cache/prod/appProdProjectContainer.php(3714): Symfony\\Component\\DependencyI in /srv/appli/wallabag/vendor/jms/metadata/src/Metadata/Cache/FileCache.php on line 17, referer: http://wallabag.univers.local/config
`

I delete the folder var/cache/prod/, after that wallabag work correctly, But I still have the problem, the article is not complete.

**Comment by j0k3r** [comment]
Could you remove the folder vendor and make a `make update` and try again?

**Comment by xylle** [comment]
done, but I still have the problem, the article is not complete.

**Comment by j0k3r** [comment]
I don't know then since it works fine for me on wallabag 2.2.3. :confused:

**Comment by xylle** [comment]
you have mysql ou sqlite ?

**Comment by j0k3r** [comment]
This won't affect the way content is fetched.
Maybe you can turn log debug on.

- edit app/config/config_prod.yml
- replace [in line 18](https://github.com/wallabag/wallabag/blob/master/app/config/config_prod.yml#L18) `error` to `debug`
- `rm -rf var/cache/*`
- empty file `var/log/prod.log`
- reload your wallabag and refetch the content
- paste the file `var/log/prod.log` here

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
