### ISSUE TITLE
New user account created without my knowledge

### ISSUE THREAD

**Issue by BMT01** [wallabag/wallabag#3239]
Hello -

I was running wallabag 2.2.3 (latest version). I had not checked the web interface in a few weeks, but I noticed that a new user account w/ an e-mail address ending in *.ru had been created. I had not received any notification.

I have since taken down my server, but I am a bit freaked out. How could this happen? My apache configuration forced HTTPS, and I was hosting my wallabag server on a DigitalOcean droplet with the proper precautions (ssh access only).

**Comment by tcitworld** [comment]
Hi,

User registration is open for everyone as default : you need to set the `fosuser_registration` parameter to `false` in the `app/config/parameters.yml` file. See https://doc.wallabag.org/en/admin/parameters.html#other-wallabag-options

You can delete the account inside the User Management Panel.
