### ISSUE TITLE
Files being visible on the server without password protection

### ISSUE THREAD

**Issue by n00b12345** [wallabag/wallabag#3246]
I'm using the Shared Hosting version of Wallabag. As expected, some folders (like /app, /data etc.) are hosted without password protection. Wallabag authentication only protects files and folders under the /wallabag/web folder. 

I've tried using .htaccess for the entire Wallabag folder but to be honest, it's a hasssle entering two levels of passwords to get in (I know I can create exceptions for IP addresses but they won't work when I access wallabag from a data connection).

Is there any way out? I don't want outsiders to view my /data or other folders.

**Comment by nicosomb** [comment]
Hello @n00b12345 

You need to configure a virtual host to protect your folders. See https://doc.wallabag.org/en/admin/installation/virtualhosts.html#configuration-on-apache

**Comment by n00b12345** [comment]
@nicosomb but of course! Thanks for the link. Totally appreate it.
