### ISSUE TITLE
Reload all articles

### ISSUE THREAD

**Issue by Arcadio-fr** [wallabag/wallabag#3247]
Hi,

### Improvement

Please provide an option on web interface or command for reload all articles. This is for reload all articles preview's images

### Environment

* wallabag version 2.2.3
* Official docker-composer for wallabag

**Comment by tcitworld** [comment]
Should be something like that: 
* `wallabag:article:reload`
* `wallabag:article:reload --article %articleID`
* `wallabag:article:reload %user%`

It should add a warning such as: "You're going to reload *n* articles, this might take some time. With a `-f` parameter to bypass this behaviour.
