### ISSUE TITLE
Unable to fetch these two articles

### ISSUE THREAD

**Issue by EgyptBeast** [wallabag/wallabag#3250]
Unable to fetch [this](http://www.thegeekstuff.com/2009/01/12-amazing-and-essential-linux-books-to-enrich-your-brain-and-library/) article and [this](https://www.thoughtco.com/most-common-french-phrases-1371064) too. Tested on https://f43.me/feed/test and worked.
I have tested it several times to make sure it's not a network issue.

* Version: 2.2.3
* Installed via git
* php version: 7
* OS: Lubuntu 16.04
* type of hosting (shared or dedicated): localhost
* Uses SQLite as it's database

**Comment by j0k3r** [comment]
A fix will be deployed to handle the first content (which return a bad HTTP status for a good looking page, which is weird).
The first one works fine on the upcoming 2.3 (but fail on the 2.2.3).

![image](https://user-images.githubusercontent.com/62333/28201730-a669cb92-6872-11e7-9bef-5eb185090351.png)

**Comment by EgyptBeast** [comment]
Good to hear that. I'll be waiting for the 2.3 update.
