### ISSUE TITLE
Possibility to save page directly from browser

### ISSUE THREAD

**Issue by iav** [wallabag/wallabag#3251]
Is it possible to write bookmarklet to use wallabag server as http://www.peeep.us service?
Main idea of peeep.us - it not fetch content itself, but gets content loaded into browser.
It means server stores site with all website-side user customisations, user access rights, ad blocks, custom css etc. The only way to save one-time generated content.
It's like a screenshot, but as webpage,  not picture.

**Comment by nicosomb** [comment]
Hello @iav 

wallabag provides a bookmarklet, it's available in the howto page of your instance. 
But, if I understand, you want a bookmarklet which sends all the article to the webserver (for example, to skip authentication on websites) ?

**Comment by iav** [comment]
Yes, bookmarklet that send not a link to get content, not initially pulled page, but page as it shown in browser, after all possible addons, userscripts, userstyles etc. done.
If peeep.us bookmarklet can do that - than it's possible "in general".

**Comment by Rurik19** [comment]
@iav  peeep.us bookmarklet just call  peeep.us/assets/send.js script, who call ww.peeep.us/upload.php endpoint, so I don't see much difference with wallabag :smile:

**Comment by iav** [comment]
ok. I save this with peeep http://www.peeep.us/b29d9781
You can see my userpic, my current themes read|unread status etc. Is it possible to save same with wallabag?

**Comment by Kdecherf** [comment]
This feature is now possible through the browser extension starting with version 1.14.0, see https://github.com/wallabag/wallabagger/releases/tag/v1.14.0

I'm closing this issue
