### ISSUE TITLE
Wallabag shows French interface when English is choosen

### ISSUE THREAD

**Issue by he7d3r** [wallabag/wallabag#3252]
On https://framabag.org, for the third time, the user interface is back in French, even if the language selected is English. When I open the config page, it shows English, however this is inconsistent with the language used in the interface. Clicking on ENREGISTER updates it correctly (for a few weeks at least):
![bug](https://user-images.githubusercontent.com/1754791/27584475-93ab1450-5b0e-11e7-8af2-0b6323e11a23.png)

**Comment by nicosomb** [comment]
Hello @he7d3r. 

Could you clean your Framabag cookies? 
I think that we already had this issue on wallabag.it and it was a cookie issue.

**Comment by tcitworld** [comment]
Also on Framabag the navbar on the login screen might mess up with the rest.

**Comment by he7d3r** [comment]
I cleaned the cookies. If it happens again, I'll add a note here.
(BTW: it happened again a few minutes ago, before cleaning the cookies)

**Comment by he7d3r** [comment]
Cleaning the cookies didn't help. =(

**Comment by he7d3r** [comment]
Cleaning the cookies didn't help. :-1:

**Comment by tcitworld** [comment]
@he7d3r Please check that your browser requests English as language. 
Firefox : Settings > Content > Languages
Chrome : Settings > Advanced > Languages
Check that english is on top of them.

**Comment by he7d3r** [comment]
Yes, it (Firefox) does.

**Comment by tuxmouraille** [comment]
Helo,
I have the same and opposite problem. I choose french for the default language and Wallabag is always in english.

**Comment by tuxmouraille** [comment]
Helo,
I have the same kind but opposite problem. I choose french for the default language and Wallabag is always in english.

**Comment by gnppn** [comment]
I have the same problem on wallabag.it (version 2.3) but I can't reproduce it when I try. Unlogging and relogging seems to fix it for me.

**Comment by jpbaril** [comment]
Same here. Interface is constantly back to English even if French is set in configs.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by he7d3r** [comment]
The problem still happens. I still have "Langue: English" in the page
https://framabag.org/config
but the interface is in French.

**Comment by j0k3r** [comment]
poke @tcitworld

**Comment by he7d3r** [comment]
@j0k3r : Could you reopen this issue?

**Comment by mrtpcet** [comment]
Same problem for me with Wallabag on Yunohost
