### ISSUE TITLE
Some non-standard image types are not cached

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3253]
### Issue details

I have some articles, which have different kind of src attribute of the img tag, which results in those images not being cached.
I would like to see them being cached locally to my wallabag.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version: 5
* OS: debian jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): pg

### Steps to reproduce/test case

Activate image caching on your wallabag.
Add one of the following articles and see that the image is not being cached: 

SVG not being cached:
https://www.heise.de/developer/artikel/Active-Design-Reviews-3175181.html

has parameters after file ending:
https://www.splitbrain.org/blog/2015-01/06-one_year_car_sharing

google-docs image link:
http://blog.reverberate.org/2014/09/what-every-computer-programmer-should.html

maybe because of png or the colon in the url:
http://250bpm.com/blog:82

PS: to easier see which images were not cached locally i have written a small Greasemonkey user script: https://github.com/Strubbl/userscripts/blob/master/wallabag_mark_non_local_images.user.js (click on Raw to install)

**Comment by Strubbl** [comment]
Another one with special chars in the img url:
https://legacy.thomas-leister.de/einfaches-echtzeit-monitoring-mit-netdata/

**Comment by Kdecherf** [comment]
Regarding SVG images, should we store and show images in their former format (svg files) or should we convert them to another image format before caching?

cc @wallabag/core

**Comment by j0k3r** [comment]
I think we can keep the source format.

**Comment by Orhideous** [comment]
This error suspends synchronization in the Android application. Just encountered this.
I think I can fix it soon.

**Comment by j0k3r** [comment]
If someone can provide me an url which include an svg image so I can debug it.
All given links in that issue are fetching images correctly on 2.4

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by Strubbl** [comment]
Closing is okay. I cannot reproduce the issue with the 4 articles in the original post.
