### ISSUE TITLE
Affordance.info don't fetch

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#3259]
### Issue details

Hello ! Little problem with this link : http://affordance.typepad.com//mon_weblog/2017/07/la-cour-des-cons.html it's don't fetch. But, with f43, it's work.

### Environment

Framabag.org

### Steps to reproduce/test case
try to add in wallabag with bookmarklet.

**Comment by j0k3r** [comment]
Yeah we know :confused: https://github.com/wallabag/wallabag/issues/1399
