### ISSUE TITLE
The grant_type "client_credentials" doesn't associate a user to the access_token

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#3262]
Since https://github.com/wallabag/wallabag/pull/3227 we've added the `client_credentials` grant type. Which means, apps don't need to ask user its login / password to be able to be logged in the user.

BUT that grant type should only be used when the app want to update sth about it.
See https://aaronparecki.com/oauth-2-simplified/#client-credentials

> In some cases, applications may need an access token to act on behalf of themselves rather than a user.

Problem is when user logged in using client_credentials grant type, the generated `access_token` isn't associated to the user so the client won't be able to retrieve sth related to the user (since the client_credentials should only allow the app to call the api without reguesting sth related to the user).

Since one client_id / client_secret is associated to only one user (in our case), we can try to find a way to associate a token generated by client_credentials to its associated user.

What do you think @di72nn @jlnostr @Simounet?

If we don't agree about that and if the solution is too long to build, we'll have to revert that PR before release the 2.3.0.

**Comment by di72nn** [comment]
I think it should be reverted and eventually be implemented along with other changes in #3068.

**Comment by jlnostr** [comment]
I agree with @di72nn. It doesn't help if we publish a semi-finished implementation with the next release.
