### ISSUE TITLE
Cannot fetch article

### ISSUE THREAD

**Issue by ssemigr** [wallabag/wallabag#3265]
### Issue details

This [article](http://www.ecosophia.net/july-2017-stormwatch-climate-change/) isn't fetched, but works on https://f43.me/feed/test.
The other articles from that site also work in https://f43.me/feed/test but not in wallabag.

### Environment

* type of hosting (shared or dedicated): wallabag.it

**Comment by j0k3r** [comment]
It works fine on the 2.3 branch so it'll be ok for the next update.
![image](https://user-images.githubusercontent.com/62333/28200996-4be57b06-686f-11e7-8c1e-d1eee662a0f4.png)
