### ISSUE TITLE
Article export API endpoint fails to return HTML

### ISSUE THREAD

**Issue by di72nn** [wallabag/wallabag#3268]
### Issue details

`/api/entries/{entry}/export.html` responds with `HTTP 500`.
Works fine with other (pdf, txt, etc.) formats.

Server log message:
```
request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The format "html" is not yet supported." at /usr/share/webapps/wallabag/src/Wallabag/CoreBundle/Helper/EntriesExport.php line 89 {"exception":"[object] (InvalidArgumentException(code: 0): The format \"html\" is not yet supported. at /usr/share/webapps/wallabag/src/Wallabag/CoreBundle/Helper/EntriesExport.php:89)"} []
```

Tested with 2.2.3 and with the 2.3 branch.

Mentioned here: wallabag/android-app#587.

**Comment by j0k3r** [comment]
We never implemented the HTML export from the beginning. The error is normal to me.

Only supported export are: epub|mobi|pdf|json|xml|txt|csv

**Comment by j0k3r** [comment]
You can follow https://github.com/wallabag/wallabag/issues/3272 to now when the html export will be available.
