### ISSUE TITLE
Resolved : Blank page on login

### ISSUE THREAD

**Issue by siSSSou** [wallabag/wallabag#3269]
### Issue details

Response code is 200, but login page is empty (blank page)
This problem occurs after debian jessie to stretch upgrade.
Every other apps on this server are OK with php7.0, nginx and mariadb, but not wallabag.

access.log 
`192.168.0.254 - - [08/Jul/2017:22:13:30 +0200] "GET /api/entries/exists.json?url=https://wallabag.roger1.fr/login HTTP/2.0" 200 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"`

error.log
`2017/07/08 22:13:33 [error] 15441#15441: *24 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'wallabaguser'@'127.0.0.1' (using password: YES) in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', 'wallabaguser', '^{_6rK8]PaPp_Ug...', Array)
#1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(44): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'wallabaguser', '^{_6rK8]PaPp_Ug...', Array)
#2 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'wallabaguser', '^{_6rK8]PaPp_Ug...', Array)
#3 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect()
#4 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersis", client: 192.168.0.254, server: wallabag.roger1.fr, request: "GET /login HTTP/2.0", host: "wallabag.roger1.fr"
`
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 2.2.3
* php version: 7.0
* OS: debian stretch
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Access wallabag to login

**Comment by siSSSou** [comment]
I enabled gzip compression in nginx.conf : I had to remove json compression and everything works now.

**Comment by tcitworld** [comment]
Well, the issue was that PHP couldn't connect to your MySQL server. I removed sensitive values from your logs.

**Comment by siSSSou** [comment]
OK thanks !
