### ISSUE TITLE
Add possibility to sort articles by oldest first

### ISSUE THREAD

**Issue by roukydesbois** [wallabag/wallabag#3274]
It would be nice to have the possibility to sort the articles and put the oldest first: in my case, I like to read the articles in the order I added them in wallabag.

**Comment by nicosomb** [comment]
Hello @roukydesbois !

Is your issue a duplicate of #2178?

**Comment by roukydesbois** [comment]
Yes it is! Thanks for pointing this out! I'll vote for this one then :)

11 juillet 2017 09:21 "Nicolas Lœuillet"  a écrit:
	Hello @roukydesbois (https://github.com/roukydesbois) ! 

	Is your issue a duplicate of #2178 (https://github.com/wallabag/wallabag/issues/2178)?
