### ISSUE TITLE
Enable HTTPS in dockerized Wallabag

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/wallabag#3275]
### Issue details
How can I enable HTTPS on Docker installation on Wallabag? Didn't find any decent documentation on that. I see that Docker container uses nginx for Wallabag. Should I enable HTTPS in nginx config inside container?

### Environment

* wallabag version that exhibits the issue: 2.2.2
* How did you install wallabag: Docker
* Last wallabag version that did not exhibit the issue: None
* php version: 7.0.16
* OS: AWS AMI Linux 2017.03
* type of hosting (shared or dedicated): AWS EC2 T2 Micro
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Postgre 9.6.2

### Steps to reproduce/test case

Trying to enable HTTPS on Docker Wallabag

**Comment by Suncatcher** [comment]
Wow!!! Almost a month and no answers. Nobody can say how to set up a HTTPS?

**Comment by Suncatcher** [comment]
Is it Docker-specific setting or the way is the same for all versions?

**Comment by j0k3r** [comment]
I think Google will be your best friend for that case.
Few links:
- https://github.com/docker-library/wordpress/issues/46#issuecomment-311275059
- https://tech.acseo.co/sites-https-docker-nginx-lets-encrypt/
- https://github.com/MarvAmBass/docker-nginx-ssl-secure

**Comment by Suncatcher** [comment]
The first link is about Apache, and the latter is about securing separate nginx Docker container. In our case nginx is included in wallabag image. Is it?

**Comment by Suncatcher** [comment]
I see [here on Dockerhub](https://hub.docker.com/r/wallabag/wallabag/) we have SSL settings sample for nginx:

    server {
            listen 443;
            server_name wallabag.foo.bar;
    
        ssl on;
            ssl_certificate /etc/letsencrypt/live/wallabag.foo.bar/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/wallabag.foo.bar/privkey.pem;
    
        location / {
            proxy_pass http://wallabag;
            proxy_set_header X-Forwarded-Host $server_name;
                    proxy_set_header X-Forwarded-Proto https;
                    proxy_set_header X-Forwarded-For $remote_addr;
        }
    
    }

Where should we put it? Into Docker-file? Into docker-compose? Somewhere inside wallabag container (in running state or in stopped)?

HTTPS thing should be somehow highlighted in documentation.

**Comment by j0k3r** [comment]
This should goes to the docker-composer of wallabag/docker.
In fact, I'll move that issue in the correct repo.

**Comment by j0k3r** [comment]
This issue was moved to wallabag/docker#77
