### ISSUE TITLE
Select by Tag, export to PDF: File name and first headline is "Tag_entries articles"

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3276]
### Issue details

If you export articles to PDF, the first headline on first page is called "Tag_entries articles". Also the name of the pdf file to be downloaded is very generic.
It would be nice if it would contain the tag label, which i selected before hitting export button.

A suggestion might be:

"Articles with tag $tag" so with a tag=linux it would be "Articles with tag linux"

I also suggest to change the file name to "$tag_articles.pdf" instead of "Tag_entries articles.pdf"

### Environment

* wallabag version (or git revision) that exhibits the issue:2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Go to tags listing, select a tag with at least one article, hit export->pdf and see the first headline on page 1 of the pdf.

**Comment by Kdecherf** [comment]
This issue has been fixed by #3826 

Here is the filename of the pdf export for the tag `calibre:hello`: `Tag calibrehello articles.pdf`

The first page has been replaced too with a summary page for each exported article.
