### ISSUE TITLE
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "MainBundle" from namespace "MainBundle". Did you forget a "use" statement for another namespace? in /opt/lampp/htdocs/Mrigl/app/AppKernel.php:19

### ISSUE THREAD

**Issue by Abdelmonem-BEN-NACEUR** [wallabag/wallabag#3279]
hi everybody , i had this error after starting new projet in symfony 2.8 and after the following command : php app/console doctrine:generate:entity
![image](https://user-images.githubusercontent.com/30234640/28268939-19a17baa-6af8-11e7-88ac-361cc0b7fef1.png)

**Comment by tcitworld** [comment]
This is not the repo you're looking for.
