### ISSUE TITLE
Internal 500 error when importing an article

### ISSUE THREAD

**Issue by atbd** [wallabag/wallabag#3282]
### Issue details
I tried to import this [article](https://functionallyparanoid.com/2017/06/30/boot-all-the-things/) and get an internal 500 error.

` SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x99\x82</...' for column 'content' at row 1`

### Environment

* wallabag version (or git revision) that exhibits the issue: last docker container on the hub
* How did you install wallabag: docker-compose
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS: linux
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case
Try to add this [article](https://functionallyparanoid.com/2017/06/30/boot-all-the-things/) to your wallabag.

**Comment by tcitworld** [comment]
The issue is most probably related to the smiley face in the beginning of the article.
Does your database uses UTF-8 mb4, and is that set inside `app/config/parameters.yml` (see key `database_charset`) ?

**Comment by atbd** [comment]
I checked, my docker-compose has:
`command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]` and wallabag configuration contains `database_charset=utf8`

**Comment by j0k3r** [comment]
wallabag configuration must then be `database_charset=utf8mb4`

**Comment by atbd** [comment]
I tried with utf8 on both sides and keep getting error. Do you think i'll have better luck with utf8mb4 ?

**Comment by j0k3r** [comment]
Yes, this is what we are telling you since few comments.
That error is related to the fact emoji aren't compatible with utf8 but utf8mb4.

Please use utf8mb4.

**Comment by atbd** [comment]
I had another issue generated by docker.
Thanks, all works now

**Comment by suurmauri** [comment]
@atbd Could you elaborate on what actually was your issue and what solved it? I get the same error importing all my articles into a new wallabag instance set up with docker-compose and mariadb
