### ISSUE TITLE
Actual assets get deleted on assets:install

### ISSUE THREAD

**Issue by janLo** [wallabag/wallabag#3285]
### Issue details

If I try to test the 2.3 branch of wallabag, the `php bin/console assets:install --env=prod --symlink --relative` Step deletes everything below `web/bundles/wallabagcore` which leaves the app in a pretty unuseable state.

### Environment

* wallabag version (or git revision) that exhibits the issue: 
  * revision f0cd12f
* How did you install wallabag? Via `git clone` or by downloading the package?
  * Git clone in a docker container. See https://github.com/janLo/wallabag-docker/tree/testing
* Last wallabag version that did not exhibit the issue (if applicable):
  * 2.2.x
* php version:
  * 7.x  (what is in alpine)
* OS:
  * alpine Linux
* type of hosting (shared or dedicated):
  * Container behind reverse proxy
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
  * Postgres

### Steps to reproduce/test case
Build the container from the link above.

**Comment by j0k3r** [comment]
You should use `yarn run build:dev` or  `yarn run build:prod` to generate asset files (and run `yarn install` before).
Also, be sure to have `yarn` installed.

**Comment by janLo** [comment]
If you test it with the Dockerfile from the repo above you have to revert https://github.com/janLo/wallabag-docker/commit/f0cd12f5445cd0d6ac975be8881c0aca045c0527 because it basically chechs the files out again the assets:install deleted.

**Comment by janLo** [comment]
@j0k3r How can I do this without installing yarn in the container? It would bloat the image.

The files are in your repo, they just get deleted by `assets:install`.

**Comment by tcitworld** [comment]
IIRC, `assets:install` shouldn't be called at all.

**Comment by janLo** [comment]
Its called by `SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist`:
https://github.com/wallabag/docker/blob/master/Dockerfile#L57
https://github.com/wallabag/docker/blob/master/root/etc/ansible/entrypoint.yml#L134
