### ISSUE TITLE
[documentation] installation with git clone --depth 1

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#3289]
For all,  who is not developer,  installation with **git clone --depth 1** takes 2.5 times less download :smile:

**Comment by j0k3r** [comment]
Why not submitting a PR to the doc repo instead?

**Comment by tcitworld** [comment]
Well, most of the times installations are made on servers which have large bandwidth, so it's not that bothering.
However, the change should be applied to the makefile too.

**Comment by Rurik19** [comment]
I close this issue because I found that build process has wrong results with --depth 1
