### ISSUE TITLE
FreeBeacon rendering issue

### ISSUE THREAD

**Issue by Suncatcher** [wallabag/wallabag#3300]
### Issue details

FreeBeacon articles are rendered incorrectly. E.g., [this one](http://freebeacon.com/national-security/interview-cia-director-pompeo-cia-changing-president-trump/).

![image](https://user-images.githubusercontent.com/6388034/28755004-26539a88-755a-11e7-9e0b-48d9464b2b18.png)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag: Docker
* Last wallabag version that did not exhibit the issue (if applicable): dunno
* php version: dunno
* OS: Amazon Linux 2017.03
* type of hosting (shared or dedicated): AWS EC2 T2 Micro
* which storage system you choose at install: PostgreSQL

### Steps to reproduce/test case

Adding article to bag.

**Comment by j0k3r** [comment]
It works fine on app.wallabag.it which is using 2.2.3.

![image](https://user-images.githubusercontent.com/62333/28766755-3e681ba4-75d1-11e7-8ed2-1731bd17ef76.png)

Maybe try to upgrade your wallabag first?

**Comment by Suncatcher** [comment]
Yeah, will do. Didn't know the new version was released.

**Comment by j0k3r** [comment]
2 months agao already!

**Comment by Suncatcher** [comment]
However, on your screen the front image is duplicated :)

**Comment by Suncatcher** [comment]
Also, the update procedure for Docker [is still pending](https://github.com/wallabag/docker/issues/60). Can we somehow automate this procedure?

**Comment by j0k3r** [comment]
> However, on your screen the front image is duplicated :)

Yes, it's an old issue and a lot of discussion have already been done. We display the preview image on top of the content but sometimes the content itself might have that same image (well, same visual but not same url) so it's kind of duplicated.

> Can we somehow automate this procedure?

I'm not a Docker guru so I can't arg about how we can process in that case :confused:

**Comment by j0k3r** [comment]
It looks ok now
