### ISSUE TITLE
"No title found" on labs.mwrinfosecurity.com

### ISSUE THREAD

**Issue by 2xyo** [wallabag/wallabag#3303]
### Issue details

"No title found" on https://labs.mwrinfosecurity.com/tools/wepwnise/ despite `<title>WePWNise</title>`.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? https://www.framabag.org 
* Last wallabag version that did not exhibit the issue (if applicable): ?
* php version: ?
* OS: ?
* type of hosting (shared or dedicated): ?
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): ?

### Steps to reproduce/test case
* Add https://labs.mwrinfosecurity.com/tools/wepwnise/  (or any blog post of this website)
* get the content of the blog post with "No title found"

**Comment by techexo** [comment]
Solved by https://github.com/fivefilters/ftr-site-config/pull/563. Issue can be closed.

**Comment by 2xyo** [comment]
Thanks @techexo :+1:
