### ISSUE TITLE
Removing a tag should redirect to the article page

### ISSUE THREAD

**Issue by shtrom** [wallabag/wallabag#3305]
### Issue details

When on an article's page, with a few tags
1. click on the bin icon next to a tag to delete it
2. get redirected to the unread articles page

Expected behaviour:
2. get redirected to the article's page, no longer showing the removed tag

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? OpenBSD port which I maintain myself at https://scm.narf.ssji.net/git/openbsd-ports/tree/www/wallabag
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 5.6.30
* OS: OpenBSD 6.1
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

See details above.

**Comment by j0k3r** [comment]
Maybe we can just redirect to the referer instead.

**Comment by shtrom** [comment]
Yeah, I think that would work. Though it would be nicer with an XHR to the API, but it's probably a bigger change.

**Comment by j0k3r** [comment]
Yeah it's planned to rewrite all those littles actions to ajax request instead.

**Comment by remicmacs** [comment]
I think it's fixed on my account on https://app.wallabag.it/ (version is 2.3.8-dev)

**Comment by nicosomb** [comment]
I confirm that. I close this issue.
