### ISSUE TITLE
Rendering issue on ntoskrnl.org

### ISSUE THREAD

**Issue by 2xyo** [wallabag/wallabag#3306]
### Issue details

The rendering of http://ntoskrnl.org start almost at the end of the (big) page. See screenshot below.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? https://www.framabag.org 
* Last wallabag version that did not exhibit the issue (if applicable): ?
* php version: ?
* OS: ?
* type of hosting (shared or dedicated): ?
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): ?

### Steps to reproduce/test case

* go to   http://ntoskrnl.org  
* bag it! 

![image](https://user-images.githubusercontent.com/31675/28827981-9a1aa7e2-76cf-11e7-8675-21b0b198dc8e.png)

**Comment by j0k3r** [comment]
Did you read the doc about that?
Have you tried to fix the problem on your side using siteconfig?
https://doc.wallabag.org/en/user/errors_during_fetching.html

**Comment by 2xyo** [comment]
Thanks @j0k3r, I have created the following PR  fivefilters/ftr-site-config#320

**Comment by j0k3r** [comment]
It was in the first line of the issue template, did you read it? :wink:
