### ISSUE TITLE
Wallabag can't retrieve contents for The Art of Manliness

### ISSUE THREAD

**Issue by albertaparicio** [wallabag/wallabag#3308]
### Issue details

Some of the articles on the website [The Art of Manliness](http://www.artofmanliness.com/) are not being fetched successfully.

[This article](http://www.artofmanliness.com/2016/10/04/meditations-wisdom-action/) is fetched fine
[This other article](http://www.artofmanliness.com/2017/08/02/embracing-grind-barbell-training-beyond/) is not.

I have tested the https://f43.me/feed/test tool, and it works with the External parser, but not with the Internal one.

I have tried to fetch a siteconfig from http://siteconfig.fivefilters.org/:

```
# Generated by FiveFilters.org's web-based selection tool
# Place this file inside your site_config/custom/ folder
# Source: http://siteconfig.fivefilters.org/grab.php?url=http%3A%2F%2Fwww.artofmanliness.com%2F2017%2F08%2F02%2Fembracing-grind-barbell-training-beyond%2F

body: //article[contains(concat(' ',normalize-space(@class),' '),' single-post ')]
test_url: http://www.artofmanliness.com/2017/08/02/embracing-grind-barbell-training-beyond/
```

### Environment

I am using the version hosted on [framabag.org](https://www.framabag.org/about)

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? 
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

1. Open [this article](http://www.artofmanliness.com/2017/08/02/embracing-grind-barbell-training-beyond/)
2. Click the `+` button and paste the link

The same error occurs if the article is added with the bookmarklet, the Firefox Add-on or the Android app

Thank you for the help

**Comment by j0k3r** [comment]
It'll be fixed in the next release!
Thanks
