### ISSUE TITLE
I can't access my tags list anymore

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#3313]
### Issue details

I have a lot of tags (>700, words and emojis) and I just discovered I can't access the tags list anymore. It loads for ever then nothing, just a blank page. When I had fewer tags, it was ok, I think the number is a factor. Also, I'm on a Raspberry Pi, so it's probably related too.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.30
* OS: Raspbian (Debian Jessie)
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Add a lot of tags?

**Comment by j0k3r** [comment]
Thanks to @nclsHart it should be fixed in the upcoming release!
Thanks for reporting the issue.
