### ISSUE TITLE
Failed to fetch an article

### ISSUE THREAD

**Issue by VojtechFried** [wallabag/wallabag#3320]
Wallabag fialed to fetch this article: https://www.alt-m.org/2017/08/08/a-monetary-policy-primer-part-11-last-resort-lending2/
I read the troubleshooter and it works at https://f43.me/feed/test

**Comment by j0k3r** [comment]
And did you try to create a site config to fix it?

**Comment by VojtechFried** [comment]
No. The troubleshooter said that since it works at https://f43.me/feed/test it is an internal error, that should be reported. So far I have no idea how it works and what siteconfig is, I just blindly did what the troubleshooter says.

**Comment by j0k3r** [comment]
Which version of wallabag are you using?
In the latest, it works fine:

![image](https://user-images.githubusercontent.com/62333/29354540-2931feea-826e-11e7-8a14-bf54023c7c05.png)

**Comment by VojtechFried** [comment]
Well, it works now. I use https://www.framabag.org. I tried both firefox addon "wallabagger" and Android Wallabag app then to push it there and it did not work, now both work.
Thanks!

**Comment by j0k3r** [comment]
Ok great!
