### ISSUE TITLE
can't fetch abcdolomiti.com

### ISSUE THREAD

**Issue by lucamp** [wallabag/wallabag#3325]
### Issue details

fetching http://www.abcdolomiti.com/escursione/popera-3046-m-via-normale-salita/ does not work.
with https://f43.me/feed/test it works

### Environment

using online service framabag.org with wallabag 2.2.2, so please try it with 2.2.3

Thanks
Luca

**Comment by j0k3r** [comment]
It works on 2.2.3:
![image](https://user-images.githubusercontent.com/62333/29474077-6f20f792-845a-11e7-9d02-baa71853342c.png)

You need to wait for the framabag update.
