### ISSUE TITLE
Android developer blog article display problem

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3329]
Sorry for the bad quality issue, but I have only my mobile with me. I am going to improve this issue description as soon as I have a real keyboard and a browser at hand

:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to http://gitter.im/wallabag/wallabag.

Add https://android-developers.googleblog.com/2017/08/introducing-android-8-oreo.html and see that content might be fetched (due to reading time display), but article has only an image displayed and the text is missing. 

### Environment

* wallabag version (or git revision) that exhibits the issue:
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by nclsHart** [comment]
Reproduced in the latest version.

The content is properly fetched. The issue come from a `<noscript>` tag wrapping all the content of the article. 

This explains why the reading time seems to be correct while no content is displayed.

**Comment by Strubbl** [comment]
@nclsHart thanks for analysing and fixing the issue
