### ISSUE TITLE
Pas de chargement pour 2 sites sur wallabag.it

### ISSUE THREAD

**Issue by tiubuk** [wallabag/wallabag#3334]
Bonjour, j'utilise les services de wallabag.it, très bien au demeurant, MAIS :
- pour le site [Actualitté](http://www.actualitte.com/) ne sont affichés dans wallabag.it que le titre et l'en-être, pas le corps du texte ;
- idem pour le site [Ecran Large](http://www.ecranlarge.com).

Cordialement

**Comment by j0k3r** [comment]
Ça sera dispo dans la prochaine release.
