### ISSUE TITLE
Fetch content error on broadly.vice.com

### ISSUE THREAD

**Issue by Zeriuno** [wallabag/wallabag#3341]
### Issue details

Fetching content does not work on https://broadly.vice.com/en_us/article/kzewww/study-straight-women-are-having-fewer-orgasms-because-of-their-useless-partners 
Works on http://f43.me/feed/test

### Environment

* wallabag version (or git revision) that exhibits the issue: wallabag.it through the bookmarklet

**Comment by j0k3r** [comment]
And this one also work using the 2.3 branch.
Interesting article, btw.

![image](https://user-images.githubusercontent.com/62333/30203397-4a436940-9482-11e7-8ff2-34cd55bd5fca.png)
