### ISSUE TITLE
Error fetching content from washingtonpost.com

### ISSUE THREAD

**Issue by Zeriuno** [wallabag/wallabag#3342]
### Issue details

Tried to retrieve https://www.washingtonpost.com/graphics/2017/world/national-security/obama-putin-election-hacking/

Title and top picture are fetched, nothing else.
Works on https://f43.me/feed/test

### Environment

* wallabag version (or git revision) that exhibits the issue: wallabag.it account through the bookmarklet (Firefox)

**Comment by j0k3r** [comment]
It works great on the 2.3 branch, will be fixed when it'll be released.

_I've reduced the size of the page for the screenshot_

![image](https://user-images.githubusercontent.com/62333/30203353-20159f6c-9482-11e7-961b-6695760ee42d.png)
