### ISSUE TITLE
fetching url failed

### ISSUE THREAD

**Issue by nrobinaubertin** [wallabag/wallabag#3344]
Hi !
First, thanks for making wallabag ! 

I have an issue fetching the following url: https://guide.boum.org/tomes/2_en_ligne/unepage/
https://f43.me/feed/test is correctly fetching it's content.

Following https://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that, I'm opening this issue.

I use wallabag 2.2.3 in a docker container. You can get the dockerfile here: https://github.com/nrobinaubertin/dockerfiles/tree/master/wallabag  
PHP version: 7.1.5-r0 (https://pkgs.alpinelinux.org/package/v3.6/community/x86_64/php7)
OS: archlinux with the kernel 4.11.6-3-ARCH
Hosting: dedicated
Storage system: SQLite

**Comment by j0k3r** [comment]
Thanks for reporting.
That content is well fetched using the 2.3 branch. It'll be fixed in the next release.

![image](https://user-images.githubusercontent.com/62333/30223678-2b141f34-94cc-11e7-86e0-c4ae111bdf35.png)
