### ISSUE TITLE
HSTS Error - https://v2.wallabag.org

### ISSUE THREAD

**Issue by 4oo4** [wallabag/wallabag#3353]
Not really an issue with Wallabag itself, but just noticed today that `https://v2.wallabag.org` is totally inaccessible to me because of the below HSTS error and certificate name mismatch. Using Chromium 60.0.3112.113 Developer Build for Ubuntu 16.04.

![image](https://user-images.githubusercontent.com/15698835/30523781-161c04ec-9bad-11e7-8cc9-d1f42b49c0a4.png)

Digging in a bit more with SSLLabs, it looks like the certificate being used is for dev.framakey.org?
![selection_006](https://user-images.githubusercontent.com/15698835/30523839-918a4d22-9bae-11e7-9b24-c34fa173a03d.png)

**Comment by tcitworld** [comment]
Sorry, v2.wallabag.org is discontinued and I didn't found the time to alert the remaining users of the shutdown (and even shut it down properly).
In the meantime, you can [clear HSTS](https://www.thesslstore.com/blog/clear-hsts-settings-chrome-firefox/) and access it over **plain http**, to export your data and use https://wallabag.it or https://framabag.org.

**Comment by 4oo4** [comment]
@tcitworld Thanks. I actually didn't have any data there since I run self-hosted Wallabag, but figured it was some kind of migration like that.
