### ISSUE TITLE
Wallabag can't parse some articles from http://blog.trendmicro.com/

### ISSUE THREAD

**Issue by fhightower** [wallabag/wallabag#3359]
### Issue details

Wallabag is unable to read some blog posts from Trend Micro (for example: http://blog.trendmicro.com/trendlabs-security-intelligence/apache-struts-vulnerabilities-run-rampant/). I've tested this blog out here: https://f43.me/feed/test and it is able to parse the post, so I believe there is something inside Wallabag that is breaking it.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.0
* How did you install wallabag? Via `git clone` or by downloading the package? via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 7.0.15

### Steps to reproduce/test case

Submit the following blog post (http://blog.trendmicro.com/trendlabs-security-intelligence/apache-struts-vulnerabilities-run-rampant/) to https://f43.me/feed/test to verify that it is properly read. Next, submit this URL to a wallabag instance and note that it is unable to read the content from the blog post.

**Comment by mritzmann** [comment]
Your link is working for me.

- Wallabag Version: `2.2.3`
- Installed with: Cloudron

**Comment by j0k3r** [comment]
I noticed that you use an old version of wallabag.
Could you update your version and check the site again?

**Comment by fhightower** [comment]
Ok, I'll update and give it another shot. Thanks!

**Comment by fhightower** [comment]
This is working properly with the most recent version of wallabag. Thanks for the help!
