### ISSUE TITLE
Doesn't work in Google Translate

### ISSUE THREAD

**Issue by eemantsal** [wallabag/wallabag#3363]
### Issue details
Doesn't save anything when trying to save a translated page in Google Translate

### Environment
* wallabag version (or git revision) that exhibits the issue:
2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package?
I didn't install it, I'm using framabag.org

### Steps to reproduce/test case
Go to translate.google.com, translate any webpage and once you get the translated page save it to Wallabag with the Firefox extension. When you log in to your Wallabag account, the article is empty, not a single letter has been saved.

**Comment by j0k3r** [comment]
Is it still possible translate a webpage from translate.google.com?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by Agrotsa** [comment]
I'm not the person who posted this issue so I think I cant reopen it, but I have just posted an almost exact issue in the Android app's repository and now I've seen this other repo and  seen this issue. But I have the very same problem: I'd like to save articles in several foreign languages but translated by Google, which if far from perfect, it's still way better to understand those articles a 90% than nothing or poorly.

@j0k3r 
Yes, it is possible. You can paste a URL in GTranslates web site or you can use one of the various breowsers' addons and just right clik when you are on a page in, let's say, russian, to open a new tab with the page trnaslated in Google Translate, or just select some text, and right click to get a pop up with the translation of the selected text.
If you are still curious, here is one I use in chrome, but there are many others:
https://github.com/sienori/simple-translate

It's very useful and handy, but if you try to save that article in you Wallabag account, you will get nothing saved at all, just a couple of lines from Google, but nothing from the article you wanted. :-(

**Comment by j0k3r** [comment]
Could you then share me a full url for a Google translated webpage? So I can see what we can do?

**Comment by Agrotsa** [comment]
Sure. For example here's the URL for the french translation of one Github guide:
https://translate.google.com/translate?hl=fr&sl=auto&tl=fr&u=https%3A%2F%2Fguides.github.com%2Factivities%2Fhello-world%2F&sandbox=1

If you click on the Wallabag's clipper button in your browser you get a new article in your WB account with the link to the trasnlated page, bit not the page itself; a bookmark, not a clip. One can always just copy and paste into a LibreOffice document, of course, but then, the commodity and handyness of a web clipper like WB disapears. I'd be a very cool thing if you could make WB able to capture Gtranslated pages. So, many thanks for taking some time to see if you can do something.
