### ISSUE TITLE
Unable to parse website

### ISSUE THREAD

**Issue by jb911** [wallabag/wallabag#3364]
### Issue details

Unable to parse the website http://jumeauxandco.com/voyage/road-trip-avec-des-jumeaux-a-lautre-bout-du-monde/

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? installation from package
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install : MariaDB

**Comment by techexo** [comment]
No problem fetching this page with wallabag 2.3.3. @jb911 could you check with an updated version of wallabag, so that this issue can be closed?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
