### ISSUE TITLE
Can't retrieve mollyrocket.com 

### ISSUE THREAD

**Issue by enginmanap** [wallabag/wallabag#3365]
When I try to add the page below, wallabag fails

https://mollyrocket.com/casey/stream_0019.html

f43.me parses without issues.

* wallabag 2.2.3
* installed via git clone
* php 7.0.22-0ubuntu0.17.04.1
* Ubuntu 17.04
* x86_64 VPS
* mysql

**Comment by techexo** [comment]
The URL redirect to `caseymuratori.com`. However, pages from both `mollyrocket.com` and the other one are completely unreadable for a parser, as the HTML semantics is absolutely not respected. There is actually no `<p>...</p>` to separate paragraphs and spaces between them are done by `<div class='...'></div>` elements... 
I think it is hard to make such a bad website from a semantic point-of-view.

I am not sure what we can do for wallabag to fetch it nicely.

**Comment by j0k3r** [comment]
The content is well retrieved from POV. Closing.
