### ISSUE TITLE
CORS doesn't work?

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#3367]
Maybe I am wrong, but it seems that CORS in wallabag doesn't work?
OPTIONS preflight request returns an error 400. It happends because of default settings of the **nelmioCors** bundle in config.yml: 
`allow_headers: ['X-Custom-Auth']`
but we need the `Authorization` header to be allowed. 

When I changed that setting to `allow_headers: ['Authorization']` CORS request begin working.

Does somebody need 'X-Custom-Auth' header?
Should I make a PR?

**Comment by j0k3r** [comment]
Sadly I think it's just the default configuration for NelmioCorsBundle, see https://github.com/nelmio/NelmioCorsBundle#configuration

So maybe you can create a PR with your change.

**Comment by Rurik19** [comment]
Shure, #3368

**Comment by Rurik19** [comment]
Why not? :smile:
