### ISSUE TITLE
PDF export error, unable to get size of image

### ISSUE THREAD

**Issue by mjjzf** [wallabag/wallabag#3369]
### Issue details

Fetching from lederne.dk works.
I have two page examples exhibiting the same issue:
[https://www.lederne.dk/ledelse-i-dag/ny-viden/2017/ledelse-i-dag-juni-2017/magt-korrumperer?gbi=84030421-48f8da5b-a62bd2d6](https://www.lederne.dk/ledelse-i-dag/ny-viden/2017/ledelse-i-dag-juni-2017/magt-korrumperer?gbi=84030421-48f8da5b-a62bd2d6)
and
[https://www.lederne.dk/ledelse-i-dag/ny-viden/2017/ledelse-i-dag-juni-2017/Robusthed?gbi=84030421-48f8da5b-a62bd2d6](https://www.lederne.dk/ledelse-i-dag/ny-viden/2017/ledelse-i-dag-juni-2017/Robusthed?gbi=84030421-48f8da5b-a62bd2d6)

When I try to export to PDF, it fails with an error message from TCPDF:

> TCPDF ERROR: [Image] Unable to get the size of the image: https://www.lederne.dk/-/media/lederne/logo_hvid_vector.ashx?la=da&hash=6A6171DDF661C11BD9F6D0772BB6DBB01539D09D

They both point to the same logo graphic.

### Environment

* wallabag version (or git revision) that exhibits the issue: Version: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? - Git zip download, uploaded to shared hosting.
* Last wallabag version that did not exhibit the issue (if applicable): Unknown.
* php version: 5.6
* OS: Apache on Debian
* type of hosting (shared or dedicated): Shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case
* Saving the pages referenced above to Wallabag
* Opening Wallabag to the page where the page is saved; page appears correctly saved
* Pressing Download in the sidebar, choosing PDF as output format
* Error message appears: 

> TCPDF ERROR: [Image] Unable to get the size of the image: https://www.lederne.dk/-/media/lederne/logo_hvid_vector.ashx?la=da&hash=6A6171DDF661C11BD9F6D0772BB6DBB01539D09D

**Comment by tcitworld** [comment]
Unfortunately that's an issue with tcpdf, I'm not sure we can do much for now.

**Comment by j0k3r** [comment]
Duplicates https://github.com/wallabag/wallabag/issues/2843
