### ISSUE TITLE
Logo missing

### ISSUE THREAD

**Issue by morags** [wallabag/wallabag#3374]
### Issue details

`logo-square.png` is missing from upper left corner of web app.

Log:
`[2017-10-08 21:08:18] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /bundles/wallabagcore/themes/_global/img/logo-square.png" (from "http://127.0.0.1:8000/")" at D:\Wallabag\var\cache\prod\classes.php line 3941 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /bundles/wallabagcore/themes/_global/img/logo-square.png\" (from \"http://127.0.0.1:8000/\") at D:\\Wallabag\\var\\cache\\prod\\classes.php:3941, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at D:\\Wallabag\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:880)"} []`

### Environment

* Wallabag 2.2.3, cloned from repo
* PHP 7.1.10 ZTS MSVC14 x64
* Windows 10 Pro x64
* All system settings set to their defaults

### Steps to reproduce

1. Install Wallabag on top of PHP as per docs
2. Create/activate user and log in to web app at `http://127.0.0.1:8000/`
3. Logo missing from upper left corner

**Comment by Kdecherf** [comment]
This issue should be fixed in 2.3 via #3383 
Can you test it?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
