### ISSUE TITLE
[2.3] There is no new grant type 'client_credentials' in manually created clients

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#3380]
Hi all! An client created manualy does'n have such grant type: 
![image](https://user-images.githubusercontent.com/1955806/31486265-542134c2-af50-11e7-8110-116c06b9bf18.png)
and when I call /token api i got
```
{
"error": "unauthorized_client",
"error_description": "The grant type is unauthorized for this client_id"
}
```

**Comment by nicosomb** [comment]
@Rurik19 @j0k3r is that already a bug? 

Do we really need to fix it?

**Comment by Rurik19** [comment]
Hi! If I remember correct (that was 6 years ago), this is not a bug, I just considered about not to store user credentials, using only clientId and clientSecret to get token, as application workflow of OAuth2 suggest ( if I understand that correct). There's no need to fix it at all.

**Comment by nicosomb** [comment]
Ok. Thank you for your reply.
