### ISSUE TITLE
About tags: remove unused, massive changes and sync problem

### ISSUE THREAD

**Issue by ghost** [wallabag/wallabag#3386]
Bonjour,

### Issue details

1 : j'appose un tag erroné sur un article ("multimedia" au lieu de "multimédia" (avec accent)) depuis l'appli Android ;
2 : je met le tag correct ("multimédia") sur un autre article. Après synchro, que ce soit sur le web ou sur l'appli, le tag "multimedia" remplace "multimédia" ! J'ai aussi le problème avec des majuscules ("BD" et "bd"). Mais ça ne concerne pas tous les tags ("vie privée", malgré l'accent, est ok par ex.).

J'ai le problème dans tous les sens, que ce soit sur le web ou l'appli :( En l'état, il ne semble pas possible de modifier les tags de manière globale...

### Environment

* wallabag.it web et via appli F-Droid

### Steps to reproduce/test case

Tagger plusieurs articles depuis l'appli puis modifier les tags et synchroniser. Je ne suis pas sûr de l'ordre des manips pour reproduire l'erreur !

Merci d'avance !

**Comment by docljn** [comment]
Hello the team. I am participating in CodeTriage, and noticed that this user has been deleted, and there are no comments on the issue since opening.  Is this still an open issue, or can it be closed? Thank you.

**Comment by bipox** [comment]
I'm using the hosted version on wallabag.it

I have this exact issue.

If I add for the first time a tag named "meme" all future tags will revert to the first version, even if written with different accents ("même", "mème" will revert to "meme")

I wrongly wrote "securité". Now even when I type correctly "sécurité" the tag reverts to the original mistake.
