### ISSUE TITLE
With PostgreSQL: PDOException: SQLSTATE[08006] [7] could not connect to server: No such file or directory

### ISSUE THREAD

**Issue by tYYGH** [wallabag/wallabag#3389]
### Issue details

On a fresh install of Wallabag, in the browser, I visit: https://yalis.fr/read/app.php/login
(actually, I am redirected there after typing https://yalis.fr/read/app.php)
⇓
I get:

```
oct. 24 21:17:09 seuil3 [32275]: 2017/10/24 21:17:09 [error] 32275#32275: *213 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] could not connect to server: No such file or directory
                                         Is the server running locally and accepting
                                         connections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"? in /usr/share/webapps/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
                                 Stack trace:
                                 #0 /usr/share/webapps/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('pgsql:dbname=re...', '**********', '**********', Array)
                                 #1 /usr/share/webapps/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('pgsql:dbname=re...', '**********', '**********', Array)
                                 #2 /usr/share/webapps/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, '**********', '**********', Array)
                                 #3 /usr/share/webapps/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): D" while reading response header from upstream, client: 192.168.1.99, server: , request: "GET /read/app.php/login HTTP/1.1", upstream: "fastcgi://unix:/run/shared_sockets/php-fpm:", host: "yalis.fr"
```

### Environment

* wallabag version (or git revision) that exhibits the issue: version 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? Archlinux package
* php version: 7.1.10
* OS: up-to-date Archlinux
* type of hosting (shared or dedicated): dedicated, self-hosted
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Nginx conf:

```
location /read {
  alias /usr/share/webapps/wallabag/web;
  try_files $uri /read/app.php$is_args$args;
}
location ~ ^/read/app\.php(?<path_info>/.*|$) {
  alias /usr/share/webapps/wallabag/web;
  #internal;
  fastcgi_pass unix:/run/shared_sockets/php-fpm;
  fastcgi_index index.php;
  fastcgi_send_timeout 60m;
  fastcgi_read_timeout 60m;
  include fastcgi.conf;
  fastcgi_param HTTPS           $proxy_https           if_not_empty;
  fastcgi_param REQUEST_SCHEME  $proxy_https           if_not_empty;
  fastcgi_param SERVER_PORT     $proxy_port            if_not_empty;
  fastcgi_param SCRIPT_FILENAME /usr/share/webapps/wallabag/web/app.php;
  fastcgi_param SCRIPT_NAME     /read/app.php;
  fastcgi_param REQUEST_URI     /read/app.php$path_info$is_args$query_string;
  fastcgi_param DOCUMENT_URI    /read/app.php$path_info;
  fastcgi_param DOCUMENT_ROOT   /usr/share/webapps/wallabag/web;
  fastcgi_param PATH_INFO       $path_info            if_not_empty;
}
location ~ ^/read.*\.php$ {
  return 404;
}
```

parameters.yml:
```
parameters:
    database_driver: pdo_pgsql
    database_host: /run/shared_sockets
    database_port: 5432
    database_name: readlater
    database_user: **********
    database_password: **********
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
…
```

I’m sure that the above file is read because the login and password, as well as the database name, appear in the error logs.

**Comment by tcitworld** [comment]
The issue is about php not being able to connect to Postgres on your unix socket. Did you try emptying (or set to null) `database_host` ?

**Comment by tYYGH** [comment]
I did. My first configuration was to have host and port set to null, and socket set to “/run/shared_sockets” (the port being the default one anyway); the result was the same. I changed when I realized that:
1. The socket parameter is not read by Wallabag’s PostgreSQL driver code;
2. PostgreSQL normal way of doing things is to pass the parameters as I do now.

For your information, the actual socket node is `/run/shared_sockets/.s.PGSQL.5432`; I tried using that full name (not the usual Pg way), but it did not improve anything.

Besides, the following is successful:

```
[root ~]# sudo -u http -g http psql -d readlater -h /run/shared_sockets -p 5432 -U ********** -W
Password for user **********: **********
psql (9.6.5)
Type “help” for help.

readlater=> \quit
```

**Comment by tcitworld** [comment]
Did you also try just leaving `database_host` and `database_port` empty (ref https://github.com/symfony/symfony/issues/1788) ? FYI, after changing these kind of parameters you should execute `bin/console cache:clear -e prod`.

**Comment by tYYGH** [comment]
@tcitworld, there is no way leaving out the host/socket information is going to work, since my socket path is not the default compiled-in socket path of PostgreSQL.
However, `cache:clear` did the trick! Thank you! Here’s the output now; much better:
```
oct. 25 08:18:19 seuil3 [2348]: 2017/10/25 08:18:19 [error] 2348#2348: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERREUR:  la relation « wallabag_craue_config_setting » n'existe pas
                                LINE 1: ...t0.value AS value_2, t0.section AS section_3 FROM wallabag_c...
                                                                                             ^ in /usr/share/webapps/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
```
This is a different issue, having to do with initialization, probably. So the current issue is solved :-)

**Comment by tcitworld** [comment]
The issue you have now is that the schema wasn't created inside your database, you'll have to run `bin/console wallabag:install -e prod`

**Comment by tYYGH** [comment]
Thanks for the tip @tcitworld ! I was just wondering how to handle this, since I use ansible to install; so I:

1. create the database,
2. then install wallabag

And so I did not know how I would script the database filling in step 1 when step 2 has not been done yet… chicken and egg situation :-D
You solved this for me. Cheers,
