### ISSUE TITLE
make run is broken

### ISSUE THREAD

**Issue by notFloran** [wallabag/wallabag#3391]
### Issue details

`make run` does not work since the upgrade to Symfony 3.3 (#3376 and #3381) : the makefile execute the command `server:run` with the `prod` env by default but the WebServerBundle is only active in `dev` env.

I see several solutions:

* enable WebServerBundle for all env
* throw an error in makefile for `run` if the env <> `dev`

### Environment

* wallabag version (or git revision) that exhibits the issue: `master (1953a872932a63792293b4aec087880265ba89f7)`
* How did you install wallabag? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version: `7.1`
* OS: `macOs`
* type of hosting (shared or dedicated): `dedicated`
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): `SQLite`

### Steps to reproduce/test case

Execute `make run`: 

<img width="488" alt="capture d ecran 2017-10-25 a 08 03 55" src="https://user-images.githubusercontent.com/523981/31982894-153326e8-b95b-11e7-8492-76e4aded5506.png">

**Comment by tcitworld** [comment]
Well `make run` shouldn't be used for production, so I don't see this as an issue. :/

**Comment by notFloran** [comment]
> shouldn't be used for production, so I don't see this as an issue. :/

@tcitworld I'm ok with that but the README and the doc indicate this:

```
cd wallabag && make install
make run
```

And by default the `prod` env is used by the makefile.

**Comment by tcitworld** [comment]
@wallabag/core Since this is bad behaviour, should we remove from the docs or fix that ?

**Comment by Kdecherf** [comment]
Imo we should completely remove the target `run` and update the documentation accordingly

**Comment by nicosomb** [comment]
Fixed with https://github.com/wallabag/wallabag/pull/3481
