### ISSUE TITLE
pdf export for particular article producing Internal Server Error

### ISSUE THREAD

**Issue by aschilling** [wallabag/wallabag#3403]
Hi everybody,

first of all I would like to contratulate you all for wallabag, great work! I identified a bug with the pdf export, not in general, but for this special article: https://stratechery.com/2017/goodbye-gatekeepers/

While wallabag fetches and displays the page properly, I get a "500 Internal Server Error" when I try to export it as a pdf. 

I use wallabag 2.2.3

Best regards
Andy

**Comment by Kdecherf** [comment]
Hi @aschilling,

I can't reproduce this issue on Wallabag 2.3/master, can you give us the PHP error log and result of `phpinfo()`?

**Comment by aschilling** [comment]
Unfortunately I am running wallabag on a shared webspace in which I cannot see the precise php error. Which part of the php.ini do you need? A list of all modules?

**Comment by Kdecherf** [comment]
A list of all modules and your current `memory_limit`

**Comment by aschilling** [comment]
Thank you very much for your reply. Please find below the details of the configure command of the corresponding section in the php.ini file

  _| './configure'   '--prefix=/opt/plesk/php/7.0' '--bindir=/opt/plesk/php/7.0/bin'  '--sbindir=/opt/plesk/php/7.0/sbin'  '--libexecdir=/opt/plesk/php/7.0/lib'  '--datadir=/opt/plesk/php/7.0/share'  '--sysconfdir=/opt/plesk/php/7.0/etc'  '--sharedstatedir=/opt/plesk/php/7.0/com'  '--localstatedir=/opt/plesk/php/7.0/var'  '--libdir=/opt/plesk/php/7.0/lib/x86_64-linux-gnu'  '--includedir=/opt/plesk/php/7.0/include'  '--infodir=/opt/plesk/php/7.0/share/info'  '--mandir=/opt/plesk/php/7.0/share/man' '--build=x86_64-linux-gnu'  '--host=x86_64-linux-gnu' '--with-libdir=lib'  '--cache-file=../config.cache'  '--with-config-file-path=/opt/plesk/php/7.0/etc'  '--with-config-file-scan-dir=/opt/plesk/php/7.0/etc/php.d'  '--disable-debug' '--without-pear' '--with-pic' '--disable-rpath'  '--with-bz2' '--with-freetype-dir=/usr' '--with-png-dir=/usr'  '--with-xpm-dir=/usr' '--enable-gd-native-ttf' '--without-gdbm'  '--with-gettext' '--with-gmp' '--with-iconv' '--with-jpeg-dir=/usr'  '--with-openssl' '--with-pcre-regex' '--with-zlib' '--with-layout=GNU'  '--enable-exif' '--enable-ftp' '--enable-sockets' '--enable-sysvsem'  '--enable-sysvshm' '--enable-sysvmsg' '--with-kerberos'  '--enable-calendar' '--with-libxml-dir=/usr' '--enable-xml'  '--enable-phpdbg' '--with-enchant=shared,/usr' '--with-system-tzdata'  '--with-litespeed' '--enable-pcntl' '--with-imap=shared'  '--with-imap-ssl' '--enable-mbstring=shared' '--enable-mbregex'  '--with-gd=shared' '--enable-bcmath=shared' '--enable-dba=shared'  '--with-db4=/usr' '--with-xmlrpc=shared' '--with-ldap=shared'  '--with-ldap-sasl' '--enable-mysqlnd=shared'  '--with-mysqli=shared,mysqlnd'  '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--enable-dom=shared'  '--with-pgsql=shared' '--with-snmp=shared,/usr' '--enable-soap=shared'  '--with-xsl=shared,/usr' '--enable-xmlreader=shared'  '--enable-xmlwriter=shared' '--with-curl=shared,/usr'  '--enable-pdo=shared' '--with-pdo-odbc=shared,unixODBC,/usr'  '--with-pdo-mysql=shared,mysqlnd' '--with-pdo-pgsql=shared,/usr'  '--with-pdo-sqlite=shared,/usr' '--with-sqlite3=shared'  '--enable-json=shared' '--enable-zip=shared' '--without-readline'  '--with-libedit' '--with-pspell=shared' '--enable-phar=shared'  '--with-mcrypt=shared,/usr' '--with-tidy=shared,/usr'  '--with-unixODBC=shared,/usr' '--enable-fileinfo=shared'  '--enable-intl=shared' '--with-icu-dir=/usr' '--enable-sysvmsg=shared'  '--enable-sysvshm=shared' '--enable-sysvsem=shared'  '--enable-posix=shared' 'build_alias=x86_64-linux-gnu'  'host_alias=x86_64-linux-gnu'
-- | --_

My memory limit is 256MB

Thanks
Andy

**Comment by Kdecherf** [comment]
Could you please try to increase memory_limit to 512MB?

**Comment by aschilling** [comment]
Thank you very much. It was indeed the memory limit. Now it works for me too
