### ISSUE TITLE
closing </ins> tag gets removed and destroys article design

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3406]
### Issue details
wallabag strips out the closing `</ins>` tag, but not the opening one. It either should leave the closing one in or remove the opening also. 

### Environment

* wallabag version (or git revision) that exhibits the issue:master branch commit 1953a872932a63792293b4aec087880265ba89f7
* How did you install wallabag? Via `git clone` or by downloading the package?git
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 5.6.30-0+deb8u1
* OS:debian
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

### Steps to reproduce/test case

1. add https://www.motorsport-magazin.com/formele/news-242884-formel-e-kein-motorsport-maro-engel-kompletter-schwachsinn/
2. see source code of article in wallabag, where wallabag starts to underline all following text.
3. compare

wallabag source:
```
dass wir auf Stadtkursen fahren.</p>
<ins data-revive-zoneid="559" data-revive-ct0="%c" data-revive-id="333a0346da5f8c7583b5d41baf64ff21"><p><strong>Ein weiterer Kritikpunkt: Die Autos seien zu langsam...</strong><br>
```

with original source:
```
dass wir auf Stadtkursen fahren. </p>
<ins data-revive-zoneid="559" data-revive-ct0="%c" data-revive-id="333a0346da5f8c7583b5d41baf64ff21"></ins><p><b>Ein weiterer Kritikpunkt:﷯ Die Autos seien zu langsam... </b><br>
```

**Comment by techexo** [comment]
@Strubbl I think it should be fixed with https://github.com/j0k3r/graby/pull/178 ?

**Comment by Strubbl** [comment]
Uhm, i still have wallabag 2.3.3 installed and cannot reproduce this issue anymore.

In which wallabag version can we expect j0k3r/graby#178?

**Comment by j0k3r** [comment]
In the 2.3.5

**Comment by HolgerAusB** [comment]
I can't see any  `<ins>` nodes in the source. Seems to be a redesign at source domain.
Please close issue.

Additional edits at the config following in a few minutes to get more beautifying.
