### ISSUE TITLE
Import articles using XML (not only JSON)

### ISSUE THREAD

**Issue by lapineige** [wallabag/wallabag#3409]
Exporting in json and xml is doable, and if I understand well both contain enough data to use them as backup data / for a transfert between 2 instances.
But import only works for json files.

Is it possible to implement xml import, or at least a script to convert xml to json ?
(additional question: is there any documentation page describing the organisation of both files ? It can help to make this kind of script)

Thanks :)

**Comment by lapineige** [comment]
Up :)

**Comment by j0k3r** [comment]
You can still use [a converter](https://www.google.fr/search?q=xml+to+json) to convert xml to json

**Comment by lapineige** [comment]
There is no specific syntax, no difference in the organisation between both format ? (you could have chosen to make different arrangement)
Ok, I'll try it :)

**Comment by lapineige** [comment]
I tried a converter (this script: https://github.com/hay/xml2json) and it doesn't seem to work: my file is converted to json, it seems to be correct (the first lines/tags are equivalent), size is roughly the same, but when trying to import it just show 1 task in queue and it imports an empty article.

**Comment by lapineige** [comment]
Quick update: I managed to partly solve the issue, by removing the `result` and `entry` (from <result><entry>...</entry></result> in the xml), now it recognize a list of articles.
But import still doesn't work.

The workers raised issues like these ones (non exhaustive list):
>PHP Warning:  mb_convert_case() expects parameter 1 to be string, array given in /var/www/wallabag2/src/Wallabag/CoreBundle/Helper/TagsAssigner.php on line 48
PHP Warning:  parse_url() expects parameter 1 to be string, array given in /var/www/wallabag2/vendor/j0k3r/graby/src/SiteConfig/ConfigBuilder.php on line 114
PHP Warning:  preg_match() expects parameter 2 to be string, array given in /var/www/wallabag2/vendor/j0k3r/graby/src/Extractor/ContentExtractor.php on line 115
PHP Warning:  urldecode() expects parameter 1 to be string, array given in /var/www/wallabag2/src/Wallabag/CoreBundle/Repository/EntryRepository.php on line 318
PHP Warning:  preg_match() expects parameter 2 to be string, array given in /var/www/wallabag2/vendor/j0k3r/graby/src/Extractor/ContentExtractor.php on line 115
PHP Warning:  preg_match() expects parameter 2 to be string, array given in /var/www/wallabag2/vendor/j0k3r/graby/src/Extractor/ContentExtractor.php on line 115
PHP Notice:  Array to string conversion in /var/www/wallabag2/vendor/j0k3r/php-readability/src/Readability.php on line 247
PHP Warning:  parse_url() expects parameter 1 to be string, array given in /var/www/wallabag2/vendor/j0k3r/php-readability/src/Readability.php on line 250
PHP Warning:  trim() expects parameter 1 to be string, array given in /var/www/wallabag2/vendor/j0k3r/php-readability/src/Readability.php on line 265
PHP Warning:  tidy_parse_string() expects parameter 1 to be string, array given in /var/www/wallabag2/vendor/j0k3r/php-readability/src/Readability.php on line 277
PHP Warning:  tidy_clean_repair() expects parameter 1 to be tidy, boolean given in /var/www/wallabag2/vendor/j0k3r/php-readability/src/Readability.php on line 278
PHP Warning:  mb_convert_encoding() expects parameter 1 to be string, array given in /var/www/wallabag2/vendor/j0k3r/php-readability/src/Readability.php on line 286
PHP Warning:  DOMDocument::loadHTML(): Empty string supplied as input in /var/www/wallabag2/vendor/j0k3r/php-readability/src/Readability.php on line 295
PHP Warning:  preg_match_all() expects parameter 2 to be string, array given in /var/www/wallabag2/vendor/j0k3r/graby/src/Extractor/ContentExtractor.php on line 1065
PHP Warning:  explode() expects parameter 2 to be string, array given in /var/www/wallabag2/vendor/htmlawed/htmlawed/htmLawed.php on line 183
PHP Warning:  trim() expects parameter 1 to be string, array given in /var/www/wallabag2/vendor/j0k3r/graby/src/Graby.php on line 410
14:21:08 ERROR     [app] Error trying to import an entry. ["entry_url" => ["#tail" => """  \n        ""","#text" => "https://domain.tld"],"error_msg" => "Url "http://" is not valid."] []

**Comment by lapineige** [comment]
Ok I found the problem: Using this script https://github.com/hay/xml2json, I had to use the option `--strip_text` which removes the lines ` "#tail": "\n    ",` inserted with a basic conversion.
(and also to remove `Result`>`Entry`, as noticed above)

Solved 🙂
