### ISSUE TITLE
CSS Styling not loading for wallabag

### ISSUE THREAD

**Issue by sitaramappetals** [wallabag/wallabag#3410]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to https://community.wallabag.org/ (forum) or http://gitter.im/wallabag/wallabag (chat).

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.30
* OS: Windows 8
* type of hosting (shared or dedicated): XAMPP
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Mysql

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

Hi,
I tried installing wallabag on my local system. i cloned it on my local system using composer.phar via shell prompt.

the system is working fine but the styling seems to be broken. Please help.

![walla](https://user-images.githubusercontent.com/16318545/32552458-0709512c-c4ba-11e7-97ad-f6bc2e0e1853.jpg)

**Comment by tcitworld** [comment]
Execute `git checkout . ` inside wallabag's folder.

**Comment by sitaramappetals** [comment]
A@AIO-12 d:\xampp\htdocs\wallabag
# git checkout
M       bin/symfony_requirements
M       var/SymfonyRequirements.php
Your branch is up-to-date with 'origin/master'.

A@AIO-12 d:\xampp\htdocs\wallabag
# php bin/console cache:clear

 // Clearing the cache for the dev environment with debug
 // true

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


A@AIO-12 d:\xampp\htdocs\wallabag
#

**Comment by aaa2000** [comment]
You have cleared the cache of `dev ` environment, try `php bin/console cache:clear ---env=prod`, 

If you want use the dev environment, the url for you is `127.0.0.1:8000/app_dev.php/login`

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
