### ISSUE TITLE
Bug Report: Download to PDF on some articles fails with "TCPDF ERROR"

### ISSUE THREAD

**Issue by partoneoftwo** [wallabag/wallabag#3413]
### Issue details

I have a very light Wallabag install with 9 articles are stored. 
Download of particular article, perhaps ones hidden behind "soft"-paywalls (soft as in, sometimes blocked, sometimes not)

Download to all other file formats than PDF works fine. 

### Environment

Installation path:
Wallabag v2.0.2 (106) provisioned through Cloudron with Docker

### Steps to reproduce/test case
I have verified the steps below, by deleting the article from my Wallabag and re-adding it. The issue persists.

Search for this Financial Times article on Google, searching for this particular URL:
https://www.ft.com/content/7eebc0f2-c303-11e7-a1d2-6786f39ef675
(This is necessary to access to article without being blocked by their soft-paywall).

Store to Wallbag, with Wallabagger in Chrome, manually adding or with Android app.

Export this article to PDF to reproduce the error.
Download to all other file formats than PDF works fine. 

### Error observed

> TCPDF ERROR: [Image] Unable to get the size of the image: https://:0/

Update: By issuing a "Re-Fetch Content" the error message changes to:

> TCPDF ERROR: [Image] Unable to get the size of the image: src

**Comment by Kdecherf** [comment]
Reproducible on current master (2.3) with this message:
```
TCPDF ERROR: [Image] Unable to get the size of the image: src
```

**Comment by partoneoftwo** [comment]
Confirmed for a separate URL as well: https://www.ft.com/content/d960dd80-c3d3-11e7-a1d2-6786f39ef675  There is something in these pages that flips up the PDF export code. Thanks for picking up my bug report.

**Comment by j0k3r** [comment]
Same as https://github.com/wallabag/wallabag/issues/2843
