### ISSUE TITLE
Include `sites_credentials` in the parameters template

### ISSUE THREAD

**Issue by adborden** [wallabag/wallabag#3416]
I ran into the issue described here: https://community.wallabag.org/t/catchable-fatal-error-after-clicking-on-import/76

When installing, you are prompted for `sites_credentials`, but if you don't know what the value is for, you might put in an invalid value, like a string. It's not clear that the default is an empty object. Having `sites_credentials: {}` in the parameters template would help (with or without documentation).

### Environment

* wallabag version 2.2.3
* How did you install wallabag? git clone; make install
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.30
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

1. cp app/config/parameters.yml.dist app/config/parameters.yml
1. `php bin/console wallabag:install --env=prod --no-interaction`

### Expected

No configuration is prompted, install succeeds and clicking "import" in the web UI works without error.

### Actual

Prompted for `sites_credentials`, putting in the wrong value causes "import" screen to fail.

**Comment by j0k3r** [comment]
This is a known issue and this will be fixed in the 2.3.
`site_credentials` will be removed from parameter and moved into the database. So you won't have to worry about how you have to insert them. There will be an UI for that.

The 2.3 is almost ready to be shipped.
