### ISSUE TITLE
unable to fetch content on geo.coop

### ISSUE THREAD

**Issue by ntnsndr** [wallabag/wallabag#3417]
### Issue details

I've repeatedly found that Wallabag is unable to grab text from the news website geo.coop. For instance: http://www.geo.coop/story/untold-story-evergreen-cooperatives. No next comes up in the Wallabag version

### Environment

wallabag version (or git revision) that exhibits the issue: current version at app.wallabag.it

**Comment by techexo** [comment]
@ntnsndr I am fetching this article perfectly with wallabag's latest release (2.3.4) that should arrive soon on wallabag.it.
Could you try again on your side, and close this issue if everything is okay?

**Comment by ntnsndr** [comment]
Oh great! I guess I'll have to wait for the new release to spread to .it. Doesn't work for me yet.

**Comment by j0k3r** [comment]
Fixed in 2.3.8
