### ISSUE TITLE
Proposal: replacing some material icons

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/wallabag#3437]
We currently have the following icons on the web app:

![2017-11-25-171909_1920x1080](https://user-images.githubusercontent.com/226063/33232457-2508b604-d207-11e7-984f-cf1b26040aff.png)

The back button can be counter-intuitive for left-to-right readers, so here's a possible change using icon `reply`, I also propose a change of the re-fetch icon to `refresh`:

![2017-11-25-172102_1920x1080](https://user-images.githubusercontent.com/226063/33232502-d41093ba-d207-11e7-8c87-326d5ff046c5.png)

Here are alternatives to the `reply` icon:

`keyboard_return`

![2017-11-25-172502_1920x1080](https://user-images.githubusercontent.com/226063/33232505-ebfadbf2-d207-11e7-8578-113998117d02.png)

`arrow_back`

![2017-11-25-172509_1920x1080](https://user-images.githubusercontent.com/226063/33232506-ed9da21e-d207-11e7-8dde-91e58ce6f81b.png)

`subdirectory_arrow_left`

![2017-11-25-172545_1920x1080](https://user-images.githubusercontent.com/226063/33232507-eebf1e3e-d207-11e7-8407-28d8beae6dde.png)

Moreover, I propose a change of "mark as unread" icon, from `redo` to `unarchive`:

![2017-11-25-172202_1920x1080](https://user-images.githubusercontent.com/226063/33232535-580af7c8-d208-11e7-9fbf-e90ae426c475.png)

Alternatively to left arrows, we could use `open_in_browser` which may be more neutral for both ltr and rtl readers:

_I show the `unarchive` icon here to see if we can use both icons without adding confusion._

![2017-11-25-173832_1920x1080](https://user-images.githubusercontent.com/226063/33232544-75e9dd9a-d208-11e7-9f48-a947794a325f.png)

Thoughts?

**Comment by j0k3r** [comment]
+1 for: reply, refresh & unarchive

**Comment by nicosomb** [comment]
ping @notabene

**Comment by notabene** [comment]
Hi, 

**1. back button**

I think the simple fact that you call the `reply` icon a `reply` icon says a lot on why I wouldn't use it. It's quite well-known visually as “reply”, although yes, it points in the right direction.

My preference would be the plain `arrow_back` which does what it promises ;)

**2. Refetch**

I have no problem with the original recycle icon, so either way suits you.

**3. Mark as unread**

Good idea, the `unarchive`. +1

**Comment by zertrin** [comment]
Funny I was thinking about the back button icon today (before seeing this issue), and said to myself that the current icon was not very intuitive and could be replaced by a "Home" icon instead (since it brings you to wallabag's "home page"). Just an alternative suggestion 😉

**Comment by Kdecherf** [comment]
@zertrin well, as long as the wallabag icon redirects to the home, I think we could use the `arrow_back` to go to the previous active list (_unread, archived, starred, search, tags view, …_)

**Comment by zertrin** [comment]
Well I don't understand your comment:

1) there is no wallabag icon when on an article's page
2) I just tried it, going to Archive, opening an article and then clicking on "Back" doesn't bring back to the archive list, but to the home page

Are you suggesting to change the article view page to address 1) and 2) ?? (for example by changing the behaviour of 2) to really do the equivalent of history.back() and for 1), by adding a wallabag icon on the article page to bring back to the home?)
