### ISSUE TITLE
[Idea to discuss] Show article date

### ISSUE THREAD

**Issue by notabene** [wallabag/wallabag#3446]
Hi,

Most articles I add to Wallabag are blog entries, and their post date is interesting: to truly understand an article, you often need its historical context.

**Would there be a way to add the data to the entry in Wallabag and fetch it/show it?**

— btw @nicosomb is _Issues_ the right way to discuss general UX questions?

**Comment by nicosomb** [comment]
As discussed with you, this feature is already available in coming 2.3, see my below screenshot:
<img width="902" alt="capture d ecran 2017-12-01 a 15 20 34" src="https://user-images.githubusercontent.com/121870/33487241-ce4babf0-d6ac-11e7-8166-b0fd9a98010f.png">
