### ISSUE TITLE
[RSS] pubDate not conformant

### ISSUE THREAD

**Issue by notabene** [wallabag/wallabag#3448]
### Issue details

In starred feed, archive feed, etc., The `pubDate` of an RSS item is not valid as it does not meet the Date and Time specifications as defined by RFC822. My guess is that it lacks a timezone.

### Steps to reproduce/test case

1. Grab the RSS feed.
2. Push its URL into https://validator.w3.org/feed/
3. Get _line 9, column 42: pubDate must be an RFC-822 date-time: Fri, 01 Dec 2017 14:26:22_ as a result.

This points to https://validator.w3.org/feed/docs/error/InvalidRFC2822Date.html

Reproduced by @notabene and @foxmask 

### Possible steps to correct

1. Add a timezone? (I'm groping in the dark here)
2. Revalidate at https://validator.w3.org/feed/

**Comment by tcitworld** [comment]
I thought it was related to https://github.com/wallabag/wallabag/blob/master/app/config/config.yml#L354, but it doesn't seem to be the same.

**Comment by cvergne** [comment]
Related to [a twig template](https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig#L25).
I think the quick solution would be to use `r` as date format, but the better solution would be to use the [`DATE_RSS` PHP constant](http://php.net/manual/en/class.datetime.php#datetime.constants.types).

I'll be happy to fix it when I find time to set up the project locally (tests, etc.), if someone does not fix it before :)

**Comment by j0k3r** [comment]
@cvergne feel free to open a PR :+1:

**Comment by notabene** [comment]
❤️
