### ISSUE TITLE
Upgrading from 2.2.3 to 2.3.0

### ISSUE THREAD

**Issue by andyforceno** [wallabag/wallabag#3450]
Is upgrading from 2.2.x to 2.3.x the same process as upgrading from 2.1.x to 2.2.x? If I follow the docs, will it go smoothly, or are there additional steps that need to be performed?

**Comment by Findus23** [comment]
Hi,
I just upgraded from the latest release to master by uncommenting the following line 
https://github.com/wallabag/wallabag/blob/e9a4231d4f39c5d330d581113f577ff3ef1a3cf9/scripts/update.sh#L17
checking out master and running make update. 
All migrations ran without an issue and it’s working fine.

**Comment by Kdecherf** [comment]
This manual change is not needed anymore as the version 2.3 has been officially released.
