### ISSUE TITLE
Bookmarking Tool

### ISSUE THREAD

**Issue by Zeriuno** [wallabag/wallabag#3452]
This is a feature request, not an issue.
From time to time, I would like to use Wallabag to simply save adresses, like one can do with bookmarks, and I do not need the content retrieval: it could be a checkbox to tick.
If this fits in Wallabag, it could be useful for me.

**Comment by j0k3r** [comment]
See https://github.com/wallabag/wallabag/issues/1456#issuecomment-145437502

**Comment by Zeriuno** [comment]
Well, @nicosomb prompted me to open the issue... : )

**Comment by nicosomb** [comment]
Yes sorry, I forgot this previous issue and my comment 🙄
