### ISSUE TITLE
Incorrectly configured certificate on v2.wallabag.org

### ISSUE THREAD

**Issue by Zeriuno** [wallabag/wallabag#3453]
### Issue details

Incorrectly configured certificate on https://v2.wallabag.org/login:

v2.wallabag.org uses an invalid security certificate. The certificate is only valid for dev.framakey.org Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by j0k3r** [comment]
Sorry but v2.wallabag.org shouldn't be used.
It'll be killed in the near future.
You should jump to https://framabag.org/ or https://wallabag.it/
