### ISSUE TITLE
Can't retrieve article at vanityfair.com

### ISSUE THREAD

**Issue by Zeriuno** [wallabag/wallabag#3454]
### Issue details

Tested on wallabag.it
Can't retrieve https://www.vanityfair.com/news/2017/10/early-facebook-employees-regret-the-monster-they-created
Using the option of an external parser https://f43.me/feed/test retrieves the article text (not the header nor the main image)

**Comment by bdunogier** [comment]
Confirmed here as well.

**Comment by Kdecherf** [comment]
Fetching looks ok on the latest release (2.4.1), closing this issue.
