### ISSUE TITLE
Kill v2.wallabag.org

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#3456]
Some users (https://github.com/wallabag/wallabag/issues/3453 & https://github.com/wallabag/wallabag/issues/3353) still try to use v2.wallabag instead of framabag or wallabagit.
We should kill that domain **right now** to avoid further noise.

**Comment by Kdecherf** [comment]
The domain now redirects to wallabagit, can we close it @j0k3r @tcitworld?

**Comment by j0k3r** [comment]
I still have that issue in Chrome ...

![image](https://user-images.githubusercontent.com/62333/68665666-bd4ad580-0542-11ea-911a-4b120d44caea.png)

**Comment by Kdecherf** [comment]
Wait, there is no more redirection, it now leads to an unrelated website. Can we kill or fix the involved DNS record?

**Comment by Kdecherf** [comment]
The record has been removed, closing this ticket
