### ISSUE TITLE
Provide doc on how to enable download images feature

### ISSUE THREAD

**Issue by andrey-str** [wallabag/wallabag#3458]
### Issue details

There is no documentation(and UI option in that matter) on how to enable download images option. PR #2180 claims that feature is implemented, but I was not able to find how to turn it on. API returns external links, images in articles also refferes to external resources. 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3

* How did you install wallabag? Via `git clone` or by downloading the package?

git clone, checkout releas tag, etc. I did several upgrades. 

* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.0.22
* OS: ubuntu 17.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): damn, dont remeber. it is either sqlite or mysql

### Steps to reproduce/test case

 N/A

**Comment by andrey-str** [comment]
Also please write here also how to do that 🙈

**Comment by nicosomb** [comment]
Is this page useful for you? https://doc.wallabag.org/en/admin/internal_settings.html#download-images-locally

**Comment by andrey-str** [comment]
Yep, many hanks. 
Is this option off by default for new installations?

**Comment by nicosomb** [comment]
Yes it is.

**Comment by Alwaysin** [comment]
@nicosomb I think it makes sense to enable this feature by default. I was about to do a PR but I think would be best to discuss it with you before. There probably is a reason it is not but given the goal of the project I think it'd be the expected behaviour.
