### ISSUE TITLE
Baggy theme deprecation

### ISSUE THREAD

**Issue by Simounet** [wallabag/wallabag#3460]
Maybe it is time to mark our long time loved baggy buddy as deprecated and invite users to switch to material. I don't know if you have any information about this theme being still used.
What do you think?

**Comment by nicosomb** [comment]
FYI, on app.wallabag.it, 123 users (on 3172 users) have the baggy theme.

**Comment by Simounet** [comment]
It's a great info. It could be great to be in touch with them (mailing with a poll) to know why they are still using it instead of material.

**Comment by yelfathi** [comment]
The default of Material theme is the preview picture, I prefer to have a minimalist list of articles instead. So maybe add an option to hide this pictures.

**Comment by tcitworld** [comment]
There's a list view in material theme

**Comment by yelfathi** [comment]
I don't see the option at wallabag.it.

**Comment by tcitworld** [comment]
It's the button next to the RSS feed button.
![](https://screenshotscdn.firefoxusercontent.com/images/46b1183f-696f-45c2-96f3-b6d553bed7fb.png)

**Comment by yelfathi** [comment]
Ah this button yes I have it but on Material theme you still see the preview pictures (indeed in lower format) but it's not minimalist as I said earlier. Thanks.

**Comment by j0k3r** [comment]
I'm all in for that.
