### ISSUE TITLE
Wallabager Firefox addon not working

### ISSUE THREAD

**Issue by nunoleite** [wallabag/wallabag#3462]
### Issue details

I installed Wallabager Firefox Addon, and activated the API.
It's says "Saving the page to wallabag..." The icon goes yellow, then red, and then black again.
And it doesn't save.

### Environment

* wallabag version (or git revision) that exhibits the issue: Wallabager 1.4.4, Firefox 57.0.1, Wallabag 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? Downloaded package
* Last wallabag version that did not exhibit the issue (if applicable): just have these ones
* php version: 7.0
* OS: CentOS 7.4 with Cloudlinux
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): default SQLite

### Steps to reproduce/test case

I installed Wallabager Firefox Addon, and activated the API.
It's says "Saving the page to wallabag..." The icon goes yellow, then red, and then black again.
And it doesn't save.
I'm just stating to use Wallabag, and the bookmark works, and the rest option from the icon in Firefox works, just the page save doesn't work.

**Comment by nicosomb** [comment]
Hellop @nunoleite 

Do you still have the bug now?

**Comment by nunoleite** [comment]
Hi!
I will update and check.

**Comment by nunoleite** [comment]
After updating from 2.2.3 to 2.3 it seems to be the same, I can pocket with the bookmark link, but no with the Firefox Addon.
The Addon Check show correct values and i can go to the "All articles" or "Archived articles", but can't save.

After the upgrade now the icons are not loaded. All i have is text instead of icons. Only the wallabag logo displays.
![image](https://user-images.githubusercontent.com/173281/34257963-fa7e2c28-e653-11e7-8062-1c0782b89a42.png)
![image](https://user-images.githubusercontent.com/173281/34258014-2611d0ba-e654-11e7-9840-60412c9a75e1.png)

**Comment by nunoleite** [comment]
Hi!
Today i updated Wallabager to ver. 1.4.5 and still not working.

**Comment by nicosomb** [comment]
Did you well configured it?

**Comment by nunoleite** [comment]
Hi!
I even tried to create a new api client and the  plugin says that is ok.
I already have 2.3.1
And the images are still not working

**Comment by nicosomb** [comment]
Ping @simounet

**Comment by Simounet** [comment]
Hello,
Are your issues with icons on wallabag disappeared? About wallabagger, can you follow these steps:

- enable the debug mode into the wallabagger settings
- go to about:debugging#addons
- check in Enable add-on debugging
- click on wallabag debug link
- click on ok to accept incoming connections
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by nunoleite** [comment]
```
22:18:40.618 Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.  spectre.min.css:1:496
22:18:40.619 Unknown pseudo-class or pseudo-element ‘-webkit-inner-spin-button’.  Ruleset ignored due to bad selector.  spectre.min.css:1:2178
22:18:40.619 Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.  spectre.min.css:1:2315
22:18:40.619 Unknown property ‘user-select’.  Declaration dropped.  spectre.min.css:1:5117
22:18:40.619 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:6302
22:18:40.620 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:6827
22:18:40.620 Unknown property ‘appearance’.  Declaration dropped.  spectre.min.css:1:7778
22:18:40.620 Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector.  spectre.min.css:1:8304
22:18:40.620 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:10472
22:18:40.621 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:11874
22:18:40.621 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:14120
22:18:40.621 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:14767
22:18:40.622 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:18919
22:18:40.622 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:19486
22:18:40.622 Unknown property ‘user-select’.  Declaration dropped.  spectre.min.css:1:20613
22:18:40.623 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:21509
22:18:40.623 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:22763
22:18:40.624 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:26378
22:18:40.624 Error in parsing value for ‘display’.  Declaration dropped.  spectre.min.css:1:26452
22:18:40.624 Error in parsing value for ‘word-break’.  Declaration dropped.  spectre.min.css:1:27142
22:18:40.625 Unknown property ‘speak’.  Declaration dropped.  icomoon.css:14:5
22:18:40.625 Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.  icomoon.css:23:5
22:18:41.039 The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.  popup.html
22:18:41.131 postMessage: {"response":"setup","data":{"Url":"http://pocket.xxx.com/web","ApiVersion":"2.3.0","ClientId":"1_pt85mwybsusok0o8ow8sks000csowkkgwoo4ocgc4g4s4kso0","ClientSecret":"4ykbgwz89rks0sk80wwgc4g4occkwg4w4kcss4osgws80880cc","UserLogin":"xxx","UserPassword":"xxx","ApiToken":"Yjc1ZjQ5NjlmOTliMzA4NGE0ZDIzMjQxNzNhYzQ2N2UyMTNlYzNmM2NjMWIwMWM4OTcwNmZhNmUwNTNkNjhkNQ","RefreshToken":"ZTIyY2ZmZDYyNzJjOGUxZDc5MzhiMWM5ZmM2YWUwZTc2NzE3YmJjZjIxZDBmMzNmNGViYjAzYjVhMmRhOTU0ZA","ExpireDate":1514503044584,"isTokenExpired":false,"AllowSpaceInTags":false,"AllowExistCheck":false,"Debug":true}}  background.js:180:23
22:18:41.165 postMessage: {"response":"info","text":"Saving the page to wallabag…"}  background.js:180:23
22:18:41.550 Error: Failed to get tags http://pocket.xxx.com/web/api/tags.json
                OAuth2 authentication required  wallabag-api.js:235:23
22:18:41.617 Error: Failed to save page http://pocket.xxx.com/web/api/entries.json
                undefined  wallabag-api.js:181:23

```
I still don't have the icons

**Comment by nunoleite** [comment]
I tried again to put 2.3.1 working and now i have wallabag all in text mode. no graphics.
This seems to be too complicated to work-with in a shared hosting.
On a dedicated server i really don't know. But i find it difficult to update and move forward.
I tried to install 2.3.1 from the beginning and it doesn't have the initial installation that 2.2.3 had.
Then i created a new mysql database and tried to config the parameters.yml but too difficult to make it work. Even with all configuration set it just can't connect do database.
The documentation doesn't seem to help.
I'm using a shared hosting on a cPanel account.

**Comment by Simounet** [comment]
Are you accessing to wallabag through: http://pocket.xxx.com/web/ ? With the web at the end your URL?

**Comment by nunoleite** [comment]
Hi!
Yes, the folder "web" is the folder where i can browse Wallabag.
But i already uninstalled Wallabag, i found it too complicated, and even couldn't get almost any page that i wanted to save for later. It's not working with lots of pages and the ones that i can save are all deformed and difficult to read.
So, for now i'm saving the pages offline on my computer.
In the future i will try to find again a solution for this.
Sorry.
I think this should be simple like installing a CMS or something like that. Every time i tried an upgrade it's a nightmare. I used version 1.9 and it was better.
Thanks.
