### ISSUE TITLE
Hide the "Published by" icon if author is empty

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#3464]
It seems an empty string is sometime passed as the author of an article, resulting in this : 

![selection_141](https://user-images.githubusercontent.com/2197836/33709678-6467db50-db3e-11e7-835c-499f3eeeebf5.png)
Two things to do : 
* don't show the icon if the author is empty
* fix it inside Graby (i.e don't send the author property if it's an empty string) @j0k3r 

Version : ~2.3 / wallabag.it

**Comment by j0k3r** [comment]
Article example ?

**Comment by tcitworld** [comment]
[This one](https://www.hacking-social.com/2015/10/13/se-motiver-et-motiver-autrui-une-histoire-dautodetermination/) or [this one](https://medium.com/@adriengueret/docteur-je-suis-un-imposteur-afe8f302098f)
It also happens with [this PDF](https://simson.net/ref/ugh.pdf)

**Comment by nicosomb** [comment]
Can't reproduce it locally or on wallabag.it.

**Comment by tcitworld** [comment]
Me neither with the articles linked above. Will reopen if necessary.
