### ISSUE TITLE
Thumbails not found

### ISSUE THREAD

**Issue by TakerMc** [wallabag/wallabag#3476]
Hello,

I've just updated wallabag on my server and i've noticed that articles thumbnails doesn't show. 

The addresses of the thumbnails does not matches with the pictures,  so i got 404 errors. 

Here's what i got, for instance: 
https://wallabag.taker.fr/view/wallabag.taker.fr/assets/images/4/6/4649e573/f4cb62a6.jpeg  => 404 

The correct address for that thumbnail is https://wallabag.taker.fr/assets/images/4/6/4649e573/f4cb62a6.jpeg

My parameters.yml file: 

```# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: name
    database_user: user
    database_password: password
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: secret
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    domain_name: 'https://wallabag.taker.fr' ```

**Comment by nicosomb** [comment]
Hello @TakerMc 

Does this bug occur when you save a new article? Or is that only for existing articles?

**Comment by TakerMc** [comment]
Hello

I only have this bug on new article

**Comment by nicosomb** [comment]
@TakerMc Did you clear your cache after the upgrade? (`bin/console cache:clear -e=prod`) 

In our Download subscriber, we return the host for the instance: 

`return $this->wallabagUrl . '/assets/images/' . $relativePath . '/' . $hashImage . '.' . $ext;`

where `$this->wallabagUrl` is the `%domain_name%` defined in `app/config/parameters.yml`.

wallabag don't try to guess the value of the instance, it's only based on configuration, so I'm not sure if your instance is well configured (but maybe I'm wrong).

**Comment by TakerMc** [comment]
Hello,

I've found why it wasn't working. 

In parameters.yml, first i've tried:

`domain_name: 'wallabag.taker.fr' `

Once i've corrected it to `https://wallabag.taker.fr` i just needed to reload the articles.

**Comment by nicosomb** [comment]
Nice.
