### ISSUE TITLE
(ugly) sandwich menu visible on desktop

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#3482]
I just installed a fresh version of 2.3.0, and I've got this button: 

<img width="583" alt="capture d ecran 2017-12-12 a 08 59 43" src="https://user-images.githubusercontent.com/121870/33873403-1e7cf9b4-df1b-11e7-9eaf-9da2b8f89bd1.png">

@tcitworld do you know if I forgot something about assets? 
@Simounet not sure if it's a CSS issue in fact.

**Comment by Kdecherf** [comment]
Please clear your browser cache, I got the same thing ;-)

**Comment by nicosomb** [comment]
Nope, the bug is still there (I tried in an other browser too).

**Comment by Simounet** [comment]
Hmmm, I just tried it from a fresh install with the master branch and didn't get any issue.

**Comment by nicosomb** [comment]
Can't reproduce. Feel free to reopen if you encounter this bug again 😄

**Comment by Kdecherf** [comment]
After encountering this issue again, I think it was linked to dev assets. A `yarn build:dev` fixed it for dev env ;-)
