### ISSUE TITLE
Wallabag 2.3.0 DB prefix issue

### ISSUE THREAD

**Issue by GaneshKandu** [wallabag/wallabag#3486]
### Issue details

When i try to install wallabag by changing "database_table_prefix" it throws following error :
1 . There is no table with name 'walla230.prewb_entry' in the schema.

I have attached log file to debug.

[prod.log](https://github.com/wallabag/wallabag/files/1551025/prod.log)

### Environment

* wallabag version : 2.3.0
* How did you install wallabag? Via `git clone` or by downloading the package? wget [https://wllbg.org/latest-v2-package](https://wllbg.org/latest-v2-package) && tar xvf latest-v2-package ( mentioned on [https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting](https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting) )
* php version: 5.6.23
* OS: Apache/2.2.31 (Unix) Server
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

* Steps which i have followed
	* Unziped wallabag 2.3.0 package iin sub-directory
	* Created blank database for wallabag
	* Manually filled the database details in "app/config/parameters.yml" with "prewb_" as table prefix
	* Given writable permission to var folder.
	* Then run this command "php bin/console wallabag:install --env=prod"
	* Installer says "It appears that your database already exists. Would you like to reset it? (yesno) [no]:"
	* After hitting "no". Getting error which I mentioned above

![untitled2](https://user-images.githubusercontent.com/12833130/33878581-d9244282-df51-11e7-808d-0948c25e57a9.png)
![untitled](https://user-images.githubusercontent.com/12833130/33878582-d961459c-df51-11e7-9bd5-36d3fc875b16.png)

**Comment by nicosomb** [comment]
@aaa2000 any idea?

**Comment by aaa2000** [comment]
PR #3504 should  resolve that.

**Comment by nicosomb** [comment]
@GaneshKandu Could you try the @aaa2000's fix please?

**Comment by GaneshKandu** [comment]
Hi,
Wallabag 2.3.0 database prefix issue is solved working fine
but getting issue with font getting 404 error created new issue #3518
