### ISSUE TITLE
Wallabag returns a 500 error with "Stream or file could not be opened"

### ISSUE THREAD

**Issue by PrimordialHelios** [wallabag/wallabag#3496]
### Issue details

Every time I restart my server, Wallabag returns a 500 error. Occasionally I can somehow get it to restart by clearing the cache, but this time nothing seems to work. In my Wallabag apache logs I have entries with:

    [Tue Dec 12 19:51:34.735635 2017] [php7:error] [pid 5962] [client 45.47.130.97:36588] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/wallabag/var/logs/prod.log" could not be opened: failed to open stream: Permission denied in /var/www/wallabag/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/wallabag/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/wallabag/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php(58): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/wallabag/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(98): Monolog\\Handler\\AbstractHandler->handleBatch(Array)\n#3 /var/www/wallabag/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(119): Monolog\\Handler\\FingersCrossedHandler->activate()\n#4 /var/www/wallabag/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\FingersCrossedHandler->handle(Array)\n#5 /var/www/wallabag/vendor/monolog/monolog/src/Monolog/Logger. in /var/www/wallabag/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

The file mentioned (prod.log) exists, and everything in the Wallabag directory belongs to the apache user and is writable, so I'm not sure what the issue is

### Environment

* wallabag version: 2.2.3 - 2017-05-18
Installed from github release
* php version: 5.1.8
* OS: Fedora 26 Workstation
* type of hosting: Dedicated
* Storage system: MySQL

### Steps to reproduce/test case

Restarting the server, visiting the Wallabag page. I know it isn't much, but it works every time for me.

**Comment by PrimordialHelios** [comment]
Upgraded to 2.3.0, same issue/

**Comment by j0k3r** [comment]
Does rights are ok ?
https://doc.wallabag.org/en/admin/installation/rightaccess.html

**Comment by PrimordialHelios** [comment]
And of course the issue was SELinux. Thanks for linking that, I hadn't seen it.
I appreciate the help!
