### ISSUE TITLE
Le Monde Diplomatique paywall not working

### ISSUE THREAD

**Issue by husimo** [wallabag/wallabag#3502]
Hello,

### Issue details

When I try to add a Le Monde Diplomatique article, it's only downloading free part of article. I have LMD credentials (domain : monde-diplomatique.fr) in my options.

### Environment

* Wallabag 2.3.0
* Docker

### Steps to reproduce/test case

Add settings for LMD (I can share it if you want for testing) in wallabag options.
Try to fetch a LMD paid article.
Wait for download, you have the content as you were not connected.

Thank you :)

**Comment by nicosomb** [comment]
I think that @bdunogier tried to save articles last week and he didn't manage too. 
@bdunogier: any idea?

**Comment by TakerMc** [comment]
I've been fetching article from LMD successfully.

Let me know if I can do something to help with this issue @nicosomb

**Comment by nicosomb** [comment]
@TakerMc Sure. How did you do?

**Comment by TakerMc** [comment]
I've simply add my LMD account on wallabag.

But I've noticed something when you configure the account: if for the domain field you put `https://www.monde-diplomatique.fr` it will not work. You have to put `monde-diplomatique.fr`

Does it solve your issue @husimo ?

**Comment by husimo** [comment]
@TakerMc Nope, it's not working even with monde-diplomatique.fr. I tried fetching https://www.monde-diplomatique.fr/2017/10/SUPIOT/58009 and some others. Don't know why. I tried to change my password to test but issue is the same (I guess it's not relevant but it's working properly with nextinpact.com).
Thank you

**Comment by TakerMc** [comment]
That's weird ... 

I really don't understand why it works for me and not for you ... Maybe there's something different in our configurations.

**Comment by husimo** [comment]
You're using it with Wallabag 2.3 ? 
I just added "monde-diplomatique.fr" as domain an then my username (with email) and my password.

**Comment by TakerMc** [comment]
Yes I'm using Wallabag 2.3

Same, the login is my email, and then there's the password. 

Are you willing to try on my wallabag ?

**Comment by husimo** [comment]
Actually I tried on wallabag.it and I have the same problem.
Yeah, no problem, we can try it if you want ;-)

**Comment by TakerMc** [comment]
You can go here: https://wallabag.taker.fr/register/

**Comment by husimo** [comment]
Thank you. I tried but it's not working. So it must be related to my account. Basically, it's just connecting on the website before fetching content is it ? Because I can properly read all content on monde-diplomatique.fr.

**Comment by TakerMc** [comment]
I think so. I've run out of ideas. 

Is there any log file in wallabag that could help @nicosomb ?

**Comment by nicosomb** [comment]
Sure. In wallabag/var/logs/prod.log

**Comment by TakerMc** [comment]
@husimo Is there anything in this logfile when you try to fetch an article from LMD ?

**Comment by j0k3r** [comment]
If you have followed the documentation [about fetching errors](https://doc.wallabag.org/en/user/errors_during_fetching.html#enable-log-to-help-us-identify-the-problem): yes. Otherwise no.

**Comment by bdunogier** [comment]
I don't really have ideas based on the above. If it doesn't work on wallabag.it either, then it means that it's not a configuration problem.

**Comment by nicosomb** [comment]
@TakerMc Did you update the LMD configuration file?

**Comment by TakerMc** [comment]
No

**Comment by prolibre** [comment]
Hello. Same thing for me. This works for arrretsurimages. net but it doesn't work for monde-diplomatique.fr
__
Bonjour. Même chose pour moi. Cela fonctionne pour arretsurimages.net mais cela ne fonctionne pas pour le  monde-diplomatique.fr

**Comment by prolibre** [comment]
idem in Wallabag 2.3.2 :-(

**Comment by bdunogier** [comment]
Dammit. I'll try to have a look, thank you for reporting this.

**Comment by raf64flo** [comment]
Hi, I get the same problem for ASI, I have configured site credentials for ``arretsurimages.net`` as same as ``beta.arretsurimages.net``, but only the first lines of the article are fetched (for instance: https://beta.arretsurimages.net/articles/face-a-cash-investigation-veolia-tente-un-contre-feu).

Looking at ``prod.log`` file is not helpful, nothing is writen in it although debug is enabled.

I'm auto hosted on an up-to-date Yunohost instance (2.7.10).

Let me know of I can give you more info. o/

**Comment by thibaultamartin** [comment]
Hi everyone, does the issue still occur?

**Comment by Nimn** [comment]
Ok for me for `monde-diplomatique.fr` but not for `arretsurimages.net` (probably since the new site). Note for `arretsurimages.net`free article are also not recorded.

**Comment by j0k3r** [comment]
Thanks @Nimn I'm closing the issue. You can try to fix `arretsurimages.net` free article on your own if you want: https://doc.wallabag.org/en/user/errors_during_fetching.html#errors-while-fetching-articles
