### ISSUE TITLE
cached GIFs are not playable

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3505]
### Issue details
When i have image caching enabled on server and i add an article containing a movie in a gif, the gif is not correctly fetched. The animation is gone in wallabag article although there is one in the original article.

### Environment

* wallabag version (or git revision) that exhibits the issue: master commit 494b47f29915cc881cfeba14c16b728d3adcb85a which shows itself in wallabag as 2.3.0
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): - 
* php version: 7.0
* OS:debian stretch
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgres

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

0. have image caching in your wbg instance active
1. add article https://www.wallabag.org/en/news/new-release-wallabag-2-3-is-there-really
2. compare kangaroo animation in wallabag article with original article

**Comment by j0k3r** [comment]
Maybe `imagegif` isn't enough to keep animation.
https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Helper/DownloadImages.php#L131

**Comment by nicosomb** [comment]
https://stackoverflow.com/questions/9806732/moving-gif-animated-file-loses-animation-with-imagegif

**Comment by Simounet** [comment]
Is it a security issue that push you to create every image again? If it's your position, we can try to use `imagemagick` if available and use `imagegif` as a fallback.
