### ISSUE TITLE
Fonts URLs are hardcoded

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#3519]
### Issue details

I have wallabag installed in a shared server and It's not in the root path. I.e.
`https://domain.org/wallabag/web/`
Ant with the last version it's trying to download fonts from this path:
`https://domain.org/wallassets/fonts/MaterialIcons-Regular.woff`
Should be relative:
`https://domain.org/wallabag/web/wallassets/fonts/MaterialIcons-Regular.woff`

### Environment

* wallabag 2.3.0
* How did you install wallabag? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): 2.2.3

**Comment by nicosomb** [comment]
Hello @ngosang 

Your issue is a du plicate of #3485.
