### ISSUE TITLE
Download images locally (again)

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#3520]
This bug is the continuation of #2964

### Issue details
1) Enable "Download images locally"
2) Add => https://www.tvaddons.co/realdebrid-kodi-jarvis/
3) One image is not stored locally.

![imagen](https://user-images.githubusercontent.com/10577978/34124705-28028562-e434-11e7-925e-532fe5dd6839.png)

### Environment
* wallabag version 2.3.0

**Comment by j0k3r** [comment]
Again. Pff :disappointed:

**Comment by ngosang** [comment]
The original article has something like this:
`<img width="300" height="350" class="entry-thumb" src="https://i1.wp.com/www.tvaddons.co/wp-content/uploads/2017/01/Screen-Shot-2017-01-07-at-10.17.40-PM.jpg?resize=300%2C350&ssl=1" srcset="https://i1.wp.com/www.tvaddons.co/wp-content/uploads/2017/01/Screen-Shot-2017-01-07-at-10.17.40-PM.jpg?resize=300%2C350&ssl=1 300w, https://i1.wp.com/www.tvaddons.co/wp-content/uploads/2017/01/Screen-Shot-2017-01-07-at-10.17.40-PM.jpg?zoom=2&resize=300%2C350&ssl=1 600w" sizes="(max-width: 300px) 100vw, 300px" alt="" title="Screen-Shot-2017-01-07-at-10.17.40-PM" />`

After replacements:
`<img width="300" height="350" class="entry-thumb" src="https://domain.org/wallabag/web/assets/images/8/e/8e668b2a/1dd3344b.jpeg" srcset="https://domain.org/wallabag/web/assets/images/8/e/8e668b2a/1dd3344b.jpeg 300w, https://i1.wp.com/www.tvaddons.co/wp-content/uploads/2017/01/Screen-Shot-2017-01-07-at-10.17.40-PM.jpg?zoom=2&amp;resize=300%2C350&amp;ssl=1 600w" alt="" title="Screen-Shot-2017-01-07-at-10.17.40-PM" />`

In `srcset` parameter there are 2 URLs for different window sizes. The first one is replaced but not the second one. I don't know if HTML allows this but anyway I think this is a corner case.

**Comment by j0k3r** [comment]
Current replacement script doesn't handle `srcset` attributes.

**Comment by j0k3r** [comment]
Duplicates #2981
