### ISSUE TITLE
Login page is blank when running make in home folder rather than in /var/www

### ISSUE THREAD

**Issue by P3lUZa** [wallabag/wallabag#3523]
### Issue details

If I clone the repository in my home folder, then run
`make install` 
Follow the usual procedure
Then move wallabag to /var/www/
Then
`chown -R www-data:www-data wallabag`
When accesing mywallabag.example that takes me to mywallabag.example/login
But nothing happens, just a white page

In the other hand if I clone the repository, move it to /var/www/
Then, from there run the
`make install` 
chown it to www-data
Everything works perfect!
(the only difference is that in the first case i run the make install from home folder and in the good case from the /var/www folder)

Not problem of the database, I can login with the configuration (wallabag folder) that works, then put the configuration (wallabag folder) that does not work and accesing to  mywallabag.example takes me to mywallabag.example/quickstart - So my credentials are remembered and it tries to take me to the home page but a white page is displayed too.

No single error shown in wallabag/var/logs or /var/log/apache2/wallabag_*
Difficult to debug it!

### Environment

* wallabag version (or git revision) that exhibits the issue: latest
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: 7
* OS: Debian 8
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql 5.6

**Comment by nicosomb** [comment]
Hello @P3lUZa 

After moved your folder, could you run `bin/console cache:clear -e=prod` in your wallabag folder please?

**Comment by P3lUZa** [comment]
OK I repeated the process (make in my home folder), then moving the folder to /var/www/, then
`bin/console cache:clear -e=prod`
Then 
`chown -R www-data:www-data wallabag`

And it works now, that solves the problem. 
I took me a lot of time to fix it (the other way I suggested), I think it should be added to the GitBook the recommendation to clear the cache, that would have saved me a lot of time :)
