### ISSUE TITLE
medium link has error when adding a link 

### ISSUE THREAD

**Issue by xingh** [wallabag/wallabag#3527]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details
`SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x91\x87</...' for column 'content' at row 1`

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to https://community.wallabag.org/ (forum) or http://gitter.im/wallabag/wallabag (chat).

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3
* How did you install wallabag? Via `git clone` or by downloading the package? docker compose
* Last wallabag version that did not exhibit the issue (if applicable): ??
* php version: docker
* OS: docker
* type of hosting (shared or dedicated): docker on azure vm
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mariadb

### Steps to reproduce/test case

Added https://hackernoon.com/thinking-in-redux-when-all-youve-known-is-mvc-c78a74d35133

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by j0k3r** [comment]
What's the charter of your database in app/config/parameters.yml?
It must be "utf8mb4" but you should have "utf8"

**Comment by glego** [comment]
@j0k3r, close the issue?
