### ISSUE TITLE
bulk action

### ISSUE THREAD

**Issue by foxmask** [wallabag/wallabag#3528]
### Issue details

now that we have to confirm each deletion, it becomes hard to delete 100 articles one by one :(

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3

### Feature request:

possibility to select as many as article we want and then select the appropriate action, deletion, adding a tag, removing a tag , etc

**Comment by nicosomb** [comment]
Your issue is a duplicate of https://github.com/wallabag/wallabag/issues/3118
