### ISSUE TITLE
Added link is different than the original one

### ISSUE THREAD

**Issue by mdirik** [wallabag/wallabag#3529]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Content fetching alters the link user added thus the source address stored in reading list may end up being completely different than what did the user originally intended.

For example:
* Add https://www.reddit.com/r/linux/comments/7lgnho/llvm_501_release/ to Wallabag
* http://lists.llvm.org/pipermail/llvm-announce/2017-December/000076.html gets added instead

fetched content is content of the article posted to reddit (in other words not the comments page the user submitted to Wallabag). This may or may not be the desirable outcome for fetched text but I don't want to discuss this as this is not the real issue here.

I think the real issue here is that the original link the user has submitted is lost, even if the user clicks the original link he'll go to the content page instead of reddit discussion page.

I checked that link in https://f43.me/feed/test and the result is same. I don't know if this is the intended behavior of the fetcher or a bug, but I think it is another issue which should not distract from this one. 

I think that the original link submitted by the user should not be changed under any circumstances regardless of what result comes from fetching.

Thanks

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? Package
* Last wallabag version that did not exhibit the issue (if applicable): not checked
* php version: 5.6.30
* OS: Debian 8.0
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

provided above

**Comment by mdirik** [comment]
As a hacky workaround, after deleting this line:

``$entry->setUrl($content['url'] ?: $url);``

in ``src/Wallabag/CoreBundle/Helper/ContentProxy.php`` , original link in Wallabag points to Reddit comments page as I expected and fetched content text is content of llvm.org page.

**Comment by Kdecherf** [comment]
Hello @mdirik,
It's not fully a bug as this behavior is defined by the site-config of reddit.com: https://github.com/j0k3r/graby-site-config/blob/master/reddit.com.txt#L16-L17

However, could you upgrade to 2.3 and replace the line of your workaround with this please? 

``` php
$entry->setOriginUrl($content['url']);
```

**Comment by mdirik** [comment]
Hi, thanks for your answer


I did a dev install of 2.3.0 here is the result:

Unmodified:

Link points to llvm.org, content text is from llvm.org

Then replaced ``$entry->setUrl($content['url']);`` with ``$entry->setOriginUrl($content['url']);``

Now link points to reddit.com and content text is from llvm.org

**Comment by Kdecherf** [comment]
Can you confirm that the llvm link has been set as the originUrl attribute
(can be seen in the attributes header with date, author and entry link)?

Sent from my phone

**Comment by mdirik** [comment]
I'm not sure I've understood you correctly but here is where some links point to:

unmodified:

* original article link: llvm.org
* links inside content: llvm.org

modified:

* original article link: reddit.com
* links inside content: llvm.org

Added before modification:

![unmodified](https://user-images.githubusercontent.com/1767147/34329930-50049f60-e924-11e7-9e61-3e713f71684b.png)

![unmodified-2](https://user-images.githubusercontent.com/1767147/34329931-582ea014-e924-11e7-8aae-e4e76d4cefd6.png)

Added after modification:

![modified](https://user-images.githubusercontent.com/1767147/34329933-63610fbc-e924-11e7-8a12-43786c1332d8.png)

![modified-2](https://user-images.githubusercontent.com/1767147/34329935-6af7cf86-e924-11e7-9d53-499dd64b506a.png)

**Comment by nicosomb** [comment]
I can confirm this behavior on wallabag.it.
