### ISSUE TITLE
Incorrect string value: '\\xF0\\x9F\\x98\\x89</...' for column 'content'

### ISSUE THREAD

**Issue by webracer999** [wallabag/wallabag#3530]
### Issue details

I've getting an `Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException` error when fetching https://strato.de/blog/interview-debitor/

`Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x89</...' for column 'content' at row 1 at /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x89</...' for column 'content' at row 1 at /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []`

prod.log: https://gist.github.com/webracer999/03375bc68023951dbcd9be43526f15a0

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.0
* How did you install wallabag? by downloading the package
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version: 7.0.22
* OS: Ubuntu 16.04.3 LTS
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Just try to add article https://strato.de/blog/interview-debitor/

**Comment by nicosomb** [comment]
Hello @webracer999 
How did you configured your wallabag instance: what is the value of `database_charset`? It should be `utf8mb4` for MySQL.

**Comment by webracer999** [comment]
Hello @nicosomb 

it was set to `utf8`. I think, this was a default value, I don't remember, that I've explicitly set this value. 

I've changed it, like you wrote, to `uft8mb4`.

Now it works fine! I think the error was caused by a Unicode-smiley.

Thank you very much for your fast help!

**Comment by Cauen** [comment]
If nothing works in mysql shell, try to change some settings in mysqld.cnf

    [mysqld]
    character-set-client-handshake = FALSE
    character-set-server = utf8mb4

Original answer https://stackoverflow.com/questions/35125933/mysql-utf8mb4-errors-when-saving-emojis
Credits to: user3624198

**Comment by virtadpt** [comment]
The same thing happened on another application I use.  That should fix it.
