### ISSUE TITLE
Habrahabr.ru site config

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#3531]
Hi all! 
Habrahabr is a very popular IT community site, and I found that if the comment section after the article becomes bigger then the article itself, wallabag don't get the article, only the comments. I just founs that most part of my saved articles from habrahabr is just a comments :disappointed:  
Example of such article: https://habrahabr.ru/post/345270/
~~I can make the siteconfig myself if somebody tells me how-to.~~ 
~~Found howto, will make siteconfig soon.~~
created https://github.com/fivefilters/ftr-site-config/pull/381
Could somebody apply this to wallabag.it?

**Comment by j0k3r** [comment]
This will be available in the next release. Thanks!
