### ISSUE TITLE
Can not add Website to wallabag

### ISSUE THREAD

**Issue by xiongzi** [wallabag/wallabag#3535]
### Issue details

There are an insert error (mysql) if I try to add following url to wallabag (version 2.3.1): http://www.area51-tutorials.de/inkscape-093-draw-with-brushes-pinsel/

500: Internal Server Error
An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, is_archived, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, origin_url, user_id) VALUES (?,
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.1
* How did you install wallabag? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.0.22-0ubuntu0.16.04.1
* OS:Ubuntu 16.04.3 LTS
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL 5.7.20

### Steps to reproduce/test case

Everytime when I try to add this url

**Comment by xiongzi** [comment]
Full error message is:

500: Internal Server Error
An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, is_archived, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, origin_url, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "Inkscape 093 \u2013 Draw with Brushes, Pinsel", "http:\/\/www.area51-tutorials.de\/inkscape-093-draw-with-brushes-pinsel\/", 0, 0, "<p class=\"post-byline\">von \u00b7 Ver\u00f6ffentlicht \u00b7 Aktualisiert <\/p><div class=\"entry themeform\"><div class=\"entry-inner\"><p>Englische Titel sind oft k\u00fcrzer und knackiger. Zumal: Inkscape Bruhes sind das Thema in diesem Tutorial. Wir legen uns Pinsel an und zeichnen los. Kurz und knackig wie der Titel, ist auch die Arbeit damit.<\/p><p>Bisher habe ich das Pfad- und Freihandlienen-Werkzeug nur in Verbindung mit Dreieckformen am Anfang oder Ende genutzt. Das ist schon cool. Aber es geht <strong>noch cooler<\/strong>, zumindest noch vielseitiger, finde ich. Mann kann n\u00e4mlich mit Objekten aus der Zwischenablage zeichnen bzw. diese als Linienstil nutzen.<\/p><div id=\"attachment_10885\" class=\"wp-caption aligncenter c1\"><img class=\"size-full wp-image-10885\" src=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brushes_title.png\" alt=\"Hier habe ich Brushes verwendet\" width=\"520\" height=\"245\" srcset=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brushes_title.png 520w, http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brushes_title-300x141.png 300w, http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brushes_title-720x340.png 720w\" \/><p class=\"wp-caption-text\">Hier habe ich Brushes verwendet<\/p><\/div><p>Ich habe mir dazu verschiedene kleine Formen erstellt, die ich mir wie immer links, au\u00dferhalb der Arbeitsfl\u00e4che bereit lege. Solche Formen k\u00f6nnen Grundformen, oder\u00a0 frei gezeichnete Objekte sein. Wichtig ist: Sie m\u00fcssen in Pfade konvertiert worden sein (siehe Bild unten).<\/p><div id=\"attachment_10791\" class=\"wp-caption aligncenter c3\"><img class=\"size-full wp-image-10791\" src=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_002.jpg\" alt=\"Brushes verschiedener Gr\u00f6\u00dfe und Machart\" width=\"401\" height=\"226\" srcset=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_002.jpg 401w, http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_002-300x169.jpg 300w\" \/><p class=\"wp-caption-text\">Brushes verschiedener Gr\u00f6\u00dfe und Machart<\/p><\/div><p>Einfaches Beispiel: Man erstelle ein Quadrat und konvertiere es \u00fcber <strong>Pfad \u2013 Objekt in Pfad umwandeln<\/strong>. Das Objekt wird anschlie\u00dfend mit <strong>STRG-C<\/strong> in die Zwischenablage geladen. Dann w\u00e4hlt man das Freihandlienen-Werkzeug und zeichnet damit eine geschwungene Linie. Meine Einstellungen f\u00fcr das Werkzeug und das Ergebnis k\u00f6nnt ihr im Bild unten sehen (siehe Bild unten).<\/p><div id=\"attachment_10790\" class=\"wp-caption aligncenter c4\"><img class=\"size-full wp-image-10790\" src=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_001.gif\" alt=\"Quadrat (links) als Pinselspitze bzw. Brush\" width=\"467\" height=\"209\" \/><p class=\"wp-caption-text\">Quadrat (links) als Pinselspitze bzw. Brush<\/p><\/div><p>Es ist auch m\u00f6glich einen Brush aus mehreren Elementen zusammenzusetzen. In diesem Fall muss man alle Zeichenelemente \u00fcber <strong>Pfad \u2013 Verbinden<\/strong> zu einem Objekt verschmelzen (siehe Bild unten).<\/p><div id=\"attachment_10793\" class=\"wp-caption aligncenter c5\"><img class=\"size-full wp-image-10793\" src=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_003.jpg\" alt=\"Zusammengesetzte Brushes\" width=\"500\" height=\"184\" srcset=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_003.jpg 500w, http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_003-300x110.jpg 300w\" \/><p class=\"wp-caption-text\">Zusammengesetzte Brushes<\/p><\/div><p>Andere Formen und Beispiele:<\/p><div id=\"attachment_10795\" class=\"wp-caption aligncenter c6\"><img class=\"size-full wp-image-10795\" src=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_004.jpg\" alt=\"Verschiedene Experimente mit Brushes-Formen\" width=\"450\" height=\"521\" srcset=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_004.jpg 450w, http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_004-259x300.jpg 259w\" \/><p class=\"wp-caption-text\">Verschiedene Experimente mit Brushes-Formen<\/p><\/div><h4>Weitere Tips:<\/h4><ul><li>Die Muster aus der Zwischenablage k\u00f6nnen vom Freihandlinien- und Pfadwerkeug genutzt werden.<\/li>\n<li>Beim zeichnen von Kurven darauf achten, dass die Kurve nicht kleiner ist als der Durchmesser des Pinsel.<\/li>\n<li>Die Strichst\u00e4rke ist bei dieser Technik immer die Gr\u00f6\u00dfe des Brush! Ausprobieren und Brush ggf. kleiner bzw. gr\u00f6\u00dfer skalieren.<\/li>\n<li>In den F\u00fclloptionen \u201cVollst\u00e4ndiges F\u00fcllen\u201d aktivieren. Es sei denn man w\u00fcnscht L\u00fccken bei der \u00dcberlagerung von Linien.<\/li>\n<li>Die so erzeugten Formen k\u00f6nnen mit einer Kontur versehen werden.<\/li>\n<li>Eignet sich ein Brush nicht f\u00fcr kurze oder enge Formen, kann er f\u00fcr l\u00e4ngere Strecken besser geeignet sein \u2013 und umgekehrt. Nicht gleich wegwerfen \ud83d\ude09<\/li>\n<\/ul><p>Mit dieser Technik kann man enorm viel Spa\u00df haben. Mit Brushes zu arbeiten hat endloses Potential.<\/p><p>Gutes Gelingen!<\/p><\/div><\/div>", "2017-12-27 21:26:36", "2017-12-27 21:26:36", null, "a:1:{i:0;s:4:\"dash\";}", null, "text\/html", "de_DE", 1, "www.area51-tutorials.de", null, 200, "N;", null, 1]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x89</...' for column 'content' at row 1

**Comment by xiongzi** [comment]
`500: Internal Server Error
An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, is_archived, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, origin_url, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "Inkscape 093 \u2013 Draw with Brushes, Pinsel", "http:\/\/www.area51-tutorials.de\/inkscape-093-draw-with-brushes-pinsel\/", 0, 0, "<p class=\"post-byline\">von \u00b7 Ver\u00f6ffentlicht \u00b7 Aktualisiert <\/p><div class=\"entry themeform\"><div class=\"entry-inner\"><p>Englische Titel sind oft k\u00fcrzer und knackiger. Zumal: Inkscape Bruhes sind das Thema in diesem Tutorial. Wir legen uns Pinsel an und zeichnen los. Kurz und knackig wie der Titel, ist auch die Arbeit damit.<\/p><p>Bisher habe ich das Pfad- und Freihandlienen-Werkzeug nur in Verbindung mit Dreieckformen am Anfang oder Ende genutzt. Das ist schon cool. Aber es geht <strong>noch cooler<\/strong>, zumindest noch vielseitiger, finde ich. Mann kann n\u00e4mlich mit Objekten aus der Zwischenablage zeichnen bzw. diese als Linienstil nutzen.<\/p><div id=\"attachment_10885\" class=\"wp-caption aligncenter c1\"><img class=\"size-full wp-image-10885\" src=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brushes_title.png\" alt=\"Hier habe ich Brushes verwendet\" width=\"520\" height=\"245\" srcset=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brushes_title.png 520w, http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brushes_title-300x141.png 300w, http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brushes_title-720x340.png 720w\" \/><p class=\"wp-caption-text\">Hier habe ich Brushes verwendet<\/p><\/div><p>Ich habe mir dazu verschiedene kleine Formen erstellt, die ich mir wie immer links, au\u00dferhalb der Arbeitsfl\u00e4che bereit lege. Solche Formen k\u00f6nnen Grundformen, oder\u00a0 frei gezeichnete Objekte sein. Wichtig ist: Sie m\u00fcssen in Pfade konvertiert worden sein (siehe Bild unten).<\/p><div id=\"attachment_10791\" class=\"wp-caption aligncenter c3\"><img class=\"size-full wp-image-10791\" src=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_002.jpg\" alt=\"Brushes verschiedener Gr\u00f6\u00dfe und Machart\" width=\"401\" height=\"226\" srcset=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_002.jpg 401w, http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_002-300x169.jpg 300w\" \/><p class=\"wp-caption-text\">Brushes verschiedener Gr\u00f6\u00dfe und Machart<\/p><\/div><p>Einfaches Beispiel: Man erstelle ein Quadrat und konvertiere es \u00fcber <strong>Pfad \u2013 Objekt in Pfad umwandeln<\/strong>. Das Objekt wird anschlie\u00dfend mit <strong>STRG-C<\/strong> in die Zwischenablage geladen. Dann w\u00e4hlt man das Freihandlienen-Werkzeug und zeichnet damit eine geschwungene Linie. Meine Einstellungen f\u00fcr das Werkzeug und das Ergebnis k\u00f6nnt ihr im Bild unten sehen (siehe Bild unten).<\/p><div id=\"attachment_10790\" class=\"wp-caption aligncenter c4\"><img class=\"size-full wp-image-10790\" src=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_001.gif\" alt=\"Quadrat (links) als Pinselspitze bzw. Brush\" width=\"467\" height=\"209\" \/><p class=\"wp-caption-text\">Quadrat (links) als Pinselspitze bzw. Brush<\/p><\/div><p>Es ist auch m\u00f6glich einen Brush aus mehreren Elementen zusammenzusetzen. In diesem Fall muss man alle Zeichenelemente \u00fcber <strong>Pfad \u2013 Verbinden<\/strong> zu einem Objekt verschmelzen (siehe Bild unten).<\/p><div id=\"attachment_10793\" class=\"wp-caption aligncenter c5\"><img class=\"size-full wp-image-10793\" src=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_003.jpg\" alt=\"Zusammengesetzte Brushes\" width=\"500\" height=\"184\" srcset=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_003.jpg 500w, http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_003-300x110.jpg 300w\" \/><p class=\"wp-caption-text\">Zusammengesetzte Brushes<\/p><\/div><p>Andere Formen und Beispiele:<\/p><div id=\"attachment_10795\" class=\"wp-caption aligncenter c6\"><img class=\"size-full wp-image-10795\" src=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_004.jpg\" alt=\"Verschiedene Experimente mit Brushes-Formen\" width=\"450\" height=\"521\" srcset=\"http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_004.jpg 450w, http:\/\/www.area51-tutorials.de\/wp-content\/uploads\/2016\/11\/inkscape_brush_004-259x300.jpg 259w\" \/><p class=\"wp-caption-text\">Verschiedene Experimente mit Brushes-Formen<\/p><\/div><h4>Weitere Tips:<\/h4><ul><li>Die Muster aus der Zwischenablage k\u00f6nnen vom Freihandlinien- und Pfadwerkeug genutzt werden.<\/li>\n<li>Beim zeichnen von Kurven darauf achten, dass die Kurve nicht kleiner ist als der Durchmesser des Pinsel.<\/li>\n<li>Die Strichst\u00e4rke ist bei dieser Technik immer die Gr\u00f6\u00dfe des Brush! Ausprobieren und Brush ggf. kleiner bzw. gr\u00f6\u00dfer skalieren.<\/li>\n<li>In den F\u00fclloptionen \u201cVollst\u00e4ndiges F\u00fcllen\u201d aktivieren. Es sei denn man w\u00fcnscht L\u00fccken bei der \u00dcberlagerung von Linien.<\/li>\n<li>Die so erzeugten Formen k\u00f6nnen mit einer Kontur versehen werden.<\/li>\n<li>Eignet sich ein Brush nicht f\u00fcr kurze oder enge Formen, kann er f\u00fcr l\u00e4ngere Strecken besser geeignet sein \u2013 und umgekehrt. Nicht gleich wegwerfen \ud83d\ude09<\/li>\n<\/ul><p>Mit dieser Technik kann man enorm viel Spa\u00df haben. Mit Brushes zu arbeiten hat endloses Potential.<\/p><p>Gutes Gelingen!<\/p><\/div><\/div>", "2017-12-27 21:26:36", "2017-12-27 21:26:36", null, "a:1:{i:0;s:4:\"dash\";}", null, "text\/html", "de_DE", 1, "www.area51-tutorials.de", null, 200, "N;", null, 1]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x89</...' for column 'content' at row 1`

**Comment by nicosomb** [comment]
Hello @xiongzi 

I think that the value of `database_charset` in `app/config/parameters.yml` is defined to `utf8` but it should be defined to `utf8mb4`. Please replace it, then clear your cache (remove all files in `var/cache/` of your wallabag instance).

**Comment by xiongzi** [comment]
This fixed the problem.

Thank you!
