### ISSUE TITLE
PHP Fatal Error on update from 2.2.3

### ISSUE THREAD

**Issue by nakinigit** [wallabag/wallabag#3544]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to https://community.wallabag.org/ (forum) or http://gitter.im/wallabag/wallabag (chat).

I run 'make update'. Things seem to run smoothly until the end, I see this error:
`PHP Fatal error:  Interface 'Psr\Cache\CacheItemPoolInterface' not found in /home/naknight/Data/webpages/wallabag/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/Ad  
  apterInterface.php on line 23`

Same error if I run: bin/console cache:clear -e=prod

So then I restore my database & the wallabag folders from the last good installation (2.2.3) and all I get is a blank log on page.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.1
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 2.2.3
* php version:  5.6.32
* OS: Linux Mint 17.3
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
