### ISSUE TITLE
Links in HEAD the 2.3.1 Docker image are wrong

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#3545]
### Issue details

Just tried the Docker contener 2.3.1 in place of the 2.3.0 and Got no CSS at all.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.1
* How did you install wallabag? Via `git clone` or by downloading the package? Docker
* Last wallabag version that did not exhibit the issue (if applicable): 2.3.1
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

In the 2.3.0 contener, links in the HEAD have this pattern:

```
href='/wallabagassets/...'
```

This works. But in the 2.3.1 contener, links in the HEAD have this pattern:

```
href='https://your-wallabag-url-instance.com/...'
```

This is obviously wrong.

**Comment by Yamakuni** [comment]
+1 I've the same issue

![screen shot 2017-12-31 at 12 36 34](https://user-images.githubusercontent.com/10231985/34461357-a0762394-ee27-11e7-8994-d4a071615259.png)

**Comment by Yamakuni** [comment]
+1 I've the same issue

![screen shot 2017-12-31 at 12 36 34](https://user-images.githubusercontent.com/10231985/34461361-bac1fd04-ee27-11e7-8df5-b29a09801c51.png)

**Comment by Kdecherf** [comment]
Wallabag 2.3.1 now depends on `domain_name` parameter for wallassets path, please check that you are setting `SYMFONY__ENV__DOMAIN_NAME` when starting your Docker container

**Comment by Yamakuni** [comment]
Thanks @Kdecherf 
It's works for me!

**Comment by romu70** [comment]
Same for me. I close the ticket.
