### ISSUE TITLE
Fresh installation of Wallabag 2.3.1 has no themes or styles

### ISSUE THREAD

**Issue by jerrywaller** [wallabag/wallabag#3547]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

After cloning, and a successful installation after `make install`, Wallabag 2.3.1 loads without styles. 

![screen shot 2018-01-03 at 13 05 06](https://user-images.githubusercontent.com/3990374/34533123-d2400cc6-f086-11e7-966d-bf3b3896a5b2.png)

### Environment

* wallabag version (or git revision) that exhibits the issue: `2.3.1`
* How did you install wallabag?  `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): **n/a**
* php version: `5.6.30-0+deb8u1`
* OS: `Raspbian 8 [armhf]`
* type of hosting (shared or dedicated): `dedicated`
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): `MySQL`

### Steps to reproduce/test case

I have changed ownership of the wallabag folder and subfolders to www-data, and have confirmed this ownership via `ls -al`. There are no composer errors, and `sudo -u www-data git status` returns

```
HEAD detached at 2.3.1
nothing to commit, working directory clean
```

I've tried accessing the site in Safari 11.0.2, Firefox 57.0.3 (MacOS High Sierra and Windows 10), and Google Chrome 63.0.3239.108 (64 bit, Windows 10). None of them render any styles.

Executing `sudo -u www-data bin/console assets:install -e=prod` produces the following:

```
Installing assets as hard copies.

 --- ------------------------------ ----------------
      Bundle                         Method / Error
 --- ------------------------------ ----------------
  ✔   NelmioApiDocBundle             copy
  ✔   WhiteOctoberPagerfantaBundle   copy
  ✔   FOSJsRoutingBundle             copy
 --- ------------------------------ ----------------

 ! [NOTE] Some assets were installed via copy. If you make changes to these assets you have to run this command again.


 [OK] All assets were successfully installed.
```

Issuing the command `sudo -u www-data bin/console cache:clear -e prod` results in:

```
// Clearing the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
```

Additionally, I have:

- restarted Apache
- rebooted the Raspberry Pi

But styles still fail to load.

**Comment by noja11** [comment]
I also have this issue.  running it on docker through unRAID.

**Comment by noja11** [comment]
FIXED! Sorry, I just noticed that the dev tools on chrome was showing a bunch of errors: 

Failed to load resource: net::ERR_NAME_NOT_RESOLVED .... your-wallabag-url-instance...e-touchicon 72.png 

etc etc for all the UI elements.  

So I went back and added the environment variable for -e SYMFONY__ENV__DOMAIN_NAME= and pointed it at my url.  Bingo! Got the full version.

Not sure if that means that wallabag install is just forcing all UI elements through that example domain name, but resetting that variable solved it for me.

**Comment by jerrywaller** [comment]
@noja11 Ah hah! That helps. I'm not using Docker, but I did what you did with dev tools and took a closer look at the resources in Chrome. Sure enough, the urls for the images and styles were missing part of the path. I edited the `app/config/parameters.yml` file and changed 
```
domain_name: 'https://mydomain.org/wallabag'
```
to
```
domain_name: 'https://mydomain.org/wallabag/web'
```
After clearing the cache (as referenced in my first post above) I now have proper styles and themes. This still feels more like a workaround than, but hey... it works, and perhaps this can help others troubleshooting their own issues.

**Comment by noja11** [comment]
Yeah, I tried editing the parameters file first as well, but I think something in my instance wouldn't let the changes save.  Every time I restarted the container, it just went back to the original version.  In any case, glad it helped!

**Comment by Kdecherf** [comment]
@noja11 Indeed, a change was introduced in 2.3.1 to fix an issue with assets in subfolders. Setting `domain_name` (or `SYMFONY__ENV__DOMAIN_NAME` for Docker installations) to the real address of your wallabag installation is now mandatory for assets to load successfully.

**Comment by silberzwiebel** [comment]
A note for anyone stumbling over this issue: You also need to add the port to the domain name, if you set a non-default port on the web-server side -- at least this worked for me to see the theme.

**Comment by fotastisch** [comment]
Hi!
It seems I'm having the same problem, but adding /web and port did not change anything for me, even after clearing the cache. Is there anything else I can do or test?

**Comment by dnk8n** [comment]
My solution was:

`docker run -p 80:80 -e SYMFONY__ENV__DOMAIN_NAME=http://localhost wallabag/wallabag`

since I was running it at localhost, port 80 (http)

**Comment by dixonge** [comment]
You also need to clear the internal app cache - running ```make update``` from the command line will do this if you can't find the right place in the unstyled web page.

**Comment by sfkpmr** [comment]
Can someone dumb down this solution for me?

I've tried this many many times, but I can't seem to change the DOMAIN NAME variable. It always comes back as "your wallabag url".

That's when I have it running, mostly done with Portainer, because when I run "docker run -p 80:80 -e SYMFONY__ENV__DOMAIN_NAME=http://localhost wallabag/wallabag" directly, I end up with a "[WARNING]: Found both group and host with same name: localhost" error.

**Comment by kloki4ever** [comment]
I've also run into this problem running wallabag docker on Synology NAS. I have solved it by setting the 
SYMFONY__ENV__DOMAIN_NAME to exact URL to reach my NAS from the internet (i.e. **external** URL). You need to specify http or https and also port, if you use port forwarding on your router. No special directory name was required in my case. So it would be something like:
`SYMFONY__ENV__DOMAIN_NAME =https://mysubdomain.ddnsprovider.me:9998`

**Some other hints related to Synology specifics:**
Wallabag docker runs with http on container's port 80. When setting up the docker you must specify the local (where Synology NAS will listen for wallabag connections) port (e.g. 32999) which will be connected to Docker container's port 80. If you leave the port on "Auto", it will be different every time you start the docker, which will not work.
If you want to use https then configure a "Reverse proxy" on Synology via "Control Panel/Application Portal/Reverse Proxy" with SOURCE: Protocol="HTTPS", Hostname="*", Port="9998" and DESTINATION: Protocol="HTTP",Hostname="localhost" and Port="32999".
On your router you will need to set port forwarding for incoming port 9998 to your private synology IP address and destination port 32999.

**Comment by kloki4ever** [comment]
Adding more notes after researching additional problems I got after more testing and had to edit post above. I am using it on Synology NAS with reverse proxy from public HTTPS to HTTP (HSTS enabled). This was somehow not working properly upon signing into wallabag (nginx http to https connection error), so I had to correct the nginx configuration inside the docker.

`docker   exec -it wallabag sh
vi   /etc/nginx/nginx.conf`
add   "`ssl off;`" and "`listen 80;`" to `server { ... }` part

Then it started to work properly all the time.
After trying wallabag with several webs, I am quite disappointed, since it gets fooled by crappy "Cookie acceptance" windows and similar stuff. Not much of the page is saved...

**Comment by el3ctron** [comment]
i solved, editing the file ../wallabag/var/cache/prod/appProdProjectContainer.php

the error was in that file appears a wrong url, in my case http://localhost/bookmarks/ an the real one is https://mydomain.com/bookmarks/ (another domain, and in my case with https couse i already configured) so, i replace the five times that the wrong url appears, reload my navigator and voilá!

**Comment by tandy-1000** [comment]
I am also having this issue on a manual local installation.

**Comment by Kdecherf** [comment]
This issue had no update in the past year, closing it

**Comment by w316525096** [comment]
> A note for anyone stumbling over this issue: You also need to add the port to the domain name, if you set a non-default port on the web-server side -- at least this worked for me to see the theme.

wokred for me.
like this: ``- SYMFONY__ENV__DOMAIN_NAME=http://192.168.1.235:8001``
may be need ``docker-compose up -d``

**Comment by qqpdb** [comment]
When testing locally: `SYMFONY__ENV__DOMAIN_NAME=http://192.168.0.34:8008` worked for me. 
When I changed to my domain I had to remove the port at the end and then it worked: `SYMFONY__ENV__DOMAIN_NAME=https://subdomain.domain.com`
