### ISSUE TITLE
Impossible to fetch articles from korben.info

### ISSUE THREAD

**Issue by Aeinot** [wallabag/wallabag#3549]
### Issue details
When an article from korben.info is added, the content is empty and the title is "You are being redirected...". 
The same behavior can be observed with Pocket.

### Environment
wallabag 2.3.0 on wallabag.it

### Steps to reproduce/test case

Import an article from korben.info

**Comment by j0k3r** [comment]
It's a known issue https://github.com/fivefilters/ftr-site-config/pull/379

**Comment by techexo** [comment]
@j0k3r As https://github.com/fivefilters/ftr-site-config/pull/379 has been closed/merged, this should probably be closed too?
