### ISSUE TITLE
no theme after  update 2.30 -> 2.31

### ISSUE THREAD

**Issue by palouf34** [wallabag/wallabag#3550]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

After update 2.30 to 2.31 I obtain this  screen see the other issues 

[https://github.com/wallabag/wallabag/issues/3547](url)
Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to https://community.wallabag.org/ (forum) or http://gitter.im/wallabag/wallabag (chat).

### Environment

* wallabag version (or git revision) that exhibits the issue:
* How did you install wallabag? Via `git clone` 
* Last wallabag version that did not exhibit the issue (if applicable): 2.30
* php version: 7.0
* OS: Debian 9
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB
### Steps to reproduce/test case

Steps to reproduce/test case

I have changed ownership of the wallabag folder and subfolders to www-data, and have confirmed this ownership via `ls -al`. There are no composer errors, and sudo -u www-data git status returns

```
HEAD detached at 2.3.1
nothing to commit, working directory clean
```

I've tried accessing the site in Safari 11.0.2, Firefox, google Chrome (MacOS  Sierra and Windows 10). None of them render any styles.

Executing `sudo -u www-data bin/console assets:install -e=prod` produces the following:

```
Installing assets as hard copies.

 --- ------------------------------ ----------------
      Bundle                         Method / Error
 --- ------------------------------ ----------------
  ✔   NelmioApiDocBundle             copy
  ✔   WhiteOctoberPagerfantaBundle   copy
  ✔   FOSJsRoutingBundle             copy
 --- ------------------------------ ----------------

 ! [NOTE] Some assets were installed via copy. If you make changes to these assets you have to run this command again.

 [OK] All assets were successfully installed.
```
Issuing the command `sudo -u www-data bin/console cache:clear -e prod` results in:

```
// Clearing the cache for the prod environment with debug false

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
```

this my prod.log:

```
2018-01-04 19:01:30] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"Wallabag\\CoreBundle\\Controller\\EntryController::showUnreadAction","page":1,"_route":"homepage"},"request_uri":"https://bags.domain.fr/","method":"GET"} []
[2018-01-04 19:01:31] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2018-01-04 19:01:31] security.DEBUG: User was reloaded from a user provider. {"username":"christr87","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-01-04 19:01:32] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2018-01-04 19:01:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/bundles/fosjsrouting/js/router.js" (from "https://bags.domain.fr/")" at /media/data/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/bundles/fosjsrouting/js/router.js\" (from \"https://bags.domain.fr/\") at /media/data/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /media/data/web/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []
[2018-01-04 19:01:32] request.INFO: Matched route "fos_js_routing_js". {"route":"fos_js_routing_js","route_parameters":{"_controller":"fos_js_routing.controller:indexAction","_format":"js","_route":"fos_js_routing_js"},"request_uri":"https://bags.domain.fr/js/routing?callback=fos.Router.setData","method":"GET"} []
[2018-01-04 19:01:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/wallassets/material.css" (from "https://bags.domain.fr/")" at /media/data/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/wallassets/material.css\" (from \"https://bags.domain.fr/\") at /media/data/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /media/data/web/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []
[2018-01-04 19:01:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/wallassets/material.js" (from "https://bags.domain.fr/")" at /media/data/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/wallassets/material.js\" (from \"https://bags.domain.fr/\") at /media/data/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /media/data/web/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []
[2018-01-04 19:01:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/wallassets/themes/_global/img/logo-square.png" (from "https://bags.domain.fr/")" at /media/data/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/wallassets/themes/_global/img/logo-square.png\" (from \"https://bags.domain.fr/\") at /media/data/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /media/data/web/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []
[2018-01-04 19:01:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/wallassets/material.js" (from "https://bags.domain.fr/")" at /media/data/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/wallassets/material.js\" (from \"https://bags.domain.fr/\") at /media/data/web/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /media/data/web/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []
```

I replace  my real TLD 

Additionally, I have:

restarted nginx
But styles still fail to load.

**Comment by Kdecherf** [comment]
Hello @palouf34,

Please check that you correctly set `domain_name` in `parameters.yml` to the real domain of your wallabag installation. Don't forget to clear the cache if you edit this file.

**Comment by palouf34** [comment]
my  nginx web site file conf:

```
server {
    listen 443;
    server_name bags.domain.fr;
    root /var/www/wallabag/web;

    ssl_certificate /etc/letsencrypt/live/www.domain.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.domain.fr/privkey.pem;
    include /etc/nginx/conf.d/ciphers.conf;

    # add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;

    location / {
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
    location ~ ^/app\.php(/|$) {
        # Si vous utilisez PHP 5 remplacez
        # /run/php/php7.0 par /var/run/php5
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        # When you are using symlinks to link the document root to the
        # current version of your application, you should pass the real
        # application path instead of the path to the symlink to PHP
        # FPM.
        # Otherwise, PHP's OPcache may not properly detect changes to
        # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
        # for more information).
        fastcgi_param  SCRIPT_FILENAME  $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        # Prevents URIs that include the front controller. This will 404:
        # http://domain.tld/app.php/some-path
        # Remove the internal directive to allow URIs like this internal;
    }

    # return 404 for all other php files not matching the front controller
    # this prevents access to other php files you don't want to be accessible.
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/wallabag_error.log;
    access_log /var/log/nginx/wallabag_access.log;
```

my pamaters.yml


```
 This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: wallabag
    database_password: password
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://bags.domain.fr/web'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: password
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    database_driver_class: null
```

I'm put '/web' after my 'domain_name' parameter

**Comment by Kdecherf** [comment]
Can you provide a screenshot of the network tab of your browser when you see this issue please?

**Comment by palouf34** [comment]
tab network:

![2018-01-05_083258](https://user-images.githubusercontent.com/16334914/34599597-844c7e46-f1f3-11e7-8d8e-9c1fd5ae0bb7.JPG)

tab console:

![2018-01-05_083324](https://user-images.githubusercontent.com/16334914/34599604-885ff972-f1f3-11e7-96fb-b0dd9f86d621.JPG)

**Comment by Kdecherf** [comment]
You must remove the '/web' part on `domain_name`

**Comment by palouf34** [comment]
I modify this parameter and restart nginx, but not change this problem.
I'm go out  and login in

if you want chrome make this message on source tab and stop, when run  the menu  ok but this message is always on this source tab.

`/**/fos.Router.setData({"base_url":"","routes":{"import_chrome":{"tokens":[["text","\/import\/chrome"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"import_firefox":{"tokens":[["text","\/import\/firefox"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"import":{"tokens":[["text","\/import\/"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"import_instapaper":{"tokens":[["text","\/import\/instapaper"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"import_pinboard":{"tokens":[["text","\/import\/pinboard"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"import_pocket":{"tokens":[["text","\/import\/pocket"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"import_pocket_auth":{"tokens":[["text","\/import\/pocket\/auth"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"import_pocket_callback":{"tokens":[["text","\/import\/pocket\/callback"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"import_readability":{"tokens":[["text","\/import\/readability"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"import_wallabag_v1":{"tokens":[["text","\/import\/wallabag-v1"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"import_wallabag_v2":{"tokens":[["text","\/import\/wallabag-v2"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"user_new":{"tokens":[["text","\/users\/new"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":["GET","POST"],"schemes":[]},"developer":{"tokens":[["text","\/developer"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"developer_create_client":{"tokens":[["text","\/developer\/client\/create"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"developer_delete_client":{"tokens":[["variable","\/","\\d+","id"],["text","\/developer\/client\/delete"]],"defaults":[],"requirements":{"id":"\\d+"},"hosttokens":[],"methods":[],"schemes":[]},"developer_howto_firstapp":{"tokens":[["text","\/developer\/howto\/first-app"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"config":{"tokens":[["text","\/config"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"delete_tagging_rule":{"tokens":[["variable","\/","\\d+","id"],["text","\/tagging-rule\/delete"]],"defaults":[],"requirements":{"id":"\\d+"},"hosttokens":[],"methods":[],"schemes":[]},"edit_tagging_rule":{"tokens":[["variable","\/","\\d+","id"],["text","\/tagging-rule\/edit"]],"defaults":[],"requirements":{"id":"\\d+"},"hosttokens":[],"methods":[],"schemes":[]},"config_reset":{"tokens":[["variable","\/","[^\/]++","type"],["text","\/reset"]],"defaults":[],"requirements":{"id":"annotations|tags|entries"},"hosttokens":[],"methods":[],"schemes":[]},"new_entry":{"tokens":[["text","\/new-entry"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"new":{"tokens":[["text","\/new"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"all":{"tokens":[["variable","\/","[^\/]++","page"],["text","\/all\/list"]],"defaults":{"page":"1"},"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"archive":{"tokens":[["variable","\/","[^\/]++","page"],["text","\/archive\/list"]],"defaults":{"page":"1"},"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"starred":{"tokens":[["variable","\/","[^\/]++","page"],["text","\/starred\/list"]],"defaults":{"page":"1"},"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"archive_entry":{"tokens":[["variable","\/","\\d+","id"],["text","\/archive"]],"defaults":[],"requirements":{"id":"\\d+"},"hosttokens":[],"methods":[],"schemes":[]},"untagged":{"tokens":[["variable","\/","[^\/]++","page"],["text","\/untagged\/list"]],"defaults":{"page":"1"},"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"archive_rss":{"tokens":[["text","\/archive.xml"],["variable","\/","[^\/]++","token"],["variable","\/","[^\/]++","username"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"starred_rss":{"tokens":[["text","\/starred.xml"],["variable","\/","[^\/]++","token"],["variable","\/","[^\/]++","username"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"all_rss":{"tokens":[["text","\/all.xml"],["variable","\/","[^\/]++","token"],["variable","\/","[^\/]++","username"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"tag_rss":{"tokens":[["text",".xml"],["variable","\/","[^\/\\.]++","slug"],["text","\/tags"],["variable","\/","[^\/]++","token"],["variable","\/","[^\/]++","username"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"site_credentials_new":{"tokens":[["text","\/site-credentials\/new"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":["GET","POST"],"schemes":[]},"howto":{"tokens":[["text","\/howto"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"new_tag":{"tokens":[["variable","\/","\\d+","entry"],["text","\/new-tag"]],"defaults":[],"requirements":{"entry":"\\d+"},"hosttokens":[],"methods":[],"schemes":[]},"remove_tag":{"tokens":[["variable","\/","\\d+","tag"],["variable","\/","\\d+","entry"],["text","\/remove-tag"]],"defaults":[],"requirements":{"entry":"\\d+","tag":"\\d+"},"hosttokens":[],"methods":[],"schemes":[]},"tag":{"tokens":[["text","\/tag\/list"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"tag_entries":{"tokens":[["variable","\/","[^\/]++","page"],["variable","\/","[^\/]++","slug"],["text","\/tag\/list"]],"defaults":{"page":"1"},"requirements":[],"hosttokens":[],"methods":[],"schemes":[]},"api_get_entries_tags":{"tokens":[["variable",".","xml|json|txt|csv|pdf|epub|mobi","_format"],["text","\/tags"],["variable","\/","[^\/]++","entry"],["text","\/api\/entries"]],"defaults":{"_format":"json"},"requirements":{"_format":"xml|json|txt|csv|pdf|epub|mobi"},"hosttokens":[],"methods":["GET"],"schemes":[]},"api_post_entries_tags":{"tokens":[["variable",".","xml|json|txt|csv|pdf|epub|mobi","_format"],["text","\/tags"],["variable","\/","[^\/]++","entry"],["text","\/api\/entries"]],"defaults":{"_format":"json"},"requirements":{"_format":"xml|json|txt|csv|pdf|epub|mobi"},"hosttokens":[],"methods":["POST"],"schemes":[]},"api_delete_entries_tags":{"tokens":[["variable",".","xml|json|txt|csv|pdf|epub|mobi","_format"],["variable","\/","[^\/\\.]++","tag"],["text","\/tags"],["variable","\/","[^\/]++","entry"],["text","\/api\/entries"]],"defaults":{"_format":"json"},"requirements":{"_format":"xml|json|txt|csv|pdf|epub|mobi"},"hosttokens":[],"methods":["DELETE"],"schemes":[]},"api_delete_entries_tags_list":{"tokens":[["variable",".","xml|json|txt|csv|pdf|epub|mobi","_format"],["text","\/api\/entries\/tags\/list"]],"defaults":{"_format":"json"},"requirements":{"_format":"xml|json|txt|csv|pdf|epub|mobi"},"hosttokens":[],"methods":["DELETE"],"schemes":[]},"api_post_entries_tags_list":{"tokens":[["variable",".","xml|json|txt|csv|pdf|epub|mobi","_format"],["text","\/api\/entries\/tags\/lists"]],"defaults":{"_format":"json"},"requirements":{"_format":"xml|json|txt|csv|pdf|epub|mobi"},"hosttokens":[],"methods":["POST"],"schemes":[]},"api_get_tags":{"tokens":[["variable",".","xml|json|txt|csv|pdf|epub|mobi","_format"],["text","\/api\/tags"]],"defaults":{"_format":"json"},"requirements":{"_format":"xml|json|txt|csv|pdf|epub|mobi"},"hosttokens":[],"methods":["GET"],"schemes":[]},"api_delete_tag_label":{"tokens":[["variable",".","xml|json|txt|csv|pdf|epub|mobi","_format"],["text","\/api\/tag\/label"]],"defaults":{"_format":"json"},"requirements":{"_format":"xml|json|txt|csv|pdf|epub|mobi"},"hosttokens":[],"methods":["DELETE"],"schemes":[]},"api_delete_tags_label":{"tokens":[["variable",".","xml|json|txt|csv|pdf|epub|mobi","_format"],["text","\/api\/tags\/label"]],"defaults":{"_format":"json"},"requirements":{"_format":"xml|json|txt|csv|pdf|epub|mobi"},"hosttokens":[],"methods":["DELETE"],"schemes":[]},"api_delete_tag":{"tokens":[["variable",".","xml|json|txt|csv|pdf|epub|mobi","_format"],["variable","\/","[^\/\\.]++","tag"],["text","\/api\/tags"]],"defaults":{"_format":"json"},"requirements":{"_format":"xml|json|txt|csv|pdf|epub|mobi"},"hosttokens":[],"methods":["DELETE"],"schemes":[]},"homepage":{"tokens":[["variable","\/","\\d+","page"]],"defaults":{"page":1},"requirements":{"page":"\\d+"},"hosttokens":[],"methods":[],"schemes":[]},"fos_user_security_logout":{"tokens":[["text","\/logout"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":["GET","POST"],"schemes":[]},"craue_config_settings_modify":{"tokens":[["text","\/settings"]],"defaults":[],"requirements":[],"hosttokens":[],"methods":[],"schemes":[]}},"prefix":"","host":"bags.domain.fr","scheme":"https"});`

**Comment by Kdecherf** [comment]
Did you clear the symfony cache?

**Comment by palouf34** [comment]
YES after launch this command 
`sudo -u www-data bin/console cache:clear -e prod`

the theme is ok.

thank's.
