### ISSUE TITLE
Blank White Page at Login 

### ISSUE THREAD

**Issue by ween101** [wallabag/wallabag#3551]
Fresh install 2.3.1 

I get a blank white screen at login  I checked the error log 

 PHP Warning:  file_get_contents(/root/wallabag/src/Wallabag/UserBundle/Resources/views/Security/login.html.$
twig): failed to open stream: Permission denied in /var/www/wallabag/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 145

Any insight would be helpful

**Comment by j0k3r** [comment]
https://doc.wallabag.org/en/admin/installation/rightaccess.html

**Comment by Kdecherf** [comment]
@ween101 do you still encounter this issue?

**Comment by ween101** [comment]
no longer an issue I ended up running the docker version all is right with the world now
