### ISSUE TITLE
Multiline annotations - Internal Server Error 

### ISSUE THREAD

**Issue by valvin1** [wallabag/wallabag#3554]
### Issue details

While annotating an article if I select multiple lines it generates and internal server error. But for small annotation it is ok.

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.2.2**
* type of hosting (shared or dedicated): Shared - framabag.org

### Steps to reproduce/test case

A video is simplier than word :

![peek 2018-01-08 13-18](https://user-images.githubusercontent.com/1267915/34670490-ccda8ccc-f476-11e7-851e-de68c01736e2.gif)

**Comment by tcitworld** [comment]
Please tell us if it happens on other articles and if not, give us the url of this one.

**Comment by aaa2000** [comment]
Duplicate #2762, fixed in release 2.3

**Comment by valvin1** [comment]
@tcitworld it is an all article.

@aaa2000 : i've made a search but have not found it. good news that it is fixed in 2.3 :)

**Comment by valvin1** [comment]
Just a quick comment to mention it works well on wallabag 2.3.1 and postgresql :) 

![peek 2018-01-10 20-30](https://user-images.githubusercontent.com/1267915/34791435-42fd1166-f645-11e7-90d0-838e9a743233.gif)
