### ISSUE TITLE
Problems with tags (lowercase letters / cannot delete) after upgrade to 2.3.1

### ISSUE THREAD

**Issue by Marty6** [wallabag/wallabag#3555]
### Issue details

Since my upgrade from 2.2.2 to 2.3.1 I have two annoying problems with **tags** in wallabag:

- Tags for newly fetched articles only have **lowercase letters** but they do not link to my previously created tags (e. g. if I had the tag "USA" before, when I try to enter this tag in the application or in my Wallabagger extension for Firefox, a second tag "usa" is created...)

- I can no longer **delete tags** from an article: After clicking on the trash can, the URL _domain_/wallabag/remove-tag//_XX_ shows the error message "Not found - The requested URL /app.php was not found on this server." The selected tag is _not_ deleted.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.1
* How did you install wallabag? Via `git clone` or by downloading the package? download / upgrade from 2.2.2 according to documentation
* Last wallabag version that did not exhibit the issue (if applicable): 2.2.2
* php version: 5.6
* OS: Windows 10
* type of hosting (shared or dedicated): shared (Uberspace)
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

See above

**Comment by nicosomb** [comment]
Hello @Marty6.

This bug is fixed by @Kdecherf here https://github.com/wallabag/wallabag/issues/3536
