### ISSUE TITLE
Fetch content from juniper.net/documentation

### ISSUE THREAD

**Issue by steiler** [wallabag/wallabag#3557]
I've been trying to Bag documentation pages from juniper.net/doumentation
e.g. https://www.juniper.net/documentation/en_US/junos/topics/concept/uplink-failure-detection.html

That fails.

Tried building my own graby rule, which did not work out either.
```
# Generated by FiveFilters.org's web-based selection tool
# Place this file inside your site_config/custom/ folder
# Source: http://siteconfig.fivefilters.org/grab.php?url=https%3A%2F%2Fwww.juniper.net%2Fdocumentation%2Fen_US%2Fjunos%2Ftopics%2Fconcept%2Fuplink-failure-detection.html

body: //div[@id='topic-content']
test_url: https://www.juniper.net/documentation/en_US/junos/topics/concept/uplink-failure-detection.html
```
This also results in wrong output.

I'd be pleased if someone could help out with this.

### Environment
Wallabag version 2.3.1

**Comment by j0k3r** [comment]
I got an error from html5-lib while parsing that website.

```
ErrorException: Call to a member function hasAttribute() on boolean
#1 vendor/electrolinux/php-html5lib/src/HTML5Lib/TreeBuilder.php(3048): handleFatalError
```

**Comment by techexo** [comment]
@steiler, @j0k3r Trying  to fetch the article with wallabag 2.3.4 went just fine, except for the title not being the right one (title of the site instead of title of the article).

**Comment by j0k3r** [comment]
Looks ok on 2.3.8
