### ISSUE TITLE
Icons are missing on Firefox android

### ISSUE THREAD

**Issue by tdelmas** [wallabag/wallabag#3560]
On framabag.org, which runs walabag 2.2.2, when visiting with Firefox 57.0.4 on android 5.0.1, all icons are replaced by some text, such as "menu", "add or "filter_list"

**Comment by styfic** [comment]
Had the same issue with Firefox on Desktop. Was solved with following lines in .htaccess in wallabag's web folder:

RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteCond %{ENV:HTTPS} !=on
RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]

**Comment by mbrandis** [comment]
I see the same problem with my Wallabag installation. Affected browsers: Firefox and Chromium desktop. The workaround with htaccess didn't work for me.

**Comment by dixonge** [comment]
@styfic Thank you! That fixed my issue. No icons, both themes. Shared hosting.

mil gracias
