### ISSUE TITLE
Removing tag from article leads to 404

### ISSUE THREAD

**Issue by TwizzyDizzy** [wallabag/wallabag#3561]
### Issue details

When removing a tag from an article, a 404 occurs. On confirming the deletion, one is redirected to https://wallabag.instance/wallabag/web/remove-tag//23.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.1
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): not sure
* php version: 7.0.27-0+deb9u1
* OS: Debian 9 / Stretch
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

![ezgif-5-d4e311210e](https://user-images.githubusercontent.com/179595/35150192-adfc6716-fd19-11e7-815a-8b58feb105f3.gif)

Cheers
Thomas

**Comment by j0k3r** [comment]
Fix will arrive in 2.3.2 https://github.com/wallabag/wallabag/issues/3534

**Comment by TwizzyDizzy** [comment]
Ooops, sorry for dupe. Thanks!
