### ISSUE TITLE
Encoding error in title when retrieving contents for Journal du Net article

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabag#3565]
Hi,

### Issue details

There's an encoding error in the title when fetching articles from Journal du Net.

### Environment

* wallabag.it

### Steps to reproduce/test case

* Add [this article](http://www.journaldunet.com/solutions/expert/68326/le-cognitive-search---une-technologie-precieuse-pour-lutter-contre-le-terrorisme.shtml) to Wallabag.
* Title is "Le cognitive search : une technologie précieuse pour lutter contre le terrorisme"
* Title in wallabag is "Le cognitive search : une technologie pr\&eacute;cieuse pour lutter contre le terrorisme"
* Accents in the article body are preserved

Thanks!

**Comment by TheCapsLock** [comment]
There is also an issue with nextinpact.com where article title contains html encoded chars.

This is the case with [that one](https://www.nextinpact.com/news/107328-des-deputes-lr-veulent-taxer-presence-fiscale-significative-plateformes-en-france.htm) where title tag is:

```html
<title>Des d&#233;put&#233;s LR veulent taxer &#171; la pr&#233;sence fiscale significative &#187; des plateformes en France</title>
```

I think we may use http://php.net/manual/en/function.html-entity-decode.php to solve this

**Comment by j0k3r** [comment]
Looks like it's fixed: 
![image](https://user-images.githubusercontent.com/62333/59132522-b4435000-8975-11e9-824e-96415d341044.png)
