### ISSUE TITLE
No content fetched from Business Insider

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabag#3566]
Hi,

### Issue details

Content from Business Insider.fr is not fetched.

### Environment

* wallabag.it

### Steps to reproduce/test case

* Add [this article](http://www.businessinsider.fr/us/nuzzel-media-intelligence-enterprise-charging-subscriptions-2018-1/)
* It won't have any content
* The article's content is in `.KonaBody.post-content > div`

Thanks!

**Comment by techexo** [comment]
@pVesian The content is fetched well in the last version of wallabag (2.3.4). Wallabag.it should be updated soon.

**Comment by j0k3r** [comment]
Fixed https://github.com/fivefilters/ftr-site-config/commit/c469ee96989970d619857f22353a667acf43e268
