### ISSUE TITLE
Can't remove tag on 2.3.1

### ISSUE THREAD

**Issue by brotherduck** [wallabag/wallabag#3567]
### Issue details

When a tag is added to an article it can't be deleted, the link to do so returns a 404 error.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.1
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): I think it was working OK with 2.3.0
* php version: 7.0.22
* OS: Ubuntu 16.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

1 - add a tag to an article
2 - try to remove it by clicking on the trash icon next to it

My setup access Wallabag articles by URL of this form : https://www.mydomain.tld/wallabag/web/view/196

When I click on the remove tag icon it tries to go there (after confirming I'm OK with the deletion) : https://www.mydomain.tld/wallabag/web/remove-tag//9

In Wallabag logs I'm seeing this error :
```
[2018-01-22 09:36:38] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /remove-tag//9" (from "
https://www.mydomain.tld/wallabag/web/view/196")" at /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line
 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /remove-tag//9\" (from \"https://www.mydomain.tld/wallabag/web/view/196\") at /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:123, Symfony\\Compon
ent\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []
```

**Comment by j0k3r** [comment]
Fix will arrive in 2.3.2 https://github.com/wallabag/wallabag/issues/3534
