### ISSUE TITLE
issue at wallabag run after iinstall on Debian Stretch

### ISSUE THREAD

**Issue by fantasio31** [wallabag/wallabag#3577]
After installing Wallabag v2 on Debian Stretch (on OVH VPS) from git master sources i get the following error:

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in /var/www/html/wallabag/app/AppKernel.php:49
Stack trace:
#0 /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(448): AppKernel->registerBundles()
#1 /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(59): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/wallabag/bin/console( in /var/www/html/wallabag/app/AppKernel.php on line 49
Makefile:22: recipe for target 'run' failed
make: *** [run] Error 255

Do you have any idea of how to correct the issue ?
"Make install" worked fine an told me everything was ok.

**Comment by Strubbl** [comment]
Your error message is the same as the one mentioned in https://github.com/wallabag/wallabag/issues/2768#issuecomment-280291846

**Comment by fantasio31** [comment]
Thanks but the referenced issue if occuring after update. Mine is occuring after a fresh installation and database creation from Wallabag installer.

I also have read other threads regarding the kind of issue without found any solution.

**Comment by j0k3r** [comment]
Which command did you run?

**Comment by fantasio31** [comment]
i used the follwing commands to install an try to run:
> sudo -u www-data make install
> sudo -u www-data make run

30 janvier 2018 15:06 "Jérémy Benoist" <notifications@github.com (mailto:%22J%C3%A9r%C3%A9my%20Benoist%22%20<notifications@github.com>)> a écrit:
	Which command did you run?

**Comment by vincent-ferotin** [comment]
Hi,

I probably have a similar issue, on a fresh install of Wallabag 2.3.2, on a OVH's VPS, with Debian 9 (Stretch) as OS. I encounter similar stack trace when running commands (as root):
```
/var/www/wallabag# bin/console help                                     
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in /var/www/wallabag/app/AppKernel.php:49
Stack trace:
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(448): AppKernel->registerBundles()
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(59): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/wallabag/bin/console(29): Symfony\Component\Console in /var/www/wallabag/app/AppKernel.php on line 49
```
(but my install with ``make install`` worked fine)

**Comment by fantasio31** [comment]
Hi,

For information, i make this run.
Here are the steps i have executed:
 1) create a swap file (require for composer update): https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
 2) go to your wallabag installation path
 3) execute : sudo -u www-data composer update

I hope this will help.

**Comment by leolivier** [comment]
Tried this on my raspberrypi where I had the same issue but composer update fails with a segmentation violation (I have a 1GB memory plus a 2 GB swap file)

**Comment by fantasio31** [comment]
I think you are experiencing a specific composer error.

Try to search for composer issues. On my raspberrypi, I have not encountered this kind of error.

7 février 2018 11:19 "leolivier" <notifications@github.com (mailto:%22leolivier%22%20<notifications@github.com>)> a écrit:
	Tried this on my raspberrypi where I had the same issue but composer update fails with a segmentation violation (I have a 1GB memory plus a 2 GB swap file)

**Comment by Vertux** [comment]
@fantasio31 
> 3. execute : sudo -u www-data composer update

This worked for me (Debian 9) - thanks.

**Comment by bigretromike** [comment]
With 2GB RAM and 2GB SWAP I'm unable to `composer update` 

and without it the guide for installing `git clone` and `make install` give me:
```
PHP Fatal error:  Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none returned in /var/www/clients/client0/web8/wallabag/vendor/ocramius/package-versions/src/PackageVersions/Installer.php:80
Stack trace:
#0 /usr/share/php/Composer/Plugin/PluginManager.php(232): PackageVersions\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 /usr/share/php/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(PackageVersions\Installer))
#2 /usr/share/php/Composer/Installer/PluginInstaller.php(63): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#3 /usr/share/php/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#4 /usr/share/php/Composer/Installer/InstallationManager.php(160): Composer\Installer\InstallationManager->inst in /var/www/clients/client0/web8/wallabag/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 80

```

**Comment by j0k3r** [comment]
These kind of issue will be fixed with the 2.4.0.
In the meantime, don't try `composer update`. Clone a tagged version of wallabag and do `composer install` instead. As per your issue, try removing `vendor` folder and `composer install` again.

**Comment by bigretromike** [comment]
I end-up installing the package that I always used (shared vhost).
As always no issues there. 

Will try to install 2.4.0 when its up.
Thanks for respond.

**Comment by salexan2001** [comment]
I had the same issue on a recent installation on a raspberry pi (arch arm), but could resolve it using @j0k3r 's hint.

**Comment by j0k3r** [comment]
Please open a new issue referencing this one and **as much information as possible**, "I have the same issue" is not relevant.
