### ISSUE TITLE
Error 500 when trying to retrieve content from a specific tweet (General error: string value: '\xF0\x9F\x92\xBE A...' for column 'title' at row 1)

### ISSUE THREAD

**Issue by dalgwen** [wallabag/wallabag#3582]
### Issue details

When trying to retrieve this tweet :
**https://mobile.twitter.com/dosnostalgic/status/805507975007899648**
I get an "500: Internal Server Error"
In the bottom of the stack trace I get :
**General error: 1366 Incorrect string value: '\xF0\x9F\x92\xBE A...' for column 'title' at row 1**
Full error log :

An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, is_archived, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, origin_url, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "Tweet from \n\n \n \ud83d\udcbe Anatoly Shashkin", "https:\/\/mobile.twitter.com\/dosnostalgic\/status\/805507975007899648", 0, 0, "<div class=\"dir-ltr\" dir=\"ltr\"> Ok, so Sam &amp; Max Hit the Road design doc is pretty hilarious in itself. Check it out at <a href=\"https:\/\/t.co\/jQlCWVco6N\" rel=\"nofollow noopener\" dir=\"ltr\" data-expanded-url=\"http:\/\/wilmunder.com\/Arics_World\/Games.html\" data-url=\"http:\/\/wilmunder.com\/Arics_World\/Games.html\" class=\"twitter_external_link dir-ltr tco-link\" target=\"_blank\" title=\"http:\/\/wilmunder.com\/Arics_World\/Games.html\">wilmunder.com\/Arics_World\/Ga\u2026<\/a> <a href=\"https:\/\/t.co\/OmpsKW9UZq\" data-pre-embedded=\"true\" rel=\"nofollow\" data-entity-id=\"805507872696176642\" dir=\"ltr\" data-url=\"https:\/\/twitter.com\/dosnostalgic\/status\/805507975007899648\/photo\/1\" data-tco-id=\"OmpsKW9UZq\" class=\"twitter_external_link dir-ltr tco-link has-expanded-path\" target=\"_top\" data-expanded-path=\"\/dosnostalgic\/status\/805507975007899648\/photo\/1\">pic.twitter.com\/OmpsKW9UZq<\/a>\n<\/div>", "2018-02-04 16:01:28", "2018-02-04 16:01:28", null, "a:1:{i:0;s:21:\"\ud83d\udcbe Anatoly Shashkin\";}", null, "text\/html", "en", 0, "mobile.twitter.com", null, 200, "N;", null, 2]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x92\xBE A...' for column 'title' at row 1

### Environment

* wallabag version: **2.3.2**
* How did you install wallabag? **git clone**
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: **php7.0**
* OS: ubuntu
* type of hosting (shared or dedicated): **dedicated**
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): **MySQL/MariaDB (utf8mb4)**

### Steps to reproduce/test case

From web GUI, add an article with this URL : 
https://mobile.twitter.com/dosnostalgic/status/805507975007899648

**Comment by j0k3r** [comment]
Please use the search engin before submitting an issue : https://github.com/wallabag/wallabag/search?q=Incorrect+string+value&type=Issues&utf8=%E2%9C%93

➡️ https://github.com/wallabag/wallabag/issues/3530#issuecomment-353937163

**Comment by dalgwen** [comment]
Oups... Don't know how I could have missed it !
I'm really sorry fort the time wasted.
