### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by ghost** [wallabag/wallabag#3584]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to https://community.wallabag.org/ (forum) or http://gitter.im/wallabag/wallabag (chat).

### Environment

* wallabag version (or git revision) that exhibits the issue:
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by Mrolgs** [comment]
wallabag version (or git revision) that exhibits the issue: latest version 

How did you install wallabag? Via git clone or by downloading the package? Download 

Last wallabag version that did not exhibit the issue (if applicable):
php version: 7.2
OS: -
type of hosting (shared or dedicated): shared 
which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): dont know

**Comment by j0k3r** [comment]
What is failing?
Please give us more information otherwise we are going to close your issue.

**Comment by Mrolgs** [comment]
Hi, i don't know why my firt question isn`t there. :(

I was using wallabag with softaclouse, but my new webhoster have no softaclouse, so i download wallabag from github -> unzip it -> copy it to my webspace -> visit mydomain.de/wallabag/web/login

But i only the a blank page. My webhoster write my this logfile:

AH01071: Got error 'PHP message: PHP Warning: require(/var/www/vhosts/af9be.netcup.net/httpdocs/ wallabag /app/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/af9be.netcup.net/httpdocs/ wallabag /app/autoload.php on line 9\nPHP message: PHP Warning: require(/var/www/vhosts/af9be.netcup.net/httpdocs/save/app/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/af9be.netcup.net/httpdocs/ wallabag /app/autoload.php on line 9\nPHP message: PHP Fatal error: require(): Failed opening required '/var/www/vhosts/af9be.netcup.net/httpdocs/ wallabag /app/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/af9be.netcup.net/httpdocs/ wallabag /app/autoload.php on line 9\n'"

**Comment by j0k3r** [comment]
If you want to install it manually, you should use the one share hosting version: https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting

**Comment by Mrolgs** [comment]
Yes this Version i download from github and unzip it and copy it to my webspace. I cant install wallabag via ssh, because my wbhoster doesnt support it. 

Is it possible to download, unzip and copy wallabag to the webspace and just use it with sqllight?

**Comment by j0k3r** [comment]
I don't know _sqllight_

**Comment by Mrolgs** [comment]
Oh i mean SQLite :)

**Comment by Mrolgs** [comment]
Is it possible to install wallabag without ssh? Just download wallabag from github as zip, unzip and copy to the webhost webspace? Or do I have to change files to make it work and when wich files?

Because without changing any files i only see an empty window.

**Comment by j0k3r** [comment]
Yes. But without errors from your side we can't help you.

**Comment by Mrolgs** [comment]
I only can send the logfile from my provider. Because i can't login or see the login window. :) 

AH01071: Got error 'PHP message: PHP Warning: require(/var/www/vhosts/af9be.netcup.net/httpdocs/ wallabag /app/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/af9be.netcup.net/httpdocs/ wallabag /app/autoload.php on line 9\nPHP message: PHP Warning: require(/var/www/vhosts/af9be.netcup.net/httpdocs/save/app/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/af9be.netcup.net/httpdocs/ wallabag /app/autoload.php on line 9\nPHP message: PHP Fatal error: require(): Failed opening required '/var/www/vhosts/af9be.netcup.net/httpdocs/ wallabag /app/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/af9be.netcup.net/httpdocs/ wallabag /app/autoload.php on line 9\n'"

**Comment by j0k3r** [comment]
Did you follow instruction from here: https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting as I previously say? Because that missing file from your error exist in the archive.

**Comment by Mrolgs** [comment]
Yes i 

1. Download Wallabag from https://wllbg.org/latest-v2-package
2. Edit the app/config/parameters.yml and save it
3. Upload anythig with filezilla to my webspace
4. Open www.mydomain.de/wallabag/web/login
5. Can't see anything. :(

I'm sorry but i can't use the commands from the instruction. I can't use ssh, but my way should normaly work too, or?

**Comment by Olgsiolgs** [comment]
I have the same problem and installed it like the ghost before

**Comment by mbirth** [comment]
Similar problem. Followed the instructions for installation on shared web hosting, but it seems there's a step missing where I initialise the database.

Apache error log:

```
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: craue_config_setting in /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: Stack trace:
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: #0 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('SELECT t0.secti...', Array)
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: #1 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(844): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('SELECT t0.secti...')
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: #2 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(712): Doctrine\\DBAL\\Connection->executeQuery('SELECT t0.secti...', Array, Array)
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: #3 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(196): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: #4 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/c in /var/www/virtual/mbirth/apps/wallabag-2.3.8/src/Wallabag/CoreBundle/Resources/views/base.html.twig on line 74
```

**Comment by j0k3r** [comment]
Could you create a separate issue?
