### ISSUE TITLE
Error fetching Open Democracy article

### ISSUE THREAD

**Issue by twsh** [wallabag/wallabag#3585]
I tried and failed to fetch: https://www.opendemocracy.net/neweconomics/time-fragile-temporality-carillions-accumulation-model/

It works on https://f43.me/feed/test

I'm using 2.3.2 on https://app.wallabag.it

**Comment by j0k3r** [comment]
I got it to work using the master but yeah, on wallabag.it it doesn't work 🤔

**Comment by glego** [comment]
I've got the same issue on the 2.3.2. I'll try to fix it, but have no experience with graby, let's see!

Error: https://pastebin.com/0kvHmJCw

**Comment by j0k3r** [comment]
Well, I think you shouldn't loose your time trying to fix that issue.
It work on the master and wallabagit doesn't use the master as of now.
I guess it'll be fixed when we'll release the 2.3.3 version.

**Comment by Kdecherf** [comment]
@twsh @glego as the 2.3.3 version has been released, does it fix your issue?

**Comment by twsh** [comment]
https://app.wallabag.it is using 2.3.2. Will it be updated to 2.3.3?

**Comment by j0k3r** [comment]
Yeah it'll.

**Comment by j0k3r** [comment]
Locally I've no problem on 2.3.6.
Looks like it's a problem in wallabag.it only :thinking:

**Comment by techexo** [comment]
Probably a stupid idea, but there was some difference on how the articles where fetched on same versions of wallabag when versions of php-tidy and/or htmlawed differed. Would it be possible that it is the case between your local wallabag and wallabag.it?

**Comment by j0k3r** [comment]
wallabag.it is now up to date with tidy installed.
But fetching the article still fail 😞

**Comment by Kdecherf** [comment]
Seems to work on 2.4.1, also tested on app.wallabag.it, closing this issue.
