### ISSUE TITLE
Empty page after upgrading from 2.2.3 to 2.3.2

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#3587]
Hi

I am using the distribution tar to upgrade because I use Debian wheezy it gets harder and harder to fill upgrade requirements with manual installs. Anyway tars normally work.

Today I tried upgrading from 2.2.3 to 2.3.2 and all I got was an empty page. Thankfully I have a back up to go back.

- I copied the data (I use sqlite) and paramteter.yml to proper places. 

- I set the whole folder to www-data permission. 

- I ran the sqlite commands from query-upgrade-22-23.md ((sqlite portion) by running sqlite3 mydatabase then pasting only the commands. then I yped .exit

- I then copied the var folder and emptied the cache

Now this should work right? It does not all I get is an empty page :(

Server version: Apache/2.2.22 (Debian)

thanks

**Comment by gerroon** [comment]
I forgot to mention.

I get index number problem with sqlite upgrades but I do not know what those numbers are for so. that is one issue that might be important 

The other is this

bin/console doctrine:migrations:execute 20161001072726 --env=prod .
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  You have requested a non-existent parameter "use_webpack_dev_server".

I so dread upgrading wallabag, everytime I try it, I always hit a wall of this or wall of that :(

**Comment by Strubbl** [comment]
sqlite is not supported anymore

**Comment by gerroon** [comment]
Ok, what am I supposed to do now? Should not I upgrade?

**Comment by gerroon** [comment]
The thing is, this is nmot mentioned in the upgrade page even so the upgrade sql script includes updates for the sqlite as well. So it is something only devs know about it.

**Comment by francis-barban** [comment]
Same for me each time the cache is cleared under another group:user than wallabag. If wallabag runs under www-data:www-data be sure that all var/cache have the same owner : 
chown -R www-data:www-data *

**Comment by gerroon** [comment]
@francis-barban 

Are you saying that you were able to upgrade from 2.2.3 to 2.3.2 and it was just permission issue?

All folders have proper permission after upgrade

**Comment by j0k3r** [comment]
Your wallabag instance is pretty old, any chance to update to the latest (2.3.6) and check again?
Thanks
