### ISSUE TITLE
Failure to fetch articles from medium

### ISSUE THREAD

**Issue by jpoles1** [wallabag/wallabag#3588]
### Environment

* wallabag version: 2.3.2
* How did you install wallabag: Using docker-compose (with docker images wallabag/wallabag, mariadb, and redis:alpine)
* php version: Unknown
* OS: Ubuntu 16.04 running docker version 17.12.0-ce
* type of hosting (shared or dedicated): shared (AWS EC2)
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Mariadb

### Steps to reproduce/test case
* Trying to add URL: https://medium.com/deep-learning-turkey/google-colab-free-gpu-tutorial-e113627b9f5d
* I have had similar problems fetching other medium articles from groups like [HackerNoon](https://hackernoon.com/). That said, many medium articles do work.
* I have checked, and it does fetch properly using https://f43.me/feed/test
* Using Wallabagger: get red W
* Using add (plus) button in Wallabag top bar: 
  * 500: Internal Server Error
  * At end of error string: "Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x91\x8F a...' for column 'content' at row 1"

**Comment by glego** [comment]
The issue is most likely caused by the MySQL not configured to utf8mb4.

You can check by running this command
```
mysql -u root -p  --database wallabag -e  "SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';"
```

Output example
```
+--------------------------+--------------------+
| Variable_name            | Value              |
+--------------------------+--------------------+
| character_set_client     | utf8mb4            |
| character_set_connection | utf8mb4            |
| character_set_database   | utf8mb4            |
| character_set_filesystem | binary             |
| character_set_results    | utf8mb4            |
| character_set_server     | utf8mb4            |
| character_set_system     | utf8               |
| collation_connection     | utf8mb4_unicode_ci |
| collation_database       | utf8mb4_general_ci |
| collation_server         | utf8mb4_unicode_ci |
+--------------------------+--------------------+
```

As stated in the doc: https://doc.wallabag.org/en/admin/parameters.html

> For PostgreSQL & SQLite you should use utf8, for MySQL use utf8mb4 to handle emoji and other special characters


Other Examples 
* https://dbader.org/blog/mastering-click-advanced-python-command-line-apps
* https://dev-blog.apollodata.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b

Duplicate Issue
* https://github.com/wallabag/wallabag/issues/3527
* https://github.com/wallabag/wallabag/issues/2976

**Comment by jpoles1** [comment]
Using the fix detailed in https://github.com/wallabag/docker/issues/105 worked for me! Thanks a bunch @glego!
