### ISSUE TITLE
Option to open random unread article

### ISSUE THREAD

**Issue by sdenaro** [wallabag/wallabag#3594]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to https://community.wallabag.org/ (forum) or http://gitter.im/wallabag/wallabag (chat).

Wallabag 1.9.2 had the option to open a random unread article. The android app has this same option. I'd like to see it in the current web ux.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.x
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 1.9.2
* php version: 7.x
* OS: debian 8.x
* type of hosting (shared or dedicated): dedicated vps
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

1) Click on random in the android or in the older 1.9.2 version of the app, feel the excitement of the unknown. 🥇 👍 

2) Look the current 2.2.x version and see this is missing. Scroll up and down your list. Feel the stress of decision fatigue. 👎

**Comment by j0k3r** [comment]
Duplicates https://github.com/wallabag/wallabag/issues/2285
