### ISSUE TITLE
Add raw content via api

### ISSUE THREAD

**Issue by hajika** [wallabag/wallabag#3595]
I didn't found a solution in the api yet, how to add raw content to Wallabag, it looks like this feature does not exist yet?

With raw content I mean, not sending a link to wallabag that gets fetched then, but sending textes directly to the api. Sometimes I would like to do kind of this with longer Email Textes, or whatever I need to read on Desktop and would like to make easy available to my mobile device.

**Comment by j0k3r** [comment]
It's available.
Check the api doc: https://app.wallabag.it/api/doc#post--api-entries.%7B_format%7D
