### ISSUE TITLE
Improve importation of articles behind paywall

### ISSUE THREAD

**Issue by simon2cyrene** [wallabag/wallabag#3599]
This features is very useful and I thank you every times I'm reading an article on my e-book reader.

I think it could be even better if it import the whole article. On Mediapart and Le Monde Diplo, for example, the lead paragraph (chapeau in french) is missing. Is there a technical reason ?
In addition, I would indicate the duplicity of the illustrative pictures in the importation of Le Monde Diplo's articles.

**Comment by techexo** [comment]
If you indeed have issues with Le Monde Diplomatique paywall, please ping the following issue: https://github.com/wallabag/wallabag/issues/3502

**Comment by j0k3r** [comment]
You can follow what's going on for paywall parsing here https://github.com/wallabag/wallabag/issues/3439
