### ISSUE TITLE
Can't fetch nasa.gov articles

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabag#3604]
Hi,

### Issue details

Fetching articles from nasa.gov fails.

### Environment

* wallabag.it
* f43.me

### Steps to reproduce/test case

* Add [this article](https://www.nasa.gov/feature/jpl/new-clues-to-trappist-1-planet-compositions-atmospheres) to wallabag
* It doesn't fetch anything
* The directories to articles are not always /feature/jpl, it can also be /press-release and I'm sure there are other types.

Thanks!

**Comment by kissgyorgy** [comment]
This might be not that simple. Seems that page is an SPA. Fetching it would require to run JavaScript in Wallabag somehow which is not trivial. It's a big feature.

**Comment by Kdecherf** [comment]
Not necessarily. It seems that the webpage loads its content from `/api/2/ubernode/{_id}` which return a ElasticSearch-like JSON object with interesting part in path `._source.body`.
`{_id}` can be found in the former page at two places:
``` html
<script>window.forcedRoute = "/ubernode/418056"</script>
```
and in the body's classes: `page-node-418056` which could be generalized as `page-node-[0-9]+`.

Not sure what is the best way to handle that in wallabag.

**Comment by burkemw3** [comment]
What's the plan for AJAX situations like this?

I expect they will continue to arise, especially as the Google web crawler now supports JavaScript, and the _escaped_fragment_ has been deprecated for years [0](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html).

Sadly, I don't have any new options to add. Just adding JavaScript execution support, and custom handlers for sites/fingerprints.

**Comment by HolgerAusB** [comment]
the article is now being redirected to a subdomain:
https://science.nasa.gov/missions/hubble/new-clues-to-trappist-1-planet-compositions-atmospheres

Maybe the html has changed to.
I wrote a config to make the article nice.
