### ISSUE TITLE
Weird: impartial fetch for sofrep.com

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabag#3605]
Hi,

### Issue details

Something weird happended to [an article on sofrep.com](https://sofrep.com/98896/interview-with-an-american-ypg-fighter-straight-outta-raqqa/): it was partially fetched (see screenshot 2). This is unusual since I have read tens of sofrep articles with Wallabag. Refetching the content didn't help.
f43.me shows the complete article (see screenshot 3).

### Environment

* wallabag.it

### Steps to reproduce/test case

- Check out article length: https://sofrep.com/98896/interview-with-an-american-ypg-fighter-straight-outta-raqqa/ / screenshot 1
- Add article to wallabag: https://sofrep.com/98896/interview-with-an-american-ypg-fighter-straight-outta-raqqa/, it's partially fetched (screenshot 2)
- Test it on f43.me, it's fully fetched (screenshot 3)
- Weird++: Firefox reader view renders the same as Wallbag: partial...

Screenshot 1: Original: https://imgur.com/a/BnyIt
Screenshot 2: Wallabag impartial fetch: https://imgur.com/a/ZcE2D
Screenshot 3: f43.me fetch: https://imgur.com/a/M1Qja

What happened? Can this be fixed without breaking the behavior for other articles?
Thanks

**Comment by Kdecherf** [comment]
Hello @pVesian,

I can't reproduce this issue on 2.3.3. Do you still encounter it?

**Comment by techexo** [comment]
I confirm it works fine on 2.3.4. The issue on Firefox (63.0.3) is also absent. There was probably an issue in the code of the article that has been fixed meanwhile.

**Comment by techexo** [comment]
@pVesian Is it working for you now?

**Comment by pVesian** [comment]
@pVesian Yes, it works fine. Thanks for checking

**Comment by pVesian** [comment]
@techexo Yes, it works fine. Thanks for checking
