### ISSUE TITLE
Error 500 after upgrade

### ISSUE THREAD

**Issue by giovi321** [wallabag/wallabag#3607]
### Issue details

Error 500 after upgrade from 2.3.0 to 2.3.2:

wallabag logo
500: Internal Server Error

An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT w0_.id AS id_0 FROM `wallabag_entry` w0_ WHERE w0_.user_id = ? AND w0_.is_starred = 1 GROUP BY w0_.id ORDER BY w0_.starred_at DESC' with params [1]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'w0_.starred_at' in 'order clause'").

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 2.3.0
* php version: PHP 5.6.33-0+deb8u1
* OS: Debian 8
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Upgrade to wallabag 2.3.2 using "make update".

**Comment by Kdecherf** [comment]
Hello @giovi321 

Did the `make update` return any error/failure?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
