### ISSUE TITLE
Unable to upgrade on shared hosting. Wallabag initially installed through Softaculous

### ISSUE THREAD

**Issue by dariottolo** [wallabag/wallabag#3611]
### Issue details

Please provide issue details here.
Unable to upgrade on shared hosting. Wallabag initially installed through Softaculous

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.1
* How did you install wallabag? Via `git clone` or by downloading the package? Softaculous
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 7.1
* OS:
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL/MariaDB

### Steps to reproduce/test case

I tried to upgrade from 2.3.1 to 2.3.2 via "make update". This is the result:

> diludovi@ams25 [~/public_html/wb]# make update
> composer.phar not found, we'll see if composer is installed globally.
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> Loading composer repositories with package information
> Installing dependencies from lock file
> Nothing to install or update
> Generating optimized autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
> Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
> 
> // Clearing the cache for the prod environment with debug
> // false
> 
> 
> [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
> 
> 
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
> 
> Trying to install assets as relative symbolic links.
> 
> --- ------------------------------ ------------------
> Bundle Method / Error
> --- ------------------------------ ------------------
> ✔ NelmioApiDocBundle relative symlink
> ✔ WhiteOctoberPagerfantaBundle relative symlink
> ✔ FOSJsRoutingBundle relative symlink
> --- ------------------------------ ------------------
> 
> 
> [OK] All assets were successfully installed.
> 
> 
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile> 
> 
> Application Migrations
> 
> 
> No migrations to execute.
> 
> // Clearing the cache for the prod environment with debug // false 
> [OK] Cache for the "prod" environment (debug=false) was successfully cleared. 
> diludovi@ams25 [~/public_html/wb]#

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

try to execute "make update" via ssh. See above

**Comment by j0k3r** [comment]
I think the simplest way is to export stuff from the previous wallabag, install a new one and import entries.

**Comment by dariottolo** [comment]
make update seems to be working
