### ISSUE TITLE
Logging by email

### ISSUE THREAD

**Issue by SansPseudoFix** [wallabag/wallabag#3612]
### Issue details

Right now, we can only use username to connect. What about email? We remember much easily email than username.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2

### Steps to reproduce/test case

* connect with email
* you can"t connect :)

As @tcitworld pointed out, it can be done by: https://symfony.com/doc/master/bundles/FOSUserBundle/logging_by_username_or_email.html

**Comment by j0k3r** [comment]
Yeah looks like it's an easy pick / good first issue!
