### ISSUE TITLE
ios client can't share to app with safari

### ISSUE THREAD

**Issue by lilarcor** [wallabag/wallabag#3618]
installed the latest version from IOS APP store. 
Open one website in safari, use share function to save article to wallabag, it will wait for a while, then a windows poped up, saying Error, please open app and try to add manually your url.
For some reason, 443 port is disable by local ISP, so I have to use other port for https protocal. I am not sure if it's related. And I also found sometime, when I refresh the app, some entries are duplicated then removed, very wired. 

Thanks you for your great product

**Comment by j0k3r** [comment]
This issue was moved to wallabag/ios-app#141

**Comment by lilarcor** [comment]
is the issue addressed and will be resolved in next release?

**Comment by j0k3r** [comment]
This issue isn't related to the wallabag web application but to the wallabag ios application that's why I moved the issue to the other repository.
I've no idea is this issue will be fixed in the next ios release. You should ask on the moved issue.

**Comment by lilarcor** [comment]
thanks
