### ISSUE TITLE
Bug report: remove tag not working

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#3620]
### Issue details

Removing a tag is not working
![imagen](https://user-images.githubusercontent.com/10577978/38137154-55b5cfde-3423-11e8-98af-9c94dac66707.png)

Open URL is `web/remove-tag//68`
And should be  `web/remove-tag/ARTICLE_ID/68`

### Environment
* wallabag master

**Comment by j0k3r** [comment]
Fix is available since https://github.com/wallabag/wallabag/issues/3534
