### ISSUE TITLE
Refetching fails despite graby-site-config update

### ISSUE THREAD

**Issue by shtrom** [wallabag/wallabag#3623]
I have set up a symlink from `vendor/j0k3r/graby-site-config` to a git clone of `fivefilters/ftr-site-config`, as I understand they are the same thing, and `ftr` is more authoritative. This allows me to `git pull` the newest definitions, including some that I have just contributed.

However, in some cases, despite an up-to-date checkout, with the new definition files in the right place, re-fetching an article still fails. I suspect there is some sort of caching somewhere, but I haven't been able to find where exactly it is (I have deleted `var/cache/prod` to no avail).

How can I help diagnosing this further?

**Comment by j0k3r** [comment]
`graby-site-config` & `ftr-site-config` aren't quite the same repo.
The graby one use an autoloader for each file which allow wallabag to use them ([here](https://github.com/j0k3r/graby-site-config/blob/master/src/Files.php)). My guess is it shouldn't work if you just replace the `vendor/j0k3r/graby-site-config` to a git clone of `fivefilters/ftr-site-config`.

**Comment by shtrom** [comment]
Ah! I just forked graby and merged my ftr into it and... my issues are gone.

This might explain why I saw random failures that worked with f43.me 🤦‍♂️ Sorry, I must have reported a few false positives.

Thanks for the explanation!

Sorry about the noise...
