### ISSUE TITLE
Register button is not visible

### ISSUE THREAD

**Issue by respinfo-issat** [wallabag/wallabag#3624]
Hi,
### Issue details
Impossible to register user from login form : register button is not visible (and no code generated for it...)

### Environment

* wallabag version 2.3
* How did you install wallabag? `git clone`
* php version: 7.0
* OS: Linux Debian 9
* type of hosting : dedicated
* which storage system you choose at install : MySQL/MariaDB

### Steps to reproduce/test case
none

in my parameters.yml, the two lines : 
    fosuser_registration: true
    fosuser_confirmation: true

and smtp configuration : 
    mailer_transport: smtp
    mailer_host: 'ssl0.ovh.net'
    mailer_user: 'my@email.fr'
    mailer_password: 'mypassword'

did I miss something?

Thanks in advance to help me !

**Comment by j0k3r** [comment]
Did you clear your cache?

**Comment by respinfo-issat** [comment]
Yes, many times !
with sudo -u www-data php bin/console cache:clear -e prod

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by TROMsite** [comment]
Well I have the same issue here https://bag.trom.tf - how do I enable registrations? I am confused. Can't find anywhere in the docs. cheers!
