### ISSUE TITLE
Is there a way to apply tagging rules to entries already saved to Wallabag?

### ISSUE THREAD

**Issue by eli-oat** [wallabag/wallabag#3628]
I just set up a number of tagging rules and am wondering if there is any way to retroactively to apply them to my library of previously saved content? 

I'm currently running Wallabag 2.2.3, on centOS 7

**Comment by j0k3r** [comment]
Yes you can use the `tag:all` command: https://doc.wallabag.org/en/admin/console_commands.html#wallabagtagall

**Comment by eli-oat** [comment]
This worked like a charm @j0k3r 

Thanks so much!
