### ISSUE TITLE
Installation issue.

### ISSUE THREAD

**Issue by JamesBottomley** [wallabag/wallabag#3629]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Please provide issue details here.
Remember, this is _not_ a place to ask questions. For that, go to https://community.wallabag.org/ (forum) or http://gitter.im/wallabag/wallabag (chat).

### Environment

* wallabag version (or git revision) that exhibits the issue: Latest
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version:
```
james@LAMP01:~$ php -v
PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  6 2018 11:18:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
james@LAMP01:~$ mysql -V
mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper
james@LAMP01:~$ php -i | grep -i '^libxml'
libxml Version => 2.9.4
libxml
libXML support => active
libXML Compiled Version => 2.9.4
libXML Loaded Version => 20903
libXML streams => enabled
libxml2 Version => 2.9.4
james@LAMP01:~$
```

* OS: ubuntu server 16.04
* type of hosting (shared or dedicated):dedicated, own VM
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):tried both,. did VM snapshots and have reverted however easily replicatable

### Steps to reproduce/test case
Followed installation guide on the website to the T including apache2 virtual hosts.

Appears it redirects to domain.tld/login but displays nothing. favicon displays. 
Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

_Edit from @Kdecherf: format shell output_

**Comment by techexo** [comment]
Hi @JamesBottomley. I know it is quite an old issue, but have you succeeded in resolving this?

Origin of this could be: issues with [file permissions](https://doc.wallabag.org/en/admin/installation/rightaccess.html) or with your installation of PHP (are you able to use php easily on this server?). Finally, this error sometimes occurs when directories are moved after the installation: you shall then remove all content of `var/cache` directory.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
