### ISSUE TITLE
Configuration apache

### ISSUE THREAD

**Issue by JakubMajcher** [wallabag/wallabag#3631]
### Issue details

After install wallbag on my raspberry pi I'm connect with app from another computer. Unfortunetly i cant config apache to do it. I cant even to see login panel on raspberry on localhost. How should config wallabag.conf to do it?
```
<VirtualHost *:80>
 ServerName localhost
 ServerAlias localhost

DocumentRoot /var/www/wallabag/web
 <Directory /var/www/wallabag/web>
   Require all granted

<IfModule mod_rewrite.c>
 Options -MultiViews
 RewriteEngine On
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteRule ^(.*)$ app.php [QSA,L]
 </IfModule>
 </Directory>

# uncomment the following lines if you install assets as symlinks
 # or run into problems when compiling LESS/Sass/CoffeScript assets
 # <Directory /var/www/wallabag>
 # Options FollowSymlinks
 # </Directory>

# optionally disable the RewriteEngine for the asset directories
 # which will allow apache to simply reply with a 404 when files are
 # not found instead of passing the request into the full symfony stack
 <Directory /var/www/wallabag/web/bundles>
 <IfModule mod_rewrite.c>
 RewriteEngine Off
 </IfModule>
 </Directory>
 ErrorLog /var/log/apache2/wallabag_error.log
 CustomLog /var/log/apache2/wallabag_access.log combined
</VirtualHost>
```

### Environment

* wallabag version (or git revision) that exhibits the issue: newest
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.0
* OS: Raspbian
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by Kdecherf** [comment]
Which error are you seeing?

**Comment by Kdecherf** [comment]
I’m closing this issue because it has been inactive for a few months.

Feel free to reopen it if you still encounter this issue.
