### ISSUE TITLE
404 response received for assets under /wallassets

### ISSUE THREAD

**Issue by lgp171188** [wallabag/wallabag#3637]
### Issue details

Please provide issue details here.
I upgraded my Wallabag instance from 2.2.2 to 2.3.2 today using the `make update` command and after the upgrade, 404 response status code is received for all the assets under `/wallassets`, thereby the Wallabag site loads without CSS and JS. This happens even with a fresh install of 2.3.2.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone && git checkout 2.3.2`
* Last wallabag version that did not exhibit the issue (if applicable): 2.2.2
* php version: 7.0.27
* OS: Debian Stretch 64-bit
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL/MariaDB

### Steps to reproduce/test case

Install wallabag using the installation instructions for dedicated host and configure the apache2.4 virtualhost as shown in the documentation along with Lets Encrypt for https. Configure the `domain_name` to `https://my.domain.com` and finish the setup.

Open `https://my.domain.com` in the browser and the login page loads without CSS and JS

**Comment by j0k3r** [comment]
Your wallabag instance is pretty old, any chance to update to the latest (2.3.6) and check again?
Thanks

**Comment by lgp171188** [comment]
@j0k3r, I updated to 2.3.6 now from 2.3.2 and even now I see the same issue. Below is my apache2 VirtualHost configuration and it matches the configuration specified in the documentation.

```
<VirtualHost *:443>
    ServerName domain.tld
    ServerAlias www.domain.tld

   # Let's Encrypt SSL configuration here
    DocumentRoot /var/www/wallabag/web
    <Directory /var/www/wallabag/web>
        Require all granted
        <IfModule mod_rewrite.c>
            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ app.php [QSA,L]
        </IfModule>
    </Directory>
    <Directory /var/www/wallabag/web/bundles>
        <IfModule mod_rewrite.c>
            RewriteEngine Off
        </IfModule>
    </Directory>
    <LocationMatch "/register">
         Deny from All
    </LocationMatch>
    ErrorLog /var/log/apache2/wallabag_error.log
    CustomLog /var/log/apache2/wallabag_access.log combined
</VirtualHost>
```
Since I had a doubt that this might be related to the `.htaccess` files not working, I added a `AllowOverride All` directive under the ``wallabag/web` <Directory>` section and it worked. 

So is this a documentation mistake? I'm asking because the apache2 configuration still mentions `AllowOverride None` and the sub-section for apache 2.4 mentions that it, along with a couple of lines after, has to be replaced with `Require all granted`. The default value for the `AllowOverride` directive is `None` and hence that might have been the reason for my issue.

**Comment by andyforceno** [comment]
I'm having this same issue with a fresh install of 2.3.8, 404 errors for files under wallassets so that the login page doesn't display correctly and I can't login. I am using nginx rather than apache.
