### ISSUE TITLE
Cannot fetch Github posts

### ISSUE THREAD

**Issue by Deviad** [wallabag/wallabag#3639]
### Issue details
Cannot fetch correctly not even after trying the described procedure.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package?
Composer

* php version: 7.2
* OS: High Sierra
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Mariadb

### Steps to reproduce/test case

Try to fetch a github post like https://github.com/inversify/InversifyJS/issues/586
![screen shot 2018-04-30 at 09 15 35](https://user-images.githubusercontent.com/2238844/39416642-3b180948-4c57-11e8-86a3-4ef30b5bb5c8.png)

**Comment by Kdecherf** [comment]
Hello,

As long as these pages are more like a forum with comments and several users, what would be the expected result?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by MFYDev** [comment]
it still happens. I wanna permantely archive an issue in github by using wallabag, but it displayed things like this.

Please help.
