### ISSUE TITLE
Can't fetch content from theecologist.org

### ISSUE THREAD

**Issue by ngm** [wallabag/wallabag#3641]
### Issue details

Fetching content from https://theecologist.org/2018/apr/09/hierarchy-climate-change-and-state-nature-symbiosisrev results in an article with no content other than the featured image, and the message

>  wallabag can't retrieve contents for this article. Please troubleshoot this issue. 

I have checked at https://f43.me/feed/test and the article is fetched correctly.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? N/A
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: unknown
* OS: unknown
* type of hosting (shared or dedicated): wallabag.it
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): unknown

### Steps to reproduce/test case

* Add this article to app.wallabag.it: https://theecologist.org/2018/apr/09/hierarchy-climate-change-and-state-nature-symbiosisrev
* Expected result: article added with content
* Actual result: article added without content

**Comment by techexo** [comment]
The article is fetched with full content on the last version of wallabag. Did you try to fetch the article multiple times, or tried to reload it from your wallabag instance ([doc](https://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-try-to-re-fetch-this-article))?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
