### ISSUE TITLE
Export ePub : Call to a member function addIndexPoint() on boolean

### ISSUE THREAD

**Issue by Napator** [wallabag/wallabag#3642]
### Issue details

When i try to export ePub from unread articles, i get after 10-20s a "500 Internal error : Call to a member function addIndexPoint() on boolean"

It seems to depend on the length of the articles to export, when i delete a part of them, if works again.

If i try to export as PDF i get a 504 error, without no other details

### Environment

Account on wallabag.it

### Steps to reproduce/test case

1. Put some long articles in wallabag unread.
2. try to export as ePub

**Comment by j0k3r** [comment]
Can you add the related url which generates that error when exporting

**Comment by Napator** [comment]
I made some try:

Ffor example, if i put theses 2 pages together in unread articles :
https://openclassrooms.com/courses/apprenez-a-creer-votre-site-web-avec-html5-et-css3/pratiquez-5
https://openclassrooms.com/courses/apprenez-a-creer-votre-site-web-avec-html5-et-css3/pratiquez-4

I get the error.

If i let only one article, the export is successful.

I agree theses 2 pages are not usefull to convert in ePub, but these are part of an ensemble, so it took some time to isolate them.

I aslo got the same error with an ensemble of articles from misc websites, but did not try to isolate the problematic pages.

Thank you.

**Comment by Kdecherf** [comment]
Hello,

I can't reproduce the issue on 2.3.7. Do you still encounter it?
