### ISSUE TITLE
Ability to Revoke RSS Tokens and Disable RSS Through Wallabag Interface

### ISSUE THREAD

**Issue by pmciano** [wallabag/wallabag#3643]
At present, it is possible to generate an RSS token through the Wallabag interface (**Config > RSS**), so you can subscribe to your Wallabag queue via an RSS reader. Then, it is possible to regenerate the token, but there is no way to revoke it through the same interface and disable RSS access.

If a user decides they no longer want to use this feature, it may be useful to add this option into the **Config > RSS** settings.

**Comment by j0k3r** [comment]
When you generate a new one, the previous is disabled. So it's kind of token revocation.
But I agree we should offer a way to remove the token.
