### ISSUE TITLE
Username and login

### ISSUE THREAD

**Issue by SansPseudoFix** [wallabag/wallabag#3645]
### Issue details

Login username is not **Name** from `Config > User information` and if you change this one, and you don't remeber your login username… And you have no way to recover it (in web interface at least). So if a user want to log in with his username, 
Login is partially a problem since [we can login with email](https://github.com/wallabag/wallabag/pull/3615) but sill.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2

### Steps to reproduce/test case

* change your **Name** from `Config > User information`
* try to log in with it: you can't and if you don't remember your login username…

Maybe add an input "Login username" in `Config`?

**Comment by tcitworld** [comment]
IIRC the Name in that section is not the same as the username, just a displayed name. Usernames are not meant to be changed (Nextcloud has the same behaviour for example - though it's for other reasons).

**Comment by SansPseudoFix** [comment]
Yup, it's what I tried to say. What I mean is that users sometimes try to connect with this (changed) name, and since it's not the one to log in…

So, maybe add an input with the one we can't change **and** the *displayed* one.

**Comment by Simounet** [comment]
Does anyone knows where this `name` field is used? I thought about the public shared page but even there, it's the username that is displayed. Seems like deprecated to me.
