### ISSUE TITLE
Can't fetch scheuch.de

### ISSUE THREAD

**Issue by tinloaf** [wallabag/wallabag#3649]
### Issue details

Hi. I'm trying to fetch http://scheuch.de/vorsicht-hetze/ - which fails. This is *not* a site config issue - the server doesn't even return any content but replies with "403 Bad Behavior".

The same happens if I try to fetch the content via f43.me, thus I assume that the way the PHP code issues the request is somehow the problem?

### Environment

* wallabag version (or git revision) that exhibits the issue: 
2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? 
Downloading the package, and "make update" to get to 2.3.2
* Last wallabag version that did not exhibit the issue (if applicable):
None that I know of. At least 2.3.0 and 2.3.2 are affected.
* php version:
php5 from Debian package 5.6.33+dfsg-0+deb8u1
* OS:
Debian 8
* type of hosting (shared or dedicated):
dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
MariaDB

### Steps to reproduce/test case

Add http://scheuch.de/vorsicht-hetze/ to your Wallabag.

**Comment by Kdecherf** [comment]
Confirmed on 2.3.3.

The behavior is quite interesting: Wallabag/graby emits a first request which leads to a 403 and re-emits another request with few options which leads to a 200 OK with the actual content.
It seems that the second request is simply discarded.

![2018-09-01-170910_1920x1080](https://user-images.githubusercontent.com/226063/44947221-2a74be00-ae0a-11e8-9035-b10bb27a8327.png)

**Comment by j0k3r** [comment]
I do not have a problem on f43.me 🤔

**Comment by tinloaf** [comment]
Confirmed, f43.me seem to be working by now. Maybe they did update their graby? It doesn't seem like the site fixed their server, since I still can't add it to my wallabag.

**Comment by Kdecherf** [comment]
The issue observed by Wallabag could be linked to the Referer or the custom User-Agent header. Could be fixed by a change to the related site-config. Anyway there's still a bug in Graby which discards the content fetched during the retry.

**Comment by j0k3r** [comment]
There is not so much change in graby used by f43me and wallabag 2.3.3: https://github.com/j0k3r/graby/compare/1.13.4...1.13.5
At least, I didn't see things related to the bug.

Can you play with referer & user-agent?

**Comment by HolgerAusB** [comment]
setting curl/7.4 as user-agent surprisingly worked here
