### ISSUE TITLE
Web: placeholder image for entries without illustration

### ISSUE THREAD

**Issue by gnppn** [wallabag/wallabag#3651]
### Issue details

Hi,

When scrolling the webpages list in the web version, the difference between articles with and without header image bothers me. Could it be possible to have a placeholder image for these pages, to harmonize them? 

Something like this (with a better image) could be good:
![da91cd9f-7b86-4109-a279-ed8c1acda9aa](https://user-images.githubusercontent.com/22668283/40304146-ccf25298-5cf5-11e8-9445-2808c19cf955.png)

Thanks in advance!

### Environment

Wallabag.it (2.3.2)

### Steps to reproduce/test case

Display an webpages list.

**Comment by Kdecherf** [comment]
As a side effect, the placeholder would let us to see labels on articles without illustration as well
