### ISSUE TITLE
GDPR consent pages issue

### ISSUE THREAD

**Issue by kour1er** [wallabag/wallabag#3656]
I'm not sure if this is considered outside of the scope of Wallabag but since 25th of May, sites like https://washingtonpost.com have a consent page requiring the user to opt-in if the user is in Europe. This seems to mean that Wallabag can't download a saved page as there doesn't seem to be a way to get Wallabag to opt-in?

Thanks for any thoughts on this or workarounds

**Comment by kissgyorgy** [comment]
I came to report the same with https://www.thecut.com/
E.g. you can't save the page: https://www.thecut.com/2018/05/how-anna-delvey-tricked-new-york.html

It could be worked around if the browser extension would send the cookies to Wallabag which would then use them when downloading the requested pages. Would not work 100% of the time because of HTTPOnly cookies though.

**Comment by kissgyorgy** [comment]
Would be acceptable for me if I could set cookies manually in Wallabag interface for every site.

**Comment by tinloaf** [comment]
I just had the same problem with https://slate.com 

I wonder whether the paywall system could be leveraged to solve this problem. Basically, wallabag needs to do a HTTP POST (agreeing to the GDPR conditions) before fetching a page. That's the same it does when it logs in to paywalled sites, right? My suggestion would be to have a long checkbox-list of GDPR-walled sites somewhere in the settings, and if you tick a site it means "I consent to their GDPR conditions, please do the I-consent-HTTP-POST for me".

**Comment by j0k3r** [comment]
@tinloaf did you take a look at https://github.com/fivefilters/ftr-site-config/commit/990a605943ea790c283559a7c97d07fecd6b9d27? I don't know if it solve the problem. You should give it a try

**Comment by tinloaf** [comment]
@j0k3r Still doesn't work. It also fails in f43.me's test tool - I even copy-pasted the updated site config from the ftr-site-config repo in case f43.me wasn't up to date.

This is the URL I'm trying to fetch: http://www.slate.com/articles/technology/bitwise/2014/07/roko_s_basilisk_the_most_terrifying_thought_experiment_of_all_time.html

I always just get the GDPR page. However, good to know that site configs can set cookies. Just doesn't seem to work in this case.

**Comment by j0k3r** [comment]
Most of them got fixed in site config.
And if not, you can edit the related site config and force the cookie to bypass GDPR page, see this example for the Time for example:
https://github.com/fivefilters/ftr-site-config/blob/9bff6f80b2c544f9126743c0b115a120703337b6/time.com.txt#L8-L9

**Comment by fghhfg** [comment]
Anyone know how to add cookies on a certain website?

**Comment by Kdecherf** [comment]
@fghhfg please check the previous comment, you can make a pull request to the ftr-site-config repository to add the cookie if you want to make the change 'permanent' for this website or you can simply edit the file locally (_but the change will be erased at each update_).
