### ISSUE TITLE
ios app crashed after registration and login

### ISSUE THREAD

**Issue by wirsel** [wallabag/wallabag#3658]
### Issue details

iOS app for wallabag crashes after registration (with client_id and client_secret) and login (user name and password) with no warning or error description.

### Environment
* I used a 14 day trail account on "https://app.wallabag.it/"
* iOS 11.3.1
* Safari browser on iOS (iPad)

### Steps to reproduce/test case
* Create trial account with username and password on "https://app.wallabag.it/"
* Create client to get client_id and client_secret by following instructions on https://app.wallabag.it/developer/client/create
* install wallabag iOS app (https://itunes.apple.com/de/app/wallabag-2-offiziell/id1170800946) from apple store
* start iOS app on iPad
* follow registration instructions, enter server url (https://app.wallabag.it), former created clien_id/client_secret/username/password - > crash

**Comment by j0k3r** [comment]
This issue was moved to wallabag/ios-app#147
