### ISSUE TITLE
PHP Fatal error:  Uncaught RuntimeException: Setting "piwik_enabled" couldn't be found. in /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php:182

### ISSUE THREAD

**Issue by jinnko** [wallabag/wallabag#3662]
### Issue details

Using wallabag 2.3.2 via the official docker container I'm unable to get a working installation with MySQL.

### Environment

* wallabag version 2.3.2
* docker image wallabag/wallabag:latest (aef794efb513)
* php version: 7.1.15 and 7.2.6
* OS: Alpine Linux in the docker container
* Dedicated server
* MySQL 5.6

### Steps to reproduce/test case

1. On MySQL create a database and user for the container instance to use

2. Populate config in an env-file

```
cat > env.list <<-EOF
SYMFONY__ENV__DATABASE_DRIVER="pdo_mysql"
SYMFONY__ENV__DATABASE_HOST="172.17.0.1"
SYMFONY__ENV__DATABASE_PORT="3306"
SYMFONY__ENV__DATABASE_NAME="wallabag"
SYMFONY__ENV__DATABASE_USER="wallabag"
SYMFONY__ENV__DATABASE_PASSWORD="dbpass"
SYMFONY__ENV__FOSUSER_REGISTRATION=False
SYMFONY__ENV__DOMAIN_NAME="https://wallabag.local"
SYMFONY__ENV__SECRET="envsecret"
POPULATE_DATABASE=True
EOF
```

3. Run the container to create the database tables:

```
docker run -it --rm --env-file env.list wallabag/wallabag:latest migrate
```

4. Run the container normally

```
docker run -it --rm --env-file env.list wallabag/wallabag:latest
```

5. Make a request in a browser and see the errors logged

```
Starting provisioner...
 [WARNING]: Found both group and host with same name: localhost
Provisioner finished.
[02-Jun-2018 21:19:13] NOTICE: fpm is running, pid 207
[02-Jun-2018 21:19:13] NOTICE: ready to handle connections
2018/06/02 21:19:15 [error] 209#209: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Setting "piwik_enabled" couldn't be found. in /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php:182
Stack trace:
#0 /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php(77): Craue\ConfigBundle\Util\Config->createNotFoundException('piwik_enabled')
#1 /var/www/wallabag/vendor/craue/config-bundle/Twig/Extension/ConfigTemplateExtension.php(96): Craue\ConfigBundle\Util\Config->get('piwik_enabled')
#2 /var/www/wallabag/var/cache/prod/twig/b2/b2ed076ea096208791515657de1c778185907df95538a5a4b6efa66c2e6112ab.php(85): Craue\ConfigBundle\Twig\Extension\ConfigTemplateExtension->getSetting('piwik_enabled')
#3 /var/www/wallabag/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_34806d58992d1e92415396d8c0dc93a7e2a6b69ebaadd6037c5428dc75cea4a2->doDisplay(Array, Array)
#4 /var/www/wallabag/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
#5 /var/www/wallabag/var/cache/prod/twig/07/07cfc2e" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://unix:/run/php.sock:", host: "wallabag.ixydo.org"
127.0.0.1 - - [02/Jun/2018:21:19:15 +0000] "GET /login HTTP/1.1" 500 31 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0)Gecko/20100101 Firefox/60.0"
```

I have tried overriding the config file and providing the `piwik_enabled` config item, followed by a `console cache:clear`, but it doesn't fix the issue.

Also reviewed the diff between 2.3.2 and current master and saw no changes that would be related.

**Comment by jinnko** [comment]
I have worked out that the issue here is that the migrate command doesn't initialize the DB correctly.

I was unable to give MySQL root credentials on initial start which was the reason for using the migrate command.  As an alternative I started a local instance with a dedicated MariaDB container, then exported the DB for import into the production instance.  This process resulted in a working installation.

Is there any way to initialize the DB when one doesn't have MySQL root access but does have a DB provisioned?

**Comment by j0k3r** [comment]
You can dump the whole migration using that command:

```
php bin/console doctrine:migrations:migrate --env=prod --write-sql
```

As the doc of that command says "output the migration SQL file instead of executing it".
Might be what you need.
Let us know

**Comment by toadjaune** [comment]
Just had the same issue with a postgresql installation where I had created the SQL user, but not the DB myself. (the user obviously has CREATEDB privileges)

I'm not sure what exactly I did wrong initially, but I think the initial provisioning was interrupted, and manually running the migrations led me to this issue.

I could fix it by dropping the database and leaving the provisioner re-create it from scratch.

**Comment by Nadrieril** [comment]
Just had the same issue on a fresh install on shared hosting. The issue comes from the fact that the `craue_config_setting` table is normally populated by the install script here: https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Command/InstallCommand.php#L280-L285, but on shared hosting I could not run this command and thus couldn't populate the db as needed.
Is there a way to work around this ?

**Comment by Nadrieril** [comment]
The commands from `doctrine:migrations:migrate` only partially populate that table. Notably, `piwik_enabled` isn't set by any migrations.
It would be good if these were set either by a migration, or at first run. Another option might be for `CraueConfigBundle` to not crash when encountering an undefined option, and instead use the default value provided in `wallabag_core.default_internal_settings`.

**Comment by j0k3r** [comment]
Looks like no migration was created when the piwik stuff got merged.
https://github.com/wallabag/wallabag/commit/07643dde08a7cd3f5a556021643e64dd1d5e89f2

**Comment by Nadrieril** [comment]
It's not just the piwik stuff: the table has more than twice as many entries after installation as far as I can recall. But it shouldn't be hard to add all of them

**Comment by Nadrieril** [comment]
I might have a go at it today if I find time

**Comment by Nadrieril** [comment]
I made a PR that adds all missing entries from `wallabag_core.default_internal_settings` in a migration: https://github.com/wallabag/wallabag/pull/3868.

**Comment by najmam** [comment]
Thanks @Nadrieril, your fixed worked for me. For the record, instead of waiting for 2.4 to be released, I ran the migration manually:
```
$ docker container -it wallabag-container /bin/sh
/ # wget https://raw.githubusercontent.com/wallabag/wallabag/b886ee923d7e627da2ae0221271bedbcb495025a/app/DoctrineMigrations/Version20190129120000.php -P /var/www/wallabag/app/DoctrineMigrations/
/ # /var/www/wallabag/bin/console doctrine:migrations:migrate --env=prod
```

**Comment by hanbyul-kim** [comment]
> Thanks @Nadrieril, your fixed worked for me. For the record, instead of waiting for 2.4 to be released, I ran the migration manually:
> 
> ```
> $ docker container -it wallabag-container /bin/sh
> / # wget https://raw.githubusercontent.com/wallabag/wallabag/b886ee923d7e627da2ae0221271bedbcb495025a/app/DoctrineMigrations/Version20190129120000.php -P /var/www/wallabag/app/DoctrineMigrations/
> / # /var/www/wallabag/bin/console doctrine:migrations:migrate --env=prod
> ```

I lost this weekend to fix database problem though, I'm now happy because your trick saved me.
I guess database initialization problem exists for both mariadb and postgres.
