### ISSUE TITLE
Empty content for a saved article

### ISSUE THREAD

**Issue by bnjbvr** [wallabag/wallabag#3665]
### Issue details

A saved article has no content.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? docker
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: ?
* OS: ubuntu
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

### Steps to reproduce/test case

When I try to save the content of the following article to read it later, it is successfully saved (i.e. there's no error), but the content saved in Wallabag is empty (only the header image).

http://unenumerated.blogspot.com/2017/02/money-blockchains-and-social-scalability.html

**Comment by elibadou384** [comment]
I have the impression that the content of this particular blog post is ill-formed: after a `<style> `section it is closing a `<div>` that has not been opened, so terminating the enclosing articleBody `<div>` right at the beginning of the article. That's the reason the article looks empty.
There is many mismatch between tag opening and closing in this page, as it would be with a problematic copy/past of HTML content.
Other blog posts from this website seem OK.

**Comment by techexo** [comment]
I confirm that other articles on this blog can be fetched without an issue ; so it is an isolated case.

**Comment by Kdecherf** [comment]
I'm closing this issue as _won't fix_ considering that it's a content issue.
