### ISSUE TITLE
Cannot add specific URLs to read later

### ISSUE THREAD

**Issue by enginmanap** [wallabag/wallabag#3667]
### Issue details

On different occasions, if I try to add a page to read later, it fails. I checked with different URLs, and verified some URLs can't be saved, while others can. I have a sample URL that I can't save, and the Error message Wallabag returns.

Failing URL: https://www.gamedev.net/forums/topic/663139-evsm-is-the-best-needed/

Error message:

500: Internal Server Error

Type error: Argument 1 passed to Graby\Extractor\ContentExtractor::hasElements() must be an instance of DOMNodeList, boolean given, called in /var/www/wallabag/vendor/j0k3r/graby/src/Extractor/ContentExtractor.php on line 858

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? Package
* Last wallabag version that did not exhibit the issue (if applicable): not sure
* php version: 
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.17.04.1, Copyright (c) 1999-2017, by Zend Technologies
* OS: Ubuntu 17.04
* type of hosting (shared or dedicated): Personal VPS, it has other applications running, and Wallabag is not attached to the root of url. it is under /wallabag/
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Try to add the URL I shared in unread page top bar. It should result in the error message that I shared.

**Comment by j0k3r** [comment]
This issue was moved to j0k3r/graby#151

**Comment by j0k3r** [comment]
Thanks for reporting :+1: 
I've moved the issue in the proper repo

**Comment by enginmanap** [comment]
thanks for the heads up, and great software :)
