### ISSUE TITLE
Randomly stopped working

### ISSUE THREAD

**Issue by STaRDoGG** [wallabag/wallabag#3673]
My WB install has been working fine, and I've made no changes to it. Suddenly when I visit the main page, it's just downloading a file with this as it's contents:

```
<?php

use Symfony\Component\HttpFoundation\Request;

/**
 * @var Composer\Autoload\ClassLoader
 */
$loader = require __DIR__.'/../app/autoload.php';
include_once __DIR__.'/../var/bootstrap.php.cache';

$kernel = new AppKernel('prod', false);
$kernel->loadClassCache();
//$kernel = new AppCache($kernel);

// When using the HttpCache, you need to call the method in your front controller instead of relying on the configuration parameter
//Request::enableHttpMethodParameterOverride();
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);
```

Anyone have this happen before, and/or know what's going on?

Btw, I first tried to go ask this over at the Community forum, but it looks like the cert expired.

https://i.imgur.com/2Ap2EVP.png

### Environment
* Using the Latest wallabag version
* Installed via Softaculous
* php version: 5.6.36
* OS: Linux
* type of hosting (Shared)
* which storage system you choose at install: MySQL

**Comment by j0k3r** [comment]
It's not related to wallabag.
It seems your PHP doesn't run anymore on your server which mean the webserver doesn't know what to do with the php file and then send it to you.

**Comment by STaRDoGG** [comment]
Specifically, which configuration to look at?

**Comment by j0k3r** [comment]
Where you defined the vhost for apache or nginx, etc.
