### ISSUE TITLE
Docker. Styles not loaded.

### ISSUE THREAD

**Issue by kv-gits** [wallabag/wallabag#3676]
### Issue details

Run by the docs:
```
docker run -v /opt/wallabag/data:/var/www/wallabag/data -v /opt/wallabag/images:/var/www/wallabag/web/assets/images -p 80:80 wallabag/wallabag
```

Styles do not work

### Environment
wallabag version - latest from "docker pull"

### Steps to reproduce/test case

run docker container, go to localhost

**Comment by j0k3r** [comment]
This issue was moved to wallabag/docker#115
