### ISSUE TITLE
Saving webpage via Firefox extension with FF Multi-Account Containers

### ISSUE THREAD

**Issue by mrtargaryen** [wallabag/wallabag#3679]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

When attempting to save webpages using the Firefox Wallabag add-on and while FireFox Multi-Account Containers extension is in use, webpages won't save to Wallabag.

### Environment

* wallabag version (or git revision) that exhibits the issue:
app.wallabag.it

* How did you install wallabag? Via `git clone` or by downloading the package?
I use the website

* OS:macOS 10.14.5, FireFox Quantum 61, Wallabag extension 1.4.5

### Steps to reproduce/test case
Using Firefox Quantum on macOS 10.13.5 using the Wallabag extension 1.4.5 and signed in to app.wallabag.it

**Comment by j0k3r** [comment]
Support for wallabag.it should be done using https://www.wallabag.it/en/contact
