### ISSUE TITLE
Docker image, link to database

### ISSUE THREAD

**Issue by GiganteX** [wallabag/wallabag#3680]
Hi!

So, the --link method of connection to a DB is kind of deprecated, if not exactly deprecated yet then soon. At least recommended not to use anymore.  Can I connect to a database by specifying an IP address instead of linked container? I have a MySQL server running on another machine so I want to use that instead of creating a (redundant) MySQL container. Please advice!

And the page on Docker Hub mentions SQLite, but it says on the wallabag website that SQLite is removed? Is the docker image an older version? I can't find a version number on the Docker Hub page. If SQLite is still used I might consider using that instead of MySQL, but if it's on the way out I don't want to start using it and then when the container is updated to the current version find out that SQLite support has been removed.

I hope you can shed some light on this for me! Wallabag is looking real nice, I have been using Pocket for a long time, even back when it was called Read it Later List... but I am getting less and less happy with the UI and functionality changes, so I need a replacement.

**Comment by GiganteX** [comment]
Ok I noticed the SYMFONY__ENV__DATABASE_HOST environment variable. Sounds like that's the ticket for using my own MySQL server. Will try that.

**Comment by j0k3r** [comment]
Did you succeed?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
