### ISSUE TITLE
Does wallabagger work?

### ISSUE THREAD

**Issue by GiganteX** [wallabag/wallabag#3681]
I installed the Wallabagger addon for Chrome. Got a button. Press it, a dialog opens with the text "Loading wallabag API..." or 

The options dialog has a Check URL button. I press it, nothing happens. "Wallabag URL checked" state is "Not checked".

Wallabag API token: Expired.

There's not much else to do...

??

**Comment by GiganteX** [comment]
It worked fine on my own wallabag server though, so that's good.

**Comment by Simounet** [comment]
Sorry but I don't get your last reply. Can we close this issue? If not, can you go to the wallabagger project (https://github.com/wallabag/wallabagger/issues) to open an issue please?

**Comment by j0k3r** [comment]
This issue was moved to wallabag/wallabagger#146
