### ISSUE TITLE
Docker gets stuck

### ISSUE THREAD

**Issue by joshuamallow** [wallabag/wallabag#3682]
### Issue details

I am trying to setup a Wallabag in a Docker environment. 

root@docker-s-1vcpu-1gb-nyc1-01:~# docker run --name wallabag --restart always \                                                 
>   -e "MYSQL_ROOT_PASSWORD=password" \                                                                                        
>   -e "SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql" \                                                                               
>   -e "SYMFONY__ENV__DATABASE_HOST=database" \                                                                                  
>   -e "SYMFONY__ENV__DATABASE_PORT=3306" \                                                                                      
>   -e "SYMFONY__ENV__DATABASE_NAME=wallabag" \                                                                                  
>   -e "SYMFONY__ENV__DATABASE_USER=wallabag" \                                                                                  
>   -e "SYMFONY__ENV__DATABASE_PASSWORD=password" \                                                                      
>   -p 8080:80 wallabag/wallabag                                                                                                   
Unable to find image 'wallabag/wallabag:latest' locally                                                                          
latest: Pulling from wallabag/wallabag                                                                                           
1eae7a7426b0: Pull complete                                                                                                      
e4679db90997: Pull complete                                                                                                      
50928712277e: Pull complete                                                                                                      
95069a64e5db: Pull complete                                                                                                      
Digest: sha256:4919a7c430df86c09220668f3f9c4af1972a1af8f949e24b1a740a220cf62449                                                  
Status: Downloaded newer image for wallabag/wallabag:latest                                                                      
Starting provisioner...                                                                                                          
 [WARNING]: Found both group and host with same name: localhost

### Environment

* wallabag version (or git revision) that exhibits the issue: latest
* How did you install wallabag? Via `git clone` or by downloading the package? Docker
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Trying to install via command above. It gets hung.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
