### ISSUE TITLE
Download images locally isn’t working

### ISSUE THREAD

**Issue by michaelx** [wallabag/wallabag#3687]
### Issue details

Download images locally isn’t working for manually added entries. Worked on initial async import.

prod.log:

`request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /assets/images/f/c/fc06fc7e/1b68afff.png" (from "http://wallabag.lan/")" at /var/www/servers/wallabag.lan/wallabag/var/cache/prod/classes.php line 4243 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /assets/images/f/c/fc06fc7e/1b68afff.png\" (from \"http://wallabag.lan/\") at /var/www/servers/wallabag.lan/wallabag/var/cache/prod/classes.php:4243, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/servers/wallabag.lan/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []`

### Environment

* wallabag version: **2.3.3** (also on 2.3.2)
* install: **git clone**
* php version: **5.6.30**
* OS: **raspbian 8 (Jessie)**
* DB: **MySQL**

### Steps to reproduce/test case

1. Enable image download: Internal Settings > Misc > Download images locally > change to 1
2. Chmod 777 `/wallabag/web/assets/images`
3. Add article with an image, e.g. https://thebolditalic.com/this-is-your-life-in-silicon-valley-two-years-later-b65f450e0f80 or https://ifixit.org/blog/10229/macbook-pro-keyboard/
4. Frontend will give an 404 for the resource

It can be also reproduced on https://www.softaculous.com/demos/wallabag

**Comment by Simounet** [comment]
That's weird, I can't reproduce it but I'm not on PHP5.6 (even if I doubt this is the issue here). Do you still have this issue? Do you have some more log? Can you try to be up-to-date with master?

**Comment by michaelx** [comment]
Unfortunately it seems like it never worked for me. Only on the initial async import (Redis) images got downloaded. Now, whenever I add a new article, most (if not all) images fail with that log. There’s no other error log. I was up to date with master. If I’m really the only one with the problem I can try it on another machine next week.

**Comment by Simounet** [comment]
Do you have an error on the server side about rights maybe?

**Comment by michaelx** [comment]
Not that I’m aware of. I set the rights according to the [Documentation](https://doc.wallabag.org/en/admin/installation/rightaccess.html) and also changed `/wallabag/web/assets/images` to chmod 777. Anything missing?

**Comment by michaelx** [comment]
It was a permission problem after all. Not entirely sure why, as `ls -l` showed what I expected, but `chmod -R 777 web/assets/images` solved it the second time.
