### ISSUE TITLE
Error while processing import Instapaper .csv

### ISSUE THREAD

**Issue by Mession77** [wallabag/wallabag#3689]
### Issue details

I am trying out the Wallabag.it as an alternative for Instapaper, which is offline in Europe because of the GDPR law. The .csv file as generated by Instapaper results in the Wallabag error: Error while processing import. No matter how I change the file, the import fails. My .csv file looks like this:
[instapaper-export.txt](https://github.com/wallabag/wallabag/files/2184019/instapaper-export.txt)

**Comment by j0k3r** [comment]
I tried on the latest version of wallabag locally and I didn't get any errors.
As the problem is related to wallabag.it and not the code itself, I close that issue.

**Comment by fergbrain** [comment]
I was able to solve my self-hosted issue by renaming the .csv as .txt

**Comment by phantomtypist** [comment]
FYI this happens on 2.3.8 running on Ubuntu 16.04 w/ Apache2 and PHP 7.  Same error message/toast notification about error processing import file if the file extension is .csv.  If you rename it to .txt, then it works fine.

**Comment by nsitu** [comment]
I'm having this issue as well. Does anyone know what might be the cause of this on a self hosted wallabag?

**Comment by phantomtypist** [comment]
> I'm having this issue as well. Does anyone know what might be the cause of this on a self hosted wallabag? 

Did you try renaming it to .txt like I said worked for me?

**Comment by nsitu** [comment]
@phantomtypist Yes, it works fine when I rename the file. I would like to understand why my server doesn't accept a csv.

**Comment by phantomtypist** [comment]
> @phantomtypist Yes, it works fine when I rename the file. I would like to understand why my server doesn't accept a csv.

It's not your server per say.  It's the code.  I'd have to walk the code to find it because that's the only thing that makes any sense.  Gotta be a regression because it used to accept csv extensions before.

**Comment by nsitu** [comment]
> > @phantomtypist Yes, it works fine when I rename the file. I would like to understand why my server doesn't accept a csv.
> 
> It's not your server per say. It's the code. I'd have to walk the code to find it because that's the only thing that makes any sense. Gotta be a regression because it used to accept csv extensions before.

I would be eager to find out which part of the code is the culprit. However I do wonder... Is it possible that newer versions of PHP behave differently when it comes to file uploads?

**Comment by phantomtypist** [comment]
@nsitu I'm honestly not sure why the developers closed the issue.  They closed it with the comment it happens on wallabag.it hosted service.... but it happens just compiling their code and self hosting too, LOL.

**Comment by nsitu** [comment]
Based on the thread above, it sounds like the file that @j0k3r "tried" was in fact the instapaper-export.txt linked to by @Mession77  , but we already know that .txt files work. I am curious if a .csv also work on @j0k3r 's "fresh install".
![image](https://user-images.githubusercontent.com/3484202/96789224-c6832a00-13c2-11eb-9b0c-667e75d22eed.png)

**Comment by j0k3r** [comment]
During the import, we are checking the mimetype of the given file:
https://github.com/wallabag/wallabag/blob/5a54434db82300bd821b351b83ae06cf47804d62/src/Wallabag/ImportBundle/Controller/InstapaperController.php#L34
Allowed mimetype are defined here: https://github.com/wallabag/wallabag/blob/57f4f5bb8eb2cfd6fbd759a78d91152bcd338e74/app/config/wallabag.yml#L183

What are the mimetype of the file you are trying to import?
