### ISSUE TITLE
Empty content for a saved article

### ISSUE THREAD

**Issue by xylle** [wallabag/wallabag#3693]
### Issue details

A saved article has no content.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? N/A
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: php7.0
* OS: Debian 9.5
* type of hosting (shared or dedicated): LXC on Proxmox 

* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

When I try to save the content of the following article to read it later, it is successfully saved (i.e. there's no error), but the content saved in Wallabag is empty.

https://blog.mirabellette.eu/index.php?article24/heberger-les-marques-pages-firefox
### Log file:
[prod.log](https://github.com/wallabag/wallabag/files/2195734/prod.log)

**Comment by Kdecherf** [comment]
It seems that Guzzle encodes the query string before sending it (`article24/heberger-les-marques-pages-firefox` => `article24%2Fheberger-les-marques-pages-firefox`) which leads to an infinite redirect.

**Comment by j0k3r** [comment]
It's not relate to Guzzle but graby instead https://github.com/j0k3r/graby/pull/45
