### ISSUE TITLE
2.3.3 is not available on wallabag.org

### ISSUE THREAD

**Issue by X-dark** [wallabag/wallabag#3698]
It seems the release page on the official site is not up to date. It links to the 2.3.2 version.

**Comment by uda** [comment]
It's not on docker hub either

**Comment by j0k3r** [comment]
Yeah I need to update it.

**Comment by j0k3r** [comment]
The release is available https://static.wallabag.org/releases/

**Comment by paintedsky** [comment]
If you follow the ["self-hosted" instructions in the documentation](https://doc.wallabag.org/en/admin/installation/installation.html#installation), which links to [https://wllbg.org/latest-v2-package](https://wllbg.org/latest-v2-package), it also downloads 2.3.2 instead of 2.3.3

**Comment by jrdnlc** [comment]
Looks like the office [docker](https://hub.docker.com/r/wallabag/wallabag/)  also downloads 2.3.2 and not 2.3.3

**Comment by j0k3r** [comment]
We have the same problem for the 2.3.4.
I didn't forget that issue.

**Comment by j0k3r** [comment]
Everything is now fixed.
The 2.3.7 release is up everywhere (except the blogpost which will be available later this week).

If you still have some issue, post a comment.
