### ISSUE TITLE
Adding URL causes SQL insert errors.

### ISSUE THREAD

**Issue by philwrenn** [wallabag/wallabag#3700]
Adding this URL results in a SQL insert error:
https://github.com/priteshrnandgaonkar/react-native-call-detection

I tested this URL by fetching with http://f43.me/feed/test at it works fine. The error message I receive is attached.

[wallabag_error.txt](https://github.com/wallabag/wallabag/files/2263725/wallabag_error.txt)

## Environment

Version: 2.3.2
Installed via Docker container.
MariaDB database backend.

**Comment by tcitworld** [comment]
Was your MariaDB installed using utf8-mb4 encoding ? It's needed to store content with emojis for example.

**Comment by philwrenn** [comment]
Yes, I can confirm the database uses utf8-mb4.
![selection_971](https://user-images.githubusercontent.com/234974/43769731-719f8b72-9a08-11e8-91ab-24e48c90c1de.jpg)

**Comment by tcitworld** [comment]
Does wallabag uses proper utf8mb4 configuration ? The value of `database_charset` must be too `utf8mb4` inside `app/config/parameters.yml`

**Comment by philwrenn** [comment]
@tcitworld `database_charset` was set to `utf8`. I updated it to `utf8mb4` and restarted the application, but still receive the same result.

**Comment by tcitworld** [comment]
Please try to clear the cache at `wallabag/var/cache/prod/*` just to be sure (or something like `bin/console cache:clear -e prod`)

**Comment by philwrenn** [comment]
I deleted everything in `/var/www/wallabag/var/cache/prod/*` and restarted. Still same result when attempting to add that page.

**Comment by tcitworld** [comment]
Any idea @j0k3r ? It works for me with the same environment.

**Comment by philwrenn** [comment]
I used Ansible to setup Wallabag; Attached are the tasks I used. Possibly the environment variables could point to the issue, if you suspect it's something with my environment.

[wallabag_tasks.txt](https://github.com/wallabag/wallabag/files/2276250/wallabag_tasks.txt)

**Comment by philwrenn** [comment]
@tcitworld as you suspected form the start this was a character set issue. I resolved it by adding this to my environment variables in my task: `SYMFONY__ENV__DATABASE_CHARSET: utf8mb4`  I'm not exactly sure why editing `database_charset` in `app/config/parameters.yml` wasn't working; Possibly it was getting reverted when the container restarted.

**Comment by tcitworld** [comment]
Thanks ! Closing here.
