### ISSUE TITLE
Content retrieval from buzzfeed.com

### ISSUE THREAD

**Issue by njean42** [wallabag/wallabag#3703]
### Issue details

Fetching [this article](https://www.buzzfeed.com/gabrielsanchez/ces-photos-montrent-les-braves-hommes-et-femmes-qu?origin=shp) in wallabag doesn't work.
It does work using the [test tool f43.me](https://f43.me/feed/test).

As [advised in the documentation](https://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that), I'm reporting opening this issue since it probably "means there is something internally in wallabag that breaks the parser".

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.2.3**
* How did you install wallabag? : **git clone**
* Last wallabag version that did not exhibit the issue (if applicable): **unknown**
* php version: **5.6.36**
* OS: **debian8**
* type of hosting (shared or dedicated): **dedicated**
* which storage system you choose at install: **MariaDB** (MySQL)

### Steps to reproduce/test case

Try to add [this url](https://www.buzzfeed.com/gabrielsanchez/ces-photos-montrent-les-braves-hommes-et-femmes-qu?origin=shp) to your wallabag instance.

**Comment by shtrom** [comment]
Should be fixed with more recent graby-site-config
