### ISSUE TITLE
No site_config folder available

### ISSUE THREAD

**Issue by adx442** [wallabag/wallabag#3709]
### Issue details

Fresh installation of Wallabag 2.3.3 has no site_config folder available, so I'm unable to add site configuration changes and rules.

### Environment

Wallabag 2.3.3 on Ubuntu 18.04.01, PHP 7.1, dedicated host, installed via git clone.

### Steps to reproduce/test case

Install wallabag from Git on Debian, and search for the site_config folder.  Not found.   Additionally, past notes have indicated that it's in the ./inc/3rdparty folder, which also doesn't exist in my installation (no inc folder at all).

**Comment by j0k3r** [comment]
I guess you are reading an help note form poche instead of wallabag.
Where did you find these information?

**Comment by adx442** [comment]
[Here was one mention](https://github.com/wallabag/wallabag/issues/2487), but there were several throughout the Wallabag Github that mention that folder.  Sounds like it's no longer a part of the configuration, from your reply.  Is there a location to add rules for specific sites/pages within modern Wallabag? 

Thanks for your reply!

**Comment by j0k3r** [comment]
You can put them in `vendor/j0k3r/graby-site-config/` but they will be removed on the next upgrade of your wallabag (as the vendor folder is override on each update.

**Comment by techexo** [comment]
@adx442 As mentioned by @j0k3r, the location for site configuration files is `vendor/j0k3r/graby-site-config` in recent versions of wallabag.
If you want to keep these site-configs between updates, the best thing to do is probably to do a pull request in the main repository (https://github.com/fivefilters/ftr-site-config). The doc will soon be updated with more information on that (https://github.com/wallabag/doc/pull/81).

If it's okay for you, could you close the issue?
