### ISSUE TITLE
Remove response returned by API's delete entry call

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/wallabag#3711]
### Issue details

This issue is a follow up of #3608, failed fix #3516 and https://github.com/wallabag/android-app/issues/646.

When an API client deletes an entry (`DELETE /api/entries/{id}.json`), the server returns the full entry but its id, example:

``` json
{"is_archived":0,"is_starred":0,"user_name":"kdecherf","user_email":"kevin@kdecherf.com","user_id":1,"tags":[],"is_public":false,"id":null,"uid":null,"title":"…
```

The `null` value currently triggers an exception on the Android app, which leads to another side-effect: the client emits two `DELETE` requests for the same entry (see #3608).

It seems that #3516 does not restore the missing id at all.

While checking network packets I saw that the actual content of the entry was also sent. In my case the response to the delete request had a body of 70 KB which may degrade clients' performance on lossy connections.

I don't see any value in sending back the entity when deleting it, so I would like to remove any content sent by this call. The API would then return a `204 No content` for successful deletion, which also fixes https://github.com/wallabag/android-app/issues/646 (_tested here_).

@wallabag/android @wallabag/core do you have any objection?

### Environment

* wallabag version (or git revision) that exhibits the issue: _2.3.3_
* How did you install wallabag? Via `git clone` or by downloading the package? _git_
* Last wallabag version that did not exhibit the issue (if applicable): _N/A_
* php version: _7.0_
* OS: _Debian_
* type of hosting (shared or dedicated): _dedicated_
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): _PostgreSQL_

**Comment by j0k3r** [comment]
Maybe using `clone` instead of a single assignation [here](https://github.com/wallabag/wallabag/pull/3516/files#diff-64a88d0a183a2f7a7721ad46901bd41bR579) could solve the problem?

**Comment by Kdecherf** [comment]
It may fix the issue with the empty id field but does not actually handle the issue with the size of the returned body.

**Comment by j0k3r** [comment]
Does the android app will still work if no content are return?
Also, it breaks BC. So I don't think it might be a solution.
I still prefer to remove the content from the response, it's a less BC than returning nothing.

**Comment by Kdecherf** [comment]
The android app seems to be working like a charm with the `204 No Content` return code.

**Comment by j0k3r** [comment]
Oh. 😳 

So maybe the android app should send an extra arg like `/12/delete?no_data_return=1` and then wallabag will return a 204.

What do you think?
