### ISSUE TITLE
Uncaught Error Kernel.php - Blank Page

### ISSUE THREAD

**Issue by Revisor01** [wallabag/wallabag#3713]
### Issue details

I updated to Ubuntu Mate 18.04 with php 7.2. Now I allways get this Error in my Log.
The Login Page stays blank. Before the Update it works. I completly deleted the Installation and started from zero. Also tried Wallabag Versio 2.3.1.

### Log Status
[php7:error] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\\Component\\HttpKernel\\ctype_digit() in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:272\nStack trace:\n#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(83): Symfony\\Component\\HttpKernel\\Kernel->getName()\n#1 /var/www/wallabag/web/app.php(11): Symfony\\Component\\HttpKernel\\Kernel->__construct('prod', false)\n#2 {main}\n  thrown in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 272

### Environment
* wallabag version: 2.3.3
* Installed via git clone & make install
* php version: PHP 7.2.7-0ubuntu0.18.04.2 (cli)
* OS: Ubuntu Mate 18.04.1 LTS
* type of hosting: Raspberry Pi 3B+
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

It allways throws the error when going to the website.

**Comment by j0k3r** [comment]
Could you try to install the `ctype` php extension?

**Comment by Revisor01** [comment]
I allready installed it. It is installed via php72-common
And when I look into php -i it is enabled.

**Comment by j0k3r** [comment]
Is it enabled for your webserver too?
Could you run `php -r "var_dump(ctype_digit('test'));"` and see what it says?

**Comment by Revisor01** [comment]
It says bool(false)

**Comment by j0k3r** [comment]
Is it enabled for your webserver too?

**Comment by Revisor01** [comment]
Ok. Thx. Back to work.
Disabled and enabled php7.2, reinstalled php7.2-common and restarted apache2 and, that was the main problem I think, restarted php7.2-fpm service. Thx again for the right questions and your help.
