### ISSUE TITLE
Keep original url for redirects

### ISSUE THREAD

**Issue by tdelmas** [wallabag/wallabag#3714]
### Issue details

When saving an url that redirects to another one, the url used for the "open original" feature is the second one, not the original.

It's fine for url shortener services, but when its a Bloomberg article that redirects to https://www.bloomberg.com/tosv2.html , wallabag didn't have the article saved (obviously) but the original url is lost too!

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.3 (framabag.org)

### Steps to reproduce/test case

Save a Bloomberg article. https://www.bloomberg.com/news/articles/2018-09-04/youtube-and-netflix-throttled-by-carriers-research-finds for example.

The "open original link" should open that article, it opens instead https://www.bloomberg.com/tosv2.html
(but after a captcha you may be redirected to the original article)

###

Proposed solutions:
- keep the original and the redirected url
- if the original url is a known url shortener, keep the first redirect ( If https://bit.ly/xx redirect to https://something.com redirects to https://somethingelse.com, keep https://something.com)
- always keep the original

**Comment by j0k3r** [comment]
I think this should fix your issue https://github.com/wallabag/wallabag/pull/3271

**Comment by tdelmas** [comment]
@j0k3r Thank you for pointing it out. That PR certainly goes in the right direction.

It doesn't yet solve this issue yet, but if once that PR is merged, somebody can add an UI to access that given_url and it will solve this issue!

**Comment by Kdecherf** [comment]
Hello there,

There's another field already available, and writable: `origin_url` which was introduced in 2.3.0 via https://github.com/wallabag/wallabag/pull/3346

And there is an ongoing PR for your usecase: https://github.com/wallabag/wallabag/pull/3553 which should be ready in the next three weeks. I'm using this WIP on my own instance.

**Comment by j0k3r** [comment]
Great, can we close that issue then?

**Comment by tdelmas** [comment]
Thank you all for these comments!
