### ISSUE TITLE
Installation fails on a dash-named MySQL database

### ISSUE THREAD

**Issue by nferrari** [wallabag/wallabag#3720]
### Issue details

Installation fails while creating schema on a MySQL/MariaDB database if the database name contains a dash (-).

### Environment

* wallabag version: 2.3.2
* How did you install wallabag? downloading the package
* php version: 2.7.9
* OS: Debian
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

 * Create a dash-named database, and provide it in app/config/parameters.yml
 * launch bin/console wallabag:install -e=prod

### Error

For this example, I created a database named "wallabag_test-tiret" (tiret is the french word for dash). The exact error is returned by doctrine:migrations:migrate, after some successful CREATE TABLE and INSERT INTO:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-tiret CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci' at line 1
  15:26:53 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate --no-interaction=1 --no-debug=1 --env='=prod'". Message: "An exception occurred while executing 'ALTER DATABASE wallabag_test-tiret CHARACTER SET = utf8mb4 COLLATE = utf8mb
  4_unicode_ci;':

Cheers!

**Comment by j0k3r** [comment]
Could you install the 2.3.3 instead?
That issue has been fixed in this version.
https://github.com/wallabag/wallabag/pull/3538

(Sorry the package link in the website hasn't been updated yet...)

**Comment by nferrari** [comment]
Thank you, I missed that issue.
