### ISSUE TITLE
show something in the Config or Settings UI that confirms Wallabag is using redis

### ISSUE THREAD

**Issue by danhimalplanet** [wallabag/wallabag#3722]
I can't figure out if my instance of Wallabag is using redis

I'm using Docker, I've configured my wallabag container to be linked to an instance of redis, named redis.

If I run redis-cli in redis, I don't see any keys.

It would be nice if Wallabag showed that it was using redis.

**Comment by j0k3r** [comment]
wallabag can use Redis only for the queue import system.
And if you enable Redis as the queue import system it'll be displayed in the `/import/` page:

<img width="1000" alt="screen 2018-09-13 a 08 40 28" src="https://user-images.githubusercontent.com/62333/45471235-b2bf6100-b730-11e8-9401-fd87d6899de6.png">
