### ISSUE TITLE
Wallabagger for Firefox not working with self-hosted instance (Docker)

### ISSUE THREAD

**Issue by Sudiukil** [wallabag/wallabag#3723]
### Issue details

I just deployed a Wallabag instance to my server using the official docker-compose. I also use Nginx as a reverse proxy.

Docker compose and Nginx configs [here](https://gist.github.com/Sudiukil/e23ae1e6039d79af562ef7ad1211e4ca).

The web UI and the Android client are working fine but the Wallabagger for Firefox extension does not work. I configured it properly (and successfully) and when I try to bag a page I get the "Saving the page to wallabag..." message forever. The Wallabag icon turns yellow upon clicking and then red. See screenshot bellow.

Looking at the docker-compose logs (when running `up` without the `-d' option) shows me this error when I try to save a page with Wallabagger:

```
db_1        | 2018-09-18 12:17:26 58 [Warning] Aborted connection 58 to db: 'wallabag' user: 'wallabag' host: '172.23.0.3' (Got an error reading communication packets)
wallabag_1  | 2018/09/18 12:17:26 [error] 245#245: *164 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.23.0.1, server: _, request: "POST /api/entries.json HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:3004"
wallabag_1  | 172.23.0.1 - - [18/Sep/2018:12:17:26 +0000] "POST /api/entries.json HTTP/1.0" 502 166 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
```

### Environment

* Version: 2.3.3
* Install method: Docker (docker-compose)
* Last wallabag version that did not exhibit the issue (if applicable): -
* PHP version: 7.2.10 (Docker version, should be irrelevant)
* OS: Debian 8
* Type of hosting: dedicated
* Storage system: MariaDB

### Steps to reproduce/test case

1. Deploy Wallbag with docker-compose and a Nginx reverse proxy as mentioned above
2. Configure the Wallabagger extension for Firefox
3. Try to save a page with it

### Screenshot

![2018-09-18-141657_5120x1200_scrot](https://user-images.githubusercontent.com/5354318/45687452-2dccb100-bb4f-11e8-91bd-236a5b82abee.png)

**Comment by j0k3r** [comment]
Did you got that error with every contents you are trying to save or just some of them?

**Comment by Sudiukil** [comment]
All of them.

**Comment by Sudiukil** [comment]
The only PHP logs I managed to find are the php-fpm ones (`/var/log/php-fpm.log`). The only relevant lines are these two lines, popping when I try to use Wallabagger:

```
[19-Sep-2018 09:23:10] WARNING: [pool www] child 272 exited on signal 9 (SIGKILL) after 12.930096 seconds from start
[19-Sep-2018 09:23:10] NOTICE: [pool www] child 276 started
```

As for Wallabag, the only logs I found are in `/var/www/wallabag/var/logs/prod.log` and there's nothing relevant here (only an unrelated authentication error from yesterday).

**Comment by j0k3r** [comment]
Could you enable debug logging?
https://doc.wallabag.org/en/user/errors_during_fetching.html#enable-log-to-help-us-identify-the-problem

Then retry and check for `wallabag/var/logs/*` again

**Comment by Sudiukil** [comment]
Done, these lines appear in the logs when trying to save a page:

```
[2018-09-19 09:55:47] request.INFO: Matched route "api_post_entries". {"route":"api_post_entries","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\EntryRestController::postEntriesAction","_format":"json","_route":"api_post_entries"},"request_uri":"http://127.0.0.1:3004/api/entries.json","method":"POST"} []
[2018-09-19 09:55:47] app.DEBUG: Restricted access config enabled? {"enabled":0} []
[2018-09-19 09:55:47] graby.DEBUG: Graby is ready to fetch [] []
[2018-09-19 09:55:47] graby.DEBUG: . looking for site config for github.com in primary folder {"host":"github.com"} []
[2018-09-19 09:55:47] graby.DEBUG: Appending site config settings from global.txt [] []
[2018-09-19 09:55:47] graby.DEBUG: . looking for site config for global in primary folder {"host":"global"} []
[2018-09-19 09:55:47] graby.DEBUG: ... found site config global.txt {"host":"global.txt"} []
[2018-09-19 09:55:47] graby.DEBUG: Cached site config with key: github.com {"key":"github.com"} []
[2018-09-19 09:55:47] graby.DEBUG: . looking for site config for global in primary folder {"host":"global"} []
[2018-09-19 09:55:47] graby.DEBUG: ... found site config global.txt {"host":"global.txt"} []
[2018-09-19 09:55:47] graby.DEBUG: Appending site config settings from global.txt [] []
[2018-09-19 09:55:47] graby.DEBUG: Cached site config with key: global {"key":"global"} []
[2018-09-19 09:55:47] graby.DEBUG: Cached site config with key: github.com.merged {"key":"github.com.merged"} []
[2018-09-19 09:55:47] graby.DEBUG: Fetching url: https://github.com/wallabag/wallabag/issues/3723#issuecomment-422730669 {"url":"https://github.com/wallabag/wallabag/issues/3723#issuecomment-422730669"} []
[2018-09-19 09:55:47] graby.DEBUG: Trying using method "get" on url "https://github.com/wallabag/wallabag/issues/3723" {"method":"get","url":"https://github.com/wallabag/wallabag/issues/3723"} []
[2018-09-19 09:55:47] graby.DEBUG: Use default user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.92 Safari/535.2" for url "https://github.com/wallabag/wallabag/issues/3723" {"user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.92 Safari/535.2","url":"https://github.com/wallabag/wallabag/issues/3723"} []
[2018-09-19 09:55:47] graby.DEBUG: Use default referer "http://www.google.co.uk/url?sa=t&source=web&cd=1" for url "https://github.com/wallabag/wallabag/issues/3723" {"referer":"http://www.google.co.uk/url?sa=t&source=web&cd=1","url":"https://github.com/wallabag/wallabag/issues/3723"} []
```

**Comment by j0k3r** [comment]
Nothing more?

**Comment by Sudiukil** [comment]
Nope, that's the only lines appearing when I try to save a page using Wallabagger.

**Comment by Sudiukil** [comment]
I though maybe it could be an issue with the reverse proxy but I tried without it, nothing changes (same issue, same errors)

**Comment by j0k3r** [comment]
Yeah I though too.
I'm out of question.
I won't be able to help you more.
Looks like the PHP process is dying while handling the request but we didn't know why so it'll be hard to fix 😕

**Comment by burkemw3** [comment]
I am experiencing similar behavior (502s on adding content, (104: Connection reset by peer) while reading response header from upstream, debug logs end after "Use default referer" message). I can save content with HTTP scheme (e.g. http://neverssl.com) but get the error on HTTPS content (e.g. https://github.com/wallabag/wallabag/issues/3723).

I am running wallabag/wallabag image c3928aced495 on Ubuntu 14.04.5 LTS with docker 1.6.2 with the command `docker run -v /opt/wallabag/data:/var/www/wallabag/data -v /opt/wallabag/imagesvar/www/wallabag/web/assets/images -p 8090:80 -e SYMFONY__ENV__DOMAIN_NAME=http://192.168.1.10:8090 wallabag/wallabag`

**Comment by mqus** [comment]
I have the same issue even without docker, For more details, see #3724 .

I finally found the logs in `/var/lib/wallabag/var/logs/prod.log` : https://pastebin.com/S9R5rEq8

This part of the logs signals one attempt of the wallabag android app to upload an article, which will fail by segfaulting the php process.

**Comment by burkemw3** [comment]
I connected to a running instance (`sudo docker exec -i -t $HASH /bin/sh`) and played around more tonight. A simple php script for fetching HTTPS content that I ran in the terminal (`php ssl.php`) just output "Killed" with return code 137. Most cases look like this is Linux killing processes for Out of Memory (OOM). There's nothing in dmesg, though, as search results say there should be. (I'm also not sure dmesg is working correctly on the wallabag-docker instance. I can't write additional messages via /dev/kmsg.)

I ran wallabag/wallabag:2.3.2 and did not have this issue. I was able to save content from https schemes

ssl.php:
```php
<?php
require 'vendor/autoload.php';
$client = new GuzzleHttp\Client();
$res = $client->get('https://example.com');
echo $res;
?>
```

**Comment by Sudiukil** [comment]
@mqus I have the same issue with Pocket imports, it's most likely related, yes.

@burkemw3 My googling on the subject also lead me to think it could be a memory related issue. I tried to tweak PHP(-FPM) memory settings and all but nothing worked. I might have missed something though.

**Comment by mqus** [comment]
afaik, the oom killer only kills (not segfaults) starving processes after a bit of time. In my case there was enough memory (700mb of RAM and 10g of swap) and cpu power left and the php process exited immediately. These are all no signs of starvation but a 'simple' reproducible program error. I'll try googling some more, though.

**Comment by Sudiukil** [comment]
Yeah same here, the process exits immediately and I have enough free mem and CPU power.

The weird thing though is that Wallabag is working perfectly when I install it locally (still using Docker), I encounter the issue only on my server.

**Comment by DonHugo69** [comment]
Similar to @mqus  I experience the issue on my little home server with Arch Linux:

### **Issue details**

**Environment**
- wallabag version (or git revision) that exhibits the issue: 2.3.3
- How did you install wallabag? Via git clone or by downloading the package? via installing the aur-package
- Last wallabag version that did not exhibit the issue (if applicable): -
-  php version:7.2.10
- OS: ArchlinuxARM on Odroid HC2
- type of hosting (shared or dedicated):dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

- Nginx is used and configured according to the official recommendations
- Nextcloud is also running on the same server, no issues there
- Redis is installed and running

**Examples**
- No site can be fetched via the android app (even though it can open saved articles)
- Works: https://medium.com/@Drowzy/tramp-in-spacemacs-ef82b9e703ee
- Does not work: https://wiki.archlinux.org/index.php/Redis

My first idea was that it does not work for sites which have a lot of media content and/or pictures but for me it seems to be random which site can be saved and which not.

I am new to servers and self-hosting, so if anyone could point me towards potential log files or how to debug tutorials I would be glad to try to help. There should be something somewhere indicating why the process dies...

**Comment by rolisz** [comment]
I have the same issue. I am running the Docker version on a Synology NAS and I get this error only on https pages. Http pages are added fine.

**Comment by revelous** [comment]
Same issue here on Docker. I wasn't able to get any more interesting debug than what @Sudiukil already provided: mine looks the same. It seems it may be related to HTTPS? As an example, http://example.com works, but https://example.com does not (502 in web interface).

**Comment by gruentee** [comment]
@j0k3r Why is this issue closed? I don't see it resolved. I'm still experiencing it on plain install using git version 2.3.3

**Comment by j0k3r** [comment]
Did you try using the 2.3.4 instead?

**Comment by gruentee** [comment]
I just did, sadly the issue remains.

**Comment by j0k3r** [comment]
Could you open an issue on the docker repo instead?
Put a lot of more information, what you tried, error log, docker version, etc, etc.

**Comment by gruentee** [comment]
I'm using the "plain git install" (no container), so I guess the issue might be more appropriate here, right? ;-)

Thanks for your continued efforts, wallabag is very useful to me.
