### ISSUE TITLE
wget not fetching the latest version

### ISSUE THREAD

**Issue by STaRDoGG** [wallabag/wallabag#3728]
According to the upgrade instructions at:
https://doc.wallabag.org/en/admin/upgrade.html

It says to run this to fetch the latest release:
`wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package`

I ran it in CygWin and it fetched the previous version 2.3.2; while the latest release shown here is 2.3.3?
https://github.com/wallabag/wallabag/releases

Also, any chance of making it easier to install updates right from within WallaBag (like WordPress does for it's updates for example), rather than having to manually unpack and upload, and individually run the db migrations as shown on that update instruction page?

Btw, just a heads-up, I just noticed when trying to add the upgrade instructions page to my WallaBag it errors:

![image](https://user-images.githubusercontent.com/1524526/46209002-29905880-c2f2-11e8-9b03-228f621f5696.png)

**Comment by j0k3r** [comment]
Yeah I know I need to update the link, see https://github.com/wallabag/wallabag/issues/3698
As of now, this is the simplier solution we found. We are not as many developer as Wordpress as to build such a better tool to update wallabag, sorry.

**Comment by STaRDoGG** [comment]
@j0k3r I just uploaded all the files for 2.3.3 over 2.3.2; I can't really tell if there are any db changes I need to manually make?

I emptied the browser cache and reloaded a few pages and no errors; but on the About page it still says 2.3.3. Do I need to manually empty a cache via SSH in order to get the updated pages to load?

**Comment by j0k3r** [comment]
There is no migration between patch release, only between minor release.
You might need to reset your cache `php bin/console cache:clear -e=prod`
