### ISSUE TITLE
Create token API giving 400 Bad Request!

### ISSUE THREAD

**Issue by msubhash** [wallabag/wallabag#3729]
I am following up documentation on "How to create my first application" https://app.wallabag.it/developer/howto/first-app

I created the new client and got client id and secret. I am running following curl to get token:

 curl  -X POST "http://v2.wallabag.org/oauth/v2/token" -d "grant_type=password" -d "client_id=<client_id>" -d "client_secret=<client_secret>" -d "username=<user_name>" -d "password=<password>"

Getting following response.
------------------------ REsponse --------------------------
<body>
    <div id="page">
        <div id="header" class="status4xx">
            <h1>ERROR 400 - Bad Request!</h1>
        </div>
        <div id="content">
            <h2>The following error occurred:</h2>
            <p>You have used invalid syntax.</p>
                        <P>Please contact the webmaster with any queries.</p>
        </div>
        <div id="footer">
            <p>Powered by <a href="http://www.ispconfig.org">ISPConfig</a></p>
        </div>
    </div>
</body>

**Comment by j0k3r** [comment]
Why are you calling `http://v2.wallabag.org/oauth/v2/token`?

**Comment by msubhash** [comment]
I want to use the hosted wallabag service to add articles via API. I read the documentation and example on dashboard (https://app.wallabag.it). It mentions about calling get token API http://v2.wallabag.org/oauth/v2/token. I found errors while calling API.

I think i should not have come to github for this question since i am not using self-hosted.

**Comment by j0k3r** [comment]
`v2.wallabag.org` were the first url for the v2.
It's not dead and you should use `app.wallabag.it` instead.
