### ISSUE TITLE
Failed to fetch article from blog.strava.com

### ISSUE THREAD

**Issue by mart-e** [wallabag/wallabag#3730]
### Issue details

Trying to fetch an article on strava's blog and getting [an empty page](https://user-images.githubusercontent.com/564822/46286786-b5b7af80-c580-11e8-8521-87a79a158856.png).

Tried on https://f43.me/feed/test and, while the result is [not great](https://user-images.githubusercontent.com/564822/46286908-3080ca80-c581-11e8-8b88-4673e2057783.png), it does fetch the content.

I just made a try on wallabag.it (I was suspecting my ageing PHP), I got a [slightly better result](https://user-images.githubusercontent.com/564822/46286797-c5cf8f00-c580-11e8-8de6-a847e56e1bf9.png) (the first image) but still an error.

### Environment

* wallabag version : 2.3.3
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): NA
* php version: 5.6.38
* OS: debian
* type of hosting (shared or dedicated): dedicated

### Steps to reproduce/test case

https://blog.strava.com/galleries/racing-100-miles-why-it-is-not-about-the-running/
Getting an empty page.
When trying to reload, got a message "Entry reloaded but fetching content failed"

[`prod.log` content](https://gist.github.com/mart-e/7197555871277463b484cc118abe1918)

Thank you

**Comment by j0k3r** [comment]
As it works on f43.me it should work in the upcoming version.
While there is no site_config defined for the strava blog, you can create a one to improve the parsing.

**Comment by mart-e** [comment]
@j0k3r is it possible to change the styling in the site config? Do you know some documentation about that?
Here, for an unknown reason, the first section is inside a `h2` tag.

**Comment by j0k3r** [comment]
The only documentation we have it here: http://help.fivefilters.org/customer/portal/articles/223153-site-patterns
And you can use that tool to create the site_config: http://siteconfig.fivefilters.org/

Maybe it's a `h2` because there is an empty tag just before ? `<h2 class="aligncenter "></h2>`

**Comment by Kdecherf** [comment]
Note: I don't see this issue on my own 2.3.3 install.

**Comment by mart-e** [comment]
@Kdecherf you can correctly parse the strava article on your side? Could you share your logs to compare?

**Comment by techexo** [comment]
The article is fetching OK on my wallabag instance too, except for the ugly h2 issue. For a reason I do not explain, when the `<h2 class="aligncenter"></h2>` is here and empty, the following `<p>...</p>` are considered also titles and not text.

I tried to create a siteconfig replacing `<h2 class="aligncenter"></h2>`  with `<br />`, but it is not taken into account at all by the parser...

```
tidy: no
prune: no
title: //h2[@class='post-title']
find_string: <h2 class=\"aligncenter\"></h2>
replace_with: <br />

test_url: https://blog.strava.com/galleries/racing-100-miles-why-it-is-not-about-the-running/
```

**Comment by techexo** [comment]
I reckon there is an issue in _php-readability_, or in _graby_. See issue https://github.com/j0k3r/php-readability/issues/39 for the minimal misinterpreted code that I could figure.
