### ISSUE TITLE
docker/php Dockerfile is deprecated since php:fpm use latest php version

### ISSUE THREAD

**Issue by davidmohamedfr** [wallabag/wallabag#3732]
### Issue details

I just noticed that when I try to build dev environnement with docker stack, it broke since php:fpm is now php 7.2 and there's several deprecated/removed extension called during image building.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.3
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.2
* OS: 
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

git clone the repository
execute `docker-compose build`

**Comment by j0k3r** [comment]
Hello David, welcome on GitHub :tada: 

You should use https://github.com/wallabag/docker instead as defined in the documentation https://doc.wallabag.org/en/developer/docker.html

I don't really know why we left the docker folder in wallabag as we have a dedicated repository for that. I think we should better remove it.
