### ISSUE TITLE
Wallabag on Ubuntu Server 18.04LTS shows an apache listing

### ISSUE THREAD

**Issue by bchauvin** [wallabag/wallabag#3736]
### Issue details
Installed wallabag on an Ubuntu Server 18.04 LTS (PHP 7.2) following the dedicated server procedure.
Everything looks ok during the make install phase.
When enabling the site and accessing it all that appears is an apache file listing.

![screenshot from 2018-10-07 03-41-05](https://user-images.githubusercontent.com/4656125/46577396-2fb7c080-c9e7-11e8-9201-e3716abc3dfa.png)

Checked:
- Requirements => OK
- Database connection => OK, db can be reset during make install phase
- chown => OK, everything belongs to www-data
- chmod => I tried a chmod -R 770 and even 777 but did not help
- Logs => /var/log/apache2/wallabag_error.log is empty

### Environment

* wallabag version: 2.3.3
* How did you install wallabag? Via `git clone` or by downloading the package?: git clone directly in /var/www using a sudo -H -u www-data to make sure things were not run as root
* Last wallabag version that did not exhibit the issue (if applicable): Did not try on another version, but installed it on an Ubuntu Server 16.04LTS using PHP 7.0 some time ago and everything went fine. Only difference between the two machines is that the one running 18.04 does not have php-mcrypt (removed from PHP 7.2 and not listed as a requirement in the doc).
* php version: 7.2
* OS: Ubuntu Server 18.04 LTS
* type of hosting (shared or dedicated): dedicated 
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB (10.1)

### Steps to reproduce/test case

* cd /var/www
* git clone wallabag
* cd wallabag
* install composer locally by copying composer-setup and running php composer-setup.php
* make install => all is ok
* setup vhost for apache2 as described in doc
* enable site for wallabag 
* visit url

**Comment by bchauvin** [comment]
Found the issue source: it was a problem with virtualhost config.

**Comment by virtadpt** [comment]
What was the exact problem, so it can be documented for later?

**Comment by bchauvin** [comment]
My installation of ampache and wallabag keep conflicting: either wallabag takes over and ampache is not accessible, or ampache wins and wallabag ends up showing the listing as seen above.

Only solution that worked so far is to declare them on separate domains.
