### ISSUE TITLE
Fresh install with strange errors

### ISSUE THREAD

**Issue by sigmap** [wallabag/wallabag#3737]
### Issue details
`composer install` with pdo_mysql asks for database socket, does mysql/mariadb need a socket? Entering null gives ```Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table ``` as an error trying to access wallabag for the first time.

### Environment

* wallabag version that exhibits the issue: 2.3.3
* How did you install wallabag? downloading the package
* php version: 7.2.9
* OS: Windows 7 64bit
* type of hosting (shared or dedicated): shared on vhost
* which storage system you choose at install: MySQL/MariaDB

### Steps to reproduce/test case

`composer install`

`parameters.yml` ```
parameters:
    database_driver: pdo_mysql
    database_driver_class: null
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: xxxxx
    database_path: null
    database_table_prefix: wall_
    database_charset: utf8mb4
    domain_name: 'https://wall.localhost'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    database_socket: 3306

**Comment by j0k3r** [comment]
Did you follow steps to install wallabag?
https://doc.wallabag.org/en/admin/installation/installation.html

**Comment by sigmap** [comment]
`wget https://wllbg.org/latest-v2-package`
extracted to and cd into `wallabag-2.3.3`
ran `composer install`
answered all prompts for `parameters.yml`

the section [on shared hosting](https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting) could be written as a more step by step rather than putting step 4 first.

**Comment by j0k3r** [comment]
Feel free to make the change to a more step by step: https://github.com/wallabag/doc/blob/master/en/admin/installation/installation.md

And no, MySQL doesn't need a socket, you should leave that field empty. In your parameters.yml, edit `database_socket: 3306` to `database_socket: ~`

**Comment by sigmap** [comment]
I tried that and `null`. Still get an error.
```
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag.wallabag_craue_config_setting' doesn't exist ```

**Comment by j0k3r** [comment]
Which steps did you forgot in your previous installation then?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
