### ISSUE TITLE
Wallabag Service Not Found - Check URL (Android APP)

### ISSUE THREAD

**Issue by andre-faria** [wallabag/wallabag#3738]
### Issue details

Can't connect to Wallabag server with Android App, Using the browser it work as usual, I'm using a self-signed certificate (installed locally at my android too).

### Environment

2.1.6-1201-g0f5c15d
via git clone
N/A
7.0.32
Ubuntu 16.04.5
Dedicated
MySQL
Android, with App version 2.0.2 (106)

### Steps to reproduce/test case

Testing connection in Wallabag App via connection wizard  or Autofill (Test connection and fill in client ID and client secrer).

**Comment by j0k3r** [comment]
I think issue should better be on the Android repo instead https://github.com/wallabag/android-app

**Comment by andre-faria** [comment]
@j0k3r how could I make sure that is a problem with app and not with my Wallabag installation?

I will open a thread there, thanks

**Comment by andre-faria** [comment]
I was using a old version of wallabag.
