### ISSUE TITLE
Pocket import sends entries to queue, but never imports the entries

### ISSUE THREAD

**Issue by alisynthesis** [wallabag/wallabag#3741]
### Issue details

* Pocket API key appears to be working, as hitting the import button redirects to my Wallabag dashboard and pops up a message that says "332 entries in queue"
* Pocket app has add, modify, and retrieve permissions
* I've waited several hours between attempts to see if the queue is a bit slow, but still no new articles.

### Environment

* hosted wallabag.it trial account

**Comment by j0k3r** [comment]
As stated on Twitter few days ago: https://twitter.com/wallabagit/status/1041937680752435200

Workers aren't stable at the moment on wallabagit platform. We are working on it.
Don't worry about your articles, they'll be imported. The queue has 45k items at the moment.

**Comment by j0k3r** [comment]
The queue is empty now.

**Comment by alisynthesis** [comment]
Thanks!
