### ISSUE TITLE
500: Internal Server Error with Medium page

### ISSUE THREAD

**Issue by TofPlay** [wallabag/wallabag#3742]
### Issue details

When I try to save medium articles that generate error 500

### Environment

* wallabag version: 2.3.2
* Docker version

### Steps to reproduce/test case

1. Open page https://medium.com/@ajvanderlee/measure-the-performance-of-code-in-swift-6377b8c135b9
2. Try to add this page on Wallabag

**Comment by TofPlay** [comment]
I try to upgrade to 2.3.3
Run the command: 
```
/var/www/wallabag/bin/console doctrine:migrations:migrate --env=prod --no-interaction`
```
I also try to reset the database like it's the fist time I start Wallabag

I always have the error 500
```
500: Internal Server Error
An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, is_archived, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, origin_url, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)....'
```

**Comment by j0k3r** [comment]
Can you give me the full error please?

**Comment by TofPlay** [comment]
@j0k3r sure! 🙂
[Wallabag - 500 Internal Server Error.txt](https://github.com/wallabag/wallabag/files/2472086/Wallabag.-.500.Internal.Server.Error.txt)

**Comment by j0k3r** [comment]
I was almost sure of what will be in your log, please check the doc: https://doc.wallabag.org/en/admin/common_errors.html#incorrect-string-value-with-mysql

**Comment by TofPlay** [comment]
@j0k3r thanks for your help
Just a quick question: I'm using the docker version of wallabag how I'm supposed to set? 
```
[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```
Why is not already set in the docker image?!?!

**Comment by Strubbl** [comment]
Somebody should set that. You can set it with environment variables to the database docker.

**Comment by Strubbl** [comment]
hmm, there is also the PR https://github.com/wallabag/docker/pull/119 besides my new PR in https://github.com/wallabag/docker/pull/127

**Comment by TofPlay** [comment]
@j0k3r It works 👍 🙂
On the other hand the extraction of the articles in medium does not recover everything but it is another story
