### ISSUE TITLE
Filtering by tag only works for a single tag

### ISSUE THREAD

**Issue by y-muller** [wallabag/wallabag#3744]
### Issue details
The API /api/entries.json?&tags=... does not filter the articles by tags as expected.
According to the documentation the tags are a coma separated list URL encoded.
If only one tag is provided, entries matching the tag are returned.
If 2 or more tags are provided, there is a valid reply from the server but it does not contain any article.

I tried 
/api/entries.json?&tags=news%2Ctest
/api/entries.json?&tags=news,test
and a few variations.

If I am not using the correct syntax then the documentation is not clear enough.

### Environment
Wallabag 2.3.2 (on wallabag.it)
Also tested on 2.2.3 where is returns results for the last tag in the list

### Steps to reproduce
Save articles on the server with a least 2 tags, eg test1 and test2.
Call /api/entries.json?&tags=test1%2Ctest2
No article returned in the reply.

**Comment by j0k3r** [comment]
Duplicates #1197
