### ISSUE TITLE
Can't anymore protect wallabag web access with the apache2 auth access module

### ISSUE THREAD

**Issue by Massedil** [wallabag/wallabag#3749]
### Issue details

Thanks to #2768, adding `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` also solves the API problem for me (apache2 version `2.4.10`).

But, before, I was using [apache2 auth access module](https://httpd.apache.org/docs/2.4/howto/auth.html) to protect my wallabag website :

```
<Directory "web">
  AuthType Basic
  AuthName "Restricted Files"
  AuthBasicProvider file
  AuthUserFile "/aaa/bbb/ccc"
  Require user user_1

[...]
```

To have the API/AndroidApp working, I had to disable it.

I think there is a conflict with the `Authorization` header used by the apache2 auth access module and `Authorization` header used by the API.

Do you know how I can use both ?

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? downloading the package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6.38
* OS: Debian Jessie
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

**Comment by j0k3r** [comment]
From my POV it's not an issue related to wallabag but to Apache. You should better ask that question on https://serverfault.com/ for example.
But if someone got an idea here, comment will still be allowed.
But I'm closing the issue.
