### ISSUE TITLE
2FA using OTP (Google Authenticator)

### ISSUE THREAD

**Issue by 74cmonty** [wallabag/wallabag#3753]
### Feature request

Many web services with offer 2FA OTP using another app for key generation (e.g. Google Authenticator).
Hereby the security level is increased as 2 different applications are required to authenticate.
Furthermore this would allow user authentication in case smtp is not working.

Could you enhance the 2FA functionality in wallabag with this?

THX

**Comment by j0k3r** [comment]
Dup https://github.com/wallabag/wallabag/issues/2822
