### ISSUE TITLE
Site Conflict: Can't fetch article from freedom.press 

### ISSUE THREAD

**Issue by slavniyteo** [wallabag/wallabag#3761]
Hi. I try wallabag and it seems nice. Thank you for your work here.

### Issue details

Wallabag fails to fetch this [article](https://freedom.press/training/everything-you-wanted-know-about-media-metadata-were-afraid-ask/) from https://freedom.press.

The log produced in _debug_ mode and the part of article wallabag is able to fetch are [here](https://gist.github.com/slavniyteo/9a78ebd447370345829775e3fa1d64b5).

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.3.3**
* How did you install wallabag: **docker image** `wallabag/wallabag:2.3.3`
* type of hosting (shared or dedicated): **dedicated**
* which storage system you choose at install: **PostgreSQL**

**Comment by j0k3r** [comment]
Did you try to [fix it yourself](http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that)?

**Comment by slavniyteo** [comment]
Yes, I tried.

Internal parser do the job fine, but external fails and fetch only a part of the article (exactly the same part as wallabag do).

Obviously, the thing is around their weird DOM structure, but I'm not good enough in creating site-configs to fix it myself.

**Comment by j0k3r** [comment]
wallabag use the internal parser defined in f43me which means if it works with the internal parser it'll work in wallabag (I say _will_ because f43me is getting update faster than wallabag)
