### ISSUE TITLE
Trouble writing first site_config for lesswrong.com

### ISSUE THREAD

**Issue by Najrim** [wallabag/wallabag#3767]
I'm trying to make a site_config for lesswrong.com. I'm trying it out at f43.me. (Can I try it locally? Will my site_config that I place in `.../graby-site-config/` be used next time I press "re-fetch content" in Wallabag?)

This is the site_config:

```
title: //h1[contains(@class, 'PostsPage-title')]
body: //div[contains(@class, 'PostsPage-mainContent')]

#title: /html/body/div/div/div[2]/div/div[3]/div[3]/div[1]/h1
#body: /html/body/div/div/div[2]/div/div[3]/div[3]/div[2]/div[2]
```

I've tried both the top and the bottom version and both result in: "Warning: We failed to make this item readable, the default text from the feed item will be displayed instead." I really can't figure out what's wrong. (The bottom version is of course not ideal but it should work for the specific article I'm trying at least). The article I'm testing with is [this](https://www.lesswrong.com/posts/XSKQLeQnBupFo7GGC/coordination-problems-in-evolution-eigen-s-paradox).

Am I making something obviously wrong? I haven't tried anything like this before. I'm just following the documentation from [wallabag](https://doc.wallabag.org/en/user/errors_during_fetching.html) and [fivefilters](https://help.fivefilters.org/full-text-rss/site-patterns.html). In the bottom version I'm getting the XPath from "Copy XPath" in the Firefox Inspector.

**Comment by j0k3r** [comment]
You can try by placing the new file named `lesswrong.com.txt` in `vendor/j0k3r/graby-site-config` and then hit "re-fetch content".
Can you provide a link to an article of that website, so I can try on my side?

**Comment by j0k3r** [comment]
I've just checked about it on f43.me using the debug tab on the result page and I guess there is a problem while fetching the content.
It returns:
> "body": "(only length for debug): 3930",

Which seems pretty short for the whole article.
That might explain why all your xpaths don't work.

**Comment by Najrim** [comment]
Yes, just copying the "body" section when looking at the HTML of the page gives me about 39000 characters. Can we get around this? I don't see how it can fail in the first place. The content is all there in the plain HTML of the page.

**Comment by j0k3r** [comment]
Here is the html we retrieve :thinking: 

```html
<!DOCTYPE html>
<html>
<head>
  <script id=\'serverTimezoneOffset\' type=\'application/ejson\'>{"offset":0}</script>


  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/packages/vulcan_forms/lib/stylesheets/style.scss.css?hash=f716b4d769ab09e764b530ee67f9805895cd2b5a">
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/packages/vulcan_forms/lib/stylesheets/datetime.scss.css?hash=b016fd5b55fbbc7c7104cdfc80a1d756d4f1d515">
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/packages/vulcan_admin/lib/stylesheets/style.scss.css?hash=565b7bfdf7141bdf018c2274f4e0f64f37663e9f">
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/packages/vulcan_embed/lib/stylesheets/embedly.scss.css?hash=befe7d83d858ba91ed003d50451a56660c565d51">
  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/packages/lesswrong/styles/main.scss.css?hash=0a6c3acb6586aab43d7d738d3efdd24679d15c2e">

</head>
<body>
  <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.8.1-beta.0%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%22title%22%3A%22LessWrong%22%2C%22tagline%22%3A%22A%20community%20blog%20devoted%20to%20refining%20the%20art%20of%20rationality%22%2C%22logoUrl%22%3A%22https%3A%2F%2Fres.cloudinary.com%2Flesswrong-2-0%2Fimage%2Fupload%2Fv1498011194%2FLessWrong_Logo_skglnw.svg%22%2C%22logoHeight%22%3A%2250%22%2C%22logoWidth%22%3A%22200%22%2C%22faviconUrl%22%3A%22https%3A%2F%2Fres.cloudinary.com%2Flesswrong-2-0%2Fimage%2Fupload%2Fv1497915096%2Ffavicon_lncumn.ico%22%2C%22requirePostsApproval%22%3Afalse%2C%22requireViewInvite%22%3Afalse%2C%22requirePostInvite%22%3Afalse%2C%22autoSubscribe%22%3Afalse%2C%22emailNotifications%22%3Atrue%2C%22postInterval%22%3A20%2C%22RSSLinksPointTo%22%3A%22post%22%2C%22commentInterval%22%3A20%2C%22maxPostsPerDay%22%3A10%2C%22startInvitesCount%22%3A5%2C%22postsPerPage%22%3A10%2C%22siteImage%22%3A%22https%3A%2F%2Fres.cloudinary.com%2Flesswrong-2-0%2Fimage%2Fupload%2Fv1503704344%2Fsequencesgrid%2Fh6vrwdypijqgsop7xwa0.jpg%22%2C%22language%22%3A%22en%22%2C%22locale%22%3A%22en%22%2C%22googleAnalytics%22%3A%7B%22apiKey%22%3A%22UA-60844744-4%22%7D%2C%22googleMaps%22%3A%7B%22apiKey%22%3A%22AIzaSyA3C48rl26gynG3qIuNuS-3Bh_Zz9jFXkY%22%7D%2C%22twitterAccount%22%3A%22foo%22%2C%22facebookPage%22%3A%22http%3A%2F%2Ffacebook.com%2Ffoo%22%2C%22runVoteMigration%22%3Afalse%2C%22embedProvider%22%3A%22builtin%22%2C%22algolia%22%3A%7B%22appId%22%3A%22Z0GR6EXQHD%22%2C%22searchKey%22%3A%220b1d20b957917dbb5e1c2f3ad1d04ee2%22%7D%2C%22sentry%22%3A%7B%22url%22%3A%22https%3A%2F%2F1ab1949fc8d04608b43132f37bb2a1b0%40sentry.io%2F1301611%22%2C%22environment%22%3A%22production%22%2C%22release%22%3A%22edbccfed778bfdfcc8654e0e690c636b2030f6ba%22%7D%7D%2C%22ROOT_URL%22%3A%22https%3A%2F%2Fwww.lesswrong.com%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22autoupdate%22%3A%7B%22versions%22%3A%7B%22web.browser%22%3A%7B%22version%22%3A%228a15c730002ba09d8bbaaec4fa215fe74a6c45c8%22%2C%22versionRefreshable%22%3A%22adea52fe08b3708934b8c1bcd6b0f6b8e2b683dc%22%2C%22versionNonRefreshable%22%3A%22c34b42fb0c32160078425516b0333b576e5fe23f%22%7D%2C%22web.browser.legacy%22%3A%7B%22version%22%3A%22515fe3554d55cccda890301515e1fdcaee5adc8a%22%2C%22versionRefreshable%22%3A%22adea52fe08b3708934b8c1bcd6b0f6b8e2b683dc%22%2C%22versionNonRefreshable%22%3A%228ba4260744f5957eecf8f5e9c112a9feef0d868b%22%7D%7D%2C%22autoupdateVersion%22%3Anull%2C%22autoupdateVersionRefreshable%22%3Anull%2C%22autoupdateVersionCordova%22%3Anull%2C%22appId%22%3A%221txv9r51kxht481ysl8bb%22%7D%2C%22appId%22%3A%221txv9r51kxht481ysl8bb%22%2C%22isModern%22%3Afalse%7D"))</script>

  <script type="text/javascript" src="/4a5477f280fb424f75dfcf95871d520eae787328.js?meteor_js_resource=true"></script>


</body>
</html>
```

**Comment by Najrim** [comment]
Got it. I guess it's the "meteor.js" thing they used to build the site with that's the problem. But I don't understand why I see the real content in the HTML if I just click "view source" from the context menu.

Anyway, I don't seem to be the only one who's sick of websites obfuscating stuff. Someone made an alternative website called greaterwrong.com. Here is the same article which extracts just fine, no site config needed: [https://www.greaterwrong.com/posts/XSKQLeQnBupFo7GGC/coordination-problems-in-evolution-eigen-s-paradox](https://www.greaterwrong.com/posts/XSKQLeQnBupFo7GGC/coordination-problems-in-evolution-eigen-s-paradox).

**Comment by techexo** [comment]
Hi @Najrim,
If the second website is permanent, you could pass around the issue by modifying `vendor/j0k3r/graby/src/Extractor/HttpClient.php` and adding an url rewrite (below the _vanityfair_ one):
```php
            'rewrite_url' => [                                                      
                'docs.google.com' => ['/Doc?' => '/View?'],                         
                'tnr.com' => ['tnr.com/article/' => 'tnr.com/print/article/'],      
                '.m.wikipedia.org' => ['.m.wikipedia.org' => '.wikipedia.org'],     
                'm.vanityfair.com' => ['m.vanityfair.com' => 'www.vanityfair.com'],
                'www.lesswrong.com' => ['www.lesswrong.com' => 'www.greaterwrong.com'],
            ],                                                                      
```
This should work as they keep the same URL besides the domain name. Then you just have to write a classic site config for greaterwrong.com! :-)

**Comment by Najrim** [comment]
Cool :)
Works fine without a specific site config in this case.
