### ISSUE TITLE
Failed to fetch a newyorker.com article

### ISSUE THREAD

**Issue by gnppn** [wallabag/wallabag#3768]
### Issue details

Hi,

I tried to get a long newyorker.com article but wallabag tells me it can't get the content, via the Wallabagger extension and by re-fetching it.

The article: https://www.newyorker.com/magazine/2018/11/12/why-doctors-hate-their-computers

I can't get the server log, I'm using wallabag.it. How could I help?

Thanks!

### Environment

wallabag.it (2.3.2)

### Steps to reproduce/test case

Try to add the article mentioned above.

**Comment by j0k3r** [comment]
You can try to fix it on your own: https://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

**Comment by techexo** [comment]
Log here : https://gist.github.com/techexo/28123843817d2c0d39a76b2f6755e206
I cannot see any obvious reason it wouldn't work given the siteconfig, and it doesn't work either on f43.me.

**Comment by 4oo4** [comment]
This appears to be the same issue as https://github.com/j0k3r/graby/issues/163, so I believe it was an issue with php-readability.

I was curious if there was any progress with getting that fixed? I know there are a few sites for me besides newyorker.com that I run into on a regular basis that aren't wallabag-able because of that issue.

**Comment by techexo** [comment]
I confirm that commenting [this line](https://github.com/j0k3r/php-readability/blob/ed3393a79fe8fbbf1abe7daf17a47b21d862ddfb/src/Readability.php#L124) in _php-readability_ allows for the retrieval of the content of `newyorker.com/magazine` articles.

If I understand well how the content of an article is retrieved in wallabag, _graby_ loads the configs of _graby-site_config_, then calls _php-readability_ to get the content. The pre-filters containing the infamous "script-stripping regex" are applied in php-readability's `loadHTML()` function *if the flag `FLAG_DISABLE_PREFILTER` is not present*.

I am not at all a PHP coder, but couldn't it be possible to add the possibility to pass flags in site configs, allowing for specific websites to drop for example the pre-filters (in much the same way that the `tidy: no` instruction in site configs is passed to Readability's instance)? Or would it cause some breaks on compatibility? (I don't know if optional arguments for a constructor exist in PHP)

**Comment by techexo** [comment]
Actually, I also think that there could be other uses to disabling prefilters via site configs, as they also remove `<span>` HTML elements, which are sometime very useful to retrieve data for wallabag (I am thinking authors and date mostly).

**Comment by 4oo4** [comment]
I like the sounds of that, but wouldn't that be a break with the upstream site configs from https://github.com/fivefilters/ftr-site-config? I'm pretty sure @j0k3r's repo is always pulling from there.

**Comment by techexo** [comment]
Indeed it is. However, is it not already the case for paywall information? I think this information is embedded in site configs despite not being used by Full Text RSS. (To be confirmed by a maintainer.)

**Comment by j0k3r** [comment]
>  I think this information is embedded in site configs despite not being used by Full Text RSS. (To be confirmed by a maintainer.)

true

**Comment by j0k3r** [comment]
That commit doesn't fix everything but looks like there were more commits during the summer that improved the parsing.
