### ISSUE TITLE
issue with headers on first request

### ISSUE THREAD

**Issue by burkemw3** [wallabag/wallabag#3771]
### Issue details

On the first request, I think wallabag is using different headers than on content refetch.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.3
* How did you install wallabag? Via `git clone` or by downloading the package? docker
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

0. Request a URL
0. Observe the headers wallabag sends to the host
0. Trigger content refetch from the UI
0. Compare the headers wallabag sent on the initial request to the refetch request.

Expected: headers are the same for both requests
Actual: headers are different for each request.

https://header-honeytrap.herokuapp.com can be used to observe headers that were sent.

On the first request, I see "User-Agent: Guzzle/5.3.1 curl/7.61.1 PHP/7.2.10", which definitely shouldn't be happening.

**Comment by j0k3r** [comment]
First try:

```
HTTP_HOST	header-honeytrap.herokuapp.com
HTTP_CONNECTION	close
HTTP_USER_AGENT	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.92 Safari/535.2
HTTP_REFERER	http://www.google.co.uk/url?sa=t&source=web&cd=1
HTTP_X_REQUEST_ID	dd20659c-8fb9-4fbc-9aff-9a15e71582bb
HTTP_X_FORWARDED_FOR	195.154.29.18
HTTP_X_FORWARDED_PROTO	https
HTTP_X_FORWARDED_PORT	443
HTTP_VIA	1.1 vegur
HTTP_CONNECT_TIME	0
HTTP_X_REQUEST_START	1547534236287
HTTP_TOTAL_ROUTE_TIME	0
HTTP_VERSION	HTTP/1.1
```

Second try (using refetch):

```
HTTP_HOST	header-honeytrap.herokuapp.com
HTTP_CONNECTION	close
HTTP_USER_AGENT	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.92 Safari/535.2
HTTP_REFERER	http://www.google.co.uk/url?sa=t&source=web&cd=1
HTTP_X_REQUEST_ID	7d49be9a-5bd6-4f29-b7a3-e22b65870e1d
HTTP_X_FORWARDED_FOR	195.154.29.18
HTTP_X_FORWARDED_PROTO	https
HTTP_X_FORWARDED_PORT	443
HTTP_VIA	1.1 vegur
HTTP_CONNECT_TIME	1
HTTP_X_REQUEST_START	1547534265318
HTTP_TOTAL_ROUTE_TIME	0
HTTP_VERSION	HTTP/1.1
```

Looks like it's exactly the same for me.
Maybe this has been fixed as you are running an old version of wallabag.

**Comment by Kdecherf** [comment]
Closing this issue as it seems to be not an issue anymore on the current release. Feel free to re-open if it's still relevant.
