### ISSUE TITLE
Help/doc for graby and graby-site-config

### ISSUE THREAD

**Issue by techexo** [wallabag/wallabag#3773]
Hi everyone. 
I saw the bug https://github.com/wallabag/wallabag/issues/1284 and it would indeed be a great idea to be able to update the graby-site-config from an instance. 

I was wondering however if it was possible to update the documentation to test modifications on a siteconfig when you host your instance.

My main questions are: 
- can I update a file in `vendor/j0k3r/graby-site-config`, refetch the article in wallabag, and that's it?
- do I have to purge the cache every single time?
- would it be possible to separate graby logs from other logs? (I think having to switch all wallabag on debug level to troubleshoot site configs are a wee bit overkill.)
- is there a way to have a "standalone" graby install, showing what has been fetched, what operations are made on the code, and what is the output? (I know that f43.me is supposed to help on that, but I was unable to make it work recently. Furthermore, I cannot wrap my head around the comportment of the fetcher on some websites, and I reckon having the steps detailed would help very much.)

As 15% (at this moment) of the issues are SiteConfig ones, I really think writing down the necessary procedures somewhere would be extremely useful. 

Thanks in advance

**Comment by j0k3r** [comment]
> can I update a file in vendor/j0k3r/graby-site-config, refetch the article in wallabag, and that's it?

Yep.

> do I have to purge the cache every single time?

I don't think so.

> would it be possible to separate graby logs from other logs?

Well, it's almost already available. The log are in a different _channel_ but are written in the same log file. Maybe we can move it to an other file.
As graby log in a custom channel, this is how I can extract them and display them in the _debug log_ tab of https://f43.me/feed/test

> is there a way to have a "standalone" graby install

You can clone the repo https://github.com/j0k3r/graby and create a custom file like:

```php
<?php

require 'vendor/autoload.php';

use Graby\Graby;

$article = 'http://www.20minutes.fr/montpellier/1952003-20161030-video-car-tombe-panne-rugbymen-perpignan-improvisent-melee-route';

$graby = new Graby(['debug' => true]);
$result = $graby->fetchContent($article);

var_export($result);
```
Then you can check for `log/graby.log` to see what's happening.

> As 15% (at this moment) of the issues are SiteConfig ones, I really think writing down the necessary procedures somewhere would be extremely useful.

We'll always have a lot of issue related to site config as graby isn't bulletproof.
Feel free to update the doc to add more way / option / tips on how to create the siteconfig yourself https://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

**Comment by techexo** [comment]
Thanks for your detailed answer.

> > would it be possible to separate graby logs from other logs?
>
> Well, it's almost already available. The log are in a different _channel_ but are written in the same log file. Maybe we can move it to an other file.
> As graby log in a custom channel, this is how I can extract them and display them in the _debug log_ tab of https://f43.me/feed/test

OK. I am not familiar with logging, but is there a solution to specify a different bug level for _wallabag_ and for _graby_ in `app/config/config_prod.yml`? It is just that in my opinion, having everything in debug is really a pain when you just want to debug a site config, as the information is scattered among the wallabag website and app requests, for example. I know you can just `grep` the hell out of it, but I think it is an idea worth considering.

> You can clone the repo https://github.com/j0k3r/graby and create a custom file like [...]

I am indeed trying to find an easier workflow to create and/or debug siteconfig, but I still have some issues (see https://github.com/j0k3r/graby/issues/177).
However, with your sample file, I do not see how to break down the steps taken by graby (maybe it is not possible in its current form!). My main issue is trying to figure out how `strip` or `strip_id_or_class` are working, as I made site configs where these statements where ignored for a reason I cannot explain...

Does the cleanupHtml method (https://github.com/j0k3r/graby#cleanup-content) also use site configs? And if it does, is it possible to specify an html file as entry for the `$html` variable?

> We'll always have a lot of issue related to site config as graby isn't bulletproof.
> Feel free to update the doc to add more way / option / tips on how to create the siteconfig yourself https://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

I will as soon as I figure it myself ;)

Thanks for your answers!

**Comment by Kdecherf** [comment]
> OK. I am not familiar with logging, but is there a solution to specify a different bug level for _wallabag_ and for _graby_ in `app/config/config_prod.yml`? It is just that in my opinion, having everything in debug is really a pain when you just want to debug a site config, as the information is scattered among the wallabag website and app requests, for example. I know you can just `grep` the hell out of it, but I think it is an idea worth considering.

Yep that's possible. I had it on my own instance, the sad thing is the last release destroyed my changes :D

I'll try to make a little howto in the coming days.

**Comment by techexo** [comment]
In my opinion @Kdecherf, such a feature could have its place in an upcoming release, as it would allow someone to help without being drown under Symphony errors.

**Comment by techexo** [comment]
> Feel free to update the doc to add more way / option / tips on how to create the siteconfig yourself https://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

See https://github.com/wallabag/doc/issues/80 for updated on this.
