### ISSUE TITLE
Add better api docs

### ISSUE THREAD

**Issue by swalladge** [wallabag/wallabag#3787]
### Issue details

The autogenerated api docs are nice, but missing a lot of information. It would be nice to see full specs of the responses and examples. I'm working on developing a client at the moment and happy to document my reverse engineering.

Also having a proper api spec would help for anyway wanting to mock the api and/or develop alternative implementations.

**Comment by j0k3r** [comment]
Duplicates of https://github.com/wallabag/wallabag/issues/2721
