### ISSUE TITLE
wallabag and bookeen 

### ISSUE THREAD

**Issue by ghost** [wallabag/wallabag#3800]
Hello all,
sorry for my question , just want to know if wallabag will be one day part of bookeen ebook readers.

Thanks for your work

I'am a user of wallabag.it

**Comment by j0k3r** [comment]
No news since https://twitter.com/BookeenTeam/status/816293054927736832
:man_shrugging:

**Comment by lapineige** [comment]
And since your last message ? 🤞

**Comment by nicosomb** [comment]
I just sent them a new tweet https://twitter.com/wallabagapp/status/1348914355329503232

**Comment by nicosomb** [comment]
I close this issue. Apparently, this company don't want to work with us and we can't force them.
