### ISSUE TITLE
Full debug mode for graby

### ISSUE THREAD

**Issue by techexo** [wallabag/wallabag#3801]
Hi everyone,

This is a mix of a wallabag issue, a [graby](https://github.com/j0k3r/graby) and a [php5-readability](https://github.com/j0k3r/php5-readability)

I really would enjoy the possibility to have a script with a _full debug mode_, that would help to understand why (or where) parsing of HTML pages sometimes go sideways. Premises [here](https://github.com/wallabag/wallabag/issues/3773#issuecomment-439328203).

_Note: this is totally overkill most of the time, but it would be a great mode when debugging site configs or weird rendering of some pages._

This mode would mainly allow the logging of the HTML code at the various steps taken by the parser:
- when fetching the body (`graby->HttpClient->fetch`);
- when extracting content (`graby->ContentExtractor->process`):
  - after string replacements (optional);
  - before and after tidying (`readability->loadHtml`);
  - after pruning (`readability->prepArticle`);
  - after `graby->cleanupHTML`.

I know some of these manipulations are streamlined with the document in a DOM form and would need extra transformation in this _full debug_ mode.

There is some thoughts to have on the best way to render all this (in a log file? In `.html` files saved in the log directory? diff form?). I would prefer HTML files that are _diff-ables_. If so, it might also need to pass everything into a linter before saving, so that diffs be usable.

**Comment by techexo** [comment]
Yes, so I was wondering if there is a way to empty graby.log at the beginning of a fetch. It is of course to use only on a per-article basis, not constantly.

**Comment by techexo** [comment]
@j0k3r I modified [a bit more the code](https://github.com/j0k3r/graby/compare/master...techexo:debug) to use `RotatingFileHandler` instead of `StreamHandler`. With this, when calling graby with `parsing_debug => true`, only one file is used, overwritten at each iteration, and I think the file is changed everyday and the other deleted.

It does the job for debugging and avoid having a gigantic file.

I tried creating another instance of the logger (to have a `parsingLogger` and put the codes in a separated file), but it created problems when calling the _content extractor_, as only one logger can be passed as argument.

**Comment by techexo** [comment]
No, my mistake. It isn't overwritten at each iteration, but the log file is rotated everyday and I specified that I only want one file (so the oldest files will always be deleted). 

I think it is okay for debugging purposes (as you wouldn't need archives nor would test so many URLs in one day for the file to become too big). I will still try a few things and open a PR.

**Comment by techexo** [comment]
@j0k3r Here is my PR, totally different of what I thought it would be ;) https://github.com/j0k3r/graby/pull/184

**Comment by j0k3r** [comment]
As the PR got merged, maybe you should update the wallabag doc to explain how to enable this full debug mode? 🙂

**Comment by techexo** [comment]
Yes, I'll try to make that asap. (No promise however, cause I'm leaving for one-week holidays in a few days.) @j0k3r can you assign me the issue so I remember to do it?

**Comment by techexo** [comment]
@j0k3r I actually never tested the new logging running on wallabag, how do I pass args to the graby constructor in `config_prod.yml`?
Currently, the level indication is done with `level: debug`, but I need to be able to pass the `log_level` argument... (which will be quite confusing).

**Comment by j0k3r** [comment]
`log_level` is a config parameter of Graby, not the Monolog handler.
It should be defined here: https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Resources/config/services.yml#L41

**Comment by techexo** [comment]
OK, so this means that we have to change both `config_prod.yml` & `services.yml` if we want to activate the extra level of logging?
It feels definitely weird to have `level: debug` in `config_prod.yml`, and have to add `log_level: debug` in the other file!

**Comment by techexo** [comment]
@j0k3r OK, I finally kind of figured out what was happening...

I don't know if it's a good thing or not, but wallabag somehow overwrites graby's configuration, so if you activate the logs as [described currently in the doc](https://doc.wallabag.org/en/user/errors_during_fetching.html#enabling-debug-logs-self-hosting):
1. You'll end up with *full debug* mode activated
1. The `log_level: debug` in `services.yml` is useless
1. All logs are stored in `graby.log`

I know it shouldn't be like that, but it is actually quite a relief! The only modification to do is in `config_prod.yml`. In the `graby` section of `monolog`, indicating `level: info` triggers the "old simple debug mode", indicating `level: debug` triggers the "full debug mode".

By the way, it's also the way to fix *f43.me*: pass graby in INFO level on monolog and you'll be back the old way.

**Comment by j0k3r** [comment]
Good job! :clap:
