### ISSUE TITLE
Make the untagged list more visible

### ISSUE THREAD

**Issue by huegelc** [wallabag/wallabag#3804]
Would be a nice feature to filter pages without tags.
Thanks

**Comment by nicosomb** [comment]
@huegelc you mean this existing page `http://your-wallabag/untagged/list`?

**Comment by huegelc** [comment]
Exactly, didn't know this page existed. Would it make sense to integrate it in the filter menu?

**Comment by nicosomb** [comment]
I edited the title of your issue 👍
