### ISSUE TITLE
Problems configuring vhost for multiapplication server

### ISSUE THREAD

**Issue by Najrim** [wallabag/wallabag#3805]
### Issue details

Final stages of setting up Wallabag but I'm stuck. It's the first time for me setting up an apache server so please be patient with me. At first I tried installing Wallabag on my own and then moving the `wallabag` folder to `/var/www/html/` but now I've also tried downloading the version for shared hosting. I get the same result in both.

I want more applications than Wallabag on my server so I want to access wallabag with `mydomain.net/wallabag`. Still I tried using [the vhost configuration file from the docs](https://doc.wallabag.org/en/admin/installation/virtualhosts.html) for the sake of seeing if it works but it doesn't seem like it's meant for use https (my server is https only). It didn't do anything, even after symlinking to `enables-sites` and restarting apache. Some guy in issue #1913 provided a [this config](https://github.com/wallabag/wallabag/issues/1913#issuecomment-338558039) to put in `/etc/apache2/conf-available` instead but after that I get error 500:

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.
```

which really doesn't tell me much. (Of course I changed the filepaths to include my html folder to).

Should I be able to access wallabag by following the index to `wallabag/web/app.php`? I just get a blank page when I do that.

I have control of the full OS of the server. Should I still use the "shared hosting" method? It seems like the recommended way after reading around in issue #1913. But as far as I can tell there is no difference. The installation of Wallabag with `make install` completed sucessfully for me.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.4 and 2.3.2 (the latter for the package)
* How did you install wallabag? Via `git clone` or by downloading the package? I've tried both
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.0
* OS:
* type of hosting (shared or dedicated): I have my own server and want to run more applications than wallabag on it.
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Mariadb for the `git clone` version, default settings for the downloaded package.

**Comment by j0k3r** [comment]
Have you check the file in `path/to/wallabag/var/logs/prod.log`? What's in there?
Also, I think it's simplier to setup wallabag using a subdomain instead of folder?

**Comment by Najrim** [comment]
@techexo 
I was just trying it out to see if it worked by using app.php even though I could just see an index of files when going to `mydomain.tld/wallabag`. It didn't so I thought I'd mention it.

I tried both `mydomain.tld/wallabag` and `mydomain.tld` for the `domain_name` part. Which one should I use?

It's really my first time setting up a server apart from using Yunohost before (which does these things for you). I thought that I would need to go through more hassle with DNS and stuff if I want to use a subdomain. Isn't this the case? It doesn't matter so much to me what the URL looks like so I'll happily go with the simplest way.

The thing I'm the most confused about right now is the Apache configuration. Am I correct in that I *can't* just use the vhost conf for "site-enabled" from the docs because it will conflict with my other applications?

@j0k3r 
I checked the logs and there were some errors from when I had the database path misconfigured from my previous issue #3803 and then some from renaming a folder. I'll do a fresh install and see if there's still anything there.

**Comment by techexo** [comment]
@Najrim It is really difficult to explore all cases (and I'm not sure it's the place for it).

If you have a domain name `mydomain.tld` that redirects to your server, most of the time `anything.mydomain.tld` will also be redirected to your server. Then Apache use its configuration to know what it is supposed to fetch. If your domain name provider doesn't do that by default, you might want to look into DNS zones, but that's not a first thing to worry about most of the time.

Looking at [the documentation](https://doc.wallabag.org/en/admin/installation/virtualhosts.html#configuration-on-apache), you would just have to use:
```
<VirtualHost *:80>
    ServerName wallabag.domain.tld
    ...
```
and write `domain_name: 'http://wallabag.domain.tld' in `app/config/parameters.yml`.

**Comment by Najrim** [comment]
Yes, fair enough. I don't want to use Github issues as a support forum but I imagined this was something that could be of use to others too since my setup is so basic. Feel free to not reply or to point me somewhere else. You've been of great help already.

@j0k3r, I did a new install and there were no error logs. The file prod.log was not produced so everything seems fine in the installation. There's only a file named `.gitkeep` in that folder. It must be something with my vhost conf.

I want to use https for wallabag as with my other applications so I generated a certificate with Let's Encrypt which is valid for the subdomain too. Now I can access wallabag.mydomain.tld but it doesn't show Wallabag. It shows the page from `/var/www/html/index.html`. This is `/etc/apache2/sites-available/wallabag.conf`:

```
<VirtualHost *:443>
    ServerName wallabag.<here-goes-my-domain-name>

	SSLCertificateFile /etc/letsencrypt/live/<here-goes-my-domain-name>/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/<here-goes-my-domain-name>/privkey.pem
	Include /etc/letsencrypt/options-ssl-apache.conf

    DocumentRoot /var/www/html/wallabag/web
    <Directory /var/www/html/wallabag/web>
	Require all granted

        <IfModule mod_rewrite.c>
            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ app.php [QSA,L]
        </IfModule>
    </Directory>

    # uncomment the following lines if you install assets as symlinks
    # or run into problems when compiling LESS/Sass/CoffeScript assets
    # <Directory /var/www/wallabag>
    #     Options FollowSymlinks
    # </Directory>

    # optionally disable the RewriteEngine for the asset directories
    # which will allow apache to simply reply with a 404 when files are
    # not found instead of passing the request into the full symfony stack
    <Directory /var/www/html/wallabag/web/bundles>
        <IfModule mod_rewrite.c>
            RewriteEngine Off
        </IfModule>
    </Directory>
    ErrorLog /var/log/apache2/wallabag_error.log
    CustomLog /var/log/apache2/wallabag_access.log combined
</VirtualHost>
```

On my system I of course use my actual domain name instead of the placeholder. I also edited the `domain_name` key in the `parameters.yml` file. I've restarted Apache. Why do I end up getting the Apache2 Debian Default Page on my subdomain?

**Comment by techexo** [comment]
@Najrim I did not check this, but isn't the default configuration of Apache taking precedence in the `html` folder? If you move the `wallabag` folder into `/var/www` and replace all `/var/www/html/wallabag[...]` by `/var/www/wallabag[...]` in your VirtualHost, does it work?

**Comment by Najrim** [comment]
I tried it but the result is the same. Still the default configuration seems to take precedence.

I'm a bit confused about how the server knows the difference between the subdomain and my main domain. I'm using Cloudflare and put in a CNAME record that points the wallabag subdomain to my main domain. Maybe it has something to do with ports, based on this excerpt from [Wikipedia](https://en.wikipedia.org/wiki/CNAME_record):

> A Canonical Name record (abbreviated as CNAME record) is a type of resource record in the Domain Name System (DNS) which maps one domain name to another, referred to as the Canonical Name. 
>
> This can prove convenient when running multiple services (like an FTP server and a webserver; each running on different ports) from a single IP address. One can, for example, point ftp.example.com and www.example.com to the DNS entry for example.com, which in turn has an A record which points to the IP address.

but isn't https supposed to always go over port 443? When it "points" to my main domain, doesn't it just request the main domain in that case?

**Comment by techexo** [comment]
There is two things: DNS and VirtualHosts.
For your DNS issues, maybe [this can be of help](https://www.siteground.com/kb/how-to-enable-cloudflare-for-a-subdomain-with-a-free-or-plus-cloudflare-plan/) or [maybe this](https://help.clickfunnels.com/hc/en-us/articles/360005906774-Adding-A-Cloudflare-Subdomain-). But basically, if you're able to call `wallabag.yourdomain.tld`, see something on your server (even the default page) and the address in your URL bar is actually `wallabag.yourdomain.tld`, it means the DNS is OK (if in the URL bar you see `yourdomain.tld`, you made a redirection, not what you wanted).

As far as I know, there is absolutely no need to bother with ports in DNS records, except for weird configurations. The 80 vs. 443 port will be dealt with on your server.

Now, on your actual machine, you have VirtualHosts that will say "I'll take care of requests coming to this or that subdomain", and that is the `ServerName` instruction in your Apache configuration.

I am trying some things to configure Apache and I'll come back to you on that.

**Comment by techexo** [comment]
@Najrim After some tests and moving the wallabag folder in `/var/www`, it seems ok (I have troubles with my PHP, but it's yet another thing). 

I was wondering:
- do you access **explicitely** the address `https://wallabag.yourdomain.tld/` (**https**)? There is no "by default" redirection from port 80 to port 443 with Apache;
- in `/var/www/wallabag/app/config/parameters.yml`, is your `domain_name` also prefixed with `https://`?

**Comment by Najrim** [comment]
The reason that the subdomain showed the Apache Default Page of the main domain was that I hadn't symlinked my site config. That is, I had created the file `etc/apache2/site-available/wallabag.conf` but I hadn't run `a2ensite wallabag.conf`. After this my problems with VirtualHosts was solved. I still have the problem that the login page is completely blank but that is a different issue so I'll close this one.

**Comment by JialuZhang** [comment]
@Najrim 

In your posted configuration,
```
    <Directory /var/www/html/wallabag/web/bundles>
        <IfModule mod_rewrite.c>
            RewriteEngine Off
        </IfModule>
    </Directory>
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
