### ISSUE TITLE
nakedcapitalism.com fails fetching the content

### ISSUE THREAD

**Issue by meskio** [wallabag/wallabag#3806]
### Issue details

For the articles from https://www.nakedcapitalism.com/ the content is not detected correctly, it fetches the 'recent items' instead of the articles. In f43.me it works fine and detects the content of the article correctly.

### Environment

* wallabag version 2.3.4

### Steps to reproduce/test case

Add https://www.nakedcapitalism.com/2018/12/200pm-water-cooler-12-10-2018.html to wallabag and see how it only displays `recent items`.

**Comment by techexo** [comment]
Hi @meskio . Weirdly enough, I have no issue fetching the article you linked (and others from this website) with my 2.3.4 wallabag instance, and there is no site configuration file for this website, so wallabag's parser should be able to retrieve the content without help.

Could you:
- try again to fetch it?
- if you're hosting your own version of wallabag, give us the results of `composer info | grep j0k3r` (launched in the directory where wallabag is installed, of course).

**Comment by meskio** [comment]
This is weird, I have tried with several articles from the blog and all of them give me only the recent items instead of the content of the article. And I try several times for the same one as well.

I don't host my own wallabag, but I'll ask if the people that hosts it can help here.

**Comment by Kdecherf** [comment]
Hello,

@meskio I can reproduce your issue when I build PHP without the support of tidy. Checking with your administrator to enable tidy should do the trick ;-)
