### ISSUE TITLE
All Kinja (Gizmodo, Lifehacker, Jalopnik, etc.) articles fail to load

### ISSUE THREAD

**Issue by kmlucy** [wallabag/wallabag#3807]
### Issue details

All Kinja (Gizmodo, Lifehacker, Jalopnik, etc.) articles fail to load. There is just a blank page, and trying to re-fetch content results in `Entry reloaded but fetching content failed`. The page parses correctly on f43.me. There are no log entries in `prod.log`.

Example: https://jalopnik.com/why-some-trucks-have-five-little-lights-on-the-roof-1830914130

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.4
* How did you install wallabag? Docker image
* Last wallabag version that did not exhibit the issue (if applicable): Unknown, just started using Wallabag
* php version: 7.2.13
* OS: Alpine (inside container), Debian Stretch (host)
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Postgres

### Steps to reproduce/test case

This happens everytime I try to save an article from the sites listed above.

**Comment by techexo** [comment]
There is an issue with the existing site-config.
The following works almost perfectly (except for embedded images):
```
title: //head/title
author: //meta[@name="author"]/@content
body: //div[contains(@class, 'post-content')]
//div[contains(@class, 'content-summary')]

test_url: http://jalopnik.com/5892124/1955-porsche-550-spyder-sells-for-record-3685-million/
```

As it is a common issue to all Kinja websites, we should probably use fingerprinting. One that could work is 
```
//head/link[@rel='dns-prefetch' and @href='//kinja.com']
```

I don't know yet how fingerprinting works on wallabag so I cannot do a PR on that, @j0k3r or @Kdecherf , could you help me on that one?

**Comment by techexo** [comment]
I just saw that it was recently changed by @Kdecherf on https://github.com/fivefilters/ftr-site-config/commit/0e9aa6ff05c1c3d9c6841a8ff1b6477a791868f1
I think my version is better though (no offense :wink:) and should be applicable on:
- avclub.com
- clickhole.com
- deadspin.com
- gizmodo.com
- jalopnik.com
- jezebel.com
- kotaku.com
- lifehacker.com
- splinter.com
- theonion.com
- theroot.com
- thetakeout.com
- theinventory.com
- .kinja.com

Is that enough to go with fingerprinting, or should I do a PR to update all the corresponding files on https://github.com/fivefilters/ftr-site-config ?

**Comment by j0k3r** [comment]
Fingersprints are hardcoded both in FullTextRss & in graby, I think the fastest way to fix these sites issues is to update all corresponding files 🤷‍♂️

**Comment by techexo** [comment]
PR https://github.com/fivefilters/ftr-site-config/pull/579

**Comment by techexo** [comment]
@Kdecherf, new expert in htmLawed (😉), I have an issue to load the pictures of these websites.
The following code:
```html
<figure class="js_marquee-assetfigure align--center">
    <div class="img-wrapper lazy-image img-permalink-sub-wrapper img-permalink-sub-wrapper--nobackground">
        <svg class="svg-icon svg-zoom-in" />
        <picture>
            <source class="ls-small-media-source" data-srcset="https://i.kinja-img.com/gawker-media/image/upload/s--vDNHQuiV--/c_fit,f_auto,fl_progressive,q_80,w_636/17fyzivpvmahqjpg.jpg" media="(max-width: 599px)" sizes="636px" srcset="https://i.kinja-img.com/gawker-media/image/upload/s--vDNHQuiV--/c_fit,f_auto,fl_progressive,q_80,w_636/17fyzivpvmahqjpg.jpg">
            <source data-srcset="https://i.kinja-img.com/gawker-media/image/upload/s--vDNHQuiV--/c_fit,f_auto,fl_progressive,q_80,w_636/17fyzivpvmahqjpg.jpg" media="(max-width: 1487px)" sizes="636px" srcset="https://i.kinja-img.com/gawker-media/image/upload/s--vDNHQuiV--/c_fit,f_auto,fl_progressive,q_80,w_636/17fyzivpvmahqjpg.jpg">
            <source data-srcset="https://i.kinja-img.com/gawker-media/image/upload/s--vDNHQuiV--/c_fit,f_auto,fl_progressive,q_80,w_636/17fyzivpvmahqjpg.jpg" sizes="636px" srcset="https://i.kinja-img.com/gawker-media/image/upload/s--vDNHQuiV--/c_fit,f_auto,fl_progressive,q_80,w_636/17fyzivpvmahqjpg.jpg">
            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" class="ls-lazy-image-tag cursor-pointer lazyautosizes lazyloaded" data-sizes="auto" data-width="640" data-chomp-id="17fyzivpvmahqjpg" data-format="jpg" sizes="636px">
        </picture>
    </div>
</figure>
```

is reduced into
```html
<figure class="js_marquee-assetfigure align--center">
 <div class="img-wrapper lazy-image img-permalink-sub-wrapper img-permalink-sub-wrapper--nobackground">
  <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" class="ls-lazy-image-tag cursor-pointer lazyautosizes lazyloaded" data-sizes="auto" data-width="640" data-chomp-id="17fyzivpvmahqjpg" data-format="jpg" alt="image" />
 </div>
</figure>
```
by the `cleanupXss` function (calling htmLawed) of graby.

The issue here is that the `<picture><source datasrc="">...<img src="..." /></source></picture>` is totally valid from an HTML point-of-view, but the function destroys totally the actual links to the pictures by deleting the `source` and `picture` markups.

This blocks wallabag for retrieving the pictures in all Kinja websites, as far as I can tell (except the header one).

**Comment by techexo** [comment]
PR has been accepted, so content fetching will be better after merging in graby-site-config.

There is still an issue with the pictures (see comment above) but I really can't see how to fix it. @j0k3r or @Kdecherf, an idea?
