### ISSUE TITLE
Add API endpoint for app name

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3808]
### Issue details

Currently wallabag Android app detects if a given URL is really a wallabag site by parsing the URL's source code and searching for some strings. This is an ugly solution. Errors occur like: https://github.com/wallabag/android-app/issues/744

It would be awesome if we can have an API endpoint which only tells what kind of application this is. E.g.

`/api/applicationname` returns only "wallabag"

I have thought about `/api/version`, but that does might be duplicate with other applications on the planet.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.4 (and before)
* How did you install wallabag? Via `git clone` or by downloading the package? git
* Last wallabag version that did not exhibit the issue (if applicable): none
* php version: 7.0
* OS: debian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): pg

**Comment by j0k3r** [comment]
Why not create a better version endpoint?
As of now we have `api/version` returning a plain version string. Which is a really bad idea because we can't add new stuff to that enpoint. Anyway.

Can't we introduce a `/api/info` (or an other name) returning something like:
```json
{
	"appname": "wallabag",
	"version": "2.4.0-dev",
	"allowed_registration": false
}
```
