### ISSUE TITLE
Moving the installation folder breaks not relative links

### ISSUE THREAD

**Issue by techexo** [wallabag/wallabag#3809]
### Issue details

I report this issue following a discussion with @Najrim on Gitter.
After an installation done in `/home/***/wwwdata/wallabag` was moved in `/var/www/wallabag`, the login page was blank without obvious reason.

Logs indicated however the following:
> [Wed Dec 12 10:58:23.075754 2018] [:error] [pid 9881] [client 193.xxx.xx.xxx:52184] PHP Warning: file_get_contents(/home/***/wwwdata/wallabag/src/Wallabag/UserBundle/Resources/views/Security/login.html.twig): failed to open stream: No such file or directory in /var/www/wallabag/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 145

It seems that some hard links are made during the installation, and it probably isn't that good an idea?

I checked the symbolic links in the installation folder and they're all relatives, so the installation path has to be stored somewhere. If "it is a feature, not a bug", I propose to update the doc accordingly with a warning.

### Environment

* wallabag version (or git revision) that exhibits the issue: git
* How did you install wallabag? Via `git clone` or by downloading the package? Git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS: Debian
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case
1. Install wallabag in a folder
2. Move the folder and change your vhosts accordingly
3. Try to access wallabag

**Comment by techexo** [comment]
That's what I was looking at on my instance right now, all the references are either in `var/log` or in `var/cache/prod`. I didn't think the cache could be the issue as it was on a never-accessed-before instance. Is the cache created during installation, and not at the first time the page(s) is/are loaded?

**Comment by j0k3r** [comment]
The cache is created during the installation too.

**Comment by techexo** [comment]
OK, I think it solves the issue then. I'm wondering if we shouldn't add that in the FAQ, I'll try to do a PR soon.

I'll close the issue when I'll have confirmation that @Najrim didn't cleared the cache after moving files.

**Comment by Najrim** [comment]
Yeah, I didn't clear the cache.
