### ISSUE TITLE
Tags privacy leak

### ISSUE THREAD

**Issue by swalladge** [wallabag/wallabag#3815]
When calling the api methods to delete tags, it's possible for tags from other
users to be exposed.

Affected endpoints:

- /api/tags/<tag>
- /api/tag/label
- /api/tags/label

When using the DELETE method on these endpoints and supplying a tag id or label
that corresponds to (I suspect but cannot confirm) a tag by another user, that
tag information is returned. The tag is not deleted, because sending the same
request multiple times continues to respond with the same tag data.

**Comment by j0k3r** [comment]
Thanks @swalladge!
