### ISSUE TITLE
500 error invalid text representation on login

### ISSUE THREAD

**Issue by swalladge** [wallabag/wallabag#3817]
### Issue details

When authenticating to the api, I accidentally sent some incorrect values and got a 500 error:

```
500: Internal Server Error

An exception occurred while executing 'SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5, t0.name AS name_6, t0.user_id AS user_id_7 FROM wallabag_oauth2_clients t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1' with params ["$WALLABAG", "CLIENT_ID"]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "$WALLABAG"
```

(The incorrect/malformed value was that the client_id was `$WALLABAG_CLIENT_ID` - guess who messed up expanding environment variables. :P )

### Environment

The Framabag instance. Apologies if this is already fixed on master.

### Steps to reproduce/test case

Send a client id that is in the format of `NotAnInteger_whatever` when authenticating against the `/oauth/v2/token` endpoint. It appears that the first part of the client id before the first underscore is expected to be an integer and isn't sanity checked.

**Comment by j0k3r** [comment]
@biva It's not related I think. It's a bad configuration.

**Comment by j0k3r** [comment]
Sadly it's not up to us...
https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/428
As the project seems to be dead we'll see what we can do.
