### ISSUE TITLE
Wallabag.org showing server error

### ISSUE THREAD

**Issue by fspoettel** [wallabag/wallabag#3822]
### Issue details

Trying to access [the website](https://wallabag.org/) results in the following server error:

> 
> Server Error
> 
> Sorry, something went terribly wrong!
> E_WARNING - session_write_close(): write failed: No space left on device (28) For further details please review your logs/ folder, or enable displaying of > errors in your system configuration.

### Environment

Not applicable

### Steps to reproduce/test case

Not applicable

**Comment by techexo** [comment]
Ping @j0k3r for this issue.

**Comment by tcitworld** [comment]
It seems to be back.
