### ISSUE TITLE
Update `Problems?` menu link to create an issue on GitHub rather than sending an email

### ISSUE THREAD

**Issue by shtrom** [wallabag/wallabag#3828]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

Ok, my suggestion may not actually be desirable in light of this warning above, but here goes.

### Issue details

The `Problems?` link in the sidebar when reading an article sends an email to `info@`. Perhaps it would be better if it were a link to some pre-filled issue template using, e.g., https://help.github.com/articles/creating-issue-templates-for-your-repository/ for reporting fetching errors. I guess that template could also include ticky boxes wrt. testing with f43.me and custom site-configs first.

**Comment by j0k3r** [comment]
I agree too but not every body does have a GitHub account.

**Comment by tcitworld** [comment]
I would prefer an API submission to a server that handles the list itself.

**Comment by j0k3r** [comment]
Fixed in https://github.com/wallabag/wallabag/pull/3861
