### ISSUE TITLE
Wallabag doesn't get the titles from site-config

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#3830]
I think there is a regression in the last Wallabag version. I tried everything!!!

Months ago I made this site-config and it worked perfectly => https://github.com/fivefilters/ftr-site-config/blob/master/eleconomista.es.txt

After the last update of Wallabag (2.3.5),  the title is not working anymore. I always see "elEconomista.es" I tried to change the site-config with a lot of variants and none of them work.

Example article => https://www.eleconomista.es/opinion-blogs/noticias/9624014/01/19/Trabajar-mas-anos-la-unica-forma-de-sostener-pensiones-que-se-revalorizaran-al-IPC.html

**Comment by Kdecherf** [comment]
Hello @ngosang,

On the linked example the title is extracted using json-ld data which take precedence on the `title` directive. You can disable this behavior by adding the following line to your site-config:

```
skip_json_ld: yes
```

It's not the first time we encounter issues with json-ld data, we may have an issue in our processor. I will take a look.

**Comment by Kdecherf** [comment]
Well, there's a bug here. My workaround should do the trick while waiting for a fix.

**Comment by techexo** [comment]
@Kdecherf : in [Extractor.php](https://github.com/j0k3r/graby/blob/7ac1e2d696744c1f7c9c76658677efda33df020a/src/Extractor/ContentExtractor.php#L1145-L1151), the title is detected by looking for `headline` or `name` entries. On the website, the JSON data contained in the header has indeed an entry `"headline": "Trabajar mÃ¡s aÃ±os, la Ãºnica forma de sostener pensiones que se revalorizarÃ¡n al IPC"` (_sic_) with the "good" value, but there is also in the **body** of the page another JSON data containing the `"name": "elEconomista.es"`.

I reckon that wallabag takes into account the last one encountered. I don't see however how it could've work before and not anymore. Is it absolutely sure that is not a coincidence and the website has been modified?

**Comment by techexo** [comment]
@Kdecherf : introduced by https://github.com/j0k3r/graby/commit/dc01726f752cf1a127a87c77ed7c143aad472fcb . This addition seems debatable to me, it should at least check before if an headline has been found.

**Comment by ngosang** [comment]
@techexo @j0k3r I have more sites with the same problem. e.g https://github.com/fivefilters/ftr-site-config/pull/595

I will use the workaround by now but I think this is not a real fix. I mean, if I write a specific site-config for a site with the tag "title", this should be the text used. If site-config doesn't have the tag "title" or the title is not found or something like that, you can try to get the title from other places...

**Comment by techexo** [comment]
The issue is that XPath-defined elements are looked at later in the process, while JSON-LD are very early in the process (before script nodes are removed). I guess we could check later, and overwrite the value if the site config specifically define an XPath.

**Comment by Kdecherf** [comment]
@techexo nope, the main issue is that Graby should take json-ld node types into account to extract data (which is not currently the case, I'm working on a fix.
