### ISSUE TITLE
Content extraction via the command line

### ISSUE THREAD

**Issue by aicioara** [wallabag/wallabag#3834]
I was wondering whether or not it is currently possible to extract content from a web page without the rest of the functionality wallabag provides (i.e. no server, no browser extension). Ideally just using a tool such as `bin/console`?

If possible, could anyone please point me in the right direction? If not currently possible, where in the project can I find the related logic?

Thank you!

**Comment by j0k3r** [comment]
There is no such tool for the moment.
All the fetching content is perform here: https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Helper/ContentProxy.php#L48

**Comment by Kdecherf** [comment]
To complete the answer of @j0k3r, Wallabag uses [Graby](https://github.com/j0k3r/graby/) to actually fetch and extract content of a web page. You can create a command/client using only Graby with something like that:

``` php
<?php

use Graby\Graby;

$graby = new Graby();
$content = $graby->fetchContent('https://example.com');
```

**Comment by aicioara** [comment]
Thank you @j0k3r and @Kdecherf for your quick responses. That is exactly what I was looking for.
