### ISSUE TITLE
To parse lepoint.fr is not working

### ISSUE THREAD

**Issue by klorydryk** [wallabag/wallabag#3840]
I try to add this article:
https://www.lepoint.fr/invites-du-point/tribune-comment-la-france-s-est-vendue-aux-gafam-05-01-2019-2283510_420.php
and the content is empty, despite the fact it gets the picture.
Reload button does not work better.
The test with f43 website is working fine.
Thanks!

**Comment by Kdecherf** [comment]
Hello,

Please provide information requested by the issue template: wallabag version, php version, self-hosted or managed instance

**Comment by klorydryk** [comment]
Sorry, forgot XD
Wallabag version: 2.3.2
Self hosted (Yunohost 3.3.3)
PHP 7.0

**Comment by techexo** [comment]
Hi @klorydryk 
I recently updated the site configuration file for lepoint.fr, which explains why it works on f43.me but not on your instance. Could you upgrade your wallabag instance to `v2.3.6`?

**Comment by j0k3r** [comment]
Site is well parsed.
Issue isn't related to wallabag itself.
