### ISSUE TITLE
Do not parse antigone21.com

### ISSUE THREAD

**Issue by quentinDupont** [wallabag/wallabag#3842]
### Issue details

Trying to get this website (https://antigone21.com/2014/04/03/falafels-hummus-maison-vegan-sans-gluten/) but it doesn't work, nothing appear on my wallabag.

With **f43.me** :  "We failed to make this item readable, the default text from the feed item will be displayed instead."
### Environment

Yunohost package with version 2.3.2

**Comment by quentinDupont** [comment]
Thanks for searching the solution :)

**Comment by j0k3r** [comment]
@techexo the fingerprint works great but none of the existant rule are matching in https://github.com/fivefilters/ftr-site-config/blob/master/.wordpress.com.txt

**Comment by techexo** [comment]
@j0k3r Yes indeed... The question remains: how to know if  it is a _global_ change in wordpress' templates which should affect the general site config, or a theme issue that breaks recognition?

Looking at some site that I know of running on WordPress, it seems that a much more conserved node would be `//article`. We could maybe add a fallback on that?
