### ISSUE TITLE
Toggling article state send to unread first page

### ISSUE THREAD

**Issue by klorydryk** [wallabag/wallabag#3843]
Wallabag version: 2.3.2
Self hosted (Yunohost 3.3.3)
PHP 7.0

When toggling, on the unread category, an article as "read", Wallabag is loading the first page.
Same when in "archive", toggling an article send us to first page of "unread".

Behavior should be to stay on the current page.

**Comment by techexo** [comment]
Hi @klorydryk. Have you checked in your configuration the option `Where do you want to be redirected to after marking an article as read?` ? If `Stay on the same page` is chosen, this shouldn't happen.

Could you check if the chosen parameter is the good one on your installation, and report back? :smile:

**Comment by lizyn** [comment]
I think what @klorydryk  means is that, if you enter an entry from page `n` of the list (i.e., https://app.wallabag.it/unread/list/n), when you're done with that entry (archive/delete), it's supposed to go back to page `n`. The current behaviour is ignoring this and always going back to the fist page.

**Comment by nicosomb** [comment]
This issue is fixed.
