### ISSUE TITLE
Add php-tidy as requirement?

### ISSUE THREAD

**Issue by techexo** [wallabag/wallabag#3844]
Hi everyone,

`php-tidy` has been added to requirements for wallabag in the docker build (see PR https://github.com/wallabag/docker/pull/137). Why not add it to composer requirements for the main project?

It would fix https://github.com/wallabag/wallabag/issues/3806 (and probably others).

**Comment by j0k3r** [comment]
It could be a good idea.
Should this go to 2.4.0 or 2.3.7 @Kdecherf?
