### ISSUE TITLE
Large import on shared hosting hard to achive

### ISSUE THREAD

**Issue by thgie** [wallabag/wallabag#3846]
### Environment

* wallabag version: 2.3.2
* How did you install wallabag? download package followed by composer install
* php version: 7.1.24
* OS: cloudlinux 7.5
* type of hosting: shared, no redis/rabbit-mq
* storage system): MySQL

### Steps to reproduce/test case

- install via wget
- composer install (i can to a bit more then on a usual shared hosting)
- setup pocket consumer key
- start import via pocket

I have a timeout after 180 entries. If I restart the import via webclient I get another 180 entries with some duplicates. The wallabag:clean-duplicates takes care of that. But after some imports the amount of duplicates is 180 per batch. 

- I upped timeout and memory to the max. 999sec and 999MB, which didn't result in a larger import.

I have 1900 entries in Pocket which I'd love to migrate and after around 800 I hit the threshold of imported to duplicated entries.

I tried to import my Pocket entries to Instapaper and then import the Instapaper csv but that fails as well with a generic error, that I should validate my csv.

Where to go from here?

**Comment by j0k3r** [comment]
I guess the shared hosting can be the bottleneck.

Any chance to have a cli access?
You might want to try to import (from instapaper for example) using `php bin/console wallabag:import --env=prod --importer=instapaper --username=YOURUSERNE --filepath=path/to/your/csv/file`

Otherwise, you can create an account on wallabagit, you'll have a free trial, import your entries from Pocket and then export them as wallabag v2 export and import them on your instance.

**Comment by thgie** [comment]
Thank you @j0k3r for the quick response. I had to use the command like this

`bin/console wallabag:import admin instapaper-export.csv --env=prod --importer=instapaper`

It didn't recognize the

**Comment by j0k3r** [comment]
Oh yeah sorry about parameter, written them by head not by checking the code :innocent: 
Let us know

**Comment by thgie** [comment]
Salü @j0k3r, the import via wallabag.it (Pocket API in, Wallabag v2 JSON out) worked liked a charm. It dropped 20 entries in the process from wallabag.it to my selfhosted installation somewhere but I guess I can live with that.

I did use the webinterface and not the cli importer to take in the json.

Thank you for the help :)
