### ISSUE TITLE
Move all Unread articles to Archive

### ISSUE THREAD

**Issue by ghost** [wallabag/wallabag#385]
Is it possible to quickly switch all unread articles to archived ?

I use poche and calibre to create a weekly reading ebook of poche'd articles.

After creating the ebook file I would like to mark all unread articles as archived so that they are not picked up again the week later.

Thanks.

**Comment by markwaters** [comment]
I have now upgraded from 1.9.2 to 2.0.3 and am wondering if there is a nice API method to archive all unread articles quickly from bash ?

Can someone explain it for me ?

Thanks.

**Comment by markwaters** [comment]
In the meantime the SQL incantation is "UPDATE wallabag_entry SET is_archived = 1 WHERE user_id = 1"

**Comment by nicosomb** [comment]
In 2.1, when you'll import via CLI, you'll be able to set "markAsRead" option, to mark all the entries as read.
