### ISSUE TITLE
No images in wikipedia articles

### ISSUE THREAD

**Issue by miwasp** [wallabag/wallabag#3852]
### Issue details

All wikipedia articles are displayed without images. Tested with Firefox, Chrome and Edge.
This is also reproducable with a test account on app.wallabag.it.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.6
* How did you install wallabag? Via `git clone` or by downloading the package? Downloading package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.2
* OS: Ubuntu 16.04LTS
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

* Set Firefox to normal zoom (display at 100%)
* Add any wikipedia article to wallabag (e.g. https://de.wikipedia.org/wiki/L%C3%B6tkolben, storing images local makes no difference)
* Display the article and Zoom in and out. Images are only displayed if your zoom factor is >100%

Generated source looks like this:
`<div class="thumb tright"><div class="thumbinner"><a href="https://de.wikipedia.org/wiki/Datei:Benzinlötlampen_und_Lötkolben.jpg" class="image"><img alt="" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Benzinlötlampen_und_Lötkolben.jpg/220px-Benzinlötlampen_und_Lötkolben.jpg" width="220" height="165" class="thumbimage" srcset="1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Benzinl%C3%B6tlampen_und_L%C3%B6tkolben.jpg/440px-Benzinl%C3%B6tlampen_und_L%C3%B6tkolben.jpg 2x" data-file-width="2592" data-file-height="1944" /></a>  <div class="thumbcaption">Lötkolben, die mit Lötlampen erhitzt werden</div></div></div>`

If i remove the "1.5x, " from srcset the images are displayed all the time

**Comment by techexo** [comment]
@j0k3r with the issue being the srcset value and the zoom value, are you sure it is a site config issue?

**Comment by j0k3r** [comment]
I just flag it as site config to know it's related to parsing. But we can change it or link to another issue on the same subject

**Comment by miwasp** [comment]
Additional info:
Regardless of the zoom level, the images are not displayed at all in Chrome and Edge

**Comment by techexo** [comment]
I don't know if it's related, but looking at the code using the Inspection mode in Firefox shows that a `:before` statement disappears when zooming in (and when the picture is finally displayed).
