### ISSUE TITLE
wiki.c2.com fails to fetch

### ISSUE THREAD

**Issue by PascalMinder** [wallabag/wallabag#3865]
### Issue details
The page [wiki.c2.com](http://wiki.c2.com/?CompositionInsteadOfInheritance) can't be fetched. I also tested it with [f43.me](https://f43.me)

### Environment

* Wallabag Version: 2.3.2

**Comment by anarcat** [comment]
well the c2.com wiki looks down from here in a web browser, not sure this is a problem with wallabag...

**Comment by techexo** [comment]
The content is loaded with JavaScript, so wallabag is unable to fetch it in its current state. Related to https://github.com/wallabag/wallabag/issues/3604 & https://github.com/wallabag/wallabag/issues/2527.
