### ISSUE TITLE
Import from Pocket: archived entries imported as unread

### ISSUE THREAD

**Issue by sepanko** [wallabag/wallabag#3866]
### Issue details

When importing from Pocket, all items -- both read and unread -- end up in "Unread", none in "Archive".

This happens both with asynchronous import (Redis) enabled and disabled.

### Environment

* Version: 2.3.5 (latest image from [hub.docker.com](https://hub.docker.com)) and 2.3.6 (built from current [wallabag/docker](https://github.com/wallabag/docker))
* Install method: Docker (docker-compose)
* Last wallabag version that did not exhibit the issue: don't know
* PHP version: 7.2.13
* OS: Ubuntu 18.04 (Docker host)
* Type of hosting: dedicated
* Storage system: SQLite

### Steps to reproduce/test case

To reproduce, I've created created a dummy account at [getpocket.com](https://getpocket.com) and set up access for my wallabag app. In my wallabag instance, I've removed all entries.

Then I've added 6 entries at  [getpocket.com](https://getpocket.com), marked 3 of them "Read" (Archived), and imported into wallabag. Expected: 3 entries in "Unread" and 3 in "Archive". Got: all 6 entries in "Unread".

**Comment by sepanko** [comment]
Yes! 
https://github.com/wallabag/wallabag/pull/3819#discussion_r245397572 fixes the "Archived" status for me, _AND_ the same change 2 lines below fixes the "Starred" status.

Thank you, you've saved me a lot of time :)

**Comment by j0k3r** [comment]
Great! I’m goin to work in that PR to have these fixes merged into the master!
I’ll re-open the issue until the fix is merged.
