### ISSUE TITLE
Saved article looks better when in "public link" view

### ISSUE THREAD

**Issue by bipox** [wallabag/wallabag#3870]
Hosted on wallabag.it

An article from the NYT [on my Wallabag](https://ncloud.zaclys.com/index.php/apps/files_sharing/ajax/publicpreview.php?x=1920&y=606&a=true&file=wallabagnormal.png&t=Qdy54FNHjTTc6eX&scalingup=0) and shared [by public link](https://app.wallabag.it/share/5c538c789cca42.17275616)

On my Wallabag instance the text area is wider and the picture is missing. The shared article looks great.

Pictures aren't always missing but the captions start next to the pictures instead of under.
[on my Wallabag](https://ncloud.zaclys.com/index.php/apps/files_sharing/ajax/publicpreview.php?x=1920&y=606&a=true&file=wallnorm2.png&t=p3ccSXEQEcBLyq8&scalingup=0)
and [shared link](https://app.wallabag.it/share/5c53881e195588.83657562)

I happens regardless of which browser I use.

**Comment by j0k3r** [comment]
Any chance to put really image hosted on GitHub? So they can still be there in the future..

**Comment by nicosomb** [comment]
As @j0k3r said, pictures are not available. I close this issue. Feel free to reopen it when you'll have files.
