### ISSUE TITLE
Boston Review article content not fetched

### ISSUE THREAD

**Issue by syclops** [wallabag/wallabag#3874]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

The following page seems to work in `f43.me` (both internal and external parsers) but not in the `wallabag.it` app: `https://bostonreview.net/books-ideas/nathan-robinson-forensic-pseudoscience-criminal-justice`

### Environment

Everything was done via my account on `wallabag.it`. I can't seem to find details on the Wallabag version, OS, etc. used there.

### Steps to reproduce/test case

Non-working: attempt to add the link above to Wallabag.

Working: display page contents in f43.me.

**Comment by techexo** [comment]
I confirm I am able to fetch that almost perfectly on my 2.3.6 wallabag instance.  @j0k3r, isn't wallabag.it supposed to be auto-updated to last versions now?

**Comment by j0k3r** [comment]
auto-updated, nope.
But wallabag.it is running 2.3.6 already.

**Comment by techexo** [comment]
Weird then. I have no problem with self-hosted 2.3.6.
```
j0k3r/graby                          1.18.0     Graby helps you extract article content from web pages
j0k3r/graby-site-config              1.0.72     Graby site config files
j0k3r/php-readability                1.1.11     Automatic article extraction from HTML
```

**Comment by Kdecherf** [comment]
@j0k3r could you give the current installed versions of graby, php-readability and system package libtidy on wallabag.it?

**Comment by j0k3r** [comment]
Tidy is not installed on wallabag.it.
We'll install it for the 2.3.7

**Comment by j0k3r** [comment]
wallabag.it is now up to date and the url is well parsed.
