### ISSUE TITLE
Link Fetching issue

### ISSUE THREAD

**Issue by widolf** [wallabag/wallabag#3881]
### Issue details
not fetching [this link ](https://www.blickpunkt-wiso.de/post/gekaperte-staaten-von-europa-wie-regierungen-lobbyismus-fuer-konzerne-betreiben--2287.html)
f43.me does

### Environment
* wallabag version: wallabag.it
### Steps to reproduce/test case
Just try to fetch above url

**Comment by techexo** [comment]
Works fine on the last version of wallabag on self-hosted server. What version are we running right now on wallabag.it?

**Comment by j0k3r** [comment]
@techexo 2.3.6

**Comment by techexo** [comment]
Weird then. I have no problem with self-hosted 2.3.6.
```
j0k3r/graby                          1.18.0     Graby helps you extract article content from web pages
j0k3r/graby-site-config              1.0.72     Graby site config files
j0k3r/php-readability                1.1.11     Automatic article extraction from HTML
```

**Comment by techexo** [comment]
Might be related to #3874, as `php-tidy` is not yet available on wallabag.it, when it was on my wallabag instance.

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/issues/3874#issuecomment-469411508
