### ISSUE TITLE
Don't send referrers when viewing online images

### ISSUE THREAD

**Issue by lizyn** [wallabag/wallabag#3889]
### Issue details

Some sites seem to decide whether to serve images based on `referrer` in the request header. Usually (for these sites), only requests whose referrers are within specific domains or with no referrer are legal, as what happens [here](https://test.smzdm.com/pingce/p/70110564/). 

I picked one of the images in the above article and tested it with [httpie](https://github.com/jakubroztocil/httpie):

```
# Failed with the default referrer
~
➜ http GET https://am.zdmimg.com/201901/19/5c4334c515dfa5006.jpg_e600.jpg \
"Referer: https://app.wallabag.it"
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 50
Content-Type: application/json
Date: Thu, 21 Feb 2019 15:01:25 GMT
Server: marco/2.8
Via: M.ntt-us-lax-147
X-Error-Code: 40310014
X-Request-Id: 22f24c864f83b3c8460501d8b3410d62

{
    "code": "40310014",
    "msg": "invalid Referer header"
}
```

```
# Returns the image with a specific referrer (where the articles originally locates)
~
➜ http GET https://am.zdmimg.com/201901/19/5c4334c515dfa5006.jpg_e600.jpg \
"Referer: https://smzdm.com"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 533843
Cache-Control: max-age=691200
Connection: keep-alive
Content-Length: 381021
Content-Type: image/jpeg
Date: Thu, 21 Feb 2019 15:07:24 GMT
ETag: "d4b1a407705ded5c43e54d7d222e98fe"
Expires: Sat, 23 Feb 2019 10:52:02 GMT
Last-Modified: Sat, 19 Jan 2019 14:31:35 GMT
Server: marco/2.8
Via: T.203.H, V.403-zj-fud-209, S.ntt-cn-hkg-009, T.13.M, V.ntt-cn-hkg-013, T.148.H, M.ntt-us-lax-147
X-Request-Id: 56f1ce04ff8ba849162df923b8c4e4a0; b9ec97057e2807bedf26f2d6f706a2ed; 5496529430c40c4de0236e68ac4c5b93
X-Source: U/200, G/200



+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+
```

And same as above (success) with **no referrer**.

Also, I tried using a chrome [extension](https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin) to block referrers coming from my wallabag domain (so the requests are without referrers), then the images got successfully displayed too.

So can we have the referrer removed when requesting images online (not downloaded locally)? Will it work to set referrerpolicy of <img> tags to `no-referrer` ?

The existing `download images locally` option would be a workaround. However, my storage is sort of limited and the connection to my server is not very good (which results in longer image loading time), sad. Also, there are currently other issues with this option, e.g., #3505.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.5
* How did you install wallabag? docker-compose
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.2
* OS: Ubuntu 18.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Bag this [article](https://test.smzdm.com/pingce/p/70110564/) and see if the images get displayed correctly.

**Comment by j0k3r** [comment]
Look likes the `no-referer` is valid on an `img` tag using attributes `referrerpolicy`. That might be an option.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#Integration_with_HTML

**Comment by tcitworld** [comment]
Support is not perfect though https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Browser_compatibility
