### ISSUE TITLE
Wallabag update breaks with pdo_sqlite not implementing DBAL interface?

### ISSUE THREAD

**Issue by Matthias84** [wallabag/wallabag#3890]
### Issue details

I run an instance on a shared hosting (uberspace.de) and updated by replacing all files with new package install and merged my parameters.yml.

When I start the migration, I get
> SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
> ...
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
> PHP Warning:  class_implements(): Class pdo_sqlite does not exist and could not be loaded in /var/www/virtual/oneofx/html/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php on line 210
> PHP Warning:  in_array() expects parameter 2 to be array, boolean given in /var/www/virtual/oneofx/html/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php on line 210
>
>                                                                               
>  [Doctrine\DBAL\DBALException]                                                
>  The given 'driverClass' pdo_sqlite has to implement the \Doctrine\DBAL\Driver interface.                                                                
>
> Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-cmd event terminated with an exception
>                                                                                                                                                                     >  [RuntimeException]                                                                                                                                                    >  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                             
>                                                                                                                                                                        
> PHP Warning:  class_implements(): Class pdo_sqlite does not exist and could not be loaded in /var/www/virtual/oneofx/html/wallabag/vendor/doctrine/dbal/lib/Doctrin/DBAL/DriverManager.php on line 210                                                                                                                                   
> PHP Warning:  in_array() expects parameter 2 to be array, boolean given in ../wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php on line 210                                                                                                                                                     
>                                                                                                                                                                   
> [Doctrine\DBAL\DBALException]                                                                                                                                       
> The given 'driverClass' pdo_sqlite has to implement the \Doctrine\DBAL\Driv                                                                                     er interface. 
>
> And a lookup of the webfrontend returns
>> request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\DBALException: The given 'driverClass' pdo_sqlite has to implement the \Doctrine\DBAL\Driver interface. at ../wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 191) {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): The given 'driverClass' pdo_sqlite has to implement the \\Doctrine\\DBAL\\Driver interface. at ../wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:191)"} []

I checked all settings twice, but see no error. SQLite is present and active and the DB file is there.

### Environment

* wallabag version : 2.3.6
* How did you install wallabag?  package
* Last wallabag version that did not exhibit the issue (if applicable): pretty old 2.x
* php version: 7.2.13
* OS: centOS
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Additional Infos

> php -i
> ...
> PDO
> 
>PDO support => enabled
>PDO drivers => mysql, pgsql, sqlite
>
>pdo_mysql
>
>PDO Driver for MySQL => enabled
>Client API version => mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
>
>Directive => Local Value => Master Value
>pdo_mysql.default_socket => /var/lib/mysql/mysql.sock => /var/lib/mysql/mysql.sock
>
>pdo_pgsql
>
>PDO Driver for PostgreSQL => enabled
>PostgreSQL(libpq) Version => 9.2.6
>Module version => 7.2.13
>Revision =>  $Id: 9c5f356c77143981d2e905e276e439501fe0f419 $ 
>
>pdo_sqlite
>
>PDO Driver for SQLite 3.x => enabled
>SQLite Library => 3.20.1
>
> sqlite3
>
>SQLite3 support => enabled
>SQLite3 module version => 7.2.13
>SQLite Library => 3.20.1
>
>Directive => Local Value => Master Value
>sqlite3.extension_dir => no value => no value

parameters.yaml
> # This file is auto-generated during the composer install
> parameters:
>    database_driver: pdo_sqlite
>    database_driver_class: null
>    database_host: 127.0.0.1
>    database_port: null
>    database_name: wallabag
>    database_user: root
>    database_password: null
>    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
>    database_table_prefix: wallabag_

**Comment by j0k3r** [comment]
Looks like a weird issue.
Have you tried to remove the cache `rm -rf var/cache/*` and then retry?

**Comment by Matthias84** [comment]
Thanks, now the composer runs fine. Unfortunatly this seems to result in a broken build?

There is no css/logo/.. at the login page and when I login, I run into a new error:
> An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT w0_.id AS id_0 FROM "wallabag_entry" w0_ WHERE w0_.user_id = ? AND w0_.is_starred = 1 GROUP BY w0_.id ORDER BY w0_.starred_at DESC' with params [2]: SQLSTATE[HY000]: General error: 1 no such column: w0_.starred_at").
Should I remove the db and start from scratch?

**Comment by j0k3r** [comment]
You should run the migration.
Can't you run `make install`?

**Comment by Matthias84** [comment]
Now I did make install and make update did the trick and solved the SQL issue.
Unfortunately no GFX and CSS even, if I clean my browser cache. any ideas?

**Comment by Matthias84** [comment]
I noticed, that parameters.yml domain name wasn't only the domain but full path to the installation
`domain_name:` 'https://mydomain.de/wallabag/web'
One more `make update` and it's working fine :+1:

**Comment by TheNomad11** [comment]
I got exactly the same error message after upgrading from 2.2.1 to 2.3.7 and can no longe use Wallabag (error 500)

**Environment**

- wallabag version : 2.3.7
- How did you install wallabag? https://got-tty.org/installation-von-wallabag-auf-debian-jessie
- Last wallabag version that did not exhibit the issue (if applicable): 2.2.1
- php version: 5.6.40
- OS: Ubuntu 14.04
- type of hosting (shared or dedicated): VPS
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

I tried the suggested options but without success. Again and agian the same error message

[Doctrine\DBAL\DBALException]                                                
  The given 'driverClass' pdo_mysql has to implement the \Doctrine\DBAL\Driver interface.                                                                 
                                                                               

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-cmd event terminated with an exception

                                                                                                                    
  [RuntimeException]                                                                                                
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                         
                                                                                                                    
                                                                                                                    
                                                                                                                    
  PHP Warning:  class_implements(): Class pdo_mysql does not exist and could not be loaded in /var/www/html/wallab  
  ag/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php on line 210                                           
  PHP Warning:  in_array() expects parameter 2 to be array, boolean given in /var/www/html/wallabag/vendor/doctrin  
  e/dbal/lib/Doctrine/DBAL/DriverManager.php on line 210                                                            
                                                                                                                    
                                                                                                                    
    [Doctrine\DBAL\DBALException]                                                                                   
    The given 'driverClass' pdo_mysql has to implement the \Doctrine\DBAL\Drive                                     
    r interface.

**Comment by tcitworld** [comment]
@TheNomad11 Are you sure you got the `pdo_mysql` extension installed ?
