### ISSUE TITLE
Changing password via mysql  not working. 

### ISSUE THREAD

**Issue by TinkerFu** [wallabag/wallabag#3891]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details
Unable to use the forgot password for some reason. 
Changed password via this article: 
https://github.com/sovereign/sovereign/issues/643

### Environment

* wallabag version 2.3.4
* How did you install wallabag? Git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
* OS: Debian 9 ( crunchbang ++ )
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Mysql

### Steps to reproduce/test case
Went to http://www.sha1-online.com/
Entered newpasswordusernamesalt with no spaces. 
Took resulting hash and updated my wallabag_user table. 
UPDATE wallabag_user set password="newpasswordhash" where username="username";

Everything updated just fine.  Unable to login.   Still getting bad credentials error.

**Comment by j0k3r** [comment]
Why does the forgot password does work in the first place?
Did you get an error? What's in your log (ie: `var/log/prod.log`)?

**Comment by TinkerFu** [comment]
I fixed the email issue and got logged back in. For future reference is that process still valid for changing a password via mysql or is there another way?

**Comment by j0k3r** [comment]
From sovereign? Absolutely not. It's pretty damn old and completly outdated.
