### ISSUE TITLE
Falcoholic + other SB Nation sites site config

### ISSUE THREAD

**Issue by kmlucy** [wallabag/wallabag#3892]
### Issue details

Articles like [this](https://www.thefalcoholic.com/2019/2/26/18238771/assessing-the-status-of-every-falcons-unrestricted-free-agent-on-the-roster-grady-jarrett-dan-quinn) and [this](https://www.buffalorumblings.com/2019/2/26/18240822/few-free-agent-safeties-make-sense-for-buffalo-bills-earl-thomas-chris-conte-mike-adams) don't load properly when the headings of paragraphs are links. 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.5
* How did you install wallabag? Docker

**Comment by j0k3r** [comment]
Have you tried on the 2.3.6?

**Comment by kmlucy** [comment]
Yes, same result on 2.3.6.

**Comment by j0k3r** [comment]
Could you properly describe what's wrong with these 2 links? Because they seems to be well parsed on 2.3.6.

**Comment by kmlucy** [comment]
Using the first one as an example, if you look at the original article, the names of the players are links and serve as the headings for each section. In Wallabag, the names don't show up. 

![](https://i.imgur.com/JdryDLF.png)

![](https://i.imgur.com/e4DdMbz.png)
