### ISSUE TITLE
Possibility to disable HTTPS redirect?

### ISSUE THREAD

**Issue by jepster** [wallabag/wallabag#3903]
### Issue details

Wallabag always redirects me to a HTTPS url. Even on my local system, where I want to try things. How can I disable the automatic HTTPS redirect?

I am not posting to https://community.wallabag.org/ (forum) because it has an invalid SSL certificate.

### Environment

* wallabag version: 2.3.7
* How did you install wallabag?: "git clone"
* php version: 7.1.13
* OS: MacOSX
* type of hosting (shared or dedicated): Local machine (MAMP)
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Clone wallabag via Git, run composer install, insert the values for parameters.yml file. Then point apache webserver to the web directory. Open the host via webbrowser. Wallabag will always redirect you to the https url.

**Comment by j0k3r** [comment]
We do not have a redirect to https rule in wallabag.
I'm running it locally without any issue about that and without any local ssl certificat.

What domain name are you using locally?
Also, what value did you define for `domain_name` in `parameters.yml`?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
