### ISSUE TITLE
https://wallabag.org/ down

### ISSUE THREAD

**Issue by ewolfe** [wallabag/wallabag#3907]
https://wallabag.org/ is returning 502 Bad Gateway

**Comment by j0k3r** [comment]
We got notified at 3am. It's back now, thanks for the issue.

**Comment by TheNomad11** [comment]
500 Internal Server Error
https://doc.wallabag.org/en/admin/upgrade.html

**Comment by j0k3r** [comment]
@TheNomad11 fixed too, thanks!
