### ISSUE TITLE
Add Hungarian language

### ISSUE THREAD

**Issue by domag02** [wallabag/wallabag#3910]
I would like to add Hungarian language.

**Comment by Kdecherf** [comment]
Hello @domag02,

If you are able to translate the files from another language, you can follow this documentation to add a new language: https://doc.wallabag.org/en/developer/translate.html

Even if you're not a git user you should be able to fork this repository and edit files without leaving your browser using the inline editor of GitHub :)

**Comment by domag02** [comment]
@Kdecherf : Thanks!

**Comment by j0k3r** [comment]
See https://hosted.weblate.org/languages/hu/wallabag/
