### ISSUE TITLE
Improvement : Article is an audio or video : "Time to read" should be the media duration

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#3912]
### Issue details

Simple example, add a youtube video page to wallabag. The "time to read" indicator is "< 1 min". It would be better to show the duration of the media.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.5
* How did you install wallabag? Via `git clone` or by downloading the package? Docker
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.1
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
PostGres

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by j0k3r** [comment]
Might be related to https://github.com/wallabag/wallabag/issues/880

**Comment by romu70** [comment]
Yep. I searched indeed before posting, but obviously, I missed something.

**Comment by j0k3r** [comment]
I don't say it's a duplicate :)

**Comment by romu70** [comment]
I do say :D because the idea is expressed in the discussion of the issue.

**Comment by nicosomb** [comment]
> I do say :D because the idea is expressed in the discussion of the issue.

And you are right 😉 I close this issue.
