### ISSUE TITLE
Slow query when Wallabager checks a new page on visit.

### ISSUE THREAD

**Issue by shtrom** [wallabag/wallabag#3919]
I have seen this in my slow query log (prepare for meta):
```sql
mariadb root@localhost:wallabag> explain SELECT w0_.id AS id_0, w0_.uid AS uid_1, w0_.title AS title_2, w0_.url AS url_3, w0_.is_archive
                                 d AS is_archived_4, w0_.is_starred AS is_starred_5, w0_.content AS content_6, w0_.created_at AS created
                                 _at_7, w0_.updated_at AS updated_at_8, w0_.published_at AS published_at_9, w0_.published_by AS publishe
                                 d_by_10, w0_.starred_at AS starred_at_11, w0_.mimetype AS mimetype_12, w0_.language AS language_13, w0_
                                 .reading_time AS reading_time_14, w0_.domain_name AS domain_name_15, w0_.preview_picture AS preview_pic
                                 ture_16, w0_.http_status AS http_status_17, w0_.headers AS headers_18, w0_.origin_url AS origin_url_19,
                                  w0_.user_id AS user_id_20 FROM `wallabag_entry` w0_ WHERE w0_.url = 'https://github.com/wallabag/walla
                                 bag/issues?utf8=✓' AND w0_.user_id = 1;
+----+-------------+-------+------+----------------------+----------------------+---------+-------+------+-------------+
| id | select_type | table | type | possible_keys        | key                  | key_len | ref   | rows | Extra       |
+----+-------------+-------+------+----------------------+----------------------+---------+-------+------+-------------+
| 1  | SIMPLE      | w0_   | ref  | IDX_F4D18282A76ED395 | IDX_F4D18282A76ED395 | 5       | const | 5592 | Using where |
+----+-------------+-------+------+----------------------+----------------------+---------+-------+------+-------------+
1 row in set
```
Note the number of rows that needed to be inspected.

It essentially happens everytime I open a tab in a browser running Wallabager. It looks to me like we'd need a new compound index on `user_id` AND something that relates to the `url`.

Now, the problem is that the `url` is a `longtext`, so we can't place an index directly on it. I would suggest adding a column containing a (fast) hash of the URL, so it's a `VARCHAR` of a known size, and include that in an index on `(`user_id`, `url_hash`)`.

This will also require changing all queries that do a `WHERE url_hash=MD5('http://...`)` (we're cool with MD5, there's nothing security-related here, just performance). Note however [0], which further points out.

> If an application stores values from a function such as MD5() or SHA1() that returns a string of hex digits, more efficient storage and comparisons can be obtained by converting the hex representation to binary using UNHEX() and storing the result in a BINARY(N) column. Each pair of hexadecimal digits requires one byte in binary form, so the value of N depends on the length of the hex string. N is 16 for an MD5() value and 20 for a SHA1() value. For SHA2(), N ranges from 28 to 32 depending on the argument specifying the desired bit length of the result. 

(My Wallabag is a bit old: 2.3.2, because of a limitation I currently have with ext-tidy on OpenBSD; so maybe this has already been fixed).

[0] https://dev.mysql.com/doc/refman/5.5/en/encryption-functions.html#function_md5

**Comment by shtrom** [comment]
> (My Wallabag is a bit old: 2.3.2 [...] so maybe this has already been fixed).

Looking at the code, it doesn't look like it has.

**Comment by j0k3r** [comment]
Thanks for this clear explanation :+1: 
We are already aware of the problem, see https://github.com/wallabag/wallabag/issues/3157
And this is we have already starded (using a hash instead of the url) but not yet finished: https://github.com/wallabag/wallabag/pull/3158
