### ISSUE TITLE
missing translation top menu

### ISSUE THREAD

**Issue by evs-pn** [wallabag/wallabag#3920]
### Issue details

There is a missing translation for a top menu tooltip. 
data-tooltip="menu.top.random_entry"

In the "src/Wallabag/CoreBundle/Resources/translations/messages.*.yml" files you have to add:

menu:
      top:
         random_entry: "Random entry"

### Environment

* wallabag version (or git revision) that exhibits the issue: bfd69c7

### Steps to reproduce/test case

Using material theme and mouse over the random entry icon in the top menu.

**Comment by j0k3r** [comment]
Feel free to fork and provide a PR to fix it 👍

**Comment by j0k3r** [comment]
Hum random entry only exists in the 2.4 branch. That's why it's not defined in the master.
https://github.com/wallabag/wallabag/blob/2.4/src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml#L40

How do you find that using the master? :thinking:
