### ISSUE TITLE
Attempted to call function "token_get_all" from namespace "Doctrine\Common\Annotations"

### ISSUE THREAD

**Issue by nimonimonimo** [wallabag/wallabag#3923]
### Issue details

After some fiddling got composer install and wallabag install script to run. Now pointing web browser to the project I get 500-error and in error log of nginx this error:

2019/04/07 14:06:35 [error] 17733#101702: *592 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "token_get_all" from namespace "Doctrine\Common\Annotations". in /usr/local/www/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/TokenParser.php:56
Stack trace:
#0 /usr/local/www/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/PhpParser.php(57): Doctrine\Common\Annotations\TokenParser->__construct('<?php namespace...')
#1 /usr/local/www/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(415): Doctrine\Common\Annotations\PhpParser->parseClass(Object(ReflectionClass))
#2 /usr/local/www/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(334): Doctrine\Common\Annotations\AnnotationReader->collectParsingMetadata(Object(ReflectionClass))
#3 /usr/local/www/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(214): Doctrine\C" while reading response header from upstream, client: x.x.x.x, server: webhost.se, request: "GET /nwb2/app.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "webhost.se"

### Environment
 /usr/local/www/wallabag]$ bin/console --env=prod about
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665
 -------------------- ---------------------------------------------- 
  Symfony                                                            
 -------------------- ---------------------------------------------- 
  Version              3.3.18                                        
  End of maintenance   01/2018 Expired                               
  End of life          07/2018 Expired                               
 -------------------- ---------------------------------------------- 
  Kernel                                                             
 -------------------- ---------------------------------------------- 
  Type                 AppKernel                                     
  Name                 app                                           
  Environment          prod                                          
  Debug                false                                         
  Charset              UTF-8                                         
  Root directory       ./app                                         
  Cache directory      ./var/cache/prod (7.5 MiB)                    
  Log directory        ./var/logs (11 KiB)                           
 -------------------- ---------------------------------------------- 
  PHP                                                                
 -------------------- ---------------------------------------------- 
  Version              7.3.2                                         
  Architecture         64 bits                                       
  Intl locale          en_US_POSIX                                   
  Timezone             Europe/Stockholm (2019-04-07T14:46:25+02:00)  
  OPcache              true                                          
  APCu                 true                                          
  Xdebug               false                                         
 -------------------- ---------------------------------------------- 

git describe --tags
2.1.6-1315-gb1992b34

Installed via git clone.

OS:  FreeBSD 11.2-RELEASE-p5
In jail on local machine.
MySQL used as db.

**Comment by j0k3r** [comment]
wallabag isn't yet ready for PHP 7.3.
This might be fixed in the upcoming 2.4 version.

**Comment by nimonimonimo** [comment]
Thanks for reply! Must have missed that requirement :)

Any clue about when 2.4 version will be released?

**Comment by j0k3r** [comment]
No clue sorry.
But you can test by downloading the 2.4 branch

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/issues/3537#issuecomment-499134956
