### ISSUE TITLE
Why web/app.php and how to avoid mod_rewrite

### ISSUE THREAD

**Issue by techexo** [wallabag/wallabag#3931]
Hi to all devs :)

I am currently trying to update the documentation for wallabag's installation (which is asked repeatedly by users).

## `app.php` vs `index.php`
Among other things (that I might develop in other issue tickets), I am wondering why wallabag doesn't use the classical `(web/)index.php` instead of `(web/)app.php`. 
Indeed, there is probably no actual need for this distinction (pardon me if I'm mistaken) and it obligates to clutter the webserver configuration file with this information. Couldn't we rename `app.php` in `index.php`?

## Deactivated `mod_rewrite` allows one to see `web/` listing
Another troubling (and related thing) is with apache2 `mod_rewrite`: if this module is disabled, going to wallabag's root (let it be `https://wallabag.lvh.me/`) doesn't display wallabag but the index of the `web/` folder, a click on `app.php` then gives access to `https://wallabag.lvh.me/app.php/login` or `/app.php/quickstart` and so on.

However, **we shouldn't be in a situation where it is possible to see the listing of `web/` directory, even with `mod_rewrite` deactivated!** _(Note that it circles back here to the issue described above using `app.php` instead of `index.php`, as the latter would be loaded automatically, but the former doesn't without tweaking the config file.)_

## Redirections are broken without `mod_rewrite`
Finally, another issue emerges here: if we force Apache2 to consider `app.php` as the file to load (using `DirectoryIndex app.php` in the virtualhost's config), the web browser allows direct access using the URL `https://wallabag.lvh.me/` (note that `app.php is not displayed, as it is automatically loaded). But redirection is  then made by wallabag to `https://wallabag.lvh.me/login` or `https://wallabag.lvh.me/quickstart` even if `mod_rewrite` is deactivated. 

**We should find a way to fix these redirections**, as they should be respectively `https://wallabag.lvh.me/app.php/login` or `https://wallabag.lvh.me/app.php/quickstart` for them to actually work.

_Sorry for the novel above, but I think this is this need for tweaking that can make the experience with wallabag as an administrator a bit miserable. I know `mod_rewrite` is almost always activated, but it should work out of the box if it is not specified as an actual dependency_ 😃

**Comment by techexo** [comment]
I am seeing only now that `web/.htaccess` contains quite a bit of information about some of these issues.

The [current documentation for installation on Apache2.4](https://doc.wallabag.org/en/admin/installation/virtualhosts.html#configuration-on-apache) is a bit stupid as it rewrites some stuff already in the `.htaccess`, disable it, and forget the fallbacks measures that were taken! 😞 I'll fix that in the version of the documentation that I'm writing, but for anyone interested:

> `AllowOverride` in Apache2.4 is now defaulted to `None`, which consequently disables the loading of `.htaccess` files.

For a "classical" Apache2.4 configuration, we should get rid of all this nonsense rewrite instructions that are already in the `.htaccess`, and use the following instruction in the vhost:
```apache
<VirtualHost *:80>
   ServerName wallabag.lvh.me
   ServerAlias wallabag.lvh.me
   <Directory /var/www/wallabag/web>
       Require all granted
       AllowOverride FileInfo Indexes Options=MultiView
   </Directory>
</VirtualHost>
```

**Comment by j0k3r** [comment]
About the `app.php` it was the _defacto_ when building a website using Symfony version <4, you can find it in many projects:
- https://github.com/j0k3r/f43.me/tree/master/web
- https://github.com/slince/phpdish/tree/master/web
- https://github.com/symfony/demo/tree/v1.0.4/web (that version use the Symfony 3 instead of 4)

This can of course be moved to `index.php` but it'll need some tests to ensure no change are required to the webserver in order to be used. Mostly to avoid people doing extra more configuration once their wallabag is already running.

About `mod_rewrite` I think it just should be always activated. It's the only way to have _nice_ urls.

**Comment by techexo** [comment]
@j0k3r OK, didn't know the specifics for Symfony. 

Actually, once the `.htaccess` is enabled, everything is going quite smoothly on Apache2, with or without `mod_rewrite`. I maybe wasn't clear in my presentation: my idea wasn't to disable `mod_rewrite`, but to ensure that wallabag could run without it (and it can!). :smile:

I'm currently trying to work out how to install wallabag in a sub-folder with nginx (which is a pain in the *** compared to a sub-domain). More to come, thanks for your answer!
