### ISSUE TITLE
Use stored domain credentials for all its subdomains

### ISSUE THREAD

**Issue by dsaoijhlgfdngfsd** [wallabag/wallabag#3936]
### Issue details

Wallabag uses Graby to fetch the links it stores. Graby uses site-specific configuration files, that contain parsing rules and/or paywall configuration. Also, configuration files may be specified for a domain and in turn cover all subdomains on that domain.

When grabbing a link, a SiteConfig is created for the host; in the process a configuration file is loaded from the disk and credentials are loaded from the DB (if available - in both cases). At this point, while we can have site configuration on the domain-level, all the credentials are fetched on the hostname level. _As a result, for some news portals one needs to specify credentials for all the subdomains used by the domain. (As an example take https://ihned.cz, which has articles on various subdomains)_

I suggest to enable storing credentials in the format 

> .domain.com (or .ihned.cz for the given exmaple)

which would make it more aligned with the site config capabilities/specification.

### Environment

* wallabag version (or git revision) that exhibits the issue: **all**
* How did you install wallabag? **Docker**
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): **PostgreSQL**

**Comment by j0k3r** [comment]
Did you try to just write `ihned.cz` has domain name in the site credentials editon UI?

**Comment by dsaoijhlgfdngfsd** [comment]
Just to be sure I understand - do you suggest I add `ihned.cz` to the `Site credentials` section in the Wallabag GUI?

I did try that before creating an issue. Here's an example: 

I am trying to add 

> https://archiv.ihned.cz/c1-66557420-nerovny-byznys-lva-a-draka-cesko-by-melo-byt-agresivnejsi-letecka-spojeni-ma-export-ale-vazne

to Wallabag. This is my `Site credentials` section:
<img width="908" alt="Screenshot 2019-04-23 at 19 09 44" src="https://user-images.githubusercontent.com/48893334/56601474-c007cc80-65ea-11e9-9062-834ab6607557.png">

With this setup (and a proper graby site config file) Wallabag was unable to pass the paywall. Looking at the (debug) logs I see:

> [2019-04-23 17:04:52] graby.DEBUG: Auth: no credentials available for host. {"host":"archiv.ihned.cz"} []

Looking at the source code, this cannot work. Method `GrabySiteConfigBuilder::buildForHost` takes host as the argument and this host is determined as `$request->getHost()`, thus in this case `archiv.idnes.cz`. Within the `GrabySiteConfigBuilder::buildForHost` the following code is called 

```
$credentials = null;
if ($this->currentUser) {
    $credentials = $this->credentialRepository->findOneByHostAndUser(
        $host, 
        $this->currentUser->getId()
    );
}
```
where function `findOneByHostAndUser()` is:
```

public function findOneByHostAndUser($host, $userId)
    {
        $res = $this->createQueryBuilder('s')
            ->select('s.username', 's.password')
            ->where('s.host = :hostname')->setParameter('hostname', $host)
            ->andWhere('s.user = :userId')->setParameter('userId', $userId)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        if (null === $res) {
            return;
        }

        // decrypt user & password before returning them
        $res['username'] = $this->cryptoProxy->decrypt($res['username']);
        $res['password'] = $this->cryptoProxy->decrypt($res['password']);

        return $res;
    }
```
The important part in this case is 
```
->where('s.host = :hostname')->setParameter('hostname', $host)
```
which suggests credentials are selected based on equality to the requested host.

In contrast to that, graby site-configuration files are located as follows (bunch of code omitted preceding this snippet):
```
$try = [$host];
// should we look for wildcard matches
// will try to see for a host without the first subdomain (fr.example.org & .example.org)
// @todo: should we look for all possible subdomain? (fr.m.example.org &.m.example.org & .example.org)
if (!$exactHostMatch) {
    $split = explode('.', $host);

    if (\count($split) > 1) {
        // remove first subdomain
        array_shift($split);
        $try[] = '.' . implode('.', $split);
    }
}
```
In this case we have `$try = ['archiv.ihned.cz', '.ihned.cz'], thus the host is matched agains the wildcard site-config.

**Comment by j0k3r** [comment]
Good point 👍
