### ISSUE TITLE
Add archived_at field for entries

### ISSUE THREAD

**Issue by lizyn** [wallabag/wallabag#3947]
I'm using 2.3.7. Currently, fields like `updated_at`, `starred_at` are available for entries. However, I think an `archived_at` field would useful too. My use case for this is to track how many articles I add (using `created_at`) and read/archive each week.

There is is a similar pull https://github.com/wallabag/wallabag/pull/3330 that adds support for `starred_at` field. Maybe by following the code changes there, it won't be hard to add an `archived_at` as well. But I'm not sure, being quite unfamiliar with coding, especially PHP. 
###

**Comment by j0k3r** [comment]
The PR you mention adds that field in the database.
It'll be available in the 2.4.0 release (no ETA yet).

**Comment by lizyn** [comment]
Really sorry that I didn't see it before opening the issue.
