### ISSUE TITLE
Export: Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by mart-e** [wallabag/wallabag#3950]
### Issue details

Trying to export a long article in epub fails with a "Maximum execution time of 30 seconds exceeded".

### Environment

* wallabag version: 2.3.6
* How did you install wallabag? Via `git clone`
* php version: 7.0
* OS: Debian Jessie
* type of hosting: dedicated
* which storage system you choose at install: SQLite

### Steps to reproduce/test case

1. save the following long article in wallabag: https://www.inkandswitch.com/local-first.html
2. export it in epub
--> Error `Error: Maximum execution time of 30 seconds exceeded`

Details in log:
```
2019/05/06 08:52:08 [error] 652#652: *661332 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /srv/../wallabag/vendor/grandt/phpepub/src/PHPePub/Helpers/ImageHelper.php on line 287" while reading response header from upstream, client: 81.240.117.159, server: read.mart-e.be, request: "GET /export/402.epub HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "read.mart-e.be", referrer: "https://read.mart-e.be/view/402"
```

Is there a way to either increase the maximum time or to export in epub using a cli ?

**Comment by tcitworld** [comment]
You can increase maximum execution time inside your `php.ini` config file by changing `max_execution_time`.
CLI export currently only supports JSON.

**Comment by mart-e** [comment]
Great thanks, it works. I guess nothing needed at wallabag level.
30 seconds to generate an epub seems a lot to me but maybe there is a reason (anyway to see with phpepub probably)
