### ISSUE TITLE
Buttons not removed from content

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#3953]
### Issue details

When fetching the content from the link below the buttons are not removed.

![image](https://user-images.githubusercontent.com/3419050/57464440-044acc00-727d-11e9-92c4-2db85b079d8f.png)

f43.me does remove the buttons.

Link: https://medium.com/@antoine.ansel/mots-de-passe-et-entropie-d5256019d06d

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? package (yunohost)
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.0
* OS: Linux
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Grab the link https://medium.com/@antoine.ansel/mots-de-passe-et-entropie-d5256019d06d

**Comment by j0k3r** [comment]
f43.me does remove the buttons because it uses a most updated config than the 2.3.2 version of wallabag.
Your version is outdated.
You should update it to fix that problem.

**Comment by nicofrand** [comment]
Thanks, will do soon! Sorry for the noise
