### ISSUE TITLE
 Impossible import : Maximum execution time

### ISSUE THREAD

**Issue by prolibre** [wallabag/wallabag#3957]
I notice this day that I have an error with each import.

Example of trying to import: https://www.actu-environnement.com/ae/news/Autorisation-environnementale-projet-decret-supprime-consultations-genantes-33386.php4

I have the message: 
PHP Fatal error: Maximum execution time of 120 seconds exceeded in /**/wallabag/vendor/symfony/symfony/src/Symfony/Component/Intl/Locale.php on line 72

I had 30 seconds in my setting but I went up to 120 to test.

This message appears regardless of the site (midi-libre.fr, wikipedia etc).

I don't use wallabag every day but I didn't touch anything and a few days ago it was working. The only changes for the regular updates of my debian.

No connectivity problems: I connect to the sites from the server under lynx

### Environment
* debian stretch
* wallabag 2.3.7
* PHP 7.3.5

**Comment by tcitworld** [comment]
Duplicate from #3926
