### ISSUE TITLE
Cannot fetch articles

### ISSUE THREAD

**Issue by nicofrand** [wallabag/wallabag#3958]
### Issue details

I did a fresh install of wallabag with `make dev` (I want to hack some things, I did not touch the code yet). The installation was fine, every missing lib was installed etc.

But I can't grab any article: the article is added but without content. Here are the logs:

```
[2019-05-08 19:11:22] app.ERROR: Error while saving an entry {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: A non well formed numeric value encountered at /home/nicofrand/www/wallabag/vendor/j0k3r/php-readability/src/Readability.php:1118)","entry":"[object] (Wallabag\\CoreBundle\\Entity\\Entry: {})"} [] 
```

**I tested with graby and readability directly, I have no issues…**

Line 1118 https://github.com/j0k3r/php-readability/blob/master/src/Readability.php#L1118 the values are:

`$grandParentNode->getAttributeNode('readability')->value` = `'4,0909090909091'`.
`$contentScore` = `1,3636363636364`.

### Environment

* wallabag version (or git revision) that exhibits the issue: ea54c2ad
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): dev
* php version: PHP 7.2.17-0ubuntu0.19.04.1 Development Server
* OS: Ubuntu 19.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Any link really… 
Example of a link: https://blog.eleven-labs.com/fr/po-vs-pm-like-batman-vs-superman/

That might come from my config since I have no issue with a prod version of wallabag on my server but I can't find why this happens… Would you have an idea?

**Comment by j0k3r** [comment]
I found it :)

**Comment by nicofrand** [comment]
Thanks a lot, it now works perfectly. Just by curiosity, how did you finally manage to reproduce?

**Comment by j0k3r** [comment]
I was working a complete different topic (on Graby 2.0 with httplug) and got the error.
