### ISSUE TITLE
ErrorException upon installation

### ISSUE THREAD

**Issue by korewazombie** [wallabag/wallabag#3961]
### Issue details

i'm getting this error upon installation:

`www-data@raspberrypi:~/wallabag$ make install
composer.phar not found, we'll see if composer is installed globally.
HEAD is now at 9796a3aa... Release wallabag 2.3.7
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                           

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

PHP Warning:  require(/nas/data/wallabag/app/../vendor/autoload.php): failed to open stream: No such file or directory in /nas/data/wallabag/app/autoload.php on line 9
PHP Fatal error:  require(): Failed opening required '/nas/data/wallabag/app/../vendor/autoload.php' (include_path='.:/usr/share/php') in /nas/data/wallabag/app/autoload.php on line 9
GNUmakefile:14: recipe for target 'install' failed
make: *** [install] Error 255
`

### Environment

* wallabag version (or git revision) that exhibits the issue: newest
* download via git-clone
* php version: 7.3 AND 5.6
* OS: raspian stretch-lite
* type of hosting (shared or dedicated): dedicated
* which storage system mysql / mariadb
* apache2 webserver

### Steps to reproduce/test case

since i've had installed php7.3 and i was aware of the fact that this is not running with wallabag i tried to set up in parallel php5.6 using libapache2-mod-fcgid. i found a useful tutorial for doing so here: https://tecadmin.net/install-multiple-php-version-with-apache-on-debian/

i ran the installation as user www-data. during the installation the issue occured.

since var/www/wallabag is only a symbolic link pointing to /nas/data/wallabag, i checked the permissions of the file. however var/www/wallabag has the permission 777. i changed the ownership of the directory from root to www-data and ran the installation process again.

same error message.

i understand that the issue has to do with conflicting php7..3. wondering whether this can be avoided.

**Comment by j0k3r** [comment]
Could you try now that the 2.3.8 is released?

Just for information, we aren't sure the 2.3.8 is running OK on PHP 7.3.
But we are sure the upcoming 2.4 will run OK on PHP 7.3.

**Comment by 4oo4** [comment]
I'm getting this with 2.3.8, and using php 7.3.5-1+ubuntu16.04.1+deb.sury.org+1. Also @korewazombie, you should have your permissions as 755 for the folder and 644 for files. Having permissions that open, especially when it's exposed to the internet, is a really bad idea.

**Comment by j0k3r** [comment]
Could you try again on the master?

**Comment by 4oo4** [comment]
That fixed the install warnings for me, but got a different fatal error when it clears the cache:

```
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
mailer_port (false): 
mailer_encryption (null): 
mailer_auth_mode (null): 
sentry_dsn (null): 
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Declaration of DoctrineORMEntityManager_0000000054054dfd0000000062aa310c616b8355fd16583861fa0e6675c7c349::initializeProxy() must be compatible with ProxyManager\Proxy\LazyLoadingInterface::initializeProxy(): bool in /var/www/wallabag/var/cache/prod/appProdProjectContainer.php on line 8875
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-cmd event terminated with an exception

                                                                                                                                                                  
  [RuntimeException]                                                                                                                                              
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                       
                                                                                                                                                                  
                                                                                                                                                                  
                                                                                                                                                                  
  PHP Fatal error:  Declaration of DoctrineORMEntityManager_0000000054054dfd0000000062aa310c616b8355fd16583861fa0e6675c7c349::initializeProxy() must be compatib  
  le with ProxyManager\Proxy\LazyLoadingInterface::initializeProxy(): bool in /var/www/wallabag/var/cache/prod/appProdProjectContainer.php on line 8875      
                                                                                                                                                                  

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

**Comment by tcitworld** [comment]
Could you manually `rm -rf` it ? `var/cache/prod/*`

**Comment by 4oo4** [comment]
@tcitworld Yep, I can definitely do that. I'm wondering if the cache thing might have been something with permissions, I might have accidentally `chown`'ed some of the files when I was upgrading it.

**Comment by j0k3r** [comment]
No it’s not. That error is related to code update between the 2.3.8 and the upcoming 2.4.0.
Is your problem fixed?

**Comment by 4oo4** [comment]
@j0k3r Gotcha. My issue was solved by upgrading my composer, even though I got those warnings when installing everything still worked, I'm happy to test whatever else you guys want to help with php 7.3 compatibility.

So I think it's up to @korewazombie to test now.

**Comment by korewazombie** [comment]
@4oo4 sure, i wanted to test it, but i ran unfortunately into a major mysql/mariadb problem which is completely unrelated to wallabag. have to fix this first, but this might take some time as i think i need assistance...

**Comment by korewazombie** [comment]
tried again. same error:

```
www-data@raspberrypi:/nas/data/wallabag$ make install
composer.phar not found, we'll see if composer is installed globally.
Note: checking out '2.3.8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9bbafdaa... Release wallabag 2.3.8
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file

                                                                               
  [ErrorException]                                                             
  "continue" targeting switch is equivalent to "break". Did you mean to use "  
  continue 2"?                                                                 
                                                                               

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

PHP Warning:  require(/nas/data/wallabag/app/../vendor/autoload.php): failed to open stream: No such file or directory in /nas/data/wallabag/app/autoload.php on line 9
PHP Fatal error:  require(): Failed opening required '/nas/data/wallabag/app/../vendor/autoload.php' (include_path='.:/usr/share/php') in /nas/data/wallabag/app/autoload.php on line 9
GNUmakefile:14: recipe for target 'install' failed
make: *** [install] Error 255

```

**Comment by j0k3r** [comment]
Have you installed composer?

**Comment by korewazombie** [comment]
Composer version 1.2.2 2016-11-03 17:43:15

**Comment by j0k3r** [comment]
Please upgrade it to the latest version, which is 1.8.5: `composer upgrade`

**Comment by korewazombie** [comment]
sorry, i've got troubles upgrading composer.. 
getting this error:
`pi@raspberrypi:~ $ composer upgrade

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "upgrade" is not defined.    `

**Comment by j0k3r** [comment]
That command was introduced later I guess.
Try `composer selfupdate`

**Comment by korewazombie** [comment]
same error

**Comment by j0k3r** [comment]
Well, run `composer` and check if there is something about upgrading composer itself.
Otherwise re-install it: https://getcomposer.org/download/

**Comment by korewazombie** [comment]
i re-installed it.
```
Composer (version 1.8.6) successfully installed to: /root/composer.phar
Use it: php composer.phar
```
however, if i run composer --version i get the old version...

**Comment by j0k3r** [comment]
You should update the `composer` binary.
Do the following: `which composer`.
It'll dump the path to the bin.
Then move the `composer.phar` to that location: `mv /root/composer.phar /PATH/TO/composer`

**Comment by korewazombie** [comment]
weird... i already moved the composer.phar to `/usr/local/bin/`

**Comment by j0k3r** [comment]
yeah but `composer.phar` is different from `composer`.

**Comment by korewazombie** [comment]
i don't understand how to resolve this problem... if i run
`composer update`
i get```

Composer could not find a composer.json file in /usr/local/bin
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```
the getting started section of the composer page is of no help in this regard..

**Comment by korewazombie** [comment]
now i got version 1.8.6
i think it just needed to restart...

**Comment by korewazombie** [comment]
tried again to install. now it circumvents the fatal error above. but still stuck in the installation:
```
www-data@raspberrypi:/nas/data/wallabag$ make install
composer.phar not found, we'll see if composer is installed globally.
Note: checking out '2.3.8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9bbafdaa... Release wallabag 2.3.8
Cannot create cache directory /var/www/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-tidy * is missing from your system. Install or enable PHP's tidy extension.
  Problem 2
    - Installation request for php-amqplib/php-amqplib v2.9.2 -> satisfiable by php-amqplib/php-amqplib[v2.9.2].
    - php-amqplib/php-amqplib v2.9.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
  Problem 3
    - php-amqplib/php-amqplib v2.9.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - php-amqplib/rabbitmq-bundle v1.14.4 requires php-amqplib/php-amqplib ^2.6 -> satisfiable by php-amqplib/php-amqplib[v2.9.2].
    - Installation request for php-amqplib/rabbitmq-bundle v1.14.4 -> satisfiable by php-amqplib/rabbitmq-bundle[v1.14.4].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.3/cli/php.ini
    - /etc/php/7.3/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.3/cli/conf.d/10-opcache.ini
    - /etc/php/7.3/cli/conf.d/10-pdo.ini
    - /etc/php/7.3/cli/conf.d/15-xml.ini
    - /etc/php/7.3/cli/conf.d/20-calendar.ini
    - /etc/php/7.3/cli/conf.d/20-ctype.ini
    - /etc/php/7.3/cli/conf.d/20-curl.ini
    - /etc/php/7.3/cli/conf.d/20-dom.ini
    - /etc/php/7.3/cli/conf.d/20-exif.ini
    - /etc/php/7.3/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.3/cli/conf.d/20-ftp.ini
    - /etc/php/7.3/cli/conf.d/20-gd.ini
    - /etc/php/7.3/cli/conf.d/20-gettext.ini
    - /etc/php/7.3/cli/conf.d/20-iconv.ini
    - /etc/php/7.3/cli/conf.d/20-json.ini
    - /etc/php/7.3/cli/conf.d/20-mbstring.ini
    - /etc/php/7.3/cli/conf.d/20-mysqli.ini
    - /etc/php/7.3/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.3/cli/conf.d/20-phar.ini
    - /etc/php/7.3/cli/conf.d/20-posix.ini
    - /etc/php/7.3/cli/conf.d/20-readline.ini
    - /etc/php/7.3/cli/conf.d/20-shmop.ini
    - /etc/php/7.3/cli/conf.d/20-simplexml.ini
    - /etc/php/7.3/cli/conf.d/20-sockets.ini
    - /etc/php/7.3/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.3/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.3/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.3/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.3/cli/conf.d/20-wddx.ini
    - /etc/php/7.3/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.3/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.3/cli/conf.d/20-xsl.ini
    - /etc/php/7.3/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
PHP Warning:  require(/nas/data/wallabag/app/../vendor/autoload.php): failed to open stream: No such file or directory in /nas/data/wallabag/app/autoload.php on line 9
PHP Fatal error:  require(): Failed opening required '/nas/data/wallabag/app/../vendor/autoload.php' (include_path='.:/usr/share/php') in /nas/data/wallabag/app/autoload.php on line 9
GNUmakefile:14: recipe for target 'install' failed
make: *** [install] Error 255
```

**Comment by j0k3r** [comment]
>     - The requested PHP extension ext-tidy * is missing from your system. Install or enable PHP's tidy extension.

**Comment by korewazombie** [comment]
php --ini
```
www-data@raspberrypi:/nas/data/wallabag$ php --ini
Configuration File (php.ini) Path: /etc/php/7.3/cli
Loaded Configuration File:         /etc/php/7.3/cli/php.ini
Scan for additional .ini files in: /etc/php/7.3/cli/conf.d
Additional .ini files parsed:      /etc/php/7.3/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.3/cli/conf.d/10-opcache.ini,
/etc/php/7.3/cli/conf.d/10-pdo.ini,
/etc/php/7.3/cli/conf.d/15-xml.ini,
/etc/php/7.3/cli/conf.d/20-calendar.ini,
/etc/php/7.3/cli/conf.d/20-ctype.ini,
/etc/php/7.3/cli/conf.d/20-curl.ini,
/etc/php/7.3/cli/conf.d/20-dom.ini,
/etc/php/7.3/cli/conf.d/20-exif.ini,
/etc/php/7.3/cli/conf.d/20-fileinfo.ini,
/etc/php/7.3/cli/conf.d/20-ftp.ini,
/etc/php/7.3/cli/conf.d/20-gd.ini,
/etc/php/7.3/cli/conf.d/20-gettext.ini,
/etc/php/7.3/cli/conf.d/20-iconv.ini,
/etc/php/7.3/cli/conf.d/20-json.ini,
/etc/php/7.3/cli/conf.d/20-mbstring.ini,
/etc/php/7.3/cli/conf.d/20-mysqli.ini,
/etc/php/7.3/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.3/cli/conf.d/20-phar.ini,
/etc/php/7.3/cli/conf.d/20-posix.ini,
/etc/php/7.3/cli/conf.d/20-readline.ini,
/etc/php/7.3/cli/conf.d/20-shmop.ini,
/etc/php/7.3/cli/conf.d/20-simplexml.ini,
/etc/php/7.3/cli/conf.d/20-sockets.ini,
/etc/php/7.3/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.3/cli/conf.d/20-sysvsem.ini,
/etc/php/7.3/cli/conf.d/20-sysvshm.ini,
/etc/php/7.3/cli/conf.d/20-tokenizer.ini,
/etc/php/7.3/cli/conf.d/20-wddx.ini,
/etc/php/7.3/cli/conf.d/20-xmlreader.ini,
/etc/php/7.3/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.3/cli/conf.d/20-xsl.ini,
/etc/php/7.3/cli/conf.d/20-zip.ini

```

**Comment by j0k3r** [comment]
Yep that's just confirm `tidy` & `bcmath` extension aren't installed 🙄

**Comment by korewazombie** [comment]
i do my best. i'm rather new to unix, please bare with me...!
i installed php-tidy and php-amqplib. it now seems to work... wallabag is still in the process of being installted..

**Comment by korewazombie** [comment]
in the very end of the installation process i'm getting the error
```
  [RuntimeException]                                                           
  Some system requirements are not fulfilled. Please check output messages an  
  d fix them.
```                                                                  
the sole problem seems to be that wallabag can't connect to the database which i alread anticipated, since i don't have the correct passwort at hand... shall i run the whole installation proccess again once i have my password ready?

**Comment by j0k3r** [comment]
Might be good idea, yeah.

**Comment by j0k3r** [comment]
Can we close the issue as the main problem is solved?

**Comment by korewazombie** [comment]
jup, wallabag works now fine with updated composer...
