### ISSUE TITLE
Wallabag - FieryFeeds synchronization issues

### ISSUE THREAD

**Issue by vdbm** [wallabag/wallabag#3971]
Wallabag seems to have new syncing issues with FieryFeeds (the iOS reader app). When synchronizing on FieryFeeds, a new notification appears “Wallabag: Request failed: not found (404)” and total numbers of articles do no longer match those in app.wallabag.it. Both FieryFeeds and Wallabag released updated versions this week, so not clear where problem resides.

**Comment by vdbm** [comment]
The issue above is partially resolved by deleting the Wallabag account on FieryFeeds entirely and then reinstalling it. The notification no longer appears, but there is still a discrepancy between all entry counts that I cannot explain: while app.wallabag.it calculates all entries as the sum of unread and archived articles, the all entries view in FieryFeeds displays the sum of unread and starred articles. Not sure if the problem resides with FF or with Wallabag.

**Comment by vdbm** [comment]
Issue is addressed. I found out that Fiery Feeds downloads only starred and unread articles.

**Comment by j0k3r** [comment]
Should we close the issue then?
What could be the problem of the first 404 you got?

**Comment by vdbm** [comment]
Yes, it can be closed. I have no idea why the first 404 occurred. But removing wallabag entirely and reinstalling it resolved the problem.

**Comment by vdbm** [comment]
The error mentioned in the meanwhile closed #3971 represented itself: when synchronizing on FieryFeeds, a new notification appears “Wallabag: Request failed: not found (404)”.
