### ISSUE TITLE
The Wallabag ecosystem within the Apple environment  

### ISSUE THREAD

**Issue by vdbm** [wallabag/wallabag#3973]
The Wallabag ecosystem within the Apple environment is starting to work really well. Having used the hosted solution on wallabag.it for some time now, I can say that the iOS experience is nearly seamless, while there is still lots of room for improvement on macOS:

1. **iOS integration**: Wallabag now works really well with FieryFeeds version 2.2. No need for the separate app (Wallabag 2 Official) anymore, except for its essential Share extension that can be accessed from within all other apps, including all browsers and twitter.

2. **macOS integration**: the only way to read articles saved on wallabag.it is via the browser. None of the non self-hosted reader apps allow you to read articles saved on wallabag.it (as of yet). Saving articles works well with the Wallabagger browser extension (or addon) in Chrome or Brave, which is also beautifully designed. Feedreader also provides a push to Wallabag saving option. Getting wallabag to work with an accomplished RSS reader (e.g. Reeder 4) is an essential priority, but unfortunately outside of wallabag's control.

3. **macOS reading experience**: the browser-only app.wallabag.it site works well and fast. There are no visual customization settings available (besides the ugly Baggy theme). If you want dark mode or font choices, you may want to install a non-wallabag extension (e.g. Reader View) as a workaround. Wallabag could definitely improve this experience.

**Comment by j0k3r** [comment]
Thanks for this summary. What’s your issue after all? The last point?

Also for 2, we sent many emails to Silvo about a wallabag integration into Reeder, we never got a single reply.

For 3, something started here https://github.com/wallabag/wallabag/pull/3791 but help are welcome

**Comment by vdbm** [comment]
First of all, my message was one of appreciation and encouragement. I paid for the wallabag.it service and am very happy I did. 
Secondly, it provides some indication on priorities: 
1. if I were you, I wouldn't spend too much energy on the iOS app as there is at least one very good alternative (except, at this stage, for the share extension); 
2. encourage your user base to speak up to the rss reader developers (I just sent a message to Silvio); and 
3. there is a trade-off to be made on app.wallabag.it: you can - and probably should - spend resources improving it now (or giving people guidance on how they can do so themselves through other extensions), knowing full well that this effort could be superseded if Silvio (or another developer) finally integrates your service. 
I will look at #3791 and try to help.

**Comment by vdbm** [comment]
More in general, I think you really have to improve your communications. You have done a great job on wallabag.org and this site can definitely make people excited. But once you got them interested and they go beyond that, they will be lost as they will discover that wallabag is still too much a service for insiders, for geeks even. E.g. on app.wallabag.it the left menu options underneath the horizontal line (Subscription, Config, etc.) are very hermetic and not easy to understand. It took me a while to figure out things (e.g. on the API clients management). In the end I got everything to work and it now works smoothly - at least on iOS - but I have to admit it was a struggle. I didn't give up and made it work, but most people will give up if you don't improve this. You really need step-by-step guides to support your users. I would also recommend a service that allows for a conversation with your community that is less geeky than Github (or Gitter). Brave and Bitwarden use Discourse. FieryFeeds uses Slack and Twitter. Since wallabag.org is already doing a great job, I would expand there.

**Comment by j0k3r** [comment]
Just to let you know that the iOS app might take full advantage of iOS 13 with dark mode & also with MacOS Catalina and the ability to have iPad app running on the Mac.
I'll close your issue in the meantime.
Keep an eye on the iOS repo: https://github.com/wallabag/ios-app
