### ISSUE TITLE
When accent in image src, wrong encoding in database

### ISSUE THREAD

**Issue by arakeis** [wallabag/wallabag#3978]
On a fully working wallabag setup, with local image : on

### Steps to reproduce/test case

on this article : https://mauditsfrancais.ca/2019/05/21/corporate-hacking/
the main image has a src : 
https://images.mauditsfrancais.ca/2019/05/6acce3fb-stéphanie-bacquere-696x378.jpg

here is an extract of the html of the article's tile on the main page :

            <div class="preview activator" style="background-image: url(https://images.mauditsfrancais.ca/2019/05/6acce3fb-steÌphanie-bacquere.jpg)"></div>

**Comment by Kdecherf** [comment]
Hello @arakeis,

Can you specify the database engine and other settings of your installation please?

**Comment by arakeis** [comment]
Hi @Kdecherf ,

Installation on a synology
apache 2.4
php7
mysql version: mariadb10
on the preview_picture field side : 
preview_picture | longtext | utf8mb4_unicode_ci |

**Comment by j0k3r** [comment]
That problem doesn't seems to happen on the 2.4 because it detect the image url as not a valid url :man_shrugging: 

![image](https://user-images.githubusercontent.com/62333/58947854-1d19a500-8789-11e9-9cba-6e5bf4e53c84.png)

**Comment by arakeis** [comment]
indeed my version in 2.2.3
