### ISSUE TITLE
Wrong display in wallabag

### ISSUE THREAD

**Issue by fchaix** [wallabag/wallabag#3988]
### Issue details

Articles from www.lopinion.fr won't parse. Works in f43.me, but not from my wallabag.

### Environment

* wallabag version (or git revision) that exhibits the issue:2.3.7
* How did you install wallabag? Via `git clone` or by downloading the package?
→ git clone
* php version: 7.3.5
* OS: archlinux
* type of hosting (shared or dedicated): dedicted
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case

Just try to add an article from this website.
[graby.log](https://github.com/wallabag/wallabag/files/3251171/graby.log)

**Comment by j0k3r** [comment]
Works great on app.wallabag.it which runs on 2.3.8.

![image](https://user-images.githubusercontent.com/62333/58861872-b07ea780-86af-11e9-8cc5-2ece7dc447b1.png)


Could you update your intance to the latest version?

**Comment by j0k3r** [comment]
Please provide a JSBin / jsfiddle containing a set of reproducible steps.
