### ISSUE TITLE
Import 413 Request entity too large 

### ISSUE THREAD

**Issue by wjjessen** [wallabag/wallabag#4002]
Even after changing my server configuration (using [Wallabag on Yunohost)](https://github.com/YunoHost-Apps/wallabag_ynh) I was having import problems. I found a python script that was able to take a large json file and chunk it up into smaller files. I thought I'd document it here for others to use. 

`import json`
`with open('C:/Users/myuserdir/Downloads/All articles.json') as infile:`
`  o = json.load(infile)`
`  chunkSize = 1000`
`  for i in xrange(0, len(o), chunkSize):`
`    with open('file_' + str(i//chunkSize) + '.json', 'w') as outfile:`
`      json.dump(o[i:i+chunkSize], outfile)`

**Comment by mattbk** [comment]
This is great! Copying below with proper indents.
```
import json
with open('Unread articles 2020-09-03.json') as infile:
    o = json.load(infile)
    chunkSize = 1000
    for i in xrange(0, len(o), chunkSize):
        with open('file_' + str(i//chunkSize) + '.json', 'w') as outfile:
            json.dump(o[i:i+chunkSize], outfile)
```
