### ISSUE TITLE
wallabag - website - 3rd visualisation with highlights/notes

### ISSUE THREAD

**Issue by waluwaz** [wallabag/wallabag#4003]
### Issue details
The wallabag website offers two ways to display the list of entries/articles. Highlighted text or notes are NOT displayed among the list of articles.
Suggestion: add a third visualisation mode including the highlighted text or the notes for the listed articles. It could only display e.g. 3 bits of text by default, with the option to expand for each single article.

### Environment

* wallabag version (or git revision) that exhibits the issue: Version: 2.3.8
* Based on wallabag.it
* OS for the web browser: Firefox 67.0.1 on Ubuntu 18.04

### Steps to reproduce/test case
Click Unread to display the list of Unread Entries/Articles. See the option to switch visualization mode. No mode shows highlighted text or notes.

**Comment by nicosomb** [comment]
Hello @waluwaz 

I think your feature is now implemented in wallabag, as you can see in the screenshot: 

![Capture d’écran 2023-08-03 à 17 35 18](https://github.com/wallabag/wallabag/assets/121870/65fd5431-ea09-412e-9076-a6096af612ff)

You can easily access to the articles with annotations. 

I close this issue. If you think I'm wrong, feel free to reopen it.
