### ISSUE TITLE
update issue - composer not installed message (but it's there)

### ISSUE THREAD

**Issue by jkrobin** [wallabag/wallabag#4007]
I have a working installation of Wallabag 2.3.1 on a VPS hosted by Dreamhost that I wish to update to 2.3.8. Following the Upgrading from 2.3.x to 2.3.y instructions at https://doc.wallabag.org/en/admin/upgrade.html, I go to my directory and run 'make update' but get an error returned:

**"composer.phar not found, we'll see if composer is installed globally.
wallabag requires composer but it's not installed (see http://doc.wallabag.org/en/master/user/installation.html). Aborting.
make: *** [update] Error 1"**

Obviously, composer had to be there when I installed 2.3.1 and previous versions, which have been working great for a long time.

Suggestions/help needed and welcome! Thanks.

**Comment by j0k3r** [comment]
You have to install composer on your machine.
https://getcomposer.org/download/

Launch command from the root of wallabag. It'll install the `composer.phar` file in that directory.
Then you can re-launch the update.

We'll have to update the doc about that point.

**Comment by jkrobin** [comment]
Thank you. I got composer.phar installed and then ran make update. 

The update process generated multiple error and warning messages, but appeared to continue through to the end, with the two 'red' error messages both containing references to SQLite (which I am using). There are also several references to items being "already loaded in Unknown on line 0."

See the attached text output of the whole process, as well as a screenshot showing the colored output in the terminal.

After the process, nothing appears to have changed on my live site, and clicking on 'about' at the bottom of the live site still shows the installed version to be 2.3.1.
<img width="1222" alt="Screen Shot 2019-06-12 at 10 59 01 AM" src="https://user-images.githubusercontent.com/33295430/59362409-65910f80-8d01-11e9-8ee0-4a2bd827b971.png">
[full make update output.txt](https://github.com/wallabag/wallabag/files/3281908/full.make.update.output.txt)

**Comment by j0k3r** [comment]
How did you install wallabag in the first place?
Which database are you using? Looks like it's SQLite

**Comment by jkrobin** [comment]
I installed it manually back in the 2.2x series and it has been running great for a long time. Update to 2.3.x series was done following the shared hosting instructions (though, technically, I'm on a VPS at Dreamhost, not normal shared hosting). 

And, yes -- I am using SQLite.

**Comment by j0k3r** [comment]
Okay, so the `make update` only runs fine if you installed wallabag using `git`. If you installed it using the shared hosting way (the tar archive) you have to follow the manual process: https://doc.wallabag.org/en/admin/upgrade.html#upgrade-on-a-shared-hosting

BUT the queries link is dead.

**Comment by jkrobin** [comment]
Thank you, again, for your assistance.

A final question: since this will be a 2.3.x to 2.3.y update, do I still need to do any of the SQL update queries noted in the shared hosting instructions?

**Comment by j0k3r** [comment]
That page isn't up to date as of the 2.3.8 :disappointed: 
We should have a page listing all migrations from one version to an other...

**Comment by j0k3r** [comment]
I replied to fast. As it's a patch update, you're right, you don't need to run queries. Jump need to update the code.

**Comment by jkrobin** [comment]
Thanks very much. I was able to successfully update to 2.3.8, but only after noting that the new files did not include an .htaccess file. Once I put a backup of that file in the directory, my 2.3.8 installation worked just fine. You may want to add that step to the instructions (along with replacing the data directory and the parameters.yml file, as noted in the instructions).

**Comment by j0k3r** [comment]
What `.htaccess` are you talking about?

**Comment by jkrobin** [comment]
I have an .htaccess file in place to force resolution to https version of the URL. With no htaccess file in place the site would not come up, just a directory listing.

**Comment by j0k3r** [comment]
You mean, the `.htaccess` in the `web/` directory?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
