### ISSUE TITLE
couldn't fetch any articles from this site

### ISSUE THREAD

**Issue by toyqiu** [wallabag/wallabag#4012]
### Issue details

couldn't fetch any articles from this site https://zhuanlan.zhihu.com/
like artile https://zhuanlan.zhihu.com/p/67184988
OR https://zhuanlan.zhihu.com/p/31755660
I tried for months 100% failue.

### Environment

* wallabag version (or git revision) that exhibits the issue: Self-hosted docker wallabag 2.3.8
* OS:
* MariaDB

### Steps to reproduce/test case

fetch https://zhuanlan.zhihu.com/p/19856796
![image](https://user-images.githubusercontent.com/479873/59562631-8b9c1400-9061-11e9-9145-4374e60926ee.png)

![image](https://user-images.githubusercontent.com/479873/59562638-98206c80-9061-11e9-9172-033e5b7a44ac.png)

**Comment by j0k3r** [comment]
Fixed https://github.com/fivefilters/ftr-site-config/commit/7c07baced71006f2ad157a238f7be4c4827ad3df

**Comment by toyqiu** [comment]
thank you
and how can I apply this fix to my server?

**Comment by j0k3r** [comment]
Create a file in `vendor/j0k3r/graby-site-config/.zhihu.com.txt` with the content of the previous commit I posted and it should work.

**Comment by toyqiu** [comment]
> Create a file in `vendor/j0k3r/graby-site-config/.zhihu.com.txt` with the content of the previous commit I posted and it should work.

got it done!
THANK YOU very much

**Comment by toyqiu** [comment]
> Create a file in `vendor/j0k3r/graby-site-config/.zhihu.com.txt` with the content of the previous commit I posted and it should work.

after applying the fix I found another bug

before the fix
this was normally well fetched article :
https://www.zhihu.com/question/325437240/answer/714755215

and this always fail :
https://zhuanlan.zhihu.com/p/67184988

after the fix
this was normally well fetched article :
https://zhuanlan.zhihu.com/p/67184988

and this always fail :
https://www.zhihu.com/question/325437240/answer/714755215

**Comment by toyqiu** [comment]
got it done!
There is a default file named zhihu.com.txt witch makes https://www.zhihu.com/question/325437240/answer/714755215 fetched well.

and I created a file in vendor/j0k3r/graby-site-config/zhuanlan.zhihu.com.txt with the content 

`http_header(user-agent): PHP/7.2

test_url: https://zhuanlan.zhihu.com/p/67184988`

then
https://zhuanlan.zhihu.com/p/67184988
and
https://www.zhihu.com/question/325437240/answer/714755215
both fetched!

**Comment by j0k3r** [comment]
Fixed as well: https://github.com/fivefilters/ftr-site-config/commit/9d920b3a4ad988496fa2e4756aa67b6439768e7e
Thanks 👍
