### ISSUE TITLE
Question/Feature Request: Multiuser-Workspace

### ISSUE THREAD

**Issue by demlak** [wallabag/wallabag#4014]
Hi,
i just discovered wallabag,
is it possible to have a shared workspace for multiple users, where every user is only able to edit his/her own bookmarks, but can see the bookmarks of every other (incl. tags) user?
and maybe users can suggest tags for bookmarks of other users.

We would like to have a collaborative bookmarking software with content-caching.

thx for your attention

**Comment by j0k3r** [comment]
There is no nothing like that for now.
But we already have an issue https://github.com/wallabag/wallabag/issues/805 about that point (with some work done months ago https://github.com/wallabag/wallabag/pull/2268).
But nobody is working on that point atm.

I'm closing as duplicate.

**Comment by demlak** [comment]
thx for the hint
