### ISSUE TITLE
nullable reading_time in SQLite

### ISSUE THREAD

**Issue by di72nn** [wallabag/wallabag#4015]
### Issue details

[There is a report](https://github.com/wallabag/android-app/issues/793) of `reading_time` being null in SQLite.
Apparently, it can be reproduced with these articles:
```
http://organic-center.org/uncategorized/newcastle-study-non-technical-summary/?utm_source=The Organic Scoop&utm_campaign=3aa680a698-The_Organic_Scoop_July_20146_30_2014&utm_medium=email&utm_term=0_6c4c22519d-3aa680a698-414554937
http://blog.generalassemb.ly/where-are-they-now-kate-zasada/?utm_source=GA&awesm=ga.co_ta&utm_medium=Twitter&utm_campaign=GA Blog Kate Zasada Student Spotlighta
http://www.gwern.net/Google shutdowns
```
Not sure whether this is a problem for UI, but API returns `null`, which is undesirable.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8 (but the articles might have been fetched with an earlier version)
* How did you install wallabag? Via `git clone` or by downloading the package? *unknown*
* Last wallabag version that did not exhibit the issue (if applicable): *unknown*
* php version: *unknown*
* OS: *unknown*
* type of hosting (shared or dedicated): *unknown*
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): **SQLite**

### Steps to reproduce/test case

Add the articles, check DB.

**Comment by j0k3r** [comment]
Can't reproduce using the master branch.
![image](https://user-images.githubusercontent.com/62333/59754151-d7c79e00-9285-11e9-9bc5-859837a11364.png)

But as you said, data might have been fetched using an earlier version.
I'll create a migration to change the default value of the field in the database and convert previous one too.

**Comment by j0k3r** [comment]
It has been fixed a long time ago https://github.com/wallabag/wallabag/pull/3373
But the migration wasn't done on SQLite :man_shrugging:
