### ISSUE TITLE
Configuration option for not saving content

### ISSUE THREAD

**Issue by mdirik** [wallabag/wallabag#4031]
Hi

I don't use article contents at all, I always open the original page for viewing.
Still Wallabag fetches and stores content for every single item added and AFAIK there is no option to disable that behavior.
Unused data inside content fields makes  the size of API responses and database files many times more larger. I'm aware that the API problem is recently fixed (#2585) but fetching contents still takes time during addition of articles and storing them makes the database 10x larger.

In the meantime I patch my installation with this to avoid bloating the database:

```
--- wbg/src/Wallabag/CoreBundle/Helper/ContentProxy.php.orig    2019-06-02 07:06:18.561680343 -0400
+++ wbg/src/Wallabag/CoreBundle/Helper/ContentProxy.php 2019-06-02 07:11:30.323680053 -0400
@@ -266,7 +266,6 @@
             }
         }

-        $entry->setContent($content['html']);
         $entry->setReadingTime(Utils::getReadingTime($content['html']));

         if (!empty($content['status'])) {
```

but of course that's a hack. 
I would be much happier if a configuration option is provided for disabling fetching & storing of contents.

**Comment by j0k3r** [comment]
wallabag main purpose is to save url and its content so you can read it later. It was never intended to work as a bookmark tool like the one you have on your browser.
Disabling this feature is like removing the ability to view tweets on Twitter but keeps ability to post tweets. Weird.

That's I'm against that feature.
What do you think @wallabag/core?

**Comment by mdirik** [comment]
> Disabling this feature is like removing the ability to view tweets on Twitter but keeps ability to post tweets. Weird.

I don't agree with the analogy. Obviously URLs are still saved and could be opened and viewed any time.

> That's I'm against that feature.

That's okay with me as it's not hard to work around, fortunately.

**Comment by tcitworld** [comment]
@mdirik Have a look at Shaarli instead.

**Comment by Kdecherf** [comment]
This issue had no update in the past three years, closing it
