### ISSUE TITLE
couldn't get title from this site mp.weixin.com

### ISSUE THREAD

**Issue by toyqiu** [wallabag/wallabag#4032]
### Issue details

fetching contents from this site https://mp.weixin.qq.com/  works well
but couldn't get the tilte
like artile https://mp.weixin.qq.com/s/dL3XjH3a5bU4S4wUfpx6yg
OR https://mp.weixin.qq.com/s/fWG6zQ9z_LWYyYjlo5HLBw

![image](https://user-images.githubusercontent.com/479873/60267127-18758600-991c-11e9-93d1-dd82e7bd626a.png)

I tried writing a graby-site-config 

> http_header(user-agent): Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/53
> 
> title: //h2[@class="h s-2"]
> convert_double_br_tags: yes
> 
> test_url: https://mp.weixin.qq.com/s/TVA6Zlc8yONVSe4Mwxt1Zw

it does not work.

### Environment

* wallabag version (or git revision) that exhibits the issue: Self-hosted docker wallabag 2.3.8
* OS:
* MariaDB

**Comment by j0k3r** [comment]
I succeeded using that expression for title: `title: //h2[@class="rich_media_title"]`

**Comment by toyqiu** [comment]
> I succeeded using that expression for title: `title: //h2[@class="rich_media_title"]`

it works!
Thank you very much!
