### ISSUE TITLE
Version number is still 2.3.6 after upgrading to 2.3.8

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#4035]
### Issue details
I am hosting this on my own server. I used the zip releases to install and upgrade so I used 2.3.8 - 2019-05-14 for uograde.  I copied the files from the zip file to serve's wallabag folder. ThenI copied the config folder and the assets folders onto the unzipped folder.

The upgrade seems to work no problem, except that I see that the release is 2.3.6 instead of 2.3.8 in `URL/wallabag/about`  page.  However it says it is 2.3.8 in `CHANGELOG.md`

### Environment
Debian Buster, Apache/2.4.38 (Debian), mariadb  Ver 15.1 Distrib 10.3.15-MariaDB,

thanks

**Comment by j0k3r** [comment]
Can you dump the content of the file `app/config/wallabag.yml`?

**Comment by gerroon** [comment]
That was it thanks
