### ISSUE TITLE
Formatting is off

### ISSUE THREAD

**Issue by sgzmd** [wallabag/wallabag#4041]
### Issue details

When reading [this medium article](https://medium.com/@justsitthere/team-health-morale-checks-ed534816e53) the formatting gets off quite a bit: each consecutive section is getting more and more nested (see PDF attached).

### Environment

* wallabag version (or git revision) that exhibits the issue:  2.3.8
* How did you install wallabag? -- via `git clone` 
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
* OS: Ubuntu 18.04.2 LTS
* type of hosting (shared or dedicated): personal machine, running in ESXi
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

wallabag [this article](https://medium.com/@justsitthere/team-health-morale-checks-ed534816e53) and scroll it down.
[Team Health and Wellbeing — A Leading Indicator of Just About Everything (medium.com) – wallabag.pdf](https://github.com/wallabag/wallabag/files/3353887/Team.Health.and.Wellbeing.A.Leading.Indicator.of.Just.About.Everything.medium.com.wallabag.pdf)

**Comment by Kdecherf** [comment]
This issue is due to a missing post-processing feature in Graby, fix is planned.

**Comment by Kdecherf** [comment]
Closing this in favor of #3134
