### ISSUE TITLE
Installation on windows 10

### ISSUE THREAD

**Issue by ParikhKadam** [wallabag/wallabag#4048]
Can't find a proper guide to install wallabag on windows.. Need help.

**Comment by j0k3r** [comment]
Everything is here: https://doc.wallabag.org/en/admin/installation/readme.html
There is no special case for windows 10.
You need to have a running web server, PHP & a database.

**Comment by ParikhKadam** [comment]
No.. that doesn't work. Windows doesn't have the `make` tool. Thought I installed one but it's throwing errors like file not found even though the file is in that directory.

```D:\wallabag>make install
process_begin: CreateProcess(NULL, env bash D:\wallabag\scripts\install.sh prod, ...) failed.                           make (e=2): The system cannot find the file specified.
make: *** [install] Error 2 ```

help pls..

**Comment by sirkojac** [comment]
I know this is old but I thought I'd post to help anyone else running on Windows. You install Docker for Windows (or Rancher) then use the wallabag container https://hub.docker.com/r/wallabag/wallabag

**Comment by noobyme** [comment]
If my understandjng is correct, the makefile points to the gnumakefile, which is for bash. windows doesnt have bash
