### ISSUE TITLE
Allow Custom Syles (site wide)

### ISSUE THREAD

**Issue by BrookeDot** [wallabag/wallabag#4060]
### Issue details
Related to #1521 and #1278 it would be great to be able to add a custom stylesheet to override the default styles. For example, store `custom.css` outside of the core folder then have it loaded within wallabag. In my case I like the Material theme but want to make a few customizations such as changing the logo, a few colors, etc.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.3.7
* OS: Debian 10
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB 10.14.6

**Comment by j0k3r** [comment]
Can't you use an extension like https://userstyles.org/ so you can apply whatever css you want on whatever website you want.

**Comment by BrookeDot** [comment]
> Can't you use an extension like https://userstyles.org/ so you can apply whatever css you want on whatever website you want.

That would work per device, and is a solution I've used in the past. However, I'm looking for a global solution which would allow custom styles for all users (including logged out visitors). I currently use several computers and browsers throughout the day so not having to install an extension or style per device.

**Comment by BoyMechanicus** [comment]
Why not edit the css file for the theme and replace the logo img files? Since you're self hosting that would seem the fitting solution

**Comment by BrookeDot** [comment]
> Why not edit the css file for the theme and replace the logo img files

The main goal is to not have to modify or replace any core files, thus making future upgrades trivial. Of course with any self-hosted solution it's possible to modify theme files but I believe that providing a simple method to customize styles without needing to change bundled code is more beneficial long term.  

I also am aware of that forking a theme is possible but again I'm worried about forward compatibility.

**Comment by BoyMechanicus** [comment]
It's maybe five changes to a css file, and replacing some images if you don't want to edit the logo names. I've made a dark theme, imo copying the theme you want to use and editing the css of the copy is the way to go in terms of forward compatibility.

**Comment by BrookeDot** [comment]
> imo copying the theme you want to use and editing the css of the copy is the way to go in terms of forward compatibility.

That's fair, it's clear that we have a difference of opinion when it comes to providing a way for the end user to make these type of changes. In my experience, the addition of a theme setting, custom CSS flle, or hook/filter (ie, variable) are all common approaches. 

I'm open to  other solutions instead of a custom CSS file but not convinced that a custom theme is the best method.

**Comment by BoyMechanicus** [comment]
If you do indeed want to use an external css file, why not put `@import url("name_of_external.css");` in the css files of the themes you intend on using on your instance? It's one file per theme. And all you have to do is paste that line in the file and then you're good to go. No need to worry about breaking anything and you can always compare the css files of updates with a diff check.
