### ISSUE TITLE
latest docker image corrupt?

### ISSUE THREAD

**Issue by Daniel451** [wallabag/wallabag#4061]
I have run...
```
docker run -p 80:80 wallabag/wallabag
```
...on two different hosts + a RaspberryPi and on every device `http://localhost` returns a plain HTML website. No images, no CSS, nothing.

Running an older docker image (i.e., for example, 2.2.3) works without any problems. HTML, CSS, JS, ... runs as expected:
```
docker run -p 80:80 wallabag/wallabag:2.2.3
```

Is this behavior intended? Are additional steps required to setup the latest docker image?

**Comment by Wizkidje** [comment]
You need to append `-e SYMFONY__ENV__DOMAIN_NAME=http://localhost` to your docker run command. You can get more information regarding this variable and others from the README.md that sits in the Git repository.

I agree that the documentation should be updated to reflect this, I ran into the same issue when I first set it up yesterday.

**Comment by j0k3r** [comment]
@Wizkidje every contribution is welcome :)

**Comment by Wizkidje** [comment]
> 
> 
> @Wizkidje every contribution is welcome :)

Touché 😉. I'll see what I can do.

**Comment by Kdecherf** [comment]
This issue had no update in the past three years, closing it
