### ISSUE TITLE
fetching content from tz.de does not work

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#4064]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Content fetching for tz.de does not work.
e.g.: https://www.tz.de/reise/in-italien-drohen-streiks-bei-bahn-fliegern-und-schiffen-zr-12847211.html

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

add https://www.tz.de/reise/in-italien-drohen-streiks-bei-bahn-fliegern-und-schiffen-zr-12847211.html and see article content is missing

**Comment by j0k3r** [comment]
https://github.com/fivefilters/ftr-site-config/commit/70b24b5ce202b9e7a1253dbab7da53d576ee6f77
