### ISSUE TITLE
Wrong content is fetched for bosch-presse.de

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#4065]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Wrong content is fetched for bosch-presse.de

e.g.
https://www.bosch-presse.de/pressportal/de/de/bosch-system-schiebt-digitalem-autoklau-einen-riegel-vor-179142.html

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

add https://www.bosch-presse.de/pressportal/de/de/bosch-system-schiebt-digitalem-autoklau-einen-riegel-vor-179142.html and see only the content hidden in the "Basisinformation" is fetched, but not the article itself

**Comment by j0k3r** [comment]
https://github.com/fivefilters/ftr-site-config/commit/5d7a19c3e9dbf24e07eb3e2fb8550cafe48d8610
