### ISSUE TITLE
fetching gameswirtschaft.de does not work

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#4066]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Fetch error for gameswirtschaft.de
e.g.:
https://www.gameswirtschaft.de/wirtschaft/goodgame-studios-gruender-geschaeftsfuehrung/

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

add https://www.gameswirtschaft.de/wirtschaft/goodgame-studios-gruender-geschaeftsfuehrung/ and see that the article content is not fetched

**Comment by j0k3r** [comment]
Maybe next time try to fix them on your own first 😉
https://github.com/fivefilters/ftr-site-config/commit/eb69b478d940e824a91e106f216639ea1925e401

**Comment by Strubbl** [comment]
Thanks for fixing! Yes, of course. i just did not want to forget about these sites. If i am back at my dev machine, i could have fixed them.
