### ISSUE TITLE
Preserve created_at date during import

### ISSUE THREAD

**Issue by grindsa** [wallabag/wallabag#4073]
### Issue details

I am trying to migrate a larger v1 data-set to v2.3.8. Export and import by using json files run fine after some initial hiccups.

What I noticed is that all imported articles get the import date and time i the created_at field of the database which messes up the data. 
```
MariaDB [wallabag]> select created_at, updated_at from wallabag_entry limit 10;
+---------------------+---------------------+
| created_at          | updated_at          |
+---------------------+---------------------+
| 2019-07-28 10:05:54 | 2019-07-28 10:05:54 |
| 2019-07-28 10:05:54 | 2019-07-28 10:05:54 |
| 2019-07-28 10:05:54 | 2019-07-28 10:05:54 |
| 2019-07-28 10:05:54 | 2019-07-28 10:05:54 |
| 2019-07-28 10:05:54 | 2019-07-28 10:05:54 |
| 2019-07-28 10:05:54 | 2019-07-28 10:05:54 |
| 2019-07-28 10:05:54 | 2019-07-28 10:05:54 |
| 2019-07-28 10:05:54 | 2019-07-28 10:05:54 |
| 2019-07-28 10:05:54 | 2019-07-28 10:05:54 |
| 2019-07-28 10:05:54 | 2019-07-28 10:05:54 |
+---------------------+---------------------+
10 rows in set (0.00 sec)
```

Is there any chance to add the created_at date from the json file into the database? I am a bid confused as [#2275](https://github.com/wallabag/wallabag/pull/2275) indicates that it should work since 2.1.

Issue occurs regardless of the import way (UI or CLI) 

### Environment

* wallabag version: 2.3.8
* How did you install wallabag?  `git clone` 
* php version: 7.2
* OS: Ubuntu 18.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install: MySQL

### Steps to reproduce/test case

Export a data-set from v1, import it to v2. I can provide a json-file if required.

Thanks you for your help and have a nice day.

BR GrindSA

**Comment by j0k3r** [comment]
Sadly the v1 table for entries doesn't have a date: https://github.com/wallabag/wallabag/blob/1.x/install/mysql.sql#L8

So we can't retrieve them when importing in v2 nor exporting in v1.
