### ISSUE TITLE
Slow query retrieving starred entries

### ISSUE THREAD

**Issue by shtrom** [wallabag/wallabag#4079]
### Issue details

I'm seeing this query in my slow query log:

```
SELECT DISTINCT w0_.id AS id_0, w0_.starred_at AS starred_at_1 FROM `wallabag_entry` w0_ WHERE w0_.user_id = 1 AND w0_.is_starred = 1 ORDER BY w0_.starred_at DESC LIMIT 10
```

This seems to be due to a `filesort` that I suspect is caused by the `ORDER BY`

```
mariadb root@localhost:wallabag> explain SELECT DISTINCT w0_.id AS id_0, w0_.starred_at AS starred_at_1 FROM `wallabag_entry` w0_ WHERE w0_.user_id = 1 AND w0_.is_starred = 1 ORDER BY w0_.starred_at DESC LIMIT 10\G
***************************[ 1. row ]***************************
id            | 1
select_type   | SIMPLE
table         | w0_
type          | ref
possible_keys | IDX_F4D18282A76ED395,IDX_entry_starred,hashed_url_user_id
key           | IDX_entry_starred
key_len       | 1
ref           | const
rows          | 248
Extra         | Using where; Using filesort
1 row in set
Time: 0.480s
```

Adding an index makes things much better.

```
alter table wallabag_entry add index idx_user_starred_at  (user_id, is_starred, starred_at)
```

No more `filesort`:

```
mariadb root@localhost:wallabag> explain SELECT DISTINCT w0_.id AS id_0, w0_.starred_at AS starred_at_1 FROM `wallabag_entry` w0_ WHERE w0_.user_id = 1 AND w0_.is_starred = 1 ORDER BY w0_.starred_at DESC LIMIT 10\G
***************************[ 1. row ]***************************
id            | 1
select_type   | SIMPLE
table         | w0_
type          | ref
possible_keys | IDX_F4D18282A76ED395,IDX_entry_starred,hashed_url_user_id,idx_user_starred_at
key           | idx_user_starred_at
key_len       | 6
ref           | const,const
rows          | 247
Extra         | Using where; Using index
1 row in set
Time: 0.090s
```

I think this index could replace the `IDX_entry_starred` that is currently there. However, the `user_id` may need to be moved to the end if there are queries that look for starred articles across users.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Manually packaged from the tag
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: PHP 7.3.4
* OS: OpenBSD
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
> if there are queries that look for starred articles across users.

I don't think we have such query for the moment.
Same as the other, could you create a PR?

Thanks for taking care of these slow queries 🙏
