### ISSUE TITLE
Possibility of collaboration between wallabag and Nextcloud

### ISSUE THREAD

**Issue by jancborchardt** [wallabag/wallabag#408]
@nicosomb, @jogaulupeau, we from [Nextcloud](https:/nextcloud.com) (http://github.com/nextcloud) are preparing to enter Google Summer of Code this year. Among the ideas is a read-it-later/Pocket/Readability app: https://github.com/owncloud/core/wiki/GSoC,-GCI-and-OPW#read-later-app-similar-to-pocket--instapaper--readability

There I wrote that it might be best for Nextcloud to work on an own solution, but screw that. I think collaboration is very important here, especially in this field where there is a lack of open source solutions while the data you give away (a lot of stuff you’re interested in) is very personal and sensitive.

So how could we collaborate? (Edited after discussion)
1. Poche is working to separate their app into a server which exposes an API and a fully JS client app which could be offline-capable for use as Firefox OS app for instance.
2. Poche also has an Android app and browser extensions working on that same API. **Now we should discuss together to decide how the API should look like.**
3. For Nextcloud, we will also implement a server which works with this API, hence we could make use of the existing Android app, browser extensions and Firefox OS app.
4. We can also have a front-end for the Read-later items inside Nextcloud. Probably best to combine it with the Bookmarks app.

I think the more important point is that we can share the extensions and app ecosystem, since that requires most work and polish especially when it comes to the little details (hence the bunch of design enhancement issues I filed ;)

cc @cosenal (GSoC coordinator for Nextcloud, wants a Pocket alternative as well ;)

**Comment by nicosomb** [comment]
Hello @jancborchardt! 

We are not dead. 

You can read my post on diaspora* here: https://framasphere.org/posts/367022

And collaboration between owncloud & wallabag will be possible!

**Comment by nicosomb** [comment]
Hello @jancborchardt! Is a collaboration between owncloud and wallabag still possible?

**Comment by jancborchardt** [comment]
@nicosomb of course! :) Not a lot has happened on our end. @blizzz for example has taken up developement of the [Bookmarks app](https://github.com/owncloud/bookmarks) again, so it might make most sense to use that for our part.

Come join our IRC channel #owncloud-dev so we can discuss, or let us know how we can proceed. :)

**Comment by torstenfroehling** [comment]
@jancborchardt As a user of both programs I would say that it would be very nice wallabag integrate into ownCloud. For me and my users it would be another criterion for the use of these two programs.

**Comment by menelic** [comment]
@nicosomb @jancborchardt Are you aware of this new owncloud app that promises wallabag installation? https://apps.owncloud.com/content/show.php/Wallabag?content=170869 Too bad there is no description, but maybe you can have a look and create synergies between that app and your efforts? as @torstenfroehling said, integration of the two would be great...

**Comment by jtojnar** [comment]
@menelic the app is just Wallabag, the download link leads to http://wllbg.org/latest.

**Comment by jalcine** [comment]
That app should be removed; it's misleading.

**Comment by nicosomb** [comment]
You're right, it should me removed. Just to be clear, it's not our team who published this app on owncloud store.

**Comment by jancborchardt** [comment]
Thanks for the note, deleted it.

Any collaboration/sync should be with the Bookmarks app: https://github.com/owncloud/bookmarks – that's the most related and actovely developed one.

We don't have a specific read later app, but it would make most sense to add that to Bookmarks. cc @blizzz

**Comment by 1337sup3rh4x0r** [comment]
Maybe this would better be integrated with the owncloud news app, so that read later items could be added to the starred articles collection? Thats basically where I store my read later items from the news feeds already.

**Comment by nicosomb** [comment]
@jancborchardt still interested for @nextcloud?

**Comment by jancborchardt** [comment]
@nicosomb yes, very much! : ) What would be a good integration from your side?

Since Wallabag is PHP as well, maybe it makes sense to have a Nextcloud app which is a frontend in Nextcloud-Style for Wallabag. This could then connect either to a Wallabag instance or even save the stuff in Nextcloud according to Wallabag APIs, so that Wallabag clients can connect to it.

What do you think?

**Comment by jancborchardt** [comment]
Also cc @schiessle @MorrisJobke @LukasReschke for doability discussions. :)

**Comment by tcitworld** [comment]
I also think the best thing is just a frontend for wallabag. We also want our UI to relay only on our API in the long term. wallabag is installable with docker, so it would be just like collabora online for instance.

**Comment by DeepDiver1975** [comment]
FYI: the owncloud universe is also still interested in a wallabag integration - collaborative development is welcome

**Comment by jancborchardt** [comment]
@nicosomb @tcitworld cool, so how do we proceed here? :) A frontend would be quite easy to write probably, cc also @BernhardPosselt who wrote the ncdev tool: https://docs.nextcloud.com/server/9.0/developer_manual/app/tutorial.html

It’s probably best to model it after your existing interface first, or taking that pretty much verbatim and then using the relevant HTML structure / classes to achieve the normal Nextcloud layout & styling for free: https://docs.nextcloud.com/server/9/developer_manual/app/css.html#standard-layout :)

**Comment by AndyScherzinger** [comment]
https://github.com/nextcloud/android/pull/253 has the complete implementation for prefilling via URLs. 

Nextcloud would be happy to provide the Android part, see wallabag Android app issue :)  If you want us to.

**Comment by AndyScherzinger** [comment]
The Android part has been merged https://github.com/wallabag/android-app/pull/300 :tada: 
Nextcloud is always happy to help :gift_heart: Looking forward to further collaboration :rocket: 

![giphy](https://cloud.githubusercontent.com/assets/1315170/18742711/fed1665a-80b5-11e6-9fe4-a9e0a0c1e568.gif)

**Comment by tcitworld** [comment]
We have an Angular-based web client that should arrive here soon. From there I guess *cloud integration should be feasible.

**Comment by nicosomb** [comment]
You have information that I don't have 😁

**Comment by AngelBCN** [comment]
More and more applications work on nextcloud. Would it be possible now to be wallabag as an application within nextcloud?

**Comment by AngelBCN** [comment]
More and more applications work on nextcloud. Would it be possible now to be wallabag as an application within nextcloud?

**Comment by jones4410** [comment]
+1 for Wallabag integration into nextcloud / owncloud

**Comment by nico202** [comment]
Any news?

**Comment by tcitworld** [comment]
Nope.

**Comment by bepolymathe** [comment]
+ 1

**Comment by jtojnar** [comment]
Please use GitHub’s thumbs up function. Nobody is interested in you being interested, unless your interest actually includes an implementation.

**Comment by marcelklehr** [comment]
Hey everyone :)
I'm kind of late to the party, but I'll add my two cents anyway :)
I've been working on revamping the bookmarks app in nextcloud for some time. And we have of course been considering adding read-it-later functionality.
I don't see the benefit in making people install wallabag in addition to nextcloud while having a separate frontend for it in nextcloud, as long as there's no integration with nextcloud. Collabora for example integrates with nextcloud by allowing you to edit files. A wallabag nextcloud app would simply be a passthrough facade with no benefit, no?
I think the original idea of sharing a common API would be more beneficial, so as to establish a kind of standard that grows an ecosystem around it (see php-fig, etc.).
On the nextcloud side read-it-later functionality in nextcloud would fit into either the news app or the bookmarks app. I'm personally not particular about where it should be added. From a UX perspective, the concepts of the news app seem to be closer to read-it-later, as it already allows reading articles, and has collections of them. On the other hand, at its core, it's a feed reader, which fetches feeds of articles regularly and makes them available, whereas read-it-later would be on-demand fetching of arbitrary articles and assembling them in a separate collection, possibly with the need to search and organize them. This is closer to the usage concepts of the bookmarks app.

Here's an idea: We could add the wallabag API to the bookmarks app for adding and managing the pages/articles, but also add feeds for bookmark tags, which then can be integrated into the news app. How does that sound?

**Comment by silverhook** [comment]
> Here's an idea: We could add the wallabag API to the bookmarks app for adding and managing the pages/articles, but also add feeds for bookmark tags, which then can be integrated into the news app. 

If the API would work in both directions – so changing a Nc bookmark would also change the Wallabag article (and vice versa) – that could make sense.

**Comment by jancborchardt** [comment]
@marcelklehr that sounds good! So basically you could then use the Wallabag mobile apps to connect to your Nextcloud and have the content from the Bookmarks app available offline.

For Nextcloud News, there are already Android and iOS apps, so there integration is less needed. Bookmarks seems good since it's a more similar format to Wallabag. :)

@nicosomb @tcitworld what do you think?

**Comment by violoncelloch** [comment]
An other possible solution I thought of could be to just make wallabag installable as a nextcloud app (like it's done with rainloop)...
the advantage would be that we can just use wallabag as it is (with all options and hopefully mobile apps too) on top of nextcloud in an easy way to install...
the downside is that possibly serving the wallabag on top of nextcloud could be difficult and wallabag wouldn't fit into the design sheme of nextcloud either

So maybe just sharing the api and building and or copying wallabag features in a standalone nextcloud app is easier

**Comment by jancborchardt** [comment]
@violoncelloch which is exactly why @marcelklehr suggested the integration. ;)

**Comment by Shadesss** [comment]
Would love this.

**Comment by 1337sup3rh4x0r** [comment]
Another thing to keep in mind, at least for my workflow, is the "Starred" section of nextcloud News. It would be great if "starring" an article would send it to wallabag/bookmarks/that-combined-api, or if news integraded an additional button for that.

It should however be ensured that we don't go in circles, when you subscribe to the bookmarks feed and star an item form it ;)

**Comment by sunjam** [comment]
Bounty has been added for Wallabag support in Nextcloud Bookmarks app.  [Please consider putting some money on the bounty here](https://www.bountysource.com/issues/60958412-wallabag-integration) to encourage devs.

**Comment by nicosomb** [comment]
There is no more discussion about this possibility of collaboration. I close this issue.

**Comment by menelic** [comment]
this would still be a great integration, with omnivore having closed and wallabag offering omnivore import, this would be a great time to finally get Nextcloud users a full read it later solution

**Comment by ChimeraFire** [comment]
And Pocket gone now too... This is needed.
