### ISSUE TITLE
Slow query rendering the front page

### ISSUE THREAD

**Issue by shtrom** [wallabag/wallabag#4080]
### Issue details

I'm seeing this in my slow query log when rendering the front page, and this seems to be leading to timeouts.

```
SELECT w0_.language AS language_0 FROM `wallabag_entry` w0_ WHERE w0_.user_id = 1 AND w0_.language IS NOT NULL GROUP BY w0_.language ORDER BY w0_.language ASC;
```

This query is using both temporary storage and a filesort

```
mariadb root@localhost:wallabag> explain SELECT w0_.language AS language_0 FROM `wallabag_entry` w0_ WHERE w0_.user_id = 1 AND w0_.language IS NOT NULL GROUP BY w0_.language ORDER BY w0_.language ASC\G
***************************[ 1. row ]***************************
id            | 1
select_type   | SIMPLE
table         | w0_
type          | ref
possible_keys | IDX_F4D18282A76ED395,hashed_url_user_id
key           | hashed_url_user_id
key_len       | 5
ref           | const
rows          | 2140
Extra         | Using where; Using temporary; Using filesort
1 row in set
Time: 0.071s
```

(the `hashed_url_user_id` index is from me manually fixing #3919 for the time being)

It is not possible to add an index on the `language` column as it is a `longtext` (I am not sure this actually makes sense...)

```
mariadb root@localhost:wallabag> alter table wallabag_entry add index idx_user_language  (user_id, language)
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
(1170, u"BLOB/TEXT column 'language' used in key specification without a key length")
```

However, removing the `ORDER BY` (which can probably be done easily on the PHP side, once the data has been filtered), and replacing the `GROUP BY` by a `DISTINCT` allows to get rid of the `filesort`

```
mariadb root@localhost:wallabag> explain SELECT distinct w0_.language AS language_0 FROM `wallabag_entry` w0_ WHERE w0_.user_id = 1 AND w0_.language IS NOT NULL  \G
***************************[ 1. row ]***************************
id            | 1
select_type   | SIMPLE
table         | w0_
type          | ref
possible_keys | IDX_F4D18282A76ED395,hashed_url_user_id,idx_user_starred_at
key           | hashed_url_user_id
key_len       | 5
ref           | const
rows          | 2140
Extra         | Using where; Using temporary
1 row in set
Time: 0.125s
```

This is a slight improvement, but it does seem like changing the type of the `language` column and adding an index on it would be better. Particularly as it only seems to store locale names, a `longtext` seems overkill where, say,  a `varchar(10)` would already be plenty.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Manually packaged from the tag
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: PHP 7.3.4
* OS: OpenBSD
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
> a varchar(10) would already be plenty.

I think that's a good idea. We really don't need a `longtext` here.
Would you mind creating the PR with:
- the migration file to change the type of the field and create the index
- the updated field in `Entry` model

Thanks :)
