### ISSUE TITLE
 Is there a way to filter by multiple tags?

### ISSUE THREAD

**Issue by PedroSturmer** [wallabag/wallabag#4085]
Hi!
I have just started using Wallabag and it's been great so far.
But one of the main features I was looking for is a way to filter items by multiple tags.

I found and older issue about this at: https://github.com/wallabag/wallabag/issues/1197

But I am not sure if this feature was already released or not.
Can anyone give me and update on this?

Thanks in advance!

**Comment by j0k3r** [comment]
Nope the feature wasn't implemented yet. That's why the other issue you found is still open.

Duplicate of #1197
