### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by ivndnkn** [wallabag/wallabag#4086]
Hello!
Wallabag.org and wallabag.it seems to be unreacheble from Russian IPs. Is this supposed to be so?
Thank you.

**Comment by Kdecherf** [comment]
Hello @ivndnkn,

Could you provide the output of a `traceroute`, `tracert`, `tracepath` or `mtr` command to `wallabag.org` please?

**Comment by ivndnkn** [comment]
`
  1    <1 мс    <1 мс    <1 мс  192.168.0.1
  2     1 ms    <1 мс    <1 мс  192.168.100.1
  3     3 ms     2 ms     2 ms  ip.178-69-32-1.avangarddsl.ru [178.69.32.1]
  4     4 ms     5 ms     4 ms  87.226.183.55
  5    54 ms    53 ms    53 ms  217.161.68.34
  6    43 ms     *        *     217.161.68.33
  7    46 ms    46 ms     *     lag-120.ear2.Frankfurt1.Level3.net [4.68.70.37]
  8    62 ms    62 ms    62 ms  ae-2-3203.ear3.Paris1.Level3.net [4.69.161.126]
  9    63 ms    63 ms    63 ms  212.3.235.198
 10    56 ms    55 ms    55 ms  195.154.2.112
 11    55 ms    55 ms    56 ms  195.154.2.117
 12    65 ms    64 ms    65 ms  195-154-29-18.rev.poneytelecom.eu [195.154.29.18]`

**Comment by ivndnkn** [comment]
@Kdecherf 

  1    <1 мс    <1 мс    <1 мс  192.168.0.1
  2     1 ms    <1 мс    <1 мс  192.168.100.1
  3     3 ms     2 ms     2 ms  ip.178-69-32-1.avangarddsl.ru [178.69.32.1]
  4     4 ms     5 ms     4 ms  87.226.183.55
  5    54 ms    53 ms    53 ms  217.161.68.34
  6    43 ms     *        *     217.161.68.33
  7    46 ms    46 ms     *     lag-120.ear2.Frankfurt1.Level3.net [4.68.70.37]
  8    62 ms    62 ms    62 ms  ae-2-3203.ear3.Paris1.Level3.net [4.69.161.126]
  9    63 ms    63 ms    63 ms  212.3.235.198
 10    56 ms    55 ms    55 ms  195.154.2.112
 11    55 ms    55 ms    56 ms  195.154.2.117
 12    65 ms    64 ms    65 ms  195-154-29-18.rev.poneytelecom.eu [195.154.29.18]195.154.29.18]

**Comment by nicosomb** [comment]
Hello @ivndnkn. Is that still blocked?
