### ISSUE TITLE
Error migrating database when updating from 2.3.3 to 2.3.8

### ISSUE THREAD

**Issue by kahnwong** [wallabag/wallabag#4106]
### Issue details
I'm migrating from 2.3.3 (archive) to the latest version from git, during db migration I get a few errors during migration `20190510141130`:

```
An exception occurred while executing 'ALTER TABLE `wallabag_oauth2_access_tokens`
   DROP FOREIGN KEY FK_368A4209A76ED395':

  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'FK_368A4209A76
  ED395'; check that column/key exists
```
Note: `Migrating up to 20190808124957 from 20190425115043`

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? git clone (as of 2019-08-28)
* Last wallabag version that did not exhibit the issue (if applicable): 2.3.3
* php version: 7.3
* OS: debian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mariadb

### Steps to reproduce/test case
Install Wallabag 2.3.3 from archive, then clone the repo for the latest version, make install and execute database migration.

note: I need to use wallabag so I decided to do a fresh install.

**Comment by j0k3r** [comment]
Did you still have access to the previous database?
If yes, could you run `SHOW INDEX FROM wallabag_oauth2_access_tokens`?

**Comment by kahnwong** [comment]
I don't exactly but  I have an [SQL dump](https://www.dropbox.com/s/feyekzbiyznrjfb/wallabag.sql.zip?dl=0) before I do a fresh install (as in I already executed migration command). Sorry couldn't be more helpful.
