### ISSUE TITLE
Empty website after a fresh installation

### ISSUE THREAD

**Issue by timaschew** [wallabag/wallabag#4113]
### Issue details

First I had lot of errors due a wrong value for `open_basedir`. After changing `open_basedir` I've got a database error. I found out that I need to run this command: `php bin/console wallabag:install --env=prod` even if that is **NOT** documented in the installation on shared hosting. During that setup I was asked to create an admin and when I was asked to set a password I saw this error:

```
 Password [wallabag]:
 > bash: stty: command not found
xxxx
bash: stty: command not found
```
The wizzard continued and asked me for my email. So I was assuming the bash error can be ignored. The setup was also finished with this output:

```
 Config successfully setup.
 [OK] Wallabag has been successfully installed.
 [OK] You can now configure your web server, see https://doc.wallabag.org
```
But the `wallabag_user`table in the database is empty!
I tried to open the website but I got an error that a twig file could not be loaded even if does exist in the path. I tried to change the `open_basedir` again but I've got the old errors. So I switched again and then the errors gone, but both pages: /login/ and /register/ show me an empty page. Curl is also showing an empty result.

I've tried to create a user via the CLI but I get this error, also for other commans like list users.

```
php bin/console fos:user:create

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in /wallabag.my-domain.com/2.3.8/app/AppKernel.php:49
Stack trace:
#0 /wallabag.my-domain.com/2.3.8/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(448): AppKernel->registerBundles()
#1 /wallabag.my-domain.com/2.3.8/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /wallabag.my-domain.com/2.3.8/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(60): Symfony\Component\HttpKernel\Kernel->boot()
#3 /wallabag.my-domain.com/2.3.8/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /wallabag.my-domain.com/2.3.8/bin/console(29): Symfony in /wallabag.my-domain.com/2.3.8/app/AppKernel.php on line 49
```

### Environment

* wallabag version: 2.3.8 
* How did you install wallabag? downloading the package via wget
* php version: 7.2.19 (cli: 7.3.9)
* OS: Linux a2e0d 4.9.0-0.bpo.9-amd64 #1 SMP Debian 4.9.168-1~deb8u1 (2019-04-28) x86_64 GNU/Linux
* type of hosting: shared
* which storage system you choose at install: MySQL

### Steps to reproduce/test case
On a shared webhosting (https://www.netcup.de/)
- `wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package`

**Comment by j0k3r** [comment]
Try `php bin/console fos:user:create --env=prod`

**Comment by timaschew** [comment]
Okay, the `--prod` works and I see also both users, the admin account and the normal user.

But the the website is still an empty page.

**Comment by timaschew** [comment]
Ended up using Shaarli.
