### ISSUE TITLE
"Search engine" and "new link" forms are broken

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#4130]
### Issue details

See this screenshot (firefox or chrome, macos) : 

<img width="1445" alt="Capture d’écran 2019-09-27 à 16 38 50" src="https://user-images.githubusercontent.com/121870/65778093-89a81d80-e145-11e9-9824-7e4976f2e7db.png">

We have too many icons 😉 

### Environment

* wallabag version (or git revision) that exhibits the issue: master
* How did you install wallabag? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.2
* OS: macos
* type of hosting (shared or dedicated): localhost
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

**Comment by bmillemathias** [comment]
perhaps an hacktober tag would be nice (https://hacktoberfest.digitalocean.com/)

**Comment by ldidry** [comment]
J’peux prendre et m’en occuper ce soir (ça tombe bien, j’ai besoin de faire des PR pour le hacktoberfest :grin: )

**Comment by j0k3r** [comment]
@ldidry si tu t'ennuies ensuite https://github.com/wallabag/wallabag/issues/3804 :)

**Comment by nicosomb** [comment]
Thank you @ldidry 😘
