### ISSUE TITLE
Feature Request: Disable RSS Feed

### ISSUE THREAD

**Issue by DeWir3** [wallabag/wallabag#4132]
I enabled the RSS-feed to try it out by generating a token in my wallabag instance (selfhosted with yunohost). I didn't like that it is available to anyone who has the link without any password protection, so I wanted to disable it again. But there doesn't seem to be any option to do that. I think that would be a useful feature.

**Comment by j0k3r** [comment]
This will be available in the 2.4.0 https://github.com/wallabag/wallabag/issues/3643
In the mean time, you can just re-generate the token and all previous link (with the old token) will be unavailable.
