### ISSUE TITLE
createdAt filters do not get passed

### ISSUE THREAD

**Issue by hennevogel** [wallabag/wallabag#4133]
### Issue details

Going to the filter UI, selecting some values for ` Creation date` and hitting submit doesn't result in any `createdAt` filters in the request.

In general this seems to work, manually adding `entry_filter[createdAt][left_date]=28/09/2019` and `entry_filter[createdAt][right_date]=29/09/2019` shows me the links I'm looking for. They also show up in the UI, a subsequent click on `Filter` again omits them from the request.

### Environment

https://app.wallabag.it from today

**Comment by nicosomb** [comment]
The bug is that the 2 fields have no name (the attribute is empty): 

```
<input type="text" id="entry_filter_createdAt_left_date" name="" placeholder="dd/mm/yyyy" class="datepicker picker__input" data-value="28/09/2019" value="28/09/2019" readonly="" tabindex="-1" aria-haspopup="true" aria-expanded="false" aria-readonly="false" aria-owns="entry_filter_createdAt_left_date_root">
```

These fields are `DateRangeFilterType::class` fields.

**Comment by nicosomb** [comment]
🤔  in the DOM, we have the name, see below: 

```
<input type="date" id="entry_filter_createdAt_left_date" name="entry_filter[createdAt][left_date]" placeholder="dd/mm/yyyy" class="datepicker" data-value="" />
```

My previous post give the result with the inspect tool of my browser.
