### ISSUE TITLE
Missing images and styles

### ISSUE THREAD

**Issue by Vantageright** [wallabag/wallabag#4138]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

The only thing displaying is text, there is nothing in the way of styling or images.
[This is what it looks like.](https://imgur.com/a/njkgo1U) The rest of the page is more of the same
### Environment

* wallabag version (or git revision) that exhibits the issue:2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:7.2.19-0ubuntu0.18.04.2 
* OS:Ubuntu Server 18.04.3-preinstalled-server-arm64+raspi3
* type of hosting (shared or dedicated):Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySql

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by nicosomb** [comment]
Hello @Vantageright. 
Could you please execute `yarn run build:prod` ?

**Comment by Vantageright** [comment]
Resulted in this.

yarn run v1.19.0
warning Skipping preferred cache folder "/home/ubuntu/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-33".
$ ./node_modules/.bin/webpack --env=prod
warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/ubuntu/.yarn"
/bin/sh: 1: ./node_modules/.bin/webpack: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Kdecherf** [comment]
Hello @Vantageright,

Can you ensure that `domain_name` is correctly set in `app/config/parameters.yml`?
See https://doc.wallabag.org/en/admin/parameters.html for more information

**Comment by Vantageright** [comment]
It's set to http://192.168.0.200. I access it at ip/wallabag/web. do I need to change it to that and redo something?
