### ISSUE TITLE
v2: API routes definition

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#414]
This is an issue to talk about the new API for wallabag v2.  
I will start working on it and here is the way I will follow.

*I won't talk about authentication, since we'll follow OAuth (using an external library, for sure).*

The API will allow to:

- manage entries (get, create, update, delete, restore)
- manage tags associated to an entry (get, add, delete)
- manage tags in a global view (get, delete)

I made things more simple about star/unstar, read/unread. We can also create a dedicated endpoint for each of these actions..

-----

# Entries

### Get entries

Retrieve all entries. It could be filtered by many options.

````
GET /api/entries
````
#### Parameters

Name | Type | Description
--- | --- | ---
archive | boolean | filter by archived status. Default `false`.
star | boolean | filter by starred status. Default `false`.
delete | boolean | filter by deleted status. Default `false`.
sort | string | can be `created`, `updated`. Default `created`.
order | string | can be `asc` or `desc`. Default `desc`.
page | integer | what page you want. Default `1`
per_page | integer | results per page. Default `30`, maximum `100`.
tags | string | a list of tags url encoded, ie: `?tags=api%2Crest`.  Will returns entries that matches **ALL** tags

### Get an entry

Retrieve a single entry

````
GET /api/entries/{entry_id}
````

### Create an entry

Create an entry

````
POST /api/entries
````

#### Input

Name | Type | Description
--- | --- | ---
url | string | Url for the entry (**required**)
title | string | Optional, we'll get the title from the page
tags | string | a comma-separated list of tags

### Update an entry

Since we use `PATCH`, at least one field is necessary to update the entry.

````
PATCH /api/entries/{entry_id}
````

#### Input

Name | Type | Description
--- | --- | ---
title | string | 
tags | string | a comma-separated list of tags (will erase all other tags?)
star | boolean | starred the entry. Default `false`.
archive | boolean | archived the entry. Default `false`.
delete | boolean | flag as deleted. Default `false`. In case that you don't want to *really* remove it.

### Delete an entry

This method will remove **permanently** an entry.

````
DELETE /api/entries/{entry_id}
````

# Tags

## Tags associated to entries 

All actions are related to one entry.

### Get all tags

Retrieve all tags

````
GET /api/entries/{entry_id}/tags
````

### Add tags

Add one or more tags

````
POST /api/entries/{entry_id}/tags
````

#### Input

Name | Type | Description
--- | --- | ---
tags | string | a comma-separated list of tags (will erase all other tags?)

### Remove one tag

Permanently remove one tag

````
DELETE /api/entries/{entry_id}/tags/{tag_id}
````

### Get all tags

Retrieve all tags

````
GET /api/tags
````

### Remove one tag

Permanently remove one tag from **every** entries

````
DELETE /api/tags/{tag_id}
````

**Comment by nicosomb** [comment]
Just for information, I'm working on v2, based on symfony. 

You can try it there: http://v2.wallabag.org
Documentation for API is there: http://v2.wallabag.org/api/doc (I only declared method, code is not yet implemented)
If it's OK for all of you, I can contact our smartphones apps for working on v2 applications.

**Comment by j0k3r** [comment]
Looks good to me !

**Comment by nicosomb** [comment]
For your information, all the code in in refactor branch https://github.com/wallabag/wallabag/tree/refactor

**Comment by nicosomb** [comment]
About API, I think we'll have to add User entity (see #1346).

**Comment by tcitworld** [comment]
:+1:

**Comment by nicosomb** [comment]
Unless tags API, everything seems to be implemented. 

I move this PR to 2.1.0, that's the milestone for all "tags" issues.

**Comment by nicosomb** [comment]
I close this issue. For missing routes (tags?), we'll create issues when it will be necessary.
