### ISSUE TITLE
Unable to save sites via web interface

### ISSUE THREAD

**Issue by Vantageright** [wallabag/wallabag#4144]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Cannot save webpages with wallabagger or through the web interface. Results in /new-article displaying the following:
Compile Error: require(): Failed opening required '/var/www/html/wallabag/var/cache/prod/rulerz/rulerz_executor_f87b0888' (include_path='.:/usr/share/php')

### Environment

    wallabag version (or git revision) that exhibits the issue:2.3.8
    How did you install wallabag? Via git clone or by downloading the package? git clone
    Last wallabag version that did not exhibit the issue (if applicable):
    php version:7.2.19-0ubuntu0.18.04.2
    OS:Ubuntu Server 18.04.3-preinstalled-server-arm64+raspi3
    type of hosting (shared or dedicated):Dedicated
    which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySql

**Comment by j0k3r** [comment]
Check https://doc.wallabag.org/en/admin/installation/rightaccess.html

**Comment by Vantageright** [comment]
I'd missed a folder, thanks.
