### ISSUE TITLE
Can no longer add items after server upgrade to Debian 10

### ISSUE THREAD

**Issue by Ygster** [wallabag/wallabag#4148]
### Issue details

After upgrading my server to Debian 10 I can't no more add any items to wallabag.
I can use it and mark items as read.
I have the following error when I try to add an item :
```
500: Internal Server Error

Attempted to call an undefined method named "toggleImgNoReferrer" of class "Graby\Graby".
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): 2.3.4 in Debian 9
* php version: 7.0 or 7.3
* OS: Debian 10.0
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

I try to install wallabag on another folder, and have another error.
I try too to update wallabag via make update and now have the following error
```
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 43 (delta 20), reused 18 (delta 15), pack-reused 4
Dépaquetage des objets: 100% (43/43), fait.
Depuis https://github.com/wallabag/wallabag
   43fab736..afe48653  master     -> origin/master
HEAD est maintenant sur 9bbafdaa Release wallabag 2.3.8
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                           

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

make: *** [GNUmakefile:17: update] Error 1
```

**Comment by j0k3r** [comment]
Looks similar to: https://github.com/wallabag/wallabag/issues/3961
Can you check the discussion and try solution we asked?

**Comment by Ygster** [comment]
I think I've already read this issue and tested it

What solution are you talking about?
If this is the version to compose, here is the version on my server
Compose version 1.9.0 2019-08-02 20:55:32

If it's another solution, can you tell me more about it, point to the corresponding exchange?

Thank you in advance

**Comment by j0k3r** [comment]
- Manually clear the cache `rm -rf var/cache/*`
- Fix permission for composer to use its cache
- Check version of graby (which generate the `toggleImgNoReferrer` error): `composer show j0k3r/graby`

**Comment by Ygster** [comment]
I cleared the cache with 
<code> rm -rf var/cache/* </code>

Create the directory /var/www/.compose and give the rights to the user www-data on it

I still have the same mistakes, but I no longer have the warnings related to the cache with dialing.

Below is the result of the order for graby, but I'm not sure what to do next:
```
name : j0k3r/graby
description. : Graby helps you extract article content from web pages
keywords : 
versions : * 1.19.1
type : library
license: MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source : [git] https://github.com/j0k3r/graby.git 6c1506f19d1bb876fb26bfc11e3e11a993eb7fe8
dist : [zip] https://api.github.com/repos/j0k3r/graby/zipball/6c1506f19d1bb876fb26bfc11e3e11a993eb7fe8 6c1506f19d1bb876fb26bfc11e3e11a993eb7fe8
path : /var/www/html/wallabag_v2/vendor/j0k3r/graby
names: j0k3r/graby

autoload
psr-4
Graby\ => src/

requires
ext-curl *
fossar/htmlawed ^1.2.4
guzzlehttp/guzzle ^5.2.0
j0k3r/graby-site-config ^1.0
j0k3r/php-readability ^1.0
j0k3r/safecurl ~2.0
monolog/monolog ^1.13.1
php >=5.4
simplepie/simplepie ^1.3.1
smalot/pdfparser ~0.11
symfony/options-resolver ~2.6|~3.0
true/punycode ~2.0
wallabag/tcpdf ^6.2

requires (dev)
friendsofphp/php-cs-fixer ~2.0
php-coveralls/php-coveralls ~0.6
symfony/phpunit-bridge ~2.6|~3.0|~~4.0
```

**Comment by j0k3r** [comment]
What is weird is that the locked version of graby for the 2.3.8 release is the 1.20.0 and not the 1.19.1: https://github.com/wallabag/wallabag/blob/2.3.8/composer.lock#L3128-L3129

Could you check these lines on your side?

**Comment by Ygster** [comment]
Yes, that's what I thought I understood, but I don't see how to solve it.

If I check these lines, I find this:
```
            "name": "j0k3r/graby",
            "version": "1.20.0",
```

I have looked but I don't see if I can update the repository via git.
Or if I delete the repository, it will be recreated or you have to run a command for that?

**Comment by Ygster** [comment]
Okay, I didn't realize we had to run this command.
So here is the result and I still have the exception

```                                                                               
  [Symfony\Component\Debug\Exception\ContextErrorException]                    
  Warning: "continue" targeting switch is equivalent to "break". Did you mean  
   to use "continue 2"?                                                        
                                                                               

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-cmd event terminated with an exception

                                                                                   
  [RuntimeException]                                                               
  An error occurred when executing the "'cache:clear --no-warmup'" command:        
                                                                                   
                                                                                   
                                                                                   
                                                                                   
                                                                                   
    [Symfony\Component\Debug\Exception\ContextErrorException]                      
    Warning: "continue" targeting switch is equivalent to "break". Did you mean    
     to use "continue 2"?                                                          
                                                                                   
```
I see this line about graby
```
- Updating j0k3r/graby (1.19.1 => 1.20.0): Downloading (100%)
```

**Comment by Kdecherf** [comment]
@Ygster as you have the new version now, can you try again `rm -rf var/cache/*` and finish with another call to `composer install`?

**Comment by Ygster** [comment]
I tried that and the result is the same.
Do you want me to put the complete output of the command?

**Comment by Ygster** [comment]
The problem of adding items has disappeared.

After the last action requested, I did a system update of my server and a reboot (in another frame than this issue) and after rebooting by testing the addition of an item it worked.

I close the exit but I don't really understand exactly where my problem came from.

Thank you for your help
