### ISSUE TITLE
Installation on shared webhosting

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#4164]
### Issue details

I have try to install wallabag on legtux (a webhobsting), with this tutorial : https://doc.wallabag.org/en/admin/installation/virtualhosts.html. I have create a virtual host (my subdomain bag.example.org is on /www/qwerty/wallabag/web). I have this error, when i go on bag.example.org/login (and don't have wallabag tables) : 

```
 Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'qwerty.wallabag_craue_config_setting' doesn't exist in /var/www/legtux.org/users/qwerty/bag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105 Stack trace: #0 /var/www/legtux.org/users/qwerty/bag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL) #1 /var/www/legtux.org/users/qwerty/bag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(847): Doctrine\DBAL\Driver\PDOStatement->execute() #2 /var/www/legtux.org/users/qwerty/bag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(712): Doctrine\DBAL\Connection->executeQuery('SELECT t0.secti...', Array, Array) #3 /var/www/legtux.org/users/qwerty/bag/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(196): Doctrine\ORM\Persisters\Entity\BasicEntityPersis in /var/www/legtux.org/users/qwerty/bag/src/Wallabag/CoreBundle/Resources/views/base.html.twig on line 74
```
**How to create mysql tables ?**

### Environment

* wallabag version (or git revision) that exhibits the issue:
* Downloading package like is indicate in tutorial
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.2
* OS: linux
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

Thinks a lo

**Comment by tcitworld** [comment]
You need to run `wallabag:install`.

**Comment by qwertygc** [comment]
I can't, i have just access in the FTP...

**Comment by nicosomb** [comment]
@qwertygc as your issue is pretty old, I close it. 

If you still have problems during installation (with wallabag 2.6.x), feel free to open a new issue.
