### ISSUE TITLE
Medium article is missing images

### ISSUE THREAD

**Issue by cfitzfor** [wallabag/wallabag#4166]
### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone`
* php version: 7.2
* OS: Ubuntu 18.04.3 LTS
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case
* Add URL: https://medium.com/@100trillionUSD/modeling-bitcoins-value-with-scarcity-91fa0fc03e25
* No error happens so far, but images inside the article are just gone
* This site: https://f43.me/feed/test has the same problem when using the internal parser. It works fine when using the external one which is https://github.com/postlight/mercury-parser

**Comment by rodh** [comment]
+1 I'm experiencing this same problem.

**Comment by Kdecherf** [comment]
I am unable to reproduce this issue on 2.3.8 and current master, @cfitzfor @rodh do you still see it?

**Comment by nicofrand** [comment]
I can reproduce it on 2.3.8 with https://medium.com/refactoring-ui/7-practical-tips-for-cheating-at-design-40c736799886, https://f43.me has no issue with it.

**Comment by j0k3r** [comment]
It looks perfectly ok for me on the upcoming 2.4.0: [screenshot](https://user-images.githubusercontent.com/62333/79226295-6aad7680-7e5e-11ea-8b17-697c010b88a7.png)

Same for the article OP are talking about.

**Comment by nicofrand** [comment]
BTW, I failed to mention I have "Download images locally" enabled.
I'll try with 2.4.0.

**Comment by nicofrand** [comment]
I tested it locally (through `make dev`) and it worked fine! I could not test with 2.3.8 though (`make install && make run` were giving errors).

**Comment by j0k3r** [comment]
Great ! I’ll consider the issue fixed then
