### ISSUE TITLE
Unusable after install

### ISSUE THREAD

**Issue by The-Inamati** [wallabag/wallabag#4185]
I just did a fresh install of wallabag on an Ubuntu Server 18.04. Everything goes well with the installation but the app is inaccessible after that. I get a 404 error from the app itself. I followed the wallabag documentation during installation.

### Environment

* wallabag version (or git revision) that exhibits the issue: latest
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): NA
* php version: 7.3
* OS: Ubuntu Server 18.04 LTS
* type of hosting  (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Apache Virtual Host Configuration**

```
<VirtualHost *:80>
    ServerName domain.ltd 
    DocumentRoot /var/www/html/wallabag/web
    <Directory /var/www/html/wallabag/web>
        AllowOverride None
        Order Allow,Deny
        Allow from All
        <IfModule mod_rewrite.c>
            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ app.php [QSA,L]
        </IfModule>
    </Directory>
 <Directory /var/www/html/wallabag/web/bundles>
        <IfModule mod_rewrite.c>
            RewriteEngine Off
        </IfModule>
    </Directory>
    ErrorLog /var/log/apache2/wallabag_error.log
    CustomLog /var/log/apache2/wallabag_access.log combined
</VirtualHost>
```

**Error in Wallabag Logs**

`[2019-11-13 10:24:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /index.php"" at /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /index.php\" at /var/www/html/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:128, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []`

**Error in Apache Logs (Probably Unrelated)**

`[Wed Nov 13 10:24:43.455498 2019] [php7:warn] [pid 21035] [client 10.0.100.1:37360] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636`

**Comment by nicosomb** [comment]
Hello @The-Inamati. 
* is composer up to date `composer selfupdate`? 
* could you try with php 7.2 and then `composer install` ?

**Comment by The-Inamati** [comment]
Sorry. Issue fixed a long time ago. It was on my end.

**Comment by JialuZhang** [comment]
@The-Inamati 

In your posted configuration,

```
<Directory /var/www/html/wallabag/web/bundles>
        <IfModule mod_rewrite.c>
            RewriteEngine Off
        </IfModule>
    </Directory>
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".

More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.

Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.

Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
