### ISSUE TITLE
domain_name parameter not utilized

### ISSUE THREAD

**Issue by dangerfish96** [wallabag/wallabag#4214]
### Issue details

I set the "domain_name" in paramaters.yml to https://domain.site/wallabag. Still, I am being redirected after the login page (https://domain.site/wallabag/login) to https://domain.site/login_check and not the wallabag subdirectory.
The redirection from https://domain.site/wallabag to https://domain.site/wallabag/login works as expected.

### Environment

* wallabag version (or git revision) that exhibits the issue: revision b76bf31bca6b1909751daf15e33a22a902074d41 (Current master)
* How did you install wallabag? Via `git clone` or by downloading the package? docker-compose
* OS: ubuntu alpine
* type of hosting (shared or dedicated): nginx reverse proxy
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mariadb

### Steps to reproduce/test case
After install login with admin account

**Comment by dangerfish96** [comment]
Did I setup the parameters file incorrectly?

**Comment by nicosomb** [comment]
Seems to be a duplicate as https://github.com/wallabag/wallabag/issues/1913
