### ISSUE TITLE
OTP Label is username instead of wallabag or instance

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#4215]
### Issue details

QR code URI is `otpauth://totp/%username%?secret=%secret%`. Instead of username [it should be a label](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) to know about the service or instance, something like `wallabag` maybe including the instance, such as `wallabag (wallabag.it)`.

### Environment

`wallabag.it`

### Steps to reproduce/test case

Setup OTP.

**Comment by j0k3r** [comment]
This is not the way the library we are using work:
- https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/providers/google.md#qr-codes
- https://github.com/scheb/two-factor-bundle/blob/dd2fe19845d346bce35acacb094ec7b8b485ffa6/Security/TwoFactor/Provider/Google/GoogleAuthenticator.php#L36-L39

This kind of change should be applied upstream instead I guess

**Comment by tcitworld** [comment]
It seems it [actually does](https://github.com/scheb/two-factor-bundle/blob/master/Security/TwoFactor/Provider/Google/GoogleTotpFactory.php#L39-L44). 
The configuration in `app/config/config.yml` under `scheb_two_factor.google` is just missing (see [reference](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/providers/google.md#configuration-reference)):
```
server_name: Server Name       # Server name used in QR code
issuer: Issuer Name            # Issuer name used in QR code
```
