### ISSUE TITLE
Renaming a tag removes the relation between tag and entry

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#4216]
### Issue details

I tried the renaming tags feature. The tag is renamed but the relation between tag and entry is removed. 

### Environment

* wallabag version (or git revision) that exhibits the issue: master
* How did you install wallabag? Via `git clone`
* php version: 7.3
* OS: debian 
* type of hosting (shared or dedicated): wallabag.it
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

You can't reproduce it on wallabag.it because I disabled this feature to avoid bad experience for users.

**Comment by Kdecherf** [comment]
The issue is a little more complex than that. The relation is not lost if the tag only has one article.

If the tag has more than one article, the rename will create as many labels as there are articles
