### ISSUE TITLE
Invalid byte sequence for encoding UTF-8 from a PDF link

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/wallabag#4221]
### Issue details

There is an 500 Internal Server Error when trying to add a PDF to wallabag.

```
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF6f";}' for column 'published_by' at row 1
```

On wallabag 2.3.8 / PostgreSQL 9.6 the error looks different:
```
SQLSTATE[22021]: Character not in repertoire: 7 ERROR: invalid byte sequence for encoding "UTF8": 0xf6 0x66 0x22 0x3b
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8 / `master` (_though there is a different error between these versions_)
* How did you install wallabag? Via `git clone` or by downloading the package? `git`
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version: 7.3.11
* OS: Linux
* type of hosting (shared or dedicated): local env
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL 5.7

### Steps to reproduce/test case

1. Add https://www.ivl.se/download/18.14d7b12e16e3c5c36271070/1574923989017/C444.pdf
2. Profit

**Comment by Kdecherf** [comment]
May be related to #3576

**Comment by tcitworld** [comment]
> MySQL 5.7

Are you sure the charset is utf8mb4?

**Comment by di72nn** [comment]
Saving [this PDF](https://openresearch-repository.anu.edu.au/bitstream/1885/98880/2/01_Homer-Dixon_Synchronous_failure%253A_the_2015.pdf) to **wallabag.it** results in
```
500: Internal Server Error ... SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xE9pin, ...' for column `app_wallabag_it`.`wallabag_entry`.`published_by` at row 1
```

Saving it with 2.3.8 (with latest mariadb) however results in this:
```
500: Internal Server Error ... Incorrect string value: '\xE9pin, ...' for column `wallabagv2`.`wallabagv2_entry`.`published_by` at row 1
```
(no mention of `datetime format`).

The problem seems to be caused by the following sequence being saved to `published_by`:
```
"\x61\x3a\x31\x3a\x7b\x69\x3a\x30\x3b\x73\x3a\x31\x37\x35\x3a\x22\x54\x68\x6f\x6d\x61\x73\x20\x48\x6f\x6d\x65\x72\x2d\x44\x69\x78\x6f\x6e\x2c\x20\x42\x72\x69\x61\x6e\x20\x57\x61\x6c\x6b\x65\x72\x2c\x20\x52\x65\x69\x6e\x65\x74\x74\x65\x20\x42\x69\x67\x67\x73\x2c\x20\x41\x6e\x6e\x65\x2d\x53\x6f\x70\x68\x69\x65\x20\x43\x72\xe9\x70\x69\x6e\x2c\x20\x43\x61\x72\x6c\x20\x46\x6f\x6c\x6b\x65\x2c\x20\x45\x72\x69\x63\x20\x46\x2e\x20\x4c\x61\x6d\x62\x69\x6e\x2c\x20\x47\x61\x72\x72\x79\x20\x44\x2e\x20\x50\x65\x74\x65\x72\x73\x6f\x6e\x2c\x20\x4a\x6f\x68\x61\x6e\x20\x52\x6f\x63\x6b\x73\x74\x72\xf6\x6d\x2c\x20\x4d\x61\x72\x74\x65\x6e\x20\x53\x63\x68\x65\x66\x66\x65\x72\x2c\x20\x57\x69\x6c\x6c\x20\x53\x74\x65\x66\x66\x65\x6e\x2c\x20\x4d\x61\x78\x20\x54\x72\x6f\x65\x6c\x6c\x22\x3b\x7d"
```
The string contains two diacritics (or whatever it is):
```
a:1:{i:0;s:175:"Thomas Homer-Dixon, Brian Walker, Reinette Biggs, Anne-Sophie Crépin, Carl Folke, Eric F. Lambin, Garry D. Peterson, Johan Rockström, Marten Scheffer, Will Steffen, Max Troell";}
```

I'm almost sure I have utf8mb4 set up correctly (the DB is in utf8mb4, wallabag's `parameters` contain `utf8mb4`) - there are not issues with emojis.

**Comment by anarcat** [comment]
adding this article to the wallabag android app makes sync crash with a 500 internal server error as well, clogging the queue until we "Remove first local queue item" in Misc -> Local changes...

https://www.geeek.org/content/files/2022/01/ebook_sept2003.pdf

old PDF in french, maybe some funky encoding going on there as well...

**Comment by Kdecherf** [comment]
I am unable to reproduce it on current master, closing it
