### ISSUE TITLE
Make install stuck while setting up database

### ISSUE THREAD

**Issue by danmacode** [wallabag/wallabag#4234]
### Issue details

I just did a fresh install of wallabag on an raspberry pi 3B+. Everything goes well with the installation until we access the database for reset, then it gets stuck. 
In raspbian buster for pc (raspi VM w/ VirtualBox) this error doesn't appear and all goes well. Not sure if it's a problem with wallabag or with mariaDB, since doing a DATABASE DROP wallabag after the failed install takes also ~30 seconds or so, which seems too much and probably indicates something wrong with it.
Docker wallabag works fine in the same raspi.

### Environment

* wallabag version 2.3.8
* How did you install wallabag? Via `git clone` then `make install`
* php version: 7.3
* OS: raspbian buster
* hardware: raspi 3B+
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

- `git clone` 
- `make install`
All goes well except that the installation gets stuck at this point:
```

 [OK] Success! Your system can run wallabag properly.


Step 2 of 4: Setting up database.
---------------------------------

 It appears that your database already exists. Would you like to reset it? (yes/no) [no]:
 > yes

 Dropping database, creating database and schema...
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/pi/wallabag/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 272
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/pi/wallabag/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 275
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/pi/wallabag/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 281
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/pi/wallabag/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 287
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/pi/wallabag/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 296
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/pi/wallabag/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 314
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/pi/wallabag/vendor/zendframework/zend-code/src/Reflection/MethodReflection.php on line 319
```

`sudo -u www-data php bin/console cache:clear -e prod` works without problem, but 
`php bin/console wallabag:install --env=prod` gets stuck the same way

**Comment by nicosomb** [comment]
Hello. 

This issue is a composer related issue (see https://stackoverflow.com/questions/54184707/warning-continue-targeting-switch-is-equivalent-to-break-did-you-mean-to-u). I close it.
