### ISSUE TITLE
shared-hoster download package on your main site does not work 

### ISSUE THREAD

**Issue by Caliandroid** [wallabag/wallabag#4236]
No source code issue but your download link does not seem to work anymore:
`wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package`

I've tested also 
 `wget --no-check-certificate https://wllbg.org/latest-v2-package && tar xvf latest-v2-package
`

result: 404

**Comment by ei-ke** [comment]
workaroung: https://static.wallabag.org/releases/

**Comment by undrwater** [comment]
Unfortunately, these appear to require composer to install. Not appropriate for shared hosting without composer. Are the built packages no longer provided?

**Comment by andrewchenshx** [comment]
i installed the version 2.3.8 from https://static.wallabag.org/release/,
after unzipped, i got a 403

**Comment by j0k3r** [comment]
@andrewchenshx could you open a different issue please? It's not related to OP

**Comment by nicosomb** [comment]
Does https://wllbg.org/latest-v2-package work now?

**Comment by andrewchenshx** [comment]
@nicosomb 
--2020-03-31 12:02:41--  https://wllbg.org/latest-v2-package
Resolving wllbg.org... 138.201.122.115, 2a01:4f8:172:25b0::2
Connecting to wllbg.org|138.201.122.115|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://static.wallabag.org/releases/wallabag-release-2.3.8.tar.gz [following]
--2020-03-31 12:02:42--  https://static.wallabag.org/releases/wallabag-release-2.3.8.tar.gz
Resolving static.wallabag.org... 138.201.122.115, 2a01:4f8:172:25b0::2
Connecting to static.wallabag.org|138.201.122.115|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43680377 (42M) [application/octet-stream]
Saving to: 'latest-v2-package'

so, it is actually https://static.wallabag.org/releases/wallabag-release-2.3.8.tar.gz

**Comment by j0k3r** [comment]
Which means issue is fixed!
