### ISSUE TITLE
Export epub title and author could be more descriptive

### ISSUE THREAD

**Issue by henrythemouse** [wallabag/wallabag#4241]
### Issue details

When I export unread articles to an epub the title of the epub is "unread articles"
and the author of the epub is  "Various authors". This is OK but could be more
useful. In my EntriesExport.php file I have changed these defaults slightly so that
when I see them on my e-reader I can know what to expect without opening the
epub. I'm not a php programmer and I don't know the correct way to write a patch
file, but I'd like to try to explain where and what I changed, hopefully it's understandable.

```
EntriesExport.php

21      -   private $author = 'wallabag';
21      +   private $author = 'Wallabag';

59      -   $this->title = $Method . ' Articles'
59      +   $d = date('Y-m-d');
60      +   $this->title = 'Wallabag Articles ' . $d;

78      -   $this->author = 'Various authors';
78      +   $this->author = 'Wallabag Export';
```

If you adopt this 'improvement' I won't have to patch it locally each time I upgrade ;-).

### Environment

* wallabag version 2.3.8
* How did you install wallabag? Via `git clone`
* php version: 7.3
* OS: debian 10
* type of hosting (dedicated):
* which storage system you choose at install (MariaDB):

### Steps to reproduce/test case

Open your Wallabag unread articles in your browser and export them to EPUB.
(if you have an e-reader, send them to the e-reader)
Note the file name, title and author.

**Thank you to everyone at  Wallabag for a very useful application.**

**Comment by j0k3r** [comment]
First of all, wallabag shouldn't be written with a capital letter :)
I'm not against adding the date to the export, it could be a good thing.
About the author, why not use both solution, with _Various authors (wallabag Export)_?

**Comment by henrythemouse** [comment]
I'll admit the capital W is not a good fit.
The date is good for me, if I have more than one wallabag epub it makes for a good reference.
About the author, would you consider: wallabag Export (various authors)?

It seems to me we all know that it's various authors because it's a package of articles that we made. In addition, 'various authors' is not a distinguished name where as 'wallabag Export' specifically distinguishes the wallabag epub from other epubs. Just to give you my thinking regarding the author name.

Thanks for your quick reply.
And thank you again for wallabag, it's the best 'read-it-later' application available.

**Comment by Kdecherf** [comment]
I think adding _wallabag_ in the authors field is semantically wrong. I would prefer exploring other fields provided by the specification for this kind of information like `subject` or `publisher`.

**Comment by henrythemouse** [comment]
I can understand that. Being a user my perspective is to have wallabag do what I want it to do, adhering to the epub specification is not a top priority for me.

I can appreciate your position on this matter and am willing to support whatever decision you make.
Whatever is better for the future of wallabag is what should be done.

Thank you for considering my post. As far as I'm concerned this issue can be closed.
