### ISSUE TITLE
Export to Markdown

### ISSUE THREAD

**Issue by Agrotsa** [wallabag/wallabag#4243]
Wallabag can export to various formats like PDF, EPub and others. Could be added a new option to export in markdown format? For taking notes and create brief documents, MD is usually preferred than ODT and HTML. It's a light format, there are a ton of apps compatible with it, and you can edit them in anything that can edit plain text.

**Comment by tcitworld** [comment]
Converting from HTML to markdown is quite a tricky thing to do though.

**Comment by Agrotsa** [comment]
Oh, I didn't know. I thought it would be more or less as easy as converting to MD to HTML. My apologies.

**Comment by tcitworld** [comment]
There's libraries (such as [html-to-markdown](https://github.com/thephpleague/html-to-markdown)) to do it but results may vary.

**Comment by Agrotsa** [comment]
Ok, it seems way more complex than I thought at first. Sorry for my development stuff ignorance. Heheh. And thanks for you explanations.

**Comment by brimwats** [comment]
I would also like to add support for this idea, especially given the takeoff in Personal Kowledge Base/Management applications like obsidian, foam, etc that are markdown based. I've used the MarkDownloader extension on wallabag pages and it does an excellent job, so it might be worth taking a look at how they do it. The only thing it doesn't catch is tags.

**Comment by nicosomb** [comment]
A pull request is opened for this feature: https://github.com/wallabag/wallabag/pull/7799
