### ISSUE TITLE
print only first page

### ISSUE THREAD

**Issue by GusevVictor** [wallabag/wallabag#4251]
### Issue details

I use Version: 2.4.0-dev by https://app.wallabag.it (demo)

### Environment

* wallabag version 2.4.0-dev
* How did you install wallabag? I use demo free hosting

### Steps to reproduce/test case

Just add any web pages after that open this page call left side menu and hit print. You will have only fisrt page on printer.

![изображение](https://user-images.githubusercontent.com/7081357/72374317-1853a100-371b-11ea-81c0-475594c08031.png)

**Comment by j0k3r** [comment]
What do you mean by “first page”?

**Comment by GusevVictor** [comment]
> 
> 
> What do you mean by “first page”?

for exaple: article contains many text but printer print first page. So, I think wallabag send only one page because **1 of 1 stamp** in bottom of printed page.

**Comment by GusevVictor** [comment]
> 
> 
> What do you mean by “first page”?

@j0k3r do you have same problem?

**Comment by j0k3r** [comment]
Could you share the article you put in your wallabag, so I can try on my own

**Comment by GusevVictor** [comment]
> 
> 
> Could you share the article you put in your wallabag, so I can try on my own

**Yes, step to reproduce:** 

1. Reg trial on https://app.wallabag.it
2. Add test arcticle: https://englishwithatwist.com/2019/12/19/mindset/
3. Try to print by use left side menu

Thank a lot for you time.

**Comment by virtadpt** [comment]
I'm experiencing the same problem.  Started with v2.3.4, still happening with v2.3.8.

**Comment by GusevVictor** [comment]
> 
> 
> I'm experiencing the same problem. Started with v2.3.4, still happening with v2.3.8.

Thank for you answer I hope developers fix that problem. :)

**Comment by j0k3r** [comment]
Did you use Firefox?
I've no problem when using Chrome & Safari.

Did you really printed the page? Or only using the PDF export for the print?

**Comment by GusevVictor** [comment]
> 
> 
> Did you use Firefox?
> I've no problem when using Chrome & Safari.
> 
> Did you really printed the page? Or only using the PDF export for the print?

Yes. I have tested it in firefox and edge. The problem exist when print or when export to pdf too...  :(

**Comment by virtadpt** [comment]
Firefox, Chrome, and Chromium here.

**Comment by Kdecherf** [comment]
The issue seems to be limited to Firefox, there's an open issue on their bug tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=939897

One workaround is to replace the flex display with block, I'll try it and push a PR to fix it.

**Comment by GusevVictor** [comment]
Wow... Thank you! It works in latest Ghrome as expected. Firefox... Oh... I want to use Firefox.
