### ISSUE TITLE
Autotagging: new tag created with identical name to existing one

### ISSUE THREAD

**Issue by Najrim** [wallabag/wallabag#4266]
# Issue details

When using tagging rules it seems that each time a new article is added, a new tag with the same name as a preexisting one is created but it only contains the new article. It might look like:

Politics (13)
Politics (1)

in the list of tags.

### Environment

Wallabag.it with Wallabagger on Firefox.

### Steps to reproduce/test case

1. Add an autotagging rule to tag with X if title matches X (and there are already articles tagged X in Wallabag)
2. Go to a an article with X in the title.
3. Press Wallabagger button or add article through right-click menu or copy URL and add with the add-by-URL function inside Wallabag.
4. Check list of tags.

There is now one more tag in the list of tags with identical name to an already existing one but only containing one article (the new one).

**Comment by Najrim** [comment]
Is anyone able to reproduce?

**Comment by Kdecherf** [comment]
I was able to reproduce this issue on current master with tags containing letters in uppercase

**Comment by Najrim** [comment]
Seems to be the same way here.

I should also mention that re-adding the article (pressing the Wallabagger button twice) fixes it for that article.

**Comment by fbroussais** [comment]
Perhaps it come from the same bug : I've created automated tagging rules then imported data from Poclet. Now I have 393 similar tags.

**Comment by bjoernv** [comment]
Is there a good way to fix this problem in a database with existing duplicate tags?

**Comment by Kdecherf** [comment]
@bjoernv renaming a tag from the tags page should be enough to trigger a merge

**Comment by bjoernv** [comment]
@Kdecherf 
>renaming a tag from the tags page should be enough to trigger a merge

Thanks, but this unfortunately does not work for me. I renamed "corona" to "corona1" and "corona1" to "corona" back in tags view. There is only one tag "corona" left in tags view. But the database still has duplicates.

```
mysql> select label, count(*) as count from wallabag_tag group by label having count(*) >1;
+------------------+-------+
| label            | count |
+------------------+-------+
| 2018             |     2 |
| corona           |    23 |
| covid-19         |    23 |
| google home      |     2 |

| password manager |     2 |
| windows 10       |     2 |
+------------------+-------+
7 rows in set (0,03 sec)
```

**Comment by Kdecherf** [comment]
Hm, I guess this "feature" has been fixed.

You could use a sql query like this one to merge tags:

``` sql
update wallabag_entry_tag
  set tag_id = 54
  where tag_id in (
    select t.id 
      from wallabag_tag t
      left join wallabag_entry_tag et
        on et.tag_id = t.id
      where t.label = 'corona'
        and t.id <> 54
      group by 1);
```

You can then clean the duplicate tags with the following query:

``` sql
delete from wallabag_tag
  where id in (
    select id
      from wallabag_tag
      where label = 'corona'
        and id <> 54);
```

Replace `54` with the id of the tag you want to keep and `'corona'` with the label to deduplicate.

**Comment by bjoernv** [comment]
@Kdecherf, Thank you. MySQL 5.7 shows an error for the first SQL command, but with executing the sub-query separately first I could clean up my database.
```
mysql> update wallabag_entry_tag
    ->   set tag_id = 2765
    -> where tag_id in (
    ->     select t.id 
    ->       from wallabag_tag t
    ->       left join wallabag_entry_tag et
    ->         on et.tag_id = t.id
    ->       where t.label = 'corona'
    ->         and t.id <> 2765);
ERROR 1093 (HY000): You can't specify target table 'wallabag_entry_tag' for update in FROM clause
```
