### ISSUE TITLE
Fatal error with PHP 7.4

### ISSUE THREAD

**Issue by prolibre** [wallabag/wallabag#4271]
Wallabag (2.3.8) does not work under PHP 7.4

Logs :

`[Tue Jan 28 12:47:53.978736 2020] [php7:error] [pid 32192] [client IP] PHP Fatal error:  Cannot redeclare mb_str_split() in INSTALL_DIR/wallabag/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119`

If I comment the code that redeclares the function the page is displayed but with a bad display.

Have a good day

**Comment by j0k3r** [comment]
We are aware of that and it'll be fixed in the 2.4.0
See https://github.com/wallabag/php-mobi/commit/bfe9c18d038e5ca24664cfdab107a645ac57c9b5

**Comment by CardSnap** [comment]
Any idea on when 2.4.0 is coming out?

**Comment by pete1450** [comment]
> 
> 
> Any idea on when 2.4.0 is coming out?

Can't speak to that but until then- with a brand new clone I went to wallabag/vendor/wallabag/php-mobi and made then changes listed in the commit j0k3r linked(skipped the gitignore). All up and running now for me.

**Comment by m3Lith** [comment]
> > Any idea on when 2.4.0 is coming out?
> 
> Can't speak to that but until then- with a brand new clone I went to wallabag/vendor/wallabag/php-mobi and made then changes listed in the commit j0k3r linked(skipped the gitignore). All up and running now for me.

Did the same with my existing installation. Only needed to restart the web server after that and it works.

**Comment by Glandos** [comment]
PHP 7.4 is the only choice in Debian/testing now.

I don't want to put more pressure, just to make it clear :)

**Comment by jfmcbrayer** [comment]
Also the only choice in Fedora 32. Applying the php-mobi patch mostly fixes this, but I still get a ton of 'PHP Notice:  Trying to access array offset on value of type null in /var/www/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 995' warnings, and there are a number of layout problems.

**Comment by 3n-k1** [comment]
@jfmcbrayer is the patch still working? my instance just went down and composer isn't having a fun time, throwing errors everywhere

**Comment by Square252** [comment]
Any update on the planned release date?

**Comment by lapineige** [comment]
Hello,
With the upgrade to php7.4 we are having a very similar issue : https://github.com/YunoHost-Apps/wallabag2_ynh/issues/162
How can we investigate and possibly fix this ? I'm not sure it's the same bug.
