### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by martineizayaga** [wallabag/wallabag#4279]
### Issue details

I got this when trying to download Wallabag to my DigitalOcean droplet.
`Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. `

### Environment

* wallabag version (or git revision) that exhibits the issue:
Latest one
* How did you install wallabag? Via `git clone` or by downloading the package?
Via `git clone`. I followed [these instructions](https://nxnjz.net/2019/02/install-wallabag-on-ubuntu-18-04-lts/)
* php version: 7.3
* OS: macOS 10.15.3
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case
I followed [these instructions](https://nxnjz.net/2019/02/install-wallabag-on-ubuntu-18-04-lts/)

**Comment by BrookeDot** [comment]
To help the developers (and others like me) help you could you let us know what page you got the 404 on? For installing Wallabag see the official documentation at:
https://doc.wallabag.org/en/admin/installation/readme.html

**Comment by deepesharora** [comment]
this instruction >>> wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package
at https://doc.wallabag.org/en/admin/installation/installation.html is broken. 

I was able to get the latest package by simply referring to it from https://static.wallabag.org/releases

**Comment by andrewchenshx** [comment]
@deepesharora , it seems the package from https://static.wallabag.org/release can NOT be deployed in a shared host.
i got a 403 after installation

**Comment by j0k3r** [comment]
@deepesharora @andrewchenshx this isn't related to the OP, please open a new issue instead.

**Comment by Kdecherf** [comment]
There is not much activity on this issue, closing it.
