### ISSUE TITLE
Add Read It Later to the list of clients

### ISSUE THREAD

**Issue by bilelmoussaoui** [wallabag/wallabag#4286]
Hey!

I wrote a Wallabag client for Linux desktop/mobile(as the app is fully adaptive) that uses GTK & Rust. I was wondering if it's possible to add it the list of available clients? :) the website repo seems to be deprecated hence my issue here. 

The source code is available at: https://gitlab.gnome.org/bilelmoussaoui/read-it-later.
It can be installed from: https://flathub.org/apps/details/com.belmoussaoui.ReadItLater.

Thank you!

**Comment by thibaultamartin** [comment]
It has a [beautiful set of icons](https://gitlab.gnome.org/bilelmoussaoui/read-it-later/-/tree/master/data/icons) you can use to promote it as well

![image](https://user-images.githubusercontent.com/1688309/75781591-c82dae00-5d5d-11ea-86f3-a121f38b9e93.png)

**Comment by j0k3r** [comment]
@bilelmoussaoui where is the list of available clients? 🤔

**Comment by bilelmoussaoui** [comment]
@j0k3r https://www.wallabag.it/en/applications?

**Comment by nicosomb** [comment]
Done.

**Comment by tcitworld** [comment]
@nicosomb You put the Opera logo next to "For Linux desktop/mobile "

**Comment by bilelmoussaoui** [comment]
> Done.

Thanks! 


We have a monochrome icon in the repo btw https://gitlab.gnome.org/World/read-it-later/-/blob/master/data/icons/com.belmoussaoui.ReadItLater-symbolic.svg

**Comment by nicosomb** [comment]
> @nicosomb You put the Opera logo next to "For Linux desktop/mobile "

oups! 

@bilelmoussaoui thank you. I will take it.

**Comment by tcitworld** [comment]
also it needs to be added on https://www.wallabag.org/en#applications
