### ISSUE TITLE
Import from Pocket stops at 140 articles

### ISSUE THREAD

**Issue by bipox** [wallabag/wallabag#4289]
Hi!

I have Wallabag installed through Yunohost, so version is 2.3.8~ynh1. I tried asking for help on their forums first.

Every time I launch an import, it's stops after 140 articles imported. If I launch it again, I now have 280 articles etc... mostly the same are re-downloaded, but some are new (I think).

Those are the error messages I've seen so far (in the browser):

`Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8788904 bytes)`

and

```
500: Internal Server Error

An exception occurred while executin g'INSERT INTO `entry` (uid, title, url, is_archived,   
is_starred, content, created_at, updated_at, published_at, published_by, starred_at, 
mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, 
origin_url, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params
```
followed by a list of wikipedia articles. I tried deleting them all before import, but it doesn't help.

And this error in the prod.log file:

```
2020-03-08 03:45:32] app.ERROR: PocketImport: Failed to authorize client: Client error response 
[url] https://getpocket.com/v3/oauth/authorize [status code] 403 [reason phrase] Forbidden 
{"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 403): Client error response 
[url] https://getpocket.com/v3/oauth/authorize [status code] 403 [reason phrase] Forbidden at 
/var/www/wallabag2/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89)"} []
[2020-03-08 03:45:32] security.DEBUG: Stored the security token in the session. 
{"key":"_security_secured_area"} []
```

Thanks for reading

**Comment by Kdecherf** [comment]
Hello @bipox,

For the first error, you should increase the `memory_limit` given to wallabag in order to help it handle large requests.

For the second one, the error message is incomplete as we don't see the actual exception that occurred. Could you provide a more precise log message?

**Comment by bipox** [comment]
Hi @Kdecherf, thank you for taking the time to help me. 

Yes, that was it!

I changed /etc/php/7.0/fpm/php.ini
```
; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = -1
```
I don't know how to apply the change.
I tried sudo /etc/init.d/nginx restart, but wallabag still failed. 
It worked after a reboot though.

**Comment by Kdecherf** [comment]
@bipox great, does it fix all reported issues?

**Comment by bipox** [comment]
Yes. Could you please tell me how to restart php so I can share the solution in the other thread?

I'm very surprised it doesn't come up more often (or at all) since almost everybody migrating from Pocket would be affected and Yunohost is supposed to be targeted towards beginners.

**Comment by Kdecherf** [comment]
You should be able to restart the php process using `/etc/init.d/php-fpm` or php7*-fpm depending on your distribution and php version.

Also I recommend to avoid setting `memory_limit` to -1 in order to prevent any side effect on your Yunohost instance. 512M or 768M should fit a large amount of use cases.

**Comment by bipox** [comment]
Yes I was planning to revert that. I'll try it with 512M.

Thanks for your help!
