### ISSUE TITLE
Download shared hosting package fails

### ISSUE THREAD

**Issue by mjjzf** [wallabag/wallabag#4297]
### Issue details

Tried to download WB package for shared hosting as directed on https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting .
When I use the wget link as indicated, I get a 404.

### Steps to reproduce/test case

Calling `wget http://wllbg.org/latest-v2-package && tar xvf latest-v2-package`

**Comment by nicosomb** [comment]
Hello. 

It's fixed now.
