### ISSUE TITLE
Clear cache via web interface?

### ISSUE THREAD

**Issue by gnimor** [wallabag/wallabag#4300]
I have a 2.2.3 installation on shared host (webhoster). No I want to disable the public user registration via the parameters.yml file. After changing the corresponding parameter I have read I have to clear the cache. So I have no console or ssh remote access. How can I clear the cache via the web interface or via ftp?

**Comment by Kdecherf** [comment]
Hello @gnimor,

You should have a folder named `var/cache/prod`, you can remove the content in it to clear the cache.

**Comment by gnimor** [comment]
Thanks for your update - works as expected.
