### ISSUE TITLE
fails to fetch articles from xda-developers.com

### ISSUE THREAD

**Issue by BasilTomato** [wallabag/wallabag#4306]
### Issue details

Wallabag is not able to fetch the article content from https://www.xda-developers.com/

f43.me error output:
- Request throw exception (with a response): Service Temporarily Unavailable
- error_message: Service Temporarily Unavailable

I have tried to build siteconfig with http://siteconfig.fivefilters.org/
body: //div[contains(concat(' ',normalize-space(@class),' '),' entry_content ')]

Unfortunately the issue remains the same.

Example article:
- https://www.xda-developers.com/google-camerax-android-api-third-party-apps-best-features-stock-camera/

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.0 (219), Android app from F-Droid repo
* How did you install wallabag? AuroraDroid, F-Droid repo
* OS: Android 10
* type of hosting (shared or dedicated): shared (app.wallabag.it)

### Steps to reproduce/test case

1. try to fetch any articles from XDA-Developers, see example above
2. error message: "wallabag can't retrieve contents for this article"

**Comment by j0k3r** [comment]
It looks like it's related to the DDOS protection from cloudflare.
See https://github.com/wallabag/wallabag/issues/1399
