### ISSUE TITLE
freshrss

### ISSUE THREAD

**Issue by Cristophe** [wallabag/wallabag#4307]
Dans freshrss, j'ai au préalable défini un partage sur wallabagv2, adresse : https://app.wallabag.it 

Quand je clique sur "partage" puis "wallabag", j'aboutis à la page :
https://app.wallabag.it//bookmarklet?url=https%3A%2F%2Fflus.io%2Fcarnet%2Frecap-3.html
Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by tcitworld** [comment]
Tu as du mettre un `/` à la fin de l’adresse de wallabag, et wallabag ne semble pas aimer le double `//` dans l'URL.

**Comment by Cristophe** [comment]
Merci pour la réponse ultra rapide !
C'était ça. Encore merci.
