### ISSUE TITLE
add aoc.media in the site credentials 

### ISSUE THREAD

**Issue by TontonMollo** [wallabag/wallabag#4321]
Please add support for saving aoc.media articles.

ps: They have never illustrations nor photos

tnx

**Comment by j0k3r** [comment]
Please help us achieve you want you gently request https://doc.wallabag.org/en/user/errors_during_fetching.html

tnx

**Comment by TontonMollo** [comment]
Any of theses categories of issues:

- a network problem;
- an issue with the remote server;
- wallabag can't fetch content due to the website structure.
- 

AOC.media is a paywall, Wallabag "see" only the public version of the articles, and not the suscribers version.

**Comment by j0k3r** [comment]
And it's already done.
We'll be available in the upcoming 2.4.
https://github.com/fivefilters/ftr-site-config/commit/94fad829d617ef5055b09250d76b3b3f0cf5de16

**Comment by TontonMollo** [comment]
Le 2020-04-14 14:39, Jérémy Benoist a écrit :

Hi !

> And it's already done.
>  We'll be available in the upcoming 2.4.
>  fivefilters/ftr-site-config@94fad82 [1]

Bravissimi !

Congrats !
