### ISSUE TITLE
Support refresh header 

### ISSUE THREAD

**Issue by hrehfeld** [wallabag/wallabag#4330]
### Issue details

`https://quantocracy.com/redirect.php?key=lHDrg1a9AN&source=feedburner` issues a `refresh` http header to redirect. This is sort of incorrect, but supported by most webbrowsers: https://stackoverflow.com/questions/283752/refresh-http-header

```
HTTP/2 200 OK
server: nginx
date: Mon, 13 Apr 2020 20:07:12 GMT
content-type: text/html; charset=UTF-8
content-length: 0
refresh: 0; url=https://miltonfmr.com/range-bound-trading-strategy/
strict-transport-security: max-age=2592000;
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
referrer-policy: strict-origin-when-cross-origin
x-cache-status: HIT
X-Firefox-Spdy: h2
```

Both wallabag and https://f43.me/feed/test fail to follow the redirect. Please add support for the `refresh` http header.

### Environment

* wallabag 2.3.8
* probably git, at least there's a valid .git
* php version: 7.1.33
* OS: centos
* shared

**Comment by hrehfeld** [comment]
awesome, thanks for the quick fix!

**Comment by hrehfeld** [comment]
I just tested, and https://quantocracy.com/redirect.php?key=lHDrg1a9AN&source=feedburner is still broken when I try to add it to wallabag or refetch.

My server was just updated: ```Version: 2.3.8```

**Comment by j0k3r** [comment]
It does not exist in the 2.3.8. The fix will be in the 2.4.0 (as the associated milestone says).

**Comment by hrehfeld** [comment]
Ah, sorry, I missed the milestone. Is the master branch stable enough to use?

**Comment by j0k3r** [comment]
Yep it is
