### ISSUE TITLE
[BUG] Download as file: cannot handle unicode characters

### ISSUE THREAD

**Issue by montechristos** [wallabag/wallabag#4339]
I am new to wallabag and so far I am liking the concept.

When using the Android tool, and trying to download the articles as MOBI or EPUB, the filename does not support unicode characters.

Example article to test: https://tvxs.gr/news/istoria/bikingks-polemistes-xoris-ethnos

**Comment by nicosomb** [comment]
Hello @montechristos 
On my side, I can save this article in my wallabag account and export it in epub. 

I close this issue. 
If you still have problem with this feature, feel free to a open an issue with more details to reproduce it.
