### ISSUE TITLE
[feature request] Download all articles as files

### ISSUE THREAD

**Issue by montechristos** [wallabag/wallabag#4340]
In order to backup my collection, I would like to download all of my articles as files instead of doing it one-by-one

**Comment by nicosomb** [comment]
Hello @montechristos 
You need to go on the All pages (yourwallabag.com/all/list) and click on download button to choose the correct format. 

<img width="248" alt="Capture d’écran 2020-04-20 à 17 12 25" src="https://user-images.githubusercontent.com/121870/79767783-202e6d00-832a-11ea-87fa-c995fe6269cc.png">
