### ISSUE TITLE
Disable proxy image

### ISSUE THREAD

**Issue by Yurius38** [wallabag/wallabag#4342]
If I want to see real urls images in article, how disable proxy image function (to display "no ssl pictures")?

**Comment by nicosomb** [comment]
Hello @Yurius38. 

Proxy image is not available in the standard release of wallabag. It's a bundle (https://github.com/nicosomb/wallabag-camo-bundle), enabled on wallabag.it. And this feature won't be disabled on wallabag.it.

**Comment by Kdecherf** [comment]
There is not much activity on this issue, closing it.
