### ISSUE TITLE
Wired articles are incomplete within wallabag

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#4355]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Those Wired articles are incomplete, as many others from the same site.

https://www.wired.com/story/climate-issue/
https://www.wired.com/story/pfas-free-waterproof-apparel/

f43.me parses them correctly and completely.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? docker
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:docker
* OS:docker
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):PostgreSQL

### Steps to reproduce/test case

Add the above mentioned article to wallabag.

**Comment by j0k3r** [comment]
Well if f43.me fetch them properly, it means it'll be fixed in the upcoming 2.4.0 version :)
And I can confirm by trying it on wallabag.it

**Comment by romu70** [comment]
good to read, thanks.
