### ISSUE TITLE
An error occurred when generating the bootstrap file.

### ISSUE THREAD

**Issue by vorkuta** [wallabag/wallabag#4362]
Tried running make install after installing all dependencies etc.

### Issue details

Cannot install wallabag
```
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
PHP Fatal error:  Cannot redeclare mb_str_split() in /var/www/wallabag/html/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-cmd event terminated with an exception

[RuntimeException]
An error occurred when generating the bootstrap file.


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

PHP Fatal error:  Cannot redeclare mb_str_split() in /var/www/wallabag/html/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119
GNUmakefile:14: recipe for target 'install' failed
make: *** [install] Error 255
```

[Paste](https://pastebin.com/ueXEnkte)

### Environment

* wallabag version (or git revision) that exhibits the issue: [Cloned around 10m ago](https://github.com/wallabag/wallabag/commit/976b4bbb115e50feb71accc0e55f1129ac3557e5)
* How did you install wallabag? Via `git clone` or by downloading the package? Git clone
* Last wallabag version that did not exhibit the issue (if applicable): n/a first install
* php version: 7.4
* OS: Ubuntu 18.04
* type of hosting (shared or dedicated): dedi
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Installed dependencies and composer. Ran the makefile. Entered in some params for SQLite when prompted, did not change the remainder. Full output in the paste above.

**Comment by j0k3r** [comment]
See https://github.com/wallabag/wallabag/issues/4271
