### ISSUE TITLE
Article from mediapart gets a title "Mediapart" not their html title

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#4372]
### Issue details
All articles from mediapart have a title Mediapart

### Environment

* wallabag version that exhibits the issue: 2.3.8
* How did you install wallabag? docker install
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: one for the official docker images
* OS: one for the official docker images
* type of hosting (shared or dedicated): self-hosted dedicated
* which storage system you choose at install: MariaDB

### Steps to reproduce/test case

1. setup an authenticated provider mediapart
2. fetch an article from mediapart.fr

result: The title of the article is mediapart https://youtu.be/Rh476PqR7rk

**Comment by j0k3r** [comment]
Have you read http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

**Comment by nicosomb** [comment]
On wallabag.it I can’t reproduce this issue

**Comment by bmillemathias** [comment]
Logs from graby.
Strange for this article I did not get the complete article 

[graby-mediapart.log](https://github.com/wallabag/wallabag/files/4639105/graby-mediapart.log)

**Comment by qwertygc** [comment]
i have the same error (shared host, ftp install etc)

**Comment by doc75** [comment]
I confirm that this issue is still present in wallabag v2.3.8. A workaround has been described in https://github.com/wallabag/wallabag/issues/4196.

**Comment by j0k3r** [comment]
As the workaround is working and f43.me correctly retrieve the title, the fix will be part of the 2.4.0 release.
