### ISSUE TITLE
same article from mediapart can be imported several times

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#4373]
### Issue details

An article from Mediapart (authenticated method) can be imported several times, which is not possible for other public website.

### Environment

* wallabag version that exhibits the issue: 2.3.8
* How did you install wallabag? docker install
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: one for the official docker images
* OS: one for the official docker images
* type of hosting (shared or dedicated): self-hosted dedicated
* which storage system you choose at install: MariaDB

### Steps to reproduce/test case

Import an article from mediapart, it is imported
Import a second time the article from mediapart, it creates an new entry

expected result: doing the standard result, not importing it.
video https://youtu.be/IQLegp1yGjg

**Comment by qwertygc** [comment]
hello,
same error here :-)
