### ISSUE TITLE
wallabag does not fetch from zeit.de - f43 does

### ISSUE THREAD

**Issue by gbeine** [wallabag/wallabag#4380]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

I try to fetch
https://www.zeit.de/gesellschaft/schule/2020-04/rueckkehr-schule-lehrer-coronavirus-lockdown-gewerkschaft-erzieher
and get an error.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? git clone & make install
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version: 7.3.14
* OS: Debian 10.3
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Try to fetch the article.
[graby.log](https://github.com/wallabag/wallabag/files/4583394/graby.log)

**Comment by j0k3r** [comment]
This will be fixed in the 2.4.0

https://github.com/fivefilters/ftr-site-config/pull/773
