### ISSUE TITLE
No SMTP Mailer port?

### ISSUE THREAD

**Issue by voryzen** [wallabag/wallabag#4381]
### Issue details
No option to set the SMTP mailer port.
Environment variables available for host, name, and pass, but not port

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8/latest
* How did you install wallabag? Via `git clone` or by downloading the package?: Docker
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.2
* OS: Debian
* type of hosting (shared or dedicated): dedicated / my own server
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

When requesting user to be registered, no email appears.
Using mailgun, which requires the port to be set, as they use 587, not 25 or 457 (whichever wallabag defaults to, sorry)

**Comment by j0k3r** [comment]
Use `mailer_port` in `parameters.yml` to define whatever SMTP sport you want.

**Comment by voryzen** [comment]
@j0k3r parameters.yml is not accessible if using the docker container..
