### ISSUE TITLE
php request error

### ISSUE THREAD

**Issue by Farenew** [wallabag/wallabag#4391]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Unable to fetch from daily.zhihu.com, error log says:

> [2020-05-10 23:34:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /bundles/fosjsrouting/js/router.js" (from "http://123.57.59.59:6677/quickstart")" at /home/han/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /bundles/fosjsrouting/js/router.js\" (from \"http://123.57.59.59:6677/quickstart\") at /home/han/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:128, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /home/han/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? via git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.2
* OS: Linux Ubuntu 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* type of hosting (shared or dedicated): dedicated 
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

Example site: https://daily.zhihu.com/story/9723629

**Comment by j0k3r** [comment]
The pasted log isn’t related. Have you chercher the doc about fixing site config yourself?

**Comment by Farenew** [comment]
@j0k3r It seems not related with site configuration, for example, I tested NYtimes articles in [f43.me](http://f43.me/feed/test), it worked fine. But I still cannot fetch content, and the error log is just same.

**Comment by j0k3r** [comment]
Do you still have the issue with latest version?

**Comment by Kdecherf** [comment]
There is not much activity on this issue, closing it.
