### ISSUE TITLE
New rendering: Add the fonts

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#4400]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

New rendering improvement.

In the header, add the following line:

<link href="https://fonts.googleapis.com/css?family=Karma|Raleway|Raleway:600|Raleway:600|Raleway:800&amp;display=swap" rel="stylesheet">

Of course, we can also imagine those fonts directly embedded by wallabag.

### Environment

* wallabag version (or git revision) that exhibits the issue:
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

**Comment by nicosomb** [comment]
Will be fixed with https://github.com/wallabag/wallabag/pull/6773
