### ISSUE TITLE
Cannot change settings in web-frontend

### ISSUE THREAD

**Issue by TalmarGrosskotz** [wallabag/wallabag#4404]
### Issue details

I can't change any setting in the configuration via web. The layout is also messed up. Nothing sees clickable.

![grafik](https://user-images.githubusercontent.com/8271443/82153025-4f6ec600-9865-11ea-9068-3cdfb1b909be.png)

### Environment

* 2.3.8
* release package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.4
* OS: Armbian (Bionic Ubuntu 18.04)
* shared
* MySQL/MariaDB

### Steps to reproduce/test case

Stop apache server start apache server 
surf to wallabag/web/app.php/config

Is there any way to make configuration work?

**Comment by j0k3r** [comment]
Can this be the same problem https://github.com/wallabag/wallabag/issues/4294 ?

**Comment by TalmarGrosskotz** [comment]
Yes it really sounds very similar.. sorry for not noticing that when I was searching for this issue. I think we could merge it.
