### ISSUE TITLE
Tagging articles on one domain differently depending on content

### ISSUE THREAD

**Issue by SyntrophicConsortium** [wallabag/wallabag#4405]
This is not a bug report, but rather a help question.

I'd like to know how I can tag different articles on a particular domain differently depending on content. Here's an example: 

I read article from the science journal Nature. Some are research articles, and some are short/flash fiction called Nature Futures. Both are hosted on nature.com, and there is nothing in the page title or url that I can use to distinguish between them. I'd like to tag the research articles as "research", and the fiction as "fiction". There's a few other sites like this too, where they have content under a broad heading (such as science), but the articles are about particular branches of science, and I would like to tag those differently based on scientific area. 

Two questions: Is this possible? Also, does the "content" tagging rule only look in the body of the page? That appears to be the case, but I wanted to confirm. 

Example:
Tagging rule: if « domainName = "nature.com" AND content = "Futures" » then tag as « Fiction »

I would expect that rule to correctly tag the following as "Fiction", but it does not: 
https://www.nature.com/articles/d41586-020-01350-4

Perhaps "content" is only the body, though (while "Futures" appears in a heading at the top of the page)? Creating a rule to match something else such as "research" won't help, as the science fiction articles often contain that word, too.

I'm running an older version of Wallabag, v2.2.3, but from the notes on subsequent releases, I'm not seeing any changes to automatic tagging that might solve my issues (I don't think "notmatches" will help).

**Comment by j0k3r** [comment]
`content = "Futures"` means the whole article content has to be "Futures".
What you might have looking for is `content matches "Futures"` which means, if the string `Futures` is found in the whole article, the rule will match.

Also, did you close your issue because you found the solution, or?
