### ISSUE TITLE
Quotes or <figure> from medium.com are not formatted properly

### ISSUE THREAD

**Issue by thansk** [wallabag/wallabag#4415]
### Issue details

I am not sure if this is a problem of how medium is structured, but quotes or figures get infinitely nested and if a post has 10 quotes in it, the text after the 10th quote is very thin.

### Environment

* wallabag version (or git revision) that exhibits the issue: 9bbafdaa... Release wallabag 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.4.6
* OS: Debian 9
* type of hosting (shared or dedicated): VPS
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL/MariaDB

### Steps to reproduce/test case

You can try to add this url `https://medium.com/@cache_86525/how-covid-19-will-push-for-an-even-more-aggressive-automation-f81d6fc0c4d7` to wallabag.

**Comment by HolgerAusB** [comment]
@thansk try the current siteconfig:
https://github.com/fivefilters/ftr-site-config/blob/master/medium.com.txt
and maybe for subdomains of mdium.com:
https://github.com/fivefilters/ftr-site-config/blob/master/.medium.com.txt

copy/overwrite this to folder `vendor/j0k3r/graby-site-config/` and clear the cache, e.g.:
`sudo -u www-data /path/to/wallabag/bin/console --env=prod cache:clear`

re-fetch content in wallabag

**Comment by Kdecherf** [comment]
@thansk does this issue persist on wallabag 2.6.2?

**Comment by thansk** [comment]
I reported this issue more than 3 years ago, I no longer use wallabag.

**Comment by Kdecherf** [comment]
@thansk noted, closing it then
