### ISSUE TITLE
FR: Provide Option to Disable Registration

### ISSUE THREAD

**Issue by paulcalabro** [wallabag/wallabag#4422]
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

A nice feature would be to provide an option to disable registration for users who do not wish to allow for registration on a publicly accessible host.

### Environment

N/A

### Steps to reproduce/test case

N/A

**Comment by j0k3r** [comment]
Define `fosuser_registration: false` in your `parameters.yml`.

https://doc.wallabag.org/en/admin/parameters.html
