### ISSUE TITLE
cannot fetch the title of daily.zhihu.com

### ISSUE THREAD

**Issue by toyqiu** [wallabag/wallabag#4434]
I add a daily.zhihu.com.txt like below

http_header(user-agent): Mozilla/5.0 (Windows NT
6.1; Win64; x64) AppleWebKit/53

title: //p[@class="DailyHeader-title"]
convert_double_br_tags: yes

test_url: https://daily.zhihu.com/story/9724713

tried different articles,always same titles

**Comment by j0k3r** [comment]
Use `title: //p[contains(@class, 'DailyHeader-title')]` and it'll work!
