### ISSUE TITLE
Blank installation page after fresh install.

### ISSUE THREAD

**Issue by zeeshansayyed** [wallabag/wallabag#4435]
### Issue details
Hello, I did a fresh install of wallabag on Ubuntu. I am facing a complete blank page, with no HTML whatsoever. I read in the documentation, that such a thing can happen when apache doesn't have permission to the wallabag DocumentRoot. I made sure I gave it the right permissions according to the docs, it's still the same. There are no errors in Wallabag/var but the apache error is as follows:

[Wed Jun 10 02:11:01.224881 2020] [php7:notice] [pid 30272] [client 100.100.100.100:50000] PHP Notice:  Trying to access array offset on value of type null in /var/www/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 995

Can you please help me?

**Comment by j0k3r** [comment]
The issue template (which you almost completely omitted) is here for a reason: we need information to understand what could be wrong.
Please fill it.

```

### Environment

* wallabag version (or git revision) that exhibits the issue:
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
```

**Comment by zeeshansayyed** [comment]
### Environment

* wallabag version (or git revision) that exhibits the issue: **2.3.8 - 2019-05-14**
* How did you install wallabag? Via **`git clone`**
* Last wallabag version that did not exhibit the issue (if applicable): First installation
* php version: 7.4.3
* OS: Ubuntu 20.04
* type of hosting (shared or dedicated): Shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

After a fresh git clone, `make install` ran into the following error:

```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
PHP Fatal error:  Cannot redeclare mb_str_split() in /home/shahensha/Software/wallabag/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-cmd event terminated with an exception
```
As was mentioned by a user in #4271 I made the changes in the commit: wallabag/php-mobi@bfe9c18 manually and completed the installation process.

**Comment by zeeshansayyed** [comment]
### Environment

* wallabag version (or git revision) that exhibits the issue: **2.3.8 - 2019-05-14**
* How did you install wallabag? Via **`git clone`**
* Last wallabag version that did not exhibit the issue (if applicable): First installation
* php version: 7.4.3
* OS: Ubuntu 20.04
* type of hosting (shared or dedicated): Shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

After a fresh git clone, `make install` ran into the following error:

```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
PHP Fatal error:  Cannot redeclare mb_str_split() in ~/Software/wallabag/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-cmd event terminated with an exception
```
As was mentioned by a user in #4271 I made the changes in the commit: wallabag/php-mobi@bfe9c18 manually and completed the installation process.

**Comment by j0k3r** [comment]
The reported error is a notice, it can be ignored.
Is there sth inside `var/logs` in your wallabag folder?
What does `php bin/console cache:clear --env=prod` says?

**Comment by zeeshansayyed** [comment]
`cat /var/logs/prod.log` says

`
[2020-06-09 23:51:20] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /index.html"" at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /index.html\" at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:128, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/wallabag/var/cache/prod/appProdProjectContainerUrlMatcher.php:1012)"} []` 

`php bin/console cache:clear --env=prod` says
                                                                                                    
```
  [UnexpectedValueException]                                                                        
  The stream or file "/var/www/wallabag/var/logs/prod.log" could not be opened: failed to open stream: Permission denied                                                                            
```

**Comment by j0k3r** [comment]
https://doc.wallabag.org/en/admin/installation/rightaccess.html

**Comment by zeeshansayyed** [comment]
@j0k3r Thanks. I have actually tried that. As mentioned, I ran the following commands and then restarted the apache server:

```
chown -R www-data:www-data /var/www/wallabag/var
chown -R www-data:www-data /var/www/wallabag/bin
chown -R www-data:www-data /var/www/wallabag/app/config/
chown -R www-data:www-data /var/www/wallabag/vendor/
chown -R www-data:www-data /var/www/wallabag/data/
chown -R www-data:www-data /var/www/wallabag/web
```
Also, I do not have SELinux enabled. 

Can you recommend something else that I can try?

**Comment by j0k3r** [comment]
Then you could run `php bin/console cache:clear --env=prod` it shouldn't display an error

**Comment by zeeshansayyed** [comment]
Thanks a lot. I ran `php bin/console cache:clear --env=prod` with `sudo` and the output is:
` [OK] Cache for the "prod" environment (debug=false) was successfully cleared.`

Then after restarting apache again, I see a barebones login page without any images. If I click on register, it throws the following error.
`Type error: Argument 1 passed to Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory::mergeConstraints() must be an instance of Symfony\Component\Validator\Mapping\ClassMetadata, null given, called in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php on line 93`

var/logs/prod.log now contains:

[2020-06-11 00:51:15] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Failed to create "/var/www/wallabag/var/cache/prod/fosJsRouting": mkdir(): Permission denied." at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php line 103 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Failed to create \"/var/www/wallabag/var/cache/prod/fosJsRouting\": mkdir(): Permission denied. at /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:103)"} []

It still looks like an issue with permissions. I chowned  the wallabag directory recursively once again, but it doesn't solve the problem.

**Comment by j0k3r** [comment]
Don't run `bin/console` with `sudo` it'll change permission of some folder to root and your apache user won't be able to write into them later.
Never seen that error before.
Once permission are properly defined, clear `var/logs/prod.log` and retry to be sure you won't get old logs.

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
