### ISSUE TITLE
wallabag can't handle plain text

### ISSUE THREAD

**Issue by lightonflux** [wallabag/wallabag#444]
wallabag can't handle plain text

E.g. http://ibiblio.org/pub/linux/docs/ldpResearch/ldp-historic/LinuxNews.03A

**Comment by nicosomb** [comment]
I just tried the URL in the 1st post and this one for example (http://www.oracle.com/technetwork/java/readme-2-149793.txt) with wallabag v2. And it works. 

Is this issue still mandatory?

**Comment by tcitworld** [comment]
And I heard someone saved pdfs. So I guess we're good, with MIME Type now stored.

**Comment by nicosomb** [comment]
mimetype is not yet stored. 
About PDF, it's not the document content.

**Comment by tcitworld** [comment]
No, but the thing is : the url is saved, with the title.

**Comment by nicosomb** [comment]
yes :+1: 

about mimetype, I don't know if it's easy. Because you can't get the URL "mimetype", it doesn't exist ...

**Comment by tcitworld** [comment]
Of course you can, it's the Content-Type http header. ;-)

**Comment by nicosomb** [comment]
oh yes, you're right.

**Comment by j0k3r** [comment]
Fixed in graby.
