### ISSUE TITLE
Grey out entries marked as read when all entries from a tag are displayed 

### ISSUE THREAD

**Issue by py-crash** [wallabag/wallabag#4466]
### Issue details

When a tag is selected all articles are displayed. However, there is no easy way to distinguish the already read from those entries which aren't read. There should be a visual cue to which ones were marked as read before.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package?: Installed it building the docker container by cloning the repository and building it. 
* Last wallabag version that did not exhibit the issue (if applicable): Not applicable
* php version: 
* OS: Ubuntu 20.04 Host
* type of hosting (shared or dedicated): dedicated (Raspberry Pi 4)
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):

### Steps to reproduce/test case

When selecting a tag all entries (read or not are displayed). This behaviour is good, however there is no easy way to distinguish which one were already read. For example here only the last one was read

![image](https://user-images.githubusercontent.com/3385947/86784166-9728f700-c037-11ea-8059-5e158b5cb476.png)

One great way to fix this would be to _grey out_ (using opacity: 0.5; in the CSS) for those entries which were marked as read.

**Comment by py-crash** [comment]
Thank you for this improvement

**Comment by brynmrgn** [comment]
I can see why the py-crash requested this, but for me, my archived articles are the important ones - I use unread as my inbox. It's counter-intuitive for my system to have the vast majority of my items showing as faded. This would be better as something the user can configure.
