### ISSUE TITLE
Installation failed in Ubuntu 18.04, Error: PHP Fatal error: Cannot redeclare mb_str_split()

### ISSUE THREAD

**Issue by mohdluqman** [wallabag/wallabag#4469]
### Issue details

Fresh installation of ubuntu 18.04 with nginx, PHP 7.4 and mariadb-server runs into following error during installation

`PHP Fatal error:  Cannot redeclare mb_str_split() in /var/www/DIR_PATH/wallabag/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-cmd event terminated with an exception`

`In ScriptHandler.php line 313:`

`An error occurred when generating the bootstrap file.`

`install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...`

`PHP Fatal error:  Cannot redeclare mb_str_split() in /var/www/html/wbserver/wallabag/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119
GNUmakefile:21: recipe for target 'install' failed
make: *** [install] Error 255`

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.3.8**
* How did you install wallabag? Via `git clone` or by downloading the package? **git clone**
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: **PHP 7.4.7 with NTS (nginx server)**
* OS: **Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-101-generic x86_64)**
* type of hosting (shared or dedicated): **dedicated**
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):  **MySQL/MariaDB**

### Steps to reproduce/test case

First i cloned the script using git clone command and then  cd in the directory. After running `make install`  and providing all necessary values the installation failes to abovementioned message. I have also tried to use `php bin/console cache:clear --env=prod` but it also gave the same abovementioned error.

**Comment by j0k3r** [comment]
See https://github.com/wallabag/wallabag/issues/4271
