### ISSUE TITLE
Error on User Creation on Fresh Install

### ISSUE THREAD

**Issue by iinuwa** [wallabag/wallabag#4473]
### Issue details

When I try to create a new user (through the web UI as the admin user), I am able to load the form page, but when I click submit, I get an error:
```
500:Internal Server Error

Type error: Argument 1 passed to Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory::mergeConstraints() must be an instance of Symfony\Component\Validator\Mapping\ClassMetadata, null given, called in /usr/share/webapps/wallabag/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php on line 93
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? I used the [AUR package](https://aur.archlinux.org/packages/wallabag/), so I guess the 2.3.8 tarball?.
* Last wallabag version that did not exhibit the issue (if applicable): This is my first install, so I don't know.
* php version: 7.4
* OS: Arch Linux (ARM)
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL 12
*
I'm also running with NGINX and php-fpm.

### Steps to reproduce/test case

1. Log in as admin user to the web UI
2. Go to "Users Management"
3. Click "Create New User"
4. Fill out form:
  - Username: "bobsmith"
  - Password: "bobsmith"
  - Email: "bobsmith@example.com

**Comment by j0k3r** [comment]
Everything else is working fine?
I've no problem adding user in using the upcoming 2.4.0

**Comment by iinuwa** [comment]
I think so. Some of the CSS on the config page looks a little weird, but I'm able to pull in an article using the admin user. I'd like to be able to run a couple of different non-admin users though.

**Comment by nsitu** [comment]
I have the same issue here. 
![image](https://user-images.githubusercontent.com/3484202/96476333-0f8c8000-1203-11eb-9717-58cfd4ee7a5b.png)
I can confirg that the CSS does indeed look weird as you said @iinuwa 
Speaking of weird CSS, Of note, I am also experiencing broken styling (or perhaps markup) on the Config page, as described here: https://github.com/wallabag/wallabag/issues/4478 (I am not sure whether this is related but would like to report it either way.
![image](https://user-images.githubusercontent.com/3484202/96476603-6f832680-1203-11eb-97fa-4c44072bc5e6.png)

**Comment by iinuwa** [comment]
This seems to be working in 2.4.2. I'll close it.
