### ISSUE TITLE
Wrong display in wallabag (privacyinternational.org)

### ISSUE THREAD

**Issue by mirenbz** [wallabag/wallabag#4497]
### Issue details

In trying to add a page (https://privacyinternational.org/news-analysis/3709/schools-and-covid-19), it gives the "can't retrieve contents" error. Parsed just fine in f43.me though.

### Environment

* wallabag version (or git revision) that exhibits the issue: wallabag.it web version and Android app 2.4.0-beta.5(224), but happened with the Play Store version as well
* How did you install wallabag? Via `git clone` or by downloading the pack: Hosted so IDK, and downloaded package for Android
* Last wallabag version that did not exhibit the issue (if applicable): I don't know
* php version: -
* OS: -
* type of hosting (shared or dedicated): wallabag.it
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): -

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

Tried a few times to add https://privacyinternational.org/news-analysis/3709/schools-and-covid-19 to Wallabag using both the browser and the Android app (latest beta from Github), doesn't parse. Testing with f43.me works OK though.

**Comment by Kdecherf** [comment]
Fetched content looks good on current master, closing this issue.
