### ISSUE TITLE
Mysql 8 authentication issues during make install

### ISSUE THREAD

**Issue by SyntrophicConsortium** [wallabag/wallabag#4512]
### Issue details

During install for dedicated webserver (from git repo), make install fails with this error:
`Database connection      ERROR!   Can't connect to the database: An exception occured in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client`

### Environment

* wallabag version (or git revision) that exhibits the issue:  **latest git revision** 
* How did you install wallabag? Via `git clone` or by downloading the package? **git clone**
* Last wallabag version that did not exhibit the issue (if applicable): **n/a, new install on new server**
* php version: **7.3**
* OS: **Ubuntu 20.04.1**
* type of hosting (shared or dedicated): **dedicated**
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): **MySQL**

### Steps to reproduce/test case

Clone git repository, cd to wallabag
run make install 

I can't recall if I pre-populated parameters.yml or used the prompts, but it doesn't matter, result should be the same. I confirmed the db information is correct. I can login to mysql with the user and password specified.

I last used Wallabag 2.2.3, I think, on a server that is now out of commission. That was running mysql 5.7.2 or so, so mysql 8 is quite new to me. Is it too new for Wallabag as well? I've read the authentication methods have changed from v5 to 8. v8 now uses `caching_sha2_password` plugin rather than `mysql_native_password`. I have tried changing 
`default-authentication-plugin` to `mysql_native_password` in mysql configuration, but I am still getting the same error during make install. I have confirmed the setting took effect by executing `show variables;` in mysql command line.

I also noticed that after I run `make install`, the single-quotes around my password in `parameters.yml` are being removed. This seems like it would cause an issue maybe, unless that is no longer needed? My password has some valid special characters (an "!").

Full error output during `make install`:

```
Step 1 of 4: Checking system requirements.
------------------------------------------

 ------------------------ -------- -------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Checked                  Status   Recommendation                                                                                                                                          
 ------------------------ -------- -------------------------------------------------------------------------------------------------------------------------------------------------------- 
  PDO Driver (pdo_mysql)   OK!                                                                                                                                                              
  Database connection      ERROR!   Can't connect to the database: An exception occured in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client  
  Database version         OK!                                                                                                                                                              
  curl_exec                OK!                                                                                                                                                              
  curl_multi_init          OK!                                                                                                                                                              
 ------------------------ -------- -------------------------------------------------------------------------------------------------------------------------------------------------------- 

10:18:11 ERROR     [console] Error thrown while running command "wallabag:install --env=prod". Message: "Some system requirements are not fulfilled. Please check output messages and fix them." ["error" => RuntimeException { …},"command" => "wallabag:install --env=prod","message" => "Some system requirements are not fulfilled. Please check output messages and fix them."] []

                                                                                          
  [RuntimeException]                                                                      
  Some system requirements are not fulfilled. Please check output messages and fix them.
```

**Comment by SyntrophicConsortium** [comment]
I was informed in chat that Wallabag hasn't been tested with MySQL 8 yet. I'm going to say it doesn't work as it is. Unless someone has a suggestion, I'll see about reverting to an older version of MySQL.

**Comment by SyntrophicConsortium** [comment]
Closing this. I moved to MariaDB, so this is no longer an issue. I have new problems though, will open up another issue.

**Comment by j0k3r** [comment]
As an old follow up, see https://github.com/wallabag/wallabag/pull/5729 it's a bug in PHP < 7.3, just use PHP >= 7.4 and it'll be fine.
