### ISSUE TITLE
Many Grammar Police on Quickstart

### ISSUE THREAD

**Issue by chris2fr** [wallabag/wallabag#4535]
Hi,

On https://app.wallabag.it/quickstart

One reads "There are so much features in wallabag. Don't hesitate to read the manual to know them and to learn how to use them."

One should read "There are so many features in wallabag. Don't hesitate to read the manual to know them and to learn how to use them.""

**Comment by j0k3r** [comment]
All translated string are now centralized on Weblate https://hosted.weblate.org/projects/wallabag/
Feel free to update them and they will be automatically updated on the main repo 👍
