### ISSUE TITLE
Import error using postgres

### ISSUE THREAD

**Issue by papylhomme** [wallabag/wallabag#4547]
### Issue details

I'm trying to migrate from mysql to postgres. I've exported all the articles with the json format, and I'm trying to import them back on a new instance using `php bin/console wallabag:import --env=prod -v user articles.json`. It fails with

    [PDOException (23502)]                                                                                                                                                                      
    SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "is_starred" violates not-null constraint

In the debug log of the sql server I can see that the `is_starred` value is indeed set to `null`, but the JSON file contains `"is_starred": 0`

### Environment

* wallabag 2.3.8
* Installation from sources
* PHP 7.3.14
* OS: alpine: 3.10.0
* Self hosted using docker

### Steps to reproduce/test case

Install a fresh wallabag instance using PostgreSQL, try to import articles exported as JSON format

**Comment by j0k3r** [comment]
Is there a more detail stack trace of that error or only the line you put?
Could you share the entry in your JSON which contains the failing line?

**Comment by papylhomme** [comment]
Sure, more information below, but I don't have any stacktrace from PHP.

It affects every records (I tried inserting only one of them and the error is still present). Somehow every `0` is converted to `null`

DB log:

    db_1        | 2020-08-31 16:31:40.878 UTC [51] ERROR:  null value in column "is_starred" violates not-null constraint
    db_1        | 2020-08-31 16:31:40.878 UTC [51] DETAIL:  Failing row contains (63, 1, Table of Contents | Learn You Some Erlang for Great Good!, https://learnyousomeerlang.com/content, f, null, <p>contenthere</p>, 2020-08-31 16:31:40, 2020-08-31 16:31:40, null, null, 0, learnyousomeerlang.com, null, null, null, null, N;, N;, null, null).
    db_1        | 2020-08-31 16:31:40.878 UTC [51] STATEMENT:  INSERT INTO "wallabag_entry" (id, uid, title, url, is_archived, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, origin_url, user_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)

Command output (shows parameters values):

    [Doctrine\DBAL\Exception\NotNullConstraintViolationException]                                                                                                                               
    An exception occurred while executing 'INSERT INTO "wallabag_entry" (id, uid, title, url, is_archived, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, origin_url, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [63, null, "Table of Contents | Learn You Some Erlang for Great Good!", "https:\/\/learnyousomeerlang.com\/content", 0, null, "<p>contenthere<\/p>", "2020-08-31 16:31:40", "2020-08-31 16:31:40", null, "N;", null, null, null, 0, "learnyousomeerlang.com", null, null, "N;", null, 1]:                                                                                      
                                                                                                                                                                                              
    SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "is_starred" violates not-null constraint                                                                               
    DETAIL:  Failing row contains (63, 1, Table of Contents | Learn You Some Erlang for Great Good!, https://learnyousomeerlang.com/content, f, null, <p>contenthere</p>, 2020-08-31 16:31:40, 2020-08-31 16:31:40, null, null, 0, learnyousomeerlang.com, null, null, null, null, N;, N;, null, null).

Example file:

    [
       {
          "annotations" : [],
          "content" : "<p>CONTENT HERE</p>",
          "created_at" : "2019-07-23T19:52:35+0000",
          "domain_name" : "learnyousomeerlang.com",
          "http_status" : "200",
          "id" : 43,
          "is_archived" : 1,
          "is_public" : false,
          "is_starred" : 0,
          "language" : "en",
          "mimetype" : "text/html",
          "reading_time" : 0,
          "tags" : [
             "info",
             "erlang"
          ],
          "title" : "Table of Contents | Learn You Some Erlang for Great Good!",
          "updated_at" : "2019-07-23T20:07:23+0000",
          "url" : "https://learnyousomeerlang.com/content"
       }
    ]

**Comment by j0k3r** [comment]
What is weird, is the `is_starred` field should be casted as boolean and should to be null

https://github.com/wallabag/wallabag/blob/2.3.8/src/Wallabag/ImportBundle/Import/WallabagV2Import.php#L40

Even if the field is `null` it should then be converted to `false` https://3v4l.org/EoLa1

**Comment by papylhomme** [comment]
OK my bad, I try fiddling with the code a bit, and the import was using `WallbagV1Import` (which does not cast the fields). Problem resolved using the command line option `--importer=v2`

**Comment by j0k3r** [comment]
Great!
