### ISSUE TITLE
 import process stops halfway (Wallabag2 to Wallabag2)

### ISSUE THREAD

**Issue by petesimonic** [wallabag/wallabag#4610]
### Issue details

User tried to move to Ynh-Wallabag from another instance. He have his 744 entries (to the moment) in *All articles* export file. But Ynh-Wallabag imports only top 400 (tried couple times). The export file does look complete (and takes 44 MB). The import process doesn’t really finish but more like ends with a blank screen (it was given around 15 minutes to complete just in case). Then you reload the page and find partial import.

### Environment

* wallabag version (or git revision) that exhibits the issue:
from `2.4.0-dev` to `2.3.8`
* How did you install wallabag? Via `git clone` or by downloading the package?
as Yunohost app
* Last wallabag version that did not exhibit the issue (if applicable):
n/a
* php version:
Powered by YunoHost 3.8.5.9 (stable). Can't say which version it use for this app.
* OS:
Debian.
* type of hosting (shared or dedicated):
VPS
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):
Yunohost app

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

*Please indicate where the export file (download link) can be attached.*

**Comment by j0k3r** [comment]
Isn't an issue about YunoHost instead?
What can be do?
Does the import system on YunoHost is using queue (redis or rabbit)?

**Comment by petesimonic** [comment]
It would be wonderful to know where the issue happens exactly. Unfortunately, no idea how to check it right.

My reasoning was that Ynh basically provide container management for the app to run, and such problems could be something you're aware of. Or know a workaround; maybe somehow export in a few files and import in smaller batches.

Sorry, if it was created in wrong place. Is it better to ask Ynh community about the issue?

**Comment by petesimonic** [comment]
Is it possible Wallabag can't process an article and that's the reason import fail? User added some entries since the issue was opened, and retried import. The number of imported articles looks the same as the number of entries since previous import attempt.

**Comment by petesimonic** [comment]
Easiest workaround to apply is to slice your export file with `jq`. https://www.howtogeek.com/529219/how-to-parse-json-files-on-the-linux-command-line-with-jq/
