### ISSUE TITLE
when is release 2.4 ?

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#4621]
Hi,
I use a shared hosting. My hoster have upgrade PHP to 7.4 and all is broken... I would like when Wallabag 2.4 will be release.

Regards

**Comment by j0k3r** [comment]
I hope to find some time during Octobre to push the release.
In the meantime, you can check the current master (which is pretty stable) on your shared hosting to see if everything is ok

**Comment by qwertygc** [comment]
OK, thank for you anwser. I download, unzip and send files on the FTP, or i have a particular manipulation for installation (i usually package when i install wallabag)

**Comment by qwertygc** [comment]
OK, with [this script](https://github.com/wallabag/wallabag/blob/master/scripts/release.sh) i have generate the new version. In my database, i have [execute this](https://doc.wallabag.org/en/admin/query-upgrade-23-24.html).  I have adapted my app/config/parameters.yml with goods information.

**Comment by j0k3r** [comment]
Let us know if you got some issues 👍

**Comment by qwertygc** [comment]
I have wrong translation

![image](https://user-images.githubusercontent.com/4261986/95389582-54a3de80-08f4-11eb-8dd8-f457697fcddb.png)
