### ISSUE TITLE
icons blocked/not loading when font is blocked

### ISSUE THREAD

**Issue by autrui** [wallabag/wallabag#465]
Using v1.5.0
Could you maybe separate the icons (logout, favorites, marked as read etc.) from the font? I'm using Firefox (27) in a restricted security environment where post-loading of & the use of fonts other than the 3 three defined in the Firefox settings menu is not allowed.

Since you chose to make the icons part of the font they won't show. If you could separate them from the font I might not get the nice font experience as others but at least I'll get the icons. Without icons the web GUI is not hard to impossible to use.

Thank you.

**Comment by tcitworld** [comment]
No news, so closing time.
