### ISSUE TITLE
unable to export

### ISSUE THREAD

**Issue by js-d-coder** [wallabag/wallabag#4663]
### Issue details

I first tried to update then it failed with this error:

```
PHP Fatal error:  Cannot redeclare mb_str_split() in /var/www/wlbg/vendor/wallabag/php-mobi/MOBIClass/RecordFactory.php on line 119
```

then I manually deleted that function declaration and tried to install again.

Now I am trying to get the hell out of this service so I am trying to export articles but I am getting some PHP error. (Not a PHP expert)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? downloading the package
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: PHP 7.4.3 
* OS: Ubuntu 20
* type of hosting (shared or dedicated): dedicated VPS
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

```
sudo -u www-data bin/console wallabag:export

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in /var/www/wlbg/app/AppKernel.php:49
Stack trace:
#0 /var/www/wlbg/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(448): AppKernel->registerBundles()
#1 /var/www/wlbg/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/wlbg/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(60): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/wlbg/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/wlbg/bin/console(29): Symfony\Component\Console\Application->run(Object in /var/www/wlbg/app/AppKernel.php on line 49
```

**Comment by j0k3r** [comment]
Trying that:
```
sudo -u www-data bin/console wallabag:export --env=prod
```
Specifying the environment will avoid the error you get.

Also the 2.3.8 is not fully compatible with PHP 7.4.
The upcoming 2.4.0 will be.

**Comment by js-d-coder** [comment]
@j0k3r Hey, thanks a lot for your response. Currently, I am stuck because my instance is not working. I don't want to use Pocket (I am using that temporarily)
Apparently, Ubuntu 20 has upgraded to PHP 7.4. Currently I only want it to save URL and I open the original URL in browser i.e. I only use it store URL - don't need any other feature. Is there any way I can get 2.3.x to work with PHP 7.4 until Wallabag has full support? I am okay with disabling some features to make the instance usable.
Please let me know the solution. 
Thanks!

**Comment by j0k3r** [comment]
Check https://github.com/wallabag/wallabag/issues/4271
