### ISSUE TITLE
Erorr during installationf rom git

### ISSUE THREAD

**Issue by vojtapolasek** [wallabag/wallabag#4680]
### Issue details

I can't install wallabag from git.

### Environment

* wallabag version (or git revision) that exhibits the issue: latest master
* How did you install wallabag? Via `git clone` or by downloading the package? - git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.4
* OS: Ubuntu 20.04.1
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Posgresql

### Steps to reproduce/test case

git clone https://github.com/wallabag/wallabag.git
chown -R www-data:www-data wallabag
cd wallabag
make install

logs attached
[wallabag.log](https://github.com/wallabag/wallabag/files/5433553/wallabag.log)

**Comment by j0k3r** [comment]
If you want to install the master, you shouldn't use the `make install` because that command will retrieve the latest tag of wallabag: 2.3.8 (as you can see in the first line of your log) instead of using the freshly cloned master.

You should instead run command manually:
```
SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
php bin/console wallabag:install --env=prod
```

**Comment by vojtapolasek** [comment]
OK thanks. Insatlling latest master was not even my goal, I am fine with the latest stable tag. Still, how to fix this error?

**Comment by j0k3r** [comment]
Using the search engine here with the error will point you to that issue: https://github.com/wallabag/wallabag/issues/4271

**Comment by georgedorn** [comment]
> 
> 
> If you want to install the master, you shouldn't use the `make install` because that command will retrieve the latest tag of wallabag: 2.3.8 (as you can see in the first line of your log) instead of using the freshly cloned master.
> 
> You should instead run command manually:
> 
> ```
> SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
> php bin/console wallabag:install --env=prod
> ```

For an existing install, you want to run `php bin/console doctrine:migrations:migrate --env=prod` between those two, or the schema changes won't be applied and you'll get SQL errors.  Unless resetting the database or schema during `wallabag:install` does this non-destructively (I wasn't going to try it and see.)

**Comment by vojtapolasek** [comment]
Hm, In the end I deleted the installation, leaving databse in tact and performed installation again. I had to use PHP 7.3.
