### ISSUE TITLE
Email use in Wallabag

### ISSUE THREAD

**Issue by BeecherNetworks** [wallabag/wallabag#4701]
Again sorry for off-topic post, the forums are offline. I'd just like to know what Wallabag uses email for, is it just for sharing via email or does it send reports, or something else? I'm basically wondering if there's a need to configure it. Running via Docker.

**Comment by j0k3r** [comment]
There is no report. We use email for sharing and also for send a confirm email to validate account.
You can manually validate an account in the database. So you might not need an email server.

**Comment by BeecherNetworks** [comment]
Great, thanks!
