### ISSUE TITLE
Error 500 when adding an article

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#4764]
### Issue details

Each time I add the page https://danvops.fr/un-vrai-bastion-opensource-qui-a-tout-pour-plaire-propulse-par-ovh/
I get a error 500, due to a mysql error. I never had such problem.

```
An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, is_archived, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, origin_url, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "Un vrai bastion OpenSource qui a 
....
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x99\x82</...' for column `wlb_db`.`wallabag_entry`.`content` at row 1
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? docker
* Last wallabag version that did not exhibit the issue (if applicable): don't know
* php version: the one provided in docker
* OS: N/A
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Mariadb (official image)

### Steps to reproduce/test case
Go to wallabag website
paste the url
Bam

**Comment by bmillemathias** [comment]
Confirmed in version `2.4.0`

**Comment by j0k3r** [comment]
What's the `database_charset` defined value in `app/config/parameters.yml`?

**Comment by bmillemathias** [comment]
> What's the `database_charset` defined value in `app/config/parameters.yml`?

`utf-8`

**Comment by j0k3r** [comment]
Use `utf8mb4` instead.
It should been that value since 2.2.0 (as utf8 as issue with emoji for example).

**Comment by bmillemathias** [comment]
> Use `utf8mb4` instead.
> It should been that value since 2.2.0 (as utf8 as issue with emoji for example).

I recreated twice my installation and each time it ends up with `database_charset: utf8` in the file `parameters.yml`.
I can't see anywhere where I could have set that, where could I look ? (or could it be a bug ?)

**Comment by j0k3r** [comment]
It's weird. The default value is `utf8mb4`. So if you do nothing, it should be that value.

Anyway, you are allowed to manually edit that file. Clearing the cache right after was a good idea.
Does that fix your issue?

**Comment by bmillemathias** [comment]
> Does that fix your issue?

yes,

**Comment by j0k3r** [comment]
Great!
