### ISSUE TITLE
Error 500 - User Creation fresh Instal

### ISSUE THREAD

**Issue by GivouDev** [wallabag/wallabag#4772]
Issue details

When I try to create a new user(web ui as admin and register page), In the admin Panel the pages loades and the errors comes as you press send, the register page instandly gives me the error

500:Internal Server Error

Type error: Argument 1 passed to Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory::mergeConstraints() must be an instance of Symfony\Component\Validator\Mapping\ClassMetadata, null given, called in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php on line 93

Environment

    wallabag version (or git revision) that exhibits the issue: 2.3.8
    How did you install wallabag? git clone and then make install...and because of an error i used this commit: https://github.com/wallabag/php-mobi/commit/bfe9c18d038e5ca24664cfdab107a645ac57c9b5
    Last wallabag version that did not exhibit the issue (if applicable): This is my first install, so I don't know.
    php version: 7.4.12
    OS: Debian 9.9 Stretch (using this server since 3 years and yeah debian v9)
    type of hosting (shared or dedicated): dedicated server
    which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL(on different Server, VServer)

Running with Apache2
Steps to reproduce/test case

    Log in as admin user to the web UI
    Goto the User Managent and try to create user

   Or directly go to the register page on the login page.

--- Maybe a fix? ---
From the php file /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php on line 93 i just removed the code in line 93 xD

And now it works....but i think thats not the best solution? 
I removed this: $this->mergeConstraints($metadata);
What does this do?

**Comment by j0k3r** [comment]
Could you test using the master instead of the 2.3.8 tag?

**Comment by GivouDev** [comment]
> 
> 
> Could you test using the master instead of the 2.3.8 tag?

sure

**Comment by GivouDev** [comment]
> 
> 
> Could you test using the master instead of the 2.3.8 tag?

ran git pull origin master
Now i have a blank white page

**Comment by j0k3r** [comment]
`SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist`

**Comment by GivouDev** [comment]
> 
> 
> `SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist`

I mean i installed it with https://github.com/wallabag/wallabag.git
Shouldnt i not already be on the master then?

**Comment by GivouDev** [comment]
So, now ive put the code back in the code on line 93....
And then i run flushed the cache with php bin/console cache:clear --env=prod and run SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist....then i gave www-data access right to the wallabag directory with chown -R www-data:www-data /var/www/wallabag

And now it runs perferctly.
