### ISSUE TITLE
NextInpact / Inpact Hardware v7 content

### ISSUE THREAD

**Issue by X-dark** [wallabag/wallabag#4773]
### Issue details

https://www.nextinpact.com/ and https://www.inpact-hardware.com/ subscribers content is no longer loading since  the v7 of their website deployed last summer. Only "public" content is loaded.

### Environment

* wallabag version: 2.3.8
* How did you install wallabag? AUR packages
* php version: 7.4.13
* OS: Arch Linux
* type of hosting: dedicated
* which storage system you choose at install: MariaDB

### Steps to reproduce/test case

Just did the test with a recent article: https://www.nextinpact.com/article/44132/lhistoire-windows-10

Site credential is configured for host "nextinpact.com"

**Comment by Kdecherf** [comment]
Yeah, I took a look on it last week.
The fix will be quite complicated and may require some work on the authentication system and the SiteConfig builder.

Several notes:
* The login expects a JSON object, as of today we only submit form-encoded body.
* The JSON objects contains mandatory semi-dynamic fields to limit automated actions, `ei`, `pi` and `tk`; the first two being random numbers between 0 and the length of, respectively, the login name and the password. `tk` being the concat of login[ei] and password[pi]. For example, with the login `toto` and password `foobar` a valid object could be `{"ei":0,"pi":3,"tk":"tb"`
* The server returns a JWT token that must be forwarded as a cookie entry with the key `__crossAuth`.

**Comment by Pofilo** [comment]
A solution for this website but that could work with all capricious websites was discussed here: https://github.com/wallabag/wallabag/issues/1525

**Comment by Pofilo** [comment]
We can maybe close this issue with https://github.com/wallabag/wallabagger/pull/300.

**Comment by nicosomb** [comment]
@Pofilo did you try on NXi website?

**Comment by Pofilo** [comment]
@nicosomb yes, and it works like a charm :)
