### ISSUE TITLE
not properly displaying buttons/menus

### ISSUE THREAD

**Issue by completion** [wallabag/wallabag#4804]
### Issue details

On fresh install, wallabag is not properly displaying buttons/menus. 
[Picture of quickstart page](https://user-images.githubusercontent.com/11341916/101617268-ea272180-39bc-11eb-9b4d-899738fd4387.png). There are no errors in nginx's logs or wallabag's prod.log

### Environment

* git revision: 0bbe55e478993f5df623368d38a2581f1bbd9483
* Installed via git clone
* php version: 7.4
* OS: Ubuntu 20.04
* dedicated
* PostgreSQL

### Steps to reproduce/test case

I just followed the install instructions. The one deviation was I had to make these [changes](https://github.com/wallabag/php-mobi/commit/bfe9c18d038e5ca24664cfdab107a645ac57c9b5) to fix #4271 as I am running php 7.4.

**Comment by j0k3r** [comment]
You can revert the change you made, as you had fetched the master, the fix is already included.
Is there error in the console of your browser? What about the network tab? Is there other stuff broken?

**Comment by completion** [comment]
Yes, lots of errors in the console. All of the fonts are being blocked by CORS policy. 'Access-Control-Allow-Origin' header is not present.
I think this was caused because I was access wallabag using the servers hostname while wallabag was expecting me to use the domain I configured. I am connecting two nginx instances together. Once I access wallabag from the nginx instance connected to the domain, everything is fine.
Thank you for your help!

**Comment by completion** [comment]
Yes, lots of errors in the console. All of the fonts are being blocked by CORS policy. 'Access-Control-Allow-Origin' header is not present.
I think this was caused because I was access wallabag using the servers hostname while wallabag was expecting me to use the domain I configured. I am connecting two nginx instances together. Once I access wallabag from the nginx instance connected to the domain, everything is fine.
Thank you for your help!
