### ISSUE TITLE
Problems on fresh install 2.4.0 on shared hosting

### ISSUE THREAD

**Issue by Meuschke23** [wallabag/wallabag#4809]
### Issue details

The download: https://static.wallabag.org/releases/wallabag-release-2.4.0.tar.gz doesn't contain the vendor directory.
That leads to 

> Fatal error: require(): Failed opening required '/*****/Wallabag/bin/../vendor/autoload.php'... 

if i call 

`php bin/console wallabag:install -e=prod` 

like recommended on https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.4.0**
* How did you install wallabag? Via `git clone` or by downloading the package?: **Package**
* Last wallabag version that did not exhibit the issue (if applicable):**2.3.8**
* php version:**7.4**
* OS:**debian**
* type of hosting (shared or dedicated):**shared hosting**
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):**MySQL**

**Comment by j0k3r** [comment]
Try `php bin/console wallabag:install --env=prod`

**Comment by Meuschke23** [comment]
hi,
thx for the help, but that gives me the same error, because autoload.php is missing in https://static.wallabag.org/releases/wallabag-release-2.4.0.tar.gz

**Comment by Meuschke23** [comment]
Update: in https://github.com/wallabag/wallabag/releases/download/2.4.0/wallabag-2.4.0.tar.gz the vendor directory exists. That worked for me.

**Comment by j0k3r** [comment]
It should be the same archive 🤔

**Comment by di72nn** [comment]
The archives are still different, why is this closed?

**Comment by j0k3r** [comment]
Yes they are different, the one on static is the repo without deps. @nicosomb is going to fix that

**Comment by nicosomb** [comment]
Fixed.
