### ISSUE TITLE
Dark mode not remembered

### ISSUE THREAD

**Issue by kmlucy** [wallabag/wallabag#4812]
### Issue details

I just updated to 2.4.0, and am trying to use dark mode. If I click on dark mode it switches successfully, but when I reload the page, or close and navigate back, I get a flash of dark as it loads, then it switches to light. I've tried clearing cache/cookies with no change. 

There is a cookie with the name `theme` and content `dark` set.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.4.0
* How did you install wallabag? Docker image
* Last wallabag version that did not exhibit the issue (if applicable): N/A
* php version: Docker
* OS: Docker (Debian host)
* type of hosting (shared or dedicated): Self hosted
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Update to 2.4.0, clear cache/cookies, switch to dark mode

**Comment by Simounet** [comment]
Hi there,
I'm sorry to ear that. Could you give to me your browser's name and version please?

**Comment by kmlucy** [comment]
This is on Chrome 86.0.4240.199.

**Comment by Simounet** [comment]
Do you have any extension that can be involved in this issue? Do you have any javascript error? Can you try it on a fresh profile or another browser just to be sure please?

**Comment by kmlucy** [comment]
It did appear to be something with Chrome, but I'm not actually sure what. I deactivated all extensions and still had the issue. It did work in incognito and a fresh profile though, so I cleared all cache and cookies, not just for the Wallabag URL. That seems to have fixed the issue, though I have no idea why.

**Comment by Meuschke23** [comment]
i have the same problem on firefox 83.0. The cookie theme: dark is set, but the theme switch to light. the cookie stays the same. It looks like an override (short flickering). No errors in console.

**Comment by nicosomb** [comment]
@Simounet I upgraded wallabag.it and the bug is there.

**Comment by Simounet** [comment]
Can you be more specific please? How can I reproduce it? Where your logged in? I just tried it right now and it's working as expected.

**Comment by nicosomb** [comment]
When I enable the dark theme, it's ok. 
If I click to display an other page, I see firstly the dark theme, then the white one. It flashes very quickly.

**Comment by Simounet** [comment]
Can you see any JS error in the console? What's your cookies' state?

**Comment by nicosomb** [comment]
`theme` = dark and no js error

**Comment by nicosomb** [comment]
I have the same issue with Chrome and Firefox.

**Comment by Simounet** [comment]
Were you logged in in both browsers? Is private browsing fixing the issue?

**Comment by nicosomb** [comment]
The fix has been deployed on app.wallabag.it and it works :tada:
