### ISSUE TITLE
QR code for 2FA OTP not rendering correctly in *fox

### ISSUE THREAD

**Issue by noplanman** [wallabag/wallabag#4813]
### Issue details

QR code for 2FA OTP isn't rendering and **it would be great to show the secret to allow manual input**, where a QR code can't be scanned / isn't possible.

I've tried installing `imagemagick` and `php7-pecl-imagick` packages in case it had to do with that.

After some more testing, it seems to be some issue with *fox browsers, as Opera works fine 🤔 

### Environment

* Browser: Waterfox (G3.0.1) or Firefox (83.0)
* wallabag version (or git revision) that exhibits the issue: 2.4.0
* How did you install wallabag? Via `git clone` or by downloading the package? Docker
* Last wallabag version that did not exhibit the issue (if applicable): -
* php version: 7.3
* OS: Alpine (from Docker)
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

Go to `https://<my.walla.bag>/config/otp/app` and see this as a result:
![qr-code-not-rendering](https://user-images.githubusercontent.com/9423417/101833088-5e360680-3b30-11eb-9eee-e26f155d1b70.png)

**Comment by zertrin** [comment]
I also concur to not only fix any QR code display bug, but also the need to be able to get the secret in text form easily.

This is needed for example when using a dedicated password manager to back-up TOTP secrets.
(To have a fallback in case the phone breaks and you don't have access to the TOTP app on the phone).

**Comment by Kdecherf** [comment]
@zertrin I referenced your comment in a new and separate issue

**Comment by Kdecherf** [comment]
@noplanman I'm currently unable to reproduce this issue on Firefox 83

**Comment by noplanman** [comment]
Hmm, strange. It's very reproducable on my machine, with every page refresh I get a new "code" (or image as above) with new codes.

Since it works on Opera, it's clearly not Wallabag issue, but something browser-related, so i'll close off here 🤷‍♂️

**Comment by ssokhey** [comment]
Anybody facing the same issue on *fox browser;

In my case, it was due to `privacy.resistFingerprinting=true` under `about:config`

I toggled it back to `false`, refreshed the page, QR code appeared.

So, if someone is using hardened version of firefox, this problem will persist.

**Comment by noplanman** [comment]
@ssokhey Thanks for that, works perfectly after disabling the fingerprint resistance.

Has been driving me nuts, but now I can actually live with it, knowing what it is 🙏

**Comment by Kdecherf** [comment]
For future reference, here is a meta bug regarding breakages with fingerprinting resistance on Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1507517
