### ISSUE TITLE
Delete unused images

### ISSUE THREAD

**Issue by webracer999** [wallabag/wallabag#4827]
### Issue details
My wallabag instance is now a few years old. The complete wallabag directory has a size of 2 GB (I already cleared var/logs/prod.log, which had over 250 MB).
The directory web/assets/images uses 1,7 GB. There are 18630 files in it. As today I have 225 articles (incl. archived) in wallabag. I often delete saved articles, so I think there are still images from deleted articles there.
How can I do house keeping for the images directory?

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.4.0
* How did you install wallabag? Via `git clone` or by downloading the package? Think I used package, but "git status" prints "HEAD detached at 2.4.0". Upgrade from 2.3 to 2.4 done with "make update"
* php version: 7.4.3
* OS: Ubuntu 20.04.1 LTS
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
Images saved locally should be removed when you remove an entry
https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Event/Subscriber/DownloadImagesSubscriber.php#L68-L80

Can you give a try and test if there is a bug when removing images?

**Comment by Kdecherf** [comment]
There was a bug in the event dispatcher on versions prior to 2.4.0: the event was not dispatched when removing an entry through the API (_like from the Android app_).

I worked on a cleanup on my instance several months ago, I'll try to find my notes with the script helper I used.

**Comment by j0k3r** [comment]
What about a task that:
- retrieve all entries id
- generate the hash for all of them (using crc32)
- calculate existing (and valid) path for images
- remove all other path which doesn't match built one

**Comment by Kdecherf** [comment]
Having a housekeeping command could be useful, yeah

**Comment by webracer999** [comment]
Oh yes, I'm using the android app quite often and used wallabag version < 2.40 long time (upgraded two days ago to 2.40). So this could be the root cause of my big images directory.

A housekeeping command would be very nice. :)

**Comment by j0k3r** [comment]
@webracer999 is there any chance you can try that command ☝️ `php bin/console wallabag:clean-downloaded-images --env=prod`?
Backup your images folder because, just in case.

Just apply changes except for `phpstan.neon`.

**Comment by webracer999** [comment]
Looks great!
"[OK] Finished cleaning. 14810 deleted images"

Images directory reduced from 1.7G to 206M. I did some random samples and found no missing image.
Thank you very much! :thumbsup:

**Comment by j0k3r** [comment]
Wow impressive!
