### ISSUE TITLE
support end-to-end encryption using etebase

### ISSUE THREAD

**Issue by haadr** [wallabag/wallabag#4830]
### Issue details

Support end-to-end encryption to make paid/managed wallabag hosting more attractive and protect the users privacy.

> Etebase makes building end-to-end encrypted applications easy by taking care of the encryption and its related challenges. 

[Etebase](https://docs.etebase.com/protocol-specs/introduction/) is the underlying protocol/library of [etesync](https://www.etesync.com/), a "secure, End-to-End encrypted, and privacy respecting sync for contacts, calendars, tasks and notes with clients available on all major platforms". It's moving at a great pace and support has just landed in KDE and GNOME, as well as receiving a bunch of new language bindings (see [here](https://docs.etebase.com/installation)).

Etebase is the library which let's you implement your own e2ee applications using the same protocol. _It would be great if wallabag would implement support for syncing to servers via etebase, making it much more attractive to use wallabag with paid hosting where you don't necessarily trust the server._ 

I've had a chat with the author of etesync (TAsn at #etesync on irc.freenode.net or #EteSync:matrix.org) who says he'd be happy to assist and who thinks it would be relatively simple to add support for wallabag.

Thank you for wallabag!

**Comment by Kdecherf** [comment]
Duplicates #3339

**Comment by Kdecherf** [comment]
@haadr I moved your comment in #3339, also please check my comment on the topic: https://github.com/wallabag/wallabag/issues/3339#issuecomment-451662041
