### ISSUE TITLE
Installatron current version is 1.9.0

### ISSUE THREAD

**Issue by iSimorgh** [wallabag/wallabag#4831]
Hi all,

I was wondering if I should post this issue here or contact Installatron. The version on [Installatron's website; https://installatron.com/wallabag](https://installatron.com/wallabag) is 1.9.0 and my web hosting company says that they can't do anything about it because they pull it from a repository that is not in their control. Who has access to that repository? Is it wallabag?

Would appreciate guidance and help.

Kind regards

**Comment by j0k3r** [comment]
I've no idea what Installatron is.
I guess they published a version of wallabag 5 years ago without updating it later.
You should contact them instead to solve that issue.
