### ISSUE TITLE
Syntax error updating to 2.4

### ISSUE THREAD

**Issue by biva** [wallabag/wallabag#4845]
I try to update from 2.3.8 to 2.4 on Debian (Apache) : sudo -u www-data make update

I have the following errors:
<code>
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
22:18:34 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate --no-interaction --env=prod". Message: "An exception occurred while executing 'ALTER TABLE wallabag_entry ADD given_url LONGTEXT DEFAULT NULL, ADD hashed_given_url TINYTEXT DEFAULT NULL':

SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "doctrine:migrations:migrate --no-interaction --env=prod","message" => """  An exception occurred while executing 'ALTER TABLE wallabag_entry ADD given_url LONGTEXT DEFAULT NULL, ADD hashed_given_url TINYTEXT DEFAULT NULL':\n  \n  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs  """]

In AbstractMySQLDriver.php line 110:

  An exception occurred while executing 'ALTER TABLE wallabag_entry ADD given_url LONGTEXT DEFAULT NULL, ADD hashed_given_url TINYTEXT DEFAULT NULL':

  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some
   columns to TEXT or BLOBs

In PDOConnection.php line 91:

  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

In PDOConnection.php line 86:

  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]

make: *** [GNUmakefile:24: update] Error 1
</code>

I have followed https://doc.wallabag.org/en/admin/common_errors.html to add the required option in `app/config/config.yml` but still the same error. And when I check this file, the added lines are not there anymore.

Finally, I tried to clear cache with `bin/console cache:clear -e=prod` but I get this error:
`The file "/var/www/html/wallabag/app/config/config_=prod.yml" does not exist.`

Any idea?

**Comment by j0k3r** [comment]
See https://github.com/wallabag/wallabag/issues/4820

**Comment by biva** [comment]
It worked, thanks! I saw this issue but I thought it was a docker issue, so I did not dig into it. May I suggest to change the title?

**Comment by j0k3r** [comment]
Good idea, I'll.
