### ISSUE TITLE
Error 500 when fetching https://posts.specterops.io/building-a-freeipa-lab-17f3f52cd8d9

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#4855]
We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched
**Content related:**
 - URL: https://posts.specterops.io/building-a-freeipa-lab-17f3f52cd8d9
 - wallabag version: 2.4.0

**Describe what's wrong:**
I Get an error 500 on fetching the URL I got it even in 2.3.8. 
the messqge is
```
500: Internal Server Error

Compile Error: require(): Failed opening required '/var/www/wallabag/var/cache/prod/rulerz/rulerz_executor_fcf8b5da' (include_path='.:')
```
The docker container is brand new from 2.4.0 (volume removed from previous config)
looking at the config the parent directory (`rulez`) is owned by `root` but php-fpm is running under user `nobody`.
I joining the log file `prod.log` [prod.log](https://github.com/wallabag/wallabag/files/5705270/prod.log)

I don't get the problem for other pages.

**Comment by j0k3r** [comment]
Could you try to fix permission?

https://doc.wallabag.org/en/admin/installation/rightaccess.html#production-environment

**Comment by bmillemathias** [comment]
> Could you try to fix permission?
> 
> https://doc.wallabag.org/en/admin/installation/rightaccess.html#production-environment

I thought it wa a problem in the container permission but actually could it be a permission issue implied when fixing #4764
