### ISSUE TITLE
Package from URL for upgrade of shared hosting does not contain the "vendor" directory

### ISSUE THREAD

**Issue by yvesle** [wallabag/wallabag#4863]
### Environment

* **Version**:2.3
* **Installation**:shared hosting
* **PHP version**:7.2
* **OS**:linux
* **Database**:SQL
* **Parameters**:

As of yesterday, the URL given in [the documentation](https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting) for upgrade on shared hosting ( https://wllbg.org/latest-v2-package ) does give a package that does NOT contain the "vendor" directory. 

The one on the package list on github does contain the vendor directory : https://github.com/wallabag/wallabag/releases/download/2.4.0/wallabag-2.4.0.tar.gz

Please update either the documentation or the package.

**Comment by j0k3r** [comment]
Can you double check @nicosomb?

**Comment by nicosomb** [comment]
Fixed. I don't understand, because I thought that I already fixed that last week.
