### ISSUE TITLE
fos is not defined running with docker image

### ISSUE THREAD

**Issue by krswin** [wallabag/wallabag#4870]
Version:     2.4.0 - 2020-12-10
Installation: Using docker image from docker hub. 
OS:           macOS Catalina 10.15.7
Database:     default by docker image
Parameters:   default by docker image

### What steps will reproduce the bug?

on Macbook pro Intel Processor
Run in Terminal : 
`docker run -p 80:80 wallabag/wallabag`

open in firefox version 84.0 > http://localhost:80

Screenshot attached for the bugs.
<img width="1277" alt="Screenshot 2020-12-20 at 14 11 11" src="https://user-images.githubusercontent.com/53046777/102714241-9aeec400-42cd-11eb-80d5-41bee947c223.png">
<img width="1269" alt="Screenshot 2020-12-20 at 14 06 38" src="https://user-images.githubusercontent.com/53046777/102714245-9f1ae180-42cd-11eb-948d-eca55e0bc4e0.png">
<img width="1278" alt="Screenshot 2020-12-20 at 14 06 20" src="https://user-images.githubusercontent.com/53046777/102714246-a04c0e80-42cd-11eb-8e54-c6d1ccce4bb0.png">
<img width="842" alt="Screenshot 2020-12-20 at 14 05 15" src="https://user-images.githubusercontent.com/53046777/102714247-a0e4a500-42cd-11eb-8026-3489823c0fff.png">
<img width="865" alt="Screenshot 2020-12-20 at 14 04 58" src="https://user-images.githubusercontent.com/53046777/102714248-a17d3b80-42cd-11eb-8fec-601b7e247dda.png">

**Comment by Kdecherf** [comment]
Hello @krswin,

Please check that you set up the correct value for the `SYMFONY__ENV__DOMAIN_NAME` environment variable.

See the list of environment variables and their default value here: https://github.com/wallabag/docker#environment-variables

**Comment by krswin** [comment]
Thank you for your quick reply. It worked.
I think its a issue in document then, can you please update installation documentation as mentioned below is bit misleading. so this can help who are newly installing. thanks. have a good day.

https://github.com/wallabag/docker#environment-variables
The easiest way to start wallabag is to use the SQLite backend. You can spin that up with
$ docker run -p 80:80 wallabag/wallabag
