### ISSUE TITLE
Change behavior on starred feed (ATOM vs RSS)

### ISSUE THREAD

**Issue by franek** [wallabag/wallabag#4871]
### Environment

* **Version**:  2.4.0
* **Installation**: downloading the package and use make update to upgrade from 2.3.X to 2.4.0
* **PHP version**: 7.3.23
* **OS**: Debian
* **Database**: Mysql

### What steps will reproduce the bug?

Due to https://github.com/wallabag/wallabag/pull/3223, you have migrated feed from RSS to Atom format. Everything is working well except there is an unexpected change on feed format.

I am used to publishing my favorites wallabag item to Twitter through an IFTTT recipe. This recipe takes each item into `/feed/user/token/starred` and publishes it to Twitter. URL which is sent to twitter is the source feed url and not the wallabag url `/view/5040`. I don't want that my that followers are redirected to my wallabag instance. I want that they are going to the original source url.
Everything is working well on 2.3.X.

On 2.4.0, it is now the wallabag url `/view/5040` which is published because the format looks like this : 

``` 
<link rel="alternate" type="text/html"
              href="https://wallabag.instance.com/view/5040"/>
        <link rel="via">https://www.source-content.com/</link>
``` 
whereas on 2.3.0, format looked like : 
``` 
  <source url="https://wallabag.instance.com/view/5040">wallabag</source>
                <link>https://www.source-content.com/</link>
``` 
IFTTT seems to take the first `<link>` in order to publish content on twitter which is the internal link url and not the source url.

I think this change could have some unexpected changes for other users..

I don't really know how we could fix this behavior. I don't even know if we can consider it as a bug.
Perhaps, returning first `link rel="via"` instead of `link rel="alternate"` will fix my problem. 

Thnaks for 2.4.0 release ;)

**Comment by Kdecherf** [comment]
@franek which IFTTT recipe are you using?

**Comment by franek** [comment]
> @franek which IFTTT recipe are you using?

I use "RSS feed: new item" connected to twitter : "If new feed item from https://mywallabag.instance.com/user/token/starred.xml, then post a tweet to @_twitter_account_" 

We can't choose which link from feed can be used : 
![image](https://user-images.githubusercontent.com/417716/102718551-085c1e00-42e9-11eb-8042-8904f3d8f1ca.png)

**Comment by franek** [comment]
I have tried to switch `<link rel="via">̀ as first element : 
```
<link rel="via">https://www.source-content.com/</link>
<link rel="alternate" type="text/html"
              href="https://wallabag.instance.com/view/5040"/>
``` 
but it does not fix my problem.
So, I read the specification https://tools.ietf.org/html/rfc4287#section-4.2.7.2 and Wallabag implementation is good.
* `<link rel="alternate">` must be used to identify the main ressource (in our case, wallabag url).
* `<link rel="alternate">` must be used to identify the source of the main ressource (in our case, article source url).

Unless you have another solution, I think I will have to add a proxy between wallabag and IFTTT in order to modify feed format. Will continue to investigate.

**Comment by franek** [comment]
Don't know if you will accept it but I try to fix this problem with this PR : https://github.com/wallabag/wallabag/pull/4883

**Comment by j0k3r** [comment]
That's a way to fix the problem but requiring user to execute a migration only to apply that change looks a bit heavy for me.

I think about something, shouldn't links be like that instead:

```diff
<link rel="alternate" type="text/html"
              href="https://wallabag.instance.com/view/5040"/>
-       <link rel="via">https://www.source-content.com/</link>
+       <link rel="via" href="https://www.source-content.com/"/>
```

Maybe IFFT will better handle it if you then move the `via` link first?

**Comment by franek** [comment]
> That's a way to fix the problem but requiring user to execute a migration only to apply that change looks a bit heavy for me.

I could handle this config with a symfony parameter but I thought it would be nice to have this config by user (for a multi-user environment).

> 
> I think about something, shouldn't links be like that instead:
> 
> ```diff
> <link rel="alternate" type="text/html"
>               href="https://wallabag.instance.com/view/5040"/>
> -       <link rel="via">https://www.source-content.com/</link>
> +       <link rel="via" href="https://www.source-content.com/"/>
> ```
> 
> Maybe IFFT will better handle it if you then move the `via` link first?

You are right. The syntax should be `<link rel="via" href="https://www.source-content.com/"/>` (cf. https://tools.ietf.org/html/rfc4287#section-4.2.7) but it won't fix my problem. 
IFTTT takes the first `<link rel="alternate...`.

I have tried an IFTTT alternative (https://github.com/n8n-io/n8n) and I have the same behavior.

**Comment by j0k3r** [comment]
Alright.
Could you update your PR to fix the `href` thing?

As there is a migration, that feature will target 2.5.0.

**Comment by franek** [comment]
Chouette. Thanks ;)
I have updated ATOM feed : https://github.com/wallabag/wallabag/pull/4883/commits/11986230699c1a93abf4c8af987fccbff8dc76a4
