### ISSUE TITLE
remote connection to database mysql 8 do not work.

### ISSUE THREAD

**Issue by ghost** [wallabag/wallabag#4880]
### Environment

* **Version**: 2.4.0
* **Installation**: Docker container for wallabag and mysql runs on remote ip address
* **PHP version**:
* **OS**: linux
* **Database**: MySQL 8
* **Parameters**:

<details>

  ```
The server requested authentication method unknown to to the client [caching_sha2_password].
  ```
</details>

### What steps will reproduce the bug?
Run Wallabag with remote MySQL 8 database.

**Comment by j0k3r** [comment]
Looks like we hit the problem too, see https://github.com/wallabag/wallabag/pull/5729

You should run at least PHP 7.4 to fix the issue without doing nothing.
Otherwise, please check all links for the linked PR.
