### ISSUE TITLE
Package from URL for upgrade of shared hosting does not contain the "vendor" directory

### ISSUE THREAD

**Issue by yvesle** [wallabag/wallabag#4892]
The problem in #4863 occurs gain. I checked after your fix and it was ok. 
However the same problem occurs as of 2020-12-30 10H55 CET, no vendor folder in the package from https://wllbg.org/latest-v2-package

**Comment by j0k3r** [comment]
@nicosomb can you check again?

@yvesle in the meantime, you can use the archive `wallabag-2.4.0.tar.gz` associated to the 2.4.0 release https://github.com/wallabag/wallabag/releases

**Comment by yvesle** [comment]
@j0k3r yeah, I did that, no issues then. Thanks.

**Comment by nicosomb** [comment]
@j0k3r it seems ok for me :thinking:
