### ISSUE TITLE
Upload files into wallabag 

### ISSUE THREAD

**Issue by simonfrey** [wallabag/wallabag#4895]
I would like to upload PDFs and Ebook files (.epub, .mobi) to wallabag for reading them.

Can we make this possible? It is kind a weird hack to first host them on my server and than download add them via that URL to wallabag.

I am mainly using wallabag on iOS so if there is a way to already do it I would appreciate a hint how I could do it.

Thanks for your help and happy new year,
Simon

**Comment by fr-laurentn** [comment]
I'd also like to have the ability to upload files in Wallabag.
I'm not using the self-hosted version, so I understand you might have extra storage costs. Maybe, charge a little more for this option?

**Comment by joenepraat** [comment]
Yes, this would be great. I have sometimes newssites who can't be fetched, so I save the page manually as a pdf. Instead of transfer it than manually to my ebook-reader, I like it to have in Wallabag along with the other stuff.

**Comment by nicosomb** [comment]
Hello. 

Thank you for your issue, but wallabag won't have this feature. I don't want to develop and maintain a gaz factory. 

Nicolas

**Comment by joenepraat** [comment]
> Hello.
> 
> Thank you for your issue, but wallabag won't have this feature. I don't want to develop and maintain a gaz factory.
> 
> Nicolas

Wow, this is a harsh, closing a valid feature request like this. 🙄 Can you at least explain what a 'gaz factory' is?

**Comment by nicosomb** [comment]
Sorry for this short message. 

Upload files is a complex part for wallabag, which is only a "save and read articles" application. 
I think that Nextcloud and apps like that are more adapted for this requested feature.

**Comment by joenepraat** [comment]
Ok, thank you for your longer reply. Most pdf's can also be shared with Wallabag, so that will do.
