### ISSUE TITLE
Improve dark theme colors

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#4898]
First of all, thank you for implementing the dark theme. I'm not a UX expert but I think "dark theme" is not just changing the background color to black. I found some parts of the web UI with high contrasts that hurt my sight.

Header is too bright:
![imagen](https://user-images.githubusercontent.com/10577978/103422643-cbbedb00-4ba2-11eb-8cd5-f2901903de82.png)
Article border is ugly:
![imagen](https://user-images.githubusercontent.com/10577978/103422660-df6a4180-4ba2-11eb-9e98-30f4c8155c09.png)
Labels are hard to read:
![imagen](https://user-images.githubusercontent.com/10577978/103422668-e8f3a980-4ba2-11eb-9b26-99a3b58c7496.png)
Green text in the menu:
![imagen](https://user-images.githubusercontent.com/10577978/103422869-e9407480-4ba3-11eb-8b77-830cf4f10eab.png)

As I said I don't know much about colors/design but I think you should follow the material design recommendations. The UI should be more like this:
![imagen](https://user-images.githubusercontent.com/10577978/103422727-26583700-4ba3-11eb-8d4c-9559a2f835fa.png)

Documentation => https://material.io/design/color/dark-theme.html#usage

**Comment by ngosang** [comment]
Another example with dark material design is Gotify:
![image](https://user-images.githubusercontent.com/10577978/103480866-525bfe00-4dd7-11eb-9348-85406d001661.png)

**Comment by techexo** [comment]
Hello all,
I completely agree with @ngosang, right now it's not really usable as a dark theme because of the high contrast. I'd be happy to try and have a look, see if just tweaking the CSS could work at first.
However, trying to modify `./app/Resources/static/themes/material/css/dark_theme.scss` directly doesn't seem to work, as everything is bundled in a webpack? I tried clearing the prod cache with no success, and on two different browsers.

Is there something I have to run after each CSS modification on my local instance so I can see them in prod?
Thanks in advance

**Comment by Kdecherf** [comment]
@techexo yes, there are commands to run when you change the scss files.

In short, when you are in dev mode, you must run `yarn build:dev` to rebuild dev assets. And `yarn build:prod` for prod assets.

See https://doc.wallabag.org/en/developer/front_end.html

**Comment by techexo** [comment]
@Kdecherf I understand it's not good practice but I don't have a "test" environment set up for this and would like to try it in prod directly. However, trying `yarn build:prod` in my wallabag folder generates the following message:
`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build:prod'`

**Comment by Kdecherf** [comment]
Yeah, I don't necessarily recommand editing scss and making yarn calls on production environments.

As an alternative you could test your css changes in the custom.css file, which is loaded by wallabag and is empty on new installs.

**Comment by techexo** [comment]
I am on my way to publish something on it, maybe you could assign the ticket to me so that we don't duplicate work effort?

**Comment by techexo** [comment]
I think the following is not to bad and solves quite a number of the issues mentioned by @ngosang. I have followed the recommendations of Dark Material themes for the various level of grey and the background.

![image](https://user-images.githubusercontent.com/1850197/103903320-0c1add80-50fc-11eb-8b9d-d797777ee6bb.png)
![image](https://user-images.githubusercontent.com/1850197/103903414-25bc2500-50fc-11eb-9248-6db73a3320b8.png)
![image](https://user-images.githubusercontent.com/1850197/103903452-310f5080-50fc-11eb-9afe-6a0c7c58314c.png)
![image](https://user-images.githubusercontent.com/1850197/103903550-543a0000-50fc-11eb-9afd-bae7c15394e9.png)

**Comment by j0k3r** [comment]
> What git base should I use to create a PR? master? 2.5? 2.4.2?

2.4.2 is fine

**Comment by ngosang** [comment]
@techexo Thank you. Please, take a look at Whatsapp web too. The dark theme is the same color as Wallabag. Black + green.
https://web.whatsapp.com/
