### ISSUE TITLE
Error parsing image URL

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#4914]
In this article, the URL of the first image is wrong.
https://www.eleconomista.es/empresas-finanzas/noticias/10977143/01/21/Asi-son-los-grandes-proyectos-inmobiliarios-que-transformaran-Madrid.html

The source code of the image is this:
```
<img itemtype="//schema.org/ImageObject" itemprop="url" class="" data-sizes="50vw" alt="MNN.jpg" id="3419283" 
onload="mylazy()"
src="https://s03.s3c.es/imag/_v0/770x420/a/2/8/180x100_MNN.jpg"
data-src="https://s03.s3c.es/imag/_v0/770x420/a/2/8/700x420_MNN.jpg"
data-srcset="https://s03.s3c.es/imag/_v0/770x420/a/2/8/490x_MNN.jpg 500w, https://s03.s3c.es/imag/_v0/770x420/a/2/8/700x420_MNN.jpg 1000w">
```

Image in Wallabag:
```
<img itemtype="//schema.org/ImageObject" itemprop="url" class="" data-sizes="50vw" alt="MNN.jpg" id="3419283" 
src="https://s03.s3c.es/imag/_v0/770x420/a/2/8/490x_MNN.jpg%20500w,%20https://s03.s3c.es/imag/_v0/770x420/a/2/8/700x420_MNN.jpg%201000w"
referrerpolicy="no-referrer">
```

I though that this is a corner case but I'm seeing it in more websites lately. This is a strategy to speed up the page load. They configure a thumbnail in the `src` attribute and load the full image using Javascript after the page is complete from attribute `data-srcset`. We are already grabbing `data-srcset` when it's present but if fails if there are 2 images (for different resolutions). I don't know if it will be better to get the first image or use the attribute `data-src`. It must work for other sites too.

### Environment
* **Version**: Wallabag 2.4.1

**Comment by ngosang** [comment]
Same thing happens with the 2nd and 3rd image in this article:
https://www.redeszone.net/noticias/redes/cloud-pc-servicio-microsoft-trabajo-nube/

**Comment by ngosang** [comment]
I think this is not working. Try with https://www.redeszone.net/noticias/redes/cloud-pc-servicio-microsoft-trabajo-nube/

**Comment by Kdecherf** [comment]
@ngosang the fix is in a dependency of the project (graby). It will be available in the next release.
