### ISSUE TITLE
wallabag css being applied to article in web interface.

### ISSUE THREAD

**Issue by RayBB** [wallabag/wallabag#4916]
### Environment

Hosted app.wallabag.it as of jan 7

### What steps will reproduce the bug?

Add an article to your wallabag from hawaiinewsnow.com. Example [here](https://www.hawaiinewsnow.com/2021/01/06/massive-musubi-tenn-business-whips-up-potentially-record-breaking-spam-musubi/).

What you'll see is that it renders the page oddly because wallabag uses the "card" class in CSS.
However, the html scraped from Hawaii news now also uses the card class. This ends up creating an issue where the css is being applied to the article body to cause undesired changes.

This issue doesn't impact the android app or f43.me from what I can tell.

Perhaps html classes should be stripped before rendering in wallabag website?

<img width="1220" alt="Screen Shot 2021-01-07 at 7 36 45 AM" src="https://user-images.githubusercontent.com/921217/103926976-c3443400-50bd-11eb-86c2-6e43dfde2378.png">

**Comment by Kdecherf** [comment]
There's a work on that topic (that I should continue) here: https://github.com/j0k3r/graby/pull/211

**Comment by Kdecherf** [comment]
Closing this in favor of #3134
