### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by fr-laurentn** [wallabag/wallabag#4922]
Hello, 

I'm using wallabag.it for personal use and I love it.

I'd like to use it with my company and one of the features we'd like is a Slack integration.
The idea would be to have a Slack notification when a new link is saved on our wallabag.it instance.

I've seen https://github.com/clem/slack-to-wallabag but it's not what I'm looking for. However, it shows it is possible. 

Thanks for considering this request.

**Comment by nicosomb** [comment]
Hello! 

The unread section of your account provides a RSS feed. You can connect it to a slack channel. 

Nicolas

**Comment by fr-laurentn** [comment]
Hello,

Thanks for the prompt reply.

I'll try that, thanks!
