### ISSUE TITLE
>Issues to save images locally - not working

### ISSUE THREAD

**Issue by rodrigoawk** [wallabag/wallabag#4944]
**Issue details**

Internal Settings > MISC > Download images locally - default is '0'; if set to '1', after saving a new url it goes to a page error and do not save images locally:

`
 500: Internal Server Error
 Call to a member function bindHandles() on null
`

The article is saved though, but the images on it (includding the thumbnail) still point to original url.

Another side effect from this Settings is that mobile app (Android) stopped syncing as expected.

(both /wallabag/web/assets and /wallabag/web/uploads are set chmod -R 777)

_Originally posted by @rodrigoawk in https://github.com/wallabag/wallabag/issues/3735#issuecomment-760915372_

**Environment**

wallabag 2.4.1 
Shared hosting

**Comment by Kdecherf** [comment]
@rodrigoawk could you give an example url that triggers this bug in order for us to reproduce it?

**Comment by Kdecherf** [comment]
There is not much activity on this issue, closing it.
