### ISSUE TITLE
Column already exists: 1060 Duplicate column name 'googleAuthenticatorSecret'

### ISSUE THREAD

**Issue by HLFH** [wallabag/wallabag#4979]
Version: 2.4.1 
PHP version: PHP 7.4.14
OS: Arch Linux
Database: MariaDB Ver 15.1 Distrib 10.5.8

### What steps will reproduce the bug?

Upgrade from 2.3.x to 2.4.1 does not work at all. First issue you encounters is this one: https://github.com/wallabag/wallabag/issues/4820.
Then you do this: https://github.com/wallabag/wallabag/issues/4820#issuecomment-743863156
Then you get the following issue: `Column already exists: 1060 Duplicate column name 'googleAuthenticatorSecret'` and nothing works.

### Off-topic
(And I cannot even test [old issues](https://github.com/wallabag/wallabag/issues/2114) since it is not working)

Thanks,
HLFH

**Comment by HLFH** [comment]
The workaround with SQL command is the following:

> USE wallabag;
> ALTER TABLE wallabag_user
> DROP COLUMN googleAuthenticatorSecret;

**Comment by Kdecherf** [comment]
@HLFH do you still have this issue with the last release 2.5.0?

**Comment by P3lUZa** [comment]
Issue has not being fixed.
