### ISSUE TITLE
on app.wallabag.it Fetching www.contretemps.eu articles goes to error 500

### ISSUE THREAD

**Issue by TontonMollo** [wallabag/wallabag#4982]
Hi Guys,

(Almost) all articles on Contretemps.eu fail to be saved in wallabag, going to an Error 500

https://www.contretemps.eu/pandemopolitique-covid-triage-inegalites-sante-vaccins-alternatives/

(End on error message says "invalid date format)

I maintly use Vivaldi browser, seen even on Debian ans W7.

![Screenshot_2021-01-27_10-31-27](https://user-images.githubusercontent.com/63392889/105971461-d6c63780-608a-11eb-9177-2eb669fee13e.png)
![Screenshot_2021-01-27_10-30-57](https://user-images.githubusercontent.com/63392889/105971468-d7f76480-608a-11eb-861f-01173bd80fd1.png)

Thanks for watching.

**Comment by nicosomb** [comment]
Hello. 
It works on wallabag.it now. (I did nothing).
