### ISSUE TITLE
Several articles cannot be exported to epub (Gateway Time-out)

### ISSUE THREAD

**Issue by brabalan** [wallabag/wallabag#5103]
### Environment

* **Installation**: subscribed to app.wallabag.it

### What steps will reproduce the bug?

- add one of these articles to wallabag
  - https://writings.stephenwolfram.com/2020/10/faster-than-light-in-our-model-of-physics-some-preliminary-thoughts/
  - https://writings.stephenwolfram.com/2020/12/combinators-and-the-story-of-computation/
  - https://writings.stephenwolfram.com/2020/12/where-did-combinators-come-from-hunting-the-story-of-moses-schonfinkel/
  - https://writings.stephenwolfram.com/2020/12/launching-version-12-2-of-wolfram-language-mathematica-228-new-functions-and-much-more/
  - https://writings.stephenwolfram.com/2021/01/tini-veltman-1931-2021-from-assembly-language-to-a-nobel-prize/
- try to export to epub (just one file among these)
- this results in an error 504 Gateway Time-out

**Comment by j0k3r** [comment]
I guess the 504 is related to a timeout on the PHP site.
Maybe @nicosomb has some insight from wallabag.it or some errors?

**Comment by brabalan** [comment]
I’m pretty sure it’s a time-out issue, but I wonder if there is something special about that site that makes it happen. I have longer articles that can be transformed to epubs with no issue.

**Comment by nicosomb** [comment]
The error : 

```
upstream timed out (110: Connection timed out) while reading response header from upstream, 
request:     "GET /export/tag_entries.epub?tag=bug HTTP/2.0",
```

**Comment by nicosomb** [comment]
I fixed this bug by changing my nginx configuration. I added this: 

```
    proxy_http_version 1.1;
    proxy_set_header Connection "";
``` 

found here https://stackoverflow.com/a/28365664

**Comment by ldidry** [comment]
As you pass the request to PHP-FPM through `fastcgi_pass`, I think that `proxy_` directives will have no effect.

I suggest increasing `fastcgi_connect_timeout` and `fastcgi_read_timeout` (and maybe, but I don’t think it’s useful here, `fastcgi_send_timeout`).

See https://stackoverflow.com/questions/59713432/nginx-php-fpm-fastcgi-upstream-timed-out

**Comment by nicosomb** [comment]
@brabalan could you try please?

**Comment by brabalan** [comment]
I confirm that it works. Thanks!
