### ISSUE TITLE
Url works with f43.me but not with wallabag

### ISSUE THREAD

**Issue by matclab** [wallabag/wallabag#5104]
http://www.amusesbouche.fr/article-52827337.html works with f43.me but fails with wallabag

(The caks is also very tasty :-) )

**Comment by j0k3r** [comment]
Are you using wallabag.it or which version are you using?

**Comment by matclab** [comment]
Oups sorry for not saying upfront. I'm using wallabag.it

**Comment by j0k3r** [comment]
So maybe we'll wait for the 2.4.2 to be released and wallabag.it to be updated to see if it fix the issue

**Comment by Kdecherf** [comment]
Fetched content looks good on current master, closing this issue.
