### ISSUE TITLE
Add support for webp image when saving them locally

### ISSUE THREAD

**Issue by Ogg3l** [wallabag/wallabag#5107]
Hello,

i noticed that Graphics which have the Format .webp are not saved.

For Example this Site: https://www.heise.de/news/Ausprobiert-Platinen-mit-kostenloser-SMD-Bestueckung-5070776.html

or this: https://developers.google.com/speed/webp/gallery1

There you can see the jpg images work but the webp images not.

Is there an opportunity to add this functionality?

Thanks for your great work :)

**Comment by j0k3r** [comment]
You mean when saving images locally?
For now, only gif, jpg & png are supported: https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Helper/DownloadImages.php#L159-L188

Does Imagick or GD support creating a webp from a string?
It looks a bit complex to add webp support in Imagick 😕 
https://github.com/rosell-dk/webp-convert/wiki/Installing-Imagick-extension-with-WebP-support

**Comment by Ogg3l** [comment]
> 
> 
> You mean when saving images locally?
> For now, only gif, jpg & png are supported: https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Helper/DownloadImages.php#L159-L188

Yes i mean when saving images locally.

> Does Imagick or GD support creating a webp from a string?

Unfortunately i don't know what you mean :)
