### ISSUE TITLE
Cant login on a fresh install

### ISSUE THREAD

**Issue by niladrishekhar** [wallabag/wallabag#5162]
Version:     Version 2.4.2 
Installation: Using Git clone
PHP version:  PHP 7.4.15 
OS:           Debian
Database:  MySQL/MariaDB 

parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: wallabag
    database_user: wallabag
    database_password: null
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'http://localhost/wallabag/web'
    server_name: 'Your wallabag instance'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: CHANGE_ME_TO_SOMETHING_SECRET_AND_RANDOM
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null

Issue - this is a fresh install => along with the config yml - 
Step 3 of 4: Administration setup.
----------------------------------
 Would you like to create a new admin user (recommended)? (yes/no) [yes]:
 > yes
 Username [wallabag]:
 >   
 Password [wallabag]:
 > 
 Email [wallabag@wallabag.io]:
 > 
 Administration successfully setup.

Step 4 of 4: Config setup.
--------------------------
 Config successfully setup.
 [OK] wallabag has been successfully installed.                                                                
 [OK] You can now configure your web server, see https://doc.wallabag.org     

When I try to login http://localhost/wallabag/web/app.php/login I enter username wallabag, password wallabag hit login - nothing happens keep redirecting to the login page. 

select username,password from wallabag_user;
+----------+------------------------------------------------------------------------------------------+
| username | password                                                                                 |
+----------+------------------------------------------------------------------------------------------+
| wallabag | M6OSQEqu4SDAJSBbs+5m1Y6vZPLfanV8BuhgJv1MJd2dY5tdC3/gq3GETgbPN44XmYMPNiz4l/KX6i5g8FcWxw== |
+----------+------------------------------------------------------------------------------------------+

What am I missing ?

**Comment by niladrishekhar** [comment]
Hi - any input - suggestion - anything ?

**Comment by blindjoedeath** [comment]
I've had the same problem. The solution was to configure permissions for wallabag folder at /var/www.

`sudo chown -R www-data:www-data <folder>'
'sudo chmod -R 755 <folder>`
