### ISSUE TITLE
Set expectations in simple language re: import delay

### ISSUE THREAD

**Issue by sfirke** [wallabag/wallabag#5196]
Hello,

New user here, signed up for wallabag.it.  I went through the Import from Pocket steps a few times, seeing a message about "3946 articles added to queue" but then no indicator of progress.

I figured the process was broken.  After looking through old Github issues, it looks like the import worker only works intermittently so it can take a day or two (?) to import the articles.

If that's the case, could I suggest adding a sentence to the page displayed after clicking import like, "Import request successful.  Article import does not happen immediately.  It may take several hours or up to 2 days to import your articles."  That way new users don't spend time trying to troubleshoot, or give up on Wallabag.

Right now I see "Import is made asynchronously. Once the import task is started, an external worker will handle jobs one at a time. The current service is: RabbitMQ" but to a non-technical user, it's unclear what this means.

Thanks for considering!

Sam

**Comment by sfirke** [comment]
The import succeed this morning, ten days later :grin: I became a paying subscriber last night, is the import feature only for paid subscribers and not those on a free 14-day trial?  Or did it really take ten days - if so is that because I imported 3,400 articles?

At any rate, glad it succeeded, I'm happy to be on board with Wallabag, and I think it would be a great enhancement to message expectations to new users - it could succeed in retaining them as paying users.

**Comment by ngklingler** [comment]
I'm definitely curious about this as well... Imported articles from pocket and firefox bookmarks a few hours ago and still nothing. On a 14 day trial and want to see if it's worth paying for, but can't really make that decision until I see the import process work.

**Comment by stelioskat** [comment]
Same issue here!

**Comment by nicosomb** [comment]
Hello. 
Sorry for the delay (I'm as long as the import system on wallabag.it 😁). If you have any issue with wallabag.it, it's better to contact me on nicolas@wallabag.it 

About import system, sometimes, it crashes and I need to restart it. Sorry for that.
