### ISSUE TITLE
Arxiv support

### ISSUE THREAD

**Issue by theophilec** [wallabag/wallabag#5205]
Hi wallabag !

I save a lot of research papers and wallabag seems to not handle pages like https://arxiv.org/abs/2006.13198 (for example).

I actually opened a pull request in fivefilters here: https://github.com/fivefilters/ftr-site-config/pull/870 
But they don't seem to be responding.

I think being able to save from arxiv would be useful for a lot of people!

**Comment by Kdecherf** [comment]
Linked PR has been merged in ftr-site-config, I'll close this issue then.
However the change has not yet landed in wallabag releases.

@theophilec feel free to comment if you think there's more work to do.
