### ISSUE TITLE
Firefox OS app

### ISSUE THREAD

**Issue by jancborchardt** [wallabag/wallabag#521]
A Firefox OS app would be great! Easiest would be to just use the same front-end as the web app does. Differences though:

* Server location needs to be configurable
* Needs to work offline (AppCache)
* Ideally also save some articles locally (IndexedDB)

**Comment by nsteinmetz** [comment]
Having a Firefox OS device, I *may* be tempted to implement a FxOS App ; would it be worth starting on a 1.x series (may be quiet basic like only the share button management) or some "embed" version of the normal one which is RWD compliant.

Or to start on a 2.x basis if 2.x is stable enough to be used and started dev on it ?

**Comment by nicosomb** [comment]
Hi ! 

2.x is not but I think it's better to dev on it. I think you saw my tweets about 2.x ;-)

**Comment by nicosomb** [comment]
Is not stable ;-)

**Comment by tcitworld** [comment]
I think it's better to focus on 2.0 too. If users want to have access articles to a 1.x device, they can use the RSS feeds for now.

@nicosomb has created nice documentation for 2.x API :)

**Comment by nicosomb** [comment]
https://github.com/wallabag/wallabag-fxos thank you @freddyb!
