### ISSUE TITLE
Ability to share a link that includes my highlights/annotations?

### ISSUE THREAD

**Issue by ReessKennedy** [wallabag/wallabag#5219]
Issue: 
I love being able to share a story from my own domain hosting Wallabag but I also want to be able to share my highlights from an article. 

Solution: 
* I Couldn't find discussion about this online. Did I miss something? Surely others want this too. 
* Instapaper doesn't allow this either, I don't think, and it's been a pain point for me
* Being that Wallabag is open source I figured that if it doesn't exist here and no one has worked on it, maybe I could work with someone on this

**Comment by lapineige** [comment]
I would be interested too 🙂

**Comment by rocky-III** [comment]
any news about this feature?

**Comment by Kdecherf** [comment]
@rocky-III there's no work in progress on this issue

**Comment by Kdecherf** [comment]
Duplicate of #4907
