### ISSUE TITLE
Wrong display in wallabag (numerama.com)

### ISSUE THREAD

**Issue by AltB** [wallabag/wallabag#5299]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [X] I've tried myself without success
- [X] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://www.numerama.com
 - wallabag version: 2.4.2

**Describe what's wrong:**
Unable to grab content (tried custom xpath). Various message about 'Readability', 'bad date format passed to strtotime, and grab failed. Tested with f43.me and graby log.

Time: | 2021-05-21T10:51:29+02:00
Trying //article[@class='post-content'] for body (content length: 22226)
pattern: //article[@class='post-content']  content_length: 22226 | //article[@class='post-content'] | 22226
//article[@class='post-content']
22226
                                            
Time: | 2021-05-21T10:51:29+02:00
Using Readability
                                            
Time: | 2021-05-21T10:51:29+02:00
Date is bad (strtotime failed):
date: | &nbsp;
&nbsp;
                                            
Time: | 2021-05-21T10:51:29+02:00
Success ?
is_success: (bool) false | (bool) false
(bool) false
                                           
Time: | 2021-05-21T10:51:29+02:00
Extract failed

**Comment by Kdecherf** [comment]
Hey @AltB,

Are you talking about fetching the homepage or a specific article?

**Comment by alteiis** [comment]
Specific article but seems fixed today...

**Comment by alteiis** [comment]
Tried again with f43.me too and It's now ok

**Comment by Kdecherf** [comment]
I'm closing this issue then
