### ISSUE TITLE
RSS feeds of tags

### ISSUE THREAD

**Issue by xplosionmind** [wallabag/wallabag#5307]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Parse a RSS feed also for all of the entries tagged with a specific value, so that I can make public e.g. all of the posts I tag with `public`, by linking the tag-specific URL on my website.

**Describe alternatives you've considered**
There are no alternatives. As of right now, only four kinds of feed can be generated: read, unread, starred, all. It would be great to remove those limitations and parse RSS feeds for some user-defined tags, too.

**Additional context**
\-

**Comment by nicosomb** [comment]
Hello @xplosionmind. 

I'm not sure if I well understand your issue. 
RSS feed are already available for tags: you just need to go on the Tags page (`https://yourwallabag/tag/list`) and you have RSS icon on each tag.

**Comment by xplosionmind** [comment]
This is wonderful. I did not notice this. Thank you very much!
