### ISSUE TITLE
Keep local anchors as is

### ISSUE THREAD

**Issue by fradav** [wallabag/wallabag#5315]
**Is your feature request related to a problem? Please describe.**
Links to anchor in the same page are often used for footnotes. However, wallabag keeps the original site url, which redirects to the anchored original website, not to the local rendered wallabag's one.
For example [this](https://m00natic.github.io/emacs/emacs-wiki.html)

```html
<a id="fnr.1" class="footref" href="#fn.1">1</a>
```
Is rendered as :

```html
<a id="fnr.1" class="footref" href="https://m00natic.github.io/emacs/emacs-wiki.html#fn.1" name="fnr.1">1</a>
```

**Describe the solution you'd like**
Just keep original anchor *as is*, without rewriting the href.

**Comment by fradav** [comment]
1. $X_{0}=X ; y_{0}=y$
2. Pour $k=1,2,...,s$ :
    1. $w_{k}=\frac{X_{k-1}^{T} y_{k-1}}{y_{k-1}^{T} y_{k-1}}$
    2. Normer $w_k$ à 1
    3. $t_{k}=\frac{X_{k-1} w_{k}}{w_{k}^{T} w_{k}}$
    4. $p_{k}=\frac{X_{k-1}^{T} t_{k}}{t_{k}^{T} t_{k}}$
    5. $X_{k}=X_{k-1}-t_{k} p_{k}^{T}$
    6. $q_{k}=\frac{y_{k-1}^{T} t_{k}}{t_{k}^{T} t_{k}}$
    7. $u_{k}=\frac{y_{k-1}}{q_{k}}$
    8. $y_{k}=y_{k-1}-q_{k} t_{k}$

**Commentaires** Lorsqu'il n'y a pas de données manquantes, on peut remplacer les étapes $2.1$ et $2.2$ par $w_{k}=\frac{X_{k-1}^{T} y_{k-1}}{\left\|X_{k-1}^{T} y_{k-1}\right\|}$ et l'étape $2.3$ par $t_{k}=X_{k-1}w_{k}$

**Comment by guelfey** [comment]
Hi @j0k3r , I was looking into this as well and found this issue in grabby https://github.com/j0k3r/graby/pull/127 which supposedly fixed this, but the check for local anchors was removed again in https://github.com/j0k3r/graby/commit/75982696f5b3e2ee70d1f0e1d6988348a5ad7bed (also modifying the tests back again). Is there anything speaking against introducing that check again?

Somewhat related, I found that some sites implement footnotes using absolute anchor links. For better readability in wallabag, we could also translate them to relative anchors links (as we know the base URL we're fetching), though I understand that's a slightly different topic.

**Comment by j0k3r** [comment]
Good point, I don't know why we reverted back the fix.
I'll fix it again and put a comment.

About the second option, it could be more difficult to handle, I mean, I think it could have too much side effect / behavior.

**Comment by guelfey** [comment]
Thanks! Regarding the absolute anchors: I will try if I can easily work around that in some other place - if not, I might open a PR here and/or in graby. I will make it a configurable option though.

**Comment by eatsfoobars** [comment]
Hi there, is this still working as intended? Saving the original [link](https://m00natic.github.io/emacs/emacs-wiki.html) in wallabag converts footnotes/relative links to absolute ones, unless I've misunderstood something.

**Comment by SylvainChevalier** [comment]
Local anchors are still turned into absolute urls. It looks like the relevant code is still [in graby](https://github.com/j0k3r/graby/blob/master/src/Graby.php#L829), but maybe it's failing for some reason?

**Comment by fradav** [comment]
Ahem,
The code you just pointed :
```javascript
        if (!preg_match('!^(https?://|#)!i', $url)) {
            try {
                $absolute = $this->makeAbsoluteStr($base, $url);
            } catch (\Exception $exception) {
                $this->logger->info('Wrong content url', ['url' => (string) $url]);
            }
        }
```
It is not failing it does exactly what it says it does : it converts relative urls to absolute ones. That’s precisely the problem. 😄 

@j0k3r any insigthts about what’s going on here ? You said the fix was in, but if this is the fix, why is it doing the exact opposite of what it says it wants to do in the comment just above? This is very confusing. 🙀

**Comment by eatsfoobars** [comment]
The code above seems to be correct - if the URL does not start with `http[s]://` or `#` (so it is a relative link), it will be converted to an absolute link. Anchors should therefore not be converted to absolute links.

Isn't the issue that the fix hasn't been backported to Graby 2.x? https://github.com/j0k3r/graby/blob/2.x/src/Graby.php#L818-L845 Wallabag uses Graby 2.4.6. https://github.com/wallabag/wallabag/blob/aadc66c09d79fe7be5ea9557274ec69fe9844316/composer.json#L86
