### ISSUE TITLE
Failing authentication in Wallabag, wrong token expiry

### ISSUE THREAD

**Issue by dlastov** [wallabag/wallabag#5322]
I have installed wallabag on my Apache server, from git, so I assume the latest version on 13/6/2021. The clients fail to get a valid token. To see why, I tried to authenticate using a command line like below (real server name, id and secret amended). The problem is that in the response there is `"expires_in": "wallabag@MYSERVER.COM", ` instead of `"expires_in": 3600,`

Request:
`http POST https://wallabag.MYSERVER.COM/oauth/v2/token grant_type=password client_id=2_hclgw5h2xnkkscccc44cwswskoogwsoww4sosk44k448o8cwo client_secret=2yp72jtbs4u8so4w0s0sc0ws8sgk48oo408ow8wsc4s8kcwogs username=john password=dkeuedkadakds84adfake`

Response:
```
HTTP/1.1 200 OK
Cache-Control: no-store, private
Connection: Keep-Alive
Content-Length: 283
Content-Type: application/json
Date: Fri, 18 Jun 2021 18:42:18 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Server: Apache/2.4.46 (Ubuntu)

{
    "access_token": "YmQ4MzlmMGQ2YmUxMjk4YTlmOTQ4YmM4M2I4MDRiMWE2NTIyZjI5NWU2Yzk5NjZhNzBmYjA5YWRhMzQ3ODNiMA",
    "expires_in": "wallabag@MYSERVER.COM",
    "refresh_token": "MWFiOWI3MjM0ODdhZjIyNTkwYmU3NDNiNDU2YTZhMDVmNDBhZWMwM2JlYzc3MTQ2YjA3MzFkMWY1YjQ2ZDJmZQ",
    "scope": null,
    "token_type": "bearer"
}
```

**Comment by j0k3r** [comment]
Without a config file or a proper issue (by following the good template), we can't help you.
