### ISSUE TITLE
为什么我的界面会是这样？？？

### ISSUE THREAD

**Issue by mapleshadow** [wallabag/wallabag#5325]
![image](https://user-images.githubusercontent.com/525478/123541346-9fad9c80-d776-11eb-9de0-b431d4323029.png)

如图，好像是CSS没加载完成？

**Comment by tcitworld** [comment]
确保`parameters.yml` 文件包含`domain_name` 参数并且它与您的域名匹配 更改后，运行`bin/console cache:clear --env=prod` 清除缓存

Make sure the `parameters.yml` file contains the `domain_name` parameter and that it matches your domain name. After you change it, run `bin/console cache:clear --env=prod` to clear the cache.

https://doc.wallabag.org/en/admin/parameters.html
