### ISSUE TITLE
clear name when extracting the package with all dependencies inside

### ISSUE THREAD

**Issue by oupala** [wallabag/wallabag#5344]
**Is your feature request related to a problem? Please describe.**

When extracting the package with all dependencies inside, the resulting directory is simply a version number - currently `2.4.2`. It makes Wallabag very hard to find if the root folder is full of files.

**Describe the solution you'd like**

It would be really clearer if the resulting directory was named with the name of Wallabag and then the version number. For example: `wallabag-2.4.2`.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by j0k3r** [comment]
That's a good idea, feel free to update the `release.sh` script.
https://github.com/wallabag/wallabag/blob/master/scripts/release.sh

**Comment by oupala** [comment]
I just did it in #5542.
