### ISSUE TITLE
Hypothes.is Integeration

### ISSUE THREAD

**Issue by katana-hydra** [wallabag/wallabag#5345]
**Is your feature request related to a problem? Please describe.**
Annotation function is pretty basic at present.
**Describe the solution you'd like**
Integrate Hypothes.is 
**Describe alternatives you've considered**
1. hypothes.is as an annotation tool
2. export article or annotation or both
**Additional context**

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/issues/5484#issuecomment-1006873829
