### ISSUE TITLE
Unable to complete 2FA authentication and login to https://app.wallabag.it/

### ISSUE THREAD

**Issue by MagicAndi** [wallabag/wallabag#5349]
This issue is occurring on the https://app.wallabag.it/ site

### Details

When I try and login to the Wallabag application, I enter my username (MagicAndi) and password as normal, and I am taken to the 2FA prompt as expected. When I enter my 2FA token and hit return, I see a 500 error screen with the following message:

_Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused._ 

See attached screenshot.
<img width="833" alt="Wallabag" src="https://user-images.githubusercontent.com/5617999/125447206-62dbb6c4-3ebf-4010-a529-d511fc1b4df8.png">

I've tried to login several times over the past 24 hours, and I still get the smae error. I have tried using different browsers (Firefox, Edge), and again, same result.

### What steps will reproduce the bug?

- Login to Wallabag at https://app.wallabag.it/ with a 2FA enabled account
- Enter username and password, and press enter
- Then 2FA token, and press enter

**Comment by Kdecherf** [comment]
@nicosomb ^

**Comment by nicosomb** [comment]
I sent you an email. I close this issue.
