### ISSUE TITLE
Internal Server Error when adding a new link

### ISSUE THREAD

**Issue by dlastov** [wallabag/wallabag#5351]
An error below is displayed when adding a link to the following web site: https://www.centralepneus.lu/ .
Other links I can add without problems.

500: Internal Server Error

An exception occurred while executing 'INSERT INTO `wallabag_entry` (uid, title, url, hashed_url, origin_url, given_url, hashed_given_url, is_archived, archived_at, is_starred, content, created_at, updated_at, published_at, published_by, starred_at, mimetype, language, reading_time, domain_name, preview_picture, http_status, headers, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "CentralePneus.lu : Pneu pas cher", "https:\/\/www.centralepneus.lu", "75265cdad736f6621ccb4131f8d57f7fdd7b3eae", null, "https:\/\/www.centralepneus.lu", "75265cdad736f6621ccb4131f8d57f7fdd7b3eae", 0, null, 0, "<div class=\"col-md-6 col-xs-12\"><p><strong class=\"red\">Pour payer vos pneus moins chers !<\/strong> CentralePneus analyse les prix des concurrents et s'aligne sur les prix plus bas. Nos clients profitent des meilleurs prix.<\/p><p><strong class=\"red\">Pour un montage simple et rapide.<\/strong> Nos <a href=\"https:\/\/montage.centralepneus.lu\/\" class=\"red\" target=\"_blank\">stations de montage partenaires<\/a> vous accueillent partout au Luxembourg. Comparez les tarifs et avis en ligne. Livraison directement en station ou \u00e0 l\u2019adresse de votre choix.<\/p><p><strong class=\"red\">Pour effectuer une transaction s\u00e9curis\u00e9e.<\/strong> Notre site est couvert par le protocole HTTPS\/SSL. Nous ne conservons pas vos num\u00e9ros de carte bancaire. Notre charte de confidentialit\u00e9 vous assure un haut niveau de protection de vos donn\u00e9es.<\/p><br \/><\/div><div class=\"col-md-6 col-xs-12\"><p><strong class=\"red\">Pour avoir un grand choix.<\/strong> Quel que soit votre v\u00e9hicule et votre budget, nous avons des pneus qui correspondent \u00e0 vos besoins. <a href=\"https:\/\/www.centralepneus.lu\/pneu-auto-205-55-16\/\" class=\"red\">Pneus auto<\/a>, <a href=\"https:\/\/www.centralepneus.lu\/pneu-auto-235-60-16-100-H\/\" class=\"red\">SUV\/4x4<\/a>, <a href=\"https:\/\/www.centralepneus.lu\/pneu-auto-195-70-15\/\" class=\"red\">utilitaires<\/a>, <a href=\"https:\/\/www.centralepneus.lu\/pneu-moto-120-70-17\/\" class=\"red\">moto<\/a>, <a href=\"https:\/\/www.centralepneus.lu\/pneu-quad-25-8-12\/\" class=\"red\">quad<\/a>... tout est en ligne !<\/p><p><strong class=\"red\">Pour b\u00e9n\u00e9ficier d'une livraison gratuite<\/strong> \u00e0 partir de 2 pneus voitures, SUV, utilitaires... et \u00e0 partir de 1 pneu moto. Les num\u00e9ros de colis vous permettent de suivre la livraison de votre commande.<\/p><p><strong class=\"red\">Pour confier votre commande \u00e0 une entreprise de confiance.<\/strong> Chaque jour, CentralePneus exp\u00e9die des milliers de commandes avec succ\u00e8s. La satisfaction de nos clients est notre priorit\u00e9.<\/p><br \/><\/div>", "2021-07-18 20:18:43", "2021-07-18 20:18:43", null, "N;", null, "text\/html; charset=utf-8", "fr_LU", 0, "www.centralepneus.lu", null, 200, "\x61\x3a\x39\x3a\x7b\x73\x3a\x34\x3a\x22\x64\x61\x74\x65\x22\x3b\x73\x3a\x32\x39\x3a\x22\x53\x75\x6e\x2c\x20\x31\x38\x20\x4a\x75\x6c\x20\x32\x30\x32\x31\x20\x31\x38\x3a\x31\x38\x3a\x34\x33\x20\x47\x4d\x54\x22\x3b\x73\x3a\x36\x3a\x22\x73\x65\x72\x76\x65\x72\x22\x3b\x73\x3a\x36\x3a\x22\x41\x70\x61\x63\x68\x65\x22\x3b\x73\x3a\x31\x30\x3a\x22\x73\x65\x74\x2d\x63\x6f\x6f\x6b\x69\x65\x22\x3b\x73\x3a\x32\x38\x35\x3a\x22\x63\x70\x3d\x66\x30\x62\x36\x62\x33\x39\x63\x35\x66\x64\x32\x37\x37\x39\x61\x33\x39\x32\x34\x37\x65\x30\x65\x37\x31\x30\x33\x39\x64\x36\x37\x62\x62\x35\x65\x35\x37\x31\x62\x7c\x23\x7c\x31\x36\x32\x39\x32\x32\x34\x33\x32\x33\x7c\x23\x7c\xac\xe4\x7f\x5d\x69\xda\xf4\xda\x81\x3d\x5a\x19\xef\x99\x84\x21\xcf\x17\x20\x73\xa8\x93\x6d\x40\xd8\x14\x0a\x0d\x79\x12\xdd\x27\x9f\x03\x70\xdf\xe6\x8e\xb4\xa4\xf1\xf7\xaa\xf5\xbe\xbc\x8a\xaa\x16\xcf\x57\xd0\x19\x27\xb5\x22\xd2\xdb\x1c\xd7\x09\x4b\x20\xb9\x7c\x23\x7c\x39\x36\x33\x31\x66\x37\x64\x39\x36\x38\x37\x31\x31\x34\x39\x33\x64\x33\x66\x37\x64\x35\x33\x61\x32\x63\x38\x39\x39\x36\x30\x33\x61\x39\x64\x36\x30\x64\x61\x32\x7c\x23\x7c\x63\x33\xdc\xec\x2a\xaf\xe5\x29\x7d\x99\x48\xb4\x6d\x1a\x5c\x89\x3b\x20\x65\x78\x70\x69\x72\x65\x73\x3d\x54\x75\x65\x2c\x20\x31\x37\x2d\x41\x75\x67\x2d\x32\x30\x32\x31\x20\x31\x38\x3a\x31\x38\x3a\x34\x33\x20\x47\x4d\x54\x3b\x20\x4d\x61\x78\x2d\x41\x67\x65\x3d\x32\x35\x39\x32\x30\x30\x30\x3b\x20\x70\x61\x74\x68\x3d\x2f\x3b\x20\x64\x6f\x6d\x61\x69\x6e\x3d\x2e\x63\x65\x6e\x74\x72\x61\x6c\x65\x70\x6e\x65\x75\x73\x2e\x6c\x75\x3b\x20\x48\x74\x74\x70\x4f\x6e\x6c\x79\x22\x3b\x73\x3a\x31\x35\x3a\x22\x78\x2d\x6d\x6f\x64\x2d\x70\x61\x67\x65\x73\x70\x65\x65\x64\x22\x3b\x73\x3a\x31\x31\x3a\x22\x31\x2e\x31\x33\x2e\x33\x35\x2e\x32\x2d\x30\x22\x3b\x73\x3a\x34\x3a\x22\x76\x61\x72\x79\x22\x3b\x73\x3a\x31\x35\x3a\x22\x41\x63\x63\x65\x70\x74\x2d\x45\x6e\x63\x6f\x64\x69\x6e\x67\x22\x3b\x73\x3a\x32\x37\x3a\x22\x61\x63\x63\x65\x73\x73\x2d\x63\x6f\x6e\x74\x72\x6f\x6c\x2d\x61\x6c\x6c\x6f\x77\x2d\x6f\x72\x69\x67\x69\x6e\x22\x3b\x73\x3a\x31\x3a\x22\x2a\x22\x3b\x73\x3a\x31\x33\x3a\x22\x63\x61\x63\x68\x65\x2d\x63\x6f\x6e\x74\x72\x6f\x6c\x22\x3b\x73\x3a\x31\x39\x3a\x22\x6d\x61\x78\x2d\x61\x67\x65\x3d\x30\x2c\x20\x6e\x6f\x2d\x63\x61\x63\x68\x65\x22\x3b\x73\x3a\x31\x34\x3a\x22\x63\x6f\x6e\x74\x65\x6e\x74\x2d\x6c\x65\x6e\x67\x74\x68\x22\x3b\x73\x3a\x36\x3a\x22\x32\x37\x33\x36\x32\x37\x22\x3b\x73\x3a\x31\x32\x3a\x22\x63\x6f\x6e\x74\x65\x6e\x74\x2d\x74\x79\x70\x65\x22\x3b\x73\x3a\x32\x34\x3a\x22\x74\x65\x78\x74\x2f\x68\x74\x6d\x6c\x3b\x20\x63\x68\x61\x72\x73\x65\x74\x3d\x75\x74\x66\x2d\x38\x22\x3b\x7d", 24580]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xAC\xE4]i\xDA...' for column `app_wallabag_it`.`wallabag_entry`.`headers` at row 1

**Comment by j0k3r** [comment]
Duplicate of #5455
