### ISSUE TITLE
Documentation / List of available sites/paywalls can be fetched via credentials

### ISSUE THREAD

**Issue by TontonMollo** [wallabag/wallabag#5356]
Dears,

Would-you please update the documentation section on the hosted version of wallabag : https://app.wallabag.it , for detail the list of sitesµ/paywalls that can be fetched via credentials.

The documentation is a bit outdated : 

List of supported websites
Les Jours
Mediapart
Le Monde Diplomatique
Next INpact
Courrier International

Soon:

Alternatives Économiques
Telegraph.co.uk
Le Figaro
Le Monde
L'Équipe

https://www.wallabag.it/en/doc

Thanks !

**Comment by j0k3r** [comment]
There is a pinned issue about it https://github.com/wallabag/wallabag/issues/3439
But I agree, wallabag.it doc should be updated.
Poke @nicosomb
