### ISSUE TITLE
scheb/two-factor-bundle is outdated

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#5359]
The scheb/two-factor-bundle library is outdated and it will be in EOL in November 2021 : https://github.com/scheb/two-factor-bundle

We need to migrate to https://github.com/scheb/2fa

**Comment by tcitworld** [comment]
Note : The not EOL version requires Symfony 4.4.

**Comment by Kdecherf** [comment]
Yeah, fixing this issue implies to complete the upgrade to sf4.4 at least (I'm working on it but it will take time)

**Comment by j0k3r** [comment]
Closing because we'll update it when (if) we use sf >= 4.4
