### ISSUE TITLE
can't retrieve article contents from jacobinmag.com

### ISSUE THREAD

**Issue by odelaf** [wallabag/wallabag#5374]
Hi,

It works on f43.me but not in wallabag

https://jacobinmag.com/2020/11/covid-19-privacy-big-data-surveillance

thx

**Comment by sfirke** [comment]
+1, any Jacobin article I try works on f43 but not Wallabag.  Additionally, I believe this is a new behavior and Jacobin articles could be retrieved until recently.

**Comment by sfirke** [comment]
This issue is now resolved, the above Jacobin.com URL and others now can be read successfully on Wallabag.it instance.  This issue can be closed.
