### ISSUE TITLE
Easy setup for Apps

### ISSUE THREAD

**Issue by kevmeyer** [wallabag/wallabag#538]
Until we have OAuth (or something else) we could add a lightweight setup for apps.
My proposal:  
-    App sends the user to user's wallabag entry-point, like: 
  `http://my-wallabag-server/?action=iOS-setup`
-    after successful login the wallabag redirects the user back to the app (providing ID and token), e.g.:  
  `wallabag://?userID=1&token=a1b2c3s1337`

No more token copy pasting, and no QR code generation needed.
(The token should be encoded, as it can contain pretty everything)

What do you think?

**Comment by nicosomb** [comment]
See https://github.com/wallabag/wallabag/pull/2523
