### ISSUE TITLE
Automatic export to a folder

### ISSUE THREAD

**Issue by mbhkoay** [wallabag/wallabag#5388]
Would like to have a central location for all articles where cross referencing and reading and taking notes can be done. 

Using Joplin for that at the moment, which have a plugin called hotfolder that will automatically import notes from a selected folder. 

With automatic export of all articles saved to Wallabag, it would be possible to seamlessly integrate both platforms together.

**Comment by j0k3r** [comment]
Folder from where? Your computer? The wallabag's server?
