### ISSUE TITLE
Open all external links in new tab in Config

### ISSUE THREAD

**Issue by rakleed** [wallabag/wallabag#5400]
**Is your feature request related to a problem? Please describe.**
All external links in Config open in the same window, which is inconvenient.

**Describe the solution you'd like**
Open all external links in Config in a new window.

**Describe alternatives you've considered**

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target

**Comment by j0k3r** [comment]
Feel free to provide a PR to fix it!

**Comment by wyntonfranklin** [comment]
hi, i would like to do this

**Comment by j0k3r** [comment]
@wyntonfranklin please do.
