### ISSUE TITLE
SSL error when specific URI is added

### ISSUE THREAD

**Issue by korkosson** [wallabag/wallabag#5401]
### Environment

* **Version**: 2.4.2
* **Installation**: Apache
* **PHP version**: 7.3.29-1
* **OS**: Debian 10
* **Database**: MariaDB/MySQL
* **Parameters**:

### What steps will reproduce the bug?
When any URL from the addres [vytapeni.tzb-info.cz](https://vytapeni.tzb-info.cz) is added, following error is reported in Apache error.log:
`[Thu Aug 26 21:49:31.392409 2021] [mpm_prefork:notice] [pid 2784] AH00169: caught SIGTERM, shutting down`
`[Thu Aug 26 21:49:31.637263 2021] [mpm_prefork:notice] [pid 7602] AH00163: Apache/2.4.38 (Debian) OpenSSL/1.1.1d configured -- resuming normal operations`
`[Thu Aug 26 21:49:31.637378 2021] [core:notice] [pid 7602] AH00094: Command line: '/usr/sbin/apache2'`
`[Thu Aug 26 21:49:54.675946 2021] [core:notice] [pid 7602] AH00052: child pid 7607 exit signal Segmentation fault (11)`
and web browser reports "Secure Connection Failed" error.

Saving works fine for all other URLs that I've tried so far.

**Comment by j0k3r** [comment]
Got a problem too
```
cURL error 7: Failed to connect to vytapeni.tzb-info.cz port 443 after 151 ms: Bad file descriptor
```
