### ISSUE TITLE
Fetching lemonde.fr articles behind a pay wall doesn't work anymore

### ISSUE THREAD

**Issue by biva** [wallabag/wallabag#5422]
Fetching lemonde.fr articles behind a pay wall doesn't work anymore. It worked until recently, maybe a few days/weeks?

I checked my password, still valid. And I checked other websites (mediapart): the paywall feature works for them.

I can provide credentials if needed.

(following the original issue https://github.com/wallabag/wallabag/issues/2909)

**Comment by nicosomb** [comment]
I can confirm this issue on wallabag.it. 
It still worked on August, 28st.

**Comment by Kdecherf** [comment]
Confirmed on my own instance

**Comment by biva** [comment]
Congrats @j0k3r , it works for me as well. Thank you so much for your reactivity!

**Comment by techexo** [comment]
Is it just me or did they rolled back the change now?

**Comment by techexo** [comment]
@Kdecherf FYI, I just had to roll back your change because it seems that Le Monde just undid the changes they made... The fields names are back to `connection[mail]` and `connection[password]`!

**Comment by Kdecherf** [comment]
@techexo yes, I saw that too on saturday :shrug:

**Comment by biva** [comment]
Pfffff :( Is it possible to have both possibilities in the file, and the parser tries both?

**Comment by techexo** [comment]
Yeah, they changed it back. I don't know if it's some kind of anti-grabbing technique or if they rolled-out something not finished and undid their changes at first, but I sure hope they stop yoyo-ing between the versions!

**Comment by Kdecherf** [comment]
@techexo I've opened a new PR to reintroduce the change: https://github.com/fivefilters/ftr-site-config/pull/906
