### ISSUE TITLE
how to install static version

### ISSUE THREAD

**Issue by oupala** [wallabag/wallabag#5426]
In the issue #3083, @nicosomb told me that it was useless to process to installation:

> Yes, as a wallabag core developer, I'm sure that wallabag:install is not mandatory when you download the archive. Please read the documentation: https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting

However, the doc is telling me to process to installation:

> You must create your first user by using the command php bin/console wallabag:install --env=prod If an error occurs at this step due to bad settings, you must clear the cache with php bin/console cache:clear --env=prod before you try again the previous command.

As the issue #3083 is 4 years old, has the install process of Wallabag static changed since 4 years? Or is there a mistake in the doc?

**Comment by j0k3r** [comment]
I think the process changed.
You now need to run the `wallabag:install` command as the doc says.
https://github.com/wallabag/doc/commit/dffafcb170c5b5cf78b838747d43649b901a8fd8
