### ISSUE TITLE
missing libraries in the static package

### ISSUE THREAD

**Issue by oupala** [wallabag/wallabag#5427]
### Environment

* **Version**: 2.4.2
* **Installation**: static
* **PHP version**: 7.3.29-1~deb10u1
* **OS**: debian (raspbian)
* **Database**: sqlite
* **Parameters**: n/a

I think that this issue comes from some missing libraries in the static package.

### What steps will reproduce the bug?

```log
>sudo -H -u www-data bash -c 'bin/console wallabag:user:list'
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
...
#4 /home/user/apps/2.4.2/bin/console(27): Symfo in /home/user/apps/2.4.2/app/AppKernel.php on line 52
```

This can be fixed by commenting the line 52:

```php
$bundles[] = new Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle();
```

I then have another issue:

```
>sudo -H -u www-data bash -c 'bin/console wallabag:user:list'
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "MakerBundle" from namespace "Symfony\Bundle\MakerBundle".
...
#4 /home/user/apps/2.4.2/bin/console(27): Symfo in /home/user/apps/2.4.2/app/AppKernel.php on line 59
```

This can be fixed by commenting the line 59:

```php
$bundles[] = new Symfony\Bundle\MakerBundle\MakerBundle();
```

Then it becomes possible to list users...

**Comment by nicosomb** [comment]
Hello @oupala. 

You need to run this command `sudo -H -u www-data bash -c 'bin/console wallabag:user:list -e prod'`. 

Withou the last argument, you are in "development" environment and it's not ok.

**Comment by oupala** [comment]
Oups, you're right, it works like a charm when you add `-e prod` or ` --env=prod`.

Furthermore, it was written [in the doc](https://doc.wallabag.org/en/admin/console_commands.html):

> If you're in a production environment, remember to add `--env=prod` to each command.

Can you please elaborate a bit about the reason of this parameter when applied on a *prod* environment?

**Comment by j0k3r** [comment]
By default the `dev` environment is used.

**Comment by oupala** [comment]
Ok, thanks.

I still do not understand why listing users is not possible on a dev environment...

What are the differences between a prod environment and a dev environment?

**Comment by j0k3r** [comment]
Because the static package does not include development stuff.
The static package aims as a production package.

**Comment by oupala** [comment]
Ok, so development is not possible with the static package.

And hence the static package can only be used as a prod environment.

Am I right?

**Comment by j0k3r** [comment]
That's the idea.

**Comment by oupala** [comment]
Ok, right.

I think this should be explicitly written in the doc, on the [installation page](https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting):

> The static package requires each command to be appended by `--env=prod` as the static package is only usable as a prod environment (dev environment is not supported and won't work at all).

And by the way, the documentation is also saying something wront, that "(SQLite is no longer supported from version 2.4)". See [this comment](https://github.com/wallabag/wallabag/issues/2766#issuecomment-490918115) for memory.

**Comment by j0k3r** [comment]
Good idea!
Feel free to update it https://github.com/wallabag/doc

**Comment by oupala** [comment]
Just did it in [pull request #152](/wallabag/doc/pull/152).
