### ISSUE TITLE
Custom CSS snippets

### ISSUE THREAD

**Issue by xplosionmind** [wallabag/wallabag#5487]
**Is your feature request related to a problem? Please describe.**
Not related to any bug or problem

**Describe the solution you'd like**
Adding the possibility to type (in config, or somewhere in the settings) custom CSS snippets, to customize appearance.

**Describe alternatives you've considered**
Changing the CSS file of the theme directly, by SSHing into the server where Wallabag is hosted.

**Additional context**
The current workaround breaks when Wallabag is updated.

**Comment by j0k3r** [comment]
It already exists
https://doc.wallabag.org/en/admin/custom_css.html

**Comment by xplosionmind** [comment]
Thank you! I missed that!

Nevertheless, I believe the issue is still relevant since it would be nice if not only server admins, but end users too, could add CSS snippets from their personal settings, in the GUI.
