### ISSUE TITLE
"Download Images locally:1" --> 500:Internal Server Error

### ISSUE THREAD

**Issue by utrost** [wallabag/wallabag#5488]
### Environment

* **Version**:Version: 2.4.2
* **Installation**: Selfhosted, Non-Docker, Shared Hoster (Hetzner)
* **PHP version**:7.4, 7.3- ImageMagick enabled.
* **OS**:Linux
* **Database**:MySQL
* **Parameters**:

<details>
  <summary>500: Internal Server Error on ALL pages if "Download images locally" is set to 1</summary>
If I enable "Load images locally" by setting it's value to 1 I always get, example page:  https://github.com/wallabag

500:Internal Sever Error
Call to a member function bindHandles() on null

Remark: The clipped page appaers some minutes later in Wallabag. So....somehow it's working, despite the error message.
</details>

### What steps will reproduce the bug?

1. Enable  "Download Images locally"
2. Try to capture any website
![Clipboard01](https://user-images.githubusercontent.com/46228819/142884173-2b487d7c-f00c-4e7f-8332-ad31250d7b33.jpg)
![Clipboard02](https://user-images.githubusercontent.com/46228819/142884179-2add20a1-a257-4810-88a8-4318019cf8e6.jpg)

**Comment by Kdecherf** [comment]
Hello @utrost,
Could you specify wallabag's version and an example URL please?

**Comment by utrost** [comment]
Example page: https://github.com/wallabag
Where do I find the Wallabag Version?

**Comment by Kdecherf** [comment]
You can find it on the "about" page (link in the footer of any page)

**Comment by utrost** [comment]
Version: Version: 2.4.2

**Comment by utrost** [comment]
Remark: The clipped page appears some minutes later in Wallabag. So....somehow it's working, despite the error message.

**Comment by j0k3r** [comment]
Can you check logs and tell us what you find?
