### ISSUE TITLE
Zotero integration

### ISSUE THREAD

**Issue by xplosionmind** [wallabag/wallabag#5500]
**Is your feature request related to a problem? Please describe.**
\-

**Describe the solution you'd like**
I would like posts that are tagged in a certain way, specified by the user, to be added to Zotero’s library.

**Describe alternatives you've considered**
Manually adding to Zotero

**Additional context**
\-

**Comment by j0k3r** [comment]
I don't know what Zotero is but for now we don't provide webhook or something like that to ping external service.
Kinda duplicate https://github.com/wallabag/wallabag/issues/500

**Comment by xplosionmind** [comment]
If it is just “for now”, why not leaving this issue open?

Zotero is among the most diffused academic citation software, and it is open source.

Not only implementing Zotero would be awesome, but I think it could greatly increase the Wallabag user-base, since many students and scholars might find this implementation crucial for their research workflow.
