### ISSUE TITLE
Just highlight, dont annotate

### ISSUE THREAD

**Issue by putzwasser** [wallabag/wallabag#5504]
**Is your feature request related to a problem? Please describe.**
Wallabag has the possibility to annotate parts of the text. If you select it, the button shows up.
![image](https://user-images.githubusercontent.com/26040044/145383762-b554049d-d89b-4b22-8e32-018898c91a64.png)

**Describe the solution you'd like**
It would be nice, to have a second button that just highlights the text.
I know that I can just create an empty annotation, but it is a click more—every time. I'd like to get rid of the extra click.
Another option were to create shortcuts for annotating/highlighting the text.
E.g. `h` for highlight, when text is selected (because `a` is already taken for archive).
Or `t` + `h` for text highlight and `t` + `a` for text annotate.
#2495
#512

**Comment by j0k3r** [comment]
That's a good idea and I think integrating Hypothesis will resolve the issue, so I'm closing in favor of #5484
