### ISSUE TITLE
500: Internal Server Error after installation : datefmt_create: no such time zone: 'Europe/paris'

### ISSUE THREAD

**Issue by Flashpok** [wallabag/wallabag#5508]
After the installation and first connexion, this message : 

  ```
500: Internal Server Error

An exception has been thrown during the rendering of a template ("datefmt_create: no such time zone: 'Europe/paris': U_ILLEGAL_ARGUMENT_ERROR").
  ```

### Environment

* **Version**: fresh installation (14 december)
* **Installation**: I used git clone
* **PHP version**:  7.4.25 
* **OS**: debian 11
* **Database**:  10.5.12-MariaDB-0+deb11u1 - Debian 11 
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
 database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: ****
    database_user: ******
    database_password: ***
    database_path: null
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 'https://***'
    server_name: ***
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: fr
    secret: **
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
  ```
</details>
Thank you for your help :!!

Ps: I confirm that the servers's time zone is well configured !

**Comment by tcitworld** [comment]
Should it be `Europe/Paris` with a capital letter ?

**Comment by Flashpok** [comment]
> Should it be `Europe/Paris` with a capital letter ?

Perhaps... But how ? I changed the server's "timedatectl status" with 'Time zone: Europe/Brussels', but no change... same error (and strangely, I have the same message : "datefmt_create: no such time zone: 'Europe/paris". Can you help me ? Or a browser thing ?

**Comment by Flashpok** [comment]
Any help please ?

**Comment by Kdecherf** [comment]
Hello @Flashpok,

Timezone in PHP is not handled by timedatectl. You should check that the parameter `date.timezone` has value "Europe/Paris" in php.ini or equivalent file.

**Comment by Flashpok** [comment]
> Hello @Flashpok,
> 
> Timezone in PHP is not handled by timedatectl. You should check that the parameter `date.timezone` has value "Europe/Paris" in php.ini or equivalent file.

Yes, It works !!! Thank you !! (I edit 'paris' with 'Paris')
