### ISSUE TITLE
Provide an endpoint to save a page's html directly

### ISSUE THREAD

**Issue by kolaente** [wallabag/wallabag#5559]
**Is your feature request related to a problem? Please describe.**
Using wallabag with sites that are js powered only (like notion) usually does not work because the content has to be rendered by a web browser. When the wallabag server tries to access the site to save it there's no content retrieved.

**Describe the solution you'd like**
A possible solution would be for wallabag to provide an endpoint which takes the full html content from the page I want to save. The server would still need to do all the cleanup to get the html in the same format as all other articles but would not try to fetch it from the server. This would require additional work in the addons to let them send the html content with the page url, title, etc.

I think this could also solve the paywall problem without requiring a lot of integrations for all kinds of sites in wallabag itself.

If there's interest in this, I could send a PR.

**Comment by Kdecherf** [comment]
I started working on a dirty fix for this feature a few month ago.

I'm using the WebScrapBook[^1] extension to capture the content of a page within my browser and I've added a quick'n'dirty support for the WebScrapBook backend[^2] to wallabag.

There's also a mandatory work on Graby which is waiting for reviews: https://github.com/j0k3r/graby/pull/274

[^1]: https://github.com/danny0838/webscrapbook
[^2]: https://pypi.org/project/webscrapbook/

**Comment by kolaente** [comment]
@Kdecherf oh that sounds very nice!

**Comment by Ruakij** [comment]
This is such a necessary feature and i cant believe it was very hard to implement either.
Even "Save Page as Html" from my Browser works perfectly fine, but Wallabag still doesnt have this?

**Comment by j0k3r** [comment]
@Kdecherf it has been merged https://github.com/wallabag/wallabag/pull/5593

**Comment by Kdecherf** [comment]
@kolaente you can now provide html content of a page on the POST `api/entries` endpoint, see https://app.wallabag.it/api/doc/

**Comment by ajkessel** [comment]
Is there any end-user support for this capability now? Does a new feature need to be added to the browser extensions so the page HTML can be provided to Wallabag?

**Comment by Kdecherf** [comment]
@ajkessel the browser extension *wallabagger* has this feature since v1.14.0, see https://kdecherf.com/blog/2023/08/02/fetch-content-from-browser-on-demand-with-wallabagger/
