### ISSUE TITLE
Wrong display in wallabag (shahinkalantari.com)

### ISSUE THREAD

**Issue by Monirzadeh** [wallabag/wallabag#5595]
We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:

[*] I've tried myself without success
 I've replaced HOST in the issue title with the host of the URL that can't be fetched (ie: nytimes.com, 20minutes.fr, bbc.com, etc.)
Content related:

URL: [[full url of the content](https://shahinkalantari.com/%D9%86%D8%AB%D8%B1%D9%87%D8%A7%DB%8C-%DB%8C%D9%88%D9%85%DB%8C%D9%87-09/)]
wallabag version: [ 2.4.2]
Describe what's wrong:
it is not return content and https://f43.me/feed/test return warrning too
```
We failed to make this item readable, the default text from the feed item will be displayed instead.
```

do you need any specific log?

**Comment by j0k3r** [comment]
Could you please use the template and answer question inside it? Thanks.
https://github.com/wallabag/wallabag/issues/new?assignees=&labels=Site+Config&template=1-fetching-content.md&title=Wrong+display+in+wallabag+%28HOST%29

**Comment by Monirzadeh** [comment]
> @Monirzadeh thanks for the referer I was wondering :) You could submit a PR on the doc repo

done (sorry it is not clean)

**Comment by HolgerAusB** [comment]
a simple `body: //main` makes it readable for f43.me and two more lines brings back the right-to-left orientation:

```
body: //main
find_string: <main
replace_string: <main dir="rtl"
```
@Monirzadeh, would you please check this with f43.me ? I can't read the text, so I don't know if it is complete or maybe to much content. You should also test some other articles on that site, maybe with images and report, if something is missing, with URL.
