### ISSUE TITLE
Many 502 errors (segfault)

### ISSUE THREAD

**Issue by hydrargyrum** [wallabag/wallabag#5613]
### Environment

* **Version**: `wallabag/wallabag:latest` from dockerhub
* **Installation**: docker image
* **PHP version**: see docker image
* **OS**: linux (docker image)
* **Database**: `postgres:12` docker image

### What steps will reproduce the bug?

Just "sync local changes" from android app. Recently I noticed several links failed to be shared from android app, now nothing can be shared anymore, and the app fails to sync anyway. Each sync creates a 502 error.

Extract from docker logs:
```
server_1  | 172.23.0.2 - - [11/Feb/2022:20:00:09 +0000] "POST /oauth/v2/token HTTP/1.1" 200 245 "-" "okhttp/4.9.1"
server_1  | 2022/02/11 20:00:09 [error] 258#258: *21 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.23.0.2, server: _, request: "POST /api/entries.json HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "XXX.redacted"
server_1  | 172.23.0.2 - - [11/Feb/2022:20:00:09 +0000] "POST /api/entries.json HTTP/1.1" 502 150 "-" "okhttp/4.9.1"
server_1  | 2022/02/11 20:00:12 [error] 258#258: *21 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.23.0.2, server: _, request: "POST /api/entries.json HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "XXX.redacted"
server_1  | 172.23.0.2 - - [11/Feb/2022:20:00:12 +0000] "POST /api/entries.json HTTP/1.1" 502 150 "-" "okhttp/4.9.1"
```

Extract from `/var/log/php-fpm.log` in the docker container:
```
[11-Feb-2022 06:26:18] WARNING: [pool www] child 276 exited on signal 11 (SIGSEGV) after 27.986230 seconds from start
[11-Feb-2022 06:26:18] NOTICE: [pool www] child 280 started
[11-Feb-2022 08:29:21] WARNING: [pool www] child 280 exited on signal 11 (SIGSEGV) after 7382.325715 seconds from start
[11-Feb-2022 08:29:21] NOTICE: [pool www] child 282 started
[11-Feb-2022 13:54:25] WARNING: [pool www] child 282 exited on signal 11 (SIGSEGV) after 19504.230974 seconds from start
[11-Feb-2022 13:54:25] NOTICE: [pool www] child 284 started
[11-Feb-2022 20:00:09] WARNING: [pool www] child 284 exited on signal 11 (SIGSEGV) after 21944.403981 seconds from start
[11-Feb-2022 20:00:09] NOTICE: [pool www] child 293 started
[11-Feb-2022 20:00:12] WARNING: [pool www] child 278 exited on signal 11 (SIGSEGV) after 48854.492929 seconds from start
[11-Feb-2022 20:00:12] NOTICE: [pool www] child 295 started
```

I'm using a `caddy` container as a reverse proxy.

**Comment by Kdecherf** [comment]
@hydrargyrum could you check again using the last released docker image (2.4.3)?

Also could you take a look at app logs in `/var/www/html/var/logs/prod.log`?

**Comment by hydrargyrum** [comment]
> @hydrargyrum could you check again using the last released docker image (2.4.3)?

Yes, unfortunately the 502s are still there and `php-fpm.log` contains roughly the same stuff.

> Also could you take a look at app logs in `/var/www/html/var/logs/prod.log`?

This file does not seem to exist and `find / -name prod.log` doesn't find it anywhere.

**Comment by hydrargyrum** [comment]
@Kdecherf, is there any way to have more logs to find what's going on? As is, wallabag became unusable for me.

**Comment by Kdecherf** [comment]
@hydrargyrum does it occur with the last release 2.5.2?

**Comment by hydrargyrum** [comment]
@Kdecherf, I had less usage of wallabag recently but I didn't notice any recent 502. Maybe the issue was fixed then.

**Comment by Kdecherf** [comment]
@hydrargyrum I'll close it then, you can open a new issue if it occurs again
