### ISSUE TITLE
Save Recepies from rezeptwelt.de

### ISSUE THREAD

**Issue by aschilling** [wallabag/wallabag#562]
Hi everybody,

I am really amazed how well the data extraction in wallabag works. It is even that good that I started to archive my cook recipes with it. However, one thing at the rezeptwelt.de site which does not work yet, is to extract also the ingredients part. Would it be possible to extract for articles from this site also the div:

    <div class="global-active ingredients-box">

Thanks

Andy

**Comment by j0k3r** [comment]
Works fine on the v2
