### ISSUE TITLE
It should be nice to have a merging tags tool 

### ISSUE THREAD

**Issue by franck-paul** [wallabag/wallabag#5620]
For example, I have `font` and `fonts` tags and I would like to merge to 'fonts' them without editing every posts which use those tags.

**Comment by Kdecherf** [comment]
@franck-paul there's an undocumented way to achieve that.
We recently added the rename functionality on tags.
You can rename of these tags into the other and wallabag will merge articles.

**Comment by franck-paul** [comment]
Nice, thanks for the tip!
