### ISSUE TITLE
some dependencies have moved or are deprecated

### ISSUE THREAD

**Issue by hobbes** [wallabag/wallabag#5621]
Hello, 

today, while upgrading wallabag to the latest, I noticed that some dependencies have moved or are not maintained anymore:

Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Package doctrine/doctrine-cache-bundle is abandoned, you should avoid using it. No replacement was suggested.
Package liip/theme-bundle is abandoned, you should avoid using it. Use sylius/theme-bundle instead.
Package scheb/two-factor-bundle is abandoned, you should avoid using it. Use scheb/2fa-bundle instead.
Package sensiolabs/security-checker is abandoned, you should avoid using it. Use https://github.com/fabpot/local-php-security-checker instead.
Package sensio/distribution-bundle is abandoned, you should avoid using it. No replacement was suggested.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.

Might be a good idea to keep a list, and keep it as short as possible.

Thanks,
-- 
Rémi

**Comment by j0k3r** [comment]
Yeah we are aware of that.
We are thinking on who we could manage to updated properly.
The main problem is that we have a lot of deprecation message to fix and we are still using Symfony 3.4.

**Comment by yguedidi** [comment]
@j0k3r so if I understand currently, it's the deprecation notices that block the Symfony upgrade?

**Comment by j0k3r** [comment]
Yep

**Comment by yguedidi** [comment]
I want to contribute, I'll open PRs in the following days I think :)

**Comment by j0k3r** [comment]
Most of them have been updated or are in the process of being updated.
Some of them won't be updated because there is no replacement and we don't have an alternative yet.
