### ISSUE TITLE
Tag autosuggest

### ISSUE THREAD

**Issue by franck-paul** [wallabag/wallabag#5624]
When adding a (or several) tag(s) to an article, it should be nice to have an autosuggest (from already created tags) at least 2 or 3 characters are entered.

**Comment by Kdecherf** [comment]
Duplicate of #5236

**Comment by franck-paul** [comment]
Oh sorry for this duplicated issue!

I searched for "suggest tags" "autosuggest tag" … but not for "existing", "show" and "labels" :-)

**Comment by Kdecherf** [comment]
No worries :)
