### ISSUE TITLE
HTTP 400 when trying to grab content from zeit.de

### ISSUE THREAD

**Issue by bwa-** [wallabag/wallabag#5633]
For some reason, I cannot get the content from zeit.de pages anymore. It did work until last night, now I get an HTTP 400 whenever I try getting the site.
I did follow all the steps in [the docs](https://doc.wallabag.org/en/user/errors_during_fetching.html) to try and find out what the problem may be but was not successful.

f43.me can get the contents just fine. I do use a custom site config but the only difference is the login information at the bottom of the file. I can get the contents using f43.me using that config just fine as well.

I use docker to run Wallabag. I can cUrl the URL from within the container with the user agent and cookie defined in the site config just fine. This is for both the login url as well as the actual article url. Both work on f43.me as well.

I attached the custom site config as well as the graby.log.

[zeit.de.txt](https://github.com/wallabag/wallabag/files/8115372/zeit.de.txt)
[graby.log](https://github.com/wallabag/wallabag/files/8115374/graby.log)

**Comment by j0k3r** [comment]
What wallabag version are you using?
What version of PHP?

If f43.me can get the content without the 400 it means, the problem might be on your side.
Have you tried to remove your login information? Or made some edit in the config file?

**Comment by bwa-** [comment]
Sorry, I knew I forgot important stuff.

Wallabag version is 2.4.3 (Docker Image ID 198bb5363140)
PHP version is PHP 7.3.33 (cli) (built: Nov 18 2021 20:26:09) ( NTS )

I just reverted to the original site config file and the error is gone. For some reason though I can STILL get through the paywall even though I just removed the entire Docker container and created a new one...?

**Comment by j0k3r** [comment]
What changes did you apply to the site config apart the login stuff?

**Comment by bwa-** [comment]
Here's the diff: https://github.com/bwa-/ftr-site-config/commit/63b9980ceff3285addc6171ac2cb64ea7487c9dc

**Comment by j0k3r** [comment]
Maybe it was the login stuff?
Have you tried re-adding line by line to see what could go wrong?
Also, being able to fetch paywalled content after removed the Docker and without the login stuff is strange..

**Comment by bwa-** [comment]
Huh, so apparently you don't need to log in to bypass the paywall if you use the default config. I don't remember if I even tried doing that before setting up the login.
Using just the changes without login part works fine now. I don't understand why I didn't have problems until now, though.

Never mind, I'm closing this since the problem is gone. Thank you for the super quick help! 👍
