### ISSUE TITLE
Wrong display in wallabag (wired.com)

### ISSUE THREAD

**Issue by nwa573** [wallabag/wallabag#5638]
- URL: https://www.wired.com/story/browser-fingerprinting-tracking-explained/ 
 - wallabag version: wallabag.it

**Describe what's wrong:** The version that wallabag.it downloads is cut off (it stops at "Tracking people [across different browsers](https://www.ndss-symposium.org/ndss2017/ndss-2017-programme/cross-browser-fingerprinting-os-and-hardware-level-features/) is also possible.") The same thing happens if I use https://f43.me/feed/test, but if I paste in the contents of https://github.com/fivefilters/ftr-site-config/blob/master/wired.com.txt then I see the whole article. 

(I'm not sure whether I should submit this here or send it to wallabag.it.)

**Comment by j0k3r** [comment]
If it works when you paste the content of `wired.com.txt` in f43.me, it means f43.me isn't up to date (same for wallabag.it).
Just wait for one of them to be updated (wallabag.it still runs on 2.4.2, the latest is 2.4.3).
