### ISSUE TITLE
Order on RSS feeds for a tag

### ISSUE THREAD

**Issue by agallou** [wallabag/wallabag#5658]
The order of the rss feed for a tag is the creation date.
It could be useful if we could choose to order by updated_at date;

* If a have a tag "mytag" with 0 entries.
* On day one I add to wallabag an entry "A"
* On day two I add to wallabag an entry "B"
* On day three I add the tag "mytag" to the entry "B"
* On day four I add the tag "mytag" to the entry "A"

-> with that the latest item of the tag "mytag"'s RSS feed will be "B".

It could be usefull to be "A" because it's the latest entry added on the tag and should reflect on the RSS feed (on some RSS readers A won't be displayed).

**Describe the solution you'd like**

Add an option to sort on the tag feed.

On the `showTagsFeedAction` https://github.com/wallabag/wallabag/blob/c57cd26d6856030c602fd54386f2b20d45a8d4d7/src/Wallabag/CoreBundle/Controller/FeedController.php#L91
get a sort parameter on the querystring, by default it would be "created" to not change the current behaviour (with only "updated" accepted as other value)

Depending on this value, pass either "createdAt" or "updatedAt" on the `findAllByTagId` call : https://github.com/wallabag/wallabag/blob/c57cd26d6856030c602fd54386f2b20d45a8d4d7/src/Wallabag/CoreBundle/Controller/FeedController.php#L103 

Then, pass it to the `getSortedQueryBuilderByUser` method : https://github.com/wallabag/wallabag/blob/c57cd26d6856030c602fd54386f2b20d45a8d4d7/src/Wallabag/CoreBundle/Repository/EntryRepository.php#L348

The for two times the `entries.xml.twig` template is called 
* https://github.com/wallabag/wallabag/blob/c57cd26d6856030c602fd54386f2b20d45a8d4d7/src/Wallabag/CoreBundle/Controller/FeedController.php#L198
* https://github.com/wallabag/wallabag/blob/c57cd26d6856030c602fd54386f2b20d45a8d4d7/src/Wallabag/CoreBundle/Controller/FeedController.php#L131

pass an `updated` parameter (a datetime) that would be used here : https://github.com/wallabag/wallabag/blob/ca4d7283d2eeab57ba119c7fe6865f9bcf056cf5/src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig#L15 

in the showTagsFeedAction the value would depend on the sort value.

If all of this seems ok for you I can try to make a Pull Request.

**Describe alternatives you've considered**
* change the default behaviour for this controller to sort on the updatedAt value : it would change something that may works for some people (for exemple that use tag rules), and don't have the same workflow (for example for people that changes the article after tagging it)
* add an createdAt field on the entry_tag table : https://github.com/wallabag/wallabag/blob/6bd257a711c352ffa4828e78bca8971cd674ca28/src/Wallabag/CoreBundle/Entity/Entry.php#L291 That would be an ideal solution, because it would allow to exacly sort of when that tag will be added. Would'nt this solution be problematic on large databases ?

**Comment by nicosomb** [comment]
Hello @agallou! 

Thank you for the suggestion. Your pull request seems to be ready 😊😉 Just send it, and we'll review it. 

Nicolas
