### ISSUE TITLE
current name sucks (really does)

### ISSUE THREAD

**Issue by parafollar** [wallabag/wallabag#5678]
1. It consists from three syllables, one of means nothing. Whatever-a-bag.
2. Prefix sounds like «wallahi»-word from Arabic, which translates as swearing (or promising) on God.
3. From all possible options, one of the worst was chosen, by all the open-source traditions.

Here are the better ones (on my opinion):
- **Crockett** as an alternative to Pocket, also in honor of American folk hero. Personally my fav.
- **Shelfheld** as in «handheld».
- **Seilf** (Irish for shelf ¿ idk). But seilf.it looks cool.
- **Holdon** for «hold» and «on». «Put it [page] on Holdon.»
- **Stown** («stowed on»).

**Comment by j0k3r** [comment]
Thanks for your POV.
But I don't think the name will change for now.

**Comment by parafollar** [comment]
> Thanks for your POV. But I don't think the name will change for now.

very sad

**Comment by Kdecherf** [comment]
I would also like to add that the name is not random as it's a reference to the wallaby, see https://wallabag.org/en/news/let-s-go

**Comment by nicosomb** [comment]
@parafollar ❤️

**Comment by parafollar** [comment]
> @parafollar heart
> 
> are you a pocket lawyer? :trollface:

problem?
