### ISSUE TITLE
Wrong display in wallabag (https://reclaimthenet.org)

### ISSUE THREAD

**Issue by zecamigo** [wallabag/wallabag#5691]
Hi there!

Thanks in advance if you're able to look into this. I could *try* to tinker with site config files myself if there is a similar one I could adapt from, in that case please let me know and I'll be glad to contribute.

- [X] I've tried myself without success
- [X] manually updated the site config files from five filters
- [X] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)
- [X] Tested in https://f43.me/feed/test and it works over there

**Content related:**
 - URL: [[https://reclaimthenet.org/telegram-is-unbanned-in-brazil-after-agreeing-to-censor/]](https://reclaimthenet.org/telegram-is-unbanned-in-brazil-after-agreeing-to-censor/)
 - wallabag version: 2.3.8 (yunohost self hosted)

**Describe what's wrong:**
There is a subscribe box very similar to substack, with a link below to the full article. Wallabag is unable to parse this.
"wallabag can't retrieve contents for this article. Please [troubleshoot this issue](http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that)."

**Comment by zecamigo** [comment]
Logs:
[pastebin](https://pastebin.com/WVA9Xqq4)

**Comment by Kdecherf** [comment]
I don't see any fetching issue on current master, closing it
