### ISSUE TITLE
Deprecate/remove MOBI export

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/wallabag#5773]
It looks like Amazon is planning[1] to support conversion of EPUB files for their Kindle devices, which is a quite good news.

They also plan to phase out their support of the legacy MOBI file format; that we support in wallabag mostly for Kindle devices afaik.

@wallabag/core I think we could simplify our dependencies and maintenance by planning the deprecation and removal of this export format. What do you think?

[1]: https://gizmodo.com/amazon-kindle-e-readers-will-now-convert-epub-to-kindle-1848867278

**Comment by tcitworld** [comment]
Yup, there's all kind of tools to convert to mobi anyway.

**Comment by nicosomb** [comment]
OK for me.

**Comment by j0k3r** [comment]
@Kdecherf I'm ok to deprecate in 2.5.0 (if you create the PR) and then remove it in 2.6.0

**Comment by Kdecherf** [comment]
@j0k3r I will

**Comment by reischlfranz** [comment]
Isn't it a bit premature to immediately jump to removing it? Consider that this change from Amazon is only to happen late this year, not everybody is going to use the send-to-kindle feature, and there are quite a few legacy Kindle devices out there that perhaps don't even have a network connection anymore. For those, moving a MOBI file over USB might be the only option.

Making the user jump through hoops (using additional conversion tools) to achieve the same thing that was already possible just a version previously, never is good optics; and thus should be approached with caution.
As far as I can tell, the MOBI export is working fine for now. As long as there are no downstream complications, I would suggest leaving it in as legacy feature. Maybe the text could "recommend" another format, and warn that it might not deliver the best result of the available formats.

**Comment by Kdecherf** [comment]
@reischlfranz you're right, thanks for your feedback.
We made the deprecation message more vague, removing any version constraint for its actual removal.

Outside of the end of support on Kindle devices by Amazon, the other consideration I have in mind with this proposal is to ease maintainance as legacy libraries can prevent dependency updates and new development (_like PHP or Symfony version update_).
