### ISSUE TITLE
[RFC] Increase PHP minimum required version

### ISSUE THREAD

**Issue by yguedidi** [wallabag/wallabag#5776]
Currently the minimum required version is 7.2.5 based on Composer php requirement.

It's [not supported since a while](https://www.php.net/supported-versions.php)!
Currently minimum supported version by PHP is 7.4, but its security only support ends by the end of this here (in 6 months at the time of writing).

I'd like to suggest to move the minimum PHP version requirement to at least PHP 8.0, that is supported for a year and a half from now.

I know Symfony doesn't consider such PHP version requirement bump a BC break, but a feature, and so they are introduced in minor versions.
Is wallabag aligned with such statement? If not, what is wallabag position?

Also, Symfony 6.1 is coming, and [it will require at least PHP 8.1](https://symfony.com/blog/symfony-6-1-will-require-php-8-1) because of a PHP 8.0 bug in preloading feature.
You know I'd like to work on the Symfony upgrade, but you may not know that I'd like to upgrade to latest version! :slightly_smiling_face: 
This means that at a moment we will need to require PHP 8.1 to move to Symfony 6.1.

I'd like to discuss in which way we could increase the PHP version requirement in a safe way of everyone.

**Comment by j0k3r** [comment]
We usually do the jump like Symfony, in a minor version:
- Dropping < 7.2 in 2.4.0: https://github.com/wallabag/wallabag/pull/4441
- Dropping < 5.6 in 2.3.0: https://github.com/wallabag/wallabag/pull/2861

I don't know if we should already jump to PHP 8.1 or Symfony 6.
Maybe we can drop PHP < 7.4 and then upgrade to Symfony 5 for the 2.6.0. And maybe drop PHP < 8.1 in the 2.7.0 if we still find the courage to upgrade to Symfony 6.1.

Also, @nicosomb'll have to update the wallabag.it server to the newer version we'll choose for 2.6.0

**Comment by yguedidi** [comment]
Thank you for your answer @j0k3r 
What do you think about this idea, following the dropping path taken by previous wallabag minor versions:

- 2.5.0: drop PHP < 7.4
- 2.6.0: drop PHP < 8.0 + Symfony 5 upgrade
- 2.7.0: drop PHP < 8.1 + Symfony 6 upgrade

I can work on a PR dropping PHP < 7.4 for the 2.5.0 if you agree on this proposal

**Comment by Kdecherf** [comment]
If we consider that Ubuntu will stop updating its 18.04 LTS version (_which provides PHP 7.2 without extra repository_) later this year and the 20.04 natively provides PHP 7.4, this plan looks fine for me.

**Comment by yguedidi** [comment]
I'll work on a PR dropping PHP prior to 7.4 ASAP

**Comment by yguedidi** [comment]
I'll base the upcoming PR on https://github.com/wallabag/wallabag/pull/5772
