### ISSUE TITLE
[RFC] Prefered way to get Doctrine repositories

### ISSUE THREAD

**Issue by yguedidi** [wallabag/wallabag#5777]
Part of the work on Symfony upgrade is about moving from using the container to get services to constructor/action service injection.

There is no particular question for normal services, but there are two ways to get a Doctrine repository:

- Service repositories, so like any normal service, passed as a typehinted constructor/action parameter
- from the `EntityManager`, with the well knowen `$em->getRepository(MyEntity::class)` method

The thing is that controllers for exemple can need both, to call methods on repositories and persist/flush on the entity manager.

My open question is what to do in that case? should we inject both entity manager and service repositories? or just the entity manager and get the repositories from it?

I'd say that the former way enforces types but may lead to long list of parameters, and the later allow lighter list of parameters but the return type of `getRepository()` is `object` (without additional tooling)

Personally I prefer the type safe way, what is your opinion?

**Comment by yguedidi** [comment]
@j0k3r @nicosomb @Kdecherf any opinion here?
I'd like to start working on migrating from usages of the container to dependency injection, and introducing autowiring meanwhile.
I'll do it section by section (at least a PR per "light" bundle, and then multiple PRs for the Core one).
But I'd like to know first your point of view on this :)

**Comment by j0k3r** [comment]
I usually do both.

- When I need to flush and persist, I inject the EntityManager and retrieve the repository from it (and I add a phpdoc just before `/** @var \App\Repository\MyModelRepository */`).
- When I only need the repository, I inject them as a service.
