### ISSUE TITLE
Wrong display in wallabag (linkedin.com)

### ISSUE THREAD

**Issue by jjanvier** [wallabag/wallabag#5781]
We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://www.linkedin.com/posts/christianhujer_tdd-bdd-atdd-activity-6927473327531778048-ZeYr/#main-content
 - wallabag version: the one on wallabag.it

**Describe what's wrong:**

Wallabag is able to fetch only the cookies part of the page (the one in red in the screenshot). The real content part of the article is not fetched.

![2022-05-04-173420_3840x1080_scrot](https://user-images.githubusercontent.com/3691804/166717814-461a0aed-8186-4db5-b528-e059cf27e2fd.png)

**Comment by Strubbl** [comment]
I think wallabag.it has been updated. With wallabag version 2.5.4 the content is fetched. 
Can you please check if this fixed?

**Comment by jjanvier** [comment]
It works, yes, thanks :+1:
