### ISSUE TITLE
Save articles to read later within the Raven Reader

### ISSUE THREAD

**Issue by renaldofreire** [wallabag/wallabag#5804]
I have been using the [Raven Reader](https://github.com/hello-efficiency-inc/raven-reader). I saw that they have support for sharing articles to services like _instapaper_ and _pocket_. 

I would like to suggest implementing the sharing option for **Wallabag** as well.

Could you consider this possibility?

**Comment by j0k3r** [comment]
It's more something **they** should implement instead of us, don't you think?

**Comment by renaldofreire** [comment]
I was also left with this same question. I will suggest it directly to them. Thank you.
