### ISSUE TITLE
material black starts clipping in white when loading any page

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#5808]
### Environment

* **Version**: 2.5.0
* **Installation**: docker
* **PHP version**: the one in docker
* **OS**: linux
* **Database**: mysql
* **Parameters**: n/a

### What steps will reproduce the bug?

Use material dark variant
when any page is loading first it appears briefly white

**Comment by nicosomb** [comment]
@Simounet Hmm ... we already had this bug, right? https://github.com/wallabag/wallabag/issues/4812

**Comment by ngosang** [comment]
This is still present in 2.5.2

**Comment by ngosang** [comment]
![image](https://github.com/wallabag/wallabag/assets/10577978/3c2b65a3-d09a-4cb5-bc3f-2fdfea45b8a0)
Check those links:
* https://stackoverflow.com/questions/63033412/dark-mode-flickers-a-white-background-for-a-millisecond-on-reload
* https://stackoverflow.com/questions/71799083/white-flash-on-dark-mode-on-refreshing-page

**Comment by Simounet** [comment]
But we're not using JS to set the dark theme after your choice. It's pure CSS. You can check disabling JS. What's your browser and browser's version please?
Could you try with a fresh profile? Is it the same behavior on mobile?

**Comment by ngosang** [comment]
Firefox with Automatic theme. If I set the "dark theme" it's fine, there is not flicker. It's good enough for me.

**Comment by Simounet** [comment]
Ok, now I can reproduce your issue. I'll investigate.
