### ISSUE TITLE
Unable to extract archive due to data not being able to be encoded UTF8

### ISSUE THREAD

**Issue by muppie** [wallabag/wallabag#5809]
### Environment

* **Version**:
* **Installation**:
* **PHP version**:
* **OS**:
* **Database**:
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  500: Internal Server Error
Your data could not be encoded because it contains invalid UTF8 characters.
  ```
</details>

### What steps will reproduce the bug?

I don’t understand why the contents here does show up after posting

**Comment by j0k3r** [comment]
Fill your issue with information otherwise we can't and won't help you.

**Comment by muppie** [comment]
I tried but the text won’t show. I’ll try again.

**Comment by Kdecherf** [comment]
This issue seems to be staled, closing it
