### ISSUE TITLE
Whether we can consider editing the collected articles in the future?

### ISSUE THREAD

**Issue by i-iooi-i** [wallabag/wallabag#5825]
Hello, I just started using wallabag. It's really great. 

But I found a troublesome problem in use, when there are advertisements or unnecessary pictures in my collected articles. I want to rearrange these contents, such as deleting advertisements or deleting pictures.

But at present, it seems that you can only edit the title. I think it will be a little inconvenient for those who are keen on sorting out the content.

In the future, we can consider adding some simple editing gadgets, such as deleting article content or pictures. In this way, collection + sorting seems to be more attractive.

Thank you~wallabag ❤️

**Comment by tcitworld** [comment]
Duplicate from #3358
