### ISSUE TITLE
Can wallabag not save articles in Craft?

### ISSUE THREAD

**Issue by i-iooi-i** [wallabag/wallabag#5827]
I tried to save an article, but it seemed to go wrong.😢
This is the article link: https://www.craft.do/s/48MFW9QwaCQMzt

Here is the result:

![image](https://user-images.githubusercontent.com/1827701/170715562-d8342ada-9a04-4535-9882-9434e486d5fb.png)

![image](https://user-images.githubusercontent.com/1827701/170715488-e0bdf114-89cf-49a7-a2de-a9fb17606163.png)

**Comment by Kdecherf** [comment]
The page is loaded through javascript, closing this issue as won't fix
