### ISSUE TITLE
app.wallabag.it 500 Error

### ISSUE THREAD

**Issue by zeorin** [wallabag/wallabag#5859]
Go to any URL on https://app.wallabag.it and it'll return HTTP 500 with the following response:

```
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.1". 
```

The browser extension is also not working as a result.

**Comment by Kdecherf** [comment]
@nicosomb

**Comment by zeorin** [comment]
Seems to be fixed now.
