### ISSUE TITLE
Translation missing for annotations, instead shows label's name

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#5860]
### Environment

* **Version**: 2.5.1
* **Installation**: git
* **PHP version**: 7.4.28
* **OS**:debian
* **Database**: pg
* **Parameters**:

### What steps will reproduce the bug?

After the update i have no translations text for some labels rgd. annotations. e.g in the main menu on the left, it shows the label's name `menu.left.with_annotations` instead of a text. I am using German as language, but if there is no German translation for this text, i would have expected it to be in English at least.

![image](https://user-images.githubusercontent.com/97055/173438012-51cfc232-8a93-483e-86bd-298e17201e59.png)

I also found this issue in the filter view: 

![image](https://user-images.githubusercontent.com/97055/173438072-fb22b561-8e36-49a6-aeb5-0de2ec15fa18.png)

And of course the headline of the annotations page in `/annotated/list` itself:

![image](https://user-images.githubusercontent.com/97055/173438138-8c59df68-72af-4835-b1b7-53ad2b89202c.png)

**Comment by j0k3r** [comment]
Feel free to translate what is missing in German: https://hosted.weblate.org/translate/wallabag/messages/de/?checksum=ac2fe2780d3494c5
