### ISSUE TITLE
Servers unreachable

### ISSUE THREAD

**Issue by walhallaRV** [wallabag/wallabag#5885]
Hi,
can't connect to wallabag - servers. All machines (app / wallabag.it / download install) are unreachable with "refused connection". Sad thing .... 

root@machine# wget https://wllbg.org/latest-v2-package
--2022-07-05 04:02:21--  https://wllbg.org/latest-v2-package
Resolving wllbg.org (wllbg.org)... 138.201.122.115, 2a01:4f8:172:25b0::2
Connecting to wllbg.org (wllbg.org)|138.201.122.115|:443... failed: Connection refused.

**Comment by nicosomb** [comment]
Hello @walhallaRV 

Do you still have this bug? 
If yes, do you use a firewall?
