### ISSUE TITLE
Confusing UI: Export Selected Entries

### ISSUE THREAD

**Issue by stephen-hill** [wallabag/wallabag#5889]
I was trying out the new export feature, and on my installation it would timeout.

Eventually I realized that it was trying to export everything that was unread and for me, that 200+ items.

If any items are selected (checked) then I think only those items should be exported.

**Comment by jerrykan** [comment]
I agree, it would be really useful to export select articles.

At the moment my work-around to to star a bunch of articles, go to the star view, export the articles, then unstar the articles. Not the best solution, especially if you use the star article functionality for its intended purpose.
