### ISSUE TITLE
Change Default Instance Domain

### ISSUE THREAD

**Issue by stephen-hill** [wallabag/wallabag#5890]
Currently, the default value for the instance is: your-wallabag-url-instance.com. This domain appears not to be own by wallabag org, or if it is, it has a parked domain page by the registrar.

I understand this only happens when the installation is incorrectly configured, but we should protect our users. I believe we should do the following:

- The default domain should be HTTPS
- The default domain should be owned by wallabag org
- The website of the default domain should tell users that their instance is incorrectly configured, and how to fix it.

Thanks

**Comment by j0k3r** [comment]
That's a good idea!

**Comment by j0k3r** [comment]
Maybe we should use something like `https://your-wallabag-instance.wallabag.org` and put a description on that page or a redirection to the config page to properly configure that config.

**Comment by nicosomb** [comment]
@j0k3r what do you think about creating a new git project, hosted on netlify with this simple page?

**Comment by nicosomb** [comment]
I opened a new repo: https://github.com/wallabag/your-wallabag-instance and created [index.html](https://github.com/wallabag/your-wallabag-instance/blob/main/index.html) file.

@Simounet As you can see, my webpage is wonderful but I know that you can make it prettier ❤️ 

Website is deployed thanks to Netlify and available here: http://your-wallabag-instance.wallabag.org/

Steps: 
- [ ] make the page more complete and prettier
- [ ] make the changes in default parameters.yml

**Comment by nicosomb** [comment]
PR is opened for parameters.yml https://github.com/wallabag/wallabag/pull/6616

**Comment by Simounet** [comment]
I can help with CSS but I'm not a designer at all. 😅
I will try to make it look like wallabag. 😁

**Comment by nicosomb** [comment]
@j0k3r @stephen-hill @Kdecherf which content do you want to see on this page?

**Comment by stephen-hill** [comment]
@nicosomb I think what is there is very good. I don't think we need much.

All I would add would be:

- Explicitly state that the parameter "domain_name" is not/miss configured
- Link directly to the https://doc.wallabag.org/en/admin/parameters.html (I'm not sure if you can link to this lanaguage agnosticly)

Otherwise, really good work. I feel this security update should be deployed as soon as ready.

**Comment by nicosomb** [comment]
https://github.com/wallabag/your-wallabag-instance/pull/2 and preview here https://deploy-preview-2--your-wallabag-instance.netlify.app/

**Comment by nicosomb** [comment]
Fixed.

**Comment by stephen-hill** [comment]
Awesome work everyone. Thank you.

**Comment by stephen-hill** [comment]
@j0k3r Any chance this could be merged into a 2.5.5 release?

**Comment by nicosomb** [comment]
The 2.6.0 will be available soon. You don't want to upgrade to 2.6.x ?

**Comment by stephen-hill** [comment]
@nicosomb I do, but I consider this issue security related. If 2.6 is more than a couple of weeks away, then I would argue this update is worth pushing out to 2.5.5.

I know the issue only affects new users, but anyone could buy that domain and then start harvesting usernames and password.

I'll leave that judgement call to you, just thought I would ask/raise the question.
