### ISSUE TITLE
Batch epub-export of separate articles 

### ISSUE THREAD

**Issue by Krysztophe** [wallabag/wallabag#5891]
**Is your feature request related to a problem? Please describe.**
I usually store articles in wallabag from my smartphone and read them later from a remarkable tablet, offline (without the RM cloud).
The painful part of the process is exporting dozens articles from wallabag one by one: click on article, wait 1/2s, click on export as epub, click to save into the transfert directory, click to set as read, next one...

**Describe the solution you'd like**
- An export function that would export separately each selected article in a separate Epub/PDF
- The same as a simple CLI
- A script to connect, list unread articles, get the export URL.  I know there are APIs for this, but the doc is a bit dry, I am not a developer.

**Describe alternatives you've considered**
The "export" item on the main page does not export each article separately.
I've tried to export through RSS+Calibre but I still get one big Epub for N articles
(I may have missed something obvious)

**Additional context**
I use wallabag on my own small 1-cpu server.

Thanks!

**Comment by Krysztophe** [comment]
I've written the CLI tool : https://gitlab.com/Krysztophe/wallabag2epub/-/blob/main/wallabag2epub.py (very basic but enough for me)

At first I tried  WallabagAPI (https://pypi.org/project/wallabagapi/ ) but it seems totally outdated and not maintained and it did not work, and that was too complex for my needs anyway. The code was helpful though. So was https://gist.github.com/petermolnar/988ba2fa2770b71a443e437cd4052aeb.

**Comment by tomash** [comment]
Hi @Krysztophe , apologies for writing in old and closed issue but there's no messaging info on your Github nor Gitlab profile pages. Your script was exactly what I needed. I forked it and made some changes, most notably the ability to merge downloaded articles epub files into one "book" with table of contents, not yet perfect but scratches my itch to have my daily ebook of articles I wanted to read: https://github.com/tomash/wallabag2epub

**Comment by Krysztophe** [comment]
> Your script was exactly what I needed. I forked it and made some changes, most notably the...

I had almost forgotten this script (not much time to read random articles)! I'm happy to know it's helpful for someone else 😄
