### ISSUE TITLE
Changing from http to https - doesn't work

### ISSUE THREAD

**Issue by walhallaRV** [wallabag/wallabag#5899]
Hi, after installing I changed from http tp https, but wallabag doesn't work properly anymore. I changed the part in parameters.yml - but doesnt help / work.

Version:      2.43
Installation: downloading the package
PHP version:  8.1
OS:           Debian
Database:     MySQL/MariaDB
Parameters:   
database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: xxx
    database_user: xxx
    database_password: xxx
    database_path:
    database_table_prefix: wallabag_
    database_socket:
    database_charset: utf8mb4
    domain_name: 'https://xxx.yyy'
    server_name: 'Test'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: xxx
    twofactor_auth: true
    twofactor_sender: no-reply@xxx.yy
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@xxx.yy
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null

Thx & Cheers

**Comment by j0k3r** [comment]
> wallabag doesn't work properly anymore.

What does that means?

**Comment by Kdecherf** [comment]
This issue did not have activity for the past four months, closing it
