### ISSUE TITLE
Android app cannot connect 

### ISSUE THREAD

**Issue by silverman10** [wallabag/wallabag#5900]
**Describe what's wrong:**

Android app cannot complete the initial connection and test.
Get the error saying connection cant be established due to unknown error.
Something i noticed is that it shows port 80 even though i am using https.

Interface loads without issues on Android and PC browser.

![Screenshot_20220719-183820_wallabag~2.png](https://user-images.githubusercontent.com/33454830/179817395-83925442-b71a-40b1-9f55-76d7610ac706.png)

**Comment by j0k3r** [comment]
This should be posted at https://github.com/wallabag/android-app
