### ISSUE TITLE
Use bookmarklet without the need of being loged in

### ISSUE THREAD

**Issue by aschilling** [wallabag/wallabag#591]
Hi everybody,

I use Mr. Reader for my daily rss consumption. I provides a mechanism in which you can execute a bookmarklet action on any article. Using this mechanism I would love to fill Wallabag with relevant articles. However, it redirects me always to the login page. Is there any possibility to use the Wallabag Bookmarklet without beeing loged in?

Thanks

Andy

**Comment by tcitworld** [comment]
We don't support the bookmarklet anymore, use the browser extensions instead.
