### ISSUE TITLE
Internal server error on the unread list when language is set to Czech

### ISSUE THREAD

**Issue by aiwo79** [wallabag/wallabag#5924]
I'm using free trial of wallabag. When I switch language of the web application to Czech and go to the unread list (https://app.wallabag.it/unread/list), there is 500: Internal Server Error with this info:

An exception has been thrown during the rendering of a template ("Unable to choose a translation for "{0} Nemáte žádné položky.|{1} Máte jednu položku.|]1,4[ Máte %count% položky.|]4,Inf[ Máte %count% položek." with locale "cs" for value "4". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples").").

**Comment by j0k3r** [comment]
Maybe wallabag.it isn't up to date because locally using master, I don't have any problem to list entries.
<img width="429" alt="image" src="https://user-images.githubusercontent.com/62333/191974826-bd1c07f0-9436-4087-99b6-165e9bafa0eb.png">

**Comment by aiwo79** [comment]
It only happens when there are no items on the list.

**Comment by j0k3r** [comment]
No problem again when there is no items on the list (you filtered by something and got no results right?)
<img width="341" alt="image" src="https://user-images.githubusercontent.com/62333/191978974-ee197991-7e35-4b63-a717-0810f615ef53.png">

**Comment by aiwo79** [comment]
No, I don't think so. It's getting even more weird now. I have just made a test - had six unread items, marked one as read and got 500 error.

![screenshot-app wallabag it-2022 09 23-16_17_15](https://user-images.githubusercontent.com/11314317/191981795-2806ac87-5563-448c-9bb6-93284947f50d.png)

**Comment by nicosomb** [comment]
@aiwo79 could you try again please?

**Comment by aiwo79** [comment]
It's ok now. Thank you!
