### ISSUE TITLE
https://wllbg.org/latest-v2-package  redirects to 2.4.3, not to latest version

### ISSUE THREAD

**Issue by Georg311** [wallabag/wallabag#5945]
I was using the installation documentation from
https://doc.wallabag.org/en/admin/installation/installation.html

If i download the package via following command
```
wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package
```
the url points to wallabag-2.4.3.tar.gz - shouldn't the latest url point to https://github.com/wallabag/wallabag/releases/download/2.5.1/wallabag-2.5.1.tar.gz or is the vhost installation package different from the dedicated package?

### What steps will reproduce the bug?
wget https://wllbg.org/latest-v2-package

Enter details about your bug and how to reproduce it
Download the Package, version is wrong

**Comment by j0k3r** [comment]
@nicosomb 👋

**Comment by nicosomb** [comment]
Good catch @Georg311. 

It's fixed.
