### ISSUE TITLE
Add entries count to /api/tags.format

### ISSUE THREAD

**Issue by yotamN** [wallabag/wallabag#5970]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a Wallabag client and I want to show entries count per tag just like the official web client but I can't get this information from the REST api.

**Describe the solution you'd like**
I think the API endpoint should have the counter as a field and maybe even a way to sort by the count. Changing the method call from `findAllTags` to `findAllFlatTagsWithNbEntries` should add the entries count but I'm not sure what flat means in this context, would love some help so I could try to fix it.

**Describe alternatives you've considered**
The only possible way I could think of is to iterate all entries which is a big no no

**Comment by j0k3r** [comment]
That's interesting, let me dig into that
