### ISSUE TITLE
Wrong display in wallabag (m.dailykos.com)

### ISSUE THREAD

**Issue by dflock** [wallabag/wallabag#5981]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://m.dailykos.com/stories/2007/3/9/310038/-
 - wallabag version: app.wallabag.it/about says 2.5.1 

**Describe what's wrong:**
It says "wallabag can't retrieve contents for this article", but it works fine in a browser - and fine with f43.me

**Comment by HolgerAusB** [comment]
@dflock, it is fine with my selfhosted wallabag and the old site_config from 2014. If you are self-hosting please check the file `.../vendor/j0k3r/graby-site-config/dailykos.com.txt` with content of [this repo](https://github.com/fivefilters/ftr-site-config/blob/master/dailykos.com.txt).

**Comment by dflock** [comment]
This article appears to work fine now, without me changing anything
