### ISSUE TITLE
Cannot import Instapaper file (.csv) on web app

### ISSUE THREAD

**Issue by sanketpath** [wallabag/wallabag#5996]
### Environment

* **Version**: 2.5.1
* **Installation**: Trial version on https://app.wallabag.it
* **PHP version**: NA
* **OS**: MacOS 12.5
* **Database**: NA
* **Parameters**: NA

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  PASTE HERE
  ```
</details>

### What steps will reproduce the bug?
I'm using Safari to try out Wallabag. I went to [import page](https://app.wallabag.it/import/) and tried importing the `.csv` file I downloaded from my Instapaper. But it keeps throwing me the error:

```
500: Internal Server Error
stream socket client: unable to connect to
tcp://localhost:5672 (Connection refused)

```

I tried a different browser (Brave) to import. Still getting the same error.

**Comment by sanketpath** [comment]
@nicosomb @j0k3r Looks like this one is resolved. I was able to import my Instapaper CSV. I just converted my trial into paid subscription and then the import worked.

**Comment by nicosomb** [comment]
There is no restriction. Strange ...
