### ISSUE TITLE
API calls return 500 internal server error

### ISSUE THREAD

**Issue by kahnwong** [wallabag/wallabag#6007]
### Environment

* **Version**: 2.5.0
* **Installation**: docker image (on a new machine, not with existing docker deployment)
* **PHP version**: the one bundled in with official wallabag image
* **OS**: macos
* **Database**: postgres:13.1-alpine
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```python
POSTGRES_PASSWORD: ########
POSTGRES_USER: ########
SYMFONY__ENV__SECRET: ########
SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
SYMFONY__ENV__DATABASE_DRIVER_CLASS: Wallabag\CoreBundle\Doctrine\DBAL\Driver\CustomPostgreSQLDriver
SYMFONY__ENV__DATABASE_HOST: wallabag_db
SYMFONY__ENV__DATABASE_PORT: 5432
SYMFONY__ENV__DATABASE_NAME: ########
SYMFONY__ENV__DATABASE_USER: ########
SYMFONY__ENV__DATABASE_PASSWORD: ########
SYMFONY__ENV__REDIS_HOST: ########
SYMFONY__ENV__REDIS_PASSWORD: ########
SYMFONY__ENV__DOMAIN_NAME: http://localhost:100
  ```
</details>

### What steps will reproduce the bug?

- `docker-compose up` via official docker compose file (it has always been this docker compose file I used)

### Details

- API calls don't work. It returns `{"error":{"code":500,"message":"Internal Server Error"}}`
- can't fetch article in iOS app
- can't fetch articles on Android app
- Wallabag firefox extension returns error, but articles are added to the instance anyway
- Additionally, accessing `$DOMAIN/api` and `$DOMAIN/api/docs` return `<error code="404" message="Not Found"/>`

**Comment by j0k3r** [comment]
Can you look for log inside the docker image? `var/logs/*`
Also, update to 2.5.1, just in case.

**Comment by kahnwong** [comment]
Update: upgrading to `2.5.1` yields success api calls

however, `$DOMAIN/api` and `$DOMAIN/api/docs` still yield `404`

tested against my docker deployment. only update wallabag image version, then docker-compose down and up

**Comment by Kdecherf** [comment]
There's no page on `$DOMAIN/api` nor `$DOMAIN/api/docs`.

The API documentation is hosted at: `$DOMAIN/api/doc`, its link can be found on the API client management page.
