### ISSUE TITLE
Wallabag broken during upgrade from 2.4.x to 2.5.2

### ISSUE THREAD

**Issue by satak-azat** [wallabag/wallabag#6030]
### Environment

* **Version**: 2.5.2
* **Installation**: git
* **PHP version**: 7.4.30
* **OS**: Debian 11
* **Database**: Postgres 13.8
* **Parameters**:  `    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wallabag
    database_user: wallabag
    database_password: 
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8mb4
    domain_name: 
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret:
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: false
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
    server_name: 
    mailer_port: false
    mailer_encryption: null
    mailer_auth_mode: null
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    sentry_dsn: null
`

<details>
While upgrading wallabag and my current debian install (from 10 to 11) wallabag crashed. Composer version is 2.4.3

Running make update returns:

`HEAD est maintenant sur 63b7b1c18 Merge pull request #6026 from wallabag/release/2.5.2
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires composer < 2.3, found composer[2.4.3] but it does not match the constraint.

make: *** [GNUmakefile:24 : update] Erreur 2
`

Composer update returns:

`Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires composer < 2.3, found composer[2.4.3] but it does not match the constraint.
`

The only way i could go past this was by doing composer update --ignore-platform-reqs but even then make update still returns the same message. I tried using composer 2.3 too, same thing. Currently, the wallabag page is blank and the error log returns:

`2022/10/23 19:21:01 [error] 4593#4593: *8126 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '|', expecting '{' in /var/www/wallabag/vendor/thecodingmachine/safe/lib/special_cases.php on line 434" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "xxx.xxx"
`

(The config is correct, I just removed url, secret and password)
</details>

**Comment by j0k3r** [comment]
See https://github.com/wallabag/wallabag/issues/5909#issuecomment-1195404877
