### ISSUE TITLE
Can't add a tag with a single character like >

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#6048]
### Environment

* **Version**: 2.5.2
* **Installation**: locally
* **PHP version**: 8.0
* **OS**: debian
* **Database**: mariadb
* **Parameters**:

### What steps will reproduce the bug?

1. Save an article
2. Add a new tag to this article with `>` as name
3. On unread page, click on the tag to see all the articles linked to this tag
4. See the 404 page 

In database, no slug are stored for tags like this one, that's why we have a 404. 

To fix this bug, we need to store a slug. 
We also need to write a database migration to fetch all tags with empty slug and generate a new one.

### Expected bahaviour 

I want to see the articles with the `>` tag.

**Comment by nicosomb** [comment]
@j0k3r do you think that adding the `prefix` option could be a solution https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/sluggable.md#some-other-configuration-options-for-slug-annotation-and-attribute ?

**Comment by Kdecherf** [comment]
I don't think `prefix` is enough to address this issue.

I'm able to reproduce it by creating a tag with this label: 📰🗞️📜📃📄🗒️📒📓📔📑📖🔖📚, slug is empty.

We could maybe use hash (e.g. SHA1) for these corner cases.
Punycode could also work for most unicode characters. My label would give the following punycode slug: `xn--ct8hc3bdfgp6ak3rkq48eme`; however this wouldn't work for characters like '>'

**Comment by Kdecherf** [comment]
After some testing, setting a `prefix` is enough to address this issue.

However I'm wondering if it is a long-term solution:
- we embed `gedmo/doctrine-extensions` in the sole purpose of _slugifying_ the tag label
- even with a prefix, the implementation simply removes special characters from the slug

E.g., without prefix:
- `>` gives the slug ``
- `🔗` gives the slug ``
- `néà£lヹ-` gives the slug `neapslve`
- `+=^àç<#~-h` gives the slug `ac-h`

After all, do we really need the slug? I think we could replace the slug with the tag id in the routing.

cc @wallabag/core

**Comment by nicosomb** [comment]
As we don't use slug for articles for example, I think that we can remove them for tags. 

Is that a BC break?

**Comment by Kdecherf** [comment]
I think it is a breaking change for the API, so we may need to reconsider it for 3.x and going forward with the prefix fix for the 2.6 branch

**Comment by j0k3r** [comment]
What does the prefix fix if the tag label is `>`? What will be the slug?

**Comment by bourvill** [comment]
Hello, 

Removing slug from tag will be a BC for the iOS app.
App simply crash without update

**Comment by nicosomb** [comment]
> What does the prefix fix if the tag label is `>`? What will be the slug?

I think it will be `t:`. The same slug as `🔗` tag for example 🤔

**Comment by Kdecherf** [comment]
The slug will indeed be `t:`, however there is an implicit routine which ensure uniqueness, thus changing it to `t:-1`, `t:-2`… if it is already used by another tag
