### ISSUE TITLE
Search doesn't search on read entries

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#6077]
Version:      2.5.2
Installation: Docker
PHP version:  The docker image one
OS:           The docker image one
Database:     Postgres 14, external instance
Parameters:   The docker image ones

### What steps will reproduce the bug?

1. From the home page, click on Search
2. Enter a term which appears only on a read entry
3. Run your search
-> No result found.

**Comment by Kdecherf** [comment]
@romu70 could you do the same search from the "All entries" page?

I think there's a misunderstanding on the feature: the homepage only shows unread entries and the search is done depending on the current page.

**Comment by romu70** [comment]
Indeed ;)

It works on the "All entries" and "Archive" page.

November 13, 2022 1:42 PM, "Kevin Decherf" ***@***.*** ***@***.******@***.***>)> wrote:
	@romu70 (https://github.com/romu70) could you do the same search from the "All entries" page?

	I think there's a misunderstanding on the feature: the homepage only shows unread entries and the search is done depending on the current page.

**Comment by nicosomb** [comment]
Thank you @Kdecherf
