### ISSUE TITLE
missing message/translation for entry.confirm.delete_entries

### ISSUE THREAD

**Issue by mstevens** [wallabag/wallabag#6175]
### Environment

app.wallabag.it

I think it's 2.5.2.

I had a look in the code which suggests the same issue is in the github release.

English.

### What steps will reproduce the bug?

Go to archived entries screen.

Select at least one entry.

click trashcan.

Get a popup with entry.confirm.delete_entries.

There's no translation for this.

The actual code is in `wallabag/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig`

Wasn't sure on the workflow, possibly it needs adding in `src/Wallabag/CoreBundle/Resources/translations/messages.en.yml`?

**Comment by j0k3r** [comment]
Good catch 👍🏼 

Thanks I've just added it in weblate: https://hosted.weblate.org/translate/wallabag/messages/en/?offset=1&q=entry.confirm.delete_entries&sort_by=-priority%2Cposition&checksum=

Translations moved over here: `translations/messages.en.yml` but yeah it was the good file.

**Comment by mstevens** [comment]
thanks!
