### ISSUE TITLE
dark mode is sometimes unreadable with too little contrast

### ISSUE THREAD

**Issue by hydrargyrum** [wallabag/wallabag#6200]
In dark mode, when the search field has focus, its text is simply invisible.

![2022-12-30-walla-light](https://user-images.githubusercontent.com/2804645/210053614-0078208c-401a-4661-933e-8c33b9a3e262.png)
![2022-12-30-walla-dark](https://user-images.githubusercontent.com/2804645/210053615-f3f0e225-9b54-47e6-b4d9-e2269fdcf0e3.png)

Even the search icon at left of text field is invisible.

### Environment

* **Version**: 2.5.2
* **Installation**: docker image https://hub.docker.com/r/wallabag/wallabag
* **PHP version**: docker image
* **OS**: docker image
* **Database**: postgresql
* **Parameters**:

### What steps will reproduce the bug?

- use dark mode
- focus search field
- type something

**Comment by hydrargyrum** [comment]
Outside of contrast, the dark theme has very little nuance in colors. Light mode presents visual blocks well separated, while dark mode is just black everywhere, so it's impossible to distinguish zones.

In this example:
- in light mode, the title has a blue background and rest of page has white background, plus there are shadows and borders between left menu sidebar and rest of page, so it's easy to see 3 zones: left menu, title, main content
- in dark mode, every background is black, there are no borders or shadows, it looks like there's a single zone

![2022-12-30-101505_642x97_scrot](https://user-images.githubusercontent.com/2804645/210054151-3343b390-402f-4834-9911-154bc5ea7923.png)
![2022-12-30-101518_475x96_scrot](https://user-images.githubusercontent.com/2804645/210054152-8674e858-4d4e-4c41-85a6-d3b647374927.png)

**Comment by hydrargyrum** [comment]
@j0k3r I confess I didn't test the patch, but seeing as small the diff is, I believe only the first comment of this issue was addressed by #6510 , not [the second part](https://github.com/wallabag/wallabag/issues/6200#issuecomment-1367811868) about how blocks can't be distinguished at all, unlike in light mode where they are nuanced.

**Comment by Simounet** [comment]
Yep, I missed that point. I will do something about that.
