### ISSUE TITLE
epub export times out on app.wallabag.it

### ISSUE THREAD

**Issue by mstevens** [wallabag/wallabag#6201]
### Environment

* **Version**: 2.5.2
* **Installation**: app.wallabag.it

### What steps will reproduce the bug?

Tried to do epub export at:

https://app.wallabag.it/export/all.epub?search_entry%5Bterm%5D=

times out with:

500: Internal Server Error
Error: Maximum execution time of 30 seconds exceeded

I have about 2000 entries.

**Comment by j0k3r** [comment]
Are you trying to export all 2000 entries as epub?

**Comment by mstevens** [comment]
yes, I wanted to backup my data

**Comment by nicosomb** [comment]
Hello @mstevens! 

I can't remember if you contact me by email. 
You can send me an email or use this interface: https://app.wallabag.it/premium/account

I close this issue as it's not related to the open source project.

**Comment by mstevens** [comment]
Happy to leave this closed, but just to confirm I opened a ticket just now in the interface.
