### ISSUE TITLE
Memory leak PHP 8.1

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabag#6212]
Wallabag 2.5.2
I have been testing the latest Docker image (master, not released).
Both versions, PHP 8 and PHP 8.1 works as expected but there is a noticeable memory leak when using PHP 8.1

Before 30/11 => PHP 8.0
After 30/11 => PHP 8.1 => https://github.com/wallabag/docker/commit/b10121989c0651d40d5f41c8470138fcdb29f368

![image](https://user-images.githubusercontent.com/10577978/210612624-f3973869-30b6-4df9-a4ce-1f8370e7c8ab.png)

I reviewed all the commits in the Docker repository but I can't not find anything wrong. I don't think there is a problem in PHP 8.1 but maybe we are using some libraries that are not compatible.
I don't have experience debugging memory leaks in PHP but if we can not fix it we should release Wallabag 2.6.0 with PHP 8.0

**Comment by j0k3r** [comment]
Thanks for reporting.

Is there any chance you try on the master of wallabag? 2.5.2 has old dependencies and they are all up to date on the master. I think it should fix your problem.

**Comment by ngosang** [comment]
Is master branch stable enough to use in production? I don't want to break the database when 2.6.0 is released.

**Comment by j0k3r** [comment]
Well, not yet I think. I though you were testing instead of running in production.

**Comment by ngosang** [comment]
For now this issue is not affecting anyone since the latest changes in the Docker image are not released. I will deploy and report back when 2.6.0 is out.

**Comment by ngosang** [comment]
When 2.6.0 will be released?

**Comment by j0k3r** [comment]
When we'll have time to work on it.

**Comment by nicosomb** [comment]
> For now this issue is not affecting anyone since the latest changes in the Docker image are not released. I will deploy and report back when 2.6.0 is out.

So, this issue can be milestoned to 2.6.1?

**Comment by ngosang** [comment]
@nicosomb This issue is already present in 2.5.4 release but it's not a big deal. I could test it after you release 2.6.0.

**Comment by ngosang** [comment]
I just deployed 2.6.1. It's working fine but I will keep it running for 2 days to see if I can reproduce the memory issue.

**Comment by ngosang** [comment]
@nicosomb @j0k3r It's fixed!!
![image](https://github.com/wallabag/wallabag/assets/10577978/8ea73a34-a470-4b7f-89c3-b2dbc0e08df4)
