### ISSUE TITLE
No content fetch at all in wallabag (medium.com)

### ISSUE THREAD

**Issue by cukabeka** [wallabag/wallabag#6213]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [ ] I've tried myself without success
- [x ] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://forge.medium.com/100-very-short-rules-for-a-better-life-f7f5191c7586
 - wallabag version: [e.g. 2.3.8]

**Describe what's wrong:**
I guess that medium a few months ago changed to some js page generator that is hard to fetch with wallabag at all. 
At the very best, title and image are fetched, but that's mostly it, the content is zero. 
I thought that maybe an additional python script or something else might help to retrieve the full content from articles?

**Comment by cukabeka** [comment]
Hi, thanks for looking into this. I upgraded to 2.4.2 and it's still not fetching the whole article. Is there some setting that might influence this? Or PHP Version?

I'll try to upgrade to 2.5.2 but found no instructions for shared hosting upgrades for that case yet.

**Comment by j0k3r** [comment]
You can follow these steps for a minor version upgrade: https://doc.wallabag.org/en/admin/upgrade.html#upgrading-from-22x-to-23x
