### ISSUE TITLE
Use WebExtensions for Firefox plugin

### ISSUE THREAD

**Issue by shtrom** [wallabag/wallabag#625]
Mozilla has a pretty cool API in the works for all things social, including sharing and bookmaking [0]. Creating plugins seems to boil down to writing a couple of webpages with som meta markup.

I know there already is a Firefox addon, but the social API might provider a smoother integration.

[0] https://developer.mozilla.org/en-US/docs/Social_API/Guide/Bookmarks

**Comment by azrdev** [comment]
This is implemented in 090957fe3e12ffe23d2f847f6007c72eb9ca072d which is part of release 1.9.1beta3

**Comment by tcitworld** [comment]
Yup, closing here for now, will have to reopen for v2.

**Comment by raf64flo** [comment]
Hi, seem this feature is not available for v2.

Could you reopen/clone the issue please?

**Comment by shtrom** [comment]
Yup, that'd be great! No need for more addons if protocols do it out of the box!

**Comment by tcitworld** [comment]
Hmm, better do WebExtensions instead, I guess the social API was not very used.

**Comment by raf64flo** [comment]
Good idea, especially if it facilitates the development of the extension for different browsers. Do you have any roadmap for that? I don't know about web extensions, so I don't know if their current [implementation](https://wiki.mozilla.org/WebExtensions/RoadMap) already allows to develop such a feature.

**Comment by tcitworld** [comment]
Support inside the browser looks quite enough for what we would use of it.

**Comment by nicosomb** [comment]
@tcitworld @Simounet @Rurik19 It's done. I close, please reopen if necessary.

**Comment by raf64flo** [comment]
Great news! Thanks!

Could you remind me how to install the up-to-date Firefox plugin please?
Is the following plugin officialy related to Wallabag: https://addons.mozilla.org/fr/firefox/addon/wallabag-v2/ ?

**Comment by nicosomb** [comment]
Hello @raf64flo! The webextension for Firefox is not yet available, you can have more info (and ask questions) here https://github.com/wallabag/wallabagger

**Comment by Simounet** [comment]
Now it is: https://addons.mozilla.org/en-US/firefox/addon/wallabagger/

**Comment by raf64flo** [comment]
Great! I'll check that asap. :)
Thanks guys!

**Comment by nicosomb** [comment]
I need to update our website. Will do that this afternoon.
