### ISSUE TITLE
Better Metadata: Harvest and display source, author and date

### ISSUE THREAD

**Issue by menelic** [wallabag/wallabag#629]
Only some of the articles saved to wallabag contain info on the author and the time of publication of the article. It would be great if this would be standardized and allways displayed. This is important for two reasons:

1) I want to use my wallabag as a searchable archive of internet content that is important to me. This info is important for structured archiving and also to find teh content later

2) I want to use wallabag as a content provider for my eBook Reader, to be able to organise content in a way that makes it easy to package and handle for the eReader such metadata are crucial.

An idea: I know that wallabag and zotero (https://www.zotero.org/ ) have very different use cases, but zoteros metadata harvesting is great, maybe you could reuse some of their recognition engine, as it is open source as well...

**Comment by tcitworld** [comment]
This is a Graby issue. @j0k3r

**Comment by j0k3r** [comment]
Yeah and we can already retrieve most the of the information (date and author) using siteconfigs

**Comment by tcitworld** [comment]
Of course but I think dublin core, twitter cards and opengraph support could be better in graby.

**Comment by Simounet** [comment]
What is the next step for this issue? Storing the datas (date/author) on the entry table, for example?

**Comment by tcitworld** [comment]
- [ ] Increase support in Graby
- [ ] Provide datas though Graby
- [ ] Get them in wallabag
- [ ] Save them with the entry
- [ ] Display them
