### ISSUE TITLE
md5 and wallabag version not updated on wallabag.org

### ISSUE THREAD

**Issue by Massedil** [wallabag/wallabag#6295]
[Instructions](https://doc.wallabag.org/en/admin/installation/installation.html#installation) says : 
>Execute this command to download and extract the latest package:
>
>```
>wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package
>
>```
>
>You will find the [md5 hash of the latest package on our website](https://wallabag.org/en#download).

Now, the website says : 

```
Last release: wallabag 2.5.2
(md5 checksum: 3aeb95148ea213a7f30ba7ea1b3d423f)
```
The download gives the 2.5.3 release.
https://wllbg.org/latest-v2-package -> https://github.com/wallabag/wallabag/releases/download/2.5.3/wallabag-2.5.3.tar.gz

 So md5sum differs and it is not the latest 2.5.4 release.

**Comment by nicosomb** [comment]
Sorry I have to update the server configury

**Comment by nicosomb** [comment]
All is done.

**Comment by Massedil** [comment]
Thanks ! Everything is fine for me now !
