### ISSUE TITLE
Assign tag to articles create tag duplicates

### ISSUE THREAD

**Issue by jerome-tgl** [wallabag/wallabag#6330]
### Environment

Version: 2.5.2 on https://app.wallabag.it instance, MacOS 13.2.1 on Firefox 110.0

### What steps will reproduce the bug?

1. Click 🔎 search button in top bar
2. Enter "youtube.com" query or any domain which have multiple entries
3. Click "Assign this search as a tag to each result"
4. Go to https://app.wallabag.it/tag/list

Result: there are as many tags named `youtube.com (1)` as their are results for that search.  Each tag links to `https://app.wallabag.it/tag/list/youtube-com-<id>` where `<id>` is the result number starting from 1.

<img width="1055" alt="Screenshot 2023-02-23 at 17 48 39" src="https://user-images.githubusercontent.com/8667221/220977062-565c8f38-470c-4654-a4f7-102e74ab707e.png">

I don't know how to fix this mess:
- can't delete tags from the tag list page (not in batch #1922 but not one by one either)
- can't edit 🖊️ `youtube.com` tag and submit. Tag won't be merged with another dupe.

**Comment by nicosomb** [comment]
Reproduced on master. Not related to app.wallabag.it.
