### ISSUE TITLE
Wrong display in wallabag dennikn.cz

### ISSUE THREAD

**Issue by vojtapolasek** [wallabag/wallabag#6334]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://denikn.cz/1088308/fejeton-ivy-pekarkove-chvala-penez/
 - wallabag version: 2.5.4

**Describe what's wrong:**
The content is behind paywal, but I have added correct login info into Wallabag. I expect the content to be fetched correctly.
there is already even a config file for the dennikn.cz server, but for some reason it does not work.

**Comment by HolgerAusB** [comment]
the problem with paywall is, that one needs to have a subscription to modify and test new configs. If you are selfhosting, try to modify the login_uri, because the current link only shows an offer but not log-in field.

`login_uri: https://predplatne.denikn.cz/sign/in/`

**Comment by HolgerAusB** [comment]
@vojtapolasek have you tried my suggestion? Does it work?

**Comment by vojtapolasek** [comment]
Hello, I can modify the file, but I was not able to find out correct parameters. I tried it with Firefox web console and with Mitmproxy... but I am blind and I use screenreader and unfortunately these tools are not ideally accessible... What other tools for capturing HTTPS traffic would you recommend please?

**Comment by HolgerAusB** [comment]
@vojtapolasek,  I looked a bit deeper and must say, that login-page is using kind of ajax/scripting for the login process. I don't know if we could get around this. But I also saw, that the previously used login_uri was correct but there might be a parameter ('url') missing, which we could try to set via `login_extra_fields`

Please try the following in `.../wallabag/vendor/j0k3r/graby-site-config/denikn.cz.txt` and report if that helps:

```
title: //h2[contains(concat(' ',normalize-space(@class),' '),' e_title ')]
author: //cite[contains(concat(' ',normalize-space(@class),' '),' e_author_t ')]
date: //time[@class='e_terms_posted']
strip: //article[contains(concat(' ',normalize-space(@class),' '),' a_art__link ')]
strip: //div[contains(concat(' ',normalize-space(@class),' '),' t_thankyou ')]//p
body: //div[contains(concat(' ',normalize-space(@class),' '),' b_single_e ')]//p | //div[contains(concat(' ',normalize-space(@class),' '),' a_single__post ')]

requires_login: yes

login_uri: https://predplatne.denikn.cz/
login_username_field: email
login_password_field: password
login_extra_fields: url=@=xpath("//meta[@property='og:url']/@content", request_html(config.getLoginUri()))

not_logged_in_xpath: //div[contains(concat(' ',normalize-space(@class),' '),' e_lock_button_login ')]

test_url: https://denikn.cz/3186/jsem-vnitrne-vyhorely-mam-odpracovano-cunek-je-stary-provokater-rika-belobradek/
```

If this doesn't help, I recommend installing the Firefox-Plugin 'wallabagger'. In it's settings you need to set your wallabag credentials and activate the option 'Retrieve content from the browser by default when saving page'. Now you can hit Alt+W on any site to fetch the current page, which is not only sending the url to wallabag but the hole content. With Shift+Alt+W you can just sending the URL if necessary for other sites.

Please give feedback (included anyone else with a subscription on denikn.cz) if this works or you find out other working parameters.

**Comment by HolgerAusB** [comment]
Sorry @vojtapolasek, I needed to edit my previous post, as I was wrong about the base url for log-in. So try the current version above and not the version which might be in your email-notification.

Another way, worth to to try, is setting the url-parameter directly to the login_uri field and not using the extra_field:

```
title: //h2[contains(concat(' ',normalize-space(@class),' '),' e_title ')]
author: //cite[contains(concat(' ',normalize-space(@class),' '),' e_author_t ')]
date: //time[@class='e_terms_posted']
strip: //article[contains(concat(' ',normalize-space(@class),' '),' a_art__link ')]
strip: //div[contains(concat(' ',normalize-space(@class),' '),' t_thankyou ')]//p
body: //div[contains(concat(' ',normalize-space(@class),' '),' b_single_e ')]//p | //div[contains(concat(' ',normalize-space(@class),' '),' a_single__post ')]

requires_login: yes

login_uri: concat( 'https://predplatne.denikn.cz/sign/in?url=', //meta[@property='og:url']/@content )
login_username_field: email
login_password_field: password

not_logged_in_xpath: //div[contains(concat(' ',normalize-space(@class),' '),' e_lock_button_login ')]

test_url: https://denikn.cz/3186/jsem-vnitrne-vyhorely-mam-odpracovano-cunek-je-stary-provokater-rika-belobradek/
```

**Comment by vojtapolasek** [comment]
Hello and thank you. I have some news. I tried both of your suggested configurations by docker exec into the container and modifying the file.
None of them worked. I tried to enable the Wallabagger option you suggested (I am already using the extension) and when I open the site in my browser, it works.
I also went into my account settings and tried to edit credentials for denikn.cz... but I found a strange thing. Whenever I click "edit" at the credential, I see the domain filled in, but the user name and password fields are always blank. Even after I fill them in, click save, and then click edit again. Is this expected?
Could you point me to database table where I can check this configuration?
Thank you.

**Comment by HolgerAusB** [comment]
I am not a dev and I don't know about databases. The credentials in wallabag indeed do not show, when editing existing ones. Don't bother about that, they are in. Hostname should be `denikn.cz` without 'http(s)://'. Login should be your email-address, you used to register denikn. And of course your password.

**Comment by HolgerAusB** [comment]
Sorry, I forgot to write, that you need to clear wallabag's cache each time you change the config. I don't know, how to do this with docker (maybe restarting the container helps).

For my Debian GIT-install it is:
`sudo -u www-data /path/to/wallabag/bin/console --env=prod cache:clear`

**Comment by digicommons** [comment]
A few days ago, I realized that denikn.cz wasn't loading properly anymore, just to find out that it had already been fixed :) I can confirm that the following approach works when using site credentials:

> ```
> requires_login: yes
> 
> login_uri: https://predplatne.denikn.cz/sign/in
> login_username_field: email
> login_password_field: password
> login_extra_fields: url=@=xpath("//meta[@property='og:url']/@content", request_html(config.getLoginUri()))
> ```

Thank you, @HolgerAusB!

PS: Tested with this URL:
```
test_url: https://denikn.cz/1299903/byl-to-takovy-soudruh-panbicek-duch-bozi-byl-v-cudu-vzpomina-reziserka-dabrowska-na-to-jak-za-komunismu-vyrustala-v-podzemni-cirkvi/
```

**Comment by HolgerAusB** [comment]
Thank you for confirmation, @digicommons. The change is now in the official repository. Wallabag will get this with one of its next releases, I think.
