### ISSUE TITLE
Composer version higher than composer.json constraint

### ISSUE THREAD

**Issue by Epy** [wallabag/wallabag#6353]
Hi !

### Environment

* **Version**: `git clone https://github.com/wallabag/wallabag.git` (today)
* **Installation**: with `make install` or `SYMFONY_ENV=prod composer install -o --no-dev -vvv`
* **PHP version**: 7.4 
* **OS**: Debian Bullseye
* **Database**: Postgresql
* **Parameters**: N/A

### What steps will reproduce the bug?
I'm trying to install the latest stable wallabag, using your doc and this one: https://wiki.valde.fr/fr/self-hosted/wallabag
It has no major problems, except composer current version is higher than the one in composer.json file, as says the error I'm getting:

```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires composer < 2.3, found composer[2.5.4] but it does not match the constraint.

```
I may be able to force the composer installer to install version 2.3, but I'm not sure if it could have security issues.

Composer update returns the same error:
```
# sudo -u wallabag /usr/local/bin/composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires composer < 2.3, found composer[2.5.4] but it does not match the constraint.
```

What is the best solution from here ?

What if I update composer.json wth the actual version or if someone update it on the git repo ? Could it break everything ?

Thanks !

**Comment by nomad-fr** [comment]
same trouble on FreeBSD 13.1-RELEASE-p7 in a jail with PHP 8.1

`Root composer.json requires composer < 2.3, found composer[2.5.5] but it does not match the constraint.`
