### ISSUE TITLE
[Suggestion]: When clicking the "Unread entries" area ...

### ISSUE THREAD

**Issue by YouveGotMeowxy** [wallabag/wallabag#6362]
**Is your feature request related to a problem? Please describe.**

A very nice, Quality of Life addition to Wbag would be to add: when clicking the entire area at the top where it says "Unread entries", and the entire blank area to it's right all the way up to the Plus sign, would auto switch that area to the "add new entry" field, just as if you had clicked that plus sign manually.

I noticed this as I was manually adding 10+ new links to my Wbag, and thought how much nicer it would be if I didn't have to keep clicking that relatively small plus sign to do it. I kept finding myself mentally on autopilot after adding 2-3 links, and just trying to click that blank area to add the next one, and then repeatedly saying to myself, "oh, I have to click the little plus sign again".

Keep the Plus icon there as usual, but just include the auto switch to adding a new link field if that area is clicked, as well.

And it actually makes sense to add this since Wbag is literally all about adding links, so making it super easy/easier, fits right into the overall project concept.

**Comment by nicosomb** [comment]
@Simounet Do you think that it's possible ?

**Comment by Simounet** [comment]
Not sure about the not so obvious UI behaviour but this is a great idea! Did a PR for it https://github.com/wallabag/wallabag/pull/6612 .

**Comment by nicosomb** [comment]
Thank you @YouveGotMeowxy & @Simounet !
