### ISSUE TITLE
Image not loaded from medium

### ISSUE THREAD

**Issue by mbouksim** [wallabag/wallabag#6365]
Environment

- wallabag version (or git revision) that exhibits the issue:  2.5.2
- How did you install wallabag? Via git clone
- php version: 7.4
- OS: Fedora 37
- type of hosting (shared or dedicated): dedicated
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL/MariaDB

Steps to reproduce/test case

- Add URL: https://towardsdatascience.com/equal-size-spectral-clustering-cce65c6f9ba3
- The aricle is loaded correctly but without images
I got the same error using app.wallabag.it

**Comment by Oppen** [comment]
While not a real fix, what I do for Medium is simply using a Scribe proxy. Those tend to work well with Wallabag.

**Comment by Kdecherf** [comment]
This issue is due to HTMLawed not accepting `source` tags in `picture` blocks, I'll take care of it.
