### ISSUE TITLE
Delete account on wallabag.it doesn't work

### ISSUE THREAD

**Issue by acolombo25** [wallabag/wallabag#6375]
I'm trying to delete my account on wallabag.it.

I get the following error:

`Oops! An Error Occurred
The server returned a "405 Method Not Allowed".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. `

I don't know if this problem is related only to the instance on wallabag.it or in general to the app.

**Comment by nicosomb** [comment]
Hmm I tried with a very old account and a new one, and it works. 

But you are not the only one to have this error. I will have to dive into the code ...

**Comment by nicosomb** [comment]
@acolombo25 could you try again please?

**Comment by acolombo25** [comment]
> @acolombo25 could you try again please?

just tried now, still getting the same error

Oops! An Error Occurred
The server returned a "405 Method Not Allowed".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by nicosomb** [comment]
Ooooh I found the issue. 
You tried to delete your account from the subscription view. 

It's now fixed. 

Could you confirm that please?
