### ISSUE TITLE
Repeating notifications

### ISSUE THREAD

**Issue by konfiot** [wallabag/wallabag#648]
Hello,
When poching multiple links in a short period of time, the notifications on the top appear multiple times on one page and do not appear on other pages.
![Screenshot](https://cloud.githubusercontent.com/assets/961690/2740850/2372c580-c6dc-11e3-8c14-8438bb02e829.png)
Wallabag 1.6.1, PHP 5.4.4, Apache 2.2.22

**Comment by nicosomb** [comment]
Won't be fixed in 1.x. And this bug doesn't appear in 2.x.
