### ISSUE TITLE
Wrong display in wallabag (blast-info.fr)

### ISSUE THREAD

**Issue by setop** [wallabag/wallabag#6482]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://www.blast-info.fr/articles/2023/mark-zuckerberg-lhomme-qui-assassina-lamitie-auZbx-ROT_uqfFGbdCo3dQ
 - wallabag version: 2.5.4

**Describe what's wrong:**

Got a paywall.

**Comment by pipoprods** [comment]
The page we're getting is not a paywall but the static contents of the site that is now based on Nuxt which needs Javascript interpretation for the contents to appear :(
