### ISSUE TITLE
Wrong display in wallabag (mediapart.fr)

### ISSUE THREAD

**Issue by Napator** [wallabag/wallabag#6498]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [X] I've tried myself without success
- [X] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://www.mediapart.fr/journal/international/060523/aux-etats-unis-des-milliers-de-femmes-victimes-de-l-industrie-cosmetique
 - wallabag version: wallabat.it (2.5.4)

Paywall not solved despite good credentials in app configuration : "La lecture des articles est réservée aux abonné·es. [Se connecter]"

Tried to add "login-extra-fields: op=Se+connecter" in config file.

Maybe it is the cookie "MPSESSID" which needs to be retained after "login-check", but i didn't find any way to manage this in available documentation.

Thank you for your help

**Comment by Simounet** [comment]
Hi @Napator I just tested on wallabag.it and it's working as expected with the article you provided. Are you sure not having extra spaces around your info? Using `mediapart.fr` as an host configuration?

**Comment by Napator** [comment]
Thank you very much for your anwser, i've just tried again with "mediapart.fr" instead of "www.mediapart.fr". It works now !

**Comment by Simounet** [comment]
Good to hear. Enjoy!
