### ISSUE TITLE
Site credentials not working on wsj.com

### ISSUE THREAD

**Issue by nwa573** [wallabag/wallabag#6511]
Starting a couple of days ago, I can no longer fetch complete articles from wsj.com. For example, the article https://www.wsj.com/articles/ftx-founder-sam-bankman-fried-seeks-dismissal-of-criminal-charges-19fe469b shows only a couple of paragraphs and then says "Already a subscriber? Sign in" although I have entered my site credentials in Wallabag.

I'm using wallabag.it.

**Comment by FahadBinHussain** [comment]
I am encountering the precise identical problem. Kindly address it expeditiously.

**Comment by HolgerAusB** [comment]
There is no section for paywall yet in the site_config  `wsj.com.txt`. So entering your credentials into the wallabag UI has no effect. When I try to fetch the example URL from May 10, I get the whole article with my self-hosted wallabag 2.6.2

They don't use a real paywall there, just a curtain with full content already loaded behind.

So please post new article URLs where full content is not working.

Are you using browser-plugin Wallabagger with "use browser retrieved content" activated? ... while not logged in with browser?

**Comment by FahadBinHussain** [comment]
The Nixnet instance API I'm using doesn't seem to be retrieving this complete article, like the one found at:
 https://www.wsj.com/tech/personal-tech/if-one-flatscreen-tv-on-your-wall-isnt-big-enough-try-four-e4bcbc0e

**Comment by HolgerAusB** [comment]
This indeed seems to be a payWALL issue. I am am not a dev and don't have the skills to help with that. Have you tried the wallabagger addon for chrome based browsers like firefox? In it's settings you can activate "Content fetching from the browser", which helps on many websites with heavy scripting or paywall (paid and already logged in, of course).

**Comment by FahadBinHussain** [comment]
Sure, I'll give the wallabagger extension a try and keep you posted on how it goes. However, when you mentioned 'chrome based browsers like firefox', I must clarify that Firefox is not based on Chromium.

**Comment by FahadBinHussain** [comment]
> This indeed seems to be a payWALL issue. I am am not a dev and don't have the skills to help with that. Have you tried the wallabagger addon for chrome based browsers ~like~ and Firefox? In it's settings you can activate "Content fetching from the browser", which helps on many websites with heavy scripting or paywall (paid and already logged in, of course).
> 
> Also read [blog article of @Kdecherf about shortcuts with wallabagger](https://kdecherf.com/blog/2023/08/02/fetch-content-from-browser-on-demand-with-wallabagger/)

I tried out the wallabagger extension but found that it is not functioning properly. The articles on WSJ are still behind a paywall and are not being fully fetched. Is there a solution to retrieve the entire articles from WSJ?

**Comment by HolgerAusB** [comment]
@FahadBinHussain is it possible that wsj changed their design lately? The selectors in the site_config seem not to exist any more.

Do you have, by chance, any link to an article without paywall. Just need that to find things to strip after the article ends.

**Comment by FahadBinHussain** [comment]
> @FahadBinHussain is it possible that wsj changed their design lately? The selectors in the site_config seem not to exist any more.
> 
> Do you have, by chance, any link to an article without paywall. Just need that to find things to strip after the article ends.

@HolgerAusB I figured it out! All you need to do is modify the URL slightly to restore things to how they were. 
For instance, change the link from (https://www.wsj.com/tech/ai/some-of-the-thorniest-questions-about-ai-will-be-answered-in-court-e7fd444b) to (https://www.wsj.com/amp/articles/some-of-the-thorniest-questions-about-ai-will-be-answered-in-court-e7fd444b), and then simply send it to the Wallabag API or normally save it in your instance. 

Works like a charm!

**Comment by FahadBinHussain** [comment]
This JavaScript code accomplishes the identical task.

`function removeDOMElement(...elements) {
  for (let element of elements) {
    if (element)
      element.remove();
  }
}

let url_article = window.location.pathname.includes('/articles/');
let path_article = window.location.pathname.match(/((\w)+(\-)+){3,}\w+/);
if (url_article || path_article) {
  if (window.location.pathname.startsWith('/amp/')) {
    amp_unhide_subscr_section();
    let masthead_link = document.querySelector('div.masthead > a[href*="-"]');
    if (masthead_link)
      masthead_link.href = 'https://www.wsj.com';
  } else {
    let snippet = document.querySelector('.snippet-promotion, div#cx-snippet-overlay');
    let wsj_pro = document.querySelector('meta[name="page.site"][content="wsjpro"]');
    if (snippet || wsj_pro) {
      removeDOMElement(snippet, wsj_pro);
      if (url_article)
        window.location.href = window.location.href.replace('wsj.com', 'wsj.com/amp');
      else
        window.location.href = '/amp/articles/' + path_article[0];
    }
  }
}
let ads = document.querySelectorAll('div.wsj-ad, div.adWrapper, div.uds-ad-container');
removeDOMElement(...ads);`

**Comment by nwa573** [comment]
I'm having this issue again; I'm on Android and use the DuckDuckGo browser to share things to the wallabag app. Here's an example of an article that didn't download: https://www.wsj.com/arts-culture/food-cooking/the-best-peak-summer-tomato-recipes-straight-from-rome-48853da

**Comment by HolgerAusB** [comment]
@FahadBinHussain I now see the problem. What you described is a trick, where your load the page for mobile browsers or special apps. On that version there is no paywall. In the config this parameter formerly did that:

`single_page_link: concat('https://www.wsj.com/amp/', substring-after(//link[@rel="canonical"]/@href, 'https://www.wsj.com/'))`

The problem is, that wsj changed the system and now have some categories between the hostname and the article identifier, in your example `/tech/ai/`, unfortunatly I can't find a way in XPath/1.0 to get the last part of the URL after the last slash.

**Comment by FahadBinHussain** [comment]
> @FahadBinHussain I now see the problem. What you described is a trick, where your load the page for mobile browsers or special apps. On that version there is no paywall. In the config this parameter formerly did that:
> 
> `single_page_link: concat('https://www.wsj.com/amp/', substring-after(//link[@rel="canonical"]/@href, 'https://www.wsj.com/'))`
> 
> The problem is, that wsj changed the system and now have some categories between the hostname and the article identifier, in your example `/tech/ai/`, unfortunatly I can't find a way in XPath/1.0 to get the last part of the URL after the last slash.

Maybe you can try to use a regex to catch the last part? For example, I used a regex to replace the category part of the links in my discord bot. Check here:(https://github.com/FahadBinHussain/wallabot/commit/7b3d16e81b5a9cd29f9f8ae3bdcff468eb9bfb98)

**Comment by FahadBinHussain** [comment]
> I'm having this issue again; I'm on Android and use the DuckDuckGo browser to share things to the wallabag app. Here's an example of an article that didn't download: https://www.wsj.com/arts-culture/food-cooking/the-best-peak-summer-tomato-recipes-straight-from-rome-48853da

@nwa573, please take a look at my solution in the comment above. You can find it here: https://github.com/wallabag/wallabag/issues/6511#issuecomment-1694328733

**Comment by HolgerAusB** [comment]
@FahadBinHussain, I am not a dev to graby and I do not have the skills to make such changes to the code. I am just able make or change the site_configs from [fivefilters](https://github.com/fivefilters/ftr-site-config) which are used in wallabag. Ans unfortunately there is no regex in XPath/1.0 an I did't find an other way, to extract this.

On the other hand, this is kind of misusing the single_page_link method to get behind the paywall.

I am just writing a new site_config that will work with wallabagger, of course, that will need a subscription and a logged-in (wsj) user. Maybe I PR this later this day

**Comment by HolgerAusB** [comment]
@FahadBinHussain, @nwa573 I finally found a way to get around this.

For app.wallabag.it you unfortunately have to wait for the next release :-( @nicosomb, @j0k3r please consider to update site_configs again with 2.6.5, because The Wallstreet-Journal is a big site.

**Comment by j0k3r** [comment]
This will be done.
