### ISSUE TITLE
Wrong display in wallabag (elements.visualcapitalist.com)

### ISSUE THREAD

**Issue by Pierric82** [wallabag/wallabag#6516]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL:  https://elements.visualcapitalist.com/the-solar-power-duck-curve-explained/
 - wallabag version: 2.5.4 (running on Docker wallabag/wallabag:latest)

**Describe what's wrong:**
That page gets parsed incorrectly. It's one of those sites where scrolling beyond the end of the article adds more articles; it seems that instead of the main article, what gets parsed is the 2nd next article...
f43.me gets it wrong as well (getting the same content), which is why I open this ticket as suggested.

**Comment by Pierric82** [comment]
Thank you for the update! Which version / when should this change be reflected in wallabag releases?

**Comment by j0k3r** [comment]
It'll be available in the next release: 2.6.2
