### ISSUE TITLE
Docker : can't import pocket data : PHP Warning:  mkdir(): Permission denied 

### ISSUE THREAD

**Issue by fseraphine** [wallabag/wallabag#6663]
With a docker installation on Synology, I can't import pocket data.

Wallabag seems to want to create a directory somewhere and has a permission denied error.

But on the two share volumes (data and images), everyone can read/write.

### Environment

* **Version**:  latest / 2.6.1
* **Installation**: Docker
* **PHP version**: N/A
* **OS**: N/A
* **Database**: SQLite 
* **Parameters**:

  ```
2023/06/23 09:28:06 [error] 54#54: *125 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/wallabag/vendor/friendsofsymfony/jsrouting-bundle/Extractor/Expose RoutesExtractor.php on line 179" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET /js/routing?callback=fos.Router.setData HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mywallabaghost", referrer: "https://mywallabaghost/import/pocket"  
  ```

**Comment by j0k3r** [comment]
Have you checked rights for the `var` folder as well?

https://doc.wallabag.org/en/admin/installation/rightaccess.html

**Comment by fseraphine** [comment]
This folder is inside the docker container and not mapped from an outside volume.

Permissions are : 
```
/var/www/wallabag # ls -ld var                                                                     
drwxrwxr-x    1 nobody   nobody          34 Jun 26 08:17 var
```

But I wonder how I encounter theses difficulties. I can't be the sole one trying the docker container. Must be something on my side. Perhaps docker capabilities or root permissions.

**Comment by fseraphine** [comment]
I found out ! On Synology NAS you must check "Execute this container with high privileges"

![image](https://github.com/wallabag/wallabag/assets/5850015/5ceb781b-e47f-4a34-b3ac-d53e7555231f)
