### ISSUE TITLE
Can’t select a post without picture for mass ation

### ISSUE THREAD

**Issue by ldidry** [wallabag/wallabag#6664]
### Environment

* **Version**: 2.6.1
* **Installation**: git clone, make install
* **PHP version**: 8.1
* **OS**: Debian
* **Database**: PostgreSQL

### What steps will reproduce the bug?

Have a page saved with no thumbnail (ex: https://sebsauvage.net/wiki/doku.php?id=deepfilternet).
Click the mass action icon in the list of pages: no checkbox is added to the pages without a thumbnail (well, the thumbnail is in fact the wallabag logo).

**Comment by Simounet** [comment]
Can you give me a screenshot? I can use mass action with the default wallabag logo:
![wallabag-issue](https://github.com/wallabag/wallabag/assets/582666/11a9fde6-8713-4272-b6c2-dae11475f00b)

**Comment by ldidry** [comment]
I use the dark theme, may it be the source of the bug?

![Screenshot 2023-06-26 at 09-24-13 Articles non lus – wallabag](https://github.com/wallabag/wallabag/assets/922350/72cb6ce9-d16d-4750-a440-22ee112d58a1)

**Comment by Simounet** [comment]
Yep, that was the issue. Will be fixed with https://github.com/wallabag/wallabag/pull/6673 .

**Comment by ldidry** [comment]
:+1:  Thanks!
