### ISSUE TITLE
Allow the docker container to run rootless

### ISSUE THREAD

**Issue by fseraphine** [wallabag/wallabag#6670]
**Is your feature request related to a problem? Please describe.**
When installing Wallabag on my Synology NAS, I must enable root privileges to the container for it to run without errors. This settings is opening a security hazard.

**Describe the solution you'd like**
Change the container construction to allow rootless exécution

**Comment by j0k3r** [comment]
Duplicate of https://github.com/wallabag/docker/issues/330
