### ISSUE TITLE
No login possible with 2.6.1

### ISSUE THREAD

**Issue by Shadow27374** [wallabag/wallabag#6676]
With the new version (2.6.1), I get the following message when logging in:

> Authentication request could not be processed due to a system problem

If I use the previous Docker image (2.5.4) it works.

**Comment by Linuxine** [comment]
Hi ! 

First of all, thanks for all the work on Wallabag, and the new version seems to have a lot of nice features ! 
But I dit not test it yet because I have the same error here, with the latest Docker Image. 
I found no error message in the logs of the container, and same, with the previous docker image, and the same parameters (database, mount points for the container) there was no issue. Is there a migration to perform between version ?
Thanks in advance for the help !

**Comment by nicosomb** [comment]
Could you please read this blog post and apply the requested changes https://wallabag.org/news/20230621-new-release-wallabag-261/  ?

**Comment by Linuxine** [comment]
Oh sorry, I just realized, as we are using the Docker image, maybe this is not the right Github repository to submit an issue ? Thanks for the answer, I will try tomorrow to perform the update on my db !

**Comment by Shadow27374** [comment]
> Oh sorry, I just realized, as we are using the Docker image, maybe this is not the right Github repository to submit an issue ? Thanks for the answer, I will try tomorrow to perform the update on my db !

So it works for me now. What we need to do with Docker is only the database modification.

In my case it's a MirandaDB, so MySQL:

```
ALTER TABLE wallabag_config DROP theme;
ALTER TABLE wallabag_user CHANGE backupCodes backupCodes JSON DEFAULT NULL;
ALTER TABLE wallabag_config ADD display_thumbnails INT(11) NOT NULL DEFAULT 1;
```

**Comment by YouveGotMeowxy** [comment]
@nicosomb How do I do `make update` with the docker container?

**Comment by Kdecherf** [comment]
@YouveGotMeowxy first you need to change the version number of the docker image you use, thus you can use the command below to update the database and it should be enough.

@Shadow27374 you should be able to do that by running the following steps:

```
docker-compose stop php
docker-compose run --rm php migrate
docker-compose up -d php
```

**Comment by Linuxine** [comment]
Thanks @Shadow27374 for the  SQL queries to perform !  Were did you found them ? I was looking at https://doc.wallabag.org/en/admin/query-upgrade-25-26.md but did not found them ?

For information, I am currently using the Docker Image from https://hub.docker.com/r/wallabag/wallabag, with a sqlite database. 

I connected to my db from the host, and performed the following queries (sqlite does not allow to change the type of a table AFAIK, so I had to copy/delete/rename):

```
ALTER TABLE wallabag_config DROP theme;
ALTER TABLE wallabag_config ADD display_thumbnails INT(11) NOT NULL DEFAULT 1;
ALTER TABLE wallabag_user add column backupCodes2 JSON DEFAULT NULL;
UPDATE wallabag_user set backupCodes2  = CAST(backupCodes as JSON);
ALTER TABLE wallabag_user DROP backupCodes;
ALTER TABLE wallabag_user RENAME COLUMN backupCodes2 to backupCodes;
```

And after that, tadaa, up and running :partying_face: 
Thank you all ! :hugs:
