### ISSUE TITLE
Add sharing support for unmark.it

### ISSUE THREAD

**Issue by tristan-k** [wallabag/wallabag#668]
Hi there,

I recently found out about unmark.it (https://github.com/plainmade/unmark), which can also be self hosted.

Is it possible to integrate a sharing button for the service, much like for shaarli?

Thanks.

**Comment by j0k3r** [comment]
We can still support it, but does someone care about that (ssl certificat is dead, no release / activity since few months, etc..) ?

The url to add a direct link:

```
https://unmark.it/mark/add?url=URL&title=TITLE&v=6
```

**Comment by nicosomb** [comment]
https://twitter.com/unmarkit/status/717482447949139968

**Comment by nicosomb** [comment]
Done in #2566.
