### ISSUE TITLE
Major UX issue : Delete an entry without confirmation

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#6693]
### Environment

* **Version**: 2.6.1
* **Installation**: Docker
* **PHP version**: Docker
* **OS**: Docker
* **Database**: Postgres
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  PASTE HERE
  ```
</details>

### What steps will reproduce the bug?

Tap on the delete button on the home page.

Since few versions (I would say since 2.5.3), it's possible to delete an entry from the home page without being asked to confirm. This is a major usability issue, in particular on touch devices where it's easy to tap on something by mistake.

Any destructive action must always ask for confirmation. This statement is valid for every app, not only Wallabag.

**Comment by nicosomb** [comment]
Hello @romu70! 

Are you sure to be on 2.6.1? 
Because I fixed this bug here: https://github.com/wallabag/wallabag/pull/6644 which is shipped in 2.6.1.

**Comment by romu70** [comment]
I think so.

<img width="330" alt="Screenshot 2023-07-04 at 15 18 30" src="https://github.com/wallabag/wallabag/assets/1898319/05ea4554-ae6d-4a84-88a8-24558c33f540">

**Comment by nicosomb** [comment]
So I close this issue 😃 Feel free to reopen it if necessary.
