### ISSUE TITLE
Footnotes lost in article

### ISSUE THREAD

**Issue by lightonflux** [wallabag/wallabag#670]
I used wallabag with this article:

http://blog.tjll.net/ssh-kung-fu/

There are two footnotes below the article, which wallabag missed. 

Luckily the HTML is 

    <div class="footnotes">

so at least for this site the fix should be easy. But i don't know how other blog software handles footnotes.

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.

**Comment by lightonflux** [comment]
Does this work in 2.0? I don't have a v2 instance for testing at the moment.
