### ISSUE TITLE
change "w"-links to internal links if the linked article is wallabagged 

### ISSUE THREAD

**Issue by lightonflux** [wallabag/wallabag#671]
In articles in wallabag there is this w-link next to links. If you wallabagged a link then the w-link should be internal to the other wallabagged article.
![35](https://cloud.githubusercontent.com/assets/1377943/2836418/d2961bf6-cffc-11e3-8f15-68389c4170a2.png)

**Comment by j0k3r** [comment]
Can someone clearly explain what should be done here?
I've no idea what this "w" link is.

**Comment by nicosomb** [comment]
In wallabag v1, after each link in an article, you have a "W" (see screenshot): if you click on it, it saves the article in your wallabag. 

![capture d ecran 2016-04-14 a 14 18 25](https://cloud.githubusercontent.com/assets/121870/14527691/e3c1f2b4-024b-11e6-96a5-6da03917e40d.png)

**Comment by tcitworld** [comment]
This can be done through the API now that we have the `exists` call.
