### ISSUE TITLE
New config for medium.com based sites. Should I overwrite medium.com.txt?

### ISSUE THREAD

**Issue by HolgerAusB** [wallabag/wallabag#6711]
I just wrote a config for medium.com based sites and PRed some of theese. But I am not sure if I should also overwrite the content of the existing files `medium.com.txt` and `.medium.com.txt`

In particular, there might be other contents with different schemes on the www.medium.com website, or?

So what do you think?
```
# website-engine: medium.com
http_header(user-agent): Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)

body: //article

strip: //h1[contains(@class, 'pw-post-title')]
strip_id_or_class: speechify-ignore
strip: //a[@rel='noopener  ugc nofollow']/parent::div
strip: //p[contains(text(), 'You may also be interested in')]/self::p | //p[contains(text(), 'You may also be interested in')]/following-sibling::*
strip: //footer/self::footer | //footer/following-sibling::*

# rewrite image-links to plain html
find_string: source srcSet="http
replace_string: img src="http
find_string: .png 640w,
replace_string: .png"><foo bar="
find_string: .jpg 640w,
replace_string: .jpg"><foo bar="
find_string: .jpeg 640w,
replace_string: .jpeg"><foo bar="
find_string: .gif 640w,
replace_string: .gif"><foo bar="

strip: //img[contains(concat(' ',normalize-space(@class),' '),' bg ')]

tidy: no
prune: no
```

**Comment by Strubbl** [comment]
Good question. I do not know if that helps with the decision, but i have some example links for subdomains:

https://clivethompson.medium.com/linux-on-the-laptop-works-so-damn-well-that-its-boring-29014b347941
https://lilithwittmann.medium.com/bundesservice-telekommunikation-wie-ich-versehentlich-eine-tarnbeh%C3%B6rde-in-der-bundesverwaltung-a8823f308536
https://robthorne-26852.medium.com/integrating-javascript-frameworks-into-your-golang-projects-57d662033130

**Comment by j0k3r** [comment]
I'm sure @fivefilters has a point of view on this :)

**Comment by HolgerAusB** [comment]
I just realized, that FTR has a fingerprint for medium.com based sites. I need to investigate this deeper, because that doesn't work properly/reliably on my Test-FTR.

@j0k3r is there generally a fingerprinting available in graby/Wallabag? If yes, is there allready one for medium.com in?

**Comment by fivefilters** [comment]
The sub domains should be handled okay with the .medium.com.txt files. For platforms like Medium that offer custom domains, where medium.com is not in the URL at all, Full-Text RSS uses fingerprints to try and match an HTML fragment to a site config file. I haven't checked if the one we use for Medium is still valid (it was added years ago). It looks for this fragment: `<meta data-rh="true" property="al:ios:app_name" content="Medium"/>` I'll see if I can find out if this is still valid, but I don't think it should influence the decision on your proposed site confic @HolgerAusB 

Personally, I don't think we should worry too much about existing rules and whether we may be overwriting something that still matches in certain cases. If those cases are important enough, I think we should add comments to the site config files with URLs, so later on we can see if the URL that resulted in a particular rule still needs special consideration. It's quite time consuming to try and find articles where a particular rule may still be valid years later, so unless they're signposted in this way, I'm personally in favour of accepting new rules to replace existing ones if someone's gone to the trouble of testing the new rules on a few current articles. I think the best thing we can do is test the test_urls at the bottom of the site config file and if they still work, I'm in favour of merging.

**Comment by Kdecherf** [comment]
I think the find/replace stuff for replacing `source` tags with `img` is not a good idea. There's work in progress to stop stripping tags within `picture` html5 tags that should fix this.

**Comment by fivefilters** [comment]
Is the reason for the srcset find/replace rules because such images currently get stripped? Or is it to ensure absolute image URLs?

**Comment by HolgerAusB** [comment]
@fivefilters:
The currently used fingerprint in FTR is valid for current medium sites. However, FTR sometimes did not apply it. I will test that during the weekend again intensively and report to the FTR forum.

The problem with current `.medium.com.txt` is, that FTR gets an `[unable to retrieve full-text content]` error. So I made a config, that works both, with FTR and wallabag.

But these changes made it necessary to make some  additional clean-up, which was made by graby before automatically.

Its not only the srcset. The image is hidden within a `<source srcSet=`. And yes, the images would be striped at least for one product (wallabag/FTR). Can't check tonight.

@Kdecherf:
I am absolutely with you! This kind of image cleaning should do the software and not a string_replace orgy in the config. But at the moment there is no other way to get the most out of an article with wallabag **_and_** FTR.

'Work in progress' could, for an open source project, mean days or weeks or months or even longer. And meanwhile FTR users can't get content from these sites. I would be happy to review all the configs, I had made or modified, after this code change is the stable releases of wallabag **_AND_** FulltextRSS.

But for the moment, I think, we need this kind of config.

Since before a few weeks I've just checked my new or modified configs against FTR and believed, that this would work with wallabag the same way. But I had to learn that it does **_not_**. And it is very hard to find a way to get the most out of the content with _one_ site_config it for _both_ products. And medium is, by far, not the only site, where I had to fight hardly against the differences.

**Comment by HolgerAusB** [comment]
Maybe I just tried the wrong sites. But non of any somewhat.medium.com sites I tried was catched with images by wallabag with current config from the repo, except for the authors avatar. And there was lots of other fringe from the header in extracted content. In Fulltext-RSS (FTR) the same config throws an error and content can't be retreived.

Therefor I had to write a new config and I had to change some existing rules, in order to work with FTR and wallabag.

I understood, that the main focus is on text. Personally, I think that images should always be catched too, if it is possible anyhow. I also accept, that these string_replacements could be dangerous, when upstream site layout changes, especially for a meta-config like `.media.com.txt`.

So I decided to #comment-out the string_replacements but keep it in the config, so every self-hoster could decide him/herself to activate images. But I think I will will PR configs for medium based sites with a unique Domains with activated replacements if that site uses images to illustrate the article, e.g. with diagrams, charts or travel reports with photos.

So @Kdecherf, @j0k3r, @Strubbl and, of course, everyone else: Please check my changed config at https://github.com/HolgerAusB/ftr-site-config/blob/0174eec5556af4b16633afcb242bf80b08e8bcda/.medium.com.txt

@j0k3r does it make sense to have a fingerprint in graby, like it is already in FTR?

**Comment by fivefilters** [comment]
I tried your config with Full-Text RSS, @HolgerAusB, and the results looked good! Feel free to make a PR and if there are no objections from anyone else here, I'll merge.

**Comment by Kdecherf** [comment]
@HolgerAusB I'll take a look at the end of the week

**Comment by j0k3r** [comment]
@HolgerAusB there are fingersprint in graby as well (might be outdated compared to FTR): https://github.com/j0k3r/graby/blob/348cc5b463900cac23ac7a13905a5ee6dbdc1962/src/Extractor/ContentExtractorConfig.php#L51-L56

**Comment by HolgerAusB** [comment]
@j0k3r yes, I finally found them, but **medium.com** is missing there, while it is in FTR for a long time. 

But you implemented my ippen.media ❤ so I should restore the meanwhile deleted `.ippen.media.txt` soon. I'm not at home right now and I'm not sure but I think my Wallabag 2.6.1 didn't have a fingerprint for ippen.media yet. Are you sure that this is in the wallabag release?

**Comment by j0k3r** [comment]
Graby is based on the latest open source version of FTR (which doesn't contains medium fingerprint. We should add it.
That changes is one the master, almost ready for the 3.0.0 version. wallabag is using the 2.x version for now.

**Comment by fivefilters** [comment]
@j0k3r, the latest entries for the fingerprints in FTR are the following, feel free to use. Haven't checked to see if the Substack one is still valid, but the Medium one does appear to be:

* Medium: `<meta data-rh="true" property="al:ios:app_name" content="Medium"/>`
* Substack: `<link rel="stylesheet" type="text/css" href="https://substackcdn.com/min/main.css`

**Comment by j0k3r** [comment]
@fivefilters We need to ship a new version of wallabag itself, so you can update the site config right away.

**Comment by fivefilters** [comment]
@j0k3r Great, thanks! I've gone ahead and merged @HolgerAusB's [changes](https://github.com/fivefilters/ftr-site-config/pull/1159) now. 👍
