### ISSUE TITLE
Bug  or maybe  a missing feature

### ISSUE THREAD

**Issue by leftsidestory** [wallabag/wallabag#6724]
Version:      2.5.4
Installation: Through Cloudron
PHP version:  The version of PHP you are using
OS:          Ubuntu 20.04.6
Database:    Redis with MySql

I use Wallabag primarily on my ipad and it seems that in order to use the annotation function, I would have to select texts with the a physical keyboard. With the touchscreen, the annotation just would not show up after selection.

**Comment by nicosomb** [comment]
Hmmm you’re right. 

@Simounet any idea how can we handle that?

**Comment by Simounet** [comment]
I'll check that.

**Comment by EFLS** [comment]
This is probably the same issue as #2749

**Comment by nicosomb** [comment]
You're right, it's a duplicate.
