### ISSUE TITLE
New config screen

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#673]
Today, config page is not sexy.

We can make better. Let's go.

**Comment by j0k3r** [comment]
This is the config page for the v2:

![](https://s3.amazonaws.com/f.cl.ly/items/0A0V210t1J1s1f3M1k1w/Image%202015-02-22%20at%206.16.25%20PM.png)

Maybe we can put every category inside a tab. The page will be shorter then.

**Comment by tcitworld** [comment]
How would it be with tabs ? Especially mobile view.

**Comment by j0k3r** [comment]
That would required some CSS touch here, but these tabs can change to a kind of dropdown list when user browser the config from a mobile.

**Comment by tcitworld** [comment]
I think we can keep it this way for the moment. We can always change it later, no big deal.

**Comment by nicosomb** [comment]
> How would it be with tabs ? Especially mobile view.

Done with material theme ;-)
