### ISSUE TITLE
Wrong display in wallabag (https://www.richardkmorgan.com)

### ISSUE THREAD

**Issue by clach04** [wallabag/wallabag#6740]
**Before submitting the issue, please read:**
I have read 
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that
Wording is not super clear but sounds like a fetching content issue needs to be raised

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://www.richardkmorgan.com/2023/07/gone-but-not-forgotten/
 - wallabag version: https://app.wallabag.it/api/version reports "2.6.1"

**Describe what's wrong:**

Super unclear message in web UI with link to https://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that when adding pages from www.richardkmorgan.com

I'm trying out a trial at wallabag.it and error gives no insight into the issue.

Checking this outside of wallabag it looks like the webserver either returns 403 to non-browsers or just severs the connection if if thinks the client is a robot. It is possible to scrape the content without issue if headers are sent that match a browser (nothing else, no need for cookies, etc.) which is what I've done with a simple scraper script.

I've had a few other issues with the trial with poor scrap/epub results but this is the only one I can report with complete detail (and what the solution is). I don't believe wallabag.it offers a way to provide custom https://github.com/j0k3r/graby confing files

http://f43.me/feed/test fails with all techniques.

Hope this helps!

Off topic but kudos on a nice UI for adding URLs in the web version :+1: . The android app is also great as s Share To end point, very nice!

**Comment by HolgerAusB** [comment]
@clach04 unfortunately every website is different. Wallabag can not guess in every case what belongs to the content. It even less can recognize if this website takes measures to prevent the content from being tapped (403 forbidden).

Wallabag currently uses over 1800 config files from [fivefilters/ftr-site-config](https://github.com/fivefilters/ftr-site-config), but these are not currently automatically updated to app.wallabag.it.

I just wrote a config for richardkmorgan.com. Once that has been checked and merged and pushed to wallabag.it it should work.

In this case it was enough to use a different user-agent with 'cURL'.
