### ISSUE TITLE
Remove MOBI export

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/wallabag#6746]
Last year we've deprecated MOBI export, see #5773.

Amazon stopped supporting MOBI and AZW files for their "_Send to Kindle_" feature earlier this year.

Knowing that we embed an unmaintained and quite old dependency to support this format, I would be in favor of removing it in next minor release.

We may need to provide some documentation on how to convert other file formats to MOBI if required by a user.

Resources:
- https://en.wikipedia.org/wiki/Kindle_File_Format
- https://www.amazon.com/gp/help/customer/display.html?nodeId=G5WYD9SAF7PGXRNA

**Comment by nicosomb** [comment]
> We may need to provide some documentation on how to convert other file formats to MOBI if required by a user.

I'm not sure that wallabag documentation should document this. It's not a wallabag-related feature ...

**Comment by j0k3r** [comment]
I think we can put that information in the release note (+ in the blog post).

**Comment by Kdecherf** [comment]
@j0k3r ok with that
