### ISSUE TITLE
categorize the articles with annotation automatically

### ISSUE THREAD

**Issue by suppergit** [wallabag/wallabag#6752]
**Describe the solution you'd like**

is it possible for a feature which categorize the articles with annotation automatically？

**Comment by j0k3r** [comment]
You mean being able to filter on articles which have at least one annotation?
If so, there is already a filter for that:
<img width="283" alt="image" src="https://github.com/wallabag/wallabag/assets/62333/55a34925-d3c2-4252-aa9f-40ce3b1cecd8">

**Comment by nicosomb** [comment]
You can also see them here: `yourwallabag.com/annotated/list`.
