### ISSUE TITLE
Not scraping the entire page (newsletter.pragmaticengineer.com)

### ISSUE THREAD

**Issue by iHateCode** [wallabag/wallabag#6757]
**Before submitting the issue, please read:**

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://newsletter.pragmaticengineer.com/p/the-scoop-50-why-are-many-snap-employees
 - wallabag version: Firefox 1.16.0

**Describe what's wrong:**
Instead of archiving the entire page, it only archives the publicly accessible portion. I am logged in and can see the entire article in my browser.

**Comment by HolgerAusB** [comment]
First thing you should know is, that wallabag does not grab the content from your browser. It is a server, which tries to get the content directly from the destination. You only send the link/URL to wallabag.

Paywalls are kind of problematic here. Every website that need a login has to be configured manually (once per site, not per wb user) and even that is not possible for all sites. e.g. when they are using java script or captcha

I just signed-up a free account and found out that this is a substack site and you can login in either by getting a one-time login-link by email or by emailaddress+password+CAPTCHA

email+password might be possible, but the software can't pass the captcha test.

So I don't see a chance to grab full articles, except of this one monthly free article. But I am not a dev, maybe I am wrong.

**Comment by Kdecherf** [comment]
A possible workaround is to use the "content fetched from browser" feature of wallabagger, it'll save the content of the page loaded by your browser on wallabag, it's not perfect though and it implies to open the page in your browser first.

**Comment by HolgerAusB** [comment]
nice @Kdecherf, I didn't even know that this firefox-plugin is able to do this. Is there a simple way to do this on-the-fly for a single page? In settings I can activate to do so for all pages or for a list of URLs (I hope that means domains).

**Comment by iHateCode** [comment]
@Kdecherf, could you link me to that feature within the docs? I want to try it. Many articles and resources are behind login screens, so this feature is essential to me. I often come across these websites at work and on my usual go-to websites.

Thank you, @HolgerAusB, for explaining how it works. I did expect that it was scraping websites on the server side rather than the client side, like on OneNote. 

So what I need is a new addon which scrapes and stores the website locally and then uploads to a temporary public website which I can thenWallabag to Save from. Probably overkill.. but I do need to figure this out.

**Comment by HolgerAusB** [comment]
@iHateCode firefox-plugin Wallabagger:
https://addons.mozilla.org/de/firefox/addon/wallabagger/

In the settings of this ff-plugin you can activate this feature for all sites or for a list of domains.

Please report if this works for newsletter.pragmaticengineer.com

**Comment by nicosomb** [comment]
FYI, this addon works with Firefo, Chrome and Opera.

**Comment by nicosomb** [comment]
We need to add more documentation about our (great 😜) project. 

This tip is very useful.

**Comment by iHateCode** [comment]
Absolutely! And with that, the SEO of Github should help people looking to use Wallabag to save webpages locally from the browsers instead of from the server.

**Comment by Kdecherf** [comment]
> nice @Kdecherf, I didn't even know that this firefox-plugin is able to do this. Is there a simple way to do this on-the-fly for a single page? In settings I can activate to do so for all pages or for a list of URLs (I hope that means domains).

@HolgerAusB I have a workaround for that, considering that I enabled the option for all websites by default:

- Use shortcut `Alt+W` to fetch content from browser
- Use shortcut `Alt+Shift+W` to fetch content from server
