### ISSUE TITLE
Wrong display in wallabag (HOST)

### ISSUE THREAD

**Issue by leftsidestory** [wallabag/wallabag#6760]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- I've tried myself without success
- I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - all contents
 - wallabag version: 2.6.2

**Describe what's wrong:**
Unable to fetch content since the latest update.

**Comment by nicosomb** [comment]
Hello @leftsidestory. 
If I understand your message, no more content is fetched with your wallabag instance, is that right?

**Comment by leftsidestory** [comment]
> Hello @leftsidestory. If I understand your message, no more content is fetched with your wallabag instance, is that right?

Hello, sorry if I caused any confusion. The contents showed up in the Unread Articles section but each one of them is “trouble fetching articles”

**Comment by nicosomb** [comment]
For **all** the new articles? Or only some articles? If yes, could you send us the URL please?

**Comment by leftsidestory** [comment]
Currently none of the articles worked. I am attaching some of them here for your reference:

https://www.washingtonpost.com/world/interactive/2023/singapore-china-news-influence-lianhe-zaobao/

https://foreignpolicy.com/2023/07/25/china-qin-gang-foreign-minister-missing-replaced-wang-yi/

**Comment by nicosomb** [comment]
@leftsidestory why did you close this issue?

**Comment by leftsidestory** [comment]
> @leftsidestory why did you close this issue?
Hello, I decided to redeploy the Wallabag app from Cloudron after a re-installation. The problem was then resolved. Thus I cannot verify if what occurred was a Wallabag problem or a Cloudron problem or maybe both.
