### ISSUE TITLE
Wrong display in wallabag blog.men.ci

### ISSUE THREAD

**Issue by yehonghao** [wallabag/wallabag#6790]
Before submitting the issue, please read:
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:

☑ I've tried myself without success
☑ I've replaced HOST in the issue title with the host of the URL that can't be fetched (ie: nytimes.com, 20minutes.fr, bbc.com, etc.)

Content related:

URL: https://blog.men.ci/backup-pve-with-pbs
wallabag version: [e.g. 2.6.1]
Describe what's wrong:
The images in the article cannot be displayed and clicking on the image links does not work. I expected the article images to be displayed properly and the image links to work as expected.
![image](https://github.com/wallabag/wallabag/assets/16252285/57e290ae-862f-4ef1-b38a-d80c75bdd3b1)

**Comment by HolgerAusB** [comment]
@yehonghao on my 2.6.2 and on app.wallabag.it I got the whole article including images from https://blog.men.ci/backup-pve-with-pbs

In your screenshot it seems, that you put it the link of the image in the 'Link' field of https://f43.me/feed/test
If you you use the article link instead it works. Wallabag is for saving articles not single pictures ... but that also works, as I just tested with first image link https://static.cdn.menci.xyz/menci-blog/backup-pve-with-pbs/set-admin-email@1.822c0fc0.333x.svg

**Comment by yehonghao** [comment]
Today, I upgraded to version 2.6.2, deleted the article, and saved it again, but the issue persists. In the article, I'm unable to save images. When I click the link, the following error is displayed.
![image](https://github.com/wallabag/wallabag/assets/16252285/6c70a31c-72fa-4a75-bcf5-000014c40393)
![image](https://github.com/wallabag/wallabag/assets/16252285/89e103f4-5594-45a4-a332-9be219f92cf2)
Do special configurations need to be made for saving this type of CDN images in Wallbag?

**Comment by HolgerAusB** [comment]
I can't reproduce this behavior. Even with setting different referers in f43.me with `http_header(referer): https://example.invalid:9443/` I always get the image. The site seem not to like your sitename/server anyhow. Kinda blocklist on their side maybe?

Try:

- make a new file `blog.men.ci.txt` in vendor/j0ker/graby-site-config with content:
`http_header(referer): https://blog.men.ci`
- login your admin to wallabag, go to 'internal settings' > 'misc' and set 'Download images locally' to `1`
- clear your wallbag cache, for debian (don't ask me for docker):
`sudo -u www-data /var/www/wallabag/bin/console --env=prod cache:clear`
or reboot and/or wait a day
- refetch your page

**Comment by HolgerAusB** [comment]
@yehonghao: Another idea is, that this cdn (cloudflare) is blocking traffic from your country OR that your country is blocking the cdn.

Do you get the images when you load the article directly (without wallabag/f43) in your browser? Without using a proxy?

**Comment by yehonghao** [comment]
@HolgerAusB You're right, I can't access the image directly either.
