### ISSUE TITLE
url greater than 255 chars are not saved (was: urls with redirection(s) silently fail to be downloaded)

### ISSUE THREAD

**Issue by pmaziere** [wallabag/wallabag#681]
When sending wallabag a url that ends up to be a redirection (HTTP 3xx) to another url, it seems that wallabag does not follow the redirection, and page download fails silently wihout even a failure notice

**Comment by j0k3r** [comment]
`url` column are now defined as `text` in the v2 branch.

```
@ORM\Column(name="url", type="text", nullable=true)
```
