### ISSUE TITLE
Mass actions: autofocus on tags textfield when clicking on add tags button

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/wallabag#6818]
A recent update changed the way check-boxes and buttons work for mass actions, including the text field for adding/removing tags. Now we must click on the "add tags" button first to show the field.

However there's no auto focus, which forces the user to do an extra click to focus on the field and start editing tags.

Considering that when we click on the "add tags" button we are expected to add or remove tags, I think that we could directly enable focus on this field.

![2023-08-08-144253_4480x2520](https://github.com/wallabag/wallabag/assets/226063/c5168b04-b356-4f42-bef2-5a8aad809c2d)
![2023-08-08-144805_4480x2520](https://github.com/wallabag/wallabag/assets/226063/33d06557-47f3-4cd3-b4a4-d3f98cf6dc50)

**Comment by Simounet** [comment]
I close this issue because of https://github.com/wallabag/wallabag/pull/6912 .
