### ISSUE TITLE
Out of memory size limit with big article

### ISSUE THREAD

**Issue by Dual-Boot** [wallabag/wallabag#682]
Hi,

 Here is how to reproduce the bug : 
- wallabag 1.6.1b
- go here : http://www.openldap.org/doc/admin24/guide.html
it is the full admin guide for OpenLdap
- try to put it in your wallabag (with FireFox extension but it does not matter) and see what happen. A window pop up and after a view second you will end with this message inside the pop-up windows : 
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 78 bytes) in /srv/www/wallabag.freesquare.local/inc/3rdparty/htmlpurifier/HTMLPurifier/Node/Text.php on line 50

 This error is also present in the Apache2 log.

 After searching about how to solve it, I found a solution by adding this line into index.php from wallabag files : 
ini_set("memory_limit","256M");

 I tried more than one value but in my case I should use 256M , it depends on the size of the article.

What do you think of it ?

  Best regards

**Comment by P3lUZa** [comment]
Ok, it worked for me :dancer:

**Comment by Dual-Boot** [comment]
Hi,

 Since 1.9.0 , it seems the article is fully uploaded.

 regards,

**Comment by tcitworld** [comment]
Can't remember to have done anything in particular, but good news anyway. :)

**Comment by P3lUZa** [comment]
No way, I'm using 1.9.0 and I was trying to export 1,500 articles. But there was one in particular which didn't work until I added

 ini_set("memory_limit","256M");

**Comment by nicosomb** [comment]
I can parse this article via Framabag. Can I close this issue? It's not really a bug from wallabag. wallabag can't parse very long articles, I think it's normal.

**Comment by Dual-Boot** [comment]
Hello,

 From my point of view you can close this issue.

 Regards
