### ISSUE TITLE
Wrong display in wallabag (hessen.de)

### ISSUE THREAD

**Issue by HolgerAusB** [wallabag/wallabag#6828]
- [X] I've tried myself without success
- [X] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: [hessen.de](https://hessen.de/node/13705/newsletter-preview)
 - wallabag version: 2.6.2

**Describe what's wrong:**

While I get all images with FTR, wallabag and f43.me don't catch them. hessen.de uses some script with hiding code in `<!-- xxx -->` so every image has two blocks with kind of an if-constouction. But in the html-code the second block is not hidden, so this should be catched. Even a firefox with no-script addon active shows the images.

f43.me/feed/test debug log gets this in 'HTML after site config strings replacements':
```html
<tr>
    <td style="text-align:left;">

    </td>
</tr>
```
while original curl delivers:
```html class:"lineNo"
<tr>
    <td style="text-align:left;">
        <!--[if mso]>
            <img width="660"
                style="text-align: right; width: 660px; border: 0; text-decoration:none; vertical-align: baseline;"
                src="https://hessen.de/sites/hessen.hessen.de/files/styles/crop_image_style_16_9_md/public/infodamlocalcopy/2023-07/20220719_mp_boris_rhein_265_hires.jpg?itok=jz7iKJya"
                alt="PortrÃ¤taufnahme von MinisterprÃ¤sident Boris Rhein">
            <![endif]-->
        <!--[if !mso]><!-- -->
        <img style="width:100%;height:auto;"
            src="https://hessen.de/sites/hessen.hessen.de/files/styles/crop_image_style_16_9_md/public/infodamlocalcopy/2023-07/20220719_mp_boris_rhein_265_hires.jpg?itok=jz7iKJya"
            alt="PortrÃ¤taufnahme von MinisterprÃ¤sident Boris Rhein" />
        <!-- <![endif]-->
    </td>
</tr>
```
while the 9th line is a bit faulty with two opening comments:
`<!--[if !mso]><!-- -->`

**For testing you should use my new [site_config](https://github.com/fivefilters/ftr-site-config/blob/master/hessen.de.txt) or you will get only one paragraph**

I think, this is not a site_config problem

**Comment by Kdecherf** [comment]
The issue seems to be Graby-related, I'll push a PR to fix that
