### ISSUE TITLE
Miss p.intro elements from Le Grand Continent

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#6852]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [X] I've tried myself without success
- [X] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: [full url of the content]
 - wallabag version: [e.g. 2.4.0]

**Describe what's wrong:**
Le Grand Continent articles often begin by introductions, which can be quite large. These elements are “p.intro” HTML elements, which are not fetched by f43. But we can see them if we try via custom filters.

Example: https://legrandcontinent.eu/fr/2023/08/03/jai-eu-des-doutes-deux-conversations-avec-robert-oppenheimer/

**Comment by HolgerAusB** [comment]
fixed. @j0k3r please close
