### ISSUE TITLE
Future plans for wallabag

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#687]
I open here so we can discuss it.

## API ##
The API is certainly the most blocking thing now with the features we want to see in wallabag. It will make (nearly) everything possible. Third-party apps could have exactly the same features than the webapp has, so I consider it on top of our todo-list.

#### Why can't an API be in wallabag right now ? ####
Because wallabag is not written for it. Actions are most of the time not handled by a unique function. It's not very oriented-object too, and this is much better for building an API.
#### Our options ####
* **change the major part of wallabag** (the poche.inc.php file) to make it clean and usable. Use more oriented-object, create more classes. The rest can stay as it is.
* rewrite all from scratch (good luck)
* **use a framework** (Silex, Symphony, etc.) and rewrite wallabag on top of it.
I think the best option would be to use a framework, but it needs devs who know it a little.

## wallabag v2 - A framework ? ##
Previous paragraph leads us here. I've read somewhere that over 100 (or was it 1000 ?), lines of code, using of a framework was starting to be better for your app. wallabag is way over this limit, and the way it works suits to the use of a framework (MVC).
I leave up to you to discuss the framework we should use, I've no experience with that.

## Third-party apps ##
Even though we have no API, it seems to me they could be improved. But there's no need to do it now if we focus on the API, because we will have to rewrite them (at least a large part) anyway for the API.
Yup, I'm really not saying anything constructive here.

## Things that can be done before ##
I think the best thing to do before starting work on v2 (whatever are the plans) is to deliver a stable release. 
Can we be stable right now or should we add more features ? These features could be : 
* **epub export** It's detached of the rest of wallabag's code, not much influence, the library handles most of it. I should merge this soon.
* **Change database structure** (#620) This can lead in a lot of improvements, not all necessary directly implemented : 
  * Save metadata (#629)
  * Saving PDFs/plain text files (#116)
  * Comments about articles (#592)
  * public (or restricted) articles 
  * Find articles based on estimated reading time (#393)
  * Edit title, content ? (~#564)
  * ...
* **Display/appearance/theme changes** Apart from huge changes, should not be a problem.

## Conclusion ##
Should we start the big changes ? when ? with what method ?
Please give your advice. And as always, help is always welcomed (now it would be *very* welcomed)

**Comment by nicosomb** [comment]
We are not dead :) https://framasphere.org/posts/367022 v2 is coming.

**Comment by ptah-alexs** [comment]
How about php7 support in newest versions of wallabag?

**Comment by tcitworld** [comment]
PHP7 is already supported and even advised.

**Comment by ptah-alexs** [comment]
Ok,although, I didn't found it in google.

**Comment by tcitworld** [comment]
About ?

**Comment by ptah-alexs** [comment]
Search query "wallabag php7" doesn't clearify about wallabag's support php 7 .

**Comment by tcitworld** [comment]
I'll clarify it in [the documentation](http://doc.wallabag.org/en/v2/user/installation.html#requirements).

**Comment by nicosomb** [comment]
@ptah-alexs you can also have a look to our testsuite: https://travis-ci.org/wallabag/wallabag/builds/115307113 all is green with PHP7.

**Comment by ptah-alexs** [comment]
Ok thanks.

**Comment by nicosomb** [comment]
I close this issue: we are in the future today :-) and wallabag v2 is born. I think this issue is useless, you can reopen it if you think it's necessary.
