### ISSUE TITLE
Checkboxes for mass actions are broken

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#6873]
Same issue than https://github.com/wallabag/wallabag/pull/6864

**Comment by HolgerAusB** [comment]
Are you shure, that this is fixed, @nicosomb? With my 2.6.3 I could check the checkboxes, but now 2.6.4 it is not possible. Self-hosted and app.wallabag.it; in list and card view mode

**Comment by nicosomb** [comment]
These checkboxes are fixed in an other pull request by @Simounet. We’ll publish it soon.
