### ISSUE TITLE
app.wallabag.it can't fetch articles from medium.com

### ISSUE THREAD

**Issue by HolgerAusB** [wallabag/wallabag#6878]
### Environment

* **Version**: 2.6.4
* **Installation**: app.wallabag.it

### What steps will reproduce the bug?

app.wallabag.it is not able to fetch content of medium.com, subdomain.medium.com or unique domains hosted by medium, while self-hosted wallabag can.

As @fivefilters has the same problem with his hosted FTR-Service at ftr.fivefilters.[net|org), he told me that he thinks, that medium is blocking his server due to too many requests from his IPs.

So I think, that is the same problem for app.wallabag.it.

To prevent more reports by users, that they can't fetch content from medium.com based sites, I suggest to change the error message for those known services with the hint, that one could use the wallabagger browser addon with activated `Retrieve content from the browser by default when saving page` option.

example URLs:
* https://joshrose.medium.com/cultivating-curiosity-in-photography-3931b2d316f
* https://medium.com/obsidian-observer/i-uninstalled-most-of-my-obsidian-plugins-here-are-the-ones-i-kept-e4d46b449fd1
* https://writingcooperative.com/expanding-universes-make-better-stories-1cebc1857400

**Comment by nicosomb** [comment]
Hello @HolgerAusB 
I tried to `curl` a medium article (from wallabag.it server) and here is what I got: 

```
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: 'joshrose.medium.com',cType: 'managed',cNounce: '92238',cRay: '7fdb9e23fbbd9001',cHash: '75cc809c028de21',cUPMDTk: "\/cultivating-curiosity-in-photography-3931b2d316f?__cf_chl_tk=4Wih35r9yZtGDTOfXH1_kSpH2GFqvIWRbzElqWatGco-1693215887-0-gaNycGzNC3s",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "",fa: "/cultivating-curiosity-in-photography-3931b2d316f?__cf_chl_f_tk=4Wih35r9yZtGDTOfXH1_kSpH2GFqvIWRbzElqWatGco-1693215887-0-gaNycGzNC3s",md: "is4xysfREDwQRhgjfQqyJOp3uvcoMfoRH6RmpWJjaS0-1693215887-0-AZP1eknJ1xDmvCgNNlwhiy6ClPZ4uWMM6Rg1R0kQAPMvdkXVjBwveIPsflbVlWhaAtdpIkM7s-jaGhVwW1JXFFJaQwyEAGUxqObR-O5QCHWNPIILjEu6eS_Xc-0wp0PikO1yb1DLT8RENjFv1glSjtDfNezyi0OchKkYpqs-K18y-XW0lN7nObwGDfH9rbOgbmbzJ3A1Phe6hwUwJE8nJ1JJzrVogJWWe-_GrPYtn52rbkgHWQXHera1c7trC22pe7utiy83A3v-3ESPkMmOdHNzRa9Gwpj95PAi3kiw4338b7keWJR1jOmxSuqkx5XczjC8pxjk9BYepSgrbPEIz9AvkTaIO_vABpq2tpiZTKzbDFJvcTfAY9BuBeTZHwcOXO5TUUdAzx9eviZ0GbztlX8w2q65T8_a3zNnRSWSLpbgH3n_YlmI2Cw41ZRTSuKZBAWwUWqWFr7Oun1jyWRgEZJMHSg6yKZsWQMUgEgd0jelB3Bd0g1qPmLhn7xDWuzkEz5nHbYWa76jjxp0EPI2OccAnmJDHW3k1MmIb6t6cxZLy_FCoLinypSBHallAgVoSH_h1Ol0NrXUo09Af77BYGQujZy1HbIrCCoJAYVCXFdI_KJoQo679AcHQo53-JijoE6kpXloRKiuTPnXd-6b-qnSowVecrGJq02cqpN2Uq4DrUh_moIp8_uCbgI47IwAriQatNNujcVMrOrdnSa5tN-CUTHNLrXqcLIynJPY6DIEQ1PXA8xLtK9v7ul_MneutConkXfqYYWvc9w19BZY2_qlV1q0zZALUVDrf5TMlO55uju6__QU3BJGLmgswAxrHD3hyJLeMVJ1WhcmMQ0L1bwg47w2VG9IKB0XDXgWx2GR3xXfIiw5GgcRQp0z0-2Z0v2euCvDmZKhJAS4hoQktp7q00WqRy27qasyTR966ovtZCHflKOVB-07e0B42YklxlgeONB3igBya6q95Mksaa0cHth1XcEOOhMNB-SxPb4prac6RPYqM1i4RPitck5DaA5EihV7gNg50l552QHjGmsIju--Bu305DZiG4PKA1vz99Ye26ej3IWCoel7LaUqnlcYlXKZ0V8UYJZ0G7T22AZkgMS6VcR6jpeXSLyrGUFHWDiwDCPF1eKyAmCH4Pgu8ls-QM6Ub28Nu2GQ-CD7n3NfRsKnVjmm0TQXaxSCRsnfQQjFWGsiKXU93VFV6zs9vXC71R1s359sDkOeRf44eE5uF142NlvE7qB7mxSJKKNh_jas8PYwzit2Cw3rQ1Z68kspounNNsmObfG3Z2n9EDupK6Ug00kTMZzo_3kLG0dZGCQtJKEsdAj4tlWTGBpJLVoHddw4oJP4D5lc-fCCJzoSKo9qrrb2ImzCI3Onz-wHIhNzdhNNQhz1Zyqq4fHknFo9Ednmj30KuUELRTtyHXETa3pJrIZfY-yGiGye4nmQgj1OEvnji7meypVOQEdGlEFnS9Pz_DMhTYZDtnaVtckVnbNpw-gpJl6EjM0fsCHqzsCbVKELE2B1Xl2tS45fl_QKKhTcnjOy-pKTCbGjVAzA0wiYYeA-zGdYHrO9l11Oy4DgJTB9-uYKWU920vuvPIQr8PKMTmgmZhqdWfEnc24ddPzRh1rb1lA9Nfw5xnFpp_A5eLuT_IcD4LPEJqanCtWoeeQlAYcZWpjXYjSxf8AkIPe0sC33DF0ss-6SqJ8F46KU97cTvPlgECjnKpQxpHusec-vjSlJJWT_ruFRLW6G5pRAkwVlaMr5gbYwo-P3_ml1KwyRdqRUqcp5yc28sQk7l0MAlbUl1KCdBduj7hAmwYZZVgtoQrgLm0B9kquVvwWazCh2pWezsOsvOyXYI8g3fq0pQLE74EjtFNAC8Per0nTbs1KuppnHW4rTE64ejB3Rt6Rvc43S6e6CqNcZwRkUYb-4eoZOfI9f_PRCsfossxcFUlemKdMD4-dmOcxepGtf6u8isA1A20GMrLqX21n-WGMP-QMQvoEM3_-VHUarrMuqCFIukXKkIPrDwzYMJoDiSKg6b6jFOhDjtqpdE6fuTERehejpcQFbgK3PFyXJTCLTjMumr3siFTTFEv23rQuNeI_K21bd7T8JaJtgUEJ5k8CuDocGbSiK80Os3s0l26NCP3EjB59akGvG2sW8QpwLFkgq0ctvxvLsWjf2tumW_FJRDb1s5AOV5Debxw1z7fzZ4xljxxyh-4mr7ZSRqcuokApMyokkocQzrD7npotRuYPsi_QE4vPYvMfEX_8YMoCRsrIxPAf8VjIpD-6J4gaQZgP7ByeGFegHnwnGA0HrpIdaNHItpaXu4K8XCG-nsC71J3xmqlCRkDBThEmGt2-5QafyQMasDesvCtuNRaMvW2SmE_GOy-EQJcIHZSwQ8w2OyWUIt3drA4uMHPLS9dhUmluOAIp53zS3FsYNbJcxkUNPiPHPiz0rh4SfWdCP_xWD-sTeL_9tfTUCC72ngr8_dGnpzjhWkdu-zq4Pq9A5Mni8QTCOAFDZo7prXB40bcAueprNDPa5iQxznkTj8QG9hCuXc_qGXVrAY6NmhBJk9k0PqR7BdtSZBZ0F6nGak93jDUk-eEBXGzY07btW2tshV20AKRjTUzFtemYy7CLuacUP6ZxL8mplBsO6JfuNS6kxVP1hxVT6gExLlS5Wj7YkBZVq0A983fmSpz8I_7yrur3tm28hp8Yn-8yON02xtNRVH_CvlT4T639saV273s3-tFQXgS6wUpp7vRyusM2GCJi19i-EFP46GwFJx6VJKm9PPG3kIZtc6DLp9ar2wpzh5ava2JcOsdT9CT4LY5AJte_zSp6jUUr31I7NMN1SUuMSTwXdhvZueu_ROTPUg4i37ocbOmhpSaJRHlr2vA",cRq: {ru: 'aHR0cHM6Ly9qb3Nocm9zZS5tZWRpdW0uY29tL2N1bHRpdmF0aW5nLWN1cmlvc2l0eS1pbi1waG90b2dyYXBoeS0zOTMxYjJkMzE2Zg==',ra: 'Y3VybC83Ljg4LjE=',rm: 'R0VU',d: '7kRbUSmpTdYuI0/MK5xBGfXWzLGGOalduN+OQq2HK6BBdzPXWKJb7LU3QnV4lEXQgJiu6MWUvLsgrSQYwU7qgxU4Qi2N3MxVKRjD0k8+E6e8+PhwlizA71yLdOfbPkg9klU/91mh3Wto5iQdk3IUDZZK2Ap6KarLAowzQ7692pIj6WGNQOGtgM8jjNxtIEDnWcXMHKJ/dR9fcxg1/EnDCzhGyDNgvexi4JAOj8OZBTrx9eRnWTXRPGW9InUVclvbqmyHl1Rg8oDnm5UTyuFN+tjTRwY10YJQ4ArdHM+SAB+yyhTPU9JnNpJU8JjZwDo9ELVFxt4aK37e/gdwTvPdiF0UzgWFNMJchjxy0r+t6e2ScLzX6z13BUToQUEYQcttUCCR0r35Vnb72m0K4brlxp5hRb1fA0jCt4pHjLkU80Rwem0F+szg2EzT10HBVEDm/yFZggrVhpF349CFU5ZvH8nl0iOfsliN9x+R23vLQjL5Hu2kjmMI1bpJTlvTWy1+DdKHa6742c5Xp5CTfQ/ioIDLx8yAlRFpr04O0E0OLqI6fehd273X4jA2LKZ5zgxl',t: 'MTY5MzIxNTg4Ny45OTUwMDA=',cT: Math.floor(Date.now() / 1000),m: 'McvQ0ztB4zQMiJzJnEVkzVBW3uXlxG/Vcp4wECgGhEQ=',i1: 'XQ25wtvSWHqbXnkiiyzlYA==',i2: 'UlvZS1p5pIIrTtdqKfHpXA==',zh: 'Ycgpu9r177LxjbQGFsmz/e0ei9K/7m7t1CDoKCYIB7I=',uh: 'lX+4ytSWIAYmrLLYT6PFt6+dDmxcA8mUI2GojLU4YNU=',hh: 'hrFhSr5VyU7Juk7Hth4WZUdr0e7aBAACWA9Mib0z8XU=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=7fdb9e23fbbd9001';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/cultivating-curiosity-in-photography-3931b2d316f?__cf_chl_rt_tk=4Wih35r9yZtGDTOfXH1_kSpH2GFqvIWRbzElqWatGco-1693215887-0-gaNycGzNC3s" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);};}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
```

🤔  `Enable JavaScript and cookies to continue` 

I tried with my Firefox (after disabling js) and medium articles can be displayed... 

So, I think we are blocked. 

About your proposal, we can't do specific things here (a custom message for medium articles). 
Maybe we can change the global message defined here: https://github.com/wallabag/wallabag/blob/master/app/config/wallabag.yml#L36

**Comment by HolgerAusB** [comment]
You curl it with parameter `-A useragent`?

I think, it is generally a good idea to advice users to try it with wallabagger in that error message.

**Comment by nicosomb** [comment]
Same message 😓

**Comment by PackElend** [comment]
Is any workaround known to make medium.com work with https://app.wallabag.it/ ?

**Comment by HolgerAusB** [comment]
You can use 'wallabagger' browser extension for desktop browsers. That is the only way I know.

If you are a paying subscriber of medium, wallabagger also helps to catch articles, needing a subscription to read.

**Comment by PackElend** [comment]
> You can use 'wallabagger' browser extension for desktop browsers.
I tried that on https://towardsdatascience.com/zero-etl-chatgpt-and-the-future-of-data-engineering-71849642ad9c (which is free) but it shows up as 
> wallabag can't retrieve contents for this article. Please [troubleshoot this issue](https://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that).





> If you are a paying subscriber of medium

nope, switched to substack

**Comment by HolgerAusB** [comment]
sorry, I forgot to mention, that you need to go to the settings of 'wallabagger' extension. Besides your wallabag credentials you have to activate 'Content fetching from the browser'. Without that, the plugin only sends the link to app.wallabag.it. When activated it sends the completely iterpreted/rendered html code to the server.

I recommend to activate the option as standard behavior because it is very helpful on different paywall sites and JavaScript sites and some sites, that are 'protected' against non-human bots.

**Comment by HolgerAusB** [comment]
alternatively there is https://github.com/Freedium-cfd/web

just paste your medium-url in the form at site freedium.cfd

**Comment by QuAzI** [comment]
> Is there any workaround known to make medium.com work with https://app.wallabag.it/ ?

+1 . Currently wallabag can't fetch article while f43.me can. Only title. And both of them can't read cyrillic titles
Example: https://medium.com/nuances-of-programming/10-%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B9-%D0%BF%D0%BE-%D1%83%D1%81%D0%BA%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D1%8E-%D1%80%D0%B0%D0%B1%D0%BE%D1%87%D0%B5%D0%B3%D0%BE-%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%B0-%D0%B2-visual-studio-code-6e1e4f98a5cc

**Comment by HolgerAusB** [comment]
@QuAzI as mentioned above. Use 'wallbagger', a browser plugin for desktop browsers and activate 'Content fetching from the browser' in the settings of that plugin.

Not available for Edge at the moment, but Chrome, Firefox and their forks should work.

**Comment by QuAzI** [comment]
@HolgerAusB even for articles which not closed by paywall? f32.me can fetch article content

**Comment by HolgerAusB** [comment]
Yes, but medium is actively blocking the ip address of app.wallabag.it, so the server is not getting ANY content from medium. So you could either use wallabagger or setting up you own wallabag server

**Comment by HolgerAusB** [comment]
seems to work again - for now

**Comment by nicosomb** [comment]
Yes, I updated wallabag.it few hours ago.

**Comment by HolgerAusB** [comment]
Yes, I saw it, thank you for that. But the main problem here was, that medium was blocking your server IP, which seems to be not the case any longer or at least for today ....

**Comment by nicosomb** [comment]
@HolgerAusB FYI, Cloudflare also blocks our server. And youtube too...
