### ISSUE TITLE
External - myreadspeed content

### ISSUE THREAD

**Issue by dahamsta** [wallabag/wallabag#6886]
This is a bug with the **myreadspeed** microsite [linked](https://wallabag.github.io/myreadspeed/calculate/) from the webapp. The content of some of the books is missing some whitespace, making it hard to read, which of course will affect results. The errors are in the [JS source](https://wallabag.github.io/myreadspeed/j.js), it's not client-side. Perhaps just link to an external read speed calculator?

![2023-08-24_21-53-59](https://github.com/wallabag/wallabag/assets/105064689/94261692-d792-45cb-a378-df023e35ae51)

**Comment by j0k3r** [comment]
That tools is open source, if you found issue, you can submit a PR :)
https://github.com/wallabag/myreadspeed/
