### ISSUE TITLE
Update to last version of full-text-rss

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#694]
Version 3.2 [is available](http://code.fivefilters.org/full-text-rss/src/ec7275f58df130b18f185bb16a0db7026ba51dca/changelog.txt?at=master). We've got to keep our local changes too.

**Comment by nicosomb** [comment]
Now we'll have graby (https://github.com/j0k3r/graby), maybe can we close this issue?

**Comment by j0k3r** [comment]
Yes :)

See https://github.com/wallabag/wallabag/issues/1262
