### ISSUE TITLE
Unable to get full article from gq-magazine.co.uk

### ISSUE THREAD

**Issue by thomas-mm** [wallabag/wallabag#6940]
I'm trying to save the following article to a self-hosted wallabag instance: https://www.gq-magazine.co.uk/politics/article/british-newsrooms-queen-elizabeth-ii-death

This only gets the last few paragraphs of the article by default. Playing around on f43.me I can't find a selector which gets the whole article - the best I can do is to get the first couple of paragraphs instead of the last couple but this doesn't make much sense because the entire article body is contained within an article tag.

One thing I did notice is that looking at the raw page, the HTML includes a literal "\n" at several points. If I use "//article" as the body selector on f43.me then I get the text as far as the first "\n". If I use the default site config then I get everything after the last "\n".

**Comment by HolgerAusB** [comment]
@thomas-mm that one was a hard one. While FTR (Fulltext-RSS) gets a fine result with `body: //article`, wallabag and f43.me don't.

With some trial and error I found a strip which fixes the problem:

`strip: //div[contains(@class, 'AdWrapper-')]`

Try using Firefox right-click on the original site on the last paragraph wallabag takes > 'inspect'
Then press F1 and deactivate JavaScript. Now check that paragraph again. You see a greyed-out `<div class="AdWrapper-dQtivb... ` betwen your last paragraph and the next paragraph or figure or other element.
