### ISSUE TITLE
Session-based redirect may redirect to incorrect pages

### ISSUE THREAD

**Issue by Kdecherf** [wallabag/wallabag#6944]
The PR #6119, which replaces redirects based on client-side referer header with server-side session parameter, introduces a bug.

When having several tabs open on the same browser, you may be incorrectly redirected to a unrelated page, based on the most recent opened tab.

### Environment

* **Version**: 2.6.6
* **Installation**: docker
* **PHP version**: 8.1
* **OS**: Linux
* **Database**: PostgreSQL
* **Parameters**: -

### What steps will reproduce the bug?

On _tabA_, from _viewA_ you click on _linkA_, then on _tabB_, from _viewB_ you click on _linkB_.
If you delete _linkA_, _tabA_ will be redirected to _linkB_ instead of _viewA_.

This is due to the fact that the server-side session parameter `prevUrl` is shared between all tabs of a user's browser.

A better fix would be to add a query param to all links in order to know where to go when a redirect is needed.

**Comment by yguedidi** [comment]
I'll give this a try

**Comment by yguedidi** [comment]
@wallabag/core moving this to 2.6.8 milestone as the PR introducing the bug is in milestone 2.6.3

**Comment by yguedidi** [comment]
closed by #7140
