### ISSUE TITLE
Wrong display in wallabag (piped.video)

### ISSUE THREAD

**Issue by daniporr** [wallabag/wallabag#6948]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://piped.video/watch?v=3aIcO0vrrQE
 - wallabag version: 2.5.4

**Describe what's wrong:**

It shows:

> wallabag can't retrieve contents for this article. Please troubleshoot this issue.

Instead of showing something about the video (at least the title, better if the description).

`f43.me` reports:

> Warning We failed to make this item readable, the default text from the feed item will be displayed instead.

**Comment by HolgerAusB** [comment]
unfortunately that is a java-script only site. When you check f43.me you can click 'debug log' and see, that f43 is only receiving little content which say, that you need a browser with activated JavaScipt.

You can try the browser-plugin wallabagger and activate 'Retrieve content from the browser' for piped.video or all sites. But you also need to have a site_config in your wallabag installation.

Create a file `piped.video.txt` to `path-to-wallabag/vendor/j0k3r/graby-site-config` with following content:

```
# This works NOT with ftr.fivefilters.net (FTR|Fulltext-RSS)
# This works NOT with wallabag UI

# This only works with wallabagger browser-plugin with activated
# option 'Retrieve content from the browser' in it's settings

body: //div[@class='w-full']
title: substring-before( //title/text() , ' - Piped' )

strip_id_or_class: mb-3
strip_id_or_class: mt-2
strip_id_or_class: gap-1

strip: //label[@for='chkAutoLoop']/self::* | //label[@for='chkAutoLoop']/following-sibling::*
strip: //label[@for='chkAutoPlay']/self::* | //label[@for='chkAutoPlay']/following-sibling::*

strip: //label[@for='showChapters']

strip: //hr
strip: //button
strip: //footer

test_url: https://piped.video/watch?v=3aIcO0vrrQE
```

Then you may need to clear wallabags cache, e.g.:
`sudo -u www-data /path-to-wallabag/bin/console --env=prod cache:clear`

**Comment by daniporr** [comment]
Thank you for your answer
