### ISSUE TITLE
Remove font format `eot`

### ISSUE THREAD

**Issue by Rotzbua** [wallabag/wallabag#6959]
### Environment

Current `master`.

### Suggested change

Update webpack config.

### Why?

Remove font format `eot`. This format was used by the dead Internet Explorer and is not necessary.

Reference:
https://caniuse.com/eot

**Comment by j0k3r** [comment]
Thoughts @Simounet?

**Comment by Simounet** [comment]
I agree with the fact we should remove it. BUT we should define if IE10/11 are a thing for wallabag users. Actually, we are not supporting it. Browserlist is not defined so the default rule applied: `> 0.5%, last 2 versions, Firefox ESR, not dead`.
- IE11: 0.42%

**Comment by j0k3r** [comment]
@nicosomb can we have some stats about wallabag.it and IE?

**Comment by Rotzbua** [comment]
Sorry about the issue. I saw the `.eot` asset and thought it would be easy to remove with webpack by removing it, but after testing I noticed that it is not that simple. So closed for now since there is no big effort.

Internet Explorer is the only browser which can use `eot` but also supports the common `ttf`, `woff` and `woff2`.

**Comment by nicosomb** [comment]
About wallabag.it and 2023:

![Capture d’écran 2023-09-18 à 13 33 38](https://github.com/wallabag/wallabag/assets/121870/b0542634-9719-41f8-82af-859608b17238)
