### ISSUE TITLE
Clean webpack target folder

### ISSUE THREAD

**Issue by Rotzbua** [wallabag/wallabag#6960]
### Environment

Current `master`.

### Suggested change

Clean webpack target folder before building.

### Why?

Avoid keeping outdated assets.
Currently old assets are not deleted.

**Comment by yguedidi** [comment]
This should be solved by the initiative of building prod assets on the fly in Docker and on release (see https://github.com/wallabag/docker/pull/362 and https://github.com/wallabag/wallabag/pull/6982).
After they get merged we will be able to simply removed prod assets from the repository

**Comment by yguedidi** [comment]
I think this can be closed
