### ISSUE TITLE
Locally hosted Wallabag behind proxy

### ISSUE THREAD

**Issue by bradchaus** [wallabag/wallabag#698]
hi, it would be useful to tell a locally hosted wallabag to use a proxy for downloading URLs ... its great software, but I am behind a squid proxy and need to channel all fetches through the proxy.

Thanks

**Comment by nicosomb** [comment]
@tcitworld In the next blog post, you wrote `If you're using a reverse proxy, you might interested by the BASE_URL constant.` 
Is that a fix for this issue?

**Comment by tcitworld** [comment]
It fixes #1075. This one should be ok too.

**Comment by OlegKorchagin** [comment]
> It fixes #1075. This one should be ok too.

Wrong, realy
reverse proxy ( nginx, haproxy, apache + mod_proxy ) != web proxy ( squid )
both of them usually placed in DMZ, but do completely different things

# no direct requests FROM internet
internet -> reverse proxy -> trusted environment
# no direct requests TO internet
trusted environment -> web proxy -> internet

i.e.
user -> reverse proxy -> wallabag
wallabag -> web proxy -> web pages to grab

looks like wallabag 2.3 still have no web proxy support

To fetch web through web proxy, use this dirty hack:
1) in ./vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php, add to getDefaultOptions() 
CURLOPT_PROXY          => '10.10.10.10:3128',

2) maybe not necessary, but i add CULROPT_PROXY in next files ( during answer search ) :
  ./vendor/wallabag/tcpdf/include/tcpdf_static.php
  ./vendor/simplepie/simplepie/library/SimplePie/File.php
