### ISSUE TITLE
Tag slug gets prefixed with t:

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#7009]
### Environment

* **Version**: 2.6.7
* **Installation**: git
* **PHP version**: 8
* **OS**: Debian 12
* **Database**: pg
* **Parameters**: 

### What steps will reproduce the bug?

When i create a new tag in wallabag, i can see the unread RSS feed that it is prefixed with `t:`, e.g.:
`<category term="t:mytag" label="mytag" />`

It would be nice if this prefix is not output to the feed, otherwise parsing the feed with libs, like gofeed, sees the term with the prefix. The label is not used.

**Comment by j0k3r** [comment]
It's a feature not a bug. https://github.com/wallabag/wallabag/pull/6226

Feel free to remove the `t:` when you parse your feed.

**Comment by Strubbl** [comment]
Then, may i request the feature, that you remove this prefix when creating the feed? I haven't seen any other feed with this kind of prefix. 

My feed parsing is generic and not wallabag specific. Removing this while parsing would make it wallabag-specific, which is not intented as it should work with every other valid feed, too.

**Comment by j0k3r** [comment]
I think this is too specific for your needs.

wallabag tag's slug are now prefixed by `t:` for every one.
What if someone else is using RSS feed to retrieve entries and then, get slug to do an api call to the wallaabg api? We'll have to reminder people to re-add `t:` before each tag's slug because we removed them from the RSS feed? I don't think so.

**Comment by Strubbl** [comment]
> What if someone else is using RSS feed to retrieve entries and then, get slug to do an api call to the wallaabg api?

Someone uses the wallabag RSS to make wallabag API calls? Because if you already have access to the API, you are using RSS to create requests to the API? 

I see. You want to discuss this issue away. Thanks for clarifying.
