### ISSUE TITLE
wallabag  webpage garbled code

### ISSUE THREAD

**Issue by Greedwolf** [wallabag/wallabag#7022]
1、docker-compose   install  
2、docker version
Client:
 Version:           20.10.22-qnap7
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        57ed8b8
 Built:             Wed May 17 03:40:17 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22-qnap7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       268ae3b
  Built:            Wed May 17 03:36:24 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.13
  GitCommit:        78f51771157abb6c9ed224c22013cdf09962315d
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d1
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
3、wallabag  webpage garbled code，lost  ui

**Comment by j0k3r** [comment]
Please fill the template and provide more config information otherwise we are just going to close the issue.

**Comment by Greedwolf** [comment]
-->
### Environment

Version: 2.6.7
Installation: docker
PHP version: 8.1.9/8.2.11
OS: Linux PanelNas 5.10.60-qnap
Database: MySQL/MariaDB 
Parameters: 
version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
      - SYMFONY__ENV__MAILER_DSN=smtp://127.0.0.1
      - SYMFONY__ENV__FROM_EMAIL= ********@163.com
      - SYMFONY__ENV__DOMAIN_NAME=https://*******:8120
      - SYMFONY__ENV__SERVER_NAME="HongWorld"
      - SYMFONY__ENV__SERVER_NAME=redis
      - SYMFONY__ENV__REDIS_PORT=6379

    ports:
      - "8120:80"
    volumes:
      - /share/CACHEDEV3_DATA/ContainerStation/wallabag/images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - db
      - redis
  db:
    image: mariadb:10.10
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
    volumes:
      - /share/CACHEDEV3_DATA/ContainerStation/wallabag/dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
### What steps will reproduce the bug?

After installing through Docker Compose, the login page and the webpage was garbled with no UI after login。
