### ISSUE TITLE
the login page and the webpage was garbled with no UI after login

### ISSUE THREAD

**Issue by Greedwolf** [wallabag/wallabag#7023]
-->

Environment
Version: 2.6.7
Installation: docker
PHP version: 8.1.9/8.2.11
OS: Linux PanelNas 5.10.60-qnap
Database: MySQL/MariaDB
Parameters:
version: '3'
services:
wallabag:
image: wallabag/wallabag
environment:
- MYSQL_ROOT_PASSWORD=wallaroot
- SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
- SYMFONY__ENV__DATABASE_HOST=db
- SYMFONY__ENV__DATABASE_PORT=3306
- SYMFONY__ENV__DATABASE_NAME=wallabag
- SYMFONY__ENV__DATABASE_USER=wallabag
- SYMFONY__ENV__DATABASE_PASSWORD=wallapass
- SYMFONY__ENV__DATABASE_CHARSET=utf8
- SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
- SYMFONY__ENV__MAILER_DSN=smtp://127.0.0.1
- SYMFONY__ENV__FROM_EMAIL= ********@163.com
- SYMFONY__ENV__DOMAIN_NAME=https://*******:8120
- SYMFONY__ENV__SERVER_NAME="HongWorld"
- SYMFONY__ENV__SERVER_NAME=redis
- SYMFONY__ENV__REDIS_PORT=6379

ports:
  - "8120:80"
volumes:
  - /share/CACHEDEV3_DATA/ContainerStation/wallabag/images:/var/www/wallabag/web/assets/images
healthcheck:
  test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
  interval: 1m
  timeout: 3s
depends_on:
  - db
  - redis
db:
image: mariadb:10.10
environment:
- MYSQL_ROOT_PASSWORD=wallaroot
volumes:
- /share/CACHEDEV3_DATA/ContainerStation/wallabag/dbdata:/var/lib/mysql
healthcheck:
test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
interval: 20s
timeout: 3s
redis:
image: redis:alpine
healthcheck:
test: ["CMD", "redis-cli", "ping"]
interval: 20s
timeout: 3s

What steps will reproduce the bug?
After installing through Docker Compose, the login page and the webpage was garbled with no UI after login。
https://photos.app.goo.gl/q39y3LUFMYMcmLK86

**Comment by Greedwolf** [comment]
The webpage has no layout, no images, icons, and the interface is black and white

**Comment by Selwyk** [comment]
Same here, but it is my first installation, so not sure if I am doing it properly.

**Comment by Greedwolf** [comment]
Version: 2.4
Installation: docker 
Parameters:
docker run -v /opt/wallabag/data:/var/www/wallabag/data -v /opt/wallabag/images:/var/www/wallabag/web/assets/images -p 80:80 -e "SYMFONY__ENV__DOMAIN_NAME=http://wallabag.appinn.com/" wallabag/wallabag:2.4

I also tried version 2.4, which is normal, but versions after 2.5 no longer work properly

**Comment by j0k3r** [comment]
Can you please tell us what's inside the network tab of your browser? Some assets might be 404 I guess.
I'm 99% sure it's about the wrong domain given for the `SYMFONY__ENV__DOMAIN_NAME`.

**Comment by Selwyk** [comment]
In my case, it is solved. And yes, it was the domain name. I didn't get I had to use a real one and call the app using it. Now it is working fine. Thanks!

**Comment by Greedwolf** [comment]
> Can you please tell us what's inside the network tab of your browser? Some assets might be 404 I guess. I'm 99% sure it's about the wrong domain given for the `SYMFONY__ENV__DOMAIN_NAME`.


Based on your suggestion, I have set up a domain name and enabled HTTPS. It is now working properly
