### ISSUE TITLE
Unable to find template "FOSUserBundle::layout.html.twig" server error 500

### ISSUE THREAD

**Issue by DeRuiterIndustrieleAutomatisering** [wallabag/wallabag#7032]
Version:      2.6.7
Installation: Installatron (host provider)
PHP version:  8.0.27
OS:           Linux
Database:     MariaDB
Parameters:   

when I try to login I  suddenly get "500: Internal Server Error

Unable to find template "FOSUserBundle::layout.html.twig" (looked into: /../public_html/templates, /../public_html/vendor/symfony/twig-bridge/Resources/views/Form) in "@FOSUser/Security/login.html.twig" at line 1."

As far as I know the configuration and the system wasn't changed. What can I do to solve this error?

### What steps will reproduce the bug?
no idea

**Comment by j0k3r** [comment]
What did you do to have that error? Did you upgrade wallabag? Did you make a fresh installation?

**Comment by Selwyk** [comment]
I had that one (and many others) but it was a new installation. The issue was the domain name.

**Comment by DeRuiterIndustrieleAutomatisering** [comment]
it looks like some symbolic links in the bundles folder where invalid (../../filename instead of ../filename) since the octobere update. I recreated them and now it's working fine again

**Comment by Sebfff** [comment]
> it looks like some symbolic links in the bundles folder became invalid (../../filename instead of ../filename) after the octobere update. I recreated them to the new level and now it's working fine again

Hello, Thanks for this answer, I've exactly the same error but can you describe how to recreate the symbolics links ? (In which files on my ftp server ) My host provider is Infomaniak and I've Maria DB too. thanks a lot

**Comment by Sebfff** [comment]
Hello @j0k3r have you any idea to repair this ? thanks a lot


> it looks like some symbolic links in the bundles folder became invalid (../../filename instead of ../filename) after the octobere update. I recreated them to the new level and now it's working fine again
> 
> @DeRuiterIndustrieleAutomatisering Hello, Thanks for this answer, I've exactly the same error but can you describe how to recreate the symbolics links ? (In which files on my ftp server ) My host provider is Infomaniak and I've Maria DB too. thanks a lot

**Comment by j0k3r** [comment]
Sorry no, I've no idea.

**Comment by Sebfff** [comment]
> Sorry no, I've no idea.

Thanks you for you response, @DeRuiterIndustrieleAutomatisering  please can you help me to get your solution ? Thanks a lot

**Comment by DeRuiterIndustrieleAutomatisering** [comment]
I logged in with SSH into my server and renamed the corrupted symbolic links (just in case) and then created new ones with the old names

**Comment by Sebfff** [comment]
> I logged in with SSH into my server and renamed the corrupted symbolic links (just in case) and then created new ones with the old names

Thanks a lot but precisely my problem is how to do that ? thanks

-->     it looks like some symbolic links in the bundles folder became invalid (../../filename instead of ../filename) after the octobere update. I recreated them to the new level and now it's working fine again    @DeRuiterIndustrieleAutomatisering Hello, Thanks for this answer, I've exactly the same error but can you describe how to recreate the symbolics links ? (In which files on my ftp server ) My host provider is Infomaniak and I've Maria DB too. thanks a lot

**Comment by DeRuiterIndustrieleAutomatisering** [comment]
but do you know how to login with ssh on your Infomaniak  server?

**Comment by Sebfff** [comment]
> but do you know how to login with ssh on your Infomaniak server?

hello, yes I do but I don't know exactly what to do to exactly to fix the problem in the ssh terminal. Is it with the ln command or something else ? (I am on shared server) Thanks a lot if you can tell me what is the prompt / steps to use to solve this issue

**Comment by Sebfff** [comment]
@DeRuiterIndustrieleAutomatisering Can you please tell me the command you've used in the ssh terminal ? I can navigate in directories but I am not sure on the  precise command to use to fix the problem (and I don't want to mess it all) thanks a lot

**Comment by Sebfff** [comment]
Hello @DeRuiterIndustrieleAutomatisering 

My Bundles folder
Initialy like that

```
drwxr-xr-x  2 uid174014 ldapusers  124 Jan  4 22:40 .
drwxr-xr-x 21 uid174014 gid174014 4096 Mar  4 00:35 ..
lrwxrwxrwx  1 uid174014 ldapusers   45 Jan  4 22:39 babdevpagerfanta -> ../../vendor/babdev/pagerfanta-bundle/public/
lrwxrwxrwx  1 uid174014 ldapusers   50 Jan  4 22:39 craueconfig -> ../../vendor/craue/config-bundle/Resources/public/
lrwxrwxrwx  1 uid174014 ldapusers   64 Jan  4 22:39 fosjsrouting -> ../../vendor/friendsofsymfony/jsrouting-bundle/Resources/public/
-rw-r--r--  1 uid174014 ldapusers    0 Jan  3 09:18 .gitkeep
lrwxrwxrwx  1 uid174014 ldapusers   52 Jan  4 22:39 nelmioapidoc -> ../../vendor/nelmio/api-doc-bundle/Resources/public/

```
I've done this :

```
unlink fosjsrouting

unlink craueconfig

unlink nelmioapidoc

unlink babdevpagerfanta

```

and this

```

ln -s  ../vendor/friendsofsymfony/jsrouting-bundle/Resources/public/ fosjsrouting

ln -s  ../vendor/craue/config-bundle/Resources/public/craueconfig

ln -s  ../vendor/nelmio/api-doc-bundle/Resources/public/ nelmioapidoc

ln -s  ../vendor/babdev/pagerfanta-bundle/public/ babdevpagerfanta
```

To obtain this

```
lrwxrwxrwx  1 uid174014 ldapusers   42 Mar  4 17:37 babdevpagerfanta -> ../vendor/babdev/pagerfanta-bundle/public/
lrwxrwxrwx  1 uid174014 ldapusers   58 Mar  4 17:37 craueconfig -> ../vendor/craue/config-bundle/Resources/public/craueconfig
lrwxrwxrwx  1 uid174014 ldapusers   61 Mar  4 17:30 fosjsrouting -> ../vendor/friendsofsymfony/jsrouting-bundle/Resources/public/
-rw-r--r--  1 uid174014 ldapusers    0 Jan  3 09:18 .gitkeep
lrwxrwxrwx  1 uid174014 ldapusers   49 Mar  4 17:37 nelmioapidoc -> ../vendor/nelmio/api-doc-bundle/Resources/public/
```

but the result is the same, still Unable to find template "FOSUserBundle::layout.html.twig" server error 500

Is there a another solution ? Thanks a lot
