### ISSUE TITLE
Wrong display in wallabag : chatgpt

### ISSUE THREAD

**Issue by arakeis** [wallabag/wallabag#7057]
- [X] I've tried myself without success
- [X I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://chat.openai.com/share/d02f6660-f56f-4afb-b5e6-96c74ead88a3
 - wallabag version: [2.6.7]

**Describe what's wrong:**
wallabag can't retrieve contents for this article...

**Comment by j0k3r** [comment]
What I've you tried?

**Comment by arakeis** [comment]
Hi Jérémy

On a specific page of chatgpt :
upper right "share" -> copy link :
https://chat.openai.com/share/d02f6660-f56f-4afb-b5e6-96c74ead88a3
on wallabag : add new entry with above link
result : wallabag can't retrieve contents for this article.

Le mer. 8 nov. 2023 à 13:31, Jérémy Benoist ***@***.***> a
écrit :

**Comment by HolgerAusB** [comment]
I wrote a config, but I could not save the svg images. What do you think @j0k3r  and @arakeis how to mark the real person. It should be something most people should except, even if they are not English. I sat `Q` for question:
![grafik](https://github.com/wallabag/wallabag/assets/3876469/4fa07e7e-cef4-41fa-9b54-2ddcdccd1899)

**Comment by HolgerAusB** [comment]
alternatively we could blockqoute the question or the answer:
![grafik](https://github.com/wallabag/wallabag/assets/3876469/996f8788-8ffe-41ab-ac67-640ca7eb4552)

**Comment by arakeis** [comment]
the blockquoted version (for the initial prompt) seems a good choice !

**Comment by j0k3r** [comment]
@HolgerAusB https://chat.openai.com/share/437ea5d5-597b-45bc-92f0-0abe0ed50e27

**Comment by HolgerAusB** [comment]
That thing is driving me crazy. Most times I got a fetching error, but I don't know if my last change in the config is the problem or a timeout or bounce because of too many catches... so it could last minutes or hours before I can upload the config.

**Comment by arakeis** [comment]
Holger, OpenAI is experiencing a major outage, so it *may* be on their side
!

**Comment by HolgerAusB** [comment]
have phun
