### ISSUE TITLE
Clear cookie jar to avoid free article limit

### ISSUE THREAD

**Issue by digicommons** [wallabag/wallabag#7074]
Many pages implement a "You are reading your last free article for this month" paywall. In most cases this can be bypassed by clearing the cookies for said site, e.g. opening the article in an incognito window.

Wallabag seems to persist cookies, which in the above mentioned cases triggers the paywall. For some pages setting a random value on the paywall cookie in the site config seems to work (e.g. `http_header(Cookie): paywall=random_value`). On other pages an empty cookie value (not possible with ftr-site-config) does the job.

Is there any way to reset/clear the cookie jar for specific sites or even disable setting cookies?

If this issue fits better with [j0k3r/graby](https://github.com/j0k3r/graby), I'll of course move the request there. Thank you!

**Comment by HolgerAusB** [comment]
Yes, that would be nice.
Have you tried to set just `http_header(Cookie): paywall` without `=` to set empty cookie? I don't know if that works with wallabag.

While using this with fulltext-rss the log says:
`* ......sending cookies: paywall`

**Comment by digicommons** [comment]
Thanks for the suggestion! Not including the `=` seems to work: `graby.INFO: Found cookie "random_cookie_key"`.

The site I'm testing, needs two cookies with empty values. What doesn't seem to work, is including multiple lines of `http_header(Cookie)` like so:

```
http_header(Cookie): cookie_key_1
http_header(Cookie): cookie_key_2
```

Here, `cookie_key_2` overrides number 1. I tried working around this by setting multiple empty cookies in one line, but to no avail:
```
# without =
http_header(Cookie): cookie_key_1; cookie_key_2
```
```
# with =
http_header(Cookie): cookie_key_1=; cookie_key_2=
```

Setting multiple cookies with proper values works as expected with the following syntax
```
http_header(Cookie): cookie_key_1=value; cookie_key_2=value
```

I guess, a very labor-intensive and manual workaround is to simply include browser-generated values in the site config and updating them when necessary. Clearing the cookie jar would be easier though :)

**Comment by HolgerAusB** [comment]
You, of course, have tried the obvious things `cookie=""` or `cookie=''` or `cookie=\0`
I'm not a dev, so I'm just guessing in the dark

**Comment by Strubbl** [comment]
Multiple lines of Cookie are only allowed starting with http2. To unset a cookie value add the expires values, e.g. https://stackoverflow.com/a/5285982/709697

**Comment by digicommons** [comment]
Thanks for the suggestion, @Strubbl!

I may be approaching this wrong, but f.e. in the case of hbr.org I've been unsuccesful with unsetting the cookie by adding an expires value.
When visiting the site two tracking cookies are added. One contains a JWT with an id and a lastVisited timestamp, another contains presumably a checksum. The only way I've found to keep reading after the limit is to receive new cookies by clearing them beforehand (or not keeping them at all).

Is there anything, I might be missing? :)

**Comment by Strubbl** [comment]
I just had a look at the hbr website and i think they load the article content via Javascript. The summary is part of the HTML, so this can be fetched. The other content cannot be fetched. You need to use the wallabagger browser addon to collect articles from this website.

**Comment by digicommons** [comment]
I can confirm that a browser with disabled JavaScript doesn't load more than the summary.

Yet, a Wallabag instance that hadn't accessed HBR before was able to retrieve a full article. Only on subsequent articles, the limit kicked in and only the summary is loaded. As I wrote above, one can insert two required cookies into a site config and retrieve a new limited set of articles.

That's why I assume that cookies persist between requests and content fetching is possible as long as Wallabag either doesn't have any cookies for the site or a new cookie is imported through a site config.

**Comment by digicommons** [comment]
Thanks for your quick reply! I just set up a new instance and checked this once more. You are right, a fresh instance with the currently shipped site config doesn't render more than the summary.

Since this summary included stuff to be stripped, I started off by rewriting the config before posting this issue originally. In this config I also added cookies that I had retrieved through the browser (this config is not committed yet, therefore yours doesn't include a line with a cookie). Once the proper cookie is set, Wallabag is able to fetch the content properly:

<img width="376" alt="image" src="https://github.com/wallabag/wallabag/assets/43313518/a7d5cb55-63f3-4037-99e4-04709af5d57f">

I still don't understand, why Wallabag is able to render an article if the desired cookies are sent with the request, since as you say, the content is loaded via JavaScript. But I guess with the current tooling it's best to just use the Wallabagger browser add-on.

**Comment by Strubbl** [comment]
You are right:
1. I open Firefox private tab
2. open e.g. https://hbr.org/2023/11/how-to-prepare-for-the-deluge-of-year-end-requests
3. Now i disable JS
4. Reload
5. The full article is still loaded

So if you add the cookie from the browser, you might be able to fetch one other article and then it stops. Or how many articles can you fetch with the cookie from your browser?

I fear, one might have a valid, known (to hbr) cookie in order to fetch articles.

If you mind to share your built site config, i would take a look.

**Comment by digicommons** [comment]
Yes, that's exactly what I've been experiencing. In a single session one can access the entry article and then a second article (both with or without JavaScript enabled). Fetching a third article is not possible with a free id.

I've changed/added two things in the config to make it work:
```
body: //div[contains(concat(' ',normalize-space(@class),' '),' article-body ')]

...

http_header(Cookie): _hbr_u=value_from_browser; HBR_SESSION_ID_N=value_from_browser
```

**Comment by Strubbl** [comment]
Thanks, with your config i can reproduce the fetching works. Unfortunately we would need new valid values for the two cookies in order to fetch an article. Setting it to a random value does not work and results in a server 503 error.

**Comment by HolgerAusB** [comment]
The given example didn't fit in your first problem. Clearing the cookies would not help.

Even with java script enabled, I got full-text of the article in Firefox when hitting F5 after the first (incomplete) load.

I don't see a way to get around this fast. We would need a possibility to auto-reload the page a second time with sending the cookies, received from first load. Meanwhile you can get around this by using browser extension 'wallabagger' with activated option 'Retrieve content from the browser'
