### ISSUE TITLE
Wrong display in wallabag (admin-magazin.de)

### ISSUE THREAD

**Issue by digicommons** [wallabag/wallabag#7092]
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://www.admin-magazin.de/Das-Heft/2015/02/Im-Vergleichstest-Open-Source-Software-fuer-Mailarchivierung
 - wallabag version: 2.6.6

**Describe what's wrong:**
Wallabag/Graby only picks up the first page of a multi-page article, even though `next_page_link:` seems to be set up properly in [admin-magazin.de.txt](https://github.com/fivefilters/ftr-site-config/blob/master/admin-magazin.de.txt).

**Comment by HolgerAusB** [comment]
the problem is, that wallabag strips all `<span>`tags (only the tags itself, not their content)  before your can anything trigger within that :-(
So I added a second next_page_link. As this is not working with FTR we still need both.
