### ISSUE TITLE
Boston Globe content missing images

### ISSUE THREAD

**Issue by ajkessel** [wallabag/wallabag#7094]
Running wallabag in the latest Docker image on an Ubuntu host with default configuration, Boston Globe articles typically lack any images. Example URL is https://www.bostonglobe.com/2023/11/28/business/child-care-costs-massachusetts-government-funding/ which shows up in Wallabag with no images. Seems like issue is with [these rules](https://github.com/j0k3r/graby-site-config/blob/master/bostonglobe.com.txt).

**Comment by HolgerAusB** [comment]
@ajkessel you can now copy the file to your installation and don't forget to clear the cache before refetching the article.

Every site is different, so you can't use the same trick for the same issue on a different sites.

**Comment by ajkessel** [comment]
Thanks, that fixed it! At some point, that change will make its way into the docker latest image?
