### ISSUE TITLE
Allow filtering /api/entries by http_status

### ISSUE THREAD

**Issue by voltagex** [wallabag/wallabag#7159]
**Is your feature request related to a problem? Please describe.**
It'd be nice to be able to filter by http_status so I could easily see all the pages that might appear to have been archived correctly but got redirected or were 404

Sidenote: there's a UI issue here where entries that were 404 when archived are not shown any differently

**Describe the solution you'd like**
Add http_status (and possibly other headers) as filter options in the API

**Describe alternatives you've considered**
I am currently writing code against the API to do a semi-automated check, which is how I ran into this

**Comment by HolgerAusB** [comment]
I agree, that would be nice. Specially when (massively) using third party link-sharing, to push an URL to wallabag without getting an immediate response of failure, e.g. when using a smartphone.
