### ISSUE TITLE
Can't fetch articles - monde-diplomatique.fr

### ISSUE THREAD

**Issue by supersarma** [wallabag/wallabag#7168]
Hi,

I have an account on monde-diplomatique.fr and can't fetch any article from this website. 
Only thing I get is the sample for non subscribers. 

In the account settings on **wallabag.it** I filled fields with my credentials. 

Someone else on this situation ? 
As I do not host it on my own server I am not able to see the logs. 

Thank you.

**Comment by HolgerAusB** [comment]
that should be fixed with the last release (2.6.8), which is not yet on app.wallabag.it (2.6.6)

**Comment by supersarma** [comment]
Thank you a lot for this information. Hope everything will be fine.
