### ISSUE TITLE
Wrong display in wallabag (wsj.com)

### ISSUE THREAD

**Issue by FahadBinHussain** [wallabag/wallabag#7172]
- [✅] I've tried myself without success
- [✅] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: [https://www.wsj.com/tech/personal-tech/things-to-do-our-12-top-tech-tips-of-2023-ab4e9899]
 - wallabag version: [latest]

**Describe what's wrong:**
The article is not completely fetched. Only a few paragraphs were fetched. It happened because of paywall. And it can be bypassed by using `www.drudgereport.com` as the `request` `header` `referrer` value

**Comment by j0k3r** [comment]
We already pass a custom referrer https://github.com/HolgerAusB/ftr-site-config/blob/master/wsj.com.txt#L2
What value are you using?

Also don't forget to link to the other issue https://github.com/wallabag/wallabag/issues/6949

**Comment by FahadBinHussain** [comment]
> We already pass a custom referrer https://github.com/fivefilters/ftr-site-config/blob/master/wsj.com.txt#L2 What value are you using?
> 
> Also don't forget to link to the other issue #6949

use `www.drudgereport.com` as referrer to bypass the wall

**Comment by j0k3r** [comment]
You can make the change yourself on the repo

**Comment by FahadBinHussain** [comment]
> You can make the change yourself on the repo

Did you mean, here? 

`https://github.com/fivefilters/ftr-site-config/blob/master/wsj.com.txt#L2`

**Comment by HolgerAusB** [comment]
I can't see any difference with your referer line in https://github.com/fivefilters/ftr-site-config/pull/1301

the article shows two paragraphs only. In Fulltext-RSS (FTR) and in wallabag

![grafik](https://github.com/wallabag/wallabag/assets/3876469/dccabb99-1d1f-4bb3-86ad-9dfbf25b18f1)

While I am using wallabag 2.6.7 at the moment (I might update this to 2.6.8 next week, I think)

Maybe you had tested this line, with an [older version of the config](https://github.com/fivefilters/ftr-site-config/commits/master/wsj.com.txt)?

**Comment by FahadBinHussain** [comment]
Manually, when you click on any WSJ link on the drudgereport site, it redirects to that WSJ article fully unlocked (No-paywall). So, I thought it would work when drudgereport is sent as a referrer header when sending the request to the WSJ server. But it looks like it doesn't work. I also thought Wallabag uses virtual browsers like Axios, Selenium, Puppeteer or PhantomJS to fetch articles.

**Comment by HolgerAusB** [comment]
I think, that is more than the referer. I don't get full article with my normal an privacy secured Firefox, when clicking on the links in drudgereport. I need to use my insecure profile to get the full text. So there might be additional techniques like cross-site-cookies or other voodoo.

**Comment by FahadBinHussain** [comment]
> I think, that is more than the referer. I don't get full article with my normal an privacy secured Firefox, when clicking on the links in drudgereport. I need to use my insecure profile to get the full text. So there might be additional techniques like cross-site-cookies or other voodoo.
> 
> But you might be able to use the browser plugin 'wallabagger' in this case, with activated 'Content fetching from the browser' in the plugin settings.

But I am currently working on developing a discord bot for wallabag. You can check it out on GitHub at: https://github.com/FahadBinHussain/wallabot. Therefore, the extension doesn't serve me much purpose. Nonetheless, I appreciate your assistance. Thank you.
