### ISSUE TITLE
Error when registering (500: Internal Server Error)

### ISSUE THREAD

**Issue by Opening-Button-8988** [wallabag/wallabag#7195]
### Environment
Version:      2.6.8
Installation: Docker
PHP version:  8.2.14
OS:           The container? I don't even know how to find that out.
Database:     Whatever the docker image uses by default?
Parameters:   

```
   database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    database_path: '%kernel.project_dir%/data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'http://localhost'
    server_name: 'Your wallabag instance'
    mailer_dsn: 'smtp://127.0.0.1'
    locale: en
    secret: [redacted]
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
```

### Steps to reproduce

`docker pull wallabag/wallabag`
`docker run -p 80:80 -e "SYMFONY__ENV__DOMAIN_NAME=http://localhost" wallabag/wallabag`
Go to `localhost:80`
Register
Receive error:
```
500: Internal Server Error
Connection could not be established with host "ssl://127.0.0.1:465": stream_socket_client(): Unable to connect to ssl://127.0.0.1:465 (Connection refused)
```

### Context

At first I tried to install using git. I did read the [requirements](https://doc.wallabag.org/en/admin/installation/requirements.html) page but I wasn't sure how to complete the steps under php extensions and PDO.

I then went ahead with docker-compose, but I wasn't able to connect to the database at the port specified by `docker ps`, I wasn't sure why. Later I fixed it, and I receive the same error as I do with the `docker run` method. 

Lastly I used `docker run` (sqlite). I made no changes to the command, it was literally `docker run -p 80:80 -e "SYMFONY__ENV__DOMAIN_NAME=http://localhost" wallabag/wallabag`. While registering, I get the error as shown above. I followed all installation steps and made no changes to it. I did try changing the ports but I wasn't able to connect to it in the browser.

Please note that I am running on localhost and have no intentions on using this app remotely. The reference to 127.0.0.1 was odd because that's usually used for when accessing servers remotely, since that address won't be able to find the host, however, I also have no idea what I'm talking about and only learned about this recently.

I realised this error is probably related to email (port 465 is smtp). I'm guessing it's checking to see whether my email address exists or not, but it can't connect because it's expecting me to access the server remotely. Firstly, I see no reason to use this tool remotely, and secondly, why do I need to register with an email address for my own server for a tool that simply saves bookmarks? It's simply unnecessary. And of course, I didn't use a real email address, I just entered something like test@test.test (and I tried working addresses to make sure that wasn't the issue).

**Comment by v-marinkov** [comment]
I had the same problem on docker-compose now. It turned out I was using the old `SYMFONY__ENV__MAILER_HOST`, so I changed to the new `SYMFONY__ENV__MAILER_DSN` (see https://github.com/wallabag/docker/issues/388). Fixing the connection to the smtp server fixed the error for me.

I suppose in your case the problem is `mailer_dsn: 'smtp://127.0.0.1'` or if it's missing, it is defaulting to it.
