### ISSUE TITLE
Renaming tags

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#720]
Renaming tags. 
How to do it : 
- create a new tag for new name if not already exists
- assign all of the articles for the old tag name to the new one
- delete old tag

This should also allow merging two different tags in a single one.

**Comment by shulard** [comment]
Hello guys, I've just faced this issue and I'll be glad to help adding this feature.

I haven't contributed to Wallabag at the moment but I'll try to do my best here 😄.

**Comment by shulard** [comment]
Hello guys,

I've just installed a Wallabag instance on my dev environment. Have you already discussed implementation details here ?

I've some ideas but I need help to refine them :

* I think adding an "edit" icon in tag tag list on the right of each label ;
* When user click on that label two options :
  * Create an inline field in place of the label and update the edit icon to a save one ;
  * Go to a new page where the field is displayed and the tag renamed (like the edit icon on the view article page).

Any though here ?
Maybe I'm not really clear, please ask questions if it's needed 😄.

**Comment by nicosomb** [comment]
I'd prefer an inline field. 
@j0k3r @tcitworld @Kdecherf any opinion?

**Comment by Kdecherf** [comment]
Go for the inline way 👍

**Comment by shulard** [comment]
Hello,

I've started working on the implementation (#3574). I've searched inside the codebase and found a lot of server side logic (clic -> action -> reload -> display). Is there a "standard" way to handle the inline field generation inside JavaScript ? 

Do you prefer having a `<form>` inside each tag element that can be submitted or handle it with an Ajax request ?

**Comment by j0k3r** [comment]
Not at the moment.

**Comment by ewoks** [comment]
@shulard what are missing steps that need to be completed? Do you still need some feedback to make decision? Is there any specific blocker?

**Comment by Kdecherf** [comment]
@ewoks a review has been requested, trying to do it today :)

**Comment by timokau** [comment]
@j0k3r why the close? Has this been implemented or was it given up on?

**Comment by shulard** [comment]
@timokau, this was implemented in the #3574 MR.

**Comment by timokau** [comment]
Great, thank you!
