### ISSUE TITLE
No images while saving pages on ispatguru.com

### ISSUE THREAD

**Issue by PackElend** [wallabag/wallabag#7207]
### Environment

* **Version**:  2.6.6
* **Installation**: ttps://app.wallabag.it
* **PHP version**: -
* **OS**: -
* **Database**: -
* **Parameters**: -

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  n/a
  ```
</details>

### What steps will reproduce the bug?
save the website  https://www.ispatguru.com/process-control-instruments-and-their-classification. Images won't be saved. 

### Solution:
_Originally posted by @HolgerAusB in https://github.com/wallabag/wallabag/issues/6414#issuecomment-1899915172_

> In your case it was easy (for me), I fixed that with [fivefilters/ftr-site-config#1311](https://github.com/fivefilters/ftr-site-config/pull/1311) If you are self-hosting wallabag copy ispatguru.com.txt from there to your installation: `<wallabag>/vendor/j0k3r/graby-site-config/`, clear cache and re-fetch article. For app.wallabag.it you unfortunately have to wait for the next release.

**Comment by j0k3r** [comment]
From what I understand, the problem is already solved and you are waiting for a new release, right?

**Comment by PackElend** [comment]
I don't know, if the code has already been updated with the solution proposed.
I understood that was only a test on self hosted instance.
I don't see reference to a pull request

**Comment by j0k3r** [comment]
The reference is here: https://github.com/fivefilters/ftr-site-config/pull/1311
We are using that repo in wallabag.
So as soon as we release a new version, you'll get the update.

In the mean time, you can replace it on your instance (in the way @HolgerAusB told you)

**Comment by PackElend** [comment]
I using only cloud hosted by you guys, so I'm waiting for you 😊
