### ISSUE TITLE
Wrong display in wallabag (link.springer.com)

### ISSUE THREAD

**Issue by RMHogervorst** [wallabag/wallabag#7215]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x ] I've tried myself without success
- [x ] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: [full url of the content] https://link.springer.com/article/10.1007/s42113-023-00193-2
 - wallabag version: [e.g. 2.4.0] current version of wallabag.it

**Describe what's wrong:**
Academic publishers are hostile to everyone so it is maybe not surprising but this article does open on my mobile browser and f43.me finds the text too, but not wallabag.

It can't parse content.

**Comment by HolgerAusB** [comment]
@RMHogervorst: I managed to catch the whole article. [Proposal of my site-config is here.](https://github.com/HolgerAusB/ftr-site-config/blob/link.springer/link.springer.com.txt).

But your article also contains MathJax/TEX symbols. I was surprised that wallabag can show them out of the box. Except for a non-standard notation. In the wallabag view, some of the math symbols are prefixed with a literal `/varvec` in red letters. The symbols itself seems not to have any difference to the original article. Maybe except that they might be a bit bolder in the original version.

Do you think, I should try to remove that `/varvec` or better keep it?

![grafik](https://github.com/wallabag/wallabag/assets/3876469/4cba8ba0-5c34-4079-97b8-b13e1e7bd874)

As a user of app.wallabag.it you need to wait for the next wallabag release after I've committed my proposal to the site-config-repo

**Comment by RMHogervorst** [comment]
Getting rid of those varvec annotations would be best, but I think this 'imperfect' solution is good enough
