### ISSUE TITLE
 Unable to find template "FOSUserBundle::layout.html.twig" server error 500

### ISSUE THREAD

**Issue by Sebfff** [wallabag/wallabag#7256]
Hello 
I've the Same problem displayed in this post (https://github.com/wallabag/wallabag/issues/7032) but I can't solve it. Can someone can help me ? Thanks a lot 

Version: 2.6.8 
Installation: Infomaniak (host provider)
PHP version: 8.0
OS: Linux
Database: MariaDB

**each time I try to login I have**

"500: Internal Server Error
Unable to find template "FOSUserBundle::layout.html.twig" (looked into: /home/clients/xxxxx/sites/monsite.fr/templates, /home/clients/xxxxx/sites/monsite.fr/vendor/symfony/twig-bridge/Resources/views/Form) in "@FOSUser/Security/login.html.twig" at line 1."

**Apache log are :**
"myserver.wallabag.org [Mon Feb 19 17:30:27.504311 2024] [core:error] [pid 174708:tid 139940998391552] [client 10.4.45.29:0] AH00037: Symbolic link not allowed or link target not accessible: /home/clients/79xxxxxx/sites/myserver.wallabag.org/bundles/fosjsrouting, referer https://myserver.wallabag.org/login "

"myserver.wallabag.org [Mon Feb 19 17:30:27.503220 2024] [core:error] [pid 174708:tid 139940998391552] [client 10.4.45.29:0] AH00037: Symbolic link not allowed or link target not accessible: /home/clients/79xxxxxx/sites/myserver.wallabag.org/bundles/fosjsrouting, referer https://myserver.wallabag.org/login "

### What steps will reproduce the bug? 
each time I want to connect to wallabag in my browser (mobile app is ok)

**Comment by Sebfff** [comment]
Hello, I really cannot solve this problem, is this a way to reinstall Wallabag and keep the current database ? thanks

**Comment by Sebfff** [comment]
> Hello, I really cannot solve this problem, is this a way to reinstall Wallabag and keep the current database ? thanks

Hello, nobody has a clue ? thanks

**Comment by HolgerAusB** [comment]
`myserver.wallabag.org` ???? Are you realy using `wallabag.org` as domain or did you just mask the real one for us?

and for `Symbolic link not allowed or link target not accessible` you'd check if `/home/clients/79xxxxxx/sites/myserver.wallabag.org/bundles/fosjsrouting` exists and is accessible by user www-data (Debian).

Maybe you post your Apache site-conf too.

**Comment by Sebfff** [comment]
> `myserver.wallabag.org` ???? Are you realy using `wallabag.org` as domain or did you just mask the real one for us?
> Thanks for your answer yes this is to mask rela domain :+1
> and for `Symbolic link not allowed or link target not accessible` you'd check if `/home/clients/79xxxxxx/sites/myserver.wallabag.org/bundles/fosjsrouting` exists and is accessible by user www-data (Debian).
> 
> Maybe you post your Apache site-conf too.

**Comment by Sebfff** [comment]
@HolgerAusB Hello Is that helps to see the problem ? Thanks a lot

**Comment by HolgerAusB** [comment]
I was just wild guessing. I do not have the skills to solve that problem, sorry.

**Comment by Sebfff** [comment]
> I was just wild guessing. I do not have the skills to solve that problem, sorry.

Hello, I am still stuck in this error, is someone knows how to reinstall the app but keep database and settings ? thanks a lot

**Comment by Sebfff** [comment]
Finally I solve it by changing instance, first install wallabag on a new instance, dump a sql file of my old database. Change the prefix from the dump `sed -i 's/old-tableprefixr2bz/newtableprefixld/g' *.sql` and reimport the sql file in my new wallabag instance and it finally works
