### ISSUE TITLE
Retrieved articles not showing up in Koreader

### ISSUE THREAD

**Issue by hightide591** [wallabag/wallabag#7276]
### Environment

* **Version**: 2.6.8
* **Installation**: Koreader
* **PHP version**: ?
* **OS**: ?
* **Database**: ?
* **Parameters**: ?

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```


  ```
</details>

### What steps will reproduce the bug?
After retrieving articles from server in Wallabag/Koreader on my Kobo, the articles do not appear in the download folder (on the device). I realized the issue is related to filenaming. When I FTP into the device's wallabag folder from my computer, I can see the articles but they do not show up on the device. When I add .epub extension to the articles on my kobo from my FTP client, they suddenly appear on the device. It appears Wallabag isn't adding the correct extension (.epub) when it retrieves them from wallabag.

This ONLY occurs when the article was saved manually from wallabag. If i right click a link and "add to wallabag" the .epub extension is added correctly when I retrieve them on Koreader. But if I run wallabagger from the extension menu in my browser, I get this issue when trying to retrieve them on my Kobo.

Update: adding .epub does not actually work. The files appear on the device but the formatting is actually all fucked up. They are not readable when I do this. My new workaround: export the articles to epub on my computer then add manually via USB or FTP to Kobo. This works for now but is inconvenient.

**Comment by j0k3r** [comment]
I'm sorry for you but I think the problem should be reported to Koreader instead.

The wallabag team does maintain the plugin on Koreader.

**Comment by Frenzie** [comment]
I don't think that's what I said. ;-)

**Comment by Frenzie** [comment]
NB https://github.com/koreader/koreader/issues/11481#issuecomment-1962387461

> the problem only arises if I save the article to Wallabag by using the extension

**Comment by HolgerAusB** [comment]
I don't even know about koreader but I was curious about the odd behavior in the 2nd part of your post. Normally the results with wallabagger are better than the method of just pushing the URL to walllabag.

Are you experiencing this with all websites (domains) or only one/few?

I just installed calibre epub reader for windows to test your problem. I saved an article with wallabagger to my self-hosted wallabag server. Then I opened that saved article in wallabag UI with my browser. Then clicked on Export>EPUB to save the file. Extension .epub was added. I opened that file with calibre and everything is fine. Can read a nicely formatted text.

Maybe you could explain your set-up and workflow more detailed. Especially how the whole thing relates to koreader.

**Comment by Frenzie** [comment]
The reason is that when Wallabag retries a page by itself it gives it a mimetype of `text/html`, while with this Wallabagger extension it returns `text/html; utf-8`. For the latter the KOReader plugin didn't download the EPUB export because it wasn't a mimetype where we prefer EPUB. See https://github.com/koreader/koreader/pull/11492

**Comment by hightide591** [comment]
> I don't even know about koreader but I was curious about the odd behavior in the 2nd part of your post. Normally the results with wallabagger are better than the method of just pushing the URL to walllabag.
> 
> @hightide591, Are you experiencing this with all websites (domains) or only one/few?
> 
> I just installed calibre epub reader for windows to test your problem. I saved an article with wallabagger to my self-hosted wallabag server. Then I opened that saved article in wallabag UI with my browser. Then clicked on Export>EPUB to save the file. Extension .epub was added. I opened that file with calibre and everything is fine. Can read a nicely formatted text.
> 
> Maybe you could explain your set-up and workflow more detailed. Especially how the whole thing relates to koreader.

Exporting to EPUB from browser works fine. The issue w/ epub is only when I retrieve from Koreader on my Kobo. Frenzie figured it out.

**Comment by Frenzie** [comment]
@HolgerAusB Though I'd like to be a touch more explicit that it's called mimetype and it's actually HTTP Content-Type. The distinction only matters when Content-Type contains more than just a MIME type. But presumably it's about 8 years too late to change anything about that now.
