### ISSUE TITLE
Browse or group articles by domain

### ISSUE THREAD

**Issue by Menti** [wallabag/wallabag#729]
I would like to be able to browse, search, sort or group articles by their domain of origin. It could be displayed in a similar way to the tags interface, but in this case the tag would be automatically assigned by wallabag.

Why the domain? Because it's useful information about content. Most domains have more or less coherent styles, themes, editorial positions... In many cases (like blogs) a domain equals an individual author (or a few authors), so browsing by domain is an approximation to browsing a library by book author... which is actually the most common way of sorting and browsing libraries. It would be a nice bit of order and structure in your wallabag library, and the information is already gathered automatically by wallabag.

**Comment by nicosomb** [comment]
Done in wallabag 2.x.

**Comment by Menti** [comment]
Great! I'm expecting to use the new v2.
