### ISSUE TITLE
Author is blank when exporting to EPUB

### ISSUE THREAD

**Issue by charleshan** [wallabag/wallabag#7291]
### Environment

* **Version**: 2.6.8
* **Installation**: https://app.wallabag.it/
* **PHP version**: -
* **OS**: -
* **Database**: -
* **Parameters**: -

### What steps will reproduce the bug?
1. Wallabagger > Options > Content fetching from the browser > Enable
2. https://app.wallabag.it/ > Click on an article > Export > EPUB

When "Content fetching from the browser" is enabled, the author is blank. When "Content fetching from the browser" is disabled, the author is set.

**Comment by HolgerAusB** [comment]
Dublicate of https://github.com/wallabag/wallabag/issues/6972

**Comment by charleshan** [comment]
Got it. Thanks for pointing it out
