### ISSUE TITLE
Text colour from article might conflict with theme

### ISSUE THREAD

**Issue by lightonflux** [wallabag/wallabag#741]
E.g. If you save an article that has citation in grey text wallabags saves it as grey text, which can conflict with dark themes. ![Image](http://i.imgur.com/9ftzTgZ.png)

I don't know what the __best__ fix would be. But stripping the text colour information from the text would give a good result.

**Comment by j0k3r** [comment]
This seems to be fixed in 2.0.0-alpha.0: http://v2.wallabag.org/view/13
