### ISSUE TITLE
Add AI to WallaBag :)

### ISSUE THREAD

**Issue by YouveGotMeowxy** [wallabag/wallabag#7453]
**Is your feature request related to a problem? Please describe.**

Not a problem so much as a really nice advancement for the app.

**Describe the solution you'd like**

Imagine adding AI for things like the page summary when adding a new URL to Wallabag?

and/or

Having AI auto suggest super-relevant tags to add to the new (or even when editing) link?

Ideas could be, in settings to allow user to prefer the AI versions over the current summary fetching scheme, always with the option to select either the AI choice or regular.

For tags, the AI tags could be noted when adding, such as "ai: <tag>", or "<some AI icon>:<tag>", or just perhaps a different CSS color background to denote an AI tag., and so forth.

The same can be added to the Wallabagger Browser extension, as well.

**Describe alternatives you've considered**

None others available, afaik.

**Additional context**

I know it's probably pretty ambitious for such a small and busy dev team, but we're living in a quickly-growing AI era, and imagine how nice, and modern it would be to add? :)

**Comment by nicosomb** [comment]
https://wallabag.org/news/wallabag-wont-accept-pr-feature-request/

**Comment by YouveGotMeowxy** [comment]
Wow, didn't realize I would get such a negative reaction  to what seems like an excellent idea to me.

Personally speaking, I really think you're limiting WallaBag by standing steadfast in your won vision, and not allowing the app to grow and evolve into something much bigger, and more diverse as to what individual users would like to customize it to their own needs. i.e.  you only want to Archive old articles (there's already Archive.org) for that, but other's may want to use it as a robust bookmark manager, complete with their own tweaked summaries, and so on.

Suggesting relevant tags doesn't seem so far fetched either, to me.

I'm a big fan of "options"; let the user choose how they like their app to work. i.e. a setting in options to stick with "archive mode", or "AI summary" mode.

**Comment by Kdecherf** [comment]
@YouveGotMeowxy as you've mentioned in your first message, the team is pretty small and busy, thus our efforts are mostly focused on maintaining the core features of this project.

wallabag is not an "archive old articles" nor a bookmark manager, it's mainly a read-it-later app. I pretty much see the value of a feature like auto-suggested tags as I would like to have it myself. There's an open feature request for that and I don't think putting AI here is a necessity.

While I understand the principle of having options and ways to customize your experience on an app, I'd like to remind that adding more options is globally adding burden on the overall maintenance of the project as well. That's why we may or may not go on some roads.

**Comment by HolgerAusB** [comment]
@Kdecherf, you wrote:

 > wallabag is not an "archive old articles" ... it's mainly a read-it-later app.

hmmm, so why do we spend so much time here writing website related configurations to store as much relevant content of a page as possible? For me, wallabag IS an archive (and more). Just to save URLs for later retrieval, there are probably easier methods.

Why would anyone pay a subscription to wallabag.it if it wasn't an article archive?

**Comment by j0k3r** [comment]
Well for me archiving an article is like saving it for reading later.

The main goal is to be able to read it later (maybe offline) with as much content as possible from the original article. Once the article is read, I remove it and/or bookmark it using an other service.

**Comment by arcb01** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Not a problem so much as a really nice advancement for the app.
> 
> **Describe the solution you'd like**
> 
> Imagine adding AI for things like the page summary when adding a new URL to Wallabag?
> 
> and/or
> 
> Having AI auto suggest super-relevant tags to add to the new (or even when editing) link?
> 
> Ideas could be, in settings to allow user to prefer the AI versions over the current summary fetching scheme, always with the option to select either the AI choice or regular.
> 
> For tags, the AI tags could be noted when adding, such as "ai: ", or ":", or just perhaps a different CSS color background to denote an AI tag., and so forth.
> 
> The same can be added to the Wallabagger Browser extension, as well.
> 
> **Describe alternatives you've considered**
> 
> None others available, afaik.
> 
> **Additional context**
> 
> I know it's probably pretty ambitious for such a small and busy dev team, but we're living in a quickly-growing AI era, and imagine how nice, and modern it would be to add? :)

Honestly, I think this would be a great feature to add

**Comment by gborgonovo** [comment]
I like this idea a lot.

It would be very helpful to have an AI to translate, summarize, summarize by points the pages. It could also propose tags.

If it is a read-it-later app, having many new pages to read, it would be extremely useful to have summaries to know if it worth to read a whole page or not. Less time lost.

Furthermore it would be very helpful to retrieve and study for future reference.

AI suggesting tags would also improve a lot the archive system (believe me, I'm a knowledge manager).

**Comment by j-xella** [comment]
I know this is an old issue, but it should be resurrected IMO. Saving articles for later reading is one thing, but helping users find and decide what to read next from the saved list is also an integral part of of the process. And AI would be a real game changer here, not some gimmick.

For reference, Obsidian Web Clipper (a lot of similarities with wallabag, I believe) has AI integration.
