### ISSUE TITLE
Backup Documentation seems not up to date

### ISSUE THREAD

**Issue by Schoumi** [wallabag/wallabag#7493]
Hi,

The Backup sections (https://doc.wallabag.org/en/admin/backup) seems not really up to date. In the Pictures sections, it says that images storage should have change in version 2.2. Since we are at release 2.6.9. I think it has changed. 

Maybe take a look to that section and update it if needed will be great :)
I know maintain documentation through time is hard.

Thank you for your work.

**Comment by j0k3r** [comment]
Hey, it seems nothing changed yet :)
Images are still saved in the same place: 

https://github.com/wallabag/wallabag/blob/637d8d34465e9663e6ae4fbd8a912158636d872b/app/config/services.yml#L259-L261
