### ISSUE TITLE
A way to remove all tagging rules

### ISSUE THREAD

**Issue by hulleyrob** [wallabag/wallabag#7520]
I have exported my tagging rules of which there are many and cleaned them up.

Im happy with the import process and re-running tag all from the console.

However I can find no way to remove all rules so that I only get what ive imported and not all the old ones.

If you have many rules clicking delete and having the page refresh after a wait is time consuming and there should be an easier way.

**Comment by hulleyrob** [comment]
well ive done it by copying the delete button request as curl converting to python in a for loop and removing all 226 tags that way.

but there really should either be a console command or a button in the reset area for this.

**Comment by YouveGotMeowxy** [comment]
Any chance of adding your script to wbag itself and creating a PR? It seems the dev team needs a lot of help keeping this software going, new features, needed features, etc.

**Comment by j0k3r** [comment]
Well, that could be an interesting feature to have.
