### ISSUE TITLE
Search queries take a full minute

### ISSUE THREAD

**Issue by jtagcat** [wallabag/wallabag#7539]
**Is your feature request related to a problem? Please describe.**
With around 5k articles over 3 years, search queries are slow, clocking in at 48-53s, sometimes longer (especially with multiple 'concurrent' queries, the first one also slows down).

**Describe the solution you'd like**
Getting search down to <15s. I understand full-text search is very hard. From a self-hosting perspective, I'd like to avoid Elastic, as it needs babysitting + eats up more resources than it needs (statically configured) + disrupts service to other apps.

**Describe alternatives you've considered**
Android app search works differently (worse, very wildcardy, but at the same time oddly specific and ordered), but it's fast. Even if I find the article in the app, it's hard to get a wallabag link. This itself is a workaround to the problem of annotations being broken: I screenshot, and later carry it over in web.

**Comment by virtadpt** [comment]
It might be a problem with full-text search on the back end (MySQL or Maria, I'm guessing?)  I ran into this and had to supplement it with Manticore (plugged into SearxNG) because it takes so long.

**Comment by j0k3r** [comment]
Maybe at some point you need to fine tune a bit more your database so it can handle the full text search. I don't see what we can do on our side.
