### ISSUE TITLE
Fetching from paywalls MEDIAPART.FR & MONDE-DIPLOMATIQUE.FR is broken

### ISSUE THREAD

**Issue by TontonMollo** [wallabag/wallabag#7569]
Hi!

Fetching from paywalls MEDIAPART.FR & MONDE-DIPLOMATIQUE.FR is broken on the app.wallabag.it instance.

Could-you check this issue please ?

On monde-diplomatique.fr articles are fetched as non suscribers : https://app.wallabag.it/share/66866d8e1ea0d5.17544904

On mediapart.fr fetching give an error message : https://app.wallabag.it/share/66866db183a183.56436385

Thanks.

Best regards.

**Comment by j0k3r** [comment]
wallabag.it isn't up to date to the latest version of wallabag. That's why.

**Comment by nicosomb** [comment]
I will update it soon.

**Comment by TontonMollo** [comment]
Not yet updated. About 60 days.

**Comment by nicosomb** [comment]
I just updated wallabag.it. I'm really sorry for the delay.
