### ISSUE TITLE
Caching images?

### ISSUE THREAD

**Issue by blurmonk** [wallabag/wallabag#757]
Hi

Is it possible to cache the images locally as well? It looks like all the images in articles are referenced from external sources.

thanks

**Comment by Suncatcher** [comment]
> Have a look here: http://doc.wallabag.org/doku.php?id=wallabag:downloading_pictures ;-)

 Is this settings affect all articles or only new? I have around 500 articles added and want to download their images.

**Comment by tcitworld** [comment]
Only new. I think there's an issue to refetch all content (including pictures) somewhere for old articles.

**Comment by Suncatcher** [comment]
Didn't found. We should upvote those issue.

**Comment by chrido** [comment]
Here is a workaround, it is a Tampermonkey script which reloads every entry. To use it install the Tampermonkey extension in Chrome

`
// ==UserScript==
// @name         Wallabag re-fetch entries
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://wallabag.mydomain.com//view/1 //Open this URL to start the script
// @grant GM_setValue
// @grant GM_getValue
// @require https://code.jquery.com/jquery-3.1.1.min.js
// ==/UserScript==

(function() {
    'use strict';
    var begin = GM_getValue("current", 1); //First article ID
    var requests = [];
    for(var i = begin; i < 500; i++) { //last article ID
        requests.push(i);
    }
    function waitAndThenNext() {
        console.log("waiting");
        setTimeout(requestNext, 10*1000); //We don't want to hammer our server
    }
    function requestNext() {
        if (requests.length) {
            var curid = requests.shift();
            GM_setValue("current", curid);
            var requrl = "https://wallabag.mydomain.com/reload/" + curid; //adjust to your domain
            console.log("begin fetching: " + requrl);
            $.ajax({url: requrl}).always(waitAndThenNext);
        }
    }
    requestNext();
})();
`

**Comment by grant** [comment]
Please wrap your code in ticks like \`\`\``<code>`\`\`\`.
