### ISSUE TITLE
Some themes display a citation box wrong

### ISSUE THREAD

**Issue by lightonflux** [wallabag/wallabag#759]
Sorry for the weird title but i don't know what the exact problem is only how it looks.

If you wallabag [this article](http://moo.nac.uci.edu/~hjm/HOWTO_move_data.html) there is a citation box with a little icon left.

Some wallabag themes display this weirdly:

![](https://cloud.githubusercontent.com/assets/2197836/3450645/2e074054-0181-11e4-8782-9a170194c21d.png)

Other themes like baggy or courgette display it right.

Here a list with default themes that display it wrong:

 * Dark
 * Dmagenta
 * Solarized
 * Solarized Dark
 * Default

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
