### ISSUE TITLE
Wrong display in wallabag (t-online.de)

### ISSUE THREAD

**Issue by Molenfeuer** [wallabag/wallabag#7595]
We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [X] I've tried myself without success
- [X] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: [https://www.t-online.de/nachrichten/ausland/usa/id_100447198/supreme-court-oberster-us-richter-gastierte-wohl-in-putin-palast.html?utm_source=pocket-newtab-de-de](https://www.t-online.de/nachrichten/ausland/usa/id_100447198/supreme-court-oberster-us-richter-gastierte-wohl-in-putin-palast.html?utm_source=pocket-newtab-de-de)
 - wallabag version: 2.6.9

**Describe what's wrong:**
Wallabag only saves the first three chapters of an article! The rest of the article on the same page is ignored! Everything after the quote "damals als deutlich weniger belastet als heute." is missing!

**Comment by HolgerAusB** [comment]
@Molenfeuer I am surprised, that t-online, one of the largest online news sites in Germany [self-called], has problems with wallabag and nobody claimed it yet.

I wrote a config file for t-online. Just copy [t-online.de.txt](https://raw.githubusercontent.com/fivefilters/ftr-site-config/master/t-online.de.txt) to `/vendor/j0k3r/graby-site-config/` within your wallabag server and clear cache.

**Comment by Molenfeuer** [comment]
So can you confirm this bug? I thought I had done something wrong or something!

Thanks!
