### ISSUE TITLE
Login session is not remembered.

### ISSUE THREAD

**Issue by naquad** [wallabag/wallabag#769]
Even when I check "Stay signed in" I'm beeing logged out after 20-30 minutes.

When I log in I see the following cookie which seems correct to me:
```
Set-Cookie:poche=longhextokenhere; expires=Thu, 16-Oct-2014 23:09:13 GMT; path=/wallabag/; secure; HttpOnly
```

But still after 20-30 minutes I'm beeing asked to sign it.

Any ideas how to debug this or what to fix?

Version: master
PHP: PHP 5.4.4-14+deb7u12

**Comment by emory** [comment]
still an issue in 1.8.1 (via wallabag-dev), also.

**Comment by ParoTheParrot** [comment]
Any chance to fix this in the near future?

**Comment by tcitworld** [comment]
I would love to have help on this issue, in fact. ;)

**Comment by tcitworld** [comment]
I guess we won't fix it in wallabag v1.

**Comment by GitHubGeek** [comment]
It probably has nothing to do with the actual session files. In my setup, uwsgi [handles the session storage](http://uwsgi-docs.readthedocs.org/en/latest/PHP.html#sessions-over-uwsgi-caches-uwsgi-2-0-4). Since it's in-process and in-memory, there's no physical files.

I reckon it's a defect in `inc/3rdparty/Session.class.php`.

p.s. Sorry for replying to an closed issue. Just want to help :smile:

**Comment by tcitworld** [comment]
Hmm, I think I have seen the bug on some installations where uwsgi isn't used anyway.
Isn't it the `longSessionTimeout` part the problem of the file ? Actually I can't find it in what seems to be [the source](https://github.com/tontof/kriss_php5/blob/master/Session.php), but this source doesn't seems to implement cookies anyway.

As I'm reading #115, it seems the session has been patched [so many times](https://github.com/wallabag/wallabag/commits/master/inc/3rdparty/Session.class.php), it's quite ugly.

I'm hesitating to try some things right now, since v2 has the Session bundle to handle it. I'll do it if I find some time and motivation.

> p.s. Sorry for replying to an closed issue. Just want to help :smile: 

No worries, actually, it's still opened, that's the problem. :p

**Comment by P3lUZa** [comment]
Well, its a very annoying problem, hope we can solve it soon

**Comment by nebulade** [comment]
It also happens to me, I keep getting logged out, which is quite annoying, makes the app so much less useful.

**Comment by nebulade** [comment]
I was reading up on the source and saw this [comment](https://github.com/tontof/kriss_php5/blob/master/Session.php#L12) about IP checks. So I was logged in, changed my IP, which kinda happens quite often, as I use public wifi, tethering, ... all the time, and got logged out.

I do understand there might be some session hijacking, but such a session behavior is not standard and really makes it inconvenient to use.

Please revisit this decision, or at least make it option, if it isn't already.

Thanks.

**Comment by tgrosinger** [comment]
Agreed. Sorry to beat a dead horse, but as @nebulade said, this issue is very irritating and is my biggest complaint about wallabag.

**Comment by P3lUZa** [comment]
I think this should be tagged as "urgent" since right now it is the biggest problem on wallabag, which make it unusable

**Comment by tcitworld** [comment]
Yeah, sorry everyone. This is indeed an important bug. These last months, we've been expecting to have version v2 very soon, where this bug isn't present (it uses the SF2 framework), but it gets much delayed. So I guess we will have to fix this in the end.

We totally agree it's really a pain in the ass, to have to login each time, even though a few people would say it's a good safety measure. I can try to fix this asap, but I will be much busy in the next weeks, so don't expect an ETA now.

Sorry again.

**Comment by tcitworld** [comment]
> I was reading up on the source and saw this comment about IP checks. So I was logged in, changed my IP, which kinda happens quite often, as I use public wifi, tethering, ... all the time, and got logged out.

This feature isn't even working in fact. It's the long lasting session feature that's missing that disconnects you. :/

For the good news, I may have been a little pessimist, as the work doesn't seem much important. It will be even more faster if someone can help me test if it works correctly.

**Comment by tgrosinger** [comment]
I am following this issue and will be happy to do any testing (with a little guidance on installing a test version).

**Comment by tcitworld** [comment]
Cool, I'll release a beta version zip very soon.

**Comment by chr15m** [comment]
:+1: - happy to help testing when this is fixed, and thanks for the great software!

**Comment by chr15m** [comment]
For anybody finding this bug and wanting a quick fix, [this blog post mentioned above](http://blog.centresource.com/2006/05/23/php-session-lifetime-an-adventure/) worked for me on Debian GNU/Linux under Apache2 (as root):

```
mkdir /var/lib/wallabag-sessions
chown www-data:www-data /var/lib/wallabag-sessions
# add: "php_admin_value session.save_path /path/to/new/wallabag-sessions" to your wallabag-apache.conf
/etc/init.d/apache2 restart
```

:tada:

**Comment by HLFH** [comment]
@tcitworld Any news of the beta version? I would love to test the fix of this Wallabag issue on my Nginx server.

**Comment by nicosomb** [comment]
For your information, I made on Framabag.org what @chr15m told and it works :+1:

**Comment by HLFH** [comment]
@nicosomb Hi. On my /var/lib/php/session/ folder (owned by **http** user & group) of my Intel NUC server with ArchLinux, it seems that I got *longlastingsession|i:7776000* (in seconds), or 90 days and it's also shown when I go on my Chrome browser in the content settings for cookies management, and my Wallabag cookie will expire on 10/28/15. I'm using **nginx** and php-fpm. In /etc/php/php.ini, I have this necessary line: **session.save_path = "/var/lib/php/session"**. I'm sure I won't lose the session until I clear my browser cache & cookies, which is often done... Thanks, I believe you can close this issue.

**Comment by GitHubGeek** [comment]
Thanks @chr15m ! Nice work around. It doesn't work in some situations (For example, all sessions would be destroyed when app server is restarted). Hopefully, wallabag2 would use something more robust, such as database backed sessions if the "Remember login" checkbox is ticked.

**Comment by tcitworld** [comment]
> Hopefully, wallabag2 would use something more robust, such as database backed sessions if the "Remember login" checkbox is ticked.

It definitely does.

**Comment by Caliandroid** [comment]
Does anybody knows a similiar quick fix for nginx like the one for Apache from chr15m ?

**Comment by tcitworld** [comment]
If you're using php-fpm : http://docs.pyrocms.com/2.1/manual/setup/nginx-with-php-fpm
