### ISSUE TITLE
Can't use RSS feed in wallabag (4pda.to)

### ISSUE THREAD

**Issue by QuAzI** [wallabag/wallabag#7692]
- URL: https://4pda.to/feed/
 - wallabag version: https://app.wallabag.it/atom/list (I don't know which one published)

**Describe what's wrong:**
Just shows 'Error while fetching the feed. Please check the URL.'

**Comment by HolgerAusB** [comment]
I am not sure about this. I don't think, that wallabag can read an external feed to store all of the containing articles or show them to select. You will need a separate feed reader to read the feed and chose manually which articles you want to store at wallabag.

The Feed option in wallabag is for generating a feed of already stored articles. So you can read the articles, stored in wallabag, with a feed reader.

**Comment by j0k3r** [comment]
It's not part of the wallabag open source version.

You should reach helpdesk@wallabag.it instead.
