### ISSUE TITLE
Checkboxes for feeds to select/delete batches

### ISSUE THREAD

**Issue by QuAzI** [wallabag/wallabag#7693]
I am looking at https://app.wallabag.it/atom/items/3096
and it's very slow and uncomfortable to select one by one articles to sort out which I want to read later and which I don't need. 
It would be useful to select all articles which user would like to read, save them to read-it-later queue, then select all other and discard in a batch

**Comment by j0k3r** [comment]
Same as before, it's not part of the open source version.

Reach helpdesk@wallabag.it
