### ISSUE TITLE
Gestion d'export PDF pour lecture hors ligne

### ISSUE THREAD

**Issue by memiks** [wallabag/wallabag#77]
Implémentation d'un export PDF:

Pouvoir mettre des articles dans poche
puis les exporter en pdf pour:
- les lire partout 
- les conserver
- les mettre sur une liseuse etc...

avec un format beaucoup plus joli à regarder que les articles d'origine.

le principe :
1) mettre en place une librairie d'export pdf comme http://dompdf.github.io/
2) mettre un bouton afin d'exporter :
- la séléction d'articles
- les articles "à lire"
- les articles "favoris"

Ainsi on a plusieurs mode de lecture hors ligne tout en restant KISS

Fréd.

**Comment by Alwaysin** [comment]
" We'll implement it when 1.8 will be released", it means now? :D

(Sorry for the +1, I just neeeed this feature ^^)

**Comment by nicosomb** [comment]
This feature is done :) In dev version. So we have to release this version.

**Comment by tcitworld** [comment]
I close for the moment.

**Comment by Alwaysin** [comment]
:+1:
