### ISSUE TITLE
Entry reloaded but fetching content failed for Wikipedia page

### ISSUE THREAD

**Issue by ethan-xbl** [wallabag/wallabag#7717]
**Description:**

I am experiencing an issue with my Wallabag instance when trying to fetch content from the following URL: [https://en.wikipedia.org/wiki/Nobel_Prize_in_Literature](https://en.wikipedia.org/wiki/Nobel_Prize_in_Literature). The error message I receive is "Entry reloaded but fetching content failed."

### Steps to Reproduce:
1. Set up Wallabag in my home lab.
2. Attempt to save the article from the provided Wikipedia link.
3. Encounter the error message mentioned above.

### Logs:
I have checked the `graby.log` file, but I am unable to identify any specific errors. If necessary, I can provide snippets of the log for further analysis.

### Additional Information:
- I have verified that my internet connection is stable.
- I have tried changing the User-Agent settings, but the issue persists.
- Other URLs seem to work fine, which suggests that this might be specific to this page or its structure.

### Environment:
- Wallabag version: 2.6.9
- Operating System: Unraid

I would appreciate any guidance or suggestions on how to resolve this issue. Thank you!

---
[graby.log](https://github.com/user-attachments/files/17342460/graby.log)

**Comment by j0k3r** [comment]
This is weird because I don't any issue on wallabag.it
<img width="1441" alt="image" src="https://github.com/user-attachments/assets/da32b395-6f72-43d3-8e87-8749af4c5054">

Reading the log you provided, you got an issue on your network:

> [2024-10-11T12:05:57.987486+00:00] graby.WARNING: Request throw exception (with no response): Provided host "en.wikipedia.org" resolves to "198.18.127.197", which matches a blacklisted value: 198.18.0.0/15 {"error_message":"Provided host \"en.wikipedia.org\" resolves to \"198.18.127.197\", which matches a blacklisted value: 198.18.0.0/15"} []

**Comment by ethan-xbl** [comment]
thank 

> This is weird because I don't any issue on wallabag.it <img alt="image" width="1441" src="https://private-user-images.githubusercontent.com/62333/375760095-da32b395-6f72-43d3-8e87-8749af4c5054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTc5NDAsIm5iZiI6MTcyODY1NzY0MCwicGF0aCI6Ii82MjMzMy8zNzU3NjAwOTUtZGEzMmIzOTUtNmY3Mi00M2QzLThlODctODc0OWFmNGM1MDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE0NDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNDQwMDM3ZjQzNTA4Y2Y1OTVkOTFmMDRjNGUxZmI3YjI1N2FlMWRjZWVmODI5MzQwY2ZiMTQzNzQxNDFkNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6nFNVThpTbTJohyhS6vZGD5fgRmylp_pCN4EoLXxKpI">
> 
> Reading the log you provided, you got an issue on your network:
> 
> > [2024-10-11T12:05:57.987486+00:00] graby.WARNING: Request throw exception (with no response): Provided host "en.wikipedia.org" resolves to "198.18.127.197", which matches a blacklisted value: 198.18.0.0/15 {"error_message":"Provided host "en.wikipedia.org" resolves to "198.18.127.197", which matches a blacklisted value: 198.18.0.0/15"} []

Thank you for your help! As you suggested, I changed the network, and now the problem has been resolved.
