### ISSUE TITLE
Add my new article to wallabag's wiki: Auto-Update site-configs

### ISSUE THREAD

**Issue by HolgerAusB** [wallabag/wallabag#7734]
I wrote a wiki article, to show how one can auto-update site-depended config files from the fivefilters repo independently from wallabag releases.

As I do not have write permissions to [the wiki](https://github.com/wallabag/wallabag/wiki), I wrote this issue to get in contact. If it is possible to give me write permissions just for the wiki, it would be nice, if someone can grant this to me.

If this is not possible, please feel free to copy my draft from [my temp repo](https://github.com/HolgerAusB/temp-wiki/blob/main/Auto-Updating%20Wallabag's%20site-depended%20config.md).

@j0k3r, @Kdecherf, @Simounet; Please check whether my assumptions about how it works are correctly and adjust them if necessary. And if someone with docker skills could please fill the last paragraph with some helpful advice. ❤️

Maybe @nicosomb could also consider setting up the auto-update on app.wallabag.it as well. It is now a year behind.

**Comment by HolgerAusB** [comment]
Thank you for opening the wiki, @j0k3r.
The [wiki page](https://github.com/wallabag/wallabag/wiki/Auto%E2%80%90Updating-wallabag's-site%E2%80%90depended-config) is now live.

The docker part is still a To-Do. Would be nice, if someone could fill that gap.

**Comment by Simounet** [comment]
Thanks a lot for this, @HolgerAusB
