### ISSUE TITLE
Wrong display in wallabag (ArsTechnica.com)

### ISSUE THREAD

**Issue by condenseinform** [wallabag/wallabag#7749]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [X] I've tried myself without success
- [X] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: https://arstechnica.com/gadgets/2024/10/ward-christensen-bbs-inventor-and-architect-of-our-online-age-dies-at-age-78/
 - wallabag version: 2.6.9

**Describe what's wrong:**
Both f43.me and Wallabag miss the same first few paragraphs after Ars Technica's website redesign.

![Wallabag_-_error_with_new_ArsTechnica_design_-_Wallabag_view](https://github.com/user-attachments/assets/d81948f5-56f5-4d17-a4cf-84c2fdebdd12)

![Wallabag_-_error_with_new_ArsTechnica_design_-_ArsTechnica_view](https://github.com/user-attachments/assets/fbf396ca-c0cd-49ba-b262-bd3beec766ba)

**Comment by HolgerAusB** [comment]
This has been fixed 3 weeks ago. Copy [arstechnica.com.txt](https://github.com/fivefilters/ftr-site-config/blob/master/arstechnica.com.txt) to your installation of wallabag under `vendor/j0ker/graby-site-config` or follow this new [wiki article](https://github.com/wallabag/wallabag/wiki/Auto%E2%80%90Updating-wallabag's-site%E2%80%90depended-config) to get auto-updates of site-configuration.

Nevertheless, the excerpt starts with some navigation fringe. I will look into this in a few hours.

**Comment by HolgerAusB** [comment]
I also fixed the new nav/meta fringe now

**Comment by condenseinform** [comment]
Sorry, I should have specified this was on app.wallabag.it. It does appear to be resolved there now. Thanks for your help!

**Comment by nicosomb** [comment]
I updated wallabag.it last days, that's why it's now fixed :)

**Comment by condenseinform** [comment]
Thanks so much!

**Comment by HolgerAusB** [comment]
@nicosomb Nicolas, have you thought about setting up app.wallabag.it so that the SiteConfigs update automatically from the upstream repo? Have you seen my [wiki post](https://github.com/wallabag/wallabag/wiki/Auto%E2%80%90Updating-wallabag's-site%E2%80%90depended-config) about this?

I know, you are working hard on 2.7 right now, but you should consider this at least after that release. Please.

**Comment by nicosomb** [comment]
I will have a look to use your tips on wallabag.it
