### ISSUE TITLE
Import from omnivore?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [wallabag/wallabag#7750]
Hi,

With omnivore [getting sold to ElevenLabs](https://blog.omnivore.app/p/omnivore-is-joining-elevenlabs) and adding the ability to [fully export our data](https://docs.omnivore.app/using/exporting.html) I was wondering wether it was possible to import their export format into wallabag?

**Comment by nicosomb** [comment]
Hello @thiswillbeyourgithub 
We discuss about this feature here: https://github.com/wallabag/wallabag/discussions/7742
