### ISSUE TITLE
Wrong display in wallabag shepherd.com

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#7755]
We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: [[full url of the content]](https://shepherd.com/best-books/science-fiction-that-you-should-definitely-read)
 - wallabag version: 2.6.9

**Describe what's wrong:**
All the content is not fetched.

**Comment by HolgerAusB** [comment]
- Longer text is hidden behind an `<button onclick="script or similar"` wich I could not resolve. So you see just the short versions.
- Article contains a lot of 'related' thing, which I commonly try to strip. But as the site is for books, that could be helpful. And as I don't see unique IDs or classes to strip them, all is kept in.
