### ISSUE TITLE
FR: Search inside annotations

### ISSUE THREAD

**Issue by juanbretti** [wallabag/wallabag#7764]
# **Is your feature request related to a problem? Please describe.**
I make annotations to the articles.
These annotations are important comments based on what I read.
More likely I do remember my annotations, so would be nice to be able to search for those texts.

As mentioned on #3635 , annotations are often more important than original text.

# **Describe the solution you'd like**
Multiple ideas:
* The search input area could search inside articles and annotations at the same time
* The search area could have an operator like `annotation:(my comments on the article)`

# **Describe alternatives you've considered**
So far, I have not found any alternatives.
So, I am not searching inside my annotations.

# **Additional context**
My proposal in pictures:

![image](https://github.com/user-attachments/assets/bea2b318-2e4e-4f19-ad41-5b2e16ef940a)

or

![image](https://github.com/user-attachments/assets/a43ecde8-3d5b-41fc-93ce-9bb79ef51611)

# **Conclusion**
Thank you all for your consideration.

**Comment by nicosomb** [comment]
In fact, I checked and this feature is already implemented in next minor version (2.7) 🎉

**Comment by boston-black** [comment]
How does this feature work, @nicosomb ? I cant find a way to search or display/list by search annotations.

**Comment by HolgerAusB** [comment]
we are still on wallabag 2.6.x, no ETA for 2.7 yet
