### ISSUE TITLE
RSS feeds don't refresh

### ISSUE THREAD

**Issue by adrienneteicher** [wallabag/wallabag#7778]
### Environment

* **Version**: Wallabag.it
* **Installation**:
* **PHP version**:
* **OS**:
* **Database**:
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  PASTE HERE
  ```
</details>

### What steps will reproduce the bug?

# Steps to reproduce the issue
- I add RSS feeds
- Wallabag pulls in last ten articles
- Never refreshes feeds again unless I ask for individual refresh on a given feed

**Comment by nicosomb** [comment]
Hello @adrienneteicher. 
I close this issue, this feature is only available on wallabag.it. 
Please contact me at nicolas@wallabag.it. I will have a look to the RSS status.
