### ISSUE TITLE
Feature request: add tags on highlight

### ISSUE THREAD

**Issue by saccohuo** [wallabag/wallabag#7789]
Is there a way to add tags to highlights? So I can search highlights with specified tag.

Refer to Readwise Reader and Omnivore.

**Comment by didli** [comment]
Not sure if I understand correctly but do "highlights" refers to the left menu thingy ('unread','starred','archive' ... etc) ?
Because I intended to ask for this as a feature request too.

**Comment by saccohuo** [comment]
`Highlights` means the underline text in the article, annotation but no comment on it, like this.
![image](https://github.com/user-attachments/assets/a76ebd8f-cb5d-4edc-a8b7-b4a3568ee7e1)

**Comment by didli** [comment]
Then we're not asking for the same thing indeed. Seems also a good proposal to me though.

**Comment by nicosomb** [comment]
Hello! 

Thank you for your feature request. 

We understand your needs but we won't plan to develop it. It will add complexity to our software. 

Have a nice day!

https://wallabag.org/news/wallabag-wont-accept-pr-feature-request/
