### ISSUE TITLE
Blank page after deleting items in search results page

### ISSUE THREAD

**Issue by jman-schief** [wallabag/wallabag#7821]
### Environment

* **Version**: 2.6.8
* **Installation**: docker
* **PHP version**: -
* **OS**: Debian stable (bookworm)
* **Database**: - 
* **Parameters**: (not relevant)

### What steps will reproduce the bug?

Open this page `https://wallabag.mydomain.org/search`.

This page is reached this way:
- Run a search
- Delete one or more items from the page of search results
- User is redirected to `/search` (a blank page)

Thanks!

**Comment by nicosomb** [comment]
I confirm the bug.

**Comment by nicosomb** [comment]
Fixed.
