### ISSUE TITLE
Wrong display in wallabag (doc.rust-lang.ru and doc.rust-lang.org)

### ISSUE THREAD

**Issue by vistar** [wallabag/wallabag#7854]
**Content related:**
 - URL: https://doc.rust-lang.ru/book/print.html and https://doc.rust-lang.org/book/print.html
 - wallabag version: 2.6.10 selfhosted and SaaS versions

**Describe what's wrong:**
On https://doc.rust-lang.org/book/print.html are ignored:

```html
<h1 id="foreword"><a class="header" href="#foreword">Foreword</a></h1>
...
<h1 id="introduction"><a class="header" href="#introduction">Introduction</a></h1>
...
<h2 id="who-rust-is-for"><a class="header" href="#who-rust-is-for">Who Rust Is For</a></h2>
```
etc.

On https://doc.rust-lang.ru/book/print.html are ignored:

```html
<h1 id="Предисловие"><a class="header" href="#Предисловие">Предисловие</a></h1>
...
<h1 id="Введение"><a class="header" href="#Введение">Введение</a></h1>
...
<h2 id="Кому-подходит-rust"><a class="header" href="#Кому-подходит-rust">Кому подходит Rust</a></h2>
```

And after it 
```html
 <h2 id="Кому-подходит-rust"><a class="header" href="#Кому-подходит-rust">Кому подходит Rust</a></h2>
```
all text is h2: https://i.imgur.com/79IERcN.jpeg

**Comment by HolgerAusB** [comment]
Hi @vistar had you tested my suggestions in #7850 ? I can't test this here, because of the huge amount of content.

**Comment by HolgerAusB** [comment]
Thank you @vistar for testing, feedback and PR. I changed the configs a little, because most human readers/editor expecting the test_url(s) at the bottom of the file.
