### ISSUE TITLE
Installation Error: connection refused; error code 255; system requirements are not fulfilled

### ISSUE THREAD

**Issue by Hitumi** [wallabag/wallabag#7856]
<img width="563" alt="截屏2024-11-26 11 55 35" src="https://github.com/user-attachments/assets/42b6ca8b-aa28-4420-b7a0-4f43ab22102f">
<img width="565" alt="截屏2024-11-26 11 56 03" src="https://github.com/user-attachments/assets/acd337ac-d799-4538-843a-3502f8295542">

### system: 
macOS Sonoma 14.2.1
### Installation: 
git clone
### php & composer: 
latest ver.
### parameters:
database_driver (pdo_mysql): pdo_mysql
database_host (127.0.0.1): 127.0.0.1
database_port (null): null
database_name (wallabag): WuYingLi
database_user (root): root
database_password (null): null
database_path (null): null
database_table_prefix (wallabag_): wallbag_
database_socket (null): null
database_charset (utf8mb4): utf8mb4
domain_name ('https://your-wallabag-instance.wallabag.org'): https://your-wallabag-instance.wallabag.org
server_name ('Your wallabag instance'): Your wallabag instance
mailer_dsn ('smtp://127.0.0.1'): smtp://127.0.0.1
locale (en): en
secret (CHANGE_ME_TO_SOMETHING_SECRET_AND_RANDOM): CHANGE_ME_TO_SOMETHING_SECRET_AND_RANDOM
twofactor_sender (no-reply@wallabag.org): no-reply@wallabag.org
fosuser_registration (true): true
fosuser_confirmation (true): false               
fos_oauth_server_access_token_lifetime (3600): 3600
fos_oauth_server_refresh_token_lifetime (1209600): 1209600
from_email (no-reply@wallabag.org): no-reply@wallabag.org
rss_limit (50): 50
rabbitmq_host (localhost): localhost
rabbitmq_port (5672): 5672
rabbitmq_user (guest): guest
rabbitmq_password (guest): guest
rabbitmq_prefetch_count (10): 10
redis_scheme (tcp): tcp
redis_host (localhost): localhost
redis_port (6379): 6379
redis_path (null): null
redis_password (null): null
sentry_dsn (null): null

**Comment by j0k3r** [comment]
Just read the error message.
Ensure you MySQL is up and running and that PHP can connect to it.
Nothing more we can do.
