### ISSUE TITLE
403 Forbidden, Blocked on nature.com

### ISSUE THREAD

**Issue by mrhalliwell** [wallabag/wallabag#7862]
Have searched the nature.com. Two popped up and closed. But that doesn't help me solve the problem.

**Content related:**
 - URL:https://www.nature.com/articles/s41366-024-01473-y

**Describe what's wrong:**
Using edge browser extension to fetch the content. The entry in wallabag shows below.

403 Forbidden

Blocked

Debug Information
Server: cache-fra-etou8220045-FRA

Client: 138.201.122.115

Debug: 0149f47eabf9a20d0893e2a44e5a6323

Varnish cache server

**Comment by HolgerAusB** [comment]
- Which wallabag version?
- self-hoster or hosted service (which)?
- which browser extension exactly including version?

For Edge Browser it is recommended to use 'wallabagger' from the [Chrome WebStore](https://chrome.google.com/webstore/detail/wallabagger/gbmgphmejlcoihgedabhgjdkcahacjlj). The version on the Edge Store is too old and not longer maintained.

In wallabagger's settings you need to activate the option 'Retrieve content from the browser' to get articles from site, that uses anti bot mechanics or need a log-in.

I fixed the site config, so you now could fetch the article with wallabag UI or your existing browser extension. But I recommend a newer wallabagger as written above.

If self-hoster, you need to copy [nature.com.txt](https://github.com/fivefilters/ftr-site-config/blob/master/nature.com.txt) to your installation to `vendor/j0ker/graby-site-config/` or read [this wiki article](https://github.com/wallabag/wallabag/wiki/Auto%E2%80%90Updating-wallabag's-site%E2%80%90depended-config) to get automatic updates.

**Comment by mrhalliwell** [comment]
Your solution using chrome extension worked. Thanks. I will close this issue
