### ISSUE TITLE
some fetched some not on the same domain ( barrons.com)

### ISSUE THREAD

**Issue by mrhalliwell** [wallabag/wallabag#7864]
We have a lot of requests about fetching config issue. It'll help us A LOT if you give a try to fix it on your own following the doc.
If you failed to fix it yourself, tick the following boxes:
- [V ] I've tried myself without success
- [ ] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: 
 https://www.barrons.com/articles/60-40-portfolio-bond-yield-inflation-fddb9c4b?st=MKL2je
https://www.barrons.com/articles/ai-evs-nuclear-energy-electricity-a4198583
 - wallabag version: 
subscribed to app.wallabag.it
using laptop and edge browser.
Wallabag v2
Wallabag Extension 1.18 (using chrome extesion on edge browser)  (retrieve content from browser is checked)

**Describe what's wrong:**
So the first barrons.com article can not be fetched. But the second article is fetched perfectly. 
Not sure exactly why. 

below is the first article in Wallabag
![image](https://github.com/user-attachments/assets/b9d37088-3cbb-4d07-b0f0-c629445f2e30)

and this the second article
![image](https://github.com/user-attachments/assets/2c32c414-104e-487a-9ca3-b34ec592dfbd)

**Comment by HolgerAusB** [comment]
@mrhalliwell, I fixed the problem, but unfortunately you need to wait until the new config file for barrons has been updated to app.wallabag.it

**Comment by mrhalliwell** [comment]
> @mrhalliwell, I fixed the problem, but unfortunately you need to wait until the new config file for barrons has been updated to app.wallabag.it

Thank you so much for the imminent response. WOuld you mind share what causes the problem? Why some articles were properly fetched some not?

**Comment by HolgerAusB** [comment]
@mrhalliwell without any site depended config, wallabag tries to predict which parts of the webpage is relevant an which are not. Sometimes that works great and sometimes it does not, even on the same domain. That could be caused by different designs or just by the structure of the article.

A domain depended config, as the one I wrote, defines the relevant parts by html nodes via XPath selectors.
