### ISSUE TITLE
RSS feeds retrieve already removed articles

### ISSUE THREAD

**Issue by QuAzI** [wallabag/wallabag#7868]
I have 2 RSS feeds with 'Import automatically all the articles' option. I read some articles on https://app.wallabag.it/unread/list , then remove some non-interesting, duplicates... on next RSS load I can found again those already removed articles in top of articles list as unread.

Installation: https://app.wallabag.it/

**Comment by nicosomb** [comment]
Hello! 

Could you send me an email please? https://app.wallabag.it/subscription/helpdesk
