### ISSUE TITLE
Plop instead of article for some links from feed

### ISSUE THREAD

**Issue by QuAzI** [wallabag/wallabag#7876]
Sometimes I see empty articles by links from feed
![image](https://github.com/user-attachments/assets/74a72307-5ba7-419c-a0a9-9daf9c28ac2c)
I thought it was already removed articles but in this case article present and works fine
link: https://habr.com/ru/posts/863978/

It would be nice to fix it or at least to use title and description with link from RSS data for missed articles. 
Something like
![image](https://github.com/user-attachments/assets/d8e1876d-38b5-4abd-9122-5ce9dd62e5ef)

**Comment by QuAzI** [comment]
Re-fetch content doesn't work
![image](https://github.com/user-attachments/assets/3b94f6e8-f328-48e6-8a1f-369632e1c53e)

**Comment by nicosomb** [comment]
Could you please use this page to have support on wallabag.it https://app.wallabag.it/subscription/helpdesk?

**Comment by QuAzI** [comment]
It less convenient, increases duplication of same issue by many users (as they can't find issue) and looks like no fixes happen

**Comment by Kdecherf** [comment]
@QuAzI the main point of using the helpdesk page is because this feature is not something that is part of the open source version of wallabag
