### ISSUE TITLE
Error when requesting entry list in iOS app

### ISSUE THREAD

**Issue by victor10292** [wallabag/wallabag#7890]
### Environment

* **Version**:  latest
* **Installation**: Package
* **PHP version**: 8.4
* **OS**: Armbian
* **Database**: Sqlite
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  PASTE HERE
  ```
</details>

### What steps will reproduce the bug?

I have wallabag installed in my iPhone. It will connect to the wallabag server hosted in my own server. When refresh the home page to list all the entry list, although all the entries are listed correctly,  I happen to find some error messages in var/log/prod.log file. Here is the screenshot of the error. Could you help me why it happens.
![2024-12-11_21-00](https://github.com/user-attachments/assets/4dbc5103-a274-4a00-9676-644ca5401cf6)

**Comment by Kdecherf** [comment]
Hello @victor10292,

You should probably open an issue on the [ios-app](https://github.com/wallabag/ios-app) repository instead

**Comment by victor10292** [comment]
I will do it. Thanks
