### ISSUE TITLE
Can't add a new entry in web browser

### ISSUE THREAD

**Issue by victor10292** [wallabag/wallabag#7892]
### Environment

* **Version**: 2.6.10
* **Installation**: Package
* **PHP version**: 8.4
* **OS**: Armbian
* **Database**: sqlite
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  ```
</details>

### What steps will reproduce the bug?

Wallabag is deployed in my own server. I can create a new entry using http://localhost. However it fails if using https://mydomain/ to do the same thing. The page is blank. The page is forwarded to /new-entry. The other functions work fine except for creating a new entry. Could you please help me out?

My parameters.yml is as follows:

![2024-12-11_21-00](https://github.com/user-attachments/assets/ae79be0f-2d7e-4e5f-9c7e-2b3223243020)

**Comment by HolgerAusB** [comment]
- I hope these aren't your real database_user, database_password in parameters.
- Your "Register" button is open, **you should block this** or anybody can register a new account! This is a bug (in my opinion) which has never been closed.

What is your webserver or reverse proxy? I use Apache2:

### deactivate register button
in the apache2 conf file for wallabag:
```xml
<LocationMatch "/register">
     Deny from All
</LocationMatch>
```

### activate rewrite rules
in apache2 conf file for wallabag:
```xml
<Directory /var/www/wallabag/web>
    AllowOverride None

    <IfModule mod_rewrite.c>
        Options -MultiViews
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ app.php [QSA,L]
    </IfModule>
</Directory>
```
If this doesn't help, please post your web-server's configuration for the wallabag subdomain. But please MASK all sensible data this time.

**Comment by victor10292** [comment]
Thanks for your reminder. I am using Nginx as the web server. Here is the configuration file for wallabag application. Appreciate your help.

![2024-12-11_21-00](https://github.com/user-attachments/assets/6d52d821-5bd1-477c-89b6-0a3f489b0427)

**Comment by HolgerAusB** [comment]
I never used Nginx, so I can't help here. It seems, you took the template from the [docs](https://doc.wallabag.org/en/admin/installation/virtualhosts#configuration-on-nginx). Maybe you could also activate the logs. Maybe they can help here.
```conf
error_log /var/log/nginx/wallabag_error.log;
access_log /var/log/nginx/wallabag_access.log;
```

**Comment by victor10292** [comment]
It works pretty well for any other functions except for adding a new entry. What's weird is that I can't find any errors in either wallabag or nginx system logs when it fails.

**Comment by j0k3r** [comment]
Have you tried to add a real content instead from a public domain, like a news media?
Have you check wallabag log in `WALLABAG_DIR/var/logs/prod.log`?

**Comment by victor10292** [comment]
@j0k3r yes, I traced the log file `var/logs/prod.log` while adding a new entry. But there is no messages printed in the terminal. As I mentioned above, if I visit wallabag through `http://localhost`, it works. If I visit wallabag via `https://my_domain`, adding a new entry fails, but others function well.

**Comment by j0k3r** [comment]
Have you check browser logs?

I'm sorry but if you can find any logs, it'll be hard almost impossible to help you.

**Comment by victor10292** [comment]
@j0k3r Completely understood.  Thanks for your advice, I compared http request from localhost and domain visiting. If the request is sent from localhost, the request method is `POST` and the `/new-entry` is forwarded. New entry is created successfully. If the request is sent from my domain, the request method is `GET`, and `/new-entry` is not forwarded further. Then the entry is not created. Did I do something wrong in the configuration file that prevents forwarding the requests? But other similar functions work perfect in the same instance.

![local](https://github.com/user-attachments/assets/41999ee9-2b10-4730-b3b9-1bca6a39f8ec)
![domain](https://github.com/user-attachments/assets/246e250d-e21d-41d7-89f9-ed273e2ce1c9)

**Comment by HolgerAusB** [comment]
As you still haven't disabled your 'Register' button @victor10292 , I tried to register myself. After sending the register form I got this: 
```
500: Internal Server Error
Connection could not be established with host "ssl://127.0.0.1:465": stream_socket_client(): Unable to connect to ssl://127.0.0.1:465 (Connection refused)

```
Maybe that helps @j0k3r to identify the problem?

**Comment by j0k3r** [comment]
It means wallabag can't send emails. I don't think it's related to adding a content.

**Comment by victor10292** [comment]
As I mentioned, the request is not forwarded to the target. I did further investigation by tracking the request and its response. I find the response from /new-entry is as follows. It seems that CSRF token is invalid. But I am not familiar with PHP. I don't know where to find the source php file and fix it. 
![domain_response](https://github.com/user-attachments/assets/2e617d94-c35f-420c-839d-cbdb932cba88)

**Comment by victor10292** [comment]
Thanks for all of your patience. I don't know why the token is not valid. I have to temporarily disable CSRF protection in wallabag application.

**Comment by j0k3r** [comment]
This is most of the time a session problem. Maybe the generated cache for localhost and the one generated for mydomain conflicts ecah other.. I don't know
