### ISSUE TITLE
Articles content never fetched after import if no article is present

### ISSUE THREAD

**Issue by MattiSG** [wallabag/wallabag#793]
This is on a self-hosted v1.7.2.

1. Delete the default articles from the Home tab.
2. Import a `ril_export.html` file from Pocket.

**Result:** the import process supposedly works fine, but on only gets empty “Click to finish import” articles. If one clicks on these articles, or on the “fetch content for articles with no content” link in the configuration page, one only immediately gets an “Import finished” notification.

If the procedure is repeated, then the fetching of articles starts.

If the import is done without deleting the default articles, then the fetching of articles starts fine too.

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
