### ISSUE TITLE
Fetch articles via proxy

### ISSUE THREAD

**Issue by markwaters** [wallabag/wallabag#794]
By fetching the content directly we may be exposing our reading habits , interests , etc to any agency snooping on the connection between the wallabag server and the 'bagged' articles site.

Would it be possible to have wallabag download the saved article content via a proxy server - http or socks.

Thanks.

**Comment by m0** [comment]
All issues related "fetching articles through an outgoing proxy" (not how to use a reverse proxy!) seem to be closed, but I can't find any support for this in wallabag. Did I miss something?

**Comment by j0k3r** [comment]
Well, there are all old issues.
We aren't using FullTextRSS for example.

Maybe you can create a new issue and link all issues related to proxy in it.
