### ISSUE TITLE
oAuth implementation

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#795]
Here is a silex provider for oAuth authentication https://github.com/gigablah/silex-oauth

**Comment by willdurand** [comment]
OAuth is not designed for authentication, "Auth" stands for authorization, even if it is possible to use authorization to simulate an authentication process..

**Comment by nicosomb** [comment]
We'll have 2 ways to create an account on wallabag: 
* via a standard form
* via oAuth (and third services like github, twitter)

First one is already implemented, and for the API, we use wsse. 

Do you think I can implement the 2 ways?

**Comment by willdurand** [comment]
Wallabag promotes free software, open source, and freedom IMO, so I don't think using third-party services to auth[enticate|orize] users is wise.

**Comment by tcitworld** [comment]
Yeah, I was searching for similar cases around other free software webapps, but it seems none are using oAuth in that way.

However, I still think oAuth could be proposed as a possibility for registering. Having to click just on a button will be appreciated by many users. And I would sign anytime to use 3rd party services if in return it encourages them to use non proprietary alternatives. I found it like using Windows to run free software.

But I'm not sure on the issue, I'll discuss with some people.

**Comment by foxmask** [comment]
The main pro for "monsieur tout le monde" is to avoid to register a 10000th time a new acount. Even if i personaly wont use a third party provider, its an explanation like another one

**Comment by tcitworld** [comment]
Can't wait to login with Pocket to wallabag. :-)

**Comment by nicosomb** [comment]
Aaaaand oAuth is in #1436!

**Comment by nicosomb** [comment]
#1436 is merged, we can close this issue.

**Comment by ViViDboarder** [comment]
@nicosomb I was looking over the merged patch and it seems to allow Wallabag as an oAuth provider, rather than allowing Wallabag to authorize some user based on an external provider, no?

I've been making an attempt to host all my own applications and a key part of making that easy is for me to use a single oAuth provider for all my services. Is there a way to configure Wallabag to use an additional provider?

**Comment by j0k3r** [comment]
This was something we talked about in the past, like being able to login using facebook / twitter / google / openid / whatever but we never implemented it because of the lack of interest from our users.
