### ISSUE TITLE
Prefix for database

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#799]
Contrary to v1, we must give availability to wallabag users to create tables with prefix. 

This issue concerns only mysql and postgres storage.

**Comment by j0k3r** [comment]
Solution to try:

- http://doctrine-orm.readthedocs.org/en/latest/cookbook/sql-table-prefixes.html
- http://www.port8000.de/blog/2011/01/table-prefix-for-doctrine-ormdbal/
- http://stackoverflow.com/a/8366548/569101
