### ISSUE TITLE
Search does not work properly after first page

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#809]
If I search for a term, here are my results : 

![](https://lut.im/zl6gohkY/6wH0hpkN)

3 pages of results, as expected

![](https://lut.im/ggQ2XNPc/5wq5X6iH)

But if I click on second page, I get all my articles (which are not linked to my search).

The "apply tag to this search" function works properly.

**Comment by nicosomb** [comment]
I close. We don't have this bug in v2 (this feature is not implemented yet).
