### ISSUE TITLE
Wallabag seems to download doubleclick ad images

### ISSUE THREAD

**Issue by lvuser** [wallabag/wallabag#827]
Wallabag seems to be downloading images from doubleclick.
It seems to point to a 1x1 pixel. Not sure if the ad is tied to IP so when accessing from another IP, you get a pixel.
Can you add a filter to exclude downloading images from doubleclick? 
Note: I do have enabled the option to cache images locally.
Original Article: http://9to5mac.com/2014/08/29/seeing-through-the-illusion-understanding-apples-mastery-of-the-media/
Example: 
![wallabag](https://cloud.githubusercontent.com/assets/4620411/4163296/4beafe34-34e5-11e4-9065-a90329ad8ccb.png)

**Comment by tcitworld** [comment]
It doesn't seem to download them anymore in dev version.
