### ISSUE TITLE
Unclear config settings

### ISSUE THREAD

**Issue by igufi** [wallabag/wallabag#832]
1. Under the configuration screen, there is a link with the guidance "You can click here to fetch content for articles with no content." This sentence makes little sense without some additional clarification of the intended usage. (I assume this is for imported URLs without further content?).

2. It would be good to also expand on the difference between downloading your "wallabag database" and "wallabag data" - for the uninitiated, these sound more or less identical?

**Comment by nicosomb** [comment]
This issue concerns wallabag v1 only. wallabag v2 won't evolve.
