### ISSUE TITLE
Fatal error on Importing from Pocket

### ISSUE THREAD

**Issue by fujianto** [wallabag/wallabag#833]
I've got this Fatal error when trying to import from Pocket.

`Fatal error: Call to a member function fetch() on a non-object in /home/u634230043/public_html/inc/poche/Database.class.php on line 389`

Here's my host configuration.
Wallabag version 1.7.2
MySQL

Result from compatibility check.
*PHP*		5.3.3 or higher		**5.4.32**
*XML*			     Enabled			**Enabled, and sane**
*PCRE*			Enabled			**Enabled**
*Data filtering*		Enabled			**Enabled**
*Tidy*			Enabled			**Disabled**
*cURL*			Enabled			**Enabled**
*Parse ini file*		Enabled			**Enabled**
*Parallel URL fetching*	Enabled			**Enabled**
*allow_url_fopen*		Enabled			**Enabled**
*gettext*			Enabled			**Enabled**

I don't have access to php.ini file and php error log. I've tried to keep importing, after several batches the Fatal error persist, sometimes causing 500 internal server error.
Is it because the host just bad? Since I'm using free hosting.

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
