### ISSUE TITLE
Adding Tags when saving URL from Chrome extension

### ISSUE THREAD

**Issue by fujianto** [wallabag/wallabag#835]
On the current version, Is it possible to add tag after saving article url from Chrome? Perhaps adding extra tags parameter on popup.js will do the trick?

`var if_url = base_url + '?action=add&url=' + btoa(url)+'&tags='+tags;`

Is there a way to get the latest article ID? After the url is submitted, the  latest article ID could be used to update the tags of the recently submitted article.

**Comment by nicosomb** [comment]
this issue needs to be moved to the chrome ext project.

**Comment by nicosomb** [comment]
And I think it's already available in the next version of the Chrome ext.

**Comment by nicosomb** [comment]
It's done here https://github.com/Rurik19/wallabagger
