### ISSUE TITLE
Make joomla sites show full articles

### ISSUE THREAD

**Issue by jakschu** [wallabag/wallabag#838]
It would be great if wallabag could add ?print=1 to the url of joomla sites (can be detected most of the time by their meta generator tag), which renders multi-page sites to a single page.

**Comment by j0k3r** [comment]
@jakschu this can be done in graby (the content extractor of wallabag v2).
Do you know if *all* joomla website have this meta ?

```
<meta name="generator" content="Joomla! 1.5 - Open Source Content Management" />
```

If yes, could you provide us the class / id we should find in the html to get the content ?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
