### ISSUE TITLE
Contributing to wallabag and/or site_config

### ISSUE THREAD

**Issue by zinnober** [wallabag/wallabag#849]
Hey folks, I did some contributions to site_config on reworking/extending existing templates as well as adding templates for new sites. Except for one initial commit (https://github.com/wallabag/wallabag/commit/19438d30215e59c8433d869b0ff23777c7bc3ab2) I only contributed to the ftr-site-config repository. My purpose is actually to support wallabag.

I am now not really sure what you would prefer for wallabag: Should I also commit the same changes to the wallabag repository (dev branch)? Or are you merging changes to site_config on aregular basis into wallabag anyway? In that case I'm fine with just submitting to site_config...

What would you prefer?

**Comment by j0k3r** [comment]
The best solution is to commit site_config updates to the _official_ repo: https://github.com/fivefilters/ftr-site-config
Wallabag v2 uses these files.
And we'll think about an automatic update in Wallabag itself (see https://github.com/wallabag/wallabag/issues/1284)
