### ISSUE TITLE
Bylines not being grabbed

### ISSUE THREAD

**Issue by nathanairplane** [wallabag/wallabag#850]
More often than not, bylines are not being grabbed by Wallabout. As a writer myself, I take personal offense! :) Is there any way that this can be fixed? 

Thanks for all your great work!

**Comment by nicosomb** [comment]
Hello @nathanairplane! 

Do you have some URL who don't work?
We can change configuration for specific URL, but not for all websites (we can't tell "for every website, take the byline").

**Comment by nathanairplane** [comment]
Greetings again! This seems to be a problem with most sites. I realize it might be too difficult a thing to generalize, and that's okay. But, for instance, the author doesn't appear for articles on Medium, like [this](https://medium.com/backchannel/how-india-pierced-facebook-s-free-internet-program-6ae3f9ffd1b4#.wmrgfdcif). NYTimes.com articles seem to work (as I recall from working on their backend years ago, we might be benefiting from their fairly archaic system, but things have probably changed). But just about all other publications are author-less.

By the way, 2.0 looks great. Wonderful work, all who contributed!

**Comment by nicosomb** [comment]
Thank you (and for your tweet too).
About big websites like medium.com and nytimes, we need to fix that.

**Comment by j0k3r** [comment]
Can you provide a link please ?
Thanks

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
