### ISSUE TITLE
how to import big files from pocket, pre-processing to avoid import of read links without a tag

### ISSUE THREAD

**Issue by aisbergde** [wallabag/wallabag#857]
when importing my links from pocket export into wallabag (hosted on framabag) I get this error:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 76 bytes) in /datas/vol2/w4a141590/var/www/framabag.org/htdocs/core/inc/3rdparty/simple_html_dom.php on line 1523

My pocket export contains > 13.000 links. Most of them are not required (read links without a tag), but I have no idea how to filter them out before importing. Maybe some pre-processing of the file would be reqired. Maybe some kind of pre-processing could also be implemented into wallabag import interface?

**Comment by nicosomb** [comment]
This issue concerns wallabag v1 only. wallabag v1 won't evolve.
