### ISSUE TITLE
Create an "About" section - Get a way to check server configuration again

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#864]
*wallabag_compatibility_test.php* has been moved to install/ and is therefore automatically deleted.
We need a way for users to still have access to this information.

My idea : create an « About » subsection of the « Config Page » and put it this kind of stuff (About, Version Number, Licence, Debug Output, Informations on server, eventually phpinfo(),...).

### Advantages : 
- Clean user interface

### Drawbacks :
- If there's something wrong with the display of the themes, it won't be shown.

**Comment by nicosomb** [comment]
still needed?

**Comment by j0k3r** [comment]
I don't think we need this kind of information.
But I think we need a way to display end user log when an entry fail to be parsed, but this is an other topic :)

**Comment by tcitworld** [comment]
No we won't need it anymore. I second @j0k3r idea, though.

**Comment by nicosomb** [comment]
I close this issue. If you want to open a new issue, you can ;-)
