### ISSUE TITLE
The pagination's variable has no effect

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabag#875]
When I edit the pagination's variable in `inc/poche/config.inc.php`, there is no effect. I'm stuck with 10 articles per pages. I'm in 1.8 but this bug was here before the upgrade.I tried to edit `inc/poche/config.inc.default.php` but no results.

I use sqlite.

**Comment by Aypac** [comment]
Would love to have a front-end setting for this, too :+1:  :)

**Comment by nicosomb** [comment]
Fixed in 2.x.
