### ISSUE TITLE
Migration from MySQL to PostgreSQL with import

### ISSUE THREAD

**Issue by anayrat** [wallabag/wallabag#884]
Hi,
I want to move my database from mysql to postgresql. I use the DOWNLOAD_PICTURES option.

I do an export from wallabag and on the a fresh install (wallabag with postgresql) I do an import.
I can see my articles but the tags are lost and wallabag don't download pictures?

Here are the log : 
2014/10/23_20:50:38 - 5.39.83.159 - storage type postgres
2014/10/23_20:50:38 - 5.39.83.159 - display home view
2014/10/23_20:50:47 - 5.39.83.159 - storage type postgres
2014/10/23_20:50:47 - 5.39.83.159 - config view
2014/10/23_20:51:30 - 5.39.83.159 - storage type postgres
2014/10/23_20:51:30 - 5.39.83.159 - Import stated: parsing file
2014/10/23_20:51:33 - 5.39.83.159 - Import of articles finished: 80 articles added (w/o content if not provided).
2014/10/23_20:51:33 - 5.39.83.159 - Import finished completely
2014/10/23_20:51:33 - 5.39.83.159 - redirect to http://wallabag./?view=config

**Comment by j0k3r** [comment]
This can be done using the v2 export (and the downloaded images aren't implemented yet in the v2).
