### ISSUE TITLE
unable to retrieve full-text content

### ISSUE THREAD

**Issue by lvuser** [wallabag/wallabag#885]
Wallabag says it is unable to retrieve the full text content of the following url http://www.leviathansecurity.com/blog/the-case-of-the-modified-binaries/

Does wallabag have any logging enabled or can be enabled to see why it is failing?

Wallabag version: 1.8.0

![unable to retrieve](https://cloud.githubusercontent.com/assets/4620411/4768016/611f0db8-5b64-11e4-85b3-ac570697e22b.png)

**Comment by steppy** [comment]
I experienced this issue for this URs:

http://sectio-aurea.org/2014/07/dateirechte-warum-eigentlich/

**Comment by nicosomb** [comment]
It works with wallabag v2.
