### ISSUE TITLE
Ability to login in password protected websites 

### ISSUE THREAD

**Issue by etiess** [wallabag/wallabag#886]
I'm using Framabag and may abandon Pocket thanks to your job, thanks!

A feature I'd love to see in Wallabag is the ability to login into a website in order to fetch the content which is protected by a password.

The best example is Mediapart (www.mediapart.fr): I subscribed to this news website, but they don't have any Android app. The best way to read it on mobile would be wallabag. For this, I would need to give my login and password somewhere in order the wallabag server is able to login in mediapart.fr and the fetch the full version of the article.

**Comment by etiess** [comment]
Do we want to close this issue and keep only https://github.com/wallabag/wallabag/issues/438 ?

**Comment by tcitworld** [comment]
Yup, but I have to put what you quoted above in the other one.
