### ISSUE TITLE
1.8.0: Only the RSS for favs works, unread and archive RSS doesn't 

### ISSUE THREAD

**Issue by lightonflux** [wallabag/wallabag#914]
Version 1.8.0

When i open the feeds in firefox only the fav feeds (10 items) gets displayed right. The archive feed (30 items) and the unread feed (278 items) are displayed empty. But when you check the "source file" (ctrl + u) the feed looks right and all the tags are closed at the end. And the file is only 26000 lines long. Downloading it with wget also does not work.

Is this a known problem?

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
