### ISSUE TITLE
crashing because unknown character set 'utf8mb4'

### ISSUE THREAD

**Issue by kevmeyer** [wallabag/wallabag#935]
After updating and removing the `install` folder, the only thing i got is a `500 Internal Server Error`. After running the php from terminal i got the reason:  
This is the output:  

    $ php index.php
    PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000] [1115] Unknown character set: 'utf8mb4'' in /var/www/virtual/******/html/wallabag-dev/inc/poche/Database.class.php:37
    Stack trace:
    #0 /var/www/virtual/******/html/wallabag-dev/inc/poche/Database.class.php(37): PDO->__construct('mysql:host=loca...', '******', '******', Array)
    #1 /var/www/virtual/******/html/wallabag-dev/inc/poche/Poche.class.php(64): Database->__construct()
    #2 /var/www/virtual/******/html/wallabag-dev/inc/poche/Poche.class.php(44): Poche->init()
    #3 /var/www/virtual/******/html/wallabag-dev/index.php(21): Poche->__construct()
    #4 {main}
    thrown in /var/www/virtual/******/html/wallabag-dev/inc/poche/Database.class.php on line 37

On Stackoverflow i found this answer: http://stackoverflow.com/a/21929328/2115477  
It turns out, that this seems plausible as the version running on my system is 5.1:  

    $ mysql -V
    mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

This is running on shared hosting, so i can't change my mysql version. I'm sure i'm not the only one with this error, although i didn't find any similar issue.

**Comment by benjaminoakes** [comment]
DreamHost shared hosting is affected.

**Comment by Kondra007** [comment]
Still no solution?

**Comment by tcitworld** [comment]
Default is now with UTF8MB4 disabled, a checkbox can be checked if people want to force UTF8MB4.
