### ISSUE TITLE
White Screen when mysql user has no privileges.

### ISSUE THREAD

**Issue by flasheater** [wallabag/wallabag#940]
1. Configure a mysql instance with a db and a user.:
    create database wallabag;
    create user 'wallabag'@'localhost' identified by 'testesttest';
    --- omit this
    --- grant all privileges on wallagab.* for 'wallabag'@'localhost';
2. Install wallabag through web interface and hit "install"
3. Screen becomes and stays white.

**Comment by tcitworld** [comment]
Same as #995, I didn't remember this one.
