### ISSUE TITLE
Download pictures: some pictures are not downloaded

### ISSUE THREAD

**Issue by three15** [wallabag/wallabag#949]
Some pictures are not downloaded at all at some pages even from the simple img src tag.
Example url:
http://krebsonsecurity.com/2014/11/link-found-in-staples-michaels-breaches/
Example image url:
http://krebsonsecurity.com/wp-content/uploads/2014/10/staples-285x180.png

The assets directory for this article stays empty, the image url is unchanged.

**Comment by nicosomb** [comment]
1. Yes. 
2. Yes, and with download_pictures activated too (but linked to original picture).

**Comment by tcitworld** [comment]
With download pictures activated if the download fails the original picture is shown ? That's good. 
All we have to do is to make these warnings ignored then.
And maybe also email the webadmin of this server to ask him why does he does such a styling thing.

**Comment by tcitworld** [comment]
*stupid

**Comment by tcitworld** [comment]
Changing the User-Agent doesn't help. Forcing the referer doesn't change anything.
All I can do is removing the warning in the error log. :'(

**Comment by nicosomb** [comment]
It affects only wallabag v1. Won't be fixed, we work only on wallabag v2.
