### ISSUE TITLE
public mode

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#95]
I don't know if it's a good idea :  to allow everyone to read the articles, but without being able to archive and delete it, etc.. 

Do you have any idea?

**Comment by nicosomb** [comment]
How do you think we can implement public view for each article? (@j0k3r)
A URL like wallabag/share/T0K3N with a clean view for the article? 

So when we'll edit the entry to set it as public, we have to generate a token.

**Comment by tcitworld** [comment]
> So when we'll edit the entry to set it as public, we have to generate a token.

If we can do this, why not directly check if the *is_public* property of the entry is true when doing the routing ?

**Comment by nicosomb** [comment]
I don't want to publicize the id of each entry.

**Comment by tcitworld** [comment]
I don't see why it would be a secret.

**Comment by nicosomb** [comment]
Because with the id, you can try to access to other entries. And some entries will be shareable, but not public for everybody (I want to share this article to my father, I don't want everybody can see it)

**Comment by tcitworld** [comment]
I see.

**Comment by j0k3r** [comment]
Maybe we can generate and uuid for them ?

**Comment by j0k3r** [comment]
Will up in the 2.1
