### ISSUE TITLE
unable to add link, when user needs to login first

### ISSUE THREAD

**Issue by kevmeyer** [wallabag/wallabag#961]
When using my Bookmarklet or one of the Apps and try to add an url via the `?action=add&url=` method, it fails if the user isn't logged in already. The action is lost after login (It works on 1.7.9 though).  
In case of an already logged in user, the add-method works as expected.

Test Url:  

    https://example.com/wallabag/?action=add&url=aHR0cDovL3d3dy56ZWl0LmRlL3dpcnRzY2hhZnQvMjAxNC0xMi9lb24ta29obGUtZ2Fz

**Comment by nicosomb** [comment]
Can we close this issue? Seems to be fixed in v2.

**Comment by j0k3r** [comment]
Did you test it? Using the bookmarklet while being logged out?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
