### ISSUE TITLE
Problem with Readability.php when save link

### ISSUE THREAD

**Issue by Narga** [wallabag/wallabag#963]
I have this error message when save a link (Xenforo forum with blockquote as post content) but other website still works.
`FastCGI sent in stderr: "PHP message: PHP Warning:  DOMElement::setAttribute(): ID readability-content already defined in /wallabag/inc/3rdparty/libraries/readability/Readability.php on line 698" while reading response header from upstream`
When I save it via Framabag, it's works well.
Can you give some advide about this problem?
I'm setup Nginx, PHP on Arch as localhost

**Comment by nicosomb** [comment]
@tcitworld @fivefilters we just have to add this line into makefilltextfeed.php, right?

**Comment by tcitworld** [comment]
I think it works, but I have another bug linked to the mobi class we use, which provides it's own Readability file. Working on disabling that.

**Comment by tcitworld** [comment]
Should be good. Please have a go.

**Comment by OlaitanMayowa** [comment]
libxml_use_internal_errors(true);

This works for me too.
