### ISSUE TITLE
Preview picture for each article

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#972]
As @moafred (from Bookeen team) told me yesterday, we can use og:image meta to get a preview picture for each article. 
This tag is used by twitter and facebook to generate preview in posts. 

For example, with this article http://www.lemonde.fr/pixels/article/2014/12/18/affaire-sony-pictures-la-strategie-anti-piratage-d-hollywood-revelee_4542100_4408996.html, we have this meta :

```
<meta property="og:image" content="http://s1.lemde.fr/image/2014/12/17/600x315/4542146_3_8afb_le-legendaire-signe-surplombant-hollywood-en_443f1e6556ca1af14830f9d266203bcf.jpg" />
```

It can be useful for generating nice ePUB files (instead of wallabag logo). 

@tcitworld Are you interested to have a look to this feature?

**Comment by tcitworld** [comment]
I was looking if FTRSS already has something like that, but it doesn't seem so (I only looked the 3.2 version). The picture they produce comes only from pure RSS feeds (`<itunes:image>`, `<atom:logo>`, `<atom:icon>`, `<image><title>` or `<image><dc:title>) via Simple Pie, not regular html pages.
I could build the detection right in the makefulltextfeed.php file, or in wallabag itself. Are you interested, @Fivefilters ?

**Comment by tcitworld** [comment]
Wondering if it's better to extend the Readability class or the ContentExtrator one.

**Comment by tcitworld** [comment]
Thanks a lot for the link !
I'll start the work with the ContentExtractor class.

**Comment by nicosomb** [comment]
for your information, @fivefilters implemented this feature in last version http://blog.fivefilters.org/post/121443274427/full-text-rss-35

**Comment by j0k3r** [comment]
This mean I need to add this feature to graby :)

**Comment by j0k3r** [comment]
Picture is now attached to each entry. We need to display it now.

**Comment by nicosomb** [comment]
what do you think of this?

![](https://lut.im/5FDiZ4PY/Ym3XuecZ)

**Comment by j0k3r** [comment]
Great !
