### ISSUE TITLE
Option to ignore links in a webpage

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#973]
On the article of Le Monde, each verb is associated with a link to it's conjugation. If some users like it, it's rather useless in our case. Here's [an example](http://www.lemonde.fr/pixels/article/2014/12/18/affaire-sony-pictures-la-strategie-anti-piratage-d-hollywood-revelee_4542100_4408996.html).

I'm talking about conjugations here, but I remember some articles from some sites did linked to sponsored content on certain keywords.

I propose an option to ignore links with a specific class (in that case `lien_interne conjug`) and show them as normal text, but with the rest of the links displaying. That (optional, of course) option could be written in the _site_config_ files.

What do you think ? I also ask @fivefilters for idea here.

**Comment by nicosomb** [comment]
Maybe this issue can be moved into Graby project (ping @j0k3r)

**Comment by j0k3r** [comment]
Hum yep but it's also linked to FTRSS since we both rely on siteconfig.
This kind of information must be in siteconfig.

**Comment by j0k3r** [comment]
Looks like they stopped to do that awful thing, can we close that issue?

**Comment by tcitworld** [comment]
At f****** last.

**Comment by tcitworld** [comment]
Nope, still doing it.

**Comment by j0k3r** [comment]
Grrr

**Comment by fivefilters** [comment]
Got a hacky fix for this I think. See https://github.com/fivefilters/ftr-site-config/blob/master/lemonde.fr.txt

Just tries to rewrite the HTML by turning the opening `<a` tags into hidden input fields. After parsing, the closing `</a>` tags get stripped as they no longer match. And the style attribute on the hidden input field we introduced is `style='display:none;'` so it gets stripped itself. 

Not the greatest solution, but hopefully there'll be a better way of handling these in the future.

**Comment by j0k3r** [comment]
Just tested on http://www.lemonde.fr/immigration-et-diversite/article/2016/11/08/la-france-se-prepare-a-expulser-plus-de-migrants_5027326_1654200.html with the hacky fix from @fivefilters and links are removed.
Thanks :+1: 

I'm closing that issue.
