### ISSUE TITLE
Integrate some new icons

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#977]
Ideas when I was browsing Icomoon : 
- icons depending on the content (text page, picture, music, video, pdf, text file)
- tag (*price-tag* icon)
- *lifebuoy* for help
- *clock* for estimated time to read
- *undo2* to undo
- *equalizer* or *cog* for settings
- *pie-chart* for statistics
- *menu*
- *earth* for language
- *sort-alpha-asc* and *sort-alpha-desc* and *filter* to filter and show by order
- *share2* for a share menu
- more awful social networks
- ?

Todo: 

- [x] article view
- [ ] tags
- [ ] unread, fav, archive pages
- [ ] text for shaarli is too big
- [ ] config page
- [ ] disconnect link
- [ ] sort links
- [ ] rss

**Comment by nicosomb** [comment]
@tcitworld If you can take 2/3 minutes to try the branch. All is not over.

**Comment by tcitworld** [comment]
Will do tomorrow. I could do this now but I'm too sleepy to make good things. ;)

**Comment by Simon-L** [comment]
Suggestion:
* Icons depending on websites. I find myself saving a lot of Github repos, Soundcloud or Bandcamp pages etc...
Maybe having a list of known websites and corresponding icons/favicons. Automating it is possible but like text retrieval from a webpage as we see in Wallabag, it does fail sometimes.

**Comment by tcitworld** [comment]
Why not, when we'll classify entries by domain name.

**Comment by nicosomb** [comment]
@tcitworld I close. If necessary, you can reopen it.

**Comment by tcitworld** [comment]
Just if it gives @modos189 ideas...

**Comment by modos189** [comment]
I think on the page list of articles it would be convenient to use these two icons:

clock for estimated time to read
earth for language

On other pages, I think enough icons.
