### ISSUE TITLE
Can not add a GitHub Gist

### ISSUE THREAD

**Issue by frankgerhardt** [wallabag/wallabag#979]
I can't add https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

Not with the Firefox addon and also not in the Wallabag UI, on Config / Saving Articles / Bag it!

It shows up as

Untitled
estimated reading time : < 1 min
[unable to retrieve full-text content]...

I can open the article and using the link icon I can navigate to it. 
The article should have been saved in Wallabag though.

**Comment by tcitworld** [comment]
Thanks to @vpmalley, this is fixed.
