### ISSUE TITLE
Search by same domain name

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#981]

**Comment by j0k3r** [comment]
Could you add more information about that point?

I mean, for you this domain name `www.example.com` is the same as `blog.example.com` ?

Do we need to store the *domain name* (ie: `example.com`) or the *host name* (ie: `www.example.com`, `blog.example.com`) ?

**Comment by tcitworld** [comment]
We need to discuss about this point, you're right. @nicosomb had introduced a field in database for domain name, but I said we wouldn't need it, we could extract the information from URL when it's needed.

I had thought to go with domain name and not hostname (blog.example.com is the same as www.example.com), but if we go with this issue, we've got to cover cases like .co.uk and so on.
So hostname is good.

**Comment by j0k3r** [comment]
I agree about hostname too.

I think it'll be more efficient if we have the `hostname` field in the database when we want to search for a specific hostname. Instead of performing an ugly `WHERE url LIKE '%example.com%'` :)

BTW this mean we'll be able to display something like how many entries by domain name.

**Comment by nicosomb** [comment]
Please do what you think is the best. Sorry, but I don't have the solution ...

**Comment by nicosomb** [comment]
2 options: 
* we store domain name with subdomain **but** we can filter only on hostname
* we only store hostname and we can only filter on hostname

I think the 1st method could be great, if in next months, we need to have the subdomain+hostname. 

What is your opinion?

**Comment by nicosomb** [comment]
hmmm.. but with 1st solution, filter on hostname can be more complicated to implement (for the sql query)...

**Comment by nicosomb** [comment]
PR is opened https://github.com/wallabag/wallabag/pull/1342

**Comment by nicosomb** [comment]
And PR is merged :)
