### ISSUE TITLE
logic bug in autoclose code?

### ISSUE THREAD

**Issue by paulgazz** [wallabag/wallabag#984]
I'm running 1.8.1 and using Safari, but see the possible bug in the latest github version too.  When investigating how to disable autoclose, I came across this code in `inc/poche/Poche.class.php`:

    143: public function action($action, Url $url, $id = 0, $import = FALSE, $autoclose = FALSE, $tags = null)
         ...
    190: if ($autoclose == TRUE) {
           Tools::redirect('?view=home');
         } else {
           Tools::redirect('?view=home&closewin=true');
         }

It seems like the test on line 190 should be `$autoclose == FALSE`, i.e., when `$autoclose` is `TRUE`, then the `closewin=true` link should be used.  Since the default to `autoclose` on 143 is `FALSE`, shouldn't window closing not happen?  I'm not asking to change code behavior or anything, just wanted to let the developers know.  Perhaps a config.inc.php setting would be useful.

Just started using wallabag, and I love it! Thanks for the the code!

**Comment by tcitworld** [comment]
@nicosomb Is it me or does the autoclose feature has never been used ?
I can't find any reference to a call the the $autoclose parameter from action() function. I guess it has disappeared when you cleaned classes and introduced the routing.inc.php file.

Working on it.

**Comment by tcitworld** [comment]
Fixed.
