### ISSUE TITLE
Untitled articles

### ISSUE THREAD

**Issue by dtrolle** [wallabag/wallabag#989]
I have a lot of Untitled document. (Yunohost installation)

Here are some of them:

http://videos.cctvcamerapros.com/digital-io-alarm-in-out/send-push-notifications-from-raspberry-pi.html

http://floatlearning.com/2014/04/buying-mobile-learning-is-a-lot-like-buying-a-suit/

android-france.fr/2014/07/02/developpez-polymer-tuto-2/

http://android-france.fr/2014/04/28/andy-os-emulateur-android-pc-mac/

http://www.toolinux.com/Wi-Fi-Linksys-WRT-la-legende-de

http://libre-ouvert.toile-libre.org/index.php?article187/pitivi-a-besoin-de-vous

http://www.lairdofblackwood.com/cart/

http://www.dadall.info/blog/index.php?article316/passman-l-application-oc-7-qui-sauvegarde-vos-mots-de-passe

http://homeserver-diy.net/?p=1842

**Comment by tcitworld** [comment]
Seems to be a big problem, since they worked in version 1.7.0.

**Comment by j0k3r** [comment]
All links looks good on the upcoming 2.0.1
