### ISSUE TITLE
An error occured: "db" directory must be writeable for your web server user!

### ISSUE THREAD

**Issue by ambaloo** [wallabag/wallabag#990]
I cannot access to Wallabag after installation got this error "An error occured: "db" directory must be writeable for your web server user!"

The owner is apache, and I set up the right to write to all user and still not work ?

My config is 
Server : CentOS
DB : PostgreSQL

Thanks a lot for your help

**Comment by ambaloo** [comment]
Hello,

Here are some details about my issue : 
After installing wallabag, i delete the install/ folder.

After that i wasn't able to acces the application, the error : "An error occured: "db" directory must be writeable for your web server user!"

I check the permission on that folder and and the web server user have the right to read the folder.

Please what could be the probleme.

Thank you

**Comment by tcitworld** [comment]
I think the error comes from the installer : it thinks your have selected SQLite as the database system. If the install has worked, you should be able to get access to wallabag by deleting the install/ directory. Otherwise we'll have to investigate further.

**Comment by tcitworld** [comment]
I think the error comes from the installer : it thinks your have selected SQLite as the database system. If the install has worked, you should be able to get access to wallabag by deleting the install/ directory. Otherwise we'll have to investigate further.

**Comment by ambaloo** [comment]
I had the same issue with PostgreSQL installed. Is there any action I can do, or a workaround to solve this issue.

**Comment by tcitworld** [comment]
As I said, can you test if deleting the install/ directory solves anything ?

**Comment by ambaloo** [comment]
Nope, like I said above the install/ directory was deleted just after the installation, and still have the same issue.
Thanks for the support

**Comment by tcitworld** [comment]
Oops, sorry, missed that. Working on it. Does the db/ directory contains a poche.sqlite file ?

**Comment by ambaloo** [comment]
The db/ directory is empty.

**Comment by tcitworld** [comment]
Thanks for the help.

**Comment by ambaloo** [comment]
No, thank you !

**Comment by tcitworld** [comment]
OK, I could reproduce the same error (with MySQL), but I've got good reasons to think it's the same bug with Postgres (will confirm in a few minutes).
It's when the connexion is refused by the server (wrong credentials), an exception is not thrown like it should be. Fatal error, same message.
I worked when I deleted the directory and made a clean install with the right credentials.

Let's hope it's only this. :)

**Comment by tcitworld** [comment]
It's the same for me with PostgreSQL

**Comment by ambaloo** [comment]
Do I have to reinstall ? When you say wrong credentials, are you talking about the database user ?

**Comment by tcitworld** [comment]
Yes you have to reinstall. And yes I'm talking about the database user.

**Comment by ambaloo** [comment]
Still have the same issue when I re-install wallabag.

**Comment by tcitworld** [comment]
And you're sure about your credentials ? Sure tout fulfill all the fields (already written values, like localhost are exemples ans are not taken into account).

Can you check your PHP logs while you're installing, too ?

**Comment by tcitworld** [comment]
Hmm, sorry for bad writing, French autocorrect on.

**Comment by ambaloo** [comment]
No problem, so yes I fulfill all the fields.
below my php logs :

[Sat Jan 10 21:06:12.524277 2015] [:error] [pid 13360] [client 105.101.0.239:56789] PHP Fatal error:  Class 'PDO' not found in /var/www/html/wallabag/install/index.php on line 110, referer: http://[my.ip.address]/wallabag/
[Sat Jan 10 21:11:34.571463 2015] [:error] [pid 13361] [client 105.101.0.239:56860] PHP Fatal error:  Class 'PDO' not found in /var/www/html/wallabag/install/index.php on line 110, referer: http://[my.ip.address]/wallabag/

**Comment by tcitworld** [comment]
Reinstall. Then checkout the link that says « Check your server compatibility ». Seems PDO is not installed.

I should have started by asking you this. Anyway, this makes me urge to rethink all the install process.

**Comment by ambaloo** [comment]
Sorry I forgot to say that the "wallabag_compatibility_test.php" is ok every thing is green :+1:.
And I just check, php pdo is installed

**Comment by tcitworld** [comment]
Hmm, so your installation is having a problem with PDO. Can you provide a phpinfo() ?

Also, there's multiple answers if you search online for « Class 'PDO' not found CentOS ». I suggest you try out some.

**Comment by ambaloo** [comment]
Where can I provide you the phpinfo() ?

**Comment by tcitworld** [comment]
Any pastebin service you want, like https://gist.github.com/

**Comment by ambaloo** [comment]
https://gist.github.com/ambaloo/30f428fd416d48e2f9ee

**Comment by tcitworld** [comment]
Seems there's absolutely no reference to PDO. I guess it's been installed but not activated.
Look at the `/etc/php.ini` file. If there's any reference to the PDO extension (like `;extension=pdo.so`), activate it by uncommenting (by removing the `;`).
If there's a reference to a file named something like pdo.ini , activate it too. And maybe look out in that other file if `extension=pdo.so` is activated too.

After all that, restart/reload apache and check if a reference to PDO has appeared in the phpinfo.

**Comment by ambaloo** [comment]
GREAT ! it's working, PDO was not enabled in the php.ini file and not even parsed in additional .ini files (/etc/php.d)

Thanks a lot

**Comment by tcitworld** [comment]
Good for you.
I'll note somewhere to note to check PDO in the documentation.

**Comment by ambaloo** [comment]
Thanks for the support again, yes it would be a good idea if there is a PDO check in the wallabag_compatibility_test.php

**Comment by tcitworld** [comment]
Actually, I really though there was a test. It should even be in the first things to test. This will be corrected soon.
