### ISSUE TITLE
Allow tagging when saving to wallabag

### ISSUE THREAD

**Issue by Simon-L** [wallabag/wallabag#991]
In my usecase I find I could take a few extra seconds to type in some tags related to the page I'm saving right when I'm saving it.
This would make easier to browse the archives and the articles that I have still to read.
I had this idea thinking I would be saving a lot of things on various topics.

I'm thinking it could be an option to enable in the settings and then display the tagging available in the window that opens when saving?
Maybe the browser extensions and mobile apps could provide this too.

Related to: #719

**Comment by tcitworld** [comment]
Well, this could be done in the actual app, but it would be better to push for v2.0 with API which can handle all this...
Will try something for 1.9.0, though.

**Comment by nicosomb** [comment]
Done in #999 :)
