### ISSUE TITLE
Register with Packagist?

### ISSUE THREAD

**Issue by Crell** [wallabag/wallabag#993]
As a Composer-using program, Wallabag can (and I believe should) be registered on Packagist.  It's quite simple to do, and requires only some additions to the composer.json file and filing out a form on Packagist.org.

That would then allow it to be downloaded and installed purely through Composer, by anyone with Composer.  That's the preferred way that, for instance, Symfony is installed:

http://symfony.com/download

Offering a packaged zip file with everything is still fine, but it would allow for a one-line-installer familiar to anyone with even basic PHP knowledge.  Since Composer is required for installation right now anyway, that means pretty much everyone.

**Comment by Crell** [comment]
Huzzah!

**Comment by nicosomb** [comment]
https://packagist.org/packages/wallabag/wallabag

**Comment by nicosomb** [comment]
Still trying to configure my composer.json file :-)

**Comment by Crell** [comment]
@nicosomb I'm in #composer on freenode if you want assistance. :smile:
