### ISSUE TITLE
Highlight text

### ISSUE THREAD

**Issue by fl0rent** [wallabag/wallabag#994]
I used wallabag, in a specific manner.
I read a lot of articles. _A LOT_.
I would like to keep track of them and the best would be if **I could highlight important phrases**.
For example, instapaper offers a highlighting solution. 

Is it possible to do the same in wallabag?

_+ We could do better by blurring the text wich is not highlight, if necessary_

**Comment by tcitworld** [comment]
It's possible, yes.

**Comment by SqlBarbarian** [comment]
I'd mention that the inline highlighting of webpages that Diigo does is excellent, and saves to the "repository" for future reference. I'd suggest that this one area is something that would take wallabag to a whole new level of functionality for those in IT looking to aggregate specific knowledge highlights on topics. Love Framabag so far, but the one feature I've been looking for is the Diigo inline article highlighting that doesn't require saving an entire article first. Great work devs on this app. I love what I see so far!

**Comment by j0k3r** [comment]
Any direct link to see how this Diigo / Instapaper feature works ?

**Comment by nicosomb** [comment]
Thanks to #1653 (and @tcitworld), you can now highlight text. @tcitworld: can you confirm?

**Comment by tcitworld** [comment]
Yup, you don't need to put any comment.

**Comment by fl0rent** [comment]
@j0k3r : http://blog.instapaper.com/post/85125160146

**Comment by tcitworld** [comment]
@fl0rent The thing that we implement kinda look like that.
