### ISSUE TITLE
[Installation] Throw an exception if PDO isn't found at installation.

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#996]
In response to #990, if PDO is installed with but not properly configured (PDO class not found).

Or not at all installed ?

An entry in wallabag_compatibility_test should be enough.

**Comment by ambaloo** [comment]
PDO is installed and it's enabled. What do you mean by "not properly configured" ?

**Comment by tcitworld** [comment]
Not correctly found and used by PHP, obviously. That's why a phpinfo() would come handy. Can we stay on the other issue, please ? :)

**Comment by ambaloo** [comment]
Of course

**Comment by tcitworld** [comment]
Now finished, see @ #1026.
