### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by bitsandnumbers** [wallabag/wallabag#997]
I have a scenario where it is possible to retrieve a db content without knowing the credentials, just with the sqlite DB file:

If you install a new instance of Wallabag and log to it, you can then just replace the newly created db file with the one which you don't know the credentials. Reload the page and the content of the database shows up. Go into settings, set a new password and you're there: the database is hacked and you just set your own password for it if you want to log back in again.

It was helpful to retrieve a DB from which I lost the password, but I think it's kind of a huge security issue. Just to let you know :-)

**Comment by tcitworld** [comment]
Thanks a lot.
OK, so for starters, we can ask for current password when we change it in the settings.

A viable solution to recover password should be implemented ASAP also.

**Comment by bitsandnumbers** [comment]
Yeah, the two solutions you propose are mandatory.

To recover the password, the good old mail sent to an address you setup in the settings ? Using php to send is enough imho. It could redirect you to a page where you can change the password (as sending the old one is not a good idea if people use the same password for different accounts). What do you think ? I'm sure you already thought of such a solution.

I also propose some kind of verification of the database to check whether it's still the one you logged in with. Maybe some kind of hash, I don't know, I'm not an expert on this matter. 

I noticed that the token is stored as plain text in the database, which lead to a second security issue: a simple scenario is to read a sqlite database, look for the token, open up a Wallabag client (i.e: iOS or Android) and write down an ID and the token. Maybe the clients should ask for the password too ? Or go the encryption route: https://www.sqlite.org/see/doc/trunk/www/readme.wiki ?

**Comment by bitsandnumbers** [comment]
Yeah, the two solutions you propose are mandatory.

To recover the password, the good old mail sent to an address you setup in the settings ? Using php to send is enough imho. It could redirect you to a page where you can change the password (as sending the old one is not a good idea if people use the same password for different accounts). What do you think ? I'm sure you already thought of such a solution.

I also propose some kind of verification of the database to check whether it's still the one you logged in with. Maybe some kind of hash, I don't know, I'm not an expert on this matter. 

I noticed that the token is stored as plain text in the database, which lead to a second security issue: a simple scenario is to read a sqlite database, look for the token, open up a Wallabag client (i.e: iOS or Android) and write down an ID and the token. Maybe the clients should ask for the password too ? Or go the encryption route: https://www.sqlite.org/see/doc/trunk/www/readme.wiki ?

**Comment by nicosomb** [comment]
> I noticed that the token is stored as plain text in the database

The token is store into inc/poche/config.inc.php. 

> we can ask for current password when we change it in the settings.

@tcitworld is right, it's a first thing to do. 

> you can then just replace the newly created db file with the one which you don't know the credentials. 

You don't know the credentials, but you can open the sqlite file and read the content. No need to have the password. 

If someone has your sqlite file, the security problem is on the web server, I think. 

Maybe I don't understand the real problem ..

**Comment by tcitworld** [comment]
Yeah, the main problem is that the admin has access to everything anyway.

We should say : if all data was encrypted (i.e : the admin can't know about the content*), this would be a problem.

* even though he knows the hash and can therefore bruteforce more easily.

**Comment by nicosomb** [comment]
>  the main problem is that the admin has access to everything anyway.

sys admin or wallabag admin?

**Comment by tcitworld** [comment]
sys admin, of course

**Comment by tcitworld** [comment]
But wallabag admin shouldn't have access to content also
